### ISSUE TITLE
applyTheme includes undesired styles to components

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow#10038]
There seems to be a regression regarding how `applyTheme` works between versions `19.0.0.alpha4` and `19.0.0.beta1`. While applying custom theme to a view, each Vaadin Web Component in that view also gets applied styles that affect the appearance of the component.

Example: see the difference in spacing of radio buttons inside a group:
- [Before the regression](https://deploy-preview-167--vaadin-docs-preview.netlify.app/ds/components/radio-button/)
- [After the regression](https://deploy-preview-178--vaadin-docs-preview.netlify.app/ds/components/radio-button/)

**Comment by pleku** [comment]
It seems like the changes are because the `<span part="label">` for a radio-button is inheriting css from
```html
<div class="render CodeExample-module--render--1x58S" data-has-example="true" style="min-height: 64px;"></div>
```
which has line height that is applied
```css
constructed stylesheet
:host {
...
    line-height: var(--lumo-line-height-m);
...
}
```
But why

**Comment by tomivirkki** [comment]
This is also noticeable on https://start.vaadin.com/ Every component inherits those styles from a constructed stylesheet

**Comment by Haprog** [comment]
I guess this is caused by https://github.com/vaadin/flow/commit/ecfb800747a0d54ed4ce72a5423105aa23ef5368

**Comment by tomivirkki** [comment]
This is quite an urgent issue imo. As time passes and people get used to these styles getting included in the Components, someone may consider fixing this a breaking change.

**Comment by Artur-** [comment]
What exactly is the problem? I don't understand it based on the text here. Which styles are applied where?

**Comment by tomivirkki** [comment]
If you open the "after the regression" link, the `<vaadin-radio-button>` -elements are too far apart due to the styles included via constructed stylesheet:

![Screenshot 2021-04-07 at 11 03 45](https://user-images.githubusercontent.com/1222264/113832243-16975280-9791-11eb-9305-dbdc0c4a730c.png)

**Comment by Artur-** [comment]
and where are the styles from?

**Comment by tomivirkki** [comment]
That's for the fixer to find out. As mentioned, it's not just an issue in the docs, if you inspect the components in https://start.vaadin.com/ you can see they have the same constructed stylesheet applied

**Comment by Artur-** [comment]
Which components do you mean?

e.g. `line-height: var(--lumo-line-height-m);` is at least defined in https://github.com/vaadin/vaadin-lumo-styles/blob/master/typography.html#L46 so that it should be applied to both `html` and all shadow roots

**Comment by tomivirkki** [comment]
> Which components do you mean?

<img width="1003" alt="Screenshot 2021-04-07 at 12 05 05" src="https://user-images.githubusercontent.com/1222264/113840623-89a4c700-9799-11eb-8991-d815275426ae.png">

**Comment by Artur-** [comment]
So you have a `<radio-button-basic-imported-86907302>` in the "after" example. For that element (its shadow root) the theme is applied. The theme is based on Lumo, which contains `line-height: var(--lumo-line-height-m);`. Why should this `line-height` not apply to the `vaadin-radio-button` instances inside `<radio-button-basic-imported-86907302>` as you are not overriding it?

**Comment by tomivirkki** [comment]
Took another look and you're right. Seems like the change in fact _fixed_ the appearance of the example. The "before" example was missing the Lumo typography styles.
