### ISSUE TITLE
TemplateRenderer - events other than on-click don't seem to work

### ISSUE THREAD

**Issue by DSW-PS** [vaadin/flow#10035]
### Description of the bug / feature
I'd like to use TemplateRenderer in a Grid with event-handler for mousedown, however it looks like only "on-click" is working.
Using onmousedown or onmousemove has the browser show the message "ReferenceError: <name-of-handler> is not defined"

### Minimal reproducible example
Create any Grid with columns using TemplateRenderer, let the template use an element (span, div, etc.) with a onmousedown event, wire it up using withEventHandler. Fire it up and press the mouse-button on the element.

`    
    Grid<Person> gr = new Grid<>();

    List<Person> items = new ArrayList<>();
    items.add(new Person("Name 1", "FirstName 1"));
    items.add(new Person("Name 2", "FirstName 2"));

    // create a span with onmousedown which should use our handler
    gr.addColumn(TemplateRenderer.<Person> of("<span onmousedown='handleMouseDown'>[[item.name]]</span>")
        .withProperty("name", Person::getName)
        // our handler
        .withEventHandler("handleMouseDown", p -> {
          // do whatever
          System.out.println(p.getName());
        })).setHeader("Name");

    gr.addColumn(TemplateRenderer.<Person> of("<span onmousedown='handleMouseDown2'>[[item.firstName]]</span>")
        .withProperty("firstName", Person::getFirstName)
        .withEventHandler("handleMouseDown2", p -> {
          // do whatever
          System.out.println(p.getFirstName());
        })).setHeader("First name");

    gr.setItems(items);

    add(gr);`

**Note:** 
I did try "on-mousedown" and "on-mouse-down" but nothing doing.
Also tried running in production-mode, also nothing.

### Expected behavior
I'd expect that the handler is executed and the cell-value to be printed to console.

### Actual behavior
Browser shows message "ReferenceError: handleMouseDown is not defined"

Chrome-Log:
[localhost-1613387408616.log](https://github.com/vaadin/flow/files/5981172/localhost-1613387408616.log)

### Versions:
    - Vaadin / Flow version: 14.4.6 (also in 18.0.5)
    - Java version: 8
    - OS version: Linux 
    - Browser version: any (tried with current Chrome and Firefox)

**Comment by jcgueriaud1** [comment]
Hi,

I've tried 'on-mousedown' and it's working, onmousedown is not working and gives me an error.
```
        grid.addColumn(TemplateRenderer.<Person> of("<span on-mousedown='handleMouseDown'>[[item.name]]</span>")
            .withProperty("name", Person::getName)
            // our handler
            .withEventHandler("handleMouseDown", p -> {
                // do whatever
                System.out.println(p.getName());
            })).setHeader("Name");
```

I tried with Vaadin 14.4.6, Java  8/14. Can you re-check if it's working with on-mousedown?

**Comment by DSW-PS** [comment]
Alright, might have been an issue on my side but yes, "on-mousedown" is working.
Thanks for double-checking, I'll close this issue.
