### ISSUE TITLE
vaadin.devDependencies versions are not updated unless the installed versions match

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#10032]
### Description of the bug / feature

If you have manually upgraded webpack to the latest version in a project and upgrade to Vaadin 19 beta2, the package.json will contain
```
{
  "devDependencies": {
    "webpack": "4.46.0",
  },
  "vaadin": {
    "devDependencies": {
      "webpack": "4.42.0",
    },
}
```

This makes little sense as Vaadin uses webpack 4.46.0 in this version. If Vaadin later on upgrade to e.g. webpack 5, I probably want that updated in my project also.

### Expected behavior
The `vaadin` section of `package.json` contains what the current Vaadin version would install.

### Actual behavior
The `vaadin` section of `package.json` contains versions which were installed by Vaadin earlier at some point.

### Versions:
    - Vaadin / Flow version: 19 beta2

**Comment by pleku** [comment]
> The vaadin section of package.json contains what the current Vaadin version would install.

So if one has manually updated a dependency for something that Vaadin uses, you expect that Vaadin will override your version as a side effect from updating the Vaadin version ? One could probably argue either way, but I don't really understand why it is not updated either in this case when the version should be the same.

**Comment by caalador** [comment]
It's by design that we don't touch anything that the user has manually set.

**Comment by caalador** [comment]
The problem is that even though we actually update the Vaadin dependency version to 4.46.0, but we don't write the file as we had no real dependency changes.
