### ISSUE TITLE
Upgrade to Lit 2

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#10040]
### Description of the feature

To be able to implement rendering directives for Grid and other components in a good way, we need the features from Lit 2. 

Lit 2 allows us to enable inline renderers, like

https://github.com/web-padawan/lit-vaadin-helpers/blob/280c21e37c4f2f1dfe0e1565b379ba29c28f808b/test/grid.test.ts#L73-L80

or

https://github.com/web-padawan/lit-vaadin-helpers/blob/280c21e37c4f2f1dfe0e1565b379ba29c28f808b/test/grid.test.ts#L49

instead of having to manually bind a function to the element instance and then refer to the function in the template.

To be able to include the renderers in the platform, we need to move everything from Lit 1 to Lit 2. To avoid doing this as a last minute, rushed change before the next LTS, we should aim to get it done for Vaadin 21.

### Backwards incompatibilities in Lit 2

As Lit 2 is a new major version, it is not 100% compatible. The biggest breaking changes are for people who create their own directives but there is one noteworthy change for template users:
-`@internalProperty` is now named `@state`

**Comment by pleku** [comment]
When is "lit" 2.0.0 coming out ? Cannot find the release notes for the `2.0.0-pre1` version ? What is "pre" anyway, is it before alpha or something else ?

I imagine we're not going to take it into use (and merge #10023) unless there is a final release available before mid April (or at least a release candidate).

**Comment by Artur-** [comment]
Lit 2.0.pre1 is the first release that is API stable. There has been other pre releases before that.

The assumption for the real release is end of Q1. If we wait for the final to be out before moving on this, it will be impossible to include it in V20 and we will have little time iterating on any problems we find.

We might want to include it only in a feature branch at this point to avoid the situation where it blocks the release of everything else. Would that make more sense?

**Comment by Artur-** [comment]
Lit 2.0-pre2 is backwards compatible with everything except `internalProperty` and custom directives

**Comment by haijian-vaadin** [comment]
For the Fusion team, the task would be to update the [field directive](https://github.com/vaadin/flow/blob/master/flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts#L119) in Binder.

**Comment by Haprog** [comment]
Lit `2.0.0-rc.1` was released yesterday. https://www.npmjs.com/package/lit

**Comment by Haprog** [comment]
The `field` directive should probably be updated to work as an element expression as demonstrated here in the Lit launch event https://youtu.be/f1j7b696L-E?t=1561 (26:01 - 27:22). Justin showed an example how the usage syntax can be simplified from:
```html
<vaadin-text-field
  ...="${field(model.fullName)}"
></vaadin-text-field>
```
to just:
```html
<vaadin-text-field
  ${field(model.fullName)}
></vaadin-text-field>
```

Not sure if we should also try to keep backwards compatibility with the older more complex syntax.

**Comment by Artur-** [comment]
The PR supports both `...="${field}` and `${field}`. If we can deprecate `...` we should keep it for one major I think

**Comment by Legioth** [comment]
It's technically the same function so directly deprecating might be tricky. It might still make sense to detect at runtime how it's used and log a warning if used in the old way. The main problem is that there's probably no way of detecting that while `render()` is running so that we could give some context to where the deprecated use site is.

**Comment by denis-anisimov** [comment]
Once Lit support is upgraded here the things needs to be done:
- Go through documentation and update examples. In most cases the only one thing is required: change `import` declaration in the templates. ( like `import {LitElement, html} from 'lit';` instead `import {LitElement, html} from 'lit-element';`) See https://lit.dev/docs/releases/upgrade/#update-packages-and-import-paths
- Update starter projects :they contain at least `package.json` file which has previous lit version.
- Designer doesn't support lit 2: designer code needs changes.

**Comment by Haprog** [comment]
Also because of:
> The type of the `css` function has been changed to `CSSResultGroup` and is now the same as `LitElement.styles`. This avoids the need to cast the `styles` property to `any` when a subclass sets `styles` to an Array and its super class set a single value (or visa versa).

https://lit.dev/docs/releases/upgrade/#litelement

all starters etc. will also need to update the contents of [types.d.ts](https://github.com/vaadin/flow/blob/master/flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts) in the project (like [this](https://github.com/vaadin/flow/pull/10023/commits/e63053f21c31fe5e921622a9dae1f4a36f257a38)).

**Comment by Haprog** [comment]
Related issues in Vaadin Start:
- https://github.com/vaadin/start/issues/1181
- https://github.com/vaadin/start/issues/1182
