### ISSUE TITLE
Unable to save a new entity through an endpoint in Vaadin 19

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#10051]
### Description of the bug / feature
It is not possible to store new entities through an endpoint in V19.

### Minimal reproducible example
1. https://start.vaadin.com/?preset=fusion-prerelease
2. Select "master-detail-view"
3. Download
4. Run `mvn`
5. Enter values in all fields
6. Press `save`. 

### Expected behavior
The entity is stored in the backend, which generates an id for it

### Actual behavior
Console.logs
```
Uncaught (in promise) ValidationError: There are validation errors in the form.
 - id - IsNumber: must be a number
    at Binder.submitTo (webpack-internal:///../target/flow-frontend/form/Binder.ts:134:19)
    at async HTMLElement.save (webpack-internal:///./views/helloworld/hello-world-view.ts:152:13)
```

### Versions:
    - Vaadin / Flow version:19 beta 1

**Comment by knoobie** [comment]
Looks kinda similar to https://github.com/vaadin/flow/issues/10008, or?

**Comment by Artur-** [comment]
Thanks, works with Flow 6.0-SNAPSHOT
