### ISSUE TITLE
Make it easy to import styles from CSS files in node_modules

### ISSUE THREAD

**Issue by Haprog** [vaadin/flow#10105]
There should be an easy way to import styles from 3rd party dependencies (via `node_modules`) either as a `CssResult` or directly inject to the document (depending on what the developer wants).

Related to the feature implemented for #9970. Depending on how we decide to support/implement this, it might require changes (possibly breaking changes) to that global CSS loader feature.

One option would be to change the CSS loader configuration to not rely on filename suffixes but instead use `requestQuery` string (e.g. `?shadow` / `?global`) but there are probably other ways to solve this too. Needs some design/decision on how we want to do this.

One use case would be to import e.g. Bootstrap grid styles, Prism.js styles or any kind of utility classes into the document or into a shadow root of a component (depending on where the developer wants to use the styles).

**Comment by haijian-vaadin** [comment]
one downside of using query string is that it's only supported in Webpack, might be difficult to migrate to e.g. Snowpack.

**Comment by Haprog** [comment]
After spending some time to think about all the possible ways to load styles currently in V19 and master (V20) I think it was a mistake to change the CSS loaders as was done as a new feature "global CSS loader" to close #9970. We could have avoided the issues if we had realized to think about the use case of importing styles from npm packages (either into document or shadow root) before implementing that.

Due to the change it's currently not possible to import arbitrary CSS files from npm packages into a TypeScript variable (as a `CSSResult`) in a non-deprecated way as you can't control the filenames in 3rd party npm packages.

The new theming mechanism in V19 (which is well documented) allows to easily import CSS into the document both from local CSS files (adding an `@import` in `styles.css`) and from npm packages (adding a reference to `theme.json`).

And since up to V19 all `*.css` imports in TypeScript resulted in a `CSSResult` it was also easy to import any CSS file (either local or from npm package) to be used for shadow DOM (or any other purpose).

A `CSSResult` can also be explicitly added to the document pretty easily in 2-4 lines of code (depending on if you have a helper method for it or not). This is useful if you want to optimize page load performance by lazy loading CSS along with the view.

I would suggest we revert #10036 from master and improve documentation for loading styles in Fusion apps. Then we can also close https://github.com/vaadin/docs/issues/193 as not needed. We should recommend using the [custom theme](https://vaadin.com/docs-beta/latest/ds/customization/custom-theme/) feature for loading styles into the document. Loading styles into shadow root would work like before (in V19 and earlier). Start Vaadin should be updated to import view specific CSS files in the `styles.css` (of custom theme) instead of this syntax in TS `import '!style-loader!css-loader!./about-view.css';`. The view specific CSS files can still stay next to the view TS file.
