### ISSUE TITLE
Flakey test DevModeHandlerTest.start_twoInstances_secondInstanceUsesAnotherPort 

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#10101]
Spot the flaky test in [this build](https://bender.vaadin.com/viewLog.html?buildId=214755&tab=buildResultsDiv&buildTypeId=Flow_Flow70_Flow60Snapshot)

**Comment by denis-anisimov** [comment]
The test is disabled for now: #10299.
It's also disabled in `6.0` .
