### ISSUE TITLE
Cannot do production build with Java 16

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#10115]
To reproduce:
1. Install a Java 16 prerelease. I'm using `zulu@1.16.0-0` through `jabba` which gives `OpenJDK 64-Bit Server VM Zulu16+47-CA (build 16-ea+22, mixed mode, sharing)` from `java --version`
2. Download a project using the default settings from start.vaadin.com (choices such as Vaadin version or Flow vs Fusion doesn't seem to matter)
3. Unzip
4. Run `mvn -Pproduction package`

Expected outcome is that a production build is created. The actual outcome is this error message:
```
[INFO] --- vaadin-maven-plugin:18.0.6:build-frontend (default) @ myapp ---
[INFO] Scanning classes to find frontend configurations and dependencies...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.871 s
[INFO] Finished at: 2021-02-23T17:10:38+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:18.0.6:build-frontend (default) on project myapp: Execution default of goal com.vaadin:vaadin-maven-plugin:18.0.6:build-frontend failed: Unsupported class file major version 60 -> [Help 1]
```

Doing just `mvn` to run the application in development mode seems to work as expeted.

**Comment by Artur-** [comment]
Can reproduce with 19.0.0 and JDK 16 GA
