### ISSUE TITLE
Duplicated methods in Custom Theme bundle

### ISSUE THREAD

**Issue by tanbt** [vaadin/flow#10114]
When a custom theme has a parent, the generated JS files `[custom-theme].generated.js` and `[parent-theme].generated.js` have duplicated methods, e.g. `injectGlobalCss` which end up in the bundle.

Looks like the plugin is changed on master but there is still `injectGlobalCssMethod` helper inlined
https://github.com/vaadin/flow/blob/d505af8253f9245deb902ef032ca5b39802b1d62/flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js#L37-L44

It would be nice to import them from some common theme utils package.

### Versions:
    - Vaadin / Flow version: 6.0.0.rc1

**Comment by Artur-** [comment]
This has been fixed in 24.1
