### ISSUE TITLE
RouterLink: Unable to navigate to route with special characters

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/flow#10129]
### Description of the bug / feature
If the app contains routes that contain Germanic umlauts (e.g. ÄÅÖ), `RouterLink `is unable to navigate to those routes
### Minimal reproducible example
Assuming this view,
```
@Route("åöä")
public class SpecialCharacterView extends VerticalLayout {

    public SpecialCharacterView() {
        add(new Span("some content"));
    }

}
```
And
```
@Route("")
public class MainView extends VerticalLayout {
    public MainView() {
        add(new RouterLink("go to åöä", SpecialCharacterView.class));
    }
}
```
Navigate to MainView and click on the `RouterLink`

### Expected behavior
The app should navigate to the _åöä_ url
### Actual behavior
The user receives an error message:
```
Could not navigate to '%C3%A5%C3%B6%C3%A4'
Reason: Couldn't find route for '%C3%A5%C3%B6%C3%A4'
```
### Versions:
    - Vaadin / Flow version: 14.4.8
    - Java version: 11
    - OS version: Windows

**Comment by tarekoraby** [comment]
Note, the issue doesn't occur if

1. The user enters the url directly in the browser
2. using an Anchor: ` add(new Anchor("åöä", "go to åöä"));`
3. using UI.navigate(): `add(new Button("go to åöä", e -> UI.getCurrent().navigate(SpecialCharacterView.class)));`

**Comment by javier-godoy** [comment]
See also https://github.com/vaadin/flow/issues/7454 (Unable to navigate to a route containing a space)
