### ISSUE TITLE
ShortcutRegistration listenOn with Dialog

### ISSUE THREAD

**Issue by Springrbua** [vaadin/flow#10121]
### Description of the bug / feature
The `ShortcutRegistration` allows you to specify the components to listen on. This way the shortcut triggers only if the focus is inside one of the specified components.
However, this system does not work with the `Dialog`, as on the client it is only some kind of template and you would need to listen on the `vaadin-dialog-overlay` instead. The problem is, that the overlay does not exist on the server so I am not able to use it inside "listenOn".

### Workaround
I haven't found a suitable workaround yet, the solution with the least drawbacks is to use the UI as `listenOn` (default).
The drawback is, that the shortcuts trigger, even if the dialog is not focused (for example if another dialog is opened on top).

**Comment by taefi** [comment]
Hi @Springrbua, thanks for creating the issue. Is it possible to elaborate more on this? For example, by providing a snippet code illustrating the desired API form or the issue you want to solve using this.

**Comment by Springrbua** [comment]
Let's say, I have a `Dialog` with a form. `closeOnEsc` is set to false, as I would need to perform some checks (ask the user if he really wants to close etc.) before closing it. Therefore I register a `Shortcut` for the ESC key. Also, if saving the data fails, I show the error message in a dialog with `closeOnEsc`.
Now if I register the `ShortcutListener` using `listenOn(dialog)`, it will never be triggered.
If I don't use `listenOn` (default is the UI), the ESC shortcut is triggered, even if the error dialog is open and focussed.

The DOM in this case looks something like this:
- body
- - Dialog
- - DialogOverlay
- - Error Dialog
- - Error DialogOverlay (focus)

So would like to trigger the `Shortcut` only if the focus is within the DialogOverlay. However this does not seem to be possible, as we don't have the `DialogOverlay` on the server. The `Dialog` itself is only some kind of template on the client side and therefore it can't be used as `listenOn`

**Comment by knoobie** [comment]
@Springrbua this could probably help you with a workaround https://github.com/vaadin/vaadin-dialog/issues/229

**Comment by Springrbua** [comment]
@knoobie thank you for pointing me to that issue. Seems like my issue is a duplicate of it.
Gonna close this one in favor of the other issue.
Thank you
