### ISSUE TITLE
2.6 LitTemplates support : there are no ITs for LitTemplates

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#10149]
`master` contains lit templates ITs in the root-context test module:
https://github.com/vaadin/flow/tree/master/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate
Apparently the tests were not backported along with the LitTemplates support.
As a result the feature is not tested via ITs and regressions-prone.

**Comment by caalador** [comment]
For v14 the LIT tests are in `flow-tests\test-npm-only-features\test-npm-general\`

**Comment by denis-anisimov** [comment]
Ah.
Wasn't obvious. Couldn't find.
Thanks.
