### ISSUE TITLE
TC validation is totally broken

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#10153]
Fake PR: https://github.com/vaadin/flow/pull/10152

NO any single semantic change: only one new line is added

Validation is failed which is nonsense.
The reason is 
```
Caused by: java.net.BindException: Address already in use
```

Something wrong with build cluster.

**Comment by denis-anisimov** [comment]
Similar failures happens in various branches, not just `2.4`

**Comment by pleku** [comment]
Agents are back up for now but we need to revisit this if it happens again to understand what causes the situation and then extrapolate the issue
