### ISSUE TITLE
[Vaadin 20] Move Lumo and Material theme integrations to Flow components

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow#10182]
### Description

We are going to move all the web components to the [monorepo](https://github.com/vaadin/vaadin-web-components) for Vaadin 20, including themes.

So we will have unified version for every web component as well as `vaadin-lumo-styles` and `vaadin-material-styles`.
This means every time we make a new platform release e.g. `20.0.1`, we bump version also for Lumo and Material.

### Problem

Currently, Flow theme integrations contains `@NpmPackage` annotation with fixed version ([Lumo](https://github.com/vaadin/flow/blob/fd3fe381e2807e97f669fdafbd2b44e9883d0cc3/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L34), [Material](https://github.com/vaadin/flow/blob/fd3fe381e2807e97f669fdafbd2b44e9883d0cc3/flow-theme-integrations/material/src/main/java/com/vaadin/flow/theme/material/Material.java#L33)).

When moving to a new versioning, we need to keep these npm package versions in sync across the platform.
Otherwise we will get recurring issues like #9762 (that was fixed by bumping version at #9763).

### Proposed solution

Move theme integrations to  [vaadin-flow-components](https://github.com/vaadin/vaadin-flow-components) monorepo.
This would allow us to bump `@NpmPackage` for all the web components, including themes, at the same time.

The releasing workflow would look as follows:

1. Release web components (+ themes)
2. Bump versions in Flow components
3. Release Flow components

This means that Flow release will no longer be coupled with web components releases (and can be done any time).

### Alternative solutions

- Keep theme integrations in Flow, create automatic PR to bump @NpmPackage every time we release web components.
  - pros: less effort
  - cons: makes Flow release part of the components releasing workflow, requires to have more releases
- Relax `@NpmPackage` in Flow to not use fixed version, e.g. use `~20.0.0` instead of `20.0.1`
  - pros: less effort
  - cons: sounds more riskier
- Align Flow version with the platform
  - pros: versions are consistent
  - cons: : makes Flow release part of the components releasing workflow, requires to have more releases

**Comment by web-padawan** [comment]
As mentioned by @manolo there are two modules under flow-theme-integrations (lumo and material) but there are dependencies in flow-component-demo-helpers, flow-maven-plugin, flow-bom, and flow-tests.

Regarding `flow-component-demo-helpers` - `@Theme` usage removed by #9395 (looks like we can remove dependency).

I assume the `flow-tests/test-material-theme` and `flow-tests/test-lumo-theme` would be moved away too.

Otherwise the imports are present in following tests:

- `flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/TestComponents.java`
- `flow-tests/test-embedding/test-embedding-theme-variant/src/main/java/com/vaadin/flow/webcomponent/ThemedVariantComponentExporter.java`

**Comment by caalador** [comment]
It seems that the plugin class `TestComponents` is not used at all anymore so it can just be removed.
For the `ThemedVariantComponentExporter` we just need to create a `VariantTheme extends AbstractTheme` that has implemented the `getHtmlAttributes(String variant)` so that there is a variant to use.

As for the material and lumo test modules, they should probably live in the same place as the modules.

**Comment by web-padawan** [comment]
> It seems that the plugin class TestComponents is not used at all anymore so it can just be removed.

Submitted https://github.com/vaadin/flow/pull/10193 to remove it.

**Comment by web-padawan** [comment]
Looks like the test class is used by `BuildFrontendMojoTest.java` which checks for some imports being present.
So the validation build for my PR failed because of that. 

Probably we could keep the class but remove Lumo from there?

**Comment by caalador** [comment]
My how bad the asserts are. But it seems they are used from scanning the classpath.
Would expect there to be a possibility to have the tests using a CustomTheme file.

**Comment by manolo** [comment]
I guess all tests using Lumo can be refactored in order not to use it, or in the case a theme is needed we can create a stub theme just for testing. Having theme modules in flow components repo has a lot of pros, and simplifies flow project.

**Comment by web-padawan** [comment]
Reopening until #10220 is merged.
