### ISSUE TITLE
HasUrlParameterErrorIT::testNavigationTriggers is flaky

### ISSUE THREAD

**Issue by taefi** [vaadin/flow#10203]
Link:
https://bender.vaadin.com/viewLog.html?buildId=217056&tab=buildResultsDiv&buildTypeId=Flow_Flow25_Nightly_FlowFelixJettyCompatModeIntegrationTests25osgi#testNameId6931099944780672713

**Comment by denis-anisimov** [comment]
Link doesn't work.
As a result there is absolutely non any information why the test is flaky:
- no exception
- no stacktrace
- no screenshot

Please try to find at least some information about this and add it here. May be a link which is not broken.
Otherwise there is nothing to do.

**Comment by taefi** [comment]
There was a nightly build under 2.5 for felix jetty integration with osgi (as the url implies), which seems to be deactivated or removed. If the build is not there anymore, this issue is irrelevant and can be closed.
