### ISSUE TITLE
[Vaadin 19.rc1][PWA] Compile Error with @PWA annotation

### ISSUE THREAD

**Issue by pk1057** [vaadin/flow#10216]
Vaadin 19.0.0.rc1
Flow 6.0.0

I tried Vaadin 19rc1 due to a Comobobox bug and got the following error during compilation:

 Execution default of goal com.vaadin:flow-maven-plugin:6.0.0:build-frontend failed: There can only be one @PWA annotation and it must be set on the AppShellConfigurator implementor.

I have only one @PWA annotation:
`
@PWA(name = "jED PWA",
        shortName = "jED PWA",
        startPath = WebAppManager.FLOW_PWA_URL,
        description = "Progressive Web App for jED")
public class MainView extends AppLayout implements BeforeEnterObserver, HasDynamicTitle {
`

**Comment by denis-anisimov** [comment]
The error is not a compile error but it's a build error.
Unfortunately I cannot identify the reason without having the exact project.

But it looks like the error says what the mistake is: `There can only be one @pwa annotation and it must be set on the AppShellConfigurator implementor.`.
May be you have _ONE_ `@Pwa`annoation but it's not for `AppShellConfigurator`: your `MainView` doesn't extend `AppShellConfigurator`.

**Comment by knoobie** [comment]
As Denis said, your `@PWA` annotation is on the wrong class - this changed introduced in V15+

Just implement a simple `AppShellConfigurator` and move your annotation there, then it should work again. 

See: https://vaadin.com/docs-beta/latest/guide/configuration/pwa/#creating-pwas-with-flow
