### ISSUE TITLE
Endpoint with RolesAllowed (spring security) are not allowed

### ISSUE THREAD

**Issue by Lars-jnk** [vaadin/flow#10210]
### Description of the bug / feature
Can't execute methods from endpoints that are decoreated with RolesAllowed.

### Minimal reproducible example
1) setup up a vaadin fusion project (v18.0.6) with spring security that use a custom userDetailsService
2) add a Endpoint with @RolesAllowed("USER")
3) log in with a user that has this role
4) call a method of the endpoint

### Expected behavior
Execute and getting the result of the method

### Actual behavior
Get a 401 with the msg "Endpoint 'MyEndpoint' method 'myMethod' request cannot be accessed, reason: 'Unauthorized access to Vaadin endpoint'".

To test if I have really the right role I added an other endoint and SecurityContextHolder.getContext().getAuthentication().getAuthorities().toString() return "[USER]".

### Versions:
    - Vaadin / Flow version: 18.0.6
    - Java version: 11.0.2
    - OS version: Win10

**Comment by Lars-jnk** [comment]
Hi @haijian-vaadin,

I've made a example project: https://github.com/Lars-jnk/vaadin-security-role-bug
You can login with user:user or admin:admin. After that you see the user status (name and roles). I've made some view (User- and AdminView) to showcase the problem with the roles.

Your crm tutorial uses the inMemoryAuthentication. In this case it works fine, only when using a custom userDetailsService it didn't work.

**Comment by Artur-** [comment]
Did you take into account that a "role" and an "authority" is not the same thing? Roles should be prefixed by `ROLE_` if I remember correctly

**Comment by Lars-jnk** [comment]
Hi Artur,

your right. The prefix "Role_" was missing. Thanks a lot. Sry for wasting your time with these.

But, add this info to the documentation please. With a fat red blinking border. :)

**Comment by Lars-jnk** [comment]
There should an exception on the start if someone use @RolesAllowed() without the right prefix.
