### ISSUE TITLE
[Vaadin 19] Embedded Applications with Custom Theme and external font: error in dev tool console when there are two different servers

### ISSUE THREAD

**Issue by darmro** [vaadin/flow#10228]
### Description of the bug
I have an Vaadin 19 application with my custom theme (called zaiks) and some components exported via `WebComponentExporter`. This web components (I call them 'widgets') are then embedded in other external application.

But from the beginning what I have:

**A. I configured all according to the:**
1) custom theme documentation (https://vaadin.com/docs-beta/latest/ds/customization/custom-theme/)
2) custom theme demo source (https://github.com/vaadin/custom-theme-demo)
3) test embedding source (https://github.com/vaadin/flow/tree/master/flow-tests/test-embedding)

**B. Like in demo and test source I'm using an external font**
I'm using Google Poppins font. I put all needed ttf files into my theme folder:
![image](https://user-images.githubusercontent.com/56316289/110330682-59dd9480-801e-11eb-812f-92965f614465.png)

**C. I'm including this font** 
In `document.css`:
```
@font-face {
  font-family: "Poppins";
  font-style: normal;
  font-weight: 400;
  src: url("./webbase/font/poppins/Poppins-Regular.ttf") format("TrueType");
}
@font-face {
  font-family: "Poppins";
  font-style: normal;
  font-weight: 500;
  src: url("./webbase/font/poppins/Poppins-Medium.ttf") format("TrueType");
}
....
```
**D. All widgets classes (which extends `WebComponentExporter`) use my theme** 
via `@Theme("zaiks")` annotation.

**E. The same components (widgets) are added to the normal Views in my vaadin app**
so I can route to this view and see my widgets as normal internal components.

**F. My Vaadin app is deployed / served on serv1** (Tomcat)

**G. The external app is deployed / served on serv2** (IIS)
This exteernal app embeds my widgets served from serv1.
 
**The result:**
When I'm running my Vaadin app from serv1 and route to a View everything is ok (external font are used) .

But when I open a page from the external app on serv2 which embeds my widget is shown, but without my fonts, and in dev console I can see an error:
`GET https://<serv2>/<external app>/VAADIN/static/themes/zaiks/webbase/font/poppins/Poppins-Regular.ttf net::ERR_ABORTED 404 (Not Found)
`
Its because font is search in `<serv2>/<external app>` but it is in `<serv1>/<vaadin app>`:
`http://<serv1>/<vaadin app>/VAADIN/static/themes/zaiks/webbase/font/poppins/Poppins-Regular.ttf`

### Minimal reproducible example
Just run test embedding (https://github.com/vaadin/flow/tree/master/flow-tests/test-embedding) but in scenario in which embedding app is on a different server than embedded web components are deployed.

**Comment by caalador** [comment]
Hi.

As the css is already precompiled there is no way of actually injecting the server url of the resource on the fly.

There are a couple ways to get around this.

Have the url be a direct link to the embedded server in the css (this has also the problem of needing to know the deployment url)

Have the resource available online and directly link there.

The font/resource could be given as base64 encoded data in the css

To get the base64 encoded data you could use the static page to have the browser generate the base64 data for the file:
```
<html>
<body>
<input type="file" onchange="base64convert(this.files)">
<input onClick="this.select();" id="result" />
<script type="text/javascript">
  function base64convert (files) {
    console.clear()
    const reader = new FileReader()
    reader.onload = (e) => {
      document.getElementById("result")['value'] = e.target.result;
    }
    reader.readAsDataURL(files[0])
  }
</script>
</body>
</html>
```
Where you would give the file (for instance `ostrich-sans-regular.ttf`) and receive in the result input `data:application/octet-stream;base64,AAEAAAAQAQAA...`

This would then be added to the css as:
```
@font-face {
    font-family: "Ostrich";
    src: url(data:application/x-font-ttf;charset=utf8;base64,AAEAAAAQAQAA...) format("truetype");
}
```

 For fonts the `application/octet-stream` can be replaced with:
 - `application/vnd.ms-fontobject` for `eot`
 - `application/font-woff` for `woff`
 - `application/x-font-ttf`for `truetype`
 - `mage/svg+xml` for `svg`
but should work with the given octet-stream also.

**Comment by darmro** [comment]
Thanks @caalador.
The problem appeared when we moved to new Vaadin Custom Theme mechanism. 
Earlier (on Vaadin 14) we just had `<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900&amp;display=swap" rel="stylesheet">` to import font. But in Custom Theme it was said that the font should be introduced via @font-face (for example in document.css in theme folder). But in @font-face url have to be the same domain.
How can one import external font using external font using new Vaadin Custom Theme mechanism?
Your idea to user base64 is quite good, but needs some extra / hack trick ;)  Using just external url to the font will be the simplest option.

**Comment by caalador** [comment]
Hi.
Using the link the way you did on V14 should be fine even in combination with using the Custom Theme and would sound like a good solution for this issue as the link previously used only brings in a css with a set of `@font-face` declarations with external url's.

The new Custom Theme mechanism should work with any previous styling method also and should more be seen like an addition to the existing with the aim to make styling simpler than it was.

Would there be some way to formulate the `Document Root Style Sheet` part for custom theme that would not make it seem like fonts would need to be explicitly served through document.css with font-face?

**Comment by darmro** [comment]
But unfortunately this combination old v14 styling + custom theme didn't work.
We had in V14 font declared in `shared-styles.js` (in frontend folder) in `<custom-tag>`:
```
...
<custom-style>
	<style include="lumo-badge"></style>
	<style>
		@import url('https://fonts.googleapis.com/css?family=Poppins:200,400,500,600,700&display=swap');
...
```

Then usage of this font in any css declared in our custom theme didn'work, for example font weights wasn't recognized inside custom theme css, as if they were not visible inside the custom theme.
That's why we change it to @font-face.

**Comment by caalador** [comment]
Can you have the `@import url('https://fonts.googleapis.com/css?family=Poppins:200,400,500,600,700&display=swap');` in `document.css`?

**Comment by darmro** [comment]
I tried using only @import few months ago and it didn't work, ie font weight=200,500,700 were not visible. Only standard 400 (normal) and 600 (bold) were.  That's why we used @font-face.
Quick example:
[my-app.zip](https://github.com/vaadin/flow/files/6342128/my-app.zip)

**Comment by jouni** [comment]
> Can you have the @import url('https://fonts.googleapis.com/css?family=Poppins:200,400,500,600,700&display=swap'); in document.css?

This should be the correct solution for this use case, IMO. Not sure why it’s not working as expected. Did you still have the `@font-face` declaration as well (it should be removed, as that is going to come from Google Fonts then)?

**Comment by darmro** [comment]
I have only  `@import` in document.css (without any `@font-face`). Also in this test app (my-app) I've attached to this issue.
And unfortunately it seems not to work as expected :/

**Comment by caalador** [comment]
Does it work if you copy over all the font-faces from the import url?

**Comment by darmro** [comment]
Hi @caalador,
I dont't quite undersand. You mean if I download these font-faces into some font folder in my project? If this is what you mean then the answer is no, it doesn't work either- look the first comment in this issue. 
I give `my-app.zip` simple test app, in which when only `@import` is used then some font weights are not seen in the app - strange. Did you check this?

**Comment by caalador** [comment]
I meant that as the import of the fonts.googleapis.com returns
```
* devanagari */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 200;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLFj_Z11lFc-K.woff2) format('woff2');
  unicode-range: U+0900-097F, U+1CD0-1CF6, U+1CF8-1CF9, U+200C-200D, U+20A8, U+20B9, U+25CC, U+A830-A839, U+A8E0-A8FB;
}
/* latin-ext */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 200;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLFj_Z1JlFc-K.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 200;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLFj_Z1xlFQ.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
/* devanagari */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiEyp8kv8JHgFVrJJbecmNE.woff2) format('woff2');
  unicode-range: U+0900-097F, U+1CD0-1CF6, U+1CF8-1CF9, U+200C-200D, U+20A8, U+20B9, U+25CC, U+A830-A839, U+A8E0-A8FB;
}
/* latin-ext */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiEyp8kv8JHgFVrJJnecmNE.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiEyp8kv8JHgFVrJJfecg.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
/* devanagari */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLGT9Z11lFc-K.woff2) format('woff2');
  unicode-range: U+0900-097F, U+1CD0-1CF6, U+1CF8-1CF9, U+200C-200D, U+20A8, U+20B9, U+25CC, U+A830-A839, U+A8E0-A8FB;
}
/* latin-ext */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLGT9Z1JlFc-K.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLGT9Z1xlFQ.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
/* devanagari */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLEj6Z11lFc-K.woff2) format('woff2');
  unicode-range: U+0900-097F, U+1CD0-1CF6, U+1CF8-1CF9, U+200C-200D, U+20A8, U+20B9, U+25CC, U+A830-A839, U+A8E0-A8FB;
}
/* latin-ext */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLEj6Z1JlFc-K.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLEj6Z1xlFQ.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
/* devanagari */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7Z11lFc-K.woff2) format('woff2');
  unicode-range: U+0900-097F, U+1CD0-1CF6, U+1CF8-1CF9, U+200C-200D, U+20A8, U+20B9, U+25CC, U+A830-A839, U+A8E0-A8FB;
}
/* latin-ext */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7Z1JlFc-K.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7Z1xlFQ.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```
To just add those directly to the document.css

**Comment by darmro** [comment]
Aaaa, here it is :)  I've just check your idea and it works! Thanks @caalador.
Is this the only and official way for Vaadin to use external fonts with Vaadin embedded components?

**Comment by caalador** [comment]
As Jouni commented I would have expected the import to work the same.

Another choice could be to add to the importing page head:
`<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:200,400,500,600,700&display=swap">`
though this will make it hardcoded and not change if the embedded one is changed.
This could perhaps be added from the embedded component also in some way, but I can't say from the top of my head
where and how.

**Comment by darmro** [comment]
The workaround for this, we did few months ago, was exactly adding to the importing page head (in external web CMS which embeds our vaadin component) `<link rel="stylesheet" ..>` for our (vaadin componenet) font. It works thats why we could wait 2 months for this issue (we set BFP for this) being solved in some nicer way :)

**Comment by caalador** [comment]
Well with one embedded application on the page it's possible to in the constructor have
```
getElement().executeJs("var link = document.createElement('link'); link.rel ='stylesheet'; link.href='https://fonts.googleapis.com/css?family=Poppins:200,400,500,600,700&display=swap'; document.head.appendChild(link);");
```
Which would also do the same thing and be controlled from the webcomponent.

Also I guess the problem might be that the import is an external url and under the hood the new theme mechanism uses `Constructable StyleSheets` which may or may not work with external stylesheet references. At least looking at the generated `document.adoptedStyleSheets` I can't see anything for the import or what it should bring in.

**Comment by darmro** [comment]
Hmm .. unfortunately this external CMS app (which embeds our vaadin components) i SPA app- there's only one page for the whole app, only its content changes. So there's only one page header. Our vaadin components are embedded in few pages of this CMS app, so we cannot inject to this single page the link element into the head.

I wonder why the use of `@import` for importing the font doesn't work as expected (some font widths are not visible in the app). I've prepared siplme app (my-test.zip) that you could use to see it. 

The use of `@import` is the best option, it'll work for both cases (single vaadin app and embedded web components), but it doesn't work as expected, its the main problem.

**Comment by caalador** [comment]
Well even adoptedStyleSheets will get added again if it's loaded again on the page.

Have you tried just using an external stylesheet using `@StyleSheet("https://fonts.googleapis.com/css?family=Poppins:200,400,500,600,700&display=swap")`?

**Comment by darmro** [comment]
We're using new Vaadin Custom theme mechanizm. Where we are to put `@StyleSheet`? In front of each web component which is embedded in this external CMS? And then in each View in our vaadin app (or in the AppShellConfigurator)?

**Comment by caalador** [comment]
It would work best from the exported component as this would always add it on load.
Else it would need to be on a component in the view chain as it is an annotation that is read during execution.

This might be an enhancement need for the custom theme feature so it would be easier to reuse with the theme by being able to have external links in the `theme.json` that would be added to head as a `link rel="stylesheet"`. @rolfsmeds what would you think about it?

**Comment by rolfsmeds** [comment]
Yes, I think making it possible to do it through theme.json would be the second best option (the best of course being that regular css imports would just work), and would be in line with how stylesheets from npm packages are included.

DX-wise, optimally the same importCss property could be used as for npm, with the value being a url as the only difference.

**Comment by darmro** [comment]
Hi @caalador & @rolfsmeds.
In my opinion, just the `@import url('https://fonts.googleapis.com/css?family=Poppins:200,400,500,600,700&display=swap');` id `document.css` would be the best option and should work properly both for single vaadin app and components embedded via WebComponentExporter 
But now:
1) `@import` - doesn't work at all
2) `@font-face` with with font places locally in theme folder (method described in vaadin doc)- works for single vaadin app but not for embedded components.
3) @StyleSheet- dont't know if it works, probably yes, but requires a lot of effort (must be placed in every view, component).

There should be one way in custom theme mechanism to include fonts in all scenarios :)

**Comment by darmro** [comment]
I checked it again today and the `@import` for font doesn't work completely. I don't know why this Poppins for 3 weights were visible earlier. I have in the workspace few other projects which uses this font ;)  Now (after cleaning the whole my-app test project) the font Poppins is not visible at all with only `@import` in `document.css.` 
So `@import` for font doesn't work at all.

**Comment by caalador** [comment]
Yes I actually just found out that even though almost all links and information talks that it should be possible to use `@import` with `CSSStyleSheet.replace()` that the feature was actually removed and the new situation is:
- `replace()` ignores `@import` rules and continues to parse the rest of the sheet.
- `replaceSync()` ignores `@import` rules and continues to parse the rest of the sheet.

https://www.chromestatus.com/feature/4735925877735424

I see that we could probably handle the external import by making a link reference by ourselves, but I need to investigate first what the output of the css file is after webpack and its loaders have handled it so that we can parse the correct imports to generate links for.
