### ISSUE TITLE
[Vaadin 19] Strange behavior when setting width on a TextField

### ISSUE THREAD

**Issue by darmro** [vaadin/flow#10243]
### Description of the bug / feature
I have a static constant value:
```
public final class Width {
	public static final String TRIPPLE_LONG = "34‬em";
}
```

I have a simple Vaadin 19.0.0.beta4  app. I took some sample app from Vaadin "Start building" page, changed Vaadin version from 18 to 19 and from jar to war app.

I added to main view only two fields with a specific width:
```
TextField f0 = new TextField("Field 0");
f0.setWidth("34em");
...
TextField f1 = new TextField("Field 1");
f1.setWidth(Width.TRIPPLE_LONG);  // = 34em!
...
```
And the result is strange:
![image](https://user-images.githubusercontent.com/56316289/110491531-ab0a8880-80f1-11eb-83d0-7658925d93f0.png)

Two fields are set to 34em width, but one via constant value. Why only setting exact value works?
I even displayed `Width.TRIPPLE_LONG` value on console (doing syso) in front of `f1.setWidth()` to check if this static fild is set by jvm and it is! Equal to 34em. Hmm ... I am dumbfounded ;)

### Minimal reproducible example
My simple app:
[my-app.zip](https://github.com/vaadin/flow/files/6109453/my-app.zip)

### Versions:
    - Vaadin / Flow version: 19.0.0.beta4
    - Java version: 1.8
    - OS version: Win10
    - Application Server (if applicable): Tomcat9

**Comment by denis-anisimov** [comment]
`"34‬em".equals(Width.TRIPPLE_LONG)`. returns `fasle`.

This is the reason.
I have no idea which way `Width.TRIPPLE_LONG` is declared even though it looks like `"34‬em"` : it's not.
May be some unicode issues or whatever. If I remove valiue in `Width.TRIPPLE_LONG`  declaration and write it properly then it works as expected.

Anyway: this has no any relation to Vaadin: the constant defined in Java has exactly the value which you written (and the value is wrong).

**Comment by darmro** [comment]
Thank you Denis, I have to look closer what's going. Thanks!
