### ISSUE TITLE
wrong font used in the connection indicator

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#10253]
The connection indicator uses the system default font whereas it should use the font defined in the application theme. Vaadin 19.0.0.

**Steps to reproduce**
 - create a new Vaadin 19 project: `npx @vaadin/cli init v19-fusion --latest --fusion`
 - start the app with `mvn`
 - turn on the offline mode in the browser dev tools
 - see the font in the connection indicator
   ![image](https://user-images.githubusercontent.com/22416150/110632783-afe24180-81b0-11eb-9326-2e1bf68ce911.png)

Expected: the connection indicator should use the font from the lumo theme.

**Comment by Haprog** [comment]
Steps to reproduce seem to be wrong atm. since that seems to generate a project that doesn't use endpoints and thus doesn't have a connection indicator at all.

**Comment by Haprog** [comment]
If I use this to init a project:
```
npx @vaadin/cli init v19-fusion --preset master-detail-view --latest --fusion
```
I get an offline indicator when toggling dev tools to offline mode, but I see it's already using `font-family: var(--lumo-font-family);` (inherited from `<html>`) so it seems I can't really reproduce the issue.

**Comment by Artur-** [comment]
If you have an application theme, then that sets the font family on `<html>` and the font is correct in the indicator

**Comment by haijian-vaadin** [comment]
Close as not reproducible.
