### ISSUE TITLE
Import to Intellij broken

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#10307]
`flow-client/pom.xml` loads `../flow-server/src/main/java` as a resource folder, causing Intellij to ignore sources from that folder, causing a lot of compiler errors.

Workaround is to
1. Comment out the `<resource><directory>../flow-server/src/main/java</directory></resource>` from the pom.xml
2. Remove the source in Project Structure modules

This is confusing and should be mentioned in CONTRIBUTING.md.

**Comment by knoobie** [comment]
Thanks and I was wondering if that's only my problem..

**Comment by mvysny** [comment]
It's actually an issue with IntelliJ IDEA https://youtrack.jetbrains.com/issue/IDEA-192220

**Comment by pleku** [comment]
We need to mention this in the contribution guide.
