### ISSUE TITLE
Give BuildUtil possability to  define FLOW_RESOURCES_FOLDER

### ISSUE THREAD

**Issue by stbischof** [vaadin/flow#10318]
Will do a PR

Extract  FrontendUtils.DEFAULT_FLOW_RESOURCES_FOLDER into Adapter to have more possibilitiea to control where the resource should be placed. For example, in not maven Layouts, the base path '/target' is not the best idea

https://github.com/vaadin/flow/blob/0be0cb985311bfe9a95eb5b264459a42d6b24ca9/flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java#L133

**Comment by mcollovati** [comment]
Resources folder is not hard-coded anymore
