### ISSUE TITLE
Make hard-coded 'target/' folder configurable

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#10335]
Certain places in Flow contain hard-coded Maven-style 'target/' folders, while Gradle use 'build/'. For example:
* the `VaadinConnectTsGenerator` class - the `outputFolder` field.
* `FrontendUtils.TARGET`
* Possibly others?

### Versions:
    - Vaadin / Flow version: 20 / 7.0.0.alpha1

**Comment by stbischof** [comment]
@mvysny thank you for this! #10319 adresses the ability to set the folder in the plugin-base.

**Comment by stbischof** [comment]
https://github.com/vaadin/base-starter-flow-osgi/blob/49207b830e8654f04188218af59af9899ace51f9/starter/webpack.generated.js#L63

Here is one more hard coded .

**Comment by caalador** [comment]
`webpack.generated.js` is generated each run by the application so the paths will update by what the application uses.

**Comment by mvysny** [comment]
@stbischof thank you, but I believe that the credit for this goes to you, @taefi and @caalador :1st_place_medal:
