### ISSUE TITLE
fix: Add API to control whether Binder converts back to presentation (forward port from v8)

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#10342]
### Description

Since Vaadin 7 the binder API did not propagate conversion back to presentation. This changed in [8.12.1](https://github.com/vaadin/framework/pull/12132) and [19.0.0](https://github.com/vaadin/flow/pull/9227) to always update the field with the converted value as well. 

This fix / behaviour change introduced a major regression in most of our application that were pretty hard to spot and raised a lot of problems on our side that's why I opened VS-3752 after discussing this with Anna and Tatu to allow for configuration of the behaviour. 

### Use Case

We heavily rely on Binder and it's conversion to protect us from XSS attacks and other security concerns that come from user input. To reduce the need of checking every field on submit, we always trigger those conversion within the 

```java
    binder.forField(name)
      .withConverter(new CleanUpUserInputConverter())
      .bind(MyObject::getName, MyObject::setName);
```

One of those conversion uses `Jsoup` to escape anything `html` related like e.g. `Jsoup.clean(value, Whitelist.none())` - *this resulting in removal of trailing white spaces*.

This and other validations have to be done while the user is typing / filling out the field to allow for instant feedback (default 400ms from Textfield), that's why `onBlur` isn't really an option for us.

With the use case above, you get a okayish sanitized user input for further processing and the user gets instant feedback while typing without any magic which reformats his input. ;)  

### Problem Description

After we updated our applications to a version that has the fix, we got calls from customers that they space bar won't work anymore and we got messed up inputs from some users. We analyzed the problem and tried to reproduce it, which was pretty easy. While typing *slowly* you can literally see that the trailing space from an input is removed - resulting in a major problem for our older user. Our user base is kinda diverse (18-80 years old). 

To fix the problem for now, I updated our conversions to check if the input has a trailing space and adds it after the conversion. This fixes the problem for the user, but results in problems later for us because now we have to remove every trailing space on submit. 

### Example (V8)

https://gist.github.com/knoobie/74fe2bf2e4745be4bd52d5ccd48566d3

**Comment by jsalts** [comment]
Just wanted to add a note that enabling this by default is api breaking in a specific scenario: 

1. Using a converter like this. 
`    builder.withConverter(c -> c == null ? null : c.getId(), id -> null)`
2. Using a write-to-bean only binder without any readBean() calls. 

In v14 this this would have been sensible code (e.g. why write id -> bean lookup code that would never be used?). In v23 this causes a quite difficult to debug exception with the fix being to add setConvertBackToPresentation() my vaadin grid binding to avoid triggering the toPresentation part of my combobox binding. From an api perspective I don't even understand why it specifically needs to be on the grid versus the combobox.
