### ISSUE TITLE
Allow null in `Element.createText(text)`

### ISSUE THREAD

**Issue by Peppe** [vaadin/flow#10355]
### Description of the bug / feature
I had this code in my app. 
```java
Div title = new Div(new Text(person.getTitle());
```

It worked well up until I happened to have a person with no title set. At that point I got a `IllegalArgumentException: Text cannot be null`. To go around this problem, I refactored my code to 
```java
Div title = new Div(
                new Text(person.getTitle() != null ? person.getTitle() : ""));
```
It would be easier for the users if they would not have to take care of this kinds of null checks themselves, and `Text` would work even if you would pass in `null`. 

### Minimal reproducible example
Div title = new Div(new Text(null));

### Expected behavior
`<div></div>` in DOM.

### Actual behavior

`IllegalArgumentException: Text cannot be null`

### Versions:
    - Vaadin / Flow version: 20.0.0.alpha3 / 7.0.0.alpha1
    - Java version: 11
    - OS version: Mac
    - Browser version (if applicable):
    - Application Server (if applicable):
    - IDE (if applicable):

**Comment by Peppe** [comment]
```java
H6 department = new H6(person.getDepartment());
```
H6 and similar elements already works this way. Element#L381
```java
public Element setText(String textContent) {
        if (textContent == null) {
            textContent = "";
        }
```

**Comment by pleku** [comment]
So it has been like this for over 5 years (!) but I think is not really user friendly. The idea probably was that creating a `null` text would not a developer error ... but as the `Element:setText` accepts `null` and like pointed converts it to `""`, it could be done for `createText` too.

#### Acceptance Criteria
- swap the `createText` to allow `null` and convert it to `""`
- update the javadocs
- add a unit test to `ElementTest`

**Comment by knoobie** [comment]
@pleku I created a PR which is a little bit more than your acceptance criteria, because they would not fix the original problem of Peppe. Additionally to `Element` the `Text` API was also updated to allow null.

**Comment by Peppe** [comment]
Thank you @knoobie for fixing this!
