### ISSUE TITLE
Support servlet 5 aka jakarta.servlet

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/flow#10366]
The newer versions of many app-servers (e.g. Tomcat 10 and Jetty 11) have shifted to use the `jakarta.servlet` namespace. Consider the possibility of supporting those in Vaadin apps.

**Comment by Legioth** [comment]
There is no known good way of supporting both the `jakarta.servlet` and `javax.servlet` namespaces at the same time.

Our options are therefore probably limited to one of these:
* Publish separate releases for each standard. We could in theory split out the differing parts to a separate library, but right now it would require separate versions of at least the `flow-server` dependency.
* Drop support for `javax.servlet`.
* Provide some kind of supported integration to transform between the two standards. This could be based on  https://github.com/eclipse/transformer or https://github.com/apache/tomcat-jakartaee-migration.

**Comment by pleku** [comment]
I think we need to do something for this for the next-LTS - not maybe immediately but at least have a plan for what/when.

**Comment by knoobie** [comment]
Just a service notification; Spring 6 / Spring Boot 3 to be released in Q4 2022 requires Java 17+ and Jakarta 9+

https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6

**Comment by Artur-** [comment]
Some fundamental issues:
* Atmosphere has no version for servlet 5: https://github.com/Atmosphere/atmosphere/issues/2467
* Jetty websocket support has changed in Jetty 10 so it needs some refactoring, e.g. the `websocket-server` does not exist in Jetty 11
* Apache commons file upload is for Servlet 3: https://issues.apache.org/jira/browse/FILEUPLOAD-345

**Comment by mperktold** [comment]
>     * Jetty websocket support has changed in Jetty 10 so it needs some refactoring, e.g. the `websocket-server` does not exist in Jetty 11

We are already running on Jetty 10 without any problems in that regard, using the new `websocket-javax-server` module.

I have a [repo](https://github.com/mperktold/vaadin14-embedded-jetty) that replicates our setup. It is forked from a Vaadin 14 project, but it has been upgraded to Vaadin 19, and the same setup works for us with Vaadin 22.

**Comment by mshabarov** [comment]
Implemented in Vaadin 24.0.
