### ISSUE TITLE
Update docs and starter project for the default endpoint access change

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#10372]
#10328 changes the default endpoint access from `PermitAll` to `DenyAll`. It's a breaking change, we should update the existing docs and starters accordingly, also should mention it in the upgrade guide.

**Comment by joheriks** [comment]
Which starters need update?

**Comment by haijian-vaadin** [comment]
The starter wizard https://github.com/vaadin/starter-wizard. The endpoints in the generated projects should now have `@PermitAll`.

**Comment by joheriks** [comment]
Silly question perhaps, but they have `@AnonymousAllowed` since there is no auth in start.vaadin.com apps? Or am I missing something?

**Comment by haijian-vaadin** [comment]
oh, right, the Start Vaadin doesn't have authentication. So no need for change there. Updating docs would be enough.
