### ISSUE TITLE
support query parameters in `BeforeEnterEvent.forwardTo`

### ISSUE THREAD

**Issue by HermanBovens** [vaadin/flow#10420]
Currently you can't supply query parameters in any of the overloads for the `forwardTo` method of `BeforeEnterEvent`.
In some cases this is necessary.  For example, you want to forward to a view which requires these parameters to be present, or you have a view with an optional query parameter and want to let it forward to itself but with a default value for this parameter.

**Comment by pleku** [comment]
Hello Herman. I think this so closely related to #7680 - the title is the same but it has a slightly different description - that we should merge this issue to that one. Please comment and +1 that and we'll get on it. Thanks

**Comment by HermanBovens** [comment]
OK, actually I wasn't even aware that original query parameters were
retained by default, don't think I saw it mentioned in the javadoc.

Op ma 29 mrt. 2021 13:47 schreef Pekka Hyvönen ***@***.***>:
