### ISSUE TITLE
Fusion : PopStateHandlerIT fails

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#10485]
`PopStateHandlerIT` had a number of `hasClientIssue("7572")` which effectively disabled some piece of test in every test method.

I'm going to make a PR and change the test to disable the parts which are failing .

But the all the tests should work in the end. The fix for this ticket should remove all disabled parts (and may be just return the test state to the same as it has e.g. in `2.5` branch).

Similar ticket: https://github.com/vaadin/flow/issues/7572.

For some reason #7572 doesn't mention `PopStateHandlerIT` anyhow.

**Comment by denis-anisimov** [comment]
This PR disables failing parts : https://github.com/vaadin/flow/pull/10486

**Comment by haijian-vaadin** [comment]
TODOs:
1. Find out why the IT is failing with new bootstrapping, update the test to make it green. Open a discussion if the test is irrelevant.
2. Test against the v14 bootstrapping mode is out of scope for this ticket.
