### ISSUE TITLE
Upgrade Atmosphere to 2.7

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#10510]
Atmosphere 2.6.5 will contain an important patch which will make Vaadin run on Quarkus without further workarounds: https://github.com/Atmosphere/atmosphere/issues/2427 . Please upgrade the Atmosphere version to 2.6.5 in flow master once it's released.

### Versions:
    - Vaadin / Flow version: 20.0.0.alpha5 / 7.0.0.alpha2

**Comment by pleku** [comment]
This is currently in progress as #10510 but there is a regression in new Atmosphere 2.7.0 which is being handled before we cant proceed.

**Comment by pleku** [comment]
The version would need to be 2.7+ instead since the fix didn't land to 2.6, but there is doubt over whether or not it actually fixes the Quarkus + Atmosphere web sockets issue.

**Comment by Artur-** [comment]
Upgrade reverted because of https://github.com/Atmosphere/atmosphere/issues/2444

**Comment by caalador** [comment]
updated to 2.7.3 in #12738
