### ISSUE TITLE
Fusion: NavigationTriggerIT fails

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#10513]
Related ticker : https://github.com/vaadin/flow/issues/7572

The `NavigationTriggerIT` has been disabled because of `7572`.
The latter ticket is closed but `NavigationTriggerIT` still fails.

I'm going to refactor the test to disable its part which is failing in fusion.
The functionality should be fixed and restored. The test should be enabled after that.

**Comment by denis-anisimov** [comment]
Test is disabled : https://github.com/vaadin/flow/pull/10514

**Comment by haijian-vaadin** [comment]
TODOs:
1. Find out why the IT is failing with new bootstrapping, update the test to make it green. Open a discussion if the test is irrelevant.
2. Test against the v14 bootstrapping mode is out of scope for this ticket.
