### ISSUE TITLE
HasSize relies on inline style for values, which is not always accurate

### ISSUE THREAD

**Issue by nrayburn-tech** [vaadin/flow#10554]
### Description of the bug / feature

I want to set the height of a grid to be (100% - height of the button).  To do this, I am attempting to do `grid.setHeight('calc(100% - ' + button.getHeight() + ')');`.  However, set/getHeight relies on the element's style attributes.  In this case there is not any inline style applied, so it is inaccurate.
While this is my exact use case currently and could be resolved in other ways, I believe the issue is still the same.  I think there should be a way to get the current size when inline styles have not been applied.

### Minimal reproducible example

> If this snippet isn't enough, I can create an example in a git repo.
```java
        Div headerDiv = new Div();
        Button button = new Button("Test");
        headerDiv.add(button);

        Div mainDiv = new Div();
        mainDiv.setHeight("calc(100% - " + button.getHeight() + ")");
        // This provides the desired outcome, but requires the use of a static value.
        // mainDiv.setHeight("calc(100% - 44px)");
        add(headerDiv, mainDiv);
```

### Expected behavior

`button.getHeight()` returns a value of 44 or 44px.

A few alternative HTMLElement attributes `offsetHeight`, `clientHeight`, `getBoundingClientRect().height`.  The downside of these is they are all in pixels, there is not any unit provided like the current implementation.  An option could be to default to the current implementation, but fallback to one of these if needed.

### Actual behavior

Null or an empty string is returned, because the button does not have an inline style for the `height` attribute.

### Versions:
    - Vaadin / Flow version: 14 (Appears to still be the same on current [master](https://github.com/vaadin/flow/blob/d342b88dbbb3bfc709f69b014a958ef91c98ed65/flow-server/src/main/java/com/vaadin/flow/component/HasSize.java#L289-L291).)
    - Java version: 11
    - OS version: macOS 11.2.3
    - Browser version (if applicable): N/A
    - Application Server (if applicable): N/A
    - IDE (if applicable): N/A

**Comment by knoobie** [comment]
See the note within the javadoc: 


> Note that this does not return the actual size of the component but the height which has been set using {@link #setHeight(String)}.


Meaning it can only return the height, if you specify it yourself on the server side.

**Comment by nrayburn-tech** [comment]
I don’t know how I missed that.

it makes sense why. I can resolve my issue in another way.
