### ISSUE TITLE
[BUG] Vaadin 14.5.1 pnpm enabled does not build correctly

### ISSUE THREAD

**Issue by sascha-frinken** [vaadin/flow#10586]
**Describe the bug**
Running vaadin 14.5.1 with `pnpm` enabled makes styles and components disappear.

**To Reproduce**
1. Download app with vaadin 14.5.1 from [vaadin starter](https://start.vaadin.com/?preset=lts)
2. Add `vaadin.pnpm.enable = true` to `application.properties`
3. Delete `package.json` and `package.json.lock`    
3. Run application
4. Open http://localhost:8080 in browser

**Expected behavior**
Application looks as run with `vaadin.pnpm.enable = false`.

**Screenshots**

**Not working (pnpm.enable = true)**
![not-working](https://user-images.githubusercontent.com/1926770/113882455-9b986100-97bd-11eb-97e9-4183d4b644df.png)

**Working  (pnpm.enable = false)**
![working](https://user-images.githubusercontent.com/1926770/113882583-b5d23f00-97bd-11eb-838c-ea7ef898d28c.png)

**Desktop (please complete the following information):**
- OS: Linux
- Browser: Firefox, Chrome
- Version: latest
- Vaadin platform version: 14.5.1

**Additional context**
Same happened with vaadin gradle plugin.

**Comment by knoobie** [comment]
Duplicate of https://github.com/vaadin/flow/issues/10571 - a fix is already in development.

**Comment by caalador** [comment]
Is `Run application` executing through maven or and IDE? (I did get a functional app with running from maven)
Which version of the gradle plugin was used for the gradle run? 
The gradle plugin version should be 0.14.5.1 

Was there any exceptions in the logs as npm vs pnpm should not make a difference to the actual application look if they succeed in getting all the packages.

**Comment by sascha-frinken** [comment]
Looks like it is a known bug #10571

**Comment by knoobie** [comment]
I was thinking the same, but yours kinda manifested in another way.

**Comment by sascha-frinken** [comment]
> Is Run application executing through maven or and IDE? (I did get a functional app with running from maven)

We ran it both ways (IDE and with mvn / gradle)

> Which version of the gradle plugin was used for the gradle run?

Latest version 0.14.5.1, as recommended

> Was there any exceptions in the logs as npm vs pnpm should not make a difference to the actual application look if they succeed in getting all the packages.

Nothing specific. Otherwise, I would have added it.

I should mention that we almost spent half a day in debugging and verifying the problem.  
It looks like it is not easy to reproduce.  It looks like doing it from scratch with no `.vaadin`, `.pnpm-store`, `.npm`, `.pnpm-state.json` in home dir and no `node_modules`, `xpackage.json`, `webpack.generated.js`, `webpack.config.js`, `package-lock.json`, `package.json` in your project root does the trick.

**Comment by sascha-frinken** [comment]
OK below is my reproducer.

1. Run the script below. This will start a docker container with the gradle spring boot sample run via `./gradlew bootRun`
2. wait until you see _Completed initialization…_ in the docker logs.
3. Open http://localhost:8080 in your browser

It doesn't look too weird but notification is not working.

To see a working version, delete the ./base-starter-spring-gradle (might require sudo…), and change the line with `echo 'vaadin.pnpm.enable = true' >> …` to `echo 'vaadin.pnpm.enable = false' >> …`. 

```bash
#!/bin/sh

git clone https://github.com/vaadin/base-starter-spring-gradle

echo 'vaadin.pnpm.enable = true' >> ./base-starter-spring-gradle/src/main/resources/application.properties

cat > ./base-starter-spring-gradle/docker-run.sh<< EOF
#!/bin/sh

cd /var/app
./gradlew bootRun
EOF

chmod 755 ./base-starter-spring-gradle/docker-run.sh

docker run -d --name vaadin-bug  --rm  -v  `pwd`/base-starter-spring-gradle:/var/app -p 8080:8080 --entrypoint /var/app/docker-run.sh adoptopenjdk:11-hotspot

docker logs -f  vaadin-bug
```

**Comment by pleku** [comment]
Please retest with Vaadin 14.5.2 to see if it still reproduces.

**Comment by sascha-frinken** [comment]
Looks like it doesn't reproduce. Just add a line with `sed -i "s/\"14\.5\.1\"/\"14\.5\.2\"/g" base-starter-spring-gradle/build.gradle` after the `git clone…` in above script.

**Now:**  
![image](https://user-images.githubusercontent.com/1926770/114266390-6a56a580-99f6-11eb-892a-0f0533270573.png)

**Before:**  
![image](https://user-images.githubusercontent.com/1926770/114266502-fb2d8100-99f6-11eb-92ef-0ed171d8497b.png)

Thank you.
