### ISSUE TITLE
When using a template I want to be able to use two way databinding so that I can create a form using input tags

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#1067]
I want to write `<input [(value)]="firstName">` in the template and have template automatically update the "firstName" part of the model using a "change" event.

In practice this could be implemented in Template as

```
protected Stream<String> getSynchronizedEvents(String tagName, String propertyName)
```

which is capable of providing the event names for  `value` used in an `<input>`

**Comment by mshabarov** [comment]
Closed as outdated. The template syntax described here pre-dates Polymer template support.
