### ISSUE TITLE
Use Double Submit Cookie for Fusion CSRF token

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#10703]
Instead of storing the CSRF token in the session, the [Double Submit Cookie](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie) approach should be used.

The CSRF token would be put in a cookie, and also be sent in a header as is currently done. The server compares that these two tokens are equal.

This has the benefit of enabling CSRF even when there is no session, for example for stateless applications.

**Comment by Legioth** [comment]
> This has the benefit of enabling CSRF even when there is no session, for example for stateless applications.

What's the point of CSRF protection in cases with no session?

**Comment by haijian-vaadin** [comment]
Related to https://github.com/vaadin/flow/issues/9789
