### ISSUE TITLE
Grid initially loads more than page size number of items when configured to lazy load

### ISSUE THREAD

**Issue by fionnachan** [vaadin/flow#10752]
### Description of the bug / feature
I'm looking to implement lazy load to a grid with a custom backend data provider.
I'm trying to load ~5 rows initially (total item count is 33 from the backend)
```
grid.setPageSize(5);
grid.setDataProvider(dataProvider);
```
However it seems like the data provider would just return all 33 (default limit is 50 according to what I read from the docs?) because the grid has determined that there's a scroll bar so it could load up to 50 items?
[This comment on stackoverflow describes what I think I'm experiencing](https://stackoverflow.com/a/63065739/5143717)

### Versions:
    - Vaadin / Flow version: 14.4.10
    - Java version: 11

**Comment by knoobie** [comment]
Is it possible that you have `grid.setHeightByRows` used in your application? See https://github.com/vaadin/vaadin-grid/issues/2157

**Comment by fionnachan** [comment]
Hello, no we don't have this setup, however the grid has `flex: 1 1 100%;` if it's relevant at all.

**Comment by miguelatvaadin** [comment]
Hi @fionnachan ,

the `setPageSize` method only sets up the preferred page size, but the grid component can request more items from the server for performance sake.

According to my tests, the component tries to preload at least 25 items, but it also depends on the component size. If you set the page size to a higher value (e.g. 60) you will see that the component asks for data as expected.

This makes sense, as you will probably never want to retrieve so few rows from the server (it would usually be quite inefficient).

I hope this helps. Please let us know if you need further assistance

**Comment by fionnachan** [comment]
Thanks for the reply @miguelatvaadin. In my case, because I have several component columns. Preloading 25 rows is enough to slow down the page load. Is there any way to get around this to reduce the number of preloaded items?

**Comment by miguelatvaadin** [comment]
Hi @fionnachan,

I've been told that there are plans to change this behavior, so you will be able to change the minimum rows that the grid needs to load.

I have opened a new issue in the grid component repository (https://github.com/vaadin/vaadin-grid/issues/2166), so you can follow up it from there.

Thanks and best regards
