### ISSUE TITLE
When I have typoed the name of a synchronized property I want a clear exception so I can know why it doesn't do anything

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#1077]
We can most likely assume that any JS property that we define is always present (i.e `foo in element` is true)

**Comment by pleku** [comment]
I think this might be still relevant when building polymer templates manually or integrating existing ones to Java, but not probably that important as this has been around for a while without any feedback. Closing the issue, I'm sure it will surface again if it bothers users.
