### ISSUE TITLE
[Fusion]: research on how to use Spring Security with JWT based authentication

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#10773]
By default, the authentication in Spring Security is session-based, which prevents an application to be stateless.
Let's start a research on how to use Spring Security with JWT based authentication. The expected outcomes are:
1. A prototype of having a client-side middleware to inject the JWT into the request header.
2. A recommendation on which JWT library to use.

**Comment by platosha** [comment]
Spend some time prototyping a stateless Fusion application using JWT + Spring Security OAuth2.0 Resource Server as an alternative for sessions.

Prototype repository: https://github.com/platosha/stateless-app

There is no login form and no authorization endpoints yet.

In the absence of login form, the prototype’s endpoint simply client inserts a hard-coded JWT: https://github.com/platosha/stateless-app/blob/latest/frontend/connect-client.ts

Some notable things from the [security config](https://github.com/platosha/stateless-app/blob/latest/src/main/java/com/example/application/config/SecurityConfig.java):
  - It’s set to trust a hard-coded symmetric secret for token verification — seems to be the simplest way for demos and prototypes, without a configuring an oauth2.0 server / provider.
  - Fusion endpoints rely on `ROLE_` prefixed authorities, whereas the resource server by default decodes `scope` claims from JWT as `SCOPE_` authorities. A simple `JwtAuthenticationConverter` bean is provided in security config to workaround that.
  
Regarding obtaining JWT tokens in the client side, pretty much the only simple way is to configure Vaadin Login Form to use a custom endpoint that takes user credentials and returns a token. For generating a signed token, I’d suggest to use `nimbus-jose-jwt`, the same library that Spring Security uses.

As an alternative to a custom token endpoint, considered using [Spring Authorization Server](https://github.com/spring-projects-experimental/spring-authorization-server), but found that too complex. OAuth2.0 specifies using [Resource Owner Password Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.3), a way for trusted clients to obtain access / refresh tokens in exchange of user credentials. Unfortunately, the Spring Authorization Server (v0.1.0 atm) does not support this, which makes it hard to have a single application with it and a stateless resource server.

**Comment by haijian-vaadin** [comment]
We can close this ticket now, as the research is done and the result is shared in the comment.

**Comment by haijian-vaadin** [comment]
We can close again this ticket now, as we decided to go with the split cookie approach as described in the [design doc](https://docs.google.com/document/d/1jmIEHyijaP6wUAhOnTDmGSz3fWDUjKXC0cMIVZoSa2I/edit#heading=h.h7eezjets2ag)

**Comment by michael-newsrx** [comment]
Is there a working template project for oauth2 against Google/Github/Other with a Fusion app?
