### ISSUE TITLE
Upgrade to LitElement 2.5 once available

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#10826]
### Description of the bug / feature
Lit 2 contains one significant breaking change for users: `@internalProperty` is renamed to `@state`.
This has been backported to LitElement 2.5 so that this version contains both `@internalProperty` and `@state`.

We need to update from LitElement 2.4 to 2.5 as soon as it is available and replace all usages of `@internalProperty` with `@state`.

This update is needed for both V20 and V14.

This will enable e.g. start.vaadin.com to generate the same template for both Lit 1 and Lit 2 projects.

**Comment by pleku** [comment]
> This update is needed for both V20 and V14

Is it needed for v14 other than just to get people using the latest lit version and feature ? I don't think there is anything that relies on this in flow/designer, or is there ?

**Comment by Artur-** [comment]
It is primarily needed to be able to migrate to using `@state`, at least for new templates in places like start.vaadin.com. In the long run it reduces the migration burden to V21+ with Lit 2
