### ISSUE TITLE
Adding validators to a checkbox changes the bound value.

### ISSUE THREAD

**Issue by fgrazi** [vaadin/flow#10822]
I am using Vaadin 19.0.5

Here is a short example to reproduce the error:

    @Route("test")
    public class TestView extends VerticalLayout {
    
      TestView() {
        add(new Form());
      }
    
      class Form extends FormLayout {
        private FormData formData = new FormData();
        private Binder<FormData> binder = new Binder(FormData.class);
    
        Form() {
          Checkbox cb = new Checkbox("I agree");
          binder.setBean(formData);
          binder.forField(cb).asRequired().bind("agree");  // if asRequired() is removed it works!
          cb.addClickListener(event -> {
            new Notification("agree=" + formData.agree, 3000).open();
          });
          addFormItem(cb, "Agree?");
        }
    
    
        public class FormData {
          private boolean agree;
    
          public boolean isAgree() {
            return agree;
          }
    
          public void setAgree(boolean agree) {
            this.agree = agree;
          }
        }
      }
   
    
    }
    
As you can see from attached screenshot the value of formData.agree is 
always true. If you remove the asRequired() call it works. If you add a 
second validator (as in my actual code) then the problem is reversed
(always false), if this can help you to spot the issue (took me hours
to identify the issue).

![Peek 2021-04-24 13-01](https://user-images.githubusercontent.com/28322826/115956609-09eb5c00-a4fe-11eb-8044-96dd848fcbd4.gif)

**Comment by TatuLund** [comment]
Is this related to https://github.com/vaadin/vaadin-checkbox/issues/84

**Comment by fgrazi** [comment]
Not exactly. That was my impression at first (unhappily navigating Vaadin docs is difficult due to the many version differences). The other issues are about the fact check box was not a field so did not implement (time ago I believe) has value, no label and so on. I even found a work around embedding it in another composed field. But now it is a field and I would like to use it as that. What happens is that whenever the validator is  fired it changes value.

**Comment by Legioth** [comment]
Binder writes values to the bean (an instance of `FormData` instance) in this case only when validation passes, and validation passes only when the the checkbox is checked if it's marked as required.

If you want to access non-valid data, then you must read it directly from the field rather than reading it from the bean.

**Comment by miguelatvaadin** [comment]
Thanks for creating the issue, @fgrazi.

As @Legioth has pointed out, there is no bug here. @Legioth has also perfectly explained the way to proceed, in his comment.

I close the issue.

**Comment by Legioth** [comment]
It might argued that values should be written to the bean even if validation doesn't pass. This is not a good idea in the generic case since e.g. primitive field (e.g. `int`) cannot be assigned without exceptions if the value is `null`. There are also cases when invalid values cannot even be converted to the type that is expected by the bean.

There is however a recently introduced `writeBeanAsDraft` method in Binder that can be used to write out those bindings that can be written into a separate bean instance (i.e. not the same one that was passed to `setBean`). You need to explicitly invoke this method when appropriate, rather than having it invoked automatically for every change.

**Comment by fgrazi** [comment]
It is not a question of writing to the bean. The point is what does asRequired mean? I understand that asRequired means that the user provided a value, the value can be true or false but was provided, this is the checkbox was clicked. The same way a numeric field can have no value (blank) or have any numeric value. If I require a numeric field to be, say, 10, then I code the predicate value == 10 as validator. The same way I would expect value = true as a predicate to validate a boolean field, and not asRequired. Using asRequired to verify that the value is true, is confusing. Further useless because once set to true the user is unable to reset it and, if the checkbox is initialized with true, the user can't change it to false. I tried to use a Boolean (3 states checkbox) but I see it is not supported. Anyway once known is just a fact of not using asRequired on boolean fields.

**Comment by Legioth** [comment]
`asRequired` is about whether the field is "empty". It only matters _what_ the value is right now. It doesn't matter _how_ that value was set. A `TextField` that doesn't contain any text is empty regardless of whether it was originally in that state or if the user has removed the original value. A `TextField` that contains text is non-empty regardless of whether the text is the original value set from the server or a text that the user has entered.

A checkbox is empty when its visual representation doesn't contain the check symbol, i.e. when the value is `false`. The main use case where it makes sense from a UI design point of view to have a checkbox as required is for the case of accepting some terms and conditions. The interpretation that `true` passes `asRequired` does also make sense for this use case. It is required that the checkbox is in a checked state, regardless of how it ended up in that state.

If you want to have validation logic that doesn't care about the value of the checkbox but only whether the user has interacted with it, then you need to implement that manually by setting a flag the first time there is a user-originated value change event and using that flag for validation. You can also use `setIndeterminate(true)` on the checkbox but that will only affect the visual representation to let the user know that they haven't made a choice, but the value of the component will still be either true or false.

**Comment by fgrazi** [comment]
Now I understand: required means "visually filled" and not "value different from null". Still the fact that the validation message is not shown (who knows why?) complicates things because the user does not know what is wrong and why she is not allow to proceed.

**Comment by miguelatvaadin** [comment]
Hi @fgrazi,

thanks for your comment. There is already 1 open issue regarding the validation message/required indicator (https://github.com/vaadin/vaadin-checkbox/issues/84), if you want to follow it up.

Best regards,
