### ISSUE TITLE
Provide framework support for server-push to Fusion views

### ISSUE THREAD

**Issue by jtreml** [vaadin/flow#10839]
Provide simple out-of-the-box mechanism to notify client-side Typescript views of changes from the server-side.

The same way it is possible to update views from the server side e.g. when data changes or on a regular interval in Flow, there should be a native way of doing this for client-side views using Fusion.

There is a custom example by JC here which is surprisingly low-effort, but one single, native way, baked into the framework would be nice in the future.
https://github.com/jcgueriaud1/vaadin-fusion-mobx/blob/feature/push_sockjs/frontend/store.ts

**Comment by jcgueriaud1** [comment]
I'm closing this as duplicate in the fusion repository: https://github.com/vaadin/fusion/issues/56
