### ISSUE TITLE
Gradle plugin: support for "disable.automatic.servlet.registration" from maven plugin

### ISSUE THREAD

**Issue by d123456temp** [vaadin/flow#10844]
Vaadin gradle plugin: 20.0.0.alpha6

After building the Vaadin 19/20 webapp with gradle plugin and deploying it, the Vaadin servlet/filters are automatically registered at /* servlet path. This leads to a situation when I cannot deploy Vaadin app along non-Vaadin app/servlets within the same web application.

I guess this is what "disable.automatic.servlet.registration" option does in maven plugin. I cannot see any corresponding option fro gradle plugin.

**Comment by d123456temp** [comment]
Supporting question: in the meantime - is there currently any other way to prevent the automatic Vaadin servlets registration during startup?

**Comment by miguelatvaadin** [comment]
Hi @d123456temp ,

thanks for reporting this issue.

Please note that "disable.automatic.servlet.registration" is a system property, so it is not gradle/maven plugin related. Please also note that the "disable.automatic.servlet.registration" is for fully disabling the vaadin servlet registration, so your Vaadin app would not work unless you register the Vaadin servlet by yourself. 

According to the servlet specification, the Vaadin servlet registered at "/*" should not conflict with your non-Vaadin servlets as long as their url paths are more specific, so you should not be experiencing conflicts, indeed.

If you still want to avoid the "/*" servlet path, please follow the instructions from https://vaadin.com/docs/latest/flow/advanced/application-lifecycle/#automatic-servlet-registration. Basically, you only need to create your own servlet extending VaadinServlet and map it to whatever url you would like:

```java
@WebServlet(urlPatterns = "/vaadinOnly/*")
public class MyServlet extends VaadinServlet {
}
```

If you are using SpringBoot, you should follow the instructions from https://vaadin.com/docs/latest/flow/integrations/spring/spring-mvc#registering-the-vaadin-serlet.


Thanks and best regards,

**Comment by d123456temp** [comment]
@miguelatvaadin Thank you for you reply. I'm using plain Spring with web.xml (Servlet 2.5 compatible) setup...

That brings another question: is binding "MyServlet" from you example to /vaadinOnly/* suffiecient? Back in the time it was a hard-coded requirement that /VAADIN/* was also mapped to allow Vaading to serve resources.

so something like:

<servlet-mapping>
        <servlet-name>vaadinServlet</servlet-name>
        <url-pattern>/vaadinOnly/*</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
    <servlet-name>vaadinServlet</servlet-name>
        <url-pattern>/VAADIN/*</url-pattern>
    </servlet-mapping>

Is it no longer the case?
 
BTW binding /* is a no-go as I have a heavy public traffic going through /* which I don't want to spawn Vaadin-related resources for.

**Comment by miguelatvaadin** [comment]
Hi @d123456temp ,

as far as I know mapping to `/vaadinOnly/*` should be enough. No `/VAADIN/*` mapping is required now.
