### ISSUE TITLE
Use pretty compiled client engine for development time with assertions enabled

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#1086]
`When developing using Flow and something goes wrong I want to have a pretty compiled client engine version with assertions enabled so that I can either figure out what is wrong or create a sensible issue about the problem`

**Comment by heruan** [comment]
Could enabling source-maps in the client engine be a solution for this?

**Comment by Legioth** [comment]
I don't think the GWT compiler supports source maps for regular compiles, but only for Super Dev Mode?

**Comment by heruan** [comment]
I'm finding references of GWT source-maps only in SuperDevMode indeed, but I've tried to add

```xml
<set-property name="compiler.useSourceMaps" value="true"/>
```

in `ClientEngineXSI.gwt.xml` and source-maps *are* generated also for regular compiles… but unfortunately the browser doesn't pick them up.

**Comment by pleku** [comment]
Our own `ClientEngineLinker` specifically doesn't support source maps & SDM, that is why we have setup the `CrossSiteIframeLinker` to be used when you want to want SDM.

I'm not sure if we want to make the development time client engine compiled with a different linker than what will be used in production mode, compared to just having pretty and maybe assertions enabled. Or maybe that could be the third one, so we have one for production, one for development, and one for debugging with SDM...

Currently there is no timeline for this anyway.

**Comment by Legioth** [comment]
One example that allegedly has working source maps without SDM can be seen in https://gwt.googlesource.com/gwt-site-webapp/+/master/src/main/java/com/google/gwt/site/webapp/GWTProject.gwt.xml#12. I don't know whether the difference comes from our no-standard linker or from the extra `includeSourceMapUrl` property that is also set in that case.

**Comment by pleku** [comment]
Superseded by #11120
