### ISSUE TITLE
Update all the starters to use Lit 2.0 in package.json and lock files

### ISSUE THREAD

**Issue by taefi** [vaadin/flow#10873]
Update the Lit version to `2.0` (newest version available at the moment) in package.json and lock files. This should happen after the Lit version updated on the flow side (#10023).

**Comment by Artur-** [comment]
Won't this happen automatically as soon as `21.0.0.alpha1` is taken into use?

**Comment by pleku** [comment]
> Won't this happen automatically as soon as 21.0.0.alpha1 is taken into use?

Yes the version update will be noticed and necessary files are regenerated.
