### ISSUE TITLE
Update Flow html templates to use Lit 2.0.0-rc.1 in start.vaadin.com 

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#10871]
Update Flow html templates to use Lit version `2.0.0-rc.1` in https://github.com/vaadin/start after Lit version will be updated on the flow side https://github.com/vaadin/flow/pull/10023.

Fusion views are out of scope of this ticket.

**Comment by Artur-** [comment]
This has quite a few dependencies on the Start side as the same templates are shared for many Vaadin versions and for the preview of the application itself

**Comment by pleku** [comment]
And apparently the idea is to first update the templates to use lit-template 2.5 & lit-html 1.4 first and then after that (?) update to lit 2.0 at some point.

**Comment by caalador** [comment]
Closing as outdated as start is using lit 2.0.0
