### ISSUE TITLE
Autogeneration of package.json is not compatible with the new theme structure

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#10972]
### Description of the bug / feature

Vaadin automatically creates front-end files like package.json if not present. This has been possible and become a de-facto way to use Vaadin in the past and many Vaadin developers have package.json on their gitignore as well. Now if one is using the new theme system (now introduced also to 14.6), things will not work, something in package.json file don't re-appear properly.

The issue will also be present when upgrading from older versions and starting to use the new theme mechanism.

### Minimal reproducible example

1. Check out a simple project from start.vaadin.com
2. "Do the Vaadin dance" aka remove all front-end build related files from the top level (package.json etc)
3. Start the application (either from CLI using mvn spring-boot:run or from IDE)

### Expected behavior

Application starts properly with the theme

### Actual behavior

Errors on the console and in browser

### Versions:
    - Vaadin / Flow version: 14.6.0

**Comment by caalador** [comment]
This is basically a start.vaadin.com java only project problem as it adds a npm package only through package.json instead of having also the `@NpmPackage` in the project.

I would see this approach as ok if you have a fusion or hybrid application, but if you get a Java only it's a bit unexpected.

Any automatic Vaadin cleanup (gradle plugin at least has a defined cleanTask) never removes package.json nor webpack.config.js as those are files that can contain user made changes and additions.

**Comment by jcgueriaud1** [comment]
This is related: https://github.com/vaadin/start/issues/1205

**Comment by pleku** [comment]
Like repeated elsewhere - this has nothing to do with the new theming system. For the new theming system, it is even documented that if you add npm dependencies, you need to include the `@NpmPackage` annotation. https://vaadin.com/docs/v14/flow/styling/custom-theme-configuration/#stylesheets

Not sure what we could do to a copy-paste error like this. I would imagine that people who install dependencies directly to thein package.json via npm/pnpm will not delete the file. And those who are deleting it, even when they should not, probably add all dependencies with the `@NpmPackage` annotation.

**Comment by mstahv** [comment]
Oh, I spent quite a while yesterday to find this from the documentation. Maybe it should be somewhere else. As already the "Creating custom theme" part talks about Lumo, I think it should be highlighted with example already there.

People be copy pasting things from our demos, which is another reason the getting started part in documentation is not very helpful. I don't want to read the whole documentation just to make my app look similar to the app as we create using start.vaadin.com.

**Comment by mstahv** [comment]
But yeah, I'd add the annotation to our start.vaadin.com template anyways, or make our package.json autogeneration to always include relevant lumo dependencies.

**Comment by mstahv** [comment]
@mvysny was also suggesting to include lumo by default, when recreating the package.json. Would there be a big performance penalty 🤔

**Comment by caalador** [comment]
But what is even `lumo-css-framework` as I for instance have not heard about it before nor can I find any information for it by doing a google search

**Comment by mstahv** [comment]
Yup, throwing in @jouni and @rolfsmeds also to the discussion.

We should probably pull in that to the core or stop using that in the start.vaadin.com. I heard it wasn't used there before (but similar rules were hard coded to the project template).

**Comment by mvysny** [comment]
Even less documentation here: https://www.npmjs.com/package/lumo-css-framework

**Comment by knoobie** [comment]
Wasn't it planned as feature in V21? https://github.com/vaadin/platform/issues/2029

It was created / published here: https://github.com/vaadin/vaadin-lumo-styles/pull/103#issuecomment-783669362

**Comment by caalador** [comment]
This makes it even more of a question that why are we using a non supported volatile package in the LTS starter for a "feature" that is coming for V21.

**Comment by pleku** [comment]
As there have not been any further updates for this, closing it as invalid.

The `package.json` file should not be deleted in projects as then this issue can occur with any project that has added dependency directly to it, as maybe done by following instructions from anywhere on the interwebs for npm/pnpm.
