### ISSUE TITLE
In client-side bootstrapping mode with eagerServerLoad, initial UIDL always renders home page

### ISSUE THREAD

**Issue by platosha** [vaadin/flow#10981]
Steps to reproduce:

- Make an application with client-side bootstrapping mode and `eagerServerLoad` enabled
- Add Flow view mapped to some path, e. g., `@Route("foo") FooView`
- Add a Fusion client-side view 
- Start the application
- Navigate to the view by opening the URL directly, e. g., `http://localhost:8080/foo`

Expected behavior:
- `200 OK` response
- The UIDL containing the view
- Only one navigation roundtrip to the server

Actual behavior:
- The response is `404 Not Found`, despite the view is shown
- The initial UIDL response is related to empty path ("") instead of the FooView
- Second roundtrip from the client-side router to render the "foo" view

**Comment by haijian-vaadin** [comment]
close as duplicates to https://github.com/vaadin/flow/issues/11036
