### ISSUE TITLE
Unable to login when app is using non-default servlet context

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#10997]
Steps to reproduce:
1. Create SVC project
2. Follow https://vaadin.com/docs/latest/fusion/security/spring-login docs
3. Set `server.servlet.context-path` to `/fusion`.
4. Start the application and navigate to `http://localhost:8080/fusion/login`
5. Login

Expected behaviour:
- You are logged in

Actual behaviour:
- You are not logged in; clicking "login" makes a call to `http://localhost:8080/login` which returns 404.

**Comment by haijian-vaadin** [comment]
For this issue, I think it would work if a `loginProcessingUrl` is configured as `fusion/login` for the `login()` helper method as an optional parameter. We could mention this in the doc.

**Comment by fluorumlabs** [comment]
Does this mean that I would need to explicitly specify `loginProcessingUrl` if I plan to deploy WAR to a container? (Or did I understood the whole servlet context path thingie wrong?). How would that work if I want to develop an app in an embedded tomcat locally, but deploy it as a WAR?

**Comment by Artur-** [comment]
Sounds reasonable to think that the login protects the web app and not only a specific servlet inside it. You are basically telling that the login page is at `/login` and then you are not serving a login page at `/login`?

**Comment by fluorumlabs** [comment]
When you do `setLoginView("/login")` and your servlet context is, let's say, `/zzz`, Spring Security will redirect to `/zzz/login` for you, not `/login`

**Comment by fluorumlabs** [comment]
Can confirm that `loginProcessingUrl` works, but still not clear what should be done if the intention is to run application under different servlet contexts (or when you don't have control over servlet context path or otherwise don't know it in advance). Potential use case: company develops software that can be downloaded by its customers as a WAR.

**Comment by haijian-vaadin** [comment]
For that case, I think we cause set the `loginProcessingUrl` to `login` instead of `/fusion/login`, which should work.

**Comment by haijian-vaadin** [comment]
Now I think it's a mistake to `/login` as the default login processing URL, should change to `login`, then this issue would be fixed automatically.
