### ISSUE TITLE
BeforeEnterEvent.forwardTo(String) should forward to the given URL

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#11029]
### Description of the bug / feature
With this before enter event handler
```
@Route(value = "hello")
public class HelloWorldView extends HorizontalLayout implements BeforeEnterObserver {

    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        event.forwardTo("/hello/world/");
    }
```
and a servlet deployed using context path `/context`

You would expect that opening `/context/hello` would redirect to `/hello/world/`. Instead it redirects to `/context/hello/world`.

The  URL is wrong (relative to `/context`) and the trailing slash is missing.

### Minimal reproducible example
```
git clone https://github.com/Artur-/test-forward-to-url
cd test-forward-to-url
open http://localhost:8080/context/hello
```

### Expected behavior
http://localhost:8080/hello/world/ is shown

### Actual behavior
http://localhost:8080/context/hello/world is shown

### Versions:
    - Vaadin / Flow version: 19
    - Java version: 15

**Comment by fluorumlabs** [comment]
`forwardTo` accepts Flow route as an input, not arbitrary URL.

**Comment by Artur-** [comment]
That is true for Vaadin 14 but Vaadin 19 forwards to the given URL also if it cannot find a corresponding Flow view

**Comment by knoobie** [comment]
I would expect in both cases (v14 / v19) `contextPath` to be prefixed, or should it only be added if `./` is used? 

This the developer be aware of the possible `contextPath` and has to add it himself? Seems more like a problem / bug to me

**Comment by Artur-** [comment]
As the `base` path is set for the app you can always redirect to `my-view` and it will go to `my-view` prefixed with the context path if I understand it correctly

**Comment by pleku** [comment]
Maybe I'm missing something - but it looks to me that the existing `forwardTo` API in `BeforeEvent` is either
- for Flow based routes or paths to the routes
- for `NavigationState` which I think should not be even visible for users (?)

Now it should instead redirect to an URL outside the application ? Why not add `forwardToUrl(String url)` instead ?
Basically like requested in https://github.com/vaadin/flow/issues/4606 but since `redirectTo` is not intended to update the URL, it should not be `redirectTo` but `forwardTo` instead. I don't think it is possible to redirect without changing the url so the other issue is kind of invalid in that regard.

**Comment by Artur-** [comment]
Based on the code and commits I would interpret it as `forwardTo` is for navigating to either a server or client side view. In that case (and to prevent breaking compatibility) a `forwardToUrl` would make more sense. 

The use case here is to be able to prevent navigation to a given view and redirect to a (maybe external) login view instead.

**Comment by pleku** [comment]
Yeah, also from #9386 which I earlier marked as duplicate for #4606: 
> My use case is that I am controlling access via an BeforeEnterListener. When authentication is required I need to redirect to an external URL (web-based SSO). I can use Page#setLocation(...) but that won't stop the original target from being shown before navigating to the new URL. So I have to reroute to what is essentially a dummy view.
While my use case specifically would also be satisfied by #4606, it just seemed like a reasonal expectation to me that a reroute target wouldn't need to have a registered route, as its path is never shown.

Which I interpret as the same use case (as you have) and is simply trying to work around that by having a dummy route to navigate to.

Backwards compatibility is very nice indeed and thus if any of the existing `forwardTo` methods work unexpectedly in certain cases, I would rather deprecate those and create new variants to _suit that specific use case_.

So unless there are some objections - the new API could resolve this and #4606 ? There is requests for query parameters there but I think that can be handled separately in https://github.com/vaadin/flow/issues/7680. https://github.com/vaadin/flow/issues/8712 is about Flow route path parameters, which is already done (closing it).
