### ISSUE TITLE
Not possible to extend AbstractRouteRegistry from Vaadin 14.5 onwards

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow#11022]
If you want to implement your own routing, one needs to have CustomRouteRegistry extending AbstractRouteRegistry. 

In Vaadin 14.5 and newer versions this will require implementing

public NavigationRouteTarget getNavigationRouteTarget ( String url )
public RouteTarget getRouteTarget ( Class<? extends Component> target, RouteParameters parameters ) 

This will not be straightforward because NavigationRouteTarget does not have a public constructor.

**Comment by pleku** [comment]
I don't think we've documented it as a feature to have your own route registry, but as it has been possible before Vaadin 14.5, it should be possible to do so later on too. And apparently fixing this should not be an issue. A test needs to be added though to prevent future regressions.
