### ISSUE TITLE
Security annotations are not checked on parent layouts

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#11044]
Implementation in #10609 doesn't take into account parent layouts (either prefixed or not). 

Use case:
```java
@SecuredByRole({"ADMIN", "SUPER_ADMIN"}) 
@RoutePrefix("admin") 
public class AdminView implements RouterLayout {}

@RoutePrefix("users") 
@ParentLayout(AdminView.class) 
public class UsersView implements RouterLayout {}

@SecuredByRole("SUPER_ADMIN") 
@Route(value = "delete", layout = UsersView.class) 
public class BanView {}
```

This comes from the fact, that for nested routes `BeforeEnterListener` is called only once

**Comment by pleku** [comment]
While the "use case" code seems very artificial, I would still expect that to open any subview inside a router layout, the roles from the router layout need to be applied too. If we only make the roles to be applied when the component is used as a `@Route` but not when used as a router layout, it would be a bit confusing.

**Comment by fluorumlabs** [comment]
Yes, sorry for the confusing example...

**Comment by pleku** [comment]
@Artur- @taefi what are your thoughts on this ? I don't think at least the exact same issue is present with fusion end-points. Not sure if there are any other examples of similar situations with "nested view hierarchies" for view-based access control.

**Comment by Artur-** [comment]
Sounds like we should fix this and also #10705

**Comment by Artur-** [comment]
Just to be clear, we are saying that you need to have access to all views in the view chain for anything to be rendered?

**Comment by fluorumlabs** [comment]
> Just to be clear, we are saying that you need to have access to all views in the view chain for anything to be rendered?

Yes IMO

**Comment by taefi** [comment]
Using the latest SNAPSHOTs of Flow 8.0 and Vaadin-Spring 18.0, I created an example project, with this setup for the views: 
```
public class MainView extends AppLayout { ... }

@RoutePrefix("employment-wizard")
@ParentLayout(MainView.class)
@Route(value = "start-employment", layout = MainView.class)
@AnonymousAllowed
public class WizardView extends VerticalLayout implements RouterLayout { ... }

@Route(value = "person-step", layout = WizardView.class)
@PageTitle("Person Form")
@RolesAllowed("ADMIN")
public class PersonFormView extends Div { ... }

@Route(value = "experience-step", layout = WizardView.class)
@PageTitle("Experience Form")
@PermitAll
public class ExperienceFormView extends Div { ... }
``` 
And it is working as expected, this means that you can navigate to the parent layout (WizardView) without logging in, and then by navigation through the menu or simply entering the route in the browser's address bar to the wizard step routes (PersonFormView and ExperienceFormView), the user would be redirected to Login correctly. 

Then I changed the security access annotation in this way: 
```
public class MainView extends AppLayout { ... }

@RoutePrefix("employment-wizard")
@ParentLayout(MainView.class)
@Route(value = "start-employment", layout = MainView.class)
@PermitAll
public class WizardView extends VerticalLayout implements RouterLayout { ... }

@Route(value = "person-step", layout = WizardView.class)
@PageTitle("Person Form")
@AnonymousAllowed
public class PersonFormView extends Div { ... }

@Route(value = "experience-step", layout = WizardView.class)
@PageTitle("Experience Form")
@AnonymousAllowed
public class ExperienceFormView extends Div { ... }
```
And even by directly entering the routes like `http://localhost:8080/employment-wizard/experience-step` that is annotated with `@AnonymousAllowed`, the user would be redirected to the login, since the parent layout needs an authenticated user. 

As I'm not a Routing champion, can somebody elaborate more on what is the problem that should be addressed here? 
Is it only about annotating an Abstract View class, or is there something else?

**Comment by fluorumlabs** [comment]
@taefi Do you happen to have a "cloneable" project for this?

**Comment by taefi** [comment]
@fluorumlabs  Yeah why not, made it available here: https://github.com/taefi/test-view-access-ctrl

Though, there so much unrelated stuff from an existing project downloaded from start.vaadin.com, I'm sure you can find the related views under `com.example.application.views.employmentwizard` package easily. 
Please let me know which parts I'm missing since I'm new to this.

**Comment by fluorumlabs** [comment]
I took the example code from https://github.com/taefi/test-view-access-ctrl and I added `createTab("Person Step", PersonFormView.class),` to the `MainView`.

With this setup we have `/employment-wizard/` (parent) with `@PermitAll` and `/employment-wizard/person-step` with `@AnonymousAllowed`.

Now, if you navigate to `/employment-wizard/person-step` in your browser you'll see LoginView, because `/employment-wizard` is not public path. However, if you click "Person Step" in the sidebar, person form will be displayed, even though it's parent layout requires authorization.

For additional insights you can place breakpoint in `com.vaadin.flow.server.auth.ViewAccessChecker#beforeEnter` and observe, that it is called only once per navigation and `beforeEnterEvent.getNavigationTarget();` returns `PersonForm.class`.

**Comment by taefi** [comment]
I'm not sure, but is this usecase really happening? Even my example, with a restricted parent layout and an anonymously allowed child form, seems a little artificial for me. 

I know that in theory, this would make `PersonFormView` reusable, but not sure how much this is really happening in practice. But, thanks for providing the example, I'll look into it.

**Comment by fluorumlabs** [comment]
You can remove `@AnonymousAllowed` and get more realistic example where developer expects that placing security annotation on parent layout will automatically protect all subviews

**Comment by fluorumlabs** [comment]
> The problem is that the default is "deny all" so it means that if you do not annotate your layout, all access will be denied

This is just hides the issue and will be true only until developer implements his own `CustomViewAccessChecker extends ViewAccessChecker` with different `AnnotationAccessChecker` implementation (say, with different defaults) (and nothing prevents him from doing so, right?)

**Comment by taefi** [comment]
When we have the `layouts` in the `BeforeEnterEvent` what stops us checking the view access annotations for all the layouts in `ViewAccessChecker::beforeEnter`?

**Comment by Artur-** [comment]
What I meant with the problem is that it is far from obvious that you need to allow access to a layout, which is what the "parent layout" really is. I am not really convinced anymore we should do this as in most cases it just means that you need to add more code to accomplish what you want.

**Comment by fluorumlabs** [comment]
Quick survey revealed that 70+% of developers would place security annotation on a parent layout when in doubt.

**Comment by taefi** [comment]
If we check the access to all the layout chains in the `ViewAccessChecker::beforeEnter`, it would solve the problem at the price of forcing users to put one of the access annotations, most probably `@AnonymousAllowed` on the application layout class (MainLayout). 

Now that there is a PR for the related issue #10705, that adds the capability of checking access annotations not only on the View class but also on its superclasses, I suggest reevaluation of adding of above fix.

**Comment by fluorumlabs** [comment]
Consider the example from https://github.com/vaadin/flow/issues/11044#issuecomment-848217545

```java
@RoutePrefix("employment-wizard")
@ParentLayout(MainView.class)
@Route(value = "start-employment", layout = MainView.class)
@PermitAll
public class WizardView extends VerticalLayout implements RouterLayout { ... }

@Route(value = "person-step", layout = WizardView.class)
@PageTitle("Person Form")
@AnonymousAllowed
public class PersonFormView extends Div { ... }
```

We imply (even though it's not stated anywhere) that annotating view with security annotations will prevent the view from instantiation if the user has no access permissions. From that point of view it would be really weird and non-obvious that `WizardView` (laylot) is accessible, depending on how it's accessed: 
- If unauthenticated user navigates to `/employment-wizard/start-employment` the `WizardView` won't be instantiated and a login screen will be presented (`@PermitAll` works)
- If unauthenticated user navigates to `/employment-wizard/person-step`, the `WizardView` will be instantiated (as a parent of `PersonFormView`, even though it has `@PermitAll` annotation in place.

**Comment by pleku** [comment]
In short: **view-based access control is checked from the view class (marked with `@Route`) or its parent class. But not from any parent layouts.**

Based on internal discussions, we've decided against this. The Flow views, the access control annotations are checked from the class, and then its parent class(es). We want to keep it simple and not bring parent **layouts** to the picture as it would make things much more complex as you would have to check both parent classes and layouts to determine what is applied.
