### ISSUE TITLE
`StaticFileServer` dumps file listing when directory is accessed and application is running in (at least) Tomcat

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#11047]
Steps to reproduce:

Development mode:
1. Create SVC project
2. Run it
3. Open `http://localhost:8080/frontend/.;` in browser
4. Observe list of files

Production mode:
1. Open `https://start.vaadin.com/frontend/.;` in browser
2. Observe list of files

**Comment by miguelatvaadin** [comment]
Hi @fluorumlabs ,

coudl you please provide versions?

Thanks

**Comment by miguelatvaadin** [comment]
ok. Thanks, @fluorumlabs

**Comment by caalador** [comment]
I couldn't replicate this running `skeleton-starter-flow`, but it does happen with the spring-boot based starter `skeleton-starter-flow-spring`

**Comment by fluorumlabs** [comment]
As far as I remember, `skeleton-starter-flow` use jetty

**Comment by caalador** [comment]
Deploying the starter war to tomcat 9.0.39 I only get the result `Could not navigate to 'frontend/.;'`

**Comment by fluorumlabs** [comment]
Same behavior can be observed with `/VAADIN/static/.;`

Not sure how `labs.vaadin.com` is configured, but probing two apps there works just "fine":
`https://labs.vaadin.com/edit-multiple/.;`, `https://labs.vaadin.com/theme-example/.;`

**Comment by caalador** [comment]
That is the same it can only be done on a spring-boot project as far as I can find.
You can even start from `start.vaadin.com/.;` and continue from there with adding folders that you see.

**Comment by fluorumlabs** [comment]
Seems it is Spring boot specific. However, my observations/debugging shown that the actual file list is served by StaticFileServer. In fact, this is the default behavior of FileInputStream when File points to a directory

**Comment by caalador** [comment]
Would seem so. Getting a Spring project to break on break points seems like a game of luck at times.
In the spring-skeleton `request.getPathInfo()` returns `/.` for `/.;` and we only check for `endsWith("/")` to determine a directory

**Comment by fluorumlabs** [comment]
`getPathInfo()` simply strips path parameters in Tomcat (the ones starting with `;`), I add `;` simply to prevent web browser from normalizing URL. The same effect can be achieved with `curl https://labs.vaadin.com/edit-multiple/. --path-as-is`

**Comment by fluorumlabs** [comment]
Regarding checking if path points to a directory or not -- all these URLs point to the same directory:
- `https://labs.vaadin.com/edit-multiple/frontend/.`
- `https://labs.vaadin.com/edit-multiple/frontend/form/..`
- `https://labs.vaadin.com/edit-multiple/frontend`

The point is: just testing for `.` or `..` is not enough (even though it will prevent from listing the root)
