### ISSUE TITLE
Flow build fails because of missing jbrotli-0.5.0

### ISSUE THREAD

**Issue by TobseF** [vaadin/flow#11098]
I try to build Vaadin flow client lib version `2.4.6`. I build it by my own, because I want to get a PRETTY printed JS files, so I can get readable stacktraces on JS exceptions.

### Setup
Run `mvn clean install` on Flow branch `2.4`. (executed in the root dir)

The first problem is, that you will get a 
```error
ReflectTools.java:[115,18] cannot access com.sun.beans.introspect.PropertyInfo
```
But this can be fixed by [this patch](https://github.com/vaadin/flow/pull/10497/commits/19e858cf29edac5230c89db0ecc6f9b707fe1d53).

The seconds problem (which is relegated to this issue) is the missing `jbrotli` dependency.
```java
[ERROR] Failed to execute goal com.github.ryanholdren:resourcecompressor:2017-06-24:compress (default) on project flow-client: 
Execution default of goal com.github.ryanholdren:resourcecompressor:2017-06-24:compress failed: 
Plugin com.github.ryanholdren:resourcecompressor:2017-06-24 
or one of its dependencies could not be resolved: Failed to collect dependencies at com.github.ryanholdren:resourcecompressor:jar:2017-06-24 -> 
org.meteogroup.jbrotli:jbrotli:jar:0.5.0: 
Failed to read artifact descriptor for org.meteogroup.jbrotli:jbrotli:jar:0.5.0: 
Could not transfer artifact org.meteogroup.jbrotli:jbrotli:pom:0.5.0 from /to 
bintray-nitram509-jbrotli (http://dl.bintray.com/nitram509/jbrotli): 
Authorization failed for http://dl.bintray.com/nitram509/jbrotli/org/meteogroup/jbrotli/jbrotli/0.5.0/jbrotli-0.5.0.pom 403 Forbidden -> [Help 1]
```
Indeed the dependency  
http://dl.bintray.com/nitram509/jbrotli/org/meteogroup/jbrotli/jbrotli/0.5.0/jbrotli-0.5.0.pom  
is not accessible (Forbidden!) and not hosted [anywhere else](https://github.com/tipsy/javalin/issues/674).

The mentioned `resourcecompressor` is a build plugin in the `flow-client` module with the sate of the art version `2017-06-24`:

```xml
<plugin>
    <groupId>com.github.ryanholdren</groupId>
    <artifactId>resourcecompressor</artifactId>
    <version>2017-06-24</version>
    <executions>
        <execution>
            <goals>
                <goal>compress</goal>
            </goals>
            <phase>prepare-package</phase>
            <configuration>
                <directory>${gwt.module.output}/client/</directory>
            </configuration>
        </execution>
    </executions>
</plugin>
```

### Expected behavior
Like mentioned in the README the `mvn install` should just build the whole project.

### Versions:
   *  Flow version: 2.4.6
   * Java version: 11.0.11
   * OS version: Win 10 x64
   * IDE: IntelliJ 2021.1.1 (of course)
     The mvn build was started in the terminal, not with the IDE.

I also tried to [download](https://github.com/MeteoGroup/jbrotli/releases/tag/v0.5.0) and build this fantastic jbrotli by my own. But unfortunately this includes native libs (for a simple compression algo), and this seems to be even more difficult to build, than flow.

**Comment by knoobie** [comment]
This probably happened because the bintray service was discontinued on 01.05.2021 - https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/.

**Comment by pleku** [comment]
As the Flow version 2.4 is not supported anymore, I'm going to close this as won't fix. We're not working on branches and versions that are not supported anymore - we have enough work on maintaining the branches that build the supported versions.

I'd just recommend switching the latest LTS Flow version, which in this case would be 2.6.1 or even building a snapshot on top of branch `2.6`. 2.6.2 is out soon.

In case you absolutely would need to build a custom 2.4 version, you can contact the support team for help to setup the Jbrotli for the build.

**Comment by TobseF** [comment]
Indeed... It was possible to  do an upgrade, so closing this issue is OK fur us. But as a dev it's hard to accept this world, where only 4 months after a **release** nobody is able to rebuild this artifact. And the reason for that is, that this artifact was build on top of an outdated dependency that no one updated [since five years](https://github.com/MeteoGroup/jbrotli/releases/tag/v0.5.0) and which just disappeared. That makes me sleeping bad and gives me nightmares, about the other things, which are hidden in the deep water of the Vaadin dependency sea.

![](https://imgs.xkcd.com/comics/dependency.png)
