### ISSUE TITLE
Investigate quarkus

### ISSUE THREAD

**Issue by miguelatvaadin** [vaadin/flow#11111]
Besides reviewing Martin's work / as a previous step to review it, we need to: 

- Refresh/step up Quarkus knowledge
- Dig into Quarkus extensions building

Sources:

- quarkus doc
- articles
- videos

**Comment by pleku** [comment]
Analysis and findings docs: 
https://docs.google.com/document/d/1Zh0T8__gCAWlPhAnW1rtFb4uXNftwyMFd9HPeDtBd9o/edit#
https://docs.google.com/document/d/1skqYgy22UYIdftd71dXCXbb6lD5twLXs8ADk3XiBSlo/edit

Further investigation topics will be covered in individual issues.
