### ISSUE TITLE
Packaging fails with Java 16

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/flow#11136]
### Description of the bug / feature
Maven archetype-generated projects for 14.6.1 and 20.0.0 fail to complete `mvn package` successfully when Java 16 is used. The issue doesn't occur with Java 11 at least. 

### Minimal reproducible example
1. Generate a Vaadin project 
```
mvn -B archetype:generate \
                -DarchetypeGroupId=com.vaadin \
                -DarchetypeArtifactId=vaadin-archetype-application \
                -DarchetypeVersion=20.0.0\
                -DgroupId=org.test \
                -DartifactId=vaadin-app \
                -Dversion=1.0-SNAPSHOT
```

2. CD to the generated project directory and run `mvn package`

### Expected behavior
Packaging completes successfully

### Actual behavior
I get a Failed to execute goal `org.apache.maven.plugins:maven-war-plugin:2.2:war` error that is caused by `java.lang.ExceptionInInitializerError: Cannot access defaults field of Properties`

### Versions:
    - Vaadin / Flow version: 14.6.1 and 20.0.0
    - Java version: 16 (Amazon Corretto)
    - OS version: Windows 10

**Comment by caalador** [comment]
Try using a newer maven-war-plugin the version 2.2 is 9 years old.
Test using 
```

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.3.1</version>
            </plugin>
```
And we'll try to update it to the generated archetype

**Comment by tarekoraby** [comment]
The newer version solves the issue. 

> And we'll try to update it to the generated archetype

Thanks!
