### ISSUE TITLE
Update tsconfig.json target field to ES2020

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow#11145]
### Description of the bug / feature

Originally reported at https://github.com/vaadin/web-components/issues/2077

Previously we upgraded to `es2019` (https://github.com/vaadin/flow/pull/10891) but apparently we actually need `es2020`.
Note, ES2020 is supported by Safari 14 which is the version we aim to support in Vaadin 21.

### Suggested change

Update `target` in all of these `tsconfig.json` files to `2020`.

This covers some proposals we'd like to use in web components:

- [optional chaining (`?.`)](https://caniuse.com/mdn-javascript_operators_optional_chaining)
- [nullish coalescing (`??`)](https://caniuse.com/mdn-javascript_operators_nullish_coalescing)

### Expected behavior

The `target` field in the `tsconfig.json` files used / created by Flow should be set to `es2020`

### Actual behavior

The `target`field in the `tsconfig.json` files used / created by Flow is set to `es2019`.

### Versions

- Vaadin / Flow version: 21.0

**Comment by Artur-** [comment]
Lit 2 decided against es2020 for now. Maybe we should do the same: https://github.com/lit/lit/issues/1589

**Comment by web-padawan** [comment]
Thanks, I think it makes sense to close this issue for now, as we need the syntax to be compatible with webpack 4.
