### ISSUE TITLE
Using parent theme from jar dependency in development mode fails build.

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#11152]
Running a project in development mode with an external parent theme fails the webpack build with:
```
[ForkJoinPool.commonPool-worker-9] INFO com.vaadin.base.devserver.DevModeHandlerImpl - Running webpack to compile frontend resources. This may take a moment, please stand by...
C:\Users\mikae\Code\flow\flow-tests\test-application-theme\test-reusable-as-parent\target\plugins\application-theme-plugin\theme-handle.js:225
          throw new Error("Could not locate files for defined parent theme '" + themeProperties.parent + "'.\n" +
          ^

Error: Could not locate files for defined parent theme 'reusable-theme'.
Please verify that dependency is added or theme folder exists.
    at C:\Users\mikae\Code\flow\flow-tests\test-application-theme\test-reusable-as-parent\target\plugins\application-theme-plugin\theme-handle.js:225:17
```
as the folder the parent theme is copied to is in target which is not watched.

To test the issue run `flow-tests\test-application-theme\test-reusable-as-parent` in development mode by adding the `vaadin-dev-server` dependency and setting the plugin to only run `prepare-frontend`. then start project with `mvn package jetty:run`

This is a regression from #10834

**Comment by rolfsmeds** [comment]
This makes it virtually impossible to use custom themes with app projects generated with Start, as those contain their own themes that supply the required css, so you can't just replace that with an external theme without first copying all the bunded css to that custom theme (and without that bundled css the views based on Start templates don't work properly).

The same problem applies to Publisher, as the Vaadin project that is used for the docs also has its own theme supplying various examples with the css they need.

**Comment by jouni** [comment]
We have a design system customer case that will be partially blocked/handicapped by this issue.
