### ISSUE TITLE
when building gradle plugin, gradle daemon remains running

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#11159]
### How to reproduce
```
$ ps -ea | grep gradle
(no output)
$ mvn clean package -pl flow-plugins/flow-gradle-plugin
...
BUILD SUCCESS
...
$ ps -ea | grep gradle
.../java .... org.gradle.launcher.daemon.bootstrap.GradleDaemon  ... 
```

### What's the issue
The problem leaving orphan gradle daemon is that they are running the original JVM version, and it might happen that we need to change the JDK, then build will fail with the error:
```
java.lang.IllegalArgumentException: Supplied javaHome must be a valid directory. ... 
```
The problem is worst in CI, because agents remain unusable for future gradle tasks

### Workaround
Stop the daemon before running a new build
```
 ./flow-plugins/flow-gradle-plugin/gradlew --stop
```

**Comment by pleku** [comment]
Wonder if https://github.com/vaadin/flow/pull/10583 would be enough to just disable it ? @taefi ?

**Comment by taefi** [comment]
> Wonder if #10583 would be enough to just disable it? @taefi ?

I made it based on the gradle documentations, so it should work. But IIRC just before we could have a validation build for #10583, @caalador disabled the execution of Gradle tests in the validation build configuration. So at that time, I closed it, but at least trying it would cause no harm, I believe.

**Comment by manolo** [comment]
Ok, thanks for the info, I've opened a task for the releases team to enable those tests without impacting flow build times.
https://github.com/vaadin/components-team-tasks/issues/587 
I'll test #10583  in platform build since it already has enabled validation

**Comment by manolo** [comment]
Added the [validation build](https://teamcity.vaadin.com/buildConfiguration/Flow_FlowPullRequestsRunGradleTests?buildTypeTab=overview&mode=builds#all-projects) in CI
