### ISSUE TITLE
Allow disabling serialization of VaadinSession and disable it by default

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#11151]
### Description of the feature
When you are using authentication in your application, the authentication information is by default stored in the HTTP session. If you use Spring dev tools during development then one every Java change, the server will be restarted. When this happens, the session is serialized and then deserialized again. If the whole application is serializable, the session will be retained and you will stay logged in. However, in most cases the Flow application is not serializable as you can very easily create code that causes serialization of the component tree to fail. When serialization of the Flow application fails, the authentication info will not be serialized either but instead the whole session will be thrown away.

### Actual behavior
The development workflow is
1. Start app
2. Login and navigate to the view you want to modify
3. Make code changes
4. Auto reload kicks in
5. Login and navigate to the view
6. Check if you did the correct changes

### Expected behavior
The workflow should be

1. Start app
2. Login and navigate to the view you want to modify
3. Make code changes
4. Auto reload kicks in
5. Check if you did the correct changes

### Suggested solution

Add a parameter called `serializeVaadinSession` with a default value of `false`.

When `serializeVaadinSession` is `false`, the `VaadinSession` and related locks that are stored in the HTTP session are not serialized when the session is serialized. Everything else in the HTTP session is serialized.

When `serializeVaadinSession` is explicitly set to `true` in the project, use the current behavior.

**Comment by mstahv** [comment]
Drafted a section of Session Serialization to docs, with this feature in mind. Also covered other issues as I couldn't find anything related to session persistency from our documentation. 

https://gist.github.com/mstahv/77f87a46027a1b3f2b51830709508b04

**Comment by knoobie** [comment]
The session serialization combined with spring boot devtools is a development only thing or?

 I'm in favor of adding this flag to the development mode, but changing the default in production doesn't seem reasonable for me.

As spring boot normally doesn't serialize any session in a production environment without proper configuration when stopped. So I don't need any harm with the current setup.

**Comment by Artur-** [comment]
In Spring Boot this is controlled by https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.server.server.servlet.session.persistent which is by default set to `false`. However Spring Boot dev tools sets this to true https://github.com/spring-projects/spring-boot/blob/47516b50c39bd6ea924a1f6720ce6d4a71088651/spring-boot-project/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/env/DevToolsPropertyDefaultsPostProcessor.java#L70

**Comment by knoobie** [comment]
^The same could be done in vaadin with the newly created `vaadin-dev-server` and `development-mode` - setting `serializeVaadinSession` to `false`, the opposite of the `spring-boot-devtools` configuration to make the development smooth without interfering with the `production-mode` later on, as both `spring-boot-devtools` and `vaadin-dev-server` should not be present in production environments.

**Comment by pleku** [comment]
I like the idea of not "changing the current default", but instead having `vaadin-dev-server` set the `serializeVaadinSession=false`.

It would probably (?) make it work in a backwards compatible manner for other usage than just Spring - with still retaining the default behavior for production mode (serialize), as long as people update their projects to exclude the `vaadin-dev-server` artifact for production build.

> When serializeVaadinSession is false, the VaadinSession and related locks that are stored in the HTTP session are not serialized when the session is serialized. Everything else in the HTTP session is serialized.

@Artur- Do you know a nifty way to do or does it require checking the property value in `writeObject` ?

**Comment by Artur-** [comment]
This is what I tested with a while back https://github.com/Artur-/keep-auth-on-redeploy/commit/2aea032c2bd70a59529f6786b8123c5096815cff

**Comment by Artur-** [comment]
There is a Flow 8.0.keepauth-SNAPSHOT that can be used to test this
