### ISSUE TITLE
Global style sheet of a custom theme is included multiple times

### ISSUE THREAD

**Issue by jouni** [vaadin/flow#11217]
### Description of the bug / feature

The `document.css` style sheet of a custom theme is included multiple times in the document, for each time the `applyTheme()` method is called.

### Minimal reproducible example

1. Download a Fusion project from start.vaadin.com
   - Include one view with the "Empty" template (e.g. "About")
2. Create `frontend/themes/myapp/document.css`
   - Add some CSS, e.g. `html { color: red; }`
3. In `frontend/views/main/main-view.ts`, add `<about-view></about-view>` before `<slot></slot>`
![Screen Shot 2021-06-11 at 11 27 04](https://user-images.githubusercontent.com/66382/121656225-f3966100-caa7-11eb-98b6-8dd1fec9f82d.png)
4. Run the app in development mode (`mvn`)

### Expected behavior

The CSS in document.css is added only once in the app.

### Actual behavior

The CSS is added twice.

Here’s the DOM in Safari (14.0.3):
![Screen Shot 2021-06-11 at 11 29 37](https://user-images.githubusercontent.com/66382/121656637-5e479c80-caa8-11eb-9bce-910c07f92f8f.png)

And in Chrome (91.0.4472.77):
<img width="1078" alt="Screen Shot 2021-06-11 at 11 29 18" src="https://user-images.githubusercontent.com/66382/121656705-70293f80-caa8-11eb-9f44-df05bf72f440.png">

### Versions:
    - Vaadin / Flow version: 20.0.1
    - Java version: 15.0.2
    - OS version: macOS 11.2.3

**Comment by Artur-** [comment]
The code looks like it tracks that the global CSS is not injected twice when applyTheme is called many times for the same shadow root but there is no tracking that the global CSS for a given theme should only be injected once

**Comment by pleku** [comment]
Does applying the `document.css` have any effect on the UI ? Or is it just inconvenient and confusing for the developer ?

**Comment by jouni** [comment]
It’s needed for defining `@font-face` rules, which don't work from shadow DOM. But basically anything that you only need to defined once globally (global custom properties) is good to do in that file.

**Comment by pleku** [comment]
Sorry @jouni , I meant that does _including it multiple times in the document_ have any effect on the UI ? 😊

**Comment by jouni** [comment]
Right. No, it’s the same style sheet, so it doesn't change the outcome. Though, there is a risk for unwanted overrides if another style sheet gets added between these multiple instances of document.css.

For example:

document.css
```css
html {
  color: red;
}
```

another-style-sheet.css (overrides document.css):
```css
html {
  color: blue;
}
```

document.css (added again, overrides another-stylesheet.css):
```css
html {
  color: red;
}
```

Not sure if that ever happens, though.

**Comment by joheriks** [comment]
Closing as this issue has been fixed.
