### ISSUE TITLE
Direct load of subpath in web application does not work anymore

### ISSUE THREAD

**Issue by roeltje25** [vaadin/flow#11221]
### Description of the bug / feature
When I have an application running at http://exanple.com/ which has a route http://example.com/test and I load this subpath in the browser directly, my application was working just fine on vaadin 19.0.8. After upgrading to 20.0.0 The application keeps showing the offline page for the /help domain when pasting the link directly. When I go to the root page it works just fine.
This is a problem because this way it is not possible anymore to bookmark pages. 

It seems to originate from commit https://github.com/vaadin/flow/commit/fd47059260b7a6e397735bafa5eb152f7aa2a0d7
where the canHandleRequest method was adjusted to include isServletRootRequest(request) explicitly making direct accesses to subpaths impossible during app init.

This seems to me a regression right?

### Minimal reproducible example
Will try to post an example later, but any multiroute app should have the issue
### Expected behavior
I can bookmark and directly navigate to a subpath
### Actual behavior
Navigating directly to a subroute shows the offline page
### Versions:
    - Vaadin / Flow version: 20.0.0
    - Java version: 11.0.11
    - OS version: Windows 10 (latest)
    - Browser version (if applicable): Chrome 91.0.4472.77 
    - Application Server (if applicable): Wildfly 22
    - IDE (if applicable): Eclipse (latest)

**Comment by pleku** [comment]
> When I have an application running at http://exanple.com/ which has a route http://example.com/test and I load this subpath in the browser directly, my application was working just fine on vaadin 19.0.8. After upgrading to 20.0.0 The application keeps showing the offline page for the /help domain when pasting the link directly

Hi Roel! Do you mean that accessing `/test` stopped working (not `/help`) ?

**Comment by roeltje25** [comment]
My apologies. Friday afternoon.... I meant example.com/test

Op vr 11 jun. 2021 17:07 schreef Pekka Hyvönen ***@***.***>:

**Comment by roeltje25** [comment]
I see. Indeed chrome and Firefox indicate a request to example.com/test?v-r=init which would not be expected if I understand you correctly. I will have to devise a working example on Monday as I cannot share my current project.

**Comment by roeltje25** [comment]
I have actually solved my problem. When changing the version from 19.0.8 to 20.0.0 in my pom file the Flow.ts in the browser was afterwards not yet updated. I removed my deployment, cleaned my project and restarted eclipse. Afterwards it was working again. Apparently sometimes the frontend files do not get updated. It's hard to trace that back.

I am closing the bug. Thank you for the follow up.
