### ISSUE TITLE
Update/Remove as much external dependencies as possible.

### ISSUE THREAD

**Issue by stbischof** [vaadin/flow#11226]
### Description of the bug / feature
Dependency handling could be very complicated. Critical OSS Vulnerabilitys also can exist in external Dependencies.

It would help to remove as much external dependencies as possible.

**Comment by pleku** [comment]
Hi. While I do agree that external dependencies can be a burden for application projects and we try to avoid brining in those unnecessarily, in this case the dependency is for Maven/Gradle plugin and thus it is not considered _as bad thing_ as those should not be leaking to the application project, but to the build time only.

And we try to avoid reinventing the wheel when we can, so it would be sensible to understand first why some dependency is a problem. Also for `dom4j` there is already version `2.1.3` from April 2020, so would it be enough to just simply update to that one ?

**Comment by stbischof** [comment]
I expected, that `dom4j`  is never used  from `org.reflections.`
If not, then was a bad example.

- I try to get guava removed. #11224

@pleku would it be an option for you to put just the required packages into the jars and not have them as dependencies?
Using the `-conditionalpackage: ` Instruction from [bnd](https://bnd.bndtools.org/instructions/conditionalpackage.html)

**Comment by Legioth** [comment]
One thing that is currently in progress is to separate all the code that is used at runtime in development but only during the build for production mode into a separate module. This would help reduce the set of dependencies needed in a production deployment and at the same time help make it easier to understand what goes where.

**Comment by stbischof** [comment]
This is a really good idea!


There is an Feature in bnd thal allows to package also  and onlY the real requires packages into the jar

https://bnd.bndtools.org/instructions/conditionalpackage.html

Maybe there is a point where this could help.
