### ISSUE TITLE
Fail accessing static resources from other jar:  java.nio.file.FileSystemNotFoundException: Provider "war" not installed

### ISSUE THREAD

**Issue by estronque** [vaadin/flow#11230]
### Description of the bug
The new method resourceIsDirectory in StaticFileServer class generates an exception for resources that have protocol "jar:war:file", when vaadin spring boot application is started standalone (java -jar xxxx.jar)

### Minimal reproducible example
the exception is raised when a static resource enclosed in another jar (different than the running one) is tried to be accessed
e.g: 
Access to resource logo.png: http://localhost:8080/other-folder/logo.png

Maven project other-component has the image:
src/main/resources/META-INF/resources/other-folder/logo.png

Maven spring boot application other-vaadin-app has compilation dependency other-component 

This worked in flow-server version 2.5.3.

### Expected behavior
No exception raised
### Actual behavior
Exception raised: java.nio.file.FileSystemNotFoundException: Provider "war" not installed
### Versions:
    - Vaadin / Flow version: 14.6.3, Flow: 2.6.3
    - Spring boot: 2.4.5
    - Java version: 11
    - OS version: Ubuntu 20.04
    - Browser version (if applicable): not applicable
    - Application Server (if applicable): vaadin spring boot maven structure
    - IDE (if applicable): not applicable

**Comment by caalador** [comment]
As a workaround you can define the static resource jar to be unpacked in the spring-boot-maven-plugin:

```
<plugin>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-maven-plugin</artifactId>
  <configuration>
    <requiresUnpack>
      <dependency>
	  <groupId>group.id</groupId>
	  <artifactId>artifact.id</artifactId>
      </dependency>
    </requiresUnpack>
  </configuration>
</plugin>
```

**Comment by estronque** [comment]
> <requiresUnpack>
>       <dependency>
> 	  <groupId>group.id</groupId>
> 	  <artifactId>artifact.id</artifactId>
>       </dependency>
>     </requiresUnpack>

Thanks, the workaround works!
