### ISSUE TITLE
Enable ViewAccessChecker by default

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#11231]
### Description of the bug / feature
`ViewAccessChecker` is used to check an access to Vaadin views since V21.

For Spring-based applications it's instance is created within auto-configuration and enables it immediately.
For non-Spring applications it is required to call `ViewAccessChecker::enable()` on initialisation phase in the docs here https://vaadin.com/docs/latest/flow/security/best-practices/#adding-vaadinserviceinitlistener .

So if the best practice is to enable it immediately and Spring add-on works like this either, then it might be better to enable it by default and let developers disable it when needed via `ViewAccessChecker::setEnabled(boolean)`.

### Versions:
    - Vaadin / Flow version: Vaadin 21.0.0.alpha5

**Comment by Artur-** [comment]
Spring adds it as a BeforeEnter listener automatically but it is not enabled unless you use `VaadinWebSecurityConfigurerAdapter`. 

Once you enable it, a default application will stop working as the default access control is ”deny”.

If we would enable it by default then all Spring Boot applications, even those not using Spring Security, would stop working when you upgrade from V19 to V20

**Comment by mshabarov** [comment]
I'd propose to improve it in this way:
1. To make `ViewAccessChecker` be enabled by default. This would mean that if the developer adds it to configuration, it would enable the security immediately.
2. To extend from `ViewAccessChecker` in Spring add-on and disable 'enable' flag in the CTOR. This would make it disabled by default for all Spring-based applications unless `VaadinWebSecurityConfigurerAdapter` is added by developer.

**Comment by pleku** [comment]
### Accept Criteria
- retain `enabled()` method. Not going to add `setEnabled` as we consider it a bad practice to make it possible to disable the security checks on the fly - someone can let us know if there would be a use case for that
- add a constructor `ViewAccessChecker` that takes flag `boolean enabled` and the default constructor sets it to `true`
- Spring based `BeforeEnter` listener doesn't enable the access checker yet, it is enabled later on like now
- The non-Spring based examples use the default constructor which enables the security by default - this should be updated to docs
