### ISSUE TITLE
21.0.0.alpha5 endpoints compile error

### ISSUE THREAD

**Issue by berndhopp** [vaadin/flow#11252]
### Description of the bug / feature
Starting with 21.0.0.alpha5, the TS generated for certain endpoints failed to compile with production profile.
For example I've got a java class called MessageEndpoint with a method with this signature

```
public void send(String text, int chatPartnerId)
```

the generated typescript is then

```
function _send(
 text?: string,
 chatPartnerId: number
): Promise<void> {
 return client.call('MessageEndpoint', 'send', {text, chatPartnerId});
}
```

however this does not compile: 

```
[ERROR] TS1016: A required parameter cannot follow an optional parameter.
[ERROR]     19 | function _send(
[ERROR]     20 |  text?: string,
[ERROR]   > 21 |  chatPartnerId: number
[ERROR]        |  ^^^^^^^^^^^^^
[ERROR]     22 | ): Promise<void> {
[ERROR]     23 |  return client.call('MessageEndpoint', 'send', {text, chatPartnerId});
[ERROR]     24 | }

````

### Minimal reproducible example
create a new java endpoint with the given signature, try to compile it with the production profile 

```
mvn -P production -DskipTests=true clean dependency:list install 
```
### Expected behavior
typescript code should compile

### Actual behavior
see above
### Versions:
Vaadin 21.0.0.alpha5, maven 3, java = corretto-11.0.11

**Comment by Artur-** [comment]
Sounds like the TS should be 
```
text: string|undefined
```
instead of
```
text?: string
```
