### ISSUE TITLE
Disabling Anchor clears href

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#11260]
### Minimal reproducible example
Paste this into the Skeleton Starter for Vaadin 21.0.0.alpha5
```
package org.vaadin.example;

import com.vaadin.flow.component.html.Anchor;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        final Anchor a = new Anchor("http://foo.com", "testing");
        a.setEnabled(false);
        System.out.println("HREF=" + a.getHref());
    }
}
```
### Expected behavior
Should print "HREF=http://foo.com"
### Actual behavior
Prints "HREF=" (the `a.getHref()` returns a blank string)
### Versions:
    - Vaadin / Flow version: 21.0.0.alpha5
    - Java version: 11
    - OS version: Ubuntu Linux 21.04
    - Browser version (if applicable): Firefox
    - Application Server (if applicable): Jetty
    - IDE (if applicable): Intellij

**Comment by knoobie** [comment]
That's correct - see https://github.com/vaadin/flow/issues/10924

**Comment by denis-anisimov** [comment]
Works as coded and designed in the https://github.com/vaadin/flow/issues/10924.

This ticket is a contradiction for https://github.com/vaadin/flow/issues/10924.

I personally don't have any preference how it should work. But it has been agreed in https://github.com/vaadin/flow/issues/10924 that it should work as designed.

If this is undesired  behavior then it's possible to override `onEnabledStateChanged` as it's implemented in the Component:
```
public void onEnabledStateChanged(boolean enabled) {
        if (getElement().getNode().hasFeature(ElementData.class)) {
            getElement().setAttribute("disabled", !enabled);
        }
    }
```
