### ISSUE TITLE
Javascript Errors after Upgrade from Vaadin 14 to Vaadin 20

### ISSUE THREAD

**Issue by aslan50** [vaadin/flow#11277]
Hello Vaadiners,

Im using Vaadin 14 with spring boot and gradle. I wanted to upgrade to the latest of version 20. 

Now I am getting Javascript Errors like:
(TypeError) : Cannot read property 'initLazy' of undefined, FlowClient.js?ca6a:216 
(TypeError) : Cannot read property 'reset' of undefined
FlowClient.js?ca6a:192 The error has occurred in the JS code: '$0, return $0.$connector.reset()' 
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
and more ...

I updated the gradle.build file to the new version like described in https://vaadin.com/docs/v20/guide/start/gradle#build-file and added the vaadin spring boot dependency.
The Server starts fine but im getting this JS Errors if i call my Applications. No Component is loading anymore. For example a grid Component. I tried the steps Vaadin clean, prepare Frontend and start again. With no success.
Maybe someone had the same problem and can suggest some solution.

Plugin:
id 'com.vaadin' version '20.0.3'
id 'org.springframework.boot' version '2.3.3.RELEASE'

dependency:
implementation "com.vaadin:vaadin-core:20.+"
implementation group: 'com.vaadin', name: 'vaadin-spring-boot-starter', version: '20.0.3'

### Versions:
    - Vaadin / Flow version: 20.0.3
    - Java version: 8
    - IDE (if applicable): IJ

**Comment by caalador** [comment]
Could you try getting a clean https://github.com/vaadin/base-starter-gradle/tree/master and then moving your sources there?
If it works then you could crossreference the `build.gradle` files.
If it fails then could you try to minimize the sources and attach the replicating project to the ticket.

**Comment by aslan50** [comment]
hi caalador, thank you very much the crossreference from the build.gradle and gradle.properties files solved my problem.
