### ISSUE TITLE
Improvement or Bug - Better handling of resync after network issues

### ISSUE THREAD

**Issue by netbeansuser2019** [vaadin/flow#11274]
If it is used e.g. Mozilla Firefox debug request blocking (drag one one request to be blocked) to simulate very short network issue it has been seen that following requests (e.g. via $server - @ClientCallable) has not been sent and resync-dialog was closed so common user possibly do not get a point what is wrong.  So only way to recover is reloading a page to make UI react again. 
	  
Suggested solution: implement real recovery
Alternative solution: keep resync-dialog open as issue persist so user can know that during his break was something wrong with connection.

Additional improvement could be possibility to set some time out for client calls ($server) so if server is off you can get rejected Promise that could be anyhow use for alternative way or to show any message to user.

- Vaadin / Flow version: 14.4.7 with compatibility and production mode on
- Java version: 11

**Comment by netbeansuser2019** [comment]
https://github.com/vaadin/flow/issues/2210
https://github.com/vaadin/flow/pull/7631

**Comment by mcollovati** [comment]
Closing because compatibility mode is not supported anymore in the maintained Vaadin versions.
