### ISSUE TITLE
Fusion: Data Binding: dynamic validation constraints values won't be mapped to TS

### ISSUE THREAD

**Issue by Lars-jnk** [vaadin/flow#11307]
### Description of the bug
If the constraint get the value on the Java side from a static propery

### Minimal reproducible example
I have a bean with one constraints that has his value from a other static property.
```
public class DemoEntity {
    @Pattern(regexp = Constants.REGEX_UUID , message = "regex fail....")
    public String id;
}
... in a other file ...
public class Constants {
    public static final String REGEX_UUID = "^\\b[0-9a-f]{8}\\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\\b[0-9a-f]{12}\\b$";
}
```

### Expected behavior
Transfer the value in Constants.REGEX_UUID_OR_EMPTY or the complete class to the TS frontend.
Or a error on build if you don't wanne support this. But support it please. :)

### Actual behavior
Nothing. Error on executing:

> Uncaught ReferenceError: Constants is not defined

### Versions:
    - Vaadin / Flow version: 20.0.3

**Comment by Lars-jnk** [comment]
Not sure if this is a vaadin thing. But if you have more than one constraint and there is a comment between them, the constraint after the comment won't be mapped.

```
@NotNull
//@Pattern(regexp = Constants.REGEX_UUID_OR_EMPTY, message = "regex fail....")
@Pattern(regexp = "(^\\b[0-9a-f]{8}\\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\\b[0-9a-f]{12}\\b$|^$)", message = "regex fail....")
public String id;
```
-> The Model has only NotNull
```
@NotNull
@Pattern(regexp = "(^\\b[0-9a-f]{8}\\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\\b[0-9a-f]{12}\\b$|^$)", message = "regex fail....")
//@Pattern(regexp = Constants.REGEX_UUID_OR_EMPTY, message = "regex fail....")
public String id;
```
-> all there like expected

**Comment by knoobie** [comment]
In my understanding you have to use `Pattern.List` to use multiple `@Pattern` on a field - but I'm not sure, if vaadin supports this use-case. 

e.g.

```java
@Pattern.List({
    @Pattern(regexp = "todo-1", message = "..."),
    @Pattern(regexp = "todo-2", message = "...")
})
private String field;

```

**Comment by Lars-jnk** [comment]
No, I dont need multiple pattern. I just wanna keep the one with the constant in a comment and detected this bug.

**Comment by jcgueriaud1** [comment]
I think it's the same issue than this: https://github.com/vaadin/flow/issues/10633

**Comment by Lars-jnk** [comment]
Right, it's the same like my initial issue. But the comment is a new bug.
I open a new issue for this bug later and close the issue.

**Comment by Lars-jnk** [comment]
You can find the bug here: #11427
