### ISSUE TITLE
Error messages in development are displayed as HTML

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow#11324]
This code
```java
UI.getCurrent().getPage().executeJs("throw Error('There was an error in <vaadin-text-field>')");
```

produces the following error message overlay:

<img width="448" alt="Screenshot 2021-06-24 at 10 06 36" src="https://user-images.githubusercontent.com/1222264/123218704-b7fe8c80-d4d4-11eb-816a-db4b9ca60599.png">

This only happens in development mode so it's not necessarily a security issue.

Probably happens due to [this logic](https://github.com/vaadin/flow/blob/02c937203824f5ddb2215d77e0d9797f9d190678/flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java#L174-L216) using `innerHTML` (instead of `textContent`)

**Comment by fluorumlabs** [comment]
Note: there is at least one place when this HTML formatting is actually used
