### ISSUE TITLE
FullCPScanningIT failed on CI

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#11329]
CI build failed on `FullCPScanningIT`, see [this build](https://bender.vaadin.com/buildConfiguration/Flow_Flow80_Flow80Snapshot/239480) for more details. 
Note the test passes after a rerun.

**Comment by caalador** [comment]
As this test hasn't failed for a long time I'm closing this issue.
If it seems to reappear then just open a new ticket.
