### ISSUE TITLE
Enable rerouting to a custom page if a View-based access is denied

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#11335]
### Description of the bug / feature
View-based access control feature introduced in V21 checks whether the user's has an appropriate role to browse the secured page via `@RolesAllowed` and makes `rerouteToError(NotFoundException.class)` if it's not the case, showing `Could not navigate to ...` message (in production mode).
While this is a more secured way than report `Access Denied` message, it's not always necessary in all cases.
This enhancement considers providing an API to set the custom page the user is navigated to, if he has no access to requested page.
Here are a couple possible use cases:
- routing the users to a 'public' version of protected page.
- showing a prompt like 'Please subscribe if you want to see this protected/subscriber-only content' or other suggestion on how he could upgrade his authorities to browse the page.

Some thoughts on how it can be achieved:
- Add a new `class RouteAccessDeniedError extends Component implements HasErrorParameter<AccessDeniedException>` default error handler (or to extend the existing error handlers) and reroute to `AccessDeniedException` in the `ViewAccessChecker`. Then the developers can extend this error handler to add any prompts/styles there.
- Configure the custom route/view class in the same place where the secured annotations like `@RolesAllowed` are configured. For example, by giving an extra annotation or an extra parameter to existing annotation. It would give a flexibility that some pages would have their 'public' versions, and the rest would be reported as 'not found' by default.

**Comment by chkpnt** [comment]
Yes, please reroute to `AccessDeniedException`. It's easy to configure it, that it behaves like a `NotFoundException`, but not vice versa.

**Comment by tltv** [comment]
Just adding new default `RouteAccessDeniedError` page would make it easier to redirect to public page or customize error page.
 
Adding new attribute like `String unauthorizedRerouteTo` and/or `String unauthorizedForwardTo` in `RolesAllowed` annotation would make it easier as you could redirect to any route before any error page is loaded. 
Also adding `Class<? extends Exception> unauthorizedRerouteToError`  would allow overriding default `AccessDeniedException` e.g. with `NotFoundException` to fall back to how it works now.

**Comment by tltv** [comment]
[PR](https://github.com/vaadin/flow/pull/17843) adds [new annotation called `AccessDeniedErrorRouter`](https://github.com/vaadin/flow/blob/2c23d70add0fb3d4898a7392902746d339c60739/flow-server/src/main/java/com/vaadin/flow/server/auth/AccessDeniedErrorRouter.java) for route specific control over which error page to show for access denied errors.
