### ISSUE TITLE
Regression in Anchor component

### ISSUE THREAD

**Issue by roastedcpu** [vaadin/flow#11349]
When upgrading from 14.4.10 to 14.6.1 the anchor component no longer sets the href attribute after the initial render.

This applies to both PolymerTemplate and LitTemplate.

See issue #3839 for attached code.

**Comment by denis-anisimov** [comment]
I can reproduce this at least (using `master`).

**Comment by denis-anisimov** [comment]
Another aspect of https://github.com/vaadin/flow/issues/8974.

`"href"` is an attribute. But it's set as a property after template parsing.
