### ISSUE TITLE
DevModeHandlerManagerImpl not serializable

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow#11371]
We're getting test failures due to:
`Caused by: java.io.NotSerializableException: com.vaadin.base.devserver.DevModeHandlerManagerImpl`

Example:
https://teamcity.vaadin.com/viewLog.html?buildId=83701&buildTypeId=VaadinFlowComponents_PullRequestValidation

Either make the class serializable or include it to excludedPatterns in [ClassesSerializableTest](https://github.com/vaadin/flow/blob/master/flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java)

**Comment by caalador** [comment]
Why is `vaadin-dev-server` added as a dependency for everything even though it's not needed apart from IT test modules running in development mode? Also most IT packages seem to do `prepare-frontend` and `build-frontend` making them not need the dev server as they are running in pseudo production mode.

**Comment by tomivirkki** [comment]
Without the dependency, running the component demos starts the server, but client resources never get processed:

<img width="1028" alt="Screenshot 2021-07-02 at 9 53 44" src="https://user-images.githubusercontent.com/1222264/124233441-82ccec80-db1b-11eb-8e19-5a61c0f9376a.png">

**Comment by caalador** [comment]
Try running
`mvn package jetty:run -am -B -q -DskipTests -pl vaadin-buttin-flow-parent/vaadin-button-flow-demo -Pwar` as I have sometimes noted that jetty:run for some reason skips executing goal steps in other plugins. 

But we'll add the ignore even though the dev-mode shouldn't be needed for the demo.

**Comment by tomivirkki** [comment]
Thx, with that command the app works fine. Will remove the dependency from the linked PR.
