### ISSUE TITLE
Url parsing goes wrong when from history

### ISSUE THREAD

**Issue by wfischlein** [vaadin/flow#11426]
### Description of the bug / feature
when you use page-history-back (e.g. browser-back-button) for urls with query parameters that are encoded you get wrong values (like this: http://localhost:8080/hello?parameter=V%C3%A4%C3%A4din%20%C3%96y).
On page reload the parsing works fine.
### Minimal reproducible example
Here is an example. Uncompress it, read the readme for more information
[urlbug.zip](https://github.com/vaadin/flow/files/6832045/urlbug.zip)
### Expected behavior
Also when using page history to get back to a parametrised url like above ther value should arrive as decoded text in the BeforeEvent of 'setParameter' of implementors of HasUrlParmeter
### Versions:
    - Vaadin / Flow version: 14.6.6
    - Java version: 8
    - Application Server (if applicable): spring-boot (embedded tomcat)

**Comment by caalador** [comment]
Tested this with 14.10.8 and the back navigation now also returns expected result.
Closing issue as fixed. If anything new comes up please open a new ticket with steps to reproduce.
