### ISSUE TITLE
Consider updating JSoup

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#11493]
The currently used JSoup version is 1.12.1 from May 2019. Since then, there's been 1.12.2 with improvements to performance and interoperability, 1.13.1 with new convenience APIs and improved performance, and 1.14.1 with improvements to robustness and performance.

There is of course also a risk of breaking changes since JSoup doesn't follow a strict versioning policy. 1.13.1 in particular har a mention of removing old deprecated APIs.

**Comment by knoobie** [comment]
@denis-anisimov  see my try last week https://github.com/vaadin/flow/pull/11467 - I hadn't much time to work on it again.. but it looks like only the creation of Text has changed. The other parts worked locally for me.

**Comment by denis-anisimov** [comment]
Should this be only in the master (9.0) or can be backported to other versions?
Which versions ? 8.0 ? 2.7 ?

**Comment by Legioth** [comment]
It looks like there are some breaking changes, which means that the change wouldn't be safe for anything else than the next major version.
