### ISSUE TITLE
Add example and doc about configuring the view-port meta

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#1149]
The `@Viewport` does not have any demo nor doc apart from javadoc.

**Comment by heruan** [comment]
Found this trying to set the viewport to test responsiveness of flex layouts. I imagine much has changed in a year so I'm looking for the current correct way to set the viewport meta!

**Comment by Legioth** [comment]
Unfortunately, nothing has changed. We haven't yet put any significant effort into coming up with what to do with the annotations that were previously put on the application's `UI` subclass, e.g.`@Push`, `@Viewport` and `@Theme`.

**Comment by Legioth** [comment]
There is now documentation in https://vaadin.com/docs/v10/flow/advanced/tutorial-bootstrap.html
