### ISSUE TITLE
Mandatory url parameters break navigation

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow#11501]
If you add mandatory parameter in url template, navigation breaks. 

**Steps to reproduce**

Create test application using start.vaadin.com, add multiple views to it. Change `AboutView `to be as below.

Observed behavior: None of the routes work

Expected behavior: See the text including the given parameter on screen

If you change `@Route(value = "about/:param", layout = MainView.class)` to `@Route(value = "about/:param?", layout = MainView.class)` or `@Route(value = "about/:param*", layout = MainView.class)`, then navigation works.

Tested with Vaadin 14.6.7 and Vaadin 20

```
@Route(value = "about/:param", layout = MainView.class)
@PageTitle("About")
@CssImport("./views/about/about-view.css")
public class AboutView extends Div implements BeforeEnterObserver {

    private String param = "";
    private Span oppinions;

    public AboutView() {
        oppinions = new Span();
        add(oppinions);
    }
    
    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        param = event.getRouteParameters().get("param").orElse("");
        oppinions.setText("Todays opinnions for: "+param);
    }
}
```

Also if to fix the above by implementing `HasUrlParameter` instead, it still breaks in similar fashion

```
@Route(value = "about", layout = MainView.class)
@PageTitle("About")
@CssImport("./views/about/about-view.css")
public class AboutView extends Div implements HasUrlParameter<String> {

    private String param = "";
    private Span oppinions;

    public AboutView() {
        oppinions = new Span();
        add(oppinions);
    }
    
    @Override
    public void setParameter(BeforeEvent event, String parameter) {
        oppinions.setText("Todays opinnions for: "+parameter);        
    }
}
```

When you `@OptionalParameter` to `setParameter `application works.

**Comment by TatuLund** [comment]
I managed to replicate the issue also with vanilla, so moved to Flow.

**Comment by apgsga-stb** [comment]
This may be still an issue, but currently not for me any more. In my case, the fault was on my side when I called errorenously `RouteConfiguration.forSessionScope().getUrl(viewClass, routeParameters)` on a viewClass without URL-Parameters.

**Comment by TatuLund** [comment]
Ok. I did some debugging. The problem in both cases seems to be that I am creating RouterLink without parameter for the menu in the MainLayout. And mandatory parameter check is also done when an instance of RouterLink is created.

**Comment by TatuLund** [comment]
Opened another ticket: https://github.com/vaadin/flow/issues/11502
