### ISSUE TITLE
build-frontend - webpack suddenly fails on production mode - 20.0.5 

### ISSUE THREAD

**Issue by osenbg** [vaadin/flow#11537]
Hi,
we actual have suddenly problems to build production mode on Flow Version 20.0.5 

[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:20.0.5:build-frontend (default) on project diwa: Execution default of goal com.vaadin:vaadin-maven-plugin:20.0.5:build-frontend failed: Webpack process exited with non-zero exit code.
[ERROR] Stderr: '
..... \node_modules\.pnpm\webpack-cli@3.3.11_webpack@4.46.0\node_modules\webpack-cli\bin\cli.js:93
[ERROR] throw err;
[ERROR] ^
[ERROR] 
[ERROR] Error: Cannot find module 'workbox-build/build/options/schema/webpack-generate-sw'
[ERROR] Require stack:

**Comment by knoobie** [comment]
See #11524 for more information.
