### ISSUE TITLE
Possible information disclosure through webcomponentsjs/package.json

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow#11560]
The VAADIN/build/webcomponentsjs/package.json file is publicly available in a deployed application, in production mode.

That file references the actual directory where the build took place:
```
  "_where": "C:\\Users\\Javier\\Downloads\\my-app\\my-app"
```

(Other files such as CHANGELOG.md and README.md are also available, though they don't disclose information)

### Minimal reproducible example

1. Download Vaadin 14 application fromn https://start.vaadin.com/app

2. Start the application in production mode: `mvn spring-boot:run -Pproduction`

3. Open http://127.0.0.1:8080/VAADIN/build/webcomponentsjs/package.json

### Expected behavior
A 404 HTTP response.

### Actual behavior
The contents of package.json are retrieved

### Versions
   - Vaadin version: 14.6.8 
   - OS version: Windows / Linux

### Workaround

The files can be excluded through POM configuration:
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-jar-plugin</artifactId>
	<version>3.1.2</version>
	<configuration>
		<excludes>
			<exclude>META-INF/VAADIN/build/webcomponentsjs/package.json</exclude>
			<exclude>META-INF/VAADIN/build/webcomponentsjs/CHANGELOG.md</exclude>
			<exclude>META-INF/VAADIN/build/webcomponentsjs/README.md</exclude>
		</excludes>
	</configuration>
</plugin>
```

**Comment by denis-anisimov** [comment]
@caalador , do you think this is a bug ?
Does it make sense to block "/VAADIN/build/" access in production mode at all ?

**Comment by caalador** [comment]
I don't see any local paths after a build (which npm / pnpm version is used?), but the copy plugin in webpack could probably be changed to only copy .js files for `webcomponentsjs`. This is not a problem for newer than 14 versions that do not have 

Access to `VAADIN/build` can not be blocked as that is the place where all the public files should be located and it contains the application bundles.

**Comment by mshabarov** [comment]
Flow `2.7` and `2.6` series are patched to not copy the mentioned files to the build directory, thus, I'm closing the ticket.
