### ISSUE TITLE
Security issue with jsoup-1.12.1

### ISSUE THREAD

**Issue by mas4ivv** [vaadin/flow#11609]
Vaadin Flow 14.6.8 is using jsoup-1.12.1, which has a security issue: https://github.com/jhy/jsoup/security/advisories/GHSA-m72m-mhq2-9p6c
The problem is fixed in jsoup-1.14.2. Unfortunately we can't simply replace the library in our application as Vaadin is using methods no longer available in the fixed version.

**Comment by mshabarov** [comment]
All supported Vaadin versions are now compliant with jsoap `1.14.2`.
