### ISSUE TITLE
Session expiration on server restart causes "endRequest called when no request is active"

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#1161]

**Comment by Artur-** [comment]
Happens in Bakery if you:
1. Start server
2. Open login screen
3. Close the laptop and go home
4. Come to work and open the laptop

**Comment by Braus** [comment]
I still have this error, does a workaround exist somewhere?

**Comment by jkoenig134** [comment]
I also have the error. Not found something yet.

**Comment by Legioth** [comment]
Are the other reporters also observing this only when resuming to use an application when the computer has been suspended for some time, or do you have some way of reproducing it also while actively using the application?

**Comment by TatuLund** [comment]
Is this copy of https://github.com/vaadin/flow/issues/4071 ?

**Comment by mshabarov** [comment]
Closed, since no reports given last few years and some bugfixes were made. Please report if you experience this issue again.
