### ISSUE TITLE
webpack manifest.json is used in an unreliable way that doesn't work with webpack 5

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#11633]
### Description of the bug / feature
https://www.npmjs.com/package/webpack-manifest-plugin describes the manifest.json output as

"The manifest file will contain a map of source filenames to the corresponding build output file. e.g.

```json
{
  "dist/batman.js": "dist/batman.1234567890.js",
  "dist/joker.js": "dist/joker.0987654321.js"
}
```
"

However the code in `FrontendUtils.parseManifestPaths` only retains the mapped value and assumes it is the same.
When using webpack 5, and probably in other cases also, the manifest can contain e.g.
```
  "sw.js": "autosw.js",

```

**Comment by mshabarov** [comment]
@Artur- so, currently `FrontendUtils.parseManifestPaths` collects the build output filenames (manifest values) gives them to static file server. Could you please elaborate how should it work otherwise? How should it take the keys into account?

**Comment by Artur-** [comment]
It should store the "public path" -> "internal file name" map and match the URL agains the "public path" (e.g. `sw.js`) and then load the file from webpack using the "internal file name" (e.g. `autosw.js`).

**Comment by Artur-** [comment]
Hmm, this might be another issue in my webpack setup because the files in webpack are actually not named `autosw.js`. Let me do some more digging

**Comment by Artur-** [comment]
The problem is not the one described here. It is a problem of a webpack plugin that is not 100% compatible with webpack 5.
