### ISSUE TITLE
flow-client cannot be built using latest npm

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#11668]
### Minimal reproducible example
```
cd flow-client
mvn install
```

### Expected behavior
It builds

### Actual behavior
```
[INFO] --- exec-maven-plugin:1.6.0:exec (npm-install) @ flow-client ---
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @vaadin/flow-deps@0.0.1
npm ERR! Found: webpack@4.39.1
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"4.39.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.40.0 || ^5.0.0" from esbuild-loader@2.15.1
npm ERR! node_modules/esbuild-loader
npm ERR!   dev esbuild-loader@"2.15.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Versions:
    - Vaadin / Flow version: master
    - Java version: 16
    - OS version: mac

**Comment by web-padawan** [comment]
Looks like a mismatch of webpack version and minimal version required by `esbuild-loader`. Let's align with the one here

https://github.com/vaadin/flow/blob/3d0dd04df7ceaefb175f5cfd613ace8ca93d551c/flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java#L385

**Comment by web-padawan** [comment]
PR is here: #11671

Note, the fact that original PR was green and validation build didn't catch this means that we probably need to make some changes.
