### ISSUE TITLE
FrontendUtils fails to find pnpm if only the newer version is installed

### ISSUE THREAD

**Issue by martaolszewskatusiek** [vaadin/flow#11730]
### Minimal reproducible example
1. Download Fusion app from start.vaadin.com for v20.
2. Have only pnpm version 6 available in system's path (in my case, 6.0.1).
3. Run `mvn spring-boot:run`.

### Expected behavior

mvn goal should run without issues, as pnpm 6 is more than the required minimum version of pnpm 5.

### Actual behavior

Error: `java.lang.IllegalStateException: Found too old 'pnpm'. If installed into the project 'node_modules', upgrade 'pnpm' to at least 5.0.0`

### Versions:
    - Vaadin / Flow version: v20
    - Java version: irrelevant
    - OS version: irrelevant
    - IDE (if applicable): Eclipse version: 2019-03 (4.11.0)

### Possible fix
The command used to check for pnpm version, `c:\_node_modules\npx.cmd --yes --quiet pnpm@5 --version` should probably be `c:\_node_modules\npx.cmd --yes --quiet pnpm@5+ --version`. In the current form it produces an empty string when only a newer version is available.

**Comment by caalador** [comment]
For a non accepted version there should be an info log `pnpm '{}' is version {} which is not supported (expected >={})` is that available and what does it say

**Comment by mshabarov** [comment]
I can't reproduce this issue on Mac OS.
Flow prints the following info message
`INFO 3792 --- [onPool-worker-9] c.v.flow.server.frontend.FrontendTools   : using '/Users/mikhail/.nvm/versions/node/v14.15.5/bin/npx --yes --quiet pnpm@5' for frontend package installation`
And
`/Users/mikhail/.nvm/versions/node/v14.15.5/bin/npx --yes --quiet pnpm@5 --version` gives `5.18.10`.

**Comment by tarekoraby** [comment]
> For a non accepted version there should be an info log `pnpm '{}' is version {} which is not supported (expected >={})` is that available and what does it say

For me, the message exsists, and it says `pnpm 'C:\Program Files\nodejs\npx.cmd --yes --quiet pnpm@5' is version 4.5.0 which is not supported (expected >=5.0.0)`.

**Comment by tarekoraby** [comment]
Which is confusing since `npm view pnpm version` indicates that my pnpm version is 6.14.5.

**Comment by caalador** [comment]
@tarekoraby what does `"C:\Program Files\nodejs\npx.cmd" --yes --quiet pnpm@5 -v` say?

**Comment by tarekoraby** [comment]
5.18.10

**Comment by caalador** [comment]
Would it be possible to add a breakpoint to `FrontendTools:validatePnpmVersion` and check the value when the project is run?

**Comment by tarekoraby** [comment]
It shows version 4.5.0 (at line 398 of FrontendTools).

**Comment by tarekoraby** [comment]
I might have found something, if I run `"C:\Program Files\nodejs\npx.cmd" --yes --quiet pnpm@5 -v` I actually get 4.5.0. But if I go to the Nodejs folder myself and run `npx.cmd --yes --quiet pnpm@5 --version` I get 5.18.10.

**Comment by caalador** [comment]
Can you find anywhere on the computer a pnpm folder where the package.json contains 4.5.0?

**Comment by tarekoraby** [comment]
Another update, actually the version difference is between Windows command prompt and the Git Bash. 
From the command prompt, the version is 4.5.0 regardless of the directory from where I'm running the command. From the Git Bash, it is 5.18.10.

**Comment by tarekoraby** [comment]
And from the Git bash, the projects seem to work just fine if I run `mvn`.

**Comment by tarekoraby** [comment]
> Can you find anywhere on the computer a pnpm folder where the package.json contains 4.5.0?

How to search for that efficiently?

**Comment by caalador** [comment]
I guess simplest would be to run `for /r /d %A in (*pnpm) do echo %A` in c:\ and check the found folders manually. Mainly of interest is non project folders like `Program Files`, `C:\Users\xyz\AppData\Local\npm-cache\`, `C:\Users\xyz\.vaadin` and the like

**Comment by tarekoraby** [comment]
Found one under `C:\Users\Tarek Oraby\AppData\Roaming\npm\node_modules\pnpm` with pnpm version 4.5.0.

**Comment by mshabarov** [comment]
It might be that the gitbash uses it's own pnpm version and thus it gives 5.18.10.
What if you remove `C:\Users\Tarek Oraby\AppData\Roaming\npm\node_modules\pnpm` and try start the app again from prompt?

**Comment by tarekoraby** [comment]
> What if you remove `C:\Users\Tarek Oraby\AppData\Roaming\npm\node_modules\pnpm` and try start the app again from prompt?

That seems to solve it 👍. 

But I wonder (1) how I ended up in this situation in the first place? (2) if this scenario is common enough that many users might face the same problem? (3) if there is something to be done in Flow to handle the issue more conveniently?

**Comment by caalador** [comment]
The simplest fix would be to have `requireHomeNodeExec` true by default in which case flow would always install/use a version from `~/.vaadin` other than that I at least do not know why the versions are installed here and there

**Comment by mshabarov** [comment]
@martaolszewskatusiek previously you said that you saw the exception on app startup:
```
com.vaadin.flow.server.frontend.FrontendUtils$UnknownVersionException: Unable to detect version of pnpm. Using command c:\_node_modules\npx.cmd --yes --quiet pnpm@5 --version
```
Could you please check what was the root cause exception (`IOException`, `CommandExecutionException`, `InterruptedException`) of unable to detect version? Was it that pnpm version returned an empty string?

**Comment by mshabarov** [comment]
> The simplest fix would be to have `requireHomeNodeExec` true by default in which case flow would always install/use a version from `~/.vaadin` other than that I at least do not know why the versions are installed here and there

@caalador good point! This shouldn't break the existing projects as once the `~/.vaadin` doesn't have a node installations, vaadin would install it automatically, right?

**Comment by tarekoraby** [comment]
Now I have a different problem, now I see the same error messages as the one originally reported by @martaolszewskatusiek:
```
2021-09-03 13:59:44.073  WARN 10228 --- [nPool-worker-19] c.v.flow.server.frontend.FrontendTools   : version check 'C:\Program Files\nodejs\npx.cmd --yes --quiet pnpm@5' failed

com.vaadin.flow.server.frontend.FrontendUtils$UnknownVersionException: Unable to detect version of pnpm. Using command C:\Program Files\nodejs\npx.cmd --yes --quiet pnpm@5 --version
	at com.vaadin.flow.server.frontend.FrontendUtils.getVersion(FrontendUtils.java:977) ~[flow-server-8.0.0.rc3.jar:8.0.0.rc3]
	at com.vaadin.flow.server.frontend.FrontendTools.validatePnpmVersion(FrontendTools.java:687) ~[flow-server-8.0.0.rc3.jar:8.0.0.rc3]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.stream.Streams$StreamBuil.....
```

**Comment by caalador** [comment]
@mshabarov It wouldn't affect those that can use the vaadin installed one, but it would break anything that is behind a proxy/firewall or can't use custom things which would be why they are installing pnpm themselves/IT

The default was at somepoint use .vaadin (in v14) but I think it was reverted to be opt in instead of opt out. Can't remember that exactly what were the painpoints.

**Comment by martaolszewskatusiek** [comment]
> 
> 
> @martaolszewskatusiek previously you said that you saw the exception on app startup:
> 
> ```
> com.vaadin.flow.server.frontend.FrontendUtils$UnknownVersionException: Unable to detect version of pnpm. Using command c:\_node_modules\npx.cmd --yes --quiet pnpm@5 --version
> ```
> 
> Could you please check what was the root cause exception (`IOException`, `CommandExecutionException`, `InterruptedException`) of unable to detect version? Was it that pnpm version returned an empty string?

This is the first exception in the logs:
```
com.vaadin.flow.server.frontend.FrontendUtils$UnknownVersionException: Unable to detect version of pnpm. Using command c:\_node_modules\npx.cmd --yes --quiet pnpm@5 --version
	at com.vaadin.flow.server.frontend.FrontendUtils.getVersion(FrontendUtils.java:966) ~[flow-server-7.0.7.jar:7.0.7]
```

This is another:
```
java.lang.IllegalStateException: com.vaadin.flow.server.ExecutionFailedException: Found too old 'pnpm'. If installed into the project 'node_modules', upgrade 'pnpm' to at least 5.0.0
	at com.vaadin.flow.server.DevModeHandler.getCause(DevModeHandler.java:273) ~[flow-server-7.0.7.jar:7.0.7]
	at com.vaadin.flow.server.DevModeHandler.getCause(DevModeHandler.java:269) ~[flow-server-7.0.7.jar:7.0.7]
	at com.vaadin.flow.server.DevModeHandler.handleRequest(DevModeHandler.java:255) ~[flow-server-7.0.7.jar:7.0.7]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1545) ~[flow-server-7.0.7.jar:7.0.7]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:299) ~[flow-server-7.0.7.jar:7.0.7]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:109) ~[vaadin-spring-17.0.2.jar:na]
```
And it was the command that checks for pnpm version that returned an empty string.

**Comment by tarekoraby** [comment]
With @mshabarov help, the issue seems to be fixed for me by deleting `C:\Users\Tarek Oraby\AppData\Roaming\npm` from the path.

**Comment by mshabarov** [comment]
@martaolszewskatusiek thanks for details! And once you execute `"c:\_node_modules\npx.cmd" --yes --quiet pnpm@5 --version` in the prompt, the output is an empty string, right?

**Comment by martaolszewskatusiek** [comment]
> 
> 
> @martaolszewskatusiek thanks for details! And once you execute `"c:\_node_modules\npx.cmd" --yes --quiet pnpm@5 --version` in the prompt, the output is an empty string, right?

Yes, yes, it is an empty string.

However if I run it without `--quiet`, it returns the proper version.

**Comment by mshabarov** [comment]
> @mshabarov It wouldn't affect those that can use the vaadin installed one, but it would break anything that is behind a proxy/firewall or can't use custom things which would be why they are installing pnpm themselves/IT
> 
> The default was at somepoint use .vaadin (in v14) but I think it was reverted to be opt in instead of opt out. Can't remember that exactly what were the painpoints.

Then for me it feels as a bigger problem to install node executable into `.vaadin` by default and I wouldn't go this way for now.

**Comment by mshabarov** [comment]
> > @martaolszewskatusiek thanks for details! And once you execute `"c:\_node_modules\npx.cmd" --yes --quiet pnpm@5 --version` in the prompt, the output is an empty string, right?
> 
> Yes, yes, it is an empty string.
> 
> However, if I run it without `--quiet`, it returns the proper version (edit: that's in my case 6.14.13).

Very strange, looks like a bug in `npx`.

**Comment by mshabarov** [comment]
To avoid such an issues when the `npx` finds the globally installed `pnpm` executable by looking into `$PATH` or `node_modules/.bin`, I would propose to:
1. Use additional flag `--ignore-existing` for `npx` by default and pin the pnpm version, like this: `npx --yes --quiet --ignore-existing pnpm@5.18.10`.
2. Since `pnpm@6` is not compatible with Node 10 (which should be still supported by Vaadin), I propose to use the latest 5.X version.
3. Then, checking of `pnpm` version won't be needed by default because we pinned the version.
4. For more complex edge cases, when the developers need the global pnpm, it can be customised through a new Vaadin parameter, say `enableGlobalPnpm` (`false` by default).
5. Once this parameter is set to `true`, Vaadin is then looking to the globally installed `pnpm` with `FrontendToolsLocator::tryLocateTool` and check it's version.
6. If the global's pnpm version is too old or if the global pnpm not fount, Vaadin throws an exception.

This is basically that you previously proposed @Artur- but with adding `--ignore-existing`. What do you think?

**Comment by mshabarov** [comment]
Until it is implemented, the workaround for this issue is to use `vaadin.pnpm.enable=false` to use `npm` instead, or to remove the globally installed pnpm by removing corresponding reference in PATH.
