### ISSUE TITLE
Grid not responsive with component cells

### ISSUE THREAD

**Issue by fgrazi** [vaadin/flow#11749]
### Versions:
    - Vaadin / Flow version:
    - Java version:
    - OS version:
    - Browser version (if applicable):
    - Application Server (if applicable):
    - IDE (if applicable):

**Comment by caalador** [comment]
Closing issue as it is missing all details and by the topic would seem to be the same as reported in #11750
I this is not so please re-open a ticket with all the information to reproduce the issue into  https://github.com/vaadin/flow-components

**Comment by fgrazi** [comment]
Hi Caalador,

Sorry, seems Github lost all information I entered. I had also produced screeshots. No, not the same as #11750, but I also deleted all associated files to reproduce. What basically happens is that if you have a component cell (horizontal layout) that grows horizontally (for example with a button), the grid does not add a horizontal scrollbar when exceeding the screen size and whatever columns at right become unreachable. Please let me know if you still have interest in the bug, I will re-write the reproducing code.

**Comment by caalador** [comment]
Hi.

If it's not the same then you can open a new issue to the [components repository]( https://github.com/vaadin/flow-components) with the details.

All all bug reports are welcome.
