### ISSUE TITLE
Remove release profile since it's not used, not working and confusing.

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#11809]
`release` profile should be removed from main pom file

**Comment by mshabarov** [comment]
This profile is used at least in `Flow & Fusion - Release` build [Step 9 config](https://bender.vaadin.com/admin/editRunType.html?id=buildType:FlowRelease&runnerId=RUNNER_783&cameFromUrl=%2Fadmin%2FeditBuildRunners.html%3Fid%3DbuildType%253AFlowRelease%26init%3D1&cameFromTitle=):
```
-B -e -V -DskipTests -DskipITs -Djetty.skip -Dgatling.skip -P validation,release,%staging.profile%,flatten-pom -DstagingRepositoryId=%staging.repository.id% 
-DretryFailedDeploymentCount=3
```

However, I don't know whether it's something we didn't clean up, or it's really needed.
@ZheSun88 do you have any ideas whether this profile is really used?

**Comment by ZheSun88** [comment]
this usage is actually wrong, as maven doesn't allow you to remove modules via calling profiles, while you can use profile to add more needed modules. 

this profile is not needed. this can be easily verified by checking the released [flow-polymer-template}(http://tools.vaadin.com/nexus/content/repositories/vaadin-prereleases/com/vaadin/flow-polymer-template/)

**Comment by mshabarov** [comment]
Profile removed.
