### ISSUE TITLE
Vaadin 14.7: Theme variant not applied on all views

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#11896]
### Description of the bug / feature

Given you have an `LoginView.java` that does NOT extend `MainLayout.java` and use `@Theme(themeFolder = "myapp", variant = "dark")` on the `MainLayout` to apply the dark theme on your whole app. Since 14.7.0 the `LoginView.java` is not properly styled anymore.

14.6.8:
 - `LoginView` and all Views that uses `MainLayout` are dark

14.7.0:
- `LoginView` has the default coloring
- All other Views extending `MainLayout` are dark

### Workaround?
 - Adding `@Theme(themeFolder = "myapp", variant = "dark")` to `LoginView` would solve the problem.. but this should not even work; looking at the javadoc of `@Theme` says: "Defining different Themes for different views will end throwing an exception." (That's not happening.)

### Minimal reproducible example

- Download [bug-1470.zip](https://github.com/vaadin/flow/files/7196495/bug-1470.zip)
- mvn 
- open localhost:8080 (light theme) // open localhost:8080/about (dark theme)

![image](https://user-images.githubusercontent.com/3968629/134021615-d2354f9b-8666-4da0-af66-ce56840aed47.png)
![image](https://user-images.githubusercontent.com/3968629/134021715-fa7c73af-8eaa-446f-8121-7ce26fc9fc4e.png)

### Expected behavior

The whole application should be dark-themed.

Question: Where should the `@Theme` annotation be added? There is no "common"  route or layout here.

### Actual behavior

14.7.0:
- `LoginView` has the default coloring
- All other Views extending `MainLayout` are dark

### Versions:
    - Vaadin / Flow version: 14.7.0 (development & production mode)
    - Java version: ---
    - OS version: Ubuntu 20.04
    - Browser version (if applicable): Firefox
    - Application Server (if applicable): ---
    - IDE (if applicable): ---

**Comment by ado2000** [comment]
Are there any workaround waiting the fix ?
Thanks

**Comment by knoobie** [comment]
@ado2000 see my heading "Workaround?" above.. it shouldn't work.. but it works..

**Comment by knoobie** [comment]
@mshabarov I think I found the problem - it's an javadoc issue? 

Looking at 2.7's `@Theme` javadoc:

```java
 * Defines that there is a theme to use and defines the theme handler
 * implementation.
 * <p>
 * {@link Theme} annotation should be added to your root navigation level,
 * {@link RouterLayout} or to the top level @{@link Route}.

```

So I exactly did this; adding the annotation to our layout. But in the current master it says:

```java

 * Defines the theme to use for the application. Should be present only once for
 * an app, in the `AppShellConfiguration` class.

```

That could explain the problem.. could it be possible that some changes that "enforcing" this behaviour / usage was backported to 2.7 but the javadoc wasn't updated?
