### ISSUE TITLE
Different instances of TemplateRenderer reuse the same property values

### ISSUE THREAD

**Issue by schwarzwald** [vaadin/flow#11897]
### Description of the bug / feature
When a grid has multiple columns which use different instances of TemplateRenderer with templates which use the same property names, but with different value providers, the provided values for one of the columns are reused for the second column even if the value provider is different
### Minimal reproducible example
```
private void createGrid() {
  Grid<TestBean> grid = new Grid<>();

  grid.addColumn(TemplateRenderer.<TestBean> of("<span>caption 1 - [[item.caption]]</span>")
      .withProperty("caption", t -> t.getName()));
  grid.addColumn(TemplateRenderer.<TestBean> of("<span>caption 2 - [[item.caption]]</span>")
      .withProperty("caption", t -> String.valueOf(t.getId())));

  int size = 100;
  List<TestBean> data = new ArrayList<>(size);
  for (int i = 0; i < size; i++) {
    data.add(new TestBean(i, "Name " + i));
  }

  grid.setItems(data);
  grid.setSizeFull();
  add(grid);
}

private static class TestBean {

  private Integer id;
  private String name;

  public TestBean(Integer id, String name) {
    this.id = id;
    this.name = name;
  }

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }
}
```
### Expected behavior
Each instance of TemplateRenderer should keep it's own map of values and it should not assume that the same property maps to the same value.
### Actual behavior
Both columns display the same values despite having different value providers.
### Versions:
    - Vaadin / Flow version: Vaadin flow (MPR) version 21
    - Java version: 8

**Comment by knoobie** [comment]
This reminds me of #8629

**Comment by schwarzwald** [comment]
> This reminds me of #8629

Thanks. That is exactly the same bug.
