### ISSUE TITLE
Increase of warm startup time of Vaadin in 14.7.0 compared to 14.6.9

### ISSUE THREAD

**Issue by martaolszewskatusiek** [vaadin/flow#11910]
### Description of the bug / feature
The warm startup time of V14.7 nearly doubled in comparison with V14.6.9. 

### Minimal reproducible example
Any 
### Expected behavior
The warm starup time should not increase that much between versions, if at all
### Actual behavior
Example times:
```
14.6.9 - [INFO] Started @5440ms
14.7.0 - [INFO] Started @11166ms
```
According to discussion with @fluorumlabs and @mshabarov it is most likely due to the `npm install` being run twice. 

https://github.com/vaadin/flow/blob/6b28d464715b59a096a7f388564d94fe4aab2ceb/flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java#L133

> Now, in 14.7.0 this flag packageUpdater.modified is always true, because updatePackageJsonDependencies in TaskUpdatePackages adds some dependencies and modifies package.json.

> Apparently it adds the pinned platform dependencies according to this change https://github.com/vaadin/flow/pull/11567

Most likely a regression. 
### Versions:
    - Vaadin / Flow version: V14.7.0

**Comment by caalador** [comment]
Is this still an issue if you run with 14.7-SNAPSHOT after #11893 was merged yesterday?

**Comment by mshabarov** [comment]
Yes, running the application with flow 2.7-SNAPSHOT resolves the problem and flow skips `npm install` now.

**Comment by denis-anisimov** [comment]
So , @caalador , @mshabarov , is this fixed and cam be closed ?

**Comment by mshabarov** [comment]
@martaolszewskatusiek could you please test on your side by using flow `2.7-SNAPSHOT`?

**Comment by martaolszewskatusiek** [comment]
Retested. On V14.7-SNAPSHOT it is `Skipping npm install`, while on V14.7.0 it is `Running `npm install` to resolve and optionally download frontend dependencies.`

Works as expected.

**Comment by mshabarov** [comment]
Thanks Marta, I close this issue then.
