### ISSUE TITLE
When using a site with a modern browser I want to load no extra polyfills so that my experience is not degraded because some people use old browers

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#1192]
https://philipwalton.com/articles/loading-polyfills-only-when-needed/ describes this strategy that you should optimize for modern browsers and penalize the old browsers instead of penalizing everyone because some people use old technology

**Comment by mshabarov** [comment]
For the latest Vaadin versions (23, 24) we have only polyfills for `construct-style-sheets-polyfill` and DnD for mobile. Is this issue still needed, WDYT?
