### ISSUE TITLE
Gradle: Fix dependency resolution

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#11943]
The Gradle plugin needs to gather all jars in order to perform a classpath scan and analyze the npm-related java annotations.

Currently, this is done in the `vaadinPrepareFrontend` task: a set of dependencies is figured out, from that a set of projects, from that a set of `assemble` tasks producing those jars. However, this does not work reliably:

1. Doesn't work for transitive `implementation` dependencies
2. Doesn't work if the jar file was not produced by `assemble` task.

Solution is to simplify the code and take advantage of the fact that Gradle can depend on a FileCollection. The line in the `VaadinPrepareFrontendTask` class will then simplify to

`dependsOn(project.configurations.runtimeClasspath.jars)`

```kotlin
/**
 * Returns the "runtimeClasspath" file collection.
 */
internal val ConfigurationContainer.runtimeClasspath: Configuration
    get() = getByName("runtimeClasspath")

/**
 * Returns only jar files from given file collection.
 */
internal val Configuration.jars: FileCollection
    get() = filter { it.name.endsWith(".jar", true) }
```

See this commit for more details: https://github.com/vaadin/vaadin-gradle-plugin/commit/62211dfe80ea824a782d46ef3da1c1c7aabf37f5

### (Possible) steps to reproduce: ###

Have a Gradle multiproject which contains WAR project which implementation-depends on another project which implementation-depends on another project. At the moment the plugin will not not depend on the third project but will still try to read the outcome jar of that project, leading to the following exception:

```
Caused by: java.lang.IllegalStateException: xyz.jar doesn't exist
        at com.vaadin.gradle.GradlePluginAdapter.getClassFinder(GradlePluginAdapter.kt:68)
        at com.vaadin.flow.plugin.base.BuildFrontendUtil.prepareFrontend(BuildFrontendUtil.java:137)
        at com.vaadin.gradle.VaadinPrepareFrontendTask.vaadinPrepareFrontend(VaadinPrepareFrontendTask.kt:71)
```

**Comment by denis-anisimov** [comment]
`VaadinPrepareFrontendTask` is in the  vaadin/vaadin-gradle-plugin repo along with the gradle plugin code.
So should this ticket be created in this repo instead ?
Should I move it there?

**Comment by mvysny** [comment]
Please keep the ticket here:

* The plugin at https://github.com/vaadin/vaadin-gradle-plugin is an unofficial Vaadin Gradle plugin only intended for Vaadin 14 LTS. I'm maintaining this plugin.
* The plugin at https://github.com/vaadin/flow/tree/master/flow-plugins/flow-gradle-plugin is a fork of the plugin above; it is officially supported by Vaadin and intended for Vaadin 20+. This plugin is maintained by Vaadin.

I have performed the fix on the unofficial plugin; however the same fix needs to be performed on the official plugin as well.

**Comment by denis-anisimov** [comment]
Ah, OK.
Thanks for explanation.
