### ISSUE TITLE
Generate index.html into the frontend folder

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#11957]
### Description of the bug / feature
Currently an `index.html` file is generated into `target` if non is present in `frontend`. There are very few benefits with this, it mostly makes it harder to understand how to customize the bootstrap page when you e.g. want to add some meta tags.

### Expected behavior
It should be generated into `frontend` instead.

**Comment by knoobie** [comment]
What do you think about `frontend/generated` instead like already used for `theme.js` and other files. This could simplify the logic for the user as well. You want your own `index.html`? Create one at `frontend/index.html` otherwise the `frontend/generated/index.html` is used by the framework.

**Comment by Artur-** [comment]
I am not sure hiding it in another place actually solves anything

**Comment by Artur-** [comment]
If you do not want to see or customize it, you can always add it to .gitignore or similar
