### ISSUE TITLE
Better object list binding

### ISSUE THREAD

**Issue by wfischlein** [vaadin/flow#1203]
In a TemplateModel when passing a list of elements of any type to the frontend I want to receive a list of these objects in an @EventHandlker method so that I can directly e.g. persist these values.
Value-copying back-and-forth boilerplate is extra, best approach would be:
require a unique identifier in list elements, magically keep references in hummingbird and pass same instances in @EventHandler method to not have any copy-boilerplavte at all

**Comment by pleku** [comment]
Closing issue due to lack of demand. Not sure if this is an issue even anymore since there has been a lot of improvements to template model since this. Anyway if this would be problem, it should surface again.
