### ISSUE TITLE
[Vite] Typescript support

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#12056]
(Possibly a no-op ticket, just recording it for verification purposes)

### How does it work today

- ForkTsCheckerWebpackPlugin
    - #10656
- Esbuild-loader for using typescript

### How could it work

- Vite handles this by default. So boring.

**Comment by joheriks** [comment]
Did not come across any issues with the TS transpilation, it just works. A noticeable difference when developing with DX compared to Webpack with plugins is the lack of type-checking (so you do not see any type errors in the console). But this is expected as typechecking is expected to e an IDE task anyway (https://vitejs.dev/guide/features.html#typescript).
