### ISSUE TITLE
[Vite] Export web components must work

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#12057]
### How does it work today

- An "export" bundle is created with everything used from exported components - this needs to be verified
    - For each WebComponentExporter a .js file is generated into {build.folder}/frontend and added as an import statement to the generated-flow-imports.js

### How could it work

- In a similar way by creating multiple bundles

**Comment by caalador** [comment]
Note. The current exported webcomponents uses v14 bootstrapping so it depends on stats.json to get the bundlefile name.

**Comment by caalador** [comment]
The exported component would seem to work as long as the `BootstrapHandler::appendNpmBundle` is made to get the correct bundle file. In production mode we could at the moment probably read that from the classpath, but where could we get the info in development mode?
Should we parse the index.html for all the required bundles perhaps?
