### ISSUE TITLE
[Vite] PWA support

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#12052]
PWA support is defined by 3 aspects:

- Web manifest
- Service worker
- Offline configuration

### How it works today
ServiceWorkerPlugin using InjectManifest for PWA (using workbox)

### How could it work
Service worker should be generated with the same configuration using the same workbox version

Note: offline support is something that might need to work in "webpack mode" for simplicity, if it doesn't work out of the box.

**Comment by gilberto-torrezan** [comment]
The web manifest doesn't concern webpack at all, but the service worker and the offline configuration does.

We are already using workbox to process the output from webpack, so _in theory_ it would be just a matter of processing the output of vite instead for this to work. Needs investigation.

**Comment by gilberto-torrezan** [comment]
The offline support will be tracked as a separate ticket: https://github.com/vaadin/flow/issues/12383

**Comment by joheriks** [comment]
PWA in dev mode is tracked in #12393.
