### ISSUE TITLE
[Vite] Serving static assets previously produced by webpack

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#12053]
The `manifest.json` is generated with WebpackManifestPlugin.

The purpose behind it is so that webpack could tell Flow what are exactly the paths to static frontend assets it produces.

webpack may output static files not only for the well-known directory prefix (like /VAADIN/static/... ), but also to serve from root (like /sw.js), because:

- it must put the service worker to the root, due to offline support,
- ultimately only webpack reliably knows what the static file paths are — the config is exposed to users

Before `manifest.json` was introduced, Flow used a hard-coded collection of well-known directory prefixes for static files. Now it additionally uses information from `manifest.json` to serve whatever files webpack wants to serve.

This `manifest.json` is a bundled webpack plugin, kind of a standard way for webpack to emit the list of output files.

Note:
The whole concept requires a frontend compilation pass, so it may not apply to Vite at all. Requires some testing though.

**Comment by gilberto-torrezan** [comment]
There's a chance that we actually don't need the `manifest.json` at all, if serving a folder with static files would work just as good. This requires some investigation.

**Comment by Artur-** [comment]
This was fixed in #12278
