### ISSUE TITLE
Component's ShadowRoot is null on attach when navigating from a Typescript view.

### ISSUE THREAD

**Issue by tulioag** [vaadin/flow#12080]
### Description of the bug / feature
Consider this view
```java
@Route(value = "shadow")
public class ShadowView extends VerticalLayout {

    public ShadowView() {
        TextField field = new TextField();
        field.addAttachListener(ui -> field.getElement().executeJs("alert(this.shadowRoot)"));
        add(field);
    }
}
```
If you navigate to this view from a typescript view, the `shadowRoot` will be null. Otherwise it will be available.

A more complex example:
1. Download the project from https://start.vaadin.com/?preset=all&preset=partial-prerelease
2. Go to one of typescript views
3. Go to the collaborative-master-detail-view
4. See that an error is shown.

![ce-issue](https://user-images.githubusercontent.com/28783969/137770030-330548b5-a702-41cf-858c-cfe939eca09c.gif)

The errors are caused by the field-highlighter trying to access the components shadow roots.

### Minimal reproducible example
[my-app.zip](https://github.com/vaadin/flow/files/7367000/my-app.zip)
1. Run the application
2. Click in "Shadow". 
3. Verify that the alert shows `[object ShadowRoot]`
4. Click in "Hello TS"
5. Click in "Shadow". 
6. Verify that the alert shows `null`
### Expected behavior
The alert should show `[object ShadowRoot]` in all cases.

### Versions:
    - Vaadin / Flow version: 22.0.0.alpha8/9.0.0.alpha10
    - Java version: 8, 17
    - OS version: Linux, MacOs

**Comment by Artur-** [comment]
The test case can actually be simplified to
```
public class ShadowView extends VerticalLayout {
    public ShadowView() {
        getElement().executeJs("alert(this.shadowRoot)");
    }
}
```
