### ISSUE TITLE
Resynchronizing on browser triggered after discrepancy on server id when using long polling

### ISSUE THREAD

**Issue by nubitic-admin** [vaadin/flow#12093]
### Description of the bug
When using Long pooling as the push transport the browser triggers a Resynchronization 'cause something increments the `server id` on the server causing a difference between the id expected on the browser and the one returned by the server. Causing an infinite loop of resynchronization requests
### Minimal reproducible example
We've uploaded a minimal maven project in which the bug is replicated in here [https://github.com/nubitic-admin/vaadin-long-polling-bug](https://github.com/nubitic-admin/vaadin-long-polling-bug)

The bug triggers only on the first interaction with the application, for example at application start you can go to http://localhost:8080 and click on the "Operación" field if after this you open another browser or incognito tab the bug happends no more.

![Operacion Evidence](https://github.com/nubitic-admin/vaadin-long-polling-bug/blob/main/evidences/MainView.png?raw=true)

### Expected behavior
No Resynchronization triggered 
### Actual behavior
Resynchronization triggered causing an infinite loop of resynchronization requests
![Resynchronization triggered Evidence](https://github.com/nubitic-admin/vaadin-long-polling-bug/blob/main/evidences/DiscrepancyOnBrowserTriggeredOnEstablishingPushConnection.png?raw=true)
We had tracked down the issue on the request establishing the push connection
![EstablishingPushConnection Evidence](https://github.com/nubitic-admin/vaadin-long-polling-bug/blob/main/evidences/EstablishingPushConnection.png?raw=true)
In which this code is executed but the new id is not informed to the browser hence the discrepancy on the next requests
![UidlWriterIncrementingServerIdOnPushConnection Evidence](https://github.com/nubitic-admin/vaadin-long-polling-bug/blob/main/evidences/UidlWriterIncrementingServerIdOnPushConnectionGeneratingDiscrepancy.png?raw=true)

We have uploaded the console log output and the har file of the interaction between the browser and the server:
[console log](https://raw.githubusercontent.com/nubitic-admin/vaadin-long-polling-bug/main/evidences/localhost-1634679402871.log)
[har file](https://github.com/nubitic-admin/vaadin-long-polling-bug/raw/main/evidences/localhost-nok.har)

### Versions:
    - Vaadin / Flow version: 14.7.2 / 2.7.2
    - Java version: 11, 8
    - OS version: Fedora 32
    - Browser version (if applicable): Any
    - Application Server (if applicable): Embedded Tomcat Spring Boot
    - IDE (if applicable): STS 4

**Comment by mcollovati** [comment]
This should have been fixed in Vaadin 24 by #15517, #15764 and #16660
