### ISSUE TITLE
Opera 49 should be detected as too old to funciton properly

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow#12131]
### Description of the bug / feature
If you try to access a V21 app with an older Opera version that is greater than 34, you will not get the "I'm sorry, but your browser is not supported". This seems to happen because BrowserDetails::isTooOldToFunctionProperly checks
```
        if (isOpera() && getBrowserMajorVersion() < 34) {
            return true;
        }
```
while the usage of `globalThis` breaks Opera < 57: https://caniuse.com/?search=globalthis

### Minimal reproducible example

Download Opera 49 from:
https://get.geo.opera.com/pub/opera/desktop/

Go to
https://collaboration-engine.demo.vaadin.com/

### Expected behavior

"I'm sorry, but your browser is not supported" should be shown. Opera is not a supported browser regardless, so maybe it could even be for all Opera versions.

### Actual behavior

A blank page is shown. 
Browser console says
```
Uncaught ReferenceError: globalThis is not defined at Object.<anonymous> (vaadin-bundle-59cec6a9f962ac280921.cache.js:23) at r (vaadin-bundle-59cec6a9f962ac280921.cache.js:1) at Object.<anonymous> (vaadin-bundle-59cec6a9f962ac280921.cache.js:1) at r (vaadin-bundle-59cec6a9f962ac280921.cache.js:1) at Object.<anonymous> (vaadin-bundle-59cec6a9f962ac280921.cache.js:101) at r (vaadin-bundle-59cec6a9f962ac280921.cache.js:1) at Module.<anonymous> (vaadin-bundle-59cec6a9f962ac280921.cache.js:499) at r (vaadin-bundle-59cec6a9f962ac280921.cache.js:1) at vaadin-bundle-59cec6a9f962ac280921.cache.js:1 at vaadin-bundle-59cec6a9f962ac280921.cache.js:1 (index):1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker: An SSL certificate error occurred when fetching the script.
```
### Versions:
    - Vaadin / Flow version: 21.0.2
    - Java version: n/a
    - OS version: n/a
    - Browser version (if applicable): Opera 49
    - Application Server (if applicable): n/a
    - IDE (if applicable): n/a

**Comment by joheriks** [comment]
Need to update browser minimum versions in `BrowserDetails::isTooOldToFunctionProperly ` to match https://caniuse.com/?search=es6

**Comment by darmro** [comment]
It could be not enough for Vaadin 21. I've checked that for Vaadin 21.0.3  app there is an empty page shown even for Chrome 65, with the error in the console:
![image](https://user-images.githubusercontent.com/56316289/140968442-a08452fc-8b1e-463d-8760-9cdc1af79e24.png)

But Chrome 65 supports ES6, according to  [ https://caniuse.com/?search=es6](https://caniuse.com/?search=es6)

**Comment by OlliTietavainenVaadin** [comment]
I believe this is more relevant than ES6: https://caniuse.com/?search=globalThis

**Comment by Artur-** [comment]
We should sync `UnsupportedBrowserHandler` with what we support and not what may happen to work today. For example for Chrome, we support the evergreen version, that is 95 today. 

It does not make sense to look at individual features as we are developing new features based on the support versions so even if Chrome XY happens to work today, it might be broken tomorrow after a bugfix.

**Comment by OlliTietavainenVaadin** [comment]
Only supporting the very latest (at the time of a release) seems a bit overkill. Many organizations only update software manually, including browsers, so requiring the latest evergreen version would cause problems for anyone who is on a perfectly fine browser that just happens to be one or two versions behind.

**Comment by Artur-** [comment]
That is a separate discussion. The supported browsers are listed here https://github.com/vaadin/platform/releases/tag/21.0.0

**Comment by OlliTietavainenVaadin** [comment]
Just to state the, perhaps, obvious: there are three different categories of browsers: 
1) Supported (most users should be here)
2) Unsupported, but fully or mostly working because of luck
3) Unsupported, and catastrophically not working

As time passes, with the introduction of certain features in the framework and the components, category 3 grows to eat more of category 2, as older browsers will refuse to do anything when faced with unknown syntax. This is fine and expected, being able to use new features is behind the whole idea of explicitly only supporting new enough browsers. IMO the "too old to function properly" feature should be used to inform users of category 3 that they have no chance of opening the app. Updating the browser list reactively (when people report breakages) seems like a reasonable compromise, and maybe less work than updating the list regularly?

**Comment by joheriks** [comment]
So let's bump the limit in `isTooOldToFunctionProperly()` to the latest versions that support `globalThis`, and then verify that there are no issues with Chrome 71, FF 65 and Opera 58).

**Comment by darmro** [comment]
For the users of our app (unknown, they're not our workers) when they're using any browser on any OS (e.g the latest Chrome 65 on iOS 10.1 ;) the main need is to get proper info on the screen, when the browser is to old. For now they get blank page and they are confused. We cannot expect they are using evergreen browser :) We of course inform them in our "terms of use" what are the min requirements, but they got an empty page from vaadin core, they dont even seen our link with "terms of use".

**Comment by anssit** [comment]
> So let's bump the limit in `isTooOldToFunctionProperly()` to the latest versions that support `globalThis`, and then verify that there are no issues with Chrome 71, FF 65 and Opera 58).

Additional issue was found in Firefox versions 65 to 77: #12442
