### ISSUE TITLE
Fallback chunk for Vite production build

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#12170]
When making a production build with Webpack, a separate entry point (`target/frontend/generated-flow-imports-fallback.js`) creates a chunk containing all components JS (in addition to those scanned from the project classes), and the resulting `fallback` chunk is dynamically loaded with custom Javascript in the normal bundle entry point (`generated-flow-imports.js`) (#6482). This should should be supported by Vite as well.

**Comment by gilberto-torrezan** [comment]
The first step would be to try to replicate what works for webpack, and take it from there.
