### ISSUE TITLE
Nullpointer related to Shortcuts

### ISSUE THREAD

**Issue by probert94** [vaadin/flow#12198]
### Description of the bug / feature
In a project I am working on, I am facing an issue related to the `ShortcutRegistration` in vaadin.
Basically, when I execute a `Shortcut` while a new `ShortcutListener` is getting registered, I get the following exception:
```
java.lang.NullPointerException
		at elemental.json.impl.JreJsonObject.getBoolean(JreJsonObject.java:92)
		at com.vaadin.flow.internal.nodefeature.ElementListenerMap$DomEventListenerWrapper.matchesFilter(ElementListenerMap.java:210)
		at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:437)
		at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62)
		at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:66)
		at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:412)
		at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$1(ServerRpcHandler.java:393)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
		at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:393)
		at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:320)
		at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:115)
		at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
		at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1535)
		at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:299)
```

In my case, I have a `F2` shortcut, which opens the selected object in a `Dialog`. The `Dialog` itself registers a `ctrl+s` shortcut to save changes on the current object. When I double-press the `F2` key, I get the mentioned exception.
Basically `JreJsonObject.getBoolean` throws a `NullPointerException`, because the given key does not exist in the `JsonObject`.
The key in this special case seems to be the filter of the `ctrl+s` shortcut:
`(['s'].indexOf(event.code) !== -1 || ['s'].indexOf(event.key) !== -1) && !event.getModifierState('Shift') && event.getModifierState('Control') && !event.getModifierState('Alt') && !event.getModifierState('AltGraph') && !event.getModifierState('Meta') && (event.preventDefault() || true) && (event.stopPropagation() || true)`

While debugging, I found that the `EventData` of the `ShortcutEvent` contains the filter of all registered `Shortcuts` as a key, with the related boolean value (filter matches). The filter key for the `ctrl+s` shortcut is obviously missing, as that `Shortcut` is only registered in the `Dialog`, which is not open yet.
So my guess is, that the exception occurs, because the second `ShortcutEvent` is created on the client **before** the `ctrl+s` shortcut is registered, but the server evaluates it **after** the `ctrl+s` shortcut is registered.

### Minimal reproducible example
This is probably a timing-problem and unfortunately I was not able to reproduce it (yet).
I'll update the issue if I am able to create a minimal reproducible example but I hope my explaination helps you to find the cause.

### Versions:
    - Vaadin / Flow version: 20.0.6
    - Java version: 11.0.10 AdoptOpenJDK
    - OS version: Windows 10 64bit
    - IDE (if applicable): IntelliJ IDEA

**Comment by pleku** [comment]
Hello. When testing with 22.0.0.beta2, I'm **not** able to reproduce this with the following code:
```java
    @Override
    protected void onAttach(AttachEvent attachEvent) {
        super.onAttach(attachEvent);
        attachEvent.getUI().addShortcutListener(this::openDialog, Key.F2);
    }

    private void openDialog(ShortcutEvent event) {
        final Dialog dialog = new Dialog();
        final Button close = new Button("Close", clickEvent -> dialog.close());
        close.addClickShortcut(Key.KEY_S, KeyModifier.CONTROL).setBrowserDefaultAllowed(false);
        dialog.add(new VerticalLayout(close));
        dialog.open();
    }
```
Nor when adding the second shortcut to `UI` instead with
```java
        event.getSource().getUI().ifPresent(ui -> ui.addShortcutListener(e -> dialog.close(), Key.KEY_S, KeyModifier.CONTROL).setBrowserDefaultAllowed(false));
```

Please provide the code and the exact steps to reproduce so we may fix the issue.

> While debugging, I found that the EventData of the ShortcutEvent contains the filter of all registered Shortcuts as a key, with the related boolean value (filter matches). The filter key for the ctrl+s shortcut is obviously missing, as that Shortcut is only registered in the Dialog, which is not open yet.
So my guess is, that the exception occurs, because the second ShortcutEvent is created on the client before the ctrl+s shortcut is registered, but the server evaluates it after the ctrl+s shortcut is registered.

This description makes no sense to me - when you create a shortcut, everything is setup on the server side first and only then the information about the DOM listener with the filter (for the key) is sent to the client side. When the event comes from the client side, everything is already there on the server side. So please provide the minimal code to reproduce it so no time is wasted on trying to guess, thanks.

**Comment by Springrbua** [comment]
I was finally able to reproduce the issue in a new vaadin starter with a `EmptyView` with the following code:

```
@PageTitle("Empty")
@Route(value = "empty", layout = MainLayout.class)
@RouteAlias(value = "", layout = MainLayout.class)
public class EmptyView extends VerticalLayout {

    private Registration gridShortcutRegistration = () -> {};
    private Registration gridShortcutRegistration2 = () -> {};

    private final Grid<User> grid;
    private final List<User> userList;

    public EmptyView() {
        grid = new Grid<>();
        grid.addColumn(u -> u.id).setHeader("ID");
        grid.addColumn(u -> u.name).setHeader("Name");
        grid.addColumn(u -> u.age).setHeader("Age");
        grid.asSingleSelect().addValueChangeListener(e -> {
            gridShortcutRegistration.remove();
            User item = e.getValue();
            if (item != null) {
                gridShortcutRegistration = Shortcuts.addShortcutListener(
                    this, () -> editEntry(item),
                    Key.F2
                ).listenOn(grid);
            }
            else
                gridShortcutRegistration = () -> {};
        });
        userList = new ArrayList<>();
        IntStream.range(1, 10)
            .mapToObj(id -> new User(id, "User" + id, (int)(Math.random() * 80 + 20)))
            .forEach(userList::add);
        add(grid);
        grid.setItems(userList);
    }

    private void editEntry(User entry) {
        gridShortcutRegistration2.remove();
        gridShortcutRegistration2 = Shortcuts.addShortcutListener(this, () -> delete(entry), Key.DELETE).listenOn(grid);
        Notification.show("Editing entry");
        try {
            // Simulating a slow operation
            Thread.sleep(500);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void delete(User user) {
        userList.remove(user);
        grid.setItems(userList);
    }

    private static class User {
        private final int id;
        private final String name;
        private final int age;

        private User(int id, String name, int age) {
            this.id = id;
            this.name = name;
            this.age = age;
        }
    }
}
```

**Steps to reproduce:**

1. Download a new Starter with an `EmptyView`
2. Copy the above code into the `EmptyView`
3. Start the application 
4. Select an entry in the grid and press `F2` fast a few times in row
5. Check the console, you will get the mentioned exception.

**Notes**
The use case in this example is the following:
You have a grid with entries. You can select an entry and enable the edit mode for it, by using the `F2` key.
When an entry enters the edit mode, a shortcut to delete the entry is registered.
Entering the edit mode is a slow operation, this is simulated with a `Thread.sleep`.
This is very important in this case, as the issue is not reproduceable without it.
