### ISSUE TITLE
Make HeartbeatListener public (moving outside of internal package)

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#12295]
### Feature Request
Currently the `HeartbeatListener` is inside the internal package "intended for internal use by the framework" which in turn implies, that it's not save to use in the long run, therefore I would request to make `HeartbeatListener` public.

Reasoning: In the past (v8) there were a lot of application that used to overwrite the `HeartbeatHandler` to calculate the time of idle in an application to show e.g. a counter to the user or some form of "idle warning". This used to be kinda invasive, because a lot of classes had to be extended. 

For example, the VaadinServletService with:
```java

  @Override
  protected List<RequestHandler> createRequestHandlers() throws ServiceException {
    List<RequestHandler> handlers = super.createRequestHandlers();
    for (int i = 0; i < handlers.size(); ++i) {
      if (handlers.get(i) instanceof HeartbeatHandler) {
        handlers.set(i, new CustomHearthbeatHandler());
      }
    }
    return handlers;
  }

```

Now that flow has a dedicated listener for such events in form of `HeartbeatListener` - I would like to use this, instead of overwriting yet again a lot of classes. This listener could be moved to the other listener like `UIInitListener` inside `VaadinService` or made accessible through the `UI`.

**Comment by pleku** [comment]
I think introducing an API for registering your own `HeartbeatListener` should be quite straight forward. The only (?) internal usage is for cleaning up embedded Flow apps. The public API in `UI` could be made to maybe just delegate to the internal one. Probably some simple IT should be added too that validates that it works also elsewhere than in embedded app cleanup case.

**Comment by knoobie** [comment]
@pleku I can work on that for flow 10 / v23. I wanted to make sure you guys are on board, because I would probably move the listener one package up  (outside of the internal package) and next to all other events and listeners.

**Comment by pleku** [comment]
@knoobie we chatted with the team and you can go for it 👍🏻
