### ISSUE TITLE
Grid resort on item field change

### ISSUE THREAD

**Issue by lanmaster** [vaadin/flow#12332]
Using Vaadin 14. 
Trying to create own `DataProvider` based on `CallableDataProvider`. It use `Javers` to detect changes in data fetched from service based on current sort orders, limit and offset. If data list change its order of items, or added new item or removed item then i call `refreshAll()`. Else if there is only some items changed its fields then i call `refreshItem()` on each. It works good. But how can i refresh grid when it has some sorted columns and some item has changed data in sorted column? I try to invoke `com.vaadin.flow.component.grid.Grid#setSortOrder` with current Grid's orders, but in `com/vaadin/vaadin-grid-flow/14.7.1/vaadin-grid-flow-14.7.1-sources.jar!/com/vaadin/flow/component/grid/Grid.java:3086` there is code:
```
if (sortOrder.equals(order)) {
          return;
}
```
Orders equals and Grid didn't resort data on page. I can use something like that:
```
                                List<GridSortOrder<T>> updatedGridSortOrders = currentSortOrder
                                        .stream()
                                        .map(gridSortOrder -> {
                                            Grid.Column<T> sorted = gridSortOrder.getSorted();
                                            SortDirection direction = gridSortOrder.getDirection();
                                            return new GridSortOrder<>(sorted, direction);
                                        }).collect(Collectors.toList());
                                grid.sort(null);
                                grid.sort(updatedGridSortOrders);

```
but it looks hackish.
Point me in right direction, please.

**Comment by pleku** [comment]
Hi. Using `refreshAll` and `refreshItem` should be enough to make things refreshed for the grid - it is notified of the changed data by the framework and then it should update itself accordingly.

> But how can i refresh grid when it has some sorted columns and some item has changed data in sorted column?

This seems like a bug in the grid integration that it is not updating the sorting based on the updated data. In my opinion, it should happen automatically. I'm suspecting this is an issue in the grid-integration, but to be able to verify things, can you please create a minimal code sample that reproduces the issue ? You can use e.g. the generated code from start.vaadin.com or fork the project base from https://github.com/vaadin/skeleton-starter-flow.

**Comment by lanmaster** [comment]
Ok, I will make sample.

**Comment by lanmaster** [comment]
Only on creating error sample i see my error, i was not truly understand processing while Grid use CallBackDataProvider. Grid ask DataProvider for data and provide sort options, offset and limit. I see now. Thank you. Closed.
