### ISSUE TITLE
`executeJs(...).wait()` fails and thus can only be run asynchronously?

### ISSUE THREAD

**Issue by Osiris-Team** [vaadin/flow#12336]
### Describe the bug

I am trying to run JavaScript code and wait until it's finished when the user clicks on a button.

### Expected-behavior

No exception.

### Reproduction

Add the code below to your View/Page:
```java
            Button btn = new Button("Click me!");
            btn.addClickListener(click -> {
                try{
                    UI ui = UI.getCurrent();
                    ui.getPage().executeJs("var number = 1; // Random JS code")
                            .wait();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
```

### System Info

Windows 10
Vaadin 20.0.7

**Comment by Artur-** [comment]
`Object.wait`

```
Causes the current thread to wait until it is awakened, typically by being notified or interrupted.
```

This method has nothing to do with `executeJs`.

Overall, it is not possible to block until the JS has executed and returned a value. The JS is sent to the browser at the end of the request so you need to use `then` or another method defined in `PendingJavaScriptResult`
