### ISSUE TITLE
there are slow unit tests calling external tools

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#12343]
There are unit tests in flow-server running external commands  like `npm install` hence they depend on those tools installed, and they take a long while to run: 
```
FrontendToolsTest
TaskRunPnpmInstallTest
TaskRunNpmInstallTest
```
They should either:
- be moved to a `flow-tests` submodule
- fixed by mocking system calls
- be retained to a test category and be run as ITs

**Comment by caalador** [comment]
System calls can at least not be mocked as then we don't know if the features work with npm/pnpm which is quite integral in seeing that they install the expected packages
