### ISSUE TITLE
Since V14.6 Vaadin does not work with embedded Undertow server

### ISSUE THREAD

**Issue by envas** [vaadin/flow#12455]
### Describe the bug

Since the 14.6 update, the Vaadin server does not work when embedded in a fatjar together with the Undertow server. The server returns the response header

```
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Type: text/html;charset=UTF-8
Content-Length: 68
Date: Fri, 19 Nov 2021 16:17:48 GMT
```

and the page content

```
<html><head><title>Error</title></head><body>Forbidden</body></html>
```

I tried to replace Undertow with Jetty 9 and such a combination works well. 

### Expected-behavior

Vaadin should bootstrap the start page and show the content.

### Reproduction

I created a demo project based on the Vaadin starter here [https://github.com/envas/vaadin-starter-undertow-gradle](https://github.com/envas/vaadin-starter-undertow-gradle). 

### System Info

With the same results tested on macOS and embedded Linux with ARM processor (iMX8).

**Comment by Artur-** [comment]
Who responds with forbidden? I don't think a `VaadinServlet` ever responds with that

One thing that might be a problem is that there are a lot of classes marked with `@HandlesTypes` and you seem to only take one into account (`RouteRegistryInitializer`)

**Comment by envas** [comment]
I cannot say where forbidden is generated. I tried the solution from @Legioth published [here](https://github.com/Legioth/vaadin-without-classpath-scanning) and it did not help. Anyway, one point is pretty clear - the problem was generated when switching from 14.5 to 14.6.

**Comment by Legioth** [comment]
Seems like one additional step is needed starting from Vaadin 14.6: `LookupServletContainerInitializer` needs to be run with at least `LookupInitializer` as a detected class.

I've updated my example project with the latest version of Vaadin. The relevant change is in https://github.com/Legioth/vaadin-without-classpath-scanning/commit/83bec6fed5e970faa58537f2bfaa11c1a68b8360#diff-6844588c7ae8804c4aabad52129f21d0a98ed59b271bae012853fc7434b463dc.

**Comment by envas** [comment]
YES! That's right, with the `LookupInitializer` the Undertow embedded server starts as expected. I updated my Vaadin starter project on Github. Thanks for the support!
