### ISSUE TITLE
Rewrite GWT router link handler test for external non-existing link.

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#1245]
Travis CI was unreliable with this test uncommented due to https://github.com/gwt-maven-plugin/gwt-maven-plugin/pull/148

`testRouterLink_anchorWithExternalRouterLink_eventNotIntercepted` was removed in https://github.com/vaadin/hummingbird/commit/b2586433fece1db33d7dc3d3dc910853b7e08d6d#diff-287ca779df93d931916a932acdbc3bceL148

This test worked before upgrading to GWT 2.8.0 and stopped working afterwards.

Test itself creates <a href="http://localhost:120/bar"></a> with routerlink attribute and clicks on it, expecting failure because of non-existing link.

The problem is connected with new behavior that GWT and HtmlUnit have now: instead of propagating the JavaScriptException to the upper level to test itself, as it was before 2.8.0, HtmlUnit logs an exception and remains in a loop until gwt maven plugin terminates the process.
Before that, the exception was propagated.

I could not make HtmlUnit to throw exception again, neither I have any ideas how to rewrite the test.

**Comment by pleku** [comment]
Not using Travis for a long time so this is probably not an issue anymore.
