### ISSUE TITLE
Close the input stream eagerly in FrontendDependencies

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#12489]
### Description of the bug / feature

When building my project with Gradle, I'm sometimes getting this mysterious exception on JDK 8:

```
java.io.FileNotFoundException: JAR entry org/x/y/Z.class not found in /your/project/folder/build/libs/yourproject.jar
        at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.visitClass(FrontendDependencies.java:490)
        at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.collectEndpoints(FrontendDependencies.java:250)
        at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.computeEndpoints(FrontendDependencies.java:228)
        at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.<init>(FrontendDependencies.java:98)
```

The stack trace apparently makes no sense since it's pointing at the following line:
```
try (InputStream is = url.openStream()) { }
```

which leads me to believe there must be something nasty going on in the JVM itself (stack trace prunning or similar).

The issue goes away when I increase the limit of open files; please read https://mvysny.github.io/Vaadin-gradle-plugin-faq/ for more details. That leads me to believe that the input stream stays around opened for longer than it needs to.

The problem could be remedied by closing the input stream eagerly; essentially straight after the ClassReader is constructed and before `cr.accept(visitor, ClassReader.EXPAND_FRAMES);` is called.

### Minimal reproducible example
Unfortunately not easy to reproduce. You may need to have a huge project with a Gradle daemon being around for longer time.

### Expected behavior
The build should succeed.

### Actual behavior
Randomly the build fails in the `vaadinBuildFrontend` task with the abovementioned stacktrace.

### Versions:
    - Vaadin / Flow version: 14.7.5/2.7.4
    - Java version: 8
    - OS version: Ubuntu x86-64 21.10

**Comment by caalador** [comment]
Is the issue better after the addition of closing?

**Comment by mvysny** [comment]
@caalador I apologize, unfortunately I'm no longer working on that particular project and therefore I don't have the means to test the fix out.

**Comment by caalador** [comment]
@mvysny That's fine. I'll close this ticket as I fixed closing streams to all that I could find that might have left some open.
If this happens again just open a new ticket so that we can try to see where something might get left open.
