### ISSUE TITLE
Static resources not reachable in executable jar with spring boot 2.6.0

### ISSUE THREAD

**Issue by ElZorrito** [vaadin/flow#12482]
Hello,

### Description of the bug / feature
I try to upgrade my vaadin flow project (v14.7.5) to spring boot 2.6.0, but there is something wrong with static resources.
I place some images in /src/main/resources/META-INF/resources/, everyting is good when I launch project in my IDE (eclipse).
But when I package my app in a jar (mvn clean compile package -P production) and I run my jar (java -jar my-todo-1.0-SNAPSHOT.jar), resources are not reachable, I have a 404 in chrome browser for images.

### Minimal reproducible example
- Download quick start project at https://vaadin.com/docs/v14/flow/guide/quick-start
- Import my-todo maven project
- Add this piece of code in MainView.java : add(new Image("icons/icon.png", "")); (icon.png is present in /src/main/resources/META-INF/resources/)
- Package the project in a jar (mvn clean compile package -P production)
- Launch the jar : java -jar my-todo-1.0-SNAPSHOT.jar
- Open your browser, you can see that image is not reachable

I have same problem if I put resources in /src/main/resources/static folder (but it doesn't work when I launch with IDE or jar).

### Expected behavior
Loading resources properly
### Actual behavior
Resources not reachable from browser
### Versions:
- Vaadin / Flow version : 14.7.5
- spring-boot-starter-parent: 2.6.0
- Java version : 11 and 8
- IDE : eclipse-2020-09

**Comment by Artur-** [comment]
This was fixed in https://github.com/vaadin/spring/pull/944

**Comment by ElZorrito** [comment]
Thanks, sorry for the duplicate issue
