### ISSUE TITLE
Vaadin compability mode issue with version 14.7.6

### ISSUE THREAD

**Issue by janiinis** [vaadin/flow#12488]
### Description of the bug / feature
Vaadin compability mode is broken with version 14.7.6.

### Minimal reproducible example
Update Vaadin version from 14.7.1 to 14.7.6
Regrettably it's not possible to share source code or example.

### Expected behavior
There should not be crash when updating for newer version

### Actual behavior
java.lang.NoSuchMethodError: org.jsoup.nodes.Element.traverse(Lorg/jsoup/select/NodeVisitor;)Lorg/jsoup/nodes/Element;
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.inspectTwoWayBindings(TemplateDataAnalyzer.java:244)
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:233)
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:96)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:91)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:106)

### Versions:
    - Vaadin / Flow version: 14.7.6
    - Java version: OpenJDK 8.x
    - OS version: Windows 10
    - Browser version (if applicable): Chrome
    - Application Server (if applicable): Wildfly 20+
    - IDE (if applicable): Eclipse

**Comment by Artur-** [comment]
Vaadin 14.7.6  / Flow 2.7.3+ uses jsoup 1.14.3 which contains a security issue fix. It is not 100% compatible with older jsoup versions.

There is something in your project that brings in an older jsoup version, causing this issue.
`mvn dependency:tree` will show you which dependency brings the older version so you can upgrade that. Alternatively you can specify the jsoup dependency in the project but then you might face the same issue later if Flow upgrades to a newer jsoup version.

**Comment by janiinis** [comment]
Thanks, Azure Cognite services integration within application did use same library
Upgrading that to suggested version together with Vaadin version, did solve problem
