### ISSUE TITLE
Build generated-flow-imports.js incrementally in devevelopment mode

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#12497]
### Description of the bug / feature
It seems like `target/frontend/generated-flow-imports.js` is populated with all JS modules annotations that can be found in the whole project. This makes both webpack and vite slow as all files need to be processed before a hello world view with a button and a text field can be shown.

We could instead only add the needed js modules to the file and update it whenever a js module is used for the first time. This should speed up startup time significantly.

### Versions:
    - Vaadin / Flow version: 22

**Comment by Artur-** [comment]
A super quick test on a Start application shows webpack time is reduced from 21s to 7s.

**Comment by Legioth** [comment]
Does Vite need any imports at all in `generated-flow-imports.js`, or could it instead have genuinely dynamic imports without needing to rewrite files?

**Comment by Artur-** [comment]
Vite does auto chunking sometimes in development mode and will then trigger a reload automatically, so the reloads will happen from time to time

**Comment by Artur-** [comment]
How would you add an import without editing a file that is included in the compilation?

**Comment by Legioth** [comment]
`<script type="module">`

**Comment by Artur-** [comment]
How would this be better than adding an import to a generated file?

**Comment by Legioth** [comment]
I assume that editing an existing file causes a reload whereas importing a new file file wouldn't do a reload. But that's just my assumption.

**Comment by platosha** [comment]
Decided to mitigate the slow startup using container bundles of components and dependencies, see #12940 #12941
