### ISSUE TITLE
Inertness should be preserved after reload with `@PreservedOnRefresh`

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#12513]
An [upcoming feature](https://github.com/vaadin/flow/pull/12434) allows true modal dialogs, meaning that the components behind the modality curtain are inactive on the server side as well. Currently, this inertness of the server-side components is lost if a view  annotated with `@PreserveOnRefresh` is reloaded.

To reproduce:
- Extract the attached project and run it
- Exercise the working case:
  -  Go to `localhost:8080`
   - Click the `Add modal dialog` button to add a true modal dialog.
   - In the browser inspector, delete the `<vaadin-dialog>` and `<vaadin-dialog-overlay>` elements to disable the client-side modality curtain.
   - Try to interact with the underlying components ("Your name", "Say hello"), and observe that the server event handlers are not executed. 
- To reproduce the faulty case:
  - Go to `localhost:8080` (in a fresh tab / browser window)
  - Click the `Add modal dialog` button to add a true modal dialog.
  - In the browser inspector, delete the `<vaadin-dialog>` and `<vaadin-dialog-overlay>` elements to disable the client-side modality curtain.
  - Reload the page once.
  - Try to interact with the underlying components ("Your name", "Say hello"), and observe that the server event handlers *are* executed. 

Expected behavior: Inertness should be retained after reload with `@PreserveOnRefresh`, i.e., clicking on the button should not cause the server-side event handler to be executed.
[demo-app.zip](https://github.com/vaadin/flow/files/7650353/demo-app.zip)

**Comment by joheriks** [comment]
Note: blocked until #12434 is finalized and merged.

**Comment by caalador** [comment]
Closing ticket as not valid as removing the `<vaadin-dialog>` element will generate a close event for the dialog releasing the modality.
reloading page and removing `<vaadin-dialog-overlay>` will keep the server side modality in place.
