### ISSUE TITLE
OSGi support broken with Vaadin 22.0.0

### ISSUE THREAD

**Issue by jochenwalz** [vaadin/flow#12515]
### Description of the bug / feature
With Vaadin 22.0.0, the flow-osgi bundle does not pass the OSGi resolver.
### Minimal reproducible example
Startup any sample application with Vaadin 22.0.0 / Flow 9.0.0 / flow-osgi 7.0.0
### Expected behavior
No OSGi resolver issues on startup.
### Actual behavior
The MANIFEST.MF or flow-osgi imports flow packages with version="[7.0,9)", which excludes usage of Flow 9.0.0.
### Versions:
    - Vaadin / Flow version: 22.0.0/9.0.0
    - Java version: 1.8.0_312
    - OS version: openjdk:8-jre (Docker image)

**Comment by caalador** [comment]
There was a missing releaseso if you update osgi to 7.0.1 it should work again. The version will be updated in Vaadin 22.0.1

**Comment by jochenwalz** [comment]
7.0.1 now available in Maven central.
