### ISSUE TITLE
Switching from '@AnonymousAllowed' to ''@RolesAllowed({"user"}) does not trigger Spring Login

### ISSUE THREAD

**Issue by xasz** [vaadin/flow#12548]
### Description of the bug
Based on the Spring Starter Vaadin Flow example i added Spring Security via Keycloak.
If i only have `@PermitAll` and `@RulesAllowed(..)` Pages everything works fine and the login gets triggered on every Page i hit until i login. When i add an '@AnonymousAllowed' which seems to be a vaadin thing :) for example for an Welcome-Page and i set an anchor to an `@RolesAllowed` page the login does not appear until i activly refresh my browser.

### Minimal reproducible example
Download the Vaadin starter with 3 pages like this:
```
@PageTitle("Home")
@Route(value = "empty")
@RouteAlias(value = "")
@AnonymousAllowed
public class HomeView extends HorizontalLayout 
add(new Anchor("profile", "Please show me my profile"));
...
@PageTitle("Profile")
@Route(value = "profile", layout = MainLayout.class)
@PermitAll
public class ProfileView extends VerticalLayout 
...
@PageTitle("Settings")
@Route(value = "settings", layout = MainLayout.class)
@RolesAllowed("admin")
public class SettingsView extends VerticalLayout {
...

```
Setup Spring Security with whatever you have :) 

If u directly navigate to `/settings` or `/profile` with a new browserwindow, the login gets triggered.
On `/empty` login gets not trigged and get's not triggered when u hit the anchor.

### Expected behavior
A Login should appear.
### Actual behavior
The Could not navigate to 'settings' with the availible routes pages in dev-mode get's triggered.

### Versions:
    - Vaadin / Flow version: 21.0.7
    - Java version: 17
    - OS version: Windows 11
    - Browser version (if applicable): Chrome, Firefox, Edge
    - Application Server (if applicable): Tomcat 9 - (Vaadin Starter Settings)
    - IDE (if applicable): Visual Code

**Comment by Artur-** [comment]
Could you add the code as a zip or a GitHub repo?

**Comment by xasz** [comment]
I can, but will take some time to strip off some code around.

**Comment by mshabarov** [comment]
Closed due to no response from author. If this is still an issue, please reopen the ticket and provide more information.
