### ISSUE TITLE
Problems with dependencies

### ISSUE THREAD

**Issue by DDDenisSobek** [vaadin/flow#12554]
### Description of the bug
Hi!
We are currently building a Vaadin Application with Vaadin 21. We have different Views with multiple Elements which compile and work fine. But if we add spring mail and spring jooq to the depencies, the views throwing errors in the browser console:
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately. FlowClient.js:996
(TypeError) : $0.$connector is undefined
It seems that all views with a wrapping AppLayout throw such errors.
If we exclude one depency of the dependencies it works fine, we change nothing at the code, just add the dependency to reproduce the error.

### Minimal reproducible example
[Example Project](https://github.com/DDDenisSobek/VaadinProblemExample) - MariaDB needed

### Expected behavior
I should be able to add both dependencies without exceptions.

### Actual behavior
After adding spring mail and spring jooq all views with an app layout throws these exceptions:
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately. FlowClient.js:996
(TypeError) : $0.$connector is undefined

### Versions:
    - Vaadin / Flow version: 21.0.6
    - Java version: 11
    - OS version: Windows 10 Enterprise
    - Browser version (if applicable): Firefox 95.0
    - IDE (if applicable): IntelliJ IDEA 2021.3

**Comment by knoobie** [comment]
I remember a issue in that direction.. but couldn't find it anymore.. Did you try to add white- and blacklisted packages defined [here](https://vaadin.com/docs/v14/flow/integrations/spring/tutorial-spring-configuration#special-configuration-parameters) to reduce the classpath scanning to your own modules?

**Comment by caalador** [comment]
Hi. 
This sounds a lot like #11572 where the classpath was too long.

**Comment by DDDenisSobek** [comment]
Thanks for this hint. I added mavenLocal() to build.gradle and vaadin.whitelisted-packages with my package to application.properties and it works fine.
