### ISSUE TITLE
Lots of warnings printed when using Vite

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#12574]
### Description of the bug
There seems to be three types of warnings printed when starting a project using Vite for the first time:
1. `[vite] Failed to load source map for /@fs/.../target/flow-frontend/VaadinDevmodeGizmo.js.` (Fixed)
2. `@vaadin/accordion is incorrectly packaged. Please contact the package author to fix.` (Fixed)
3. `[vite] Failed to load source map for /@fs/.../node_modules/.vite/chunk-HYXO6NXE.js?v=7f5865f8.`

While all of the warnings are harmless we still need to fix them
1. By adding a source map or fixing Vite so it doesn't try to load a source map that doesn't exist
2. By fixing `package.json` in our components and potentially ignore the warning for `@polymer/*`
3. Figuring out where the timing issue comes from as it is about the browser trying to load "one more file" after Vite has said "stop loading and refresh"

**Comment by vursen** [comment]
> @vaadin/accordion is incorrectly packaged. Please contact the package author to fix.

This kind of warnings is produced by SSR-analysis performed by Vite when a missing dependency is discovered.

Reported [a Vite issue](https://github.com/vitejs/vite/issues/6478) that no SSR-related logic should take place when the `config.ssr` is undefined = the SSR feature is disabled.

**Comment by vursen** [comment]
> [vite] Failed to load source map for /@fs/.../node_modules/.vite/chunk-HYXO6NXE.js?v=7f5865f8.

This kind of warnings is shown because of a race condition that sometimes occurs when the pre-bundling process starts and there is a not yet completed HTTP request at nearly the same time.

Reported this in [a Vite issue](https://github.com/vitejs/vite/issues/6508).

**Comment by vursen** [comment]
> This kind of warnings is shown because of a race condition that sometimes occurs when the pre-bundling process begins at nearly the same time as an HTTP request to the previously pre-bundled dependency.

Let's wait for https://github.com/vitejs/vite/pull/6758 to get merged as it will fix the race condition and hence warnings:

```
[vite] Failed to load source map for /@fs/.../node_modules/.vite/chunk-HYXO6NXE.js?v=7f5865f8.
```
