### ISSUE TITLE
Reconnect/reload an embedded component when the server connection is lost

### ISSUE THREAD

**Issue by paulroemer** [vaadin/flow#12592]
### Describe your motivation

As of today embedded web components do not try to reconnect to/resync with the server in case of communication errors or lost UIs/sessions. This misbehavior leads to half-dead components only noticable when a triggered server call cannot be executed.

### Describe the solution you'd like

The component should be aware of the communication errors and try to resynchronize with the server. If that is not possible, it would be nice to reload the whole component or at least call a registered callback so that the user can take care on his own (if that is possible).

### Describe alternatives you've considered

In my scenario the HTTP session is destroyed from the server side as part of logging out (this is triggered from external). I.e. at least the server side is aware of the session to destroy and could inform the client side to reload the component.

**Comment by MarcinVaadin** [comment]
This issue has been partially solved in https://github.com/vaadin/flow/issues/8101 - whole application is not reloading - which is fine, but _"I think embedded app should reinit/reconnect the embedded component when session is expired and not reload the main page."_ was not implemented.

**Comment by MarcinVaadin** [comment]
The HLD of current idea:
1. Get new JSESSIONID on client side
2. Create new UI instance and send CSRF token to client
3. Trigger resynchronize on client
