### ISSUE TITLE
Servlet 5 compatible version

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#12600]
### Describe the solution you'd like

Spring 6 / Spring Boot 3 moves to Servlet 5.0 API aka `jakarta.servlet`. We should try to get something working with Servlet 5 asap  so we can understand all the problems in dependencies or other issues that need to be ironed out.

**Comment by Artur-** [comment]
Some fundamental issues:
* Atmosphere has no version for servlet 5: https://github.com/Atmosphere/atmosphere/issues/2467
* Jetty websocket support has changed in Jetty 10 so it needs some refactoring, e.g. the `websocket-server` does not exist in Jetty 11
* Apache commons file upload is for Servlet 3: https://issues.apache.org/jira/browse/FILEUPLOAD-345

**Comment by knoobie** [comment]
@Artur- you could probably hijack https://github.com/vaadin/flow/issues/10366 it already like a lot of upvotes :)

**Comment by Artur-** [comment]
Thanks, good that somebody tracks what issues we have :)
