### ISSUE TITLE
"flow-build-info.json" contains absolute paths

### ISSUE THREAD

**Issue by jduan-highnote** [vaadin/flow#12630]
### Description of the bug

The generated file `META-INF/VAADIN/config/flow-build-info.json` seems to contain absolute paths, eg:

```
{
  "compatibilityMode": false,
  "productionMode": false,
  "npmFolder": "/Users/jduan/repos/bayone/grid-pagination",
  "generatedFolder": "/Users/jduan/repos/bayone/grid-pagination/target/frontend",
  "frontendFolder": "/Users/jduan/repos/bayone/grid-pagination/frontend",
  "pnpm.enable": false,
  "require.home.node": false
}
```

One problem with absolute paths is that the paths would be different between local builds and CI builds since they have different work paths. This means local builds won't be able to reuse the remote cache that's populated by the CI builds, or vice versa. 

Do those paths have to be absolute? Can they be relative to the repo? 

### Expected behavior

I expect this file to have relative paths.

### Minimal reproducible example

Should be easy to reproduce.

### Versions

- Vaadin / Flow version: 14.4.2
- Java version: OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
- OS version: macOS 12.0.1
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by Artur-** [comment]
The file and the folders in it are only used for development

**Comment by caalador** [comment]
Also when you do a production mode build any absolute path key in the file should be removed.

They are absolute as if you for instance run under a server which sets home to the server ./bin/ folder the the application wouldn't work as the expected files couldn't be found.

**Comment by jduan-highnote** [comment]
@Artur- @caalador thanks for your quick response. I was out due to the holidays. I'll switch our builds to production builds and see how that works.

**Comment by caalador** [comment]
As there has been no actions on this issue and the file doesn't contain absolute paths for a production build, I'm closing the issue.

If there is something specific then you are welcome to open up a new issue.
