### ISSUE TITLE
Running devMode doesn't respect nodeVersion given in plugin configuration

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#12686]
### Description of the bug

Starting up a project with `requireHomeNodeExec` and `nodeVersion` defined in for the plugin does install and use a node to `~/.vaadin`, but does not use the defined nodeVersion instead using the `DEFAULT_NODE_VERSION`

### Expected behavior

Defined version should be installed and not the default version

### Minimal reproducible example

- Define to any v14 demo to the maven plugin the configuration:
```
<configuration>
  <requireHomeNodeExec>true</requireHomeNodeExec>
  <nodeVersion>v17.2.0</nodeVersion>
</configuration>
```
- Run `mvn`
- See that the installed version is not 17.2.0, but the default 14.15.4

### Versions

- Vaadin / Flow version: 14+

**Comment by Artur-** [comment]
Isn't that how all configuration for dev mode works? The plugin configuration does not affect dev mode? If you run the `Application` class in a Spring Boot project, you do not ever even run the plugin

**Comment by caalador** [comment]
So you are saying it's ok to not respect the defined version and use the default version?
This doesn't at the moment work even if you define the version as a system property without the plugin.

**Comment by Artur-** [comment]
I am saying that the problems sounds like the same that https://github.com/vaadin/flow/issues/12498 is about, i.e. that you have to define all build related options in 2 places

**Comment by Artur-** [comment]
If it doesn't work when defining a system property, that sounds like a bug

**Comment by caalador** [comment]
It is clearly a bug as there are multiple places that default to only using the default version instead of taking into account that they could be defined.
