### ISSUE TITLE
StatisticsSenderTest is unstable and fails often.

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#12681]
The StatisticsSenderTest tests fail randomly quite often.

**Comment by caalador** [comment]
@Artur- any idea why these are so flaky on bender?

**Comment by Artur-** [comment]
Any example links to failed builds? 
- #12588 was one attempt to fix it

**Comment by caalador** [comment]
https://bender.vaadin.com/buildConfiguration/Flow_Flow100_Flow100Snapshot/279521?buildTab=overview
https://bender.vaadin.com/buildConfiguration/Flow_Flow100_Flow100Snapshot/279579?buildTab=overview
https://bender.vaadin.com/buildConfiguration/Flow_Flow100_Flow100Snapshot/279586?buildTab=overview
https://bender.vaadin.com/buildConfiguration/Flow_Flow100_Flow100Snapshot/279621?buildTab=overview
https://bender.vaadin.com/buildConfiguration/Flow_Flow100_Flow100Snapshot/279622?buildTab=overview
https://bender.vaadin.com/buildConfiguration/Flow_Flow100_Flow100Snapshot/279641?buildTab=overview
https://bender.vaadin.com/buildConfiguration/Flow_Flow100_Flow100Snapshot/279804?buildTab=overview

**Comment by Artur-** [comment]
Ok so they fail with a different error now. Maybe something in the tests that conflict (static?) as the error is mostly "java.lang.AssertionError: Status should be xyz"

**Comment by caalador** [comment]
I couldn't get it to fail locally with or without threads.

**Comment by caalador** [comment]
Closing issue as it has not been an issue for a long time after port selection fixes..
