### ISSUE TITLE
Add ListBox.setItemLabelGenerator()

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#12699]
### Describe your motivation

Would simplify migration from Vaadin 8

### Describe the solution you'd like

The function would simply call `setRenderer(new TextRenderer<>(itemLabelGenerator));`.

**Comment by knoobie** [comment]
Could be related to https://github.com/vaadin/platform/issues/2601 or?

**Comment by mvysny** [comment]
@knoobie yeah, excellent find, this looks like a duplicate of https://github.com/vaadin/platform/issues/2601 . I'll close this one.
