### ISSUE TITLE
[Vite] Add `vite.generated.ts` to `.gitignore`

### ISSUE THREAD

**Issue by vursen** [vaadin/flow#12693]
The `vite.generated.ts` file is currently not in `.gitignore` while `webpack.generated.js` is there. It would be logical to have `vite.generated.ts` in the ignore list as well.

![image](https://user-images.githubusercontent.com/5039436/148895395-b90e6c3e-3d89-4849-bc00-4d096f8d5083.png)

**Comment by Artur-** [comment]
This has been fixed
