### ISSUE TITLE
Lumo styles leak to the host page when embedding Vaadin component

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#12704]
### Description of the bug

When I embed a Vaadin application, its styles are applied also to parts that don't belong to the embedded application.

### Expected behavior

The other parts of the application are not affected by the embedded application.

### Minimal reproducible example

Check out [this project](https://github.com/mstahv/guestbook-embedding-example), deploy and navigate to basic.html file. You'll see that the H1 header from the host page changes font once the Vaadin app gets loaded.

### Versions

- Vaadin / Flow version: 22.0.2
- Java version: 17
- OS version: mac
- Browser version (if applicable): Chrome
- Application Server (if applicable): Tomcat
- IDE (if applicable): Eclipse

**Comment by caalador** [comment]
Noted that if you use a custom theme on the embedded component then lumo doesn't leak to the host page.

**Comment by mstahv** [comment]
@caalador I don't really agree with your severity label. This basically prevents embedding Vaadin apps without major changes in the host page CSS (which might be close to impossible in many cases).

**Comment by mstahv** [comment]
The custom theme workaround would be ok if that was documented.

**Comment by caalador** [comment]
Minor label was as it seemed to not affect if using the custom theme, but v22 didn't play the same game on that as v14 did.

**Comment by TatuLund** [comment]
I think this should be cross checked: https://github.com/vaadin/flow/issues/16083

**Comment by mcollovati** [comment]
The issue was assigned to a developer and is currently being investigated
