### ISSUE TITLE
Refreshing item and deselecting at the same time does not work

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#12725]
A selected item cannot be refreshed and deselected during the same round trip. The outcome depends on the order between refreshing and deselecting.

* If doing `refreshItem(item)` first and then `select(null)` and then selecting the row again in the grid, then the selection change event will contain the old item instance instead of the new one. This is thus somewhat similar to https://github.com/vaadin/vaadin-grid-flow/issues/969.
* Changing to order to do `select(null)` first and only then `refreshItem(item)` will keep showing the old values in the grid. On the positive side, the select event is correct if selecting the item again.
* If doing `refreshAll()` first and then `select(null)`, then the symptoms will be the same as with the previous combination: correct data in the event but old values are still shown in the grid
* The only working combination is to first do `select(null)` and then `refreshAll()`.

Even if someone manages to find the working combination, this is still not a good workaround since refreshing all items has a performance overhead compared to only refreshing the item that has actually changed.

Tested with Vaadin 14.3.3
```
@Route(value = "youmustbekidding")
public class TestView extends VerticalLayout {
    public static class Item {
        private final int version;

        public Item(int version) {
            this.version = version;
        }

        public int getVersion() {
            return version;
        }

        @Override
        public int hashCode() {
            // All instances in this example represent the same logical item
            return 1;
        }

        @Override
        public boolean equals(Object obj) {
            // All instances in this example represent the same logical item
            return obj instanceof Item;
        }

        @Override
        public String toString() {
            return Integer.toString(version);
        }
    }

    private Item item = new Item(0);

    private final Grid<Item> grid = new Grid<>();

    public TestView() {
        CallbackDataProvider<Item, Void> dataProvider = DataProvider
                .fromCallbacks(query -> Stream.of(item).skip(query.getOffset())
                        .limit(query.getLimit()), query -> 1);

        grid.setDataProvider(dataProvider);
        grid.select(item);

        grid.addSelectionListener(selectionEvent -> Notification
                .show("Selected " + selectionEvent.getFirstSelectedItem()
                        .map(Item::toString).orElse("<null>")));

        grid.addColumn(Item::getVersion).setHeader("Version");

        addUpdateColumn("refresh, deselect", () -> {
            dataProvider.refreshItem(item);
            grid.select(null);
        });

        addUpdateColumn("deselect, refresh", () -> {
            grid.select(null);
            dataProvider.refreshItem(item);
        });

        addUpdateColumn("refreshAll, deselect", () -> {
            dataProvider.refreshAll();
            grid.select(null);
        });

        addUpdateColumn("deselect, refreshAll", () -> {
            grid.select(null);
            dataProvider.refreshAll();
        });

        add(grid);
    }

    private void addUpdateColumn(String action, Command command) {
        grid.addComponentColumn(ignore -> new Button(action, clickEvent -> {
            item = new Item(item.getVersion() + 1);
            command.execute();
        }));
    }
}
```

**Comment by mcollovati** [comment]
The issue is not reproducible anymore with grid.
`AbstractGridSingleSelectionModel` has been changed to avoid calling refresh on `DataCommunicator` (vaadin/flow-components#3358 and vaadin/flow-components#4902)
