### ISSUE TITLE
Shortcut events triggered although it is not clickable

### ISSUE THREAD

**Issue by cdir** [vaadin/flow#12722]
### Description of the bug

I have a Button with a shortcut binding. When I open a dialog the button is not clickable anymore. But the shortcut binding is still active.

### Expected behavior

A not clickable button should not be called by key bindings.

### Minimal reproducible example

        Button button = new Button("Open Dialog");
        add(button);
        button.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        button.addClickShortcut(Key.ENTER);
        button.addClickListener(e -> {
            Dialog dialog = new Dialog();
            dialog.open();
        });

With every ENTER a new dialog is opened. A workaround like disableOnClick is not useful because the dialog may be opened by another button or a completly other event.

### Versions

- Vaadin / Flow version: 22 (same in LTS 14)
- Java version: 11

**Comment by TatuLund** [comment]
Is this related to https://github.com/vaadin/flow/issues/12307 ?

**Comment by cdir** [comment]
Maybe it's related. I think it's the problem @Avec112 described in the first comment of #12307. But as @pleku commented on 22 Nov 2021:

> I'm not 100 % the problem you describe is the same issue, my guess would be that it is not.

**Comment by caalador** [comment]
The issue is that there is no such thing as modal at the moment and dialog is only visibly modal so it is not actually blocking anything.
V23 will bring in a new feature of server-side modality which would fix this issue with the code:
```
        Button button = new Button("Open Dialog");
        add(button);
        button.addClickShortcut(Key.ENTER);
        button.addClickListener(e -> {
            Dialog dialog = new Dialog();
            dialog.open();
            UI.getCurrent().addModal(dialog);
            dialog.addDialogCloseActionListener(
                    dialogCloseActionEvent -> UI.getCurrent().remove(dialog));
        });
```
I feel this should be implemented in the dialog component so that it is also modal on the server side if using modality.

**Comment by cdir** [comment]
@caalador that sounds good at first. But why doesn't the dialog do this itself when setModal(true) is set? I can't imagine that someone wouldn't want that if the dialog is configured as modal.

**Comment by caalador** [comment]
I think it should also do this automatically, but as far as I can find at the moment it doesn't use the new modality feature, so I gave a workaround for now for v23.

**Comment by joheriks** [comment]
So could we:
- Fix this in V23 by updating the dialog to set server-side dialog (i.e., merging https://github.com/vaadin/flow-components/issues/2571)
- Fix this in V14 by backporting the server-side modality feature to 2.8 and updating the components for 14.9

**Comment by joheriks** [comment]
Note: the server-side modality feature will not be backported to V14.
