### ISSUE TITLE
java.net.BindException: Cannot assign requested address: connect when trying to start a V23 Spring Boot app

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow#12765]
### Description of the bug

When I start my application, it ends up on a whitelabel error page with 
```
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jan 19 14:47:35 EET 2022
There was an unexpected error (type=Internal Server Error, status=500).
Cannot assign requested address: connect
java.net.BindException: Cannot assign requested address: connect
```

### Expected behavior

The application should start normally

### Minimal reproducible example

[vaadin-base.zip](https://github.com/vaadin/flow/files/7897216/vaadin-base.zip)

### Versions

- Vaadin / Flow version: V23.0.0.alpha2
- Java version: Java 11 / 17
- OS version: Windows 10

**Comment by Artur-** [comment]
Can't reproduce on a mac with Node 17

The attached project starts without issues after removing the invalid
```js
import 'http://localhost:56445/files/transformed/@vaadin/vaadin-select/vaadin-select.js';
```
imports from checkout-view.ts

**Comment by joheriks** [comment]
### Expected behavior
Webpack reports the erroneous import lines in the browser as follows:
<img width="1776" alt="Screenshot 2022-01-19 at 17 56 02" src="https://user-images.githubusercontent.com/2838896/150167373-49537d5e-ada7-47a9-b000-a971a9dde829.png">

**Comment by caalador** [comment]
Running with debug logging (application.properties with row `logging.level.root=DEBUG`) I can see that even though webpack failed there is a request `Requesting resource from Webpack http://localhost:0/sw.js`

**Comment by caalador** [comment]
On windows the appication fails during generation of imports when we parse the imports from the view files and for some reason no exception is clearly thrown (from Path implementation WindowsPath) so there is an expectation that devServer started even though it was never even run.

A note `import 'http://localhost:56445/files/transformed/@vaadin/vaadin-select/vaadin-select.js';` is a Designer import that designer uses internally during execution so an interesting question would be that where did this come from as it shouldn't ever be written anywhere.

**Comment by Rattlyy** [comment]
Issue still present with latest. https://pastebin.com/sWKnR50S

**Comment by caalador** [comment]
Did you remove the broken import?
Do you not receive a error message about the faulty import?

**Comment by Avec112** [comment]
So I just experienced this exception. I have gradually upgraded from Vaadin v14 and up for every new major release. Currently I am using v23.0.1. I have always followed the documented upgrading steps. However from v21 and up `badge` and some other stuff stopped working without me noticing. 

I found out that my frontend directory was missing a separate themes folder and my "theme". I then created `frontend/themes/<theme>` and put my `src` and `styles` inside it and also adding `theme.json` so badge may be enabled. 

When starting the application I get the exception. I have searched for the `vaadin-select.js` import but did not find anything.

**Comment by agoldoni** [comment]
After debug, under windows, we solved this problem by making a folder 
./build/plugins/stats-plugin
refrenced by link
node_modules/@vaadin/stats-plugin

**Comment by ihor-lev** [comment]
Occasionally I've got a similar error when did a mistake in  a JS module import:
```
@JsModule("./js/helper.js")
```
No descriptive error was shown that the file was not found. Maybe this comment would be useful for someone.

**Comment by robeden** [comment]
I'm hitting this right now with 22.0.4, with a bootstrap app which I'm upgrading from v14. 

After digging, it seems to me that the problem is the `doStartDevModeServer()` function is not being called to configure the port to anything other than zero. This happens because an exception is thrown in the `action` `BiConsumer` on the `waitFor`. I can't find the right repo for 22.0.4, but here's the line in the current repo:

https://github.com/vaadin/flow/blob/master/vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java#L161

The exception trace is normally buried, but from poking in the debugger:
```
java.util.concurrent.CompletionException: com.vaadin.flow.server.ExecutionFailedException: Pnpm install has exited with non zero status. Some dependencies are not installed. Check pnpm command output
	at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:418)
	at com.vaadin.base.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:336)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.vaadin.flow.server.ExecutionFailedException: Pnpm install has exited with non zero status. Some dependencies are not installed. Check pnpm command output
	at com.vaadin.flow.server.frontend.TaskRunNpmInstall.runNpmInstall(TaskRunNpmInstall.java:404)
	at com.vaadin.flow.server.frontend.TaskRunNpmInstall.execute(TaskRunNpmInstall.java:142)
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:919)
	at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:407)
	... 10 more
```

Also on the console is:
[stderr] sh: pnpm: command not found
[stdout] Command `/usr/local/bin/npx --yes --quiet pnpm@5.18.10 --shamefully-hoist=true install` failed:

The line from stderr is what's printed if I run `/usr/local/bin/npx --yes --quiet pnpm@5.18.10 --shamefully-hoist=true install` manually.

I have yet to figure out the fix (still working on that), but hopefully this is at least helpful to some in the future.

> ❯ npm --version
> 8.18.0
> ❯ sw_vers
> ProductName:	macOS
> ProductVersion:	12.6.2
> BuildVersion:	21G320
