### ISSUE TITLE
VaadinSession.writeObject fails in dev mode if the session has not been used before being serialized again

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#12783]
### Description of the bug

If a session has been deserialized and `refreshTransients` has not been called, it likely cannot be serialized again.

See https://stackoverflow.com/questions/70788079/cannot-invoke-com-vaadin-flow-server-vaadinservice-getcontext-the-return-va

### Expected behavior

A deserialized session should be serialized as-is

### Minimal reproducible example

-

### Versions

- Vaadin / Flow version: 22

**Comment by Trek3** [comment]
Hi, I'm OP of the question on SO linked in the issue. 
First of all, thank you so much for the quick fix.

I'm a beginner in this, how does the whole pull-request/merge works? I mean, once it is merged to master, will I find the fix using vaadin from maven?
Thank you again!

**Comment by Artur-** [comment]
Once merged, it goes automatically into Flow 10.0-SNAPSHOT, which is used in Vaadin 23. It will then go into the following releases of both Vaadin 22 and 23
