### ISSUE TITLE
PiT v23: migration from v22 pnpm to npm v23 is super slow

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#12825]
### Description of the bug

The first time that a user compiles a v22 application migrated to v23, it needs to wait for about 5 minutes.
This is because default was pnpm and now npm which takes a long while when computing the dependency tree.
The compilation process looks frozen at `⸨⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠧ idealTree:all`  phase, in windows is even worst. 

Not sure how this should be fixed, but probably a message asking to the user to be patient, or something 

### Expected behavior

It should take similar time to previous version, DX seems worst than before

### Minimal reproducible example

- Take a any v22 project, eg: 
```
curl 'https://start.vaadin.com/dl?preset=all&projectName=all' -o all.zip` 
```
- Make sure you are not forcing pnpm configuration, https://github.com/vaadin/start/issues/1741 e.g. by running:
```
perl -pi   -e 's,.*pnpm.*,,g' pom.xml src/main/resources/application.properties
```
- Compile it:  it will take about **30 secs** 
```
mvn clean package -Pproduction
```
- Bump  vaadin version:  
```
mvn versions:set-property -Dproperty=vaadin.version -DnewVersion=23.0.0.alpha3
```
- if you have fusion views you might need to migrate them, e.g. by running these commands
```
find src/main -name '*.java' | xargs perl -pi  -e 's,com.vaadin.fusion,dev.hilla,g'
find frontend -name '*.ts' | xargs perl -pi -e 's,com/vaadin/fusion,dev/hilla,g'
perl -pi -e 's,"\@vaadin/form","\@hilla/form",g' package.json
perl -pi -e 's,"\@vaadin/fusion-frontend","\@hilla/frontend",g' package.json
```
- You might need to remove `node_modules`  https://github.com/vaadin/flow/issues/12810
```
rm -rf node_modules
```
- Compile it:  it will take about **5 minutes**
```
mvn clean package -Pproduction
```

### Versions

- Vaadin / Flow version: v22 to v23
- Java version: 11
- OS version: any

**Comment by Artur-** [comment]
The relevant and related issues are https://github.com/vaadin/flow/issues/12796 and https://github.com/npm/cli/issues/3703

**Comment by caalador** [comment]
#12796 is not directly applicable as in 22 the default in pnpm which doesn't use the npm package-lock

**Comment by joheriks** [comment]
In case the user is missing `package-lock.json` (e.g. due to switching from `pnpm` or having executed `clean-frontend`), we will mention in the logged message that `npm install` may take several minutes.
