### ISSUE TITLE
BeforeEnterEvent#forwardTo(...) does not always change browser URL in Firefox

### ISSUE THREAD

**Issue by Frettman** [vaadin/flow#12871]
### Description of the bug

When forwarding, i.e. from a `BeforeEnterObserver`, using `BeforeEnterEvent#forwardTo(...)` there are cases - at least in Firefox - where the URL of the browser is not updated correctly.

Let's say I have the MainView at `@Route("")` and TestView at `@Route(value = "test")`. The TestView implements `BeforeEnterObserver` and forwards to the MainView: `event.forwardTo(MainView.class);`
When I go to the TestView at `http://localhost:8080/test` in the browser:
1. Chrome shows the content of MainView (correct) and changes the URL to `http://localhost:8080` (correct).
2. Firefox shows the content of MainView (correct) but keeps the URL at `http://localhost:8080/test` (**wrong**)

After further testing the problem only seems to exist when forwarding to the very root as above. When the MainView is e.g. moved to `@Route("a")` it works as expected.

### Expected behavior

Firefox should display the correct URL in all cases.

### Minimal reproducible example

See https://github.com/Frettman/vaadin-flow-issue-forwardto
It's a regular Maven Spring Boot project.

### Versions

- Vaadin / Flow version: 22.0.4
- Java version: 11
- OS version: Windows 10
- Browser version (if applicable): Firefox (maybe others; Chrome did work)

**Comment by caalador** [comment]
Out of tested browsers Opera, Chrome, Edge and Firefox only firefox didn't update to `''`.
Some testing shows that where other browsers do work with `window.history.replaceState(null, '', '');` firefox only clears the value with `window.history.replaceState(null, '', './');`

**Comment by knoobie** [comment]
Could be fixed by https://github.com/vaadin/flow/pull/12991 or?

**Comment by caalador** [comment]
Yes, tested it and this issue is fixed with #12991
Thanks @knoobie for noticing this as I totally forgot this issue when reviewing the fix.
