### ISSUE TITLE
Automatically use available converters in binder

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#12881]
### Describe your motivation

When you bind a field and a property which do not have the same value type, you get an exception, e.g.
```
Caused by: java.lang.IllegalStateException: Property type 'java.util.UUID' doesn't match the field type 'java.lang.String'. Binding should be configured manually using converter.
	at com.vaadin.flow.data.binder.Binder.bindProperty(Binder.java:2972) ~[flow-data-2.7.9.jar:2.7.9]
```

### Describe the solution you'd like

Instead of saying that the user should configure a converter, Binder should automatically pick a suitable converter if one is available. For the above case there is e.g. `StringToUuidConverter`. It is just not used by default

**Comment by joheriks** [comment]
## Acceptance criteria
- Add logic to binder that compares the source-target type pair against all implementations of `Converter<S,T>` in `com.vaadin.flow.data.converter` and uses the first match (if any) by default.
- The source-target type pair in the converter should be a precise match with the one defined by the binder, i.e., no checking of inheritance.
- Should only look up converters in `com.vaadin.flow.data.converter`.
- The default should never override any converter the developer has set explicitly.

**Comment by mortensen** [comment]
I actual applications you either already get an IllegalArgumentException OR you have already chosen a fitting converter. And if this ticket will match the acceptance criteria "The default should never override any converter the developer has sex explicitly.", then the answer to your question should be "no", it should not cause problems with existing apps. But thats just an educated guess.

**Comment by joheriks** [comment]
Yes, the idea is that only in the case where now throw an exception should the automatic converter be set. Clarified this in the acceptance criteria.

**Comment by mortensen** [comment]
Just to let you know I am working on a solution for this (at least I am trying). I talked about it with Hawk in Discord and we already discussed wether a static list or a dynamical aproach with reflections fits better. Performance and stuff. ...

**Comment by joheriks** [comment]
@mortensen Nice to hear, do you plan to make a PR at some point? Let us know if we can help in any way.

**Comment by mortensen** [comment]
@joheriks Sorry I was a bit busy the last days but I will work on it tonight again and plan to make the PR somewhere this week. Thanks for the offer. If I get stuck I will reach out then :+1:

**Comment by knoobie** [comment]
We had a discussion about this a while ago in discord as well - I would suggest to use `ServiceLoader` for easy extending for custom converter. 

I'm wondering; could this be combined with the `Component::getTranslation`interface and you define properties for each error message that user can implement and fall-back to blank / default message otherwise? This is common best practise in e.g. Apache Tomcat, Spring Security and so on

**Comment by mcollovati** [comment]
A simple design could be something like the following:

* we introduce a `ConverterFactory` interface to build `Converter` instances based on presentation and model types
* a default factory implementation handles all `Converter`s in `com.vaadin.flow.data.converter`
* Binder exposes a protected `getConverterFactory()`; base implementation will return the default factory
* If a custom factory is needed, user can extend Binder and override `getConverterFactory()`
* Optional: default factory may compose with other implementations loaded via `ServiceLoader`, as proposed by @knoobie 


With this design it should be easy to have custom behaviorus in different environments by implementing `ConverterFactory` interface and extending `Binder`; for example one can implement a `SpringBinder` that uses all defined `ConverterFactory` beans,or inject into the view a `ConverterFactory` that acts as an adapter to some existing conversion service and pass it to an anonymous Binder instance.


```java
interface ConverterFactory {
	Optional<Converter<P, M>> newInstance(Class<P> presentationType, Class<M> modelType)
}

// handles all `Converter`s in `com.vaadin.flow.data.converter`
class DefaultConverterFactory < ConverterFactory { }

class Binder {
	protected ConverterFactory getConverterFactory() {
		returns DefaultConvert;
	}
}
```
