### ISSUE TITLE
PiT v23: addons fail in v23 without a meaningful message

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#12908]
### Description of the bug

If the user is running `npm` earlier to `8.3` and adds a plugin depending on other vaadin components like lumo, there is an error in devtools console regarding double wc registration.

If after that the user installs a newer version of `npm`  the error remains until the user manually removes both: `package-lock.json` and  `node_modules` 

### Expected behavior

- If npm version < 8.3,  flow should
   -  fail with an error asking the user for updating their npm
   - or install the appropriate version for the project
- If user install npm 8.3 manually, flow should remove `package-lock.json` and  `node_modules`
- In addition there should be a section in the migration guide

### Minimal reproducible example

Prepare and install the project in a system with `npm@8.1` 
```
# Clone the project
git clone https://github.com/vaadin/skeleton-starter-flow-spring.git
cd skeleton-starter-flow-spring

# Be sure you are using an npm version previoud to 8.3
npm install -g npm@8.1
npm --version

# Bump version to V23 alpha4
mvn versions:set-property -Dproperty=vaadin.version -DnewVersion=23.0.0.alpha4

# Add a plugin to the app e.g. ToolTip (https://vaadin.com/directory/component/tooltip/samples)
## Add dependency to pom.xml
<dependency>
   <groupId>com.vaadin.componentfactory</groupId>
   <artifactId>tooltip</artifactId>
   <version>1.3.7</version>
</dependency>

## Add code to src/main/java/com/example/application/views/helloworldviewjava/HelloworldviewjavaView.java

Button button = new Button("Click me");
Tooltip tooltip = new Tooltip();
tooltip.attachToComponent(button);
tooltip.setPosition(TooltipPosition.RIGHT);
tooltip.setAlignment(TooltipAlignment.LEFT);
tooltip.add(new H5("Hello"));
tooltip.add(new Paragraph("This is an example of how to use it"));
add(button, tooltip);

# Run the project
mvn

```

There is an error Error in chrome devtools is:

```
Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-lumo-styles" has already been used with this registry
```

Update npm installation to fit `8.3+` 

```
# update npm
npm install -g npm@8.3
npm --version
# Run the project
mvn
```
The error remains
```
Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-lumo-styles" has already been used with this registry
```

Manually remove npm stuff

```
# Clean package lock file and node_modules
rm -rf package-lock.json node_modules/
# Run the project
mvn
```

Project works

### Versions

- Vaadin / Flow version: 23.0.0.alpha4
- Java version: 11
- OS version: mac
- npm: 8.1 and then updated to 8.3

**Comment by haijian-vaadin** [comment]
Would it be enough that we just provide a warning message when npm version is older than 8.3, like described in [this ticket](https://github.com/vaadin/flow/issues/12824)?
People don't really 8.3 unless there are version conflicts in the addons, so we don't need to force 8.3.

**Comment by TatuLund** [comment]
And we should clearly mention npm 8.3 requirement in Vaadin 23 release notes.

**Comment by joheriks** [comment]
Replay these steps after #12998  is merged (Node 16.14, which includes Node 8.3, will be auto-installed in case the globally installed Node is too old). If the version has been forced to an older one (e.g., by setting `vaadin.ignoreVersionChecks=true`), we can assume that the user knows what they are doing.

**Comment by caalador** [comment]
One note on the issue. Did you check in the logs after updating npm that `npm install` was not skipped.
I would expect that the application did not execute the npm install task as the package.json didn´t change and the hash checks will validate that everything is ok.
The steps to get npm install to run again would be to just remove the `vaadin{hash}` from the package.json or delete the `node_modules/.vaadin/vaadin.json` file to get npm to run again.

**Comment by joheriks** [comment]
Verified that Node `16.14.0` and npm `8.3.1` are used from `~/.vaadin` when global npm is less than `8.3`, and the example project starts up normally.
