### ISSUE TITLE
Binder - multiple bindings to same property

### ISSUE THREAD

**Issue by karstrom** [vaadin/flow#12920]
### Description of the bug

When you have multiple fields binded to the same property there is some unnecessary restrictions in the class.

All the bindings are in this map:
private final Map<String, Binding<BEAN, ?>> boundProperties = new HashMap<>();

This will only return one of the bindings:
public Optional<Binding<BEAN, ?>> getBinding(String propertyName) 

Since it's possible to add 2 bindings with same name - it must be possible to retrieve them.
There is no way of getting the complete list of bindings from the map.

### Expected behavior

**Suggestion:** 
Implement getBindings() returning the complete Map<String, Binding<T, ?>>
or
Implement getBindings(String field) returning a list of all matches

### Minimal reproducible example

add 2 bindings to same property - retrieve both of bindings from Binder

### Versions

- Vaadin / Flow version: 22.0.4
- Java version: 1.8

**Comment by Legioth** [comment]
What's the reason for multiple bindings for the same property? I'm wondering whether another approach might be to prevent that from happening in the first place by making it throw an exception if you even try to add another one?

**Comment by mshabarov** [comment]
Closed due to no response from author. If this is still an issue, please reopen the ticket and provide more information.
