### ISSUE TITLE
Session expiration, cookies disabled, and internal error messages show the <u> tag in the message

### ISSUE THREAD

**Issue by drewharvey** [vaadin/flow#12939]
### Description of the bug

The default SystemMessages strings contain `<u>` tags and they get printed in the messages shown to the user.

![Home](https://user-images.githubusercontent.com/2496955/152586931-f59ee52a-a87a-4a54-9378-d29473fb16f0.jpg)

### Expected behavior

The tags shouldn't be shown in the message

### Minimal reproducible example

Force the app's session to timeout.

### Versions

Vaadin 22 and 23

**Comment by caalador** [comment]
This has been there since the change #11354 in v21 and the strings should just be cleaned.

**Comment by drewharvey** [comment]
Still seeing the tags on latest 22 release.

**Comment by javier-godoy** [comment]
This fix requires backporting to Vaadin 14 since #11354 was merged to Flow 2.7.
