### ISSUE TITLE
Enable the exclusion of handling specific URLs

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/flow#12949]
For some use cases, it is desirable to exclude specific URLs from being handled by Vaadin (without changing the Vaadin URL mapping).  For example, to integrate Swagger-UI, it would be desirable that Vaadin would refrain from handling requests for `/swagger-ui.html`.

Currently, Flow seems to already respect any added Spring REST controllers by not interfering with their handling. So, it would be good to extend this automatic exclusion of URL-handling to other things such as Swagger. Or alternatively, it would be useful to provide some mechanism by which the user can explicitly exclude certain URLs from being handled by Flow.

**Comment by simasch** [comment]
The same problem I encountered with Camunda BPM

**Comment by letrthang** [comment]
This causes issue #10163.
We should introduce a config value **vaadin.url-exclusion** so all requests forward to this URL will redirect to Spring servlet.
