### ISSUE TITLE
npx pnpm@5.18.10 executes pnpm 6 in some cases

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#12953]
### Description of the bug

Apparently when you have pnpm 6 installed globally then running
```
npx pnpm@5.18.10
```
on Windows will run pnpm 6 and not 5. So the output of
```
npx pnpm@5.18.10 --version
```
is e.g.
```
6.9.1
```

This will result in versions not being locked and e.g. today running a 22.0.4 project might result in
```
Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-lumo-styles" has already been used with this registry
```
as pnpm will pick some mixin versions that are from 22.0.5 and then there will be duplicates installed

### Expected behavior

Everything should work even if you have pnpm 6 globally installed

### Minimal reproducible example

This was reproduced on Windows with the default https://start.vaadin.com project. Cannot reproduce on Mac

### Versions

- Vaadin / Flow version: 22.0.4

**Comment by Artur-** [comment]
The duplicate dependencies come from pnpm 6 using `.pnpmfile.cjs` as the default value for the `pnpmfile` property while pnpm 5 uses `pnpmfile.js`. Maybe we could set the property explicitly when running `pnpm` as a workaround

**Comment by johannest** [comment]
My environment:
Windows 11
Node.js v14.17.0
npm & npx 7.19.0 (globally installed)
pnpm 6.9.1 (globally installed)

Workaround: rename `pnpmfile.js` to `.pnpmfile.cjs`

**Comment by caalador** [comment]
I guess this is due to npm7 dropping the `--ignore-existing` flag.

**Comment by johannest** [comment]
Cannot reproduce the issue anymore when upgraded to npm 8.4.1 (from 7.19.0).

**Comment by joheriks** [comment]
V23 will force minimum npm 8.3. Need to investigate whether this solves the issue.
