### ISSUE TITLE
Add vaadin-spring as a submodule of Flow

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#12959]
## Updated structure

Add the merge, `flow` repository should have the following structure:
```
flow 
|-- ...
|-- vaadin-spring
`-- flow-tests
    |--...
    `-- vaadin-spring-tests
         |-- test-spring
         |-- test-spring-boot
         |-- ...
```

## Considerations
- Git history should be kept. 
- Spring version should be same as flow (`23.1` in master). 
- Merge also into `23.0` branch.
- Spring test modules have separate interdependences with only one shared module (`spring-test-common`), so they can be run in separate containers from the Flow test modules.
- Note that the `spring-boot-dependencies` bom introduces a `selenium` version that conflicts with the `vaadin-testbench-bom`, the latter need to be placed so that it takes precedence (earlier in the `pom.xml`).

Part of vaadin/spring#922

**Comment by joheriks** [comment]
Spike PR for reference: https://github.com/vaadin/flow/pull/12929
Branch to start the actual integration from (already contains the `vaadin-spring` and `vaadin-spring-test` modules with history): https://github.com/vaadin/flow/tree/import-spring

**Comment by Artur-** [comment]
In #13002
