### ISSUE TITLE
Request for non-existent image results in OK 200 and bootstrap page in V22

### ISSUE THREAD

**Issue by anssit** [vaadin/flow#12965]
### Description of the bug

While testing #10965 in V23, discovered that in the default (JavaScript) bootstrap mode, requesting a non-existent image results in OK 200 response code and the bootstrap `index.html` returned as a result.

### Expected behavior

Error code 404, behaviour as described in #10965.

### Minimal reproducible example

To reproduce, add an image to some view in the application. Set image's resource name to something that will not be found from static resources.

```java
    Image image = new Image("not_found.jpeg", "alt");
    add(image);
```

### Versions

Vaadin: 22.0.4
Flow: 9.0.4
Java: Oracle Corporation 16.0.1
OS: x86_64 Mac OS X 11.5
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

**Comment by Artur-** [comment]
With 23 beta 1, I get
```
GET http://localhost:8080/not_found.jpeg 404
```

**Comment by anssit** [comment]
You are absolutely right. By mistake I tested this with V22 and assumed it is the same for V23. It is fixed for V23 in #12571. Changed the title accordingly.

**Comment by Artur-** [comment]
So it is fine to close this?

**Comment by anssit** [comment]
We decided in the team to cherry-pick #12571 to V22. We'll keep this issue open until the CP has been merged.

**Comment by anssit** [comment]
Cherry picked in PR #12969, closing this issue.
