### ISSUE TITLE
Stop using shrinkwrap

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#13008]
### Describe your motivation

The shrinkwrap does not serve its intended purpose of locking dependency versions. Now we have a better mechanism through npm `overrides` and that one actually works. We should not include shrinkwrap in package.json anymore. 

Including the shrinkwrap actually breaks npm installation because of an npm problem: https://github.com/npm/cli/issues/4409

### Describe the solution you'd like

Do not install shrinkwrap. Do not use it for anything. This can be extended to: do not publish a shrinkwrap

**Comment by joheriks** [comment]
### Acceptance criteria
1. Remove `@NpmPackage` annotation from https://github.com/vaadin/platform/blob/92d227cd26319b9b533cd9053391ee9982004a5d/vaadin-core/src/main/templates/com/vaadin/shrinkwrap/VaadinCoreShrinkWrap.java
2. We currently check the version of `vaadin-shrinkwrap` to figure out if the platform has been updated, this could check `vaadin-core` package version instead.
3. Verified that `package.json` does not contain `vaadin-shrinkwrap` nor `vaadin-core-shrinkwrap`.
4. Verified that when upgrading the platform then the cleanup step in `TaskUpdatePackages`(deleting node_modules, etc.) is executed.

**Comment by manolo** [comment]
We need to remove/skip steps during platform release

**Comment by ZheSun88** [comment]
except the vaadinCoreShrinkWrap.java, there is also the VaadinShrinkWrap.java https://github.com/vaadin/platform/blob/master/vaadin/src/main/templates/com/vaadin/shrinkwrap/VaadinShrinkWrap.java

**Comment by Artur-** [comment]
https://github.com/vaadin/platform/pull/2751

**Comment by anantjagania** [comment]
Can we have this removed from Vaadin 14 as well?

Thanks.
