### ISSUE TITLE
Theme doesn't work in production mode

### ISSUE THREAD

**Issue by gpsfl** [vaadin/flow#13007]
### Description of the bug

When running `prepare-frontend` or `build-frontend` in production mode, the theme will be ignored. It will always use default lumo in light mode. 

There are no warnings or errors in server or client log. Please tell me if there is a way to turn on any additional logging when building the frontend

### Expected behavior

Theme should be used

### Minimal reproducible example

@Theme(themeClass = Lumo.class, variant = Lumo.DARK)

### Versions

- Vaadin / Flow version: 22.0.5
- Java version: 11.0.9
- OS version: Windows 10

**Comment by caalador** [comment]
I couldn't replicate the issue as I get the DARK variant as expected on a v22.0.5 from start.vaadin.com
Can you provide a project where the issue replicates?

**Comment by caalador** [comment]
I'm closing this issue as there has been no way of replicating the issue.

If the issue persists open a new ticket with steps to reproduce and a project if possible.

**Comment by giovannitro96** [comment]
Error is still there, I have a private project where it happens.
