### ISSUE TITLE
PiT v23: Wrong styles when using the legacy bootstrap

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#13041]
### Description of the bug

When running a flow app with the legacy bootstrap, styles are not applied correctly:
- Screenshot deprecated bootstrap
![Screenshot 2022-02-16 at 10 25 47](https://user-images.githubusercontent.com/161853/154234874-0746f17b-a993-43bb-9a7f-36df01353265.png)
- Screenshot latest bootstrap

![Screenshot 2022-02-16 at 10 25 37](https://user-images.githubusercontent.com/161853/154234945-ffcabc9d-88dc-48cb-814f-110846ba7405.png)

### Expected behavior

Styles should be applied the same

### Minimal reproducible example

Download a flow app from start.vaadin.com
run `mvn -Dvaadin.useDeprecatedV14Bootstrapping=true`

### Versions

- Vaadin / Flow version: v23.0.0.beta3
- Java version: 11
- OS version: macos
- Browser version (if applicable): Chrome latest

**Comment by joheriks** [comment]
The `useDeprecatedV14Bootstrapping` mode is for easing migration, so shouldn't the test case be adding it to a V14 starter and then upgrading it to V23. Not sure should it generally be supported to switch from a V23 starter app back to the legacy bootstrap mode by setting `vaadin.useDeprecatedV14Bootstrapping=true`. Annotation such as `@Push`, `@Theme` would at least need to be moved from the `AppShellConfigurator` subclass to view classes. But it seems here that moving `@Theme` to `MainLayout` does not help here, which may be a bug.

**Comment by joheriks** [comment]
Fixing the themes not applied issue but it will not work out of the box for a started, as the annotation should be moved to `MainLayout`.
