### ISSUE TITLE
Cannot migrate Polymer component to Lit caused by MediaRecorder is not available in older TypeScript inside webpack

### ISSUE THREAD

**Issue by lanmaster** [vaadin/flow#13060]
Hello. Cannot migrate Polymer component to Lit caused by MediaRecorder is not available in older TypeScript inside webpack.
Vaadin 14.8.1. I am unsure that problem is instantly related to it, but i think it is related to older TypeScript library (4.0.3) that is used in currently webpack version (4.42.0). Maybe it is time to update webpack and TypeScript?

**Comment by Artur-** [comment]
Not sure what this is about as there is no example code here but maybe this helps https://github.com/microsoft/TypeScript/issues/34728#issuecomment-546205772 ?

**Comment by lanmaster** [comment]
Thanks, i will try it in future. Sure next try will be lucky)
