### ISSUE TITLE
FrontendToolsLocator.verifyTool incorrectly ignores tools that output something to stderr

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#13195]
### Description of the bug

In some cases, `npm -v` can give the following output
```
(node: 1124) [LRU_CACHE_OPTION_maxAge] DeprecationWarning: The maxAge option is deprecated. please use options.ttl instead
(Use node --trace-deprecation to show where the warning was created)
(node: 2688) [LRU_CACHE_OPTION_maxAge] DeprecationWarning: The maxAge option is deprecated. please use options.ttl instead
(Use node --trace-deprecation to show where the warning was created)
8.3.1
```

The first 4 rows are output to stderr and this causes `verifyTool` to assume that the npm version does not work. 

### Expected behavior

Any output to stderr should not be interpreted as a broken tool

### Minimal reproducible example

Unclear

### Versions

- Vaadin / Flow version: 23.0.0

**Comment by yaron-shamul** [comment]
anything new?

**Comment by caalador** [comment]
`Vaadin 23.0.1` and up should be able to handle such cases now.
