### ISSUE TITLE
Spring Security integration is incompatible with Vite front-end tooling

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#13202]
### Description of the bug

Spits out json for the user when trying to log in.

### Expected behavior

User should get to the view they was heading to, before guided to the login screen.

### Minimal reproducible example

Create a projet using start.vaadin.com:

 * enable access control
 * enable vite on the settings
 
Download, start, try to login.

### Versions

- Vaadin / Flow version: 23.0.0
- Java version: 17
- OS version: Mac
- Browser version (if applicable): Safari, Firefox, (in Chrome I was able to reproduce in the Incognito mode only, so some cache thing might help to avoid this)

**Comment by Artur-** [comment]
This is fixed by #13209 and #13212
