### ISSUE TITLE
LineAwesome icon set up by start.vaadin.com is not displayed if the folder name contains a space

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#13203]
Download a project from start.vaadin.com with vite enabled. When you run the project, the icons in the menu are not displayed.

 * Mac
 * 23.0.0
 * Java 17
 * Any browser

**Comment by Artur-** [comment]
This one is a bit curious because I have also seen it and the icons are not displayed because the line awesome font is not loaded. But right now I cannot reproduce it

**Comment by tarekoraby** [comment]
Reproduced with Hilla 1.0.2 on Windows.

**Comment by Artur-** [comment]
Reproduces when the folder name contains a space. Seems like CSS import urls are not encoded by Vite

**Comment by Artur-** [comment]
https://github.com/vitejs/vite/pull/7452

**Comment by tarekoraby** [comment]
And for the record, the icons work in production builds (using `mvn -Pproduction`).

**Comment by Artur-** [comment]
Additionally requires https://github.com/vitejs/vite/pull/7510

**Comment by Artur-** [comment]
Fixed in #13399
