### ISSUE TITLE
@CssImport does not work in jar sub-modules / add-ons

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow#13211]
### Description of the bug

@CssImport does not work in jar sub-modules / add-ons in Vaadin 23. Note, using WebPack. This works in Vaadin 22.0.7. 

### Expected behavior

@CssImport works

### Minimal reproducible example

- Create a new Vaadin add-on project.
- Add @CssImport in the component 

### Versions

- Vaadin / Flow version: 23.0.0
- Java version: 11

**Comment by xdenser** [comment]
It also does not work when CssImport is used with themeFor ans several times for the same component.
Then generated-flow-imports.js contains several entries like this
registerStyles('vaadin-accordion-panel', $css_12, {moduleId: 'flow_css_mod'});
registerStyles('vaadin-accordion-panel', $css_13, {moduleId: 'flow_css_mod'});
and only last wins - see 
node_modules\@vaadin\polymer-legacy-adapter\src\style-modules.js

Either fix generation of generated-flow-imports.js 
or style-modules.js

**Comment by xdenser** [comment]
This commit brings breaking changes.
https://github.com/vaadin/flow/commit/9ef3d307f9e218fe5b8d766a571b41fc11f09366
some counter needed around line 
```optionalsMap.put("moduleId", getThemeIdPrefix());```
