### ISSUE TITLE
Warning: There are multiple modules with names that only differ in casing.

### ISSUE THREAD

**Issue by simasch** [vaadin/flow#13240]
### Description of the bug

If I run the app with mvn spring-boot:run on Windows I cannot run it form IntelliJ afterwards.

Cannot run means I see a blank page and the loading indicator is blinking.

I get

```
WARNING in ../node_modules/tslib/tslib.es6.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
```

### Expected behavior

App should run

### Minimal reproducible example

Use a new project from start.vaadin.com

mvn spring-boot:run in the Windows terminal

Then open the project in IntelliJ and run the Application class main method.

### Versions

- Vaadin / Flow version: 23.0.0
- Java version: 17
- OS version: Windows 11
- IDE (if applicable): IntelliJ newest version

**Comment by caalador** [comment]
I couldn't replicate, but I'm still on windows 10 (even though it would be strange if the windows version would cause this)

Which JDK17 are you using? My JDK is Amazon Corretto 17

**Comment by simasch** [comment]
I'm using Eclipse Java 17. It also happens on Windows 10

**Comment by simasch** [comment]
It seems to be an IntelliJ issue:

https://youtrack.jetbrains.com/issue/IDEA-290292

**Comment by caalador** [comment]
Closing ticket as it is an external application issue.
