### ISSUE TITLE
RouterLink is not working inside modal dialog

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#13270]
### Description of the bug

Navigation using RouterLink is not possible inside a modal dialog.

### Expected behavior

Any RouterLink **inside** the dialog can be used to navigate to another page.

### Minimal reproducible example

```java

    add(new Button("Open Modal Dialog", e -> {
      Dialog dialog = new Dialog(new RouterLink("Click Me", AnotherRoute.class));
      dialog.setModal(true);
      dialog.open();
    }));

```

### Versions

- Vaadin / Flow version: 23.0.0 / 23.0.1

**Comment by caalador** [comment]
Seems RouterLink navigation is explicitly denied if UI is inert (in v14 bootstrap mode)
```
            // When the UI is made inert, all router link navigation is
            // ignored. For the part of the UI that is not inert, navigation
            // could be allowed by using something else than router links (with
            // server side listeners).
            // Blocking browser history back / forward navigation is not done
            // as it would be dubious and even impossible on the client side.
```
This ofc shouldn't be the case when the navigation is from inside the modal component. For js bootstrap it is blocked in the connect client due to `inert state navigation is blocked` which is problematic as the UI is always inert if a modal component is set.

**Comment by anssit** [comment]
As pointed out above, it won't be easy to cover all uses of RouterLink inside a modal component. In fact, even the seemingly simple case has no obvious solution currently.

Navigation has been disabled intentionally with the idea that typically one has little reason to navigate when in a modal component. 

We are curious about your use case @knoobie. Why do you need `RouterLink`s inside a modal, and why working around them `by using something else than router links (with server side listeners)` is not an option?

**Comment by knoobie** [comment]
Simply accessibility - links (RouterLink) are the way to go for an inclusive webdesign. I currently have a workaround in place for the specific dialog (making it non-modal) but that was an undocumented behaviour change that should be at least be documented as limitation or mentioned somewhere (that is not a comment inside java code of flow)

**Comment by caalador** [comment]
I guess it should be documented as a limitation on each of the modal components documentation.

Also I couldn't find documentation on the sever-side modality at all so that should be added to the advanced section.

**Comment by knoobie** [comment]
Tbh I was kinda confused that a dialog is by default modal and you have to opt-out from it; that's how I stumbled upon it because I explicitly called setModal(true) on other dialogs but not on this one. 

(I know there is a sentence about it in the docs; still not expected default coming from other business application where you have multiple dialogs side by side opening and dragging them around)
