### ISSUE TITLE
Vaadin 22: Safari 13 should be detected as too old

### ISSUE THREAD

**Issue by darmro** [vaadin/flow#13271]
### Description of the bug

Open https://start.vaadin.com/app on Safari 13. 
The app will appear, but doesn't work properly (there is a lot of js errors on the browser console):

![image](https://user-images.githubusercontent.com/56316289/157694029-4b960685-9413-4cd3-bcad-7eed0ce4a54b.png)

### Expected behavior

Safari 13 should be checked to be too old in Vaadin "browser to old" handler.

### Minimal reproducible example

Just open https://start.vaadin.com/app on Safari 13. 

### Versions

- Vaadin / Flow version: 22.0.8
- OS version: macOS
- Browser version (if applicable):  Safari 13

**Comment by joheriks** [comment]
`EventTarget()` constructor (use by [`@vaadin/components-base`](https://github.com/vaadin/web-components/blob/54decd0cc017ec15d717a063aba63a4c4ccc396a/packages/component-base/src/slot-controller.js#L14)) is [supported from Safari 14](https://caniuse.com/?search=EventTarget()). Increasing minimum version to 14+.
