### ISSUE TITLE
sw.js:1 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://xxxx/sw-runtime-resources-precache.js' failed to load.

### ISSUE THREAD

**Issue by darmro** [vaadin/flow#13303]
### Description of the bug

Production App:  Vaadin 22, Java only + Spring, with PWA, in production mode.
When we upgrade from Vaadin 21 to Vaadin 22 there is an error in the browser js console when a user enters the new app (with updated Vaadin):

```
sw.js:1 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://xxxx/sw-runtime-resources-precache.js' failed to load.
    at Module.<anonymous> (https://xxxxx/sw.js:1:16405)
    at s (https://xxxxx/sw.js:1:110)
    at https://xxxxx/sw.js:1:902
    at https://xxx/sw.js:1:911
The script has an unsupported MIME type ('text/html').
```

Of course, when someone refreshes the browser cache (service worker) everything is ok. But hardly any user has this knowledge. It should be some kind of automatic thing. 

### Expected behavior

I don't know what this `sw-runtime-resources-precache.js` is and when it's uploaded by the browser. 
The user doesn't know we change Vaadin version. We have a dozen thousand users, and they are ordinary people, without the knowledge of the browser and its cache and what service workers are. We cannot instruct them to refresh a browser cache :)
Is there any way to force this `sw-runtime-resources-precache.js` to refresh automatically?

### Minimal reproducible example

The problem is probably general when the app bundle changes after vaadin update to a different version. 

### Versions

- Vaadin / Flow version: 22
- Java version: 1.8
- Browser version (if applicable): Chrome

**Comment by caalador** [comment]
The `sw-runtime-resources-precache.js` is a collection of the asset paths for pre-caching for workbox manifest entries.

It would seem that at some point instead of the js some text/html (probably the index.html) was returned instead in the response and that got cached which causes this issue.

For cleaning it the `CacheStorage` API is suggested in [Clear Workbox cache of all content](https://stackoverflow.com/questions/54376355/clear-workbox-cache-of-all-content)

**Comment by mshabarov** [comment]
Please open a new ticket if the issue is still present. This ticket is being closed due to inactivity.
