### ISSUE TITLE
dynamic registration of route-template in session-scope might break existing routes of application-scope

### ISSUE THREAD

**Issue by olafj** [vaadin/flow#13348]
### Description of the bug

Following situation:
* annotated route "other/view" (OtherView.class)
* annotated route-template ":first/:second" (DefaultView.class)

=> at this point navigation to "other/view" with view OtherView.class works!

* override ":first/:second"  by RouteConfiguratio.forSessionScope().... with class OverrideView.class.

=> at this point navigation to "other/view" does not work anymore. OverrideView.class is shown instead of OtherView.class

* execute RouteConfiguration.forSessionScope().getHandledRegistry().clean() 

=> now navigation to "other/view" with view OtherView.class works again!

### Expected behavior

Navigation to path "other/view" uses OtherView.class at any time.

### Minimal reproducible example

See https://github.com/olafj/vaadin-router-problem. Start the application, default-view displays an intro text to reproduce the problem. 

### Versions

- Vaadin / Flow version: 23
- Java version: 11
- OS version: Ubuntu 21.10
- Browser version (if applicable): does not matter 
- Application Server (if applicable): Tomcat 9
- IDE (if applicable): does not matter

**Comment by caalador** [comment]
The issue is that the session registry is checked for a match first and even though we do a exact match wins a wildcard one we do not in the session registry have the exact match, but we can still find a match so we do not check the application registry where we would have an exact match.

**Comment by olafj** [comment]
@caalador 👍🏻
