### ISSUE TITLE
Backport Atmosphere 2.7.3.slf4jvaadin4 upgrade to Flow 2.8. 

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#13341]
If no issues are discovered with add-ons, pick to 2.7 and release as patchlevel update.

**Comment by mcollovati** [comment]
Following add-ons passes tests locally with upgraded atmosphere:
* CDI (11.3)
* Portlet
* Spring 12.4 
* Spring 12.4 Bower Mode
* MPR 2.2

**Comment by mcollovati** [comment]
Port to 2.8 and 2.7 seems now ok, after then pick of https://github.com/vaadin/flow/pull/13390/commits/4a68ccfeed206cbe55e9401e5a77bbea9b3e8764
