### ISSUE TITLE
package.json's vaading version number less than pom.xml's vaadin number  after build  for 22.0.x

### ISSUE THREAD

**Issue by ylyxf** [vaadin/flow#13352]
### Description of the bug

I want use vaadin flow with jdk 1.8 and spring boot  ,so I chose vaddin 22.0.9.
in the https://vaadin.com/docs/v22/flow/guide/quick-start , the pom.xml in the  download file mytodo.zip use the vaadin 14.8.6
![image](https://user-images.githubusercontent.com/3871920/159948275-367953af-afc4-4104-855f-52d563fc6a84.png)

i think it's a little old for me ,so i download mytodo.zip from https://vaadin.com/docs/latest/flow/guide/quick-start, the new mytodo project's pom.xml is 23.0.1

![image](https://user-images.githubusercontent.com/3871920/159948609-44df2150-4b95-4448-b9de-8b5a62b812ab.png)

i change this all into 22.0.9 
![image](https://user-images.githubusercontent.com/3871920/159948723-f4fd0a9b-19f0-414c-a75b-d204d3d82c72.png)

and make java version to 1.8 in pom.xml

![image](https://user-images.githubusercontent.com/3871920/159948871-e41e916d-c27f-47c0-9f7b-ab485499d0d7.png)

then i run `mvn clean package -Pproduction` and wait all things done .

now , i open the package.json( and pnpm-lock.yaml ),find that ,the vaadin version was changed to 22.0.8 ,but pom.xml is still 22.0.9 
 
![image](https://user-images.githubusercontent.com/3871920/159949409-e5d45c5d-cc3b-4cf0-a680-0269d91cbfa3.png)

### Expected behavior

package.json and  pnpm-lock.yaml 's vaading version should keep the same with pom.xml

### Minimal reproducible example

1.download mytodo.zip from https://vaadin.com/docs/latest/flow/guide/quick-start
2.change all  23.0.1  to 22.0.9 in pom.xml  package.json and  pnpm-lock.yaml  
3. change java.version property from 11 to 1.8 in pom.xml 
4. run mvn clean package -Pproduction
5. check package.json and  pnpm-lock.yaml , you can find many 22.0.8 version numbers 

### Versions

- Vaadin / Flow version: 22.0.9
- Java version:build 1.8.0_291-b10
- OS version: Windows 10 
- Browser version (if applicable):  None
- Application Server (if applicable): None
- IDE (if applicable): command line

**Comment by knoobie** [comment]
This is intended. The version used in the lock file doesn't have to be in sync because sometimes the Platform Release is increased but the web components did not change. See e.g. https://github.com/vaadin/platform/releases

Vaadin makes sure that the appropriate versions are used if you update the pom.xml

**Comment by ylyxf** [comment]
thank you  ! @knoobie
![image](https://user-images.githubusercontent.com/3871920/160035130-c041f85d-cb10-4898-a88f-3c5e89def2d8.png)
