### ISSUE TITLE
Running development mode with pre-bundling should be logged

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#13355]
It is possible to run a project in development mode with prebuilt production bundles and no development server (webpack/vite).

This is possible if executing both `prepare-frontend` and `build-frontend` goals without having production mode enabled.
The end result will be a production mode build with optimized bundles, but with development mode logs and "features" in use.

When running the application in this mode a clear indication should be logged saying `Running in development mode with production bundles. Set application into production mode to disable development mode features.`

Touches #13332

**Comment by Artur-** [comment]
This mode no longer exists
