### ISSUE TITLE
Add tests to make sure vaadin flow works with Chrome/Firefox > 100

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#13387]
### Describe your motivation

In the next weeks the major browsers are going to be released with three-digits major versions. Make sure vaadin flow can detect the versions, doesn't throw and works properly.

See fore more details: https://hacks.mozilla.org/2022/02/version-100-in-chrome-and-firefox/

### Describe the solution you'd like

Unit Tests that those version work.

### Additional context

Inspired by: https://stackoverflow.com/questions/71659794/is-vaadin-ready-for-three-digits-user-agent-strings

**Comment by Artur-** [comment]
Some super quick tests:

- https://demo.vaadin.com/sampler-for-vaadin6/#BrowserInformation shows "You are running Chrome 102.0 in Mac OSX (it is not a touch device)" (Vaadin 6)
- https://demo.vaadin.com/sampler/#foundation/advanced/browser-information shows "Chrome 102.0 in Mac OSX" (Vaadin 8)

It sounds quite improbably that another digit would affect anything but never say never...

**Comment by knoobie** [comment]
> It sounds quite improbably that another digit would affect anything but never say never...

that was exactly my thought for creating this ticket :)
