### ISSUE TITLE
Vaadin 14. Chrome screen trembles when mouseover component

### ISSUE THREAD

**Issue by standreu** [vaadin/flow#13395]
### Description of the bug

I am working with Vaadin 14. When I work with a scrollable VerticalLayout, when I move the mouse over a component inside the VerticaslLayout, the screen begins to tremble. It only happens with Chrome.

Any suggestion?

### Expected behavior

The screen couldn't tremble

### Minimal reproducible example

No example

### Versions

- Vaadin / Flow version: 14
- Java version: 11
- OS version: Windows 11
- Browser version (if applicable): Chrome 
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mcollovati** [comment]
Hello. I'm not able to reproduce the issue. Can you please provide an example project based on [Vaadin Flow Quick Start](https://vaadin.com/docs/v14/flow/guide/quick-start) that reproduces the issue?

**Comment by mshabarov** [comment]
Closed due to no reply from author. Please provide an example project within this ticket or a new one.
