### ISSUE TITLE
Custom converter throws java.lang.ClassCastException when calling setBean on binder for field type of textfield

### ISSUE THREAD

**Issue by rahuldjha** [vaadin/flow#13417]
### Description of the bug

Trying to implement a custom converter for a textfield to a custom data type and bonded the same field with the binder when I call binder.setBean(vo) it throws the given exception

java.lang.ClassCastException: class com.demo.vo.DemoVO cannot be cast to class java.lang.String (com.demo.vo.DemoVO is in unnamed module of loader 'deployment.demo.ear' @7cc3d734; java.lang.String is in module java.base of loader 'bootstrap') at deployment.demo.ear.demo.war//com.vaadin.flow.component.textfield.TextField.setValue(TextField.java:34) at deployment.demo.ear.demo.war//com.vaadin.flow.data.binder.Binder$BindingImpl.convertAndSetFieldValue(Binder.java:1275) at deployment.demo.ear.demo.war//com.vaadin.flow.data.binder.Binder$BindingImpl.initFieldValue(Binder.java:1196) at deployment.demo.ear.demo.war//com.vaadin.flow.data.binder.Binder$BindingImpl.access$200(Binder.java:1032) at deployment.demo.ear.demo.war//com.vaadin.flow.data.binder.Binder.lambda$setBean$1(Binder.java:1772) at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)

### Expected behavior

Should convert the binder type based on converter.

### Minimal reproducible example

DemoVO Class
```
public class DemoVO {
    private int id;
    private String code;
    private String details;
    // getters
    // setters
}
```

Converter Class
```
public class DemoVOToStringConverter implements Converter<String, DemoVO> {

    private DemoVO demoVO;

    @Override
    public Result<DemoVO> convertToModel(String value, ValueContext context) {

        if (null == value)) {
            return Result.ok(null);
        }

        demoVO.setCode(value);
        return Result.ok(demoVO);
    }

    @Override
    public String convertToPresentation(DemoVO value, ValueContext context) {

        if (null == value)) {
            return null;
        }

        demoVO = value;
        return value.getCode();
    }
}
```

HeaderVO Class
```
public class HeaderVO {
        private DemoVO demo = new DemoVO();
        // getter
        // setter
}
```

DemoView Class
```
public class DemoView extends VerticalLayout implements BeforeEnterListener {
            
            private Binder<HeaderVO> binder = null; 
    
            public DemoView() {
                   binder = new Binder<>(HeaderVO.class);
    
                   TextField demoField = new TextField();
                   demoField.setMaxLength(10);
                   demoField.setLabel("Demo");
                   binder.forField(demoField).withConverter(new DemoVOToStringConverter()).bind("demo");
                   add(demoField);
            }
    
        @Override
        public void beforeEnter(BeforeEnterEvent beforeEnterEvent) {
               HeaderVO headerVO = new HeaderVO();
               binder.setBean(headerVO);
        }
   }
```

### Versions

- Vaadin / Flow version: 14.6.7
- Java version: 11.0.8
- OS version: 11 Pro 21H2 22000.588
- Browser version (if applicable): Google Chrome 99.0.4844.84
- Application Server (if applicable): jboss-eap-7.3
- IDE (if applicable): IntelliJ IDEA 2021.2.3 (Community Edition)

**Comment by knoobie** [comment]
Instead of using the bind property by reflection `.bind("demo");`; you could use the explizit calls with `.bind(HeaderVO::getDemo, HeaderVO::setDemo)`

**Comment by rahuldjha** [comment]
> Instead of using the bind property by reflection `.bind("demo");`; you could use the explizit calls with `.bind(HeaderVO::getDemo, HeaderVO::setDemo)`

Non-static method cannot be referenced from a static context !

**Comment by rahuldjha** [comment]
> Instead of using the bind property by reflection `.bind("demo");`; you could use the explizit calls with `.bind(HeaderVO::getDemo, HeaderVO::setDemo)`

Found the RC its working now, thanks @knoobie for the quick response.
