### ISSUE TITLE
Object (and embed) doesn't work being added as an element via HB

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#1344]
Create an `Element` with "object" tag.
Set `type` to `"image/svg+xml"`
and set `data` attribute to some SVG image (e.g. use http://tecfa.unige.ch/guides/svg/ex/html5/green-circle.svg URL).
Add the element to the document,
Check it in EDGE.
Result: image is not shown.
For some reasons the svg URL is requested via HEAD http requested not GET.
It works fine in Chrome, FF and Safari.

It works also fine in EDGE if static markup is used.
May be something specific to "data" attribute.

**Comment by pleku** [comment]
This has been fixed by #481
