### ISSUE TITLE
vaadin-maven-plugin for Version 23.0.4 installing dependencies via prepare-frontend

### ISSUE THREAD

**Issue by 4soft-liebig** [vaadin/flow#13512]
### Description of the bug

Hi,

when running vaadin-maven-plugin:prepare-frontend behind a corporate proxy with configured proxy-settings, I get:

```
build	12-Apr-2022 12:15:08	[INFO] Globally node version 14.15.1 is older than 16.14.0. Using node from /appl/bamboo-home/.vaadin.
build	12-Apr-2022 12:15:08	[INFO] Couldn't find node. Installing Node and npm to /appl/bamboo-home/.vaadin.
build	12-Apr-2022 12:15:08	[INFO] Installing node version v16.14.2
build	12-Apr-2022 12:15:08	[INFO] Downloading https://nodejs.org/dist/v16.14.2/node-v16.14.2-linux-x64.tar.gz to /appl/bamboo-home/.vaadin/node-v16.14.2-linux-x64.tar.gz
build	12-Apr-2022 12:15:08	[INFO] No proxies configured
build	12-Apr-2022 12:15:08	[INFO] No proxy was configured, downloading directly
build	12-Apr-2022 12:15:08	[ERROR] Node.js download failed. This may be due to loss of internet connection.
build	12-Apr-2022 12:15:08	If you are behind a proxy server you should configure your proxy settings.
build	12-Apr-2022 12:15:08	Verify connection and proxy settings or follow the https://nodejs.org/en/download/ guide to install Node.js globally.
```

We configure the maven-settings via `.mvn/maven.config`
```
--no-transfer-progress --settings .mvn/project-settings.xml --update-snapshots --errors
```

and the settings are (which work in a different module with (see https://github.com/eirslett/frontend-maven-plugin) out of the box):
```
        <proxy>
            <id>http-proxy</id>
            <active>true</active>
            <protocol>http</protocol>
            <host>proxy-url</host>
            <port>3128</port>
            <username>${env.BUILD_USER}</username>
            <password>${env.BUILD_PWD}</password>
            <nonProxyHosts>localhost|127.0.0.1</nonProxyHosts>
        </proxy>
```

I tried to download node via frontend-maven-plugin myself, but I cannot configure vaadin-maven-plugin:build-frontend to use an own node-version. Trying to look at the plugin's source code I found https://github.com/vaadin/maven-plugin/tags, but I'm not sure how the latest tag 7.7.31 relates to the current vaadin-maven-plugin:23.0.4 (see https://mvnrepository.com/artifact/com.vaadin/vaadin-maven-plugin/23.0.4).

### Expected behavior

Node should be downloaded and installed successfully to ${HOME}/.vaadin

### Minimal reproducible example

I'm afraid I cannot provide such a setup, since it involves a proxy.

### Versions

- Vaadin / Flow version: 23.0.4
- Java version: 17.0.2
- OS version: Linux
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by Artur-** [comment]
Seems to me that Flow tries to find proxies using system properties and environment variables: https://github.com/vaadin/flow/blob/8e0351cc68a868d82db38462a25dfa1e1681e4c0/flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java#L719-L724

but `frontend-maven-plugin` gets it from Maven: https://github.com/eirslett/frontend-maven-plugin/blob/4d13f04678a8a24c0253a15089fe5426ab7f93b7/frontend-maven-plugin/src/main/java/com/github/eirslett/maven/plugins/frontend/mojo/MojoUtils.java#L38
