### ISSUE TITLE
Web Storage API

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/flow#13524]
### Describe your motivation

While there are ways to share data at the session and UI scopes on the server-side, there are instances where I'd want the data-sharing to be only on the client-side.

### Describe the solution you'd like

Provide a Java API to manipulate [Web Storage](https://en.wikipedia.org/wiki/Web_storage) (both  localStorage and sessionStorage).

**Comment by Artur-** [comment]
There is an implementation already in Viritin that can be integrated

**Comment by mstahv** [comment]
We are having a workshop with @simasch to make DX enhancements and this came up. I have been using the Viritin version in several occasions without issues, so that solution ought to be ready for prime time. To which module/package should it end up in?

**Comment by mstahv** [comment]
The feature in Viritin: https://github.com/viritin/flow-viritin/blob/v24/src/main/java/org/vaadin/firitin/util/WebStorage.java
