### ISSUE TITLE
Vite doesn't work with a custom theme that packaged as jar

### ISSUE THREAD

**Issue by jorginius** [vaadin/flow#13538]
### Description of the bug

Vite cannot find and serve a custom theme that packaged as jar.

### Minimal reproducible example

[extend-existing-app-theme-demo](https://github.com/vaadin/custom-theme-demo/tree/main/extend-existing-app-theme-demo) with `vaadin.version=23.0.3` and  `com.vaadin.experimental.viteForFrontendBuild=true`. 

### Expected behavior

It should work just like in webpack.

### Actual behavior

`application-theme-plugin/theme-loader` cannot find the packaged theme because the `themeResourceFolder` value on `vaadin-dev-server-settings.json` is not correct .

The application starts in dev mode but vite dev server cannot find the resources. It's looking for them in frontend/themes but they are in target/flow-frontend/themes

[custom-theme-demo](https://github.com/vaadin/custom-theme-demo) with `vaadin.version=23.0.3` and webpack works properly.

### Versions:
    - Vaadin / Flow version: 23.0.3
    - Java version: 17.0.1
    - Development or production mode: development

**Comment by jorginius** [comment]
I think it is not working (in dev mode at least)

The packaged theme seems to be working now (`theme-parent.generated.js` can be found and compiled)  but my main theme that inherits from it is not.

Chrome dev tools throw this error:

`GET http://localhost:8080/VAADIN/<absolute_path>/target/flow-frontend/themes/main/styles.css?inline net::ERR_ABORTED 404 theme-main.generated.js:49 `

The line 49 of the transpiled `theme-main.generated.js`:

`import stylesCss from '/VAADIN/<absolute_path>/target/flow-frontend/themes/main/styles.css?inline';`

But `themes/main/styles.css` is located in `frontend/themes/main/styles.css` and cannot be found.

Either of these two lines seems to work correctly:

* `import stylesCss from '/VAADIN/<absolute_path>/frontend/themes/main/styles.css?inline';`
* `import stylesCss from '/VAADIN/themes/main/styles.css?inline';`

**Comment by Artur-** [comment]
Is the original test case still valid for testing this?

**Comment by jorginius** [comment]
I think so.

The "Minimal reproducible example" is the
[extend-existing-app-theme-demo](https://github.com/vaadin/custom-theme-demo/tree/main/extend-existing-app-theme-demo)

The demo uses a packaged theme (`custom-theme`) *and* extends it. The fix solves the first part (i.e. [reusing-theme-jar-demo](https://github.com/vaadin/custom-theme-demo/tree/main/reusing-theme-jar-demo) works fine) but you cannot inherit from custom.

**Comment by caalador** [comment]
On the flow test side it would be `flow-tests/test-application-theme/test-reusable-as-parent/` that fails with vite due to the alias resolution not being run each time the alias is encountered, but only once it seems.

So now it sets the alias to the reusable folder, as it is gotten first, and can't then find the actual theme files anymore as they arre not under target.
