### ISSUE TITLE
`postinstall` in `package.json` scripts seems not to be executed anymore in VAADIN 23+ with `vaadin-maven-plugin:build-frontend`

### ISSUE THREAD

**Issue by DManstrator** [vaadin/flow#13537]
### Description of the bug

This is a bug regarding the VAADIN Maven Plugin. I hope this is the right place, I couldn't find a dedicated GitHub repository for it.

In our project, we adjusted the `tsconfig.json` to use a custom output directory for compiled JS files. This was set to `frontend/target` and worked for years now including VAADIN 22.0.12. After upgrading to VAADIN 23, this folder won't be created anymore.

It was created when building the application in production mode / starting the application in non-production mode.

We rely on a JS file in the `frontend/target` folder to be present with using `@JsModule("./target/folder1/component.js")` in a Java class (see Minimal reproducible example).

As said, since VAADIN 23, this folder won't be created anymore. Due to that, the required JS file cannot be found leading to a failure of the `build-frontend` goal of the VAADIN Maven Plugin.

### Error Log

```log
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:23.0.5:build-frontend (default) on project %project name%: Could not execute build-frontend goal: Error occured during goal execution:
[ERROR]
[ERROR]   Failed to find the following files:
[ERROR]       - ./target/folder1/component.js
[ERROR]
[ERROR]   Locations searched were:
[ERROR]       - `C:\Users\%username%\[...]\project\frontend` in this project
[ERROR]       - `META-INF/frontend` in included JARs
[ERROR]       - `META-INF/resources/frontend` in included JARs
```

### Debugging

From debugging I noticed that **the `postinstall` defined in the `package.json` scripts isn't executed anymore since VAADIN 23**. There we have `"postinstall": "tsc"` which should create the `frontend/target` folder which is missing now (see Minimal reproducible example). This is most likely the issue for the bug.

**VAADIN 22:**
```log
[INFO] Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
[DEBUG] 
C:\Program Files\nodejs\npm.cmd --no-update-notifier \
    --no-audit --scripts-prepend-node-path=true install

[DEBUG] Output of `C:\Program Files\nodejs\npm.cmd --no-update-notifier --no-audit --scripts-prepend-node-path=true install`:
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up 
to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
[DEBUG] 
[DEBUG] > postinstall
[DEBUG] > tsc
[DEBUG]
[DEBUG] 
[DEBUG] added 1436 packages in 3m
[DEBUG]
[DEBUG] 102 packages are looking for funding
[DEBUG]   run `npm fund` for details
[INFO] Frontend dependencies resolved successfully.
```

**VAADIN 23:**
```log
[INFO] Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
[INFO] Globally node version 16.13.1 is older than 16.14.0. Using node from C:\Users\%username%\.vaadin.
[DEBUG] Using node 16.14.0 located at C:\Users\%username%\.vaadin\node\node.exe
[DEBUG] Using npm 8.3.1 located at C:\Users\%username%\.vaadin\node\node.exe
[DEBUG] 
C:\Users\%username%\.vaadin\node\node.exe \
    C:\Users\%username%\.vaadin\node\node_modules\npm\bin\npm-cli.js \
    --no-update-notifier --no-audit \
    --scripts-prepend-node-path=true --ignore-scripts \
    install

[INFO] using 'C:\Users\%username%\.vaadin\node\node.exe C:\Users\%username%\.vaadin\node\node_modules\npm\bin\npm-cli.js --no-update-notifier --no-audit --scripts-prepend-node-path=true --ignore-scripts install' for frontend package installation
[WARNING] package-lock.json is missing from this project. This may cause the npm package installation to take several minutes. It is recommended to keep the package-lock.json file persistently in your project. Please stand by...    
[DEBUG] Output of `C:\Users\%username%\.vaadin\node\node.exe C:\Users\%username%\.vaadin\node\node_modules\npm\bin\npm-cli.js --no-update-notifier --no-audit --scripts-prepend-node-path=true --ignore-scripts install`:
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up 
to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
[DEBUG] 
[DEBUG] added 1208 packages in 3m
[DEBUG]
[DEBUG] 101 packages are looking for funding
[DEBUG]   run `npm fund` for details
[INFO] Frontend dependencies resolved successfully.
```

### Expected behavior

The folder should be created by `tsc` after building in production mode or starting the application in non-production mode.

### Minimal reproducible example

I made an example project showcasing it: [missing-target-folder.zip](https://github.com/vaadin/flow/files/8482105/missing-target-folder.zip)

Note: I downloaded the project from https://vaadin.com/docs/latest/flow/guide/quick-start and adjusted it.

Simply run `mvn clean install -Pproduction` to build it.

It has a git repository so you can have a look at `229bdcaf2dfb9206ef4fa1021787cd5a738281a0` to see what I exactly changed. This commit uses VAADIN 22.0.12. The build will succeed on that commit.

In commit `95f7d3e33b7eeb67f802d7aa6e86f13632d402aa`, I set the version back to VAADIN 23.0.5. The build will fail on that commit.

Important parts:
- Added a dummy TS and Java file.
- Added our `scripts` section in the `package.json`.
- Adjustments to the `tsconfig.json`.
- Set `pnpm.enable` to `false` in the `pom.xml`.

### Versions

- Vaadin / Flow version: 23.0.0+
- Java version: 17.0.2 2022-01-18 LTS
- OS version: Windows 10 21H1
- Browser version (if applicable): Not needed.
- Application Server (if applicable): Not needed.
- IDE (if applicable): Not needed.

**Comment by Artur-** [comment]
Scripts were indeed disabled for "npm install" in V23 in #12127 to greatly reduce the risk of supply chain attacks.

One potential fix would be to run the script as part of the frontend build instead, like done for Vite in cookbook here https://github.com/vaadin/cookbook/blob/ecbef4ca540fea88f7518ef10fe69f4f30453cb1/vite.config.ts#L13-L25

**Comment by DManstrator** [comment]
Hello Artur,

thank you for your fast reply.

We don't use Vite in our project and I've honestly no idea, where I could add it.

I tried setting it in Maven with the `frontend-maven-plugin` but that requires a phase instead of a goal when to execute it. So this seems to be no option.

We use Webpack and have a `webpack.config.js`, could it be added there?

**Comment by Artur-** [comment]
You can add it in the same way in `webpack.config.js`

**Comment by DManstrator** [comment]
I already tried that but it wasn't executed at all, so I thought it was the wrong place.

```log
// same as above
[DEBUG] added 1304 packages in 22s
[DEBUG]
[DEBUG] 101 packages are looking for funding
[DEBUG]   run `npm fund` for details
[INFO] Frontend dependencies resolved successfully.
[DEBUG] Running postinstall for 'esbuild'
[DEBUG] Running postinstall for '@vaadin/vaadin-usage-statistics'
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 220 resources. Took 100 ms.
[DEBUG] Found no local frontend resources for the project
[DEBUG] Updated C:\Users\%username%\[...]\project\target\frontend\generated-flow-imports-fallback.js
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  58.562 s
[INFO] Finished at: 2022-04-14T11:46:15+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:23.0.4:build-frontend (default) on project daem: Could not execute build-frontend goal: Error oc
cured during goal execution:
[ERROR]
[ERROR]   Failed to find the following files:
[ERROR]       - ./target/folder1/component.js
[ERROR]
[ERROR]   Locations searched were:
[ERROR]       - `C:\Users\%username%\[...]\project\frontend` in this project
[ERROR]       - `META-INF/frontend` in included JARs
[ERROR]       - `META-INF/resources/frontend` in included JARs
```

Do I have to do something in addition to that like building it differently?

**Comment by DManstrator** [comment]
I already tried that but it wasn't executed at all, so I thought it was the wrong place.

```log
// same as above
[DEBUG] added 1304 packages in 22s
[DEBUG]
[DEBUG] 101 packages are looking for funding
[DEBUG]   run `npm fund` for details
[INFO] Frontend dependencies resolved successfully.
[DEBUG] Running postinstall for 'esbuild'
[DEBUG] Running postinstall for '@vaadin/vaadin-usage-statistics'
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 220 resources. Took 100 ms.
[DEBUG] Found no local frontend resources for the project
[DEBUG] Updated C:\Users\%username%\[...]\project\target\frontend\generated-flow-imports-fallback.js
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  58.562 s
[INFO] Finished at: 2022-04-14T11:46:15+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:23.0.4:build-frontend (default) on project %project name%: Could not execute build-frontend goal: Error occured during goal execution:
[ERROR]
[ERROR]   Failed to find the following files:
[ERROR]       - ./target/folder1/component.js
[ERROR]
[ERROR]   Locations searched were:
[ERROR]       - `C:\Users\%username%\[...]\project\frontend` in this project
[ERROR]       - `META-INF/frontend` in included JARs
[ERROR]       - `META-INF/resources/frontend` in included JARs
```

Do I have to do something in addition to that like building it differently?

**Comment by DManstrator** [comment]
I believe I know why it (still) fails.

Before, the postinstall `tsc` was executed right after the `npm install` and before Webpack was running.

```log
[INFO] Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
[DEBUG] 
C:\Program Files\nodejs\npm.cmd --no-update-notifier \
    --no-audit --scripts-prepend-node-path=true install
[...]
[DEBUG]
[DEBUG] > postinstall
[DEBUG] > tsc
[DEBUG]
[DEBUG] 
[DEBUG] added 1393 packages in 31s
[DEBUG]
[DEBUG] 106 packages are looking for funding
[DEBUG]   run `npm fund` for details
[INFO] Frontend dependencies resolved successfully.
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 284 resources. Took 254 ms.
[DEBUG] Found no local frontend resources for the project
[DEBUG] Updated C:\Users\%username%\[...]\%project%\target\frontend\generated-flow-imports-fallback.js
[DEBUG] Updated C:\Users\%username%\[...]\%project%\target\frontend\generated-flow-imports.js
[DEBUG] Updated C:\Users\%username%\[...]\%project%\target\frontend\generated-flow-imports.d.ts
[INFO] Reflections took 1843 ms to scan 285 urls, producing 16269 keys and 85974 values
[INFO] Running Webpack ...
[DEBUG]
C:\Program Files\nodejs\node.exe \
    .\node_modules\webpack\bin\webpack.js
[...]
```

Now, the `tsc` would run with the beginning of Webpack being run when I understood it correctly.

However the expected JS files are checked before Webpack is running. They are checked when those `generated-flow-imports` files are being updated as you can see in [the error message above](#issuecomment-1098995424).

So it seems not to be a solution to adjust the `webpack.config.js`.

Can you tell me how I can manage to execute the `tsc` right in time? I honestly don't know too much about it.

**Comment by DManstrator** [comment]
Hello,

I wasn't able to find a solution for my issue yet and I still need help regarding this.

The problem is that I don't know how to execute the `tsc` just in time so the compiled TS files exist. From what I know, it should only run during the `build-frontend` execution (so either when building in production mode or when starting the application). However it has to run before those `generated-flow-imports` are getting generated. And I don't know how to manage this.

Do you need more information?

Kind Regards,

Daniel

**Comment by svein-loken** [comment]
Same problem here. This stopped to work:
![image](https://user-images.githubusercontent.com/105504445/171938493-a2a9ab6b-4329-4dc9-ad0b-2f8db9ad01fd.png)

**Comment by Artur-** [comment]
We could change the logic to run the postinstall for the project itself also by default. I cannot imagine any security implication of that

**Comment by RainerGanss** [comment]
We have the same issue as described by @DManstrator. This blocks us from upgrading to vaadin 23!

**Comment by DManstrator** [comment]
Can confirm VAADIN 23.1.1 could be build again due to the `postinstall` script running again. No additional changes were needed. Thanks!
