### ISSUE TITLE
Client sending large amount of requests

### ISSUE THREAD

**Issue by s57jr** [vaadin/flow#13548]
### Description of the bug 

For some of our users, when the connectionto the server is lost, the client starts sending large amount of requests (~60/second) which puts a huge load on our system. After the browser is reopened the issue is resolved. 

### Minimal reproducible example

Unfortunately the issue is not easily reproduced. From around 2000 active clients, it appeared for 8 of them until now. 
The issue started occurring after upgrade from vaadin 14.7.5 to 14.8.0, and persists until now (14.8.8).
Example of such request is:

`20220414 12:01:00;84.255.204.27;[issuer=-; subject=-; serial=- ; vf=NONE; proto=TLSv1.2 ; ciph=ECDHE-RSA-AES256-GCM-SHA384] ; "GET /vep-wt/?v-r=push&v-uiId=4&v-pushId=e0f7d0dd-ae72-4f7e-95e7-a35e8b671feb&X-Atmosphere-tracking-id=9e37baf8-1fc0-407a-93d6-0da2a1986452&X-Atmosphere-Framework=2.3.2.vaadin1-javascript&X-Atmosphere-Transport=long-polling&X-Atmosphere-TrackMessageSize=true&Content-Type=application%2Fjson%3B%20charset%3DUTF-8&X-atmo-protocol=true&_=1649930460406 HTTP/1.1";200;2107;"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"`

#### Browsers on which the issue occured (Chrome and Edge)
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36`

### Expected behavior

The client session should expire.

### Actual behavior

Client keeps sending requests

### Versions:
    - Vaadin / Flow version: 14.8.8
    - Java version: jdk-11.0.13
    - OS version: server on Ubuntu 18, clients on windows 10 
    - Browser version (if applicable): Chrome and Edge
    - Application Server (if applicable): wildfly 20.0.0.

**Comment by mshabarov** [comment]
Closed due to no response from author. If this is still an issue, please reopen the ticket and provide more information.
