### ISSUE TITLE
Adding JS into a Html Object malformes the JS on the frontend.

### ISSUE THREAD

**Issue by TheSilentHorizon** [vaadin/flow#13544]
### Description of the bug

When I enter for example a onClick in a element inside my Html Object like this:

`onClick="sfmanager.getConnector('test').testMethod()"`

But the output on frontend turns into this:

`onClick="sfmanager.getConnector("test').testMethod()'`

### Expected behavior

`onClick="sfmanager.getConnector('test').testMethod()"` should be set correctly.

### Minimal reproducible example

Create a HTML Object with a div with something like : onClick="sfmanager.getConnector('test').testMethod()"

### Versions

- Vaadin / Flow version: 23.0.3
- Java version: 16
- OS version: Windows 11
- Browser version (if applicable): Chrome
- Application Server (if applicable): Spring Boot
- IDE (if applicable): Jetbrains IntelliJ 2022.1

**Comment by Legioth** [comment]
I guess this isn't about JS in itself, but rather about using single quotes (`'`) inside any attribute value that is enclosed in double quotes (`"`). This is likely to happen with inline JS event handlers, but could just as well happen with something like `<span title="Codename: 'magic lizard'">`

**Comment by mcollovati** [comment]
Hi, thanks for reporting.
I was not able to reproduce the bug. Could you please provide a complete working example?

**Comment by mshabarov** [comment]
Closed due to no response from author. If this is still an issue, please reopen the ticket and provide more information.
