### ISSUE TITLE
vaadin-maven-plugin failed to build-frontend after updating java level to 17

### ISSUE THREAD

**Issue by kyberorg** [vaadin/flow#13545]
### Description of the bug

After updating language version to Java 17 vaadin-maven-plugin fails to compile frontend due to reflection error.

```
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:23.0.5:build-frontend (default) on project yalsee: Could not execute build-frontend goal: Error occured during goal execution: Cannot invoke "java.lang.Class.isInterface()" because the return value of "org.reflections.Reflections.forClass(String, java.lang.ClassLoader[])" is null
```

Full stacktrace is [here](https://gist.github.com/kyberorg/148c77e6b7a0193c7c0a08a765edcf10)

### Expected behavior

Application compile into JAR-file without issues

### Minimal reproducible example

* `git clone https://github.com/kyberorg/yalsee.git`
* `cd yalsee`
* `git checkout 827-java-17-code-adaption `
* `mvn -Pproduction-mode,noTesting clean package`

### Versions

- Vaadin / Flow version: 23.0.5
- Java version: 17.0.3 OpenJDK
- OS version:  "linux", version: "5.16.14-1-manjaro", arch: "amd64", family: "unix"
- Maven version: 3.8.1
- Browser version (if applicable): N/A
- Application Server (if applicable): N/A
- IDE (if applicable): IDEA

**Comment by mcollovati** [comment]
Seems like the problem is somehow related to lombok and `--enable-preview` flag.
The NPE is due to failure in loading class `MyLinksPage` 
```
Preview features are not enabled for io/kyberorg/yalsee/ui/pages/mylinks/MyLinksPage (class file version 61.65535). Try running with '--enable-preview')
```
Adding the `--enable-preview` flag to the main process seems to solve the issue (eg `export MAVEN_OPTS="$MAVEN_OPTS --enable-preview"`)

**Comment by kyberorg** [comment]
@mcollovati I can confirm, that adding `--enable-preview` leads to successful compilation.  Thanks/Kiitos.

**Comment by jcaSteelElec** [comment]
Hi everyone, I am new on the github forum and I don't know where I can post my question about this issu.
Where I can add in my project "--enable-preview" ? in the POM ? Thnk you in advance

**Comment by ZhukovAlV** [comment]
https://stackoverflow.com/questions/72083752/enable-preview-features-in-an-early-access-version-of-java-in-intellij It is written in detail here
