### ISSUE TITLE
Atmosphere 3 with Servlet 5: Exceptions logged during flow-server tests

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#13571]
Exceptions logged during `flow-server` tests on Atmosphere initialisation: 
`NoClassDefFoundError: jakarta/annotation/PostConstruct`. Tests pass but perhaps dependencies should be checked.

**Comment by mcollovati** [comment]
Closing, as adding test dependency fixes the issue.
For `jakarta.annotaion` see #13653
