### ISSUE TITLE
Migrate plain servlet and spring skeleton projects to Servlet 5

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#13570]
Migrate ~Bakery project https://github.com/vaadin/bakery-app-starter-flow-spring/tree/master~ plain servlet and Spring boot skeleton starters to Servlet 5 and Spring Boot 3 using feature branch in Flow and Spring Boot 3 intermediate version.
Estimate:
- efforts needed for migration
- possible issues during migration

**Comment by knoobie** [comment]
Random thought: is it enough to just release two different flow artifacts for the current Servlet version and Servlet 5? Should there be two spring boot artifacts as well for 2.x and 3.x?

**Comment by Artur-** [comment]
I think the main problem will not be servlet version nor Spring Boot version per se but the fact that Spring Boot 2 and 3 will use widely different dependency versions. When looking at the list here https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.6.6/spring-boot-dependencies-2.6.6.pom and assuming that the major version of many of those dependencies will be different in Spring Boot 3, it will become quite impossible to support both Spring Boot 2 and 3 at the same time, especially in the long run. Those dependencies affect many modules, not only the modules of Flow that depend on the servlet version.

**Comment by knoobie** [comment]
Totally agree with your on that! Spring Boot 2.7.x is (at the moment) the last planned release in the 2 series that is going to be maintained for an additional year (or two with paid support) - so it's really interesting how Vaadin stance is on this.. like do you guys instant go on SB 3 in Q1 2023 or do you have two different modules for SB 2 and SB 3 for like a year or so to allow people to choose? 

Spring Boot Support Roadmap:

![image](https://user-images.githubusercontent.com/3968629/164389499-146f00cf-9b71-401a-a43a-cbf8bf2b14cc.png)

Source: https://spring.io/projects/spring-boot#support

**Comment by mshabarov** [comment]
Done:
https://github.com/vaadin/skeleton-starter-flow/tree/feature/jakarta-servlet5
https://github.com/vaadin/skeleton-starter-flow-spring/tree/jakarta-servlet5

and with stater project from start.vaadin.com
https://github.com/mshabarov/JakartaServlet5
