### ISSUE TITLE
EventHandler should be able to stopPropagation and preventDefault

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#1363]
@EventHandler should be extended to have the possibility to stopPropagation and/or preventDefault for the handled event.

**Comment by Legioth** [comment]
This could relatively easily be implemented based on the `DomListenerRegistration` API that has been introduced for the filter and debounce functionality.

Should also consider making the same functionality available when the listener defined using `@DomEvent`.

**Comment by Legioth** [comment]
As a workaround, you can do something like `somElement.addEventListener("click", handleEvent).addEventData("event.stopPropagation();")`

**Comment by manolo** [comment]
@Legioth  Is this feature going to happen? we have a case in vaadin-crud that we need a connector just to prevent default on certain actions and skip they to be taken in client side, because server side handles them.  https://github.com/vaadin/vaadin-crud-flow/blob/master/vaadin-crud-flow/src/main/resources/META-INF/resources/frontend/crudConnector.js

**Comment by Legioth** [comment]
Ping @pleku for prioritization questions. In the meantime, you can maybe use the `addEventData` workaround instead of having to introduce a connector?

**Comment by Legioth** [comment]
In the case of a `ComponentEvent` type, you can also add an `@EventData("event.stopPropagation();") Object ignored` constructor parameter to get the same result.

**Comment by manolo** [comment]
We will try to use the workaround in the meantime, and mark it with a FIXME pointing to this

**Comment by Legioth** [comment]
@Springrbua What you describe is caused by https://github.com/vaadin/flow/issues/4871. What you can do is to not rely on event data but instead create a slightly more complex filter expression that also runs `event.preventDefault()` before returning `true` to indicate that the event should be sent to the server.

**Comment by pleku** [comment]
For the shortcut API this is done, but adding it to `EventHandler` is a separate thing.

The shortcut API just sets it as a filter text to the events https://github.com/vaadin/flow/blob/c831ca8259318c25c86c75155fcd20d8e96b43d2/flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java#L441 and

**Comment by Duncol** [comment]
Hi, I'm trying to use @Legioth 's `event.preventDefault()` workaround in terms of 'ondrop' and it doesn't seem to work (i.e. browser still opens dropped file). I've checked on 'raw' HTML/JS project and it works as long as we prevent default for 'dragover' also:
```
const element = document.getElementById('drop');
element.addEventListener("dragover",function(e){
  e = e || event;
  e.preventDefault();
},false);
element.addEventListener("drop",function(e){
  e = e || event;
  e.preventDefault();
},false);
```
And Java code:
        element.addEventListener("dragover", event -> {
            LOG.trace("You're in the element's drag zone");
        }).addEventData("event.preventDefault()");
        element.addEventListener("drop", event -> {
            LOG.trace("You've dropped something on the element");
        }).addEventData("event.preventDefault()");

Any ideas? What am I missing?

**Comment by Springrbua** [comment]
@Duncol I have added the `event.preventDefault()` as a `Filter`, not as `EventData`.  
So you could try the following:
```
element.addEventListener("dragover", event -> {
    LOG.trace("You're in the element's drag zone");
}).setFilter("event.preventDefault() || true");
element.addEventListener("drop", event -> {
    LOG.trace("You've dropped something on the element");
}).setFilter("event.preventDefault() || true");
```

Note, that the `|| true` is needed, since `preventDefault` has no return value, which results in `falsy` and the `event` would not be sent to the server.

**Comment by mvysny** [comment]
Having `DomListenerRegistration.preventDefault()` would be useful also for the following use-case:
```
        button.getElement().addEventListener("contextmenu", (DomEventListener) event -> System.out.println("Completely customized context menu")).addEventData("event.preventDefault()");
```

**Comment by enver-haase** [comment]
@pleku ping - any news?

**Comment by caalador** [comment]
@enver-haase it's @mshabarov that is the Flow PO now.
