### ISSUE TITLE
How to use a pre-release

### ISSUE THREAD

**Issue by jonasrotilli** [vaadin/flow#13652]
An innocent question, how do I use a pre-release version?

I add in my pom.xml 
`<vaadin.version>23.1.0.alpha3</vaadin.version>`
And ok, compiling via Intellij works.

But when trying to generate a Jar, via mvn clean install, I get error:
`[ERROR] Non-resolvable import POM: Could not transfer artifact com.vaadin:vaadin-spring-bom:pom:23.1.0.alpha3`

**Comment by knoobie** [comment]
You need to define the pre release repos. 

```xml

    <repositories>
        <!-- The order of definitions matters. Explicitly defining central here to make sure it has the highest priority. -->

        <!-- Main Maven repository -->
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>vaadin-prereleases</id>
            <url>https://maven.vaadin.com/vaadin-prereleases/</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <!-- The order of definitions matters. Explicitly defining central here to make sure it has the highest priority. -->
        <pluginRepository>
            <id>central</id>
          <url>https://repo.maven.apache.org/maven2</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
        <pluginRepository>
            <id>vaadin-prereleases</id>
            <url>https://maven.vaadin.com/vaadin-prereleases/</url>
        </pluginRepository>
      </pluginRepositories>

```

**Comment by jonasrotilli** [comment]
> ```
> pluginRepositories
> ```

It's exactly like that.
As I said, compiling via Intellij works, but generating a jar via MVN doesn't.

**Comment by jonasrotilli** [comment]
Can't generate an application via nvm with a pre-realese?

The goal is to provisionally put it on the air to test a feature.

**Comment by Artur-** [comment]
Either your mvn is using an invalid cache and you need run ”mvn -U” or you have something wrong in the project and can get a working example from start.vaadin.com by selecting 23.1 from settings

**Comment by mcollovati** [comment]
@jonasrotilli can you confirm if Artur's suggestions are working for you?

**Comment by jonasrotilli** [comment]
> @jonasrotillivocê pode confirmar se as sugestões de Artur estão funcionando para você?

Did not work.
I can only generate the mvn if I put version 23.0.8.

In Maven pre-realese repository only has 23.1.0.alpha1, here on github it already has alpha4.
But even trying alpha1 does not generate.
The return is:

`[INFO] Scanning for projects...
Downloading: http://repo.maven.apache.org/maven2/com/vaadin/vaadin-spring-bom/23.1.0.alpha1/vaadin-spring-bom-23.1.0.alpha1.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.vaadin.tutorial.crm:vaadin-crm:1.0-SNAPSHOT (/Users/jonasrotilli/Documents/upCampo_vaadin22/pom.xml) has 3 errors
[ERROR]     Non-resolvable import POM: Could not transfer artifact com.vaadin:vaadin-spring-bom:pom:23.1.0.alpha1 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/com/vaadin/vaadin-spring-bom/23.1.0.alpha1/vaadin-spring-bom-23.1.0.alpha1.pom. Return code is: 501, ReasonPhrase: HTTPS Required. @ com.vaadin:vaadin-bom:23.1.0.alpha1, /Users/jonasrotilli/.m2/repository/com/vaadin/vaadin-bom/23.1.0.alpha1/vaadin-bom-23.1.0.alpha1.pom, line 35, column 19 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for com.vaadin:vaadin:jar is missing. @ line 124, column 21
[ERROR]     'dependencies.dependency.version' for com.vaadin:vaadin-spring-boot-starter:jar is missing. @ line 156, column 21
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
`

**Comment by mcollovati** [comment]
One thing I can notice from the logs above is that maven is trying to download using http and not https.
Please double check that urls in pom file repository settings are all using https.
Second thing is that alpha versions should be resolved by vaadin-prereleases repository.
Can you please share your full pom.xml file, so we can check it?

**Comment by jonasrotilli** [comment]
> Uma coisa que posso notar nos logs acima é que o maven está tentando baixar usando http e não https. Por favor, verifique se os URLs nas configurações do repositório de arquivos pom estão todos usando https. A segunda coisa é que as versões alfa devem ser resolvidas pelo repositório vaadin-prereleases. Você pode compartilhar seu arquivo pom.xml completo, para que possamos verificá-lo?

Yes, the prerealeses repository is in the pom, I even put it in priority order (like first), but it still didn't work.

Follow the complete pom, thanks for the help:

`<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.vaadin.tutorial.crm</groupId>
    <artifactId>vaadin-crm</artifactId>
    <name>Vaadin CRM</name>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <java.version>11</java.version>
        <vaadin.version>23.1.0.alpha1</vaadin.version>
    </properties>

    <parent>
        <groupId>org.springframework.boot</groupId>
        
        <artifactId>spring-boot-starter-parent</artifactId>

        <version>2.6.6</version>
    </parent>

    <repositories>
        

        
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>

        <repository>
            <id>vaadin-prereleases</id>
            <url>
                https://maven.vaadin.com/vaadin-prereleases/
            </url>
        </repository>

        
        <repository>
            <id>Vaadin Directory</id>
            <url>https://maven.vaadin.com/vaadin-addons</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        
        <pluginRepository>
            <id>vaadin-prereleases</id>
            <url>
                https://maven.vaadin.com/vaadin-prereleases/
            </url>
        </pluginRepository>
        <pluginRepository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>

    </pluginRepositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-bom</artifactId>
                <version>${vaadin.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20211205</version>
        </dependency>

        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
        </dependency>

        <dependency>
            <groupId>org.vaadin.tatu</groupId>
            <artifactId>twincolselect</artifactId>
            <version>1.7.0</version>
        </dependency>

        <dependency>
            <groupId>com.flowingcode.vaadin.addons</groupId>
            <artifactId>twincolgrid</artifactId>
            <version>2.1.0</version>
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>2.6.6</version>
        </dependency>

        <dependency>
            <groupId>org.vaadin.addon</groupId>
            <artifactId>v-leaflet</artifactId>
            <version>3.0.2</version>
        </dependency>
        

        <dependency>
            <groupId>com.vaadin</groupId>
            
            <artifactId>vaadin</artifactId>
            <exclusions>
                
                <exclusion>
                    <groupId>com.vaadin.webjar</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.insites</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.polymer</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.polymerelements</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.vaadin</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.webcomponents</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-spring-boot-starter</artifactId>
            <exclusions>
                
                <exclusion>
                    <groupId>com.vaadin</groupId>
                    <artifactId>vaadin-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        
        

               <dependency>
                   <groupId>org.springframework.boot</groupId>
                   <artifactId>spring-boot-devtools</artifactId>
                   <optional>true</optional>
               </dependency>

        
               
        
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>


    </dependencies>



    <build>
        <defaultGoal>spring-boot:run</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                

            <dependencies>
                <dependency>
                    <groupId>org.springframework.boot.experimental</groupId>
                    <artifactId>spring-boot-thin-layout</artifactId>
                    <version>1.0.28.RELEASE</version>
                </dependency>
            </dependencies>


            <configuration>
                <wait>500</wait>
                <maxAttempts>240</maxAttempts>
            </configuration>
        </plugin>

        
            <plugin>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-maven-plugin</artifactId>
                <version>${vaadin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-frontend</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <trimStackTrace>false</trimStackTrace>
                    <enableAssertions>true</enableAssertions>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            
            <id>production</id>
            <properties>
                <vaadin.productionMode>true</vaadin.productionMode>
            </properties>

            <build>
                <plugins>
                    <plugin>
                        <groupId>com.vaadin</groupId>
                        <artifactId>vaadin-maven-plugin</artifactId>
                        <version>${vaadin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>build-frontend</goal>
                                </goals>
                                <phase>compile</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <productionMode>true</productionMode>
                            <pnpmEnable>false</pnpmEnable>
                        </configuration>
                    </plugin>
                </plugins>
            </build>

            <dependencies>
                <dependency>
                    <groupId>com.vaadin</groupId>
                    <artifactId>vaadin</artifactId>
                    <exclusions>
                        <exclusion>
                            <groupId>com.vaadin</groupId>
                            <artifactId>vaadin-dev-server</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>it</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>start-spring-boot</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>start</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>stop-spring-boot</id>
                                <phase>post-integration-test</phase>
                                <goals>
                                    <goal>stop</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <trimStackTrace>false</trimStackTrace>
                            <enableAssertions>true</enableAssertions>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>
</project>`

**Comment by mcollovati** [comment]
Two additional requests: please attach the output of the following two commands

mvn --version

mvn help:effective-pom

**Comment by jonasrotilli** [comment]
> mvn --versão

mvn --version:

```
Apache Maven 3.2.2 (45f7c06d68e745d05611f7fd14efb6594181933e; 2014-06-17T09:51:42-04:00)
Maven home: /usr/local/apache-maven/apache-maven-3.2.2
Java version: 11.0.14.1, vendor: Amazon.com Inc.
Java home: /Users/jonasrotilli/Library/Java/JavaVirtualMachines/corretto-11.0.14.1/Contents/Home
Default locale: pt_BR, platform encoding: UTF-8
OS name: "mac os x", version: "11.6.5", arch: "x86_64", family: "mac"
```

mvn help:effective-pom:

```
[INFO] Scanning for projects...
Downloading: http://repo.maven.apache.org/maven2/com/vaadin/vaadin-spring-bom/23.1.0.alpha1/vaadin-spring-bom-23.1.0.alpha1.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.vaadin.tutorial.crm:vaadin-crm:1.0-SNAPSHOT (/Users/jonasrotilli/Documents/upCampo_vaadin22/pom.xml) has 3 errors
[ERROR]     Non-resolvable import POM: Could not transfer artifact com.vaadin:vaadin-spring-bom:pom:23.1.0.alpha1 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/com/vaadin/vaadin-spring-bom/23.1.0.alpha1/vaadin-spring-bom-23.1.0.alpha1.pom. Return code is: 501, ReasonPhrase: HTTPS Required. @ com.vaadin:vaadin-bom:23.1.0.alpha1, /Users/jonasrotilli/.m2/repository/com/vaadin/vaadin-bom/23.1.0.alpha1/vaadin-bom-23.1.0.alpha1.pom, line 35, column 19 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for com.vaadin:vaadin:jar is missing. @ line 124, column 21
[ERROR]     'dependencies.dependency.version' for com.vaadin:vaadin-spring-boot-starter:jar is missing. @ line 156, column 21
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

```

**Comment by mcollovati** [comment]
3.2.2 is quite an old version. Try upgrade Maven to the latest version

**Comment by jonasrotilli** [comment]
It worked out! That's right, the version.
I updated to the latest, 3.8.5.
Thank you very much! that's why we love vaadin so much, there's always support!
