### ISSUE TITLE
Provide Element::addCallback() method

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#1366]
The method should be:
`void addCallback(String name, Consumer<JsonArray> argConsumer, String... argumentExpressions)`

Where the `name` is the callback name (a function that should be added to the Element instance).
The `argConsumer` is a user-defined callback which accepts arguments that are created by evaluating each `argumentExpressions`.

The `argConsumer` will be called on the server side once function `name` is called on the client side for the element.

This functionality is basically the same as we already have via `@EventHandler`. It should use the same code.
As a part of the task : `@EventHandler` functionality should be reimplemented on top of the `addCallback` (may be ignore Angular case since it's obsolete).

**Comment by pleku** [comment]
This method never made it as part of the original design and hasn't been requested since, so closing this issue. If there are valid use cases where someone needs this, please open a new ticket and explain the why.
