### ISSUE TITLE
Vite: type checking errors in frontend/sw.ts

### ISSUE THREAD

**Issue by platosha** [vaadin/flow#13693]
### Description of the bug

After copying `target/sw.ts` to `frontend/sw.ts`, TypeScript starts to fail the build with errors in the `sw.ts` file:
<img width="889" alt="screen_shot_2022-05-04_at_18 03 09" src="https://user-images.githubusercontent.com/247998/167114002-900d3a6f-c048-4dcd-b832-6423474467a5.png">

### Expected behavior

The copied `sw.ts` should compile without errors.

### Minimal reproducible example

Steps:
1. `$ npx @vaadin/cli init my-app`
2. Enable Vite feature flag
3. Start the application
4. copy `target/sw.ts` to `frontend/sw.ts`

### Versions

- Vaadin / Flow version: 23.0
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by Artur-** [comment]
This is not related to Vite. The code is sw.ts is just incorrect but it has been fixed in 23.1.0.beta1

**Comment by Artur-** [comment]
Closing as this is fixed
