### ISSUE TITLE
Supplement Polymer properties based on the server-side model

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#1371]
Without registering the property, the default value and type will not be known. In some cases, this can be worked around by explicitly assigning a value to the property, but there is most likely also cases where this isn't enough (potentially attribute reflection?).

Make sure all properties defined in the model are registered in the same way as they would be through the `properties` property returned from `static get config()` (or `static get properties()` that was introduced in rc1).

Also ensure there are no conflicts if the custom element implementation has already defined some (but not necessarily all) properties defined on the client. If a property is defined both from the client and the server, then the client-side definition should be used and a warning logged in the client-side console.

**Comment by pleku** [comment]
#1385 was never merged and thus this has been left hanging.

Because there is no description of what would be the added value of this, nor have there been any requests for this, closing the issue. If someone would find this useful, please open a new issue and explain the why.
