### ISSUE TITLE
TerminalErrorHandler triggered when Upload is cancelled (Part II)

### ISSUE THREAD

**Issue by bertvermeiren** [vaadin/flow#13736]
### Description of the bug

See https://github.com/vaadin/flow/issues/10351 for context:

Trying to open up the discussion again after the fix, since it seems there is still an issue.

On the StreamReceiverHandler:

```
try (InputStream handledStream = inputStream) {
    // Store ui reference so we can do cleanup even if node is
    // detached in some event handler 
    Pair<Boolean, UploadStatus> result = streamToReceiver(session, handledStream, streamReceiver, filename, mimeType, contentLength); 
    if (result.getFirst()) { 
        cleanStreamVariable(session, streamReceiver); 
    } 
    return result.getSecond() == UploadStatus.OK; 
} catch (Exception e) { 
   session.lock(); 
   try { 
       session.getErrorHandler().error(new ErrorEvent(e)); 
    } finally { 
        session.unlock();
    } 
}
```

When an upload is interrupted (slow upload with for example 3G throttling in the browser), you get a Failed event with an EofException. That seems all working fine.
Either, in the above code you get up to the return statement but then you get in the Exception catch block again, probably due to the "try-with-resource statement" on the input stream trying to close the input stream. That will raise again an EofException and you get again an error on the error handler. There is no way to disable somehow this behaviour. No plugin, no tweak....

It seems the EofException in the failed event is another instance of the EofException catched in the above catch block.

Please advice.

Regards,

### Expected behavior

When canceling an upload, the errorHandler should not be called.

### Minimal reproducible example

See https://github.com/vaadin/flow/issues/10351 

Just, throttle in the browser your network with 3G and start uploading a big file and cancel the upload.

### Versions

- Vaadin / Flow version: 23.0.7
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mcollovati** [comment]
Thanks for reporting and investigation.
I can confirm your guess about the missing catch `try-with-resource`.
In addition, when canceling the upload, a similar exception can also occur in `handleMultipartFileUploadFromInputStream()`, when `FileItemIterator.hasNext()` is invoked.
