### ISSUE TITLE
Maven vaadin:dance fails most of the time

### ISSUE THREAD

**Issue by simasch** [vaadin/flow#13760]
### Description of the bug

After migrating to Vaadin 23 the dance fails 80% of the time and I have to delete the node_modules folder manually.

The error message is

[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:23.0.6:dance (dance) on project tosca-develop: Execution dance of goal com.vaadin:vaadin-maven-plugin:23.0.6:dance failed: java.nio.file.NoSuchFileException: C:\Users\simon\Workspace\Dynasoft\tosca-ui\tosca-develop\node_modules@vaadin\flow-frontend -> [Help 1]

### Expected behavior

Dance should delete the generated files.

### Minimal reproducible example

Create a project and run it on Windows.

### Versions

- Vaadin / Flow version: 23.x
- Java version: 17
- OS version: Windows (10 or 11)

**Comment by caalador** [comment]
Windows has issues with symbolic links. 
For instance folders are not recognized as symbolic links and deletion tries to remove the actual folder. 

This will generate this kind of exception always if you do `mvn clean vaadin:clean-frontend`, but will not happen if you do `mvn vaadin:clean-frontend clean` as then the target file is still available for the symlink.

**Comment by simasch** [comment]
@caalador I understand thanks!

So then I'll to do dance before clean for example 

```
<execution>
<id>dance</id>
  <phase>pre-clean</phase>
  <goals>
    <goal>dance</goal>
  </goals>
</execution>
```
