### ISSUE TITLE
[vite] Update the Vite ping route in `sw.ts` when upgrading to Vite 3.0

### ISSUE THREAD

**Issue by vursen** [vaadin/flow#13826]
The ping route has changed in Vite 3.0 (https://github.com/vitejs/vite/pull/6819), so we'll need to update it also in `sw.ts` once we get to upgrading. Otherwise, the URL can end up accidentally cached.

**Before:** `/VAADIN/__vite_ping`. **After:** `/VAADIN/`.

**Comment by Artur-** [comment]
Do you mean it now pings the base URL, i.e. `/VAADIN/` and we should. make sure that this very path is never cached?

**Comment by Artur-** [comment]
i.e. in sw.ts we have
```
  registerRoute(
    ({ url }) => url.pathname.startsWith(`${scopePath}VAADIN/__vite_ping`),
    networkOnly
  );

  registerRoute(
    ({ url }) => url.pathname.startsWith(`${scopePath}VAADIN/`),
    networkFirst
  );

```

So we should delete the first and make the second `networkOnly`?

**Comment by vursen** [comment]
> So we should delete the first and make the second networkOnly?

Not exactly. I guess we should add a new `networkOnly` route specifically for the base path and then we can remove the `__vite_ping` route.

**Comment by Artur-** [comment]
Ah, sorry the second one was `startsWith` so we should just change the first one to be an exact match
