### ISSUE TITLE
Unit test: Combo Box Calling sendKeys to filter and press Keys.ARROW_DOWN+  Keys.TAB to select do not works

### ISSUE THREAD

**Issue by melDavila** [vaadin/flow#13835]
### Description of the bug

I have a combo Box and I need to test the filter.
But do not works.
The second time I write in combo box with **sendKeys**  clean the field  (at the same time clean the filter)

### Expected behavior

It is necessary to be able to set the filter and then have the possibility to move in the combo box list to select one of the filter elements.

### Minimal reproducible example

Download the project:
https://github.com/vaadin/skeleton-starter-flow-spring/archive/v23.zip
Today has vaadin version 23.0.9

Add a combo box
I have use a  sample from vaadin page. The sample class is similar to:
https://vaadin.com/docs/latest/ds/components/combo-box/#custom-filtering
need only to modify the constructor for class **MainView** add this lines ant the end:

        final ComboBox<Country> comboBox = new ComboBox<>("Country");
        final ItemFilter<Country> filter = (country, filterString) -> country.getName().toLowerCase()
                .startsWith(filterString.toLowerCase());
        comboBox.setItems(filter, getCountries());
        comboBox.setItemLabelGenerator(Country::getName);
        comboBox.setId("COUNTRY");
        add(comboBox);

And add this test  methods to the **MainViewIT** test class to reproduce the problem.

    @Test
    public void setValue_With_WebElement_Combo() {
        final WebElement webField = getDriver().findElement(By.id("COUNTRY"));
        webField.sendKeys("au"); //-> Australia, Austria 
        webField.sendKeys(Keys.ARROW_DOWN, Keys.ARROW_DOWN, Keys.TAB); //-->select Austria
        final String value = webField.getAttribute("value"); 
        Assert.assertEquals("Austria", value);
    }

The expected value for the test is "Austria", but we have a "".

### Versions

- Vaadin / Flow version:  v23    23.0.9
- Java version:  v11
- OS version:  Windows 10

**Comment by TatuLund** [comment]
I tried this out in simplified case. It really does not matter how I populate the ComboBox, as from browser perspective behavior does not change.

```
@Route("combo-box-filtering")
public class ComboBoxFiltering extends Div {

  public ComboBoxFiltering() {
    ComboBox<String> comboBox = new ComboBox<>("Country");

    comboBox.setItems("Australia","Austria","Finland");
    comboBox.addValueChangeListener(event -> {
        Notification.show(comboBox.getValue());        
    });
    add(comboBox);
  }
}
```

And the actual test case. The difference to yours is that I am using TestBench's $ search for the item, so that I get TestBench given ComboBox API etc. into play instead of using bare selenium as would happen if I use search via web driver.

```
public class ComboBoxIT extends AbstractViewTest {

    public ComboBoxIT() {
        super("combo-box-filtering");
    }

    @Test
    public void componentWorksJava() {
        final ComboBoxElement webField = $(ComboBoxElement.class).first();
        webField.sendKeys("au"); //-> Australia, Austria 
        webField.sendKeys(Keys.ARROW_DOWN, Keys.ARROW_DOWN, Keys.TAB); //-->select Austria
        NotificationElement notification = $(NotificationElement.class).last();
        Assert.assertTrue(notification.getText().equals("Austria"));
    }
}
```

**Comment by melDavila** [comment]
This is good. 
But v23 it is not compatible with version v14 for testing.
So I need to rewrite and re-check the unit test.

**Comment by mcollovati** [comment]
Related to vaadin/testbench#1449. Closing
