### ISSUE TITLE
Enable Vite by default and move webpack behind a feature flag

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#13852]
### Describe your motivation

Vite is where we want to be in the future so we should set it to be used by default. By doing this early in the 23.2 development span we can catch potential problems before the 23.2 release. Currently there are no known issues in using Vite except for #13538 that needs to be fixed before this.

### Describe the solution you'd like

- Remove the Vite feature flag and use Vite by default
- Add a webpack feature flag that says you are using a deprecated feature instead of an experimental new feature and that it will be removed in the next major version. Link to suitable docs telling what is needed to upgrade from webpack to vite. Ask the user the report any issues blocking a move to vite so we can fix them.

**Comment by mshabarov** [comment]
> Currently there are no known issues in using Vite except for https://github.com/vaadin/flow/issues/13538 that needs to be fixed before this

And this one https://github.com/vaadin/flow/issues/13525.
