### ISSUE TITLE
Page title construction in RouterLayout issue

### ISSUE THREAD

**Issue by gigi** [vaadin/flow#13871]
### Description of the bug

After these changes in Vaadin Flow 

https://github.com/vaadin/flow/pull/13825/files#diff-32470b1fe06ff7a0966c7da3ded43f636d1a013b78ff34b06049c7915c4c359cR238 

It's not possible to construct custom page title outside of each view. Navigation lifecycle always rewrites title at the end, so it seems that there is no places left where we can call `Page.setTitle("custom title")`.

### Expected behavior

It's must be possible to set custom page title after navigation finished

### Minimal reproducible example

Minimal example from the real app: https://github.com/gigi/vaadin-23-pagetitle-issue

Main idea is to avoid service dependencies coupling and delegate control of common UI elements to layouts. 

So there is custom [PageChangedEvent](https://github.com/gigi/vaadin-23-pagetitle-issue/blob/main/src/main/java/com/example/demo/event/PageChangedEvent.java) event which can be used for updating layout menu, breadcrumbs construction, setting page title etc. This event is fired in [After Navigation](https://github.com/gigi/vaadin-23-pagetitle-issue/blob/main/src/main/java/com/example/demo/view/AbstractView.java#L19) stage.
Before [these changes](https://github.com/vaadin/flow/pull/13825/files#diff-32470b1fe06ff7a0966c7da3ded43f636d1a013b78ff34b06049c7915c4c359cR238 ) it was possible to construct page title and set it by hand: https://github.com/gigi/vaadin-23-pagetitle-issue/blob/main/src/main/java/com/example/demo/layout/BasicLayout.java#L50

Possible solutions:
- Add support of `HasDynamicTitle` in the RouterLayout that has higher priority than Router's `getPageTitle` or vice versa
- Concatenate page title somewhere in response listeners (I don't know where exactly and how to handle title template properly)
- Inject [necessary layout dependencies](https://github.com/gigi/vaadin-23-pagetitle-issue/blob/main/src/main/java/com/example/demo/layout/BasicLayout.java#L25) in each view and construct title in `getPageTitle` (quite annoying)

### Versions

- Vaadin: 23.1.0.rc1
- Flow: 23.1.0.rc2
- Java: BellSoft 17.0.3
- OS: x86_64 Mac OS X 12.3.1
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36

**Comment by willemv** [comment]
One possibility would be to leave the title unchanged if the route target doesn't implement `HasDynamicTitle`

I.e. the `AbstractNavigationStateRenderer#updatePageTitle` is now this:
```java
    private static void updatePageTitle(NavigationEvent navigationEvent,
            Component routeTarget) {
        String title;

        if (routeTarget instanceof HasDynamicTitle) {
            title = ((HasDynamicTitle) routeTarget).getPageTitle();
        } else {
            title = lookForTitleInTarget(routeTarget).map(PageTitle::value)
                    .orElse("");
        }
        navigationEvent.getUI().getPage().setTitle(title);
    }
```

If you change it to this, a lot less people would be affected I think:
```java
    private static void updatePageTitle(NavigationEvent navigationEvent, Component routeTarget) {
        if (routeTarget instanceof HasDynamicTitle) {
            String title = ((HasDynamicTitle) routeTarget).getPageTitle();
            navigationEvent.getUI().getPage().setTitle(title);
        }
    }

```

**Comment by gigi** [comment]
Dirty temporary hack to set desired title

```java
private void setPageTitleAsync(PageChangedEvent event) {
    String pageTitle = constructPageTitle(event.page());
    event
        .locationChangeEvent()
        .getUI()
        .getPage()
        .executeJs("setTimeout(() => document.title = $0, 0);", pageTitle);
 }
```

**Comment by MarcinVaadin** [comment]
For me it makes sense to use `HasDynamicTitle` from first available parent layout if it implements such. It is easily accessible from active router target chain.

As for overriding title which was set during `AfterNavigation` - we could introduce a flag that will be set after title has been already set and will prevent triggering default `AbstractNavigationStateRenderer.updatePageTitle`.

@mshabarov what do you think?

**Comment by MarcinVaadin** [comment]
One thing bothers me:
```
@Test
    public void page_title_not_set_from_annotation_in_parent()
            throws InvalidRouteConfigurationException {
        setNavigationTargets(ChildWithoutTitle.class);

        router.navigate(ui, new Location("parent-with-title/child"),
                NavigationTrigger.PROGRAMMATIC);

        Assert.assertEquals("", ui.getInternals().getTitle());
    }
```
It was added in https://github.com/vaadin/flow/pull/2590 , and there
> Title should only be taken from the activated navigation target and parents should not be taken into account.

But is it still the case?

@caalador @mshabarov - please have a look

**Comment by mshabarov** [comment]
The issue was assigned to a developer and is currently being investigated.

**Comment by mshabarov** [comment]
@gig The PR fixing the issue was merged and changes will be delivered in the following versions: 23.2.12, 23.3.0, 22.0.25, 14.9.3.
Since the Vaadin 23.1 series are end of life already, we don't have plans to release a new maintenance version for it.
Would it be fine for use to upgrade to Vaadin 23.2 or 23.3 ?
