### ISSUE TITLE
Support for the component-based security configuration

### ISSUE THREAD

**Issue by mygordienko** [vaadin/flow#13910]
As described [here](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter) _WebSecurityConfigurerAdapter_ is now depricated in favor of a new approach. Unfortunately, Vaadin still relies on _VaadinWebSecurityConfigurerAdapter_ and we are not allowed to use them both at the same time.

**Comment by DManstrator** [comment]
Currently I face the issue that I can't use Spring Boot 5.7.0+ with the latest VAADIN version (23.1.3). When using Spring Boot 5.7.0+, the page reloads automatically every now and then and I suspect that it has to do with that.

The problem I face is also occurring in two different projects. And in both projects updating Spring Boot to 5.7.0+ caused that problem to appear. Also in both Projects, we are using the `VaadinWebSecurityConfigurerAdapter` and the `WebSecurityConfigurerAdapter` from Spring. When using Spring Boot 2.6.8, the problem doesn't occurr.

**Comment by RainerGanss** [comment]
This is a problem for us since we get weird reloads if we use the newest vaadin with the newest spring boot version (2.7.1)

**Comment by MarcinVaadin** [comment]
> Currently I face the issue that I can't use Spring Boot 2.7.0+ with the latest VAADIN version (23.1.3). When using Spring Boot 2.7.0+, the page reloads automatically every now and then and I suspect that it has to do with that.
> 
> The problem I face is also occurring in two different projects. And in both projects updating Spring Boot to 2.7.0+ caused that problem to appear. Also in both Projects, we are using the `VaadinWebSecurityConfigurerAdapter` and the `WebSecurityConfigurerAdapter` from Spring. When using Spring Boot 2.6.8, the problem doesn't occurr.

I've just run bakery spring starter (https://github.com/vaadin/bakery-app-starter-flow-spring) with spring-boot 2.7.1 and Vaadin 23.1.4 without any issues. Why you assume it's caused by SecurityConfigurer? Did you perform any debugging?
