### ISSUE TITLE
Embedding is not CDI aware

### ISSUE THREAD

**Issue by fy-gualtiero-testa** [vaadin/flow#13927]
### Description of the bug

Context: a Vaadin CDI application embedded as web-component.

When the web-component is initialized, the main view is not instantiated via CDI so CDI features like dependency injection are not working.

Assuming to have the following view:

```
@Route("")
public class MainView extends VerticalLayout {

    @Inject
    private GreetService greetService;

    @PostConstruct
    public void init() {  }
}

```
Inject and PostConstruct annotations work properly when the app is not embedded but not when the app is embedded as web-component. Also Vaadin specific features like the TranslationProvider injection do not work.

To bypass the problem, I should rewrite the class as following:

```
public class MainView extends VerticalLayout {

    private GreetService greetService;

    @Override
    protected void onAttach(final AttachEvent pAttachEvent) {
               setProperty("vaadin.i18n.provider", TranslationProvider.class.getName());
              greetService = javax.enterprise.inject.spi.CDI.current().select(GreetService.class).get();
              ....

}
```

### Expected behavior

The web-component should be CDI aware.

### Minimal reproducible example

1. Take the Vaadin 14 CDI example from https://vaadin.com/hello-world-starters
2. Embedded the app as explained on https://vaadin.com/docs/v14/flow/integrations/embedding

### Versions

- Vaadin / Flow version: 14.8
- Java version: 8
- OS version: Linux
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mcollovati** [comment]
Works fine for me using `CdiVaadinServlet` to handle web component requests.

```
@WebServlet(urlPatterns = { "/vaadin/*" })
public class WebComponentVaadinServlet extends CdiVaadinServlet {
}
```

**Comment by fy-gualtiero-testa** [comment]
Thanks, @mcollovati . I was not aware of the CdiVaadinServlet class.
Now CDI works.

**Comment by mcollovati** [comment]
Great to hear. I close the ticket as the issue is resolved
