### ISSUE TITLE
Adding a WebComponent exporter breaks the main UI (V23) 

### ISSUE THREAD

**Issue by petrixh** [vaadin/flow#13944]
### Description of the bug

If a WebComponentExporter<> is added for a Vaadin component that is used in one of the views, the client-side starts throwing unhandled exceptions: 

emb-test.js?7b18:125 Uncaught TypeError: Cannot read properties of undefined (reading 'disconnected')
    at EmbTest.disconnectedCallback (emb-test.js?7b18:125:1)
    at Router.__addAppearingContent (vaadin-router.js?6718:2114:1)
    at eval (vaadin-router.js?6718:1797:1)

Simply having the exporter (not using it just adding it to the code) seems to trigger this. In the client-side logs it can be seen that a custom .js-bundle is being loaded for the exported web component though (emb-test.js). 

### Expected behavior

Just adding the exporter (for later use) should not make the client-side fail. If this is expected behaviour, we need to have a better way to inform the developer what is going on and how to "fix it". 

### Minimal reproducible example

see: https://github.com/petrixh/export-testing-23

The file to comment/uncomment: 
https://github.com/petrixh/export-testing-23/blob/master/src/main/java/org/vaadin/example/components/EmbeddedTestComponentExporter.java

### Versions

- Vaadin / Flow version: 23.1.0 (Using Webpack for client-side build, happens both with dev and prod builds)
- Java version: Java 11
- OS version: OS X 12.3
- Browser version (if applicable): Chrome Version 102.0.5005.61 (Official Build) (x86_64)
- Application Server (if applicable): Tomcat (Spring Boot) 
- IDE (if applicable): IntelliJ

**Comment by petrixh** [comment]
With Vaadin 23.0.10 the component is shown, however the errors are still present in the console.. 
V14.8.12 seems to behave as expected, i.e. no errors in the console and the app/route itself shows the component that also has an exporter defined...

**Comment by Artur-** [comment]
Is what you are saying that you cannot use the same component both in the app and as an exported wc?

**Comment by Artur-** [comment]
In the example app, you have duplicate the `emb-test` tag. You cannot both use it on the component and for exporting a component.

**Comment by petrixh** [comment]
Hmm, based on a quick test, this seems to be the case yes... Hmm, ok somehow it would be nice to use the same tag-name for the custom thing both in the Vaadin side and the exported side.. But ok, the error really doesn't indicate anything (to me at least) about duplicate web component registration with the same name...

**Comment by Artur-** [comment]
You cannot use the same tag name as the name of the custom element and as the content of the custom element. There is no duplicate registration going on here, just you adding `foo` inside `foo` which will then add `foo` inside `foo` and `foo` inside `foo`. Quite many times. As you have registered `foo` as a custom element, each of the `foo` instances will run the connected callback. Which probably won't work very well for the nested `foo` instances

**Comment by petrixh** [comment]
Yeah ok, so the key part I missed was that the component with it's @Tag-annotation is `<foo></foo>` while the exporter will try to wrap the exported component with the tag given, so presumably:
`<exporter-tag> 
      <component-tag></component-tag>
 </exporter-tag>`

Closing this one as it's more of a misunderstanding...
