### ISSUE TITLE
Improve navigation with query parameters

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#14013]
### Describe your motivation

Vaadin 14.8.11

Currently, if I want to navigate to a view by java class name and I want to add a query parameter, I need to write the following code:

```java
RouteConfiguration configuration = RouteConfiguration
        .forRegistry(UI.getCurrent().getInternals().getRouter().getRegistry());
String url = configuration.getUrl(BookingFreightView.class, HasUrlParameterFormat.getParameters(bookingReference));
Map<String, List<String>> queryParameters = Collections.singletonMap("prev_view", Collections.singletonList(prevView.name()));
UI.getCurrent().navigate(url, new QueryParameters(queryParameters));
```

### Describe the solution you'd like

Please provide an additional overload for navigation: `UI.navigate(Class, Object, QueryParameters)` and also a static factory `QueryParameters.of(String, String)` so that the code can read:

```java
UI.getCUrrent().navigate(BookingFreightView.class, bookingReference, QueryParameters.of("prev_view", prevView.name()));
```

Also provide `QueryParameters.toString()` and `equals()/hashCode()`, similar to `RouteParameters`.

### Alternatives considered

`QueryParameter.simple()` still needs a map even though it's a bit better; `QueryParameter.fromString()` could work but will suffer from escaping issues.

For the massive `UI.navigate() overload` - perhaps a builder pattern could help? Not sure though, they all require a trailing `go()` call, which, when omitted, will simply run no navigation - that will be a frequent source of bugs. Not recommended:

```java
UI.getCurrent().navigateTo(it -> it.view(Foo.class, param).queryParam("foo", "bar"))
```
or
```java
new Navigation().route(Foo.class, param).queryParam("foo", "bar").go();
```

**Comment by mstahv** [comment]
Let's consider 😎 I noticed in my previous patch that working with QueryParameter would indeed have some low hanging fruits for DX enhancements.

@mvysny What is the Object in `UI.navigate(Class, Object, QueryParameters)` that you are proposing?

**Comment by mstahv** [comment]
BTW. I'd guess the code examples by @mvysny might not be there if the latest patch was already in a release 🤓

**Comment by knoobie** [comment]
I partly agree :) With your addition really complex objects can be easily exchanged without leveraging the URLs - that's true! But there are still use-cases where a bookmark-able URLs with query parameter are desired, like for example online portals with deep linking, search or filtering forms.

**Comment by mstahv** [comment]
There sure is! And even if the "new approach was used" one might still want to update the deep linking URL and use QueryParameters with enhanced API.

**Comment by mstahv** [comment]
@mvysny Would this work 🤔 Didn't test yet or write any tests, just drafted the APIs and implementation.

**Comment by mstahv** [comment]
Added the missing navigate method.

Why do you need the equals/hashCode implementations? toString definitely would ease debugging.

**Comment by mstahv** [comment]
toString ✅

**Comment by mstahv** [comment]
Fair enough. Added simple solution delegating to the parameter maps.

**Comment by mstahv** [comment]
Added tests, PR ready. At the enhancement didn't come directly from needs, would appreciate if @mvysny & @knoobie can check the improvements are as expected!

**Comment by mvysny** [comment]
Looks perfect from my side, thanks a ton @mstahv
