### ISSUE TITLE
Deprecate and remove support for a custom push URL

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#14027]
### Describe your motivation

There is no use case for setting a custom push URL. It is similar to the URL used for UIDL requests.

If you run a normal setup, the default always works.

If you want to use an external push server or similar, it won't work by just changing the URL

### Describe the solution you'd like

There should be no setting for a custom push URL.

Before removing it it should show a message when used e.g.
```
You are defining a custom push URL. This is no longer supported as it is not needed for any use case and support will be removed in a future version.
```

**Comment by mshabarov** [comment]
This use case apparently needs a custom push URL https://github.com/vaadin/flow/issues/14602 API

**Comment by MarcinVaadin** [comment]
@Artur- as a solution for https://github.com/vaadin/flow/issues/14602 I propose bringing back mapping support but setting default value to `/*` and making it configurable (like other init parameters). It results the same as committed and allows Spring users to serve custom endpoint Web Sockets services.

I've run quick test of `VaadinServletConfiguration.VAADIN_SERVLET_MAPPING = "/*";` on 23.1 and it worked as expected.

**Comment by MarcinVaadin** [comment]
Can be closed as fix is available in https://github.com/vaadin/flow/pull/14638
