### ISSUE TITLE
DataCommunicator#flush can get in a stuck state when the @PreserveOnRefresh annotation is present

### ISSUE THREAD

**Issue by willemv** [vaadin/flow#14067]
### Description of the bug

In routes annotated with `@PreserveOnRefresh` , we sometimes see empty grids after a page reload, with the following obfuscated client-side stack trace popping up:

```
10:58:01.754 Exception is thrown during JavaScript execution. Stacktrace will be dumped separately. shares:6:224
10:58:01.754 The error has occurred in the JS code: '$0, $1, return $0.$connector.setSorterDirections($1)' shares:6:224
    error shares:6
    oC FlowClient.js:209
    lt FlowClient.js:997
    kt FlowClient.js:949
    it FlowClient.js:572
    Pq FlowClient.js:500
    mr FlowClient.js:1007
    VA FlowClient.js:919
    Rq FlowClient.js:1003
    gr FlowClient.js:1007
    lk FlowClient.js:415
    Jq FlowClient.js:1005
    Kq FlowClient.js:986
    $s FlowClient.js:1007
    zB FlowClient.js:1007
    onreadystatechange FlowClient.js:582
    tb FlowClient.js:434
    wb FlowClient.js:870
    vb FlowClient.js:620
10:58:02.536 Uncaught TypeError: $0.$connector is undefined
    anonymous vaadin-3-c3811f66fa2805358b94.cache.js line 11 > eval line 999 > Function:3
    lt FlowClient.js:997
    kt FlowClient.js:949
    it FlowClient.js:572
    Pq FlowClient.js:500
    mr FlowClient.js:1007
    VA FlowClient.js:919
    Rq FlowClient.js:1003
    gr FlowClient.js:1007
    lk FlowClient.js:415
    Jq FlowClient.js:1005
    Kq FlowClient.js:986
    $s FlowClient.js:1007
    zB FlowClient.js:1007
    onreadystatechange FlowClient.js:582
    tb FlowClient.js:434
    wb FlowClient.js:870
    vb FlowClient.js:620
vaadin-3-c3811f66fa2805358b94.cache.js line 11 > eval line 999 > Function:3:1
```

This indicates that the initialization of the client-side grid connector from `com.vaadin.flow.component.grid.Grid.GridArrayUpdaterImpl` has not run at the appropriate time.

Investigating this further, it looks like the root cause is an issue in `com.vaadin.flow.data.provider.DataCommunicator`
* in `requestFlush` a `flushRequest` callback is created
* the callback is scheduled on the `StateTree` beforeClientResponse task queue
* subsequent invocations of `requestFlush` will not schedule a new flush as long as the callback from the previous step is not cleared
* the callback itself is responsible for clearing out the `flushRequest` callback field. I.e. the pending flush is only cleared when the flush runs
* the `com.vaadin.flow.internal.StateTree#runExecutionsBeforeClientResponse`
  *  gathers all tasks from that beforeClientResponse task queue **and clears that queue** (see the `flushCallbacks` implementation)
  * executes those tasks, but **only those that `canExecute`**. The ones that cannot be executed are simply skipped, and never rescheduled

When there is a `@PreserveOnRefresh` annotation present (and with some unlucky timing on the page refresh), it is possible that the `canExecute` for the flush of the `DataCommunicator` returns `false`, because it was moved from one UI to another (i.e. from one `StateTree` to another)

As a result, the `flushRequest` callback in `DataCommunicator` does not run. That results in the `flushRequest` field never being cleared.

This means that there will never be another flush for that data communicator. The initialization of `com.vaadin.flow.component.grid.Grid.GridArrayUpdaterImpl` happens during these flushes, so that is why saw the client-side error mentioned in the beginning.

### Expected behavior

When refreshing, the grid should always properly execute its initialization logic and should not remain empty.

### Minimal reproducible example

I haven't taken the time to make an MRE yet, since it takes quite a few moving parts.

In our application, we have
* A main layout annotated with `@PreserveOnRefresh` meaning all routes are preserved
* A grid with an in-memory data provider
* An asynchronous operation that updates the items in that data provider when it completes (*with* the appropriate `VaadinSession#access` calls)

### Versions

- Vaadin / Flow version: 23.0.7
- Java version: 11
- OS version: Linux
- Browser version (if applicable): N/A
- Application Server (if applicable): N/A
- IDE (if applicable): N/A

**Comment by mcollovati** [comment]
Hi, thank for the detailed report.
I'm looking at this and at the related PR, but unfortunately at the moment I'm not able to replicate the problem.
Any chance that you can provide an example?

**Comment by willemv** [comment]
The problem is quite hard to replicate, even in our application.

I was hoping that we could discuss the changes by just looking at the code. During my analysis it seemed to me that the logical flaw in the code was apparent:
* the `DataCommunicator` does not execute new flush requests as long as the `flushRequest` field is not `null`
* The `DataCommunicator` only clears its `flushRequest` field when it is executed
* There is a codepath in `StateTree` that drops the queued request, causing the request to never execute

As a result, the `flushRequest` field is never cleared, meaning the `DataCommunicator` will never execute new flush requests.

I was actually hoping that with the detailed analysis someone from Vaadin would be able to construct an automated test case.

**Comment by mcollovati** [comment]
Hi @willemv thanks for your reply.
If you take a look at your PR you can find two tests for the issue and also some comment

**Comment by willemv** [comment]
Right, hadn't checked there yet. I'll review the testcases and add them to the PR.
