### ISSUE TITLE
Vaadin 14 npm mode pulls commercial products

### ISSUE THREAD

**Issue by haijian-ccc** [vaadin/flow#14092]
### Description of the bug

Probably the same problem as in https://github.com/vaadin/flow/issues/13749. In **Vaadin 14 with npm mode**, commercial projects like vaadin-grid-pro are added to the package.json and package-lock.json even though only vaadin-core is used as dependency. **pnpm** mode works fine.

### Expected behavior

No commercial products are added into the package.json or package-lock.json when **vaadin-core** is used.

### Minimal reproducible example

1. Download the Vaadin 14 starter app https://github.com/vaadin/skeleton-starter-flow/archive/v14.zip
2. Replace vaadin dependency with vaadin-core
3. Delete package.json & package-lock.json
4. mvn
5. See the newly created package.json containing commercial products

### Versions

- Vaadin / Flow version: 14.8.13
- Java version: 11

**Comment by taefi** [comment]
Thanks @haijian-ccc for reporting this, it will be fixed by the CP for #14014 into 2.7 soon.

**Comment by mcollovati** [comment]
Closing, as the fix has been released in [2.7.17](https://github.com/vaadin/flow/releases/tag/2.7.17)
