### ISSUE TITLE
PiT 23.2: compilation error in RouterLink constructor

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#14143]
### Description of the bug

Applications using `new RouterLink(null, viewClass)` fail when upgrading to `23.2` with a compilation error.
```
[ERROR] COMPILATION ERROR :
[ERROR] ... reference to RouterLink is ambiguous
  both constructor <T,C>RouterLink(java.lang.Class<? extends C>,T) in com.vaadin.flow.router.RouterLink and constructor RouterLink(com.vaadin.flow.router.Router,java.lang.Class<? extends com.vaadin.flow.component.Component>) in com.vaadin.flow.router.RouterLink match
```

### Expected behavior

Application should compile, or there is a migration guide from 23.1 to 23.2, or there is an breaking-change advise in release-notes

### Minimal reproducible example

```
git clone https://github.com/vaadin/bakery-app-starter-flow-spring.git 
cd bakery-app-starter-flow-spring
mvn versions:set-property -Dproperty=vaadin.version -DnewVersion=23.2.0.alpha1
mvn clean install
```

### Versions

- Vaadin / Flow version: 23.2.0.alpha1

**Comment by mshabarov** [comment]
CTOR `public RouterLink(Class<? extends Component> navigationTarget)` can be used instead. Documentation should be extended with `RouterLink` constructors explanations and reflect this case.

**Comment by MarcinVaadin** [comment]
Introduced in https://github.com/vaadin/flow/issues/4449

**Comment by MarcinVaadin** [comment]
Docs updated: https://github.com/vaadin/docs/pull/1588
Bakery app updated: https://github.com/vaadin/bakery-app-starter-flow-spring/pull/1184
Release notes for Flow 23.2.0.alpha1 updated: https://github.com/vaadin/flow/releases/tag/23.2.0.alpha1
