### ISSUE TITLE
[Grid] lazy loading refreshAll causing edited item in grid jump to unknown position

### ISSUE THREAD

**Issue by letrthang** [vaadin/flow#14171]
### Description of the bug

in grid using lazy data loading, try to edit an item in grid and then call method `GridLazyDataView.refreshAll()`. the edited item will jump to unknown position.
This only happens if lazy loading is from database. **But not happen** with lazy loading from memory.

Code example:
```
// grid creation. findAllCompanies is to query data from database.
dataLazyView = gridCompany.setItems(q -> {
            return companyService
                    .findAllCompanies(myMessageManager, PageRequest.of(q.getPage(), q.getPageSize()));
        });
```

```
// edit an item and then call refreshAll
dataLazyView.refreshAll();
```

### Expected behavior

edited item will not change its current position in the grid when calling `refreshAll`

### Minimal reproducible example

N/A

### Versions

- Vaadin / Flow version: 23
- Java version: 17
- OS version: N/A
- Browser version (if applicable):N/A
- Application Server (if applicable):N/A
- IDE (if applicable):N/A

**Comment by mcollovati** [comment]
My guess is that your query does not provide and `ORDER BY` clause.
Without `ORDER BY` the ordering of the return data may not be the always same, especially after write operations

**Comment by letrthang** [comment]
if i add `ORDER BY` in query, then sort bullet in browser **not** working:
```
public Stream<SamplePerson> listAll(Pageable pageable) {
        return repository.findAllByOrderByFirstNameAscLastNameAsc(pageable).stream();
    }
```


<img width="561" alt="image" src="https://user-images.githubusercontent.com/13396193/179338394-da839be6-df50-40e1-8b79-d20e646c48d4.png">

If remove `ORDER BY` in query. the sort bullet will work fine.

**Comment by mcollovati** [comment]
Hi, the code in the issue description is not passing sorting information to the service, so when you refresh you will not have an `ORDER BY` based on the sorting selection on the user interface.

```java
// grid creation. findAllCompanies is to query data from database.
dataLazyView = gridCompany.setItems(q -> {
            return companyService
                    .findAllCompanies(myMessageManager, PageRequest.of(q.getPage(), q.getPageSize()));
        });
```

On the opposite, the code that I can now see on `MasterDetailDesingerView` is creating a `Pageable` object that carries paging and sorting information. If you turn on sql logging you will see that query has an `ORDER BY` clause for the columns you sorted on UI

```java
grid.setItems(query -> samplePersonService.listAll(
        PageRequest.of(query.getPage(), query.getPageSize(), VaadinSpringDataHelpers.toSpringDataSort(query)))
        );
```

With the last configuration, that is also the one provided by the application created on start.vaadin.com I can always see the added or edited item in a correct position with respect to the set sort order.

**Comment by mcollovati** [comment]
Forgot to mention that if you configure a column with `setSortProperty`, the property will be added to the sort order information of the Query object that is provided to `CallbackDataProvider.fetch`

**Comment by mcollovati** [comment]
Forgot to mention that if you configure a column with `setSortProperty`, the property will be added to the sort order information of the Query object that is provided to `CallbackDataProvider.fetch`

**Comment by mcollovati** [comment]
Forgot to mention that if you configure a column with `setSortProperty`, the property will be added to the sort order information of the Query object that is provided to `CallbackDataProvider.fetch`

**Comment by letrthang** [comment]
Here is my code in View:

 ```
@Id("gridCompany")
    private Grid<CompanyDTO> gridCompany;

gridCompany.addColumn(CompanyDTO::getCompanyEmail).setHeader(myMessageManager.getMessageCustom("AdminCompanyManagementView.gird.Email")).setResizable(true).setAutoWidth(true).setSortProperty("companyEmail");
  
// more columns added here but removed for tidy code

// set data provider for grid
        dataLazyView = gridCompany.setItems(q -> {
            return companyDAO.findAllCompanyDTO(myMessageManager, PageRequest.of(q.getPage(), q.getPageSize(), VaadinSpringDataHelpers.toSpringDataSort(q)));
        });

        // Optional, you may give a rough estimate of the item count,
        // good compromise for db performance and UX
        dataLazyView.setItemCountEstimate(10000);
```

Below is repo service:

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/13396193/179343067-121b4b04-31b2-484f-aec7-87ef5e828e78.png">


 And we are using a dialog to edit item in grid:

```
public void saveCompanyEdit(CompanyDTO companyDTO, AbstractTwoColumnDialog.Operation operation) {
                 userDAO.saveAndUpdate(user); // save to DB
                GridLazyDataView.refreshAll(); // refresh grid after save to db
}
```

And item still jump to unknown position :))

**Comment by mcollovati** [comment]
So, If I understand correctly, you are fetching data from database with a fixed order (`registration date` and `company email`) plus sort order by Pageable object,
and then you transform and copy items to a new list that will be handled by the grid.

Could it be that the order that you see on the UI is correct if you also consider `registration date` and `company email`?

**Comment by letrthang** [comment]
oh, sorry we updated code to remove `order`. 
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/13396193/179344082-303199a6-0d95-4c31-9c3f-2f82a4b846d9.png">

And when sort bullet is **single** -> edited item not jump 

<img width="114" alt="image" src="https://user-images.githubusercontent.com/13396193/179344302-26d3ee9e-71f7-42aa-89ba-d8d44c7cb2ce.png">


But when sort bullet is **double** -> edited item will jump 
<img width="130" alt="image" src="https://user-images.githubusercontent.com/13396193/179344320-bd5dda48-b60a-415f-8e4a-595f4b224a07.png">

**Comment by mcollovati** [comment]
The double indicator means the column is not sorted, so no order by clause is appended and the order of the query results  depends on the database.
So, for me, this is the expected behavior.

I'll investigate why things are different on start.vaadin.com preview

**Comment by mcollovati** [comment]
A workaround could be setting a default order in `Pageable` if `Query.getSortOrders()` is empty

**Comment by letrthang** [comment]
> ngs are different on start.vaadin.com pr

Thanks for the input.

One different part on demo code that you will call `UI.getCurrent().navigate(MasterDetailDesignerView.class)` after you save/update item. our code doesn't navigate to the same page.

 ```
save.addClickListener(e -> {
            try {
                if (this.samplePerson == null) {
                    this.samplePerson = new SamplePerson();
                }
                binder.writeBean(this.samplePerson);

                samplePersonService.update(this.samplePerson);
                clearForm();
                refreshGrid();
                Notification.show("SamplePerson details stored.");
                UI.getCurrent().navigate(MasterDetailDesignerView.class);
            } catch (ValidationException validationException) {
                Notification.show("An exception happened while trying to store the samplePerson details.");
            }
```

**Comment by mcollovati** [comment]
> Maybe my DTO is quite complicated so VaadinSpringDataHelpers.toSpringDataSort(query) cannot sort

`VaadinSpringDataHelpers.toSpringDataSort(query)` does not perform any kind of sort. It is just adapting Vaadin Query object to Spring Data data structure.
Sorting is done by the database applying order by clause generated by Spring Data.

`Query.getSortOrders()` is expected to be empty If you do not click on any columns header on the UI or if the columns has the double indicators.

**Comment by mcollovati** [comment]
For the navigation problem, I cannot replicate it. Navigation happens correctly

**Comment by letrthang** [comment]
> > Maybe my DTO is quite complicated so VaadinSpringDataHelpers.toSpringDataSort(query) cannot sort
> 
> `VaadinSpringDataHelpers.toSpringDataSort(query)` does not perform any kind of sort. It is just adapting Vaadin Query object to Spring Data data structure. Sorting is done by the database applying order by clause generated by Spring Data.
> 
> `Query.getSortOrders()` is expected to be empty If you do not click on any columns header on the UI or if the columns has the double indicators.

yes, in my case if column with double indicators, when i edit an item and call RefreshAll(), the edited item will jump. But this doesn't happen on your demo project.

`VaadinSpringDataHelpers.toSpringDataSort(query)` will provide the default sort method for `Pageable`.

Your DTO has extends `AbstractEntity` but my DTO has not. This makes it different ?

```
@Entity
public class SamplePerson extends AbstractEntity
```

<img width="520" alt="image" src="https://user-images.githubusercontent.com/13396193/179480893-13a8baa5-dea3-47a5-bf17-aa72c7aa2c80.png">

**Comment by mcollovati** [comment]
I think it doesn't make sense setting such a low page size.
If the purpose of changing size is to improve scrolling behavior, you can take a look at the specific [documentation](https://vaadin.com/docs/latest/binding-data/data-provider/#improving-scrolling-behavior)

**Comment by letrthang** [comment]
> I think it doesn't make sense setting such a low page size.
> If the purpose of changing size is to improve scrolling behavior, you can take a look at the specific [documentation](https://vaadin.com/docs/latest/binding-data/data-provider/#improving-scrolling-behavior)

agree, just try to test stability of the lazy loading grid.
