### ISSUE TITLE
Vaadin 22 - VaadinWebSecurityConfigurerAdapter ignores urlMapping

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow#14178]
### Description of the bug

In Vaadin 22, `VaadinWebSecurityConfigurerAdapter` does not take `vaadin.urlMapping` into consideration.
Please backport https://github.com/vaadin/flow/pull/13143 (https://github.com/vaadin/spring/issues/989) to Vaadin 22.

### Expected behavior

http://localhost:8080/ui/ must redirect to http://localhost:8080/ui/login

### Minimal reproducible example

```
vaadin.urlMapping=/ui/*
```

How to reproduce:

- Go to start.vaadin.com, chose Flow
- Create an app with access controlled view
- Set vaadin version to 22.0.18
- Add the above configuration to your application.properties file
- Run the app and try accessing vaadin app from http://localhost:8080/ui/ -> software redirects to /login (which obviously don't work)

### Versions

- Vaadin version: 22.0.18

**Comment by MarcinVaadin** [comment]
Framework updated, Spring tests will be added in https://github.com/vaadin/spring/pull/1039
