### ISSUE TITLE
Page.open(absolute URL) is not opening URL at mobile browsers (Safari and Firefox)

### ISSUE THREAD

**Issue by kyberorg** [vaadin/flow#14179]
### Description of the bug

I created page with single Button, which should open https://google.com in new tab/window of my browser.
At desktop it works (as a pop-up). At mobile (iPhone7 with iOS 15) it works only in Chrome. 

### Expected behavior

By clicking button I expect that Google Page will be opened at new tab. 

### Minimal reproducible example

```
@Route(value = "debug", layout = MainView.class)
public class DebugPage extends VerticalLayout {

    public DebugPage() {
        Button theButton = new Button();
        theButton.setText("Open Google in new tab");
        theButton.addClickListener(event -> {
           if (getUI().isPresent()) {
               getUI().get().getPage().open("https://google.com");
           }
        });
        add(theButton);
    }
}
```

Example aka Proof of Bug: https://dev-example.kyberorg.io/debug

### Versions

- Vaadin / Flow version: 23.1.3
- Java version: 17
- OS version: iOS15 
- Browser version (if applicable): Firefox 101.1 (10346) and Safari (one that comes with system).
- Application Server (if applicable): Tomcat (Spring Boot)
- IDE (if applicable): N/A

**Comment by caalador** [comment]
iOS Safari for instance has a general setting `Block Pop-ups` that is automatically true. disabling that you will get the chance to accept opening a popup/newTab in the sample case.

This is an OS security feature so there is really nothing we can do about it.
