### ISSUE TITLE
npm WARN deprecated packages - Vaadin 23 (>=14?)

### ISSUE THREAD

**Issue by knoxyz** [vaadin/flow#14194]
### Description of the bug

Hello team vaadin,

while my vaadin 23.1.3 project starts up with tomcat 9, there are deprecated warning from the npm:
Juli 21, 2022 12:37:18 NACHM. org.apache.catalina.startup.Catalina start
INFORMATION: Server startup in [24011] milliseconds
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

### Expected behavior

Update the dependent versions (seems to be 2-8 years old) to avoid all of the deprecated warnings.

### Minimal reproducible example

Happens with each vaadin (>=14) project, also with your examples https://start.vaadin.com/?preset=latest

### Versions

- Vaadin / Flow version: 23
- Node version: 16 and 17
- Java version: 11
- OS version: Windows 10
- Browser version (if applicable): each browser and version
- Application Server (if applicable): tomcat 9
- IDE (if applicable): eclipse 2022-06

**Comment by caalador** [comment]
Looking through here the dependencies are coming as transitive dependencies of dependencies for `webpack` and `extract-loader` both which have the latest version.
Locally I guess these could be overridden in the new `  "overrides": {` section with npm, but as we are aiming to move to Vite from Webpack we will not make any specific overrides to transitive dependencies.

**Comment by caalador** [comment]
To fix most deprecation warnings add to the overrides object in package.json the following:
```
    "webpack": {
      "micromatch": "4.0.5"
    },
```
The deprecations of `querystring@0.2.0` and `core-js@2.6.12` do not have anything that can be done for them when using webpack 4.

Closing issue as no updates that would work exist and they are used by webpack only when handling the fronted bundle and not in the application.
