### ISSUE TITLE
Annoying Warnings - No lit template data found in.., Couldn't find the definition of the element.., Couldn't parse template for class.. 

### ISSUE THREAD

**Issue by JustinVoitel** [vaadin/flow#14247]
### Description of the bug

We have a Npm Package that is privately published on Github Packages Registry and is containing all our 50+ Lit Components (as .ts files) 
A example Lit Component:
```ts
// my-button.ts
import { css, html, LitElement } from 'lit'
import { customElement, property } from 'lit/decorators.js'

@customElement('my-button')
export class MyButton extends LitElement {
  static styles = css`
    :host {
      display: inline-flex;
    }
  `

  @property({ reflect: true, type: Boolean })
  disabled = false

  render() {
    return html`
      <label id="label"></label>
      <button ?disabled=${this.disabled}>
        <slot></slot>
      </button>
    `
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'my-button': MyButton
  }
}
```

And use them as Flow Components in a separate Maven Package that is also privately published on Github Packages Registry.
A example Flow Component:
```java
//MyButton.java
package de.company.components.ui;

import com.vaadin.flow.component.Tag;
import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.dependency.NpmPackage;
import com.vaadin.flow.component.littemplate.LitTemplate;
import com.vaadin.flow.component.template.Id;

@Tag("my-button")
@NpmPackage(value = "@company/components", version = "1.0.0")
@JsModule("@company/components/src/my-button.ts")
public class DiButton extends LitTemplate {
        @Id
        private Label label

	public void setText(String text) {
		this.getElement().setText(text);
	}
}

```

Now when we use the mvn package in one of our projects I get the following Warnings for every imported Flow Component:
`BundleLitParser  WARN  – No lit template data found in @company/package/src/my-button.ts sources.`

`LitTemplateParserImpl  INFO  – Couldn't find the definition of the element with tag 'my-button' in any lit template file declared using '@JsModule' annotations. In a Spring Boot project, please ensure that the template's groupId is added to the vaadin.whitelisted-packages property. Otherwise, please Check the availability of the template files in your WAR file or provide alternative implementation of the method LitTemplateParser.getTemplateContent() which should return an element representing the content of the template file`

`LitTemplateParserImpl  INFO  – Couldn't parse template for class de.company.components.ui.MyButton class. Only specific Lit template format is supported. Please check that your template definition directly contains 'render' method which returns html_templatecontent.`

I added the package groupId to the projects application.yaml vaadin.whitelisted-packages

The component is rendered correctly but the repeating Warning in our logs are really annoying. 
Is there any way to prevent them ? 

### Expected behavior

The Warning to not be logged since it is working.

### Minimal reproducible example

1. Publish a .ts Lit Component as described above to Github Packages
2. Publish a Flow Lit Template using the Package Sources from 1 to Github Packages.
3. Create a simple vaadin project from start.vaadin.com and use the package from 2. in your pom dependencies
4. Use the Component in a Route Component
5. Visit the Route from 4.

### Versions

- Vaadin / Flow version: 23.2.0-alpha3
- Java version: 17.0.1
- OS version: MacOS 13.0 Beta
- Browser version (if applicable): Brave 1.41.100 Chromium: 103.0.5060.134
- Application Server (if applicable): Tomcat
- IDE (if applicable): VSCode

**Comment by caalador** [comment]
Instead of having the Java component as `public class DiButton extends LitTemplate {` try using it as `public class DiButton extends Component {` 
Using LitTemplate makes only sense if you use `@Id` to automatically bind to the template and then the TS file needs to be readable by the application. Also having it as a Component will make the server do less work for the component under the hood.

**Comment by JustinVoitel** [comment]
@caalador I forgot to mention, the  package has 50+ components and like 90% are using @Id

**Comment by caalador** [comment]
I guess this has something to do with #12204
Do the ts files get copied to `target/classes/META-INF/VAADIN/config/templates` for a production build?

**Comment by JustinVoitel** [comment]
@caalador The directory is almost empty.. 
Iam also not using vite at the moment!

![Screenshot 2022-08-02 at 14 52 29](https://user-images.githubusercontent.com/30449535/182379238-7d003229-e8ba-4a8c-a3e6-88bcd81e52ae.png)

**Comment by JustinVoitel** [comment]
Ok now I get the VAADIN/config/templates folder containing the .ts files when building for production, but the warnings are still present when running the .war on my local tomcat server. 

Is it maybe because it is a private npm package published on the Github Packages Registry and vaadin cannot handle it ? 
I would really love to get this fixed since it pollutes our logs heavily.

**Comment by caalador** [comment]
The issue is probably that the templates (at least the example given) is missing `;`
The parsing of the html from the lit template is done with regex and that at the moment states
```
Lit template pattern matches the template getter
      render() {
        return html`
          <style>
            .response { margin-top: 10px`; }
          </style>
          <paper-checkbox checked="${liked}">I like web components.</paper-checkbox>
 
          <div id="test" ?hidden="${liked}" class="response">Web components like you, too.</div>
        `;
      }
  
render\(\)[\s]*\{ finds the template getter method
[\s]*return[\s]*html[\s]*(\`) finds the return statement

([\s\S]*) captures all text until we encounter the end character with \1;} e.g. ';}
```
The same ending expectation has been used for polymer templates also.

Could you test if adding the missing `;` to the render method
```
  render() {
    return html`
      <label id="label"></label>
      <button ?disabled=${this.disabled}>
        <slot></slot>
      </button>
    `;
  }
```
clears the issue?
If it does then we know that there is no other issue than the parsing which seems is not mentioned specifically in the docs, only that the samples have the correct ending.

**Comment by JustinVoitel** [comment]
Adding the semicolons fixed the issue for me, Thanks!

**Comment by caalador** [comment]
That's great. 
I'll create an update to the documentation to specifically mention the semicolon in the render method.
