### ISSUE TITLE
HTML element does not accept number

### ISSUE THREAD

**Issue by jonasrotilli** [vaadin/flow#14240]
### Description of the bug

HTML element does not accept number.
If I include an element in a view like this:
  `add(new Html("123"));`

It doesn't compile, I get the error:
Constructor threw exception; nested exception is java.lang.IllegalArgumentException: HTML must contain exactly one top level element (ignoring text nodes). Found 0

If I add along with a text, like this:
  `add(new Html("<b>test:</b> 123"));`

The numbers disappear, only the "test" appears.

### Expected behavior

I hope to be able to create an html with numbers.

### Minimal reproducible example

```
        add(new Html("<b>test:</b> 123"));
        add(new Html("123"));
```

### Versions

- Vaadin / Flow version: 23.2.0.alpha1

**Comment by knoobie** [comment]
Displaying a number as html doesn't make sense. You can use `new Text("123")` if you really have to add a number as component. 

Additionally the exception states that you need a top-level node. Fix: `new Html("<span><b>test:</b> 123</span>") `

**Comment by jonasrotilli** [comment]
> Exibir um número como html não faz sentido. Você pode usar `new Text("123")`se realmente precisar adicionar um número como componente.
> 
> Além disso, a exceção indica que você precisa de um nó de nível superior. Fixar:`new Html("<span><b>test:</b> 123</span>") `

How does it not make sense?
I have a string that can be anything, including just number.

Putting it inside a <span> worked, but that should already be the default and never throw exceptions or disappear with a part of the string.

At least explain this in the documentation, because there is nothing there, the developer will only see this when his string has only numbers and has an exception.

**Comment by mcollovati** [comment]
Javadocs on HTML constructor states that `The fragment must have exactly one root element.`

**Comment by mcollovati** [comment]
It is also mentioned on class level javadocs

`A component which encapsulates a given HTML fragment with a single root element.`

**Comment by jonasrotilli** [comment]
In Javadocs?
Wow, this information should be on the first page of the documentation, not hidden there in Javadocs.

More examples are missing from the vaadin documentation.

Anyway, it's my mistake so, I was ignorant of not reading the javadocs and didn't understand that a component that has the name Html is not exactly a place to put anything but a complete Html tag.

Okay then, bug closed.
