### ISSUE TITLE
Vite handles style for embedded components differently from Webpack

### ISSUE THREAD

**Issue by mcollovati** [vaadin/flow#14256]
### Description of the bug

When embedding web-components using Vite, handling of style seems to be different from how Webpack works.

With Webpack, styles are added to the exported web-component shadow DOM (1), but with Vite styles seems to be handled differently (2).

Apparently, all seems to work fine on the browser page, but it should be checked that is not a regression for the bug reported in #7005.
If the behavior is correct, just duplicate the test and adapt it for Vite 
 
1.
![image](https://user-images.githubusercontent.com/4648894/182566348-2c2ddb34-65f5-4955-a71d-a3a91b4e1850.png)

2.

![image](https://user-images.githubusercontent.com/4648894/182568518-4e199ff9-3615-49b9-b9a1-4dcb5fbacf02.png)

### Minimal reproducible example

Run `NpmOnlyIndexIT` test from `flow-tests/test-embedding/test-embedding-generic` module.
It will pass with Webpack but fail with Vite

### Expected behavior

Webpack and Vite handles styles for embedded components similarly.

### Actual behavior

Webpack puts all styles in the exported web-component shadow DOM; with Vite one style element is missing. 

### Versions:
    - Vaadin / Flow version: 23.2
    - Java version: 11
    - OS version: Linux
    - Development mode:
    - Test from Flow codebase

**Comment by taefi** [comment]
I can confirm that there are some missing styles when using Vite (as mentioned in the description as well) but it is limited to the styles for `.v-reconnect-dialog` and `.v-system-error`. For example, I added an HTML content `<b class='v-system-error'>This is a test<b/>` manually to the embedded web component, and with Vite, it is rendered without any styles:
<img width="379" alt="Screenshot 2022-08-09 at 12 42 59" src="https://user-images.githubusercontent.com/70698630/183617963-34e53c33-158e-4353-a57d-a1d5e68564ed.png">
But, with Webpack it is rendered as it's supposed to:
<img width="402" alt="Screenshot 2022-08-09 at 12 47 10" src="https://user-images.githubusercontent.com/70698630/183618825-4209c264-5972-455d-9c73-c5e994d9785a.png">
