### ISSUE TITLE
Run TaskGenerateHilla only in build-frontend phase after npm dependencies install

### ISSUE THREAD

**Issue by platosha** [vaadin/flow#14281]
### Description of the bug / feature

`TaskGenerateHilla` runs the multi-module parser / generator for Hilla, which depend on:
- Java compiled classes
- npm dependencies, namely `@hilla/generator-typescript-cli`

### Minimal reproducible example

- Create a project with 23.2-SNAPSHOT Hilla and Flow
- Include / enable the multi-module engine
- Start the application

### Expected behavior

The engine is run by the `build-frontend` goal or `DevModeInitializer`, after npm dependencies are installed.

### Actual behavior

The `prepare-frontend` goal attempts to run `TaskGenerateHilla`, which fails because of missing npm dependencies.

### Versions:
    - Vaadin / Flow version: 23.2-SNAPSHOT

**Comment by cromoteca** [comment]
The `build-frontend` task is not run in dev mode. Wouldn't it be easier to fix the [order of execution](https://github.com/vaadin/flow/blob/8858e439ad32ee0a88f86002f1a462b8f8c512b5/flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java#L688-L716) in `prepare-frontend`?
