### ISSUE TITLE
CDI - Inject custom component into a sub-template throws an Exception

### ISSUE THREAD

**Issue by ndedobbeleer** [vaadin/flow#14283]
### Description of the bug

If you inject a custom component into a template nested in another template, you got an IllegalArgumentException

```
java.lang.IllegalArgumentException: A component specified to use a injected-view element cannot use an element with tag name child-view
	at com.vaadin.flow.component.Component.mapToElement(Component.java:187)
	at com.vaadin.flow.component.Component.<init>(Component.java:118)
	at com.vaadin.flow.component.littemplate.LitTemplate.<init>(LitTemplate.java:93)
	at com.vaadin.flow.component.littemplate.LitTemplate.<init>(LitTemplate.java:81)
	at tech.stayinfo.InjectedView.<init>(InjectedView.java:18)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

### Expected behavior

The exception should not throw

### Minimal reproducible example

```
@Tag("parent-view")
@JsModule("./src/parent-view.ts")
@Route("parent")
public class ParentView extends LitTemplate {

    @Id("childView")
	private ChildView childView;

}
```

```
@Tag("child-view")
@JsModule("./src/child-view.ts")
@Dependent
public class ChildView extends LitTemplate {
	
    @Inject
    public ChildView(InjectedView injectedView) {
    }

}
```

```
@Tag("injected-view")
@JsModule("./src/injected-view.ts")
@Dependent
public class InjectedView extends LitTemplate {

}
```

Full example project on : [https://github.com/Stay-Info/Vaadin-Inject-Component](https://github.com/Stay-Info/Vaadin-Inject-Component) 

### Versions

- Vaadin / Flow version: 23.1.4
- Java version: 11
- OS version: Windows
- Application Server (if applicable): Payara 5.194

**Comment by knoobie** [comment]
It's not supported, see https://github.com/vaadin/flow/issues/1328

**Comment by ndedobbeleer** [comment]
Doesn't seem to be the same. Using a child template inside a parent template works well (with LitTemplate). 
Injecting a child template inside a parent template works well 
Injecting anything into a "child template" except another template works well

**Comment by caalador** [comment]
I need to try getting payara up  and running, but at least using wildfly it works fine as long as I changed the ChildView to:
```
public class ChildView extends LitTemplate {	

    @Inject
    InjectedView injectedView;

    public ChildView() {
    }

    @PostConstruct
    public void init() {
        getElement().appendChild(injectedView.getElement());
    }

}
```
As the instantiator didn't see InjectedView as a bean

**Comment by ndedobbeleer** [comment]
Thanks caalador. I confirm you that this code works on Payara too.

Another workaround is change the ParentView :

```
@Tag("parent-view")
@JsModule("./src/parent-view.ts")
@Route("parent")
@Dependent
public class ParentView extends LitTemplate {

    @Id("childLayout")
    private VerticalLayout childLayout;

    @Inject
    public ParentView(ChildView childView) {
    	childLayout.add(childView);
    }
}
```
It's not an annoying bug when you know what's causing it
