### ISSUE TITLE
When adding external javascript libraries to my application, I want to be able to control when they are loaded, so I can avoid racing conditions.

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#1436]
Currently when using the `@Javascript` annotation, the script is added with the `defer` attribute by default. The idea here is to allow the developer to control whether he wants to defer the loading of the javascript or not.

**Comment by pleku** [comment]
There is a way to control when the JS is loaded with the load mode https://vaadin.com/api/platform/14.0.9/com/vaadin/flow/shared/ui/LoadMode.html

Closing this issue. Please create a new one with exact use case and what would be desired.
