### ISSUE TITLE
Allow to set a feature flag using a system property

### ISSUE THREAD

**Issue by cromoteca** [vaadin/flow#14407]
### Describe your motivation

While searching of how to run some integration tests twice with different values for a feature flag, we thought that being able to override its value with a system property would be a good solution, usable from a GitHub action.

### Describe the solution you'd like

I'd like to provide a PR with the code needed to set a feature flag using a Java system property.

### Describe alternatives you've considered

I tried to load the flag value from the classpath, but I couldn't, since we're running some `ChromeBrowserTest`s and the feature flag loading is hardwired. I should rewrite the `properties` file in the sources, which is not easy when other flags are present.

**Comment by taefi** [comment]
As this issue and its linked PR do not have any specific relation to hilla, the hilla label is removed.

**Comment by cromoteca** [comment]
The reason for putting the Hilla label here is that it allows us to see it in our ZenHub, but I understand that it's misleading.
