### ISSUE TITLE
BootstrapHandler should be easier to extend to allow adding/removing polyfills.

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#1440]
Currently, if you want to remove or replace a imported script (such as a polyfill), you have to rewrite the entire BootstrapHandler class, because there is no easy access to the methods that inject those scripts in the page.

The framework should of course provide a default import for polyfills, but the developer should be able to add or remove the polyfills he wants.

**Comment by pleku** [comment]
Hopefully no more polyfills should be needed after some time, and also I don't understand what extra polyfills people would want to add this way instead of just using `JsModule` or `JavaScript`.

Closing this issue as it doesn't seem to make sense anymore and there hasn't been any demand for it.
