### ISSUE TITLE
Vite is throwing an error when webpack isn't

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow#14413]
When I use webpack, my project is working but when I'm switching to vite I have this error:

> [TypeScript] Could not find a declaration file for module 'supercluster'. '/Users/jean-christophe/Documents/vaadin-addon/vite-issue/node_modules/supercluster/dist/supercluster.js' implicitly has an 'any' type. Try `npm i --save-dev @types/supercluster` if it exists or add a new declaration (.d.ts) file containing `declare module 'supercluster';`
> /Users/jean-christophe/Documents/vaadin-addon/vite-issue/node_modules/@googlemaps/markerclusterer/dist/algorithms/supercluster.d.ts:18:46
>     16 | /// <reference types="google.maps" />
>     17 | import { AbstractAlgorithm, AlgorithmInput, AlgorithmOutput } from "./core";
>   > 18 | import SuperCluster, { ClusterFeature } from "supercluster";
>        |                                              ^^^^^^^^^^^^^^
>     19 | import { Cluster } from "../cluster";
>     20 | export declare type SuperClusterOptions = SuperCluster.Options<{
>     21 |     [name: string]: any;

My project is using the npm package Google Map.
When I'm trying to add the package as asked. I have this error:

> [TypeScript] Module '"/Users/jean-christophe/Documents/vaadin-addon/vite-issue/node_modules/@types/supercluster/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
> /Users/jean-christophe/Documents/vaadin-addon/vite-issue/node_modules/@googlemaps/markerclusterer/dist/algorithms/supercluster.d.ts:18:8
>     16 | /// <reference types="google.maps" />
>     17 | import { AbstractAlgorithm, AlgorithmInput, AlgorithmOutput } from "./core";
>   > 18 | import SuperCluster, { ClusterFeature } from "supercluster";
>        |        ^^^^^^^^^^^^
>     19 | import { Cluster } from "../cluster";
>     20 | export declare type SuperClusterOptions = SuperCluster.Options<{
>     21 |     [name: string]: any;

I tried in Vaadin 23.1.x with the feature flag and i can reproduce it in Vaadin 23.2.0.beta2.
Here is the project: https://github.com/jcgueriaud1/vite-issue

**Comment by jcgueriaud1** [comment]
If I update the tsconfig and add:
```
    "allowSyntheticDefaultImports": true,
```
then the application is working.

But I don't understand it's working with webpack but not vite.

**Comment by Artur-** [comment]
This is because with webpack we are using https://github.com/TypeStrong/fork-ts-checker-webpack-plugin to do TypeScript checking. That plugin overrides the project tsconfig.json and always sets `skipLibCheck: true` so it does not check library code in `node_modules` for typing errors. If you manually set `skipLibCheck: true` in your tsconfig.json, the project will likely also compile.

We should set it by default to match the old behavior
