### ISSUE TITLE
mobile not set when going back in business demo app

### ISSUE THREAD

**Issue by klaus7** [vaadin/flow#14429]
### Description of the bug

Mobile view not set when going back in business demo app. See https://labs.vaadin.com/business/

Here is a short screen cast:
[Screencast from 2022-08-26 10:08:31.webm](https://user-images.githubusercontent.com/5364438/186855213-e44c9fcc-f4d1-4c6e-b737-007bd484951c.webm)

### Expected behavior

When going back from detail view, mobile list view is shown again.

### Minimal reproducible example

https://labs.vaadin.com/business/
all on mobile:
- go to accounts
- choose an account
- go back

### Versions

- Vaadin / Flow version:
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by Artur-** [comment]
Works fine on an iPhone

**Comment by klaus7** [comment]
Working on Android as well. Ok, obviously this is only a problem when run on an actual mobile device. Sorry for the false alarm. I run it in the mobile mode of Firefox 104.0 on Ubuntu 22.04

**Comment by MarcinVaadin** [comment]
Tested also on Chrome in mobile view on different available resolutions / devices. Closing as not a defect.
