### ISSUE TITLE
DataCommunicator gets stuck after browser refresh, eventually causing OutOfMemoryError

### ISSUE THREAD

**Issue by p-engl** [vaadin/flow#14435]
### Description of the bug

After upgrading to Vaadin 23.1.6, we encountered situations where the DataCommunicator of a Grid gets stuck after a browser refresh. It seems that the DataCommunicator gets stuck in some kind of flush-loop, which ultimately leads to an OutOfMemoryError. I suppose the problem was introduced in flow-data 23.1.4, this change might be relevant: https://github.com/vaadin/flow/commit/c55bdcc6dd9dac75be42291b5752d1d86d5a9997
This bug does not appear after downgrading to Vaadin 23.1.4

Note: In our application, we often use views that have a Grid on the left side and a TabSheet on the right side which can show data about the object that is selected in the left Grid. Most of the time, the data on the right side will be shown with a Grid. This type of view is affected by the problem. In general, it seems that the problem can appear in case that a component is shown, which was already used and removed before the browser refresh.

I created this issue in the flow repository, since the problem is at its core caused by the DataCommunicator.

### Expected behavior

After a browser refresh, it should be possible to show a component that contains a Grid and was shown before the browser refresh  without causing this bevahiour (this was possible before 23.1.6). The DataCommunicator should not get stuck in an infinite loop. 

### Minimal reproducible example

Below is an example that can reproduce the bug.

Steps to reproduce the bug:
Go to /test
Select "1" in left table
Click "Show Table 1"
Click "Show Table 2"
Press F5
Click "Show Table 1"

```java
import java.util.ArrayList;
import java.util.Arrays;

import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.checkbox.Checkbox;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.router.AfterNavigationEvent;
import com.vaadin.flow.router.AfterNavigationObserver;
import com.vaadin.flow.router.PreserveOnRefresh;
import com.vaadin.flow.router.Route;

@PreserveOnRefresh
@Route("test")
public class TestView extends Div implements AfterNavigationObserver{

	private HorizontalLayout hLayout;
		
	private Div wrapperRight;
	
	private Grid<String> tableLeft;
	
	private Grid<String> tableRightOne;
	
	private Grid<String> tableRightTwo;
	
	private Button buttonShowTableOne;
	
	private Button buttonShowTableTwo;
	
	private Div buttonSlot;
	
	private Div tableSlot;
	
	public TestView() {
		setSizeFull();
		build();
	}
	
	private void build() {
		String value1 = "1";
		String value2 = "2";
		
		hLayout = new HorizontalLayout();
		hLayout.setSizeFull();
		
		Div wrapperLeft = new Div();
		wrapperLeft.setHeightFull();
		wrapperLeft.setWidth("50%");
		hLayout.add(wrapperLeft);
		
		tableLeft = new Grid<>();
		tableLeft.addColumn(e -> e).setFlexGrow(1);
		wrapperLeft.add(tableLeft);
		
		tableLeft.setItems(Arrays.asList(value1, value2));
		
		wrapperRight = new Div();
		wrapperRight.setHeightFull();
		wrapperRight.setWidth("50%");
		hLayout.add(wrapperRight);
		
		buttonSlot = new Div();
		buttonShowTableOne = new Button("Show Table 1");
		buttonSlot.add(buttonShowTableOne);
		buttonShowTableTwo = new Button("Show Table 2");
		buttonSlot.add(buttonShowTableTwo);
		wrapperRight.add(buttonSlot);
		
		buttonShowTableOne.addClickListener(e -> {
			tableSlot.removeAll();
			tableSlot.add(tableRightOne);
		});
		
		buttonShowTableTwo.addClickListener(e -> {
			tableSlot.removeAll();
			tableSlot.add(tableRightTwo);
		});
		
		tableSlot = new Div();
		wrapperRight.add(tableSlot);
				
		tableRightOne = new Grid<>();
		tableRightOne.addColumn( e -> e).setHeader("c1").setFlexGrow(1);
		tableRightOne.addColumn(e -> new Checkbox()).setHeader("c2").setFlexGrow(1);
		tableRightOne.addColumn( e -> e).setHeader("c3").setFlexGrow(1).setVisible(false);
		tableRightOne.setItems(new ArrayList<>(Arrays.asList("1", "2", "3")));
		
		tableRightTwo = new Grid<>();
		tableRightTwo.addColumn( e -> e).setHeader("c1").setFlexGrow(1);
		tableRightTwo.addColumn(e -> new Checkbox()).setHeader("c2").setFlexGrow(1);
		tableRightTwo.addColumn( e -> e).setHeader("c3").setFlexGrow(1).setVisible(false);
		tableRightTwo.setItems(new ArrayList<>(Arrays.asList("4", "5", "6")));
		
		tableLeft.addSelectionListener(e -> {
			refreshRightSide();
		});
	}
	
	private void refreshRightSide() {
		displayNothingSelected();
		if(tableLeft.getSelectedItems().isEmpty()) {
		} else {
			
			if("1".equals(tableLeft.getSelectedItems().iterator().next())) {
				tableRightOne.setItems(new ArrayList<>(Arrays.asList("1", "2", "3")));
			} else {
				tableRightTwo.setItems(new ArrayList<>(Arrays.asList("4", "5", "6")));
			}
		}
	}
	
	private void displayNothingSelected() {
		tableSlot.removeAll();
		tableSlot.add(new Div());
	}
	
	protected void wrapRightSide(Component component) {
		if (!component.isAttached()) {
			Div wrapper = new Div();
			wrapper.setSizeFull();
			wrapper.add(component);
			wrapperRight.removeAll();
			wrapperRight.add(wrapper);
		}
	}

	@Override
	public void afterNavigation(AfterNavigationEvent event) {
		removeAll();
		
		add(hLayout);
		
		refreshRightSide();
	}
	
}
```

### Versions

- Vaadin / Flow version: 23.1.6
- Java version: 17
- OS version: Windows

**Comment by mshabarov** [comment]
This issue reproduces constantly when:
1. Preserve on refresh is used
2. Component is detached/removed from the state tree
3. Page is refreshed
4. Component from 2. is attached to a state tree in a new UI.

From my observations, `!flushRequest.canExecute(stateNode)` turns to `true` after 4. (which is expected) and the `requestFlush` method registers the `flushRequest` infinitely again and again.

Honestly, I don't understand what is a difference from `requestFlush` functionality between cases:
1. Refresh page with a grid component, while preserve on refresh is used.
2. Detach grid -> refresh the page with preserve on refresh -> attach grid.

I.e. why it doesn't go to a loop in scenario 1. and does in scenario 2.

Probably we are missing either:
1. Making `flushRequest = null;` in the `handleDetach()` method.
2. Missing `stateNode.isAttached()` somewhere in the `requestFlush()`.

**Comment by mshabarov** [comment]
DataCommunicator registers two flush requests when the component is removed from state tree before refreshing the page:
1. First one is registered just after page refresh, but the action is not being added to a state tree pending executions because the component is not attached to the page yet (removed from state tree).
2. Second one is registered after clicking on "add" button, i.e. after adding the component to the page. The data communicator sees that the owners in `flushRequest` and in current `stateNode` are not the same, so it forces making a new `flushRequest`. The flush request registered in (1) is now adds a flush action to the state tree's queue (because the component is now attached).
3. So eventually the state tree has two flush executions in the queue and both are executed before response to client.
4. Apparently this leads to registering a new `requestFlush` and executing callback again and agains -> infinite loop.

**Comment by mshabarov** [comment]
The initiator for registering `flushRequest` in 1 (see above post), is `tableRightOne.setItems(...)` called in `afterNavigation`. The issue is not reproduced anymore if you make this hack: 

```java
            if("1".equals(tableLeft.getSelectedItems().iterator().next())) {
                if (tableRightOne.isAttached()) {
                    tableRightOne.setItems(new ArrayList<>(Arrays.asList("1", "2", "3")));
                }
            } else {
                if (tableRightTwo.isAttached()) {
                    tableRightTwo.setItems(new ArrayList<>(Arrays.asList("4", "5", "6")));
                }
            }
```

Generally speaking, re-setting items to the grid is not needed after navigation. Grid registers a new flush (for data update) automatically when it's attached (added) to the page. So I'm not sure if it's an issue in DataCommunicator per se, or in the example project.

@p-engl when you use `PreserveOnRefresh`, do you really want the grid's content to be updated on page refresh? If yes, then you probably should set items to grid only when it's attached.

**Comment by p-engl** [comment]
The example I provided was simply intended to reproduce the problem we encountered in 23.1.6 in several places.

A more realsitic scenario in our application looks like this:

We have a view with a grid on the left side and a tabsheet on the right side.
The grid on the left side contains objects of different types. The data/components which are shown in the tabs on the right side depend on the object that is selected in the left grid.
Example: 
When I select an object of type A in the left grid, I have to show grid X in the first tab of the tabsheet. Grid X contains data about the object that is selected in the left grid.
When I select an object of type B in the left grid, I have to show grid Y in the first tab of the tabsheet. Grid Y contains data about the object that is selected in the left grid.
This means that everytime I change the selection in the left grid I possibly have the switch the grid that is displayed in the first tab and also have to refresh its content.
In the second tab we use another grid to show different data about the object that is selected in the left grid. For the second tab however we can use the same grid regardless of the object type that is selected in the left grid.

This can lead to the same process that you described earlier:
Select object of type A in the left grid
->Show grid X in first tab of tabsheet
Select object of type B in the left grid
->Show grid Y in first tab of tabsheet (which requires to remove grid X)
Press F5
Select object of type A in the left grid
->Show grid X in first tab of tabsheet

Some additional notes:
This problem would also arise if we use the same grid in the first tab, because switching the selected tab in the tabsheet also requires removing/adding grids.
We reuse the grids for performance and simplicity reasons - we do not want to recreate grids whenever the selection in the left grid changes. 
We also want to refresh the data on the right side when the user hits F5. The user assumes that the grid in the tabsheet displays the current data after pressing F5.

In any case I'd argue that this is a problem of the DataCommunicator, regardless of whether the provided example makes sense or not.

**Comment by mshabarov** [comment]
> In any case I'd argue that this is a problem of the DataCommunicator, regardless of whether the provided example makes sense or not.

Yes, I agree, DataCommunicator should be stable with any inputs and shouldn't trigger a loop.
I made a patch, which cancels the postponed request if a new request forced.

**Comment by mvysny** [comment]
This bug might apply to all DataCommunicator-based components, for example `ComboBox`, `IronList`, `Select`, `ListBox`, `RadioButtonGroup`, `CheckboxGroup`, `VirtualList`.

**Comment by bwajtr** [comment]
Also adding this for discoverability purposes: This is how this bug caused OOM errors in the production environment of one of the customers. This is how the customer reproduced the issue (edited):

> So while @PreserveOnRefresh is on, any component that uses DataProvider/DataCommnicator - grids, combos, listbox etc. if shown in a dialog which can be closed/detached or in any state where they can be detached from the current view without page refresh (i.e. remove from ui) and they are detached like so and page is refreshed it would cause an OOM with 14.8.18 vaadin.
The following steps can be performed to reproduce the issue:
1. Have @PreserveOnRefresh on
2. Go into view where is a button, that opens a dialog, which has a ComboBox on it
3. Click on that button to open the dialog
4. Close the dialog 
5. Refresh the browser
6. Click on the button again
7. Get OOM error
