### ISSUE TITLE
Enter-key does not submit value

### ISSUE THREAD

**Issue by wfischlein** [vaadin/flow#14433]
### Description of the bug

When I have a TextField and a submit-button that is bound to the enter-key, the value of the TextField does not get submitted

### Expected behavior

No matter whether I click the submit button or hit the enter-key, the value should be in my TextField then

### Minimal reproducible example

```
		TextField tf = new TextField();
		Button button = new Button("Submit", event -> {
			Notification.show(tf.getValue());
		});
		button.addClickShortcut(Key.ENTER);

```
Put this into a layout of your choice, enter some text into the TextField, hit the enter key

### Versions

- Vaadin / Flow version: 22.0.2
- Java version: 11
- OS version: MaoOS Monterey 12.5
- Browser version (if applicable): Firefox 103.0.2 (64-bit)
- Application Server (if applicable): spring-boot
- IDE (if applicable): IntelliJ IDEA 2021.3.2 (Ultimate Edition)

**Comment by knoobie** [comment]
Probably related to https://github.com/vaadin/flow/issues/5959

**Comment by MarcinVaadin** [comment]
Tested on _master_ - works as expected. Could you retest on latest version?

In #5959 there are 2 cases - using Enter and Ctrl+Enter. For Enter itself everything works.

**Comment by mcollovati** [comment]
For Enter I cannot replicate the problem even for the latest 22.0 version.
I'm going to close the issue.
@wfischlein feel free to reopen it, if it is still not working for you with latest versions
