### ISSUE TITLE
Vite keeps pinging the server producing error logs in the browser console 

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#14451]
### Description of the bug
Vite keeps pinging the old port of the server, even after restart of the application, producing error messages in the logs, like follows:
```
The FetchEvent for "http://localhost:53620/VAADIN/" resulted in a network error response: the promise was rejected.
NetworkOnly.js:93 Uncaught (in promise) no-response: The strategy could not generate a response for 'http://localhost:53620/VAADIN/'. The underlying error is TypeError: Failed to fetch.
    at NetworkOnly._handle (http://localhost:8080/sw.js:3617:19)
    at async NetworkOnly._getResponse (http://localhost:8080/sw.js:1642:24)
```
These errors are present in the console even for a new tab after app restart.
The only way to get rid of them is to close all tabs and restart the server.

### Minimal reproducible example
1. Download starter project from start.vaadin.com for 23.2 prerelease.
2. Start the app
3. Stop the app
4. Notice the errors in the browser's console
5. Start app again, open the console of a new tab.
6. See the errors.

### Expected behavior
No errors in a new tabs after server restart.

### Actual behavior
Errors are present even after server restart.

### Versions:
    - Vaadin / Flow version: Vaadin 23.2.0.rc1
    - Java version: 17
    - OS version: Mac OS
    - Browser version (if applicable): Chrome
    - Application Server (if applicable): Spring Boot
    - IDE (if applicable): Intellij Idea
    - Development or production mode: dev mode only

**Comment by Artur-** [comment]
The typical cause for this is that you have one tab open with your app, then you restart your app and a new tab opens for the same app. What happens then is:
1. Say the old tab was running Vite on port 1111. When the server went down, it lost connection to the Vite server so it goes into "ping until it is available again" mode. It pings port 1111 repeatedly.
2. The pings go through the service worker and that logs about 6 error messages about that the ping failed
3. A new tab is opened and that server is using Vite on port 2222. The app works fine
4. HOWEVER, te service worker is shared between the two tabs and everything that is logged on tab 1 is ALSO LOGGED on tab 2. So each time tab 1 tries to ping Vite on port 1111 and fails, it logs the failure on BOTH tab 1 AND tab 2

I think the proper solution here would be to make sure that the service worker does not handle any requests to other ports than where the app is running
