### ISSUE TITLE
App never loads in Firefox Developer Edition if Vite experimental feature enabled. Pulsing blue progress bar never finishes.

### ISSUE THREAD

**Issue by Basil-Dot-Work** [vaadin/flow#14464]
### Description of the bug

With Vite enabled as an Experimental Feature, a client window  in Firefox Developer Edition  never resolves loading the app. A blue progress bar across the top of browser windows goes no further than about 90% across, pulsing endlessly. 

See screenshot on Imgur.com.

https://imgur.com/a/f5XVOZW

### Minimal reproducible example

1. Go to  https://vaadin.com/hello-world-starters
2. Click *Vaadin 23 - Gradle* to download a new project.
3. Open project in IntelliJ IDEA 2022.2.2 Preview (Ultimate Edition). 
4. In *Gradle* pane, double-click the gretty > appRun item.
5. In Firefox Developer Edition, go to localhost:8080. The app loads successfully. 
6. In the lower corner of the browser window, click the Vaadin logo widget.
7. On the Experimental Features pane of the newly-appeared windoid,  enable *Vite*.
8. Stop the app running in IntelliJ, as it endlessly prints "----------------- Frontend compiled successfully. -----------------" on the console.
9. Quit and restart IntelliJ, just because.
10. Run gretty > appRun again.
11. In Firefox Developer Edition, go to localhost:8080 again.
12. BAM -> The bug bites. Watch the blue bar load forever across the top of the browser button.

You can wait over five minutes, but the blue bar will still be there. The app never loads.

While watching the blue bar pulsing, switch to the Safari browser. Visiting localhost:8080 there loads the Vaadin app successfully. The bug never bites in Safari, only in Firefox. No bug appears in Google Chrome, Version 105.0.5195.102 (Official Build) (arm64). No bug appears in Brave browser, Version 1.43.89 Chromium: 105.0.5195.102 (Official Build) (arm64).

You can turn OFF the Vite experimental feature. Restart the server, and the app once again loads successfully in Firefox.

### Expected behavior

The Vaadin app should load successfully in Firefox whether Vite is enabled or not.

### Actual behavior

Pulsing blue progress bar appears across the top of the browser window. Never goes away.

### Versions:
    - Vaadin / Flow version: 23.1.7
    - Java version: Java 17.0.4 (Corretto)
    - OS version: macOS Monterey 12.5.1 on Apple Powerbook Pro 16" with M1 Pro ARM chip. (the latest version)
    - Browser version (if applicable): Firefox Developer Edition 105.0b6 (64-bit) (the latest version)
    - Application Server (if applicable): Jetty via Gretty, inside IntelliJ IDEA 2022.2.2 Preview.
    - IDE (if applicable): IntelliJ IDEA 2022.2.2 Preview
    - Development or production mode: Dev mode, the default for a newly downloaded project.
    - Project from start.vaadin.com or activated in application: Project downloaded from https://vaadin.com/hello-world-starters by clicking the "Vaadin 23 - Gradle" item.

Screenshot of blue bar pulsing endlessly:
![blue_bar](https://user-images.githubusercontent.com/105256796/188291302-2c99bded-970e-40b3-b9bb-019aaa5d2ec7.jpg)

**Comment by knoobie** [comment]
Updated my first app to 23.2 where I'm hitting the exact same problem, making development impossible.

**Comment by Artur-** [comment]
What does the browser console say?

Is this only in the Firefox 105 beta or also in 104?

**Comment by knoobie** [comment]
Browser console logs normal, tested with 105.0b3 (64-bit) on ubuntu

![image](https://user-images.githubusercontent.com/3968629/189313221-39ea38d3-0413-4a76-9fb3-fe3abe6104f0.png)

**Comment by knoobie** [comment]
Firefox 104 is also working - I would vote 4 ticket closing.

**Comment by Artur-** [comment]
🎉  The default project from start.vaadin.com works fine on 105.0b9 (64-bit) on Mac also. Presumable a Firefox bug that was fixed then
