### ISSUE TITLE
As a backend Java developer I would prefer not to think what to put inside of @EventData to get client side data

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#1450]
When I send some data in event from a client side, I don't know what to specify in @EventData, because it's a different context on a server side.

Items to consider:

* Standard event properties like `event.model.data`, `event.model.index` and others can be provided by default

* Every property is accessible via prefix `event.`, as a developer, it would be good to be able to omit it

* Ideally, a developer would get some object with lots of getters and other useful api to use to retrieve non-standard properties

**Comment by pleku** [comment]
Closing due to lack of demand and use cases.

If someone thinks this is still valuable, please create a new issue with more details on what do you need and why/when.
