### ISSUE TITLE
V14 - ExtendedClientDetails isIPad method does not work

### ISSUE THREAD

**Issue by paodb** [vaadin/flow#14517]
### Description of the bug

In Vaadin 14, trying to use ExtendedClientDetails#isIPad() to detect an Ipad device always returns false.

### Expected behavior

ExtendedClientDetails#isIPad() should return true if used device is Ipad.

### Minimal reproducible example

```
ui.getPage().retrieveExtendedClientDetails(details -> {
      boolean isIPadValue = details.isIPad();
      Notification.show(isIPadValue ? "ipad" : "not ipad");
});
```

### Versions

- Vaadin / Flow version: 14.8.15
- OS version: 9th generation iPad running iOS 15.4 & iPad Air 2 running iOS 15.5

**Comment by mcollovati** [comment]
Hi @paodb,
can you please post the client request related to the `retrieveExtendedClientDetails`?

It should be something like the following

![image](https://user-images.githubusercontent.com/4648894/190077845-3323483c-40b8-4c3e-876c-0dcbf5a469df.png)

`isIpad()` checks for `v-np` to start with `iPad`
If the value is null, it delegates the check to `VaadinSession.getCurrent().getBrowser()`, with the following condition
`browser.isIPad() || (browser.isMacOSX() && isTouchDevice())`

**Comment by mcollovati** [comment]
Tested with an IPad Air 2 (iOS 15.6.1) and can replicate the issue.
It seems like that `v-np` value is `MacIntel`

```json
{
   "v-sh":"1024",
   "v-sw":"768",
   "v-wh":"665",
   "v-ww":"1024",
   "v-bh":"729",
   "v-bw":"1024",
   "v-curdate":"1663160988202",
   "v-tzo":"-120",
   "v-dstd":"60",
   "v-rtzo":"-60",
   "v-dston":"true",
   "v-tzid":"Europe/Rome",
   "v-wn":"ROOT-2521314-0.9113661870159819",
   "v-td":"true",
   "v-pr":"2",
   "v-np":"MacIntel"
}
```

**Comment by johannest** [comment]
This js snippet seems to work for now, but no guarantee how long before Apple changes something
```
window.is_ipad = function() {
    return (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 0) || navigator.platform === 'iPad';
};
```

**Comment by mcollovati** [comment]
A solution can modify `ExtendedClientDetails.isIpad` be to always delegate to `WebBrowser` checks if `navigatorPlatform` does not start with `iPad` (that basically is the same as the proposed workaround, but done server side)

Original check

```java
   public boolean isIPad() {
        if (navigatorPlatform != null) {
            return navigatorPlatform.startsWith("iPad");
        }
        WebBrowser browser = VaadinSession.getCurrent().getBrowser();
        return browser.isIPad() || (browser.isMacOSX() && isTouchDevice());
    }
```

Potential change

```java
    public boolean isIPad() {
        if (navigatorPlatform != null && navigatorPlatform.startsWith("iPad")) {
            return true;
        }
        WebBrowser browser = VaadinSession.getCurrent().getBrowser();
        return browser.isIPad() || (browser.isMacOSX() && isTouchDevice());
    }
```

**Comment by mcollovati** [comment]
So, it seems that for iPad and iOS 15 all we can do is assume that if `navigatorPlatform` is `MacIntel` and it is a touch device, it is an iPad.
This should work for now, but may not be enough in the future.
Of course, we should also preserve the check for `startsWith(iPad)`

**Comment by mcollovati** [comment]
Related issue: #14133
