### ISSUE TITLE
Explore removal of Apache's httpclient dependency from flow-server

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#14538]
### Describe your motivation

Currently vaadin-flow (flow-server) has a dependency to the httpclient (4.5.13) from Apache. The only class that needs it in flow-server [DefaultFileDownloader](https://github.com/vaadin/flow/blob/bf2b84fed9071d399248b3fedfc0c8922c2282c3/flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloader.java) which is only used on build / development time.

### Describe the solution you'd like

Remove the dependency to Apache's httpclient by e.g. using Java 9's HttpClient or by moving of the whole class and its callers to the dedicated maven / gradle base plugin to reduce the dependency on runtime / production mode.

**Comment by mstahv** [comment]
@Artur-, @caalador check the PR I drafted as Friday fun. Not sure if all the hacks ("all bytes downloaded etc") are still needed with the newer JDK httpclient. Also I have no idea why there is this username/password thingie in this class. Obsolete legacy from the frontend-maven-plugin?
