### ISSUE TITLE
Allow passing config flags to the webcomponents polyfill

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#1458]
When using Flow I want to be able to pass config flags to the webcomponents polyfill to force enabling the Shady DOM polyfill even in the browsers that support Shadow DOM natively. Ideally that would be optional extra parameters in the `@WebComponents` annotation, like `@WebComponents(version=1, shadydom=true)`.

The Shady DOM polyfill is essential for transitioning from having all site styles in a global `styles.css` to the Polymer-based approach when each page is a custom element with its own local styles. With the CSS isolation of the actual Shadow DOM the global styles approach does not work at all.

To implement that, one either needs to set the `ShadyDOM = {force: true}` in a script prior to loading the polyfill (as documented [here](https://github.com/webcomponents/shadydom)), or add a `shadydom` attribute to the script tag that includes the webcomponents-lite.js polyfill (as you can see [here](https://github.com/webcomponents/webcomponentsjs/blob/master/src/pre-polyfill.js)). Since developers (user of Flow) have no way of executing any JS prior to the webcomponents polyfill is loaded by Flow, this is a feature request for you.

**Comment by pleku** [comment]
Passing flags to the polyfill is not probably that important anymore as the polyfill is not needed in evergreen browsers.

Closing the issue as _won't fix_ for now.
