### ISSUE TITLE
Dialog does not get autoclose if you add DialogCloseActionListener

### ISSUE THREAD

**Issue by arikanorh** [vaadin/flow#14587]
### Description of the bug

I'm experimenting with vaadin. I added a dialog to my view and it worked fine. It opened and closed when i click out of it.

But when i add a closeActionEventListener, the handler executed on backend but dialog stays open on frontend

### Expected behavior

Dialog should close on front end

### Minimal reproducible example

```
@PageTitle("Main")
@Route(value = "", layout = AppLayoutBasic.class)
public class MainView extends BaseView {
    private Button button = new Button("Cliik1");
    private Dialog dialog = new Dialog();

    public MainView( ) {
        dialog.setHeaderTitle("Dialog");
        add(button);
        button.addClickListener(e-> dialog.open());
        dialog.addDialogCloseActionListener((ComponentEventListener<Dialog.DialogCloseActionEvent>) dialogCloseActionEvent -> {
            System.out.println("Dialog closed");
        });

        add(dialog);
    }

}
```

`BaseView` is just extends  `Div`

### Versions

Vaadin: 23.2.1
Flow: 23.2.1
Java: Oracle Corporation 17.0.1
OS: amd64 Windows 10 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Live reload: Java active (Spring Boot Devtools): Front end active

**Comment by knoobie** [comment]
The behavior is explained in the JavaDoc of the method you have used: https://github.com/vaadin/flow-components/blob/0c98aa471b39bc16292d6d382bc1f1267e3c3595/vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L268
