### ISSUE TITLE
Endless loop on login page when setting login path for VaadinWebSecurity

### ISSUE THREAD

**Issue by mcollovati** [vaadin/flow#14582]
### Description of the bug

When configuring login view with path instead of java class in VaadinWebSecurity, the browser endlessly reloads the login page.

```java
setLoginView(http, "login", LOGOUT_URL);
```

Using view class works fine.

### Expected behavior

Login view is show correctly

### Minimal reproducible example

- Create an application with start.vaadin.com with a protected view
- Update `SecurityConfiguration` class to use path instead of class for `setLoginView` ( `setLoginView(http, "login", LOGOUT_URL)`)
- Start the server and navigate to the home page (http://localhost:8080)
- Click "Sign in" link on bottom-left corner
- See the browser reloading the page continuously (you will see "not found" page for a moment and then the reload)

### Versions

- Vaadin / Flow version: 23.2.1
- Java version: 17
- OS version: Ubuntu 22.04

**Comment by Artur-** [comment]
This is because the login view does not have `@AnonymousAllowed`. When you use `setLoginView(Class)` the ViewAccessChecker ensures that you can access the login view regardless of its annotations but when using a path, it does not.

**Comment by mcollovati** [comment]
I wonder if we can do some check also on `loginUrl` in `ViewAccessChecker`.
On the other hand, the `setLoginView` variant with path is meant to work with Hilla views, so this may not be considered an issue at all.

**Comment by Artur-** [comment]
Maybe we should add `@AnonymousAllowed` by default to the login view

**Comment by mcollovati** [comment]
Updated documentation to remind developers to add `@AnonymousAllowed` annotation to login view
