### ISSUE TITLE
Warning message "'import.meta' is not available" logged  at Vite startup

### ISSUE THREAD

**Issue by mcollovati** [vaadin/flow#14589]
On applications running with Flow 23.3 a warning message is logged at Vite startup (the application then starts and works correctly).

```
[vite] warning: "import.meta" is not available in the configured target environment ("es2019") and will be empty
1  |  // @ts-ignore
2  |  if (import.meta.hot) {
   |      ^
3  |    // @ts-ignore
4  |    const hot = import.meta.hot;

  Plugin: vite:esbuild
  File: /home/marco/tmp/buttami/flow-14570/frontend/generated/vite-devmode.ts
```

### Versions:
    - Vaadin / Flow version: 23.3
    - Java version: 11
    - OS version: Ubuntu 22.04

**Comment by Artur-** [comment]
Could we change to `es2020` and if needed, set it to `es2019` for webpack?

**Comment by OlliTietavainenVaadin** [comment]
For the record, also happens for me with `<vaadin.version>23.2.1</vaadin.version>`

**Comment by hannes-angst** [comment]
Totally crazy but Vaadin generates a `tsconfig.json` file that contains 
```
  "compilerOptions": {
    ...
    "target": "es2019",
    ...
}
```

By setting it to `es2020` the warning went away. 
Still needs to be fixed, though.
