### ISSUE TITLE
Deprecated V14 bootstrapping with Vite enabled fails silently

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow#14603]
### Description of the bug
If the deprecated V14 bootstrapping is enabled (`vaadin.useDeprecatedV14Bootstrapping=true`) and Vite is used for the build, the project fails to render anything and there's no error message 
### Minimal reproducible example
Set `vaadin.useDeprecatedV14Bootstrapping=true` in a default V23.2.1 project
### Expected behavior
There should be an error message about deprecated V14 not being supported, and the alternatives of switching back to Webpack or disabling the deprecated bootstrapping
### Actual behavior
No error is shown in the browser, console log or server log, but the app is also not rendering properly
### Versions:
    - Vaadin / Flow version:23.2.1
    - Java version:n/a
    - OS version:n/a
    - Browser version (if applicable):n/a
    - Application Server (if applicable):n/a
    - IDE (if applicable):n/a
    - Development or production mode:dev
    - Project from start.vaadin.com or activated in application:activated in application (version upgrade)

**Comment by mshabarov** [comment]
Release notes have been updated with this limitation https://github.com/vaadin/flow/releases/tag/23.2.0
