### ISSUE TITLE
Adapt to new auto configuration in spring boot. The spring.factories support for auto configuration was removed in spring boot 3.0.0-M5.

### ISSUE THREAD

**Issue by aspan** [vaadin/flow#14628]
### Description of the bug

Adapt to new auto configuration in spring boot. The spring.factories support for auto configuration was removed in spring boot 3.0.0-M5 https://github.com/spring-projects/spring-boot/issues/29699 and the current auto configuration has to be moved to a new location.

### Expected behavior

The application should auto configure spring beans.

### Minimal reproducible example

Create a new project from the starter. Change to user vaadin flow 24.0.0.alpha1 and upgrade spring boot to 3.0.0-M5.

### Versions

- Flow version: 24.0.0.alpha1
- Spring boot: 3.0.0-M5

**Comment by mcollovati** [comment]
Thanks for reporting.

Some link for additional info
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#changes-to-auto-configuration
