### ISSUE TITLE
System property for Feature Flag does not override value when loading features file with ResourceProvider

### ISSUE THREAD

**Issue by mcollovati** [vaadin/flow#14679]
In #14408 we introduced the possibility to override feature flags value by setting a system property.
This works fine unless a `ResourceProvider` is used to load the feature flags file; in this case the system property is ignored.

**Comment by mcollovati** [comment]
@cromoteca can you please confirm that the original idea was that a system property should always have precedence over the value stored in the feature flags file?

**Comment by cromoteca** [comment]
It was not our use case, I think that it's up to you to set the priorities. I'd give priority to the system property anyway.
