### ISSUE TITLE
Vaadin 23.1.2 - Error During Maven Build - TypeError: invalid options argument - opts-arg.js:13

### ISSUE THREAD

**Issue by bryan-schuknecht-noaa** [vaadin/flow#14680]
Hello.

My apologies if this is a repeat. I'm having trouble finding solutions for this issue.

We are unable to build Vaadin via Maven suddenly.

Vaadin version: 23.1.2
Maven version: 3.8.6
Java version: openjdk 11.0.16.1

Command: mvn clean install -DskipTests -Pproduction

Error: 
```
[INFO] --- vaadin-maven-plugin:23.1.2:build-frontend (default) @ ##### ---
[INFO] Reflections took 3787 ms to scan 267 urls, producing 16470 keys and 80472 values
[INFO] Scanning classes to find frontend configurations and dependencies...
[INFO] Visited 6353 classes. Took 10849 ms.
[INFO] Visited 263 classes. Took 147 ms.
[INFO] Unable to determine version information. No vaadin_versions.json found
[INFO] Skipping `npm install` because the frontend packages are already installed in the folder '##########################/node_modules' and the hash in the file '######################/node_modules/.vaadin/vaadin.json' is the same as in 'package.json'
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 266 resources. Took 352 ms.
[INFO] Copying project local frontend resources.
[INFO] Copying frontend directory completed.
[INFO] Reflections took 3472 ms to scan 267 urls, producing 16470 keys and 80472 values
[INFO] Running Webpack ...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ########################
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:50 min
[INFO] Finished at: 2022-09-28T18:25:31Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:23.1.2:build-frontend (default) on project #####: Execution default of goal com.vaadin:vaadin-maven-plugin:23.1.2:build-frontend failed: Webpack process exited with non-zero exit code.
[ERROR] Stderr: '#########################################/node_modules/.pnpm/mkdirp@1.0.4/node_modules/mkdirp/lib/opts-arg.js:13
[ERROR]     throw new TypeError('invalid options argument')
```
Any advice would be greatly appreciated.

Thank you for your time.

**Comment by Artur-** [comment]
The same thing can be seen in the Flow validation build, e.g. here https://github.com/vaadin/flow/actions/runs/3149162731/jobs/5121029735

Started yesterday

**Comment by Artur-** [comment]
Do you have a project to share where the problem can be reproduced? The Flow build problem does not reproduce well outside the automated build

**Comment by Artur-** [comment]
Also, is it related to using `pnpm` as you seem to be using?

**Comment by Artur-** [comment]
Possible related to https://github.com/pnpm/pnpm/issues/5412

**Comment by Artur-** [comment]
As https://github.com/vaadin/flow/pull/14686 fails, it seems not related to the pnpm version

**Comment by Artur-** [comment]
The problem in the Flow build has presumably been resolved by #14696 which caused the `target/frontend/version.json` file to contain both webpack and Vite dependencies. Not sure why you would see that in your project though but hopefully it will be resolved by the same fix

**Comment by mshabarov** [comment]
@bryan-schuknecht-noaa could you please test with 23.2.3 ?

**Comment by bryan-schuknecht-noaa** [comment]
Thanks for your patience. I asked the developers to upgrade their application to Vaadin 23.2.3, and it looks like that resolved this issue. We can build the applications with Maven again:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for X
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
Thanks again for your help!

**Comment by caalador** [comment]
As the issue seems to have passed with the newer version I'll close this ticket.
Please open a new issue with details if it happens again.
