### ISSUE TITLE
Vite does not observe live reload toggle with Jrebel

### ISSUE THREAD

**Issue by AdamBrowning** [vaadin/flow#14698]
### Description of the bug
Vaadin 23.2 with Vite enabled does not observe the live-reload settings being turned off for frontend changes. If you toggle it off in the browser and then save a front end file (JS/TS) the browser will still reload. This is with Jrebel.

### Minimal reproducible example
See attachment.

Load project in Eclipse or IntelliJ with Jrebel. Make any change to the single TS view file with live reload toggled off and the browser will reload.

### Expected behavior
Frontend changes should observe live reload being toggled off.

### Actual behavior
Frontend changes reload the browser regardless of the setting being toggled on/off.

### Versions:
    - Vaadin / Flow version: 23.2
    - Java version: 11
    - OS version: MacOs 12.5
    - Development or production mode: Development
[test-app.zip](https://github.com/vaadin/flow/files/9675551/test-app.zip)

**Comment by mshabarov** [comment]
@AdamBrowning have you tried changing CSS files, or is it an issue only with JS/TS files (I'm trying to understand is it a common issue with frontend resources or limited to JS/TS)? When I tested with SB dev tools, CSS files changes did not trigger live-reload when it was toggled off.

**Comment by AdamBrowning** [comment]
Looks like with Jrebel any changes under the frontend folder will do it. I saved a global-styles.css file and it did reload even with the toggle turned off.

**Comment by mshabarov** [comment]
Does the live-reload work still even after application restart after toggle off it?

**Comment by AdamBrowning** [comment]
Can no longer reproduce as of 23.2.3.
