### ISSUE TITLE
UI doesn't work because loading of JavaScript files is blocked due to disallowed MIME type

### ISSUE THREAD

**Issue by chkpnt** [vaadin/flow#14736]
### Description of the bug
Since I've updated from Vaadin 23.0 to 23.2 my Vaadin UI doesn't load anymore. In the JavaScript console (Firefox) I'm getting errors _"Loading module from ... was blocked because of a disallowed MIME type (“text/html”)"_. Safari is whining _"TypeError: 'text/html' is not a valid JavaScript MIME type."_.

I'm using a custom context path for the Vaadin servlet (`vaadin.urlMapping=/ui/*`), if this is relevant.

With the webpack-build enabled via the corresponding feature-flag (`com.vaadin.experimental.webpackForFrontendBuild=true`), the UI works again.

### Minimal reproducible example
Will provide an example later on.

### Expected behavior
Vaadin UI should load.

### Actual behavior
JavaScript isn't loaded by the browser.

### Versions:
    - Vaadin / Flow version: 23.2.3
    - Java version: 11
    - OS version: macOS 12.6
    - Browser version (if applicable):
    - Application Server (if applicable):
    - IDE (if applicable):
    - Development or production mode: dev-mode
    - Project from start.vaadin.com or activated in application:

**Comment by Artur-** [comment]
Sounds like you should see a javascript file being loaded in the browser but instead of the JS file, the index page is returned. Which file would that be?

**Comment by chkpnt** [comment]
This was a good hint. And indeed, it's `/ui/VAADIN/@vite/client`, `/ui/VAADIN/@vite-plugin-checker-runtime` and `/ui/VAADIN/generated/...`.

![grafik](https://user-images.githubusercontent.com/1956979/194062298-5ee4afea-7134-4530-8267-fd066c4b2571.png)

Before using Vite, I had `/VAADIN/static/**` and `/ui/VAADIN/build/**` in my ignoring ant-matchers for Spring Security.

```java
@Bean
    public WebSecurityCustomizer webSecurityCustomizer() {
        return web -> web.ignoring().antMatchers(
                // ...
                "/VAADIN/static/**",
                "/ui/VAADIN/build/**",
                // ...
                );
    }
```

After adding `/ui/VAADIN/@vite/client`, `/ui/VAADIN/@vite-plugin-checker-runtime` and `/ui/VAADIN/generated/**`, I've got many other files not being able to be loaded. So I've added `/ui/VAADIN/**`, which is working. But is this safe or too wide?

**Comment by mcollovati** [comment]
@chkpnt for Spring Security configuration, you can extend `VaadinWebSecurity` or inspect the class and apply same settings to your config (for example `VaadinWebSecurity.getDefaultWebSecurityIgnoreMatcher(urlMapping)`)

**Comment by chkpnt** [comment]
Thanks!
