### ISSUE TITLE
Flow 24.0.0.alpha1 no mappings found for endpoints

### ISSUE THREAD

**Issue by yarisvt** [vaadin/flow#14743]
### Description of the bug

When I start the [v24 prerelease my-app application](https://start.vaadin.com/dl?preset=default&preset=partial-v24prerelease) (from https://vaadin.com/blog/jakarta-ee-is-becoming-mainstream-get-ready-for-spring-boot-3-and-vaadin-24) and upgrade to spring boot 3.0.0-M5 and open http://localhost:8080 in my browser, I get:

![image](https://user-images.githubusercontent.com/58431019/194075230-36bf9775-a2a0-4eb0-b969-0b7f7bff1bef.png)

### Expected behavior

The application should show the UI as seen in https://start.vaadin.com/app

### Minimal reproducible example

See https://start.vaadin.com/dl?preset=default&preset=partial-v24prerelease in https://vaadin.com/blog/jakarta-ee-is-becoming-mainstream-get-ready-for-spring-boot-3-and-vaadin-24, upgrade to spring boot 3.0.0-M5

### Versions

- Vaadin / Flow version: vaadin: 23.2.3, flow: 24.0.0.alpha1
- Spring boot: 3.0.0-M5
- Java version: 17
- OS version: Ubuntu 22.04
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mcollovati** [comment]
Related to #14628
This has been fixed in #14629, but not yet released

**Comment by mcollovati** [comment]
Closing because issue is already resolved.
@yarisvt while waiting for the next release, you can give it a try using version `24.0-SNAPSHOT`
