### ISSUE TITLE
new RouterLink() should support views with multiple routes

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#1476]
When creating `RouterLink`s dynamically I want to be able to create links also to those views that have multiple routes. This is a regular practice to define several routes for some views and such view should be fully supported.

Example:
```java
public void configure(RouterConfiguration configuration) {
    configuration.setRoute("", HomeView.class);
    configuration.setRoute("home", HomeView.class);
    configuration.setRoute("about", AboutView.class);
}
```

With this routing configuration creating a `RouterLink` with `new RouterLink("Home", HomeView.class)` throws an exception: "IllegalArgumentException: Multiple routes are defined for the given view type HomeView".

Developers should be able to explicitly specify the URL they want to to use for such `RouterLink`s. And in any case this should not be a runtime error.

**Comment by mshabarov** [comment]
@vlukashov is this issue still relevant?
