### ISSUE TITLE
Commenting @import in styles.css gives net::ERR_ABORTED 404

### ISSUE THREAD

**Issue by sveine** [vaadin/flow#14770]
### Description of the bug

![image](https://user-images.githubusercontent.com/367125/194526091-e7a92de6-0a23-4b66-8a52-bbd258fcc570.png)

(File exists on disk)

![image](https://user-images.githubusercontent.com/367125/194526797-c56d3d3c-478d-4acd-b148-5448c974ead2.png)

### Expected behavior

Parser should ignore everything in comments

### Minimal reproducible example

`/*@import "my-style.css";*/`

### Versions

Hilla: 23.2.3
Flow: 23.2.3
Java: JetBrains s.r.o. 17.0.2
OS: amd64 Windows 10 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Live reload: Java active (HotswapAgent): Front end active

**Comment by Artur-** [comment]
This is a problem in https://github.com/vaadin/flow/blob/e4f7e1024b9828092408060d8b4e192a03d97d83/flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js#L37-L72 which does not at all consider that imports can be commented out
