### ISSUE TITLE
Migrate Multiplatform-Runtime to Jakarta EE 9 / Servlet 5.0

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#14783]
- [x] Migrate Vaadin 8 sources to Servlet 5.0:
Note: Vaadin `8.17.1` has been staged for testing, and Vaadin `8.17-SNAPSHOT` is available as well. So from `8.17.1` onwards Framework features "Jakarta-ization", which can be used by replacing the `vaadin-server` and `vaadin-compatibility-server` dependencies with `vaadin-server-mpr` and `vaadin-compatibility-server-mpr`, respectively.
To be tested further.
- [x] Migrate Vaadin 7 sources to Servlet 5.0
- [x] Make a CI for Jakarta version and build Jakarta-sed Vaadin 8 snapshot and pre-release
- [x] Transform MPR sources to Servlet 5.0 packages for Vaadin 8
- [x] Transform MPR sources to Servlet 5.0 packages for Vaadin 7
- [x] Make tests pass
- [x] Test with example project
- [x] Make CI for snapshot validation and release

**Comment by mshabarov** [comment]
MPR branch - https://github.com/vaadin/multiplatform-runtime-internal/tree/migrate-to-jakarta
Vaadin 24 + Spring Boot 3 + MPR 7 (V8) smoke testing project - https://github.com/mshabarov/spreadsheet-mpr/tree/V24

**Comment by mshabarov** [comment]
MPR 7.0 jakarta migration has been done in branch `convert-jakarta`, here is the pull request https://github.com/vaadin/multiplatform-runtime-internal/pull/645 , which is failing because:

- Vaadin 8.17 jakarta version hasn't yet the portlets exclusion (https://github.com/vaadin/framework-es/pull/71).
- `spreadsheet-v8` test module fails, most likely because spreadsheet needs a conversion as well.
- `ManualPushWithNoUiCallsIT` fails
- `AbstractPushTest::checkMessagesAppearing` fails

Vaadin 7 based tests are disabled until we get the jakarta version of Vaadin 7.

**Comment by knoobie** [comment]
> Note: Vaadin 8.17.1 has been staged for testing, and Vaadin 8.17-SNAPSHOT is available as well. So from 8.17.1 onwards Framework features "Jakarta-ization", which can be used by replacing the vaadin-server and vaadin-compatibility-server dependencies with vaadin-server-mpr and vaadin-compatibility-server-mpr, respectively.
To be tested further.

Is there a timeline for official Vaadin 8 Jakarta Support for extended Maintenance? @TatuLund  

Looking at the comment in 8.18.0's release notes, currently it looks kinda un-official by using MPR. 

>  This is only needed for MPR 24+, and is NOT guaranteed to work as generic Jakarta support (even though it does so at the moment) as we may add MPR specific functionality or even hard MPR dependencies in the future.

Source: https://github.com/vaadin/framework/blob/master/CHANGELOG-VAADIN8.md

**Comment by mshabarov** [comment]
MPR 7.0.0.alpha2 includes both V7 and V8 with Jakarta now. The issue is closed.
@knoobie good question! Could you please transfer it to the V7,8 framework GH repo issue tracker?
