### ISSUE TITLE
Opening a dynamically created PDF file into a new browser tab is not possible with an iPad

### ISSUE THREAD

**Issue by johannest** [vaadin/flow#14800]
### Description of the bug

A specific use-case: When clicking a button (dynamically) create a PDF file and open it into a new browser tab. This does not seem to work with iPad: when clicking the button nothing happens.

Note! Following use-cases still work:
- Using desktop browsers or Android Chrome
- Opening a **pre-created** PDF file to new browser tab with Anchor component
- Opening a dynamically created PDF to **same** browser tab with FileDownloadWrapper
- Opening a dynamically created PDF into new Vaadin Dialog

### Expected behavior

Also the specific use-case mentioned above should work.

### Minimal reproducible example

Note! This demo app uses iText for PDF creation

```xml
<dependency>
       <groupId>com.itextpdf</groupId>
       <artifactId>itextpdf</artifactId>
       <version>5.5.13</version>
</dependency>
```

```java
@Route("test")
public class UseCase extends Div {
    private int i = 0;

    public UseCase() {
        add(new Button("Open (dynamic) PDF into new browser tab", e -> {
            StreamResource streamResource = new StreamResource(getName(), () -> getByteArrayInputStream());
            final StreamRegistration registration = VaadinSession.getCurrent().getResourceRegistry().registerResource(streamResource);
            UI.getCurrent().getPage().executeJs("window.open($0, $1)", registration.getResourceUri().toString(), "_blank");
        }));
    }

    private String getName() {
        System.out.println("### getName() called");
        return "my" + (++i) + ".pdf";
    }

    private ByteArrayInputStream getByteArrayInputStream() {
        System.out.println("### getByteArrayInputStream() called");
        try {
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            writePdf(outputStream);
            return new ByteArrayInputStream(outputStream.toByteArray());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private void writePdf(OutputStream file) {
        System.out.println("### pdf() called");
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, file);
            document.open();
            document.add(new Paragraph("Hello World, Creating PDF document in Java is easy"));
            document.add(new Paragraph("You are customer # 2345433"));
            document.addCreationDate();
            document.addAuthor("Javarevisited");
            document.addTitle("How to create PDF document in Java");
            document.addCreator("Thanks to iText, writing into PDF is easy");
            document.close();
            System.out.println("Your PDF File is successfully created");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

### Versions

- Vaadin / Flow version: 14.8.15
- Java version: 1.8
- OS version: iOS 15.5

**Comment by caalador** [comment]
I expect this is probably related to security features in iOS / Safari that websites don't open pop-ups to annoy users.

iOS Safari for instance has a general setting Block Pop-ups that is automatically true. disabling that you will get the chance to accept opening a popup/newTab in the sample case.

As this is an OS security feature so there is really nothing we can do about it.

**Comment by johannest** [comment]
Good point, and yes, it seems to disabling the pop-up blocker for iPad Safari helps: After that it will ask user whether the PDF pop up should be shown or not

**Comment by gageller** [comment]
Changing to use an Anchor tag instead of a button works.
