### ISSUE TITLE
Detect ES6 support by using feature detection instead of user-agent parsing.

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#1481]
User-agent parsing can result in wrong results when an unknown or unexpected browser access the application. The proper way to detect ES6 is to run a Javascript test at the client side.

**Comment by Legioth** [comment]
With npm mode, the selection is no longer based on the user agent string. Instead, both alternatives are included in the host page and which one to use is based on how browsers process `<script type=module>` and `<script nomodule>` respectively.
