### ISSUE TITLE
Jenkins   "Failed to execute goal com.vaadin:vaadin-maven-plugin:23.2.3:prepare-frontend "

### ISSUE THREAD

**Issue by melDavila** [vaadin/flow#14811]
I have updated the project to 23.2.4 from  23.1.7 

13:56:49  [INFO] ------------------------------------------------------------------------
13:56:49  [ERROR] **Failed to execute goal com.vaadin:vaadin-maven-plugin:23.2.3:prepare-frontend (default) on project qzv: Could not execute prepare-frontend goal.: Error occured during goal execution: null**
13:56:49  [ERROR] 

I have tested with spring-boot-starter-parent    2.7.3   and 2.7.4

PS: Jenkins builds correctly with version vaadin 23.1.7

**Comment by caalador** [comment]
Could you run with the `-X` flag if it gave more info on what failed.
Also updating could warrant clearing the `node_modules` folder

**Comment by mshabarov** [comment]
Closed, because of no answer since Oct 14, please provide more information for us to reproduce and re-open the issue.
