### ISSUE TITLE
Vite fails with not exported node module

### ISSUE THREAD

**Issue by khauser** [vaadin/flow#14857]
### Actual behavior

gradlew clean build fails with:
```
> Task :vaadinBuildFrontend FAILED

 ***** All completed @ Sun Oct 16 13:23:54 CEST 2022  ***

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vaadinBuildFrontend'.
> Vite process exited with non-zero exit code.
  Stderr: 'vite v3.1.0 building for production...
  transforming...
  Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
  Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
  ? 876 modules transformed.
  'render' is not exported by node_modules/lit/index.js, imported by node_modules/@vaadin/flow-frontend/lit-renderer.ts
  file: D:/Hausi/lessoria-ui/node_modules/@vaadin/flow-frontend/lit-renderer.ts:1:9
  1: import { render, html } from 'lit';
              ^
  2:
  3: type RenderRoot = HTMLElement & { __litRenderer?: Renderer; _$litPart$?: any };
  error during build:
  Error: 'render' is not exported by node_modules/lit/index.js, imported by node_modules/@vaadin/flow-frontend/lit-renderer.ts
      at error (file:///D:/Hausi/lessoria-ui/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
      at Module.error (file:///D:/Hausi/lessoria-ui/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
      at Module.traceVariable (file:///D:/Hausi/lessoria-ui/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
      at ModuleScope.findVariable (file:///D:/Hausi/lessoria-ui/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
      at ReturnValueScope.findVariable (file:///D:/Hausi/lessoria-ui/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
      at ChildScope.findVariable (file:///D:/Hausi/lessoria-ui/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
      at Identifier.bind (file:///D:/Hausi/lessoria-ui/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
      at CallExpression.bind (file:///D:/Hausi/lessoria-ui/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
      at CallExpression.bind (file:///D:/Hausi/lessoria-ui/node_modules/rollup/dist/es/shared/rollup.js:8935:15)
      at VariableDeclarator.bind (file:///D:/Hausi/lessoria-ui/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
  '
```

### Versions:
    - Vaadin / Flow version: 23.2.4
    - Java version: OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)
    - OS version: Windows 11
    - Browser version (if applicable):
    - Application Server (if applicable): Spring
    - IDE (if applicable): gradlew clean build
    - Development or production mode: production mode
    - Project from start.vaadin.com or activated in application:

**Comment by Artur-** [comment]
Sounds like you for some reason have another Lit version that 2 in the project and it tries to import from there

**Comment by jmart1** [comment]
I'm having this problem too.  I am upgrading from 21.0.3 to 23.2.6.

- Vaadin / Flow version: 23.2.6
- Java version: Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
- OS version: Windows 10
- Browser version (if applicable):  n/a
- Application Server (if applicable): Spring
- IDE (if applicable):  mvn package 

                           <goal>prepare-frontend</goal>
                           <goal>build-frontend</goal>

- Development or production mode: development
- Project from start.vaadin.com or activated in application:

Not from start.vaadin.com.  Its an older application that I been upgrading over the past 2 years since v14.


Error:


> [ERROR] 'render' is not exported by node_modules/lit/index.js, imported by node_modules/@vaadin/flow-frontend/lit-renderer.ts
> [ERROR] file: C:/Users/jmart/git/ih_website/node_modules/@vaadin/flow-frontend/lit-renderer.ts:1:9
> [ERROR] 1: import { render, html } from 'lit';
> [ERROR]             ^
> [ERROR] 2: 
> [ERROR] 3: type RenderRoot = HTMLElement & { __litRenderer?: Renderer; _$litPart$?: any };
> [ERROR] error during build:
> [ERROR] Error: 'render' is not exported by node_modules/lit/index.js, imported by node_modules/@vaadin/flow-frontend/lit-renderer.ts
> [ERROR]     at error (file:///C:/Users/jmart/git/ih_website/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
> [ERROR]     at Module.error (file:///C:/Users/jmart/git/ih_website/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
> [ERROR]     at Module.traceVariable (file:///C:/Users/jmart/git/ih_website/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
> [ERROR]     at ModuleScope.findVariable (file:///C:/Users/jmart/git/ih_website/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
> [ERROR]     at ReturnValueScope.findVariable (file:///C:/Users/jmart/git/ih_website/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
> [ERROR]     at ChildScope.findVariable (file:///C:/Users/jmart/git/ih_website/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
> [ERROR]     at Identifier.bind (file:///C:/Users/jmart/git/ih_website/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
> [ERROR]     at CallExpression.bind (file:///C:/Users/jmart/git/ih_website/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
> [ERROR]     at CallExpression.bind (file:///C:/Users/jmart/git/ih_website/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:8935:15)
> [ERROR]     at VariableDeclarator.bind (file:///C:/Users/jmart/git/ih_website/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5269:23)

**Comment by khauser** [comment]
I have these dependencies in my project:

```
    vaadinMultiComboBoxVersion = '1.0.1'
    vaadinOlliVersion = '3.0.1'
    vaadinPaginatorVersion = '2.0.10'
...
    // Vaadin addons
    implementation group: 'org.vaadin.klaudeta', name: 'grid-pagination', version: "${vaadinPaginatorVersion}"
    implementation group: 'org.vaadin.gatanaso', name: 'multiselect-combo-box-flow', version: "${vaadinMultiComboBoxVersion}"
    implementation group: 'org.vaadin.olli', name: 'file-download-wrapper', version: "${vaadinOlliVersion}"

    // Other addons
    implementation group: "de.f0rce", name: "ace", version: "${aceVersion}"
```

Could it be that they come with another litversion?

**Comment by khauser** [comment]
https://github.com/Klaudeta/grid-pagination/blob/master/src/main/java/org/vaadin/klaudeta/LitPagination.java seems to be it

**Comment by mstahv** [comment]
My contribution to the grid-pagination addon is rather lame 😊 https://github.com/Klaudeta/grid-pagination/commit/5340cd528870b3ce36b9d14921d40ac4780a186c

Klaudeta moved to another company, getting the add-on updated might indeed be hard via her. @SebastianKuehnau has done some actual improvements for the project, would Sebastian you would be interested to take over this add-on? I guess it is fairly commonly used.

A quick fix might be to switch to [this paging grid](https://github.com/viritin/flow-viritin/blob/v23/src/main/java/org/vaadin/firitin/components/grid/PagingGrid.java) implementation in _in.virit:viritin_. That is built with server side composition instead of Lit, so it shouldn't be that fragile with the constantly changing front-end world.

**Comment by jmart1** [comment]
I'll try to remove the grid-pagination to see if that fixes it.  Will respond with the results.

**Comment by jmart1** [comment]
Ok that worked.  Now I gotta find a replacement for grid-pagination.  

@mstahv  Thank you!!!

**Comment by gl0b3** [comment]
Hi! I just made a pull request for the grid-pagination to be compatible with 23.2.4+. I hope it will be merged. [https://github.com/gl0b3/grid-pagination/tree/3.0.0](url)

**Comment by mstahv** [comment]
👍 If @Klaudeta don't respond (and cut on new release), let's cut a new version for your branch.

**Comment by Klaudeta** [comment]
Hi,
I only now got notification about the activity on the grid-pagination repository. I have not been using the Klaudeta Github account for a long time and same goes for the grid-pagination activity.
I can't actively maintain the add-on for the time being, sorry about this. Anyway I did merge the open PRs but I can't publish a new release of the add-on in the Vaadin directory. I do not have access anymore with the old credentials. 
Feel free to fork it and create a new Vaadin add-on in the directory.

**Comment by mstahv** [comment]
@gl0b3 Do you want to become the maintainer or shall we transfer the addon to "team parttio" for maintenance. That group of Vaadin users already maintain couple of add-ons that don't have active single person as a maintainer.

**Comment by gl0b3** [comment]
@mstahv Thank you for the question, but I think it will be in better hands in the team. I might contribute more in the future if possible.

**Comment by mstahv** [comment]
@Klaudeta , could you "Transfer ownership" of your repository to @parttio. That is in "Danger zone" if you go to the project settings in GitHub. A fork could be moved there as well, but it look the cleanest this way.

**Comment by Klaudeta** [comment]
I just tried to do so and I get `You don’t have the permission to create public repositories on parttio `

**Comment by mstahv** [comment]
Oh, thought there would have been an invite email to accept the transfer. I added an invitation for you to join Parttio as "owner". If you accept that, then you ought to be able to do the transfer.

**Comment by Klaudeta** [comment]
Yes, that worked. Transfer completed.

**Comment by mstahv** [comment]
I'd guess we only have an add-on issue here and no framework issue so this could be closed? 

I couldn't make the project build or to test it right away, but let's continue the discussion in: https://github.com/parttio/grid-pagination/issues/22

**Comment by khauser** [comment]
Great, thanks so far.

**Comment by jonmartinsolaas** [comment]
I also get this error, turned up after upgrading to 23.2.11

**Comment by jonmartinsolaas** [comment]
> @jonmartinsolaas: If you use grid-pagination ...

If grid-pagination is part of Klaudetas editor addon I used it. Removing the dependency didn't help, though. But after also removing .../frontend/generated folder everything started to work again. Will check later if reintroducing the dependency actually triggers the problem or if it was just my generated-folder that was messed up.
