### ISSUE TITLE
Scroll to the end of long grid, change contents shorter, items do not render correctly (empty view)

### ISSUE THREAD

**Issue by tommilukkarinen** [vaadin/flow#14859]
### Description of the bug

When 
1. I scroll to the end of grid that has several pages of content
2. Change grid contents so that there is less than one page
Result:
Contents are corrupted

Workaround before step 2:
			grid.scrollToIndex(0);
			grid.getDataProvider().refreshAll();

### Expected behavior

Contents would display correctly (as they do if I have not scrolled to the end of grid)

### Minimal reproducible example

// provider is list provider, and contents have been changed inbetween
// there's no problem, if I'm viewing top of the grid
// problem only occurs if there is several pages of content and I have scrolled to the end
		grid.setDataProvider(getProvider());
		grid.getDataProvider().refreshAll();
		grid.setSelectionMode(Grid.SelectionMode.SINGLE);

### Versions

- Vaadin / Flow version: 22.0.5
- Java version: 11
- OS version: Windows 11
- Browser version (if applicable): Chrome
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mshabarov** [comment]
Closed, because of no answer since Oct 19, please provide the project example to reproduce and re-open the ticket, if it is still an issue for you.
