### ISSUE TITLE
Page.open doesn't work on iOS

### ISSUE THREAD

**Issue by gpsfl** [vaadin/flow#14865]
### Description of the bug

Page.open dosen't work on iOS. This is probably due to Safari's restrictions on calling window.open from an asynchronous context:

See https://stackoverflow.com/questions/20696041/window-openurl-blank-not-working-on-imac-safari

A possible workaround for this is to wrap the `window.open(...)` call using `setTimeout(() => window.open(...));`. I can confirm this worked in our application.

### Expected behavior

A new window/tab should open

### Minimal reproducible example

```java
UI.getCurrent().getPage().open("https://google.com", "_blank");
```

### Versions

- Vaadin / Flow version: 23.2
- Java version: 11
- OS version: iOS 15.6.1
- Browser version (if applicable): Safari on iOS 15.6.1

**Comment by caalador** [comment]
As the feature is in iOS safari under the general setting `Block Pop-ups` and we cant guarantee that the current workarounds will always function there is really nothing we can do about it.

**Comment by gpsfl** [comment]
@caalador
Opening a new tab from a synchronous context seems to be desired way of doing this in Safari. Why can't you guarantee this will work?

**Comment by caalador** [comment]
Because it is a workaround specifically for ios safari that is extra for everything else.
Just adding extra checks to usage and then the upkeep for a feature we can't have automatic tests for.

Also what use case specifically needs the opening to happen through the server-side instead of using a link or adding a onclick client-side handler to a button?

**Comment by franrolando** [comment]
I see this is abandoned but, there is a way to detect if Popup are blocked in browser in a Sync way?

Because I did this:

```
AtomicBoolean verifyingPopups = new AtomicBoolean(true);
		StringBuilder script = new StringBuilder();
		script.append("let a = window.open('https://www.google.com', '_blank', 'width=1,height=1,resizable=yes,scrollbars=yes,status=yes');");
		script.append("if (a) {");
		script.append("console.log('Popups not blocked');");
		script.append("a.close();");
		script.append("return true;");
		script.append("} else {");
		script.append("console.log('Popups blocked');");
		script.append("return false;");
		script.append("}");
		log.debug("Validate popups");
		UI.getCurrent().getPage().executeJs(script.toString()).then(Boolean.class, result -> {
			log.debug("Are popups enabled? {}", result);
			popupsEnabled = result;
			verifyingPopups.set(false);
		});
```

But the main thread continues the execution.
Also tried with 

```
UI.getCurrent().access(() ->{
   UI.getCurrent().getPage().executeJs(script.toString()).then(Boolean.class, result -> {
			log.debug("Are popups enabled? {}", result);
			popupsEnabled = result;
   });
})

```

And 
```
FutureCompletable<Boolean> future = new FutureCompletable<>();
UI.getCurrent().getPage().executeJs(script.toString()).then(Boolean.class, result -> {
			log.debug("Are popups enabled? {}", result);
			popupsEnabled = result;           
                        future.complete(result):            
		});
future.get(); //The main thread gets locked here and the onSuccessfulCallback its not executed due executeJS use main thread to retrieve value from client and this is blocked by the get()
```
