### ISSUE TITLE
Websocket issue in Liberty when JAX-RS is used 

### ISSUE THREAD

**Issue by onuridrisoglu** [vaadin/flow#14889]
### Description of the bug

In a Vaadin project that is running on OpenLiberty 22, adding a JAX-RS Rest service, causes web sockets not to work anymore. 

The problem seems to be, [here](https://github.com/vaadin/flow/blob/587ce1e9fbec1a789a2d1ecc92bc5f84c4f87648/flow-server/src/main/java/com/vaadin/flow/server/communication/JSR356WebsocketInitializer.java#L232) the `com.ibm.websphere.jaxrs.server.IBMRestServlet` is interpreted as a Vaadin servlet. Thus the endpoints are registered twice.

The issue can be reproduced 

### Expected behavior

Websockets should work fine.

### Minimal reproducible example

The issue can be reproduced in the sample project: https://github.com/onuridrisoglu/sample-mpr-v14/tree/websocket-issue
(I basically used the same sample project used in #13627, note that the branch name is `websocket-issue`)

### Versions

- Vaadin / Flow version: 23.2.4
- Java version: OpenJDK 11.0.16.1
- OS version: macOS Monterey
- Browser version (if applicable): Chrome Version 106.0.5249.119 
- Application Server (if applicable): Open Liberty 22.0.0.4
- IDE (if applicable): N/A

**Comment by TatuLund** [comment]
Yes. I got just flashback from the past. https://github.com/vaadin/cdi/pull/238
