### ISSUE TITLE
Creating an Image with an empty alt-tag is counter intuitive

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#14880]
### Description of the bug

Creating an Image with the default constructor and supplying an empty string as `alt`-attribute does not create the proper `alt`-attribute on the client side. 

### Expected behavior

Using the constructor with an empty string creates an empty alt-tag on the client side. Needed to comply with accessibility of decorative images. 

### Workaround

```java
    var logo = new Image("/images/logo.svg", "");
    logo.getElement().setAttribute("alt", ""); // empty alt for a11y 
```

### Minimal reproducible example

Using `new Image("/images/logo.svg", "")` creates an image-element without alt-attribute `<img src="/images/logo.svg">`.

### Versions

- Vaadin / Flow version: all
- Java version: ---
- OS version: ---
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by knoobie** [comment]
@rolfsmeds You could add a11y here if you want :)

**Comment by caalador** [comment]
The component uses a ProperyDescriptor where the default for alt is "" and the descriptor removes default value attributes.
The feature change is adding a false to the descriptor generation, but would it create some other issues apart from breaking clearing the alt value using `img.setAlt("")`?

**Comment by knoobie** [comment]
It probably has to distinguish between `img.setAlt("")` which should result in an empty `alt=""` on the client and `img.setAlt(null)` which would really remove the attribute on the client side.

**Comment by rolfsmeds** [comment]
If I understand the issue correctly, for images that have no semantic purpose and shouldn't be announced by screen readers,`<img src="blarg.jpg" alt="">` is preferable to `<img src="blarg.jpg">` because the former is not announced at all (or maybe simply as "image"), whereas the latter is announced as "image blarg dot jpeg" (and you probably don't _want_ the screen reader to read the filename of the image).

So this is about providing developers with an easy way to achieve the preferred image semantics for images that don't need to be announced.

**Comment by knoobie** [comment]
Correctly @rolfsmeds! I stumbled upon this because our accessibility tester wanted me to remove the "Logo: application name" alt-text from our logo and therefore I called the appropriate constructor with an empty string, just to get called-out in the next round of tests, that the alt-attribute should still be present. (Haven't checked the DOM and had wrong? assumptions)

**Comment by knoobie** [comment]
That would be the ideal solution. Looking at the comment from @caalador above https://github.com/vaadin/flow/issues/14880#issuecomment-1284035277 - it looked like it wasn't possible with the current architecture based on ProperyDescriptor.. that's why he probably changed it this way.

**Comment by Artur-** [comment]
But there is no need to use `PropertyDescriptor`

**Comment by knoobie** [comment]
I couldn't agree more 😅

**Comment by caalador** [comment]
The main issue was keeping the clear functionality of setAlt if you have relied on that.
