### ISSUE TITLE
Frontend build breaks if folder name changed

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#14908]
### Description of the bug

When having a project, changing the project folder name with no other changes after having run the project once breaks the build with missing frontend modules.

This is due to npm creating a symlink to `./target/flow-frontend` and the symlink is absolute, so changing the project folder name doesn't break the hash check so no `npm install` is run to fix the symlink.

### Expected behavior

Changing folder name should not break build with missing frontend modules.

### Minimal reproducible example

Get app from start.
Run application and shutdown.
change folder name
Run application again.

### Versions

- Vaadin / Flow version: 14+

**Comment by Artur-** [comment]
Is this unnecessary for V23.3+ and V24+ where there is no `target/flow-frontend`?

**Comment by caalador** [comment]
It depends. 
What is the probability that the user adds a relative folder reference into package.json?

**Comment by Artur-** [comment]
Could we keep the hash as a representation of the package.json contents only and add the project folder and potentially other metadata we want to use to decide if we need to recompile in node_modules/.vaadin ? Then the hash would be usable when you want to know if package.json has changed
