### ISSUE TITLE
VaadinWebSecurity redirects POST requests on RestController to the login view

### ISSUE THREAD

**Issue by simasch** [vaadin/flow#14934]
### Description of the bug

This is my security configuration

```java
@EnableWebSecurity
@Configuration
public class SecurityConfiguration extends VaadinWebSecurity {

    public static final String LOGOUT_URL = "/";

    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests().antMatchers("/images/*.png", "/api/demo/**").permitAll();
        super.configure(http);
        setLoginView(http, LoginView.class, LOGOUT_URL);
    }

}
```

I have a RestController on /api/demo with a Get and a PostMapping:

```java
@RestController
public class DemoController {

    @GetMapping("/api/demo")
    public String get() {
        return "Demo";
    }

    @PostMapping("/api/demo")
    public String post() {
        return "Demo";
    }
}
```

The GET request works fine but the POST request redirects to the LoginView.

### Expected behavior

POST should be possible

### Minimal reproducible example

See code above

### Versions

- Vaadin / Flow version: 23.2.6
- Java version: 17

**Comment by Artur-** [comment]
Do you include the Spring CSRF token in the post request?

**Comment by Artur-** [comment]
Try `http.csrf().ignoringAntMatchers("/api/demo")` to see if this is the problem

**Comment by simasch** [comment]
Thanks! I've forgot about CSRF and POST.
