### ISSUE TITLE
PiT 23.3: PreserveOnRefresh does not work in master-detail views

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#14999]
### Description of the bug

When adding the `@PreserveOnRefresh` to a view that loads an entity based on the route path, unsaved changes are not correctly restored.

Check the following animation to see that it works with new entities, but it does not work when the entity is edited.

![preserve-on-refressh-1](https://user-images.githubusercontent.com/161853/199739575-77516094-ab09-4f3d-ba1d-405dfb39c72a.gif)

### Workaround

Use some mechanism to prevent loading the entity e.g.

```java
    @Override
    public void beforeEnter(BeforeEnterEvent event) {
    	if (binder.hasChanges()) {
    		return;
    	}
```

### Solution

When `@PreserveOnRefresh` is set, `BeforeEnterEvent` should not be called on reload. 
Based on the [documentation](https://vaadin.com/docs/latest/advanced/preserving-state-on-refresh/#preconditions-and-limitations) only `AttachEvent` and `DetachEvent` should only be generated

### Expected behavior

`PreserveOnRefresh` should work in both cases like in this screenshot:

![preserve-on-refressh-2](https://user-images.githubusercontent.com/161853/199740566-2e86d382-42e8-49ee-94fa-62ff1f6f8834.gif)

### Minimal reproducible example

- Download a project with the master-detail view from start website, and set current version
```bash
curl -s -f 'https://start.vaadin.com/dl?&preset=master-detail-view&projectName=test-app' -o test-app.zip 
unzip test-app.zip 
cd test-app
mvn -q versions:set-property -Dproperty=vaadin.version -DnewVersion=23.3.0.alpha1
```
- Add `@PreserveOnRefresh` annotation to the `MasterDetailJavaView.java` view
```bash
cat <<EOF |patch -p1
--- a/src/main/java/com/example/application/views/masterdetailjava/MasterDetailJavaView.java
+++ b/src/main/java/com/example/application/views/masterdetailjava/MasterDetailJavaView.java
@@ -31,11 +31,13 @@ import java.util.Optional;
 import java.util.UUID;
 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.data.domain.PageRequest;
+import com.vaadin.flow.router.PreserveOnRefresh;

 @PageTitle("Master-Detail (Java)")
 @Route(value = "master-detail-view/:samplePersonID?/:action?(edit)", layout = MainLayout.class)
 @RouteAlias(value = "", layout = MainLayout.class)
 @Uses(Icon.class)
+@PreserveOnRefresh
 public class MasterDetailJavaView extends Div implements BeforeEnterObserver {

     private final String SAMPLEPERSON_ID = "samplePersonID";
EOF
```

### Versions

- Vaadin / Flow version: `23.3.0.alpha1` and previous
- Java version: 11
- OS version: mac
- Browser version: chrome

**Comment by caalador** [comment]
The v23.3 preserve on refresh works the same way it does for v14 so `BeforeEnterEvent` has always been executed for the active chain when preserving.

**Comment by manolo** [comment]
Yes it was already there, and that is what I marked in the issue, but I found the issue when adding some PiT tests
> Vaadin / Flow version: 23.3.0.alpha1 and previous

The thing, is that probably that is a bad design since when reusing the view instance it would not be modified.
If you think that this is not an issue, it should be documented all the life cycle methods that are called when re-using the server view

**Comment by manolo** [comment]
Another option if we don't want to break the API, is some optional parameter to the `PreserveOnRefresh` for ignoring certain events like `@ PreserveOnRefresh(ignore = {BeforeEnterEvent.class})`
I dont follow what would be the API for the preserved flag you suggest, can you ellaborate?

**Comment by caalador** [comment]
So the BeforeEnterEvent would have a boolean field `refresh` or `preserved` that you can check to see if you should not run some code for before enter or not. 
For example `if (event.isRefreshEvent()) { return; }`

**Comment by manolo** [comment]
Gotcha, thanks for the clarification, so, either solution works to me.
Otherwise, having to figure out a workaround based on app code like `binder. hasChanges()` is quite flaky
