### ISSUE TITLE
Application doesn't start when enabling @EnableMethodSecurity with vaadin 24.0.0.alpha2

### ISSUE THREAD

**Issue by aspan** [vaadin/flow#15059]
### Description of the bug

Application doesn't start when enabling @EnableMethodSecurity with vaadin 24.0.0.alpha2.

The problem is in VaadinWebSecurity where the servletContext is fetched. When enabling global method security the SPEL `@Value("#{servletContext.contextPath}")` can't be evaluated because there is no bean named servletContext available.

To reproduce create a new project with vaadin starter with vaadin 24 and security enabled. Then add the following class 

```
@Configuration
@EnableMethodSecurity(jsr250Enabled = true)
public class GlobalSecurityConfiguration {
    @Bean
    MethodSecurityExpressionHandler methodSecurityExpressionHandler() {
        return new DefaultMethodSecurityExpressionHandler();
    }
}
```

### Expected behavior

The application should start

### Minimal reproducible example

See [https://github.com/aspan/my-app](https://github.com/aspan/my-app)

Start with `mvn spring-boot:run`

### Versions

- Vaadin / Flow version: 24.0.0.alpha2
- Java version: 17.0.5
- OS version: N/A
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by aspan** [comment]
Would it be possible to use the spring boot property `server.servlet.context-path` instead of `#{servletContext.contextPath}` like `${server.servlet.context-path}`? That way the servlet context doesn't need to be available.

**Comment by Artur-** [comment]
You can even delete the whole context path and then end up instead with
```
Caused by: java.lang.IllegalAccessError: class com.vaadin.flow.spring.security.VaadinWebSecurity tried to access method 'java.lang.String com.vaadin.flow.spring.security.RequestUtil.getUrlMapping()' (com.vaadin.flow.spring.security.VaadinWebSecurity is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @6fa5bd1e; com.vaadin.flow.spring.security.RequestUtil is in unnamed module of loader 'app')
```

Does method security by default prevent calls and maybe also injection?

**Comment by aspan** [comment]
When i replace '@Value("#{servletContext.contextPath}")' with '@Value("${server.servlet.context-path:}")' my application starts up normally. Notice the ':' in the property to set the empty string in case the property is missin.

**Comment by aspan** [comment]
I figured out what the problem is, `@EnableMethodSecurity` expects the `SecurityContectHolderStrategy` bean to be available before the `servletContext` bean is initialised. So the solution is to move that bean out of `VaadinWebSecurity` so that it is initialised before the `servletContext` bean is available.

**Comment by dinix2008** [comment]
Hello, i`m use version 24.0.3 and bug still present.
