### ISSUE TITLE
When using webcomponents in my application, I want to be able to host the polyfills outside the server (from a CDN for example), so I can have all static files in one place.

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#1512]
Currently the polyfills provided by the framework (webcomponents.js and es6-collections.js) are served from inside the WAR, and there's no simple way to change that.

**Comment by pleku** [comment]
Due to lack of demand and unclear ROI, closing this issue.

If someone needs this feature, please open a new issue with explanation on what you need and why.
