### ISSUE TITLE
PiT 23.3: compilation error when rolling-back from 23.3 to 23.2 

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#15208]
### Description of the bug

When a 23.2 developer tries their app with 23.3, if he tries to roll-back the application does not compile anymore, even running `mvn clean` 

The problem is that there is new stuff left in the `frontend/generated` folder that is not compatible with previous platform versions.

Probably `generated` folder should be cleaned up during the `prepare-frontend` goal

### Expected behavior

No errors when rolling back to the previous version

### Workaround

Run `mvn vaadin:dance` to clean everything including the `generated` folder

### Minimal reproducible example

- Download a 23.2 start project
```
curl -s -f 'https://start.vaadin.com/dl?&preset=latest-java&projectName=latest-java' -o latest-java.zip
unzip latest-java.zip
cd latest-java
```
- upgrade version to 23.3
```
mvn versions:set-property -Dproperty=vaadin.version -DnewVersion=23.3.0.alpha1
```
- Compile it for production
```
mvn -Pproduction package
```
- downgrade to 23.2 and compile
```
git checkout pom.xml
mvn -Pproduction package
```
- There is an error in console
```
frontend/generated/jar-resources/tooltip.ts(1,25): error TS2307: Cannot find module '@vaadin/tooltip' or its corresponding type declarations.
```

### Versions

- Vaadin / Flow version: 23.3.0

**Comment by Artur-** [comment]
Maybe this used to work better by coincidence when the jar resources were in target as they were then removed when doing `mvn clean install`

**Comment by mshabarov** [comment]
To be mentioned in the upgrade instructions https://vaadin.com/docs/latest/upgrading/essential-steps
