### ISSUE TITLE
Resync of UI will cause detach and attach for the same instance of UI

### ISSUE THREAD

**Issue by samulivaadin** [vaadin/flow#15246]
### Description of the bug

Originally found with https://github.com/vaadin/spring/issues/1045

Consider scenario where a proxy server breaks a websocket connection and then the "Resynchronizing UI by client’s request" happens. Internally ui.getInternals().getStateTree().prepareForResync() gets called.

What happens next is that the same existing UI instance will receive a detach event and then attach event. 

Also javadoc of UI.onDetach says "Called before the UI is removed from the session. A UI instance is detached exactly once, either..." which is incorrect in this case. UI is not removed from session and onDetach can be called multiple times on same instance because of resync causes detach & attach without creating a new instance.

### Expected behavior

When resync happens, instead of detach/attach same instance, let the UI be removed from the session and create a new UI instance. This partial recovery by re-using same instances causes issues with spring plugin that relies on the lifecycle of attach/detach and the fact that they should be called only once.

### Minimal reproducible example

See example app posted at ticket https://github.com/vaadin/spring/issues/1045

### Versions

- Vaadin / Flow version: 23.2.6.
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by Legioth** [comment]
The reason for the detach + attach is to ensure all components also get a chance to reinitialize their client-side state. It's not reasonable that we expect all component implementations to also listen to resync events for that purpose when they should already also do the same for detach and attach events.

Based on that, I would guess that a better course of action would be to adjust the javadocs and find a way of making Spring scopes survive being temporarily detached.

**Comment by tltv** [comment]
I agree with @Legioth's idea to just adjust Javadoc and update the code so that Spring beans will survive when detach/attach happens by resync. My Pull request takes care of that for UIScoped beans by making the decision based on `UI#isClosing()` which return false only when doing resync.

@samulivaadin Do you see if this would be good for the original scenario? PR should handle that case because UI scoped Spring beans would survive with this fix.

**Comment by samulivaadin** [comment]
I think so. In the original scenario the wreak and havoc was caused by the fact that the UIScoped beans were re-created unexpectedly. Its an another matter if the attach/detach can be called more than once, but as a developer I would live with that with mentions in javadoc.

**Comment by tltv** [comment]
Beans with `RouteScope` are not cleared on resync. Just pointing out as vaadin/spring#1045 description may give that idea.
