### ISSUE TITLE
Dynamic loading of a web component fails with 'Error Application ROOT-2521314 already initialized'

### ISSUE THREAD

**Issue by mrts** [vaadin/flow#15263]
### Description of the bug

I've implemented dynamic loading of a Vaadin exported web component inside a Vaadin 23.2 view, the respective commit is here: https://gitlab.com/mrts/vaadin-embedding-example-guestbook/-/commit/b091d08c1038264f25b6f2c725652297852494ce.

The custom element is loaded and registered successfully, but rendering fails with the error `Application ROOT-2521314 already initialized`:
```
Loading custom element guest-book   dynamic-webcomponent-loader.ts:37:16
registering <guest-book> using id GuestBook-0   guest-book.js:112:13
Processing time was 2ms   FlowClient.js:205:19
Uncaught Error: Application ROOT-2521314 already initialized
    initApplication   FlowBootstrap.js:93
```

### Expected behavior

When I open http://localhost:8080/dynamic-loader and click the _Load web component_ button, then the web component is loaded and displayed on the page, the same way as in http://localhost:8080/basic.html.

### Minimal reproducible example

See https://gitlab.com/mrts/vaadin-embedding-example-guestbook.

Run the project using `mvn jetty:run` and open http://localhost:8080/dynamic-loader in the browser to test.

### Versions

- Vaadin / Flow version: 23.2.9
- Java version: 11
- OS version: Ubuntu 22.04
- Browser version (if applicable): Firefox 107
- Application Server (if applicable): Jetty

**Comment by mrts** [comment]
I guess the cause of the problem is that the application root and web components can be only defined once.

To solve this issue, I would like to propose a new build target that lets developers choose to externalize Vaadin from the built bundle so that the custom components will be using the Vaadin components from the host application. For example, Vue.js provides the [`--target lib` build target](https://cli.vuejs.org/guide/build-targets.html#library) that builds the application as a reusable library where Vue is externalized (the library will not have a bundled copy of Vue even if the code imports Vue). There are a couple of more [tips in Vue docs](https://vuejs.org/guide/extras/web-components.html#building-custom-elements-with-vue) regarding how to create a web components library.

Vaadin Labs has an example where [web components are loaded only once](https://github.com/Artur-/iot#load-web-components-only-once), but it is nontrivial to set up, somewhat fragile and I think that this feature should be provided by the Vaadin framework (like Vue) if Vaadin wants to ride along the microfrontends wave. Microfrontends are becoming more and more widespread as they are the next logical step of evolution after microservices.

**Comment by Artur-** [comment]
I wonder if the incorrect assumption here is that a given vaadin servlet cannot be used as a Flow app and to export web components at the same time. The ROOT-1234 id only refers to Vaadin internals and the Flow client engine.

**Comment by mcollovati** [comment]
@Artur- is right. The same servlet cannot be used to serve both the Flow application and the exported web components into the same application.

A dirty trick may be defining two `VaadinServlet` mapped to different URLs, one for the main application and the other for the web components, but this may not work well with PUSH.

```java
@WebServlet(urlPatterns = "/embed/*", asyncSupported = true)
public class WebComponentsServlet extends VaadinServlet {
}
@WebServlet(urlPatterns = "/*", asyncSupported = true, loadOnStartup = 1)
public class MainAppServlet extends VaadinServlet {
}
```
and the dynamic loader imports the web component from the `WebComponentsServlet`

```javascript
registerAndLoadCustomElement(name: string) {
  const src: string = `/embed/web-component/${name}.js`;
  .....
}
```

Anyway, it may be worth it to document that embedding of exported web-components into a Vaadin application processed by the same Vaadin servlet is not allowed.

**Comment by Artur-** [comment]
Is there any reason for this limitation?

**Comment by Artur-** [comment]
With #15315 the embedding seems to work fine

**Comment by mcollovati** [comment]
The fix seems to work well.
However, I see continuous web socket disconnections, but I don't have yet understood if it is an issue with jetty version in use or if it is somehow related to the test project code

**Comment by mrts** [comment]
Works like a charm with Vaadin 23.3.0, thanks a lot!
