### ISSUE TITLE
Binder: hasChanges() per binding

### ISSUE THREAD

**Issue by Frettman** [vaadin/flow#15266]
### Describe your motivation

While using a `Binder`, there are cases where I need to explicitly check whether the value of a specific binding has changed. `Binder` already keeps track of this information, but it's only accessible as an aggregated value for the whole `Binder` via `hasChanges()`. I would like for this to be accessible per binding.

### Describe the solution you'd like

The two following methods would solve this. From what I can see, `Binder` should already have the required information.

- `Binder#hasChanges(Binding<?,?>)`
- `Binding#hasChanges()`

**Comment by Legioth** [comment]
This sounds like a reasonable enhancement suggestion. 

Could you describe a use case for which it would be useful to check whether a specific binding has changes so that we can be sure there are no mismatched underlying assumptions?

**Comment by Frettman** [comment]
I use `readBean(...)` and `writeBean(...)`, so the "has changes" information would be actually available. My specific use case is essentially that certain email addresses require a written justification. That justification must be entered in the Notes-field. The notes field may already contain other information, so I cannot check whether it's empty; I need to check whether it's changed. (No, I did not come up with this ;). Anyway, I basically would like to do something like this:
`emailBinding.addValidator(new SpecialEmailValidator(notesBinding::hasChanges))`
I realize that this may not be a very compelling use case and a workaround is not that difficult. But since `Binder` already has the information and provides a global `hasChanges()`, a local `hasChanges()` on the binding would fit right in. So I'd consider this a low priority enhancement; something to on a Friday afternoon, if you don't want to start any new big tickets ;)

**Comment by TatuLund** [comment]
Alternatively we just could add public getter for getting changed bindings, as there is already changedBindings private field in Binder class.

**Comment by Frettman** [comment]
It seems Vaadin 24 already has both of my suggested methods, so I'll close this ticket.
