### ISSUE TITLE
Getting routed to session expired URL on resynchronisations despite VaadinSession should not have expired

### ISSUE THREAD

**Issue by p-maraver** [vaadin/flow#15281]
### Description of the bug

This is an upgraded application from Vaadin 8 to Vaadin 23, which still using Vaadin 8 components via MPR. 

We are noticing resynchronization requests when network conditions are not optimal, which in and of itself is expected behaviour I believe. However, when the resynchronization is in process, the client receives a long poll push stating that the session has expired (even though we don't believe it should have). 

### Expected behavior

Not expiring session for not optimal network conditions.

### Minimal reproducible example

There is a reproducible example and a demo video with the steps to reproduce at https://support.vaadin.com/browse/VS-4410

### Versions

- Vaadin / Flow version: 23.2.6
- MPR: 6.0.3
- Java version: 11
- OS version: NA
- Browser version (if applicable): NA
- Application Server (if applicable): NA
- IDE (if applicable): NA

**Comment by p-maraver** [comment]
After testing the reported issue we found the following: 

The combination of high frequency PUSH messages with long polling transport and slow network causes some message to be lost during while the new http connection is established.
To overcome this problem on server side lost messages are cached and sent once the new connection is ready.
However, when going offline and then back online a couple of messages are completely lost.
It seems like that the server side broadcaster is trying to sending them, but to a wrong Atmosphere resource that does not exist anymore (needs more investigation to be confirmed).
When this happens, Flow client and server are out of sync and the server requires the client to perform a resynchronization.
The resynchronization process causes all components in the UI tree to be detached and then attached again.
And here is the issue with MPR: since also the MPR components are detached the UI gets closed, so when the flow client attempts to establish the push connection it doesn't find the UI and it raises the "Session expired" message.

**Comment by TatuLund** [comment]
Maybe related to: https://github.com/vaadin/flow/issues/13660

**Comment by czp13** [comment]
A customer opened a warranty ticket for it yesterday (BFP, VS-4468).

**Comment by mcollovati** [comment]
@p-maraver Flow 23.3.4 and 23.2.10 contains a [fix](https://github.com/vaadin/flow/pull/15764) that should prevent this issue.
May I ask you to try it and confirm if it solves the issue?

**Comment by czp13** [comment]
> @p-maraver Flow 23.3.4 and 23.2.10 contains a [fix](https://github.com/vaadin/flow/pull/15764) that should prevent this issue. May I ask you to try it and confirm if it solves the issue?
I am replying here as well because if I am right I took over this issue from @p-maraver. 
And I was recalling mistakenly, the customer was using 23.2.6, so I asked them to update it to 23.2.10, I will let you know when I got feedback from them!

**Comment by czp13** [comment]
Peter replied to me that they cannot test it anymore, as they have their own implementation for the session expiration:

> We are happy to close this now. Unfortunately we won't be retesting on our side as we turned off the vaadin controlled session expiration and implemented our own version. It's great to know that it's fixed though.

I asked him to get back to us anytime they need our help regarding to this topic (or anything else). As discussed with the planning, we probably can close this one.
