### ISSUE TITLE
With 23.3, Vite recompiles all jar-resources on every change

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#15303]
### Description of the bug

As the `jar-resources` folder is now on the watch path of Vite, the jar-resource files need to be selectively written so Vite does not have to re-process all of them all the time

### Expected behavior

A file in jar-resources is written only if it has changed

### Minimal reproducible example

vaadin init --pre hello-23.3
mvn
touch target/classes/application.properties

### Versions

-

**Comment by manolo** [comment]
I guess computing a hash if exists in target before overriding should be enough

**Comment by Artur-** [comment]
In a way related to #15208. If we know what jar-resources should be in the folder, compare the contents with what is there and write what does not match, maybe we can delete the files that should not be there at the same time

**Comment by Artur-** [comment]
I cannot reproduce this anymore for some reason. It should never have happened as #10640 was included already in V19
