### ISSUE TITLE
Gradle task ":vaadinPrepareFrontend" does not cache results

### ISSUE THREAD

**Issue by valentin-ricard** [vaadin/flow#15342]
### Describe the bug

The ":vaadinPrepareFrontend" does not cache if the source and dependencies did not change, causing increasingly long compile times on incremental builds on another project.

This shows when running the build with the `--info` flag:
```log
Task ':projectName:vaadinPrepareFrontend' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
```

### Expected-behavior

When running successive builds without changing a file, the output of ":vaadinPrepareFrontend" is identical, so there is no need to execute it twice.

### Reproduction

 - Have two Vaadin applications in the same multimodule Gradle project
 - Execute two successive build commands on the project root (the default when using IntelliJ)
 - See that the ":vaadinPrepareFrontend" command is not "UP-TO-DATE" even if the files did not change

### System Info

Windows 10, Java 17, Vaadin 23.2.0
Gradle:
- Version: 7.4
- Vaadin plugin version: 23.2.0
- Build cache: Disabled
- Config cache: Disabled
- Parallel builds: Disabled

**Comment by FritjofH** [comment]
This would be great to get done. It would be an improvement for sure, and with all the improvements done to caching in Gradle 8 which just released this makes sense.

**Comment by tarekoraby** [comment]
No work has been started on this yet, but we are currently _considering_ adding support for this functionality soon (which would be released with Vaadin 24.2, currently scheduled for September 2023).

**Comment by steve-todorov** [comment]
@tarekoraby many thanks for your reply! Are there any plans for implementing cache in `vaadinBuildFrontend` as well or only the `vaadinPrepareFrontedn` task?

**Comment by tarekoraby** [comment]
I see adding caching support to `vaadinBuildFrontend` as less of an impactful enhancement since it is only used for creating production builds, which are relatively infrequently created and are usually not time-critical. Conversely, `vaadinPrepareFrontend` affects both development and production builds. So, we will prioritize the latter for now. (of course, if there is a way to address both tasks in one go during implementation, we should consider it). 

cc @mshabarov

**Comment by benstpierre** [comment]
This would be an extremely valuable feature for us as we migrate our app to Gradle.  I might ping expert chat about this as well.

**Comment by mshabarov** [comment]
I agree with the above comments about `vaadinBuildFrontend`. Since this goal also generates files, it makes sense to apply caching there also. We will see how easy it would be to apply caching to `vaadinBuildFrontend` during development for `vaadinPrepareFrontend `.

**Comment by mshabarov** [comment]
I've made an another ticket for build frontend task, see https://github.com/vaadin/flow/issues/17354.
When you run prod build on the servers, it usually needs to build the bundle (run this task), so this feature might be useful more for local production builds.
If you think this feature would be useful in your project, please vote in the mentioned ticket and explain your use case.
Flow team will consider to implement it in the next releases, if gets much votes and feedback.
