### ISSUE TITLE
Improve the logic that decides whether to re-compile / re-build the bundle

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#15376]
The logic that checks if a default bundle or a new custom bundle is needed is not good enough. It only checks the `package.json` hash https://github.com/vaadin/flow/blob/feature/nonodemode/flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java#L131. 

It should check:
- project frontend files through hashes or similar
- npm dependencies and their versions
- ~bundle's entry points~
- package.json hash

**Comment by caalador** [comment]
Done is npm dependencies with versions and package hash.
Next would be frontend files and after that changed frontend files.

**Comment by caalador** [comment]
Validation against in-memory package.json and flow-generated-imports.js imports added.

**Comment by caalador** [comment]
Closing as done. Any missing things or updates to logic should get a new issue.
