### ISSUE TITLE
Required can be overridden by custom converter

### ISSUE THREAD

**Issue by abdullahtellioglu** [vaadin/flow#15386]
### Description of the bug

If custom converter is used and returns ok for empty value, `asRequired` is overridden. In my case, same converter is used by non-required and required fields. The result for both inputs have the same output regardless of asRequired is used or not. 

### Expected behavior

`asRequired` should check field’s value at the end of converter and validation chains and should override chain result if it equals to null. 

In the example; if user clicks the validate button firstTextField should warn the user and secondTextField should pass the validation. 

### Minimal reproducible example

```

    private TextField firstTextField = new TextField("First value");
    private TextField secondTextField = new TextField("Second value");
    private final Binder<FooPOJO> binder = new Binder<>(FooPOJO.class);

    public MainView() {
        firstTextField.setId("first-txt-field");
        secondTextField.setId("null-txt-field");
        binder.setBean(new FooPOJO());
        binder.forField(firstTextField).withConverter(new CustomStringToDoubleConverter()).asRequired().bind("firstItem");
        binder.forField(secondTextField).withConverter(new CustomStringToDoubleConverter()).bind("secondItem");


        Button btn = new Button("Validate");
        btn.addClickListener(event -> {
            BinderValidationStatus<FooPOJO> validate = binder.validate();
            if(!validate.isOk()){
                validate.getFieldValidationErrors().forEach(fieldValidation -> {
                    if(fieldValidation.isError()){
                        HasValue<?, ?> field = fieldValidation.getField();
                        ((HasStyle)field).addClassName("error");
                    }
                });
            }
        });
        add(firstTextField, secondTextField, btn);
    }

    public static class CustomStringToDoubleConverter extends StringToDoubleConverter {
        public CustomStringToDoubleConverter() {
            super("Empty value");
        }

        @Override
        public Result<Double> convertToModel(String value, ValueContext context) {
            if(value == null || value.equals("")){
                return Result.ok(null);
            }
            //some business here
            return super.convertToModel(value, context);
        }

        @Override
        public String convertToPresentation(Double value, ValueContext context) {
            if(value == null){
                return "";
            }

            return super.convertToPresentation(value, context);
        }
    }
```

```
@Getter
@Setter
public class FooPOJO {
    private Double firstItem;
    private Double secondItem;
}

```

### Versions

- Vaadin / Flow version: 23.2.9
- Java version: 11
- OS version: MacOS Monterey 12.6
- Browser version (if applicable):
- Application Server (if applicable): Spring Boot/Open Liberty - Happening in both-
- IDE (if applicable):

**Comment by abdullahtellioglu** [comment]
I can rely on `getEmptyValue()`. The thing is I have to return `Result.ok` or `Result.error` in converter otherwise for null value Binder throws an exception. **If I return Result.ok `asRequired` is overridden.** If I return Result.error if value is null or equals to `getEmptyValue()`, I cannot use the same converter for non-required fields.

```
BindingBuilder bindingBuilder = binder().forField(...);
if(propertyType == Integer.class){
   bindingBuilder.withConverter(new CustomIntegerConverter());
}
if(required){
   bindingBuilder.asRequired();
}
```
In this case, converter has nothing to do with validation and requirement is only done by `asRequired` shorthand. 

@OlliTietavainenVaadin commented in slack channel : 

I guess the problem is that the way that the default `BindingBuilder` is implemented (created by `doCreateBinding`), you can't separate the `asRequired` Validator from the others to make sure it's executed last. Even if you used `beforeClientResponse` to make sure the Validator created from `asRequired` is added last, the application could still add another Converter after the fact, which would still break the contract. But given the JavaDoc of asRequired, I do think the current behavior is buggy.

**Comment by Legioth** [comment]
Validators and converters are used in the order they are added to the chain.

If you have `forField(...).withConverter(...).asRequired()`, then it will check whether the converted value equals the field's empty value (which for `TextField` is the empty string). This does obviously not work if the converted value is something else (e.g. `null`).

You do thus have two possible alternatives:
1. Change the order to `forField(someField).asRequired().withConverter(something)` so that the validator gets the unconverted string value rather than the converted value.
2. Add a validator that checks for `null` rather than `""` after the converter. `forField(someField).withConverter(someField).withValidator(value -> value != null, "This field is required")`. To visually mark the field as required, you can then do `someField.setRequiredIndicatorVisible(true)`.

**Comment by mcollovati** [comment]
@abdullahtellioglu are the hints provided by @Legioth enough, or do you think there's something else we should check?

**Comment by abdullahtellioglu** [comment]
Changing the order solved my problem 👍
