### ISSUE TITLE
Gradle plugin - some files are not copied into the jar (production build)

### ISSUE THREAD

**Issue by roastedcpu** [vaadin/flow#15400]
### Description of the bug

After setting up a project with gradle and disabling Vite (via featureflags) it all works except when a production build is issued. I noticed the build was broken - some styles were missing and vite got enabled again. After inspecting the jar I realized featureflags was not there anymore, neither the referred styles.

### Expected behavior

Production build should work as well as the debug build - vite should be kept disabled via featureflags and styles should be copied

### Minimal reproducible example

Please contact me for further details

### Versions

- Vaadin / Flow version: 23.2.2
- Java version: 11

**Comment by MarcinVaadin** [comment]
The issue was assigned to a developer and is currently being investigated

**Comment by MarcinVaadin** [comment]
I’ve retested it on base-starter-gradle (23.3.0) and works as expected, steps I’m doing:
1. `./gradlew appRun` for first time
2. Enable webpack using feature flag slider (vaadin-featureflags.properties has been created)
3. Run `./gradlew clean build -Pvaadin.productionMode` like in README.md
4. Check build/libs/… .war/WEB-INF/classes and vaadin-featureflags.properties is there
5. Run using ./gradlew appRun and:
`[ForkJoinPool.commonPool-worker-1] INFO com.vaadin.base.devserver.AbstractDevServerRunner - Started Webpack. Time: 3475ms`

Webpack is running, properties file has not been deleted. Am I missing something?

Can you retest on 23.3.0?

**Comment by MarcinVaadin** [comment]
I've checked also on 23.2.2 and everything is ok.

**Comment by roastedcpu** [comment]
This is not reproducible, the problem was something else. Thank you!
