### ISSUE TITLE
SpringApplicationConfigurationFactory does not consider all property name variants

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#15447]
### Description of the bug

If you set 
```
vaadin.enable-dev-server=false
```

in application.properties then `SpringApplicationConfigurationFactory` fails to parse it so `ApplicationConfiguration.enableDevServer` will return `true` (the default value) and `DeplyomentConfiguration.enableDevServer` will return `false`

### Expected behavior

ApplicationConfiguration should use all variants of the property from application.properties

### Minimal reproducible example

```
npx @vaadin/cli --next test-express
echo "vaadin.enable-dev-server=false" >> src/main/resources/application.properties
mvn
```

The dev server starts Vite as it thinks a dev server should be used and the application fails to start as it cannot find an express mode bundle

### Versions

- Vaadin / Flow version: 24 snapshot

**Comment by tepi** [comment]
Closing this since we no longer support `vaadin.enable-dev-server` property, and looks like there are no other properties with similar issue.
