### ISSUE TITLE
Add option to prevent client from automatically creating a new session when previous session times out

### ISSUE THREAD

**Issue by archiecobbs** [vaadin/flow#15476]
### Describe your motivation

In older version of Vaadin like 7.x, if the session expired on the server and was closed (e.g., idle timeout) the client would show the big red banner and would just sit there until you clicked on it or pressed ESC.

This meant that the session on the server would go away and get garbage collected, and no new session would be created until if and when the user took some action. Very nice - all state is restored back to the way it was before the client connected.

In Vaadin 23, the new behavior on the client seems to be to automatically reconnect and establish a new session as soon as the old session idle times out. This means anyone who happens to walk away and leave their web browser running (as most people do) will take up resources on the server even though they're not actually doing anything.

So if you have a factory with 1,000 people who go home at 5pm, you still have 1,000 sessions active on your server all night long. Bleh.

### Describe the solution you'd like

I would like a simple boolean configuration knob that lets me enable or disable this "automatically reconnect on session timeout" behavior in the client, so that restoring the prior behavior is an option.

Maybe a servlet parameter or deployment parameter or whatever.

### Describe alternatives you've considered

None.

### Additional context

This change would be entirely backward compatible.

**Comment by knoobie** [comment]
If you configure a session timeout, that's exactly what happens. There is a pop-up once the time limit of inactivity is reached and the user is redirected to the login view. Some more in-depth infos by Martin here https://mvysny.github.io/vaadin-session-timeout/

**Comment by MarcinVaadin** [comment]
Thanks @knoobie for quick answer, @archiecobbs please have a look at knoobie's answer and close ticket if it solves your issue.

**Comment by mcollovati** [comment]
I think this can be achieved with a providing a session expired URL pointing to a static page with `CustomizedSystemMessages` 

```java
public class CustomInitServiceListener implements VaadinServiceInitListener {
    @Override
    public void serviceInit(ServiceInitEvent event) {
        event.getSource().setSystemMessagesProvider(new SystemMessagesProvider() {
            @Override
            public SystemMessages getSystemMessages(SystemMessagesInfo systemMessagesInfo) {
                CustomizedSystemMessages messages = new CustomizedSystemMessages();
                messages.setSessionExpiredURL("/session-expired.html");
                return messages;
            }
        });
    }
}
```

**Comment by mcollovati** [comment]
We should definitively improve `Session Expiration` paragraph on  `Application Lifecycle` documentation page, adding information about `CustomizedSystemMessages`

**Comment by archiecobbs** [comment]
> If you configure a session timeout, that's exactly what happens.

I think you guys are not understanding what I'm saying.... (or else the reverse :)

I'm not talking about what happens on **session timeout**. I'm talking about what happens on **idle timeout**.

That is, when you have a browser tab open and have configured `closeIdleSessions` to `true`. The browser is sending continual heartbeats but not any other activity, so it's considered idle. As I understand things, because of the heartbeats, the session is never going to timeout in this situation.

So my sessions are not timing out - they are being forcibly closed after `UI` idle timeout.

Here's what the server log shows when an idle timeout occurs (my `UI` instances log whenever they attach or detach). The first line below is being logged by Vaadin itself:
```
2022-12-14 06:28:59,619 DEBUG: Closing inactive session AB9DD4CD3F5146FC3923E6E64E615BA0
2022-12-14 06:28:59,622 DEBUG: detaching ConfigUI[id=38,peer=127.0.0.1:65438,user=null]
2022-12-14 06:29:06,105 INFO : new ConfigUI created
2022-12-14 06:29:06,106 DEBUG: attaching ConfigUI[id=39,peer=127.0.0.1:49210,user=null]
```

Note that the client is automatically and immediately reconnecting after about a 7 second delay. This is the behavior I want to stop.

**Comment by knoobie** [comment]
You can redirect the user once the idle time is too long on a static page like described Marco. It's also possible doing this with the HeartbeatListener where you can react on the heartbeats and force a redirect or logout (in my case) (ui::addHeartbeatListener)

**Comment by archiecobbs** [comment]
More information...

My servlet config has these parameters:
```xml
    <init-param>
        <param-name>closeIdleSessions</param-name>
        <param-value>true</param-value>
    </init-param>
    <init-param>
        <param-name>heartbeatInterval</param-name>
        <param-value>193</param-value><!-- every 3.22 min -->
    </init-param>
```
and this is the `web.xml` session config:
```xml
    <session-config>
        <tracking-mode>COOKIE</tracking-mode>
        <session-timeout>60</session-timeout><!-- one hour -->
    </session-config>
```
The `closeIdleSessions` setting appears to take effect about every 6½ minutes, as shown in the log below. 6½ minutes equals 390 seconds,  which corresponds closely to two heartbeats (386 seconds when the heartbeat interval is set as shown to 193).

```
2022-12-14 12:55:05,843 DEBUG: Closing inactive session 3CE9864FEF632FE456C5949F767D2B2F
2022-12-14 13:01:34,826 DEBUG: Closing inactive session 3CE9864FEF632FE456C5949F767D2B2F
2022-12-14 13:08:03,836 DEBUG: Closing inactive session 3CE9864FEF632FE456C5949F767D2B2F
2022-12-14 13:14:32,846 DEBUG: Closing inactive session 3CE9864FEF632FE456C5949F767D2B2F
2022-12-14 13:21:01,844 DEBUG: Closing inactive session 3CE9864FEF632FE456C5949F767D2B2F
2022-12-14 13:27:31,849 DEBUG: Closing inactive session 3CE9864FEF632FE456C5949F767D2B2F
2022-12-14 13:34:00,850 DEBUG: Closing inactive session 3CE9864FEF632FE456C5949F767D2B2F
2022-12-14 13:40:29,838 DEBUG: Closing inactive session 3CE9864FEF632FE456C5949F767D2B2F
```
But note that the sessions somehow come back to life with the same hex ID... ??

So perhaps there is a simple underlying bug here, which is that "Closing inactive session" doesn't actually fully close the session.

If so that would explain the behavior I'm seeing.

**Comment by archiecobbs** [comment]
See also #15489 for some suggestions on how to improve the documentation.

**Comment by mcollovati** [comment]
The `Closing inactive session XYZ` message may be a bit misleading because it refers to closing the `VaadinSession` but it prints the identifier is the HTTP session ID.
Closing `VaadinSession` does not imply invalidating the HTTP session; a new `VaadinSession` will be created for the same HTTP session if a new request comes in after later on.
Perhaps `Closing inactive Vaadin Session in HTTP session XYZ` may be better

BTW, I tried the above web.xml configuration and I got only one `Closing inactive session` message after about 1 hour and 19 heartbeat request (193 x 19 = 3667 approx 61 minutes).

So, it seems to work as expected, at least with my local test

**Comment by archiecobbs** [comment]
> The Closing inactive session XYZ message may be a bit misleading because it refers to closing the VaadinSession but it prints the identifier is the HTTP session ID.

That makes sense... thanks for the clarification.

> I tried the above web.xml configuration and I got only one `Closing inactive session` message after about 1 hour

Not sure why your experience differs. What is displayed on your browser tab after this happens?

In fact with Vaadin 23 I don't think I've ever seen any kind of "session expired" message on the client, except when the server is actually shutdown. If the server is running, the client _always_ automatically "reloads" and creates a new session automatically (assuming there is no `CustomizedSystemMessages` redirect configured).

So I'm still wondering if (a) this is the intended behavior, and if so (b) whether there could be a configuration parameter added that would revert to the original behavior of not auto-reconnecting.

**Comment by mcollovati** [comment]
> Not sure why your experience differs. What is displayed on your browser tab after this happens?

Without `CustomizedSystemMessages`, after about one hour (and a single `Closing inactive session` message) the `VaadinSession` expires and the page is automatically reloaded.

This is the expected behavior because, by default, `SystemMessages.sessionExpiredNotificationEnabled` is false.

If the flag is true, after `VaadinSession` expiration, a notification is shown and there are no reloads or reconnection attempts until the user clicks on the notification or presses the ESC key.

![image](https://user-images.githubusercontent.com/4648894/208078841-72813332-2bfa-49b3-9dae-1a642361089f.png)

So, perhaps `CustomizedSystemMessages.sessionExpiredNotificationEnabled(true)` could be the "configuration parameter" you are looking for.


Of course, documentation needs to be improved

- clarifying the difference between `VaadinSession` and HTTP session expiration
- document the default behavior on `VaadinSession` expiration and how to customize it through `CustomizedSystemMessages`
- fixing Javadoc of `CustomizedSystemMessages` as they are outdated

**Comment by archiecobbs** [comment]
> So, perhaps CustomizedSystemMessages.sessionExpiredNotificationEnabled(true) could be the "configuration parameter" you are looking for.

Of course! I didn't know `SystemMessages.sessionExpiredNotificationEnabled` existed. That sounds like exactly what I'm looking for.

Thanks!

> Of course, documentation needs to be improved

Agreed!
