### ISSUE TITLE
vaadin.launch-browser=true and HTTPS

### ISSUE THREAD

**Issue by simasch** [vaadin/flow#15496]
### Description of the bug

If https is configured the browser is opened with http://localhost:8080 instead of https://localhost:8080,

### Expected behavior

The browser should be opened with https://localhost:8080,

### Minimal reproducible example

Create a self signed certificate and set the server.ssl properties:

    server.ssl.key-store-type=PKCS12
    server.ssl.key-store=classpath:localhost.p12
    server.ssl.key-store-password=password
    server.ssl.key-alias=1

### Versions

- Vaadin / Flow version: 23.3.0
- Java version: 17

**Comment by Artur-** [comment]
If there is a Spring Boot way of knowing https is used then the logic goes here https://github.com/vaadin/flow/blob/27263db06badad85eeb13be1672d78b488dadc2b/vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java#L92

**Comment by simasch** [comment]
@Artur- You could probably check for server.ssl properties
