### ISSUE TITLE
A lot of methods are shown as deprecated even if they are not removed in future releases

### ISSUE THREAD

**Issue by rappenze** [vaadin/flow#15528]
### Description of the bug

A lot of methods shows up as deprecated, but they are just moved around in the flow code basis but projects can use them in the future.

**Examples:**
`com.vaadin.flow.component.button.GeneratedVaadinButton.removeAll()`
-> As I understand this method can be used as well in the future on the Button class, but the type hierarchy will not contain the GeneratedVaadinButton class in the future. So basically when I use this method, I should not get a deprecated warning because the method is just moved around in vaadin but will be available in the future in my project.

`com.vaadin.flow.component.button.GeneratedVaadinButton.addThemeVariants(ButtonVariant...)`
This method was moved to HasThemeVariant class, and because the GeneratedVaadinButton class is deprecated, as well the method shows up as deprecated. But this method will exist in the future, so it should not show up as deprecated in my code.

### Expected behavior

Only really deprecated methods should show up as deprecated in my code base. Probably you should prefer not to use `@Deprecated` for planned internal changes. This is very confusing for the framework users as they cannot know which deprecations are now real and which are not.

### Minimal reproducible example

```
Button button = new Button();
button.addThemeVariants(ButtonVariant.LUMO_ICON);
```

### Versions

- Vaadin / Flow version: 23.3
- Java version: 11
- OS version: Windows
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable): Eclipse

**Comment by knoobie** [comment]
> As I understand this method can be used as well in the future on the Button class

That method is not to be used. 

> This method was moved to HasThemeVariant class, and because the GeneratedVaadinButton class is deprecated, as well the method shows up as deprecated.

This was fixed in 23.3.1

**Comment by rappenze** [comment]
Yes that looks much better now. Thanks for your answer and the fast fix.

**Comment by sveine** [comment]
Flow: 23.3.2:

![image](https://user-images.githubusercontent.com/367125/210505992-64766af2-6da3-44bf-891e-edf2f438ae75.png)

IntelliJ IDEA 2022.3 (Ultimate Edition)
Hilla: 23.3.2
Flow: 23.3.2
Java: JetBrains s.r.o. 17.0.4.1
OS: amd64 Windows 10 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Live reload: Java active (HotswapAgent): Front end active

**Comment by sveine** [comment]
Seems to be a issue in Kotlin only:

![image](https://user-images.githubusercontent.com/367125/210816337-329a1549-cfde-403c-82df-7e695f6713f3.png)

**Comment by sveine** [comment]
Seems to be a Kotlin issue: https://youtrack.jetbrains.com/issue/KT-47902/Do-not-propagate-method-deprecation-through-overrides
