### ISSUE TITLE
Add support index.tsx in addition to index.ts/js

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#15529]
### Describe your motivation

In TypeScript-based React apps, the convention is to use an `index.tsx` file. We want to keep Hilla as standard as possible and therefore want to support using JSX in the index file.

### Describe the solution you'd like
Update the bootstrap code to also consider `index.tsx` valid. 

### Describe alternatives you've considered
There are two alternatives: 
- Using an `index.ts` file and using `React.createElement`. This is what we do today. It looks outdated and is difficult to expand if you need more providers etc
- Loading a secondary file like `App.tsx` from the `index.ts` file where the actual app bootstrapping happens. This works, but does not follow React conventions.

### Additional context
-

**Comment by MarcinVaadin** [comment]
Maybe @cromoteca or other Hilla member could give some more information / suggestions on that?

**Comment by cromoteca** [comment]
It could be useful to provide a test example and add it to `TaskGenerateBootstrapTest`: it might be a bit complicated to test this as the whole generated code would only make sense in a Hilla+React application, so it's important to clearly define which output we expect from Flow. Is it enough to check for the existence of `index.tsx` and import it as `../index`?

**Comment by MarcinVaadin** [comment]
I've created quick PR for @cromoteca suggestion - https://github.com/vaadin/flow/pull/15621 - but without test. There is also `TaskGenerateIndexTs` which generates JS code - how does it compares to .tsx files?

**Comment by cromoteca** [comment]
I don't understand all the details there, but it seems to generate a default `index.ts` if no custom file is available. So `index.tsx` should be added to the files that to check for.
