### ISSUE TITLE
Regression: property synchronization events cause a value flush

### ISSUE THREAD

**Issue by vursen** [vaadin/flow#15615]
### Description of the bug

A regression introduced in https://github.com/vaadin/flow/issues/14090

When changing the value of NumberField from "" to "1" back and forth, the validation starts behaving weirdly (see the recording). As follows from the server logs, changing the value that way sometimes causes a value flush, but the flushed value is always the previous one.

In this specific case, the reason is the `has-input-value-changed` event that _results from the `@Synchronize` annotation_ and that _causes a value flush_. This event is fired before `value-changed` so an old value is flushed. 

### Recording

https://user-images.githubusercontent.com/5039436/210231161-171018ce-1833-4fb0-8239-d76f175bd9d2.mov

### Expected behavior

Property synchronization events should not be treated as triggered by the user and hence should not cause a value flush.

### Minimal reproducible example

```
NumberField numberField = new NumberField();
numberField.setValueChangeMode(ValueChangeMode.LAZY);
numberField.setValueChangeTimeout(5000);
numberField.addValueChangeListener(event -> {
    System.out.println("New value: " + event.getValue());
});
add(numberField);
```

### Versions

- Vaadin / Flow version: 24
- Java version: 17
- OS version: Mac OS

**Comment by mcollovati** [comment]
PR #15583 may fix this

**Comment by MarcinVaadin** [comment]
@vursen may you have a look at https://github.com/vaadin/flow/pull/15583 ?

**Comment by vursen** [comment]
> may you have a look at https://github.com/vaadin/flow/pull/15583 ?

Yes, I left my feedback there already.
