### ISSUE TITLE
Vaadin 14 Error when adding again removed component in attachList after refreshing

### ISSUE THREAD

**Issue by MBablinski** [vaadin/flow#15642]
### Description of the bug

i have a problem with adding again btn to layout after this layout is cleared from components. I'm gettin a error

>  Can't move a node from one state tree to another. If this is intentional, first remove the node from its current state tree by calling removeFromTree

for the line

`            actionsLay.add(testButton);`

after refreshing few times, and i don't get it why this error is showing. Below is very simple code to show this error when i'm adding and removing button for refresh action. In my app it is much more complicated code and i'm getting this error aswell after some page refresh and only for one component. I know that i can just add

`testButton.getElement().removeFromTree()`

but until I know why this error appears then I won't know when when i should add this line.

The error is thrown because

```
isOwnerAttached = ((StateTree) getOwner()).getRootNode()
                .isAttached();
```

in class StateNode in method doSetTree is true.

### Expected behavior

Component should be added again without error. When i`m doing code from attachList by button clickList and refreshing then every thing is working. Removed component before adding again to layout doesn't have any parent and it should exists in any other UI.

### Minimal reproducible example

```

@Route(value = "test")
@UIScope
@PreserveOnRefresh
public class testPanel extends Div {
    private static final long serialVersionUID = 5081824598131333345L;

    Button testButton;
    private HorizontalLayout actionsLay;
    private boolean addBtn = true;
    public testPanel() {
        testButton = new Button(new Icon(VaadinIcon.REFRESH));
        actionsLay = new HorizontalLayout();
        add(actionsLay);
    }

    @Override
    protected void onAttach(AttachEvent attachEvent) {
        if (addBtn) {
            actionsLay.removeAll();
            actionsLay.add(testButton);
            addBtn = false;
        } else {
            actionsLay.removeAll();
            addBtn = true;
        }

    }
}
```

### Versions

- Vaadin / Flow version: 14.8.14
- Java version: 8
- OS version: 
- Browser version (if applicable): 
- Application Server (if applicable):
- IDE (if applicable):

**Comment by MarcinVaadin** [comment]
First of all I would recommend rethinking `@PreserveOnRefresh` and `onAttach` together. Please check https://vaadin.com/docs/v14/flow/advanced/tutorial-preserving-state-on-refresh 

It has some limitations:

> The AttachEvent and DetachEvent events are also generated when a preserved component is moved to a new UI. This means, for instance, that your view component should expect multiple calls to onAttach and listeners registered through addAttachListener during its lifetime.

If usage of `onAttach` is required, adding simple flag to your logic helps:

```
if (!alreadyAttached) {
            if (addBtn) {
                actionsLay.removeAll();
                actionsLay.add(testButton);
                addBtn = false;
            } else {
                actionsLay.removeAll();
                addBtn = true;
            }
        }
alreadyAttached = true;
```

**Comment by mshabarov** [comment]
Closed because of no response within 2 weeks. Please comment on this issue if it's still valid for you, or open a new one.
