### ISSUE TITLE
Remove deprecated API and tools in Flow 24.0

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#15665]
Remove the deprecated API and tools in Flow in the next major version 24.0:

- [x] VaadinWebSecurityConfigurerAdapter
- [x] JavaScript execution APIs executeJavaScript() and callFunction() in Element and Page:
   - [x] com.vaadin.flow.dom.Element.callFunction​(String, Serializable...)
   - [x] com.vaadin.flow.dom.Element.executeJavaScript​(String, Serializable...)
   - [x] com.vaadin.flow.component.page.Page.executeJavaScript​(String, Serializable...)
- [x] ExecutionCanceler is replaced with PendingJavaScriptResult:
   - [x] com.vaadin.flow.component.page.Page.ExecutionCanceler
- [x] ~~PageConfigurator interface:~~ - not present already
   - [x] ~~com.vaadin.flow.server.PageConfigurator~~
- [x] setDataProvider() is now deprecated (in Grid, Select, RadioButtonGroup, CheckboxGroup, ListBox and ComboBox)
   - [x] com.vaadin.flow.component.checkbox.CheckboxGroup.setDataProvider​(DataProvider<T, ?>)
   - [x] com.vaadin.flow.component.combobox.ComboBoxBase.setDataProvider​(DataProvider<TItem, String>)
   - [x] com.vaadin.flow.component.grid.Grid.setDataProvider​(DataProvider<T, ?>)
   - [x] com.vaadin.flow.component.listbox.ListBoxBase.setDataProvider​(DataProvider<ITEM, ?>)
   - [x] com.vaadin.flow.component.radiobutton.RadioButtonGroup.setDataProvider​(DataProvider<T, ?>)
   - [x] com.vaadin.flow.component.select.Select.setDataProvider​(DataProvider<T, ?>)
- [x] ~~com.vaadin.flow.server.PageConfigurator~~
- [x] ~~com.vaadin.flow.data.renderer.TemplateRenderer~~
- [x] com.vaadin.flow.internal.BrowserLiveReloadAccess
- [x] ~~com.vaadin.flow.internal.nodefeature.PolymerServerEventHandlers~~ not to be removed in V24
- [x] com.vaadin.flow.server.BootstrapPageResponse
- [x] com.vaadin.flow.server.InitialPageSettings
- [x] COM.VAADIN.FLOW.SERVER.CONSTANTS.COMPILED_WEB_COMPONENTS_PATH
- [x] com.vaadin.flow.server.Constants.DISABLE_AUTOMATIC_SERVLET_REGISTRATION
- [x] com.vaadin.flow.server.Constants.I18N_PROVIDER
- [x] com.vaadin.flow.server.Constants.REQUIRE_HOME_NODE_EXECUTABLE
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_BROTLI
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_CLOSE_IDLE_SESSIONS
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_DEVMODE_ENABLE_LIVE_RELOAD
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_DEVMODE_OPTIMIZE_BUNDLE
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_DEVMODE_WEBPACK_ERROR_PATTERN
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_DEVMODE_WEBPACK_OPTIONS
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_DEVMODE_WEBPACK_SUCCESS_PATTERN
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_DEVMODE_WEBPACK_TIMEOUT
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_DISABLE_XSRF_PROTECTION
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_ENABLE_DEV_SERVER
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_ENABLE_PNPM
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_HEARTBEAT_INTERVAL
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_INITIAL_UIDL
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_JSBUNDLE
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_MAX_MESSAGE_SUSPEND_TIMEOUT
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_POLYFILLS
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_PRODUCTION_MODE
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_PUSH_MODE
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_PUSH_SUSPEND_TIMEOUT_LONGPOLLING
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_PUSH_URL
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_REQUEST_TIMING
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_REUSE_DEV_SERVER
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_SEND_URLS_AS_PARAMETERS
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_STATISTICS_JSON
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_SYNC_ID_CHECK
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_USE_V14_BOOTSTRAP
- [x] com.vaadin.flow.server.Constants.SERVLET_PARAMETER_WEB_COMPONENT_DISCONNECT
- [x] com.vaadin.flow.server.frontend.FrontendUtils.DEAULT_FLOW_RESOURCES_FOLDER
- [x] com.vaadin.flow.server.VaadinSession.UI_PARAMETER
- [x] com.vaadin.flow.data.provider.hierarchy.HasHierarchicalDataProvider.setDataProvider​(DataProvider<T, ?>)
- [x] com.vaadin.flow.data.renderer.LitRenderer.getEventHandlers()
- [x] com.vaadin.flow.data.renderer.LitRenderer.render​(Element, DataKeyMapper<SOURCE>, Element)
- [x] com.vaadin.flow.data.renderer.LitRenderer.withEventHandler​(String, SerializableConsumer<SOURCE>)
- [x] com.vaadin.flow.data.renderer.Renderer.getEventHandlers()
- [x] com.vaadin.flow.data.renderer.Renderer.getValueProviders()
- [x] com.vaadin.flow.data.renderer.Renderer.render​(Element, DataKeyMapper<SOURCE>, Element)
- [x] com.vaadin.flow.data.renderer.Renderer.setEventHandler​(String, SerializableConsumer<SOURCE>)
- [x] com.vaadin.flow.data.renderer.Renderer.setProperty​(String, ValueProvider<SOURCE, ?>)
- [x] com.vaadin.flow.data.renderer.Rendering.getTemplateElement()
- [x] com.vaadin.flow.data.selection.MultiSelectionEvent.getNewSelection()
- [x] com.vaadin.flow.di.Instantiator.getBootstrapListeners​(Stream<BootstrapListener>)
- [x] com.vaadin.flow.di.Instantiator.init​(VaadinService)
- [x] com.vaadin.flow.internal.nodefeature.AbstractServerHandlers.getHandlerAnnotation()
- [x] com.vaadin.flow.router.BeforeEvent.getForwardTargetParameters()
- [x] com.vaadin.flow.router.BeforeEvent.getRerouteTargetParameters()
- [x] com.vaadin.flow.router.BeforeEvent.getRouteTargetType()
- [x] com.vaadin.flow.router.internal.AbstractRouteRegistry.getRouteLayouts​(String, Class<? extends Component>)
- [x] com.vaadin.flow.router.internal.ConfiguredRoutes.getParentLayouts​(String, Class<? extends Component>)
- [x] com.vaadin.flow.router.internal.RouteUtil.getParentLayouts​(Class<?>, String)
- [x] com.vaadin.flow.router.internal.RouteUtil.getRoutePath​(Class<?>, Route)
- [x] com.vaadin.flow.router.internal.RouteUtil.getTopParentLayout​(Class<?>, String)
- [x] com.vaadin.flow.router.internal.RouteUtil.resolve​(Class<?>, Route)
- [x] com.vaadin.flow.router.NavigationState.setUrlParameters​(List<String>)
- [x] com.vaadin.flow.router.NavigationStateBuilder.withTarget​(Class<? extends Component>, List<String>)
- [x] com.vaadin.flow.router.RouteBaseData.getParameters()
- [x] com.vaadin.flow.router.RouteBaseData.getUrl()
- [x] com.vaadin.flow.router.RouteConfiguration.isPathRegistered​(String)
- [x] com.vaadin.flow.router.Router.initializeUI​(UI, VaadinRequest)
- [x] com.vaadin.flow.server.AppShellRegistry.isShell​(Class<?>)
- [x] com.vaadin.flow.server.communication.StreamReceiverHandler.getContentLength​(VaadinRequest)
- [x] com.vaadin.flow.server.InlineTargets.addInlineDependency​(Inline, VaadinRequest)
- [x] com.vaadin.flow.server.PageConfigurator.configurePage​(InitialPageSettings)
- [x] com.vaadin.flow.server.RouteRegistry.getRouteLayouts​(String, Class<? extends Component>)
- [x] com.vaadin.flow.server.ServiceInitEvent.addBootstrapListener​(BootstrapListener)
- [x] com.vaadin.flow.server.ServiceInitEvent.getAddedBootstrapListeners()
- [x] com.vaadin.flow.server.SessionRouteRegistry.getRouteLayouts​(String, Class<? extends Component>)
- [x] com.vaadin.flow.server.startup.VaadinAppShellInitializer.init​(Set<Class<?>>, ServletContext)
- [x] com.vaadin.flow.server.VaadinService.modifyBootstrapPage​(BootstrapPageResponse)
- [x] com.vaadin.flow.data.renderer.LocalDateRenderer​(ValueProvider<SOURCE, LocalDate>, DateTimeFormatter)
- [x] com.vaadin.flow.data.renderer.LocalDateTimeRenderer​(ValueProvider<SOURCE, LocalDateTime>, DateTimeFormatter)
- [x] com.vaadin.flow.data.renderer.Renderer​(String)
- [x] com.vaadin.flow.server.frontend.FrontendTools​(String, Supplier<String>)

Afterwards:
- [x] Document the above removals in the V24 upgrade instruction: https://vaadin.com/docs/latest/upgrading/V23-V24-steps
- [x] Double check starter projects to not use the removed API

**Comment by MarcinVaadin** [comment]
> setDataProvider() is now deprecated (in Grid, Select, RadioButtonGroup, CheckboxGroup, ListBox and ComboBox)
>  com.vaadin.flow.component.checkbox.CheckboxGroup.setDataProvider​(DataProvider<T, ?>)
>  com.vaadin.flow.component.combobox.ComboBoxBase.setDataProvider​(DataProvider<TItem, String>)
>  com.vaadin.flow.component.grid.Grid.setDataProvider​(DataProvider<T, ?>)
>  com.vaadin.flow.component.listbox.ListBoxBase.setDataProvider​(DataProvider<ITEM, ?>)
>  com.vaadin.flow.component.radiobutton.RadioButtonGroup.setDataProvider​(DataProvider<T, ?>)
>  com.vaadin.flow.component.select.Select.setDataProvider​(DataProvider<T, ?>)
> 
> com.vaadin.flow.data.renderer.LitRenderer.getEventHandlers()
>  com.vaadin.flow.data.renderer.LitRenderer.render​(Element, DataKeyMapper, Element)
>  com.vaadin.flow.data.renderer.LitRenderer.withEventHandler​(String, SerializableConsumer)
>  com.vaadin.flow.data.renderer.Renderer.getEventHandlers()
>  com.vaadin.flow.data.renderer.Renderer.getValueProviders()
>  com.vaadin.flow.data.renderer.Renderer.render​(Element, DataKeyMapper, Element)
>  com.vaadin.flow.data.renderer.Renderer.setEventHandler​(String, SerializableConsumer)
>  com.vaadin.flow.data.renderer.Renderer.setProperty​(String, ValueProvider<SOURCE, ?>)
>  com.vaadin.flow.data.renderer.Rendering.getTemplateElement()
> 
> com.vaadin.flow.data.renderer.LocalDateRenderer​(ValueProvider<SOURCE, LocalDate>, DateTimeFormatter)
>  com.vaadin.flow.data.renderer.LocalDateTimeRenderer​(ValueProvider<SOURCE, LocalDateTime>, DateTimeFormatter)
>  com.vaadin.flow.data.renderer.Renderer​(String)

Are part of flow-components and will be removed as part of https://github.com/vaadin/flow-components/issues/4536

**Comment by MarcinVaadin** [comment]
Projects to be checked after removing deprecated code:
- [ ] cdi
- [ ] spring
- [ ] designer-internal
- [ ] multiplatform-runtime-internal
- [ ] portlet
- [ ] osgi
- [ ] quarkus
- [ ] testbench
- [ ] testbench-demo
- [ ] addressbook-portlet
- [ ] component-starter-flow
- [ ] addon-starter-flow
- [ ] base-starter-flow-osgi
- [ ] base-starter-flow-portlet
- [ ] base-starter-gradle
- [ ] base-starter-spring-gradle
- [ ] base-starter-flow-quarkus
- [ ] vaadin-flow-karaf-example
- [ ] skeleton-starter-flow
- [ ] skeleton-starter-flow-cdi
- [ ] skeleton-starter-flow-spring
- [ ] license-checker-vaadin10

**Comment by vaithu** [comment]
> * V24 upgrade instruction

Please let me know where I can find the equivalency for this
![image](https://user-images.githubusercontent.com/35440074/235073604-c8f02a66-fe7f-4e78-af83-dc97fffc32e8.png)

I was told ```setItems``` is the equivalent but I do not see anything directly matches with the deprecated setDataProvider

**Comment by vaithu** [comment]
Also this page https://vaadin.com/docs/latest/upgrading/V23-V24-steps is missing. Getting 404 Not Found error

**Comment by jouni** [comment]
Fixed the link in the description (to point to vaadin.com/docs/latest/upgrading)

**Comment by mshabarov** [comment]
> > * V24 upgrade instruction
> 
> Please let me know where I can find the equivalency for this ![image](https://user-images.githubusercontent.com/35440074/235073604-c8f02a66-fe7f-4e78-af83-dc97fffc32e8.png)
> 
> I was told `setItems` is the equivalent but I do not see anything directly matches with the deprecated setDataProvider

@vaithu thanks for the question. Could you please describe what is your case? Do you use a `DataProvider` with a configured filter? I noticed that only for `Grid` we preserved `setDataProvider` as `setItems` cannot take `DataProvider<T, F>` if `F` is not `Void`. Seems like we miss that fact and changed `public` to `private` for `ComboBox`, which can be used with a filterable data provider as well. For other components, I think that `setDataProvider` can be replaced by `setItems` easily, because they are in memory data providers. So need you case to understand the problem better. Thanks!

**Comment by mshabarov** [comment]
@vaithu thanks for the example. So the component is `ListBox`. Your data provider has a generic type for filter (second type, which is a wildcard here): `DatastoreDataProvider<ITEM, ?>`. Do you use `.setFilter()` method of this data provider anywhere? If no, then you can replace the second type with `Void` and then you can use one of the existing `setItems` methods. If you do, then my question is what is the type of this data provider - in memory or callback (what is the extended class for it and what does `isInMemory()` returns) ?

**Comment by vaithu** [comment]
No. I do not see any ``setFilter`` there. ``DatastoreDataProvider<ITEM, ?>`` is extending vaadin interface ``DataProvider<T, F>``.
Also there is no ``isInMemory() ``.

**Comment by vaithu** [comment]
Thanks. That will help a lot because the previous versions heavily depends on this and there are 3rd party enhancements relies on this DataProvider. Also, just an idea/suggestion that if there is a way to redirect setDataProvider to setItems internally with same features/parameters that would be awesome. User will get same performance advantages with same setDataprovider
