### ISSUE TITLE
Frontend folder it's still generated when custom frontend folder is defined

### ISSUE THREAD

**Issue by paodb** [vaadin/flow#15670]
### Description of the bug

In Vaadin 23.3.3, when using a custom frontend folder, the generated frontend files go to the /customFolder as expected
but the frontend folder is generated (/frontend/generated/) to the project root as well. 

![frontend-folder-dev](https://user-images.githubusercontent.com/30666649/211835034-85b125f0-8259-44ea-90c8-7c4fd093d5ab.png)

* This seems to happen only in dev mode. 
* This doesn't happen on Vaadin 23.2.x (tested it in latest 23.2.13).

### Expected behavior

When custom frontend folder is defined, not extra frontend folder should be generated.

### Minimal reproducible example

Download and mvn jetty:run [custom-frontend-23.3.3.zip](https://github.com/vaadin/flow/files/10393287/custom-frontend-23.3.3.zip)

In this sample project, frontend folder was renamed to customFolder and in the pom.xml the configuration for 'vaadin-maven-plugin' was added (in both build and profile sections)  like this:

`<configuration>
      <frontendDirectory>${project.basedir}/customFolder</frontendDirectory
</configuration>`

### Versions

- Vaadin version: 23.3.3
- Java version: 11

**Comment by MarcinVaadin** [comment]
The issue was assigned to a developer and is currently being investigated

**Comment by MarcinVaadin** [comment]
The files you see in generated _frontend_ directory are flow generated files. Please use `generatedTsFolder` configuration property to set same output directory as for your frontend files.
```
<configuration>
   <frontendDirectory>${project.basedir}/customFolder</frontendDirectory>
   <generatedTsFolder>${project.basedir}/customFolder/generated</generatedTsFolder>
</configuration>
```
if you wish to overwrite it.

See https://vaadin.com/docs/latest/configuration/maven#properties for details.

**Comment by paodb** [comment]
@MarcinVaadin just tested it and works okay for me. I was not aware of that property. I will share it with the customer that asked for the prioritization and once I get confirmation from them I will close the ticket.

**Comment by paodb** [comment]
Closing the ticket as I've got confirmation that the issue is solved.
