### ISSUE TITLE
When optimizing my application for performance, I want to be able to bundle the resources in a single file and use it without Java code modifications.

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#1570]
To better explain this ticket lets assume a class with 3 resources:

```
@HTMLImport("1.html")
@HTMLImport("2.html")
@HTMLImport("3.html")
public class MyView ...
```

Those are treated independently by the framework - they will be added at the `head` of the page as declared. But when bundling the application, only one file is created (let's say: `bundle.html`), and the framework needs to understand how to import that bundle instead of the three separate files.

One way of achieving this is to declare the class to use the bundle instead of the three files:

```
@HTMLImport("bundle.html")
public class MyView ...
```

... but that's not ideal, because when using bundling, the developer must run the Polymer CLI command `polymer build` every time a resource is changed, and depending on the size of the project, that can take several minutes, hurting the productivity.

So the framework should be able to detect when to use the bundle, and when to use the individual files, without requiring code changes. Using environment variables (or reusing the `prodMode` setting from Vaadin) is one way to detect that.

**Comment by Legioth** [comment]
Can this one be closed?

**Comment by pleku** [comment]
Yes, it's done.
