### ISSUE TITLE
Enable running `npm ci` instead of `npm install`

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#15710]
### Describe your motivation

To get a repeatable build that uses the exact package-lock version installation of npm packages should be done with the clean-install command `npm ci` instead of `npm install` which is used now.

### Describe the solution you'd like

There should be a property (`vaadin.npm.clean.install`?) that can be given on the CI server that makes npm installation use
`npm ci` (or for pnpm `pnpm install --froze-lockfile`) for npm package installation.

### Additional context

Where as `npm ci` removes node_modules before installation `pnpm install --frozen-lockfile` does not remove the folder.

**Comment by mshabarov** [comment]
Targets to Vaadin 24.1.

**Comment by knoobie** [comment]
Duplicate of https://github.com/vaadin/flow/issues/15579?

**Comment by caalador** [comment]
Closing issue as duplicate of #15579 
Thanks @knoobie ... can't remember even 3 weeks back it seems.
