### ISSUE TITLE
Plugins should have the frontend.hotdeploy configuration and propagate that to build-info

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#15765]
Maven and Gradle plugin should have the `frontend.hotdeploy` flag as a configuration that would be propagated to the `flow-build-info.json` file for development runtime configuration.

**Comment by Artur-** [comment]
Why?

**Comment by caalador** [comment]
`How do I disable the express build mode?`
SpringBoot project into `application.properties`, others - ??? - profit.
System property into build file server plugin or on command line is perhaps a bit confusing and you don't get autocomplete.
