### ISSUE TITLE
PiT 24.0: jakarta and javax validation constrain messages differ

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#15763]
### Description of the bug

When migrating bakery from 23.3 to 24.4 we saw that tests checking validation constrain messages fail.

```
ERROR] testTextFieldValidation[ANY_Chrome_](com.vaadin.starter.bakery.testbench.StorefrontViewIT)  Time elapsed: 14.729 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[maximum length is 255 characters]> but was:<[size must be between 0 and 255]>
```

### Expected behavior

This kind of errors are documented

### Minimal reproducible example

```
git clone https://github.com/vaadin/bakery-app-starter-flow-spring.git
cd bakery-app-starter-flow-spring
git checkout v24
mvn verify -Pit,production -Dit.test=StorefrontViewIT
```

### Versions

- Vaadin / Flow version: 24.0.0.alpha9

**Comment by mshabarov** [comment]
I'm not sure what is a problem here. In bakery we have `Assert.assertTrue(msg.matches("(maximum length is 255 characters|size must be between 0 and 255)"));` so I expect this test would pass with what the Jakarta 10 gives.

**Comment by mshabarov** [comment]
@manolo the expected message has been updated in https://github.com/vaadin/bakery-app-starter-flow-spring/commit/55143d36ea9839d0b60ab95c4fd2454fdc8ed2f2 . So is this issue valid still?

**Comment by manolo** [comment]
@mshabarov has this issue been documented?

**Comment by mshabarov** [comment]
Not yet apparently, I would mention this in the TextField API.

**Comment by manolo** [comment]
> so I expect this test would pass with what the Jakarta 10 gives

Actually the right way for fixing the test is not the change I did in [v23](https://github.com/vaadin/bakery-app-starter-flow-spring/commit/efe298517315488ef3fce4083bca83a9b38edfb0) in sources, but the change in this [PR](https://github.com/vaadin/bakery-app-starter-flow-spring/commit/e291ce8e58fbd0becdfd6cb39599f5b48b7d0a7d#diff-76c2e7a6131682b5f1d3863e69fc1e4559027743b49aae38c9e51cbcdac6b221L9)  in the properties file.

Closing this Issue then
