### ISSUE TITLE
Exception using JNA/Oshi libraries with 23.3 due to vaadin-license-checker

### ISSUE THREAD

**Issue by INPUTsys-Chris** [vaadin/flow#15782]
### Description of the bug

Exception occurs in projects using JNA or Oshi (which uses JNA internally).
It seems the license checker ships fixed versions of that projects in its jar.

```
Caused by: java.lang.NoSuchMethodError: 'void com.sun.jna.Memory.close()'
	at oshi.util.Util.freeMemory(Util.java:83)
	at oshi.jna.Struct$CloseableSystemInfo.close(Struct.java:166)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.queryProcessorId(WindowsCentralProcessor.java:129)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractCentralProcessor.getProcessorIdentifier(AbstractCentralProcessor.java:107)
	at org.vaadin.example.MainView.<init>(MainView.java:19)
	... 77 more
```

### Expected behavior

Developers should be allowed to use any versions/combinations of Oshi and JNA.

### Minimal reproducible example

Download 23 Plain Java starter: https://github.com/vaadin/skeleton-starter-flow/archive/v23.zip

Add this to main view:

```
        SystemInfo si = new SystemInfo();
        HardwareAbstractionLayer hal = si.getHardware();
        String microarchitecture = hal.getProcessor().getProcessorIdentifier().getMicroarchitecture();
        add(new Text("Microarch: " + microarchitecture));
```

Add current Oshi dependency in pom:

        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>6.4.0</version>
        </dependency>

Run with `mvn jetty:run`

Navigate to http://localhost:8080/

### Versions

- Vaadin / Flow version: 23.3
- Java version: 17
- OS version: Win

**Comment by Artur-** [comment]
Sounds like a standard dependency conflict. If you use a newer oshi-core that depends on a newer jna, you need to specify the version for jna also

**Comment by INPUTsys-Chris** [comment]
dependency:tree is somewhat misleading here, Oshi imports JNA 5.13:

```
[INFO] +- com.github.oshi:oshi-core:jar:6.4.0:compile
[INFO] |  +- net.java.dev.jna:jna:jar:5.11.0:compile
[INFO] |  +- net.java.dev.jna:jna-platform:jar:5.11.0:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.36:compile

[INFO] |     \- com.vaadin:license-checker:jar:1.11.2:compile
[INFO] |        +- com.nimbusds:nimbus-jose-jwt:jar:9.23:compile
[INFO] |        \- org.lucee:jcip-annotations:jar:1.0.0:compile
```

I was mislead

**Comment by INPUTsys-Chris** [comment]
Looks like Oshi doesn't define the JNA version. Opened an issue there:

https://github.com/oshi/oshi/issues/2300

**Comment by Artur-** [comment]
Updated the license checker to use the lastest oshi-core and jna. Not much more we can do here

**Comment by INPUTsys-Chris** [comment]
@Artur- thank you

**Comment by dbwiddis** [comment]
OSHI maintainer here, just leaving a bread crumb trail for anyone who stumbles on this issue.
 - Root cause is bug in maven that does not recognize versions in `<dependencyManagement>` in transitive dependencies: https://issues.apache.org/jira/browse/MNG-5761
 - I'll be updating OSHI to explicitly declare version in `<dependencies>` section to work around this in the future
