### ISSUE TITLE
Allow disabling the ViewAccessChecker even when extending VaadinWebSecurity

### ISSUE THREAD

**Issue by ILikePhysics** [vaadin/flow#15818]
### Describe your motivation

For my application I am using more a granular permission based security (using keycloak) and for that I developed my own class similar to `ViewAccessChecker` with my own annotation to protect my views with granular permissions (resource:scope).

Therefore, the `ViewAccessChecker` is no longer useful in this case. According to this previously resolved issue, [#11231](https://github.com/vaadin/flow/issues/11231), this class takes a boolean value in its constructor to disable it.

One oddity I found is that `ViewAccessChecker` is created enabled by default, and it's also enabled again in `VaadinWebSecurity`  with `ViewAccessChecker.enable()`

### Describe the solution you'd like

I would like to be able to disable this class while taking advantage of VaadinWebSecurity.
Maybe expose a method `setEnable(boolean)` so we can disable it manually. It would allow more use cases without impacting anything else.
Or, remove the line `viewAccessChecker.enable()` in `VaadinWebSecurity`.

### Describe alternatives you've considered

I tried to inject my own version of bean `ViewAccessChecker` with the enable field set to false by exposing my own instance:
```kotlin
@Bean
@Primary
fun viewAccessCheckerOverride(): ViewAccessChecker {
    return ViewAccessChecker(false)
}
```
The problem is that it is re-enabled by `VaadinWebSecurity` (the oddity described above). 

### Versions
I am currently developing with Vaadin 24.0.0.alpha10 and Spring Boot 3.0.2

**Comment by knoobie** [comment]
You could try to expose a bean based AccessAnnotationChecker which is internally used by your mentioned bean.

**Comment by ILikePhysics** [comment]
I also went that path but the logic in `ViewAccessChecker` is incompatible with what I am trying to do.
Also, you comment made me realize I can do this:

```kotlin
class ViewAccessCheckerDisabler : ViewAccessChecker(false) {
        override fun beforeEnter(beforeEnterEvent: BeforeEnterEvent) {
            return
        }
    }

    @Bean
    @Primary
    open fun viewAccessCheckerOverride() : ViewAccessChecker {
        return ViewAccessCheckerDisabler()
    }
```
I just find it's an ugly hack to disable such a simple thing.
