### ISSUE TITLE
Please do not remove Feature Flag com.vaadin.experimental.webpackForFrontendBuild before Vite has fixed an important bug

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow#15832]
### Describe your motivation

A customer is using a component, namely 'devextreme-scheduler' which is missing nested dependencies when Vite is doing the Vaadin production mode build.

### Describe the solution you'd like
Do not remove the option to use the webpack frontend optimizer until a version of Vita is included in Vaadin that has this bug here fixed:
https://github.com/vitejs/vite/issues/5688

### Describe alternatives you've considered

Maybe use the work-around in
https://github.com/vitejs/vite/issues/4312

### Additional context

Please get in touch with me when you think Vite have fixed this, so that I can double-check with customer code before the feature flag is being removed.

**Comment by Artur-** [comment]
The flag has been removed in V24, it will not be removed from V23
