### ISSUE TITLE
Cannot assign to import "idMapping": getting this error on Vite but not on Webpack

### ISSUE THREAD

**Issue by alirazashopdev** [vaadin/flow#15864]
### Description of the bug

I am installing Vite on an existing project and getting this error with a changed value. There are tens of files.

Cannot assign to import "idMapping"

    src/libs/utils/library/react-blockly/generator/generator.js:866:14:
      866 │       Blockly.idMapping = []
          ╵               ~~~~~~~~~

  Imports are immutable in JavaScript. To modify the value of this import, you must export a setter
  function in the imported file (e.g. "setIdMapping") and then import and call that function here
  instead.

### Expected behavior

It should work as on the WEBPACK CONFIG. Is there a way to get rid of this error?

### Minimal reproducible example

IF directly mutating Blockly on React app with Vite.

### Versions

- Vaadin / Flow version:
- Node version: 14.20.1
- OS version: Ubuntu
- Browser version (if applicable): Chrome Latest
- Application Server (if applicable):
- IDE (if applicable):

**Comment by Artur-** [comment]
Can you create a small example project for this e.g. based on a start.vaadin.com project?

**Comment by mshabarov** [comment]
Closed because of no reply for more than 2 weeks. @alirazashopdev please comment here or open a new ticket if you have still this problem. If so, please give us an example project how to reproduce your case.
