### ISSUE TITLE
vcf-nav is added in package.json

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow#15866]
### Description of the bug

In Vaadin 24.0.beta1, the package.json contains:
"@vaadin-component-factory/vcf-nav": "1.0.6",

Even if the project is not using it.

### Expected behavior

vcf-nav shouldn't be there.

### Minimal reproducible example

You can see the pull request between the project downloaded and after a production build.
https://github.com/jcgueriaud1/app-vcf/pull/1/files

### Versions

- Vaadin / Flow version:24.0.beta1
- Java version:17

**Comment by Artur-** [comment]
Fixedin https://github.com/vaadin/platform/pull/3764
