### ISSUE TITLE
Favicon does not work

### ISSUE THREAD

**Issue by FelixGaebler** [vaadin/flow#15886]
### Description

When creating a project via https://start.vaadin.com/app an index.html is automatically created in the frontend/ folder, which does not load a favicon. In previous versions the favicon was automatically loaded from the path META-INF/resources/icons/icon.png. The icon is also present in the download but is not loaded.

### Expected outcome

Favicon should be loaded on page

### Minimal reproducible example

https://start.vaadin.com/app

### Steps to reproduce

1. Download example project from https://start.vaadin.com/app
2. Launch project
3. Open browser
4. No favicon is shown

### Environment

Vaadin version(s): 23.3.6
OS: Windows

### Browsers

Chrome, Edge

**Comment by Artur-** [comment]
If you add the `@PWA` annotation, the icon defined using the `iconPath` attribute will be used (default is `icons/icon.png`)

**Comment by mshabarov** [comment]
@FelixGaebler this issue is closed, because no reply for more than 2 weeks. Please let us know if the issue is still present for you (comment here or open a new issue).
