### ISSUE TITLE
Express mode build not triggered when adding index.ts

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#15883]
### Description of the bug

When I add a custom `frontend/index.ts` to a new project, it is not taken into use.

### Expected behavior

The file is taken into use

### Minimal reproducible example

```
npx @vaadin/cli init --next indexts
cd indexts
npx upgrade-vaadin 24.0-SNAPSHOT
echo "window.alert('hello');" > frontend/index.ts
mvn
```

### Versions

- Vaadin / Flow version: 24.0-SNAPSHOT

**Comment by caalador** [comment]
We only check for the imports named in `generated-flow-imports.js` which only covers jar-resources and npm files and from those only files in jar-resources are checked for content changes.

**Comment by Artur-** [comment]
What makes this an enhancement and not a bug? You are supposed to be able to customize index.ts by copying it to the frontend folder

**Comment by caalador** [comment]
It's an enhancement in that it was never a feature that has been implemented or talked about.
