### ISSUE TITLE
Auto-optimize the initial bundle

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#15930]
### Describe your motivation

You want an application to start as quickly as possible. A large part of the startup time is caused by loading the initial JS bundle with components and other frontend code.

### Describe the solution you'd like

Today Flow scans through all entry points (routes, exported web components) and gathers all frontend imports into `target/frontend/generated-flow-imports.js`. This then forms the initial (and only) JS bundle.

Instead of doing this, we should gather the imports separately for each entry point, e.g. into
`frontend/generated/flow/entrypoints/route-hello.ts`
`frontend/generated/flow/entrypoints/route-about.ts`

Then we generate the main JS file, e.g. `frontend/generated/flow/entrypoint.js` with dynamic imports for all the other generated files + the logic so we can ensure the correct bundle is loaded when navigating to a given route or loading a given exported web component.

Additionally we guess which the first route is (`/login` is a good guess if it exists, otherwise `""`) and allow the user to override this. The first route file is loaded eagerly.

**Comment by Legioth** [comment]
Is this a "duplicate" of https://github.com/vaadin/flow/issues/5537 that is just expressed more from the user's point of view?

> `/login` is a good guess if it exists, otherwise `""`

I would claim that if `/login` exists, then both  `/login` and `""` should by default be included in the initial load. This is because of all the applications where you stay logged in "forever".

**Comment by Artur-** [comment]
Let's keep the discussion in #5537 as this is almost the same
