### ISSUE TITLE
Unclear when to use vaadin. -prefix for system properties

### ISSUE THREAD

**Issue by tepi** [vaadin/flow#15969]
### Description of the bug

https://vaadin.com/docs/latest/configuration/npm-pnpm states the following:

"Vaadin also supports using [pnpm](https://pnpm.io/) (also known as performant npm). To switch to pnpm, you can set the `vaadin.pnpm.enable` system property to `true`."

However, when running this: `mvn jetty:run -Pproduction -Dvaadin.pnpm.enable=true`, npm will be used.

When running `mvn jetty:run -Pproduction -Dpnpm.enable=true`, pnpm will be used.

### Expected behavior

As per the documentation, I expect the vaadin. -prefixed system property would work in the above case.

### Minimal reproducible example

Just run any starter with 24.1-SNAPSHOT with the commands mentioned above.

### Versions

- Vaadin / Flow version: 24.1-SNAPSHOT

**Comment by Artur-** [comment]
All system properties are supposed to start with `vaadin.` to avoid conflicts with other libraries and frameworks. Thus pnpm works incorrectly if it works as described above

**Comment by tepi** [comment]
The difference might be that when system properties are read through `com.vaadin.flow.server.AbstractPropertyConfiguration#getSystemProperty` it adds the "vaadin." prefix to the property name, but I believe in the above case the property is read directly by the maven plugin's `FlowModeAbstractMojo`, and I don't find similar logic there.

**Comment by tepi** [comment]
`vaadin.` -prefix has been added to properties which are only used for the plugin configuration, so closing this ticket as fixed.
