### ISSUE TITLE
Invalid JSON response from server when redirect to another vaadin application

### ISSUE THREAD

**Issue by Viktoriya-dem** [vaadin/flow#15985]
### Description of the bug

Hi. 
We have two application: first on Vaadin 14, second on Vaadin 23, nginx between them. Log in is in first application, when we go to second application, we send credentials in headers. When we log out from first application, and try to open some tab in second application, we send to second application response with status 302 and put in header location url login page of first application. After that no redirect performed, we take "Invalid JSON response from server ..." and in error message there is our html login page, on which we try to redirect.
How can we handle this error?

![image](https://user-images.githubusercontent.com/72566689/220596203-21bb31b4-757f-485d-94b2-04cf79335913.png)

### Expected behavior

Redirect on login page (which url is setting in header location) without errors

### Minimal reproducible example

If user is null (log out from first application) :
        httpServerResponse.putHeader("location", "example/login"));
        httpServerResponse.setStatusCode(302);
        httpServerResponse.end();

### Versions

- Vaadin / Flow version: 14.9.6 (first application) and 23.3.6 (second application)
- Java version: 8 (first application) and 11 (second application)

**Comment by mcollovati** [comment]
My guess is that the redirect is sent to a XmlHttpRequest issued by Vaadin, so the client follows the redirect, but then it fails because it is expecting JSON contents.
You can try to add the Vaadin refresh token to the body of the response
```
Vaadin-Refresh: example/login
```

Can you elaborate the mechanism you are using to issue the redirect?
Looking at the code in the "Minimal reproducible example", it seems like you are not using Servlet API.
It seems more like Vert.x API or some other technology

**Comment by Aleksey2093** [comment]
> Can you elaborate the mechanism you are using to issue the redirect?
> Looking at the code in the "Minimal reproducible example", it seems like you are not using Servlet API.
> It seems more like Vert.x API or some other technology

Between vaadin and the browser is a custom nginx on vertx , which is responsible for the session and authorization check. It is this layer (custom nginx) that responds with 302 status.

**Comment by knoobie** [comment]
That mentioned html page has to contain the snippet provided by Marco, otherwise this error is thrown.

**Comment by Viktoriya-dem** [comment]
Thanks for your help.
Can you tell if there is documentation about Vaadin-Refresh?
What is the best way to add "Vaadin-Refresh: example/login" to a vaadin page? Use @HtmlImport? Add it as a property to the layout?

**Comment by knoobie** [comment]
It's mentioned in the JavaDocs of https://github.com/vaadin/flow/blob/7eb73618ac2a45e017672ad7370e90b830c35022/flow-client/src/main/java/com/vaadin/client/communication/ConnectionStateHandler.java#L54 

One solution could be to customize the index.html of that second services to contain this information for the initial request.

**Comment by Viktoriya-dem** [comment]
Thanks for your help.
We add Vaadin-Refresh by implementing VaadinServiceInitListener, issue solved.
