### ISSUE TITLE
Production build is not reproducible with the new dev bundle mode

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#16041]
### Description of the bug

When you use frontend hotdeploy mode, you have a `package.json` and `package-lock.json` in the project and they are always up to date. Assuming you commit `package-lock.json` to the repository your builds will be reproducible, especially when using `npm ci` instead of `npm install`(#15986). Otherwise, you might get newer frontend dependencies than originally used and they might be incompatible or have new bugs.

When you are using dev bundle mode, you have no package.json and the package-lock.json used to create the bundle (both for the default and an app specific) is not available for the production build. It might always pick up newer versions which can break the build.

### Expected behavior

When using dev bundle mode, the production build should use the same package-lock.json as used when building the dev bundle. This will ensure reproducible builds and that the production build works like development mode.

For this to work, `package-lock.json` (and maybe `package.json`) should be added to the bundle folder (default and app bundle) after the build is complete. A production build should use this `package-lock.json` when performing ´npm install` or `npm ci`.

At the same time solving this would solve the problem that `npm install` takes a long time for production builds as `package-lock.json` typically is not in the repository.

### Minimal reproducible example

```
npx @vaadin/cli init --next hello
cd hello
mvn clean vaadin:clean-frontend install -Pproduction

# Store the bundle
cp -R target/classes/META-INF/VAADIN/webapp/ webapp-1

# Remove all created files
mvn clean vaadin:clean-frontend

# Wait for a new dependency to be released

mvn clean vaadin:clean-frontend install -Pproduction
# Store the bundle
cp -R target/classes/META-INF/VAADIN/webapp/ webapp-2

# Compare
diff -r webapp-1 webapp-2
```

### Versions

- Vaadin version: 24 beta 5

**Comment by mshabarov** [comment]
This would mean that `vaadin-dev-bundle` dependency should be added to the classpath even when the app is being built for production. What if Flow would always place `package-lock.json` into `src/main/dev-bundle` even if the default bundle is used? This is not a good solution though, since the dev-bundle then should be committed always.

**Comment by Artur-** [comment]
It does not need to be on the build path when building but the Maven plugin needs to be able to access it. A Maven plugin can dynamically resolve an import I think? It only needs it to be able to extract that one file

**Comment by Artur-** [comment]
This is not really resolved. The basic case of creating a project and building for production does not use the lock file
```
npx @vaadin/cli init hello
cd hello
mvn install -Pproduction
```

results in
```
[INFO] using '/.../node/v18.16.0/bin/npm --no-update-notifier --no-audit --scripts-prepend-node-path=true --ignore-scripts install' for frontend package installation
[WARNING] package-lock.json is missing from this project. This may cause the npm package installation to take several minutes. It is recommended to keep the package-lock.json file persistently in your project. Please stand by...
```

**Comment by Artur-** [comment]
Apparently this is because the plugin cannot find the default dev bundle as the production profile excludes it. Maybe the plugin can depend on it so it is always available during the production build but still not included in the resulting jar/war
