### ISSUE TITLE
Symlink folder deleted failure for Flow 23.3 branch

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#16089]
### Description of the bug

Symlink folder is deleted after the related folder is deleted, which is shown in the broken test 
```
FrontendUtilsTest.symlinkByNpm_deleteDirectory_doesNotDeleteSymlinkFolderFiles:424
```
for the Flow 23.3 branch. See the validation results, e.g. for this pull request https://github.com/vaadin/flow/pull/15965.
Test fix also doesn't work, see https://github.com/vaadin/flow/pull/16025.

The problem with symlinks was caused by Node version upgrade: `Upgrade default Node to 18.14.1 (#15931)`

This block pull requests to be merged into 23.3.

### Expected behavior

Test passes.

### Minimal reproducible example

Run FrontendUtilsTest.symlinkByNpm_deleteDirectory_doesNotDeleteSymlinkFolderFiles in 23.3 branch

### Versions

- Flow version: 23.3.

**Comment by Artur-** [comment]
#16025 solves this
