### ISSUE TITLE
V24: error during dev-bundle build in add-on project with css file in src/main/resources

### ISSUE THREAD

**Issue by taefi** [vaadin/flow#16109]
### Description of the bug

For Vaadin add-on components, it is normal to have the styles and other resources in `src/main/resources/META-INF/resources/frontend` instead of the default `[project root]/frontend` folder, and referencing them by `@CssImport` on the component class.

Migrating an add-on project to v24 and running it (e.g. by `mvn jetty:run`), it tries to build the `dev-bundle` and it complains about not having the referenced resource in the `/frontend` folder:
> [main] INFO com.vaadin.flow.server.frontend.scanner.FullDependenciesScanner - Visited 92 classes. Took 38 ms.
[main] INFO com.vaadin.flow.server.frontend.TaskRunDevBundleBuild - Checking if an express mode bundle build is needed
[main] INFO com.vaadin.flow.server.frontend.TaskRunDevBundleBuild$1 - Added 5 default dependencies to main package.json
[main] ERROR com.vaadin.flow.server.frontend.TaskRunDevBundleBuild - Error when checking if an express mode bundle build is needed
java.lang.IllegalStateException: 
  Failed to find the following css files in the `node_modules` or `/Users/soroosh/tmp/toggle-button-group/frontend` directory tree:
      - ./addons-styles/toggle-button-group.css
  Check that they exist or are installed. If you use a custom directory for your resource files instead of the default `frontend` folder then make sure it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.getCssLines(AbstractUpdateImports.java:230)
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.run(AbstractUpdateImports.java:101)
	at com.vaadin.flow.server.frontend.GenerateMainImports.run(GenerateMainImports.java:53)
	at com.vaadin.flow.server.frontend.TaskRunDevBundleBuild.frontendImportsFound(TaskRunDevBundleBuild.java:343)
	at com.vaadin.flow.server.frontend.TaskRunDevBundleBuild.needsBuildInternal(TaskRunDevBundleBuild.java:152)
	at com.vaadin.flow.server.frontend.TaskRunDevBundleBuild.needsBuild(TaskRunDevBundleBuild.java:105)
	at com.vaadin.flow.server.frontend.NodeTasks.<init>(NodeTasks.java:110)
	at com.vaadin.base.devserver.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:310)

Surprisingly, the above exception seems not to prevent the process of building `dev-bundle` and it continues. When the startup is completes, some files are created under `src/main/dev-bundle` but one cannot be sure if the build has successfully completed or if it is a broken output in that folder. 

### Expected behavior

Running add-on projects with v24 should be possible without any errors.

Many component projects in Vaadin Directory do not have any themes and whatever resource they contain should be placed under `src/main/resources/META-INF/resources/frontend` to be accessible by the user projects. It should be possible to run the add-on project in dev mode and get the dev-bundle if needed without any error. 

In the error stacktrace (above), it instructs the user to define a custom frontend folder by setting the `vaadin.frontend.frontend.folder` property which is not relevant here since in add-on projects, only the main resources are stored in the `src/main/resources/META-INF/resources/frontend`, but other needed styles and resources (e.g. for the demo or the integration-test pages) should be put there `[project-root]/frontend` so they don't end up in the output of the published component.

### Minimal reproducible example

1. Clone `https://github.com/taefi/toggle-button-group.git`
2. Check out the `v24` branch
3. Run the project: `mvn jetty:run`
4. The `IllegalStateException` is displayed in the console output

In my case, the build continues, and finally, the demo page seems to be available at http://localhost:8080/ and it is working as it should. However, this component only consists of a set of Buttons and styles, but in the case of more complex components, the behavior also might be broken.

### Versions

- Vaadin / Flow version: v24
- Java version: 17
- OS version: macOS 13.2.1
- Browser version (if applicable): N/A
- Application Server (if applicable): Jetty 11.0.14 (mvn-jetty-plugin)
- IDE (if applicable): N/A

**Comment by taefi** [comment]
Apart from the above issue (the error while running the add-on project itself), when the add-on component is used in another project (e.g. a starter downloaded from start.vaadin.com with v24), it shows the same error in the console while starting up. However, after that, the starter project works normally, but no idea about more complex components and projects.

So, tested version `1.0.1` of `toggle-button-group` add-on in a starter project with `v23.3.6`, and it works witout any errors.

Then tested version `2.0.0` of the same add-on in a starter project with `v24.0.0.rc1`, and the same error shows up during the startup:

> java.lang.IllegalStateException: 
  Failed to find the following css files in the `node_modules` or `/Users/soroosh/Downloads/my-app 5/./frontend` directory tree:
      - ./addons-styles/toggle-button-group.css
  Check that they exist or are installed. If you use a custom directory for your resource files instead of the default `frontend` folder then make sure it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)

Version `2.0.0` of the add-on has no changes in comparison to `1.0.1`, it is just a recompilation version (with v24) for the binary compatibility issues (since the GeneratedVaadinButton is removed in v24).

**Comment by mshabarov** [comment]
Fixes for V24.0, needs merge for V24.1.

**Comment by AB-xdev** [comment]
I also noticed this problem in the latest 23 version (currently ``23.3.17``). 
Maybe a backport is needed.

**Comment by mcollovati** [comment]
@AB-xdev dev-bundle is Vaadin 24+.
If you are experiencing issues with CSS in Vaadin 23, it would be better to create a new issue providing the details and, if possible, a reproducible example
