### ISSUE TITLE
Button in Grid row that updates the item gets detached even after refreshAll

### ISSUE THREAD

**Issue by ugur-vaadin** [vaadin/flow#16116]
### Description of the bug

Note: Even if the name contains specific components, the issue seems to be related to `DataCommunicator` and `KeyMapper`, and should be reproduceable with other components that use `DataCommunicator`.

An item is updated via a `Button` on a `Grid` row. The button click works only once. The second click event never makes it to the server. The first click updates the item, and depending on the implementation, the hashCode of the unique key provided by the identifier getter (defaults to the object itself) as well. When `DataProvider.refreshAll` is called, in `DataCommunicator.activate`, the item cannot be found in the `keyMapper` even if the item is there. This is due to the hashCode already been computed, and not matching the updated one. This leads to a duplicate in the `keyMapper`, and also the key not being removed from `passivatedByUpdate`. The keys in `passivatedByUpdate` are then unregistered in `DataCommunicator.doUnregister` and the node is removed from the parent.

Another note: If the button clicks are alternated (ie click the button on row 1, then on row 2, etc), the buttons work provided the clicks only happen once per button. With every click, only the clicked button is detached.

See: original Flow components [issue](https://github.com/vaadin/flow-components/issues/4515)

### Expected behavior

Calling `DataProvider.refreshAll()` should be able to handle the hashCode changes in the unique keys produced by the identifier getter. 

An option could be to re-compute the hashCodes for `KeyMapper.objectIdKeyMap` while retaining the mappings in `DataCommunicator.reset()`

### Minimal reproducible example

    public UnnamedView() {
        Grid<Item> grid = new Grid<>();
        grid.addColumn(Item::getId);
        grid.addColumn(Item::getText);
        grid.addComponentColumn(item -> {
            Button updateItem = new Button();
            updateItem.addClickListener(e -> {
                item.setText(item.getText() + "+");
                grid.getDataProvider().refreshAll();
            });
            return updateItem;
        });
        grid.setItems(new Item(1, "Item 01"));

        add(grid);
    }

    public static class Item {

        private int id;
        private String text;

       // add constructor & getters & setters

        @Override
        public int hashCode() {
            return Objects.hash(id, text);
        }
    }

### Versions

- Vaadin / Flow version: 24.0 (original issue was submitted for 23.3.3)
- Java version: 17
- OS version: MacOS
- Browser version (if applicable): Not applicable
- Application Server (if applicable): Not applicable
- IDE (if applicable): Not applicable

**Comment by tepi** [comment]
The provided code does not work because the Item class hashCode/equals is not stable. As per the documentation: "To function, components such as the Grid and ComboBox require that the assigned items have identifiers that are stable and unique. This usually requires a proper implementation of the hashCode() and equals() methods". In the provided code this is not true, instead the hashCode changes based on the item's field values.

More details can be found [here](https://vaadin.com/docs/latest/binding-data/data-provider#data-binding.data-provider.item-identifiers).
