### ISSUE TITLE
Vaadin + WebPackServer + DevMode -> Error in @types/node

### ISSUE THREAD

**Issue by kPlock** [vaadin/flow#16132]
### Description of the bug

When starting a server with Vaadin in DevMode, a webpackserver is also started. This uses npm/pnpm to get all the necessary components. Among these components is the @types/node. Some tests (test.d.ts) have recently been included here - these throw errors during depleyment.

Is the error greed correctly placed?

I think vaadin/flow has no error here - but that's using @types/node(18.14.6)

P.S.: Löscht man die fehlerhaft Datei, funktioniert alles wie es soll.

----

Beim Starten eines Server mit Vaadin im DevMode wird auch ein webpackserver gestartet. Dieser nutzt npm/pnpm um sich alle erforderlichen Komponeneten zu holen. Unter diesen Komponenetn ist auch die @types/node. Hier sind seit neustem auch irgendwelche Tests (test.d.ts) dabei - diese werfen Fehler beim depleyment.

Ist der Fehlwer gier richtig platziert?

Ich denke vaadin/flow hat hier keinen Fehler - aber das benutze @types/node(18.14.6)

P.S.: Löscht man die fehlerhaft Datei, funktioniert alles wie es soll.

--------

16:43:56,837 INFO  [stdout] (ForkJoinPool.commonPool-worker-1) ------------------ Starting Frontend compilation. ------------------
16:43:56,844 INFO  [dev-webpack] (ForkJoinPool.commonPool-worker-1) Running webpack to compile frontend resources. This may take a moment, please stand by...
16:44:10,327 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,327 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(612,34)[0m
16:44:10,327 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: '?' expected.[0m
16:44:10,327 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,327 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(613,17)[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ':' expected.[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(614,17)[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ',' expected.[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(617,34)[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: '?' expected.[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(618,17)[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ':' expected.[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(619,17)[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ',' expected.[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,328 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(619,26)[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ',' expected.[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(620,5)[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196m      TS1109: Expression expected.[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(624,24)[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ',' expected.[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(628,35)[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ',' expected.[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(634,39)[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ',' expected.[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(638,21)[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ',' expected.[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(643,19)[0m
16:44:10,329 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ',' expected.[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(643,27)[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ':' expected.[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(643,36)[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ',' expected.[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(643,55)[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: '{' expected.[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(643,64)[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ',' expected.[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(643,77)[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ',' expected.[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196mERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196m[tsl] ERROR in /Users/Shared/PROJEKTE/RIMAGO/SRC/rimago-frontend-server/RiMaGoFrontendServer/RiMaGoFrontendServer-FRONTEND-web/node_modules/.pnpm/@types/node@18.14.6/node_modules/@types/node/ts4.8/test.d.ts(647,22)[0m
16:44:10,330 ERROR [dev-webpack] (webpack) [38;5;196m      TS1005: ',' expected.[0m
16:44:10,331 ERROR [dev-webpack] (webpack) [38;5;196mℹ ｢wdm｣: Failed to compile.[0m
16:44:10,331 ERROR [dev-webpack] (webpack) [38;5;196m
------------------ Frontend compilation failed. -----------------[0m

<img width="1768" alt="error-webpackserver" src="https://user-images.githubusercontent.com/13207847/222915793-6dd97a5e-c862-4506-9d15-945ce62a1fda.png">

### Expected behavior

The webPackServer should start without errors.

### Minimal reproducible example

Just clear the node_modules - Folder and bevor starting. The Deployment should download the node_module again with the wrong version.

### Versions

- Vaadin / Flow version: 14.9.6
- Java version: 11
- OS version: Mac OS (newest)
- Browser version (if applicable):  each

JBoss Modules version 2.0.2.Final
JBoss MSC version 1.4.13.Final
JBoss Threads version 2.4.0.Final
WildFly Full 26.1.3.Final (WildFly Core 18.1.2.Final) 

- IDE (if applicable): Eclipse

**Comment by Artur-** [comment]
This is fixed in #16052

**Comment by kPlock** [comment]
Also fixed in 2.6  (Vaadin  14.x). ?

**Comment by kPlock** [comment]
now fixed - with Vaadin 14.9.6
