### ISSUE TITLE
Vite-bundled static resources are not served in development mode with 24.0.0

### ISSUE THREAD

**Issue by xeals** [vaadin/flow#16208]
### Description of the bug

We use a JavaScript library (Cesium) that does a lot of static resource loading at runtime and we've used Vite to bundle those assets into our frontend build in version 23. Our configuration no longer works in 24.0.0 and there has been no notice in the upgrade notes to suggest that it should not.

The relevant lines in the plugin we use to copy the assets are here: https://github.com/nshen/vite-plugin-cesium/blob/3fb46a510d3c90a7f2c0b9533bdb02f3b45dae4e/src/index.ts#L80-L94, which puts all the static resources (in v24) in `dev-bundle/webapp/cesium/*`

### Expected behavior

Bundled resources such as images and CSS should load.

### Minimal reproducible example

- Clone https://github.com/xeals/vaadin-24-cesium
- Run using `mvn spring-boot:run`
- Viewer elements are loaded but not styles, and images are not loaded

For success reproduction with v23:
- Check out revision `fbc1952`
- Remove all build artifacts and `node_modules`
- Run using `mvn spring-boot:run`
- [Cesium viewer loads with all styles](https://user-images.githubusercontent.com/21125058/223944133-6adaa545-14bd-4b96-a5b0-dc61f82a4f15.png) (requires OpenGL) or with a red error screen (without OpenGL)

### Versions

Vaadin: 24.0.0
Flow: 24.0.0
Java: N/A 17.0.5
OS: amd64 Linux 5.15.96
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Live reload: Java active (Spring Boot Devtools): Front end active

**Comment by Artur-** [comment]
I think there are a couple of issues here, both in Flow and in the cesium Vite plugin. The workaround is to enable frontend hotdeploy mode, so you use the Vite dev server like in V23

**Comment by mshabarov** [comment]
@xeals thank you for reporting this issue. Please set `vaadin.frontend.hotdeploy=true` to use Vite dev server mode, while this bug is being fixed.

**Comment by Artur-** [comment]
#16210 has been fixed in 24.0.4. Does this problem still occur with newer versions?

**Comment by xeals** [comment]
I'm still seeing the same issue with 24.0.5, yes. `vaadin.frontend.hotdeploy=true` still works as a workaround.

**Comment by Artur-** [comment]
Try with 24.1.0.beta1

**Comment by mshabarov** [comment]
@xeals could you please try with 24.1.0 as it finally out.

**Comment by xeals** [comment]
Apologies, got lost in the noise. This appears to be working with `vaadin.frontend.hotdeploy=false` again.

**Comment by mshabarov** [comment]
@xeals thanks for a fast reply. So seems it's not an issue in 24.1 anymore.
