### ISSUE TITLE
Production build with Pro components succeeds with no license

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow#16234]
### Description of the bug

I removed the `proKey` from `.vaadin` directory and run a maven production build with Vaadin 14.9.7 on Windows 10.

With `-X` the build log mentions:
```
[DEBUG] No pro key or offline key found. Dropping '@vaadin/vaadin-cookie-consent/src/vaadin-cookie-consent.js' from the fallback bundle without asking for validation
[DEBUG] No pro key or offline key found. Dropping '@vaadin/vaadin-board/vaadin-board.js' from the fallback bundle without asking for validation
[DEBUG] No pro key or offline key found. Dropping '@vaadin/vaadin-board/vaadin-board-row.js' from the fallback bundle without asking for validation
[DEBUG] No pro key or offline key found. Dropping '@vaadin/vaadin-grid-pro/src/vaadin-grid-pro.js' from the fallback bundle without asking for validation
[DEBUG] No pro key or offline key found. Dropping '@vaadin/vaadin-grid-pro/src/vaadin-grid-pro-edit-column.js' from the fallback bundle without asking for validation
[DEBUG] No pro key or offline key found. Dropping '@vaadin/vaadin-crud/src/vaadin-crud.js' from the fallback bundle without asking for validation
[DEBUG] No pro key or offline key found. Dropping '@vaadin/vaadin-crud/src/vaadin-crud-edit-column.js' from the fallback bundle without asking for validation
```
(There is no indication of rich-text-editor being dropped)

The build succeeded. When I execute the jar, both components are functional.

![image](https://user-images.githubusercontent.com/11554739/224354925-2f2bd9a1-2d52-4891-9837-163154caad67.png)

### Expected behavior

- The build should open a license validation window.
- The build should fail, since I have no license.

### Minimal reproducible example

A Vaadin 14 application that uses `RichTextEditor` and `ConfirmDialog`:

```
public class MainView extends VerticalLayout {
  public MainView() {
    new ConfirmDialog().open();
    add(new RichTextEditor());
  }
}
```

### Versions

- Vaadin / Flow version: 14.9.7
- OS version: Windows 10

**Comment by Artur-** [comment]
I could not reproduce this on a mac. The component is not and should not be dropped from the fallback bundle as it is used in the application.

After webpack is run however, I see
```
[DEBUG] Checking license for Product [name=vaadin-rich-text-editor, version=1.3.2]
```
and then the browser is opened and the build remains waiting

**Comment by javier-godoy** [comment]
Attached complete [build log](https://github.com/vaadin/flow/files/10951273/log.txt) in Windows (`mvn package -Pproduction -X`). There is no `Checking license for Product` log entry.

**Comment by mcollovati** [comment]
It seems like there's something wrong with the generation of `stats.json` file.
On Linux I have a `npmModules` section that looks like this

```
 "npmModules": [
  ....
  "@vaadin/vaadin-rich-text-editor",
  ....
}
```

But on Windows I get the following

```
 "npmModules": [
  ....
  "@vaadin\\vaadin-rich-text-editor\\src\\vaadin-rich-text-editor-content-styles.js?babel-target=es5/undefined",
  "@vaadin\\vaadin-rich-text-editor\\src\\vaadin-rich-text-editor-content-styles.js?babel-target=es6/undefined",
  "@vaadin\\vaadin-rich-text-editor\\vendor\\vaadin-quill.js?babel-target=es5/undefined",
  "@vaadin\\vaadin-rich-text-editor\\vendor\\vaadin-quill.js?babel-target=es6/undefined",
  ....
}
```

During `build-frontend`, the Vaadin maven plugin checks for commercial artifacts by inspecting the `package.json` of each module listed in `npmModules`, searching the file basically in `${project.baseDir}/node_modules/${npmModules[i]}/pacakge.json`

So, for example, on Linux the path for `vaadin-rich-text-editor` is `${project.baseDir}/node_modules/@vaadin/vaadin-rich-text-editor/package.json` (that exists), but on Windows it becomes `${project.baseDir}\node_modules\@vaadin\vaadin-rich-text-editor\src\vaadin-rich-text-editor-content-styles.js?babel-target=es5/undefined\package.json`, that of course does not exists, so the license check is skipped.

**Comment by Artur-** [comment]
So a path separator normalization is missing in vite.generated.js and then it does not strip the filenames either, and it all becomes wrong

**Comment by mcollovati** [comment]
I tested it for Flow 2.8, so with Webpack.
The problem seems to be in the StatsPlugin, that splits the module identifier with a hard-coded `/`.
Using `path.sep` seems to fix the issue.

I did not yet tested if 23.3 with Vite has a similar issue

**Comment by mcollovati** [comment]
23.3 does not have `flow-server/src/main/resources/plugins/stats-plugin/stats-plugin.js`, so the fix should be applied at in `webpack.generated.js` and `vite.generated.ts`2

**Comment by mcollovati** [comment]
This has been fixed for Vite on Flow 24
https://github.com/vaadin/flow/pull/15493

**Comment by mcollovati** [comment]
V23 with Vite seems no to be affected by the issue
