### ISSUE TITLE
Spring configuration documentation does not mention `frontend.hotdeploy`.

### ISSUE THREAD

**Issue by oliveryasuna** [vaadin/flow#16239]
See https://vaadin.com/docs/latest/integrations/spring/configuration.

It does not mention `vaadin.frontend.hotdeploy`.

Further, it does not mention `vaadin.async-supported`, `vaadin.load-on-startup`,  and `vaadin.pnpm-enabled`.

**Comment by knoobie** [comment]
Everything is mentioned here https://vaadin.com/docs/latest/configuration/properties

**Comment by oliveryasuna** [comment]
@knoobie Thanks for linking that. I was aware, just thought it would be good to add more to the link in my first post. Looks like this was handled!
