### ISSUE TITLE
Generated `tsconfig.json` should be updated for Vaadin 24.

### ISSUE THREAD

**Issue by oliveryasuna** [vaadin/flow#16235]
### Description of the bug

In Vaadin 24, the generated `tsconfig.json` still uses `23.3.4` for `flow_version`.

### Expected behavior

Use `24.0.0`.

### Minimal reproducible example

Starter app demonstrates this.

### Versions

- Vaadin / Flow version: 24.0.0
- Java version: 17

**Comment by Artur-** [comment]
This is expected. The number is just a number identifying the content. Unfortunately it is written in a confusing form. Maybe it can become ”4” or something the next time it is updated

**Comment by oliveryasuna** [comment]
@Artur- If I understand, the `flow_version` property is really an indication of the iteration of the template `tsconfig.json`? In other words, the `tsconfig.json` file we see was last updated in Vaadin 23.3.4, right?

If that is the case, I definitely agree it should be given something like `4`, rather than the Vaadin version.
