### ISSUE TITLE
Packages get generated in root directory of a multi-module maven project

### ISSUE THREAD

**Issue by gero-vachkov** [vaadin/flow#16265]
### Description of the bug

When I start the Vaadin-Flow server in a multi-module project without previously running `mvn install` additional packages (`frontend`, `target`, `node_modules`) are generated in the root module.

### Expected behavior

The packages get generated in the directory where the Vaadin Application is located or no package gets generated and an exception is thrown with a message what should be done in order to run the server.

P.S. I know it's stated that `mvn install` should be executed before running the project, but IMO if someone forgets to do it that shouldn't lead to generation of multiple files and directories that need to be deleted afterwards manually.

### Minimal reproducible example

https://github.com/vaadin/multi-module-example

- Start the `main` method of `org.vaadin.multimodule.example.Application` class

### Versions

- Vaadin / Flow version: 23.3.7 & 24.0.0
- Java version: 17
- OS version: MacOS Ventura 13.0.1
- Browser version (if applicable):
- Application Server (if applicable):
- IDE: IntelliJ

**Comment by Artur-** [comment]
The problem is that Flow does not know that "vaadin-app" is the application you are launching. Even more when you have "vaadin-app" and "vaadin-app2" in that folder, which one should Flow pick, or based on what?

**Comment by gero-vachkov** [comment]
Thanks for the fast reply! Ok, I understand, but why then trying to generate the packages in that case?

**Comment by mcollovati** [comment]
When starting the application in a submodule from IDEA you need to set the working directory setting in the run configuration to point to the module containing the class you are running

**Comment by Artur-** [comment]
What could work is detecting the project folder based on the classpath. I wonder if e.g.
```
getClass().getClassLoader().getResource(".");
```
and stripping `/target/classes/` would give the correct folder in most cases

**Comment by Artur-** [comment]
#16266 would fix this for me but it won't work on windows without some tweaking

**Comment by Artur-** [comment]
No apparently it could also work on windows as it handles a URL which does not get backslashes

**Comment by gero-vachkov** [comment]
Thank you guys for the hint. This solves the problem 👌
