### ISSUE TITLE
Provide the pre-compiled frontend bundle also for production mode

### ISSUE THREAD

**Issue by haijian-ccc** [vaadin/flow#16277]
### Describe your motivation

I was quite excited about the [Pre-Compiled Front-End Bundle](https://vaadin.com/docs/next/configuration/development-mode#pre-compiled-front-end-bundle-for-faster-start-up) in Vaadin 24, but soon realised it's only for Dev mode.

I have a dozen of Vaadin applications with only server-side Java code, no frontend code at all. Would be great if the the pre-compiled frontend bundle could be available for both Dev and Production mode, so that I don't have to worry about:
1.  compile the frontend each time I make a build, especially that Vaadin is already doing so in each Vaadin release.
2.  the frontend tools like `nodejs`, `npm `etc. (for both devs and CI servers).
3.  the frontend files like `package.json`, `package-lock.json`, `vite.config.ts`, `vite.generated.ts` etc.
  

### Describe the solution you'd like
Vaadin provides a pre-compiled frontend bundle that is available for both Dev and Production mode, similar as `vaadin-client-compiled` in Vaadin 7/8.

**Comment by mshabarov** [comment]
Implemented in Vaadin 24.1.

**Comment by haijian-ccc** [comment]
Is the documentation available somewhere already?

**Comment by mshabarov** [comment]
Yes, here https://vaadin.com/docs/latest/production/production-build
