### ISSUE TITLE
Images from theme folder are not loaded in UI after upgrade to Vaadin 24

### ISSUE THREAD

**Issue by jonas-tm** [vaadin/flow#16366]
### Description of the bug

After upgrading from 23.3.x to Vaadin 24.0.1 my images located in the theme folder are not resolved (loaded) anymore.
This problem is not appearing when  Vite is activated via `frontend.hotdeploy=true`.

Theme folder setup
```
themes
  common
    components
    styles.css
  theme1
    styles.css
    theme.json
    img
      logo.png
```

CSS
```
.mydiv {
  background-image: url("./img/logo.png")
}
```

This is what is looks like:
<img width="536" alt="image" src="https://user-images.githubusercontent.com/95413009/226950072-619377f5-faf8-47ac-a4fe-116acf3a1fe8.png">

### Expected behavior

Image is being loaded.

This is what it looks like with Vite enabled:
<img width="536" alt="image" src="https://user-images.githubusercontent.com/95413009/226945435-873bf033-93c1-40ae-8727-f76a638a6db8.png">

### Minimal reproducible example

[my-app2 2.zip](https://github.com/vaadin/flow/files/11041617/my-app2.2.zip)

### Versions

- Vaadin / Flow version: 24.0.1
- Java version: 17.0.5

**Comment by jonas-tm** [comment]
@Artur- I am unfortunately still experiencing this issue.

This is where I define it in my CSS:
```css
html{
    --logoImage: url("./img/logo-white.svg");
}
```


This is what the browser shows when running a production build. The image **is missing** on the page.
```css
html {
    --logoImage: url(./logo-white-1d401839.svg);
}
```

However, when running locally it is shown correctly:
```css
html {
    --logoImage: url(VAADIN/themes/ChartsWatcher/img/logo-white.svg);

}
```

This is quite frustrating since dev and prod behave different. So it is hard to catch the issue during development.

How can I make the image appear correctly in production mode

**Comment by mcollovati** [comment]
@jonas-tm I tried the application you uploaded against Vaadin 24.1.3 and Spring Boot 3.1.1, and I'm able to see the image both on development and production.

In production, I see 
```
html {
    --logo: url(./ipsum-4623a4a3.png);
}
```
that is resolved as http://localhost:8080/VAADIN/build/ipsum-4623a4a3.png

In development 

```
html {
    --logo: url(VAADIN/themes/theme1/img/ipsum.png);
}
```
that points to http://localhost:8080/VAADIN/themes/theme1/img/ipsum.png

**Comment by jonas-tm** [comment]
Thanks for taking the time to check it out @mcollovati 
I can confirm in the example it is working correctly. 

However, in my full production application I am seeing unexpected behavior:
In the browser dev tool the image is referenced correctly
![image](https://github.com/vaadin/flow/assets/95413009/3007ab1d-aee0-42c5-ab80-39fd74b64916)
I can successfully load the image when opening the link shown by the browser.

However, the browser is never calling this URL when loading the website:
Instead, it is calling it is calling without `VAADIN/build/`
![image](https://github.com/vaadin/flow/assets/95413009/59e913a3-ef05-470f-95d4-d51b439aef52)

Do you have any idea what could cause this?
