### ISSUE TITLE
Production build navigation buttons broken

### ISSUE THREAD

**Issue by MrDraqon** [vaadin/flow#16386]
### Description of the bug

When building the project in production mode, the navigation items are not functioning properly and are not positioned correctly. Additionally, the theme is not being applied. 

After further testing i downloaded a new starter and build a production version the Navigation was fine
Then converted it to a Kotlin project and build production again and that broke the Navigation i am not whats going on with that

![image](https://user-images.githubusercontent.com/26146033/227395775-701f4d07-5563-438a-83c9-c661c8b7ee20.png)
![image](https://user-images.githubusercontent.com/26146033/227396463-8299a358-b1ab-4e50-888d-1d17f19b4ab8.png)

### Expected behavior

I was hoping to see the same navigation buttons as in the development environment, but unfortunately, when building the project in production mode, they are not functioning correctly and are not positioned correctly either. Additionally, the expected theme is not being applied.

Expected visuals
![image](https://user-images.githubusercontent.com/26146033/227396299-53e035ca-cae0-4235-bd31-518b386fc2be.png)
![image](https://user-images.githubusercontent.com/26146033/227396386-a6cd57aa-10b3-419a-996a-7ac2054468d4.png)

### Minimal reproducible example
Convert starter project to Kotlin project then build production

Build a vaadin app in production mode

### Versions

Vaadin: 24.0.0 updated to vaadin 24.0.2 same issue
Flow: 24.0.0
Kotlin: 1.8.20-RC
OS: amd64 Windows 11 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 OPR/96.0.0.0
Live reload: Java active (Spring Boot Devtools): Front end active

**Comment by Artur-** [comment]
Hi, can you provide a reproducible example for this? It is not a generic problem like all Vaadin apps would be broken

**Comment by MrDraqon** [comment]
> Hi, can you provide a reproducible example for this? It is not a generic problem like all Vaadin apps would be broken

Yes attached zip is a fresh starter project, that has been converted to Kotlin build it with 

mvn clean package -Pproduction

[my-app.zip](https://github.com/vaadin/flow/files/11065090/my-app.zip)

**Comment by MrDraqon** [comment]
I dont understand how you are getting a different result than me, theme also seem to work for you.

When i build it it looks like
![image](https://user-images.githubusercontent.com/26146033/227608788-36690a48-3c13-4ae2-9bdf-90792c9db57c.png)

**Comment by MrDraqon** [comment]
> I dont understand how you are getting a different result than me, theme also seem to work for you.
> 
> When i build it it looks like ![image](https://user-images.githubusercontent.com/26146033/227608788-36690a48-3c13-4ae2-9bdf-90792c9db57c.png)

Alright send the project to a friend and he compiled it, hes version also came out with broken navigation and missing theme settings

**Comment by Artur-** [comment]
Any errors in the browser console?

**Comment by MrDraqon** [comment]
> Any errors in the browser console?

i cant see any errors

![image](https://user-images.githubusercontent.com/26146033/227731114-03d81478-98d7-4462-aaef-9b9cce33e385.png)

**Comment by MrDraqon** [comment]
Okay definitely happens when i add Kotlin


when i add these to my pom

```
<dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
</dependency>
```
```
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <configuration>
                    <compilerPlugins>
                        <plugin>jpa</plugin>
                        <plugin>spring</plugin>
                    </compilerPlugins>
                    <args>
                        <arg>-Xjsr305=strict</arg>
                    </args>
                </configuration>
                <executions>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/main/java</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/test/java</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-noarg</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-allopen</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
```

Am i setting up Kotlin wrong for vaadin?

**Comment by MrDraqon** [comment]
Alright found the issue i had to put the kotlin-maven-plugin above vaadin-maven-plugin in the <build></build> configuration
