### ISSUE TITLE
Display a more helpful error message if Flow is started without any routes

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#16432]
### Describe your motivation
When users download an app from start.spring.io, there are no view components in the application. When you start the application, it starts fine but only shows a default navigation error page. 

### Describe the solution you'd like
It might be helpful to users if we could show a more informational message in the case that you start an app with 0 routes in development mode. Something along the lines of: 

----
**No views found**

Add a view to get started. Here's a simple Hello World: 

```java
@Route("") // map view to the root
class MainView extends VerticalLayout {
    MainView() {
        add(new H1("Hello, world"));
    }
}
```

Learn more at https://vaadin.com/docs

----

**Comment by marcushellberg** [comment]
Good point. Yes, the intent was only for development mode. I’ll update

**Comment by tarekoraby** [comment]
I'm not sure that this would be a good idea. On the one hand, I wouldn't want to do anything that depends on vaadin.com, given its occasional glitchiness and how busy the team is. On the other hand, it would be good to have the instructions available while working offline anyway.
