### ISSUE TITLE
Long Class-Path may break the UI

### ISSUE THREAD

**Issue by Flaurite** [vaadin/flow#16554]
### Description of the bug

There is a project based on Gradle with Spring Boot. It uses Vaadin 23.3.0 version. OS is Windows 10.

If the project contains a lot of dependencies the UI does not work correctly. I've made some investigation: when the project contains a lot of dependencies, Gradle creates a temporary jar that contains "Class-Path" in the manifest.

When application starts, the `DevModeServletContextListener` tries to collect classes with specific annotations. However while it tries to collect classes the `PathMatchingResourcePatternResolver#addClassPathManifestEntries` method does not consider that jar contains all "Class-Path" for the application. So the classes from add-ons and from Vaadin are not collected.

### Expected behavior

The UI should not be broken.

### Minimal reproducible example

To reproduce the problem I hade to add some dependencies to increase the "Class-Path". I took some dependencies from here: https://github.com/jmix-framework/jmix/blob/master/jmix-bom/bom.gradle.

The project based on this starter: https://github.com/vaadin/base-starter-spring-gradle/tree/update-vaadin-23.3.7-1678460602
But I have to downgrade to 23.3.0 because there was some issues while I'm running the application.

1) I guess the problem is reproduced only on Windows OS.
2) Download the demo project: [demo.zip](https://github.com/vaadin/flow/files/11170981/demo.zip)

3) Run the application

**ER**
It should show: TextField, ToggleButton and Button.
![image](https://user-images.githubusercontent.com/22093943/230394033-5908c47c-bc7e-4a0b-8e00-92159f9c4a10.png)

**AR**
Only text with "Say hello" is shown
![image](https://user-images.githubusercontent.com/22093943/230394062-700ef5c8-3bb7-4eb6-9aeb-2db4b3d6e5a1.png)

### Versions

- Vaadin / Flow version: 23.3.0 (24 does not check, but probably there will be the same problem)
- Java version: JDK 17
- OS version: amd64 Windows 10 10.0

- IDE: IntelliJ Idea

**Comment by Artur-** [comment]
Sounds like https://github.com/spring-projects/spring-framework/issues/28276, would you say?

**Comment by Flaurite** [comment]
@Artur- yes, the problem goes from Spring. It seems the issue is important. Could you clarify is there any workaround for this problem?

**Comment by Artur-** [comment]
On a mac it does not combine the classpath elements, it just runs `java -cp <all the jars> com.example.demo.DemoApplication`. If you can reproduce this problem, maybe even without Vaadin, you should add a test project to the mentioned Spring framework issue

**Comment by Artur-** [comment]
What does the generated jar look contain exactly?

**Comment by Flaurite** [comment]
Jar just contains `MANIFEST.MF` file with class path:

![image](https://user-images.githubusercontent.com/22093943/230847348-0bfbd158-a54b-42d7-b53a-b2a44f71ffb9.png)

Will try to reproduce the problem with clear Spring application.

**Comment by mshabarov** [comment]
The problem described here looks the same as in this issue https://github.com/vaadin/flow/issues/11572. See https://vaadin.com/docs/latest/guide/start/gradle/#known-issues for insights how to workaround it.
