### ISSUE TITLE
StreamResource error when name contains "%"

### ISSUE THREAD

**Issue by probert94** [vaadin/flow#16561]
### Description of the bug

In an app I am working on, the users can download files from a server.
The filenames might contain allowed special characters (including "%") and the filename is also used as a name for the `StreamResource`.
I am using a `Anchor` component to display a clickable download link to the user and use `setHref` to set the `StreamResource`.
Now when I try to download a file which contains a "%" I get following error:
> java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: ".p"

### Expected behavior

The file should be downloaded without an error

### Minimal reproducible example

1. Download a new Vaadin starter
2. Copy the following code into the MainView
```
File f = new File("C:\\Users\\User\\Documents\\100%.pdf");
Anchor a = new Anchor();
a.setText("Download");
a.setHref(new StreamResource(f.getName(), () -> {
  try {
    return new FileInputStream(f);
  }
  catch (FileNotFoundException e) {
    throw new RuntimeException(e);
  }
}));
add(a);
```

3. Start the application and click the download link

### Versions

Vaadin: 24.0.3
Flow: 24.0.3
Java: Eclipse Adoptium 17.0.6
OS: amd64 Windows 11 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 OPR/97.0.0.0
Live reload: Java active (Spring Boot Devtools): Front end active

**Comment by Artur-** [comment]
I briefly looked at this and I don't understand why the code in `StaticFileServer` does what it does. It gets the decoded URL using `getPathInfo()` and then it passes that URL through `URLDecoder.decode`, so it tries to double decode it and then it fails, throwing the exception mentioned here

**Comment by TatuLund** [comment]
> using getPathInfo() and then it passes that URL through URLDecoder.decode, 

It is done because there is a bug in Undertow, and there getPathInfo is not decoded. And if we do not decode it here, there will be path traversal vulnerability.

**Comment by TatuLund** [comment]
The workaround is to encode the file path

```
@Route("file")
public class FileView extends Div {

    public FileView() {
        String path = "C:\\Users\\User\\Documents\\100%.pdf";
        try {
            path = URLEncoder.encode(path, "UTF-8");
        } catch (UnsupportedEncodingException e1) {
            e1.printStackTrace();
        }
        File f = new File(path);
        Anchor a = new Anchor();
        a.setText("Download");
        a.setHref(new StreamResource(f.getName(), () -> {
          try {
            return new FileInputStream(f);
          }
          catch (FileNotFoundException e) {
            throw new RuntimeException(e);
          }
        }));
        add(a);        
    }
}
```

**Comment by mcollovati** [comment]
The issue was triaged and currently added to the backlog priority queue for further investigation

**Comment by mcollovati** [comment]
The issue was assigned to a developer and is currently being investigated
