### ISSUE TITLE
BeforeEvent.rerouteTo fails

### ISSUE THREAD

**Issue by bsutton** [vaadin/flow#16597]
### Description of the bug

Vaadin: 24.0.3

We have a vaadin view that implements BeforeEnterObserver and calls rerouteTo

```
@RouteAlias(value = "show/:op_cuid", layout = OnePubLayout.class)
public class CampaignDirectorView extends VLayout implements PublicView, BeforeEnterObserver
```

The purpose of this class is an advert tracker so it simply forwards the caller to the intended target.

We have been experimenting with  BeforeEnterEvent.forwardTo and BeforeEnterEvent.rerouteTo to forward the URL to the intended target:

```java
	public void beforeEnter(BeforeEnterEvent event) {

            var guid = event.getRouteParameters().get(UrlKey.CAMPAIGN_URL_PARAMETER.getKeyName());
           var localUrl  = buildUrl(guid);
           event.forwardTo(localUrl);
          // or event.rerouteTo(localUrl);
         }
````

The forwardTo method works, but I think for the wrong reasons.
The rerouteTo method doesn't work 

In tracing through the code for both methods I see that they access the session registry:

```
return SessionRouteRegistry
                    .getSessionRegistry(VaadinSession.getCurrent());

```
This call returns a registry, however, the route map is empty.

I assume the session registry exists so that you can dynamically modify the registry per session but that it would be cloned from the main registry when the session is established.
I can see our main registry is fully populated with some 100+ routes.

However, I would expect the session registry to have been populated by the time the beforeEnter method is called.
Doing a page refresh doesn't help, even though the session should be fully initialised after a refresh.

Am I misunderstanding the point/lifecycle of the session registry or is there some problem with it not being initialised?

### Expected behavior

BeforeEvent.rerouteTo should route the call to the BlogView based on the Registry

### Minimal reproducible example

```java 
@Route(value = "show")
@RouteAlias(value = "show/:op_cuid", layout = OnePubLayout.class)
public class CampaignDirectorView extends VLayout implements PublicView, BeforeEnterObserver {

       public void beforeEnter(BeforeEnterEvent event) {
         /// stays on the CampaignDirectorView rather than opening the Blog route
          event.rerouteTo("https://xx.com/Blog");
         }
}

@Route(value = "Blog", layout = OnePubLayout.class)
public class BlogView extends VLayout
		implements AfterNavigationObserver, PublicView, BeforeEnterObserver, HasDynamicTitle
{
@Override
	public void beforeEnter(BeforeEnterEvent event)
	{
            /// rerouteTo should end up with this method being called.
	}

}
```

### Versions

- Vaadin / Flow version: 24.0.3
- Java version: 171.0.6
- OS version: ubuntu 22.04
- Browser version (if applicable): chrome : 112
- Application Server (if applicable): Spring boot
- IDE (if applicable):eclipse

**Comment by mcollovati** [comment]
The `rerouteTo` is meant to be used with route paths, not with absolutes URL.
If you need to use a URL or a path to something that is not a route, you should use `event.forwardToUrl`

The SessionRegistry may be empty, but when looking for navigation targets, it also delegates calls to the parent registry if the target cannot be resolved.

**Comment by mshabarov** [comment]
Closed because of no reply from author for more than 2 weeks.
