### ISSUE TITLE
Make it possible to change how communication problems are handled

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#166]
In Vaadin 7 you are able to use your own implementation of ConnectionStateHandler and decide how certain status codes and other error conditions are handled. This should be possible without creating your own ClientEngine.

It should also be possible to replace the reconnect dialog with your own

**Comment by mshabarov** [comment]
@Artur- is this issue valid nowadays when we have offline mode and PWA configuration in Vaadin apps?

**Comment by Artur-** [comment]
It is not related to PWA and offline mode but to how the client engine reacts to certain response codes from the server. We can close this issue. If somebody really needs to customize the behavior, they will open a new ticket and give a better description of what the problem is they want to solve
