### ISSUE TITLE
Re-building dev-bundle stalls server startup

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#16607]
### Description of the bug

The new dev-bundle in Vaadin 24 is great, unless you restart the server with new dependencies and the front-end compilation is actually triggered. In this case, the server startup doesn't proceed until the new dev-bundle is ready. In the previous versions, the front-end build didn't prevent the server startup, but showed an informative "front-end compilation in progress" in the browser, until the job was done.

### Expected behavior

As good UX as before, in case the front-end compilation is needed.

### Minimal reproducible example

Create a new project, (optional: delete the package lock so that the issue becomes more apparent), start, add dependency, restart.

### Versions

Vaadin: 24.0.4
Flow: 24.0.4
Java: Eclipse Adoptium 17.0.2
OS: aarch64 Mac OS X 13.3.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Live reload: Java active (Spring Boot Devtools): Front end active

**Comment by tepi** [comment]
Currently, we are stuck waiting at this point when `join()` is called: https://github.com/vaadin/flow/blob/main/vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java#L318. Tried an approach of returning a mock/fake DevModeHandler implementation to be able to run async, but I could not find a way to do this without having an actual dev server running.
