### ISSUE TITLE
Using ViewAccessChecker with RoleHierarchy

### ISSUE THREAD

**Issue by chkpnt** [vaadin/flow#16621]
### Describe your motivation

I'd like to use `@RolesAllowed(...)` annotated Vaadin views together with Spring Security's `RoleHierarchy`.

If a role `ROLE_ADMIN` is configured to imply other roles like `ROLE_USER` (`ROLE_ADMIN > ROLE_USER`), `ADMIN` shouldn't be needed to be included in all the `@RolesAllowed`-annotations, where `USER` is listed. So `@RolesAllowed("USER")` should be sufficient instead of `@RolesAllowed({"USER", "ADMIN"})`.

### Describe the solution you'd like

The `ViewAccessChecker` should make use of the `RoleHierarchy` bean, if present.

### Describe alternatives you've considered

My current work around is to override `getRolesChecker(...)` in my own `VaadinAccessChecker`. But unfortunately, it's a little bit complicated to configure a custom `ViewAccessChecker`:

In `SpringSecurityAutoConfiguration`, the `ViewAccessChecker`-bean isn't annotated with `@ConditionalOnMissingBean`, so I have to disable `SpringSecurityAutoConfiguration` (`@SpringBootApplication(exclude = {..., SpringSecurityAutoConfiguration.class}`) in order to overwrite the `ViewAccessChecker` bean configuration.

Then I'm doing the following in my own AutoConfiguration, which inherits from `SpringSecurityAutoConfiguration`:

```java
@Configuration
@ConditionalOnClass(WebSecurityConfigurerAdapter.class)
@EnableConfigurationProperties(VaadinConfigurationProperties.class)
public class FoobarSecurityAutoConfiguration extends SpringSecurityAutoConfiguration {
    @Override
    @Bean
    public ViewAccessChecker viewAccessChecker(AccessAnnotationChecker accessAnnotationChecker) {
        return new FoobarViewAccessChecker(accessAnnotationChecker, roleHierarchy());
    }

    @Bean
    public RoleHierarchy roleHierarchy() {
        return new FoobarRoleHierarchy();
    }

    class FoobarViewAccessChecker extends ViewAccessChecker {
        private final RoleHierarchy roleHierarchy;

        protected FoobarViewAccessChecker(
                AccessAnnotationChecker accessAnnotationChecker, RoleHierarchy roleHierarchy) {
            super(accessAnnotationChecker);
            this.roleHierarchy = roleHierarchy;
        }

        @Override
        protected Function<String, Boolean> getRolesChecker(VaadinRequest request) {
            if (request == null) {
                return expectedRole -> false;
            }
            return expectedRole -> {
                if (request.isUserInRole(expectedRole)) {
                    return true;
                }

                Authentication authentication =
                        SecurityContextHolder.getContext().getAuthentication();
                Collection<? extends GrantedAuthority> authorities = authentication.getAuthorities();
                return roleHierarchy.getReachableGrantedAuthorities(authorities).stream()
                        .map(GrantedAuthority::getAuthority)
                        .map(a -> StringUtils.removeStart(a, "ROLE_"))
                        .anyMatch(role -> role.equals(expectedRole));
            };
        }
    }
}
```

**Comment by Artur-** [comment]
This sounds a bit like https://github.com/spring-projects/spring-security/issues/2152 where the recommendation is to use a `GrantedAuthorityMapper` to make sure the roles are correct in all places

**Comment by chkpnt** [comment]
I first tried to use an expression handler in the Spring Security part, but then I learnt it doesn't make sense, as the roles are checked in `ViewAccessChecker`: https://stackoverflow.com/questions/76043291/how-to-use-spring-securitys-rolehierarchy-with-vaadin

Even if the `VaadinAccessChecker` were to get the functionality to make use of the `RoleHierarchy` bean, I suggest to add a `@ConditionalOnMissingBean` in `SpringSecurityAutoConfiguration`, as it would make customization a little bit easier (In my case, I'm redeclaring `getRolesChecker` as public in my subclass, as I need that functionality at another place, where I decide, which menu items should be displayed for the current user).

**Comment by Artur-** [comment]
As the view checker uses `HttpServletRequest.isUserInRole` to check the roles, I would assume that you want to set up Spring to that this returns the correct results. It is already Spring that provides the info there. Otherwise you might get surprises from other places too. 

If this is the code that provides that functionality (not sure about that) https://github.com/spring-projects/spring-security/blob/dd14bbb365f8517fb6de6fa97ab9dc668204f9ea/web/src/main/java/org/springframework/security/web/servletapi/SecurityContextHolderAwareRequestWrapper.java#L135-L151 then it looks like you need to ensure that `Authentication.getAuthorities()` is correct, which I guess the hint about `GrantedAuthoritiesMapper` was about

**Comment by chkpnt** [comment]
Yes, you were right. Several `AuthenticationProvider` like the `DaoAuthenticationProvider` or the `LdapAuthenticationProvider` can be configured to use an `GrantedAuthoritesMapper`.  

So this is working fine for my `dummyUserAuthenticationProvider`:
```java
@Bean
@Conditional(DummyUserCondition.class)
public DaoAuthenticationProvider dummyUserAuthenticationProvider(
        InMemoryUserDetailsManager dummyUserDetailsService, RoleHierarchy roleHierarchy) {
    var provider = new DaoAuthenticationProvider();
    provider.setUserDetailsService(dummyUserDetailsService);
    provider.setAuthoritiesMapper(new RoleHierarchyAuthoritiesMapper(roleHierarchy));
    return provider;
}
```

Unfortunately, the `KerberosServiceAuthenticationProvider` doesn't support an AuthoritiesMapper. But that's not a problem: You can instead integrate the mapper into your `LdapAuthoritiesPopulator`, which is used by your `LdapUserDetailsService`.

I am closing the ticket as the problem has been resolved. But I still think it would be good to have an additional `@ConditionalOnMissingBean`-annotation in `SpringSecurityAutoConfiguration`. I'll file a follow-up issue.
