### ISSUE TITLE
Better descriptive error message for Text::addClassName

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#16646]
```java
Text test = new Text("test");
test.addClassName("test");
```
fails in V24.0.4 with error
```There was an exception while trying to navigate to '' with the root cause 'java.lang.UnsupportedOperationException: This instance is immutable'```.

`setClassName` should be overridden in `Text` to throw a better descriptive UOE error.

**Comment by Legioth** [comment]
In addition to the error message, it could also make sense to mark the method as `@Deprecated` in `Text`.

**Comment by Legioth** [comment]
And the same also applies for all the other "inappropriate" methods on `Text`, e.g. everything that is inherited now when `HasStyle` has been added to `Component`.

**Comment by czp13** [comment]
It would be good to look into the class more deeply and fix other potential problems/methods e.g. `setId()`.
