### ISSUE TITLE
Development mode classes are initialized in production mode when push connection is lost

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#16707]
### Description of the bug

When a push connection is lost there is code that checks if the push connection was the dev tools window connection or not. As a side effect, this logic triggers initialization of the live reload code, even when in production. This causes logging output like
```
2023-04-27T15:50:10.457+03:00 ERROR 69948 --- [nio-8080-exec-6] c.vaadin.base.devserver.IdeIntegration   : IdeIntegration should never be created in production mode
```

### Expected behavior

No debug classes are instantiated when in production mode

### Minimal reproducible example

Any app using push + `mvn install -Pproduction`

### Versions

- Vaadin / Flow version: 24.0.6

**Comment by RainerGanss** [comment]
Just saw this in our prod logs. What´s the target release for this fix?

**Comment by knoobie** [comment]
If you exclude the `vaadin-dev` from the production build like e.g. shown in start.vaadin.com the problem should not be present on your production env.

**Comment by RainerGanss** [comment]
So for everybody else, this would be it.
```xml
<profile>
    <!-- Production mode is activated using -Pproduction -->
    <id>production</id>
    <dependencies>
        <!-- Exclude development dependencies from production -->
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-core</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.vaadin</groupId>
                    <artifactId>vaadin-dev</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-maven-plugin</artifactId>
                <version>${vaadin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build-frontend</goal>
                        </goals>
                        <phase>compile</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</profile>
```

**Comment by mcollovati** [comment]
Here's the link to the documentation https://vaadin.com/docs/latest/production/production-build/#excluding-the-development-server-module
