### ISSUE TITLE
Syntax errors in index.html lead to non-creation of the Vaadin bundle into the production build.

### ISSUE THREAD

**Issue by leangermany** [vaadin/flow#16705]
### Description of the bug

When we tried to test our Vaadin 24 production build in Tomcat 10, we got only a white page. The index.html file was delivered but in the html-head the linked Vaadin script src was `"frontend/vaadin.ts"`. This file didn't exist (and the path was for dev-build anyway). First we tried to add some context-path information info spring or the Servlet but that didn't work either.

So when I compared the production `war` of a new starter-project to our `war`, I saw that the bundle was missing. The static resource `VAADIN`-Folder didn't exist under `.\WEB-INF\classes\META-INF\VAADIN\webapp`.

Further I inspected the index.html, I saw that some script tags had a syntax error: 
`<script defer src="" />` instead of `<script defer src=""></script>`

When correcting this syntax error and build a production war again, everything worked out and the application finally worked in Tomcat 10.

### Expected behavior

Throw an error when could not inject the production frontend bundle into the `index.html` or when couldn't build it.

### Minimal reproducible example

Have wrong syntax in your index.html and try to deploy an production build.

### Versions

- Vaadin / Flow version: 24.0.4 with Spring Boot
- Java version: 17
- OS version: Win10
- Browser version (if applicable): Chrome 100-ish
- Application Server (if applicable): tomcat 10
- IDE (if applicable): Ecplise

**Comment by caalador** [comment]
I can not replicate the issue. 
Can you make a sample project or a clear step by step to reproduce the issue.

**Comment by mshabarov** [comment]
We cannot reproduce this issue. Please comment or create a new ticket if this is still valid for you.
