### ISSUE TITLE
Support finding Node when installed with Node Version Manager (NVM) and maybe an option for configure custom Nodejs repo

### ISSUE THREAD

**Issue by Avec112** [vaadin/flow#16789]
### Describe your motivation

We have developers on mostly Linux and everybody are working offline with no access to Internet. 

By default Vaadin seems to look for `node` from `/usr/bin/node` however many of us use `NVM` and have `node` installed under `/home/<username>/.nvm/versions/node/<version>/bin/node`. While this works just fine when building and running Vaadin with Maven node is not found when running Vaadin from Intellij with Run Configuration. 

When running our Vaadin application from Intellij Vaadin always want to install Node under .vaadin directory. However since we are offline nodejs.org is not accessible and therefor the install always fails. We do host our own NodeJS repository but we have not defined a url for nodejs.org so this do not work. I do not think nodejs.org is needed for any developers except for us working with Vaadin Flow and may be to much to ask for internally. 

### Describe the solution you'd like

1. Primarily we want Vaadin to find node where installed when using NVM. 
2. Secondarily we want to be able to configure where Vaadin (class NodeInstaller) may find our NodeJS repo (aka nodejs.org/dist) unless solved by number 1
3. Both option 1 and 2 is probably a good thing

### Describe alternatives you've considered
1. Symlink `/usr/bin/node` to NVM Node path, and same for npm
2. Host an url internally pointing at nodejs.org/dist since node is not found and need to be installed 

Rather we make this work for every developer we would prefer Vaadin Flow where more robust by offering more ways to solve this either at runtime or by configuration. 

### Additional context
Our Linux distro comes with Node 12 (via apt) something and this is what Vaadin refers to even when newer Node is installed with NVM. In this case Vaadin informes about the old version and that a newer is needed. If Node 12 is removed Vaadin wants to install Node from nodejs.org/dist since it cannot find Node installed with NVM.

**Comment by Artur-** [comment]
When you install node with nvm, it should end up in `PATH` by default and Vaadin should find it there. This is apparently not the case then?

**Comment by Avec112** [comment]
The `PATH` is fine and contains the nvm node path.

**Comment by Avec112** [comment]
`which node` also confirms this.

**Comment by Artur-** [comment]
Does IntelliJ use another shell or something then because https://github.com/vaadin/flow/blob/a23d76d6d3eca93d420a362f7591498e3d6b39ee/flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsLocator.java#L78 tries to use `which node` to find it

**Comment by Avec112** [comment]
That was something I also was thinking about before the weekend.  The default `Terminal` windows inside Intellij works exactly as expected same as the OS.  I tried to look for any terminal settings inside "Run Configurations" but did not find anything out of order. I will take another look and do some more research.

**Comment by Avec112** [comment]
Have not found anything special. I think however it is possible to recreate this problem outside from work. I will try this later today or tomorrow. Thanks so far.
