### ISSUE TITLE
ErrorHandler is not triggered correctly on some exceptions

### ISSUE THREAD

**Issue by edler-san** [vaadin/flow#16806]
### Description of the bug

I have a custom ErrorHandler to log any potential error that does not get caught elsewhere.
However, some errors do not get passed to it and instead land on the UI with the notification "Internal error. Please notify the administrator. Take note of any unsaved data...". _No_ stacktrace or error is logged on the terminal - only the browser terminal contains "Response didn't contain a server id. Please verify that the server is up-to-date and that the response data has not been modified in transmission. Es @ client-7411BA7112A12159D80"

(From my limited analysis there seems to be an additional problem with null handling in Grid as well, see reproduction example).

### Expected behavior

The ErrorHandler should be called.

### Minimal reproducible example

Add a grid with some data to a view as well as

```java
Text txt = null;
grid.setItemDetailsRenderer( new ComponentRenderer<>( x -> txt) );
```

and click on the loaded grid. The internal error should appear.

### Versions

- Vaadin / Flow version: 14.9.7; I also tested 23.x which seems not affected by this
- Java version: 17.0.7
- OS version: Win 11
- Browser version (if applicable): Edge 113.0.1774.42, Firefox 113.0.1
- Application Server (if applicable):  not applicable
- IDE (if applicable):  not applicable

**Comment by tltv** [comment]
Thanks for reporting. Could you provide an example also of the `ErrorHandler` and how you use it?

**Comment by edler-san** [comment]
[skeleton-starter-flow-spring-14.zip](https://github.com/vaadin/flow/files/11552650/skeleton-starter-flow-spring-14.zip)
Here is an example that demonstrates the issue. Run via `mvn spring-boot:run` go to localhost:8080 and click anywhere within the grid.

**Comment by mcollovati** [comment]
I just tried the provided example project and the custom error hander is correctly invoked

```
2023-05-24 11:37:29.381 ERROR 120292 --- [nio-8080-exec-2] org.vaadin.example.CustomErrorHandler    : Something wrong happened

java.lang.NullPointerException: null
	at com.vaadin.flow.data.provider.ComponentDataGenerator.generateData(ComponentDataGenerator.java:86) ~[flow-data-2.8.6.jar:2.8.6]
	at com.vaadin.flow.component.grid.Grid$DetailsManager.generateData(Grid.java:1059) ~[vaadin-grid-flow-14.9.7.jar:na]
	at com.vaadin.flow.data.provider.CompositeDataGenerator.lambda$generateData$0(CompositeDataGenerator.java:47) ~[flow-data-2.8.6.jar:2.8.6]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_322]
....
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.62.jar:9.0.62]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_322]

Tracing exception null
```

**Comment by edler-san** [comment]
Hm, it seems I reduced the sample back to working and now can't get it to fail again.
Since the customer that reported this initially is currently unavailable I will close the ticket. Thanks for looking into this.

**Comment by avdhootu27** [comment]
I am also getting same exception, can you please tell me how did you make it work?

In my case I have 2 views, in one view I am modifying the data which will be shown on another view. So if after modification if I immediately go to another view, I get this exception. And if I go to another view after a bit (1 or 2 seconds) then I don't see this exception. Also if I get this exception and If I reload the page, the exception doesn't come again.
The difference is before updating the data in 1st view the grid in 2nd view is empty, after modifying the data the grid should contain 1 row but it is not getting added. The data which I am passing in 2nd view to grid is not null but don't know which component is getting null value. The stack trace does't event tell which component in the view is causing the issue.

I can't share my project. You can ask if you need any other information.
