### ISSUE TITLE
VaadinWebSecurity seems to work differently than VaadinWebSecurityConfigurerAdapter

### ISSUE THREAD

**Issue by Alabme** [vaadin/flow#16839]
### Description of the bug

I'm struggling to configure Spring Boot Security in my application. What I want to achieve is: all vaadin's views should be accesible on `localhost/ui/**` and rest api endpoints on `localhost/api/rest/**`. Right now everything is working (I think) as I wanted but with usage of  `VaadinWebSecurityConfigurerAdapter`, but, since `VaadinWebSecurityConfigurerAdapter` is deprecated and Spring guys recommend configuring Spring Boot Security with `SecurityFilterChain` I am trying to achieve same security results, but without any success - this time Vaadin security seems to work a slightly different: after logging with proper authentication credentials in Vaadin's login form view i am redirecting to `/login` page (exact same form) instead of `/ui/users` as desired.

### Expected behavior

I would like to achieve two goals:

1. everything (in a browser) pointing to `/ui/**` shows Vaadin login page (if user is not logged in), and after proper log in site redirects to desired url (e.x `/ui/users`)
2. every request to `/api/rest/**` requires http basic authentication and works as designed when provided.

### Minimal reproducible example

Working code example with `VaadinWebSecurityConfigurerAdapter`

```kotlin
@Order(Ordered.LOWEST_PRECEDENCE - 8)
@Configuration
class VaadinSecurityConfig : VaadinWebSecurityConfigurerAdapter() {
    override fun configure(http: HttpSecurity) {
        http {
            authorizeRequests {
                authorize("/public/**", permitAll)
            }
        }
        super.configure(http)
        setLoginView(http, LoginView::class.java)
    }
}

@Order(Ordered.HIGHEST_PRECEDENCE + 8)
@Configuration
class RestApiSecurityConfig : WebSecurityConfigurerAdapter() {
    override fun configure(http: HttpSecurity) {
        http {
            authorizeRequests {
                authorize("/api/rest/**", authenticated)
            }
            httpBasic { }
            csrf { disable() }
        }
        super.configure(http)
    }
}
```
===================================================================
Not working code example with `SecurityFilterChain`

```kotlin
@Configuration
class VaadinSecurityConfig : VaadinWebSecurity() {
    override fun configure(http: HttpSecurity) {
        http {
            authorizeRequests {
                authorize("/public/**", permitAll)
            }
        }
        super.configure(http)
        setLoginView(http, LoginView::class.java)
    }
}

@Configuration
class RestApiSecurityConfig {
    @Order(Ordered.HIGHEST_PRECEDENCE + 8)
    @Bean
    fun restApiSecurityFilterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            authorizeRequests {
                authorize("/api/rest/**", authenticated)
            }
            httpBasic { }
            csrf { disable() }
        }
        return http.build()
    }
}
```

### Versions

- Vaadin / Flow version: 23.2.10
- Java version: 17.0.5 / kotlin: 1.8.21
- OS version: Ubuntu 23.04
- IDE (if applicable): 2023.1.1

**Comment by castellanos94** [comment]
I have the same problem with version 24.0.5 and spring boot 3.06

**Comment by mcollovati** [comment]
Hi @Alabme, I'm trying to reproduce the issues, but it seems there are some missing parts in the configuration you provided.

Could you please share a complete example project with the working solution for `VaadinWebSecurityConfigurerAdapter`?

**Comment by mcollovati** [comment]
I have just tried to setup a configuration similar to the one in the ticket and it works as expected for me with `VaadinWebSecurity`.

When not authenticated:
* All requests to protected views under `/ui/` are redirected to the Vaadin login page, and after entering the credentials the browser redirects to the originally requested page.
* When accessing resources under `/api/rest/` the basic auth dialog is shown, and after entering credentials the response is rendered

Once the user is authenticated (either with form or basic auth), Vaadin views and spring controllers work as expected, without requiring further authentication.

@Alabme, @castellanos94 if you can provide a full project we can try to compare the configuration and figure out the differences.

**Comment by Alabme** [comment]
@mcollovati I have gave You an access to my personal toy project where You can try to track my issue.

**Comment by mcollovati** [comment]
@Alabme I quickly tested the application without any changes (so I guess it is the configuration that is working for you using `VaadinWebSecurityConfigurerAdapter`), but it always shows me the default Spring login page.
If I try to access the `/api/rest/**` the basic auth dialog is not shown, instead there's a redirection to the default Spring login page.

I also noticed only now that you are using Vaadin 23.2.x. I strongly suggest upgrading to the latest Vaadin 23.3 and Spring Boot 2.7.x.

Anyway, I'll try to apply the new configuration to the project and let you know

**Comment by mcollovati** [comment]
A couple of notes:
 - on the original configuration in `RestApiSecurityConfig` there's a call to `super.configure()` that basically resets part of the configuration, activating the default form-based login for every request. In the logs I got this warning `s.s.c.a.w.c.WebSecurityConfigurerAdapter : Using default configure(HttpSecurity). If subclassed this will potentially override subclass configure(HttpSecurity).`
 - The `LoginView` is not adding the `LoginForm` component to the component tree (`add(login)` in `init { }`), so the form is not shown
 - With the new configuration, I had to change `RestApiSecurityConfig` to restrict it to only `/api/rest/**` paths, defining a `securityMatcher` (see below); otherwise this configuration hides the VaadinWebSecurity, because they match the same paths and this one has higher priority

```kotlin
@Configuration
class RestApiSecurityConfig {
    @Order(Ordered.HIGHEST_PRECEDENCE + 8)
    @Bean
    fun restApiSecurityFilterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            securityMatcher("/api/rest/**") // <---------------- Added configuration
            authorizeRequests {
                authorize(anyRequest, authenticated)
            }
            httpBasic { }
            csrf { disable() }
        }
        return http.build()
    }
}
```

**Comment by Alabme** [comment]
@mcollovati Not yet, I will do it during a weekend.

**Comment by Alabme** [comment]
@mcollovati I've made a changes as You suggested and it seems everything is working now... 
Thanks for help and sorry that You had to sacrifice Your time to fix my mistakes :/

**Comment by mcollovati** [comment]
@Alabme no worries, I'm glad we could help.
Do you think we can close the ticket, as the issue was mostly about Spring security configuration?

**Comment by Alabme** [comment]
@mcollovati Yeah, sure 👍

**Comment by Alabme** [comment]
Closed.

**Comment by brunoamuniz** [comment]
> A couple of notes:
> 
> * on the original configuration in `RestApiSecurityConfig` there's a call to `super.configure()` that basically resets part of the configuration, activating the default form-based login for every request. In the logs I got this warning `s.s.c.a.w.c.WebSecurityConfigurerAdapter : Using default configure(HttpSecurity). If subclassed this will potentially override subclass configure(HttpSecurity).`
> * The `LoginView` is not adding the `LoginForm` component to the component tree (`add(login)` in `init { }`), so the form is not shown
> * With the new configuration, I had to change `RestApiSecurityConfig` to restrict it to only `/api/rest/**` paths, defining a `securityMatcher` (see below); otherwise this configuration hides the VaadinWebSecurity, because they match the same paths and this one has higher priority
> 
> ```kotlin
> @Configuration
> class RestApiSecurityConfig {
>     @Order(Ordered.HIGHEST_PRECEDENCE + 8)
>     @Bean
>     fun restApiSecurityFilterChain(http: HttpSecurity): SecurityFilterChain {
>         http {
>             securityMatcher("/api/rest/**") // <---------------- Added configuration
>             authorizeRequests {
>                 authorize(anyRequest, authenticated)
>             }
>             httpBasic { }
>             csrf { disable() }
>         }
>         return http.build()
>     }
> }
> ```

this answer was very useful!! Thanks a lot @mcollovati 

I was completely stucked using "http.authorizeHttpRequests" but I changed to "http.securityMatcher("/api/**").csrf().disable();" and it is working fine

**Comment by padmalcom** [comment]
Hi I'm facing exactly the same issue at the moment. We want to integrate a rest api and a vaadin ui and split the authentication mechanisms. This thread seems to be the only valuable information for me. Unfortunately, I don't have access to the sample projekct @Alabme mentioned. Would it be possible to get access to it, too? Thanks!

**Comment by Alabme** [comment]
Hi @padmalcom , I've gave You an access, please check if it is working.

**Comment by padmalcom** [comment]
Hi @Alabme, thanks a lot, I was able to fix my security issue, api and vaadin work fine now in parallel. Great to get some help here! :)

**Comment by frankrues** [comment]
@padmalcom 
I have the same issue and could let us know what you have fixed to get it to work, please?

**Comment by padmalcom** [comment]
@frankrues: This is the answer I'd have payed 1000$ for a year ago :)
```
    override fun configure(http: HttpSecurity) {
        http.csrf {
            it.ignoringRequestMatchers("/api/**")
        }
        http
            .authorizeHttpRequests {
                it.requestMatchers("/api/v1/auth/login").permitAll()
                ...
                it.requestMatchers("/api/**").authenticated()
            }
            .sessionManagement {
                it.sessionCreationPolicy(SessionCreationPolicy.STATELESS)
            }
            .addFilterBefore(jwtAuthFilter, UsernamePasswordAuthenticationFilter::class.java)
            .exceptionHandling { eh ->
                eh.defaultAuthenticationEntryPointFor(
                    HttpStatusEntryPoint(HttpStatus.UNAUTHORIZED),
                    AntPathRequestMatcher("/api/**")
                )
            }

        http
            .authorizeHttpRequests {
                it.requestMatchers("/images/**").permitAll()
                it.requestMatchers("/.well-known/**").permitAll()
            }
        super.configure(http)
        http.sessionManagement {
            it.sessionCreationPolicy(SessionCreationPolicy.IF_REQUIRED)
        }
        setLoginView(http, LoginView::class.java, "/logout")
    }
```

Hope it helps.

**Comment by frankrues** [comment]
@padmalcom 
It was worth every penny :-) - Thank you!
