### ISSUE TITLE
Disable the live reload when the theme editor is opened

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow#16864]
### Description of the bug

When I open the theme editor and pick an item, I can assign a classname with the theme editor.
It changes the Java code then refresh the page if the live reload is enabled. (tested with JRebel).

When the page is refreshed, I'm losing my context (opened dialog for example) and also the theme editor.

### Expected behavior

The page should not be refreshed and the live reload should be disabled if the theme editor is opened

### Minimal reproducible example

You can reproduce in any application

### Versions

- Vaadin / Flow version: Vaadin 24.1.beta1
- Java version: 17
- OS version: Mac

Tested with JRebel

**Comment by jcgueriaud1** [comment]
I'm wondering if it's possible to disable the live reload just before changing the code in the code editor then re-enable it just after.

**Comment by jcgueriaud1** [comment]
It doesn't seem to work in the Vaadin 24.2.0.beta1. Is it a regression?

**Comment by szolo** [comment]
@jcgueriaud1 I could check, are you using JRebel?

**Comment by jcgueriaud1** [comment]
Yes, I'm using the same environment as described in the ticket (except the Vaadin version)
