### ISSUE TITLE
Support for serialization of record object to Json

### ISSUE THREAD

**Issue by rmuller** [vaadin/flow#16879]
Vaadin 24 currently does not support serialization of record objects to JSON. Which is a pity because of the great DX record type bring on the table. 

Serialization is done by `com.vaadin.flow.internal.JsonSerializer`. It is easy to extend it with support for record types (depending on `com.vaadin.external.gwt:gwt-elemental:2.8.2.vaadin2` for the real work).

Instead of 

        try {
            JsonObject json = Json.createObject();
            BeanInfo info = Introspector.getBeanInfo(bean.getClass());
            for (PropertyDescriptor pd : info.getPropertyDescriptors()) {
                if ("class".equals(pd.getName())) {
                    continue;
                }
                Method reader = pd.getReadMethod();
                if (reader != null) {
                    json.put(pd.getName(), toJson(reader.invoke(bean)));
                }
            }

            return json;
        } catch (Exception e) {
            throw new IllegalArgumentException(
                    "Could not serialize object of type " + bean.getClass()
                            + " to JsonValue",
                    e);
        }

Use

        try {
            JsonObject json = Json.createObject();
            var type = bean.getClass();
            
            if (type.isRecord()) {
                for (var rc : type.getRecordComponents()) {
                    json.put(rc.getName(), toJson(rc.getAccessor().invoke(bean)));
                }
                return json;
            }            
            
            BeanInfo info = Introspector.getBeanInfo(type);
            for (PropertyDescriptor pd : info.getPropertyDescriptors()) {
                if ("class".equals(pd.getName())) {
                    continue;
                }
                Method reader = pd.getReadMethod();
                if (reader != null) {
                    json.put(pd.getName(), toJson(reader.invoke(bean)));
                }
            }
            return json;
        } catch (Exception e) {
            throw new IllegalArgumentException(
                "Could not serialize object of type %s to JsonValue".formatted(bean.getClass()), e);
        }

**Comment by Legioth** [comment]
Something like that would indeed make sense starting from Vaadin 24 since we no longer need to support Java versions without `Class::getRecordComponents` and similar APIs.

**Comment by Legioth** [comment]
Should probably also do something similar for `BeanPropertySet` so that you could do `new Grid<>(MyRecordType.class)` to automatically configure columns based on record components.

**Comment by rmuller** [comment]
> Should probably also do something similar for BeanPropertySet so that you could do new Grid<>(MyRecordType.class) to automatically configure columns based on record components.

Perfect moment to modernize this class using `LambdaMetafactory` :)
However this is more involved. Maybe you can consider first implement my suggestion. That makes using LitRenderer much more convenient!
