### ISSUE TITLE
expired certificate maven.vaadin.com - TODAY

### ISSUE THREAD

**Issue by bsutton** [vaadin/flow#16870]
### Description of the bug

When running a mvn install we are seeing an expired certificate on maven.vaadin.com

This is blocking !!!!!!!!

### Expected behavior

The certificate should not be expired.

### Minimal reproducible example

use a browser to access maven.vaadin.com and note the status of the certificate.

### Versions

all.

Edit: corrected the url.

**Comment by oliveryasuna** [comment]
Please, needs attention immediately!

**Comment by lcorson-carma** [comment]
This is urgent, we have a client down at the moment because of this.

**Comment by rodolforfq** [comment]
Hello. I have reported this internally.

Thanks for the heads up! The team will work to sort this out asap.

**Comment by oliveryasuna** [comment]
This seems to be resolved.
