### ISSUE TITLE
Allow to reuse the production bundle when files have not changed.

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#16886]
### Describe your motivation

(based on our internal discussion)

While the newly introduced production bundle (PB) is intended to prevent devs from having to install and indirectly use node / npm, it  could also help speed up integration tests on developer machines, as ITs should always be run in production mode. 

Unfortunately, there is currently no way to keep the PB, when using custom JS/TS files, even when they haven't changed. Therefore this feature is not usable for more complex projects running ITs.

### Describe the solution you'd like

It should be possible to keep the production bundle, when the respective file hashes have not changed. ~~To prevent any build server complications, this feature should be turned off by default. A configuration flag (e.g. "keep production bundle") allows to enable/disable it. Our starter application.property should however set the flag to true, so that developers have this feature enabled by default.~~
The feature should be enabled by default so that developers, who run ITs on their machines, may benefit from this new feature automatically. A configuration flag should be provided so that this feature can be disabled.

**Comment by benstpierre** [comment]
This would relieve a huge pain point for us.

**Comment by mshabarov** [comment]
**Acceptance criteria:**
- [ ] When default production bundle is not enough to run the application, because of JS/TS changes, Flow should re-build the prod bundle, copy it into build directory (as it works now) and additionally save the bundle in the project, in the `src/main/prod-bundle` directory, similar to `dev-bundle`
- [ ] On each subsequent prod build runs Flow should check if existing bundle in `src/main/prod-bundle` is enough for project (same checks as for dev-bundle) and re-copy the bundle from this dir to build directory
- [ ] Default is to re-use the custom bundle if possible, existing parameter `vaadin.force.production.build=true` can be used to trigger the build always
- [ ] License checking is done always for custom prod bundle.

**Comment by mshabarov** [comment]
@stefanuebe I propose to have this feature by default, why do you think re-bundle by default is better?

**Comment by stefanuebe** [comment]
> @stefanuebe I propose to have this feature by default, why do you think re-bundle by default is better?

I think this feature will be primarly used by devs to run ITs or test prod builds on their own machines to see, if things can be committed. Time is an important resource in that case since ITs on their own already can eat up a lot of it.

On the other hand, production builds are most times run by CI test servers, which in my opinion should not activate this feature, so that they really have the latest state of development when building things (e.g. to see if all dependencies are still available, no caches that affect builds, etc). Plus they do not have the time pressure that a developer has. 

Therefore, since prod builds by CI servers are the more common use case, we should turn it off by default to not have all admins need to deactivate this feature, but give those devs, who need it on their machines the possibility to turn it on. 🙂 

I hope my explanation is more or less understandable 😄

**Comment by mshabarov** [comment]
CI pipelines usually checkout a fresh project repo, where no pre-compiled bundle exists. Thus, practically on CI servers the build will always be running in case of JS/TS customisations. Even if sources are updated, if Vaadin sees that the frontend dependencies have changed, it should trigger a new build.

**Comment by stefanuebe** [comment]
Fair point. So for me it's fine to have it activated by default.
