### ISSUE TITLE
Provide a way to clean the dev-bundle

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow#16888]
### Describe your motivation

I would like to be able to clean the dev-bundle.

### Describe the solution you'd like

The goal vaadin:clean-frontend should clean the dev-bundle.

### Describe alternatives you've considered

Manually removing the folder dev-bundle.

### Additional context

I would like to clean the dev-bundle when I'm removing a dependency, since the dev-bundle is not rebuilt automatically when I remove a dependency. I don't know if this is considered as a bug.

**Comment by manolo** [comment]
I guess this is what happens in this case, right @jcgueriaud1 ?
1. clone this repo and checkout the branch that has already a `src/main/dev-bundle/` folder
```
git clone git@github.com:vaadin/hackathon-24-1.git
cd hackathon-24-1/
git checkout dev-bundle-tests
```
2. run the project
```
mvn
```
3. it fails with the errors
```
java.lang.RuntimeException: Unable to initialize com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener
...
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException:

  Failed to find the following css files in the `node_modules` or `/private/tmp/kkk/hackathon-24-1/frontend` directory tree:
      - lumo-css-framework/all-classes.css
  Check that they exist or are installed. If you use a custom directory for your resource files instead of the default `frontend` folder then make sure it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)

	at com.vaadin.flow.server.frontend.AbstractUpdateImports.getCssLines(AbstractUpdateImports.java:339) ~[flow-server-24.1.0.beta2.jar:24.1.0.beta2]

```

Is it possible somehow that dev-mode is able to discard the previous dev-bundle in case of failure?

**Comment by Artur-** [comment]
Do you have an example where the bundle is not rebuilt when removing an addon? This sounds like a bug. If an addon has e.g. `@JsModule("hello.js")` then removing the addon should remove the import from `hello.js` from the `flow-generated-imports js` and this change should cause a new bundle to be built

**Comment by jcgueriaud1** [comment]
Here is the branch with an example:
https://github.com/vaadin/hackathon-24-1/tree/dev-bundle-tests-sortable

And the diff:
https://github.com/vaadin/hackathon-24-1/commit/89485a96aa6c4da9d9850707bdac64c4b3c8ce3f

The package is updated but nothing in the dev-bundle

**Comment by caalador** [comment]
This probably is due to that we accept a bundle with at least what we need, but may contain more than needed.

**Comment by caalador** [comment]
The clean targets `flow:clean-frontend` and `vaadin:clean-frontend` now also remove any application specific devBundles.
Closing this as done.
If there is a clear need for rebundling due to removed dependencies, it should be made as a new issue and it should probably only concern user added/removed frontend files/packages.
