### ISSUE TITLE
Dev-bundle is failing after mvn clean + clean-frontend

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow#16885]
### Description of the bug

I'm building an application with a third party addon viritin.
A new dev-bundle is created when I run the application.
If I run `mvn clean vaadin:clean-frontend`, then the application does not start anymore.

> 
> Caused by: java.lang.IllegalStateException:
> 
> Failed to find the following css files in the `node_modules` or `/Users/xxxx/hackathon-24-1/./frontend` directory tree:
> - lumo-css-framework/all-classes.css
> Check that they exist or are installed. If you use a custom directory for your resource files instead of the default `frontend` folder then make sure it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)
> 

### Expected behavior

The application should run.

I think it's related to the CSS imported in the addon from a NPM package. Since I can't reproduce it with the other addons I tested.

### Minimal reproducible example

https://github.com/vaadin/hackathon-24-1/tree/dev-bundle-tests

### Versions

- Vaadin / Flow version: Vaadin 24.1.beta2 and 24.0.5
- Java version: 17

**Comment by Artur-** [comment]
At the end of `AbstractUpdateImports.getUniqueEs6ImportPaths` the case is handled for JS imports. In `getCssLines` the same suppression of the error message would be needed but the code is missing.

**Comment by mshabarov** [comment]
This is related to https://github.com/vaadin/flow/issues/16888 : need to delete dev-bundle

**Comment by Artur-** [comment]
It is not really related to that. It is related to invalid error reporting for CSS files in the bundle

**Comment by jcgueriaud1** [comment]
Removing the dev-bundle won't help for the other persons who are getting the application + dev-bundle from git (for example.
--> No target and no node_modules so they will have the error (I think you have it with the example I pushed)

**Comment by Artur-** [comment]
We should fix this

> At the end of `AbstractUpdateImports.getUniqueEs6ImportPaths` the case is handled for JS imports. In `getCssLines` the same suppression of the error message would be needed but the code is missing.
