### ISSUE TITLE
vaadin-maven-plugin plugin.xml does not list `forceProductionBuild`

### ISSUE THREAD

**Issue by oliveryasuna** [vaadin/flow#16898]
### Description of the bug

Not exactly a bug, more-so an overlooked feature. See title.

### Expected behavior

The plugin's configuration should list the new configuration property, `forceProductionBuild`.

### Minimal reproducible example

https://vaadin.com/docs/latest/production/production-build/#enabling-production-builds

### Versions

- Vaadin / Flow version: 24
- Java version: 17
- OS version: macOS

**Comment by mshabarov** [comment]
@oliveryasuna thank you for the issue! What minor version do you use? This config parameter has been introduced in V24.1 and not available in 24.0.

**Comment by oliveryasuna** [comment]
@mshabarov 24.0. Thanks for letting me know it's added in 24.1.
