### ISSUE TITLE
UT010026 Error, Vaadin23 + Push + SpringBoot on Wildfly

### ISSUE THREAD

**Issue by moryakovdv** [vaadin/flow#16907]
### Description of the bug

I have an application running under Wildfly 21+.
Sometimes the application log is full of messages like 

```
IllegalStateException 
UT010026: Async is not supported for this request, as not all filters or Servlets were marked as supporting async
```

Might be it happens when session is dead or on network re-connections, I'm unable to find out.
Error description shows there is some filter with no ```<async-supported>```  configured.

But configuration has no web.xml and there are no extra filters as well. 

Sentry says that error occures when requesting ```/VAADIN/Push/``` url.

Push is enabled in WEBSOCKET-mode.

Full stacktrace is attached.
Any suggestions will be appreciated.
Thanks in advance.

### Expected behavior

No error should occur

### Minimal reproducible example

[UT010026-stack-trace.txt](https://github.com/vaadin/flow/files/11592998/UT010026-stack-trace.txt)

### Versions

- Vaadin / Flow version: 23.3.4
- Java version: 11
- OS version: Ubuntu 20+
- Browser version (if applicable): Any
- Application Server (if applicable): Wildfly 21+

**Comment by mshabarov** [comment]
@moryakovdv thank you for the issue! Do you have a minimal reproducible example, so that we can run locally and see the problem?

**Comment by moryakovdv** [comment]
@mshabarov, thanks for the answer.
It's tricky to create reproducible example, because this error is quite stochastic.
At the first glance: In production environment we have Nginx at the front and I notice this error more often than in stage or debug environment without Nginx.

**Comment by Legioth** [comment]
While there might not be any explicitly registered filters through `web.xml`, there's still a whole bunch of dynamically registered filters in the stacktrace. I didn't carefully review the full list of filters but most of them are part of Spring and they are in general expected to support async.

I don't think Nginx or anything else in front of Wildfly is relevant here but instead only how things are deployed inside Wildfly. At the same time, there isn't anything obvious we can do based the provided information.

**Comment by Artur-** [comment]
Websockets should not care about async support in servlets so maybe you are seeing this when a user for some reason is unable to use websockets and it downgrades to long polling

**Comment by moryakovdv** [comment]
@Artur- thanks, it may be valuable. 
Is there a way to detect switching to long-polling rather than monitor browser network logs?

**Comment by moryakovdv** [comment]
It was simple to emulate. 
I just switched to LONG_POLLING instead of WEBSOCKET in ```AppShellConfigurator``` class
```
@NoTheme
@Push(transport = Transport.LONG_POLLING)
public class VaadinAppInit implements AppShellConfigurator {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4925377690787336700L;
	
}
```
Now I have the above stack in console and can continue investigation

**Comment by moryakovdv** [comment]
Funny. 
[Sentry](http://sentry.io) reported me about this issue in production environment. 
And it turns to that ```SentryUserFilter.class``` is a culprit.
Now I removed ```sentry-spring-boot-starter``` from pom and from source-code and long-polling acts as expected without issues.
Thank you for your ideas, probably I need to report that on to Sentry.io

**Comment by mshabarov** [comment]
@moryakovdv thanks for letting us know. I close this issue. If you experience any other problems with Vaadin, please open a new issue.
