### ISSUE TITLE
Vaadin hash in package.json is not invariant (VCS changes)

### ISSUE THREAD

**Issue by gitgdako** [vaadin/flow#16913]
### Description of the bug 
It is common practice to have package.json version controlled. The value in "vaadin" -> "hash" differs between different clients and builds. Probably related to com.vaadin.flow.server.frontend.TaskRunNpmInstall. The problem persists even after running "npm ci"

### Minimal reproducible example
Not sure how to consistently reproduce the issue though, sometimes the hash stays the same. According to expert chat: "I somehow suspect that the hash will keep changing at least every time you do mvn vaadin:clean-frontend and then do mvn clean install/package again"

### Expected behavior
The hash should produce the same result for same code base (at least with a clean build)

### Actual behavior
Sometimes (regularly) the hash differs

### Versions:
    - Vaadin / Hilla version: 1.2
    - Node version: 18.15
    - Java version: OpenJDK 1.8.0_352
    - OS version: Windows

**Comment by platosha** [comment]
I have transferred this issue to the Flow repo for keeping the team aware about this. As the actual feature implementation is in Flow, it might affect Flow users as well, not only Hilla.

**Comment by gitgdako** [comment]
We have checked that on both systems the package.json is UTF-8 LF. If there is any additional info I can provide please do contact me, we are out of ideas

**Comment by Artur-** [comment]
If you provide the two versions of package.json with different hashes, then it is at least possible to check which one is correct

**Comment by gitgdako** [comment]
[package.json.txt](https://github.com/vaadin/flow/files/11609846/package.json.txt)

It didnt let me upload a .json extension. Starting the server on my system changes the hash from 
a98e6503d9a6d032fefe3d1e1bfe9cdcfc927b797dd57ab19e5a5859785b0231
to the value present in this file
3fbcd428084be6ec9aeb08bc6b1b7cb8da14a678bb60c2989d21f5673d807f3d

**Comment by Artur-** [comment]
I did a quick check of passing that package.json through `TaskUpdatePackages.generatePackageJsonHash` and get `b219dc1b833f3ee6ab2adf08d09327d115c6b7d4326ba16d24bf3ef1720c83a6`, which does not match either one..

**Comment by gitgdako** [comment]
Using the same file in our reproducer project yields 
5a9653cec172f79726afd173b5bd777411b8db104b359d52db2c33c7fcf5fb25

**Comment by Artur-** [comment]
You mention Hilla 1.2 but you should test the latest version 1.3.12

**Comment by gitgdako** [comment]
The issue seems to be resolved with the upgrade to 1.3.12
