### ISSUE TITLE
Make component scan to scan annotations on methods

### ISSUE THREAD

**Issue by leluna** [vaadin/flow#16925]
### Describe your motivation

With https://github.com/vaadin/flow/pull/16592, bundles  are only loaded if they can be reached by the bycode scanner. However, we build a library which uses annotation to declare UI components. When such an annotation is used on a class, it still works, but annotations on methods seems to be ignored by the scanner. Thus, bundles of components that are referred in the method level annotations are not loaded.

### Describe the solution you'd like

I think it would help us if the bycode scanner also respect method annotations as they respect type level annotations.

### Describe alternatives you've considered

We are currently annotating the router layout with ALL Vaadin components using `@Uses`. This is still not a good workaround as a developer who creates a new component with bundle still need to annotate `@Uses` somewhere to make their component/annotation usable everywhere in the application. 

### Additional context

An annotated class may look like this:

```
@UISearchlLayout
public class MyPmo {

  @UISearchField(...)
  public String getText() { return "value to be displayed"; }
}
```

The annotations `UISearchLayout` and `@UISearchField` are again annotated with a marker annotation for component creation functional interface, e.g.

```
@LinkkiComponent(SearchLayoutComponentDefinitionCreator.class)
public @interface UISearchLayout {
  ...
  class SearchLayoutComponentDefinitionCreator implements ComponentDefinitionCreator<UISearchLayout> {
    public LinkkiComponentDefinition create(UISearchLayout annotation, AnnotatedElement annotatedElement) {
      return pmo -> new SearchLayout();
    }
  }
}
```

**Comment by Artur-** [comment]
#16937 adds scanning of method annotations
