### ISSUE TITLE
@CssImport with value and include fails with Vaadin 24.1

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#16979]
### Description of the bug

In cookbook there was
```
@CssImport(value = "./recipe/large-upload-area/file.css", include = "lumo-badge")
```
which causes a runtime failure after upgrading to 24.1:
```
Uncaught (in promise) ReferenceError: addCssBlock is not defined
    at generated-flow-imports.js:66:1
```

The code in the file is
```
import $cssFromFile_20 from "/VAADIN/recipe/large-upload-area/file.css?inline";
const $css_20 = typeof $cssFromFile_20 === 'string' ? unsafeCSS($cssFromFile_20) : $cssFromFile_20;
addCssBlock(`<style include="lumo-badge">${$css_20}</style>`);
```

### Expected behavior

`addCssBlock` should be available when used

### Minimal reproducible example

```
@CssImport(value = "./any.css", include = "lumo-badge")
```

### Versions

- Vaadin / Flow version: 24.1.0

**Comment by gpsfl** [comment]
Any ETA for 24.1.1 release?

**Comment by mshabarov** [comment]
New Flow version `24.1.1` with this patch is being released and should be available today June 19.
Vaadin `24.1.1` release with a new Flow is planned afterwards.
Not sure about exact day, but expect it during this week.
