### ISSUE TITLE
EAP feedback from Stephan Diehl 

### ISSUE THREAD

**Issue by macjuan** [vaadin/flow#1698]
From @ossd 

"is there a getting started documentation, to understand the development?

- why i need a html file
- what can be generated

my first impression is: i see a lot of static strings, the reference between code and html file. the main reason i use vadim framework is to be able to refactor anything without the risk of runtime errors. we used primefaces in the past and the main problem was, that you reference methods in html files that are not in sync with your java file. when you refactor a method, you will not get an compilation error.

when you need strings in html to reference to variables or methods in java, you will not be type safe. when you ask me, this was the main reason for using java for web development and not php, ruby or something other fancy

my questions for the getting started is: how to work without html files or how to generate them or other way to avoid a runtime error."

**Comment by pleku** [comment]
#3305 changes the structure of the documentation from _almost random_ to a recommended reading order. The _building hello world_ and _getting started_ are in the beginning.

It also adds an introduction / architecture documentation that briefly touches on different ways of implementing components. The documentation structure is now formulated in a way that the already existing components are introduced first, then general server side component building, and lastly the web component and template topics.
