### ISSUE TITLE
getter returning Optional is not compatible with Kotlin properties

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#1699]
Flow 0.1.6: Kotlin supports properties (a getter/setter pair shrinks into a property syntax in Kotlin, please see https://kotlinlang.org/docs/reference/properties.html for more details). However, Kotlin only supports properties when both the getter and the setter return the very same type. Unfortunately, Flow introduces this paradigm of setting String, getting `Optional<String>` which is incompatible with Kotlin. Can you please consider using Nullable/NotNull annotations instead? This approach is visible e.g. in `Input.getPlaceholder()/setPlaceholder()`, `Anchor.getTarget()`.

**Comment by pleku** [comment]
Not considering investing in first-class-support for Kotlin at the moment, so probably not going to do anything for this issue. 

If this is deemed an important thing to fix, I'm sure it will surface again.

**Comment by mvysny** [comment]
Fixed in Vaadin 24.3.0.alpha6 since `Input` now implements the `HasPlaceholder` interface which conforms to the bean spec.
