### ISSUE TITLE
flow-client-sources.jar contains source files from flow-server.jar

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#17020]
### Description of the bug

For example, the `VaadinServletRequest.java` is present both in `flow-client-sources.jar` and `flow-server-sources.jar`.

As a side-effect, it messes up with IDEA: https://youtrack.jetbrains.com/issue/IDEA-322302 .

### Expected behavior

The `VaadinServletRequest.java` (and all other files) should only be present in `flow-server-sources.jar` since that's where the corresponding class files are actually located.

In fact, the `flow-client-sources.jar` should be empty since `flow-client.jar` contains no Java `.class` files.

### Minimal reproducible example

1. Download https://repo1.maven.org/maven2/com/vaadin/flow-client/24.1.0/flow-client-24.1.0-sources.jar
2. Verify that it contains the `com/vaadin/flow/server/*.java` files.

### Versions

- Vaadin / Flow version: 24.1.0

**Comment by knoobie** [comment]
Sadly that's a known bug for over 5 years now.. see https://youtrack.jetbrains.com/issue/IDEA-192220/Maven-project-Idea-is-unable-to-compile-the-project-when-one-module-imports-other-modules-sources-as-resource. 

Everytime I contribute to flow I'm hacking stuff to get a "proper" developer exprience.. like removing specific parts from the build process or only opening sub projects. Total pain in the ***.

**Comment by caalador** [comment]
A small history walk for why this is so gave the result https://github.com/vaadin/flow/pull/309 
Perhaps eclipse should be retested to see if we can revert this...
