### ISSUE TITLE
CSS loading order differs in dev and production builds

### ISSUE THREAD

**Issue by leangermany** [vaadin/flow#17053]
### Description of the bug

Since 24.1.0 the loading order of the CSS source in the production build (both with prod bundle and without) differs from the order in dev build (with dev bundle) and the documentation [CSS Loading Order](https://vaadin.com/docs/latest/advanced/css-loading-order).

When Prod build is deployed I can see in the DOM that the `<link>` to `index-hash.css` is imported **before** the styles added by an addon (with `@CssImport`). When in dev, the `<link>` is after these styles.

So in dev first the imports are loaded and then the theme, but in prod it's the other way around.

_( Speculation: Could be caused by the fix of #16231 )_

Dev:
![image](https://github.com/vaadin/flow/assets/72908339/82bea3dc-4c4e-4305-82f0-870226f0677a)

Prod:
![image](https://github.com/vaadin/flow/assets/72908339/5938cb64-9575-497c-8652-167f2fbf53fa)

### Expected behavior

First the styles via @CssImport are added into DOM then the style of the theme. The theme classes are then higher in the hierarchical precedence due to CSS.

### Minimal reproducible example

Download a [new project](https://start.vaadin.com/app). Create a CSS class in `/frontend/my-style.css`. Import it on `MainLayout.java` with `@CssImport`. Add the class name to a component in the `MainLayout`. Add to the theme's `style.css` the same class but with another value (like color). Start dev server. The value of the theme is applied. Create a [production build](https://vaadin.com/docs/latest/production/production-build) and start it with `java -jar FILENAME`. The value of the CSS import is applied.

### Versions

- Vaadin / Flow version: 24.1.0
- Java version: 17
- OS version: Win10
- Application Server (if applicable): tomcat 10

**Comment by Artur-** [comment]
Oh joy. The workaround for this is to change `frontend/index.html` from e.g.
```
...
    </style>
    <!-- index.ts is included here automatically (either by the dev server or during the build) -->
  </head>
```
to
```
    </style>
    <something-stupid></something-stupid>
    <!-- index.ts is included here automatically (either by the dev server or during the build) -->
  </head>
```

**Comment by Artur-** [comment]
There is a test for exactly this case in CssLoadingViewIT, but it does not test the real world case as it happens to have an old 
```
<custom-style>
```
tag hanging around in its index.html. It is removed in #17118 and then the test will probably show the same problem described here
