### ISSUE TITLE
--lumo-font-size-m is applied to the html font-size breaking font scaling when a value different than 1rem is set

### ISSUE THREAD

**Issue by gert-dubois** [vaadin/flow#17070]
### Description of the bug

A change was made somewhere in Vaadin 24+ that applies a CSS rule `font-size = var(--lumo-font-size-m)` to both the body and html.
Since setting the font-size on the html sets the new reference baseline for all `rem` calculations deeper in the DOM tree, when you set the value of `--lumo-font-size-m` to a value above or below 1rem (we use 0.875rem), all font sizes get multiplied by this factor leading to unexpected font sizes.
For example, my browsers has a default font-size of `16px`, before when setting the  `--lumo-font-size-m` to `0.875rem` all body fonts would be `14px` (0.875 * 16px). Currently all body fonts come out at `12.25px` (0.875 * 0.875 * 16px)

We worked around this issue by adding a `font-size = 1rem` block to our `styles.css` file in our common theme

### Expected behavior

The font-size override should only be applied to the `body` tag. This will ensure all fonts behave as expected

### Minimal reproducible example

[broken-fonts.zip](https://github.com/vaadin/flow/files/11815523/broken-fonts.zip)

### Versions

- Vaadin / Flow version: 24.x
- Java version: 17
- OS version: Windows 11
- Browser version (if applicable): Firefox 114.0.1

**Comment by Artur-** [comment]
https://demo.vaadin.com/lumo-editor/ does not use Flow and uses a quite old version of the web components. Sounds odd that you could reproduce a new problem there

**Comment by gert-dubois** [comment]
I updated the issue with an example generated with the latest Vaadin starter.

**Comment by gert-dubois** [comment]
I also checked on the https://demo.vaadin.com/lumo-editor/ there is also a CSS fragment that sets the `font-size` on the html tag (this is why the problem is reproducible there).
In Vaadin 23 (our current production build) the same block targets `body, :host`
In Vaadin 24 that block target `body, html` instead (breaking the font sizes again)

**Comment by Artur-** [comment]
The change that causes this is https://github.com/vaadin/flow-components/commit/bfea1987f983c484cf59ee39f44ed60dd9cb39e5

It used to inject typography without rewriting it, adding `:host` also inside a `<style>` block but now it is injected like all other Lumo styles using https://github.com/vaadin/web-components/blob/bc3cb6506499308258c8fdd2949d5bd0a0611ac6/packages/vaadin-themable-mixin/register-styles.js#L14 so because the typography css in https://github.com/vaadin/web-components/blob/bc3cb6506499308258c8fdd2949d5bd0a0611ac6/packages/vaadin-lumo-styles/typography.js#L32-L34 contains `:host`, it will be replaced by `html` and the font family, size etc are applied to both `html` and `body`

**Comment by gert-dubois** [comment]
Setting the font-size on the html tag does change the reference size for rem calculations (see https://developer.mozilla.org/en-US/docs/Web/CSS/length)
So in this case either this is intended so the typography documentation needs to be updated, although all `--lumo-font-size-m` fonts still are calculated incorrectly in that case.
Or this is not intended and a change needs to be made how the font-size is set on the html tag vs the font-size for body/ui text

**Comment by TatuLund** [comment]
Check this too: https://stackoverflow.com/questions/76522146/how-to-reset-the-global-font-size-of-vaadin-flow-24-1-to-the-font-size-settings

**Comment by knoobie** [comment]
Note: there was a recent discussion about this in discord as well (looks more wide spread) https://discord.com/channels/732335336448852018/774369063454638141/1116679482821062737
