### ISSUE TITLE
Issues surfacing detailed exceptions

### ISSUE THREAD

**Issue by kaelensayth** [vaadin/flow#17090]
### Describe your motivation

Hi! I am having issues raising descriptive exceptions for my federated module. Webpack will spit out a generic error like 'Script error' into application insights without any additional details. Is there a way to get webpack to give more descriptive exceptions? I have tried setting my `mode` to `development`, setting `devtool` to `eval-source-map`, and customizing error formatting with `stats` but nothing seems to work

### Describe the solution you'd like

A way to raise detailed exceptions

**Comment by mshabarov** [comment]
Did you try change `stats.logging` as described in this article https://webpack.js.org/configuration/stats/#statslogging ?

**Comment by Artur-** [comment]
How is this related to Vaadin? It seems like a question about module federation and webpack

**Comment by kaelensayth** [comment]
Sorry I was writing this on the github for webpack, but it seems that it somehow posted here. So sorry about this!
