### ISSUE TITLE
Endless immediate push requests causing high CPU usage (long polling transport)

### ISSUE THREAD

**Issue by muhammetaltindal** [vaadin/flow#17127]
### Description of the bug

In certain situations with pending JS invocations the app starts quickly sending push requests one after the other. It never ends. If you assume enough UI instances running this may increase the CPU usage to a level where UI interaction is perceivably too slow.

In the following gif you can observe this behavior in the web dev tools when opening the minimal example below in the browser (in this case Chrome).

![push_reqs](https://github.com/vaadin/flow/assets/1894101/4b09e3f0-e096-4e94-80d7-f41586d99959)

### Expected behavior

The client should eventually stop sending so many requests to the server since all UI changes should have been communicated to the client after a few roundtrips.

### Minimal reproducible example

```java
@Push(transport = Transport.LONG_POLLING)
@Route("")
public class View extends Div {

  public View() {
    Button a = new Button("a");
    a.setVisible(false);
    add(a);
  }
}
```

### Versions

- Vaadin / Flow version: 14.10.2
- Java version: 17.0.6
- OS version: macOS 13.4.1

**Comment by muhammetaltindal** [comment]
Note (How to temporarily overcome this issue):

- copy the `UIInternals` class in your own project with the exact same package name
- change the `UIInternals#isDirty()` implementation to only look for pending JS invocations which actually would be sent to the client since their owner is effectively visible (i.e. the owner and all its parents are visible)
```java
public boolean isDirty() {
  return getStateTree().isDirty()
      || getPendingJavaScriptInvocations().filter(js -> js.getOwner().isVisible()).count() != 0;
}
```

**Comment by caalador** [comment]
Thank you for the issue. I'm closing it as done as there was a fix for this case just a couple days ago in #17109 that will come out with the next releases.
