### ISSUE TITLE
Version-Inconsistency date-fns.

### ISSUE THREAD

**Issue by LordTylus** [vaadin/flow#17126]
### Describe the bug

Recently I have the problem, that Vaadins Styling always breaks. Components aren't shown correctly, the CSS default style is absent and basically nothing works.

I have to do VaadinClean VaadinPrepareFrontend and VaadinBuildFrontend in my gradle tasks a couple of time before it functions correctly ONCE and on next startup it is completely broken again. Without ANY changes to the code. 

The Browser outputs a bunch of error messages as well:

```
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, return (function() { window.Vaadin.Flow.comboBoxConnector.initLazy(this)}).apply($0)'
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, return (function() { window.Vaadin.Flow.comboBoxConnector.initLazy(this)}).apply($0)'
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, return (function() { window.Vaadin.Flow.comboBoxConnector.initLazy(this)}).apply($0)'
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, return (function() { window.Vaadin.Flow.comboBoxConnector.initLazy(this)}).apply($0)'
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, $1, return $0.$connector.updateSize($1)'
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, $1, $2, $3, return $0.$connector.set($1,$2,$3)'
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, $1, $2, return $0.$connector.confirm($1,$2)'
TypeError: window.Vaadin.Flow.comboBoxConnector is undefined (http://127.0.0.1:8080/VAADIN/generated/jar-resources/FlowClient.js line 1090 > Function:3:22)
TypeError: window.Vaadin.Flow.comboBoxConnector is undefined (http://127.0.0.1:8080/VAADIN/generated/jar-resources/FlowClient.js line 1090 > Function:3:22)
TypeError: window.Vaadin.Flow.comboBoxConnector is undefined (http://127.0.0.1:8080/VAADIN/generated/jar-resources/FlowClient.js line 1090 > Function:3:22)
TypeError: window.Vaadin.Flow.comboBoxConnector is undefined (http://127.0.0.1:8080/VAADIN/generated/jar-resources/FlowClient.js line 1090 > Function:3:22)
TypeError: $0.$connector is undefined (http://127.0.0.1:8080/VAADIN/generated/jar-resources/FlowClient.js line 1090 > Function:3:1)
TypeError: $0.$connector is undefined (http://127.0.0.1:8080/VAADIN/generated/jar-resources/FlowClient.js line 1090 > Function:3:1)
TypeError: $0.$connector is undefined (http://127.0.0.1:8080/VAADIN/generated/jar-resources/FlowClient.js line 1090 > Function:3:1)
```

We figured this might have something to do with differences in the package.json, and concluded that it happened since we updated Vaadin to 23.3.10, which suffered from the Version inconsistency with vaadin router, which we use for site navigation. So, it made sense that things don't work, if the versions are inconsistent. 

Now I updated to 23.3.12 which supposedly has a fix for it. But now, I noticed that my package.json still is edited occasionally. 

It sometimes adds the "date-fns" with Version 2.29.3 and after a startup it removes it again. So basically, it looks like the vaadin router bug all over again, and we are unsure how to properly workaround it this time.

Could someone take a look at it? 

### Expected-behavior

my package.json does not get altered on build and startup. And if there is a need for it to be altered, I expect the same outcome every time. 

If in the end the Javascript errors we are getting are unrelated to the version inconsistencies we would create a separate report for that, but as of right now it points at that. 

### Reproduction

We use IntelliJ IDEA for working with Vaadin right now.

When executing

run gradlew vaadinClean vaadinPrepareFrontend vaadinBuildFrontend

you will notice that the package.json gets the aforementioned update of date-fns.

If you run it using spring boot in development mode, the package.json gets reverted back to where date-fns is not added.

### System Info

Windows 10 Pro (22H2) (Build 19045.2846)
Vaadin 23.3.12
Gradle 7.6
IntelliJ IDEA 2022.3.1 (CE)
Microsoft Edge 112.0.1722.58 
Mozilla Firefox 102.8.0esr (64-Bit)

**Comment by Artur-** [comment]
You have two separate issues here: The JS exceptions (about combobox) and the date-fns version. They are most likely not related.

The date-fns dependency for 2.29.3 is defined by DatePicker: https://github.com/vaadin/flow-components/blob/d2bd0b6a420a5efd55db5b0c19cc9b23d0592c4c/vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L80 so that should be in package.json

**Comment by Artur-** [comment]
The first thing you should do is try 23.3.15 though, that is the latest 23.3 version. There is no point in testing what might already have been fixed

**Comment by LordTylus** [comment]
Hello Artur,

thank you for your response. 

Indeed, since creation of the Issue quite a few new versions have been released. I will gladly confirm it with the latest version to see if the problem was already fixed in the meantime.

I found out that the second problem I described was also mentioned in https://github.com/vaadin/flow/issues/16725
The issue was closed due to inactivity, but we got it "fixed" by explicitly adding vaadin.whitelisted-packages with our relevant packages to our application.properties. I assume it has something to do with us using a special "dev" source set for launching out App. 

After verifying if 23.3.15 still has the problem or not, I will get back to you. I hope I can get to it today, and if not, Ill do so tomorrow.

**Comment by LordTylus** [comment]
Hello once again,

ich was able to check out 23.3.15 and as far as I can tell it seems to work fine. The package.json doesn't get edited when I build it via gradle, or launching it via spring from the IDE. So it appears it indeed magically fixed itself.

One thing I noticed though:
I use 23.3.15 but the package.json now contains many 23.3.16 versions. This is a bit odd, but for as long as it still works doesn't matter much to me.

**Comment by mcollovati** [comment]
The various components of Vaadin Platform have their own versioning, that may differ from platform.
If you look at the [Vaadin 23.3.15 release notes](https://github.com/vaadin/platform/releases/tag/23.3.15), you can see, for example, that Flow is 23.3.14, Flow components are 23.3.15 and Web components are 23.3.16.

**Comment by LordTylus** [comment]
I see. Well works fine now. Thanks for the info.
