### ISSUE TITLE
Add ability to disable auto-configured ViewAccessChecker

### ISSUE THREAD

**Issue by HerbertsVaadin** [vaadin/flow#17189]
### Describe your motivation

Using Vaadin Spring auto-configuration, and extending `VaadinWebSecurity` automatically enables the use of `ViewAccessChecker` (more specifically `SpringViewAccessChecker` in the `VaadinWebSecurity.configure(..)` method:

```java
    protected void configure(HttpSecurity http) throws Exception {
        ...
        // Enable view access control
        viewAccessChecker.enable();
    }
```

However, there is no good way (only reflection) to disable this `viewAccessChecker`. In a customer project, we are using custom access check logic through the use of `VaadinServiceInitListener`, so we need to disable the default one. 

### Describe the solution you'd like

It would be best if multiple solutions are provided.
1. `SpringSecurityAutoConfiguration.viewAccessChecker(..)` bean declaration should be conditional (`@ConditionalOnMissingBean`) so that we can provide our own implementation. 
2. `ViewAccessChecker` interface should have a `disable()` or an `enable(boolean)` method. 

### Describe alternatives you've considered

Executing the following code after `super.configure(http)` that uses reflection.
Disable existing view checker:
```java
    private void disableViewAccessChecker() throws NoSuchFieldException, IllegalAccessException {
        var enabledField = ViewAccessChecker.class.getDeclaredField("enabled");
        enabledField.setAccessible(true);
        try {
            enabledField.set(getViewAccessChecker(), false);
        } finally {
            enabledField.setAccessible(false);
        }
    }
```
or override existing view checker;
```java
    private void overrideViewAccessChecker() throws NoSuchFieldException, IllegalAccessException {
        var viewAccessChecker = VaadinWebSecurity.class.getDeclaredField("viewAccessChecker");
        viewAccessChecker.setAccessible(true);
        try {
            viewAccessChecker.set(this, new ViewAccessChecker(false));
        } finally {
            viewAccessChecker.setAccessible(false);
        }
    }
```

### Additional context

Currently using Vaadin 24.1 where this is a problem.

**Comment by mcollovati** [comment]
An additional solution may be providing a `vaadin.viewAccessChecker.enabled` configuration property, with default `true`

**Comment by Artur-** [comment]
I think the original idea was that you in most cases want to override how you check the access level (`AccessAnnotationChecker`) and not how the access checker is integrated with the router (`ViewAccessChecker`). `AccessAnnotationChecker` is defined using `@ConditionalOnMissingBean`

**Comment by HerbertsVaadin** [comment]
That might work for us (hard to tell at the moment, tricky to rewrite), but `ViewAccessChecker.beforeEnter()`
does have its own logic and assumptions about annotation use, thus for as, an error message like:
> Consider adding one of the following annotations to make the view accessible: @AnonymousAllowed, @PermitAll, @RolesAllowed."
Would be misleading, since we don't use those annotations.

**Comment by ILikePhysics** [comment]
I also requested the same thing in [#15818](https://github.com/vaadin/flow/issues/15818).
Another related issue where the user requires more easy way to customize (or replace) the ViewAccessChecker: [#16636](https://github.com/vaadin/flow/issues/16636)

**Comment by mcollovati** [comment]
Since Flow 24.3, ViewAccessChecker has been replaced by NavigationAccessControl.
Access control can now be disabled either by overriding the `VaadinWebSecurity.enableNavigationAccessControl()` method or by providing a custom `NavigationAccessControlConfigurer` bean

```java
    @Bean
    NavigationAccessControlConfigurer navigationAccessControlConfigurerCustomizer() {
        return new NavigationAccessControlConfigurer().disabled();
    }

```

See [documentation](https://vaadin.com/docs/latest/security/advanced-topics/navigation-access-control#spring-projects) for additional information.
