### ISSUE TITLE
Add ability to cancel DialogCloseActionEvent on ESC close

### ISSUE THREAD

**Issue by felix-office** [vaadin/flow#17193]
### Describe your motivation

I want to provide the users with the possibility to close dialogs with ESC but still show a confirm message if the binder has changes so no form input is lost. 

Currently the Dialog Component has the ability to add a listener to the DialogCloseActionEvent. In this Event there is no possibility to cancel the close and show a ConfirmDialog instead.

The BinderCrudEditor used for the CrudComponent has exactly the functionality I want to have but is not interoperable without the Crud.

### Describe the solution you'd like

Add the feature to cancel the dialog close initiated by the user.

### Describe alternatives you've considered

None

### Additional context

Is there anything else you can add about the proposal?

**Comment by mcollovati** [comment]
@felix-office Can you please provide and example of what is not working for you?

I did a test with the following code, and it seems to me that it works as expected:
- adding a  `DialogCloseActionListener` prevents the dialog to be close automatically
- in the listener, I can open a confirm dialog
- the confirm dialog listener closes the outer dialog if "Confirm" button is pressed

```java
        Dialog dialog = new Dialog("My dialog");
        dialog.setCloseOnEsc(true);
        dialog.addDialogCloseActionListener(ev -> {
            if (formIsDirty()) {
                ConfirmDialog confirmDialog = new ConfirmDialog("Unsaved changes", "Are you sure", "Confirm", confEv -> {
                    System.out.println("========= OK, close dialog");
                    ev.getSource().close();
                }, "Cancel", cancelEv -> {
                    System.out.println("========= Don't close");
                });
                confirmDialog.open();
            } else {
                ev.getSource().close();
            }
        });

```

**Comment by felix-office** [comment]
Hey @mcollovati, seems like I mixed up a condition. Seems to be fully working like your example now.
Thanks a lot. As this seems to work already, I'm going to close this request.
