### ISSUE TITLE
Enabling Push causes reload loop

### ISSUE THREAD

**Issue by benruehl** [vaadin/flow#17205]
### Description of the bug

When I add `@Push` to my `AppShellConfigurator` and visit the application website it loads the page but as soon as it is done it starts over and reloads the whole page again and again.

This results in a reload loop that seems to stop after a random amount of iterations. Sometimes it stops after 5 to 10 reloads, and sometimes it seems to not stop at all.

Some things I noticed:
- it works fine when run locally
- it occurs only on one of our two environments (but the hosting infrastructure is identical)
- it does not matter which push mode is used
- it does not matter which route is visited
- it does not matter if push is actually triggered; enabling it is enough to break it, even on an empty page
- we do not use jetty (I read about issues with Push in combination with jetty)

### Expected behavior

The website should load only once.

Or maybe you have an idea on what could cause such a behavior on our side, so we can investigate further.

### Minimal reproducible example

I cannot deliver much here, sorry.
That's because it only occurs on one of our deployed stages and I cannot reproduce it anywhere else. But I tested different applications on that environment and they all show the same issue.

The only thing that I need to add to one of our applications is this (kotlin):
```kotlin
@Push // <-- this 
class AppShell : AppShellConfigurator
```
That's it.

These are some recordings I made of how the issue looks like:

1. The following shows the issue on an almost empty website with Chrome's network traffic open. You can see that the page makes a few requests and then starts over. The gif itself is looping of course, but it shows like 8 reloads before the gif loop ends.
![vaadin-push-censored](https://github.com/vaadin/flow/assets/17962788/7a59b3d0-b6f6-4b59-b4a7-ae0f9237f574)

2. When I pause the reload and have a look at the last request (before everything starts over), I can see that it is a query of the original website. So it is basically identical to the first request made when I enter the URL in the browser. Just that this time it originates from Vaadin itself, more precisely from `vaadinPush-min.js` (see on the right). Looks like this is causing the page reload.
![vaadin-initiator-censored](https://github.com/vaadin/flow/assets/17962788/0642277b-3980-4742-a994-ae61858b924c)

Any hints on how to address this are welcome.

### Versions

- Vaadin / Flow version: 23.3.15
- Java version: 11
- OS version: Amazon Linux
- Browser version: Chrome 114 ARM (currently latest)
- Application Server: Spring Boot / Tomcat

**Comment by mcollovati** [comment]
Hi, thanks for the ticket.
The version you mentioned (23.3.15) is Vaadin or Flow?
I'm asking because Vaadin 23.3.16 (that ships Flow 23.3.15) has a fix for push when there are invisible components.
You may try upgrading to Vaadin 23.3.16

**Comment by benruehl** [comment]
Thanks for the quick response.

I see what you mean. I thought the versions were identical, but you are right, it was Vaadin 23.3.15 I was talking about which comes with Flow 23.3.14.
Anyway, I did the upgrade to Vaadin 23.3.16 / Flow 23.3.15 but it did not change anything, unfortunately.

**Comment by mcollovati** [comment]
Thanks for confirming the version and testing with the latest.
It's hard to say what is going on here.
Nothing on the server and browser console logs?

**Comment by mcollovati** [comment]
Page reload may happen because of session expiration that can be caused by for example by cookie name or path issues behind a reverse-proxy.
Could you please also post the contents of the failing UIDL (`?v-r=uidl&....`) and previous `push` requests?

**Comment by benruehl** [comment]
### Browser console
The only line in there is "Vaadin push loaded" which gets reset and reprinted on every reload.

![vaadin-browser-console](https://github.com/vaadin/flow/assets/17962788/4858d5fe-7cac-4eeb-ad10-36d936982b65)

### Server logs
Nothing. Not a single line related to Vaadin.

### UIDL `(?v-r=uidl&....)`
Please note, this request is not really failing. It is just colored red because it got marked as "canceled" when I paused the page reload to take screenshots. In the gif you can see that it looks fine.

![vaadin-uidl](https://github.com/vaadin/flow/assets/17962788/1d04664b-e0cc-4493-ac52-459797c40a39)
![vaadin-uidl-2](https://github.com/vaadin/flow/assets/17962788/1cb0c649-f0bb-41af-af19-876e6c5483aa)

The push requests below the canceled requests do exist only because I paused the reload. They are added in a regular interval. I think we can ignore them.

### Push requests
Last push request payload:
![vaadin-push-1](https://github.com/vaadin/flow/assets/17962788/77b47f7a-6fa2-44ab-aaff-794ddf9176ce)

Last push request messages:
![vaadin-push-2](https://github.com/vaadin/flow/assets/17962788/97a938d5-76f4-4303-bb1e-4321d5c7ee13)

**Comment by mcollovati** [comment]
Thanks for the info.
It looks like the session for some reason expires after the first UIDL request.
Can you check if the session cookie carries the same value in the HTTP requests?

**Comment by mcollovati** [comment]
On the server side, you can try to set the log level to DEBUG for `com.vaadin` and  `org.atmosphere`. Maybe we can collect some additional information

**Comment by benruehl** [comment]
Ok thanks, now we got some server logs. All debug level. Read from bottom to top.

![image](https://github.com/vaadin/flow/assets/17962788/2ae32c81-f115-43a3-843e-b83a993c2946)


Session cookie looks like this:

![image](https://github.com/vaadin/flow/assets/17962788/ab105179-1c5e-4cee-b2fc-1aaa9afbdefb)

Its value is different for every request. Looks like each response value is used for the next request which then receives a new response value again. That applies to every request though, not just the UIDL requests.

**Comment by mcollovati** [comment]
Looks like there's something that invalidates the session on the server side.
Or the JSESSIONID cookie is not correctly propagated to the server by the reverse-proxy.
I would first try to investigate the second case, since you said that this issue happens only on one particular deployment (if I understood correctly, the same application is deployed on several servers, but only one is failing)

**Comment by benruehl** [comment]
I ran the application locally again and found that the `JSESSIONID` cookie behaves just the same way. But here I don't get the reloads. How is this cookie supposed to look like?

Regarding the second case, it is weird that the reload loop often ends after a few iterations. So if some reverse-proxy is consuming the cookies why does it stop and pass them at some point?
I'll try to get some more info on that matter though.

I just organized a few people to test the behavior and for some it didn't even show for the first 10 tries or so. Eventually, all of us had seen the issue at least a few times. But while it occurs basically 100% of the time for me, for some others it occurred more like 50% of the time.
As soon as the loop ends, the application becomes usable. Then, one can navigate to different routes and do stuff without reloads happening.

**Comment by mcollovati** [comment]
> I ran the application locally again and found that the JSESSIONID cookie behaves just the same way. But here I don't get the reloads. How is this cookie supposed to look like?

The JSESSIONID should not change between requests, except after a successful login when a new cookie may be generated.
I cannot replicate the described behavior locally.

Do you have a custom Spring Security configuration?
One thing that comes to mind is that the session is recreated for some reason when accessing static resources because of some security setting.

**Comment by benruehl** [comment]
Yes, we have a custom Spring Security config.
The only thing I can find in there that is related to sessions is this line:

```kotlin
.sessionManagement().sessionCreationPolicy(STATELESS)
```

**Comment by benruehl** [comment]
I did some tests with our Spring Security configuration and it seems to be resolved now.

Changing
```kotlin
.sessionManagement().sessionCreationPolicy(STATELESS)
```
to
```kotlin
.sessionManagement().sessionCreationPolicy(NEVER) // or IF_REQUIRED
```
made it work.

The server logs also show that after this change the `JSESSIONID` cookie has the same value for every request.

It is still unclear though why this was not an issue on our other hosting environment which uses the same security configuration.

Thank you @mcollovati for your help figuring this out!
