### ISSUE TITLE
Push websocket disconnects repeatedly and alerts user

### ISSUE THREAD

**Issue by mijutu** [vaadin/flow#17215]
### Description of the bug

Push with websocket transport disconnects and reconnects repeatedly showing "Connection lost, trying to reconnect..." and then"Online".

This happens once or twice per minute when user does nothing. 

### Expected behavior

Websocket should keep connected for several minutes.

### Minimal reproducible example

* Download Vaadin 24 plain java hello world starter from https://vaadin.com/hello-world-starters
* Edit AppShell.java: Add `@Push(transport = Transport.WEBSOCKET)`
* Run it with mvn jetty:run and open localhost:8080 with firefox or chromium
* Wait, do nothing
* After about 30 seconds websocket disconnects and browser shows "Connection lost, trying to reconnect..." and then "Online" on the top of the page.

### Versions

- Vaadin / Flow version: 24.1.3
- Java version: 17.0.7
- OS version: Debian 12
- Browser version: Firefox 102.13.0esr, Chromium 114.0.5735.198
- Application Server (if applicable): Jetty 11.0.14

**Comment by mijutu** [comment]
I tried setting org.atmosphere.websocket.maxIdleTime to 40 and 50 seconds and it worked. Now I get "Connection lost, trying to reconnect" after 40 or 50 seconds depending on the setting.

I guess better way would be to add some kind of keepalive to make the websocket not timeout at all.  Then we could keep the timeout setting short. It would also prevent nat routers and reverse proxies from closing the connection too early.

**Comment by mcollovati** [comment]
Just for the record, if I didn't get it wrong, the default idle timeout in Jetty 9.4 was 5 minutes

**Comment by mshabarov** [comment]
I marked this issue as an enhancement for further research on what would be the optimal value for maxIdleTime.
Not sure the "bug" resolution is proper here, because it actually doesn't break the apps.
