### ISSUE TITLE
@CssImport of the add-on gets ignored in production mode on the first load

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow#17221]
### Description of the bug

I have an add-on that has some styles of its own, say, e.g. TwinColSelect

```
@Tag("twin-col-select")
@CssImport(value = "./twincolselect.css")
@CssImport(value = "./twincolselect-checkbox.css", themeFor = "vaadin-checkbox")
public class TwinColSelect<T> extends AbstractField<TwinColSelect<T>, Set<T>>
...
}
```

This worked ok in Vaadin 24.0, but styles fails to load in Vaadin 24.1.3 in production mode when using the add-on in actual app. However in Vaadin 24.1.3 styles are loaded ok in development mode.

Production mode looks like this

![image](https://github.com/vaadin/flow/assets/14309836/2a9055fb-233f-420c-a140-54301a4765ee)

### Expected behavior

The development mode works, I would expect to see the same in production mode

![image](https://github.com/vaadin/flow/assets/14309836/bfa43784-9534-4668-9767-adbc10a56ab6)

### Minimal reproducible example

See above

### Versions

- Vaadin / Flow version: 24.1.3
- Java version: 17

**Comment by TatuLund** [comment]
Furher info, I can see the following warning in the console log in production mode

![image](https://github.com/vaadin/flow/assets/14309836/9e45c9b1-1617-454a-ab93-da3d0a4d8416)

Also, if I reload the page, the styles are being loaded. I.e. the bug happens only at the first load of the view.

**Comment by knoobie** [comment]
I'm wondering.. does this also effect 24.1.1? Or could this be related to https://github.com/vaadin/flow/pull/17129/files?

**Comment by mcollovati** [comment]
@TatuLund I did a quick test adding TwinColSelect add-on to the flow spring starter application.
I built for production and the styles seem to be correct, and I cannot see the error on the console.

Could you provide an example project that reproduces the issue? Maybe it happens when mixing different add-ons or with a some custom theme settings?

**Comment by mcollovati** [comment]
Tried also that way, but I'm still not able to reproduce

**Comment by mcollovati** [comment]
Ok, I can reproduce the issue if I load a page with a CheckBox component and then navigate to the route with the TwinColSelect add-on

**Comment by mcollovati** [comment]
Same issue also with Vaadin 24.1.1 and 24.1.0
