### ISSUE TITLE
Incorrect handling of empty QueryParameters

### ISSUE THREAD

**Issue by AB-xdev** [vaadin/flow#17287]
### Description of the bug

When getting the query parameters of a view these are never empty and always contain an empty String Queryparameter:
![grafik](https://github.com/vaadin/flow/assets/45384811/b7674067-2481-4c05-b26d-1a7493576a93)

After a lot of debugging I found out that the parameters come directly from the client:
![grafik](https://github.com/vaadin/flow/assets/45384811/f3469380-5ff8-456e-a7bb-857edf16741d)

https://github.com/vaadin/flow/blob/217f89c4546e8464939727b0a1533457a9df7769/flow-client/src/main/frontend/Flow.ts#L378

This causes misbehavior when these Queryparameters are e.g. used with ``RouterLinks``:
```java
@Route("test")
public class MainView extends VerticalLayout implements BeforeEnterObserver {

    final RouterLink routerLink = new RouterLink();

    public MainView() {
        add(routerLink);
    }

    @Override
    public void beforeEnter(BeforeEnterEvent beforeEnterEvent) {
        routerLink.setRoute(MainView.class);
        routerLink.setQueryParameters(beforeEnterEvent.getLocation().getQueryParameters());

        System.out.println(routerLink.getHref());
    }
}
```
→ prints out ``test?`` but should be ``test`` as there are no query parameters

### Expected behavior

If there are no query parameters the ``QueryParameters``-object should also be empty.

I would suggest the following improvements:
* When parsing / creating ``QueryParameters`` it should be checked if the string is empty/whitespaceonly. If so the internal map should also be empty
* The flow-client should not report non-existent queryparameters to the server

### Minimal reproducible example

See above

### Versions

- Vaadin / Flow version: 23.3+
- Java version: -
- OS version: -
- Browser version (if applicable): -
- Application Server (if applicable): -
- IDE (if applicable): -

**Comment by mcollovati** [comment]
I can spot two bugs here:
* QueryParameters for an empty string should be empty, as reported
* RouterLink should not add query string for empty QueryParameters

**Comment by AB-xdev** [comment]
Very nice. Thank you for the quick fix :)
