### ISSUE TITLE
com.vaadin.flow.server.ExecutionFailedException: npm install. Some dependencies are not installed

### ISSUE THREAD

**Issue by Dharmik2510** [vaadin/flow#17302]
### Description of the bug

Using,
Spring boot: 3.2.1
Vaadin: 24.1.4
I am using below command on my local machine and everything is working fine.

```
gradle clean vaadinBuildFrontend build -DproductionMode=true -x test --stacktrace
```

However, 
when same command is executed in gitlab pipeline it throws an exception/error:
```
com.vaadin.flow.server.ExecutionFailedException: npm install. Some dependencies are not installed.
```

I am also getting following logs:

```
npm ERR ! code EPROTO
npm ERR ! request to https://registery.npmjs.org/@open-wc%2fdedupe-mixin failed
```

### Expected behavior

Application should successfully build and compile in gitlab as well.

### Minimal reproducible example

NA

### Versions

- Vaadin / Flow version: 24.1.4
- Java version: 17
- OS version: 
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable): IntelliJ

**Comment by mcollovati** [comment]
By searching a bit, it looks like this issue may be related to connections behind a proxy server.
If this is your case, you can take a look at the documentation to properly setup the proxy server settings on your CI system https://vaadin.com/docs/latest/configuration/development-mode/node-js#proxy-settings-for-downloading-the-front-end-toolchain

**Comment by Dharmik2510** [comment]
It was working before without any problem. I do not know what's happening.

**Comment by mcollovati** [comment]
Taking a more in-depth look at the failed URL `https://registery.npmjs.org/@open-wc%2fdedupe-mixin`
It seems there's a typo `registEry` instead of `registry`

**Comment by mcollovati** [comment]
All the information I have found points to some proxy issue with NPM.
I currently have no other ideas other than checking the proxy settings

**Comment by mcollovati** [comment]
Nothing else on the logs?

**Comment by Dharmik2510** [comment]
I did set 
```
export no_proxy="registry.npmjs.org" 
```
in gitlab pipeline.

Not it gives me following logs:

```
npm WARN Could not resolve dependency
npm WARN peerOptional @open-wc/dedupe-mixin@"1.3.1" from @Vaadin/bundles@24.1.4
npm WARN ERESOLVE overriding peer dependency
npm WARN found: @open-wc/deduoe-mixin@undefined

npm ERR code E503
npm ERR 503 Service unavailable - GET https://registry.npmjs.org/rollup
```

**Comment by mcollovati** [comment]
The URL `https://registry.npmjs.org/rollup` works for me locally. Maybe some temporary issue on npm registry?

**Comment by Dharmik2510** [comment]
I tried but still not working!

**Comment by mcollovati** [comment]
It may definitely be some issue with npm registry: https://status.npmjs.org/

![image](https://github.com/vaadin/flow/assets/4648894/0f36096e-725a-4cf2-b24a-826a24d258be)

**Comment by Dharmik2510** [comment]
The server status is up now. However, getting the same error.

npm ERR ! code EPROTO
npm ERR ! request to https://registery.npmjs.org/rollup failed

**Comment by Dharmik2510** [comment]
When I see my pipeline job logs it says:
```
"345 error pnpm":{

"message":{
"code": "ERR_PNPM_NO_IMPORTER_MANIFEST_FOUND"
},
"err":{
"message": "No package.json was found in "/home/{user}/dev/{project-repo}/build/flow-frontend/form"
}
```

**Comment by mshabarov** [comment]
I propose to close this ticket and follow https://github.com/vaadin/flow/issues/17318 for further investigation and discussions, as it looks like a duplicate.
