### ISSUE TITLE
Font is not loaded when hotdeploy=false

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow#17314]
### Description of the bug

I want to use a local font in a theme, I'm following the documentation here: https://vaadin.com/docs/latest/styling/application-theme#images-fonts

When I start the application with vaadin.frontend.hotdeploy=false the font is not loaded.
![image](https://github.com/vaadin/flow/assets/51313578/b9f02722-1745-4895-8a4c-4785ee93af72)

If I start the application with vaadin.frontend.hotdeploy=true the font is loaded.
![image](https://github.com/vaadin/flow/assets/51313578/7c28cbf8-8784-4e4c-a4e3-b2adca5f7bad)

### Expected behavior

The font should be loaded. 

### Minimal reproducible example

Here is the example: https://github.com/jcgueriaud1/spring-proxy-issue/tree/fonts-v24
```
@font-face {
    font-family: Luciole;
    font-weight: 400;
    font-style: normal;
    src: local("Luciole Regular"),local("Luciole-Regular"),url(./fonts/Luciole-Regular.woff2) format("woff2"),url(./fonts/Luciole-Regular.woff) format("woff");
}
```

### Versions

- Vaadin / Flow version: 24.1.4
- Java version: 17

**Comment by caalador** [comment]
In bundle mode there is no url fixing which is why the font doesn't load.
As a workaround the font urls can be defined with the theme beginning like `url(themes/myapp/fonts/Luciole-Regular.woff2)` which works in all execution modes.

**Comment by caalador** [comment]
Another fix is havingthe url to contain `'` or `"` e.g. `url('./fonts/Luciole-Bold.woff2') ` this also fixes the issue when running with devBundle without having the need to target the theme folder and theme name.
