### ISSUE TITLE
Theme get not loaded when views package location get defined with @EnableVaadin

### ISSUE THREAD

**Issue by egloffmark** [vaadin/flow#17317]
### Description of the bug

I like to have my view in another package then the main Vaadin Spring Boot Application. For this I am using the `@EnableVaadin`annotation at the SpringBootApplicaiton class. But when I apply this then the `@Theme` annotation at my application class get ignored and the stylesheet not loaded

e.g. package locations
- com.example.app
- com.example.views
- com.example.config

My Application 
```
package com.example.app;
...
@SpringBootApplication(scanBasePackages = "com.example.config" )
@EnableVaadin(value = "com.example.views")
@Theme(value = "my-theme")
public class MyApplication implements AppShellConfigurator, CommandLineRunner {
....
}
```

### Expected behavior

The Theme should get loaded at the application start  time

### Minimal reproducible example

1. Simple download the example Vaadin Flow app https://vaadin.com/docs/latest/guide/quick-start
2. Restructure the packages as outlined above so that everything is in its own root packages
3. Update the annotations 
4. Run the application

### Versions

- Vaadin / Flow version: 24.1.4
- Java version: 17
- OS version: Ubuntu
- Browser version (if applicable): Firefox
- Application Server (if applicable): Spring Boot 3.0.5 - embedded tomcat
- IDE (if applicable): Eclipse 2023

**Comment by knoobie** [comment]
Because of the EnableVaadin annotation, ONLY the added package is scanned by Vaadin for Vasdin related stuff. Therefore your theme annotation in the other package is not found and applied anymore. You have to specify your multiple values to the annotation (e.g. adding "com.example.app" as second entry) or move all Vaadin related code to your views, including the AppShell with the Theme annotation.

**Comment by egloffmark** [comment]
Thank you, yes this worked. 

```
package com.example.app;
...
@SpringBootApplication(scanBasePackages = "com.example.config" )
@EnableVaadin(value = {"com.example.views", "com.example.app"})
@Theme(value = "my-theme")
public class MyApplication implements AppShellConfigurator, CommandLineRunner {
....
}
```
