### ISSUE TITLE
Vaadin 24 and Node 18 incompatibility issue behind company firewall

### ISSUE THREAD

**Issue by Dharmik2510** [vaadin/flow#17318]
### Description of the bug

I am trying to build and test my Vaadin 24 application on gitlab and my project is running behind company firewall.

I am getting following error:

```
npm Err ! request to https://registry.npmjs.org failed,
reason: write EPROTO :error:0A00152:SSL routines:final_renegotiation:unsafe legacy renegotiation disabled:

I strongly suspect that this is the issue with node v18.
```

### Expected behavior

Application should run

### Minimal reproducible example

NA

### Versions

- Vaadin / Flow version:24.1.4
- Java version:17
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable): IntelliJ

**Comment by mcollovati** [comment]
It could be that the proxy server uses legacy SSL options, as pointed out here https://github.com/npm/cli/issues/6070.

There's a suggestion on how to workaround the prion that issue. You may give it a try and see if it works for you.

**Comment by mcollovati** [comment]
This looks like a continuation of #17302

**Comment by mshabarov** [comment]
Please comment on this issue or create a new one, if this problem is still present for you. Closed because of no response.
