### ISSUE TITLE
Pick Jetty 10 fix to Vaadin Atmosphere fork version 2.7

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#17326]
### Description of the bug

Pick the following bug-fix for the Jetty 10 from https://github.com/Atmosphere/atmosphere/commit/3be649fdd8e643dd252e55aca460be96c13e6125 to https://github.com/vaadin/atmosphere/tree/2.7.3, release a new version and upgrade it for Flow versions used in Vaadin 14/22/23.

**Comment by mshabarov** [comment]
The issue was triaged and currently added to the backlog priority queue for further investigation.

**Comment by cliviu** [comment]
It looks like the Push with WebSockets is not supported with Jetty10/Vaadin 23.3.24. 

AsynchronousProcessor         |WARN |Websocket protocol not supported

**Comment by mshabarov** [comment]
Reopened for further investigation, because of https://github.com/vaadin/flow/issues/17326#issuecomment-1727549094

**Comment by mcollovati** [comment]
Just tested on our starter project with Vaadin 23.3.24 and it looks like to work correctly

```
Atmosphere is using async support: org.atmosphere.container.JSR356AsyncSupport running under container: jetty/10.0.11 using javax.servlet/3.0 and jsr356/WebSocket API
```

**Comment by mcollovati** [comment]
I tested running Jetty through `jetty-maven-plugin`.
@cliviu are you starting an embedded jetty instance in your application? Maybe some dependency missing like `org.eclipse.jetty.websocket:websocket-javax-server`?

**Comment by cliviu** [comment]
@mcollovati , thanks for your quick reply. After adding the missing dependency, atmosphere  is completely silent, i cannot find the  `|INFO |Initializing AtmosphereFramework ` log entry. Do you have some example somewhere, maybe I miss some settings. Thank you!

**Comment by mcollovati** [comment]
Do you perhaps have set log level to warn for atmosphere? What logger library are you using and how the configuration looks like?

**Comment by cliviu** [comment]
> Do you perhaps have set log level to warn for atmosphere? What logger library are you using and how the configuration looks like?

No, the logging is fine, the line was printed before.  What I have changed is  this line `JavaxWebSocketServletContainerInitializer.configure(this, null);`  in my class which  extends 
`org.eclipse.jetty.webapp.WebAppContext `. Before it was ` JettyWebSocketServletContainerInitializer.configure(this, null);`
`

**Comment by mcollovati** [comment]
I do not have an example with embedded jetty, but you can take a look at @mvysny  [vaadin-boot](https://github.com/mvysny/vaadin-boot/tree/10.x)

https://github.com/mvysny/vaadin-boot/blob/10.x/vaadin-boot/src/main/java/com/github/mvysny/vaadinboot/VaadinBoot.java

**Comment by cliviu** [comment]
hey @mcollovati , you were right, it was really a logging problem, some slf4j-log4j2  bridge related problem. Everything works fine now, thanks for your support!

**Comment by mcollovati** [comment]
@cliviu Glad to hear!
I close the ticket since the fix seems to work correctly.

**Comment by cliviu** [comment]
@mcollovati , do you know if  native jetty web socket is also supported for push ? 
having this dependency `org.eclipse.jetty.websocket:websocket-jetty-server`
instead of `org.eclipse.jetty.websocket:websocket-javax-server`

**Comment by mcollovati** [comment]
Sorry, I don't know if atmosphere is compatible with native jetty web socket.

**Comment by cliviu** [comment]
okay, thanks!
