### ISSUE TITLE
Email Pattern accepts double dot between domain and tld

### ISSUE THREAD

**Issue by gronono** [vaadin/flow#17333]
### Description of the bug

I'm using an EmailField without overriding the  validation pattern.
An email like "example@gmail..com" is not considered invalid (using `emailField.isInvalid()`)

I got an exception from javax.mail.internet.InternetAddress when I send an email to this address:

```
Caused by: javax.mail.internet.AddressException: Domain contains dot-dot
at javax.mail.internet.InternetAddress.checkAddress(InternetAddress.java:1413) ~[jakarta.mail-1.6.7.jar!/:1.6.7]
at javax.mail.internet.InternetAddress.parse(InternetAddress.java:1191) ~[jakarta.mail-1.6.7.jar!/:1.6.7]
at javax.mail.internet.InternetAddress.parse(InternetAddress.java:728) ~[jakarta.mail-1.6.7.jar!/:1.6.7]
at javax.mail.internet.InternetAddress.parse(InternetAddress.java:705) ~[jakarta.mail-1.6.7.jar!/:1.6.7]
```

### Expected behavior

The method `isInvalid()` should return true when email address contains multiple dots (like example@gmail..com)

### Minimal reproducible example

```java
var emailField = new EmailField("Email");
emailField.setValue("example@gmail..com");
Notification.show(emailField.getValue() + " : " + emailField.isInvalid());
```

### Versions

- Vaadin / Flow version: 23.1.2 
- Java version: 17
- OS version: Docker image from eclipse-temurin:17-jdk-focal
- Browser version (if applicable): 
- Application Server (if applicable): Embedded Tomcat with Spring Boot 2.6.7
- IDE (if applicable):

**Comment by mshabarov** [comment]
`EmailField` allows two consecutive dots in the domain, also `EmailValidator` uses the same email pattern. Thus, the fix should go to both Flow and Flow-components (EmailField).

@yuriy-fix FYI

**Comment by gronono** [comment]
@mshabarov I will try to make a merge request for you by the end of the week

**Comment by gronono** [comment]
The new Regex : 
```
private static final String PATTERN = "^" + "([a-zA-Z0-9_\\.\\-+])+" // local
            + "@" + "([a-zA-Z0-9-]+\\.)+" // domain with the separator dot before the tld
            + "[a-zA-Z0-9-]{2,}$" // tld
            + "$";
```
and the method for testing it: 
```
    @Test
    public void testDomainWithDotDotFails() {
        EmailValidator v = validator("domains containing dot dot should fail");
        assertFails("hello@sample..com", v);
        assertFails("hello@samp..le..com", v);
    }
```

Can i reference EmailValidator pattern into EmailField class to remove its duplication ?
