### ISSUE TITLE
Add a method to Binder to check if a specific Binding changed

### ISSUE THREAD

**Issue by felix-office** [vaadin/flow#17395]
### Describe your motivation

Inside our binder, we use a custom field for address input. If the values in it change, I need to persist the new address object before I can persist the binder bean. So I need to be able to find out if the address field has changed. Binder#hasChanged() only tells me if any field of the binder has changed.

### Describe the solution you'd like

The binder already has a set of changed bindings https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/data/Binder.java#L1536. 
We can use this to add a method hasChanges(Binding<BEAN, ?> binding).

In the perfect word it would also remove the "change state" if the value is changed back to the original one but I don't see that this is currently a feature of the Binder.

### Describe alternatives you've considered

Building the logic myself using the value change listener.

### Additional context

Is there anything else you can add about the proposal?

**Comment by benedikt-roth** [comment]
Hello, is this still needed? I would like to contribute to the project and can have a look at it.

**Comment by knoobie** [comment]
Still up to grab

**Comment by knoobie** [comment]
@mshabarov sounds like you should answer this :)

**Comment by mshabarov** [comment]
@benedikt-roth thank you very much for willing contribute! 👍 
Yes, this is still good to have in Flow.
This feature should be contributed to Vaadin Flow repo, to the [Binder class](https://github.com/vaadin/flow/blob/main/flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java) (not only there, but this is a main API).

Vaadin Flow team will review it as soon as we can. Feel free to post even a draft PR or incomplete PR, will try to help.

@knoobie thanks for pinging me, I missed the notification for this.
