### ISSUE TITLE
Introduce a small delay between test attempts.

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#1742]
Currently when an integration test fails, the same test is executed again 2 more times. But there aren't any delay between the attempts, making the retries useless when the problem is a connection timeout to a remote service.

That can be seem in this build, for example: http://r2d2.devnet.vaadin.com/viewLog.html?tab=buildLog&buildTypeId=Flow_FlowSnapshot&buildId=154287#_state=10555

There are 3 attempts to run the RouterLinkIT in the same second, and all three fail due to a `Session [707f8230-aebc-47ca-9ed9-bcf928247752] was terminated due to SO_TIMEOUT`.

**Comment by pleku** [comment]
Since nobody knew whether this is an issue or not, probably not an issue anymore.
