### ISSUE TITLE
Upgrade Gradle plug-in to Gradle 8

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#17446]
### Describe your motivation

Upgrade Vaadin Gradle plug-in to use Gradle 8 (latest 8.2.1 at the time when issue created).
At the moment, if I change the version in [gradle-wrapper.properties](https://github.com/vaadin/flow/blob/main/flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.properties) and run `./gradlew wrapper` in `flow-plugins/flow-gradle-plugin`, I get this error:

```
1: Task failed with an exception.
-----------
* Where:
Build file '.../flow/flow-plugins/flow-gradle-plugin/build.gradle' line: 47

* What went wrong:
A problem occurred evaluating root project 'flow-gradle-plugin'.
> Could not set unknown property 'classifier' for task ':javadocJar' of type org.gradle.api.tasks.bundling.Jar.
```

If I remove 
```
task javadocJar(type: Jar, dependsOn: dokkaJavadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}
```
the command completes fine and building the add-on also completes fine.

**Comment by caalador** [comment]
The Jar target `classifier` is deprecatd and removed so it needs to read:
```
task javadocJar(type: Jar, dependsOn: dokkaJavadoc) {
    archiveClassifier = 'javadoc'
    from javadoc.destinationDir
}
```
Also the dokka version could be updated at the same time from `1.7.20` to `1.8.20`
