### ISSUE TITLE
PiT 24.2: improve message when app does not have any view/route

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#17441]
### Description of the bug

When I create a new application from scratch, for instance by using spring initializer, when running it the first time, message in browser should indicate that there are no flow views marked with the route value

![Screenshot 2023-08-14 at 12 46 06](https://github.com/vaadin/flow/assets/161853/3704c808-bb00-49bd-ae19-c5513bad952b)

### Expected behavior

A better message like

```
The application does not have any Flow View marked with the Route annotation.
Please create your first view as it is explain at  
https://vaadin.com/docs/latest/guide/quick-start#add-code
```

### Minimal reproducible example

1. download a maven project from https://start.spring.io/ (Select maven, and add Vaadin and spring-dev-tools dependencies)
2. run the app in dev mode with `./mvnw spring-boot:run`, or in prod mode by running `./mvnw package -Production; java -jar target/*.jar` 
3. go to http://localhost:8080

### Versions

- Vaadin / Flow version: 24 and previous

**Comment by manolo** [comment]
No, in development mode it shows the same screen, unless there are routes defined that they are listed, so
- when in dev mode you go to '/' or '/foo' and there is no such views, but there is '/bar' this is listed
- when in dev mode you go to any route but there are no routes at all, the message is the same that in the screenshot above

**Comment by mshabarov** [comment]
We have a "no routes" html page in Flow here `flow-server/src/main/resources/com/vaadin/flow/router/NoRoutesError_dev.html`. Not sure why it is now shown in this case.

**Comment by caalador** [comment]
What is the version that spring gave when the message was as shown?

I just generated and got `<vaadin.version>24.1.4</vaadin.version>` and see the expected message
![image](https://github.com/vaadin/flow/assets/2726090/37c66ea6-cee4-4c73-8aac-f16518192d1e)

Also got the same for 24.2-SNAPSHOT

**Comment by manolo** [comment]
It does not show that page to me see this [video](https://recordit.co/PXXSiEWDyW)

**Comment by manolo** [comment]
Ok, in dev mode it shows the page, so I think it's not an issue any more
