### ISSUE TITLE
Select.setEmptySelectionAllowed(true) throws NullPointerException

### ISSUE THREAD

**Issue by osawyerr** [vaadin/flow#17456]
### Description of the bug

Setting ``Select.setEmptySelectionAllowed(true)`` throws a NullPointerException. Example below - note that regions in ``region.setItems()`` is an empty ``List``

```java
Select <Region >region = new Select<>();
region.setLabel("Region");
region.setItems(regions);
region.setPlaceholder("Select a region");
region.setItemLabelGenerator(Region::getName);
region.setEmptySelectionCaption("Unknown size");
region.setEmptySelectionAllowed(true); //throws Exception
```

### Expected behavior

NullPointerException shouldn't be thrown.

### Minimal reproducible example

```java
Select <Region >region = new Select<>();
region.setLabel("Region");
region.setItems(regions);
region.setPlaceholder("Select a region");
region.setItemLabelGenerator(Region::getName);
region.setEmptySelectionCaption("Unknown size");
region.setEmptySelectionAllowed(true); //throws Exception
```

### Versions

- Vaadin / Flow version: 24.1.4
- Java version: 17
- OS version: MacOS
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by caalador** [comment]
Hi.

The thrown nullpointer is due to your ItemLabelGenerator not taking into account the null value from the empty selection.

This is documented in for the custom label in:
https://vaadin.com/docs/latest/components/select#custom-item-label

```
When using setItemLabelGenerator() in combination with setEmptySelectionAllowed(), ensure that the implementation is capable of handling null values, as the empty selection item has the value null.
```
