### ISSUE TITLE
Dev tools websocket connection is not reopened

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#17476]
### Description of the bug

When running with Jetty (mvn jetty:run), the websocket connection is closed after 30s and never reopened. Most features in the dev tools window are thus only available for 30 seconds after a refresh.

### Expected behavior

The connection is re-established

### Minimal reproducible example

```
flow-tests/test-dev-mode % mvn jetty:run
```
in this project

### Versions

- Vaadin / Flow version: main

**Comment by mshabarov** [comment]
Does it mean that the front end live reload isn't available after 30 secs? Just want to know the severity of this.

**Comment by Artur-** [comment]
It would not be surprising if this happens also with Tomcat but the idle timeout can be 5 minutes or something

**Comment by tepi** [comment]
https://github.com/vaadin/flow/commit/e3a5a5b9d4611c29f7347a1e61cb24240c2972a8 might have fixed this

**Comment by tepi** [comment]
Confirmed fixed via https://github.com/vaadin/flow/issues/17546
