### ISSUE TITLE
Shortcut listener on TextField sees old values

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#17484]
### Description of the bug

Use-case: the customer wants a TextField for an e-mail address; pressing ENTER would add the e-mail address to the list of e-mail addresses.

Adding a shortcut listener via `Shortcuts.addShortcutListener()` runs given `Command`, unfortunately the value of `TextField.getValue()` does not reflect the actual value which the user has typed into the `TextField`.

I understand that this requirement conflicts with the default value change mode; however I'd argue that the only way to work around this issue is to change the mode to EAGER which will cause a rapid stream of events to be sent to the server.

### Expected behavior

Perhaps the ShortcutListener, if targeted to a TextField, could cause the TextField value to flush&send the value to the server-side, before calling the shortcut listener itself. Alternatively, a function `ShortcutRegistration.flushFields(HasValue... fields)` could be added, which would reconfigure TextField in this manner.

### Minimal reproducible example

Paste this into the skeleton starter:
```java
@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        TextField textField = new TextField("Your name");
        textField.setPlaceholder("Type something then press ENTER");
        Shortcuts.addShortcutListener(textField, (Command) () -> Notification.show("Hello, " + textField.getValue()), Key.ENTER)
                .listenOn(textField);
        add(textField);
    }
}
```

### Versions

- Vaadin / Flow version: 24.1.5
- Java version: 17

**Comment by mvysny** [comment]
Workaround is to set the text field value change mode to EAGER, but that causes a rapid fire of events to be sent to the server-side, potentially triggering a rapid fire of validations.

**Comment by knoobie** [comment]
That has a long history :) https://github.com/vaadin/flow/issues/7046

**Comment by mvysny** [comment]
@knoobie haha, good catch :)

If there only was a way to flush the new value and send it to the server... Then, I could write:
```java
        Shortcuts.addShortcutListener(textField, (Command) () -> getElement().executeJs("flush();").then((SerializableConsumer<JsonValue>) jsonValue -> Notification.show("Hello, " + textField.getValue())), Key.ENTER)
                .listenOn(textField);

```

**Comment by mshabarov** [comment]
I propose to close this as a duplicate for https://github.com/vaadin/flow/issues/7046.
But cross-posting, because this ticket has helpful comments 👍
