### ISSUE TITLE
Vaadin OAuth2 with basic authentication doesn't work

### ISSUE THREAD

**Issue by Alexenon** [vaadin/flow#17505]
### Description of the bug

I am trying to add OAuth 2.0 in my Vaadin Application that will work also with my login form. I read this [documentation](https://vaadin.com/blog/oauth-2-and-google-sign-in-for-a-vaadin-application) on adding OAuth for Google.

Firstly, I added required dependency
```
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-oauth2-client</artifactId>
</dependency>
```

Then I added client-id and client-secret both for GitHub and Google in application.properties file

```
# Github
spring.security.oauth2.client.registration.github.client-id={id}
spring.security.oauth2.client.registration.github.client-secret={secret}
# Google
spring.security.oauth2.client.registration.google.client-id={id}
spring.security.oauth2.client.registration.google.client-secret={secret}
```

After this, I set up my Web Configuration file

```
@Configuration
@EnableWebSecurity
public class VaadinSecurityConfiguration extends VaadinWebSecurity {

    private static final String LOGIN_URL = "/login";
    private static final String LOGIN_PROCESSING_URL = "/login";
    private static final String LOGIN_FAILURE_URL = "/login?error";
    private static final String LOGOUT_SUCCESS_URL = "/";
    private static final String DENIED_PAGE_URL = "/404";

    @Autowired
    private UserService userService;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
                .csrf().disable()
                .authorizeHttpRequests(auth -> {
                    auth.requestMatchers("/").permitAll();
                    auth.requestMatchers("/login").permitAll();
                    auth.requestMatchers("/register").permitAll();
                    auth.requestMatchers("/icons/**").permitAll();
                    auth.requestMatchers("/images/**").permitAll();
                    auth.requestMatchers("/oauth2/**").permitAll();
                })
                .oauth2Login(oauth -> oauth.loginPage(LOGIN_URL).permitAll())
                .formLogin(loginForm -> {
                    loginForm.loginPage(LOGIN_URL);
                    loginForm.loginProcessingUrl(LOGIN_PROCESSING_URL);
                    loginForm.failureUrl(LOGIN_FAILURE_URL);
                })
                .logout(logout -> logout.logoutSuccessUrl(LOGOUT_SUCCESS_URL))
                .exceptionHandling(e -> {
                    e.authenticationEntryPoint(new HttpStatusEntryPoint(HttpStatus.UNAUTHORIZED));
                    e.accessDeniedPage(DENIED_PAGE_URL);
                });

        super.configure(http);
        setLoginView(http, LoginView.class);
    }

    @Override
    public void configure(WebSecurity web) throws Exception {
        super.configure(web);
    }

    @Bean
    public AuthenticationManager authenticationManager(AuthenticationConfiguration authConfiguration) throws Exception {
        return authConfiguration.getAuthenticationManager();
    }

    @Bean
    public DaoAuthenticationProvider authenticationProvider() {
        DaoAuthenticationProvider daoAuthenticationProvider = new DaoAuthenticationProvider();
        daoAuthenticationProvider.setPasswordEncoder(passwordEncoder);
        daoAuthenticationProvider.setUserDetailsService(userService);
        return daoAuthenticationProvider;
    }
}
```

And then login form

```
@AnonymousAllowed
@PageTitle("Login")
@Route(value = "login", layout = MainLayout.class)
public class LoginView extends VerticalLayout implements BeforeEnterObserver {

    private static final String GITHUB_OAUTH_URL = "/oauth2/code/github";
    private static final String GOOGLE_OAUTH_URL = "/oauth2/code/google";

    private final LoginForm loginForm = new LoginForm();

    public LoginView() {
        Anchor githubLoginLink = new Anchor(GITHUB_OAUTH_URL, "Login with Github");
        Anchor googleLoginLink = new Anchor(GOOGLE_OAUTH_URL, "Login with Google");
        githubLoginLink.getElement().setAttribute("router-ignore", true);
        googleLoginLink.getElement().setAttribute("router-ignore", true);

        loginForm.setAction("login");

        add(
                new H1("Welcome to Login Form"),
                loginForm,
                githubLoginLink,
                googleLoginLink
        );
    }

    @Override
    public void beforeEnter(BeforeEnterEvent beforeEnterEvent) {
        if (beforeEnterEvent.getLocation()
                .getQueryParameters()
                .getParameters()
                .containsKey("error")) {
            loginForm.setError(true);
        }
    }

}
```

### Expected behavior

After pressing the GitHub anchor, it goes to `http://localhost:8080/oauth2/code/github`, which I suppose isn't the right behavior, because of this
```
        // Set router-ignore attribute so that Vaadin router doesn't handle the login request
        githubLoginLink.getElement().setAttribute("router-ignore", true);
        googleLoginLink.getElement().setAttribute("router-ignore", true);
```     
which is taken from Vaadin official documentation. On this redirected page, nothing happens without OAuth happening. Hope somebody could help to fix this issue, cheers!

### Minimal reproducible example

See https://stackoverflow.com/questions/76989057/vaadin-oauth2-with-basic-authentication

### Versions

- Vaadin / Flow version: 24
- Java version: 17
- OS version: Windows
- Browser version (if applicable): Chrome
- Application Server (if applicable): localhost
- IDE (if applicable): IntelliJ IDEA

**Comment by knoobie** [comment]
The usage of only ID and SECRET relies on defaults provided by spring security. To ensure that non-standard oauth2 provider work, add the recommended properties described by spring security. https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-custom-provider-properties

**Comment by Alexenon** [comment]
Hi @knoobie, thanks for your answer. 
I am wondering how then in this [example](https://vaadin.com/blog/oauth-2-and-google-sign-in-for-a-vaadin-application), provided in official documentation, is working ? 
Another question is how should be configured `oauth2Login()` ?
```
http.oauth2Login().loginPage(LOGIN_URL).permitAll();
```
or
```
http.oauth2Login(withDefaults());
```

I also found in the comments section that for somebody it worked both login form and OAuth authorization
<img width="604" alt="image" src="https://github.com/vaadin/flow/assets/58091611/7a7a6120-6a1a-4a4d-a39d-501f9abe3d9a">
on my side, it's just working basic auth.

**Comment by knoobie** [comment]
The example is working because Google is a well-known Oauth2 provider and GitHub isn't. You can read this all within the Spring docs and source code. 

Both variants work, it depends on your use case. But you are better off asking spring related question on their Gitter to get appropriate feedback.

**Comment by Alexenon** [comment]
The main problem is that the Google Auth doesn't work also, but the steps are identical to documentation ones.

**Comment by knoobie** [comment]
Your example has more moving parts (the second authentication mechanism) - once you remove all of those, I would highly guess that the documentation is working again like described.

**Comment by Alexenon** [comment]
> The usage of only ID and SECRET relies on defaults provided by spring security. To ensure that non-standard oauth2 provider work, add the recommended properties described by spring security. https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-custom-provider-properties

After adding additional properties for spring, it's still failing on processing OAuth request, both for GitHub and Google

```
# Github Oauth2 Login
spring.security.oauth2.client.registration.github.client-id={id}
spring.security.oauth2.client.registration.github.client-secret={secret}
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=name

# Google Oauth2 Login
spring.security.oauth2.client.registration.google.client-id={id}
spring.security.oauth2.client.registration.google.client-secret={secret}
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://www.googleapis.com/oauth2/v4/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=profile
spring.security.oauth2.client.provider.google.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs
```

**Comment by mcollovati** [comment]
It looks like to me that the path is incorrect in you login view

```
    private static final String GITHUB_OAUTH_URL = "/oauth2/code/github";
    private static final String GOOGLE_OAUTH_URL = "/oauth2/code/google";
```

I suppose it should be `/oauth2/authorization/github`

Take a look also at this guide https://spring.io/guides/tutorials/spring-boot-oauth2/#_social_login_simple

**Comment by mshabarov** [comment]
@Alexenon is this issue still valid for you? Could you please check [this reply](https://github.com/vaadin/flow/issues/17505#issuecomment-1811998673)?

**Comment by mshabarov** [comment]
Closed as no answer provided within more than 2 weeks. If this issue is still valid for you, please comment.
