### ISSUE TITLE
Option to run npm ci in maven build to have reproducible builds in V23 (already in V14 + V24)

### ISSUE THREAD

**Issue by jqpaul** [vaadin/flow#17520]
### Describe your motivation

Add the option to only run npm ci on maven builds to Vaadin V23
This feature is already present in V14 and V24 as seen in issue #15579 

### Describe the solution you'd like

Same as #15579 I would like a ciBuild parameter for the vaadin-maven-plugin for Vaadin V23

### Describe alternatives you've considered

Downgrading to V14

### Additional context

Currently stuck with Java 11 for our business application, so a switch to the newest version is sadly not possible. Similarly if I would be using V14 and update to V23 I would loose this feature.

**Comment by mshabarov** [comment]
At the time when this feature was implemented we had already released Vaadin 23.3 and our release policy allow to include features only to the minor version. So this one is expected in Vaadin 23.4, which is currently not planned.

**Comment by mshabarov** [comment]
Back-ported to upcoming Vaadin 23.4 version, see https://github.com/vaadin/flow/pull/17994.
