### ISSUE TITLE
Keep web socket connections alive for still open browser tabs

### ISSUE THREAD

**Issue by muhammetaltindal** [vaadin/flow#17546]
### Description of the bug

When using the default transport mechanism `websocket-xhr`, only server-side communicates changes via web socket to the client. The client only talks via XHR to the server, including the heartbeats if enabled.

Now, on a production environment it makes sense to cleanup connections where no communication has occurred for a certain period (timeout). If this timeout occurs, such web socket connections would be closed.

**Would it make sense to let the heartbeats run via web sockets, if the web socket transport is used either via `websocket-xhr` or `websocket`?** This would ensure that web socket connections would be kept alive.

Right now, after a web socket has been closed due to the timeout because no server-side communication has happened, the client notices this and reconnects the push connection again. However, for the reconnect there can be a time window up to like 10 seconds.

<img width="1108" alt="Screenshot 2023-09-04 at 11 24 59 AM" src="https://github.com/vaadin/flow/assets/1894101/5d18d2f8-af90-4578-86d1-db2966540f2b">

In the screenshot above you can see the initial push request which sets up the initial web socket connection. After the timeout occurs, you can notice the warning in the console. Finally, after the closed web socket connection has been noticed by the client, another `?v-r=push` request has been done to set up a new push connection.

### Expected behavior

The expected behavior would be, that the heartbeats also keep the web socket connection alive.

### Minimal reproducible example

In order to reproduce this, (a) the heartbeat interval must be set to a positive number, so it is enabled, (b) the push transport needs to be enabled, e.g. via the Push annotation, and (c) some kind of a proxy needs to be set up which kills inactive connections after a certain timeout.

### Versions

- Vaadin / Flow version: 14.10.3
- Java version: 17

**Comment by Legioth** [comment]
Could potentially be easier to configure Atmosphere to send internal keep-alive messages over the websocket rather than making changes to the heartbeat mechanism.

**Comment by muhammetaltindal** [comment]
Note that in `c.v.f.s.c.PushRequestHandler` the atmosphere heartbeat has been disabled explicitly:
```java
        // Disable heartbeat (it does not emit correct events client side)
        // https://github.com/Atmosphere/atmosphere-javascript/issues/141
        atmosphere.addInitParameter(
                ApplicationConfig.DISABLE_ATMOSPHEREINTERCEPTORS,
                HeartbeatInterceptor.class.getName());
```

**Comment by mshabarov** [comment]
I would propose first to re-enable the Atmosphere heartbeat and see if it works. The issue mentioned in the comment has been closed, but no mentions about actual fix.
If it won't help, I propose to try adding a dedicated heartbeat, as Leif mentioned.

**Comment by mshabarov** [comment]
@muhammetaltindal could you explain why do you have a proxy configured in a way that it "kills inactive connections after a certain timeout" ? If loosing the UI updates is critical for this application, why not dropping the proxy timeout setting, so that the connection wouldn't be closed ?

**Comment by muhammetaltindal** [comment]
The idea of the connection timeout is to cleanup unused connections in order to be able to accept new ones since per app server there is a certain upper limit regarding the total amount of connections per server.

Sorry, I just tried to explicitly reproduce UI updates as I initially described in the bug description. However, in `c.v.f.s.c.AtmospherePushConnection#push(boolean)` the code is capable of pushing the changes after the connection has been reestablished. I couldn't reproduce such case.

In my opinion this issue is then only about the unnecessary reconnections that may happen without a keep-alive heartbeat. I will adjust the ticket description to point this out.

**Comment by muhammetaltindal** [comment]
@mshabarov @Legioth I agree, it is just fine to configure the atmosphere heartbeat to solve this issue. However, in the init of atmosphere in `c.v.f.s.c.PushRequestHandler` the heartbeat interceptor has been disabled in a hard coded way. I think this issue can be just resolved by allowing the web-socket heartbeat to be enabled/disabled via some kind of a configuration (per default this could be set to disabled). What do you think?

**Comment by muhammetaltindal** [comment]
**Temporary workaround**
- copy paste c.v.f.s.c.PushRequestHandler into your project under the same package
- delete statement at line 206, or where `ApplicationConfig.DISABLE_ATMOSPHEREINTERCEPTORS` is set to disable the heartbeat interceptor.
```java
    atmosphere.addInitParameter(
                ApplicationConfig.DISABLE_ATMOSPHEREINTERCEPTORS,
                HeartbeatInterceptor.class.getName());
```
- if you use the WEBSOCKET transport, and you had servlet filters in use, you can define analogue atmosphere interceptors, for each filter create an interceptor class that implements `o.a.c.AtmosphereInterceptor`
- add servlet context init param `org.atmosphere.cpr.AtmosphereInterceptor` with all the interceptors you have comma-separated

**Comment by tepi** [comment]
On the Framework side, the offending code has been removed years ago and apparently tested to work fine: https://github.com/vaadin/framework/pull/9877/files
