### ISSUE TITLE
(Documentation) Cannot find the description of  the change to H1 .. H6 spacing (and its workaround)

### ISSUE THREAD

**Issue by jflamy** [vaadin/flow#17563]
### Description of the bug

The description of the spacing change to H1 .. H6 in v24 is described somewhere.
I remember seeing it.
I can't find it.
I have an application where the look depended on the previous default spacing.
I remember a workaround being given, which would give me time to do the change correctly to my app.
I can't find the workaround because there is no convenient way to search the release notes, and there is no documentation of the H tags as components in flow (I opened a separate issue).

### Expected behavior

Document the styling with the tags.

### Minimal reproducible example

N/A

### Versions

- Vaadin / Flow version: 24

**Comment by knoobie** [comment]
The workaround would be to apply the 6 margins yourself. I've seen your comment on the PR introducing the change - there you can find the CSS to re-apply to fix the issue.

**Comment by mshabarov** [comment]
Closed, as it is explained in the migration guide/breaking changes chapter in online documentation.
