### ISSUE TITLE
Provide method to set Anchor's router-ignore flag.

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#17617]
### Describe your motivation

Currently, when I want to tell Vaadin to not intercept an anchor click, I need to set the `router-ignore` flag using the Element API. Since we should prevent make devs use the Element API for "normal" features, a dedicated `setRouterIgnore` method should be provided.

Also see: https://vaadin.com/docs/latest/routing/navigation#using-standard-links

### Describe the solution you'd like

Anchor should provide a `setRouterIgnore` method to improve the DX for configuring this feature.

**Comment by jcgueriaud1** [comment]
It's a duplicated to this https://github.com/vaadin/flow/issues/17518
