### ISSUE TITLE
Detached node is not removed from the state tree when removeFromTree is called

### ISSUE THREAD

**Issue by ugur-vaadin** [vaadin/flow#17653]
### Description of the bug

When any element is removed via calling, `Element::removeFromTree`, the detached node still persists in the client-side tree. Therefore, it is never garbage collected, leading to potential memory leaks.

Follow-up from a Flow component [issue](https://github.com/vaadin/flow-components/issues/5427).

### Expected behavior

I would expect the detached node to be removed from the client side-tree.

### Minimal reproducible example

```java
Element element = new Element("vaadin-random-element");
UI.getCurrent().getElement().appendChild(element);
add(new Button("Remove all elements from tree", click -> element.removeFromTree()));
```
1. Add the snippet to a view
2. Click the button
3. Observe that the detached elements are still in the tree
4. Elements can be appended and removed repeatedly to reproduce a growing number of detached elements 

### Versions

- Vaadin / Flow version: 24.2
- Java version: 17
- OS version: MacOS
- Browser version (if applicable): Chrome 116
- Application Server (if applicable): -
- IDE (if applicable): -

**Comment by caalador** [comment]
I couldn't replicate this with the minimal example when adding it as a view in the flow-root-context tests. 
Is there something specific in the application stack?
Where should the element be left?

**Comment by ugur-vaadin** [comment]
Using the following snippet, appending and removing the element repeatedly results in a growing number of `Detached HTMLElement` entries on the browser memory heap snapshots (at least with Chrome). They don't get removed even with manual triggering of garbage collection. The retainers section traces the reference back to the client side state tree. I might be missing something or using the API in an unintended way though.

```j́ava
Element element = new Element("vaadin-random-element");
add(new NativeButton("Append element to UI element", click -> UI.getCurrent().getElement().appendChild(element)));
add(new NativeButton("Remove element from tree", click -> element.removeFromTree()));
```
