### ISSUE TITLE
Problem upgrading from Vaadin 14.4.4 to 14.10.7

### ISSUE THREAD

**Issue by aghasemi** [vaadin/flow#17662]
### Description of the bug

Hi. I have an old Vaadin 14 application which runs fine on version 14.4.4. When I update the Vaadin version to 14.10.7, although the app still compiles and runs via `mvn spring-boot:run`, it fails somewhere in the middle of rendering the screen, showing the following window:

![image](https://github.com/vaadin/flow/assets/7351535/229a2373-ceaa-4039-9b59-a0da69d92637)

Is there anything I can do? Maybe also upgrade Spring  Boot starter parent (currently 2.7.12)?

Thanks 

### Expected behavior

Application loads the screen

### Minimal reproducible example

-

### Versions

- Vaadin / Flow version: 14.1.0.7
- Java version: 17
- OS version: Ubuntu 22.04
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by caalador** [comment]
I would start by updating spring-boot to 2.7.16 and then running `mvn vaadin:clean-frontend`

**Comment by mshabarov** [comment]
You could check this [base starter project](https://github.com/vaadin/skeleton-starter-flow-spring/tree/mshabarov-patch-2) as a base/reference for upgrade.

**Comment by mshabarov** [comment]
Closed because waiting more than 2 weeks for answer from author. Please comment in this ticket or open a new one if you still have this problem.

**Comment by aghasemi** [comment]
Hi. Sorry for the delay. Following the changes in the `pom.xml` from the starter project solved the issue. It is interesting how much the POM file has changed since I started this project in late 2019. 

Thanks and Best
