### ISSUE TITLE
ComboBox setRenderer with Error '$0, $1, $2, return (function() { this.$.overlay.$.overlay.style[$0]=$1}).apply($2)'

### ISSUE THREAD

**Issue by dheitmann** [vaadin/flow#17702]
### Description of the bug

We run into a problem while using ComboBox with Renderer. Here is our code:

var combobox = new ComboBox<String>("Open me");
combobox.setItems(List.of("AA", "AB", "AC"));
combobox.setRenderer(new ComponentRenderer<>(s -> new Span("Awesome " + s)));
add(combobox);

If I try to open the ComboBox, we only see a rotating blue circle, but no text and the complete Browser page is frozen. This is my Browser Console:

The error has occurred in the JS code: '$0, $1, $2, return (function() { this.$.overlay.$.overlay.style[$0]=$1}).apply($2)' [test:7:245](http://192.168.2.113/test?sessionId=E801034F45AE639C9FE8EDC686D55A6A)
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately. [test:7:245](http://192.168.2.113/test?sessionId=E801034F45AE639C9FE8EDC686D55A6A)
The error has occurred in the JS code: '$0, $1, $2, return (function() { this.$.overlay.$.overlay.style[$0]=$1}).apply($2)' [test:7:245](http://192.168.2.113/test?sessionId=E801034F45AE639C9FE8EDC686D55A6A)
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately. [test:7:245](http://192.168.2.113/test?sessionId=E801034F45AE639C9FE8EDC686D55A6A)
The error has occurred in the JS code: '$0, $1, $2, return (function() { this.$.overlay.$.overlay.style[$0]=$1}).apply($2)' [test:7:245](http://192.168.2.113/test?sessionId=E801034F45AE639C9FE8EDC686D55A6A)
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately. [test:7:245](http://192.168.2.113/test?sessionId=E801034F45AE639C9FE8EDC686D55A6A)
The error has occurred in the JS code: '$0, $1, $2, return (function() { this.$.overlay.$.overlay.style[$0]=$1}).apply($2)' [test:7:245](http://192.168.2.113/test?sessionId=E801034F45AE639C9FE8EDC686D55A6A)
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately. [test:7:245](http://192.168.2.113/test?sessionId=E801034F45AE639C9FE8EDC686D55A6A)
The error has occurred in the JS code: '$0, $1, $2, return (function() { this.$.overlay.$.overlay.style[$0]=$1}).apply($2)' [test:7:245](http://192.168.2.113/test?sessionId=E801034F45AE639C9FE8EDC686D55A6A)
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately. [test:7:245](http://192.168.2.113/test?sessionId=E801034F45AE639C9FE8EDC686D55A6A)
The error has occurred in the JS code: '$0, $1, $2, return (function() { this.$.overlay.$.overlay.style[$0]=$1}).apply($2)' [test:7:245](http://192.168.2.113/system?sessionId=E801034F45AE639C9FE8EDC686D55A6A)
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately. [test:7:245](http://192.168.2.113/system?sessionId=E801034F45AE639C9FE8EDC686D55A6A)
The error has occurred in the JS code: '$0, $1, $2, return (function() { this.$.overlay.$.overlay.style[$0]=$1}).apply($2)' [test:7:245](http://192.168.2.113/system?sessionId=E801034F45AE639C9FE8EDC686D55A6A)
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately. [test:7:245](http://192.168.2.113/test?sessionId=E801034F45AE639C9FE8EDC686D55A6A)
The error has occurred in the JS code: '$0, return (function() { window.Vaadin.Flow.dialogConnector.initLazy(this)}).apply($0)'

We used the same Code wit Vaadin Version 14+ without any problems. We update to Vaadin Version 23.3.23 a while ago.

Anybody else have this problem?

Thanks Dennis

### Expected behavior

ComboBox should show Text

### Minimal reproducible example

var combobox = new ComboBox<String>("Open me");
combobox.setItems(List.of("AA", "AB", "AC"));
combobox.setRenderer(new ComponentRenderer<>(s -> new Span("Awesome " + s)));
add(combobox);

### Versions

- Vaadin / Flow version: 23.3.24
- Java version: Coretto 17.0.7
- OS version: Windows 10
- Browser version (if applicable): Firefox and Chrome
- Application Server (if applicable): Tomcat 9
- IDE (if applicable): IntelliJ

**Comment by mcollovati** [comment]
I just tested your sample code with the Vaadin 23.3 [starter project](https://github.com/vaadin/skeleton-starter-flow/tree/v23) (Vaadin 23.3.24) and it works as expected without any error.

Did you already try to clean the generated resources with `mvn vaadin:clean-frontend`?

Or can you provide a sample project that reproduces the issue?

**Comment by mshabarov** [comment]
Closed because of no responses within 2 weeks. Please comment or create a new issue with reproducible example if this is still valid for you.
