### ISSUE TITLE
If user does not do anything (i.e. use mouse, key press, scrolling etc) for 2 mins then user will be logged out automatically and the page will be redirected to login page:

### ISSUE THREAD

**Issue by Imrnkhan** [vaadin/flow#17704]
### Description of the bug

If user does not do anything (i.e. use mouse, key press, scrolling etc) for 2 mins then user will be logged out automatically and the page will be redirected to login page:
spring boot project application java.and this this is my code can any one fix and help out this code
[demo2-master.zip](https://github.com/vaadin/flow/files/12706288/demo2-master.zip)

### Expected behavior

If user does not do anything (i.e. use mouse, key press, scrolling etc) for 2 mins then user will be logged out automatically and the page will be redirected to login page:
spring boot project application java.and this this is my code can any one fix and help out this code
[demo2-master.zip](https://github.com/vaadin/flow/files/12706288/demo2-master.zip)

### Minimal reproducible example

spring boot project application java.and this this is my code can any one fix and help out this code
[demo2-master.zip](https://github.com/vaadin/flow/files/12706288/demo2-master.zip)

### Versions

- Vaadin / Flow version:
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):
[Install IntelliJ IDEA](https://www.jetbrains.com/help/idea/installation-guide.html)
and

**Comment by mcollovati** [comment]
I can't see any Vaadin related code in the uploaded demo project.
Is something missing in the zip file, or is yours a general question about Spring Security?

**Comment by Imrnkhan** [comment]
Yes its spring securing based.

**Comment by Imrnkhan** [comment]
its based on Spring Security use in this project one kind of demo when If user does not do anything (i.e. use mouse, key press, scrolling etc) for 2 mins then user will be logged out automatically and the page will be redirected to login page:
use dependencies  1.spring security 2. spring web 3. thymeleaf    some use of js,html

**Comment by mcollovati** [comment]
Being not a Vaadin related question, it would probably be better to ask for help on Spring support channels.

You can perhaps try setting the HTTP session timeout to 2 minutes (e.g. `server.servlet.session.timeout=2m`) and check the Spring Security documentation to learn about handling session expiration (e.g. https://docs.spring.io/spring-security/reference/servlet/authentication/session-management.html#_detecting_timeouts).

On the Vaadin side, the client side sends "keep alive" heartbeat requests, but the default interval is 5 minutes, so with the above session timeout configuration, the session will expire before a heartbeat ping reaches the server.
See https://vaadin.com/docs/latest/advanced/application-lifecycle#application.lifecycle.ui-expiration for more information.

I close this issue as it is not strictly related to Vaadin applications.
Please comment here or open a new ticket providing additional details, if you think the issues relates to Vaadin.
