### ISSUE TITLE
Web Components are not properly registered in non default Route in 24.2

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#17722]
### Description of the bug

In certain projects, web components are not enhanced when changing from main route like `""` to other routes like `"/form"`.
Actually, the WC tag is in the UI, but they are not correctly registered if you inspect the DOM structure or the `window.Vaadin.registrations` object

### Expected behavior

Components are correctly registered regardless of the path

### Minimal reproducible example

1. Clone Collaboration Engine project and switch to the branch migrated to 24.2
```
git clone git@github.com:vaadin/collaboration-engine-internal.git
cd collaboration-engine-internal/
git checkout chore/bump-to-24.2
```
2. Compile and install
```
mvn clean install -DskipTests
```
3. Run the application for the ITs
```
cd collaboration-engine-test/collaboration-engine-integration-test/
mvn
```
4. Visit main page http://localhost:8080/ WC are correctly registered and UI correctly rendered
```
Vaadin.registrations.map(c => typeof c === 'function' && (new c))

[false, false, vaadin-iconset, vaadin-vertical-layout, vaadin-button, vaadin-horizontal-layout]
```

![Screenshot 2023-09-27 at 07 37 38](https://github.com/vaadin/flow/assets/161853/3d33f489-8ec1-4af2-b4dc-175f78f96258)

5. Visit another route http://localhost:8080/form only vertical layout is registered
```
Vaadin.registrations.map(c => typeof c === 'function' && (new c))

[false, false, vaadin-iconset, vaadin-vertical-layout]
```

![Screenshot 2023-09-27 at 07 37 55](https://github.com/vaadin/flow/assets/161853/79cf7064-6e7b-4449-b8e2-f8c2b82a6289)

### Versions

- Flow version: 24.2.0.beta1 24.2-SNAPSHOT

**Comment by mshabarov** [comment]
Also doesn't work with Vaadin / Flow 24.1.
The root cause is that the Flow doesn't add the reachable classes from parent view `CollaborativeFormViewCommon` to `CollaborativeFormView`, because only `CollaborativeFormView ` is marked with `AtRoute`.
```java
public class CollaborativeFormView extends CollaborativeFormViewCommon {
   // has no codes
}
```
```java
@Route("form")
@PreserveOnRefresh
public class CollaborativeFormViewCommon extends VerticalLayout {
   // TextField, Checkbox and other components included
}
```
As a result the chunk for `/form` route doesn't have a correct/expected set if web-components and isn't render propoerly.

The workaround is to add
```
<configuration>
    <optimizeBundle>false</optimizeBundle>
</configuration>
```
to Vaadin plugin configuration, or explicitly mark child routes with `AtRoute` annotations, instead of having it on parent view classes.

**Comment by mshabarov** [comment]
The same routes configuration works fine in Vaadin Spring skeleton starter.
If I place 
```java
@Route("form")
public class ParentView extends VerticalLayout {

    TextField textField = new TextField("Name");

    public ParentView() {
        add(textField);
    }
}

public class ChildView extends ParentView {
}
```
and navigate to localhost:8080/form, I would see the text field properly rendered.
So it might be an issue in the Collaboration Kit test module. I'm checking.
