### ISSUE TITLE
Page.open() not working for Vaadin applications on same host

### ISSUE THREAD

**Issue by d2k2-git** [vaadin/flow#17724]
### Description of the bug

I have two Vaadin Flow applications.

1. app-1 runs on localhost:8080
2. app-2 runs on localhost:8081

app-1 has a Button which can open a new browser for app-2
`UI.getCurrent().getPage().open("http://localhost:8081");`

### Expected behavior

the button in app-1 should open on every click a new tab for "app-2". However, this is not the case. The buttonclick will work only every 2nd time. It seems to be a problem only when the "app-2" is also a vaadin application and runs on same host with different port. I would expect that vaadin apps don't affect the behavior of other vaadin apps on same host. thats why it looks like a bug for me.

there are 2 workarounds possible:
1. use different context paths for every vaadin application
2. invalidate the session after calling "Page.open()". I am not sure if this is the clean way to go.

### Minimal reproducible example

```java
@PageTitle("app-1")
@Route
public class MainView extends VerticalLayout {

	public MainView() {

		var button = new Button("open app-2");
		button.addClickListener(event -> {

			// try to open "app-2" twice. but only every 2nd "open" will work
                        // app-2 must be also a Vaadin app
			UI.getCurrent().getPage().open("http://localhost:8081");

			// invalidating the session fixes this problem ?
			// UI.getCurrent().getSession().getSession().invalidate();
		});

		add(button);
	}
}
```

### Versions

- Vaadin / Flow version: 24.1.10
- Java version: 17
- OS version: windows 10
- Browser version (if applicable): Chrome 117.0.5938.92
- Application Server (if applicable): spring boot 3.1.4 built in tomcat
- IDE (if applicable): STS 4.15.3.RELEASE

**Comment by Legioth** [comment]
This might be caused by conflicting session cookies between the two applications since cookies are shared across different ports on the same hostname. You could try configuring a different session cookie name for one of the applications using the `server.servlet.session.cookie.name` property.
