### ISSUE TITLE
Cover more properties with the typed API in Style

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#17729]
### Describe your motivation

The Style API nowadays contains some more specific API for setting CSS than just providing string-string pairs. For example you can call `tf.getStyle().setZIndex(10);` indated of `tf.getStyle().set("z-index","10");`

The API is not complete though (and probably can't be), but was made by gut feeling to cover the most essential properties. I wrote the initial list but have already missed some properties.

### Describe the solution you'd like

We should extend the Style API whenever we find relevant missing API. Please drop in new suggestions below and let's improve it for next minor!

### Describe alternatives you've considered

Drink a six-pack of beer and carry on.

**Comment by mstahv** [comment]
I was missing these recently:

        //tf.getStyle().setFontWeight("bold");
        tf.getStyle().set("font-weight", "bold");
        //tf.getStyle().setFontSize("40px");
        tf.getStyle().set("font-size", "40px");

**Comment by mstahv** [comment]
Collecting some needs from our (bit ugly) [Notification examples](https://vaadin.com/docs/latest/components/notification): 

setMargin*Left/Right/Top/Bottom*
setFontWeight/Size (already cover in initial issue  though)

**Comment by mstahv** [comment]
Other picks from docs:

* backgroundColor
* margin-inline-start
* margin-inline-end
* flex-wrap
* min-width
* max-width
* line-height
* max-height
* align-items

**Comment by tltv** [comment]
- padding-left/-right/-top/-bottom
- border-left/-right/-top/-bottom

**Comment by tltv** [comment]
Often needed flexbox properties:
- align-self
- flex-grow
- flex-shrink
- justify-content
- flex-direction
- flex-basis
