### ISSUE TITLE
Replace apache-httpclient with java.net.http.HttpClient

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#17734]
### Description of the bug

Replace old `apache-httpclient` 4.x with modern Java 11 `java.net.http.HttpClient`.
This should allow to get rid of the commons libraries (to be tested).

GH discussion: https://github.com/vaadin/flow/discussions/17564.

### Expected behavior

-

### Minimal reproducible example

-

### Versions

- Vaadin / Flow version: 24.2

**Comment by knoobie** [comment]
Wasn't that already done and is pending GA release 24.2? https://github.com/vaadin/flow/issues/14538

**Comment by mshabarov** [comment]
You're right, I've missed this fact.
We can close this then.

**Comment by knoobie** [comment]
Looks like something is missing :) OSGI still has it as dependency: https://github.com/vaadin/flow/blob/main/flow-server/bnd.bnd#L6

**Comment by mshabarov** [comment]
Let's see if this passes https://github.com/vaadin/flow/pull/17735
