### ISSUE TITLE
Loading Vite resources fail under heavy load

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#17736]
### Description of the bug

Running a newly created application (`npx @vaadin/cli init hello`) with `vaadin.frontend.hotdeploy=true` and load testing it as
```
#!/bin/bash

for a in `seq 1 1000`
do
  (curl http://localhost:8080/VAADIN/generated/vaadin.ts -s -o out-$a.txt) &
done
```

Results in 1000 out files being written but at least one contains something else than it should:
```
% shasum out-*.txt|cut -d' ' -f 1|sort|uniq -c
 998 5f0be6e57810de2ca4c29c1edf52a1fac6a19304
   1 90c23e84ffd231f92398fe61b943e77ea8b3365b
   1 a6ba9719fd4bd2f68f76e650d307d79919289da7
```

Most often the error in the file (and printed to the server console) is
```
java.net.SocketException: Connection reset by peer
```

### Expected behavior

Doing the same test on images/empty-plant.png works as expected

```
#!/bin/bash

for a in `seq 1 1000`
do
  (curl http://localhost:1000/images/empty-plant.png -s -o out-$a.png) &
done
```

```
% shasum out-*.png|cut -d' ' -f 1|sort|uniq -c
1000 d725f8e3d95a78a8aa48ebf1a43d60221b314e9a
```

### Minimal reproducible example

Above

### Versions

- Vaadin / Flow version: 24.1.10
- Java version: 21
- OS version: mac

**Comment by mcollovati** [comment]
I couldn't reproduce the issue even with a higher number of requests.
I got different hashes only when I try to recompile a class during executions or when I updates files in the fronted folder.
But I can't see any exception in the produced files, just different contents or sometimes the body of the "build in progress" html page shown when server restarts.

@Artur- are there any other steps to do during execution to reproduce the issue (e.g. touch some frontend file or do something in the IDE)?

**Comment by Artur-** [comment]
I cannot reproduce this any longer either. Not sure if something has changed but let's close it then until it happens again
