### ISSUE TITLE
Classname "v-drag-over-target" is not added to a drop target when a draggable component is over it

### ISSUE THREAD

**Issue by bmserras** [vaadin/flow#17811]
### Description of the bug

According to this [documentation](https://vaadin.com/docs/latest/create-ui/dnd/drop-target#drop-target-styling), the drop target receives the CSS class name `v-drag-over-target` when a drag source stays over it. However, by testing this functionality and by inspecting the HTML element, the class name is not added.

However, styling the drag source does work, `with .v-dragged.card`, when a draggable component is dragged.

### Expected behavior

The drop target should get the classname `v-drag-over-target` when a drag source stays over it.

### Minimal reproducible example

Create a simple project in [Vaadin Start](https://start.vaadin.com/app). No configuration needed.

Replace the code in the `HelloWorldView` with the following code:

  ```
import com.example.application.views.MainLayout;
  import com.vaadin.flow.component.dnd.DragSource;
  import com.vaadin.flow.component.dnd.DropTarget;
  import com.vaadin.flow.component.html.H2;
  import com.vaadin.flow.component.html.Span;
  import com.vaadin.flow.component.orderedlayout.VerticalLayout;
  import com.vaadin.flow.router.PageTitle;
  import com.vaadin.flow.router.Route;
  import com.vaadin.flow.router.RouteAlias;
  
  @PageTitle("Hello World")
  @Route(value = "hello", layout = MainLayout.class)
  @RouteAlias(value = "", layout = MainLayout.class)
  public class HelloWorldView extends VerticalLayout {
  
      private VerticalLayout draggableComponents = new VerticalLayout();
  
      private VerticalLayout dropArea1 = new VerticalLayout();
  
      public HelloWorldView() {
          setSizeFull();
  
          Span draggableSpan1 = new Span("Draggable #1");
          Span draggableSpan2 = new Span("Draggable #2");
          Span draggableSpan3 = new Span("Draggable #3");
  
          // Make components draggable and store reference to the configuration object
          DragSource<Span> dragSource1 = DragSource.create(draggableSpan1);
          DragSource<Span> dragSource2 = DragSource.create(draggableSpan2);
          DragSource<Span> dragSource3 = DragSource.create(draggableSpan3);
  
          // Add draggable components to layout
          draggableComponents.add(draggableSpan1, draggableSpan2, draggableSpan3);
  
          // Make the drop areas active drop targets
          DropTarget<VerticalLayout> dropTarget1 = DropTarget.create(dropArea1);
  
          // When the component is dropped, added it to the respective drop area
          dropTarget1.addDropListener(event -> event.getDragSourceComponent().ifPresent(dropArea1::add));
  
          // Make the layouts occupy all the available space, give them a border, and add them to the main layout
          draggableComponents.setSizeFull();
          dropArea1.setSizeFull();
          draggableComponents.addClassName("with-border");
          dropArea1.addClassName("with-border");
          dropArea1.add(new H2("Drop Area #1"));
          add(draggableComponents, dropArea1);
      }
  
  }
```

In the `frontend` folder, add this to the `styles.css` file:

  ```
.v-dragged {
      outline: 5px dotted hotpink;
      opacity: 0.5;
  }
  
  .v-drag-over-target {
      outline: 1px solid green;
  }
```

Build and run the project. Go to `http://localhost:8080/` and try to drag one of the draggable components. Place a draggable component on top of a drop area while still holding the mouse button. The drop area doesn't get a green border.

### Versions

- Vaadin / Flow version: 24.1.12
- Java version: 17.0.4
- OS version: Windows 11
- Browser version (if applicable): Google Chrome 117.0.5938.149
- Application Server (if applicable): Apache Tomcat 10.1.11

**Comment by simasch** [comment]
Any news on that issue because IMO this breaks the whole DnD visual effects

**Comment by mshabarov** [comment]
The issue was triaged and currently added to the backlog priority queue for further investigation.

**Comment by tepi** [comment]
Tested right now on latest code from main branch, confirmed broken also there (Chrome and Firefox on MacOS). Looks like if I add the `v-drag-over-target` class name to the target before starting the drag, and then hover over the target and do a drag leave, the class name will be removed at that point as it should. But it is never added in the first place. Will investigate underlying reason next.

**Comment by tepi** [comment]
Looks like there's at least a workaround: highlighting seems to work just by adding this to your `HelloWorldView`:

```dropTarget1.setDropEffect(DropEffect.MOVE);```

This is checked on `dragenter`, and the class name is not added since the effect is `undefined` at that point (and by default). The code to check this has been in place since early 2019 - not to say that some other behavior couldn't have changed in between.

I'll check tomorrow if we need to change some code, or defaults, or maybe the documentation.

- `DragSource` effectAllowed defaults currently to `EffectAllowed.UNINITIALIZED` which is the same as `EffectAllowed.ALL`
- `DropTarget` defaults currently to `null` which seems to translate to `undefined` on the client side
