### ISSUE TITLE
WebPush Subscription should implement equals and hashCode

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#17832]
### Description of the bug

I want to be able to easily check if a given subscription is identical to some existing subscription, or just add multiple subscriptions to a `HashSet` and be sure there are no duplicates. This gets complicated since `nl.martijndwars.webpush.Subscription` doesn't implement `equals` and `hashCode`. 

As a workaround, I crated by own record type and manually convert that to and from the built-in `Subscription`

### Expected behavior

`Subscription` should implement `equals` and `hashCode`

### Minimal reproducible example

```
new Subscription("foo", new Keys("bar", "baz")).equals(new Subscription("foo", new Keys("bar", "baz")));
```

### Versions

- Vaadin / Flow version: 24.2.0.rc2

**Comment by tltv** [comment]
This may need a new subscription type like this:
```
public class WebPushSubscription extends Subscription {

    public WebPushSubscription() {
        super();
    }

    public WebPushSubscription(String endpoint, Keys keys) {
        super(endpoint, keys);
    }

    @Override
    public int hashCode() {
        return Objects.hash(endpoint, keys.p256dh, keys.auth);
    }

    @Override
    public boolean equals(Object obj) {
        return Objects.equals(obj, this);
    }
}
```

**Comment by mshabarov** [comment]
The new fork used for PushService implementation (`dev.blanke.webpush:webpush`) now has `Subscription` as a record:
```
public record Subscription(String endpoint, Keys keys) { }
```
and it's also backported to 24.2, so this issue is covered.
