### ISSUE TITLE
Resynchronization Issue with Vaadin 14.10.2 and @Push Annotation

### ISSUE THREAD

**Issue by gianluca-valentini** [vaadin/flow#17875]
### Description of the bug

Dear Vaadin Team,

I am writing to report a bug that I have encountered in my application using Vaadin 14.10.2 (prduction mode) in a Kubernetes deployment with OpenJDK 11, and NGINX as a proxy. 
The issue seems to be related to the use of the @Push annotation with PushMode.AUTOMATIC and Transport.WEBSOCKET_XHR and the scheduled gui component update. 
In my scenario, I have a dashboard view that is updated every 30 seconds and show the new data without refresh the page.

Error Log:
```
INFO|10-21 20:30:57|ServerRpcHandler|> Ignoring old duplicate message from the client. Expected: 870, got: 869
WARN|10-21 20:31:03|ServerRpcHandler|> Resynchronizing UI by client's request. Under normal operations this should not happen and may indicate a bug in Vaadin platform. If you see this message regularly please open a bug report at https://github.com/vaadin/flow/issues
WARN|10-21 20:31:03|ServerRpcHandler|> Resynchronizing UI by client's request. Under normal operations this should not happen and may indicate a bug in Vaadin platform. If you see this message regularly please open a bug report at https://github.com/vaadin/flow/issues
... (similar warnings continue a lot of times)
```

**Problem Description:**
After some activity in my application, it starts to write these warnings to the log and experiences a slowdown. The Kubernetes Dashboard shows that the application's memory usage reaches 2.5GB.

This issue seems to be connected to the usage of the @Push annotation with **PushMode.AUTOMATIC and Transport.WEBSOCKET_XHR.** 
In my application, I have enabled background updates using the com.google.common.eventbus.EventBus, which is correctly registered and invoked in the components using the @Subscribe annotation.

I suspect that there might be an issue with the way Vaadin handles resynchronization under certain conditions, causing a performance degradation and log warnings.

I kindly request your assistance in investigating and resolving this issue as it significantly impacts the stability and performance of our application.

Thank you for your prompt attention to this matter.

### Expected behavior

I expect that the application, when using the @Push annotation with PushMode.AUTOMATIC and Transport.WEBSOCKET_XHR, should operate smoothly without any slowdowns or resynchronization issues. Updates should be handled efficiently, and the application should not generate log warnings as mentioned in my report. Additionally, I expect the application's memory usage to remain within acceptable limits and not excessively exceed 2.5GB

### Minimal reproducible example

1. Create a new Vaadin 14.10.2 project. Begin by creating a new Vaadin project with version 14.10.2.
2. Create a MainView with refreshable components: Create a MainView class that displays a series of components that can be automatically refreshed, for example, every 30 seconds. 
3. Enable @Push with the specified configuration: Enable the @Push annotation with the specified configuration in the project.
Use EventBus and configurations: Utilize EventBus in conjunction with @Configuration, @EnableScheduling, and @EnableAsync to create a component that makes requests to fetch data for updates.
4. Implement code for component updates: Implement the provided code that allows automatic updating of components based on Vaadin examples. using the runWhileAttached method.
5. Configure an NGINX proxy: Configure an NGINX proxy server to enable access to the Vaadin application.
6. Launch the application with Spring Boot: Start the application using Spring Boot and verify if the reported issue occurs.

### Versions

- Vaadin / Flow version: 14.10.2 + SpringBoot
- Kubernetes v1.21.11
- docker 20.10.14
- openjdk version "11.0.12"
- nginx/1.18.0 (Ubuntu)

**Comment by gianluca-valentini** [comment]
Hi @mshabarov 
thanks for your help. I will try to understand if I can update the vaadin version ad the application is deplyed on our customer.
For the method, I used the one present in https://demo.vaadin.com/charts/SplineUpdatingEachSecond

**Comment by gianluca-valentini** [comment]
Hi @mshabarov 
I am currently using Vaadin version 14.10.2 in my application. I am considering updating to version 14.10.8, as you have suggested. However, before proceeding with the update, I would like to inquire about the specific changes and any significant impacts that I should be aware of.

Could you please provide information on the following:

1. Notable changes or new features introduced in Vaadin 14.10.8 compared to 14.10.2.
2. Any potential breaking changes or compatibility issues that may affect my existing codebase.
3. Recommended best practices or considerations for a smooth transition to version 14.10.8.

I want to ensure that the update process is as seamless as possible and that my application remains stable and functional. Your insights and guidance on this matter would be greatly appreciated.

Thank you for your assistance.

**Comment by gianluca-valentini** [comment]
@mshabarov thanks a lot
Maybe I switch to Vaadin version 14.10.9, which was released a few days ago. After considering the potential benefits and improvements it offers, I believe it is the right choice for my project.

Thank you for your support.

**Comment by gianluca-valentini** [comment]
Hi @mshabarov 
after some day where I update the vaadin version to 14.10.8 I can see that the memory  consumption seems to be stable but I continue to see in the log the warning message about resync 

`16:05:32.196 [http-nio-8080-exec-18] INFO  com.vaadin.flow.server.communication.ServerRpcHandler - Ignoring old duplicate message from the client. Expected: 1059, got: 1058
...(similar warnings continue a lot of times)
16:05:47.096 [http-nio-8080-exec-24] WARN  com.vaadin.flow.server.communication.ServerRpcHandler - Resynchronizing UI by client's request. Under normal operations this should not happen and may indicate a bug in Vaadin platform. If you see this message regularly please open a bug report at https://github.com/vaadin/flow/issues
...(similar warnings continue a lot of rows)
17:55:27.742 [http-nio-8080-exec-20] INFO  com.vaadin.flow.server.communication.ServerRpcHandler - Ignoring old duplicate message from the client. Expected: 1063, got: 1062
...(similar warnings continue a lot of times)
`

**Comment by mcollovati** [comment]
@gianluca-valentini the resynchronizing is usually seen with PUSH long polling transport more than with websocket or websocket-xhr.
Can you double-check that the web socket connection is effectively established and there's, and it is not a fall back to long-polling?
Can you please also share the nginx configuration?

**Comment by mshabarov** [comment]
@gianluca-valentini is this issue still valid for you? If yes, could you please answer questions @mcollovati asked?

**Comment by gianluca-valentini** [comment]
Hi,
it seems that after vaadin update to 14.10.9 there is no log error any more
Thanks
Gianluca
