### ISSUE TITLE
Cannot upload in 24.2.0 (works fine in 24.1.12)

### ISSUE THREAD

**Issue by jflamy-dev** [vaadin/flow#17872]
### Description of the bug

A trivial upload that works fine in 24.1.12 no longer does if the only change done is updating to 24.2.0
```
		MemoryBuffer buffer = new MemoryBuffer();
		Upload upload = new Upload(buffer);
```
fails with "due to Server Error".

There are no exceptions in the logs, and _none_ of the listeners are triggered (started, failed, succeeded, _rejected).

node_modules, package*.json and the vite config files were removed and regenerated.
the dev_bundle was cleared and recreated.

Reverting to 24.1.12 works again after doing the js cleanup routine.

-- end of bug report --

Observation (potentially irrelevant, apologies in advance).  There seem to have been changes in the Vaadin classes used for uploading.  I have another Vaadin program that receives uploads, that uses the same Apache classes.

In 24.1 these classes resolved to Vaadin classes, and I was using them (they work).
```
import com.vaadin.external.apache.commons.fileupload2.FileItem;
import com.vaadin.external.apache.commons.fileupload2.FileUploadException;
import com.vaadin.external.apache.commons.fileupload2.disk.DiskFileItemFactory;
import com.vaadin.external.apache.commons.fileupload2.jaksrvlt.JakSrvltFileUpload;
```

In 24.2 the files no longer resolve to Vaadin classes, and I ended up using more modern version in an attempt to get upload working.
```
import org.apache.commons.fileupload2.core.DiskFileItem;
import org.apache.commons.fileupload2.core.DiskFileItemFactory;
import org.apache.commons.fileupload2.core.DiskFileItemFactory.Builder;
import org.apache.commons.fileupload2.core.FileItem;
import org.apache.commons.fileupload2.core.FileUploadException;
import org.apache.commons.fileupload2.jakarta.JakartaServletFileUpload;
```

### Expected behavior

The upload should work.
The event listeners should trigger.
There should be something in the logs if there is a catastrophic failure.

### Minimal reproducible example

https://github.com/jflamy/owlcms4/blob/alpha/owlcms/src/main/java/app/owlcms/nui/preparation/JsonUploadDialog.java

Please advise if I can activate additional logging.

### Versions

Vaadin: 24.2.0
Flow: 24.2.0
Java: JetBrains s.r.o. 17.0.6
OS: amd64 Windows 11 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.57
Live reload: Java unavailable
          (HotswapAgent): Front end unavailable

**Comment by caalador** [comment]
Hi.
I tested running the upload code (Almost fully copied from the link) in a hello world view using 24.2.0 and could not replicate the problem inside or outside of a Dialog.
Would it be possible to get the issue replicated in a starter from [start](https://start.vaadin.com/app)?

The change to use actual release of commons-fileupload instead of a local copy was intentional and should not have any impact.

**Comment by jflamy-dev** [comment]
Is there any way I can see what the "server error" is ?  I would suspect it is the front-end not finding the upload backend.  I am running with an embedded jetty.  Can you point me at what the code for the upload backend ?

**Comment by jflamy-dev** [comment]
(I want to make sure that I actually use the same classes as does Vaadin -- even though I don't see how my two sub-modules could interact with one another and cause that problem.  But Maven sometimes does "wonderful" interactions.)

**Comment by caalador** [comment]
The server side upload code for 24.2 is here:
https://github.com/vaadin/flow-components/tree/24.2/vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload

**Comment by jflamy** [comment]
Am looking for the servlet that receives the inputs, that would be the one that would be failing (missing a class/conflicting/not found) in my setup.

**Comment by jflamy** [comment]
I use an embedded Jetty (derived from https://github.com/mvysny/vaadin-boot ).  I was able to take the Vaadin Plain Java skeleton and add the embedded Jetty and check that upload does work in that configuration.   The cause is likely clashes in the jetty versions and jakarta dependencies.

You may close the bug, I now have enough to rebuild my app piece by piece until I find the culprit.

**Comment by jflamy-dev** [comment]
The root cause was an old version of commons-io was being used, that had one missing class.  Forcing 2.14.0 instead of 2.8 fixed the issue

**Comment by rucko24** [comment]
> The root cause was an old version of commons-io was being used, that had one missing class. Forcing 2.14.0 instead of 2.8 fixed the issue

that's correct, at the moment with `2.14.0`, but not with `2.16.0`

```xml
<!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.14.0</version>
</dependency>
```
