### ISSUE TITLE
DataProvider created fromFilteringCallbacks has wrong PageSize when Paging

### ISSUE THREAD

**Issue by simasch** [vaadin/flow#17911]
### Description of the bug

If I create a DataProvider with the following code the pageSize in the Query is wrong in the FetchCallback:

    var configurableFilterDataProvider = DataProvider.fromFilteringCallbacks(
                                                     fetchCallback, countCallback).withConfigurableFilter();

If I use setItems instead, everything is fine.

For example, I have 90 elements and the default page size of 50 so the pageSize in the first call to the fetchCallback is 50 but in the second is 40, which results in wrong results.

### Expected behavior

PageSize should always be the same.

### Minimal reproducible example

-

### Versions

- Vaadin / Flow version: 24.1.10

**Comment by mcollovati** [comment]
It might be related to #17750

**Comment by simasch** [comment]
Yes, this looks exactly like my problem.
