### ISSUE TITLE
WebPushException are not thrown in sendNotification

### ISSUE THREAD

**Issue by ElZorrito** [vaadin/flow#17942]
### Description of the bug

Hello,

When I try to send notification to unsubscribed or expired subscription, I have this log errors : 
```
com.vaadin.flow.server.webpush.WebPush   : Failed to send web push notification, received status code:410
com.vaadin.flow.server.webpush.WebPush   : push subscription has unsubscribed or expired.
```
But I can't intercept them in try catch :
```
try {
	getWebPush().sendNotification(subscription, new WebPushMessage(title, body));
} catch (final WebPushException ex) {
	//never pass here
	ex.printStackTrace();
} catch (final Exception e) {
	//never pass here
	e.printStackTrace();
}
```
In `WebPush.sendNotification` I can see that errors are only logged but never thrown.
I want to delete subscription in backend that are unsubscribed or expired.
It can be good to have statusCode in WebPushException or something to determine if we need to delete subscription.

### Expected behavior

Exception have to be thrown in WebPush.sendNotification method

### Minimal reproducible example

I can't share my project

### Versions

Vaadin / Flow version: 24.2.0
Java version: 17
OS version: windows 10
Browser version : chrome 118.0.5993.89
IDE : eclipse 2023-09 (4.29.0)

**Comment by caalador** [comment]
It should throw a `WebPushException` when it fails, but it seems that throw has been forgotten or has disappeared during a merge of branches.

**Comment by ElZorrito** [comment]
Thanks for the fixe, but for me it's not enought.
I think you should although throw an exception if  statusCode != 201. You print error but there is no exception.

**Comment by jasonmcneill** [comment]
@ElZorrito The reason why you may be receiving a 410 HTTP status code may have nothing to do with the push subscription actually expiring.  Check out this quote from a Mozilla engineer who worked on their implementation of Web Push:

> The reason it's instantly 410 is because the system believes it needs to send a message to the "11-TESTING-11" bridge, which doesn't exist, fails, and returns the 410.

https://github.com/mozilla-services/autopush/issues/997#issuecomment-326600169
