### ISSUE TITLE
the vaadin system still requests to install pnpm even though it has been turn off  in build.gradle and application.properties

### ISSUE THREAD

**Issue by Rystars** [vaadin/flow#17967]
### Description of the bug

in version 24.2.0+ the vaadin system still requests to install pnpm even though it has been turn off in build.gradle and application.properties

![logs.txt](https://github.com/vaadin/flow/files/13225205/logs.txt)

↑that is the error log

### Expected behavior

I hope it will be fixed soon so that you don't request to install again

### Minimal reproducible example

use vaadin version 24.2.0 -> turn off pnpm using ```pnpmEnable = false``` in build.gradle -> then run the vaadin project

### Versions

- Vaadin / Flow version:24.2.0
- Java version:17
- OS version: Android 11
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mcollovati** [comment]
In `PrepareFrontendInputProperties`, among the other properties, we track pnpm executables to detect if the prepare frontend task is up-to-date or not.
However, this triggers the installation of the tool, if it is not present.
