### ISSUE TITLE
[Regression] Unexpected order of JavaScript execution in prod mode

### ISSUE THREAD

**Issue by vursen** [vaadin/flow#18016]
### Description of the bug

We have a [TooltipConfiguration](https://github.com/vaadin/flow-components/blob/4dd190bea5c0549f415bd2729f5093fd8606cfbd/vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/TooltipConfiguration.java) that registers a [UIInitListener](https://github.com/vaadin/flow-components/blob/4dd190bea5c0549f415bd2729f5093fd8606cfbd/vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/TooltipConfiguration.java#L86C1-L87) to run [some JavaScript](https://github.com/vaadin/flow-components/blob/4dd190bea5c0549f415bd2729f5093fd8606cfbd/vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/TooltipConfiguration.java#L92-L110) that ensures the default global configuration for tooltips. This JavaScript assumes that the `@JsModule` dependencies, particularly `tooltip.ts`, are imported in the browser before its execution.

However, in version 24.3, this no longer works consistently. In dev mode, everything still works as expected. In prod mode, the Flow client starts executing UIInitListener's JavaScript before the `@JsModule` dependencies become available, which then results in an "undefined method" error on the client-side. 

### Expected behavior

The `executeJS` instructions scheduled in `UIInitListener` should be executed only after the `@JsModule` dependencies are imported in the browser. 

### Minimal reproducible example
1. `git checkout bug/ui-init-listener` in `flow-components`.
2. Run `mvn clean install -Drelease -DskipTests`
3. Run `mvn jetty:run -Drun-it -Drelease -f vaadin-button-flow-parent/vaadin-button-flow-integration-tests`
4. Open `http://localhost:8080/vaadin-button/tooltip-defaults` and reload to get `UIInitListener` invoked.
5. Observe several JS errors in the browser log.

### Versions

- Vaadin / Flow version: 24.3
- Java version: 17
- OS version: Mac OS

**Comment by mshabarov** [comment]
Covered by changes in Tooltip configuration initialisation via https://github.com/vaadin/flow-components/pull/5724.
