### ISSUE TITLE
Gradle Plugin for Vaadin 23 compiled with JDK17, should be: JDK11

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow#18011]
### Description of the bug

`Cause: com/vaadin/gradle/VaadinPlugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0 `
[git@github.com](mailto:git@github.com):vaadin/base-starter-gradle.git
for v23

This is from my memory, and I may have made a mistake -- but please can you check. Thank you.

### Expected behavior

compile Gradle Plugin with target JDK11

### Minimal reproducible example

[git@github.com](mailto:git@github.com):vaadin/base-starter-gradle.git

Use JDK11 yourself so that any JAR compiled with V17 starts coughing.

### Versions

- Vaadin / Flow version: 23
- Java version: 11
- OS version: n/a
- Browser version (if applicable): n/a
- Application Server (if applicable): n/a
- IDE (if applicable): n/a

**Comment by ZheSun88** [comment]
I did the following steps:

- git clone git@github.com:vaadin/base-starter-gradle.git
- git checkout v23
- ./gradlew clean
- ./gradlew appRun
   -  works fine with me 
![image](https://github.com/vaadin/flow/assets/31067185/397cccb4-1fa5-4642-8b34-1bd26f78bbd2)
- ./gradlew build -Pvaadin.productionMode
  - build log shows build successful. 
![image](https://github.com/vaadin/flow/assets/31067185/5c000c59-a429-499b-b422-3d1759d7e08d)


here is my environment
- openjdk version "11.0.20" 2023-07-18
- vaadin version 23.3.26

**Comment by enver-haase** [comment]
Thank you for checking. Please close. I believe I must have made some mistake back then.
