### ISSUE TITLE
DataCommunicator flush not cancelled when grid is detached between registration and execution of flush

### ISSUE THREAD

**Issue by mperktold** [vaadin/flow#18020]
### Description of the bug

The DataCommunicator delays flushing data to the client using `UI::beforeClientResponse`.

Usually, when the Grid is removed after calling refreshAll, flushing the data is cancelled, which is as expected.

However, if removing the grid also happens inside `UI::beforeClientResponse` but before flushing the data, the data is still flushed.

In our case, this led to a NullPointerException, because we nulled out objects that are needed needed in a column's ValueProvider.

### Expected behavior

The example application below should remove the grid gracefully when clicking the button.

Instead, it currently fails with a NullPointerException, because it tries to refresh the grid after it has been detached, since one of column's ValueProviders uses a field that has been set to null on detach.

The exception should not happen because flushing the data should be cancelled when the grid is detached.

### Minimal reproducible example

Open the following view in a browser and click on the button:

```java
public class HelloWorldView extends VerticalLayout {

    private ValueProvider<String, Integer> valueProvider = String::length;

    public HelloWorldView() {
        var grid = new Grid<String>();
        grid.addColumn(ValueProvider.identity())
            .setHeader("Col 1");
        grid.addColumn(bean -> valueProvider.apply(bean))   // Uses field that will be set to null
            .setHeader("Col 2");
        grid.addDetachListener(e -> valueProvider = null);

        GridListDataView<String> dataView = grid.setItems("one", "two", "three");

        var button = new Button("Refresh and remove grid", e -> {
            // before client response, first remove the grid before flushing
            getUI().orElseThrow().beforeClientResponse(grid, ctx -> grid.removeFromParent());
            // request flush
            dataView.refreshAll();
        });

        setMargin(true);
        add(button, grid);
    }
}
```

### Versions

- Vaadin / Flow version: 24.2.2
- Java version: Eclipse Temurin 17.0.8
- OS version: Windows 10 64 bit

**Comment by mshabarov** [comment]
@mperktold thanks for the issue.
May I ask you one clarification question before we start investigating it: why do you use `beforeClientResponse` to remove the Grid? I assume just removing the Grid would be enough: `grid.removeFromParent();`. Do you have multiple "removal" or any UI updates that you want to run in the end of request handling?

Also, it's not clear for me why this is a problem, because DataCommunicator places a flush request only when component is attached:
```java
stateNode.runWhenAttached(ui -> { // put flush request into the queue }. 
```

**Comment by mperktold** [comment]
Actually, I came up with this reproducer by analyzing the code in Flow and trying to find a way that triggers the same behavior.

In the meantime, I figured out that in our project, this happens in a slightly different manner:

```java
public class HelloWorldView extends VerticalLayout {

    private ValueProvider<String, Integer> valueProvider = String::length;

    public HelloWorldView() {
        var grid = new Grid<String>();
        grid.addColumn(ValueProvider.identity())
            .setHeader("Col 1");
        grid.addColumn(bean -> valueProvider.apply(bean))   // Uses field that will be set to null
            .setHeader("Col 2");

        grid.addDetachListener(e -> {
            valueProvider = null;
            e.getUI().beforeClientResponse(grid, ctx -> Notification.show("detached"));
        });

        GridListDataView<String> dataView = grid.setItems("one", "two", "three");

        var button = new Button("Refresh and remove grid", e -> {
            // before client response, first remove the grid before flushing
            dataView.refreshAll();
            grid.removeFromParent();
        });

        setMargin(true);
        add(button, grid);
    }
}
```

So the grid is not removed inside `UI::beforeClientResponse` but just normally after `dataView.refreshAll()`. However, inside a detach listener of the grid, another unrelated task is passed to `UI::beforeClientResponse`. So internally, even though the grid's state node was removed from `StateTree.pendingExecutionNodes` when it is detached, it is added again because of the second call to `UI::beforeClientResponse`.

This problem only arises if the second call to `UI::beforeClientResponse` happens *during* detach. Because first the node is removed from `StateTree.pendingExecutionNodes`, then all detach hooks and listeners are called, and then the node is marked as detached, i.e. only then `isAttached()` returns false.

As to why we are doing this:

In our case, the call stack can be quite deep, so the code that uses `UI::beforeClientResponse` doesn't know it is called from within `onDetach`, and it also can't figure it out using e.g. `isAttached()` because it would still return true.

The concrete scenario is the following:

We have a view with a grid, where you can open an item in a dialog. When closing the dialog, it returns the focus to the grid so you can navigate with the keyboard. It happens to use `UI::beforeClientResponse` for that. At the same time, we use inline editing for the current item.

When you navigate to a different view, both the grid and the dialog will be detached, and the inline editor is closed. Closing the inline editor triggers a data refresh, and closing the dialog triggers a focus.

I can imagine some workarounds, like managing a `detachRequested` flag, but it would be simpler and more robust if listeners wouldn't be called in such an "in-between state" were a node is already unregistered from the StateTree but still indicates that it `isAttached()`.

**Comment by mperktold** [comment]
Digging down further into this, I found another reason `beforeClientResponse` is called on detach, namely `DropTarget`.

When the grid has been configured as a drop target, the example breaks in the same way even without explicitely calling `beforeClientResponse` in the detach listener, and even if the drop target has been deactivated:

```java
public class HelloWorldView extends VerticalLayout {

    private ValueProvider<String, Integer> valueProvider = String::length;

    public HelloWorldView() {
        var grid = new Grid<String>();
        grid.addColumn(ValueProvider.identity())
            .setHeader("Col 1");
        grid.addColumn(bean -> valueProvider.apply(bean))   // uses field that will be set to null
            .setHeader("Col 2");

        grid.addDetachListener(e -> valueProvider = null);

        GridListDataView<String> dataView = grid.setItems("one", "two", "three");
        // activate grid as DropTarget
        var dropTarget = DropTarget.create(grid);
        // at some later point, DropTarget is not needed anymore
        dropTarget.setActive(false);

        var button = new Button("Refresh and remove grid", e -> {
            // before client response, first remove the grid before flushing
            dataView.refreshAll();
            grid.removeFromParent();
        });

        setMargin(true);
        add(button, grid);
    }
}
```

The reason is the following code in `DndUtil`, which is called by `DropTarget.setActive`, both when passing true and when passing false:
https://github.com/vaadin/flow/blob/99235ffce6564a90eb2f6a6c6585fb1475742c0a/flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java#L114-L138

The comment explains the idea pretty clearly: when the component is detached and then attached again, it should be updated.

However, I think the implementation is flawed.
The detach listener uses `runWhenAttached` to update the component on attach. But as discussed previously, inside detach, `isAttached()` still returns true. Therefore, the component is updated immediately inside the detach listener, not when it is attached again. That is relevant for this issue because updating the component is done using `beforeClientResponse`, which adds the grid again to `pendingExecutionNodes` and so also the grid will be refreshed.

But this is wrong even from the perspective of the DropTarget itself, and probably a bug of its own: The detach listener should explicitly add an *attach listener* instead of using `runWhenAttached`.

On another note, while I see how this idea makes sense if the `DropTarget` is active, I am not so sure about the case when it is inactive. Is there any need to update the component on reattach if its drop target is inactive? Or would it be enough to do that only when/if `setActive` is called with true afterwards?

**Comment by mshabarov** [comment]
Reopened as the patch for it has been reverted in https://github.com/vaadin/flow/pull/18131 due to regressions in components.
