### ISSUE TITLE
Characters typed with the click shortcut key get cleared from input

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow#18048]
### Description of the bug

There seems to be some click shortcut related regression.

With the following view:

```java
var button = new Button("Click me");
button.addClickShortcut(Key.KEY_X).setBrowserDefaultAllowed(true);
add(button, new TextField());
```

(the outcome is the same with `NativeButton` and `Input`)

For some reason, every second character following a press of the click shortcut key gets cleared:

https://github.com/vaadin/flow-components/assets/1222264/19ad5a2b-ed99-4941-b209-36ce68a8773f

Related issue: https://github.com/vaadin/flow/issues/10362

### Expected behavior

The characters should not get cleared from the input:

https://github.com/vaadin/flow-components/assets/1222264/2380f0ac-1912-4356-bb62-f16ecca475e0

### Minimal reproducible example

See description above

### Versions

- Vaadin / Flow version: 24.3-SNAPSHOT

**Comment by tltv** [comment]
Using following instead would fix that:
```
button.addClickShortcut(Key.KEY_X).allowBrowserDefault().setResetFocusOnActiveElement(false); 
```
It calls `setResetFocusOnActiveElement(true)` by default in `ClickNotifier#addClickShortcut`. But Flow team has decided to revert this default behavior back to the previous as it may cause side effects for some after all.
