### ISSUE TITLE
Websocket connection for debugWindow should only work from localhost.

### ISSUE THREAD

**Issue by czp13** [vaadin/flow#18062]
### Describe your motivation

The idea is to check if the browser web socket connection to the server is on the same (local)host. If it is not then it shall not reach the debugWindow implementation (devtools, plugins, etc).

### Describe the solution you'd like

Check the Atmosphere connection and see if we use localhost or not to make the connection.
Relevant class:
- https://github.com/vaadin/flow/blob/67a91564547e5d31a5cec3dbbbb9f33489ca634f/vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java

### Describe alternatives you've considered

Fix this in the relevant project, which uses dev-server as dependency and so dev tools windows, but we discard, closed that PR and work as not optimal or feasible.

### Additional context

We need this fix to be able to fix an issue in another project.

**Comment by Legioth** [comment]
One thing to note is that there might be scenarios when development mode is run on a different host name, e.g. if running the development server through Docker. There should be a configuration option to also allow other host names.

**Comment by manolo** [comment]
We had to configure CI with the parameter to allow running tests in Selenoid

**Comment by Artur-** [comment]
Implemented in #18079
