### ISSUE TITLE
Add function to set borderRadius

### ISSUE THREAD

**Issue by Rystars** [vaadin/flow#18063]
### Describe your motivation

add function to set borderRadius inside Style class

It's possible if you use the ```set("","");```
but it's a bit complicated
![IMG_20231117_171451.jpg](https://github.com/vaadin/flow/assets/96302690/9d76a950-e17e-4a0c-804f-fc4a281d80d3)

I want this function to be easier, and it can also add completeness to the functions in the Vaadin Style class
vaadin version:24.2.3
### Describe the solution you'd like

```
getStyle().setBorderRadius("5px");
```

**Comment by mshabarov** [comment]
@Rystars thanks for the issue! For us it makes sense to add this method. Do you mind to [contribute to Flow](https://github.com/vaadin/flow/pulls) and add this method?

**Comment by Rystars** [comment]
> @Rystars thanks for the issue! For us it makes sense to add this method. Do you mind to [contribute to Flow](https://github.com/vaadin/flow/pulls) and add this method?

okay I will try to add this method, but tell me is it correct not to place the CSS components in this class and enum?

[Style.java](https://github.com/vaadin/flow/blob/main/flow-server/src/main/java/com/vaadin/flow/dom/Style.java)
[ElementConstants.java](https://github.com/vaadin/flow/blob/main/flow-server/src/main/java/com/vaadin/flow/dom/ElementConstants.java)

**Comment by mshabarov** [comment]
These two classes are exact places where this method and used constant are gonna be added. See this PR as a reference. Also, it makes sense to replace all entries of  `set("border-radius", "Xpx")` to a new method.
