### ISSUE TITLE
Using WebComponentExporter always detects changes

### ISSUE THREAD

**Issue by frankvoelker** [vaadin/flow#18076]
### Description of the bug

Using WebComponentExporter to inject Vaadin views into Thymeleaf templates. When I start the application, changes to *.js files are detected even though they are not changed.

Startup time takes a very long time if you have have multiple "exported" views

Log:

`
2023-11-20T13:50:26.780+01:00  INFO 11113 --- [  restartedMain] c.v.f.s.frontend.BundleValidationUtil    : Checking if a development mode bundle build is needed
2023-11-20T13:50:26.918+01:00  INFO 11113 --- [  restartedMain] c.v.f.s.frontend.BundleValidationUtil    : No hash info for 'generated/flow/web-components/my-test.js'
2023-11-20T13:50:26.918+01:00  INFO 11113 --- [  restartedMain] c.v.f.s.frontend.BundleValidationUtil    : Detected changed content for frontend files:
 - generated/flow/web-components/my-test.js

2023-11-20T13:50:26.918+01:00  INFO 11113 --- [  restartedMain] c.v.f.s.frontend.BundleValidationUtil    : A development mode bundle build is needed
`

### Expected behavior

Unchanged files should not trigger bundle builds

### Minimal reproducible example

See https://github.com/frankvoelker/vaadin-test

http://localhost:8080/spring-view

should show the injected view

### Versions

- Vaadin / Flow version:
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mshabarov** [comment]
`WebComponentExporter ` should trigger a new pre-compiled bundle, this is expected, but for further restarts the bundle should be reused if no changes in project.
`stats.json` apparently misses hash codes or entries for web component, thus it says that changes detected. Looks like a bug.

**Comment by tltv** [comment]
@deep-space-explorer thanks for pointing out those cases. I'm only able to reproduce the copytoclipboard.js case. vaadin-grid.css case works for me at least with latest version. Which Vaadin version you use? I would anyway suggest to create a new ticket and include minimal example project to reproduce both issues.

Author's issue is tightly related to automatically generated web-components under `frontend/generated` folder. Files in `frontend/generated` are now detected properly with this patch https://github.com/vaadin/flow/pull/18354. But that won't help with copytoclipboard.js and vaadin-grid.css cases however.

**Comment by tltv** [comment]
One more similar case: https://github.com/vaadin/flow/issues/18365
