### ISSUE TITLE
Getting item's index through DataView/DataProvider API

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#18088]
### Describe your motivation

Vaadin components with listed items can be [scrolled to item by index](https://github.com/vaadin/flow-components/blob/c15728373a7103ca31046bab06a079b3c63f9613/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java#L4528C29-L4528C29). This isn't always possible, because index of an item might be unknown (e.g. depends on the sorting and filtering).

Thus, an API to get the index by item would be helpful for such uses cases.

### Describe the solution you'd like

Proposed solution is to have a new method in `DataView` API for this.

Acceptance criteria:
1. `DataView` interface has a method `int getItemIndex(T item)` (or with a similar name) that takes items object and return the index of this item.
2. `ListDataView` reuses the existing private method `getItemIndex`.
3. `LazyDataView` has a new method for applying a callback for getting an index from backend:
   ```java
   LazyDataView::setItemIndexProvider(T item, Query<T, F> query)
   ```
   and this callback, if being set by developer, contains a logic for project's backend/database.

   This callback is a more convenient way of customising data view, than extending data view class, because then developer would need to create it's own data view class, find a proper data view base class, set up it to component and so on.

   If no callback was given, `LazyDataView` throws an `UnsupportedOperationException` or similar and highlights that it needs a callback to properly fetch the index.
4. For point 4, a practical example is provided showing how this callback can be implemented, for instance, for relational database.

### Additional context

References:
1. https://github.com/vaadin/web-components/issues/1951
2. [Implementation in Viritin add-on](https://github.com/viritin/flow-viritin/blob/4af9c1e301266609e651fc42227af3d5c26650db/src/main/java/org/vaadin/firitin/components/grid/VGrid.java#L80).

**Comment by tltv** [comment]
`AbstractDataView::verifyDataProviderType` blocks `LazyDataView`'s to work for example when using data provider wrapper like `ConfigurableFilterDataProviderWrapper`, which is practical when using filtering with `DataProvider::withConfigurableFilter` call.
It's not possible to use new API for example with this example code documented here: https://vaadin.com/docs/latest/components/grid#lazy-loading.

To fix that, I'll make another PR for better support for wrappers with `LazyDataView`.
