### ISSUE TITLE
Removing a class name causes assertion error

### ISSUE THREAD

**Issue by onuridrisoglu** [vaadin/flow#18099]
### Description of the bug

Adding and then removing a class name on a component causes the [assertion](https://github.com/vaadin/flow/blob/c6db37c7ecf6014912592f9be29e43ec20d2d8e3/flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java#L399C21-L399C35) in below method fail :

```
public void generateChangesFromEmpty() {
        if (isRemoveAllCalled) {
            // if list ever had "clear" change then it
            // should be stored in the tracker
            addChange(new ListClearChange<>(this));
        }
        if (values != null) {
            assert !values.isEmpty();
            getChangeTracker().add(new ListAddChange<>(this, isNodeValues(), 0,
                    new ArrayList<>(values)));
        } else if (!isPopulated) {
            // make change tracker available so that an empty change can be
            // reported
            getChangeTracker();
        }
    }
```

### Expected behavior

assertion should not fail

### Minimal reproducible example

```
component.addClassName("class-name");
component.removeClassName("class-name");
```

### Versions

Vaadin: 23.3.27
Flow: 23.3.24
Java: Eclipse Adoptium 17.0.5
OS: aarch64 Mac OS X 14.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by mshabarov** [comment]
Adding and removing a class name is quite often use cases and, IIRC, the assertions are turned off by default, so this has low impact on projects. And probably this is an incorrect assertion.

**Comment by leifel** [comment]
This is causing a lot of headache to our project. We prefer to run our project with -ea/-enableassertions during testing, in which case we get this assertion error frequently.
