### ISSUE TITLE
Production bundle error when running Hilla tests

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#18106]
### Description of the bug

```
[INFO] --- hilla:2.5-SNAPSHOT:build-frontend (default) @ tests-spring-security-jwt ---
[INFO] Reflections took 425 ms to scan 143 urls, producing 9972 keys and 53191 values
[INFO] Scanning classes to find frontend configurations and dependencies...
[INFO] Visited 1000 classes. Took 347 ms.
[INFO] Checking if a production mode bundle build is needed
[ERROR] Error when checking if a production bundle build is needed
java.lang.NumberFormatException: 'file:../../../../ts/form' is not a valid version!
    at com.vaadin.flow.server.frontend.FrontendVersion.<init> (FrontendVersion.java:160)
    at com.vaadin.flow.server.frontend.FrontendVersion.<init> (FrontendVersion.java:128)
    at com.vaadin.flow.server.frontend.BundleValidationUtil.versionAccepted (BundleValidationUtil.java:452)
    at com.vaadin.flow.server.frontend.BundleValidationUtil.lambda$hashAndBundleModulesEqual$2 (BundleValidationUtil.java:434)
...
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 143 resources. Took 38 ms.
[ERROR] Require bundle build due to missing 'config/needs-build' file.
[INFO] Running Vite ...
```

### Expected behavior

No errors

### Minimal reproducible example

https://github.com/vaadin/hilla/pull/1755

### Versions

- Vaadin / Flow version: 24.3.0.alpha
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mshabarov** [comment]
BundleValidationUtils doesn't take into account possible non-numeric versions for frontend packages. See https://github.com/vaadin/flow/issues/14673 for similar error in Flow.

**Comment by mshabarov** [comment]
Not 100% sure at the moment, but I'd go with always recreating a bundle if a local package is used in the project. The version isn't set, so Flow cannot decide whether the codes of this package have been changed or not.
