### ISSUE TITLE
Binder bean validation is not triggered properly in Vaadin 24

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow#18163]
### Description

When I set a validator on the binder, the setValidationStatusHandler does not show the error.
![image](https://github.com/vaadin/flow-components/assets/51313578/a8fa12fb-7c99-4821-bd47-629f11d1fe5e)

In Vaadin 23, the error was displayed.
![image](https://github.com/vaadin/flow-components/assets/51313578/30291c19-e2a3-4df5-8462-324d60b202f4)

### Expected outcome

The error should be displayed and the binder status should be in error.

### Minimal reproducible example

```
public class HelloWorldView extends HorizontalLayout {

    private Binder<FakeBean> binder = new Binder<>();

    private TextField name = new TextField("Name");
    private TextField name2 = new TextField("Name2");

    private Span errorMessage = new Span();

    public HelloWorldView() {
        FakeBean fakeBean = new FakeBean();
        binder.forField(name).asRequired("name is required")
                .bind(FakeBean::getName, FakeBean::setName);
        binder.forField(name2).asRequired("name2 is required")
                .bind(FakeBean::getName2, FakeBean::setName2);
        binder.setBean(fakeBean);
        binder.withValidator(bean ->
                        Objects.equals(bean.getName(), "test") || Objects.equals(bean.getName2(), "test"),
                "At least one field should be test"
        );
        binder.setValidationStatusHandler(status -> {
            System.out.println("Errors " + status.getValidationErrors().size());
            if (!status.getBeanValidationErrors().isEmpty()) {
                errorMessage.setText(status.getBeanValidationErrors().get(0).getErrorMessage());
                errorMessage.setVisible(true);
            } else {
                errorMessage.setVisible(false);
            }
        });
        add(name, name2, errorMessage);
    }

}
```

See these 2 branches:
https://github.com/jcgueriaud1/spring-proxy-issue/tree/bean-validation-v24
https://github.com/jcgueriaud1/spring-proxy-issue/tree/bean-validation-v23

### Steps to reproduce

Open the view type xx as no field value = test the error should be displayed.

### Environment

Vaadin version(s): 24.1.4

**Comment by rolfwoll** [comment]
I have a similar problem to this related to DateTimePickers in Vaadin 24.4.7

If I change [Jean-Christophe Gueriaud's code snipplet above to use LocalDateTimes and DateTimePickers, then I get the same problem again. 

`public class HelloWorldView extends HorizontalLayout {

    private Binder<FakeBean> binder = new Binder<>();

    private DateTimePicker date1 = new DateTimePicker("Date1");
    private DateTimePicker date2 = new DateTimePicker("Date2");

    private IntegerField field = new IntegerField("test");

    private Span errorMessage = new Span();

    public HelloWorldView() {
        FakeBean fakeBean = new FakeBean();
        binder.forField(date1).asRequired("date1 is required")
                .bind(FakeBean::getDate1, FakeBean::setDate1);
        binder.forField(date2).asRequired("date2 is required")
                .bind(FakeBean::getDate2, FakeBean::setDate2);
        binder.setBean(fakeBean);
        binder.withValidator(bean ->
                        bean.getDate1() == null || bean.getDate2()== null || bean.getDate1().isBefore(bean.getDate2()),
                "date1 should be before date 2"
        );
        binder.setValidationStatusHandler(status -> {
            System.out.println("Errors " + status.getValidationErrors().size());
            if (!status.getBeanValidationErrors().isEmpty()) {
                errorMessage.setText(status.getBeanValidationErrors().get(0).getErrorMessage());
                errorMessage.setVisible(true);
            } else {
                errorMessage.setVisible(false);
            }
        });
        field.setMin(0);
        add(date1, date2, errorMessage, field, new Button("Clear", e-> field.clear()));
    }

}
`
LocalDateTime date1 and date2 properties are added to FakeBean of course.

In this case, validationStatusHandler is called 2 times, first time with the error from the bean level validator and the second time without any errors which clears the previous error message, so it matches the behaviour of this ticket even though it is marked as closed.
