### ISSUE TITLE
Unexcepted warning when README file already exists in src/main/dev-bundle 

### ISSUE THREAD

**Issue by gronono** [vaadin/flow#18210]
### Description of the bug

When README.md file already exists in src/main/dev-bundle , the console shows the following warning :
```
2023-12-05T09:38:57.396+11:00  WARN 51301 --- [onPool-worker-1] c.v.f.s.frontend.TaskRunDevBundleBuild   : Failed to create a README file in src/main/dev-bundle
```

The warning is displayed because `TaskRunDevBundleBuild` uses the method `File.createNewFile` without checking if the file already exists:
```
boolean created = readme.createNewFile();
if (created) {
    FileUtils.writeStringToFile(readme, README,
            StandardCharsets.UTF_8);
} else {
    getLogger().warn(README_NOT_CREATED);
}
```
If the file already exists, `createNewFile` returns false and the warning is displayed.

### Expected behavior

The warning should not be displayed if the file already exists.

### Minimal reproducible example

* Compile, package an application
* Run the application, so the frontend will be generated
* Restart the application

### Versions

- Vaadin / Flow version: 24.2.4
- Java version: 17
- OS version: Linux Mint 21.2
- Browser version (if applicable):
- Application Server (if applicable): Tomcat with Spring Boot 3.2.0
- IDE (if applicable):

**Comment by mshabarov** [comment]
@gronono thanks for this issue. This should be easy to fix and is good as a first issue. Do you mind to create a new pull request in [Vaadin Flow](https://github.com/vaadin/flow) to fix it?
