### ISSUE TITLE
Vaadin Version 24.2.5 breaks Drag n Drop in Grids

### ISSUE THREAD

**Issue by dwlabcube** [vaadin/flow#18221]
### Description of the bug

After upgrading from 24.2.4 to 24.2.5 my Application can not do any Drag N Drop in Grids anymore. Drag event seems not to happen.
Maybe someone can verify this behaviour?

### Expected behavior

DragNDrop to be working as in 24.2.4

### Minimal reproducible example

Well, i might be the only one, or elsewise everyone will have the same effect.

### Versions

- Vaadin / Flow version: 24.2.5
- Java version: 21
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by knoobie** [comment]
If you are using the Grid within a Dialog: The problem is known and already fixed; release TBD.

**Comment by dwlabcube** [comment]
Yes i was using within a Dialog. Thank you a lot for clarification. Sorry if there was already an open issue, i didn't find it.

**Comment by knoobie** [comment]
Issue: https://github.com/vaadin/web-components/issues/6879 

Workaround: `dialog.getElement().executeJs("this.$.overlay._onMouseDown = () => {}");`

**Comment by dwlabcube** [comment]
Thanks, so I close this.
