### ISSUE TITLE
Mouse click selection broken on fields inside dialogs

### ISSUE THREAD

**Issue by oliveryasuna** [vaadin/flow#18222]
### Description of the bug

We recently upgraded from Vaadin Platform 24.2.3 (Flow 24.2.3) to 24.2.5 (24.2.4). Users noticed problems with mouse click selection of some fields.

I have identified the problems to occur only on fields inside dialogs.

When fields are focused via mouse click, whether it be by clicking the label or inside the input, the cursor position is set to the last cursor position for that field. If it is the first time focusing the field, the cursor position is always set to the end.

There is nothing special about the dialog, as demonstrated in the Minimal, Reproducible Example.

Note: Tab navigation works as expected.
Note: Potentially related, [vcf-autocomplete](https://github.com/vaadin-component-factory/vcf-autocomplete/tree/v24) cannot be selected at all via mouse click if inside a dialog.

### Expected behavior

Work as it did before.

### Minimal reproducible example

https://github.com/oliveryasuna/vaadin-flow-24.2.4-dialog-bug

Not reproducible with Vaadin Platform (24.2.4) (Flow 24.2.3).

### Versions

- Vaadin / Flow version: 24.2.5 / 24.2.4
- Java version: N/A
- OS version: N/A
- Browser: Chrome and Firefox

**Comment by knoobie** [comment]
https://github.com/vaadin/flow/issues/18221#issuecomment-1840929113

**Comment by TatuLund** [comment]
It was regression related to bugfix to this issue https://github.com/vaadin/flow-components/issues/5507

The fix has been already reverted.

**Comment by mshabarov** [comment]
Should be fixed in `24.2.6` by reverting the commit caused the regression.
