### ISSUE TITLE
Grid with Drag and Drop Displayed in Dialog regression issue 24.2.4 -> 24.2.5 

### ISSUE THREAD

**Issue by valberico** [vaadin/flow#18223]
### Description of the bug

Drag and drop to reorder rows in a Grid no longer works within a grid that is displayed in a Dialog. Version 24.2.4 works as expected but breaks with version 24.2.5

### Expected behavior

Grid row drag and drop (row reordering) should function as in previous versions. 

### Minimal reproducible example

`var grid = new Grid<>(Class.class);
            grid.setItems(List.of(String.class, Integer.class, Number.class));
            grid.setDropMode(GridDropMode.BETWEEN);
            grid.setRowsDraggable(true);
            var d = new Dialog(grid);
            d.setSizeFull();
            d.open();`

### Versions

- Vaadin / Flow version: 24.2.5
- Java version: temurin-17.0.4.1
- OS version: 14.1.2 (23B92) 
- Browser version (if applicable): Firefox and Safari
- Application Server (if applicable): OpenLiberty 23.0.0.10
- IDE (if applicable): IntelliJ

**Comment by knoobie** [comment]
https://github.com/vaadin/flow/issues/18221#issuecomment-1840929113

**Comment by mshabarov** [comment]
Should be fixed in Vaadin 24.2.6.
