### ISSUE TITLE
trying to get a notification when an asynchronous call is ready

### ISSUE THREAD

**Issue by tombosa** [vaadin/flow#18234]
### Description of the bug

I have a button which launches an asynchronous GET call using a spring boot WebClient(), which returns a Mono<String>. The method is: exportService.export() and i subscribe to it. The response of the call is just 200 with an empty body. The success callback is launched, which i can see, because the console outputs "success". However the Notification is not triggered immediately. Only after i click the export button again, I see again a "success" message in the console and now i see 2 notifications.
I have the following piece of code:
      exportButton.addClickListener(event ->{
            UI ui = UI.getCurrent();
            exportService.export().subscribe(
                                success ->{
                                    System.out.println("success");
                                    ui.access(()->{
                                        Notification  notification = new Notification("success");
                                        notification.setDuration(2000);
                                        notification.open();
                                    });
                                },
                                error -> {}
                        ); }).

### Expected behavior

The notification should be launched immediately

### Minimal reproducible example

      exportButton.addClickListener(event ->{
            UI ui = UI.getCurrent();
            exportService.export().subscribe(
                                success ->{
                                    System.out.println("success");
                                    ui.access(()->{
                                        Notification  notification = new Notification("success");
                                        notification.setDuration(2000);
                                        notification.open();
                                    });
                                },
                                error -> {}
                        ); }).

### Versions

- Vaadin / Flow version:24
- Java version: 17
- OS version:windows 11
- Browser version (if applicable): any
- Application Server (if applicable): 
- IDE (if applicable): intellij

**Comment by mcollovati** [comment]
At a first glance it looks like you have not enabled Push.
Do you have the `@Push` annotation on the AppShellConfigurator implementor?
