### ISSUE TITLE
Flow 24.2 hangs on startup if there is no internet connection (not reliably reproducible)

### ISSUE THREAD

**Issue by jflamy** [vaadin/flow#18269]
### Description of the bug

A production build of a flow application hangs on startup with no message in the logs, when connected to a router that does not have an internet connection. 
Connecting the router to the internet instantly solved the problem

(Unsolicited speculation) This could be a variation of a previous bug where the application did not start when there was no internet address at all (unconnected computer).

This was observed on two different Windows 11 computers.
On one of the computers, the application started after a long delay (could not time it, I would estimate about one minute).
On the other computer, the application never started -- until the internet connection was established.

Unfortunately unable to reproduce right now (see reproducible example section below)

### Expected behavior

The application should not care.  There appears to be some sort of check that requires connectivity.

### Minimal reproducible example

The behavior appeared with versions of the application built with 24.2.3 and 24.2.5

I have not been able to reproduce the behavior again using one of the two computers and an identical router.

### Versions

- Vaadin / Flow version: 24.2.3 and 24.2.7
- Java version: 17
- OS version: Windows 11

**Comment by mshabarov** [comment]
Production build needs many downloads from internet, e.g. maven artefacts, Node.js executable, npm modules.
When Vaadin runs, for instance, `npm install`, it wait for process (npm installation) to complete and then checks the process code:

```
int errorCode = process.waitFor();

            if (errorCode != 0) {
                // logs errors/outputs
                throw new ExecutionFailedException(
                        SharedUtil.capitalize(toolName)
                                + " install has exited with non zero status. "
                                + "Some dependencies are not installed. Check "
                                + toolName + " command output");
            } else {
                logger.info("Frontend dependencies resolved successfully.");
            }
```
So if npm installation return non-zero code, e.g. because of lack of internet connection, Vaadin should interrupt with error logs.

Do you have logs with DEBUG level from these two runs on these two computers?
This could help us to understand where Vaadin stucks exactly.

**Comment by jflamy** [comment]
This is a production build where the build-frontend has been done and all the Maven dependencies have been resolved. Everything is packaged in a single jar.  There should be no npm dependency verification step at all.

The error you show in the code above does not apply to this setting, and it would have been shown in the logs since it is at INFO level.

Please tell me what logs do you want at DEBUG or TRACE level.

**Comment by jflamy** [comment]
To make myself clear: it is **not** the building process that hangs.  It is the **execution** of the production application that results from a production build.
The build is completely done, and the application is packaged as a single executable (a uber-jar).  The Vaadin development pieces are actually excluded from the build as explained in https://vaadin.com/docs/latest/production/production-build#excluding-development-server-module.

Also, the application is NOT marked as PWA.  It is running online, locally to a laptop not connected to the internet, or running on a server on a LAN where the LAN is NOT connected to the internet.

**Comment by mcollovati** [comment]
If it happens also locally, it would be good to run jstack when the process is stuck, to get mite insights on what is happening

**Comment by jflamy** [comment]
The application is either run in a docker container in the cloud (where it has internet access) or locally on a laptop for situations where internet access in not available.  So in the situations where it hangs, running jps + jstack is doable.
Any logs I can bump to DEBUG or TRACE ?

**Comment by mshabarov** [comment]
If you use Spring/Srping-boot, please try adding the `logging.level.com.vaadin.flow.server.frontend=debug` to the `application.properties` to enable debug logs for frontend build-related codes in Vaadin Flow.

**Comment by mshabarov** [comment]
And the logger class is `NodeUpdater` that should log the `npm install` output.

**Comment by jflamy** [comment]
If I may repeat myself
- I am not using springboot
- this is the result of a production build, packaged as a single jar.  There should NOT be any NPM fetching at all.
- the frontend server dependencies ARE EXCLUDED by the pom.xml

**Comment by mshabarov** [comment]
Thanks for the info.
As this is a runtime issue and not related to frontend compilation, we need a thread dump (jstack, jvisualvm or any other tool can be used) to see what is actually hanging/blocked.

For logging, you need to specify a package `com.vaadin.flow.server` for logger. I don't know what implementation do you use, for Logback it is `<logger name="com.vaadin.flow.server" level="DEBUG"/>` entry in the `logback.xml`.

**Comment by jflamy** [comment]
I cannot reproduce with 23.1, closing.
