### ISSUE TITLE
types.d.ts should use .css?inline

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#18330]
### Description of the bug

In Vite 4, you can (incorrectly) import CSS into a variable as
```
import styles from './some.css'
```

It looks like you are importing the css into the `styles` variable while Vite in fact also injects all the contents of `some.css` into the global document.

The correct way to import styles inline is
```
import styles from './some.css?inline'
```

which only puts the styles in the variable and does not inject them globally.

Starting from Vite 5 (Flow 24.3), the first version no longer works.
However, in types.d.ts, there is a definition only for the first case (which should probably be removed from there) and no case at all for the correct way of importing. Thus you get a TypeScript error when you import correctly, which is quite confusing

### Expected behavior

You get no TS error from
```
import styles from './some.css?inline'
```

### Minimal reproducible example

See above

### Versions

- Vaadin / Flow version:
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mshabarov** [comment]
Would adding the `//@ts-ignore` instruction on top of the import line address this issue.
I honestly cannot thing of something else we can do for fixing it.
Maybe add another workaround into `types.d.ts`, need a research.

**Comment by Artur-** [comment]
Workaround? We can probably add the typing info into `types.d.ts`, e.g.
```
declare module '*.css?inline' {
...
}
```
