### ISSUE TITLE
(24.3.1) Spurious "Dev tools functionality denied for this host" message

### ISSUE THREAD

**Issue by jflamy** [vaadin/flow#18351]
### Description of the bug

Local machine has address 192.168.1.174.  When using localhost, all is fine, dev tools work.  When switching to any non-localhost address for the same machine, things don't work.

![image](https://github.com/vaadin/flow/assets/678663/b27d3c16-cee9-42db-90ba-2b581fd3e9c5)

The same happens when accessing from another machine in the LAN.  This could be understood if the message is tied to the new "click UI to go to the code" feature.

Also, the info feature of the development mode box is incomplete under these circumstances
![image](https://github.com/vaadin/flow/assets/678663/739b233e-63d6-4303-9be8-94323a81b8e9)

This is probably related to the new capability to open a development tool at the line of a UI element.  

### Expected behavior

The javascript features should always be available.
If the "click on the UI to see the line in the code" features only work on localhost, the message should be clear.
And ideally, if the IP address is that of the local machine, this should still work.

### Minimal reproducible example

Change "localhost" to the machines' own IP address or to its host name
OR
access the development machine from a peer in the same local area network segment (with firewall permissions set accordingly)

### Versions

Flow: 24.3.1
Vaadin: 24.3.1
Java: JetBrains s.r.o. 17.0.6
OS: amd64 Windows 11 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Live reload: Java unavailable
          (HotswapAgent): Front end active

**Comment by Artur-** [comment]
It is related to #18079 which denies the debug connection by default for others than localhost. This was done because we have and we are adding more functionality that you do not want users you potentially share your app url with to access. 

Now the error message could apparently use some improvement and refer to vaadin.devmode.hostsAllowed which you can set to ”*” if you want to allow all connections

**Comment by jflamy** [comment]
1. The fact that the info is truncated seems to indicate that the feature is truncated outside of localhost -- Are the features for JavaScript error-reporting still available?  
2. Instead of allowing * for all addresses, an option might be to allow for local segments Inet4Address.isSiteLocalAddress().  Or to use CIDR syntax for IPV4.

**Comment by mcollovati** [comment]
> Instead of allowing * for all addresses, an option might be to allow for local segments Inet4Address.isSiteLocalAddress(). Or to use CIDR syntax for IPV4.

`vaadin.devmode.hostsAllowed` can contain a comma separated list of patterns with `?` and `*` wildcards. Not accurate as CIDR, but it should be good enough for most use cases (e.g. `vaadin.devmode.hostsAllowed=192.168.1.*,172.17.?.*`).
Loopback address are always allowed.

Anyway, it looks like documentation for the property is missing

**Comment by jflamy** [comment]
A use case for this feature occurs when testing on WSL2 (Windows Subsystem for Linux). 

Running VSCode from the Linux subsystem works perfectly and, starting a browser on both Linux or Windows works -- `localhost:8080` is redirected magically in both environments. But `vaadin.devmode.hostsAllowed` variable is required to allow the Windows browsers to be accepted.
