### ISSUE TITLE
Reuse the existing tab in browser when Vaadin app is started in dev mode

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#18393]
### Describe your motivation

When Vaadin application is started in dev mode, it always opens a new tab in browser.
This quickly leads to many tabs opened in browser, which is annoying.
Would be good, if Vaadin reused the existing tab in the browser, if it exists.
### Describe alternatives you've considered

-

### Additional context

See [BrowserLauncher](https://github.com/vaadin/flow/blob/main/vaadin-dev-server/src/main/java/com/vaadin/base/devserver/BrowserLauncher.java) (Flow repo) and [Open library](https://github.com/vaadin/open) (Separate Vaadin repo).

**Comment by tepi** [comment]
After some investigation a suitable and reliable enough approach was not found. Via the Open library it is not possible to detect if a certain tab/window is open, or reuse/refresh it.

One idea was to use a marker file which would be written when the browser window is opened for the first time, and on subsequent server starts check if this file exists, and if so, prevent opening another window. Drawbacks here is that we can't really detect if the user has closed the window at some point. A related issue is that it's unclear when and based on what criteria the file should be removed.

One potential option for detecting open tab is the development mode web socket connection. When the server is shut down, the client will keep trying to reconnect every 5000ms. So, when the server is restarted and we get one of these pings, we know that there is an open window for the application and it is enough to refresh that window, which could probably be done with a reload command as a reply to the first ping.

Downside of the last idea is that we would need to have some delayed mechanism on the server side, which would wait for the possible ping, and if it does not arrive, then opens a new window. For the cases when the window is not there, this would of course postpone opening the window, making the application start appear slower. To mitigate this, we could consider making the development mode web socket connection reconnect interval shorter, e.g. 500ms or 1000ms.

**Comment by caalador** [comment]
I have not come up with any better ideas on this either.
Perhaps as there is no way to query for open tabs and waiting for a callback is not that good either we could use the file and check it for the timestamp and after a set time just open a new tab when starting the server. At least it would lessen the opening tabs if the server is restarted often for any reason.

The developer should be able to change the timeout.

**Comment by tepi** [comment]
I agree, that's pretty much the only reliable thing that can be done here.
