### ISSUE TITLE
Push cannot re-establish connection after a while

### ISSUE THREAD

**Issue by abdullahtellioglu** [vaadin/flow#18398]
### Description of the bug

in a Hilla project, if a tab is open for a while it loses connection to the server and cannot establish a new connection due to an invalid JSON response and is stuck in an infinite loop.

<img width="653" alt="ws" src="https://github.com/vaadin/flow/assets/100126447/958c0806-8ca4-4ea7-b22a-72351dbc0355">

I investigated the bug and My findings are below:  

UI cannot parse the JSON that is generated in VaadinService -> wrapJsonForClient.
```
private static String wrapJsonForClient(JsonObject json) {
        return "for(;;);[" + JsonUtil.stringify(json) + "]";
}
```
PushHandler -> callWithUi
```
 try {
                ui = service.findUI(vaadinRequest);
                assert UI.getCurrent() == ui;

                if (ui == null) {
                    sendNotificationAndDisconnect(resource,
                            VaadinService.createUINotFoundJSON(true)); <-- This line
                } else {
                    callback.run(resource, ui);
                }
            }

```
Ajax Request sent from client:

Request: 
`http://localhost:8080/VAADIN/push?v-r=push&debug_window&token=c373d72c-915f-4968-b956-5a9de7520d98&X-Atmosphere-tracking-id=8aed545d-bbe2-4734-8030-7e3b81f4f4bc&X-Atmosphere-Framework=3.1.2-javascript&X-Atmosphere-Transport=streaming&X-Atmosphere-TrackMessageSize=true&Content-Type=application%2Fjson%3B%20charset%3DUTF-8&X-atmo-protocol=true&_=1704383588997`

Request Headers:
```
GET /VAADIN/push?v-r=push&debug_window&token=c373d72c-915f-4968-b956-5a9de7520d98&X-Atmosphere-tracking-id=8aed545d-bbe2-4734-8030-7e3b81f4f4bc&X-Atmosphere-Framework=3.1.2-javascript&X-Atmosphere-Transport=streaming&X-Atmosphere-TrackMessageSize=true&Content-Type=application%2Fjson%3B%20charset%3DUTF-8&X-atmo-protocol=true&_=1704383588997 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Content-Type: application/json; charset=UTF-8
Cookie: ajs_anonymous_id=88e3d32e-0354-43bd-b775-afc727ada910; _gcl_au=1.1.1267265298.1698405917; _ga=GA1.1.30122459.1698405917; _fbp=fb.0.1698405916919.2049096238; ajs_user_id=31000000-0000-0000-0000-000000000001; amplitude_id_08bda4db151effa673a3ccced29a643d=eyJkZXZpY2VJZCI6IjZiMzY1ZDIzLTIzZDUtNDRkYy04ZjdjLTY1ZWJjN2E0YmYxMVIiLCJ1c2VySWQiOiIzMTAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEiLCJvcHRPdXQiOmZhbHNlLCJzZXNzaW9uSWQiOjE2OTkzNzAwNjkyOTYsImxhc3RFdmVudFRpbWUiOjE2OTkzNzA5NDgwMzgsImV2ZW50SWQiOjAsImlkZW50aWZ5SWQiOjAsInNlcXVlbmNlTnVtYmVyIjowfQ==; _ga_YREEFD0WW1=GS1.1.1699377735.11.0.1699377735.60.0.0; cookieconsent_status=dismiss; csrfToken=46abf1dc-7e94-4c25-b4a7-e67081d50186; JSESSIONID=A6578F0167F15ED0C635C9A147F2F238
Host: localhost:8080
Referer: http://localhost:8080/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
```

Response: 
```
for(;;);[{"meta":{"async":true,"sessionExpired":true}}]
```

### Expected behavior

Should establish a new connection.

### Minimal reproducible example

There is no easy way to clear this example. It happens randomly.

### Versions

- Vaadin / Flow version: 24.3.2
- Java version: 17
- OS version: MacOS Sonoma 14.1.1 
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mcollovati** [comment]
One problem here seems to be that the after the dev-tools websocket connection has been closed for some reason, it tries to reconnect with the fallback transport `streaming`, but in `PushHandler` we explicitly check for `websocket` transport to determine if the current request is for dev-tools.

```java
    private boolean isDebugWindowConnection(AtmosphereResource resource) {
        String refreshConnection = resource.getRequest()
                .getParameter(ApplicationConstants.DEBUG_WINDOW_CONNECTION);
        return refreshConnection != null
                && TRANSPORT.WEBSOCKET.equals(resource.transport());
    }
``` 

We should probably define `fallbackProtocol` in `websocket-connection.ts` to `none` or `websocket` to prevent the transport downgrade.

**Comment by mcollovati** [comment]
It can be replicated with the flow starter:
* start the application in dev mode and access the application with the browser
* check that the dev-tools websocket is established and then stop the server
* check the browser console and verify that the dev-tools websocket is trying to reconnect
* after some reconnection attempts, in the console you should see the message `Websocket failed on first connection attempt. Downgrading to streaming and resending`
* dev-tools client should now try to reconnect with `streaming` transport. You should see several http calls like `http://localhost:8080/VAADIN/push?v-r=push&debug_window&token=ae5550fb-2d5d-4df8-86f8-b48edbd3e81b&X-Atmosphere-tracking-id=86c1a029-0a64-463d-83ff-2e018b632c23&X-Atmosphere-Framework=3.1.2-javascript&X-Atmosphere-Transport=streaming&X-Atmosphere-TrackMessageSize=true&Content-Type=application%2Fjson%3B%20charset%3DUTF-8&X-atmo-protocol=true&_=1704998494137`
* restart the server
* Verify that the `[SyntaxError: Unexpected token 'o', "for(;;);[{""... is not valid JSON` error message is printed on the browser console

**Comment by mcollovati** [comment]
Setting `fallbackProtocol` to `werbsocket` in dev-tools `websocket-connection.ts` prevents the `sessionExpired` issue.
However, after restarting the server, the web socket connection cannot be established because the token sent by the browser does not match the new token generated on the server side (as reported in #18404)
