### ISSUE TITLE
Consider moving /frontend directory under /src/main

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/flow#18436]
### Describe your motivation

The standard directory layout of Maven/Gradle projects involves adding source files under `src/main`. However, Vaadin (especially when used with Hilla) currently requires adding JS/TS source files under `/frontend`.

### Describe the solution you'd like

Consider moving the  `/frontend` folder under `src/main` as a default. For backward compatibility, the current location of the `/frontend` folder at the project root can remain supported.

**Comment by mshabarov** [comment]
We currently have the parameter `vaadin.frontend.frontend.folder` for setting a relative custom path for frontend folder, but I'm pretty sure that it's broken as in some parts of Flow the frontend folder path is hardcoded. Needs to be checked.
