### ISSUE TITLE
Unify Flow and Hilla plugins and dependencies

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#18466]
### Describe your motivation

A [hybrid application](https://github.com/vaadin/flow-hilla-hybrid-example/tree/v24) nowadays requires developers to set the Hilla-originated dependencies in the pom.xml, e.g:

- `hilla-maven-plugin` (and Gradle plugin as well)
- `hilla-react-spring-boot-starter` and `hilla-spring-boot-starter`
- `hilla-bom` and `vaadin-bom`
- `hilla-react` and `hilla-lit`

These are confusing, hard to maintain and a subject of unification.

### Describe the solution you'd like

A hybrid application (using Hilla and Flow views/components) should have only Vaadin-originated dependencies
- [vaadin-spring-boot-starter](https://github.com/vaadin/platform/tree/main/vaadin-spring-boot-starter)
- [vaadin-maven-plugin](https://github.com/vaadin/platform/tree/main/vaadin-maven-plugin)
- [vaadin-bom](https://github.com/vaadin/platform/blob/main/scripts/generator/templates/template-vaadin-bom.xml)

Possible solutions:
- Might be enough to set `hilla-react-spring-boot-starter` as a dependency of `vaadin-spring-boot-starter`
- The two maven plugins should be combined into a single plugin. Might be easiest to just rename `hilla-maven-plugin` to `vaadin-maven-plugin` since it does to my knowledge cover everything currently covered by `vaadin-maven-plugin` in addition to the stuff specific to Hilla.
- `vaadin-maven-plugin` after merging with the `hilla-maven-plugin` should still use the pre-compiled bundles for pure Flow apps. The expected output is that it would see that the Hilla deps are in the classpath and always force the hot deploy mode. That have to be changed (maybe by just removing this logic).

### Additional Context

See the [discussion in Slack](https://vaadin.slack.com/archives/C065KMY4D2M/p1703162299287609).

**Comment by manolo** [comment]
But hilla-maven-plugin has different code base to flow-maven-plugin which is the same than vaadin-maven-plugin, so we need somehow to have a mechanism to have both aligned

**Comment by knoobie** [comment]
> Might be enough to set hilla-react-spring-boot-starter as a dependency of vaadin-spring-boot-starter

Please don't bloat the default module; react should be opt-in and not the default for flow apps.

**Comment by tarekoraby** [comment]
@knoobie, we understand the concern. It's super important to us, too, that Flow apps stay sleek and efficient. And we'll do our best to ensure that adding React won't weigh things down. 

Having said that, we also see React as a cool opportunity to give the Vaadin community more options for building awesome web apps. In our view, enabling React support by default for Flow users is an essential component of making Vaadin appealing to a wider audience. It's a bit of a balancing act, and we will do our best to keep things as light and nimble as possible for pure Java developers.

**Comment by knoobie** [comment]
Yeah, I've noticed the React Router in the other PR. I've come to terms with it, because it removes the vaadin-router - which doesn't look like it gets much love ;) 

Like in the past with Vaadin Connect; it should be possible to exclude hilla-* from vaadin-core and the whole application should work. (yes, React Router can stay)

**Comment by Legioth** [comment]
>it should be possible to exclude hilla-* from vaadin-core and the whole application should work. (yes, React Router can stay)

That is indeed the plan.

**Comment by mshabarov** [comment]
Below are listed the sub-tasks that we have to do:
- https://github.com/vaadin/platform/issues/4934
- https://github.com/vaadin/hilla/issues/1979
- https://github.com/vaadin/flow/issues/18505
- https://github.com/vaadin/platform/issues/4936
- https://github.com/vaadin/flow/issues/18506
- https://github.com/vaadin/platform/issues/4944
- https://github.com/vaadin/platform/issues/4946
- https://github.com/vaadin/react-components/issues/229
- https://github.com/vaadin/platform/issues/4945
