### ISSUE TITLE
Include react-components into package.json

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#18506]
### Describe your motivation

Depends on https://github.com/vaadin/platform/issues/4936.

Flow should include react-components from `version.json` of the platform to the `package.json`. If the config parameter `reactRouterEnabled` is set to false, react-components should be excluded by Flow, i.e. not added at all.

### Additional context

Vaadin/Hilla 24.4.

**Comment by knoobie** [comment]
I would like to add: flow should ONLY add react components if hilla is on the classpath.

**Comment by mshabarov** [comment]
Yes, good point, it only makes sense to add Vaadin's react components only to Hilla views.
