### ISSUE TITLE
Pre-compiled bundles feature works as before with Unified Platform

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#18529]
### Describe your motivation

Pre-compiled bundles for development mode and production mode should be available as before for Flow apps (when Hilla isn't used in a project) in 24.4 after Flow/Hilla unification. i.e. when Hilla isn't used in the project. And for Hybrid apps and Hilla apps the hot-deploy mode (Vite dev server) should be triggered automatically.

**Acceptance Criteria:**
- [x] [3 SP] Both pre-compiled bundles (dev and prod) should include React (including `react-router`), `vaadin-router` and Lit dependencies, so that Flow apps can run with pre-compiled bundle with both react-router and vaadin-router (e.h. when Lit templates are used).
- [x] [5 SP] Vaadin Flow automatically detects if Hilla views are used or it's a plain Flow application. Flow chooses between hotdeploy mode and bundle mode at dev mode startup based on whether any Hilla view exists in the application. Hilla views are detected based on the existence of `frontend/routes.ts`, `frontend/routes.tsx`, the content of `routes` object or any file inside `frontend/views/`.
- [x] [3 SP] `vaadin.frontend.hotdeploy` is a boolean parameter as previously, but default value provider should call the auto-detection mechanism. So if it's missing - auto-detection is triggered, if it's blank or `true`, hot-deploy mode is ON. If it's `false` - bundle mode is ON. If some other value, like `foo` or `auto`, Flow throws an exception.
- [ ] [3 SP] Test manually the whole configuration with Hilla app, Flow app and hybrid app to be sure that a proper mode is used.
- [ ] [5 SP] Add tests for hybrid React case into the platform (new module).

19 SP

### Additional context

Vaadin 24.4.

**Comment by Legioth** [comment]
> `vaadin.frontend.hotdeploy` is a string parameter (previously - boolean). If it's missing - auto-detection is triggered, if it's blank or `true`, hot-deploy mode is ON. If it's `false` - bundle mode is ON.

What if it's e.g. `foo` or `auto`?

**Comment by mshabarov** [comment]
I think it should throw in this case. According to a current logic in `DeploymentConfiguration`, we get `Property named '%s' is boolean, but contains incorrect value '%s' that is not boolean '%s'`.

The method `getBooleanProperty()` basically covers this case well, so probably better to keep `boolean` for this property and just change the default value provider.

**Comment by Legioth** [comment]
I think it should not throw for `auto`  since you might in theory want to explicitly set it to that mode.
