### ISSUE TITLE
A configuration property to not show the 'Development mode' popup in the browser

### ISSUE THREAD

**Issue by jorgheymans** [vaadin/flow#18533]
### Describe your motivation

Developers frequently open their application in a private window. The vaadin dev mode dialog pops up each time then which becomes slightly annoying and distracting after a while. 

![image](https://github.com/vaadin/flow/assets/193792/6694f66c-8d5a-463d-9922-5b424f615ebe)

### Describe the solution you'd like

Something like `vaadin.devmode.showPopupInBrowser=false` 

### Describe alternatives you've considered

https://discord.com/channels/732335336448852018/1009201939092865084/threads/1199691913423491113

**Comment by Artur-** [comment]
Where would to put the property? It you put it in `application.properties` or `pom.xml`, it kind of defeats the purpose of noticing that you accidentally deployed to production without a proper production build

**Comment by jorgheymans** [comment]
I would have thought application.properties yes. Managing properties is the bread and butter of dev and ops so it's manageable. 

The popup is not a verifiable proof that the production build is 100% correct anyway, there's several other properties involved. My point of view is that you're giving just a bit more rope and it's up to people to manage this "risk". In any case, deploying a development mode build to production is still deploying a 100% working application, unlike for example deploying to prod with a 'liquibase drop-all' changeset.

**Comment by mstahv** [comment]
@Artur- I don't think that would be a problem, especially if that is not there by default. The Vaadin icon (where you open the developer toooling in the browser) will be still there and if a developer goes and configures the warning away, they probably know what they are doing (and double checks the configuration in build pipeline).

I have been clicking that more than enough recently as well. Maybe there even is a problem/regression with the checkbox (might be also just my habit to start a dozen of test apps in different port -> diffrent config in localstorage 🤷‍♂️).

**Comment by mstahv** [comment]
And yes, I quite often also use "the porn mode" while debugging/testing. Relevant when testing e.g. multi-user functionality.

**Comment by jorgheymans** [comment]
Forgot to mention that Dismiss-ing the popup does not really help in private mode either, it pops up again when refreshing the page.

**Comment by Artur-** [comment]
Right now I think the dismissal info is stored in localstorage. I wonder if we should store it on disk instead so that it would be for the whole machine. It sounds quite rare that you run development and production on the same computer.

**Comment by mstahv** [comment]
That might make sens 👍 Usually it is the same developer that is cliking the app being developed, just differen browsers (or "private windows"). But where to store it properly so that it works in various environments and that the state is not lost ofter mvn clean 🤷‍♂️

**Comment by jorgheymans** [comment]
You could surely solve it by tweaking the storage yes. 

The pop-up is useful perhaps only the first couple of hours when starting Vaadin development. After that you rely on the Vaadin icon in the lower right corner as an indication of dev-mode.

**Comment by Artur-** [comment]
The only purpose of the popup is to prevent accidental deployment of a development build to production as the development build has features that can read/write files on the disk and you do not want those in production

**Comment by jorgheymans** [comment]
I am not sure everyone realizes this, maybe the popup should be made into a severe warning then as it sounds like a security risk rather. 

But still, if the goal is to aid in preventing this, the Vaadin icon present in the lower right corner when running development builds can serve the same purpose. It's quite visible. One could even write a Selenium test for it and block the deployment pipeline if it's detected on the page during QA testing. Just to say there's other ways the risk can be mitigated, it's up to the development team to decide this. 

Anyway, so either the storage is changed so it works in private mode, or a config option to hide it or make it not appear alltogether.

**Comment by jorgheymans** [comment]
It was mentioned on Discord that we could use CSS to hide the popup:

![image](https://github.com/vaadin/flow/assets/193792/437842d3-d3bc-4e69-85f2-5a87491e26ed)

So, maybe all we need to address this 'niche' developer thing is a CSS variable that allows us to use the browser console or a browser plugin like Stylus to target it ?

**Comment by jorgheymans** [comment]
@Artur- just curious was anything done here? I don't see a related commit but maybe i'm looking in the wrong place.

**Comment by Artur-** [comment]
The popup code is part of copilot so it does not show up as linked here. The change that was made is that the dismissal info will be stored in ~/.vaadin instead of local storage in the browser, so selecting "don't show again" will not show it again on that machine
