### ISSUE TITLE
Circular dependencies with VaadinWebSecurity and NavigationAccessControl

### ISSUE THREAD

**Issue by ILikePhysics** [vaadin/flow#18561]
### Description of the bug

I understand that the documentation (https://vaadin.com/docs/latest/security/advanced-topics/navigation-access-control) suggests to expose a `NavigationAccessControlConfigurer` bean using a static block so that it produces a configured `NavigationAccessControl` bean before it eagerly inject it in `VaadinWebSecurity` when that `NavigationAccessControlConfigurer` is put in a class extending `VaadinWebSecurity`. The problem is by doing so, you are no longer able to inject other beans in your `NavigationAccessControlConfigurer` object if you want, for instance, pass it on some application properties.

### Expected behavior

Not having to have to expose a bean in a static method within a class extending `VaadinWebSecurity`.

Would it be better to inject that `NavigationAccessControl` bean as a `ObjectProvider` or `ObjectFactory`, as suggested in the following post: https://github.com/vaadin/flow/issues/18458#issuecomment-1892070358?

### Minimal reproducible example

None

### Versions

Using Vaadin Flow 24.3.3

**Comment by mcollovati** [comment]
https://github.com/vaadin/flow/pull/18463 introduced the usage of ObjectProvider to inject NavigationAccessControl.

**Comment by ILikePhysics** [comment]
oh, I completely missed 24.3.4. Thanks @mcollovati. I will wait for the official 24.3.4 release.
Thanks again!

**Comment by mcollovati** [comment]
I'm not sure that ObjectProvider will allow using non static methods to define beans required by NavigationAccessControl.
Please reopen the issue if you still encounter errors after upgrading
