### ISSUE TITLE
Vaadin 24.2+ breaks wiring of Spring-managed-beans on Spring-boot-devtools reload when implementing AppShellConfigurator

### ISSUE THREAD

**Issue by arbitorius** [vaadin/flow#18565]
### Description of the bug

When a class implements AppShellConfigurator (like the Application in Spring-Boot) and spring-managed-beans are wired into this class, devtools does not find those beans on reload. The application breaks with a NoSuchBeanDefinitionException and won't recover without a restart.

### Expected behavior

DI should just work like in Vaadin versions 24.1.x, where we started our project and which broke by just updating to Vaadin 24.3.x.
We also tried Vaadin 24.2.x, but the problem is the same. The changelog for 24.2 mentions this:

"Faster server reloads for Spring-based applications
Server reload time in Vaadin 24.2 is less by ~53% in average than for Vaadin 24.1, which gives a better developer experience for live-reload of Java changes."

This might be related.

### Minimal reproducible example

Create a new project via https://start.spring.io add Vaadin and devtools.

Copy these classes into the Project:

```java
@SpringBootApplication
public class DemoApplication implements AppShellConfigurator {

	// If you uncomment this, restart and then change something to let devtools do a reload it breaks the application.
	// Alternative: remove the AppShellConfigurator, then it also works.
	// @Autowired
	// private transient Service service;

	public static void main(final String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

}
```
```java
@Component
public class Service {

	public String greet() {
		return "Hello!";
	}

}
```
```java
@Route
public class MainView extends VerticalLayout {

	private final Service service;

	@Autowired
	public MainView(final Service service) {
		this.service = service;

		add(new Div(service.greet()));
	}

}
```

Run it as Spring-Boot and open the page in a browser.

When you uncomment the autowired service in the DemoApplication, restart the app and change e. g. the text from the method greet(), devtools tries to reload but fails with a NoSuchBeanDefinitionException, because it can't find the service.
A full restart of the application is needed to get it running again. Alternatively the AppShellConfigurator can be commented out, then the wiring of the Service in the DemoApplication works fine.

A possible workaround that we found is to not do any DI in the application class which implements AppShellConfigurator but to use an additional class annotated with `@Configuration`.

### Versions

Flow: 24.3.3
Vaadin: 24.3.3
Java: Eclipse Adoptium 17.0.7
OS: amd64 Windows 10 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Iron Safari/537.36
Live reload: Java active
          (Spring Boot Devtools): Front end active

**Comment by TatuLund** [comment]
I was able to reproduce this with both

Vaadin 24.2.6
Spring 3.1.5

and

Vaadin 24.3.2
Spring Boot 3.2.1

**Comment by TatuLund** [comment]
The class in Vaadin's Spring integration that is on the stack trace is this

https://github.com/vaadin/flow/blame/main/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java

And it has not been touched for five years, so for me it looks like this behavior change is not due changes in Vaadin code. But it could be a possibility that there is some change in Spring Boot 3.1 that needs to be taken into account.

**Comment by mcollovati** [comment]
It looks like related to dev mode caching, as pointed out in the issue description.
The failure does not reproduce if  `vaadin.devmode-caching` is set to `false` in `application.properties`

**Comment by mcollovati** [comment]
Interesting also that after removing the `vaadin.devmode-caching` setting and cleaning the project, I'm unable to reproduce the error anymore

**Comment by mcollovati** [comment]
The problem seems to be that the cached `Application.class`  does not match the `Application.class` after restart.
They come from different classloaders, and when `SpringInstantiator` tries to find the bean by type it cannot find it

![image](https://github.com/vaadin/flow/assets/4648894/d563c7f6-0b81-40b5-b666-ad938e7d7cae)
