### ISSUE TITLE
Add "auto" mode to vaadin.frontend.hotdeploy config parameter

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#18578]
### Describe your motivation

`vaadin.frontend.hotdeploy` should be a string parameter now, and a default value provider for this parameter should call the auto-detection mechanism (from #18577) instead of `EndpointRequestUtil.isHillaAvailable()`. 

If in a project the parameter is
- missing or `auto` -> auto-detection is triggered, 
- if it's blank or `true` -> hot-deploy mode is ON. 
- If it's false -> bundle mode is ON. 

For other values, like `foo`, Flow throws an exception.

### Additional context

Vaadin 24.4.

**Comment by caalador** [comment]
Does it actually need to be a String? Wouldn't the `${null}` value for Boolean used in `reactRouterEnabled` and `productionMode` suffice to see if we should use auto detection, hotdeploy or bundle mode?

**Comment by mshabarov** [comment]
The only reason for String is an ability to `auto` value for this parameter that triggers auto-detection, as well as absence of this parameter.

**Comment by caalador** [comment]
But isn't this still the same, except you need to do string comparisons.
If auto is default then it shouldn't be a problem to have the 3 step version with a boolean.

**Comment by mshabarov** [comment]
Yeah, with String it would need extra complexity of course.
Well, I was thinking that it is more convenient to swap `true` or `false` to `auto` and vice versa, rather than deleting and adding the whole parameter.
But perhaps this isn't something that needs a change often. Once you set it, you use it alway. Thus, I'm almost convinced to go with `Boolean`.
