### ISSUE TITLE
Gradle: vaadin.productionMode.get() returns false regardless of -Pvaadin.productionMode

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#18572]
### Description of the bug

In Vaadin 24.2, `vaadin.productionMode` would be a boolean value which would be true if ` -Pvaadin.productionMode` would be supplied on the command line.

Things changed in Vaadin 24.3 - the vaadin.productionMode is a `Property<Boolean>` now. That would be okay however the problem is that the property is always false. The actual effective value of that property is calculated in `PluginEffectiveConfiguration.productionMode`. Unfortunately, the class is internal and the app build.gradle script has no way of accessing that (except for a crazy reflection).

### Expected behavior

Either `vaadin.productionMode.get()` should be made to return the proper effective value, or we should make PluginEffectiveConfiguration public. We could maybe achieve the former by populating the extension object ourselves:
```kotlin
public class VaadinFlowPluginExtension {
  public val productionMode: Property<Boolean> = ObjectFactory.property(Boolean::class.java)
}
```
However, care must be taken that the property keeps its name and origin: that `VaadinFlowPluginExtension.productionMode.toString()` returns `extension 'vaadin' property 'productionMode'` - and I have no idea how to achieve that. Therefore, perhaps it's better to make PluginEffectiveConfiguration public.

### Minimal reproducible example

`build.gradle.kts`:

```kotlin
plugins {
    java
    application
    id("com.vaadin")
}

defaultTasks("clean", "build")

repositories {
    mavenCentral()
}

val vaadinVersion: String by extra

dependencies {
    // Vaadin
    implementation("com.vaadin:vaadin-core:$vaadinVersion") {
        afterEvaluate {
            println(vaadin.productionMode)
            println(vaadin.productionMode.javaClass)
            println("!!!" + vaadin.productionMode.get())
            if (vaadin.productionMode.get()) {
                exclude(module = "vaadin-dev")
            }
        }
    }

    // Vaadin-Boot
    implementation("com.github.mvysny.vaadin-boot:vaadin-boot:12.2")

    implementation("org.jetbrains:annotations:24.0.1")

    // logging
    // currently we are logging through the SLF4J API to SLF4J-Simple. See src/main/resources/simplelogger.properties file for the logger configuration
    implementation("org.slf4j:slf4j-simple:2.0.9")

    // Fast Vaadin unit-testing with Karibu-Testing: https://github.com/mvysny/karibu-testing
    testImplementation("com.github.mvysny.kaributesting:karibu-testing-v24:2.1.1")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType<Test> {
    useJUnitPlatform()
    testLogging {
        exceptionFormat = TestExceptionFormat.FULL
    }
}

application {
    mainClass = "com.vaadin.starter.skeleton.Main"
}
```

run it with `./gradlew clean -Pvaadin.productionMode` and it will still print false.

### Versions

- Vaadin / Flow version: 24.3.3

**Comment by mvysny** [comment]
Workaround is not pretty: use this in your build.gradle.kts:

```kotlin
    implementation("com.vaadin:vaadin-core:$vaadinVersion") {
        afterEvaluate {
            if (vaadin.productionMode.map { v -> getBooleanProperty("vaadin.productionMode") ?: v }.get()) {
                exclude(module = "vaadin-dev")
            }
        }
    }
```

**Comment by mvysny** [comment]
This thread contains very interesting solutions: https://discuss.gradle.org/t/keep-default-value-of-task-property/41848/5

```kotlin
open class AppExtension @Inject constructor(
    project: Project
) {
    val name: Property<String> = project.objects.property(String::class.java)
        .convention(project.provider { project.name })
```

or inject `ObjectFactory` and/or `ProviderFactory`. This could be the way to go!

**Comment by mvysny** [comment]
Awesome, thanks for pulling :pray: Will this please be backported to 24.3.x @mcollovati  ?

**Comment by mcollovati** [comment]
Make sense, since the bug was reported for 24.3
