### ISSUE TITLE
Auto-detect of Hilla application based on Hilla views in frontend folder

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#18577]
### Describe your motivation

Vaadin Flow should automatically detect if Hilla views are used or it's a plain Flow application. Flow chooses between hot-deploy mode and bundle mode at startup based on whether any Hilla view exists in the application. 

Hilla views are detected based on the existence of `frontend/routes.ts`, `frontend/routes.tsx`, the content of routes object and any file inside `frontend/views/`.

This should replace existing `EndpointRequestUtil.isHillaAvailable()` checks, as `EndpointRequestUtil.isHillaAvailable()` is true always now with unified platform.

### Additional context

Is there anything else you can add about the proposal?

**Comment by tltv** [comment]
`EndpointRequestUtil.isHillaAvailable()` is still useful after adding new method to check if Hilla views are used. It will tell if hilla endpoint is in the classpath (whole hilla could be excluded explicitly for some cases), new method will tell if hilla views are used.

**Comment by mshabarov** [comment]
So "is Hilla used in the project" would mean "isHillaAvailable() AND Hilla views are used".

**Comment by tltv** [comment]
Precisely. And now that you mention that, it probably makes sense to add another utility method called `isHillaUsed(File frontnedDir)` in `EndpointRequestUtil` that does that.

**Comment by mshabarov** [comment]
`EndpointRequestUtil` is probably not a best place where this should be added, we can create a new util/helper class or extend `FrontendUtils`.
