### ISSUE TITLE
Vaadin startup is failing.

### ISSUE THREAD

**Issue by KotlinFactory** [vaadin/flow#18611]
### Description of the bug

Please, double check that those files exist. If you use a custom directory for your resource files instead of default `frontend` folder then make sure you it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)

        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[na:na]
Caused by: java.lang.IllegalStateException: 

  Failed to find the following files: 
      - ./generated/jar-resources/lit-renderer.ts
      - ./generated/jar-resources/gridConnector.js
      - ./generated/jar-resources/vaadin-time-picker/timepickerConnector.js
      - ./generated/jar-resources/contextMenuConnector.js
      - ./generated/jar-resources/vaadin-grid-flow-selection-column.js
      - ./generated/jar-resources/buttonFunctions.js
      - ./generated/jar-resources/dndConnector.js
      - ./generated/jar-resources/messageListConnector.js
      - ./generated/jar-resources/contextMenuTargetConnector.js
      - ./generated/jar-resources/datepickerConnector.js
      - ./generated/jar-resources/vaadin-big-decimal-field.js
      - ./generated/jar-resources/comboBoxConnector.js
      - ./generated/jar-resources/selectConnector.js
      - ./generated/jar-resources/tooltip.ts
      - ./generated/jar-resources/flow-component-renderer.js
      - ./generated/jar-resources/menubarConnector.js
      - ./generated/jar-resources/virtualListConnector.js
  
  Locations searched were:
      - `../server/frontend` in this project
      - `META-INF/frontend` in included JARs
      - `META-INF/resources/frontend` in included JARs

  Please, double check that those files exist. If you use a custom directory for your resource files instead of default `frontend` folder then make sure you it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)

### Expected behavior

It works when running in the IDE, not when I execute the .jar file.
Well basically this not happening. Should be really self explanatory.

### Minimal reproducible example

start any project and attempt to run the .jar file?

### Versions

- Vaadin / Flow version:
- Java version: Java17
- OS version: MacOS Ventura
- Application Server: Tomcat, SpringBoot 3.1.6

**Comment by mcollovati** [comment]
It looks like that when running the application from a JAR in development mode for the first time, frontend contents from nested JAR files are not unpacked in the `frontend/generated/jar-resources` directory.
The problem seems to be that `TaskCopyFrontendFiles` does not handle nested JARs.

Anyway, usually the application is executed from JAR after a production build (by activating the maven `production` profile), so everything is bundled inside the archive and there is no need for looking to local resource.

**Comment by mshabarov** [comment]
We consider this as a potential bug, but for us the way how you run your app isn't clear: why do you use Vaadin development mode and run the .jar ? Can you use production mode instead to run the .jar, where all the frontend files are bundled?

**Comment by mshabarov** [comment]
Please comment if you still have this issue.
