### ISSUE TITLE
 Support for convention-based stereotype names is deprecated

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow#18632]
When using `@SpringComponent` in a Vaadin 24.3 application with latest version of Spring Boot (3.2.2), the following warning is logged:

> o.s.c.a.AnnotationBeanNameGenerator : Support for convention-based stereotype names is deprecated and will be removed in a future version of the framework. Please annotate the 'value' attribute in @com.vaadin.flow.spring.annotation.SpringComponent with @AliasFor(annotation=Component.class) to declare an explicit alias for `@Component`'s 'value' attribute.

### Example to reproduce

1. Download a starter application for Vaadin 24 + Spring Boot.
2. Add the following bean
```
import com.vaadin.flow.spring.annotation.SpringComponent;

@SpringComponent(value = "MyBean")
public class MyBean { }
```

3. Inject the bean in `MainView` 
```
public MainView(@Autowired GreetService service, @Autowired MyBean bean) { ...
```

4. Start the application (`mvn spring-boot:run`)

**Comment by mcollovati** [comment]
Fixed by #18643
