### ISSUE TITLE
Default development and production bundle ignores react.router.enabled=false

### ISSUE THREAD

**Issue by tltv** [vaadin/flow#18656]
Vaadin's default development and production bundle packages always `index.ts` by copying content from Flow's `index-react.ts` with react router. This is expected so as bundle can have just one router option at the moment. Setting `react.router.enabled=false` doesn't change this. React router is enabled even when disabled with this property.

At minimum, new local bundle should be built automatically when _react router is disabled and default bundle would be used otherwise_. This would ensure that vaadin-router is used instead as very likely is expected with `react.router.enabled=false`.

**Comment by mshabarov** [comment]
A solution would be:
1. To re-build the bundle to not have a react-related content there, or
2. Generate index.ts content conditionally based on this flag and not include into bundle
