### ISSUE TITLE
Incorporate App.tsx in index.ts

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/flow#18660]
For the sake of parsimony, let's incorporate the content of `App.tsx` inside `index.ts` (the latter will then need to be a `.tsx`).

**Comment by mshabarov** [comment]
About `App.tsx` file. It is usually mentioned in various [React and TypeScript tutorials](https://www.thisdot.co/blog/getting-started-with-react-and-typescript) and considered as a main React component. I vote up for moving router provider into index file
```
```
import { createElement } from "react";
import { createRoot } from "react-dom/client";
import {router} from "Frontend/routes";
import { RouterProvider } from "react-router-dom";

function Router() {
    return <RouterProvider router={router} />;
}

createRoot(document.getElementById("outlet")!).render(createElement(Router));
```
however, `App.tsx` may be useful as a starting point for React developers.
Should Flow generate it anyway with some simple content, like:
```
// This file is generated by Vaadin as a starting point for React development
export default function App() {
  return (
      <div>Hello world!</div>
  );
}
```
?

**Comment by mshabarov** [comment]
Discussed internally. Let's NOT generate `App.tsx` file in Flow.
