### ISSUE TITLE
Import ordering in formatter

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#1867]
All IDE users should check their formatters import ordering to match the used ordering.
This information should be added to the documentation and is by default the framework project eclipse ordering.

For IntelliJ IDEA the set ordering that matches the eclipse ordering would be:

- import javax.*
- import java.*
- `<blank line>`
- import all other imports
- `<blank line>`
- import com.google.gwt.*
- import com.vaadin.*
- `<blank line>`
- import elemental.*
- import static all other imports

**Comment by torok-peter** [comment]
Filed #2831 to fix method swapping in generator.

**Comment by pleku** [comment]
The https://github.com/vaadin/flow/blob/master/README.md and https://github.com/vaadin/flow/blob/master/CONTRIBUTING.md both lack the instructions on what people should do to imports.
We should have instructions for setting up the IDE for both Eclipse and IntelliJ IDEA.

**Comment by pleku** [comment]
Documented in the contribution guidelines and it even works for the IDEs most of the times https://github.com/vaadin/docs/tree/latest/articles/guide/contributing
