### ISSUE TITLE
Browser page isn't refreshed after server-side reload

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#18723]
### Description of the bug

Browser page isn't refreshed automatically when you do Java changes and rebuild a project.
Browser shows an offline page instead, saying that connection is lost.
Frontend live-reload seems to work well.

Doesn't work with Vaadin 24.4.0.alpha4. Works with Vaadin 24.4.0.alpha3.

### Expected behavior

Java livereload works.

### Minimal reproducible example

Can be reproduced with spring skeleton starter flow.

### Versions

- Vaadin / Flow version: 24.4.0.alpha4
- Java version: 21
- OS version: Mac
- Browser version (if applicable): Chrome
- Application Server (if applicable): Spring-boot
- IDE (if applicable): IntelliJ IDEA

**Comment by mshabarov** [comment]
Should be re-tested, because it works for others except me.

**Comment by mcollovati** [comment]
Tested on 24.4.0.alpha4 and 24.4-SNAPSHOT and Java hot reload works as expected: server side changes are applied and the browser page is automatically reloaded.
