### ISSUE TITLE
Server returned 405 for xhr

### ISSUE THREAD

**Issue by avdhootu27** [vaadin/flow#18729]
### Description of the bug

I have used @Push annotation with WEBSOCKET_XHR as transport. 
While loading push, I get following error:
- Failed to load resource: the server responded with a status of 405 ()
- Server returned 405 for xhr
- Reconnecting because of XHR failure

and on screen at top right corner I get "Server connection lost, trying to reconnect..." error. 
[Here](https://vaadin.com/learn/training/v14-spring) at 35:34, a solution is given, I tried it but the errors are still there, nothing has changed.
```
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
  return http
          .csrf(AbstractHttpConfigurer::disable)
          .authorizeHttpRequests(auth -> {
                      auth.antMatchers("/").permitAll();
                      auth.antMatchers("/?v-r=uidl&v-uiId=0").permitAll();
                      auth.antMatchers("/?v-r=heartbeat&v-uiId=0").permitAll();
                      auth.antMatchers("/vaadinServlet").permitAll();
                      auth.anyRequest().authenticated();
                  }
          )
          .httpBasic(withDefaults())
          .build();
}
```

And because of these things the UI is not updating.

Note: I am using vaadin with spring boot 2.7

### Expected behavior

Should not get such errors and UI should update properly

### Minimal reproducible example

I am migrating from vaadin 8 to 14 so I am getting this errors, but if you run fresh project with v14 then you might not encounter these errors

### Versions

- Vaadin / Flow version: 14.11.3
- Java version: 11
- OS version: MacOS ventura 13.6.1
- Browser version (if applicable): Chrome
- Application Server (if applicable): Tomcat
- IDE (if applicable): Intellij IDEA

**Comment by knoobie** [comment]
That security configuration is not going to work.

I would highly recommend to upgrade to Vaadin 23 or Vaadin 24. There is also a better Spring Security Integration, where all those problems are not there anymore.

**Comment by avdhootu27** [comment]
But can you please tell me why this is happening? what is the issue?
Or if I want to run it on v14 only then what I will have to do?

**Comment by knoobie** [comment]
Because your configuration is not enough for all requests done for the framework internals. 

Example; has to be perfected for your use-case 

```java

      // Permit access to vaadin's internal communication - /* means the vaadin url-mapping; not the context path
      .requestMatchers(request -> HandlerHelper.isFrameworkInternalRequest("/*", request)).permitAll()
      // Permit access to /login**
      .antMatchers("/login**").permitAll()
      // Permit access to Vaadin logic
      .antMatchers("/vaadinServlet/**", "/VAADIN/**").permitAll()

```

**Comment by mshabarov** [comment]
I agree with @knoobie : the Push requests should be allowed by the security configuration in the project. The security integration (view access checker and other classes) were introduced in Vaadin 17 (or 18, I don't remember) and haven't been back-ported to V14.
