### ISSUE TITLE
PiT 24.4: regression? NpmPackage not added to the package.json

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#18721]
### Description of the bug

It seems that certain NpmPackage are not added to the package.json breaking the build.
Removing the pakage*json files does not help

### Expected behavior

They are added as previously

### Minimal reproducible example

```
git clone git@github.com:vaadin/observability-kit.git
cd observability-kit
git checkout use-hilla-24-4
mvn clean install -DskipTests
cd observability-kit-demo-hilla
mvn
```

### Versions

- Vaadin / Flow version: 24.4-SNAPSHOT

**Comment by tltv** [comment]
Looks like something is missing in observability-kit's hilla starter.
 
NpmPackages are added in [ObservabilityClient](https://github.com/vaadin/observability-kit/blob/main/observability-kit-starter/src/main/java/com/vaadin/observability/ObservabilityClient.java).

But this is in `observability-kit-starter` artifact in `com.vaadin` group. There's another `observability-kit-starter` artifact in `com.vaadin.hilla` group that does not have this class and it's used by the demo and that could explain the missing `@opentelemetry/*` dependencies.

**Comment by heruan** [comment]
While the Flow demo infers the NPM dependencies from the `ObservabilityClient` class annotations, the Hilla demo should get them transitively from `@hilla/observability-kit-client` (defined in `ts/observability-kit-client`). Most probably the Hilla demo needs to be rebuild ground-up.

**Comment by manolo** [comment]
Fixed in https://github.com/vaadin/observability-kit/pull/244
