### ISSUE TITLE
PendingJavaScriptResult.then() stops logging JS errors in the browser

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#18782]
### Description of the bug

This code:
```java
@Route("")
public class MainView extends VerticalLayout {
    public MainView() {
        add(new Button("Click me", e -> UI.getCurrent().getPage().executeJs("aksdalkdalk")));
    }
}
```
logs the javascript error in the browser:

![image](https://github.com/vaadin/flow/assets/254091/859bf8b9-a7b7-49b1-9bc2-c51d8b613b09)

However, this code:
```java
@Route("")
public class MainView extends VerticalLayout {
    public MainView() {
        add(new Button("Click me", e -> UI.getCurrent().getPage().executeJs("aksdalkdalk").then(
                json -> {},
                error -> { throw new RuntimeException("JS failed: " + error); }
        )));
    }
}
```

Stops logging the JS error in the browser:

![image](https://github.com/vaadin/flow/assets/254091/469e74b0-8de6-4efa-86db-3b8ef37e655b)

### Expected behavior

I'd expect the JavaScript exception to be logged in the JS console, regardless of whether `then()` was called or not. That way, I, as a programmer, am immediately notified that there's a JS problem.

### Minimal reproducible example

Paste the code above to skeleton-starter, then click the button. The JS exception is missing.

### Versions

- Vaadin / Flow version: 24.3.5
- Java version: 21

**Comment by Legioth** [comment]
In my mind, you're "catching" the exception with that server-side handler. We wouldn't want to log caught exceptions in the JS console since those might be "expected" exceptions that you want to know about on the server without spamming the JS console.

**Comment by mvysny** [comment]
Good point. The client side stacktrace isn’t probably that important since it will be pointing into the obfuscated flow client code; and the exception will be logged server-side so it’s not lost. I think I changed my mind and the current implementation is good one.
