### ISSUE TITLE
Route changes are not consistently detected when redeploying through Spring Boot Devtools

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#18794]
### Description of the bug

There's something weird going on with updating the route registry when redeploying through Spring Boot Devtools. For some classes, the route registry is updated only after a full server restart whereas a Devtools redeploy is enough for other classes.

### Expected behavior

All view changes should be detected with a regular redeploy.

### Minimal reproducible example

1. Download skeleton-starter-flow-spring-24 from the quick download button on start.vaadin.com
2. Launch using `mvn` or by running the `main` method
3. Add `Test.java` with the following content
```
@Route
public class Test extends VerticalLayout {
    public Test() {
        add(new Text("Test"));
    }
}
```
4. Notice that the server is redeployed but that navigating to `/test` gives an error page
5. Restart the server. Notice that you can now navigate to `/test`.
6. Comment out `@Route` in `Test.java`. Wait for the redeploy and notice that `/test` still renders the view.
7. Restore the `@Route` annotation in `Test.java` and comment out `@Route` in `MainView.java`. Wait for the redeploy and notice that you cannot navigate to `/`.
8. Restore the annotation in `MainView.java`, wait for the redeploy and notice that you can again navigate to `/`.

### Versions

- Vaadin / Flow version: Tested with 24.3.5 and 24.4.0.alpha4
- Java version: 21
- IDE (if applicable): Tested with Eclipse and VS Code

**Comment by sxp267** [comment]
Yes, I'm also facing same issue. This used to work but after some changes it is not. Force restart works again
![image](https://github.com/vaadin/flow/assets/141144321/2eba9c35-b795-474b-8e90-7e634111fe4b)
