### ISSUE TITLE
Remove routes.tsx file when opt-out from React

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#18810]
### Description of the bug

By default, Flow creates `frontend/routes.tsx` file with a basic content having server-side routes entry, if you have hybrid configuration or if you add any JS/TS view into `frontend/views`.

Then, if you remove all the views from frontend directory and fallback to plain Flow app, this file still exists and if you opt-out from React with `reactEnable=false`, this file prevent a project to compile, as all the React deps are removed.
So developers have to remove it manually.

Flow should remove the file, if it's a standard one, and rename it to something like `routes.tsx.bak` and show a warning message that you need to save a content of this file somewhere.

### Expected behavior

Generated file should be removed.

### Minimal reproducible example

Flow+Hilla hybrid starter project.

### Versions

- Vaadin / Flow version: 24.4.0.alpha5

**Comment by mshabarov** [comment]
Just an observation: this happens quite often and produces a lot of TS compilation noise, so looks more like major issue.

Implementation detail: maybe we should move `isReactEnabled` check inside the `TaskGenerateReactFiles` task and if it false, check for this file existence and delete or backup it.

**Comment by tltv** [comment]
To keep file naming consistent in Flow, I suggest to name backup file as `routes.tsx.flowBackup`.
