### ISSUE TITLE
Support for stateless security in Flow

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#18880]
### Describe your motivation

This is a spike issue aiming to figure out what is needed in Flow to support stateless security (authentication) in a way that consistent with the [Hilla's stateless security](https://hilla.dev/docs/react/guides/security/spring-stateless).

### Describe the solution you'd like

The server-side part should be ready, see JWT auth API in [VaadinWebSecurity](https://github.com/vaadin/flow/blob/725c7ad5a836f553f93d31bac992102398dfbb4d/vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java#L552), which is used by Hilla. Flow would need the counter part in Flow client.

### Additional context

Vaadin 24.4.

**Comment by mshabarov** [comment]
As a reference, here is an example of  stateless for Flow demo app in this commit :  https://github.com/vaadin/k8s-demo-app/pull/2/files

And this [configuration](https://github.com/vaadin/k8s-demo-app/blob/v24/src/main/java/com/vaadin/k8s/security/SecurityConfiguration.java) works with 24.4.

**Comment by mcollovati** [comment]
Applying stateless authentication to a Flow application might work, but currently there are a couple of drawbacks related to token expiration and PUSH:

* With changes in Spring Security 6,it looks like the JWT token and cookie expiration time are not updated at every request, so after the expiration time set on login is over, the JWT cookie is removed even if the client is actively contacting the server. Once the JWT cookie is removed, a navigation to another view causes a logout
* PUSH background tasks are not able to obtain authentication details out-of-the-box. Tasks need to be executed with a Spring Security aware executor (e.g. `DelegatingSecurityContextExecutor`, see https://docs.spring.io/spring-security/reference/features/integrations/concurrency.html)

**Comment by mshabarov** [comment]
Also related issues:
- https://github.com/vaadin/flow/issues/18681
- https://github.com/vaadin/flow/issues/14936
- https://github.com/vaadin/flow/issues/13298

**Comment by mshabarov** [comment]
This ticket is closed, as investigation has been done and summary provided.
