### ISSUE TITLE
PiT 24.4: flow does not update entry `"type": "module"` in `package.json`

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#18924]
### Description of the bug

Discovered when [testing](https://github.com/vaadin/hilla/issues/2193) `skeleton-starter-hilla-lit-gradle` in PiT, we have realised that flow since 24.1 is adding the `"type": "module"` when creating a new `package.json` but it is not updating existing ones, causing errors like 

```
Startup of Vite failed. Output was:
✘ [ERROR] "@vaadin/hilla-file-router/vite-plugin.js" resolved to an ESM file. ESM file cannot be loaded by `require`. See https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details. [plugin externalize-deps]

    node_modules/esbuild/lib/main.js:1373:27:
      1373 │         let result = await callback({
           ╵                            ^
```

[Slack discussion](https://vaadin.slack.com/archives/C065KMY4D2M/p1709901333027389)

### Expected behavior

projects upgraded to 24.4.0.alpha9+ that use the `hilla-file-router` do not fail if they don't have the entry already in their package.json

### Minimal reproducible example

checkout branch https://github.com/vaadin/skeleton-starter-hilla-lit-gradle/tree/update-to-v24.4 and run ./gradlew bootRun twice 

### Versions

- Vaadin / Flow version: 24.4.0.alpha0

**Comment by Artur-** [comment]
Vite will also drop support for CJS in the next major: https://vitejs.dev/guide/migration#deprecate-cjs-node-api
