### ISSUE TITLE
Print a warning when an event is blocked by a modal dialog

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#18940]
### Describe your motivation

The recommended way to notify the server is to fire CustomEvent DOM events on the <body> element and then hook DOM listeners server-side to the UI.getCurrent().getElement(). However, those DOM listeners are not being called under specific conditions; if one does not understand those conditions then it's really hard to see what's going on.

For example, Viritin notifies current UI of the GPS location. However, if Viritin's Geolocation is called when a Modal dialog is being open, then the listeners are not being called, as can be seen in https://github.com/viritin/flow-viritin/issues/47 .

### Describe the solution you'd like

If a DOM event targeting current UI is caught and ignored by Vaadin server (e.g. because of modal dialog being opened), Vaadin should log a warning message clarifying the situation.

**Comment by mvysny** [comment]
Related to #15614

**Comment by mcollovati** [comment]
Flow should already print a message, but it is at TRACE level.
@mvysny could you try to set TRACE level for category `com.vaadin.flow.server.communication.rpc` and check if you can see something like

```
Ignored RPC for invocation handler 'XXXXXX' from the client side for an inert node id='YYYY'
```

If this could be the message you expect to see, we can then discuss the better level and if the information is enough or should be improved.

**Comment by mvysny** [comment]
Steps to reproduce: just paste this example to skeleton starter
```java
@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        add(new Button("Open dialog", e -> {
            final Dialog dlg = new Dialog();
            dlg.setModal(true);
            dlg.open();
            dlg.add(new Button("fire event on UI", e2 -> fireEventWithTimeout(UI.getCurrent())));
            dlg.add(new Button("fire event on modal element", e2 -> fireEventWithTimeout(UI.getCurrent().getInternals().getActiveModalComponent())));
        }));
    }

    private static void fireEventWithTimeout(Component target) {
        target.getElement().addEventListener("foo", e -> System.out.println(target + ": DOM Event fired: " + e));
        target.getElement().executeJs("let self = this; setTimeout(() => self.dispatchEvent(new CustomEvent('foo')), 1000);");
    }
}
```

@mcollovati yup you're right, enabling trace level revealed the error log:
```
2024-03-12 09:02:15.926 [] TRACE com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Ignored RPC for invocation handler 'com.vaadin.flow.server.communication.rpc.EventRpcHandler' from the client side for an inert node id='1'
```

**Comment by mvysny** [comment]
I wonder how often would this message be printed in an actual Vaadin app (how common this behavior is). If this happens rarely (and indicates some kind of problem), I'd eleviate the log level to WARN.

**Comment by knoobie** [comment]
I would be against warn at production level.

**Comment by oliveryasuna** [comment]
This would be useful. I agree with @knoobie.

**Comment by mstahv** [comment]
Facing the cluster of issues related to this again when tried to fix [other bugs](https://github.com/vaadin/flow/issues/19114). I think info level logging would be appropriate. Would help to resolve WTFs both during app and component development. I'll draft a PR.

**Comment by mstahv** [comment]
A related bug/enhancement: https://github.com/vaadin/flow/issues/19116
