### ISSUE TITLE
create server-side API to access the current Location and the View chain

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#1894]
When implementing login / logout functionality, as a developer I want to know the URL of the current page / view so that I can save it and restore later after a full page reload caused by a login / logout.

Likewise, I want to know the current view chain so that when implementing logout functionality I can check if an unidentified user has access to the current view (to decide whether or not the user can keep the current page after the logout).

**Comment by jhult** [comment]
Any updates on this?

Currently, I am using the mechanism Karibu-DSL provides seen [here](https://github.com/mvysny/karibu-dsl/blob/master/karibu-dsl/src/main/kotlin/com/github/mvysny/karibudsl/v10/Router.kt).

**Comment by tltv** [comment]
We have following API available at the moment:

- `UIInternals#getActiveViewLocation()` to get currently active `Location`
- `UIInternals#getActiveRouterTargetsChain()` to get currently active route chain (a list of `RouterLayout` components with the active location component)
- `Page#fetchCurrentURL(SerializableConsumer<URL> callback)` to fetch `window.location.href` from the browser.

In addition to these, there is also API to navigate to `Location`, relative URL or to full href via `UI`, `Page` and `Router`.

With these, it looks like all use cases are already covered as long as there's access to `UI` instance.
