### ISSUE TITLE
ReferenceError for React when using PNPM

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/flow#18978]
### Description of the bug

Starting an app in PNPM mode results in the following JS error:
```
Uncaught ReferenceError: React is not defined
    App index.tsx:19
    React 11
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    __require chunk-LNEMQRCO.js:9
    js index.js:6
    __require chunk-LNEMQRCO.js:9
    React 2
    __require chunk-LNEMQRCO.js:9
    js React
    __require chunk-LNEMQRCO.js:9
    js React
    __require chunk-LNEMQRCO.js:9
    <anonymous> react-dom_client.js:38
```

The app doesn't render as a result.

### Expected behavior

The app should work regardless whether you install dependencies via NPM or PNPM.

### Minimal reproducible example

- Download a fresh starter, for example from start.vaadin.com, select 24.4 (Pre) when downloading
- Run `mvn -Dfrontend.hotdeploy=true -Dvaadin.frontend.hotdeploy=true -Dvaadin.pnpm.enable=true -Dpnpm.enable=true` (not sure if you need the vaadin prefix to apply the params, added both to be sure)

### Versions

- Vaadin / Flow version: 24.4.0.alpha14
- PNPM version globally installed via npm: 8.6.6

**Comment by mcollovati** [comment]
Long story short: if you have pnpm >= 8.0 and <= 8.6.12, then you need to upgrade to 8.7 or set `resolution-mode=highest` in `.npmrc`

https://pnpm.io/npmrc#resolution-mode

**Comment by Artur-** [comment]
But Flow could set a better dependency also?

**Comment by Artur-** [comment]
I mean the react related dependency, which apparently needs to be new enough and the specification says an old one is fine?

**Comment by mcollovati** [comment]
Do you mean pin the `@babel/preset-react` version in package.json?
