### ISSUE TITLE
Grid-Component : Errors with Drag-And-Drop and Item-Selection

### ISSUE THREAD

**Issue by SonReimer** [vaadin/flow#18983]
### Description of the bug

A View has a grid for which a Drag-And-Drop with DragMode.BETWEEN is configured and that will navigate to another view on item click. Clicking on an item leads to several javascript erros in the browser console.
In our application this had the effect, that some checkboxes could not be clicked afterwards (something got broken), but I could not reproduce this in the showcase.
if DragAndDrop is deactivated (see if(true)-Statement in class PersonGridDragDrop no errors occur.
[example4.zip](https://github.com/vaadin/flow/files/14329862/example4.zip)

### Expected behavior

I expect that no javascript errors occur on the console

### Minimal reproducible example

See attached example

### Versions

- Vaadin / Flow version: 23.3.33
- Java version: 17
- OS version: Windows
- Browser version (if applicable): Firefox
- Application Server (if applicable): Tomcat
- IDE (if applicable): Eclipse

**Comment by mcollovati** [comment]
The issue was fixed in 24.1 for Grid, but still using ` DropTarget.create(this).setActive(false);` directly would have caused issues.
So the fix has been applied to the main branch and back-ported to 24.3 and 23
