### ISSUE TITLE
Comment in generated routes.tsx is confusing

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#18988]
### Description of the bug

There's a comment in the generated `frontend/generated/routes.tsx` file about making your own customizations to the file. The problem is that the user should only make changes to `frontend/routes.tsx` but not to the file in `frontend/generated/`.

### Expected behavior

The comment should first guide the user to create a copy of the file and only the modify that copy.

### Minimal reproducible example

N/A

### Versions

- Vaadin / Flow version: 24.4.0.alpha15

**Comment by mshabarov** [comment]
Comments added in https://github.com/vaadin/flow/pull/19020.
