### ISSUE TITLE
Flow client should remain operational when `page.executeJavaScript()` throws

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#1900]
When using Flow to execute JavaScript, I expect Flow to handle cases when the given JS code throws an exception / causes a JS run time error (e.g. `undefined is not a function` or `TypeError: Cannot set property 'x' of undefined`). In such cases Flow should not crash and should give meaningful diagnostic messages.

Example where this is not the case:
* pass a buggy script to `page.executeJavaScript()` (e.g. `window.undefined()`)
* navigate to the page that executes the buggy JS
* try navigating to another page
* see that the Flow client fails with the assertion `assert getServerId(valueMap) == -1 || getServerId(valueMap) == lastSeenServerSyncId;` in `MessageHandler.processMessage()`

It looks like the root cause of the issue is that DependencyLoader does not clear the list of callbacks if one of them throws, and after the next navigation it tries to execute old callbacks again:
``` java
private static void endEagerDependencyLoading() {
    eagerDependenciesLoading--;
    if (eagerDependenciesLoading == 0 && callbacks.length() != 0) {
        for (int i = 0; i < callbacks.length(); i++) {
            Command cmd = callbacks.get(i);
            cmd.execute();
        }
        callbacks.clear();
    }
}
```

**Comment by kolle1986** [comment]
Deployed to AWS and same issue happens. Any progress with this?

**Comment by Legioth** [comment]
@kolle1986 A fix for this issue was merged almost two years ago. If you're seeing something similar, then it's probably a different issue. Could you please create a new issue with instructions on how to reproduce.
