### ISSUE TITLE
Gradle vaadinBuildFrontend does not include filesystem dependency to classpath

### ISSUE THREAD

**Issue by elaintarha** [vaadin/flow#19024]
### Description of the bug

Local jar dependency in gradle build file is detected by vaadinPrepareFrontend, but not by vaadinBuildFrontend

On :compile mediaquery is on classpath
In :vaadinPrepareFrontend the js files from mediaquery.jar are placed to frontend/generated/jar-resources
But when :vaadinBuildFrontend runs the classpath to NodeTasks.Builder does not contain mediaquery-5.0.3.jar → js files don’t get scanned and included to generated-flow-imports.

### Expected behavior

JS resources from libs/mediaquery-5.0.3.jar should be included on production bundle but they are not. 

### Minimal reproducible example

https://github.com/elaintarha/vaadin-naughty-dep/tree/main

Build:
./gradlew -Pvaadin.productionMode=true clean build

After build  element-media-query.js is in the frontend/generated/jar-resources directory, but it is not included in generated/flow/generated-flow-imports.js nor is it in prod bundle.

The start and check the problem in the app:
unzip build/distributions/vaadin-naughty-dep.zip /tmp/;/tmp/vaadin-naughty-dep/bin/vaadin-naughty-dep
Navigate to http://localhost:8080 -> Grid does not resize as expected

### Versions

- Vaadin / Flow version: 24.2.12 (24.3.7)
- Java version: JDK19
- OS version: Macos 14.4
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mcollovati** [comment]
For the record: similar issue with maven https://github.com/vaadin/hilla/issues/2230

**Comment by mshabarov** [comment]
I'd treat this as a bug, as at least prepareFrontend and buildFrontend work differently.
