### ISSUE TITLE
Spring boot 3.2 and Vaadin 24.3.x  Connection lost in jar after startup with jetty  - maven/intelli work fine

### ISSUE THREAD

**Issue by Siedlerchr** [vaadin/flow#19041]
### Description of the bug

When I run package and start the jar I see the "Connection lost" bar. 
When I run the same using maven spring boot plugin or directly in intellij it works fine

Spring boot 3.1 and Vaadin 24.2 work fine

### Expected behavior

I run the jar and I see the Welcome page.

### Minimal reproducible example

https://github.com/Siedlerchr/vaadin-spring-jetty-reproducer/

### Versions

- Vaadin / Flow version: 24.3.8 (24.3.7 the same behavior)
- Java version: 21.02. temurin
- OS version: macos 14 sonomo
- Browser version (if applicable): Firefox/Chrome latest
- Application Server (if applicable): jetty 
- IDE (if applicable): Intellij

**Comment by Artur-** [comment]
Vaadin 23 supports Spring Boot 2
Vaadin 24 supports Spring Boot 3

**Comment by knoobie** [comment]
> When I run package and start the jar I see the "Connection lost" bar.

If you package the jar, make sure to use the production mode.

**Comment by Siedlerchr** [comment]
@knoobie  I do and I see in the logs "Vaadin is running in production mode" 
@Artur-  Sorry fixed the title, I use 24.3.8

**Comment by mcollovati** [comment]
My guess is that this is related to Jetty returning a non-null URL for not existing resources via `getResource(String)`: https://github.com/vaadin/flow/issues/18410#issuecomment-1882639949.

This seems to cause Spring Boot to activate `WelcomePageHandlerMapping` that in turn causes request to `/` to be remapped to `/index.html`.
If you look at the response for `http://localhost:8080/\?v-r\=init\&location\=\&query\=` you will see that it is the index.html page.

**Comment by mcollovati** [comment]
Might have been fixed by https://github.com/jetty/jetty.project/pull/11476, but not yet released

**Comment by Siedlerchr** [comment]
Jetty 12.0.8 ist out and for me the issue is fixed now https://github.com/jetty/jetty.project/releases/tag/jetty-12.0.8

**Comment by mcollovati** [comment]
@Siedlerchr thanks for feedback. I'll close the issue, as it seems the problem was related to Jetty,
