### ISSUE TITLE
&v-r=uidl&v-uiId=0 getting attached to url

### ISSUE THREAD

**Issue by avdhootu27** [vaadin/flow#19053]
### Description of the bug

I am updating the page url by:
```java
Location location = new Location(getPath(), QueryParameters.simple(params));
ui.getPage().getHistory().replaceState(null, location);
```

After doing this, the url updates but "&v-r=uidl&v-uiId=0" these things get appended to it. I am not adding them in params those are automatically getting appended. And in that point if I reload the page, the app doesn't work and it shows:
"for(;;);[{"syncId":7,"clientId":6,"timings":[290,3]}]" on screen

How to remove those things?

### Expected behavior

After updating url only those params should be appended to url which I am passing to QueryParameters.simple() method

### Minimal reproducible example

I am getting this by simply doing 
```java
Location location = new Location(getPath(), QueryParameters.simple(params));
ui.getPage().getHistory().replaceState(null, location);
```

### Versions

- Vaadin / Flow version: 14.11.0
- Java version: 11
- OS version: MacOS Ventura 13.6.1
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by Legioth** [comment]
How are `getPath()` and `params` defined?

**Comment by avdhootu27** [comment]
Yes, Just after posting this issue I found that the method which I am using to create params was capturing the parameters for the internal UIDL request. Sorry, I am closing this issue.
