### ISSUE TITLE
can't edit the message which is getting shown while app is building

### ISSUE THREAD

**Issue by avdhootu27** [vaadin/flow#19076]
### Description of the bug

In vaadin 14, I get "The frontend development build has not yet finished. Please wait..." message on browser page before I can see the app for few seconds. 

<img width="794" alt="message" src="https://github.com/vaadin/flow/assets/72180606/9ab673fa-c7ad-4dd6-a3b0-451e834e3895">

Even if I turn `vaadin.production-mode=true`, still I get this message. I don't want this thing to show up, instead I want to change that thing to something custom which I want.

### Expected behavior

Either we get default behaviour of browser (when the page is not loaded) (blank screen) or I should be able to edit that html

### Minimal reproducible example

any vaadin app

### Versions

- Vaadin / Flow version: 14.11.0
- Java version: 11
- OS version: MacOS 13.6
- Browser version (if applicable): Chrome
- Application Server (if applicable):
- IDE (if applicable):

**Comment by Legioth** [comment]
That message is supposed to only be shown in development mode so I guess we'd have to look into why it's also shown in production mode.

**Comment by avdhootu27** [comment]
@Artur- you are right. I missed a step that's why it was showing in production mode. Thanks.
