### ISSUE TITLE
It is not possible to specify Hilla menu information for Flow views

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#19109]
### Describe the bug

You can specify the menu order and icon for client side views e.g. as
```
export const config: ViewConfig = {
    menu: {"order":1,"icon":"file"} ,
};
```

There is no way to define this for Flow views but they are still included in the menu.
The menu class already exists but is always set to null here https://github.com/vaadin/hilla/blob/12282623322771e0351fe3ca5e34f55641a34ddf/packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListener.java#L172

### Expected-behavior

```
@Menu(order=1, icon="file")
@Route("someroute")
public class MyView extends VerticalLayout {
```

### Reproduction

-

### System Info

Vaadin 24.4 alpha20

**Comment by mshabarov** [comment]
Would it be better to have another name, e.g. `AtMenuItem` ? `AtMenu` makes me think that the annotated class is a main menu itself.

**Comment by Legioth** [comment]
It might be confusing if you would see `@Menu` on its own but it will always be used together with `@Route` and I assume the association is clear enough when you see both next to each other.

**Comment by mshabarov** [comment]
Acceptance Criteria:
- [ ] Add a new annotation `AtMenu` in Flow with the same parameters, as in [ViewConfig](https://github.com/vaadin/hilla/blob/a3258b4451215d8b4d2ce4c537c3576d749a9ca3/packages/ts/file-router/src/types.d.ts#L3) API in Hilla, except these three - `rolesAllowed`, `loginRequired`, `route` as they are configured with the existing Flow annotations.
- [] modify the implementation for [collectServerViews](https://github.com/vaadin/hilla/blob/a3258b4451215d8b4d2ce4c537c3576d749a9ca3/packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListener.java#L152) and use `AtMenu` annotation data to fill in the `AvailableViewInfo` object.
- [ ] Use `AtMenu` title parameter for menu item text. If title param is absent - fallback to `AtPageTitle` annotation value. Limitation: `HasDynamicTitle` cannot be used, as view instance may not have been instantiated at that point of time.
- [ ] Quarkus may have problems with not inheritable annotations, but as Hilla is not supported in Quarkus apps this can be left as a limitation for now.
