### ISSUE TITLE
LitRenderer can't use Java records as nested properties

### ISSUE THREAD

**Issue by to-do42** [vaadin/flow#19235]
### Description of the bug

As mentioned in the [docs](https://vaadin.com/docs/latest/components/grid/flow#binding-beans) a lit template can handle nested properties. This seems not to work if the _bean_ is a java record.

### Expected behavior

Java records should be first class citizens for use within Lit templates too.

### Minimal reproducible example

See the example. There are both variants for the relevant _bean_ AudiData:
a) as class
b) as record

If the class variant is used, it works and the grid shows the values.
If the record variant is used, the column remains empty.

hint: the usage of Lombok `@Data` and `@Builder` is only to shorten the example here.
```
@PageTitle("LitTemplate Test")
@Route(value = "test", layout = MainLayout.class)
@PermitAll
public class TestView extends VerticalLayout {

    public TestView() {
        Grid<Todo> grid = new Grid<>();
        grid.addColumn(Todo::getTitle).setHeader("Title");

        String litTemplate = """
            <p>${item.audit.createdBy}</p>
        """;

        grid.addColumn(LitRenderer.<Todo>of(litTemplate)
                .withProperty("audit", dto -> dto.getAudit()))
            .setHeader("Audit");

        // data
        grid.setItems(
            Todo.builder().title("todo-1").audit(new AuditData("Dominik")).build(),
            Todo.builder().title("todo-2").audit(new AuditData("Dominik")).build(),
            Todo.builder().title("todo-3").audit(new AuditData("Dominik")).build()
        );

        add(grid);
    }

    @Data
    @Builder
    public static class Todo {
        private String title;
        private AuditData audit;
    }

    @Data
    public static class AuditData {
        private String createdBy;
        
        public AuditData(String createdBy) {
            this.createdBy = createdBy;
        }
    }

//    public record AuditData(String createdBy) {};
}

```

### Versions

- Vaadin / Flow version: 24.3.9
- Java version: 21
- OS version: MacOS
- Browser version (if applicable): Firefox 124

**Comment by tepi** [comment]
Looks like after a couple of patches (https://github.com/vaadin/flow/commit/b07ac8e56f0ad71994ae5033d504bea77868c0a2 and https://github.com/vaadin/flow/commit/ff10370a5fb66c3951a09fdc2c09c2f8b70371bf) this works correctly with nested records (on 24.4 built from `main` branch).

Here's the code I used for testing:
```
    public HelloWorldView() {
        Grid<Todo> grid = new Grid<>();
        grid.addColumn(Todo::title).setHeader("Title");

        String litTemplate = """
                    <p>${item.audit.createdBy}</p>
                """;

        grid.addColumn(LitRenderer.<Todo>of(litTemplate)
                        .withProperty("audit", Todo::audit))
                .setHeader("Audit");

        grid.setItems(
                new Todo("todo-1", new AuditData("Creator")),
                new Todo("todo-2", new AuditData("Creator")),
                new Todo("todo-3", new AuditData("Creator"))
        );

        add(grid);
    }

    public record Todo(String title, AuditData audit) {
    }

    public record AuditData(String createdBy) {
    }
```

**Comment by to-do42** [comment]
Fine. 👍
Is there a release date for 24.4 .... beta and RC versions came a lot during the last weeks ... 😀
