### ISSUE TITLE
Refresh the view instead of reloading the page when hotswapping takes place

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#19262]
### Describe your motivation

When a class has been hotswapped, Flow currently refreshes the whole page. This reloads all JS files etc which is typically not needed, causes flickering and takes time. 

### Describe the solution you'd like

Flow could re-render the component tree for the current view instead of reloading. The implementation needed for this sounds like exactly what is requested in #19244 although that is a different use case

**Comment by tepi** [comment]
Needs https://github.com/vaadin/flow/issues/19261 to be implemented first

**Comment by mcollovati** [comment]
Releated PR https://github.com/vaadin/flow/pull/19650
