### ISSUE TITLE
Wrong import is suggested in IntelliJ

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow#19268]
### Describe the bug

In 24.4.0.alpha24, IntelliJ is suggesting these 2 imports. I guess the correct one is `./ReactAdapter` but is there a way to not have the `Frontend/generated/flow/ReactAdapter`.

### Expected-behavior

IntelliJ should suggest only one import.

### Reproduction

I'm using a project from start.vaadin.com. Run the project and add this code:
```
import { ReactElement } from "react";
import { ReactAdapterElement, RenderHooks } from "./generated/flow/ReactAdapter";
import { Button } from "@vaadin/react-components";

class ReactExample extends ReactAdapterElement {
    protected render(hooks: RenderHooks): ReactElement {
        const [value] = hooks.useState("value", "initial");
        const sendEvent = hooks.useCustomEvent("example-event", {detail: ""});
        return <Button onClick={() => sendEvent("Bar")}>{value}</Button>
    }
}

customElements.define("react-example", ReactExample);
```

Remove the import and try to auto-import.

### System Info

MacOS, Java 21

**Comment by tepi** [comment]
Flow test code does `import { ReactAdapterElement } from 'Frontend/generated/flow/ReactAdapter.js';` in `test-react-adapter` module. Not sure if correct or not.

**Comment by jcgueriaud1** [comment]
Here is what IntelliJ is suggesting
https://github.com/vaadin/flow/assets/51313578/71bf79a7-5831-44a2-bf28-e1719978965c
