### ISSUE TITLE
Flow UI.navigate() leaves client side router in invalid state

### ISSUE THREAD

**Issue by deniz-frick** [vaadin/flow#19272]
### Situation:
- Main Layout is Hilla/React based
- View A is flow based and has a menu entry
- View B is flow based and reachable over view A

### Issue:
The issue occurs when navigating to view A (navbar), then to view B (programatically with UI.navigate) and then back to view A (navbar).

**This last navigation changes the url but does not trigger a rerender of any kind! View B is still visible!**

### Further notes:
After a little bit of debugging in the browser I found this:
![image](https://github.com/vaadin/flow/assets/31888274/71f9dcc9-5212-4244-9f76-162be0de72ba)
This happened when going back to view A from view B
**The location in the router (`@remix-run/router/router.ts`) is not correct! It is the last location the client router went to.**

View B does not display the correct page title. This is likely related to #14255
This is an image of my "View B" showing that the url is correct but the title is not correct.
![image](https://github.com/vaadin/flow/assets/31888274/d8ee7de1-e187-494b-8ce9-7e0714dcb8ae)
Worthy of note is that my "View A" does not have the title "Panaudicon" so the title changes but actually to the wrong thing.
The title is even wrong when reloading the entire page even though the `@PageTitle` annotation works correctly on other pages as well as the project provided below. I don't have time to investigate this further at this time.

I am unsure if this code has anything to do with this bug but I stumbled over it during stepping through UI.navigate:
That `if` doesn't need to exist.
https://github.com/vaadin/flow/blame/ef580499f7a6e2c3a4ff3681797e0db969ac75cb/flow-server/src/main/java/com/vaadin/flow/component/UI.java#L1997-L2002

### Expected behavior

When clicking a something in the navbar, the clicked view should open.

### Minimal reproducible example

[routerbug.zip](https://github.com/vaadin/flow/files/15133287/routerbug.zip)

- Download and unpack this project.
- Run it (mvn spring-boot:run)
- Click on "A" in the sidenav
- Click the button
- Click on "A" in the sidenav and observe the lack of change

### Versions

- Vaadin / Flow version: 24.4.0.alpha24
- Java version: 21 - GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37)
- OS version: Windows 11 Pro 23H2
- Browser version (if applicable): Edge 124.0.2478.51
- Application Server (if applicable):
- IDE (if applicable): IntelliJ IDEA 2024.1 (Ultimate Edition) Build #IU-241.14494.240

**Comment by mshabarov** [comment]
The title problem looks similar to https://github.com/vaadin/flow/issues/19200, thus I propose to track the progress in that ticket.
