### ISSUE TITLE
V14 failing on frontend compilation during npm install on Tomcat 9

### ISSUE THREAD

**Issue by StefanCov** [vaadin/flow#19370]
### Describe the bug

Building a Vaadin 14 project in dev mode (prepare-frontend) and running that project on Tomcat 9 it seems to fail on npm install.
This only happens on dev build of the project as "npm install" is not ran at "clean install" stage. Therefore, "npm install" is ran at deployment on Tomcat 9. There seems to be a permissions error with npm which I can only guess Tomcat 9 is locking the files? 

The workaround is to run "npm install" before running to project or building with the goal "build-frontend" which essentially does the same thing. As soon as node_modules folder exists with no permission issues, the webapp is free to deploy with no errors and you can clean install and run. I use Netbeans and I know its not supported but I believe it is more of a tomcat issue over anything else.

This works as intended on Tomcat 8 but not Tomcat 9 and also works on Vaadin 23 but not 14.

The example errors are:

`npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, unlink 'D:\Test-Projects\skeleton-starter-flow-spring-14\node_modules\terser-webpack-plugin\node_modules\source-map-support\register-hook-require.js.DELETE.491391f56419911776e681ae5134ca8e'`

`npm WARN tar TAR_ENTRY_ERROR UNKNOWN: unknown error, open 'D:\Test-Projects\skeleton-starter-flow-spring-14\node_modules\@vaadin\vaadin-checkbox\theme\lumo\vaadin-checkbox-group-styles.js'`

It looks like npm install adds the DELETE.<hash> to these files and the Vaadin webapp can no longer find the original filename.

### Expected-behavior

The expected behavior would be that the webapp would run on the tomcat server in dev mode. It would see that npm install has not ran as node_modules doesn't exist. It runs npm install and the application would launch with no errors.

### Reproduction

I use Netbeans for this. Can probably be reproduced on other IDE's that can run Tomcat servers. To reproduce:

1. Download Netbeans (20 also occurs on latest version 21)
2. Download Tomcat 9 (I use Tomcat 9.0.40 but I believe error occurs on latest version also)
3. Download Skeleton Spring Vaadin 14 Application [https://vaadin.com/hello-world-starters](https://vaadin.com/hello-world-starters)
4. Run Netbeans as administrator
5. Open Project in Netbeans (Do not fix problems as it will do npm install)
6. Change POM packaging to WAR not JAR
7. Right click project -> run maven -> goals -> vaadin:dance in goals and ok (Just to make sure node_modules has been removed)
8. Right click project -> clean and build (Should run "clean install" -> prepare-frontend)
9. Click Services in the top left -> right click servers -> add server -> Select Apache Tomcat -> follow stops to add server (May need to edit tomcat-home/conf/tomcat_users.xml to add the username and password.
10. Go back to projects in top left and right click the project and run (This should run the project without the node_modules folder existing) 
11. The tomcat logs should appear, you want to follow the Apache Tomcat 9.0.x not the Apache Tomcat 9.0.x Log, after a while the errors will appear and the application will fail to launch. Further runs will not show the error but will show errors such as "Cant find file" 

### System Info

- Windows 11 Pro - 22H2
- Netbeans 20
- Tomcat 9.0.40
- Vaadin 14.8.x -> 14.11.x (Happens on latest version)

**Comment by tepi** [comment]
Unable to reproduce the issue on macOS, might be something Windows-related. Returning this to the board for now.

**Comment by caalador** [comment]
At least with net beans going through the steps I get a failure, but I see on server start that npm install is started tree time which is probably the problem here. also I see the application starting 2 times
```
2024-12-03 08:51:43.723  INFO 2296 --- [           main] c.v.f.server.startup.DevModeInitializer  : Starting dev-mode updaters in C:\--- folder.
2024-12-03 08:51:43.755  INFO 2296 --- [           main] dev-updater                              : Visited 78 classes. Took 18 ms.
2024-12-03 08:51:43.812  INFO 2296 --- [onPool-worker-1] dev-updater                              : Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
```
```
2024-12-03 08:51:49.399  INFO 2296 --- [           main] c.v.f.server.startup.DevModeInitializer  : Starting dev-mode updaters in C:\--- folder.
2024-12-03 08:51:49.407  INFO 2296 --- [           main] dev-updater                              : Visited 102 classes. Took 3 ms.
Vaadin application has been deployed and started to the context path "/spring-skeleton".
2024-12-03 08:51:49.418  INFO 2296 --- [onPool-worker-2] dev-updater                              : Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
```
```
2024-12-03 08:51:57.469  INFO 2296 --- [nio-8080-exec-2] dev-updater                              : Visited 78 classes. Took 25 ms.
2024-12-03 08:51:57.526  INFO 2296 --- [onPool-worker-3] dev-updater                              : Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
```
And it's after the second spring boot start that the tar warning start to appear.

With node_modules pre installed I can also see that the first started instance is undeployed and stopped and another is started, but this doesn't fail as we do not get 2 `npm install` executions from different dev-updater instances.

**Comment by caalador** [comment]
For me this doesn't seem to work with tomcat 8 either when running from netbeans. It also starts, takes it down and starts again thus getting 2 npm installs running at the same time failing the latter one.
Same happens with Idea when running with Tomcat9, but it does start the application as it doesn't startup twice.
