### ISSUE TITLE
navigation issue with hybrid application

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#19392]
### Describe the bug

Using `24.4.0.beta2` in a hybrid application causes a blank UI after navigating between different routes
![image](https://github.com/vaadin/hilla/assets/31067185/f6a2fc8a-d929-4c51-bca0-b3d6d50f0376)

### Expected-behavior

UI are loaded correctly. 

### Reproduction

```
download the app using this preset https://start.vaadin.com/dl?&preset=test-hybrid-react&projectName=test-hybrid-react&preset=partial-prerelease
unzip
./mvnw
navigate to localhost:8080 [1]
click Hello Hilla
click Hello Flow [2]
```

- [1] 
![image](https://github.com/vaadin/hilla/assets/31067185/180a0008-9ba9-4bcb-a8f8-d05a3369f191)

- [2] the url goes to about:blank#blocked and leave a blank screen
![image](https://github.com/vaadin/hilla/assets/31067185/e0c42562-1cb1-437c-b173-fcd0cc01108b)

### System Info

Vaadin: 24.4.0.beta2

**Comment by tltv** [comment]
Fix should go to Hilla for 24.4 (`RouteUnifyingIndexHtmlRequestListener`) and to flow for 24.5 (`MenuRegistry`). Code that transforms server routes into `AvailableViewInfo` was moved to Flow.
