### ISSUE TITLE
Navigation Trigger is always CLIENT_SIDE

### ISSUE THREAD

**Issue by simasch** [vaadin/flow#19418]
### Description of the bug

The bug https://github.com/vaadin/flow/issues/12770 is back.

	public void afterNavigation(AfterNavigationEvent event) {
		navigationTrigger = event.getLocationChangeEvent().getTrigger();

navigationTrigger is always CLIENT_SIDE

### Expected behavior

When hitting the browser back or triggering browser back with JavaScript the navigation trigger should be HISTORY.

### Minimal reproducible example

See: https://github.com/vaadin/flow/issues/12770

### Versions

- Vaadin / Flow version: 24.3.12
- Java version: 21

**Comment by mshabarov** [comment]
This is a regression from a user point of view, but this may be issue in the Flow / React Router integration, that was introduced in 24.3 and advanced in 24.4.

**Comment by caalador** [comment]
I tried to look into this, but I got the expected triggers HISTORY for browser back and ROUTER_LINK when navigating with a router_link.

Is there some specific setting that should be used?

**Comment by simasch** [comment]
With Version 24.4.7, I cannot reproduce the problem anymore.
