### ISSUE TITLE
Web Components are replaced with React Components in a flow only application

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#19410]
### Describe the bug

When upgrading to 24.4 the package.json is updated and all web-component imports are replaced with react-components.

<img width="1567" alt="grafik" src="https://github.com/vaadin/platform/assets/3968629/ba089dc0-983e-433f-ba19-ef05f00f4c1b">

### Expected-behavior

flow-components are not based on react, therefore web-components should been added; not react-component.

### Reproduction

Any flow 24.4 project with frontendHotdeploy=true

### System Info

24.4.beta3

**Comment by caalador** [comment]
I couldn't replicate this as the packages should get correctly filtered as long as hilla is not on the classpath. `frontendHotdeploy` 
 true or false didn't make a difference.
Did you exclude `com.vaadin:flow-react` from `vaadin(-core)`  and `com.vaadin:hilla` from `vaadin-spring-boot-starter`?

If you did then would you have an hello world type setup that replicates the issue?

**Comment by caalador** [comment]
Seems the react-components are added for a production build, but not for a dev build...

**Comment by knoobie** [comment]
> Did you exclude com.vaadin:flow-react

Thank! That did the trick. Excluding hilla and flow-react does the trick. 

Issue can be closed if you want.

**Comment by caalador** [comment]
Good to hear. 
Also my issue with the production build was that there was an exclusions to exclude `vaadin-dev` which overwrote my flow-react exclusion making it be on the classpath again.

I'll close this issue and if something still comes up just note it here or open a new issue.

**Comment by knoobie** [comment]
@caalador Just build one of my projects with the exact same problem of yours - which makes the maven config really cumbersome.. thanks for the heads up!

**Comment by caalador** [comment]
That should become better after the new artifacts and their usage after vaadin/platform#5230
But good thing I ran into that already so there was a fix for the situation. =)
