### ISSUE TITLE
Vite build errors after upgrading on Vaadin 24

### ISSUE THREAD

**Issue by Dinizzzka** [vaadin/flow#19442]
### Description of the bug
I have vaadin web application with frontend written in typescript. It compiled and works as well for vaadin v23.3.1. 
I have updated vaadin version up to 24.3.11 and got compilation error when run `mvn vaadin:build-frontend` command:
```
[ERROR] frontend/components/network-editor-components/node-editor-components/node-editors/deploy/nodes/HostEditorDialog.ts(71,71): error TS2339: Property 'theme' does not exist on type 'FormLayout'.
[ERROR] frontend/components/network-editor-components/node-editor-components/node-editors/domain/nodes/child-layouts/InnerLayout.ts(120,80): error TS2339: Property 'theme' does not exist on type 'VerticalLayout'.
```
Let's look at the code snippet that fired the error:

```
<vaadin-grid-column
                                path="items"
                                width="80%"
                                .renderer="${(root: HTMLElement, column: GridColumn<any>, model: GridItemModel<any>) => {
                                    let buttonsLayout = root.firstElementChild;
                                    column.width = '80%'
                                    if (!buttonsLayout) {
                                        buttonsLayout = new FormLayout();
                                        (buttonsLayout as FormLayout).responsiveSteps = this.responsiveStepsForGrid;
                                        (buttonsLayout as FormLayout).theme = 'spacing-xs padding'
```
The exactly code line is:
`(buttonsLayout as FormLayout).theme = 'spacing-xs padding'`
The second error is very similar:

```
                        <vaadin-grid-column
                                path="${itemKey}"
                                .renderer="${
                                        (root: HTMLElement, column: GridColumn<any>, model: GridItemModel<any>) => {
                                            let editButton = root.firstElementChild;
                                            if (!editButton) {
                                                editButton = new VerticalLayout();
                                                (editButton as VerticalLayout).theme = 'spacing-xs padding'
```
Here the exactly code line is:
`(editButton as VerticalLayout).theme = 'spacing-xs padding'`

What's happened with FormLayout and VerticalLayout in new Vaadin version? How could I handle that errors?
Thanks.

### Versions:
    - Vaadin / Flow version:  24.3.11
    - Java version: 21
    - OS version:  Windows 10
    - Browser version (if applicable):
    - Application Server (if applicable):   Embedded Tomcat in Spring Boot v3.0.10
    - IDE (if applicable):   IntelliJ IDEA 2022.1.2
    - Development or production mode:  Development 
    - Vite version: 5.1.7

**Comment by mcollovati** [comment]
I think this could be related to a change, mentioned in the [upgrading guide](https://vaadin.com/docs/latest/upgrading#web-component-apis)

> The read-only theme property was removed. Use instead the theme attribute.

**Comment by Dinizzzka** [comment]
> I think this could be related to a change, mentioned in the [upgrading guide](https://vaadin.com/docs/latest/upgrading#web-component-apis)
> 
> > The read-only theme property was removed. Use instead the theme attribute.

Thanks a lot, it works! But now I got another error:

`[ERROR] frontend/components/network-editor-components/common/dialogs/LdCreationDialog.ts(10,26): error TS2307: Cannot find module 'Frontend/generated/theme' or its corresponding type declarations.`

There really no directory /theme in  /generated. 
The content of my  /generated dir below:
![image](https://github.com/vaadin/flow/assets/22413965/2a50d204-35b8-4c81-931d-69af81c12b70)
