### ISSUE TITLE
line-awesome.min.css causes 404 Not Found

### ISSUE THREAD

**Issue by Dinizzzka** [vaadin/flow#19466]
### Description

Hello.
I run my Vaadin application and found that all layouts displayed askew. I opened developer console and found just one error :
   `GET http://localhost:8080/line-awesome/dist/line-awesome/css/line-awesome.min.css net::ERR_ABORTED 404 (Not Found)`

Application frontend has been built without any errors and there line-awesome.min.css file in node_modules directory at the path
`node_modules /line-awesome/dist/line-awesome/css/line-awesome.min.css`
Look at the buttons on the start page, all of them are shifted:
![image](https://github.com/vaadin/web-components/assets/22413965/2e88fee6-6357-4243-a5f4-04c537efa869)

Why I got the error?

### Expected outcome

Good app launch. No errors. Correct buttons render.

### Minimal reproducible example

```
@SpringBootApplication
@Theme(value = "my-application)
@PWA(name = "My Application", shortName = "My Application", offlineResources = {})
@NpmPackage(value = "line-awesome", version = "1.3.0")

public class Application extends SpringBootServletInitializer implements AppShellConfigurator {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}
```

### Steps to reproduce

Just build and run application.

### Environment

- Vaadin Framework version 24.3.11
- Browser version: Google Chrome 124.0.6367.208
- Java version: 21
- Sptring boot version: 3.0.10

### Browsers

Chrome, Firefox

**Comment by mshabarov** [comment]
@Dinizzzka please let us know if [using an add-on](https://github.com/vaadin/flow/issues/19466#issuecomment-2134745530) helps you.

**Comment by Dinizzzka** [comment]
I added line-awesome addon to project's pom.xml and removed @npm annotation `@NpmPackage(value = "line-awesome", version = "1.3.0")`
and got error ` Unable to resolve @import "line-awesome/dist/line-awesome/css/line-awesome.min.css"`
And also Idea outlines line-awesome.min.css in styles.css:

![image](https://github.com/vaadin/flow/assets/22413965/01b3fcc6-4bb3-448d-9aca-5aff2b89bd08)

**Comment by Dinizzzka** [comment]
I removed `@import url('line-awesome/dist/line-awesome/css/line-awesome.min.css');` from `styles.css` file. The frontend has been built successfully and application running as well without errors but the render still incorrect:

![image](https://github.com/vaadin/flow/assets/22413965/36736fa9-dad0-415b-9206-63c7d1b7ab25)

**Comment by mcollovati** [comment]
Can you please share the code you are using to display the icons?

**Comment by Dinizzzka** [comment]
Here is code snippet with icon element:

![photo_2024-05-29_20-21-23](https://github.com/vaadin/flow/assets/22413965/3916591c-0f24-4614-a5b1-3e67fd08825e)

**Comment by mcollovati** [comment]
Ah, you are using icons on the frontend, not on the Java side.
If so, you should use the `NpmPackage` annotation and add the `importCss` key to your `theme.json` as pointed out by Knoobie.
Also, if you are not using an icon set, you should use the `icon-class` attribute on the Vaadin Icon element. (https://vaadin.com/docs/latest/components/icons#icon-fonts)
