### ISSUE TITLE
Labels leak memory

### ISSUE THREAD

**Issue by edler-san** [vaadin/flow#19486]
### Description

Adding and remove lots of Labels (both(!) Label and NativeLabel) causes memory leakage.

### Expected outcome

None to a very low increase in memory consumption.

### Minimal reproducible example

```java
package com.example.application.views.helloworld;

import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.html.NativeLabel;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.shared.Tooltip;
import com.vaadin.flow.router.Route;


@Route("/mem")
public class BrowserMemoryIssue extends VerticalLayout {
    int labelCounter = 0;

    int tooltipCounter = 0;

    int deleteCounter = 0;

    public BrowserMemoryIssue() {
        HorizontalLayout content;
        add(content = new HorizontalLayout());
        add(createTabButton(content));
        add(createDeleteButton(content));
    }

    private Button createDeleteButton(HorizontalLayout content) {
        Button deleteButton = new Button("Delete all elements");
        deleteButton.addClickListener(buttonClickEvent -> {
            content.getChildren().forEach(child -> {
                child.getElement().getAttributeNames().forEach(child.getElement()::removeAttribute);
                child.getElement().removeFromParent().removeFromTree();
            });
            deleteCounter++;
            labelCounter = 0;
            buttonClickEvent.getSource().getUI().ifPresent(UI::push);
        });
        return deleteButton;
    }

    private Button createTabButton(HorizontalLayout content) {
        String counterWaitText = "Waiting for action...";
        int labelCount = 100;
        NativeLabel counter = new NativeLabel(counterWaitText);
        add(counter);
        Button button = new Button("Create " + labelCount + " labels with tooltip");
        button.addClickListener(buttonClickEvent -> {
            for (int i = 0; i < labelCount; i++) {
                NativeLabel newLabel = new NativeLabel("Label: " + deleteCounter + "|" + labelCounter++);
                content.add(newLabel);
                counter.setText(i + "/" + labelCount);
                buttonClickEvent.getSource().getUI().ifPresent(UI::push);
            }
            counter.setText(counterWaitText);
        });
        return button;
    }
}
```

### Steps to reproduce

Add the above view to a new project. Start it. Navigate to `http://localhost:8080/mem` and open the browser's memory profiler.
Click the "Create 100 labels with tooltip" a few times and wait until it finishes, then click "Delete all elements". The UI returns to its near-empty state but the memory profiler shows several hundreds megabytes of used memory that can't be garbage collected.

### Environment

Vaadin version(s): 24.3.12, 24.4.0.beta5
OS: Win 11
Java: 17 LTS
Browser: Chrome (125.0.6422.113), Firefox (126.0.1)

### Browsers

Chrome, Firefox

**Comment by Legioth** [comment]
I don't see any signs of a memory leak in this case. Comparing heap dumps shows some background activity going on e.g. with Atmosphere's cleanup threads that causes a constant fluctuation in the memory usage but that's similar regardless of whether I interact with the application or just keep a browser tab open without doing anything. I'm not seeing any accumulation of objects from `com.vaadin` packages and certainly nothing in the range of hundreds of megabytes.

**Comment by edler-san** [comment]
The JVM is fine - the browser's memory is getting "filled" up.
![mem](https://github.com/vaadin/flow/assets/19165931/3dd8980e-18bc-4873-8848-92ffdde1df4d)

**Comment by Legioth** [comment]
The source of that increasing memory allocation is that all updates received from the server are logged in the the browser inspector's console. The memory is reclaimed if you open the Console tab and click the button to clear the log.

The detailed logging happens only when the application runs in development mode (which is the case in the screen recording based on the Vaadin logo that is shown in the lower right corner). It happens for any updates from the server, not just label components. The effect is more pronounced with the very aggressive pushing that used in the example code (removing the `UI:push` line or moving it outside the `for` loop significantly reduces the amount of logging).
