### ISSUE TITLE
Bun not being recognized on Windows

### ISSUE THREAD

**Issue by aless2003** [vaadin/flow#19496]
### Description of the bug

When I start my application with `vaadin.bun.enable = true` it fails with an error saying it can't find bun, despite it being installed on the system via the official method from bun.sh.
It seems to have something to do with it searching for bun.cmd on Windows, which as far as I can tell just doesn't exist for a normal installation of bun

### Expected behavior

Bun should be detected and used even on Windows

### Minimal reproducible example

See https://github.com/aless2003/BunBugDemo and use gradle bootRun to run the Application. After that navigate to localhost:8080 and the error is printed to the shell.

### Versions

Flow: 24.3.10
Vaadin: 24.3.12
Java: BellSoft 21.0.3
OS: amd64 Windows 11 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
Live reload: Java active
          (Spring Boot Devtools): Front end active

**Comment by Artur-** [comment]
When bun support was added, there was no windows version of bun so there might very well be something trivial that needs fixing

**Comment by oliveryasuna** [comment]
I would very much like to switch to Bun! We have some developers on Windows, so we will have to wait until this is supported.
