### ISSUE TITLE
Hilla app with @PWA annotation fails when running as native compiled image on macOS

### ISSUE THREAD

**Issue by rbrki07** [vaadin/flow#19497]
### Describe the bug

A Hilla app with `@PWA` annotation throws an exception when running as native compiled image:

```
java.lang.UnsatisfiedLinkError: No awt in java.library.path
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:136) ~[na:na]
```

### Expected-behavior

A Hilla app with `@PWA` annotation should not throw unexpected exceptions when running as native compiled image.

### Reproduction

Create a new Hilla project:
```
npx @hilla/cli@latest init --next hilla-native-pwa
```

Add `@PWA(name = "Hilla PWA", shortName = "PWA")` to `src/main/java/com/example/application/Application.java`.

Compile Hilla app to native image:
```
./mvnw clean package -Pproduction -Pnative native:compile
```

Run Hilla app as native compiled image:
```
./target/hilla-native-pwa
```

### System Info

Hilla: 24.4.0.beta5
Hilla CLI: 2.0.1
Java: 21.0.2 (OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1 - build 21.0.2+13-jvmci-23.1-b30)
OS: macOS Sonoma 14.4.1 (23E224)

**Comment by rbrki07** [comment]
There is one more thing I noticed, and I don't understand: Let's say I managed to create a native executable using Linux like described above. The next step would be to create a Docker image using this native executable. A simple Dockerfile could look like this:
```
FROM debian:bookworm-slim

WORKDIR /app

COPY target/hilla-native-pwa /app/hilla-native-pwa

CMD ["/app/hilla-native-pwa"]
```

Creating a Docker image from this Dockerfile works as expected:
```
docker build -t hilla-native-pwa-native-image .
```

Now, I'd like to start a new Docker container using this Docker image:
```
docker run -it --rm -p 8080:8080 hilla-native-pwa-native-image
``` 

From the console output, I can see that the app has been started. When I try to access the app in the browser, I'm getting the same `UnsatisfiedLinkError`s like described above.

Why is that? Why do I get this error messages? I'm running a native executable inside a Docker container. Why is this native executable complaining about the missing AWT in `java.library.path`? Do I have to create a Docker image that provides AWT, because the native executable depends on it, but does not contain it?

**Comment by mcollovati** [comment]
I am not completely sure, and I can't check right now, but probably the executable is dinamically linked, so the required libraries should be present at runtime (there should be some library file in the target directory).
IIRC, there should also be a native compilation option to make the executable statically linked, but I never tried it.

**Comment by rbrki07** [comment]
Yes, you are right 😄 There are a couple of library files (`.so`) in the target directory of the project, after I did `./mvnw clean package -Pproduction -Pnative native:compile`. If I change my Dockerfile to copy those library files... 
```
FROM debian:bookworm-slim

WORKDIR /app

COPY target/*.so /app/
COPY target/hilla-native-pwa /app/hilla-native-pwa

CMD ["/app/hilla-native-pwa"]
```
... everything works fine! The Docker image is created a desired and when I start a Docker container from the image I can access the Hilla PWA without errors 🙌

**Comment by Artur-** [comment]
Would the correct fix here be to produce the images at production build time and not have a dependency on awt?
