### ISSUE TITLE
The Polymer.GestureEventListeners mixin is not identified by the analyzer

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#1954]
After #1903, the analyzer is able to list the mixins inherited by the webcomponents, but the `Polymer.GestureEventListeners` is never in the list (take `vaadin-button` as example).

Quoting @pleku:

> Might be a bug in the Analyzer itself. Might be good to check if any of the Polymer elements are missing mixins after the second level, or if the fact that the mixin is declared as Polymer.x instead of Vaadin.x instead.
Maybe even ask the Polymer team about it (via chat), or create an issue on it in analyzer. I suppose a little investigation wouldn't hurt anyways, I briefly tried to find a ticket on the matter but no dice.

**Comment by denis-anisimov** [comment]
`Polymer.GestureEventListeners` presents for the latest generated component.
