### ISSUE TITLE
lumoImports not recognized in dev mode , when placed in a parent theme

### ISSUE THREAD

**Issue by SonReimer** [vaadin/flow#19567]
### Description of the bug

Defining lumoImports in the theme.json of a parent theme inside the same project,
the styles defined in java by the LumoUtility are not applied.
This only happens in dev mode.

### Expected behavior

It should not matter if the import is done in the project theme or it's parent.

### Minimal reproducible example

[lumoImports.zip](https://github.com/user-attachments/files/15803974/lumoImports.zip)

### Versions

- Vaadin / Flow version: At least 24.3.12 and 24.4.1
- Java version: 17
- OS version: Windows
- Browser version (if applicable): Firefox
- Application Server (if applicable): spring-boot(embedded tomact)
- IDE (if applicable): Eclispe 23-03

**Comment by mshabarov** [comment]
This [change](https://github.com/vaadin/flow/pull/19568/files) may help fix this issue, but I'd expect `lumoImports` to work even if they are added to the parent theme, documentation doesn't state any limitation about it.

**Comment by mshabarov** [comment]
The issue was triaged and currently added to the backlog priority queue for further investigation.
