### ISSUE TITLE
SideMenu is visible for one view, hidden for another one

### ISSUE THREAD

**Issue by abdullahtellioglu** [vaadin/flow#19611]
### Description of the bug

I downloaded a sample project from start with 2 views. On first view, side menu is visible, clickable, and normal. However, menu does not get rendered on the second view.

https://github.com/vaadin/flow/assets/100126447/8d681924-5a1d-409f-9bc4-c1350a6afe52

### Expected behavior

SideMenu should be visible in both views. 

### Minimal reproducible example

Downloaded example project from the start: 
[my-app (44).zip](https://github.com/user-attachments/files/15910446/my-app.44.zip)

### Versions

- Vaadin / Flow version: 24.5.0.alpha2
- Java version: 21
- OS version: OSx
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by caalador** [comment]
This would seem to be the same issue that was fixed in https://github.com/vaadin/hilla/pull/2572 when you have an empty `@layout.tsx` the route root doesn't match correctly. 
2572 is not yet merged into main branch, but should be soon.

**Comment by mshabarov** [comment]
Cherry picked to `main` in https://github.com/vaadin/hilla/pull/2585. Will be released in next Hilla and Platform 24.5 pre-release.
