### ISSUE TITLE
Add "auto" mode to hilla.endpoint.hot-reload.enabled config parameter

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow#19652]
### Describe your motivation

If there is a Hilla view in the project the endpoint should be "hot-reload" by default. For a Flow project, it should be disabled by default.

### Describe the solution you'd like

Similar to the `vaadin.frontend.hotdeploy`, there should be a `auto` configuration as default. Then a user can force it to true or false if needed.

### Additional context

See this ticket: https://github.com/vaadin/flow/issues/18578

**Comment by cromoteca** [comment]
The hotswap handling has changed in 24.5 and `hilla.endpoint.hot-reload.enabled` is no longer there.
