### ISSUE TITLE
Flow Production Build crash in Browser wile opening the app Cannot read properties of undefined (reading 'connectClient')

### ISSUE THREAD

**Issue by MalteSchwenker** [vaadin/flow#19705]
### Description of the bug

When i open my app in production mode, the flow initialization crash with an exception:

` Cannot read properties of undefined (reading 'connectClient')
    at indexhtml-DgTPv8kH.js:196:3455
    at new Promise (<anonymous>)
    at Vo.flowNavigate (indexhtml-DgTPv8kH.js:196:3171)
    at container.onBeforeEnter (indexhtml-DgTPv8kH.js:196:2687)
    at Et (indexhtml-DgTPv8kH.js:198:13995)
    at indexhtml-DgTPv8kH.js:198:14086
    at indexhtml-DgTPv8kH.js:198:20014`

When in run my application in development the error not happens and the app runs without problems.

I clead and rebuild my application several times. Delete the target folder, the generated folder, the node_modules etc.

### Expected behavior

The application should be shown

### Minimal reproducible example

not possible, another vaadin app with this version has no problems.

### Versions

- Vaadin / Flow version: 24.4.6
- Java version: 17.x or 21.x
- OS version: Ubuntu 22.04 LTS
- Browser version (if applicable): Firefox 127.0.2 or Vivaldi 6.8.3381.46
- Application Server: Spring Boot

**Comment by Artur-** [comment]
Sounds like some version conflict in the project because the call to ”connectClient” was removed in #18570

**Comment by MalteSchwenker** [comment]
Hy Artur thanks for your quick replay, i could solve this. The tip with the version conflict was right. Thanks
