### ISSUE TITLE
Element positioning via style doesn't work after position has been edited via JS previously

### ISSUE THREAD

**Issue by F-Kamp** [vaadin/flow#19702]
### Description

In my application I have a simple div element that is moved via Javascript.  After the div's position has been changed, a custom event is fired to which the server listens to. Then some server logic is executed that might move the div to a different position using the style API. This doesn't work. The div stays at the position that has been set via JS.

I understand that changing an element's position via JS doesn't update Vaadin's style property cache. I didn't find any mechanism to notify the cache that a property has been changed via JS and to reload it.

However, even if the cached value is stale, from the element's point of view it changed to a new value and should execute the update. 

In the below example I've simplified my use-case somewhat by omitting the custom event that is the intermediary step between moving the element via JS and via style API. If necessary I can create a more complex example that is closer to my actual use-case, but the simple example already shows that it's a problem if an element is moved via JS.

### Expected outcome

Moving an element via the style API should work even if the position has been changed previously via Javascript.

### Minimal reproducible example

```java

@Route("positionBugDemo")
public class PositionBugDemo extends VerticalLayout {


    @Serial
    private static final long serialVersionUID = 6767738777541856721L;

    public PositionBugDemo() {
        setSizeFull();
        getStyle().set("background", "gray");

        var div = new Div();
        div.setHeight("100px");
        div.setWidth("100px");
        div.getStyle().set("background", "blue");
        div.getStyle().setPosition(Style.Position.ABSOLUTE);
        div.getStyle().setTop("100px");
        div.getStyle().setLeft("0px");

        print(String.format("Initial position : left=%s, top = %s%n", div.getStyle().get("left"), div.getStyle().get("top")));

        var moveDivButton = new Button("Move div only via style (twice)", (event -> {

            print(String.format("Position before style movement: left=%s, top = %s%n", div.getStyle().get("left"), div.getStyle().get("top")));
            div.getStyle().setTop("200px");
            div.getStyle().setLeft("300px");
            print(String.format("Position after style movement: left=%s, top = %s%n", div.getStyle().get("left"), div.getStyle().get("top")));

            div.getStyle().setLeft("100px");
            div.getStyle().setTop("500px");

            print(String.format("Position after 2nd style movement: left=%s, top = %s%n", div.getStyle().get("left"), div.getStyle().get("top")));

            div.getElement().executeJs("return { left : this.style.left, top : this.style.top };")
                    .then(JsonObject.class, obj -> print(String.format("Actual final position: left=%s, top = %s%n", obj.getString("left"), obj.getString("top"))));
        }));

        var moveDivJsButton = new Button("Move div via JS", (event -> {
            print(String.format("Position before JS movement: left=%s, top = %s%n", div.getStyle().get("left"), div.getStyle().get("top")));
            div.getElement().executeJs("this.style.left='200px';this.style.top='200px'; return 0;").then(Integer.class, dummy -> {

                print(String.format("Position after JS movement: left=%s, top = %s%n", div.getStyle().get("left"), div.getStyle().get("top")));

                // attempt to "fix" the cached position
                div.getStyle().setLeft("200px");
                div.getStyle().setTop("200px");

                print(String.format("Position after updating the cached position: left=%s, top = %s%n", div.getStyle().get("left"), div.getStyle().get("top")));

                // actually move the div to a new position
                div.getStyle().setLeft("400px");
                div.getStyle().setTop("800px");

                print(String.format("Position after style movement: left=%s, top = %s%n", div.getStyle().get("left"), div.getStyle().get("top")));

                div.getElement().executeJs("return { left : this.style.left, top : this.style.top };")
                        .then(JsonObject.class, obj -> print(String.format("Actual final position: left=%s, top = %s%n", obj.getString("left"), obj.getString("top"))));
            });
        }));

        this.add(new HorizontalLayout(moveDivButton, moveDivJsButton), div);
    }

    private void print(String msg) {
        System.out.println(msg);
        Notification.show(msg, 10000, Notification.Position.BOTTOM_START);
    }
}
```

### Steps to reproduce

1) Add the snippet
2) Click on the button "Move div only via style (twice)" as often as you want: Div's final position is correct

3) Click on the button "Move div via JS" - on the first click: Div's final position is correct
4) Click on the button "Move div via JS" again: Div's final position is what has been set via JS, the style API call is ignored

### Environment

Vaadin version(s): 24.4.6
OS: Windows 11

### Browsers

Chrome

**Comment by F-Kamp** [comment]
Yes, sorry about that, I meant to post this to https://github.com/vaadin/flow-components

**Comment by mcollovati** [comment]
It is expected that properties updated on the client side are not automatically synchornized with the server.
You can synchronize a property when a DOM event is fired using `Element.addPropertyChangeListener(String propertyName, String domEventName, PropertyChangeListener listener)`, but the property will be updated on the server only if the client side detects a change.
So, it won't work well with `style`, since you are not going to modify the `style` itself, but one of its property, and this change is not detected.

**Comment by F-Kamp** [comment]
I understand that it's not expected that the server updates its state when the client changes properties via JS. 
What surprises me is that 
```java
// attempt to "fix" the cached position
div.getStyle().setLeft("200px");
div.getStyle().setTop("200px");
```
doesn't update the server's state - or at least not in a way, that allows the server to detect and execute subsequent changes **from itself**:
```java
// actually move the div to a new position
div.getStyle().setLeft("400px");
div.getStyle().setTop("800px");
```

**Comment by mcollovati** [comment]
You are updating the values in the same request, so when Flow computes the changes to send to the client, it does not find any difference with the initial state.

```
              // attempt to "fix" the cached position
                div.getStyle().setLeft("200px");
                div.getStyle().setTop("200px");

                print(String.format("Position after updating the cached position: left=%s, top = %s%n", div.getStyle().get("left"), div.getStyle().get("top")));

                // actually move the div to a new position
                div.getStyle().setLeft("400px");
                div.getStyle().setTop("800px");
```

**Comment by Legioth** [comment]
The basic "rule" is that if you step down to a lower abstraction level and override e.g. a property through JS, then you can no longer reliably use the high-level mechanisms for that property. Either the property is "owned" by JS or by Flow's high-level mechanisms. A property can only have one owner and there's no reliable way of reseting the ownership once it has been moved to the lower abstraction level.
