### ISSUE TITLE
WebComponentExporter: @CSSImport styles are registered in the head

### ISSUE THREAD

**Issue by roelnoten** [vaadin/flow#19700]
### Description of the bug

When exposing a part of a vaadin application as a webcomponent via the WebComponentExporter, then all styles loaded via the java @CSSImport annotation (without themefor attribute) are registered in the head of the parent document instead of within the bounds of the webcomponent.
Not only does this leak styles in to the parent document and can thus alter it, it also leads to the absence of those styles in the webcomponent.

The issue can be circumvented by not using @CSSImport and instead importing the css files through @import statements in the themes styles.css file.
But, when using addons (form the vaadin addon directory) those typically also reference their styles via @CSSImport and thus their styling is missing when used in a WebComponentExporter.

### Expected behavior

Styles loaded via @CSSImport should be registered within the webcomponent when running as a WebComponentExport webcomponent; and should not be registered in the head of the parent document.

### Minimal reproducible example

Try for instance adding the addon `<dependency><groupId>org.vaadin.tatu</groupId><artifactId>twincolselect</artifactId<version>2.5.2</version></dependency>` to a WebComponentExporter.
This addon does a @CSSImport at https://github.com/TatuLund/TwinColSelect/blob/ec21083c1502ec8f150a603185be1f6151e45d9a/src/main/java/org/vaadin/tatu/TwinColSelect.java#L73 of https://github.com/TatuLund/TwinColSelect/blob/master/frontend/themes/mytheme/styles.css.

You'll notice these styles of that styles.css are registered in the head of the document and not active within the WebComponentExporter webcomponent.

### Versions

- Vaadin / Flow version: 23.3.34
- Java version: any
- OS version: any
- Browser version (if applicable): any
- Application Server (if applicable): any
- IDE (if applicable): any

**Comment by mcollovati** [comment]
The issue was triaged and currently added to the backlog priority queue for further investigation

**Comment by mcollovati** [comment]
The issue was assigned to a developer and is currently being investigated
