### ISSUE TITLE
Navigation does not work for empty route in hybrid application

### ISSUE THREAD

**Issue by abdullahtellioglu** [vaadin/flow#19712]
### Description of the bug

I downloaded a project form start.vaadin.com. I added 2 views one is hilla empty view, other one is flow empty view. When I open the application, app says that could not navigate to ''
```
Could not navigate to ''
Available routes:
[/empty](http://localhost:8181/empty)
This detailed message is only shown when running in development mode.
```

Flow view:
```java
@Route(value = "")
@RouteAlias(value = "")
public class EmptyView extends VerticalLayout {
```
Hilla view:
```
src/main/frontend/views/empty.tsx 
export const config: ViewConfig = { menu: { order: 1, icon: 'line-awesome/svg/file.svg' }, title: 'Empty2' };
```

### Expected behavior

Navigation should handle both routes.

### Minimal reproducible example

[my-app.zip](https://github.com/user-attachments/files/16336344/my-app.zip)

### Versions

Hilla: 24.5.0.alpha4
Flow: 24.5.0.alpha6
Vaadin: 24.5.0.alpha4
Copilot: 24.5.0.alpha4
Copilot IDE Plugin: 1.0.9-intellij
Java: Oracle Corporation 22.0.1
Java Hotswap: false
Frontend Hotswap: Enabled, using Vite
OS: aarch64 Mac OS X 14.5
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by mcollovati** [comment]
I cannot reproduce the issue. I downloaded the provided example and started the application in the IDE.
A browser tab is opened at http://localhost:8080/, and I can see the Flow view

**Comment by abdullahtellioglu** [comment]
It happened when I downloaded the project and opened it, but it did not occur afterward. There is some randomness that happens at the first initialization. Maybe files are not generated properly due to some race condition. I cannot say a concrete way to reproduce it so closing the issue.
