### ISSUE TITLE
How to disable Vaadin?

### ISSUE THREAD

**Issue by sw-tracker** [vaadin/flow#19723]
Hi there,

We are currently using Vaadin in one of our projects, but mostly in our mocks. We have the situation in which our mocks run in normal mode (starting up a spring boot application) and in CI mode (restassured - where we merge it with our main spring boot application `@SpringBootTest(classes = { BackendApplication.class, MockApplication.class }, webEnvironment = DEFINED_PORT)`).

We find that in CI mode, the startup is too slow (`Initializing AtmosphereFramework` is really slow) and the MVC routing conflicts with our other routes. We would like to completely turn Vaadin off/disable it when the `ci` spring boot profile is active. How can we do this?

Thanks!

**Comment by mcollovati** [comment]
Did you try to disable Vaadin autoconfiguration?

```
@EnableAutoConfiguration(exclude=com.vaadin.flow.spring.SpringBootAutoConfiguration.class)
```

Or in the `ci` profile application.properites
```
spring.autoconfigure.exclude=com.vaadin.flow.spring.SpringBootAutoConfiguration
```

**Comment by sw-tracker** [comment]
I considered this, but I was hoping for something easier. With that approach I would have to exclude all of my code that depends on Vaadin imports as well.

**Comment by mcollovati** [comment]
Actually, I do not understand your requirements. Excluding autoconfiguration should prevent Vaadin to startup, but it should not impact compilation.
What do you mean by "I would have to exclude all of my code that depends on Vaadin imports as well"?

If you want to turn off Vaadin, I assume you simply intend to prevent Vaadin servlet to be initialized and serve requests.

**Comment by sw-tracker** [comment]
Ok no worries, I will try that. Thanks!
