### ISSUE TITLE
URL is not changed when using `forwardTo` to the view just navigated from

### ISSUE THREAD

**Issue by MatthewVaadin** [vaadin/flow#19794]
### Description of the bug

Forwarding to the same view that the user has just navigated from doesn't change the URL.
For example, suppose we have two views, `FirstView.java` (path `/first`) and `SecondView.java` (path `/second`). The second view calls `forwardTo(FirstView.class)` in `beforeEnter`.  If the user is currently on `/first` and they navigate to `/second`, they are correctly forwarded back to the first view, but the URL is still shown as `/second`.

### Expected behavior

The URL should be shown as the view that the user has been forwarded to (`/first` in the case above).

### Minimal reproducible example

See https://github.com/MatthewVaadin/forward-bug

- Navigate to the "First" view
- Navigate to the "Second" view
- Note that the view is "First", but the URL path is `/second`

### Versions

- Vaadin / Flow version: 24.4.8
- Java version: 17
- OS version: Windows 11
- Browser version (if applicable): Chrome 127.0.6533.120

**Comment by tepi** [comment]
Confirmed to fail on 24.5-SNAPSHOT with both vaadin router and react router.
