### ISSUE TITLE
Vaadin 24.4.9 RouterLink in Drawer

### ISSUE THREAD

**Issue by alexanoid** [vaadin/flow#19823]
### Description of the bug

Previous similar bug https://github.com/vaadin/flow/issues/18736

With Vaadin 24.4.9, when I click on the RouterLink which points to the page where I currently am, the Drawer on the mobile view does not close, unlike in version 24.4.0.beta5 :

![drawer](https://github.com/vaadin/flow/assets/110009335/77d5b652-aae3-43ee-918b-9de74b5a5779)

### Expected behavior

The drawer on the mobile view should be closed after the click, even if it is pointed to the page where the user currently is

### Minimal reproducible example

n/a

### Versions

- Vaadin / Flow version:  24.4.9
- Java version: 17

**Comment by mshabarov** [comment]
This is probably a regression after some other fix, as https://github.com/vaadin/flow/issues/18736 aimed to fix the same problem.

**Comment by tepi** [comment]
Confirmed this is a regression on latest versions and on 24.5 branch as well. Investigating.

**Comment by alexanoid** [comment]
Hi @tepi I just upgraded to Vaadin 24.4.9 and the issue is still present. Could you please check what the cause might be?
