### ISSUE TITLE
MenuRegistry should have method to get List of ordered menu items

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#19905]
MenuRegistry should have a method to get the available menu items as a list
that is ordered instead of getting only the current `Map<String, AvailableViewInfo>`.

This would mean that the list would be `List<AvaiableViewInfo>` and that the route
in the AvailableViewInfo should be fixed so it is the correct route and not only the view route for client routes.

Ordering would be done according to the AvailableViewInfo.Menu.order and/or alphabetically using `Collator.getInstance()` to get the same result as Hilla menu ordering

**Comment by Legioth** [comment]
> Ordering would be done according to the AvailableViewInfo.Menu.order or alphabetically?

Same ordering as the [corresponding Hilla API](https://github.com/vaadin/hilla/blob/2eb52a85dbb6d4e67660455cca8eb04fe87fce3f/packages/ts/file-router/src/runtime/createMenuItems.ts#L30-L33). First order by the `order` property and then resolve ties by the alphabetic order of the route paths.
