### ISSUE TITLE
Cannot load resources from jar files in classpath Jetty 12.0.13 Vaadin 24.4.11

### ISSUE THREAD

**Issue by cliviu** [vaadin/flow#19960]
### Description of the bug / feature
I want to start an embedded Jetty Server. I have some Vaadin resources packed in a jar file.
When starting the Jetty/Vaadin Application with the resources in "classes" folder, it works, otherwise 
when I pack the resources in jar library they cannot be found.
### Minimal reproducible example
  - 
### Expected behavior
  resources are loaded from the jar files found in classpath
### Actual behavior
  resources are not loaded from the jar files found in classpath
### Versions:
    - Vaadin / Flow version: 24.4.11
    - Java version: 17
    - OS version: Open Suse 15.5
    - Browser version (if applicable): Chrome
    - Application Server (if applicable):  Jetty 12.0.13
    - IDE (if applicable): Intelij

**Comment by Artur-** [comment]
Please add the minimal reproducible example so we don't have to guess what is wrong

**Comment by mcollovati** [comment]
You may want to take a look at @mvysny's VaadinBoot project to see if your embedded Jetty configuration is missing something
https://github.com/mvysny/vaadin-boot/blob/30a2f14180b46a5d097a4dec675c91f446b878f5/vaadin-boot/src/main/java/com/github/mvysny/vaadinboot/common/JettyWebServer.java#L120

**Comment by cliviu** [comment]
> You may want to take a look at @mvysny's VaadinBoot project to see if your embedded Jetty configuration is missing something https://github.com/mvysny/vaadin-boot/blob/30a2f14180b46a5d097a4dec675c91f446b878f5/vaadin-boot/src/main/java/com/github/mvysny/vaadinboot/common/JettyWebServer.java#L120

Thanks, it helped. I will close the issue.
