### ISSUE TITLE
Generate MenuItems api for application menu generation

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#20063]
### Describe your motivation

There exists the MenuRegistry that can be used for collecting menu item and route data, but the implementation is aimed for internal consumption and is not as user friendly as it could be.

### Describe the solution you'd like

There should be a `MenuConfiguration` class that returns `MenuOptions` objects as an ordered collection for use within applications.

### Describe alternatives you've considered

Update and remake the current MenuRegistry api.

**Comment by mshabarov** [comment]
**Acceptance Criteria (draft)**
- [ ] `MenuRegistry` is moved under `com.vaadin.flow.internal.menu` and/or documented as "for internal use only".
- [ ] If moved to internal package, `Hilla` and `Start` are modified accordingly.
- [ ] `MenuConfiguration` new class is now public class that has needed methods for dynamic menus, similar to `RouteConfiguration` class that is public API.
- [ ] `MenuConfiguration` has methods `getAvailableMenuOptions` (or similar name) + `getAvailableClientMenuOptions` that returns new `MenuOptions` class (or as an alternative, the existing `MenuData` class? )
- [ ]  `MenuOptions` can give a collection or stream of `MenuOption`
- [ ] `MenuOption` class has path, title, order, exclude and icon fields (what else is needed?)

**Comment by mshabarov** [comment]
Should include fixes for:
- [ ] https://github.com/vaadin/flow/issues/20114
- [ ] https://github.com/vaadin/flow/issues/20109

**Comment by knoobie** [comment]
> MenuOption class has path, title, order, exclude and icon fields (what else is needed?)

Should this include a reference to the class from which the menu comes from? Custom Menu Annotations are probably a bit hard to support.. but this would at least allow to gather all other annotation / informations from the Menu's class.

**Comment by mshabarov** [comment]
Sounds like a useful data to have there, agreed.
