### ISSUE TITLE
Hilla view is not rendered inside Flow @Layout

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#20072]
### Description of the bug

```java
@Layout
public class MainLayout extends AppLayout {
```

```java
@PageTitle("Hello World")
@Route("")
@Menu(order = 0, icon = "line-awesome/svg/globe-solid.svg")
public class HelloWorldView extends HorizontalLayout {
```

```ts
export const config: ViewConfig = {
  menu: { order: 1, icon: 'line-awesome/svg/globe-solid.svg' },
  title: 'Hello World2',
};

export default function HelloWorld2View() {
```

The Flow view is rendered inside `MainLayout` but the Hilla view is rendered without any layout

### Expected behavior

Both views use `@Layout` 

### Minimal reproducible example

https://github.com/Artur-/flow-layout-hilla-view

### Versions

Hilla: 24.5.0.beta3
Flow: 24.5.0.beta2
Vaadin: 24.5.0.beta3
Copilot: 24.5.0.beta2
Frontend Hotswap: Enabled, using Vite
OS: aarch64 Mac OS X 15.0
Java: Oracle Corporation 21
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Java Hotswap: false
IDE Plugin: false

**Comment by caalador** [comment]
This is fixed in https://github.com/vaadin/hilla/pull/2745
