### ISSUE TITLE
Title in the @Menu annotation has no impact on collectMenuItemsList

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#20107]
### Description of the bug

Seems like `item.title()` from `MenuRegistry.collectMenuItemsList()` for a Flow  view always uses the view's `@PageTitle` value even if the menu title is overridden in the `@Menu` annotation.

### Expected behavior

Expected that the menu uses the title from `@Menu` if one defined and otherwise falls back to the `@PageTitle` value.

### Minimal reproducible example

Any 24.5 prerelase starter from start.vaadin.com

### Versions

- Vaadin / Flow version: 24.5.0.beta4

**Comment by Legioth** [comment]
The same is also the case for a Hilla view with `export const config: ViewConfig = { menu: {title: "Something"} }` which is also ignored.

**Comment by caalador** [comment]
For hilla the structure gives a clearer indication that it is the Menu Title not Page Title. e.g. title for the menu item.

Should the menu title be used as page title and how do all the page title choices override each other?

**Comment by Legioth** [comment]
Seems like I looked at `AvailableViewInfo.title` which is different from `MenuData.title`. Seems like `MenuData.title` is populated as expected for Flow views but not for Hilla views where sometimes the whole object is missing (https://github.com/vaadin/flow/issues/20109) and sometimes it has `null` in `MenuData.title` rather than falling back to the route title like it seems to do for Flow views.

**Comment by Legioth** [comment]
So with Flow views, I would expect that `viewInfo.title` uses `@PageTitle` if defined and otherwise falls back to a title derived from the class name. `viewInfo.menu.title` should use the value from `@Title` if defined and otherwise fall back to `viewInfo.title`.

With Hilla views, I would expect that `viewInfo.title` uses the `title` property from the `ViewConfig` object if defined and otherwise falls back to a title derived from the function name. `viewInfo.menu.title` uses the title from `ViewConfig.menu` if defined and otherwise falls back to `viewInfo.title`.

I assume this would be consistent with how both Flow and Hilla views behave in a Hilla layout.

**Comment by mshabarov** [comment]
@Legioth your last comment probably has a typo, should it be 
```
`viewInfo.menu.title` should use the value from @Menu if defined
```
instead of 
```
`viewInfo.menu.title` should use the value from `@Title` if defined
```
?

**Comment by mshabarov** [comment]
Just tested with the latest 24.5-SNAPSHOT in both dev and prod mode and the requirements proposed [here](https://github.com/vaadin/flow/issues/20107#issuecomment-2388012827) are well covered with the new menu API:
```
        List<MenuEntry> menuEntries = MenuConfiguration.getMenuEntries();
        menuEntries.forEach(entry -> {
            if (entry.icon() != null) {
                nav.addItem(new SideNavItem(entry.title(), entry.path(), new SvgIcon(entry.icon())));
            } else {
                nav.addItem(new SideNavItem(entry.title(), entry.path()));
            }
        });
```

The only observation that I got is when I set the `ViewConfig.title` as
```
 export const config: ViewConfig = {
  title: 'Page Title Hilla'
};
```
it doesn't change the browser tab name. Instead I got `My App` tab name from index html - `<title>My App</title>`. If I remove it from index html, I get `localhost:8080` as tab name.

I'd rather create a new issue in Hilla for this observation.

**Comment by mshabarov** [comment]
Well, the page title follows what is set in `ViewConfig.title`, when a Hilla main layout is used. For Flow main layout this doesn't work. Should be fixed on a Flow side.
