### ISSUE TITLE
AvailableViewInfo.menu is null if a Hilla route has no menu in its view config

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#20109]
### Description of the bug

`AvailableViewInfo.menu` returns `null` for a Hilla view without any `menu` in its `ViewConfig`. While this is technically correct, it does also seem redundant since it forced the menu building logic to have an additional `null` check that adds no value. Hilla views are included by default and should have `menu: {exclude: true}` to be excluded.

### Expected behavior

Expected that
```
export const config: ViewConfig = {
    menu: {}
}
```
and
```
export const config: ViewConfig = {
}
```
lead to the same data in `AvailableViewInfo.menu`

### Minimal reproducible example

24.5 pre starter from start.vaadin.com

### Versions

- Vaadin / Flow version: 24.5.0.beta4

**Comment by caalador** [comment]
This should be taken into account in #20063 when the outside facing api is added.

**Comment by tltv** [comment]
`MenuRegistry` can generate default `MenuData` with excluded=false for hilla views that don't have menu data. 

But then what to use as a default menu title? Should it be blank `""`, `null`, or view's title. That's all options I can think of we have there.

**Comment by tltv** [comment]
It should probably be either blank or null as `MenuData`, if given, is supposed to override view title.

**Comment by tltv** [comment]
OK, so for consistent behavior with Hilla's automenu it should use view's title (AvailableViewInfo.title) as a default value for MenuData.title.
