### ISSUE TITLE
Hotswap of translations does not work using Hotswap Agent plugin

### ISSUE THREAD

**Issue by sveinnetnordic** [vaadin/flow#20118]
### Description of the bug

Using hotswapagent 2.0.1 with watchResources=src/main/resources/vaadin-i18n. Seems to work, but UI/Vaadin does not load/refresh translations. Need a full restart.

HOTSWAP AGENT: 11:10:14.384 INFO (org.hotswap.agent.plugin.spring.reload.SpringBeanReload) - try to add changed property 'file:/D:/vaadin/src/main/resources/vaadin-i18n/translations_no.properties' into org.springframework.beans.factory.support.DefaultListableBeanFactory@17273273

### Expected behavior

Should show new translation text on hotswap

### Minimal reproducible example

H1 heading1 = new H1(translate("h1.element-1.text"));

h1.element-1.text=Hello

### Versions

Hilla: 24.5.0.beta4
Flow: 24.5.0.beta3
Vaadin: 24.5.0.beta4
Copilot: 24.5.0.beta3
Frontend Hotswap: Enabled, using Vite
OS: amd64 Windows 11 10.0
Java: JetBrains s.r.o. 21.0.3
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Java Hotswap: false
IDE Plugin: ☑ 1.9.9

https://github.com/HotswapProjects/HotswapAgent/releases/tag/RELEASE-2.0.1

**Comment by Artur-** [comment]
`ResourceBundle.getBundle` used by `DefaultI18NProvider` at least caches the bundle lookup and returns the old version. This caching is probably unnecessary in development mode

**Comment by sveinnetnordic** [comment]
FYI: Tried to patch 24.5.0.beta5 with TranslationFileRequestHandler. Did not work for Flow. Maybe patching will not work...
`HOTSWAP AGENT: 08:24:17.649 INFO (org.hotswap.agent.plugin.spring.reload.SpringBeanReload) - try to add changed property 'file:/D:/NNDev/studd2/studd-vaadin/target/classes/vaadin-i18n/translations_no.properties' into org.springframework.beans.factory.support.DefaultListableBeanFactory@67efd2c2`

**Comment by Artur-** [comment]
The latest version of #20142 is supposed to fix it for Flow

**Comment by mcollovati** [comment]
Side note: `TranslationFileRequestHandler` requires a  `DefaultI18NProvider`, that in turn does not rely on Spring, but directly uses `ResourceBundle`, so the reported log might not indicate that there's something wrong in Flow.
