### ISSUE TITLE
Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-lumo-styles" has already been used with this registry

### ISSUE THREAD

**Issue by Mehafooz** [vaadin/flow#20186]
### Description of the bug

Description
In my angular app im trying to use vaadin date picker component for that in my package json
{
@vaadin/date-picker:24.4.8
some-other-library:x.x.x
}

so here my some other library aslo has some vaadin dependencies and vaadin date picker also have the lumo style dependecies so bcz of the two different version of lumo styles my app is breaking with the below error.

Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-lumo-styles" has already been used with this registry

### Expected behavior

how to resolve it

### Minimal reproducible example

if we some other old vaadin components library vaadin-date-picker:4.3.0 and if im using newer version also in angular app  then im getting the above error

### Versions

- Vaadin / Flow version:v24
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by Artur-** [comment]
See https://github.com/vaadin/web-components/issues/7956
