### ISSUE TITLE
Automatically add the babelHelpers.js into the initial page if the browser doesn't support ES6

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#2020]
This can be done exactly like we do for the webcomponents loader polyfill: we scan the resources for the file, and if found, we just include it. When not found, we raise an warning in the console instructing the user to add the dependency at the `bower.json` file.

We also need to document that at the ES5 compilation tutorial.

**Comment by Artur-** [comment]
#2907 ?

**Comment by SomeoneToIgnore** [comment]
Indeed.
