### ISSUE TITLE
PiT 24.5: when no view found, links to generate a new view does not work

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#20216]
### Description of the bug

The 'no views found' links for creating flow or hilla views do not work
![Screenshot 2024-10-10 at 11 45 45](https://github.com/user-attachments/assets/6e555617-0c5a-49d1-ba51-8f9dc3a77f39)

### Expected behavior

links work

### Minimal reproducible example

Create a new project in e.g. https://start.spring.io/ by selecting hilla and developer tools

### Versions

- Vaadin / Flow version:  24.5.0.rc1

**Comment by manolo** [comment]
Seems a copilot issue.

This is the project I used for testing:

[initializer-vaadin-maven.zip](https://github.com/user-attachments/files/17326271/initializer-vaadin-maven.zip)

**Comment by mshabarov** [comment]
@manolo could you please transfer it to Copilot repo then ?

**Comment by ZheSun88** [comment]
this should be fixed by https://github.com/vaadin/copilot-internal/pull/3355 this already.
