### ISSUE TITLE
Flow view with access control is not visible in a Hilla menu

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#20257]
### Description of the bug

The "Flow admin" view is not shown in the main menu after logging in with the 24.5 branch of https://github.com/vaadin/flow-hilla-hybrid-example but it is shown in the default branch which uses Vaadin 24.4. Also tested updating from 24.5.0.rc1 to 24.5.0.rc2 but that had no impact.

### Expected behavior

Expected that the menu is shown

### Minimal reproducible example

* Check out https://github.com/vaadin/flow-hilla-hybrid-example/tree/v24.5
* Run with `mvn`
* Log in
* Observe that there's no "Flow admin" entry in the menu

### Versions

- Vaadin / Flow version: Vaadin 24.5.0.rc2

**Comment by tltv** [comment]
This looks same as https://github.com/vaadin/hilla/issues/2825 which has fix already.

**Comment by caalador** [comment]
This should have a fix that is not out yet. So in rc2 the hasMainMenu returns false.

Workaround is to manually set the `PopulateClientMenu` to `ALWAYS` with a `MenuAccessControl` bean. 
```
    @Bean
    public MenuAccessControl customMenuAccessControl() {
        var menuAccessControl = new DefaultMenuAccessControl();
        menuAccessControl.setPopulateClientSideMenu(
                MenuAccessControl.PopulateClientMenu.ALWAYS);
        return menuAccessControl;
    }
```

**Comment by mshabarov** [comment]
Just tested with 24.5.0 and this doesn't appear anymore.
