### ISSUE TITLE
vaadin.frontend.hotdeploy=false not possible if  Hilla views is used

### ISSUE THREAD

**Issue by sveinnetnordic** [vaadin/flow#20290]
### Description of the bug

Vite will always start if some .tsx in the magic views folder. When not developing React Vite will slow down the Flow development

### Expected behavior

https://vaadin.com/docs/latest/upgrading#frontend-bundles-hot-deploy-modes

" If it detects Hilla views in a project, it uses development server — **unless** you set the configuration parameter, vaadin.frontend.hotdeploy=false"

### Minimal reproducible example

NA

### Versions

Hilla: 24.5.0
Flow: 24.5.0
Vaadin: 24.5.0

**Comment by mshabarov** [comment]
As a potential workaround before we fix it, one can move React views aways from frontend/views folder, then Vaadin won't force the dev server.
But ofc you'll loose the File-based router feature then and have to configure the routes manually.

**Comment by tepi** [comment]
Reopening this since dev bundle is not working properly on 24.5, Hilla views are not properly detected. Needs investigation and fix.

**Comment by tepi** [comment]
https://github.com/vaadin/flow/pull/20324 fixes finding the Hilla views in dev-bundle mode

**Comment by sveinnetnordic** [comment]
Works for me :-)
