### ISSUE TITLE
Production build breaks future development

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#20294]
### Description of the bug

After building a production build of my 24.5 application, development mode is broken. 

Initially, I was missing the dev mode gizmo and no changes were reloaded

After running `mvn clean`, I got an empty screen with the following error in the browser console 

```
copilot-Cn85U7pa.js:5073 Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at copilot-Cn85U7pa.js:5073:20
```

Finally, after deleting `src/main/bundles/prod.bundle`, did the app start working again as expected. 

### Expected behavior

Creating a production build should not break development mode. I should continue to be able to run `Application.java` and have access to the dev mode gizmo and its features. I should not need to run `mvn clean` or delete any files to get my app back to a working state.

### Minimal reproducible example

App from start.vaadin.com with Flow and Hilla views. 

### Versions

- Vaadin / Flow version: 24.5
- Java version: 21

**Comment by marcushellberg** [comment]
For me, it was enough to run one `mvn -Pproduction package` to get this to happen.

**Comment by caalador** [comment]
For some reason running `mvn package -Pproduction` but instead `mvn install -Pproduction` I get left with `flow-build-info.json` in `target/classes` which says `"productionMode": true,` and as that's not cleaned when starting in development mode it is found and the state is set to production for the running application.

**Comment by caalador** [comment]
Seems the main issue is somewhere in vaadin-spring init (running Application from idea for example), as running the application in dev mode using maven we do get the development mode correctly.

**Comment by marcushellberg** [comment]
Yes, I always run the application from the IDE, not through maven.
