### ISSUE TITLE
Synchronized property unexpectedly reverts to last synchronized state

### ISSUE THREAD

**Issue by vursen** [vaadin/flow#20365]
### Description of the bug

Flow reverts the property’s value to the last synchronized state if the property changes again while the previous update is scheduled or is still being processed on the server. This behavior has blocked progress on [DatePicker fallback parser feature](https://github.com/vaadin/flow-components/pull/6743).

https://github.com/user-attachments/assets/7ab2dd8b-6a47-48b5-8fee-8bbd5d0aa859

### Expected behavior

I'd expect Flow to keep the new value and wait for the next synchronization event to send it to the server.

### Minimal reproducible example

```ts
// frontend/my-field/my-field.ts

import { html, LitElement } from 'lit';
import { customElement, query } from 'lit/decorators.js';

@customElement("my-field")
class MyField extends LitElement {
  @query('input')
  inputElement!: HTMLInputElement;

  get inputElementValue() {
    return this.inputElement.value;
  }

  set inputElementValue(value) {
    console.warn('set inputElementValue', value);
    this.inputElement.value = value;
  }

  onChange() {
    this.dispatchEvent(new CustomEvent('change', { bubbles: true, composed: true }));
    this.inputElementValue = 'foobar'; // <------ Change the property right after the synchronization event
  }

  render() {
    return html`<input @change="${this.onChange}" />`
  }
}
```

```java
@Tag("my-field")
@JsModule("my-field/my-field.ts")
public class MyField extends Component {
    @Synchronize(property = "inputElementValue", value = { "change" })
    public String getInputElementValue() {
        return getElement().getProperty("inputElementValue", "");
    }
}
```

```java
@Route("my-field")
public class MyFieldView extends Div {
    public MyFieldView() {
        MyField myField = new MyField();
        add(myField);
    }
}
```

### Versions

- Vaadin / Flow version: 24.5 and possibly earlier
- Java version: 17
- OS version: Mac OS

**Comment by vursen** [comment]
Actually, there is a more real example. I can reproduce the bug using a TextField with a slow internet connection:

```java
TextField textField = new TextField();
add(textField);
```

1. Enable network throttling in browser devtools
2. Type "test" and press <kbd>Enter</kbd>
3. After a round-trip begins, press <kbd>Backspace</kbd>
4. Result: The backspace is discarded when the round-trip completes

https://github.com/user-attachments/assets/b31940fc-89e0-417b-a4f4-f2b18555c6b3

**Comment by tepi** [comment]
The client-side property binding in Flow works in this way. The server round-trip is done asynchronously, and once it's done, flow client does a flush to make sure all the bound properties match the values that were sent to the server. It has been this way for years and I'm pretty sure I've seen that slow network example in something like Vaadin 6/7/8 (provided that network is slow enough or user is fast enough to type). I don't think we can change the basic functionality without breaking a lot of things in the process. So I'd say we need to provide some kind of workaround for the use case needed here.

I have a clarifying question though, in the first example of
```
this.dispatchEvent(new CustomEvent('change', { bubbles: true, composed: true }));
this.inputElementValue = 'foobar';
```
what should happen? The dispatched event triggers a server round-trip. Should the value change on the next line trigger another server round-trip right after the first one has finished? Or should it not trigger a server round-trip, leading to missynchronized values between server and client? Or some other option I did not think of?

**Comment by vursen** [comment]
> Or should it not trigger a server round-trip, leading to missynchronized values between server and client

It should preserve the new value until the next `change` event. There will be temporary desync, but the property will sync eventually.

**Comment by tepi** [comment]
Alright, so that means we would need to remove the whole synced property flush process that is done after the server round-trip finishes. I can try that and see what all breaks. Pinging @Legioth as well as he might have some better ideas here as well

**Comment by tepi** [comment]
@vursen Could you try your case(s) using https://github.com/vaadin/flow/tree/fix/flush-logic? Locally tested seems to fix the slow network case and did not break any `flow-client` tests.

**Comment by mshabarov** [comment]
The second [showcase](https://github.com/vaadin/flow/issues/20365#issuecomment-2454328512) gives a better presentation of the issues. It's looks now end-user affecting especially with the slow internet. I'm leaning towards this is the bug in Flow, no matter what the solution would be. As a end-user, I don't want my new value of the component to be overridden by the previous one.

**Comment by tepi** [comment]
> The second [showcase](https://github.com/vaadin/flow/issues/20365#issuecomment-2454328512) gives a better presentation of the issues. It's looks now end-user affecting especially with the slow internet. I'm leaning towards this is the bug in Flow, no matter what the solution would be. As a end-user, I don't want my new value of the component to be overridden by the previous one.

This also opens another can of worms since arbitrary business logic can do whatever kind of processing for the input value on server side and send it back in the response. I guess in such case server-sent value should still override whatever was input by the user after the round-trip started?

**Comment by vursen** [comment]
> Could you try your case(s) using https://github.com/vaadin/flow/tree/fix/flush-logic? Locally tested seems to fix the slow network case and did not break any flow-client tests.

Unfortunately, I don't see any changes with your branch. I tested both DatePicker and TextField.

> This also opens another can of worms since arbitrary business logic can do whatever kind of processing for the input value on server side and send it back in the response. I guess in such case server-sent value should still override whatever was input by the user after the round-trip started?

I would expect it to override.

**Comment by tepi** [comment]
Thanks @vursen, I'll keep working on a fix. Is it enough to test with https://github.com/vaadin/flow-components/pull/6743 or do I need a custom version of web-components as well?

**Comment by mshabarov** [comment]
> I guess in such case server-sent value should still override whatever was input by the user after the round-trip started?

Yes, I think so.
Server sends no changes -> keep the value on client, no override
Server sends a change -> override, even if user changed the value meanwhile.

**Comment by Legioth** [comment]
I don't remember what the implementation does but one potential approach might be to keep a timestamp for when a synchronized value was last sent to the server and when an updated value was last received from the server. We should re-apply only if the received value is newer than the sent value.
