### ISSUE TITLE
Component.getTranslation should not assign Optional as it's not serializable 

### ISSUE THREAD

**Issue by jorgheymans** [vaadin/flow#20361]
### Description of the bug

If one assigns a method reference to `Component::getTranslation` and uses it in a lambda (for example a valuechange listener), you can end up with a non-serializable sessions because the `Optional` is captured during serde. 

```
    public String getTranslation(String key, Object... params) {
        final Optional<I18NProvider> i18NProvider = LocaleUtil
                .getI18NProvider();
        return i18NProvider
                .map(i18n -> i18n.getTranslation(key,
                        LocaleUtil.getLocale(() -> i18NProvider), params))
                .orElseGet(() -> "!{" + key + "}!");
    }
```

A simple solution seems to be:

```
    public String getTranslation(String key, Object... params) {
        return LocaleUtil.getI18NProvider()
                .map(i18n -> i18n.getTranslation(key,
                        LocaleUtil.getLocale(() -> i18NProvider), params))
                .orElseGet(() -> "!{" + key + "}!");
    }
```

It requires inventive programming, but syntactically perfectly possible:

```
  public static class MyFilter implements Serializable {

    private final TranslationProvider translationProvider;

    public MyFilter(TranslationProvider translationProvider) {
      this.translationProvider = translationProvider;
    }

    public boolean test(String s) {
      return true;
    }
  }
```
Then from a component somewhere 

```
MyFilter myFilter = new MyFilter(this::getTranslation);
```

### Expected behavior

Internally, Vaadin should avoid where possible the use of non serializable classes like Optional. Sometimes program flows take a weird turn and places where you never thought a serialization would occur all of a sudden end up in the session.

### Minimal reproducible example

For the moment it's embedded in our application, but i can extract a reproducer if above explanation is not satisfactory. 

### Versions

Latest 24.x, but all prior versions as well that have this particular implementation of getTranslation.

**Comment by jorgheymans** [comment]
Another example, `AbstractListDataView#addFilter`, if you add a filter to a list data view from a valuechangelistener lambda for example, the session is no longer serializable. 

```
    @Override
    public AbstractListDataView<T> addFilter(SerializablePredicate<T> filter) {
        Objects.requireNonNull(filter, "Filter to add cannot be null");
        Optional<SerializablePredicate<T>> originalFilter = DataViewUtils
                .getComponentFilter(component);
        SerializablePredicate<T> newFilter = originalFilter.isPresent()
                ? item -> originalFilter.get().test(item) && filter.test(item)
                : filter;
        return setFilter(newFilter);
    }
```

**Comment by mcollovati** [comment]
For AbstractListDataView there is a PR

**Comment by mcollovati** [comment]
@jorgheymans how is the `TranslationProvider` defined? Can you provide a minimal failing serialization example?

It seems to me the problem is that the interface is not serializable, not the `getTranslation()` method itself.
If you capture the method reference, the Optional is instantiated at runtime and not stored anywhere.

If I make `TranslationProvider` implement serializable, there are no issues with serializing `MyFilter`.

**Comment by jorgheymans** [comment]
it's defined like this:
```
  @FunctionalInterface
  public interface TranslationProvider extends Serializable {
    String getTranslation(String codelistItem);
  }
```
I can try to extract a failing example, but now that https://github.com/vaadin/flow/pull/20360 was confirmed by you, i'm thinking maybe that one is the actual cause of our serde problem and `getTranslation` a red herring. I'll try and isolate an example, and if i don't manage i'll close this issue.

**Comment by jorgheymans** [comment]
In any case, Flow and components could have a build time rule using pmd or something that flags the usage of non serializable classes like Optional.of . My perception - from the outside, and I apologize if that's not the case - is that serializability is not getting always the attention it needs. Both in Vaadin framework as well as add-ons. Maybe Vaadin could provide maven plugin for this that would scan for potential unserializable code patterns? Useful for the project itself _and_ its users.

**Comment by mcollovati** [comment]
Flow and components have serialization tests, but most likely not all potential cases are identified covered and others are unfortunately really difficult to test in advance (e.g. lambda self references).
Anyway, it would indeed be good to improve this area of testing.

**Comment by jorgheymans** [comment]
Ok i could not come up with a reproducer, the root cause was indeed `AbstractListDataView#addFilter`. 

Still, given that none of the other `getTranslation` methods in `Component` store the Optional, this particular one could be aligned to the same code style.

**Comment by mcollovati** [comment]
The proposed code seems incorrect, `i18NProvider` is not defined.

```java
    public String getTranslation(String key, Object... params) {
        return LocaleUtil.getI18NProvider()
                .map(i18n -> i18n.getTranslation(key,
                        LocaleUtil.getLocale(() -> i18NProvider), params))
                .orElseGet(() -> "!{" + key + "}!");
    }
```

Did you mean something like the following? 

```java
    public String getTranslation(String key, Object... params) {
        return LocaleUtil.getI18NProvider()
                .map(i18n -> i18n.getTranslation(key,
                        LocaleUtil.getLocale(LocaleUtil::getI18NProvider), params))
                .orElseGet(() -> "!{" + key + "}!");
    }
```
It seems to me an unnecessary additional lookup of `I18NProvider`.
Even reusing the `i18n` instance,  `getLocale()` takes a `Supplier<Optional<I18NProvider>>`, so the lambda should anyway create an additional `Optional`.

**Comment by jorgheymans** [comment]
@mcollovati I agree with your observation, there was a specific reason to assign Optional then.
