### ISSUE TITLE
Javascript error: Invalid blocker state transition

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow#20404]
### Description of the bug

When I'm navigating in my Vaadin application I have some javascript errors.
> Uncaught (in promise) Error: Invalid blocker state transition: unblocked -> proceeding

![image](https://github.com/user-attachments/assets/5287c455-8458-4969-827d-f433f8c8c811)

![image](https://github.com/user-attachments/assets/88be118e-ce2a-4451-8cfa-ebc90934ee4e)

### Expected behavior

A javascript error should not appear in a normal case of usage.

### Minimal reproducible example

Create a Vaadin application with two views in a menu, clicks multiple times on the menu.

I think the error appears when you click on the menu when the application is already navigating so if the view is really fast to load you need to click fast.

### Versions

- Vaadin / Flow version: 24.5.2

**Comment by jcgueriaud1** [comment]
This might be connected: https://github.com/vaadin/copilot-internal/issues/3247

**Comment by mshabarov** [comment]
This looks like a misconfiguration or misusing of React's blocker function in Flow.tsx (ReactRouter/Flow integration).

**Comment by Lodin** [comment]
This error looks like connected to the [`useBlocker`](https://github.com/vaadin/flow/blob/c4db0411a01158a8ed3010af1f1cb47d1265f15f/flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx#L270) hook

**Comment by mshabarov** [comment]
> To me, this error looks like connected to the [useBlocker](https://github.com/vaadin/flow/blob/c4db0411a01158a8ed3010af1f1cb47d1265f15f/flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx#L270) hook

Exactly, this was what I meant.

**Comment by mcollovati** [comment]
Maybe a check is missing here in the `serverConnected` callback defintion

https://github.com/vaadin/flow/blob/c4db0411a01158a8ed3010af1f1cb47d1265f15f/flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx#L405-L413

**Comment by mcollovati** [comment]
The fix has been released with Vaadin 24.5.6. Could you try to upgrade to the latest version (or at least to 24.5.6) and try again?
