### ISSUE TITLE
Proposal: make the ComponentEvent contains the listener Registration, so the developer can remove the listener after receiving an event

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#2044]
Currently the only way of removing a `ComponentEventListener` from a component is to get the `Registration` object from the `addListener` method. For example:

```
Registration registration = button.addListener(ClickEvent.class, event -> doSomething());
// ...
registration.remove();
```
That works for most cases, except when you have listeners in constructors of some components. For example:

```
public class MyComponent extends Component {

    public MyComponent(SomeListener listener) {
        addListener(SomeEvent.class, somelistener); // <- the registration is forever lost
    }
}
```
My proposal is to change the `ComponentEvent` class to also have the `Registration` object. By doing so, the developer would be able to remove the listener associated with the event, without having to store the `Registration` object somewhere.

Example usage:
```
button.addListener(ClickEvent.class, event -> {
    doSomething();
    event.getListenerRegistration().remove();
});
```
(`getListenerRegistration` is the proposed name of the method, but could be anything else)

**Comment by pleku** [comment]
Related to https://github.com/vaadin/flow/issues/3357, this could solve that one.
