### ISSUE TITLE
Alpha testing of Vaadin 24.6.0.alpha3 vs new Flow features

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#20459]
Test the happy path of these new features:
- [x] WebPush notification options
- [x] setDragImage
- [x] exclude Vaadin components
- [x] easier config for SpringServlet
- [x] Add support for customizable projectFileExtensions

**Comment by mshabarov** [comment]
For anyone willing to start this - I'd love to try and test:
-exclude Vaadin components
-easier config for SpringServlet

**Comment by caalador** [comment]
- [x] Web push - ok
- [x] Drag image - ok
- [ ] exclude Vaadin components - works, but no documentation
- [x] easier config for SpringServlet - ok, no doc?
Skipping file extensions as I did that feature.

**Comment by mshabarov** [comment]
https://github.com/vaadin/docs/issues/3913

**Comment by mcollovati** [comment]
Add support for customizable projectFileExtensions: tested and works when importing things like `@CssImport("some.scss")`.
The new `frontendExtraFileExtensions` seems not to be documented in https://vaadin.com/docs/latest/flow/production/production-build.
A question: I tried set `frontendExtraFileExtensions=boh` and to import a file into a JS script included with `@JsModule` ont the view. The JavaScript contains `import something from 'Frontend/my.boh?raw';`. However, `my.boh` is not included in the stats JSON. Is this expected?

Side note, the maven plugin documentation seems a bit outdated. For example, it lists an `includes` setting that does not seem to exist.

**Comment by caalador** [comment]
I would expect it to be there if it is handled by vite. 

As `boh` marked with ?raw vite imports is as a String and it is thus not handled as a file, mening that vite didn't handle it and it will not show up.

**Comment by mcollovati** [comment]
Got it. Thanks for clarification.

**Comment by mshabarov** [comment]
**exclude Vaadin components**
Does it's job for React and Lit based Vaadin apps.

However, I got these info messages, even though I've already excluded components and copilot:
```
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.vaadin</groupId>
                    <artifactId>vaadin-core-components</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.vaadin</groupId>
                    <artifactId>copilot</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

message:
```
2024-11-18T12:14:57.440+02:00  INFO 6446 --- [onPool-worker-2] c.v.f.server.frontend.TaskUpdateImports  :

  Failed to find the following imports in the `node_modules` tree:
      - @vaadin/list-box/src/vaadin-list-box.js
      - @vaadin/number-field/src/vaadin-number-field.js
      - @vaadin/grid/src/vaadin-grid-sorter.js
      - ....
```
See [exclude-vaadin-components.txt](https://github.com/user-attachments/files/17799142/exclude-vaadin-components.txt)

@tltv is this expected? Could we avoid these messages?

**Comment by mshabarov** [comment]
https://github.com/vaadin/docs/issues/3921

**Comment by tltv** [comment]
With `<artifactId>vaadin</artifactId>` it includes pro component dependencies, which afaik depends on core components. Try changing that to `vaadin-core` and it should work. This is documentation issue and need to clear that pro components need to be excluded too by using only `vaadin-core` dependency.

**Comment by mshabarov** [comment]
Thanks, why I couldn't resolve it by myself 😄 
Nothing bothers me after I added this:
```xml
 <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-core</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.vaadin</groupId>
                    <artifactId>vaadin-core-components</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.vaadin</groupId>
                    <artifactId>copilot</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.vaadin</groupId>
                    <artifactId>vaadin-icons-flow</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

These three exclusions have to be added into docs, I believe.
