### ISSUE TITLE
Test new JRebel that supports Hotswapper

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#20452]
### Describe your motivation

Test Vaadin 24.6 and 24.5 with the latest JRebel [snapshot](https://www.jrebel.com/products/jrebel/download/nightly-build), where the Hotswapper API is implemented.

These should be checked:
- [x] editing, adding a new flow route, deleting a flow route leads to UI refresh
- [x] Copilot shows a proper status for Java Hotswap
- [x] Copilot features works (adding new and modifying existing route)
- [x] editing a translation file leads to server restart and UI refresh

**Comment by caalador** [comment]
Cases seen in reported logs:
- `Ignore old message from client`
  - Server receives previous message id with the same content hash as last processed
  - Server should resend last response to sync state on client.
- `Unexpected id from client`
  - If the client id is bigger than the expected there has been a dropped client request. (client updates the id on `preparePayload`)
  - Client should be requested to resend previous message and server should sync the id to current request id.
- Server expected much bigger than the client request?
  - Resynchronization should probably happen as the gap is too big and why is the client requesting with much too old id?
-

**Comment by tepi** [comment]
**Editing, adding a new flow route, deleting a flow route leads to UI refresh**
- Editing and adding works fine via Copilot and via IDE directly
- Removing a route class removes it from target folder but route remains available in app

**Copilot shows a proper status for Java Hotswap**
- Works fine

**Copilot features works (adding new and modifying existing route)**
- Works fine

**Editing a translation file leads to server restart and UI refresh**
- When first creating the translations via Copilot, the first refresh leads to Copilot log saying "Error: Failed to get translations"
- However, editing the newly created translation file in IDE after that loads the changes just fine
- Also editing the translations via Copilot does reload the change fine

**Comment by tepi** [comment]
> Removing a route class removes it from target folder but route remains available in app
This seems to work the same way with hotswap agent

**Comment by mshabarov** [comment]
Tested with the JRebel Agent 2024.4.2-SNAPSHOT (2024-11-21 11:38) and observed the same testing results as @tepi did with little difference: I got no Copilot error message - it added the translation codes then instructed me to restart the server, I did it, and then I got working refreshes on each modification of translation files.

Note that JRebel doesn't support deleted class case by design.

**Comment by tepi** [comment]
> with little difference: I got no Copilot error message

Tested this two more times, not getting an error message. Could have been something random.

**Comment by mshabarov** [comment]
I'm currently investigating the reloading case, when `@EventData` value is changed and changes are reflected on the UI, e.g. when the parameter name is wrong in Java, one want to fix it and gets no UI refresh after that.

**Comment by mshabarov** [comment]
Follow up issue - https://github.com/vaadin/flow/issues/20548.

I think this testing ticket can be closed now.
