### ISSUE TITLE
Missing hints for automatic menus

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#20458]
### Description of the bug

@marcushellberg :
I'm getting this when trying to run an app as a GraalVM native image. I can't reproduce it in a simple app, so I haven't yet filed an issue. Any pointers on what may be going wrong? Looks like we may be missing some hints again

```
2024-11-02T17:44:57.084-04:00  WARN 61021 --- [nps] [           main] c.v.flow.internal.menu.MenuRegistry      : Failed load file-routes.json from /META-INF/VAADIN/file-routes.json

com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.vaadin.flow.server.menu.RouteParamType` from String "req": not one of the values accepted for Enum class: [OPTIONAL, WILDCARD, REQUIRED]
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 10, column: 21] (through reference chain: java.util.ArrayList[0]->com.vaadin.flow.server.menu.AvailableViewInfo["children"]->java.util.ArrayList[0]->com.vaadin.flow.server.menu.AvailableViewInfo["params"]->java.util.LinkedHashMap[":token"])
```

### Expected behavior

No warnings and errors.

### Minimal reproducible example

No info, but probably Vaadin 24.6 application that uses FS router and auto menus feature, also compiled to GraalVM native image.

### Versions

Vaadin 24.6 pre

**Comment by mcollovati** [comment]
It can be reproduced with the `flow-hilla-hybrid-example`, by adding an optional parameter view route.
For example, create a `src/main/frontend/views/products/{{product}}.tsx` file with the following content

```javascript
import { useParams } from 'react-router-dom';
import type { ViewConfig } from "@vaadin/hilla-file-router/types.js";

export const config: ViewConfig = {
    loginRequired: false,
    menu: {
        title: "Product",
        icon: 'vaadin:info'
    }
};

export default function ProductView() {
    const { productId } = useParams();

    return (<>
        <span>{productId}</span>
    </>)
}
```

Then build the native executable with ``
When starting the application, you should see the error.
