### ISSUE TITLE
Dialog is not updated when doing hotswap

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#20473]
### Description of the bug

Given

```
@Route(value = "overlay", layout = MainLayout.class)
@AnonymousAllowed
public class OverlayView extends VerticalLayout {

    @Override
    protected void onAttach(AttachEvent attachEvent) {
        super.onAttach(attachEvent);

        Dialog dialog = new Dialog("The Dialog");
        dialog.setCloseOnOutsideClick(true);
        dialog.setCloseOnEsc(true);

        dialog.add(new Div("Text nr 1"));

        dialog.open();
    }

}
```

if you are running using HotswapAgent and edit the div text to "Text nr 2", then a dialog with "Text nr 1" remains on screen and a dialog with "Text nr 2" is not added at all. If you manually refresh the page, the dialog with "Text nr 2" is shown

### Expected behavior

The old dialog is closed and the new one opened

### Minimal reproducible example

as above

### Versions

- Vaadin / Flow version: 24.5.3

**Comment by mcollovati** [comment]
Refresh seems to work if the dialog is added to the route component.

```
add(dialog);
dialog.open();
```

If not added explicitly to another component, the dialog has `UI` as a parent, so it is not detached during refresh.
On refresh, we could probably remove modal components, but this might not be correct in all situations.
For example, if the dialog is added by a layout, and we request a refresh for the route component only, the dialog would not be re-opened, since the layout is not detached and attached.

**Comment by mcollovati** [comment]
In the case of route chain refresh, if dialogs attached to the UI are forcibly removed, they are not re-added.
Dialog class registers an `afterNavigationListener` that for programmatic navigation removes the `beforeClientResponse` callback that should do the attach.

https://github.com/vaadin/flow-components/blob/985c10c20d40bb706326d401bed7be50a45de4eb/vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L899-L925

**Comment by sveinnetnordic** [comment]
I am working with a big dialog an tough that form field was updated on the "new" hotswap way, but that did not happen. 
What about having a way to set the way hotswap should work in Copilot in the browser (set at cookie etc). Mode: Full refresh/"new refresh". A -Dvaadin.hotswapmode=... would also be nice. I assume the "new hotswap" will be default
