### ISSUE TITLE
React Router Future Flag warning

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#20527]
### Description of the bug

 There's a number of warnings triggered by React Router when using the latest Vaadin Flow snapshot/pre-release (24.6):
⚠️ React Router Future Flag Warning: React Router will begin wrapping state updates in `React.startTransition` in v7. You can use the `v7_startTransition` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_starttransition. indexhtml-CdhAQHz9.js:51:6661
⚠️ React Router Future Flag Warning: Relative route resolution within Splat routes is changing in v7. You can use the `v7_relativeSplatPath` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_relativesplatpath. indexhtml-CdhAQHz9.js:51:6661
⚠️ React Router Future Flag Warning: The persistence behavior of fetchers is changing in v7. You can use the `v7_fetcherPersist` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_fetcherpersist. indexhtml-CdhAQHz9.js:51:6661
⚠️ React Router Future Flag Warning: Casing of `formMethod` fields is being normalized to uppercase in v7. You can use the `v7_normalizeFormMethod` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_normalizeformmethod. indexhtml-CdhAQHz9.js:51:6661
⚠️ React Router Future Flag Warning: `RouterProvider` hydration behavior is changing in v7. You can use the `v7_partialHydration` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_partialhydration. indexhtml-CdhAQHz9.js:51:6661
⚠️ React Router Future Flag Warning: The revalidation behavior after 4xx/5xx `action` responses is changing in v7. You can use the `v7_skipActionErrorRevalidation` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_skipactionerrorrevalidation.

Options:
- to opt-in these features, fix the behaviour that fails after that
- to opt-out from these features for now, this though will come back later.

### Expected behavior

No warnings

### Minimal reproducible example

Any Vaadin 24.6 and 24.5 application that uses React Router (by default).

### Versions

- Vaadin / Flow version: 24.6 pre and 24.5.

**Comment by mshabarov** [comment]
Adding all of these feature flags to the Flow-Hilla hybrid example looks promising, I couldn't spot any warning or unexpected behaviour:
```typescript
// index.tsx:
function App() {
    return <AuthProvider>
        <RouterProvider router={router} future={{ v7_startTransition: true }} />
    </AuthProvider>;
}

// routes.tsx:
.build({
    future: {
        v7_fetcherPersist: true,
        v7_normalizeFormMethod: true,
        v7_partialHydration: true,
        v7_relativeSplatPath: true,
        v7_skipActionErrorRevalidation: true
    }
 });
```

**Comment by manolo** [comment]
@mshabarov is this actually fixed? because in beta3 I still can see warning messages when running in prod-mode check this [log](https://github.com/vaadin/platform/actions/runs/12183647317/job/34111807166#step:10:235)

**Comment by ZheSun88** [comment]
can be reproduced with mpr-demo
using vaadin.version: 24.6.0.beta3, flow.version: 24.6.0.beta7

```
git clone git@github.com:vaadin/mpr-demo.git
perl -pi -e 's|(\s*<'vaadin.version'>)[^\s]+(</'vaadin.version'>)|${1}24.6.0.beta3${2}|g' pom.xml
perl -pi -e 's|(\s*<'flow.version'>)[^\s]+(</'flow.version'>)|${1}24.6.0.beta7${2}|g' pom.xml
mvn -ntp -Pproduction -B jetty:run-war
```

**Comment by mshabarov** [comment]
This misses at least a patch in auto-generated `routes.tsx` file for Flow apps.

**Comment by mshabarov** [comment]
There is one cherry pick PR pending, but else I think the issue can be closed.
