### ISSUE TITLE
When calling some Client RPC I want to be able to use same type of arguments as I'm able to use with TemplateModel

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/flow#2056]
I'm trying to call some API exposed by the Element of my `PolymerTemplate` and right now the alternative is to use `PolymerTemplate#getElement#callFunction` which requires creating a `JsonObject` when dealing with complex objects.

The list of supported property types for `TemplateModel` is easily enabling more possibilities; it would be great to have the same freedom when doing a client RPC.

**Comment by mshabarov** [comment]
Polymer Template is under critical maintenance, so no enhancements are planned.
