### ISSUE TITLE
Missing API to configure the ReconnectDialog

### ISSUE THREAD

**Issue by paulroemer** [vaadin/flow#2059]
As a developer I want to be able to configure the ReconnectDialog. In the simplest case I just want to hide it.

Denis on Mon at 9:11
> I don't think reconnect dialog has been designed to have API to communicate with it.
You can call GWT methods fro JS but you need an instance for that. And you don't have this instance in your code.
So the feature you requested is an enhancement.
I don't know the details of it actually.
This stuff has been migrated from FW where everything has been written on GWT. So there were not problems with that.
Now situation has changed.

**Comment by mshabarov** [comment]
@paulroemer is this API needed still? I'm closing this ticket, but feel free to open it if it's still valid.
