### ISSUE TITLE
Upgrade to Vaadin 24.4.15+ causes scrollable pages to become blank when scrolling

### ISSUE THREAD

**Issue by stellirin** [vaadin/flow#20598]
### Description of the bug

With Vaadin 24.4.15+, on pages that have enough content to be scrollable, the content of the page disappears when scrolling the page, typically before reaching the bottom of the page. At what point in the scroll the content disappears seems to depend on the size of the browser window. When scrolling back up the page content reappears.

Versions 24.4.14 and earlier do not have this issue.

### Expected behavior

Content on a scrollable page should not disappear.

### Minimal reproducible example

https://github.com/stellirin/vaadin-scrolling-bug-demo

### Versions

- Vaadin / Flow version: 24.4.15
- Java version: 21
- OS version: macOS 14.7.1
- Browser version (if applicable): Firefox/Chrome latest
- Application Server (if applicable):
- IDE (if applicable): IntelliJ IDEA

**Comment by Artur-** [comment]
This is caused by https://github.com/vaadin/web-components/pull/7988
