### ISSUE TITLE
[PiT] switching between different views results in wrong url

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#20671]
### Description of the bug

for a multi view app, when i switch between different views, the url will be ended in a wron format.
check GIF
![multi-view-24 6 0 beta4](https://github.com/user-attachments/assets/54a68af4-bdd8-4d0d-b98b-02f486f3f06c)

### Expected behavior

app works

### Minimal reproducible example

```
curl -s -f 'https://start.vaadin.com/dl?&preset=latest-java&preset=partial-auth&projectName=latest-java_partial-auth' -o 'latest-java_partial-auth.zip'
unzip -q 'latest-java_partial-auth.zip'
cd 'latest-java-partial-auth'
perl -pi -e 's|(\s*<'vaadin.version'>)[^\s]+(</'vaadin.version'>)|${1}24.6.0.beta4${2}|g' pom.xml
perl -pi -e 's|(\s*)(<repositories>)|$1$2\n$1$1<repository><id>v</id><url>https://maven.vaadin.com/vaadin-prereleases</url></repository>|' pom.xml
perl -pi -e 's|(\s*)(</project>)|$1$1<pluginRepositories><pluginRepository><id>v</id><url>https://maven.vaadin.com/vaadin-prereleases</url></pluginRepository></pluginRepositories>\n$1$2|' pom.xml
perl -pi -e 's|<java.version>21</java.version>|<java.version>17</java.version>|' pom.xml
./mvnw

then navigate to `localhost:8080`
login the app admin/admin
switch between views like in the gif
```

### Versions

- Vaadin / Flow version:24.6.0.beta4/24.6.0.beta8 (hilla version 24.6.0.beta7)

**Comment by caalador** [comment]
Is this changing routes between flow routes using a hilla main layout?

**Comment by caalador** [comment]
I can see this appending of the navigation route if I use a slowed down connection for the application.

**Comment by mshabarov** [comment]
I couldn't reproduce even with 3G and slow 4G:
![appending-path](https://github.com/user-attachments/assets/477a374c-cbea-40d1-9869-a5ca58de26e6)
