### ISSUE TITLE
Gradle plugin doesn't support configuration cache

### ISSUE THREAD

**Issue by igieon** [vaadin/flow#20716]
### Description of the bug

Run build project with configuration cache and you get error:
```
Class `com.vaadin.flow.server.frontend.FrontendToolsLocator`: external process started 'which node'
  See https://docs.gradle.org/8.11.1/userguide/configuration_cache.html#config_cache:requirements:external_processes
```
```
 Starting an external process 'which node' during configuration time is unsupported.
 ```

### Expected behavior

Build project with command:
```
./gradlew --configuration-cache --build-cache vaadinPrepareFrontend 
```

### Minimal reproducible example

Use spring initliazir with vaadin and execute:
```
./gradlew --configuration-cache --build-cache vaadinPrepareFrontend 
```

### Versions

Latest from spring initializer

**Comment by mshabarov** [comment]
Using the Gradle configuration cache is an enhancement already requested here https://github.com/vaadin/flow/issues/18612.

For the problem with `which node`, we'll need to investigate, but I pretty sure Vaadin has some config parameter via which you can set the path to Node, I need to recall the name of it.

**Comment by mshabarov** [comment]
By the way, it's not only about `which node`, but other commands that Gradle does not support, see the linked issue.
