### ISSUE TITLE
Maven plugin uses wrong javassist version

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#20712]
### Description of the bug

Whenever building a project, I see
```
[WARNING] Found dependencies defined with different versions in project and Vaadin maven plugin.
Project dependencies are used, but plugin execution could fail if the versions are incompatible.
In case of build failure please analyze the project dependencies and update versions or configure exclusions for potential offending transitive dependencies.
You can use 'mvn dependency:tree -Dincludes=groupId:artifactId' to detect where the dependency is defined in the project.

org.javassist:javassist:jar: project version [3.30.2-GA], plugin version [3.28.0-GA]
```

### Expected behavior

The correct version is `3.30.2-GA`, the plugin essentially complains about itself.

```
com.vaadin:flow-maven-plugin:jar:24.7-SNAPSHOT:compile
\- com.vaadin:flow-plugin-base:jar:24.7-SNAPSHOT:compile
   \- org.reflections:reflections:jar:0.10.2:compile
      \- org.javassist:javassist:jar:3.28.0-GA:compile
```

### Minimal reproducible example

mvn vaadin:build-frontend

### Versions

- Vaadin / Flow version: 24.7-SNAPSHOT

**Comment by mcollovati** [comment]
`javassist` dependency is defined by `vaadin-spring` add-on, so it makes sense that the plugin uses the same version.

**Comment by mshabarov** [comment]
Could we pin `javassist` version in `flow-plugin-base` to be not fetched as a transitive dependency from `reflections`?

**Comment by mcollovati** [comment]
> Could we pin javassist version in flow-plugin-base to be not fetched as a transitive dependency from reflections?

Yes, this is the idea. And also put the version in a property in the root pom, so it is defined in a single place.
