### ISSUE TITLE
JsonSerializer: add support for Collections and arrays inside objects

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#2084]
Currently the JsonSerializer doesn't  support  the serialization and deserialization of Collections or arrays inside objects.

Example object:

```
public class MyBean {
    private List<String> strings; //list of simple types
    private List<OtherBean> beans; //list of complex objects
    private int[] ints; //array of primitives
    private OtherObject[] beanArray; //array of complex types
}
```
The serializer should support:
* Iterable of wrapper types (Integer, Double, Boolean and so on)
* Iterable of Strings
* Iterable of Enum
* Iterable of complex objects (java beans)

For arrays:
* Array of primitive types (int[], double[], boolean[] and so on)
* Array of wrapper types
* Array of Strings
* Array of Enum
* Array of complex objects (java beans)

**Comment by mshabarov** [comment]
Polymer Template is under critical maintenance, so no enhancements are planned.
