### ISSUE TITLE
When creating a polymer template, I want the tag name and HTML import derived from the class name, so that I don't have to boilerplate

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#2114]
Given a class defined as `public class MyTemplate extends PolymerTemplate<MyTemplateModel>`, it's reasonable to assume that the element name will be `my-template` and that the template file should be imported from `frontend://src/my-template.html`. I want to define `@Tag` and `@HtmlImport` annotations only in cases that deviate from these defaults.

**Comment by pleku** [comment]
While this would have been a quite straight forward addition, there has not been support for it to become a priority. If this would be import to do, I would expect it to come about again if we introduce support for another template format (like lit).
