### ISSUE TITLE
When listening for template model changes, I want to use API in PolymerTemplate or TemplateModel, so that I wouldn't have to know about Element APIs

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#2116]
It's a leaking abstraction that I have to use `getElement()` for getting an event when a two-way data binding has been updated from the client.

See https://github.com/vaadin/flow-hello-world/blob/abbec98/src/main/java/com/vaadin/flow/demo/helloworld/HelloWorldTemplate.java#L43 for an example.

**Comment by mshabarov** [comment]
Polymer Template is under critical maintenance, so no enhancements are planned.
