### ISSUE TITLE
Generating server side components needs to run twice to generate Java classes for new webcomponents

### ISSUE THREAD

**Issue by paulroemer** [vaadin/flow#2123]
When I added the paper-toast webcomponent in ```bower.json``` of ```flow-webcomponent-api-analyzer``` and run ```mvn -Pgenerator install``` in ```flow-components-parent``` only the json files are generated. The corresponding Java class (in this case ```GeneratedPaperToas```) was only generated during the next run.

**Comment by caalador** [comment]
Closing as generator has been removed from Flow project.
