### ISSUE TITLE
When hiding an element in a template I want a way to be sure that no event handlers for the hidden elements can be called so I do not have to check manually if the user should be able to call a method

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#2187]
As a Vaadin Framework 8 user, I'm used to being able to do `component.setEnabled(false)` or `component.setVisible(false)` and being able to trust the framework to prevent any events (rpcs) from reaching the component. It would be nice to have a similar feature when dealing with elements in a template, e.g if I have:

```
<p>
     If the button is there and enabled, feel free to click it:
    <button id="destroyEverything">Destroy it all</button>
```

```
@Id("destroyEverything")
private Button destroy;
...

public void init() {
destroy.addClickListener(e->{deleteRecursively("/");});
if (!superman) {
    // This is what I want to do, and then trust that the click listener will not be invoked, no matter what happens in the browser
    destroy.setVisible(false); // or setEnabled(false)
```

The only option right now seems to be to hide the element using CSS and do the check in the click listener itself. In a trivial case like this, it's manageable, but then you add more listeners and need to remember to check it manually in all places. At some point you will forget it and you have a problem.

**Comment by pleku** [comment]
Superseded by #2209
