### ISSUE TITLE
When configuring a DatePicker, I want to automatically populate a DatePickerI18n based on Locale so that I don't have to type the value manually.

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#2188]
Java on the server already knows most of what goes into `DatePickerI18n`, e.g. month and weekday names. We should provide a helper that sets those values based on a `Locale`.

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-date-picker-flow #3](https://github.com/vaadin/vaadin-date-picker-flow/issues/3) via [**ZenHub**](https://www.zenhub.com/)
