### ISSUE TITLE
When building web apps, I want to change the locale for all UI components at once, so that the user can easily change the language

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2206]
This corresponds to `com.vaadin.u.Component::getLocale()` from FW8, but should be redesigned to handle easily the case where you the user wants to change the locale easily on the fly. t).

**Comment by caalador** [comment]
Decided to implement this as an `LocaleObserver` that will be triggered for all
connected components implementing the observer interface when the `UI::locale` changes.

**Comment by Legioth** [comment]
Clarification: The observer method should also be triggered when the component is attached, regardless of any changes to the UI locale.

**Comment by pabloveratech** [comment]
lol
