### ISSUE TITLE
com.vaadin.ui.Component should have a feature similar to setVisible() in FW8

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2209]
`When building an app, I want to hide/show some components like error messages easily, so I can easily trigger the visibility when necessary without adding and removing components`

`When using the Tabs component, I want to have the contents of the different tabs present in the DOM but not visible or intractable, so that when the user changes the tab I can get the new contents render very quickly and without writing lots of code`

`When building an app with templates, I want to hide an id mapped component / nested template easily from server side code, so I can be productive and not write the logic into the template`

In Vaadin Framework 8, this is a server side convenience feature that also has security implications - any updates for those components from client side are not accepted. **The same applies here: the users of the feature should be able to trust that the user cannot interact with those parts of the UI that have been "hidden".**

There is a _DOM_ property `hidden` which maps to `display:none;` in that element's CSS, and it can be used for easily hiding things. This is only an easy way for hiding things on client side, but it would allow to not have to do any other DOM modifications for getting elements hidden.

The discussion thus far has been suggesting that we would rename the feature to something else than `visible`.

**Comment by pleku** [comment]
It is very important to make sure that any `setVisible(false)` component (or its children) will not accept any events or updates from the client side.
