### ISSUE TITLE
Full resynchronization of client is not implemented

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#2210]
Occasionally, due to connectivity issues, client RPCs might get duplicated (?) or lost (?) (_according to the ServerRpcHandler.handleRpc_). The server must initiate client resync in this case, but it's not there yet.

No matter what, the exception is thrown instead. 
```
java.lang.UnsupportedOperationException: FIXME: Implement resync and call it above
at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:298)
at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:87)
```

**Comment by fluorumlabs** [comment]
> Question. Is there in the logs a message Unexpected message id from the client. Expected: ...?

I can't see any.

**Comment by caalador** [comment]
Any `Ignoring old message from the client. Expected: ` then?

**Comment by paulroemer** [comment]
No, unfortunately not.

**Comment by fluorumlabs** [comment]
Any news on that?

**Comment by fluorumlabs** [comment]
BTW `Ignoring old message from the client. Expected:` probably not in the logs because it's logged with a `debug` level

**Comment by fluorumlabs** [comment]
Ok, I found the way to reproduce the issue:
1. Client makes a UIDL server request.
2. Server (or rather load balancer/cache/proxy/whatever) responds with (for example) 502 Bad Gateway or 504 Gateway Timeout
3. Client makes a next UIDL server request.
4. `java.lang.UnsupportedOperationException: FIXME: Implement resync and call it above` happens on the server side

**Comment by mpilone** [comment]
I'm also seeing this error on a couple of my v13 applications. I attached a browser client log from where I was able to reproduce the issue. In my case, the error is triggered by the client missing a message from the server. The client logs that it is missing a message and waiting, then eventually times out and attempts to resync which throws the exception on the server side.

```
Received message with server id 212 but expected 211. Postponing handling until the missing message(s) have been received
...
Gave up waiting for message 211 from the server
Resynchronizing from server
```

I can reliably reproduce the problem using long polling push and unplugging my network connection for 10 seconds or so, causing a server message to be missed, then connecting to the network again. I'm sure there are probably other scenarios that cause a message to get dropped but network connectivity seems to be the easiest to reproduce.

It really seems like this functionality needs to be implemented on the server side if the client can still send the resync request. Or the client needs to be modified to handle this gracefully. It seems like this could happen anytime a push message is dropped. Right now it will always generate the exception:

ServerRpcHandler.java:313
```
 if (rpcRequest.isResynchronize()) {
            // FIXME Implement
            throw new UnsupportedOperationException("FIXME: Implement resync");
        }
```

[Resync Error Client Log.txt](https://github.com/vaadin/flow/files/3487821/Resync.Error.Client.Log.txt)

**Comment by mhosio** [comment]
Verified. Easy to reproduce with V14 as well exactly as described by mpilone. Seems a whole bunch of push messages can be missed.

`Received message with server id 100 but expected 61. Postponing handling until the missing message(s) have been received`

In my case the situation was related to getting net::ERR_CONNECTION_RESET 200 (OK)  in response to the push connection request for long polling. Looks like server has been writing push messages to the open connection and incrementing the sequence numbers after which the connection has been reset. Thus client and server end up not being in sync. Attaching some screenshots from chrome debugger.

**Comment by m-emelchenkov** [comment]
Please fix it if possible, it's very annoying bug. I use `@Push(transport = Transport.LONG_POLLING)` instead WebSocket Push due to bug in Safari which prevents using WebSocket with client-side certificates.

**Comment by mpilone** [comment]
I implemented a very poor workaround that handles the resynchronization request and simply sends a full refresh command to the client. It is far from perfect and not the correct implementation, but I rather have the user's page reload than have them see an internal error notification and call our help desk. You might be able to use it directly or at least get some ideas for your own workaround.

[RefreshingResynchronizeHandler.java.zip](https://github.com/vaadin/flow/files/3520781/RefreshingResynchronizeHandler.java.zip)

**Comment by m-emelchenkov** [comment]
Thank you, @mpilone for sharing.

**Comment by miroslavvojtus** [comment]
I also vote for urgent resolution of this bug. It is happening to us multiple times a day with pretty stable connection over WS. Is there any more straight forward solution than @mpilone's?
The suggested workaround is more temporary hack than solution.

**Comment by mehdi-vaadin** [comment]
Can someone please provide instructions or an example to reproduce this issue?

**Comment by mpilone** [comment]
Here's a simple test case to reproduce the problem.

1. Load the view
2. Wait for the counter to start counting
3. Unplug your network connection (or take down all your interfaces)
4. Wait for 5 seconds
5. Plug in your network connection
6. Get an error.

It looks like you might get a 

> Trying to start a new request while another is active

OR 

> Internal error
> Please notify the administrator.
> Take note of any unsaved data, and click here to continue.

[Bug2210View.java.zip](https://github.com/vaadin/flow/files/3729301/Bug2210View.java.zip)

**Comment by mehdi-vaadin** [comment]
@mpilone Thanks :)

**Comment by mehdi-vaadin** [comment]
I couldn't reproduce it in Chrome 77. But, it happens in Firefox 60 ESR.

**Comment by mpilone** [comment]
The issue with resynchronization is a server side issue, see ServerRpcHandler.java:304:
```
if (rpcRequest.isResynchronize()) {
            // FIXME Implement
            throw new UnsupportedOperationException("FIXME: Implement resync");
        }
```

As long as the client can generate a resynchronization request and this code exists on the server, there are going to be problems. It's possible that there are multiple bugs here (i.e. "trying to start a new request" and "internal error") but the core resync issue should be browser type and version independent. If the client sends a resync request because it missed one or more push messages, the server throws an exception.

**Comment by Legioth** [comment]
So we'd either need the sledgehammer of full resync (which impacts UX since things may flicker or unsubmitted data may be lost when everything is rebuilt) or some mechanism that preserves messages until the server can be sure the message has been processed (which increases server memory use).

**Comment by samie** [comment]
Surprising that Atmosphere does not have any built-in/optional ACK of somekind. Could that be a contribution? Anyway, full sync might be good to have as a last resort and for other use cases, but beyond that this sounds like a very traditional communication protocol design.

**Comment by ujoni** [comment]
There seems to be this about ACK messages:
https://github.com/Atmosphere/atmosphere/issues/1034

So in some form it is a pro feature which is tagged 3.0, if I read that correctly
