### ISSUE TITLE
Keep ordering of addJavaScript() and addHtmlImport() as defined by developer

### ISSUE THREAD

**Issue by Haprog** [vaadin/flow#2235]
I want the ordering of the files loaded with `addJavaScript()` and `addHtmlImport()` to be kept same in the response as how they’re called in code so that I can do:
```java
page.addJavaScript("frontend://js/scripts-inline.js", LoadMode.INLINE);
page.addHtmlImport("frontend://views/vc-app-shell.html");
```
and expect it to work so that I can define a global function in `scripts-inline.js` and I can call it immediately in `vc-app-shell.html`.

Now it seems that Flow puts the import of `vc-app-shell.html` first and inlines the `scripts-inline.js` after that.

This is related to #1860 where @vlukashov specifically mentioned:
> The position for the inlined script should be right after the Flow bootstrap inline script block

**Comment by pleku** [comment]
As html imports are not going to be supported by the browsers and not used by default since 14, it makes no sense to invest into trying to influence the ordering of js/html imports. 
Individual js imports are imported in the correct order already and covered by tests.

Closing as wontfix
