### ISSUE TITLE
Rename @ClientDelegate to something which tells what it does

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#2249]
The javadoc says
`Publishes the annotated method so it can be invoked from the client side using the notation <code>this.$server.method()</code> in template methods`

so how about a name that says it is published so it can be invoked from the client side? 
Like `@PublishToJS` or similar?

**Comment by pleku** [comment]
`@ClientSide`
`@ClientSideMethod`
`@ClientSideAvailable`
`@ClientMethod`
`@PublishToClient`
`@PublishToClientSide`
`@CallableFromClient`
`@AvailableOnClientSide`

**Comment by pleku** [comment]
`@ClientCallable` won the popular vote and the lottery. Don't forget to update the demos(?), documentation.
