### ISSUE TITLE
When generating a component, I don't want to have duplicate methods (from generation and mixin both)

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#2252]
Open `GeneratedVaadinTextField` see two methods with the same implementation and almost the same name: `isReadonly` and `isReadOnly`.
I want to have a single method for this.

**Comment by asashour** [comment]
I believe this is fixed, `GeneratedVaadinTextField` doesn't currently have duplicate methods.

**Comment by ZheSun88** [comment]
not valid any more, reopen if it is necessary.
