### ISSUE TITLE
PasswordField is incompatible with TextField

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2306]
`PasswordField`  and `TextField` are two totally unrelated components.

But they have a lot of common methods (like `setPlaceholder` ).

Common methods have to be extracted to the separate common mixin which should be implemented by both of them.

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-text-field-flow #7](https://github.com/vaadin/vaadin-text-field-flow/issues/7) via [**ZenHub**](https://www.zenhub.com/)
