### ISSUE TITLE
We are lacking Component::getData/setData methods

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2307]
FW8 has usable `setData`/`getData`  methods.

We should introduce them into Flow `Component` class.

**Comment by Legioth** [comment]
Reopening since the PR doesn't fully cover the same case as in this issue.

**Comment by mstahv** [comment]
I think we should NOT have this kind of functionality. Extending classes is not inconvenient for Java developers. I have seen these methods to be used in apps using previous Vaadin versions, but I always take that as a code smell. This just adds obsolete complexity to our components/utils and guides our users to bad development habits.

**Comment by Legioth** [comment]
Let's close this one and reopen if anyone has a use case.
