### ISSUE TITLE
Template in template is broken after detach/attach

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2316]
See #2314.

The issue appears after the template which contains `@Id` injected children is detached and attached again.

The logic which introspects the client side for `id` and associates a node on the server side is executed only once (see  the TemplateInitializer::attachExistingElementById  method).
When the template is detached and attached again this logic is not executed anymore.
Instead the shadow root virtual children is introspected on the client side and based on `id` attributes the nodes are associated with the client side elements.

The similar situation is for template in templates.
There is the method `TemplateInitializer::doRequestAttachCustomElement` which does similar thing but it uses an indices path to identify the client-side element.

But I don't see any client-side logic which is executed for template in template once the parent template is reattached (there is no any `id` in this case and `path` is not stored anywhere. So it's not possible to identify client side element for the child template).

I'm not 100% sure but it should be broken in the same way as #2314. Except that it will require more complicated fix.

So what should be done:
- check that it's really broken. Use the test similar to IT test provided as a fix for #2314.
- fix it if it's broken.

**Comment by pleku** [comment]
Closing as nobody has run into this issue in several years. If it would be important, I would expect it to manifest and bother users.
