### ISSUE TITLE
Change reverse getters/setters to straight getters/setters

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#2329]
Components should not have `setDisabled(boolean notEnabled)`. The only reason it is that reversed way in the DOM is that the default value is `disabled=false`, i.e. `enabled`. In Java, there should always be the logical version `setEnabled(enabled)` and nothing else.

**Comment by asashour** [comment]
When thinking with Java , one would use `setEnabled`, but on remembering HTML attributes, then `setDisabled`.

I am wondering if having both `setEnabled/isEnabled` and `setDisabled/isDisabled`, would add a value by allowing the user to simply choose.

**Comment by pleku** [comment]
Will be handled by https://github.com/vaadin/flow/issues/3423
