### ISSUE TITLE
Consider replacing logging with slf4j

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#2331]
For Vaadin Framework 7, the decision was to go with java.util.logging as it was always available in all environments. If my memory serves me right, the incompatibility problems were mainly related to being able to make one war which would work on all servers and some old JBoss 4 caused problems. Times change and right now it seems Flow already use some libraries which directly or indirectly use slf4j.
```
com.vaadin:flow-server:jar:0.1-SNAPSHOT:compile
+- com.helger:ph-css:jar:4.1.3:compile
|  \- com.helger:ph-commons:jar:6.2.4:compile
|     \- org.slf4j:slf4j-api:jar:1.7.12:compile
```
```
com.vaadin:flow-push:jar:0.1-SNAPSHOT:compile
\- com.vaadin.external.atmosphere:atmosphere-runtime:jar:2.4.5.vaadin2:compile
   \- com.vaadin.external.slf4j:vaadin-slf4j-jdk14:jar:1.6.1:compile
```

If the logging was changed to be based on slf4j instead, then most of the customizations done to Atmosphere could also be removed

**Comment by SomeoneToIgnore** [comment]
Duplicates https://github.com/vaadin/flow/issues/2799
