### ISSUE TITLE
Race condition with ServerRpcQueue flags

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#2337]
`ServerRpcQueue` uses two boolean flags, `flushPending` and `flushScheduled` for determining when and how to send messages. There seems to be a race condition that in some cases a message to be enqueued but it won't be sent until the next time some other message also gets enqueued.

Moving `flushPending = true;` before the `if` in `ServerRpcQueue.flush()` seemed to fix this issue, but it's not certain that it's the right fix.

This was originally discovered when investigating #2245, but the final fix also changed some other things that also avoided this issue.

There's also a similar problem in Bakery, but it's again hard to extract it to a simple test case since there are multiple complex pieces involved. In the Bakery case, the problem has been worked around by wrapping the action that enqueues the RPC with `setTimeout(0)`.

We should reason around how those two flags are being used to come up with an explanation for how messages can remain stuck in the queue, and then based on that figure out how to build a simpler test case and fix the actual issue.

**Comment by denis-anisimov** [comment]
Artur made a good analysis of the issue.
There is the order of the steps to "reproduce".
I agree that clear should cancel the scheduled flush.
