### ISSUE TITLE
Router BeforeLeaveListener and BeforeEnterListener

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2353]
Add a `BeforeLeaveListener` that is only triggered for instances that are about to be detached. This is triggered also for navigation targets that will be reused. 

```java
public class SignupForm extends Div implements BeforeLeaveListener {
  @Override
  public void beforeLeave(BeforeNavigationEvent event) {
    if (this.hasChanges()) {
      ContinueNavigationAction action = event.postpone();
      ConfirmDialog.build(CONFIRM_MESSAGE)
        .ifAccept(e -> action.proceed()).show();
    }
  }
}
```

Similarly, trigger `BeforeEnterListener` for instances that are about to be attached. Also applies for navigation targets that are reused with new parameters. The method name is `beforeEnter(BeforeNavigationEvent event)`.

The listeners are automatically registered, similarly to `BeforeNavigationListener`and `AfterNavigationListener`s, as introduced in #2352.

Should also add a mention to the document about this. Update the demo to use this instead of `BeforeNavigationListener` when it is used only for attach.

Waits for #2352, since these listeners need to be automatically registered/unregistered for any component being attached/detached.

**Comment by torok-peter** [comment]
Based on discussion with Leif,
* there should be no relationship between `BeforeNavigationListener`, `BeforeLeaveListener` and `BeforeEnterListener`
* call order should be leave -> navigation -> enter

See original @ https://vaadin.slack.com/archives/C6RAXJATF/p1507787344000133?thread_ts=1507733310.000517&cid=C6RAXJATF
