### ISSUE TITLE
Support for Map model property type

### ISSUE THREAD

**Issue by ghost** [vaadin/flow#2391]
As a Java developer, I want to set a `Map<Number|Boolean|String, Number|Boolean|String|Bean>` property type so that I can easily have an object property on the client-side with arbitrary key/value pairs. For example:
```
{
  "someKey": someValue,
  "someOtherKey": someOtherValue
  ...
}
```

The current workaround for this limitation is to manually copy the `Map` into a `JsonObject` and set this via `getElement().setPropertyJson(name, jsonObject)`

Conversation: https://vaadin.slack.com/archives/C6RAXJATF/p1504876959000295

**Comment by mshabarov** [comment]
Implemented in https://github.com/vaadin/flow/issues/7308.
