### ISSUE TITLE
Vertical and HorizontalLayout are missing margin API

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow#2448]
The margin API is quite convenient in many cases where the developer just wants a margin and nothing else; having a stylesheet is usually overkill.

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-ordered-layout-flow #1](https://github.com/vaadin/vaadin-ordered-layout-flow/issues/1) via [**ZenHub**](https://www.zenhub.com/)
