### ISSUE TITLE
Composite<GeneratedPaperDialog> does not import HTML template automatically

### ISSUE THREAD

**Issue by torok-peter** [vaadin/flow#2454]
In freestarter-flow, when using a `Composite<GeneratedPaperDialog>` within another `Composite<GeneratedPaperDialog>`, the paper-dialog template is not automatically imported.
Symptoms:
* when added, the dialog contents appear directly in the parent view
* in the DOM, the dialog contains no `#shadow-root`
* when trying to open it, a type error occurs: `$0.open is not a function`

Quick fix is to manually `@HtmlImport` the needed template. This is now applied for the `ReviewForm`, `CategoryForm` and `ConfirmationDialog` classes of this project. By removing the annotations, the error is reproducible. See https://github.com/vaadin/free-starter-flow/issues/67 for some more details.

**Comment by haiwan** [comment]
Any update on this ticket? I would vote for this one to be fixed if I can.
