### ISSUE TITLE
CheckBox fails when value is set to 'true' on server side

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow#2459]
even though the value is sent as true to the client, the client ignores this, sets the value to false, and produces an RPC call. To reproduce:

```
final Checkbox cb = new Checkbox("asd");
cb.setValue(true);
cb.addValueChangeListener(e -> System.out.println("asdad"));
add(cb);
```

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-checkbox-flow #3](https://github.com/vaadin/vaadin-checkbox-flow/issues/3) via [**ZenHub**](https://www.zenhub.com/)
