### ISSUE TITLE
When transpiling frontend files with polymer-cli, I want to be able to specify destination directory

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#2462]
Currently polymer-cli produces transpiled and minified files in the directory with `polymer.json` file only and there is no way to override this.

This is uncomfortable, since we have to exclude an extra folder in `.gitignore` and tweak maven-war-plugin to ignore it.

`polymer-build` may be the way to deal with it: https://www.polymer-project.org/2.0/toolbox/build-for-production#use-polymer-build

**Comment by pleku** [comment]
Not relevant anymore with `flow-maven-plugin`
