### ISSUE TITLE
Correct data providers documentation

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2464]
Data providers documentation has been created along with Grid component.

But it refers to listing components. This concept simply just doesn't exist.
The documentation has been changed so that there is no any mention of Java listing component classes.
But at the moment we have only one "listing component" . It's `Grid`.
The original documentation has a lot of references to `ComboBox`.
Some of the examples have been removed because they are not applicable at the moment.

So all examples in the doc is about `Grid` which is bad.

Once `ComboBox` is implemented as an `AbstractListing` component the documentation should be corrected to match  https://github.com/vaadin/framework/blob/master/documentation/datamodel/datamodel-providers.asciidoc.

**Comment by pleku** [comment]
Since `ComboBox` is not lazy loading between client and server, not sure what documentation should be exactly added, but would make sense to go through the parts and see if anything is missing.

**Comment by ahie** [comment]
Not exactly sure what should be done with this ticket. The term _listing component_ is defined in the beginning of the chapter as follows:

> Listing components display one or several properties from a list of items

which doesn't directly relate to any implementation specific detail about the components. Furthermore, `AbstractListing` is currently not part of any module we provide for flow.

What is unclear in that definition though is how listing components relate to data providers, and basically the whole tutorial is about listing components that use data providers to fetch their data. So would it be enough to clarify the definition of listing components to mean components that have a data provider (i.e. implement `HasDataProvider`)?

**Comment by denis-anisimov** [comment]
You may ignore the term `listing` here. It's not about listings.

The ticket is about full features documentation.

In short : FW8 documentation should match the Flow documentation.
At the moment it doesn't.
It happens because we don't have enough (*_listing_*) component which can be used to demo all `DataProvider` features. I'm not sure that we have them at the moment still.

Please see the ticket description. It refers to https://github.com/vaadin/framework/blob/master/documentation/datamodel/datamodel-providers.asciidoc.

This document should be as much close to the Flow documentation as possible.
If you compare it then I will see that it doesn't.

At the moment of migration the `DataProviders` docs there was only one component which worked with `DataProvider` at all. It was `Grid`.

As a result a number of examples from the referenced tutorial have been totally removed.

They have to be moved back.

So generally one should go through all the `DataProvider` FW tutorial and check that everything is added back (may be with some corrections).

Specifically: `ComboBox` is a special case. It didn't support `DataProvider` at all when the tutorial has been created.
So there are no references to `ComboBox` at all.
They should be returned back.

Why?

Because as I said: it's a special case. There are some features in `DataProvider` which are designed specifically for `ComboBox` like components. E.g. filtering feature.
In the `Grid` case the filtering is coming externally.
In the `ComboBox` case the filtering is coming internally (filter is a part of the component itself). That's why there is a specific filtering API for `DataProvider`.
It's impossible to demonstrate it without `ComboBox` at all.

Also I replaced other `ComboBox` examples to use `Grid` instead.
They became a bit ugly.
Everything should be returned back (if it's possible now). May be it still not the correct time to do this.
I don't know. But it should be done at some point.

All `DataProvider` features should be described in the tutorial in very similar way as it's done in the https://github.com/vaadin/framework/blob/master/documentation/datamodel/datamodel-providers.asciidoc.

And this is not true at the moment.
