### ISSUE TITLE
When starting an application, I want it to work without providing `webcomponents-lite.js` myself

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#2466]
Currently our application, on start, searches for `webcomponents-lite.js` in its context.

If it is not found, our IT tests fail, but it's very hard to determine what exactly have caused the issues.

We need to:
1. (ideally) Make our application work normally without the polyfill
2. If 1. is not possible, throw an exception and refuse to start if the polyfill is not found
3. If 1. is not possible, should we provide our own, bundled polyfill?

**Comment by Artur-** [comment]
I'm pretty sure this works
