### ISSUE TITLE
Require explicit registration for template-in-template

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#2486]
Automatically initializing Java instances for any eligible tag name encountered in a template is problematic for several reasons:
1. It requires scanning the entire classpath to discover all `@Tag` annotations. This is especially problematic in Spring Boot.
2. It can cause existing code to start malfunctioning when a seemingly unrelated add-on is added to the classpath.
3. It makes it impossible to use specific tags in sub templates even though the custom element implementation is self-sustaining without a server-side Java implementation.
4. There is no way for the application developer to resolve conflicts if there are multiple components with the same `@Tag`, e.g. if one is the subclass of the other.
5. The registry is implemented as a static singleton, which might cause problems with some special classloader setups, e.g. as encountered with Spring Boot DevTools.

All these issues would be resolved if a `PolymerTemplate` would have to explicitly declare which component classes should be considered for automatic instantiation. There is a small risk of discoverability issues with requiring an explicit declaration, but it will hopefully outweigh the drawbacks with automatic discovery.

**Comment by denis-anisimov** [comment]
See PR #2654 and its issue : #2595.
It implements custom component scanning for Spring Boot application.

If this ticket then the functionality in the mentioned PR should be removed/modified.
