### ISSUE TITLE
Remove AngularTemplate from flow

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2492]
The old Router classes and AngularTemplate server side classes should be moved from `flow-server` to another module `flow-server-legacy` or `flow-legacy-server` (?) while keeping the same package names. Everything inside this package should already be deprecated.

This is for keeping demos and the website project up and running, but to not have outdated stuff in flow artifacts.

**Comment by caalador** [comment]
Updated ticket to be only for AngularTemplate and created a new one for the old router #2594
