### ISSUE TITLE
Updates to the same property on the client side should only transmit the final value to the server within a single round trip

### ISSUE THREAD

**Issue by ahie** [vaadin/flow#2497]
Currently multiple updates to the same property value all queue an `mSync` RPC to be sent to the server. Only the last sync is relevant from the server's point of view.

This behavior can be seen in the `PolymerPropertyMutationInObserver` test, which sends the following xhr to the server:

```
{"csrfToken":"12cffc9d-0aa3-4b13-90c7-e346c2d8a5fe","rpc":[{"type":"mSync","node":5,"feature":1,"property":"text","value":"mutateds"},{"type":"mSync","node":5,"feature":1,"property":"text","value":"mutated"}],"syncId":1,"clientId":1}
```

Once this issue is resolved, the xhr would only contain the last value:

{"csrfToken":"12cffc9d-0aa3-4b13-90c7-e346c2d8a5fe","rpc":[{"type":"mSync","node":5,"feature":1,"property":"text","value":"mutated"}],"syncId":1,"clientId":1}
```

**Comment by pleku** [comment]
I don't think this is relevant anymore has one can configure the cadence of the update events from client->server with debouncing and timeouts.
