### ISSUE TITLE
Support Grid's million pixel scrolling

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#2501]
`<vaadin-grid>` adds its own virtual scrolling on top of the API that is carried over from `<iron-list>`. This means that the `_virtualStart` and `_virtualEnd` variables by themselves are not reliable when scrolling beyond a certain threshold, but should additionally also be offset by `_vidxOffset`. This variable is initially 0, but will have non-zero values when scrolled far enough to risk triggering overflows in the `scrollTop` property that e.g. `_virtualStart` is based on.

**Comment by pleku** [comment]
@Legioth please clarify what this should achieve ? Removal of `size()` query from the Lazy DataProviders ?

**Comment by Legioth** [comment]
The terminology here is slightly confusing. Making `size()` optional is "infinite" scrolling, whereas the feature here is just scrolling beyond limits natively supported by the DOM.

The Grid element works around limitations to the maximum supported `scrollTop` value in different browsers by introducing a "virtual" scrollTop, reseting the actual DOM property to a value within the acceptable range and manually managing the scrollbar to make it look like the user is really scrolled somewhere else. Once this happens, `_virtualStart` and `_virtualEnd` will no longer on their own contain the right values, but in addition the `_vidxOffset` property also needs to be taken into account.

**Comment by pekam** [comment]
Issue moved to [vaadin/vaadin-grid-flow #14](https://github.com/vaadin/vaadin-grid-flow/issues/14) via [**ZenHub**](https://www.zenhub.com/)
