### ISSUE TITLE
Spring Add-on Beta

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2529]
- Works with Spring Boot
- Works with Router
- UIScope
  - SectionScope (maybe)
- Starters for Flow & Spring
  - Beverage Buddy App Starter for Flow and Spring
     - Basic integration, no Spring Data used or in-memory DB
  - Skeleton Starter for Flow and Spring
- Documentation and Tutorials for the add-on features and Starters
- DX validation

Spring security support is currently out-of-scope for Beta.

**Comment by heruan** [comment]
> Spring security support is currently out-of-scope for Beta.

Does this mean no declarative/annotation-based security on route targets will be supported in beta? 

Currently I'm working around this with ANT matchers in Spring's `WebSecurityConfigurerAdapter`, but it would be useful to know if a declarative approach will be available after beta.

**Comment by Legioth** [comment]
Even without any Spring Security integration, it should be possible to integrate your own annotation based access checks with a custom `BeforeNavigationObserver`.
