### ISSUE TITLE
If not setting the item-type for ComboBox, addValueChangeListener causes a compilation error.

### ISSUE THREAD

**Issue by pekam** [vaadin/flow#2538]
```
ComboBox comboBox = new ComboBox();
comboBox.addValueChangeListener(event -> {
    System.out.println("value changed");
});
```
Causes:
```
Compilation failure
An unknown compilation problem occurred
```
This happened in a DX testing session, so it will happen for users in the future as well.

Assigning the type parameter for the combobox fixes the issue, but that is hard to tell based on the uninformative error message.

Also Eclipse shows only a yellow warning about using the combobox without the type parameter.

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-combo-box-flow #3](https://github.com/vaadin/vaadin-combo-box-flow/issues/3) via [**ZenHub**](https://www.zenhub.com/)
