### ISSUE TITLE
Combobox setValue not working when combobox not displayed

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/flow#2547]
Vaadin version: 10.0.0.alpha2

1. When initializing template, setValue for combobox does not set any value. (set Items working well, though)
2. onAttach too.
3. only after combo is displayed on screen setValue is working ok.

Check the example: only from sayHello method setValue method really sets the value (with binder, and without)

https://github.com/vaadin/flow-demo/commit/8012ead3ee3f3d2f7c3ba89553bd7820639a829f

**Comment by gilberto-torrezan** [comment]
Blocked by https://github.com/vaadin/vaadin-combo-box/issues/554

**Comment by pleku** [comment]
The issue has been fixed and pending release for the element https://github.com/vaadin/vaadin-combo-box/issues/554

**Comment by johannesh2** [comment]
Any news?
