### ISSUE TITLE
TextField.focus() doesn't actually focus the field, it just visually looks focused

### ISSUE THREAD

**Issue by torok-peter** [vaadin/flow#2548]
Originating from one of Jouni's PR comments in free-starter-flow @ https://github.com/vaadin/free-starter-flow/pull/98.

It may be a Flow bug, or a vaadin-text-field bug - further investigation is needed.

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-text-field-flow #6](https://github.com/vaadin/vaadin-text-field-flow/issues/6) via [**ZenHub**](https://www.zenhub.com/)
