### ISSUE TITLE
WebJarServer claims to be serializable even though it isn't

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#2552]
`WebJarServer` implements `Serializable` and has problematic fields marked as `transient`, but a deserialized instance will not work because the `transient` fields will be `null` at that point.

**Comment by denis-anisimov** [comment]
The issue is not valid anymore.
`WebJarServer` has been significantly rewritten and there are no anymore transient fields or references to classes that has such fields.

So the resolution is : works for me.
