### ISSUE TITLE
Router throws unhandled IllegalArgumentException for routes containing ".."

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#2553]
Steps to reproduce: http://flow.app.fi/demo-static-menu-router-1.0.0.alpha2/..elements/

Expected behaviour: 404 page or empty page (like http://flow.app.fi/demo-static-menu-router-1.0.0.alpha2/blablabla/)
Observed behaviour:

```
Exception

javax.servlet.ServletException: com.vaadin.server.ServiceException: java.lang.IllegalArgumentException: Relative path cannot contain .. segments
	com.vaadin.server.VaadinServlet.service(VaadinServlet.java:296)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Root Cause

com.vaadin.server.ServiceException: java.lang.IllegalArgumentException: Relative path cannot contain .. segments
	com.vaadin.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1504)
	com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1467)
	com.vaadin.server.VaadinServlet.service(VaadinServlet.java:294)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Root Cause

java.lang.IllegalArgumentException: Relative path cannot contain .. segments
	com.vaadin.router.Location.verifyRelativePath(Location.java:317)
	com.vaadin.router.Location.parsePath(Location.java:276)
	com.vaadin.router.Location.<init>(Location.java:71)
	com.vaadin.router.Router.initializeUI(Router.java:85)
	com.vaadin.ui.UI.doInit(UI.java:194)
	com.vaadin.server.BootstrapHandler.createAndInitUI(BootstrapHandler.java:770)
	com.vaadin.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:246)
	com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1455)
	com.vaadin.server.VaadinServlet.service(VaadinServlet.java:294)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
```

Note: technically speaking, `..elements` does not contain `..` segment. It's not a segment ;)

**Comment by caalador** [comment]
This should be fixed by #2346

**Comment by fluorumlabs** [comment]
Will this also fix `java.lang.IllegalArgumentException: Location string can not contain query parameters in this constructor`? Can be reproduced if one add `%3Fblablabla` to the url. 

Note: works with `?blablabla`.

**Comment by caalador** [comment]
Well it will show the error view for that as I don't think we have any support for URL Encoded Characters nor did I find a ticket about supporting those.

**Comment by paulroemer** [comment]
Still valid: http://flow.app.fi/demo-dynamic-menu-1.2-SNAPSHOT/category../3 but with a different exeception.

**Comment by paulroemer** [comment]
Another example: https://vaadin.com/foo%3Fbar will throw an IllegalArgumentException

**Comment by caalador** [comment]
For the first: `// the actual part that we do not support is '../' so this shouldn't catch 'el..ement' nor '..element'`

The second one is for another ticket and I would need to know which version is it for.

Also as this has been closed almost a year ago it would well have warranted a new ticket for the correct version tested.

**Comment by Legioth** [comment]
A fix has already been released on one Flow version for this ticket. Please create separate tickets for any upcoming fixes so that it will be easier to keep track of what has been included in which version, and why.
