### ISSUE TITLE
`PasswordField#isPasswordVisible` returns `false` always

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#2558]
Current `vaadin-text-field` behaves in a special way: reveal password button works only when the component is focused, hiding the password again if the focus is lost.

The property that shows if a password is visible is `passwordVisible`.
Additional problem here is that there is no way of getting an event for this property change.
This did not work:
```java
getElement().synchronizeProperty("passwordVisible", "password-visible-changed");
getElement().addPropertyChangeListener("passwordVisible",
                event -> message.setText(
                        updateMessageText(passwordField.isPasswordVisible())));
```
trying `password-visible` did not work neither.

Example: branch with the bug: https://github.com/vaadin/flow/tree/kb/rework-password-field-demo

* launch jetty for `demo-flow-components` module
* open http://localhost:8080/vaadin-password-field
* select password field component in developer tools
* click on an eye button (show/hide password) and see that web component gets `password-visible` property toggled
* see no server component updates

In my opinion, either the method should be removed or the property should be updated on a server side by default.

**Comment by denis-anisimov** [comment]
Currently there is no public method `isPasswordVisible`.
There is only `protected isPasswordVisibleBoolean` in `GeneratedVaadinPasswordField`.
So this can be considered as solved.

There is an open question: how to make `passwordVisible` property synchronized.
I would say it's impossible (and may be intentionally done in the web component).
But why then our component generator generates a getter for the property which cannot be synced ?
Also the property is read only and there is no setter for it.
I would say that component generator logic needs to be corrected.

**Comment by pleku** [comment]
Since the web component already by default hides the password after the focus is lost, then I don't think there is a use case for needing this in the server side.
