### ISSUE TITLE
Add a gitter badge to Readmes for flow, skeleton-starter-flow and beverage-starter-flow

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2566]
The channel to link to is `vaadin-flow/Lobby`

**Comment by ZheSun88** [comment]
done
flow: https://github.com/vaadin/flow/blob/master/README.md
beverage-starter-flow: https://github.com/vaadin/beverage-starter-flow/blob/master/README.md
skeleton-starter-flow: https://github.com/vaadin/skeleton-starter-flow/blob/master/README.md
