### ISSUE TITLE
Router initialization should work with Spring Boot application

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2567]
Router is initialized correctly when the application is packaged and deployed as a WAR.
But it doesn't work when it's run as a Spring boot application.

It should work correctly in both cases.

It's primarily about `RouteRegistryInitializer`. But it might be some other thing should be done as well.

As a result Router should work with Spring in the same way as without Spring.
It means that no scopes/autowiring/other Spring features are considered here at all.
Router should just work inside Spring boot  app (ignore anything related to managed beans, injections).

**Comment by iatomic** [comment]
my classes have @Route("xxxx") etc defined...I am still getting thise errors when running in spring boot....any ideas?

**Comment by denis-anisimov** [comment]
Which errors you are referring to?

If routes don't work in Spring boot then it might be because they are defined in the separate package (other than your application package).
See `@EnableVaadin` annotation.

A snippet from the javadoc:

```
 Use this annotation in your Spring Boot application to scan the packages with
 * Vaadin types that should be discovered at startup (e.g. routes
 * via @{@link Route} annotation).
```

It's worth to create a ticket and provide a full information with a proper description.
