### ISSUE TITLE
Page is missing getTitle method

### ISSUE THREAD

**Issue by samie** [vaadin/flow#2569]
In my application I need to take the current page title and use it as description in a action button related to that page. Trying to do that with: `String myTitle = UI.getCurrent().getPage().getTitle();`

This should be symmetrical to `UI.getCurrent().getPage().setTitle(myTitle);`

**Comment by pleku** [comment]
Would be relatively straight forward to add this there, I can't recall why we have not done so yet.
The title might of course be changed from the client side too, thus we should note in this getter that _It might not be up to date_.

**Comment by samie** [comment]
Isn't the value lazily reflected from the client-side also? I.e. on next user-request title is updated also on server if it has been changed. Practically at least that should be enough for anything, since in addition to setter, the user interactions are the logic-points where it might be needed.

**Comment by Legioth** [comment]
The browser doesn't fire any event when the title is changed. In order to reflect the latest title to the server, we would have to check for changes whenever we are about to send something else to the server. I don't think we want to go that route, so the suggestion that `Page.getTitle()` return the value most recently set on the server seems good enough to me.

**Comment by samie** [comment]
I see. Would it still possible to publish own title method/property on the client-side to keep it possible to build applications that change title on client-side and use it in server-side logic?

**Comment by Legioth** [comment]
> Would it still possible to publish own title method/property on the client-side

That might be great for some advanced use cases, but I think that should be treated as a separate ticket with a lower priority than then other things mentioned in this ticket.

**Comment by pleku** [comment]
The only way this would make sense to me is to rename the method to something that makes it clear that this value does not necessarily match whatever is on client side. Thus the name would not be `getTitle` but `getLastKnownTitle` or whatever..

For the use case described here, I think there are other possible ways of acquiring the currently open _application state_ or whatever should be described in the button, not necessarily the page title.

Closing this as won't fix
