### ISSUE TITLE
Consider Navigation target (section) Spring scope

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2572]
Navigation uses section/navigation target/view scope.

It's not exactly clear how this scope should work.
Sections (navigation targets) are components that are activated during navigation via router.
One of the question that needs to be solved is: leaf navigation target components may have hierarchy. It's not clear should the scope be the same for the same navigation target component but for different hierarchical path.

Also what should happen if this scope is used for some non-leaf hierarchy component (parent layout).

All those questions should be solved. Written down here as a task.
Then it needs to be implemented if it's feasible.

**Comment by Legioth** [comment]
Slightly related: there's currently an open PR for the CDI add-on for FW8 that makes it possible to choose which events should cause the view scope to be recreated. https://github.com/vaadin/cdi/pull/212.

**Comment by pleku** [comment]
Deprioritized for now.

**Comment by Legioth** [comment]
Closed in favour of #3755 which contains more details.
