### ISSUE TITLE
Create a new repository and a basic project structure for Spring tutorial for Flow and Spring

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2573]
This task includes only:
- a new Git repository (choose a name and request Service desk to create the repo inside `vaadin` org).
- a basic project structure: `pom.xml` , initial java class and resources that should work as a Spring boot application (it should be possible to run it as a war as well). It should be Vaadin Flow application based on existing Spring support. It should show e.g. just a label.
- nothing else should be done here (no any logic/classes related to the original Spring tutorial).

**Comment by denis-anisimov** [comment]
Awaits Spring Flow integration add-on.

**Comment by denis-anisimov** [comment]
Any news on this, @pleku ?
Does it make sense to make it with Spring (as discussed on planning meeting)?
There are not that many tasks in Sprint backlog. 
It will be ready to be taken soon.

**Comment by pleku** [comment]
Sorry, missed the email notification. We will probably do instead something like `https://github.com/vaadin/spring-tutorial/tree/master/src/main/java/org/vaadin/spring/tutorial` since Beverage Buddy cannot really highlight Spring integration features that well.

**Comment by denis-anisimov** [comment]
The new repo name is : flow-spring-tutorial.
