### ISSUE TITLE
Make a DX test plan for Spring add-on

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2577]
Create a number of test cases to use Spring add-on.

The result should be a Google document with a number of tasks to do for a "tester".
Different aspects of Spring integration should be tested (ideally all of them).

Should be done after Spring integration.

**Comment by pleku** [comment]
Everything that is covered in our Spring Tutorials, should be DX tested. It is suppose to have all of the current features mentioned.
For the testing we provide our tutorial app, documentation and use the starter as a basis for that.

Scopes could be tested with following ways:
- `SessionScope` test with storing user login data from login view and reading it from main layout
- `UIScope` test with having a menu component that is added to the main layout, but is updated from another view
- `Autowired` enabling one or multiple views use the same `BackService` class
- Internationalization: show the internationalization documentation and spring property documentation and ask the tester to create their own localization provider ?
- Specifying servlet initializers for your Vaadin app - for modifying the meta data of your bootstrap page

**Comment by pleku** [comment]
The DX test project should use the latest release or snapshot version of Flow & Spring Add-on

**Comment by denis-anisimov** [comment]
https://docs.google.com/document/d/1DcFUVGsnTfyyhPXKxzKikgd7rMNKVkv7w4UisBF0LL0/edit#

The DX starter project (with pom file and structure but without any source code) is referenced from there and available here: https://drive.google.com/open?id=18WLUJo6NBV-MdNWywLJ3tNSMYhdVlWD8
