### ISSUE TITLE
Create documentation for Beverage Buddy App Starter for Flow and Spring

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2578]
Prerequisites:  Beverage Buddy App for Spring.

Make documentation for "Beverage Buddy App for Spring" project in the same way as
it's done for 
https://github.com/vaadin/beverage-starter-flow.

The documentation should reveal the Spring related aspects of using Flow.

Open question: should it also include _everything_ from the original project documentation? (duplicate Beverage Buddy App for Spring docs as well). So that it's a complete reference to Flow+Spring (so there is no need to go to the original app and see Flow only related things).
Or it should be only Spring aware documentation ?
Or it should contain references to the https://github.com/vaadin/beverage-starter-flow/tree/master/documentation somehow (how?).

**Comment by pleku** [comment]
For now it looks like we would not have a Spring version of Beverage Buddy, so this ticket blocked until there is a resolution on what is the example app for Flow & Spring features.

**Comment by pleku** [comment]
We have the vaadin/skeleton-starter-flow-spring and the vaadin/flow-spring-tutorial and the documentation on vaadin/flow for Flow & Spring, and this is enough examples and docs for now.
