### ISSUE TITLE
TextField.getValue() always return an empty string

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#2591]
I have cloned the https://github.com/vaadin/skeleton-starter-flow project, ran `mvn jetty:run` on it and modified the `MainView`'s constructor to look like this:

```java
    public MainView() {
        ExampleTemplate template = new ExampleTemplate();

        final TextField foo = new TextField("Foo");
        Button button =  new Button("Click me", event -> template.setValue("Clicked! " + foo.getValue()));
        add(button, template, foo);
    }
```

When I click the "Click me" button, I want the text I've entered into the "Foo" field to appear along the "Clicked! " string. Instead, it comes up empty.

**Comment by mvysny** [comment]
![screenshot_20171004_130843](https://user-images.githubusercontent.com/254091/31170561-2bdc90e8-a905-11e7-8788-6eb426dd749a.png)

**Comment by ZheSun88** [comment]
In fact, you can use this way to achieve your goal:
```java
foo.addValueChangeListener(event -> event.getValue());
button.addClickListener(event -> {
     template.setValue("Clicked! " + foo.getValue());
});
```
If i recall correctly, in your way, the `foo.getValue()` is getting the initial value from the textField which is empty and it doesn't fire an event until you add a listener to it.. :)

![image](https://user-images.githubusercontent.com/31067185/31179795-9b11acf8-a925-11e7-9f62-c47b461987e1.png)

**Comment by mvysny** [comment]
Ah, so the value is not transferred to the server side until the value change Listener is added :) that's why it worked in the beverage demo - it uses binder which internally sets the value Listener.

**Comment by ZheSun88** [comment]
yes, the usage maybe look not very straightforward as using `getValue()` directly, but change listener is used to sync the value from the client to server.

**Comment by pleku** [comment]
We should be making the `TextField` send the value to the server always on e.g. `blur` event when there has been a change, even if there is no `ValueChangeListener` applied.

Without that, we will confuse some users (like now), and that is always a bad thing. This is pretty similar what we had in FW 6 & 7 with the `immediate` property.

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-text-field-flow #4](https://github.com/vaadin/vaadin-text-field-flow/issues/4) via [**ZenHub**](https://www.zenhub.com/)
