### ISSUE TITLE
Custom component scanning should work in Spring Boot app

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2595]
#2567 and its PR #2593 makes possible to discover `@Route` annotations and enable Router functionality as a result.
It requires a custom autoconfigurator which scans the classpath for the `@Route` annotations.

The same issue is for `@Tag`  annotations to discover custom components.
So it should be possible to collect all custom components in the same way as `CustomElementRegistryInitializer` does in Spring Boot application (run as a Java application).
It works fine in WAR.

See details in mentioned issue and PR above.

**Comment by Legioth** [comment]
Might not be relevant if we do https://github.com/vaadin/flow/issues/2486 instead
