### ISSUE TITLE
Provide a modern look & feel for the "Session expired" notification

### ISSUE THREAD

**Issue by macjuan** [vaadin/flow#2597]
Currently the Flow apps show "Session expired" that looks really out of place, especially in our Bakery App Starter with nice Valo 2.0 designs. Could we please invest some small amount of time to design this to look good by default? 

What does out design dream think @jouni @emarc @tuomasnironen ?

@Peppe I noticed this in Bakery so cc'ing you as well.

**Comment by Peppe** [comment]
Thanks for the ping.

I absolutely dislike the popup. It looks ugly, and in many cases, it would be better if the dialog would just not be shown. For example, often it doesn't matter if a new session is created on the spot.

Take for example vaadin.com itself - it gets a huge red "session expired" if you leave it open. But almost all the links there are basic <a> links and it would not matter that I don't have a session there.

Another example - I go to the log-in screen of Bakery. If I leave it open, I will see after a while a session expired. As I don't really have a state yet, and I do a post of my credentials, it is completely irrelevant to me that there is a session. A new session looks completely identical to the old one.

In many cases, I would like to see the popup gone.

**Comment by macjuan** [comment]
I fully agree with @Peppe about Bakery log-in view - that's actually the place I noticed it and it was totally unexpected for me to even see it. End user does not understand that there is a state that might expire.

**Comment by jouni** [comment]
I’m very eager to design something better for this, but first I need to learn about the technical limitations we have, if it’s possible the disable these sometimes, and what are all the types of messages that can be displayed and in what situations.

**Comment by Peppe** [comment]
An idea ou

**Comment by Peppe** [comment]
An idea popped to my mind - can we delay the showing of the popup to the next server round trip? After that, if you just click on a link that doesn’t need a server visit, it will just work with a fresh session. If it needs to communicate back, then we show that the session is expired, save your info and refresh the browser. 

How does it sound?

**Comment by pleku** [comment]
Please also see #2058 since this is partly overlapping and duplicate to that. What we should note is:
- There is a behavior related to the session expiration. The desired behavior is not the same for all Apps.
- The dialogs and notifications should definitely also look nice.

This ticket can be about the visual look of the dialog(s), and #2058 about the behavior and customizing it.

**Comment by macjuan** [comment]
Duplicate of #2058
