### ISSUE TITLE
Create a new test module for Spring without Spring boot

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2600]
At the moment Spring boot is used to bootstrap a Flow application in two ways:
- as a Java Application (Spring boot application)
- as a deployable WAR application but it still is based on Spring Boot.

There should be a Spring boot free test module which should be a deployable WAR file.
It should work with Spring add-on as well (the way how it should work is not clear at the moment since the autoconfiguration won't be available there).

*NOTE* : we should keep `flow-test-spring-war` as is ( based on Spring boot) and add one more module which is Spring boot free. There are some common things in Spring Boot applications and some different (e.g. `@Route` components registration). And we still need to check that the code works in both cases with Spring boot.

**Comment by Legioth** [comment]
Sounds like it would be safest to have two different test projects for Spring, one with and one without Spring Boot.

**Comment by denis-anisimov** [comment]
I thought I've updated the title.
I would say we need 3 test modules for Spring:
- Spring Boot as Java application ( to check scanning of `@Tag`s, `@Route` and so on).
- Spring boot as a deployable WAR 
- Without Spring boot at all

There are already two of them created.
Spring boot free module is pending (that's the issue ). Should be created once common Spring add-on support Spring web app without Spring boot.

**Comment by Legioth** [comment]
Would it be possible to test both variations of Spring Boot from the same module by using different Maven targets or something like that? In that way, we wouldn't have to duplicate the code between two almost identical modules?

**Comment by denis-anisimov** [comment]
The code is not duplicated at all already.
Those two module are just entry points.
The UI classes and IT tests are in the one shared module https://github.com/vaadin/flow/tree/master/flow-tests/test-spring-common

**Comment by denis-anisimov** [comment]
Depends on #2628
