### ISSUE TITLE
Migrate Components to their own Repos and start using WebJars

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2602]
Each component in `flow-components` should be split to their own repos. Then they should be updated to start using WebJars instead of bower.json.

The name of the repository is `vaadin-<component-name>-flow`. The package name is the same as now, e.g. `com.vaadin.ui.<component-name>`.

The project structure should be a single module project where the `DemoUI` is in `src/test/java` and there is an additional `demo` profile which will build the `<component-name>-demo.jar` with the `DemoUI` and a have a dependency to the component. This package can be then used in a component sampler app. Both the component and demo `jar` will share the same version from the project.

**Comment by ZheSun88** [comment]
repos we need for this tickets

`vaadin-ordered-layout-flow`
`vaadin-check-box-flow` 
`vaadin-combo-box-flow`
`vaadin-date-picker-flow`
`vaadin-dialog-flow`
`vaadin-form-layout-flow`
`vaadin-split-layout-flow`
`vaadin-text-filed-flow`
`component-starter-flow`

what could be the name for this issue `Create a repository which has all the components as git submodules` #2620

**Comment by pleku** [comment]
```
vaadin-list-box-flow
vaadin-upload-flow
vaadin-tabs-flow
vaadin-dropmenu-menu-flow
vaadin-notification-flow
vaadin-radio-button-flow
vaadin-progress-bar-flow
```
