### ISSUE TITLE
Create a repository which has all the components as git submodules

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2620]

**Comment by Legioth** [comment]
What's the purpose of this repository?

**Comment by pleku** [comment]
The purpose is to be able to do one `git clone & git submodule init` and get all of the components and the component utils (e.g. testing / demo helpers) in your workspace.

**Comment by Legioth** [comment]
What's the purpose of that? (This starts to feel like a Five Whys exercise.)

**Comment by pleku** [comment]
To make it easier to do development for Flow and the components. You can always get the most up to date versions of each, or ones tagged e.g. for a specific platform version, without having to do the same stuff for each single repository. Or if a new component is added, you can easily get it since it is added as a new submodule here. Or other things, you can keep posting Whys but I don't think I will keep on answering
