### ISSUE TITLE
Migrate Vertical and HorizontalLayout to its own repository

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2623]
Repository name is according to the standard, `vaadin-ordered-layout-flow`.
Move the generated components and `VerticalLayout`, `HorizontalLayout` and `FlexLayout` to the repository. The `vaadin-button-flow` as an example of the project structure and needed configuration.

The version of the component is `1.0.0-SNAPSHOT`.

**Comment by pleku** [comment]
@ZheSun88 I don't consider this done until there is the demos in the same repository.

**Comment by ZheSun88** [comment]
oops. sorry.. one PR havent been merged yet..
