### ISSUE TITLE
Inconsistent Maven build behavior at Windows 10

### ISSUE THREAD

**Issue by szolo** [vaadin/flow#2648]
### Steps to reproduce:

1. Clone flow skeleton starter repo (https://github.com/vaadin/skeleton-starter-flow).
2. Add dependency: 

```xml
<dependency>
        <groupId>org.webjars.bower</groupId>
	<artifactId>github-com-polymerelements-paper-checkbox</artifactId>
	<version>2.0.1</version>
</dependency>
```
3. Execute `mvn clean package`.

### Actual behavior:
> Failed to execute goal on project skeleton: Could not resolve dependencies for project com.example:skeleton:war:1.0.0.alpha4: Failure to find org.webjars.bower:github-com-polymerelements-iron-flex-layout:jar:1.3.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

### Expected behavior:
Build execution should be successful.

### Notes:
It happens from command line, Eclipse and IntelliJ. I truly believe that this is connected with the fact that Windows isn't case insensitive for folder and file names.

This is how my **.m2** folder looks like:
![img](https://user-images.githubusercontent.com/3662957/31399000-7776161c-adf3-11e7-80c2-9e460e2693be.png)
You can notice that some dependencies contain strings in upper case - **PolymerElements** instead of **polymerelements**, despite the fact that all **pom** files use lower case all the time.

Interesting thing is that other dependencies except **github-com-polymerelements-iron-flex-layout** are found, even though they reside in a folder with upper case in name:
![img1](https://user-images.githubusercontent.com/3662957/31399336-a2cc7dbe-adf4-11e7-8d47-e6d1fed2e522.png)

Last thing: if I include external reference to **github-com-polymerelements-iron-flex-layout** dependency (not transitive) - everything would be ok. Upper case and lower case will be handled appropriately, depending on the specified **artifactId**. 

**Env:**

> Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T18:41:47+02:00)
> Maven home: D:\Soft\apache-maven-3.3.9-bin\apache-maven-3.3.9\bin\..
> Java version: 1.8.0_66, vendor: Oracle Corporation
> Java home: C:\Program Files\Java\jdk1.8.0_66\jre
> Default locale: en_US, platform encoding: Cp1252
> OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

**Comment by szolo** [comment]
@qtdzz do you have something to add?

**Comment by SomeoneToIgnore** [comment]
This is a "feature" of webjars creation.
The issue can be addressed to https://github.com/webjars/webjars
Unfortunately, all we can do is to create a documentation (which we'll do after integrate this PR: https://github.com/vaadin/flow/pull/2634)
