### ISSUE TITLE
HTML-related classes found in various packages

### ISSUE THREAD

**Issue by samie** [vaadin/flow#2652]
When importing classes, the many HTML-related class imports look inconsistent:

Classes are locates in `com.vaadin.ui`, `com.vaadin.ui.common` and `com.vaadin.ui.html`:
- https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/ui/common/HtmlContainer.java
- https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/ui/Html.java
- https://github.com/vaadin/flow/tree/master/flow-html-components/src/main/java/com/vaadin/ui/html

Would expect to find them all in` com.vaadin.ui.html` or use different class name to indicate that they are about different concept.

**Comment by Legioth** [comment]
Those are all slightly different, so I'm not sure how to clarify things.

* `HtmlContainer` is a utility class that is intended as a base class when creating other components.
* `Html` is related to the `Text` component, and they are therefore in the same package.
* `com.vaadin.ui.html` provides Java Component APIs for all of the most common HTML elements. This will be distributed (and maybe also versioned) as an optional module (even though it's included in e.g. the platform meta dependency).

**Comment by pleku** [comment]
I don't know what I would want to do with this at the moment, since there is reference documentation for the use cases related to Html Components and these classes have adequate javadocs. Let's see after wider adoption whether there are more issues with this.
