### ISSUE TITLE
Web Push support via service workers

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#2659]
I've just watched the [Introduction to Web Push](https://www.youtube.com/watch?v=0k0a0JWvagw) on Vaadin channel and the first thought was: that's great, I really hope Flow will include an easy API for that!

**Comment by Legioth** [comment]
This is not on our roadmap for 2017, but definitely a candidate for future development.

**Comment by pleku** [comment]
Superseded by https://github.com/vaadin/flow/issues/4747
