### ISSUE TITLE
Spring Flow IT tests are failing randomly.

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#2667]
Flow pull request CI builds on http://teamcity.vaadin.com/viewType.html?buildTypeId=Flow_FlowTests have no issues with Spring tests.

Flow snapshot builds on https://bender.vaadin.com/ are always failing with an error: https://bender.vaadin.com/viewType.html?buildTypeId=Flow_FlowSnapshots

If you run `mvn verify` locally in `flow-tests` Flow module, you may get the same error after multiple runs.

This error is very unstable, sometimes test fails in `test-spring-boot`, sometimes in `test-spring-war`.
Sometimes it's `RouteBasicIT`, sometimes it's `ScopesIT`, sometimes it's none (for local run, snapshots builds fail always at something).

The error is not shown in logs, all we have is IT test error (no element found) and an error screenshot (identical for all cases: https://bender.vaadin.com/repository/download/Flow_FlowSnapshots/2467:id/flow-tests/test-spring-boot/error-screenshots/testServletDeployed%5BANY_Chrome_%5D%28com.vaadin.flow.spring.ScopesIT%29.png) saying 

> Could not navigate to ""

We need to fix this problem.

**Comment by denis-anisimov** [comment]
This is a race condition.
`RouteRegistry` is initialized from the `ServletContainerInitializer` or `ServletContextInitializer` (in Spring).
They are execute in one thread which is out of any servlets/sessions and so on.

But routes are requested when the application handles servlet requests and it happens in servlet threads.
So there are a number of threads and it means that any class used as a storage for data during servlet context initialization should thread safe.
