### ISSUE TITLE
TestBench contributor license

### ISSUE THREAD

**Issue by pwilkin** [vaadin/flow#2668]
Currently, to contribute to Flow you need a TestBench license, however, the only free license there is a trial license that is valid for 30 days. IMO there should be a free "contributor" license whose terms specifically allow for using TestBench in Flow development (and possibly other Vaadin-related development). I'm personally quite interested in contributing to Vaadin, but unless my employer decides to purchase a ProTools subscription (which might or might not happen as it depends on the needs of our contractors), I can't really afford a private ProTools license just for contributing to Flow.

**Comment by SomeoneToIgnore** [comment]
Hi.

TestBench license is needed to run IT tests only, so you can freely contribute without it: you make a change, run unit tests locally (if you want to) and then just create the pull request.
Our CI will handle the rest and its build results are available for you without any credentials needed (you can login as guest here http://teamcity.vaadin.com/ and check it out yourself).

Would it be suitable for you?

**Comment by pwilkin** [comment]
Okay, so it's basically the same as it is now for Framework? 

Then maybe a good idea would be to update the contributor notes to point that out (i.e. that it's optional and that the tests will be automatically run for the pull requests).

**Comment by SomeoneToIgnore** [comment]
Yep, pretty much like it.

That’s a good point, will update it as soon as I can.
By the way, you can help us out and submit a pull request for it, if you want to.

**Comment by SomeoneToIgnore** [comment]
Have updated the documentation hence closing the ticket.
