### ISSUE TITLE
support Spring-managed beans to be injected as @Id components

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#2671]
When building an app with Flow and Spring, as a developer, I want to make Spring-managed beans out of my custom components (so that the components would have an easy access to other Spring-managed beans). After doing that I still want to use the `@Id` Flow feature to bind my custom spring-managed components to existing polymer template elements.

Example:
```java
@Route("dashboard")
@Tag("bakery-dashboard")
@HtmlImport("context://src/dashboard/bakery-dashboard.html")
public class DashboardView extends PolymerTemplate<PolymerTemplate.Model> {

  @Id("order-list")
  OrderList orderList;
}
```

```java
@Component
@Tag("order-list")
@HtmlImport("context://src/components/order-list.html")
public class OrderList extends PolymerTemplate<PolymerTemplate.Model> {

  @Autowired
  public OrderList(OrderService orderService) {
  }
}
```

**Comment by Legioth** [comment]
For supporting this, we should probably add something similar to `createRouteTarget` to `Instantiator` and update the `@Id` handling logic to delegate there instead of directly using reflection.

**Comment by denis-anisimov** [comment]
Exactly.
Just a new method in the `Instantiator`.
