### ISSUE TITLE
As a developer I want to use my own static fileserver to deliver content in a custom way

### ISSUE THREAD

**Issue by paulroemer** [vaadin/flow#2676]
Likely because of performance optimizations we implemented a custom fileserver that caches requests to `isStaticResourceRequest(HttpServletRequest request)`

With 0.1.22 this was possible as we could overwrite the protected method `VaadinServlet.createStaticFileServer()`. This method was removed in 2a8633ad616569d5ec57f2a5f44035fcf5c43143

I am not sure in which way it is related to the integration of webjars...

**Comment by Legioth** [comment]
Sorry for breaking this use case. Let's see what we can do about it.

> I am not sure in which way it is related to the integration of webjars...

It's called refactoring: we suddenly had to pieces of code that did almost the same thing, so we moved things around to make the things clearer.

**Comment by paulroemer** [comment]
Don't get me wrong. You made quite a lot changes in this commit and as I am missing knowledge about webjars, I have no idea to create some fix for that on my own.

So, it was more a "Sorry gyus, I cannot help you much but just report the issue".

**Comment by gilberto-torrezan** [comment]
There is still a need for this in the website. This could be achieved by adding an extension point to the `VaadinServlet` when creating a `StaticFileServer`.
