### ISSUE TITLE
Router: BeforeNavigationListener is confusing

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2683]
`BeforeNavigationListener` is the listener interface.
I would expect that I should add it to somewhere.

But in reality it can't be added explicitly.
It has to be implemented by a component. And then it's automatically "registered".
This is quite confusing if you don't know it a-priori. 

This should be emphasized in Javadocs, tutorial at least.

But also I would prefer to express it somehow via Java contract ( somehow via types). Not sure whether it's possible.

**Comment by pleku** [comment]
Documention should clarify this, no mention in e.g. https://github.com/vaadin/flow/blob/master/flow-documentation/routing/tutorial-routing-lifecycle.asciidoc

**Comment by caalador** [comment]
The document for BeforeNavigationEvent starts with:
`Any Component in the activating or deactivating navigation target chain will receive a BeforeNavigationEvent if they extend the BeforeNavigationListener interface.`

I guess there would be a need to add an own section for the Listener.

Also to note is that it's not registered, but found out by recursing the component tree.
