### ISSUE TITLE
Router: HasErrorParameter must not return 0.

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2684]
The `HasErrorParameter::setErrorParameter` should return some int value.
It's quite easy to return e.g. `0`.

Then something wrong happens with the router functionality.

So something should be done:
- either force the method return value limitation via API (it's not clean how).
- either do some runtime checks for the return value (e.g. it may not be negative and may be it should be above 200 ?)

Document carefully the return value restrictions.

**Comment by fluorumlabs** [comment]
Why don't use enum with HTTP status codes similar to `org.springframework.http.HttpStatus`?

**Comment by denis-anisimov** [comment]
That can be an option.
But there are too many of them.....
May be we can add some pre-existing library and use the enumeration from there.

**Comment by caalador** [comment]
There is the `javax.servlet.http.HttpServletResponse` that contains acceptable return value constants.
We can check the status code in the `ErrorStateRenderer` before returning and do what?
Should we log the problem and return the value ??? or should we throw with a exception explaining the problem?

**Comment by denis-anisimov** [comment]
I think we should throw an exception.
