### ISSUE TITLE
Rename methods dynamically added by gridConnector

### ISSUE THREAD

**Issue by ahie** [vaadin/flow#2697]
To avoid potential naming conflicts with other <vaadin-grid> methods and user extensions, all methods added by `gridConnector` should be scoped to `grid.$connector`. For example `grid.updateData` should be changed to `grid.$connector.updateData`.

**Comment by pleku** [comment]
Please also avoid using `var` and arrow functions to have it working on IE11 without transpiling.

**Comment by Legioth** [comment]
`var` is supported by IE11, as is the similar `let` keyword.
