### ISSUE TITLE
Grid enable user resizing columns

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2705]
```When showing a grid to users, I want the users to be able to resize columns, so that they can get the necessary data visible for them```

On `Column`, there should be a setter and getter for `resizable`. The default value is `false`.

Currently there is no event for the resizing, so no need to add that API for server side.

**Comment by gilberto-torrezan** [comment]
This ticket will introduce the `Column` class, that will be returned from the `addColumn(...)` method on Grid.

The Column class will host all the properties needed at the column level for the Grid, and will be the base for other tickets as well.
