### ISSUE TITLE
Provide API for freezing columns in the Grid

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#2708]
The Grid webcomponent already supports freezing columns. We just need the server-side API for that. The difference is that the server side API should specify the number of frozen columns (`int`) instead of providing a boolean for each column.

For instance, setting the the number of frozen columns to `2` would mean that the first 2 columns of the Grid would be frozen (even when the columns are hidden).

The default value for frozen columns is `0`.

See the demo about frozen columns on the webcomponent at: https://vaadin.com/elements/vaadin-grid/html-examples/grid-columns-demos

**Comment by Legioth** [comment]
Why should the server-side API be based on a different mode of operation than the Web Component's own API?

**Comment by jouni** [comment]
As Leif already said, do not implement this with the same API as in FW8 – follow the web component API. This applies to all of the API, not just this case. If you have concerns and would like to deviate, please discuss those before implementing. 

A number based approach for frozen columns creates problems/inconsistensies with column reordering, column hiding and column grouping.

Those were the reason why the frozen column API was revised in vaadin-grid v2.

**Comment by ahie** [comment]
@jouni this has already been taken into account in the implementation, but thank you for the clarification.

**Comment by jouni** [comment]
@ahie, great to hear!

I was late to comment, but I wanted to provide some more context to this discussion if someone from outside the team is wondering why we are changing the API.
