### ISSUE TITLE
SPIKE: investigate how the Grid Column Grouping could work

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2710]
See the top most demo in https://vaadin.com/elements/vaadin-grid/html-examples/grid-columns-demos. See the V8 Grid API for how the header & footer rows are added and merged.

The minimum is to make sure the it is possible:
1) Add more Header rows
2) Add more Footer rows
3) Be able to merge Header & Footer cells _when the Grid has not been yet rendered_ 

V8 Grid has an API also for default header/footer row, not sure if that concept matters with the web component.

For dynamically merging and splitting header/footer cells, you should verify if it can be done or not. We do have two options:
- not supporting that for now and throwing if doing dynamical changes
- refresh everything in the grid

*EDIT:* It is very unsure whether the V8 Grid column grouping way makes any sense anymore. Thus that is why this Spike exists,

**Comment by jouni** [comment]
Looking at https://github.com/vaadin/flow/pull/2828 it seems that’s exactly what you’re already doing 👍
