### ISSUE TITLE
Grid API to define a template for row details

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#2721]
"Item details" is a template that can be set at the Grid level. When the user clicks on a row, the details are shown for the item of the row.

The details row can contain anything - it is just a `<template>`.

The client demo is here: https://cdn.vaadin.com/vaadin-grid/4.0.0-alpha5/demo/#grid-row-details-demos

The Grid should have a new method to set the template renderer for the item details. Like this:

```
grid.setItemDetailsRenderer(TemplateRenderer.of("<div>My template</div>"));
```
It should support all the features present on the TemplateRenderers, such as property bindings and event handlers.

**Comment by pleku** [comment]
There should also be the API for opening and closing the details for a certain item.

The demo should preferably use `ComponentRenderers` for the details row.

**Comment by pleku** [comment]
@ahie so there is no API currently for setting the details for a certain item open/closed ? Why ? Similarly to what [FW 8](https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/Grid.java#L776) has.
