### ISSUE TITLE
STICKY: Initial setup for each new component repository

### ISSUE THREAD

**Issue by pekam** [vaadin/flow#2731]
1. Push the initial commit with the LICENSE and README files
2. Connect the repo to Reviewable by turning the switch in https://reviewable.io/repositories#
3. Copy the settings from https://github.com/vaadin/vaadin-button-flow/settings
    1. uncheck "Allow merge commits" (so that squash-merging is required)
    2. Protect `master`-branch:
        1. branches -> protected branches -> select `master`
        2. edit the protection settings to be the same as in `vaadin-button-flow` for example (require Reviewable, restrict pushing to flow-team, include admins...)
4. Enable CLA Assistant for the repository (make the repo public, before you do this)
    1. Enable repo from https://cla-assistant.io/
    2. Make a dummy PR for the repo, then you can edit `master` branch settings in github to have CLA Assistant as mandatory 
5. Don't forget to add README file when adding the component sources
   1. See other component repos for example

**Comment by SomeoneToIgnore** [comment]
Can be added here also: https://docs.google.com/document/d/1nW2FqH7k-s20uUNZ1pGoOrGp5cMA5_uZbJfh5IZRjYs/edit

**Comment by pleku** [comment]
Migrated to team wiki.
