### ISSUE TITLE
Add Contribution Guidelines to the repo

### ISSUE THREAD

**Issue by torok-peter** [vaadin/flow#2745]
FW8 is adding it right now, in https://github.com/vaadin/framework/pull/10083. We can mostly reuse that one.

**Comment by SomeoneToIgnore** [comment]
Would it make sense to edit an existing guide: https://github.com/vaadin/flow/blob/master/CONTRIBUTING.md instead?

**Comment by torok-peter** [comment]
Closed as invalid
