### ISSUE TITLE
Grid: add a way to select all the visible items in the UI (instead of all the items in the database)

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#2747]
When using the `SelectAllCheckboxVisivility.VISIBLE`, all the items from the DataProvider are selected when the user clicks on the checkbox. This can take a long time if the dataset is large enough.

The idea is to provide a mode where only the visible items in the UI are selected when the checkbox is pressed.

A use case for that can be seem here in GitHub - at the [issues page](https://github.com/vaadin/flow/issues) - when the user selects all the issues, only the visible ones are selected, and not all.

Related to #2739

**Comment by Legioth** [comment]
I'm worried about the UX implications. The example with GitHub issues works because that UI uses pagination. Applying the same semantics for the continuous scrolling used by Grid has the potential of being very confusing.

Any insights from @jouni?

**Comment by jouni** [comment]
I’ll echo what Leif said.

Instead of coming up with odd technical workarounds, I think we should just document these cases clearly, and instruct users to design/implement the most proper UI for their use case.

If they have a large dataset and want continuous scrolling, they should disable the built-in “select all” feature because it will slow down the UI and eat a lot of memory on the server.

If they have a large dataset and want select all, better use pagination, or solve the “select all” in a different way than actually creating an array in memory with all the items.

**Comment by jouni** [comment]
Also, @Legioth, have you discussed the selection API in more detail, if we should align the Java API more close to what the web component API is – e.g. not having any selection “modes”, but programmatic selection always available, and only making the end user UI behavior configurable with the selection column and custom event handlers?

**Comment by Legioth** [comment]
@jouni Having separate selection modes is still quite relevant for type safety reasons in Java.

**Comment by jouni** [comment]
Why? If the Grid only offers “always-on multi-select”, what type safety reasons are left? Honest question, I’m can’t wrap my head around all the different use cases and Java right now.

**Comment by gilberto-torrezan** [comment]
Ok, so suppose I want to use pagination and have a check box to select all the item from the page (and not all from the database). Is it possible to do with the current API?

**Comment by Legioth** [comment]
@jouni One simple example is whether a method like `getValue()` should return `Person` or `Collection<Person>`.

@gilberto-torrezan The most straightforward way of doing pagination is probably do manually fetch from the database and call `setItems` whenever the user uses the pagination controls. In that case, the select all checkbox would naturally select all the items of that page.

**Comment by jouni** [comment]
> One simple example is whether a method like getValue() should return Person or Collection<Person>.

That’s what I was referring to: if the grid is always in ”multi-select mode”, that would always return a collection. The web component has only a `selectedItems` property which is always an array.

**Comment by Legioth** [comment]
> if the grid is always in ”multi-select mode”, that would always return a collection

Always returning a `Collection` is inconvenient from a Java perspective, especially if using Grid as a fancy "list box" with `Binder`.

**Comment by jouni** [comment]
Right. That I can accept as an argument if there are no nice workarounds.

Are there any other alternatives than selection modes?
