### ISSUE TITLE
Create flow maven plugin for seamless production mode support

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#2750]
After #2749 spike is implemented, create a Maven plugin that replaces all required xml configuration.

Should be possible to be used instead of xml configuration in any project, should be configurable.
The documentation should be updated.

```
<groupId>com.vaadin</groupId>
<artifactId>flow-maven-plugin</artifactId>
```

**Comment by Legioth** [comment]
The production build support will have to collect files from at least these locations:
1) The application's own `src/main/webapp/fontend`
2) `META-INF/resources/frontend` in all jar files in the project
3) WebJars (flattened into `/bower_components/`)

**Comment by SomeoneToIgnore** [comment]
The PR: https://github.com/vaadin/flow-maven-plugin/pull/1
