### ISSUE TITLE
When creating a template model, I want to reuse global converters, so I don't have to add an annotation for every property or resort to using DTOs 

### ISSUE THREAD

**Issue by tulioag** [vaadin/flow#2752]
I have the following code:
```java
     public interface Model extends TemplateModel {
        @Convert(value = LongToStringConverter.class, path = "id")
        @Convert(value = StorefrontLocalDateConverter.class, path = "dueDate")
        @Convert(value = LocalTimeConverter.class, path = "dueTime")
        @Convert(value = OrderStateConverter.class, path = "state")
        @Convert(value = CurrencyFormatter.class, path = "items.product.price")
        void setItem(Order order);
}
```
I would like to reuse at least some of the converters. Some obvious ones are:

-  LongToStringConverter : Every entity has an id, so I basically have to add this to every mapping. If I want to add the id of related entities, I have to include it once for every entity.
-  LocalTimeConverter: It is a basic java type.
-  OrderStateConverter: It is an enumeration. I would like to have a generic converter that works with any enumeration.

For that, I would like to be able to register a converter globally. For instance, in the application initialization I could have a call like this:
```java
register(LongToStringConverter.class)
```
Then that converter would be applied for all Longs in the application.

**Comment by mshabarov** [comment]
No enhancements are planned for Polymer Templates.
