### ISSUE TITLE
Use pre-existing JSON library (Jackson, Gson, ...) instead of creating yet another object-to-json solution

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#2753]
Given that I have already existing JSON serialization scheme/annotations present on my objects, I would like to reuse those annotations/converter setup/... instead of writing yet another set of annotations on Models for Flow custom JSON-to-object converter (which even lacks basic converters like LongToString etc).

I should thus be able to tell Flow to use Jackson2 or GSON or other library, to convert model objects to JSONs.

It's arguably easiest to use GSON since it a) is small, b) easy, c) produces JsonElement which can be converted to gwt-elemental json tree and thus may be the best for performance reasons. However, if this is not required, then any JSON library could be pluggable, given that `element.setPropertyJson(String, String);` API is viable.

Perhaps there is a sound argument that an in-house object-to-JSON converter is needed; I would like to learn such argument.

**Comment by Legioth** [comment]
The main issue is that we store JSNO values in the session. This means that the native representation must be `Serializable`, which isn't true for e.g. Jackson or Gson.

Allowing pluggable conversion using any library and then copying over that into a serializable native representation might still be a good idea from a DX perspective, even though it would cause some runtime overhead.

**Comment by mvysny** [comment]
> The main issue is that we store JSNO values in the session. This means that the native representation must be `Serializable`, which isn't true for e.g. Jackson or Gson.

True. There's a bug report regarding this in Gson: https://github.com/google/gson/issues/485

**Comment by jhult** [comment]
This might relate to #8218.

**Comment by mshabarov** [comment]
Flow uses Jackson and GWT Elemental libraries: `jackson-core`/`jackson-databind` and `gwt-elemental` for mapping, parsing and binding objects to JSON.
