### ISSUE TITLE
Component Mixin test should be run on module which gets all of the Vaadin components

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2764]
Currently the test in run for `flow-components`, which is soon removed since the components are migrated to their own repositories. The test should be still run for every component we create. Options I can think of are
1. Publish the test in some test-helper run which would be a dependency for all of our components and contain some generic tests for all of our components.
2. Run the test in a integration test module in Flow which would get all of our published components, e.g. as a from the platform BOM (?)
3. Remove the test

**Comment by caalador** [comment]
Closing as components have been moved to own repositories.
