### ISSUE TITLE
Migrate Tests (unit & IT) for individual component modules

### ISSUE THREAD

**Issue by pekam** [vaadin/flow#2773]
When developing a component, I want to run unit tests and integration tests to make sure that the component works as expected.

Common configuration can be added to the super-pom `flow-component`

- [x] Button
- [x] CheckBox(at the moment, there is no IT test for **indeterminate checkbox**, will add it later)
- [x] ComboBox
- [x] DatePicker
- [x] Dialog
- [x] FormLayout
- [x] Icon
- [x] Vertical-  & HorizontalLayout `vaadin-ordered-layouts`
- [x] TextField & PasswordField
- [x] SplitLayout
- [x] Upload

Also, see comment below

**Comment by pleku** [comment]
It is enough for this issue to just port the existing component integration tests from vaadin/flow from `flow-components-parent/demo-flow-components/src/test` for each component.
