### ISSUE TITLE
RouteNotFoundError extension doesn't work

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/flow#2774]
Aim is to make custom Not Found view
According to tutorial I've extended NotFoundView from RouteNotFoundError (I can't implement HasErrorParameter since it can be implemented only once).
![screen shot 2017-10-25 at 16 10 55](https://user-images.githubusercontent.com/28781210/32003123-e6e40dec-b9a6-11e7-8311-f3f183e0060a.png)

and when I'm navigating to non-existing view at some point a have:
![screen shot 2017-10-25 at 16 09 48](https://user-images.githubusercontent.com/28781210/32003165-fc34abb6-b9a6-11e7-8651-b673f9660616.png)

Expected NotFoundView has "null" key and not associated with needed exception.

Note that if I'm using some custom exception (e.g. AccessDenied) it works properly.

**Comment by caalador** [comment]
This issue has been fixed on 20.10. so if you are not using the snapshot it won't work
unless you use the originally documented method of implementing the `HasErrorParameter` for the extending `NotFoundView` class.
