### ISSUE TITLE
I18N Support

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2776]

**Comment by pleku** [comment]
After initial design discussion, the following code examples highlight the API usage for application developers:
``java
        TextField nameField = new TextField();
        // just simple setting value from map for key
        I18N.of("nameField.label", tf::setLabel);
        // using placeholders in the translation text like {0}, {1}, which are returned from the lambda 
        I18N.of("nameField.errorMessage", tf::setErrorMessage, context -> new String[]{"param1", "param2"});
        // builder for the same
        I18N.forField(myField).key("some.random.key").withParam("one").withParam("two").build();
    }

    // allowing registering any part of a attached `Component` to get language set up
   // this would be run on attach and every time when locale changes for that UI 
    @I18NUpdate
    private void updateLabels(LocaleContext context) {
        datePicker.setLocale(context.getLocale());
        datePicker.setTimeZone(context.getTimeZone());

        nameField.setLabel(I18N.of("some.random.key"));
    }
```

**Comment by heruan** [comment]
Will the `I18N` provide an abstract way of retrieving translations (e.g. from database instead of files)?

**Comment by pleku** [comment]
Yes @heruan there will be an abstraction layer for deciding what is the source of the translation files, #2779 will have a demo & tutorial for one example of this using resource bundles. For your data base you just fetch the content from there instead based on the active locale & key.
