### ISSUE TITLE
When creating an application I want to have a defined way/place of creating language files.

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#2779]
There should be a Service Provider Interface which has a default implementation for loading the data from files, e.g. reading from `default.properties`, `default_en_EN.properties`, `default_fr_FR` from properties to `src/main/resources/lang`. The file name should have as a postfix the ISO locale code.

This can be then used by any application developer to specify another adapter for reading the locale data based on the locale and keys, such as database tables.

**Comment by pleku** [comment]
Decided that this is just about making a demo and tutorial on how to create an app that supports multiple locales like english and klingon.

**Comment by caalador** [comment]
Sorry to say I'm not putting the Klingon in as it's to a big part english and I couldn't get the font to work.
I replaced it with Japanese which is almost the same.
