### ISSUE TITLE
Theming Support

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2780]
- There needs to be a standard location for the main theme HTML file.
  - Could recommend naming like always `styles.html` or `my-theme-name.html`.
  - Should always recommend to put this file in the same place: 
    - `src/main/webapp/frontend/styles/styles.html` 
    - `src/main/webapp/frontend/theme-name/styles.html` (like in FW)
    - somewhere else ? Bakery is using `../app/style-modules/shared-styles.html`
- Have documentation on how to and where to create the Apps own theme (from above) and how to import it
  - Could consider FW approach: `@Theme("mytheme")` -> `@HtmlImport("frontend/app/themes/mytheme.html")` or `..app/themes/mytheme/styles.html` ?
- Have documentation on how to use include Valo in your own App theme and get started with Valo
  - Currently Valo documentation is in https://cdn.vaadin.com/vaadin-valo-theme/2.0.0-alpha3/demo/index.html, but we should preferably link to a permanent place for latest version (?)
- It should be really easy to take Valo2 or the Material Theme should be really easy to use from Flow side.
  - Valo2 dependency comes from platform, it should be a WebJar (not sure if one already ?)
  - `@ValoTheme` -> `@HtmlImport("frontend/vaadin-valo-theme/vaadin-all.html")` which would load Valo for all of our components
    - there is no `vaadin-all.html` yet, would be super convenient for Flow users (and us)
  - Maybe have `@MaterialTheme` which could do the same
- The DX for theming V10 Apps in Flow must be verified

This excludes anything related to:
- generating server side constants for Valo theme `theme` attribute values
- documentation or examples on the actual styling of components or customizing Valo/Material theme
- supporting dynamically changing the theme

**Comment by pleku** [comment]
@jouni @Legioth comments ?

**Comment by jouni** [comment]
> There needs to be a standard location for the main theme file. That is a HTML file. Like `styles.html` or `my-theme-name.html`. We should always recommend to put this file in the same place, e.g. `src/main/webapp/src/webapp/app/styles/`

Why? I would instead write documentation where to put such a file and how to load it – how to write CSS for a Flow app/view/component in general. I would not create a hard-coded convention for a single main theme file.

> Currently Valo documentation is in https://cdn.vaadin.com/vaadin-valo-theme/2.0.0-alpha3/demo/index.html, but we should preferably link to a permanent place for latest version (?)

We don’t know yet where Valo/theme documentation will end up. But yes, you should wait for the permanent place to appear before linking. We will discuss this tomorrow with a small group. If you have input, I think you can join in.

> Valo2 dependency comes from platform, it should be a WebJar (not sure if one already ?)

Not sure, but I haven’t created one at least.

> `@ValoTheme` -> `@HtmlImport("frontend/vaadin-valo-theme/vaadin-all.html")` which would load Valo for all of our components

In principle, I’m against this being promoted as the best practice, as it most probably ends up loading unneeded files in the browser. Could be a negligible difference in most production apps, but it’s still wrong from a performance perspective.

Haven’t thought about alternatives, though. Would it possible to set the theme on a global level, and then we would load the corresponding theme files automatically for all the components which are actually used in the app?

**Comment by jouni** [comment]
Thinking a bit more, we should think if we can come up with a solution that solves both the `styles/my-theme.html` and the “load all of our components” issues.

A way for the developer to specify from where to load component theme files, for exactly those components which are actually used in the app.

For example, if I’m using Valo as the theme for my app, and use `Button` in my app, we would automatically load `vaadin-valo-theme/vaadin-button.html`.

Or if I’m using “my-theme”, we would automatically load `my-theme/vaadin-button.html` instead.

And perhaps there could be some hard-coded convention about a “common/global/shared” style file, that we would always try to load `my-theme/shared.html` if it’s found from the file system.

**Comment by pleku** [comment]
>>There needs to be a standard location for the main theme file. That is a HTML file. Like styles.html or my-theme-name.html. We should always recommend to put this file in the same place, e.g. src/main/webapp/src/webapp/app/styles/

>Why? I would instead write documentation where to put such a file and how to load it – how to write CSS for a Flow app/view/component in general. I would not create a hard-coded convention for a single main theme file.

Very good point. Let's just demonstrate how to do it in general level.

>>Currently Valo documentation is in https://cdn.vaadin.com/vaadin-valo-theme/2.0.0-alpha3/demo/index.html, but we should preferably link to a permanent place for latest version (?)

>We don’t know yet where Valo/theme documentation will end up. But yes, you should wait for the permanent place to appear before linking. We will discuss this tomorrow with a small group. If you have input, I think you can join in.

We'll wait for that link, thanks.

>Thinking a bit more, we should think if we can come up with a solution that solves both the styles/my-theme.html and the “load all of our components” issues.

There was an idea of @Legioth that we would by default always just take Valo into use if there is no "custom theme" used and the Valo WebJar is available on the classpath. Thus we would import the `vaadin-valo-theme/vaadin-button.html` automatically when the web component `vaadin-button/vaadin-button.html` is done.
For this we need to define what it means to have another theme there than Valo

**Comment by heruan** [comment]
I'd also suggest a `HasTheme` mixin interface to add/remove theme attribute values easily, e.g.

```java
// Before: <vaadin-button theme="primary">
button.getTheme().add("small");
// After: <vaadin-button theme="primary small">
```
