### ISSUE TITLE
When registering translation methods I would like to use the builder pattern.

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#2781]
Register translation methods.

`I18n.for(myTF).withKey("label.key").forSetter("myTF::setLabel)`
or
`I18n.for(myTF).withKey("label.key").forSetter("myTF::setLabel).withParameters({"param1", "Param2"})`
or
`I18n.for(myTF).withKey("label.key").forSetter("myTF::setLabel).withParameter("param1").withParameter("Param2")`

**Comment by pleku** [comment]
Decided to use another approach and this would not be needed. See #2206
