### ISSUE TITLE
Migrate Icons to its own repository

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#2783]
the package will be `com.vaadin.ui.icon`, the old icon file will be split to `Icon` and `IronIcon`
and demos

**Comment by pleku** [comment]
Several major issues with this:
- The code does not compile, how can `IronIcon` have constructor for `Icon` ? https://github.com/vaadin/vaadin-icons-flow/blob/master/src/main/java/com/vaadin/ui/icon/IronIcon.java#L44
- The  [`HtmlImport`](https://github.com/vaadin/vaadin-icons-flow/blob/master/src/main/java/com/vaadin/ui/icon/IronIcon.java#L31) should be for `iron-icon`
- The [`IronIcon`](https://github.com/vaadin/vaadin-icons-flow/blob/master/src/main/java/com/vaadin/ui/icon/IronIcon.java#L26) javadocs don't say anything about for the class is. It should explain `<iron-icon>` and have a link to https://github.com/polymerelements/iron-icon
