### ISSUE TITLE
If template parsing fails, it should also fail on the second attempt

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#2785]
```
@Route("PolymerTemplateView")
@Tag("polymer-template-view")
@HtmlImport("non-existing.html")
public class PolymerTemplateView extends PolymerTemplate<TemplateModel> {

    public PolymerTemplateView() {
    }
}
```

When opening `/PolymerTemplateView` the first time, an error message is printed: `There was an exception while trying to navigate to 'PolymerTemplateView' with the exception message 'Unable to create an instance of 'com.vaadin.testUI.PolymerTemplateView'. The constructor threw an exception.'`. The exception is eaten because of #2724.

The problem is that if you refresh the view, there is no longer any error message but instead an empty view is rendered (or the child elements attached to an empty custom element if there are such. This makes debugging difficult

**Comment by denis-anisimov** [comment]
It looks like the fix for #2724 fixed the issue as well.
Please verify.

I cannot reproduce it anymore.
