### ISSUE TITLE
Consistently use one locale as the default

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#2791]
There's currently some logic inherited from Framework 8 that sets the locale of `VaadinSession` based on request headers from the browser (if available). At the same time, there's a `locale` field in `UI` that is completely independent from the setting in the session. Automatically choosing the locale based on the request is dangerous in cases when the application has translations for some specific languages, but no defaults.

We should clean up this to make it always use `Locale.getDefault()` by default, and then provide a way for application developers to select a locale to use so that they can use something based on the browser's settings if any of those locales are actually supported by the application (or hardcode it to some specific value, or read a cookie, or whatever).

My suggestion for how to quite easily provide support for most of these cases would be to have an application property that contains a list of locales.
1. If the list is empty or the property is not defined, then the `Locale.getDefault()` is always used as the default for new sessions and UIs.
2. If there is one item in the list, then it's always used as the the default.
3. If there are multiple items in the list, then `VaadinRequest.getLocales()` is iterated until finding a locale that exactly matches a configured locale. If nothing is found, the request locales are iterated again to find a match only based on the language, and if no matches are still found the first item from the configured list is used.

**Comment by pleku** [comment]
We should later on add an easy option for writing and reading the users preferred locale from a Cookie, so that the user can use the preferred locale instead of what the system she is using provides.  https://www.w3.org/International/questions/qa-accept-lang-locales

**Comment by pleku** [comment]
There is also a `queue` value that can be assigned to the locales by the user to specify the priority for different locales. This is a value between `[0, 1]` and a missing value means prioriry `1.0`.

**Comment by Legioth** [comment]
Please note that there should be no reason to manually parse the HTTP header and order the values based on the priority numbers. This is automatically taken care of by `VaadinRequest::getLocales`.
