### ISSUE TITLE
Add CI validation build for each component repository

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2794]
Would be great to have a CI validation build (TeamCity?) for each of the current component repositories. The validation should be run for each PR for each component listed below and it should be mandatory status check for merging into master repository. It probably makes sense to use a shared configuration for each of the repositories, since for now, they will have the exact same setup.

The build should be running the ITs from #2773 with the embedded jetty, by first starting up the server and then running `mvn verify`.

- [x] Button
- [x] CheckBox
- [x] ComboBox
- [x] DatePicker
- [x] Dialog
- [x] FormLayout
- [x] Icon
- [x] Vertical- HorizontalLayout `vaadin-ordered-layouts`
- [x] TextField & PasswordField
- [x] SplitLayout
- [x] Upload

**Comment by Artur-** [comment]
Unless you have a solution for secure variables with fork PRs (or will never need secure variables), please consider something else than Travis. Otherwise it effectively blocks contributions

**Comment by pleku** [comment]
Travis doesn't provide the same `******` feature for using secure variables in forks ? Oh great. Then have to go with TC probably

**Comment by ZheSun88** [comment]
As we are using `jetty-maven-plugin`, at this moment, the main method in the demo class will be removed and under CI validation,  `mvn clean install` will be run.
