### ISSUE TITLE
Add CI build for publishing new component versions to maven central

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2796]
The same CI configuration and build should be reusable for all of our component repositories. It should just build, verify and publish a new version of the component. It should take as a parameter the component to build and release.

There should be spreadsheet which has a release checklist for each component we have, similarly as with Flow. For now, there are not that many checklist steps, since we are not updating any demos to the website or doing anything else. 

The `maven-release` plugin setup should go to the `flow-component` parent module `pom.xml` and from there it can be shared to all of the components at once.
Before releasing, there should be a build step for running `mvn verify` #2794 

- [x] Button
- [x] CheckBox
- [x] ComboBox
- [x] DatePicker
- [x] Dialog
- [x] FormLayout
- [x] Icon
- [x] Vertical- HorizontalLayout `vaadin-ordered-layouts`
- [x] TextField & PasswordField
- [x] ProgressBar
- [x] SplitLayout
- [x] Upload
- [x] Tabs (if already added)

The releases should be made to [vaadin-prereleases repository](https://vaadin.com/framework/releases/8.2.0.alpha2) for now, like #2489 will be doing for the flow artifacts.

**Comment by ZheSun88** [comment]
the first release versions of individual Flow Components, e.g. `vaadin-upload-flow` or `vaadin-text-field-flow` (latter was part of `flow-components` following flow versioning), will be `1.0.0.alpha1`. The release notes for every component release we do should always list 
a) Flow version it has been tested with
b) The Elements version it is using

**Comment by ZheSun88** [comment]
maven.vaadin.com is not a running nexus instance but an amazon S3 bucket for serving the repository.  The contents of vaadin-prereleases Maven repository is synced there from our (your team) internal staging nexus instance at http://dh1.int.vaadin.com:8082/nexus

**Comment by ZheSun88** [comment]
https://maven.vaadin.com/vaadin-prereleases/com/vaadin/
