### ISSUE TITLE
Add CI build for publishing new component demo versions to internal maven repo

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2797]
In Bender we need a build configuration for building and publishing a new version of the demo jar enabled by #2795. Since we need it only for the website and integration test module in Flow, it should be published to the flow-internal maven repository.

As part of this ticket, all the following component demos should be also released with initial version 1.0.0.alpha1:

- [x] Button
- [x] CheckBox
- [x] ComboBox
- [x] DatePicker
- [x] Dialog
- [x] FormLayout
- [x] Icons
- [x] Horizontal- & VerticalLayout
- [x] ProgressBar
- [x] SplitLayout
- [x] Tabs
- [x] TextField
- [x] Upload

**Comment by ZheSun88** [comment]
https://repo.vaadin.com/nexus/content/repositories/flow/com/vaadin/

**Comment by pleku** [comment]
Couple of things:
- the demo releases are pending on snapshot version of flow, but they should be pending on a flow release version instead
- the artifact ID is `vaadin-button-flow` instead of `vaadin-button-flow-demo`
- it seems that the component artifact is deployed too, we should not have those deployed there but instead the demo artifact should be using the actual release versions of the component
