### ISSUE TITLE
Web Components tutorials are outdated

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#2801]
* It should use webjars
* `package.json` should not be in `src/main/webapp`, if it needs to be anywhere it should be outside the deployed folder
* When building the es5/es6 files, they should end up in the folders defined by Flow, i.e. served as `/frontend-es5` and `/frontend-es6`
* No `<resourceBases>` should be used as this is inherently incompatible with Spring Boot. The files should be automatically moved to the correct place instead.

**Comment by pleku** [comment]
Please note this @SomeoneToIgnore, mayhaps update this when working with the maven production build transpilation ?

**Comment by SomeoneToIgnore** [comment]
Let's sort things out with the plugin first.

**Comment by SomeoneToIgnore** [comment]
Awaits https://github.com/vaadin/flow-maven-plugin/issues/5

**Comment by pleku** [comment]
Should be revisited completely now that WebJars work.

**Comment by denis-anisimov** [comment]
* It should use webjars
Done.
* `package.json` should not be in `src/main/webapp`, if it needs to be anywhere it should be outside the deployed folder
The whole ES5 transpilation tutorial is outdated way to set up project for production. The tutorial is made as optional and the preferred way is to use maven plugin now. Don't see a need to spend much time on deprecated way described in the tutorial so `package.json` is kept on its place but excluded from the resulting binary archive.
* When building the es5/es6 files, they should end up in the folders defined by Flow, i.e. served as `/frontend-es5` and `/frontend-es6`
See above: the whole tutorial is optional now and describes the deprecated way. The es5/es6 files are served correctly from the location where they are transpiled. Folders are not defined by flow (by default) but the application is configured to use those folders.
* No `<resourceBases>` should be used as this is inherently incompatible with Spring Boot. The files should be automatically moved to the correct place instead.
Again: see above. The tutorial still uses  `resourceBases` for Jetty but now the web resource location is changed to `resources/META-INF/resources` which is available if packaging as JAR (in case of Spring boot).

The result is:
- webhars now is the way of using web components.
- maven plugin is the way of set up project for production
- previous tutorials are not removed but redone and made deprecated.
