### ISSUE TITLE
Classcast when session times out and using spring

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow#2802]
`
java.lang.ClassCastException: com.vaadin.server.VaadinSession cannot be cast to com.vaadin.spring.SpringVaadinSession
	at com.vaadin.spring.SpringVaadinServletService.sessionDestroyed(SpringVaadinServletService.java:103) ~[flow-spring-addon-1.0.0.alpha6.jar:na]
	at com.vaadin.spring.SpringVaadinServletService.lambda$new$f7ca4470$1(SpringVaadinServletService.java:62) ~[flow-spring-addon-1.0.0.alpha6.jar:na]`

**Comment by tmattsso** [comment]
Using alpha4

**Comment by Legioth** [comment]
I think the conclusion at some point was that we should try fix the architecture so that we won't need to have a separate `SpringVaadinSession` type that could even have the risk of causing these kinds of issues.

**Comment by denis-anisimov** [comment]
This has been already fixed.

This is a pure bug and spring add-on is able to work with any kind of VaadinSession class.

This specific issue is quite trivial typo bug.

**Comment by denis-anisimov** [comment]
That's the ticket which Leif is referring to : https://github.com/vaadin/flow/issues/2657
