### ISSUE TITLE
Grid: The first item of the first page of items gets duplicated when updating the first item of the second page.

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#2803]
Assuming the default `pageSize` of 50 items:

1. Generate a Grid with more than 100 items;
2. Lazy load the first page (50) items;
3. On the server, update the 51st item, and call `dataProvider.refreshItem`;

![grid_bug_1](https://user-images.githubusercontent.com/7464735/32182721-0a8d0ce2-bda0-11e7-821a-22b8fc2c9cc2.png)

4. Scroll down to the 51st item - it shows the correct value

![grid_bug_2](https://user-images.githubusercontent.com/7464735/32182753-1c9fa854-bda0-11e7-83ba-5b70a8fd50f4.png)

5. Update the same item again - now it shows the 1st item of the grid, instead of the 51st.

![grid_bug_3](https://user-images.githubusercontent.com/7464735/32182760-21f32038-bda0-11e7-9f62-211eaf2d8603.png)

This same code was copied from `demo-flow-components`, with some changes to make it simpler and with the fields and button to update the items inside the grid:

```
Grid<Person> grid = new Grid<>();
grid.setItems(createItems());
grid.addColumn("Name", Person::getName);

TextField idField = new TextField("", "Person id");
TextField nameField = new TextField("", "New name");

//empty ValueChangeListener due to bug https://github.com/vaadin/vaadin-text-field-flow/issues/4
idField.addValueChangeListener(event -> {});
nameField.addValueChangeListener(event -> {});

Button updateButton = new Button("Update person", event -> {
        String id = idField.getValue();
        String name = nameField.getValue();
        ListDataProvider<Person> dataProvider = (ListDataProvider<Person>) grid.getDataProvider();
        dataProvider.getItems().stream()
                .filter(person -> String.valueOf(person.getId()).equals(id))
                .findFirst().ifPresent(person -> {
                    person.setName(name);
                    dataProvider.refreshItem(person);
            });
});
```

**Comment by pekam** [comment]
Issue moved to [vaadin/vaadin-grid-flow #12](https://github.com/vaadin/vaadin-grid-flow/issues/12) via [**ZenHub**](https://www.zenhub.com/)
