### ISSUE TITLE
Flow should support browsing resources in debug mode

### ISSUE THREAD

**Issue by tsuoanttila** [vaadin/flow#2806]
When I'm developing my application I want to be able to browse through all `webjars` and `frontend` resources so that I can find out what is the actual path for the resource I need.

It would be nice to:
1) Get a 404 when I try to find something that does not exist in those paths.
2) Get a full listing of directories and files when I access a resource folder
3) In production mode this should not be allowed, but return for example 403.

This should help the developer to find out about the internal structure without digging into the Flow source code.

**Comment by mshabarov** [comment]
This is an enhancement and latest Vaadin versions don't use webjars, so this enhancement wouldn't be implemented most likely (maybe only for V14 as a sponsored feature).
