### ISSUE TITLE
Vaadin-grid filtering with DataProvider

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/flow#2813]
I have following data provider for a grid

`DataProvider<T, String> dataProvider = new CallbackDataProvider<>(query -> crudService.findAnyMatching(query.getFilter()).stream(),
query -> crudService.countAnyMatching(query.getFilter()));`

`ConfigurableFilterDataProvider<T, String, String> filteredDataProvider = dataProvider
				.withConfigurableFilter((String queryFilter, String filter) -> filter);`

on filter change I call: `filteredDataProvider.setFilter(filter);`

![oct-31-2017 14-31-31](https://user-images.githubusercontent.com/28781210/32224019-7517301c-be48-11e7-817b-184f7b04abe0.gif)

 
1. apply filter which doesn't have any corresponding data in db
2. remove filter
3. vaadin-grid gets permanent "loading" attribute

Update:

I can reproduce the issue.
To reproduce please use the very first code of the test component that I've added.

Steps: 
- write "fox" into the textfield.
- remove "x".

The result is: 
- the content is correct and it's always correct regardless of actions and filter.
- But the items in grid has another color (you may refresh the page and see the difference).
- It happens because the client-side Grid is in "loading" state.
- There is an attribute `loading` for `vaadin-grid` component.

There shouldn't be this attribute.
The client-side `Grid` is in the unexpected state.

But the content is always correct whenever you update the filter. 
So it's about "loading" state (and attribute).

**Comment by Legioth** [comment]
As a side note, you can use the zero-argument `withConfigurableFilter` overload in this case since you are completely ignoring any filter that would come from an upstream query.

**Comment by denis-anisimov** [comment]
Cannot reproduce it.

It might be that:
- There is no such issue anymore with the recent snapshot Grid version. Please check.
- You are using some specific data. E.g. it can be important the number of items which you have (client side calculation may be done wrong).

But it looks like in my example I have the same amount of data that you have in your example.

The attached image has very bad quality. I cannot see loading indicator mentioned int the description.

Please see below the code that I'm using to reproduce.
And please let me know exact steps to reproduce the issue (if it's still there) based on this code.
If you can't reproduce the issue with this code then please provide a localized code which I can use to reproduce.

```
public class GridFiltering extends TestView {

    private static final Set<String> DATA = getData();

    public GridFiltering() {
        Grid<String> grid = new Grid<>();

        DataProvider<String, String> dataProvider = new CallbackDataProvider<>(
                query -> findAnyMatching(query.getFilter()).stream(),
                query -> countAnyMatching(query.getFilter()));

        ConfigurableFilterDataProvider<String, Void, String> filteredDataProvider = dataProvider
                .withConfigurableFilter();

        filteredDataProvider.setFilter("");

        grid.setDataProvider(filteredDataProvider);

        grid.addColumn("Data", item -> item);

        TextField field = new TextField();
        field.addValueChangeListener(
                event -> filteredDataProvider.setFilter(field.getValue()));

        add(field, grid);
    }

    private Collection<String> findAnyMatching(Optional<String> filter) {
        if (filter.isPresent()) {
            return filter(filter).collect(Collectors.toList());
        }
        return Collections.emptyList();
    }

    private int countAnyMatching(Optional<String> filter) {
        if (filter.isPresent()) {
            return (int) filter(filter).count();
        }
        return 0;
    }

    private Stream<String> filter(Optional<String> filter) {
        return DATA.stream().filter(item -> item.contains(filter.get()));
    }

    private static final Set<String> getData() {
        Set<String> set = new LinkedHashSet<>();
        set.add("foo");
        set.add("bar");
        set.add("baz");
        return set;
    }
}

```

**Comment by alexberazouski** [comment]
I reproduced it with your example with flow 3 nov snapshot.
Two things:
1. changed inheritance: GridFiltering extends Div
2. added GridFiltering into slot (this might be important)

**Comment by denis-anisimov** [comment]
I'm pretty sure that neither component inheritance nor relationship (`slot`) doesn't matter .
But I will check it anyway.

What I need: 
_EXACT_ steps that I should do to see the issue.
What should I type into the text field, how to update it.

**Comment by alexberazouski** [comment]
1. Start typing some filter. Grid items will disappear little by little.
2. After all items disappeared, start to clear filter by single character. Grid items will appear
3. For me grid remains blurred (in loading mode)

**Comment by denis-anisimov** [comment]
Just information for the reference: I cannot reproduce it as is.

So may be I was wrong about relationship. 

`TestView` component above is a `div`.
So it might that `slot` matters.
But I'm afraid that I will need a complete code which allows to reproduce the issue.
I will check does `slot` matter.

**Comment by alexberazouski** [comment]
https://bakery-flow-spring.app.fi/users you could try it here
Full code in bakery's master: UsersView.java, bakery-users.html
Dataprovider is created in DefaultEntityPresenter.java

**Comment by denis-anisimov** [comment]
No, I can't.
I can't login.

I cannot reproduce the issue.

```
@HtmlImport("frontend://src/GridWrapper.html")
@Tag("grid-wrapper")
public class GridFilteringWrapper extends PolymerTemplate<TemplateModel>
        implements HasComponents {

    public GridFilteringWrapper() {
        add(new GridFiltering());
    }
}

public class GridFiltering extends Div {

    private static final Set<String> DATA = getData();

    public GridFiltering() {
        Grid<String> grid = new Grid<>();

        DataProvider<String, String> dataProvider = new CallbackDataProvider<>(
                query -> findAnyMatching(query.getFilter()).stream(),
                query -> countAnyMatching(query.getFilter()));

        ConfigurableFilterDataProvider<String, Void, String> filteredDataProvider = dataProvider
                .withConfigurableFilter();

        filteredDataProvider.setFilter("");

        grid.setDataProvider(filteredDataProvider);

        grid.addColumn("Data", item -> item);

        TextField field = new TextField();
        field.addValueChangeListener(
                event -> filteredDataProvider.setFilter(field.getValue()));

        add(field, grid);
    }

    private Collection<String> findAnyMatching(Optional<String> filter) {
        if (filter.isPresent()) {
            return filter(filter).collect(Collectors.toList());
        }
        return Collections.emptyList();
    }

    private int countAnyMatching(Optional<String> filter) {
        if (filter.isPresent()) {
            return (int) filter(filter).count();
        }
        return 0;
    }

    private Stream<String> filter(Optional<String> filter) {
        return DATA.stream().filter(item -> item.contains(filter.get()));
    }

    private static final Set<String> getData() {
        Set<String> set = new LinkedHashSet<>();
        set.add("foo");
        set.add("bar");
        set.add("baz");
        return set;
    }
}

```

GridWrapper.html:

```
<link rel="import" href="../bower_components/polymer/polymer-element.html">
<link rel="import" href="../bower_components/vaadin-grid/vaadin-grid.html">


<dom-module id="grid-wrapper">
  <template>
    <div>Grid Wrapper</div>
    <slot></slot>
    
  </template>

  <script>
    class GridWrapper extends Polymer.Element {

      static get is() { return 'grid-wrapper'; }
    }

    window.customElements.define(GridWrapper.is, GridWrapper);
  </script>
</dom-module>
```


Please localize the issue.
Important information is missing since I cannot reproduce it.
Apparently there is something in your setup which makes it behaving in this way.
This information is absent in the original description.

**Comment by heruan** [comment]
I can reproduce this at http://bakery-flow-spring.app.fi/products by simply writing `asd` on the filter input, then deleting it.

![bakery-grid-blur](https://user-images.githubusercontent.com/851745/32415330-8b830756-c238-11e7-8034-919da4e4e9e3.gif)

**Comment by denis-anisimov** [comment]
Yes, we already discussed this.
I've updated the description.
I misunderstood the issue.

**Comment by denis-anisimov** [comment]
Looks like race condition.
Sometimes it works as expected.

**Comment by denis-anisimov** [comment]
The `_getItem` method of `vaadin-grid` calls `_loadPage` asynchronously.
So it's postponed. And its work relies on emptiness of the cache for the page.
If we set the cache right away then `loadPage` logic is never executed (which is bad generally) 
and this logic actually updates `_loading` property (to `false`).
The latter method updates the cache with the correct values (but it's postponed).
