### ISSUE TITLE
Enable sorting Grid Columns

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2816]
When showing a grid to users, I want them to be able to sort the columns, so that they see the data in the way they want.

This should add the `vaadin-grid-sorter` web component for the column with the corresponding column id as the `path` parameter. 

```java
grid.addColumn() // this could take a boolean for sortable

// this can only work when it is done before the column has been rendered, 
// this is a known limitation with the way that the vaadin-grid is implemented
column.setSortable(true);

// enable multi sorting
grid.setMultiSort(true);
```

When the sorting has been enabled, and the user sorts a column, there is the `sortOrder`array provided in the parameters of the client side data provider.

```javascript
// `params.sortOrders` format: [{path: 'lastName', direction: 'asc'}, ...];
params.sortOrders.forEach(sort => url += '&orders[]=' + sort.path + ' ' + sort.direction);
```

This should be transmitted to the server side and used to build the sort order on the server side data provider, which will send the sorted data back to the client.

For in-memory data, the `Column.setComparator()` should be used, and for each column there is always a default comparator set in the beginning, see `Column` constructor in FW8 for example https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/Grid.java#L958.

The way that the grid client-server communication is implemented, for now, means that we cannot have client side only sorting.

For the first round, if #2800 column header templates is implemented, these might be in conflict, and we don't know yet if combining the sorting and a custom renderer will work. If it does not work, we will just have to throw an `UnsupportedOperationException` if the user tries to add both sorting and column header template.

**Comment by heruan** [comment]
Please do not assume sorting via `Comparator` *in-memory*, since there are repositories which from a `Comparator` are able to sort backend data.

I'm aware that *most* backends need a string label for sorting, but those adopting Java 8 already encourage using `Predicate`s to filter and `Comparator`s to sort, instead of strings.

So I'd avoid using terms like `inMemorySorting` and I'd provide means to sort without labels, e.g.

```java
Grid<Person> grid = new Grid<>();
Column<String> nameColumn = grid.addColumn("Name", Person::getName);
Column<String> dobColumn = grid.addColumn("Date of birth", Person::getDob);

Comparator<Person> compareByName = personModel.getNameComparator();
Comparator<Person> compareByDob = personModel.getDobComparator();

nameColumn.setSortable(true).sortWith(compareByName);
dobColumn.setSortable(true).sortWith(compareByDob);
```

Then `Grid` would provide a stream of comparators for sorted columns to the data provider query, applying `Comparator::reversed` when necessary; then, I'd be able to:

```java
DataProvider dp = DataProvider.fromCallbacks(query -> {
        Stream<Person> stream = personRepository.stream();
        Stream<Comparator<Person>> comparators = query.getComparators();
        return comparators.reduce(Comparator::thenComparing)
                .map(stream::sorted)
                .orElse(stream);
    }, ... );
```

or similar.

**Comment by heruan** [comment]
Was my comment considered for sorting implementation in 1.0.0.alpha10? I see the only way to sort via backend is using string property labels. Would my suggestion in the comment have a chance to be discussed for a future release? I'd be happy to contribute, of course!

**Comment by pleku** [comment]
Sorry for the lack of answer, we did discuss your proposal briefly, but for now we ended up using the same API as in V8 for now.

We do see that the use case is valid, and mayhaps we could switch from using `Comparator inmemorySorting` to `Stream<Comparator>` that would serve both use cases. Not sure if that would be enough.

Please create a new ticket though, since this one is done.

**Comment by heruan** [comment]
Thank you @pleku! See #2991.
