### ISSUE TITLE
Use predefined sorting for Grid data

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2818]
When showing a grid to the users, I want to show the data as sorted, so that they see the data in a meaningful order and can see that also from the grid that it is sorted this way.

*This feature depends on whether we can update the sort order in the `vaadin-grid-sorter`, meaning that it is exposing the ordering of the sorted columns in `multi-sort` mode.*

```java
// the following should throw, unless the column has been defined as sortable
column.sort(SortDirection.ASCENDING/DESCENDING/NONE);
```

This needs to update the sorting indicator in the UI e.g. `vaadin-grid-sorter direction="ascending"` and also update the sort orders on the server side and trigger new sorting of data. If multi-sort is enabled, then the appends to the sort order list.

If sorting is applied to the `DataProvider`, that will not be visible in the grid on the UI.

**Comment by pekam** [comment]
Issue moved to [vaadin/vaadin-grid-flow #13](https://github.com/vaadin/vaadin-grid-flow/issues/13) via [**ZenHub**](https://www.zenhub.com/)
