### ISSUE TITLE
Using -Dvaadin.force.shady.dom=true does not force shady DOM

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#2820]
Running an application using `-Dvaadin.force.shady.dom=TRUE` has no effect on whether Shady or Shadow DOM is used. It seems like an attribute (`shadydom`) is added to the webcomponents loader script tag but the attribute only works if set on a `webcomponentsjs` script tag(?).

Not sure why the whole feature exists, when should it be used? You can accomplish the same thing (except it works) using e.g. a bootstrap listener
```
head.prepend("<script type='text/javascript'>window.customElements.forcePolyfill=true;window.ShadyDOM = {force:true};</script>");
```

**Comment by Legioth** [comment]
We might maybe want to completely remove the feature?
