### ISSUE TITLE
Add the documentation/tutorial for ComponentRenderers inside Grid

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#2825]
Related to the ticket https://github.com/vaadin/flow/issues/2720

There should be a tutorial showcasing the different ways of using ComponentRenderers for rendering cells and item details.

The demo always shows multiple ways, but they are not properly explained in detail like a tutorial would do.

**Comment by pekam** [comment]
Documentation on details row could be part of this ticket. It should just be noted that you can also use `TemplateRenderer` for the details row.
