### ISSUE TITLE
Consider removing the automatic browser based stylenames added to body

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#2844]
Nowadays, there are generic approaches for basically all common CSS constructs that work in all modern browsers without any browser specific selectors. We should therefore remove the built-in hardcoded style names that encourage doing things in a non-standard way.

**Comment by pleku** [comment]
I'm not so sure about this since we are still supporting e.g. IE 11 in Flow 1.0 & Vaadin 10.
Another question is that should we just apply the `ie11` class name only for that piece of browser.

**Comment by Legioth** [comment]
I think IE 11 is still also modern enough to not need custom selectors.

**Comment by pleku** [comment]
>I think IE 11 is still also modern enough

That is very brave thinking. Should probably ask the website team for feedback, if they don't need these then surely nobody does.

**Comment by pleku** [comment]
The website is apparently not using any browser specific selectors, so I think we can do this.

**Comment by jouni** [comment]
If you need to, you can use special CSS selectors to target IE11 (or even Edge) only. Targeting other browsers is more tricky, but also less often needed.

IMO it would be good to move this feature to the “user space” or to an opt-in feature.

**Comment by manolo** [comment]
Should `v-generated-body` also be removed?

**Comment by jouni** [comment]
> Should v-generated-body also be removed?

Yes.

**Comment by rolfsmeds** [comment]
> The website is apparently not using any browser specific selectors, so I think we can do this.

With all due respect, I feel that the argument that since one specific website, built by some pretty hardcore experts, has managed without this means that none of our users, many of whom are Java developers and thus don't have world class css skills, also don't need it, is a bit... strange.

**Comment by jouni** [comment]
Like I said before, I still believe this feature belongs to “user space”. A utility for easily adding selected browser (or feature) classes seems like a nice solution.
