### ISSUE TITLE
I18NProvider type scanning should work in Spring Boot application

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#2863]
#2791 introduces one more type which should be scanned for during startup.

This is one more type which Spring boot application should care of.

**Comment by Legioth** [comment]
Why does it have to be scanned during startup. Can't it simply be based on whatever is attached, i.e. a class that isn't attached won't ever be considered.

**Comment by caalador** [comment]
Attached where and when?
It's needed at session creation if we want to use the provided list to determine locale.

**Comment by Legioth** [comment]
Sorry. I was thinking of the observers, not the init logic for selecting the locale to use.

**Comment by caalador** [comment]
Updated the usage for the provider so this ticket is now obsolete.
