### ISSUE TITLE
SharedUtil upperCaseUnderscoreToHumanFriendly should be available

### ISSUE THREAD

**Issue by johannesh2** [vaadin/flow#2868]
When converting enums to human friendly form it would be nice to have the method upperCaseUnderscoreToHumanFriendly from V8 SharedUtil to be available.

**Comment by Legioth** [comment]
We could try to come up with a more appropriate name for the hosting class than `SharedUtil`.

**Comment by asashour** [comment]
In which project, and which class should be added?

**Comment by Legioth** [comment]
I'd suggest `com.vaadin.util.CaseUtil` in `flow-server`.

I suspect we also have some similar logic spread out in multiple location for converting the case between bean property names and setter/getter method names (e.g. `fooBar` <-> `FooBar`). This could maybe also be extracted to `CaseUtil` as a separate PR.

**Comment by asashour** [comment]
@johannesh2: in FW8, this method is only called by `SharedUtil`.`propertyIdToHumanFriendly()`, is it something we need in Flow?

This question was asked in #3112
