### ISSUE TITLE
Cannot do Router.getUrl for a Spring view that uses constructor injection

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#2869]
The logic in `Router.getUrl` assumes that the navigation target class can be instantiated using `ReflectTools.createInstance`. This is not the case with classes intended to be instantiated by Spring.

Currently, an instance must be needed in order to call the `serializeUrlParameters` method that has a default implementation in `HasUrlParameter`. The design here is questionable since it requires doing a potentially expensive instantiation operation only to find out something that will in most cases always use the same default implementation that doesn't need any instance.

I would suggest removing the functionality for now, and then designing an approach that doesn't rely on creating instances once we have some specific use case that requires this kind of customisability.

**Comment by heruan** [comment]
I agree with Leif, instantiating the component just to call `serializeUrlParameters` is overkill, mostly since that method itself does not even need the instance and could be static (I guess it's not static to pair with `deserializeUrlParameters`, which needs the instance instead).

Since it's really just a line of code, why not give `RouterLink` its own static method?

```java
static <T> List<String> serializeUrlParameters(List<T> urlParameters) {
    return urlParameters.stream().filter(Objects::nonNull).map(T::toString)
            .collect(Collectors.toList());
}
```

**Comment by Legioth** [comment]
> since that method itself does not even need the instance and could be static 

The idea is an implementation could override the method to customize how its URL parameters are serialized. If we remove that customizability, then the corresponding deserialize method should also be removed since it doesn't make any sense to define one but not the other.

**Comment by heruan** [comment]
> I would suggest removing the functionality for now […]

Do you mean have the router serializing itself with a copy of `serializeUrlParameters `?

**Comment by Legioth** [comment]
> Do you mean have the router do the serialization itself with a copy of `serializeUrlParameters`?

Yes. The current `default` implementations of `serializeUrlParameters` and `deserializeUrlParameters` would instead be hardcoded into `Router`. It's an implementation detail whether they would be static methods with a copy of the current implementation, inlined, or handled in some other way.

**Comment by heruan** [comment]
I'm using #2992 in my Spring application right now, i.e. `serializeUrlParameters` as static method in `Router`. I have not ported `deserializeUrlParameters` though, since it's not used by the router.
