### ISSUE TITLE
Deadlock when shutting down Spring Boot application

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#2871]
When shutting down an application using Spring Boot (and probably also DevTools), it often ends up in a deadlock that requires force killing to resolve. This only seems to happen when running it normally, but not with a debugger attached.

This happens because of a deadlock between the shutdown procedure of Spring and the embedded Tomcat instance. According to https://github.com/spring-projects/spring-boot/issues/1314#issuecomment-50753623, you should not pass an `ApplicationContext` do the constructor of `DispatcherServlet` when using an embedded servlet engine. Otherwise, the servlet will try to shut down the application context when the servlet is undeployed, which causes a deadlock because the application context is already being shut down but waiting for the embedded servlet engine to shut itself down.

Changing our registration code in `SpringBootAutoConfiguration` to use `setApplicationContext` instead of passing the context to the constructor fixes the issue in this case, but it's not clear to me whether this will cause problems when the app is instead deployed as a war file. Should we maybe check whether `context` implements `EmbeddedWebApplicationContext`?

It's also not clear to me whether a similar fix would be needed in the other case where we create and register a `DispathcerServlet`, i.e. in `VaadinMVCWebAppInitializer`. I assume that path is never used with an embedded servlet container?

**Comment by Legioth** [comment]
This problem actually also affects live redeploys with Spring Boot DevTools, thus making it much more sever than only a minor inconvenience when actually shutting down the project.

**Comment by Legioth** [comment]
Apparently, you can work around this issue by using adding `spring-boot-starter-jetty` as a dependency, since apparently the shutdown deadlock is specific to the Tomcat works.

**Comment by Legioth** [comment]
Should also verify and close https://github.com/vaadin/skeleton-starter-flow-spring/issues/16 once this is fixed.

**Comment by heruan** [comment]
> apparently the shutdown deadlock is specific to the Tomcat works

Don't know if the same deadlock, but I'm experiencing a freeze on shutdown also in WildFly.

**Comment by Legioth** [comment]
Very likely that it's the same deadlock, and that it's only the Jetty implementation that is lock-free in this regard.
