### ISSUE TITLE
JS error "Attempted to call itemsUpdated with an invalid value" when triggering grid selection

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#2874]
When using `Grid<>.getSelectionModel().select()` the the demo [GridView](https://github.com/vaadin/flow/blob/master/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java) at the current master (commit d5d07b6e2d), I get a JS error in the browser: `(String): Attempted to call itemsUpdated with an invalid value`.

![grid-demo-toggle-selection-issue](https://user-images.githubusercontent.com/22416150/32548522-99e8ab4a-c48e-11e7-9d98-d5f09e1ae2fd.gif)

The browser error log:
<img width="1201" alt="screen shot 2017-11-08 at 13 47 40" src="https://user-images.githubusercontent.com/22416150/32549827-85f316ca-c493-11e7-8956-11ec061910ed.png">

**Comment by denis-anisimov** [comment]
This is a regression introduced recently.
https://github.com/vaadin/flow/commit/cb26215f688f04e554c3f63aa32b471fb8859b63
