### ISSUE TITLE
It should be possible to include the flow client javascript into a bundle

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#2878]
When you are optimizing the files to load initially, there is not much you can do about VAADIN/static/client/client-A2F4BBA720D0BE4D6D810593B4E46084.cache.js. It would be beneficial if this could be included in the same initial bundle as all web components and templates so that there would be one less request.

**Comment by gilberto-torrezan** [comment]
Worth mentioning special javascript files needed for some components (like `Grid`), which also would need to be optimized. For example: https://github.com/vaadin/flow/tree/master/flow-components-parent/flow-components/src/main/resources/META-INF/resources

**Comment by Legioth** [comment]
@gilberto-torrezan The plan is to automatically include anything referenced using `@JavaScript` or `@HtmlImport` from any component that is actually used, so things like `gridConnector.js` would automatically be handled by that.
