### ISSUE TITLE
Add Java API for vaadin-grid `activeItem` property

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#2879]
When working with the Flow Grid component, I want to have a Java API to access the [`activeItem`](https://vaadin.com/elements/vaadin-grid/html-api/elements/Vaadin.GridElement#property-activeItem) property of `vaadin-grid`:
 - get the current value
 - set the current value
 - set a listener for property change events

**Comment by pleku** [comment]
Why are you interested in the `activeItem` property?

Why not use selection API? E.g. `Grid.asSingleSelect()`. Have you read https://github.com/vaadin/flow/blob/master/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#handling-selection-changes?

**Comment by vlukashov** [comment]
The use case that makes me interested in the `activeItem` property rather than in the selection API is that: Clicking on / interacting with a row in the grid should open a dialog with the row details. The row should not stay selected (neither visually, not logically), i.e. the next click on the same row should not deselect it but rather open the same dialog again.

The reason why I think this property should be included into the Flow Grid API (apart from my current use case) is that I believe the Flow Grid API should have a feature parity with the vaadin-grid element API.

**Comment by pekam** [comment]
Issue moved to [vaadin/vaadin-grid-flow #15](https://github.com/vaadin/vaadin-grid-flow/issues/15) via [**ZenHub**](https://www.zenhub.com/)
