### ISSUE TITLE
Add Java API for vaadin-grid `expandedItems` property

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#2880]
When working with the Flow Grid component, I want to have a Java API to access the [`expandedItems`](https://vaadin.com/elements/vaadin-grid/html-api/elements/Vaadin.GridElement#property-expandedItems) property of `vaadin-grid`:
 - get the current list of expanded items
 - expand an item by calling the [`expandItem`](https://vaadin.com/elements/vaadin-grid/html-api/elements/Vaadin.GridElement#method-expandItem) method
 - collapse an item by calling the [`collapseItem`](https://vaadin.com/elements/vaadin-grid/html-api/elements/Vaadin.GridElement#method-collapseItem) method

**Comment by ahie** [comment]
This functionality was recently added in the commit https://github.com/vaadin/flow/commit/cb26215f688f04e554c3f63aa32b471fb8859b63. Closing this issue, but please comment if there's still something missing.

Also note that in `vaadin-grid` beta 1 the naming of `expandItem` and `collapseItem` were changed: https://github.com/vaadin/vaadin-grid/releases/tag/v4.0.0-beta1.
