### ISSUE TITLE
Port changes from FW [8.1.0.alpha1 - 8.1.0] final to Flow

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2883]
https://github.com/vaadin/framework/compare/8.1.0.alpha1...8.1.0

*Should Not Port* anything concerning
* Hierarchical Data (`TreeGrid`, `Tree`)
* OSGi (Liferay)
* Drag and Drop
* Flash
* client side
* `Navigator`
* `Grid` (migrated from a later state of Fw8, so all relevant changes are already taken)

Changes to `Binder` have also been probably migrated already, but better double check.

**Comment by pleku** [comment]
@torok-peter can you post a link to the spreadsheet with the list of everything ?

**Comment by torok-peter** [comment]
Here it is: https://drive.google.com/open?id=1zyoI3jdC40ufC7ZwFRwDHwRCzAE5ra3v
