### ISSUE TITLE
Port changes from FW [8.1.1 - 8.1.X] 

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2884]
https://github.com/vaadin/framework/compare/8.1.0...8.1

Might be easier to look at the master branch for these, since all changes to `8.1` branch should be there.

New GWT version or Java 9 support stuff should not be ported (I thinks).

**Comment by torok-peter** [comment]
Spreadsheet of all changes involved is shared at https://drive.google.com/open?id=1nBX2nqoQelEdvziZp1yu3Sa-IzlOWA57 .
