### ISSUE TITLE
Port changes from FW 8.2 to Flow 

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2885]
https://github.com/vaadin/framework/compare/8.1...master

**Comment by pleku** [comment]
The last migrated commit was https://github.com/vaadin/framework/commit/f5d8dd7bf4a58af048f0ee13061b1bde5a95facb

**Comment by ZheSun88** [comment]
port change sheets: https://docs.google.com/spreadsheets/d/1CT62GFk-9ygNhDtWSm0A9Do_bB4qfv5Q07A1RIgS6ws/
