### ISSUE TITLE
Grid Component Renderer does not refresh on `Grid.getDataCommunicator().refresh()`

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#2890]
When using a `ComponentRenderer<>` to render cells in a grid column, I want the appropriate cell to refresh when `Grid<>.getDataCommunicator().refresh()` is called. This currently works if grid cells are rendered with a `ValueProvider`, but does not work if they are rendered with a `CompoenentRenderer<>`:

![grid-refresh-demo](https://user-images.githubusercontent.com/22416150/32648593-3242979a-c5ff-11e7-85bd-f570cdd43e00.gif)

This code works OK:
```java
List<Order> orders = Arrays.asList(
        new Order(0L, "Flow Java API", LocalDateTime.now().minusDays(2)),
        new Order(1L, "A couple of nice features", LocalDateTime.now().minusDays(1)),
        new Order(2L, "A bunch of nasty bugs", LocalDateTime.now()));

Grid<Order> grid = new Grid<>();
grid.setItems(orders);
grid.addColumn("#", Order::getId);
grid.addColumn("Summary", Order::getSummary);
grid.addColumn("Created at", o -> o.getCreatedAt().format(OrderCard.FORMATTER));
        
Order order = orders.get(1);
order.setSummary("Lots of AWESOME features");
grid.getDataCommunicator().refresh(order);
```

This code does not work:
```java
Grid<Order> grid2 = new Grid<>();
grid2.setItems(orders);
grid2.addColumn("Order", new ComponentRenderer<>(order -> {
    OrderCard card = new OrderCard();
    card.setOrder(order);
    return card;
}));

Order order = orders.get(1);
order.setSummary("Lots of AWESOME features");
grid2.getDataCommunicator().refresh(order);
```

A Flow project demonstrating the issue is attached: 
[grid-refresh-demo.zip](https://github.com/vaadin/flow/files/1460532/grid-refresh-demo.zip)

**Comment by gilberto-torrezan** [comment]
Our demo at http://flow.app.fi/components/vaadin-grid uses `grid.getDataProvider().refresh(item)` instead of using the communicator. Can you test whether it works in your case?

**Comment by vlukashov** [comment]
Thanks for the hint! `grid.getDataProvider().refreshItem(order)` works in both cases.

**Comment by pekam** [comment]
Issue moved to [vaadin/vaadin-grid-flow #9](https://github.com/vaadin/vaadin-grid-flow/issues/9) via [**ZenHub**](https://www.zenhub.com/)
