### ISSUE TITLE
Non-polymer minesweeper demos do not work

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#2892]
Open:
http://flow.app.fi/demo-minesweeper-element-1.0.0.alpha9/
http://flow.app.fi/demo-minesweeper-component-1.0.0.alpha9/

Expected: minesweeper field
Actual: nothing

Polymer version works.

**Comment by Artur-** [comment]
Seems like all styles are missing. If you manage to click on a 1x1 px cell, you will see a number popping up

**Comment by caalador** [comment]
Works in 1.0.0.alpha15 version.
