### ISSUE TITLE
TemplateInitializer: correct JS execution (use beforeClientResponse in addition to runWhenAttached)

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2901]
TemplateInitializer uses `runWhenAttached` method to execute JS for the node, postponing it so that it's able to execute (because the node becomes attached).

There is a generic issue with this: the node may be attached ( so that it schedule the code to execute) and then in the same request it might be detached.

So the code should not be executed at all in this situation. Besides the logical issue it will lead to the client-side exception because there will be no DOM element to execute the code against.

The code should use `beforeClientResponse` inside `runWhenAttached`. It guarantees that the code will be executed only if the node is attached.

There is a complexity in this task: there are a number of unit tests that have to be corrected with the new behavior (emulation of `beforeClientResponse` behavior should be added).

Also as a part of this task: find all `runWhenAttached` usages in the code and check whether they are correct or not.

**Comment by Legioth** [comment]
There's still also the theoretical case when one `beforeClientResponse` action causes some node to become detached after a `beforeClientResponse` action has been run for that node. We might consider disallowing detaching (or leaving detached, but reattaching should still be acceptable?) from inside `beforeClientResponse` actions?

**Comment by denis-anisimov** [comment]
Is it really possible ?

`beforeClientResponse` checks whether the node is attached on its execution (or am I wrong?).
So it won't be just executed at all if the node is detached (whatever action has been used to detach it).

**Comment by Legioth** [comment]
The problem is that another `beforeClientReponse` might still detach the element. This is the situation that can still cause problems:
```
elementA.callFunction("focus");
tree.beforeClientReponse(anyNode, () -> elementA.removeFromParent());
```
There will now be two `beforeClientReponse` tasks. When the first is investigated, `elementA` is still attached which will cause `executeJavaScript` to be called. After that, another `beforeClientReponse` task is run which causes the element to be detached.

**Comment by denis-anisimov** [comment]
Alright.

But is it a problem ?
It's important that the first JS execution will be send to the client and will be correctly (or won't be?) handled on the client side.

Attach events are are handled at the first place.
The JS execution is done on post flush listener...... So it will throw for the detached element ?
But that's a generic issue.... (because JS is executed in the very end).

**Comment by Legioth** [comment]
In the context of the original ticket, `beforeClientReponse` is definitely the right solution.

We should probably have a separate ticket about the theoretical issues with one `beforeClientReponse` detaching a node after we have run some other `beforeClientReponse` that assumed that the node would be attached.

**Comment by denis-anisimov** [comment]
`TemplateInitializer` doesn't contain anymore JS execution with `runWhenAttached`.
But the issue is still valid since there are a number of cases when `runWhenAttached` is used with JS without `beforeClientResponse`.
