### ISSUE TITLE
Migrate `flow component` module from flow project to its own repo.

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#2904]
the repo is the here `flow-component-base`  https://github.com/vaadin/flow-component-base

and release the flow component base .

**Comment by ZheSun88** [comment]
https://maven.vaadin.com/vaadin-prereleases/com/vaadin/flow-component-base/1.0.0.alpha1/

**Comment by pleku** [comment]
@ZheSun88 please add a description on the read me on what the repository and project is about.
