### ISSUE TITLE
FlexLayout missing setWrapMode api

### ISSUE THREAD

**Issue by haiwan** [vaadin/flow#2906]
FlexLayout currently doesn't have API for setting wrap mode, in order to change the wrap, I have to deal with css in Java. Even though the code is quite simple, it's still something that Java-centered developers might not be familiar with. Getting the API as an auto complete suggestion in the IDE also beats any "manual" approach.

**Comment by pleku** [comment]
Issue moved to [vaadin/vaadin-ordered-layout-flow #10](https://github.com/vaadin/vaadin-ordered-layout-flow/issues/10) via [**ZenHub**](https://www.zenhub.com/)
