### ISSUE TITLE
Grid Component Renderer fails in Firefox when navigating to another view

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#2912]
When navigating away from a view having a grid with a Component Renderer, there is a JS error in Firefox: `TypeError: a is null`.
![grid-component-renderer-issue](https://user-images.githubusercontent.com/22416150/32765671-336ccc04-c914-11e7-855e-4c92d60d4ebe.gif)

The stack trace point to the `_clear` method in `flow-component-renderer.html`:
<img width="886" alt="screen shot 2017-11-14 at 8 13 28" src="https://user-images.githubusercontent.com/22416150/32765667-2bf79dd2-c914-11e7-8c77-ab6b256ed4bf.png">

The issue is reproducible with the [`master`](https://github.com/vaadin/flow/commit/29896bb8651e58368813ed68fe74081f137fd95f) branch of Flow in Firefox 56.0.2 (64-bit). 

A demo project is attached: 
[grid-component-renderer.zip](https://github.com/vaadin/flow/files/1469760/grid-component-renderer.zip)

**Comment by pekam** [comment]
Issue moved to [vaadin/vaadin-grid-flow #7](https://github.com/vaadin/vaadin-grid-flow/issues/7) via [**ZenHub**](https://www.zenhub.com/)
