### ISSUE TITLE
I18NProvider: public String getTranslation(String key, Object... params) is confusing

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2919]
I18NProvider has the  method 
```
public String getTranslation(String key, Object... params)
```

This method should use current `UI`  locale to delegate its call to 

```
 public String getTranslation(String key, Locale locale, Object... params)
```

The problem here is that `I18NProvider` mixes up API and SPI in one class.
`I18NProvider` is a pure SPI. It should not know anything about `UI`.
It should just provide a data on request.

The confusing method suggests that there are somewhere a `UI`  instance which is not known how to get to get its locale.

There should be only `public String getTranslation(String key, Locale locale, Object... params)` method in SPI.

The convenience method could be extracted to an utility class or directly added to `UI`/`UIInternals`.

**Comment by denis-anisimov** [comment]
Actully there is one more request/issue:

`I18NProvider`  currently is supposed to be used directly.

In reality it's SPI. 
And we need API which is not the same.

Nornally the developer in its application doesn't use SPI directly.
He uses API.

It means tht there should be a way to get translation via API but this should be API and as a result the `I18NProvider` instance shouldn't particiate in this call at all.
The provider is called internally in the implementation. But it's a kind of hidden. That's the essence of the SPI. It's intended to extend the functionality.
And API is intended to be used.

That's kind the reason of this ticket : there should be somwhere `public String getTranslation(String key, Object... params)` method but it should be not in the `I18NProvider`.
This method is API.
The  `public String getTranslation(String key, Locale locale, Object... params)`   is SPI.

**Comment by pleku** [comment]
There is feedback for the current approach using `getI18NProvider()`which is not really convenient:
https://vaadin.com/forum/#!/thread/16972466/16990903

**Comment by Legioth** [comment]
Separating API and SPI might be a good start. Then there is probably also some need for a more high-level API on top of the current barebones functionality.

**Comment by jcgueriaud** [comment]
I replied to my topic in the forum. (and make a summary here). I don't know if it's the "same" problem and if I should follow the discussion in my forum topic or here.
As a developer, I don't "want" to call i18nProvider.getTranslation for every components, validator, systemMessages to externalize strings (and translate it if necessary).
That's why in Vaadin 8 or 7 applications, I created I18nTextfield (to override setCaption for example and call my I18nProvider), but extends every Vaadin components/validator... is not the best solution (in my opinion).
As I use Hibernate validator, I suggest the same kind of functionality (because it's so easy to use it as a developer).

**Comment by Legioth** [comment]
@jcgueriaud Thank you for you input. What you're describing is basically the "high-level API" that I was  referring to in my previous comment.

**Comment by pleku** [comment]
We decided to hide the `I18NProvider` from the usage of getting translations. We will remove
`String getTranslation(String key, Object... params);` from `I18NProvider`.

Instead we'll add two methods for `Component`:
```java
public String getTranslation(String key, Object... params) { ... }
public String getTranslation(String key, Locale locale, Object... params) { ... }
```
And the first method should handle the resolving of the locale based on the current `UI` locale, as implemented in the current tutorial `getLocale()` method https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/advanced/tutorial-i18n-localization.asciidoc.

Any component that, for some reason, has its own locale, should override that method and use the locale from the component level. We currently have one example of this `DatePicker`.



### Acceptance Criteria
Update documentation and demo (in flow-demo).
