### ISSUE TITLE
IronList placeholder item support

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#2924]
By default, the `<template>` tag populated by the `IronList` component will use something like a `<dom-if>` to only use the component's `Renderer` for items that have already been lazy loaded. For missing items, an empty inline element is used instead.

It should also be possible for the user to define a placeholder item (`void setPlaceholderItem(T placeholderItem)` and a corresponding getter). For a non-`null` placeholder item, the conditional part in the `<template>` is skipped and the values from the item are instead used with the regular `Renderer`.

### Acceptance Criteria
- There is an example that shows the usage of placeholder item to show just the property names or "-", "..." or whatever for the data

**Comment by pleku** [comment]
Issue moved to [vaadin/vaadin-iron-list-flow #6](https://github.com/vaadin/vaadin-iron-list-flow/issues/6) via [**ZenHub**](https://www.zenhub.com/)
