### ISSUE TITLE
I18N: VaadinSession.setLocale() doesn't update locales for UIs

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2926]
I'm not sure whether this is a bug or not but I would expect that
the locale is updated being set to the `VaadinSession` instance for the all active `UI`s.

If I don't want to update locales for all `UI`s I use `UI::setLocale` only for specific `UI`s.

**Comment by Legioth** [comment]
Maybe just remove the method?

**Comment by denis-anisimov** [comment]
I'm OK with that.

But I think it's used in the impl.
When the new UI is created it gets the Locale from the session :

```
protected UI createAndInitUI(Class<? extends UI> uiClass,
            VaadinRequest request, VaadinSession session) {
        UI ui = ReflectTools.createInstance(uiClass);

        // Initialize some fields for a newly created UI
        ui.getInternals().setSession(session);
        ui.setLocale(session.getLocale());
```

**Comment by Legioth** [comment]
It uses the getter, but not the setter.

**Comment by denis-anisimov** [comment]
But the setter is apparently used in another place to set the `Locale`  for the session.
Or it's `final` /initialized inside the session?

**Comment by caalador** [comment]
The session could do the initialisation of the locale by itself. VaadinService could for instance call `VaadinSession.initializeLocale(I18NProvider)` then we wouldn't need to have a `setLocale` in 2 places. But then perhaps the getter should be renamed to `getInitialLocale` ?

**Comment by caalador** [comment]
Or just have in the UI init the locale on `doInit(VaadinRequest request, int uiId)` that is called on createAndInitUI from the BootstrapHandler.
Or should we remove the set from UI and only have it used from VaadinSession?
