### ISSUE TITLE
Grid: when changing the sortable state of a column that uses ComponentRenderers in the header, the header is not updated

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#2936]
To reproduce this, create a Grid with a ComponentRenderer for the header of one of the columns, making it sortable by default:

```java
Grid<Person> grid = new Grid<>();
grid.setItems(getItems());

Column<Person> nameColumn = grid.addColumn(Person::getName, "name")
                .setHeader(new ComponentRenderer<>(() -> new Label("Name"));
```

... and after attaching and rendering the Grid, change the column to be not sortable anymore (you can do that by having a button in the UI, for instance):

```java
new Button("Set sortable false", evt -> nameColumn.setSortable(false));
```

When the sortable is set to false, the header is not updated in the client-side. The arrows for sorting are still presented.

The other way around is also true: if you have a column which is non-sortable by default, and after the Grid is rendered you change it to be sortable, the header is not updated to show the arrows.

**Comment by gilberto-torrezan** [comment]
This is related to how the `vaadin-grid-column` interprets a column as being sortable: it expects the header template to have a `vaadin-grid-sorter` element inside. See the example at https://cdn.vaadin.com/vaadin-grid/4.1.0-alpha3/demo/#grid-sorting-filtering-demos

So the way the Java code does is to create a template with the `vaadin-grid-sorter` when the column is sortable, and without when it's not. So far so good. The problem starts when it tries to change the template after it has been processed (to add or remove the `vaadin-grid-sorter` element). Apparently changing the template doesn't make the Grid to refresh the view automatically.

**Comment by pekam** [comment]
Issue moved to [vaadin/vaadin-grid-flow #5](https://github.com/vaadin/vaadin-grid-flow/issues/5) via [**ZenHub**](https://www.zenhub.com/)
