### ISSUE TITLE
Build a bundle for all the transpiled files

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2939]
We need to have _a file_ that has all the dependencies to build. For now this file should be manually constructed by the user, and then be defined as an input with a default option of _my-bundle-configuration.json_ to the maven plugin. (Later on we want to autogenerate this).

The maven plugin target will use the transpiled files to build two bundles, one for es5 and another for es6 resources.

### Acceptance Criteria
- I'm able to create a file with all my frontend dependencies and run a maven target to get everything in there to a bundle

**Comment by SomeoneToIgnore** [comment]
Closed in https://github.com/vaadin/flow-maven-plugin/pull/25
