### ISSUE TITLE
Read the manifest.json bundle file in the DependencyFilter

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2943]
Similarly as [what bakery has tried](https://github.com/vaadin/bakery-app-starter-flow-spring/commit/59af8bccf164360023c225acd207d4ff4a291340#diff-ce5cfaf272860ddb1e8a9df397cad191) we should have a dependency filter that is used automatically when in production mode and read the bundle manifest file and loads the correct bundles for the resources.

The maven plugin should output the bundle manifest file automatically.

The filter is added automatically, but if production mode is not used or if there is no `bundle-manifest.json` file available, then the filter does nothing.

### Acceptance Criteria
I can use my bundles without implementing a `DependencyFilter` myself.

**Comment by SomeoneToIgnore** [comment]
`bundle-manifest.json` explanation can be found in https://github.com/Polymer/polymer-build/issues/263

Since Polymer team is not eager to review the corresponding PR, we should implement the logic in the plugin.

**Comment by Legioth** [comment]
Please note that the PR is only about adding this capability to `polymer build`. The low-level `polymer-bundler` tool is already capable of producing a `bundle-manifest.json` file.

**Comment by SomeoneToIgnore** [comment]
As agreed with @ahie , he will pick it up, since he has a few changes to the functionality.
