### ISSUE TITLE
SPIKE: investigate how to scan classpath with maven plugin to find out used resources

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2950]
Need to investigate how to detect used vaadin components in the project classpath when running the maven plugin. Mayhaps there is a way for this in maven, or we need to add some build lifecycle step to gather this information and write it somewhere.

**Comment by SomeoneToIgnore** [comment]
Spike was a success, https://github.com/ronmamo/reflections library allows to retrieve annotation data from the compiled project and its dependencies.
Implementation draft is in https://github.com/vaadin/flow-maven-plugin/tree/kb/analyze-project-sources
all that is left to 
* normalize (remove `frontend://`, `context://` prefixes) and, possibly, verify urls collected
* use them in the gulp task
