### ISSUE TITLE
Put in a lang attribute to <html>

### ISSUE THREAD

**Issue by Peppe** [vaadin/flow#2956]
Screen readers need to know in which language a page is in. This is done with the `lang` attribute on the `<html>` tag. If there is no lang defined, then screen readers will choose the default language of the end user. So for example if a user with a Finnish language OS and screen reader accesses an app in English, then the screen reader will try to read English with a Finnish accent.

There is locale info in Flow which can be used to select the correct language, and a `<html lang="en">` could be a good default.

**Comment by samie** [comment]
I guess this needs to be dynamic also and depend on the content of the view in case of deep linking?

**Comment by Peppe** [comment]
As a workaround I did this by having a BootstrapListener and setting in a lang attribute from there. There is however no direct way to access `<html>` so I had to go via `<head>`.

```java
public class CustomBootstrapListener implements BootstrapListener {
  public void modifyBootstrapPage(BootstrapPageResponse response) {
    // Language of the page. This is important for screen readers. If none is
    // defines, screen readers will use the default language of the user. If
    // the users' default language is other than app language, then the screen
    // reader does not make sense.
    response.getDocument().head().parent().attr("lang", "en");
  }
```

**Comment by Legioth** [comment]
@samie It would use whatever the application's `I18NProvider` tells it to use.

See https://github.com/vaadin/flow/blob/master/flow-documentation/miscellaneous/tutorial-i18n-localization.asciidoc for more information.

**Comment by samie** [comment]
Ok.  Only making sure that the initial delivered html has the right attributes (i.e. view based, not app based). Any later attribute changes are not visible to e.g. search index.

**Comment by Legioth** [comment]
Yes. We're currently implementing the `Locale` to be fixed during initialization and then you'd have to do your own workarounds to support changing it on the fly. We might still add support for changing later on, but it's out of scope for now.

**Comment by samie** [comment]
Ok, to be clear: does this mean that site search indexing of views (or pages) is in the scope now?

**Comment by Legioth** [comment]
The main reason for this feature is to help e.g. screen readers better interpret the effective DOM.

It's a positive side effect that it also helps with search indexing, but that's not the primary purpose of doing this particular change.

**Comment by samie** [comment]
Thanks. If I understood correctly, the answer is yes and we can trust host html is already delivered with correct attributes for that specific view. Serving (easily) view based host html attributes correctly is generally very important to SEO, and it is good to hear we're not making any shortcuts/traps here.

**Comment by Legioth** [comment]
@samie You can trust that the `lang` attribute of the `<html>` tag has the intended value. That's all this ticket says.

**Comment by pleku** [comment]
### Acceptance Criteria
- setting the `lang` attribute value in `BootstrapHandler` to whatever is resolved by the session initialization.
