### ISSUE TITLE
JavaScript exceptions should not be swallowed in production mode

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#2963]
If you do `page.executeJavaScript("lkajsfd");` you will get a `SyntaxError` error message in the console when running in development mode (in addition to a popup) but in production mode you get absolutely nothing and have no clue that the JS failed and is causing problems.

**Comment by SomeoneToIgnore** [comment]
Logging was removed due to https://github.com/vaadin/flow/issues/2028

I think even the error messages can be used to print critical information also hence this ticket should be closed.

**Comment by Artur-** [comment]
#2028 was about logging what was going to be executed, I don't see any mention of exceptions in that

**Comment by Legioth** [comment]
`console.error` sounds like a quite logical place of logging for exceptions, since that's where they would end up naturally if a similar error would be in a regular JS file that is included into the page.

**Comment by paulroemer** [comment]
As we just got hit by the issue on vaadin.com I can tell you that logging to `console.error` isn't enough because we cannot monitor the error log of our clients.
If you would log it to the server log we could filter for those warnings/errors and get informed about it immediately.

**Comment by Legioth** [comment]
It would be quite obtrusive (and has the potential of causing infinite exception handling loops) for Flow to try to submit exceptions to the server.

What Flow could do is to provide a hook for plugging in your own exception handler.

**Comment by paulroemer** [comment]
We can of course start with a hook so that we can experiment with the feature and give you feedback. But on the other hand it feels crucial to me that the developer is (at least) informed about template model related issues in the server logs without the need to register a special handler.

It would make the support team's life much easier, too. Reusing the example above: I would ask for the server log, notice that there are warnings about template issues and first ask them to fix that.

**Comment by Legioth** [comment]
I agree that it would help simplify many cases, but I'm also worried that it might cause quite spectacular explosions in other cases unless the implementation is flawless.

**Comment by Legioth** [comment]
Could you create a separate ticket about an hook and/or possibility to send information to the server, so that this ticket could remain focused on the original request of making the errors available in the browser console?

**Comment by paulroemer** [comment]
See #3708

**Comment by fluorumlabs** [comment]
Any news on that? It's getting extremely hard to debug in IE11.

**Comment by denis-anisimov** [comment]
No any news.
It's an enhancement and has a label `needs design` and in the staging backlog.
It means that  it has the lowest priority.

**Comment by pleku** [comment]
Debugging IE11 will become much easier in 13 for project using npm since you will not need to run production mode for IE11.

I don't expect us to do anything this before that.

**Comment by Artur-** [comment]
This is still a problem in V23. It has nothing to do with IE11.

**Comment by Artur-** [comment]
5 years later. When your app does not start in production mode, you get a white screen and no error message.
