### ISSUE TITLE
Do not open details row for each click

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2972]
`When showing a grid to the users, I don't want the details row to open automatically for each row click, because I want them to open it only when necessary`

### Acceptance Criteria
There is demo and documentation on the feature for how to
- Disable the default of always opening row details for each click
- Make the details open when the user clicks an "open details" button in the last column of the grid

**Comment by pekam** [comment]
Issue moved to [vaadin/vaadin-grid-flow #6](https://github.com/vaadin/vaadin-grid-flow/issues/6) via [**ZenHub**](https://www.zenhub.com/)
