### ISSUE TITLE
Grid column setFlexGrow is not working before grid is displayed

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/flow#2978]
When grid is attached via @Id then I can't configure columns (setFlexGrow, setWidth).

But after grid was displayed, if I do column setFlexGrow on grid selection, it works.
This can be checked (check last small commit):
https://github.com/alexberazouski/skeleton-starter-flow/tree/bug/grid-set-flex-grow

grid: 4.1.0.alpha3 (alpha2 as well); flow: 1.0.0.alpha10

Note: previously we used workaround for another flow bug, so we created Grid object on server and put it into slot. Then .setFlexGrow works as expected.

**Comment by pekam** [comment]
Issue moved to [vaadin/vaadin-grid-flow #8](https://github.com/vaadin/vaadin-grid-flow/issues/8) via [**ZenHub**](https://www.zenhub.com/)
