### ISSUE TITLE
Enable DataProvider sorting via backend Comparators

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#2991]
When dealing with data providers, I wan to be able to sort the returned stream via my one comparators, which are special implementations for backend optimization.

At the moment, the `Query` object provides this sorting data:

1. a list of `SortOrder<String>` via `getSortOrders()`
2. a `Comparator<T>` via `getInMemorySorting()`

The main problem with (1) is that it assumes backend sorting can be done with a string, which is very common but excludes modern abstractions such as custom database-backed streams which needs special implementation of `Comparator` to sort.

Getting the `Comparator<T>` with `Query::getInMemorySorting()` though, returns an instance built from comparators set via `Column::setComparator`, which immediately re-assigns the comparator instance passed as argument via `this.comparator = comparator::compare` to make is serializable, thus discarding the original implementation which may have been backed-aware.

What I suggest is having `Column::setComparator` to keep the original argument beside the serializable version, and add a `Query::getBackendSorting` returning a `Stream<Comparator<T>>` of all the original instances of column comparators. This way, it would be simple for a data provider to sort the stream with custom comparators, e.g.

```java
@Override
protected Stream<T> fetchFromBackEnd(Query<T, Predicate<T>> query) {
    Stream<T> stream = this.repository.stream();
    if (query.getFilter().isPresent()) {
        stream = stream.filter(query.getFilter().get());
    }
    Stream<Comparator<T>> comparators = query.getBackendSorting();
    Optional<Comparator<T>> comparator = comparators.reduce(Comparator::thenComparing);
    if (comparator.isPresent()) {
        stream = stream.sorted(comparator.get());
    }
    return stream.skip(query.getOffset()).limit(query.getLimit());
}
```

**Comment by heruan** [comment]
Seems like the original instance of a method reference lambda (such as `comparator::compare` can be obtained via reflection: the method reference object has a field named `arg$1` which contains the referenced method owner. Albeit dangerous, it can be used by backend frameworks to obtain the original comparator from the serializable ones created by `Column::setComparator`.

**Comment by heruan** [comment]
This might be way simpler than expected. If components keep original comparators, using just method references to make them serializable (e.g. `comparator::compare`), the original instances can be traced back via reflection by persistence frameworks to look for custom implementations of `Comparator`.

Then, the scenario I described would work out of the box with the comparator obtained from `Query::getInMemorySorting`, which at last could be renamed to `getSortingComparator` or similar to avoid wrong assumptions.

**Comment by Legioth** [comment]
Do you have any reference to documentation on how persistence frameworks can trace back method references? Last time I looked at the issue, it was easy to find the method for code compiled by `javac`, but the same code compiled with the Eclipse compiler was not as obvious.

From what I've understood, frameworks such as Speedment are instead relying on factories that create instances of e.g. `Comparator` that also implement some additional interface through which the querying part of the framework can find what to sort by.

That kind of case would of course also benefit from direct access to the original comparator instead of the way Vaadin combines them all together into one composite comparator.

**Comment by heruan** [comment]
Nothing official yet, I've written some utility methods and a test which is passing in both Eclipse and Maven: https://gist.github.com/heruan/f52d2195471ac08a66a7c44c519b8730

I think that's more a persistence framework issue though, on the Vaadin side it's just to keep in mind to not mangle more than necessary with potential arguments to `Stream` methods.

See for example https://github.com/vaadin/vaadin-grid-flow/pull/21.

**Comment by heruan** [comment]
With #3015 and https://github.com/vaadin/vaadin-grid-flow/pull/21 I'm able to sort with custom comparators, inspecting the lambda with the utility in the Gist above.
