### ISSUE TITLE
Create a unified renderer abstraction

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3003]
From a user's point of view, there are three different types of renderers.
* String extracted from each item and as plain text or rendered as HTML
  * With variations for formatting e.g. dates or numbers and rendering the formatted string as plain text
* A component is created and configured for each item
* An inline Polymer template with placeholders that are populated with JSON values extracted from each item.

There are two types of components that internally use different approaches, but work the same way from the user's point of view.
```
ComboBox<Person> cb = new ComboBox<>();
cb.setDataProvider(provider);
cb.setRenderer(new ComponentRenderer(PersonLabel::new));

ListBox<Person> lb = new ListBox<>();
lb.setDataProvider(provider);
lb.setRenderer(new ComponentRenderer(PersonLabel::new));
```
Internally, they work in completely different ways.
* `ComboBox` uses an array of JSON items and a `<template>`. The renderer defines the innerHTML of the `<template>` and how to populate each item JSON to contain values used by bindings inside the template.
* `ListBox` items are defined in the DOM. The renderer defines how to build the server-side light DOM for an item. There's no JSON to populate.

While the two component types have different native representations, they can both support all three basic renderer types with various degrees of overhead.
* `<template>` based components natively support `TemplateRenderer`. The string renderers can be expressed as simple templates with a single generated item property per renderer. ComponentRenderer requires some special consideration to manage the attachment status of components when lazy loading, and a custom element implementation that attaches the DOM tree of each component.
* Light DOM based components support strings and components natively. `TemplateRenderer` can be implemented by adding a `<dom-bind>` element to the light DOM and giving that element a JS property named `item`.

One implication of supporting the same renderer classes with both types of component is that each renderer implementation needs two different and unrelated feature sets.
* Item to `Element` for light DOM components
* Item to JSON and a static template innerHTML (or another `Element`) for template based components.

Full separation of concerns can be achieved by having two different implementations of the same concept, e.g. `ComponentLightDomRenderer` and `ComponentTemplateRenderer`, but this would be quite confusing for the application developer.

To make it easier for application developers to create their own completely custom renderer for one specific case, e.g. only using together with Grid, we could also define separate base interfaces for each case, e.g. `LightDomRenderer` and `TemplateBasedRenderer` (slightly ugly name to distinguish it from the high level `TemplateRenderer`), and then make all built-in implementations implement both interfaces.

**Comment by gilberto-torrezan** [comment]
Worth mentioning that despite the name, the current implementation of the `TemplateRenderer` actually doesn't use a `<template>` at all. It could be used for light-dom elements as well.

But of course the name of the class doesn't help with that.

**Comment by Legioth** [comment]
> Worth mentioning that despite the name, the current implementation of the `TemplateRenderer` actually doesn't use a `<template>` at all. It could be used for light-dom elements as well.

How can template bindings, e.g. `<div>[[name]]</div>` together with `withProperty("name", callback)`, work without a `<template>` that is stamped and managed by Polymer?

**Comment by gilberto-torrezan** [comment]
They don't. My point is that currently nothing prevents you from using `TemplateRenderer.of("<div>Something</div>");`, because it is not encapsulated in a `<template>`.

**Comment by Legioth** [comment]
Sounds like it will only confuse users. What's the point of allowing that kind of functionality?

**Comment by gilberto-torrezan** [comment]
IMO this is just a class naming problem. The `TemplateRenderer` actually doesn't use any `template` - so it should be renamed to something more generic - and that renamed class could be the base class that unifies the renderer abstraction. A proper `TemplateRenderer` could then be created to support more specific `template` needs (that today as scattered among utility classes).

**Comment by pleku** [comment]
Lets list out the renderer hierarchy and all components that have renderer API as public what so that we see an overview and its easier to decide what we should change.

**Comment by ZheSun88** [comment]
Inside `flow-server` we have a [`renderer` package](https://github.com/vaadin/flow/tree/master/flow-server/src/main/java/com/vaadin/flow/renderer), where there are a few basic renderers:

- public class: [`TemplateRenderer`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/renderer/TemplateRenderer.java)
  - helper method class [`TemplateRendererUtil`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/renderer/TemplateRendererUtil.java)
  - [`ButtonRenderer`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/renderer/ButtonRenderer.java) extends `TemplateRenderer` implements `ClickableRenderer`
  - [`ComponentTemplateRenderer`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/renderer/ComponentTemplateRenderer.java) extends `TemplateRenderer` implements `ComponentRenderer`
  - public abstract class: [`SimpleValueTemplateRenderer`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/renderer/SimpleValueTemplateRenderer.java) extends `TemplateRenderer`
    - [`LocalDateRenderer`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/renderer/LocalDateRenderer.java), [`LocalDateTimeRenderer`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/renderer/LocalDateTimeRenderer.java), [`NumberRenderer`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/renderer/NumberRenderer.java) extends `SimpleValueTemplateRenderer`

- public interface: [`ComponentRenderer`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/renderer/ComponentRenderer.java), [`ClickableRenderer`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/renderer/ClickableRenderer.java)
  - [`IconRenderer`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/renderer/IconRenderer.java), [`TextRenderer`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/renderer/TextRenderer.java) Implements `ComponentRenderer`

Components have render API as public:

`ComboBox`: [`setItemRenderer`](https://github.com/vaadin/vaadin-combo-box-flow/blob/master/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L166)
[`Grid`](https://github.com/vaadin/vaadin-grid-flow/blob/master/src/main/java/com/vaadin/flow/component/grid/Grid.java): `setItemDetailsRenderer`, `addColumn`, also `Render` have been used in `AbstractColumn.java`, `ColumnBase.java` and `GridTemplateReendererUtil.java` too.
`IronList`: [`setRenderer`](https://github.com/vaadin/vaadin-iron-list-flow/blob/master/src/main/java/com/vaadin/flow/component/ironlist/IronList.java#L178)
`ListBox`: [`getItemRenderer`] and [`setItemRenderer`](https://github.com/vaadin/vaadin-list-box-flow/blob/master/src/main/java/com/vaadin/flow/component/listbox/ListBox.java#L138)
`RadioButton`: [`getItemRenderer`] and [`setItemRenderer`](https://github.com/vaadin/vaadin-radio-button-flow/blob/master/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L137)

Components have used render:
[`Dialog`](https://github.com/vaadin/vaadin-dialog-flow/blob/master/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L185), [`Notification`](https://github.com/vaadin/vaadin-notification-flow/blob/master/src/main/java/com/vaadin/flow/component/notification/Notification.java#L250)

**Comment by pleku** [comment]
There is three types of renderers:
- TemplateRenderer
- ComponentRenderer
- Basic renderers:
  - DateRenderer
  - DateTimeRenderer
  - HtmlRenderer NOTE does not support events!
  - IconRenderer
  - NativeButtonRenderer
  - NativeCheckboxRenderer
  - NumberRenderer
  - RouterLinkRenderer (has a separate ticket for it)
  - TextRenderer

The component renderer and basic renderers can be used in both, components that support light-dom and templates. `TemplateRenderer` is only supported in components supporting templates. 

Light-dom renderers only: ListBox, RadioButtonGroup
Support all renderers: Grid, IronList, ComboBox
IronList supports only TemplateRenderer, but not with events.

**Comment by Legioth** [comment]
Suggestion based on offline discussion:
* `Renderer` only works with components that support template rendering. This is the type used by e.g. `Grid.addColumn`.
* `TemplateRenderer` is retained as a factory for constructing `Renderer` instances.
* `ComponentRenderer` extends `Renderer` and also works with components that only support light-dom contents. This is the type used by e.g. `ListBox.setItemRenderer`.

This means that the current `ComponentTemplateRenderer` functionality somehow needs to be folded into `ComponentRenderer` so that it has an already implemented (`default` or non-`abstract` depending on whether it's a class or an interface) method for getting a template for e.g. `Grid` that uses `<flow-component-renderer>` elements, while also having a method for getting a component for use by e.g. `ListBox`,  and also internally used when generating data for e.g. `Grid`.

It should also be possible for specific `ComponentRenderer` implementations (e.g. `RouterLinkRenderer`) to provide their own `getTemplate()` implementation that directly uses the native component representation (e.g. a `<a router-link>` template) instead of the less efficient default approach of wrapping everything through `<flow-component-renderer>`.

All `Basic renderers` listed in the previous comment should be based on `ComponentRenderer` so that they can be used also with e.g. `ListBox`.
