### ISSUE TITLE
Update Spring add-on to use Boot 2.0.0.M6 (or newer) 

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3006]
### Acceptance Criteria

- Update all the spring modules' dependencies to use Boot 2.0.
- Update the `skeleton-starter-flow-spring` dependencies too and update the `published` tag for it
- Update documentation and tutorial that Boot 2.0 Spring 5.0 (or greater) are supported
  - Tutorial in https://github.com/vaadin/flow-spring-tutorial

**Comment by caalador** [comment]
Seems like the only change needed is renaming org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration to org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration

**Comment by Legioth** [comment]
Does this also automatically imply updating to Spring 5, or is there a separate ticket about that?

**Comment by pleku** [comment]
> Does this also automatically imply updating to Spring 5, or is there a separate ticket about that?

We're already using 5.

**Comment by caalador** [comment]
Current changes and status in branch:
https://github.com/vaadin/flow/tree/issues/3006_update_spring_boot

Not creating a PR as the newest published release is only M6 and is only available in the spring milestone repository.
