### ISSUE TITLE
Execute Spring DX testing based on #2577

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3007]
Based on #2577 conduct the DX testing.

### Acceptance Criteria
- there is a document with the notes on the tests and initial conclusions (separated clearly) with possible suggested actions
- there is has been a meeting where all discovered issues have been covered and resolved (issue / PR or _this is fine_)

**Comment by pekam** [comment]
DX test report:
https://docs.google.com/document/d/1uUpNRL9mvOonzRoKnQNwFLhNfK05WFPblpYgmUSZW6I/edit#

**Comment by pleku** [comment]
Spun out #3177 #3179 #3180 #3181
