### ISSUE TITLE
Viewport should be usable on any navigation target

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3008]
Designs based on discussion on this issue and Epic #3011. 

The end result will not change (the meta tag in the initial page html), but after this ticket the annotation is read from navigation targets instead of UI.

### Acceptance Criteria
- I can add `@Viewport("my-view-port-string")` to a navigation target (marked with `@Route`)
   - If the navigation target has a parent layout, it is a programming error and should result in e.g. a deployment time exception -> forcing the configuration to only be on the topmost level
   - There can only be one `@Viewport` for a navigation target hierarchy, on the root level
   - `@Viewport` cannot be added for `UI` 
- There is a documentation on Initial Page Settings (which should replace the https://github.com/vaadin/flow/blob/master/flow-documentation/application-structure/tutorial-bootstrap.asciidoc) which has (for now only) a chapter on using the `@Viewport` annotation and the custom bootstraplistener part (which is already there)
- The `ViewportGenerator` annotation is removed

**Comment by Legioth** [comment]
Should the viewport change when navigating to a navigation target with some other setting?

**Comment by Legioth** [comment]
Seems like it's in general more useful to be able to define the same viewport for the same application, without having to duplicate the same settings to each individual navigation target class?

**Comment by pleku** [comment]
> Seems like it's in general more useful to be able to define the same viewport for the same application, without having to duplicate the same settings to each individual navigation target class?

Yes, but define where ? Either we bring back the `UI` and then the question is that should you have to declare it in the `VaadinServletConfiguration` or should it be automagically picked when you have it somewhere (like with navigation targets) ?

Which is worse, having to add something extra or just having to declare a root layout for these things or e.g. `AbstractRootLayout` which has all those things.

I agree that these should probably be just defined once, and if you need to customize the data, depending on the initial request data (?) or opened navigation target, you should use the generator. And there we could mayhaps add additional data on the resolved Navigation Targets (after redirects and everything have been done).

**Comment by pleku** [comment]
> Yes, but define where?
> Which is worse, having to add something extra or just having to declare a root layout for these things or e.g. AbstractRootLayout which has all those things.

This also relates to #3010

**Comment by Legioth** [comment]
My thoughts in https://github.com/vaadin/flow/issues/3011 also applies here.

**Comment by Legioth** [comment]
One clarification to the current Acceptance Criteria: The annotation can be on a navigation target or a router layout, not only on navigation targest.
