### ISSUE TITLE
Check the test coverage of Binder and add unit tests if needed

### ISSUE THREAD

**Issue by torok-peter** [vaadin/flow#3025]
`BinderTest` has not been migrated from Fw8 because it has component dependencies. Make sure nevertheless, that `Binder` is adequately covered with tests.

**Comment by denis-anisimov** [comment]
I'm not sure that it _has not been migrated_.

**Comment by denis-anisimov** [comment]
https://github.com/vaadin/flow/commit/317160c609a30de7e9b8d90b7c5da57cc17c79be

There is the `BinderTest` class.
