### ISSUE TITLE
Rename package names for Flow to make it easier to migrate from 8 to 10

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3032]
Consideration on the package name changes:
https://docs.google.com/document/d/1S1Ou0OmurgNGoVMKt9eFfCNZv1PjiHvRbql-gYKN9lw/edit?ts=5a01c637

**Comment by Legioth** [comment]
Please note that there are still a couple of open questions in the current version of the document.

**Comment by pleku** [comment]
There should not be any open questions anymore.

This will break and require new releases of all the
- Demos
- Starters
  - BB, 2*Skeleton, and to release those you need to tag them with `published`
- Components, all need new releases
