### ISSUE TITLE
Introduce PageConfigurator for initial page settings

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3036]
`When creating an app, I want to easily customize the initial page response based on the browser data or navigation target, because I want to make the UX as good as possible` 

```
@Route("")
@Viewport("width=device-width")
public class MyApp extends Div {
  public MyApp() {
    setText("Hello world");
  }
}

class MyPageConfigurator implements PageConfigurator {
  @Override
  public void configurePage(InitialPageSettings settings) {
    if (settings.getBrowser().isAndroid()) {
      settings.setViewport("width=960");
    } // else, the @Viewport value is used, the getter should return what has been set in the annotation
  }
}
```

### Acceptance Criteria
- There is a `PageConfigurator` interface with one method `void configurePage(InitialPageSettings settings)`
  - This is triggered only on the initial page load
  - allowed only on one class, throw clear deployment time error if it is in multiple places
- `InitialPageSettings` contains (for now) the following input:
  - `VaadinRequest` the initial request
  - `UI`
  - `AfterNavigationEvent` - meaning the navigation target has been resolved and possible redirects done
  - `WebBrowser`
- I'm able to override the `@Viewport` annotation value via `void setViewport(String)` method in the `InitialPageSettings`.
- There is documentation for this in the Initial Page Settings from #3008

**Comment by Legioth** [comment]
> allowed only on one class, throw clear deployment time error if it is in multiple places

Please done require more classpath scanning. What's wrong with my original suggestion that it's only allowed on navigation targets or router layouts that don't have a parent?

**Comment by caalador** [comment]
First implementation is made the way @Legioth originally suggested.
This is quite simple to move if the DX is would be better the other way.
