### ISSUE TITLE
Styling documentation is misleading

### ISSUE THREAD

**Issue by vaadin-kim** [vaadin/flow#3042]
https://vaadin.com/docs/v10/flow/get-started.html#flow.tutorial.margin

"Styling Vaadin Flow applications is easy, we can just add whatever CSS directives we wish into the style file src/main/webapp/frontend/styles.html. For example, to make the UI feel a bit more airy, add the following lines just before </style> closing tag:"

This doesn't apply for CSS targeted for code within a template and thus feels misleading. I would suggest adding a section about theming templates.

**Comment by pleku** [comment]
Still need to update the tutorial, there is now proper documentation available for scoping the styles.
