### ISSUE TITLE
The 'custom-elements-es5-adapter.js' script should not be loaded in IE11

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#3062]
When serving a Flow application to a ES5 browser (IE11), the Flow server should not inject the `custom-elements-es5-adapter.js` script into the HTTP response. Currently it does, and that leads to run-time JS errors:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/22416150/33306981-83986ee0-d41d-11e7-8013-7b3457223991.png">

<img width="576" alt="image" src="https://user-images.githubusercontent.com/22416150/33306994-966d99c8-d41d-11e7-8a4c-4fbd0fc064be.png">

Note: the `custom-elements-es5-adapter.js` script is intended to be used only when serving ES6->ES5 transpiled custom elements to the browsers that do support ES6 (Chrome, Firefox, Safari, Edge).

Since Flow detects the browser's ES5/ES6 support and serves the correct bundle (transpiled code for ES5 browsers, and non-transpiled code for ES6 browsers), it would not end up serving transpiled code to the browsers that do not need transpilation. Therefore, I do not see any scenario where using `custom-elements-es5-adapter.js` would make sense at all.

**Comment by SomeoneToIgnore** [comment]
Fixed in https://github.com/vaadin/flow/pull/3064
