### ISSUE TITLE
Create IT tests for Flow starters

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#3068]
Without any tests, starters are tend to be broken as the time passes and the only way to detect it is manual testing.
This is tiresome, useless, annoying and usually happens when you need to do anything else but fixing the bugs in the starters.

Most of the errors are connected with UI part and most of the starters do not have any logic in them, so unit tests are pretty useless in this case, hence IT tests should be introduced.

IT tests should cover both development and production modes, since both should be represented in them.

IT tests were not introduced before because of many reasons combined:
* Selenium tests are considered less preferable than TestBench ones, since we may end up implementing TestBench functionality for starters
* TestBench tests are considered as a no-go in public part of the starters, because starters' users may not have the TestBench license which is a bad thing for the first user experience
* There is an intention to have starters as simple as possible
* There should be as less junk as possible in starters since they are packed in zips that are available at vaadin.com

Considering the restrictions, most viable approach seems to be standalone private project, downloading starters' wars and testing them in both modes (dev and production).

Other alternatives may be:
* another branch with tests in each starter (hard to keep up to date with the main project due to increased chance of getting conflicts; concept is counter intuitive for newbies)
* standalone module that would be excluded from the zip file (still complicates the project set up)

Starters to cover with tests:
- [x] https://github.com/vaadin/skeleton-starter-flow (nice to start with, only button with text are in the project)
- [x] https://github.com/vaadin/skeleton-starter-flow-spring
- [x] https://github.com/vaadin/beverage-starter-flow (relatively complex project with multiple views and custom logic)

Discussion: https://vaadin.slack.com/archives/C6RAXJATF/p1511868958000039

**Comment by SomeoneToIgnore** [comment]
skeleton-starter-flow ITs: https://github.com/vaadin/flow-starters/pull/1

**Comment by SomeoneToIgnore** [comment]
Spring starter seems to be hard to approach due to Spring issues:
1. If we use current version of Jetty (old one), it will fail to start due to having `spring-boot-logging` with log4j dependency that has Java 9 class that this old version of Jetty fails to load
1. spring-boot-plugin fails to run in one module with classes in another
1. Newer Jetty version fails to start because of Atmosphere framework failing to find `ContinuationListener` and https://github.com/Atmosphere/atmosphere/issues/978 does not help
1. There may be more issues, see https://docs.spring.io/spring-boot/docs/current/reference/html/howto-traditional-deployment.html#howto-create-a-deployable-war-file

**Comment by Legioth** [comment]
> Spring starter seems to be hard to approach due to Spring issues:

Is this problem only related to creating an IT, or will regular users also have the same problems?

**Comment by SomeoneToIgnore** [comment]
It depends on how users approach to testing and which servlet container will be used.
I would say it's more ours problem than the users'.

If they will be using `spring-boot-plugin` and have IT tests in the same project, they're fine
If they will be trying to use Tomcat with the current set up, the might be fine.
If they will be using any other servlet container, they need to manually exclude `spring-boot-starter-tomcat` from our `flow-spring-boot-starter` and hope that Atmosphere works (for Jetty you need to add the dependency from the ticket above)
If they will be trying to run tests from a different Maven module, they will have full spectre of issues we have currently.

Also, current war built by the spring starter is incorrect by another reason (apart from having dependencies for Tomcat only): frontend resources appear to be lost somewhere in the depths of `META-INF` directory and are not available to requests when run from Jetty.

**Comment by Legioth** [comment]
Ok. Could you ensure there are tickets for the stuff that aren't specific to our way of running integration tests? At least the issue with frontend resources seem like something that we should fix quite quickly since it might cause lots of problems for users.

**Comment by SomeoneToIgnore** [comment]
Sure.

**Comment by SomeoneToIgnore** [comment]
https://github.com/vaadin/skeleton-starter-flow-spring/issues/26

I propose to fix those problems before returning to creating IT tests for the module.
