### ISSUE TITLE
Port the flow-component-renderer webcomponent (and related server-side classes) to use the virtual children mechanism introduced with #2826

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#3077]
After #2826 is implemented, the `flow-component-renderer` webcomponent should be updated to not use the DOM anymore, and components that support component renderers (such as Grid) should be updated to use the new structure as well.

**Comment by Legioth** [comment]
I'd suggest that instead of changing Grid to support a different kind of component renderer, the render API itself would instead be changed so that components wouldn't have to do anything special for supporting component renderers.
