### ISSUE TITLE
Provide an easy way to get all elements demos available via a single dependency

### ISSUE THREAD

**Issue by paulroemer** [vaadin/flow#3091]
At the moment I am forced to add each and every element that provides a demo manually into our POM. This works already for the elements itself (they are provided by vaadin platform dependency) but does not work for the 'demo' classfier.

**Comment by pleku** [comment]
This is about having a `flow-component-demo` artifact which has all the component demos and it uses the platform version, instead of the current way of having all the component demos in their own repositories... we need to fix this before V11.

**Comment by denis-anisimov** [comment]
Aaah, OK, thanks.

**Comment by pleku** [comment]
This is not in the plans at the moment. Will be revisited if we make a sampler type of thing where the demos will be, but that is an issue for flow.
