### ISSUE TITLE
Spike: investigate how the server side may mark component as "hidden"/"invisible"

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#3122]
See #2209.

The main issue is about blocking the client side to send events to the server-side.
At the moment we don't have any mechanism for that.

Regardless of client side behavior ( whether the DOM element is detached from the DOM tree or it's just hidden via property/attribute) we need to send request to the client that we need to "hide" it.
We cannot use regular properties for that since it's open API which can be used to set property by the developer. So we can't collide with this.

It means that we need a dedicated (not implemented at the moment) way to say to the client to "hide" the element.
This task is not about doing this on the client side ( there will be another ticket for that) but investigate which way can be used to inform the client.

The available ways are: 
- Execute JS on the client (providing the dedicated JS function on the client side which does it). There can be issues with that similar to attach by @Id  functionality. So it needs to be considered carefully. 
- Reuse `ElementData`  `payload`  data to notify the client side about need to hide the element. The payload data is used in `VirtualChildrenList` feature. So it needs to be checked that the existing functionality based on payload doesn't collide with the new one ( on the client side the payload presence for the element may be considered as an indicator of VirtualChild. In this case the logic will  require adjustment).
- Some another (totally new) mechanism.

The result of the investigation should be: the chosen way with some short explanation about what needs to be done and what issues should be considered to avoid collisions with the existing functionality.

**Comment by denis-anisimov** [comment]
The resulting issue is : #3136.

- Executing JS: don't see serious issues but we will need to keep the state on the client side somehow. Which means JS execution is not enough and some additional storage will be required on the client side. It means that we need to keep the state. And that solved with the `StateNode`s and their features.
- As I said above: we need to keep the state of this "visibility" "feature". So the node features is the most appropriate solution here.

I would avoid reusing `ElementData`payload.
Several reasons for this:
- We may want to use the feature for the elements which has no this feature.
- The payload is resent completely when it's changed. It means that the change request will contain also parts of the data that are not changed.
- The payload also needs to be replaced ( not changed as an existing object) otherwise there will be changes noticed by the feature. It means that the previous value of the payload should be copied, copy updated and set replacing the previous value. It's not convenient.

So let's create a new feature derived from the `NodeValue` and use its value as a switch between "on" and "off".

**Comment by Legioth** [comment]
Would it make sense to "upgrade" `ElementData` to be a `ModelMap` instead of abusing an array?

**Comment by denis-anisimov** [comment]
May be not , may be yes.

As I remember the main reason to have `NodeValue` was a memory consumption issue.
Since every element uses `ElementData`  there will be `HashMap` in memory for each `ElementData`  per `Element`.
Another argument: `ElementData` is used only by plain element. So it won't be possible to use anything from `ElementData`  for text node e.g. (not sure about usecase for that).

On the other hand,  "visibility" is quite rarely used comparing to `ElementData` usage.
So it's an overhead to convert `ElementData` from single value wrapper to `HashMap` just because additional "visibility" key.

So I would say no.
But I'm not 100% sure.

**Comment by Legioth** [comment]
Wouldn't it use even more memory to introduce yet another `NodeFeature` that would be used for all element nodes?

**Comment by denis-anisimov** [comment]
I don't know. May be.
But that's we may avoid: do not create the feature until it's required.
Right now it's created immediately in the `StateNode` CTOR.
