### ISSUE TITLE
Create a new feature for "visibility" functionality

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#3136]
This is a result of #3122

I think it's better to use a dedicated feature for this.

So what should be done:
- extend `NodeValue` feature and make a new feature which has only one value (Boolean)
- Register the feature (`NodeFeatures`, `NodeFeatureRegistry`, tests, etc.)
- Add it to the providers which should support this feature (definitely `BasicElementStateProvider`, most likely has no sense for the `ShadowRootStateProvider`, probably should be in the `BasicTextElementStateProvider` ?)
- Add Element API method which sets the value for the feature.

No any client side code should be written here.
This is quite simple task for the server-side code only.
The only challenge here is: select a name for the feature and the API method name.

**Comment by pleku** [comment]
Any updates for the state tree or rpc calls for the nodes that have been hidden (or child nodes) should be discarded by the server side.

**Comment by pleku** [comment]
Naming for the `Component` API is still open.

**Comment by pleku** [comment]
The name shall be `Component.setVisible(boolean visible)`, which is the same as in previous Vaadin Framework versions.
