### ISSUE TITLE
Using Vaadin 10.0.0.alpha9/Flow 10.0.0.alpha13/vaadin-grid-flow 1.0.0.alpha3 with bower fails with grid._createPropertyObserver is not a function

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#3137]
Please see the bug report here: https://github.com/vaadin/vaadin-grid/issues/1152 . Could it be that the bower-installed vaadin-grid 4.1.0-alpha1 (and 4.1.0-alpha2) is somehow incompatible with vaadin-grid-flow 1.0.0.alpha3 ?

**Comment by heruan** [comment]
Same here, lots of `gridConnector.xxx is not a function`.

**Comment by Artur-** [comment]
Cause by https://github.com/vaadin/flow/pull/3088 and requires all components to be recompiled with the latest Flow version

**Comment by mvysny** [comment]
@heruan yup I agree. Could you please open a bug report at vaadin-grid-flow?

**Comment by heruan** [comment]
Since @Artur- said all components needs to be rebuild, I guess the team will fix this one shot and I'm not sure they'll need an issue on each repo.

**Comment by ZheSun88** [comment]
In fact,  all the other components should work, and 'grid' is under working, so the fix will come after next flow release.

**Comment by mvysny** [comment]
@ZheSun88 is it thus true that Grid doesn't work in Vaadin 10 alpha9 (or rather vaadin-grid-flow 1.0.0.alpha3) and I should wait for a fixed version of vaadin-grid-flow please?

**Comment by Legioth** [comment]
Can this issue be fixed now when https://github.com/vaadin/vaadin-grid-flow/issues/43 is closed, or is there still also something that we need to do in Flow?

**Comment by heruan** [comment]
No more an issue for me in Grid. @mvysny do you feel this can be closed?

**Comment by mvysny** [comment]
I'm waiting for https://github.com/vaadin/beverage-starter-flow to be updated so that I can verify that everything works.
