### ISSUE TITLE
Dynamically inlining resources for initial response

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3139]
`When building an app, I want to inline different resources to body element to the initial response based on the opened browser, so I may only inline content when necessary`

Add the same API as with #3036 to `PageConfigurator` but with option to add for `<body>` instead of `<head>`

### Acceptance Criteria
- I'm able to dynamically inline data to `<body>` on `PageConfigurator` based on e.g. what browser was opened.

**Comment by caalador** [comment]
Only thing not implemented on this in 3036 is the body /head targeting and everything goes to head.

**Comment by pleku** [comment]
Updated the description about inlining to `<body>`.

**Comment by mshabarov** [comment]
This should be possible now with `AppShellConfigurator`.
