### ISSUE TITLE
Flow goes into infinite loop on the app start up when a webjar dependency has a `//` folder

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#3142]
If a project has a webjar dependency with the contents like below (note the double slash), the `com.vaadin.server.DefaultDeploymentConfiguration#getWebComponentsPolyfill()` method goes into an infinite loop on the application startup.

```
/webjars/vaadin-ordered-layout/
/webjars/vaadin-ordered-layout/1.0.0-alpha3/
/webjars/vaadin-ordered-layout/1.0.0-alpha3/common.html
/webjars/vaadin-ordered-layout/1.0.0-alpha3/ordered-layout-basic-demos.html
/webjars/vaadin-ordered-layout/1.0.0-alpha3/index.html
/webjars/vaadin-ordered-layout/1.0.0-alpha3/demos.json
/webjars/vaadin-ordered-layout/1.0.0-alpha3//
```

**Comment by heruan** [comment]
Notice that WebJars like that are corrupted (see https://github.com/webjars/webjars/issues/1679).

**Comment by SomeoneToIgnore** [comment]
Until the next Flow version is released with the fix, you may want to add a new repo to the project:
```
<repository>
            <id>webjars</id>
            <url>https://dl.bintray.com/webjars/maven</url>
        </repository>
```

this one has the same WebJar with the correct paths.
