### ISSUE TITLE
BeforeNavigation is executed twice

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/flow#3151]
If View implements BeforeNavigationObserver then the beforeNavigation method is executed twice on each navigation.

Can be easily reproduced in beverage starter (flow 1.0.0.alpha11):
https://github.com/vaadin/beverage-starter-flow/commit/d34e52f281aedbe273c48667c878c946ac4915af

Implement BeforeNavigationObserver in MainLayout.
See that you will stop in beforeNavigation twice:
1. NavigationStateRenderer.executeBeforeLeaveNavigation
2. NavigationStateRenderer.executeBeforeEnterNavigation

**Comment by caalador** [comment]
Yes this is as implemented. it comes one time for DEACTIVATING state and one time for ACTIVATING state. if it comes twice then the same component is used both in the deactivating and activating component chains.

If you only want one event then you should implement BeforeEnterObserver or BeforeLeaveObserver to get one event in the wanted state.

**Comment by Legioth** [comment]
Are there any semantical differences between the two states? If not, we might consider whether it would be less confusing if the two occurrences would be combined.

**Comment by caalador** [comment]
There was a decision to remove the BeforeNavigationObserver and only support  BeforeEnterObserver and BeforeLeaveObserver.

This will make it clearer when they will be fired and you can still get both events by just implementing both observers so you aren't loosing any functionality.
