### ISSUE TITLE
Demo and Tutorial for Component Feature formerly known as Visible

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3152]
`When building an app, I want to hide/show some components like error messages easily, so I don't have to initialize and add them to the layout always`

`When using the Tabs component, I want to have the contents of the different tabs present in the DOM but not visible or intractable, so that when the user changes the tab I can get the new contents render very quickly and without writing lots of code`

`When building an app with templates, I want to hide an id mapped component / nested template easily from server side code, so I can be productive and not write the logic into the template`

### Acceptance Criteria
- There is a demo for the `Tabs` component to set inactivated tab contents as "hidden" once the tab changes.
- There is "Flow Component Basic Features" tutorial that introduces this feature and explains what it does, showcasing it with hiding e.g. edit button, error message or something similar
- It should be clear from the documentation to know how to use this with a template (using `@Id` mapping)
- The javadocs for the `Component.setVisible(boolean visible)` need to very clearly explain what does setting the component to invisible mean, e.g.:
  - no updates from client->server
  -  what goes from server->client
      - child elements ?
      - properties / attributes ?

**Comment by denis-anisimov** [comment]
The javadocs for the `Component.setVisible(boolean visible)` need to very clearly explain what does setting the component to invisible mean, e.g.:
 - no updates from client->server: if the element is not visible then nothing goes from the client side to the server side (all RPC are discarded on the server side currently and may be even client side won't send anything at all). It affect the invisible component itself and all its descendants.
 -  what goes from server->client: Attach/Detach events are always sent. Generally speaking: no user-aware updates are sent except visibility state. User aware updates are changes done via API (not implementation). Those are: new children, no updates in existing children, no properties/attributes updates. On the implementation level: if the element is initially invisible then only changes in required (reported) and visibility features are sent (values from required/reported features are necessary to be able to choose a strategy which needs to be applied on the client side to bind element. Such features normally are not updated: they get their values only once at the element creation and those values don't change anymore). If the element has been initially visible then only visibility changes are sent while it invisible. Once the element becomes visible all changes that have been done while it has been invisible (along with new ones if any) are sent to the client side (the same true for children of invisible element).

The latter is the description how it works from the implementation point of view. You can look at https://reviewable.io/reviews/vaadin/flow/3213 for exact code.

This implementation description will need to be converted to user friendly API description for JavaDoc. So it shouldn't mention any features but describe it from the point of view of Element/Component API mutation methods of course.
