### ISSUE TITLE
improve the DX of InitialPageSettings.addLink()

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#3163]
When using the `InitialPageSettings#addLink()` method to add favicon tags I would have to write significantly more code compared to that in `BootstrapListener#modifyBootstrapPage()`. I believe that this should and can be improved.

Example:
```java
public void modifyBootstrapPage(BootstrapPageResponse response) {
	final Element head = response.getDocument().head();

	head.append("<link rel=\"shortcut icon\" href=\"icons/favicon.ico\">");
	head.append("<link rel=\"icon\" sizes=\"192x192\" href=\"icons/icon-192.png\">");
	head.append("<link rel=\"icon\" sizes=\"96x96\" href=\"icons/icon-96.png\">");
	head.append("<link rel=\"apple-touch-icon\" sizes=\"512x512\" href=\"icons/icon-512.png\">");
	head.append("<link rel=\"apple-touch-icon\" sizes=\"192x192\" href=\"icons/icon-192.png\">");
	head.append("<link rel=\"apple-touch-icon\" sizes=\"96x96\" href=\"icons/icon-96.png\">");
}
```
vs.
```java
public void configurePage(InitialPageSettings settings) {
	HashMap<String, String> attributes = new HashMap<>();
	attributes.put("rel", "shortcut icon");
	settings.addLink("icons/favicon.ico", attributes);

	attributes.clear();
	attributes.put("rel", "icon");
	attributes.put("sizes", "192x192");
	settings.addLink("icons/icon-192.png", attributes);

	attributes.clear();
	attributes.put("rel", "icon");
	attributes.put("sizes", "96x96");
	settings.addLink("icons/icon-96.png", attributes);

	attributes.clear();
	attributes.put("rel", "apple-touch-icon");
	attributes.put("sizes", "512x512");
	settings.addLink("icons/icon-512.png", attributes);

	attributes.clear();
	attributes.put("rel", "apple-touch-icon");
	attributes.put("sizes", "192x192");
	settings.addLink("icons/icon-192.png", attributes);

	attributes.clear();
	attributes.put("rel", "apple-touch-icon");
	attributes.put("sizes", "96x96");
	settings.addLink("icons/icon-96.png", attributes);
}
```

A few examples that come to my mind is
```java
settings.addLink("icons/icon-96.png", attr("rel", "apple-touch-icon"), attr("sizes", "96x96"));
...
public static KeyValueTuple attr(String key, String value);
public void addLink(String href, KeyValueTuple... attributes);
```
or with a fluent API
```java
settings.addLink("icons/icon-96.png")
  .withAttribute("rel", "apple-touch-icon")
  .withAttribute("sizes", "96x96");
```
or with a specific API for favicons:
```java
settings.addFavIcon("icons/icon-96.png", FavIconType.APPLE_TOUCH_ICON, "96x96");
```

**Comment by pleku** [comment]
For this we would recommend you move all the html to another file and instead inline that directly.
It looks kind of bad anyway to try to build _this much html_ from Java code, no matter what API you use, so using a separate file would make the most sense.

We need to improve the documentation by adding an example of the external file (with e.g. this specific case) to highlight that the best practice for adding lots of html is to inline it from another file.

**Comment by Legioth** [comment]
I don't agree that it would be better to use HTML for this (especially not until such a feature is implemented). Another reason for avoiding HTML is that it forces Java-centric developers to use HTML, prevents doing things dynamically and spreads out related concerns over multiple files.

I like the suggestions for a shorthand specific for favicons. The fluent API also seems promising, except that I think `rel` should probably be used instead of `href` as the starting point so that the qualifying information is written out in the code before the actual data. I'm not very fond of the suggested `attr` API since it assumes static imports.

I would also suggest adding shortands for the most common cases, e.g. `rel` + `href`: `settings.addLink("manifest", "manifest.json")`.

**Comment by pleku** [comment]
>I don't agree that it would be better to use HTML for this (especially not until such a feature is implemented). 

We have that feature, just have to emphasize that in the documentation (for this ticket).

>Another reason for avoiding HTML is that it forces Java-centric developers to use HTML, prevents doing things dynamically and spreads out related concerns over multiple files.

I see, we should merge the Java code with the Polymer Templates too ? Like JSP ? :trollface:

>I like the suggestions for a shorthand specific for favicons.
I would also suggest adding shortands for the most common cases, e.g. rel + href: settings.addLink("manifest", "manifest.json").


Created #3203, for Fluent API please create an issue.
