### ISSUE TITLE
InitialPageSettings.addInlineWithContents() creates a <span> in the document head

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#3168]
When using `InitialPageSettings.addInlineWithContents()` to add inline HTML to the initial response, that HTML is wrapped into a `<span hidden></span>` and appended to the `<head>` of the document. Having a `<span>` inside the `<head>` element is [invalid HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head#See_also). (Chrome automatically moves such `<span>` into the `<body>`).

Example:
```java
settings.addInlineWithContents(
		"<link rel=\"shortcut icon\" href=\"icons/favicon.ico\">" +
		"<link rel=\"icon\" sizes=\"192x192\" href=\"icons/icon-192.png\">" +
		"<link rel=\"icon\" sizes=\"96x96\" href=\"icons/icon-96.png\">" +
		"<link rel=\"apple-touch-icon\" sizes=\"512x512\" href=\"icons/icon-512.png\">" +
		"<link rel=\"apple-touch-icon\" sizes=\"192x192\" href=\"icons/icon-192.png\">" +
		"<link rel=\"apple-touch-icon\" sizes=\"96x96\" href=\"icons/icon-96.png\">",
		Dependency.Type.HTML_IMPORT);
```

results in
```html
<head>
  ...
  <span hidden>
    <link href="icons/favicon.ico" rel="shortcut icon">
    <link href="icons/icon-192.png" sizes="192x192" rel="icon">
    <link href="icons/icon-96.png" sizes="96x96" rel="icon">
    <link href="icons/icon-512.png" sizes="512x512" rel="apple-touch-icon">
    <link href="icons/icon-192.png" sizes="192x192" rel="apple-touch-icon">
    <link href="icons/icon-96.png" sizes="96x96" rel="apple-touch-icon">
  </span>
  ...
</head>
```

Note: the type constant `Dependency.Type.HTML_IMPORT` looks really confusing in this context because it's not adding an HTML import.

**Comment by Legioth** [comment]
`Dependency.Type` might not make sense for inlining dependencies. The `STYLESHEET` and `JAVASCRIPT` values are indeed similar between both cases, but `HTML_IMPORT` is really weird. 

For inlining, it might make more sense to have a new annotation like `WrapMode` with the values `NONE`, `JAVASCRIPT`,  and `STYLESHEET`.

**Comment by pleku** [comment]
Should be investigated after #3221
