### ISSUE TITLE
InitialPageSettings.addLink() adds a <link> element to the document body

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#3169]
When using `InitialPageSettings.addLink()` to add a `<link>` element, that link is added to the body of the document. `<link rel="shortcut icon" href="icons/favicon.ico">` inside the `<body>` element does not work (links should be in the document head)

Example:
```java
Map<String, String> attributes = new HashMap<>();
attributes.put("rel", "shortcut icon");
settings.addLink("icons/favicon.ico", attributes);
```

results in
```html
<body>
  ...
  <link href="icons/favicon.ico" rel="shortcut icon">
  ...
</body>
```

Expected behavior: the `<link>` element should be appended to the head of the document by default.

**Comment by Legioth** [comment]
According to the code, the `<link>` element is added to the `<head>` tag, which is also the case with my testing view:
```
@Route("link")
public class LinkPage extends Div implements PageConfigurator {
    public LinkPage() {
        setText("Page with link");
    }

    @Override
    public void configurePage(InitialPageSettings settings) {
        settings.addLink("Added link");
    }
}
```

The end of the resulting HTML is like this:
```
  <script type="text/javascript" defer src="./../VAADIN/static/client/client.nocache.js"></script>
  <link href="Added link">
</head>
<body><noscript>You have to enable javascript in your browser to use this web site.</noscript></body>
</html>
```

Did you check the generated HTML or the effective DOM that the browser produced? Sometimes, the browser chooses to move things to different parts of the DOM e.g. if some parts are invalid in the location defined by the HTML. Could this be happening in your case?

**Comment by vlukashov** [comment]
Either this is not reproducible (and can be closed as such), or it has to do with other bits of the initial page configuration that might have been added before calling `settings.addLink()`.

**Comment by Legioth** [comment]
Could you leave a temporary branch in the Bakery repo where this is reproducible?

**Comment by vlukashov** [comment]
I've checked the HTTP response and indeed the `<link>` elements are in the HEAD. But since they are _after_ a `<span hidden></span>` Chrome moves them to the document body along with the `<span>`.

It looks like this ticket can be closed.
