### ISSUE TITLE
Validate Flow, Flow Maven Plugin and Components

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3172]
We should run a build which builds and validates together
- flow
  - flow-documentation can be skipped since it currently depends on the components that are not built yet
- flow-maven-plugin
- all the components
  - this uses the previously build flow version

and then validates flow-demos against the build versions.

This can be done with by building snapshots or by building something to staging and testing against the staged version. The advantage of staging something is that then this could be used as a first part of the release build. 

This should be anyway something that is a _pre-step_ for any release of flow or our artifacts.

**Comment by ahie** [comment]
Current project is at https://bender.vaadin.com/project.html?projectId=FlowStaging&tab=projectOverview. The chain is as follows:

Flow Staging, which contains flow, flow-component-base and flow-maven-plugin -> all components built, tested and staged separately -> composite build that gathers all the components -> close the staging repo.

Running "Flow Staging" runs the whole chain. Before running the build you should verify that each of the version parameters is set correctly, for Flow Staging that is flow.version, flow.maven.plugin.version, flow.component.base.version; for each component build separately the parameter is component.version. To not stage some component, the maven plugin or the component base you simply disable the "deploy" build step for it.

More builds can be added to this chain after the staging repo closing step, such as releasing the staging repo or validating starter/demo projects with it.

There seems to be some issue with the environment the build is running in at the moment, causing a single binder test to fail (which tests custom localization of messages). So the verification step for flow in the Flow Staging build has been disabled for the moment to test the rest of the build chain. This needs to be investigated and the build step should then be re-enabled.

**Comment by pleku** [comment]
Thanks, Great Job @ahie 🥇
