### ISSUE TITLE
Improve Spring documentation based on DX feedback

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3179]
- https://github.com/vaadin/flow/blob/master/flow-documentation/spring/tutorial-spring-basic.asciidoc#spring-boot
  - Add a link to Spring Boot official docs
  - Clarify that the `@SpringBootApplication` handles the magic of making your app bootful
- https://github.com/vaadin/flow/blob/master/flow-documentation/spring/tutorial-spring-basic.asciidoc
  - Split the Spring Boot and Spring Web Application to separate pages (move web app to its own page) and add clarity on the beginning that _this it for using X, see link-to-Y for foobar_.  
- https://github.com/vaadin/flow/blob/master/flow-documentation/spring/tutorial-spring-scopes.asciidoc
  - Add a link to the Vaadin Session documentation which explains what is Vaadin Session #3177
  - Add a link to the UI lifecycle documentation which explains the UI lifecycle
- https://github.com/vaadin/flow/blob/master/flow-documentation/spring/tutorial-spring-scopes.asciidoc
  - Remove the `Bean` interface, and instead just have two `Service` classes with both Session and UI scoped (no need to have the interface definition there)
  - Explain that the services are now for the ui/session
- Add a list of things to the README for [the tutorial](https://github.com/vaadin/flow-spring-tutorial) that list the things the tutorial has
  - e.g. adding a service initialization listener

**Comment by denis-anisimov** [comment]
#3336 is created for the scopes improvements to be able to unblock this ticket and make all other changes.

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/spring #276](https://github.com/vaadin/spring/issues/276) via [**ZenHub**](https://www.zenhub.com/)
