### ISSUE TITLE
Add an example on using Flow I18N with Spring

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3180]
### Acceptance Criteria
- There is an example of using an I18NProvider bean via Spring in the [flow-spring-tutorial](https://github.com/vaadin/flow-spring-tutorial)
  - pends on #2928 
  - just show a label for a localized test from I18NProvider and a button for switching to the other available locale 
- There is a section in the flow spring documentation that says that this is possible and people should look at the tutorial code for an example
  - the documentation should only briefly highlight what is needed for this to work

**Comment by heruan** [comment]
As a side note, it would be really great to just be able to expose a `I18NProvider` bean, instead of setting the servlet parameter.

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/spring #275](https://github.com/vaadin/spring/issues/275) via [**ZenHub**](https://www.zenhub.com/)
