### ISSUE TITLE
When using a hot deploy solution I want to clear relevant class metadata caches so that updating a bean works without a server restart

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3186]
If you have e.g. a bean that you use with Binder, you can add a field + getters/setters to the bean but Binder will not pick up the new property because `BeanPropertySet` contains
```
private static final ConcurrentMap<Class<?>, BeanPropertySet<?>> instances = new ConcurrentHashMap<>();
```
which is not updated when the new class is deployed or the class is modified.

If there was a global method for cleaning all class meta data caches, then it should be trivial to e.g. create a https://github.com/HotswapProjects/HotswapAgent plugin for Flow

**Comment by Legioth** [comment]
I think we should use `ReflectionCache` throughout the framework and then make all `ReflectionCache` instances register themselves in a shared location that allows resetting them all at once.

**Comment by Legioth** [comment]
I've created https://github.com/vaadin/flow/pull/3968 for making it possible to clear all `ReflectionCache` instances. There might still also be some caches that don't use `ReflectionCache`.

**Comment by Artur-** [comment]
Has not encountered any problems so far when using https://github.com/HotswapProjects/HotswapAgent/tree/master/plugin/hotswap-agent-vaadin-plugin. Closing this so more specific issues can be opened in the future, if needed
