### ISSUE TITLE
add JustifyContentMode.CENTER

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow#3190]
FlexLayouts have the rest of the settings, but not this. Please add to enum.

**Comment by heruan** [comment]
I've documented the enums and added the missing value in https://github.com/vaadin/vaadin-ordered-layout-flow/pull/19. I can split the changes in a different PR, if needed.

**Comment by heruan** [comment]
@tmattsso Now that #19 is merged, do you feel this can be closed?

**Comment by tmattsso** [comment]
Yup, I'll close.
