### ISSUE TITLE
Provide a default logger for empty flow projects

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow#3193]
Currently, empty flow projects default to a no-op logger (because slf4j behaviour). This results in projects not logging anything at all, which is very, very confusing for users. The situation can be fixed by e.g. adding slf4j-simple to the classpath; but users shouldn't need to know this.

Please figure out a way to provide a logger out of the box when users start fresh.

**Comment by Legioth** [comment]
I guess this mostly applies to starters.

**Comment by pleku** [comment]
Should be enough to add `slf4j-simple` to the starters:
- [ ] https://github.com/vaadin/skeleton-starter-flow
- [ ] https://github.com/vaadin/skeleton-starter-flow-spring
- [ ] https://github.com/vaadin/beverage-starter-flow

The components demos might be missing logging too, but that could be added to `flow-component-base` if necessary. The later on added component starter should have logging also there.

**Comment by tmattsso** [comment]
If we have any maven archetypes, those need a logger as well.

**Comment by tmattsso** [comment]
All of the projects pleku mentioned have a configured logger already.  I wonder if there are any 'quick start' guides somewhere that might need this too?

**Comment by pleku** [comment]
All of the three starters have, for some reason, these dependencies:
```xml
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
```

For `skeleton-starter-flow-spring` it might be so that there are no version conflicts when deploying the app to jetty/tomcat, but I have no idea why they are required for the plain skeleton and BeverageBuddy starters. 

>If we have any maven archetypes, those need a logger as well.

Don't have.
