### ISSUE TITLE
add convenience API for enabling scrolling in FlexLayout

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow#3194]
with the removal of Panel, V10 is missing a Java API to enable scrolling for any layout. Please to add.

**Comment by mvysny** [comment]
I agree: Panel's scrolling was vital for Vaadin 8-based apps. We need such mechanism with Vaadin 10 as well, especially if one uses the `@BodySize(width = "100vw", height = "100vh")` layouting approach (which is default for Vaadin 8 and actually near-impossible to change).

**Comment by Legioth** [comment]
As a workaround before this is implemented with a proper Java API, you can do something like `someComponent.getElement().getStyle().set("overflow", "auto")`.
