### ISSUE TITLE
Create theme class for Lumo

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#3199]
Create a class `Lumo extends AbstractTheme` that can be
used for enabling use of Lumo theme.
Note! there should be no dependecy from flow to vaadin-lumo-styles (vaadin-lumo-theme) webjar

**Comment by jouni** [comment]
> Note! there should be no dependecy from flow to vaadin-valo-styles (vaadin-valo-theme) webjar

Why not? I think the theme should import and include the shared style modules that affect the whole page (typography and colors).

**Comment by Legioth** [comment]
Vanilla Flow should be decoupled from our web component implementations. Valo only makes sense when also using our elements, and it should therefore defined as a dependency for each of the component API modules instead of being required directly by Flow.

**Comment by heruan** [comment]
Then maybe `Valo extends AbstractTheme` should be in its own `flow-theme-valo` module?

**Comment by jouni** [comment]
> Vanilla Flow should be decoupled from our web component implementations.

Not necessarily true. An app could just want to use the shared styles, like fonts and colors defined in the main Valo package, without actually using any of our elements. A developer could be building all elements by themselves, but still use the shared styles from Valo.

**Comment by Legioth** [comment]
@jouni In that case, I think it's best that the developer explicitly adds the required dependency instead of we automatically always putting it there.

**Comment by heruan** [comment]
I agree with @Legioth and @jouni both: from my perspective, shared styles should be usable independently from the elements, but not included by default in Flow. I would then depend on:

- no use of Valo at all: no dependencies
- use of Valo shared styles: `flow-theme-valo` (or whatever 😄)
- use of Valo shared styles and e.g. Button: `flow-theme-valo`, `vaadin-button-flow`

**Comment by pleku** [comment]
### Acceptance Criteria
- There is documentation about how Valo can be the used in your app
- All the starters should be updated to use Valo theme by default. This will have to wait for a platform release, but the PRs can be made

**Comment by pleku** [comment]
PRs for starters have been made, closing this for now.
