### ISSUE TITLE
Flow components are deployed in maven without sources and javadocs

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3206]
When debugging in Eclipse, I cannot debug components because source are unavailable.

https://maven.vaadin.com/vaadin-prereleases/com/vaadin/vaadin-grid-flow/1.0.0.alpha4/
https://maven.vaadin.com/vaadin-prereleases/com/vaadin/vaadin-combo-box-flow/1.0.0.alpha4/

Other artefacts in the framework are correctly deployed

https://maven.vaadin.com/vaadin-prereleases/com/vaadin/flow-client/1.0.0.alpha14/

**Comment by pleku** [comment]
For the next round of components alphas, the sources & javadocs should be available.
