### ISSUE TITLE
Custom Validator is checked on any keypress, though it should be on focus out

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3229]
When having a custom validator in a text field, I would like to be error-notified when I blur, but not in each key press,  at least for the very first time that I focus the empty field to write content, otherwise it might be on each key press (as current is) when the notification message is already displayed.

For instance with this code
```
binder.forField(customerNumber)
	.withValidator(number -> number.replaceAll("[ -]", "").matches("^\\+?(?:[0-9] ?){6,14}[0-9]$"),
		"type a valid phone number")
	.bind("customer.phoneNumber");
```

I get validation error message very early as shown in this screenshot 

<img src="http://g.recordit.co/WzByTPhbQJ.gif">

**Comment by pleku** [comment]
This is due to the fact that the values are submitted to server on each input value change on client. 

Related to https://github.com/vaadin/flow/issues/467

**Comment by pleku** [comment]
This can be handled for `TextField`, `PasswordField` and `TextArea` without #467 by introducing the `ValueChangeMode` with two options:
- `EAGER` that corresponds to the current mode of synchronizing the `value` for every `value-change` event on the client side. Currently this is fired for each key press that changes the `value`.
- `ON_BLUR` that corresponds to synchronizing the `value` only when the `blur` event has happened.

### Acceptance Criteria
- Introduce `ValueChangeMode` enum and `HasValueChangeMode extends HasValue` interface to `flow-data`
  - `ValueChangeMode` has two options for now:
    - `EAGER`
    - `ON_BLUR`
  - `HasValueChangeMode` has the API for controlling the `ValueChangeMode` for the component
- Apply the `HasValueChangeMode` to `TextField`, `TextArea` and `PasswordField`.
  - The default value should be changed for all to `ON_BLUR`
  - Add a demo for `TextField` for using the `EAGER` mode as e.g. filtering a contents in a label (or something)

**Comment by manolo** [comment]
BTW, why is flow using `value-changed` instead of `change` event which should be a more  standard way?
Probably we might align all our elements with the spec and send `input` on keystroke and `change` on blur, thus flow has a common way for listening to one or another depending on when it's interested on running the server validation.

**Comment by SomeoneToIgnore** [comment]
> Introduce ValueChangeMode enum and HasValueChangeMode extends HasValue interface to flow-data

`HasValue` is located in `flow-server`, should it be better to put `HasValueChangeMode` and `ValueChangeMode ` there also?  Or vice versa? Maybe it's better not to extend anything and just put everything into `HasValue`?

**Comment by SomeoneToIgnore** [comment]
> BTW, why is flow using value-changed instead of change event which should be a more standard way?

Do you mean those `@Synchronize(property = "value", value = "value-changed")` annotations that our generator produces?

**Comment by heruan** [comment]
> Probably we might align all our elements with the spec and send input on keystroke and change on blur

I agree, see also #3379 which enables any `Component` to these "standard" events.

**Comment by heruan** [comment]
Currently `HasValue.ValueChangeEvent` and `ChangeEvent` are somehow redundant: the former is not bound to any DOM event and is used in many components implementing `HasValue`, the latter is bound to the `change` DOM event and only used in the `Input` native HTML component.

As a developer I find it confusing to use two different event names/classes for the same event semantic and I'd expect the change event to trigger by default when the user has committed the change (as stated in [MDN Event reference](https://developer.mozilla.org/en-US/docs/Web/Events/change)), otherwise I'd listen to the [`input` event](https://developer.mozilla.org/en-US/docs/Web/Events/input).

**Comment by manolo** [comment]
> otherwise I'd listen to the input event.

It is inside the shadow boundaries, so you should not listen to it directly, since it's part of the implementation details

**Comment by heruan** [comment]
@manolo Of course, I didn't mean the `input`-element's event, but the `input`-event itself on the `vaadin-text-field` (see https://jsfiddle.net/heruan/fx04smtu/).

Currently, the `value-change` event acts the same as the `input` event (triggers at every input). I'd expect the former (possibly renamed to `change`) to trigger only when the user has committed the change, as it happens with native elements.

**Comment by manolo** [comment]
Agree.
For the flow point of view, I wouldn't use value-changed event at all in binders, value-changed might behave different depending on the element, for instance it does not happen the same in combo-box, date-picker and text-field, in the last one value property changes each time the text does, but in others text input means filtering but not value change. Thus the best option seems to  modify flow to rely on standard `change` event.

**Comment by SomeoneToIgnore** [comment]
Put on hold before https://github.com/vaadin/flow/issues/3395 is resolved.
