### ISSUE TITLE
Kill webjars-bom when stable elements are available

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#3236]
Clone https://github.com/vaadin/platform/ got to `vaadin` directory and run `mvn dependency:tree`

Expected: all dependencies are stable and won't change unpredictably
Actual: `vaadin-upload-flow` webjar dependencies are not fixed:
![screen shot 2018-01-02 at 16 58 47](https://user-images.githubusercontent.com/2690773/34487719-3de0c0be-efde-11e7-87e7-6881065cefa6.png)

This is bad, since it means that users won't be able to have a stable builds: any minor updates will be picked up automatically.

We should also think of the way of automatically testing this on/after each flow snapshot run.

**Comment by pleku** [comment]
Since we will kill the web-jars BOM after we get stable versions of the elements available, I understand that this won't be an issue.

Renaming the issue to remind that the whole webjars-bom should go away.
After that, this is more an issue for the `vaadin-core` bom in the platform and there I think it is handled already.

**Comment by pleku** [comment]
We've still waiting for the last final releases of the web components.

**Comment by ZheSun88** [comment]
Web-Components, stable versions, haven't been released
[Check Here for the list](https://github.com/vaadin/flow/blob/master/flow-components-parent/flow-webcomponent-api-analyzer/bower.json)
- [ ] vaadin-combo-box
- [ ] vaadin-date-picker
- [ ] vaadin-dialog
- [ ] vaadin-form-layout
- [ ] vaadin-notification
- [ ] vaadin-tabs
- [ ] vaadin-upload

**Comment by Artur-** [comment]
Isn't this only related to what's in the bom, i.e. transitive dependencies? These are already final?

**Comment by ZheSun88** [comment]
actually, you are correct, because all the dependencies in the `webjars-bom` are stable versions.  Thanks @Artur-
