### ISSUE TITLE
Move generator functionality into flow-maven-plugin

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#3239]
Current workflow for using generated components is cumbersome.
If we need to update any of the frontend dependencies and we have a Java wrapper generated for it, we need to:
* update bower.json and the bom file to the new version
* fix the transitive dependencies in the bom file, if needed (see https://github.com/vaadin/flow/issues/3236 to understand why it's needed)
* generate the components in flow repo (because the generator is in the flow repo)
* **copy and paste** the generated files to the corresponding component repo
* ensure that it works, release the component, etc

Copy pasting step looks totally unnecessary and our users had shown interest in the generator.
It seems more beneficial and easy to move it to flow-maven-plugin, since it has already implemented a lot of the functionality required by the generator.

The following modules should be removed from flow and, if necessary, moved to flow-maven-plugin:
* flow-code-generator – just a user interface of the plugin, most probably should be moved without major changes
* flow-code-generator-api – the generator, uses analyzer output files to generate the classes, most probably should be moved without major changes
* flow-generated-components – contains the generated classes, should be removed completely
* flow-webcomponent-api-analyzer – should be moved, requires changes, but not the hure ones.

Changes required to be done in `flow-webcomponent-api-analyzer`: 
* Remove bower.json dependency in https://github.com/vaadin/flow/blob/master/flow-components-parent/flow-webcomponent-api-analyzer/lib/js/analyzer-transform.js#L87-L91 since flow components use WebJars instead of raw bower components and there simply will be no bower.json
* Replace `frontend-maven-plugin` bower install calls with WebJar unpacking, the unpacking is already implemented in the plugin 
* Replace `frontend-maven-plugin` gulp calls with corresponding Java gulp calls, plugin already has the example of doing this via Java code

Intended workflow, sufficient for our current component generation needs is:
* user adds the plugin into his project, configures it, if needed (specify license header, the correct goal to run generation in, etc)
* the plugin automatically unpacks all project's webjars into the directory specified and run analyzing and generation afterwards

**Comment by SomeoneToIgnore** [comment]
Recent findings that require further attention:

* https://github.com/vaadin/flow/issues/4477

Turns out that some components depend on each other in a way that they import a component and then declare that a JS class `extends` one of the classes imported.
In the case when we split the bower.json into multiple smaller `bower.json` in each component repo, we might get a situation where there's nothing to import, but we still extend the non-imported class.
In this case the analyzer silently generates the data that shows that there's no inheritance at all.

We should modify the analyzer and fail if such situation occurs otherwise we risk generating incorrect classes after the split.

* https://github.com/vaadin/flow/issues/4479

Does not really impacts us, but may cause problems for new components added.
Do not need to fix now, need to keep it in mind.

**Comment by caalador** [comment]
Closing issue as the generator is not used anymore nor is it a part of the project.
