### ISSUE TITLE
Add HasLabel

### ISSUE THREAD

**Issue by henrikerola** [vaadin/flow#3241]
I have the following Vaadin 7 code, which I ported to Flow.

```
private Field<?> createField(FilterBy filterBy) {
  if (filterBy.getType() == Date.class) {
    return new DateField();
  }
  return new TextField();
}

private Field<?> doCreateField(FilterBy filterBy) {
  Field<?> field = createField(filterBy);
  field.setCaption("Search For");
  return field;
}
```

I ended up with the following solution with Flow because there is no a superclass or an interface which would contain the `setLabel` method:
```
private Component createField(FilterBy filterBy) {
  if (filterBy.getType() == Date.class) {
      return new DatePicker("Search For");
  }
  return new TextField("Search For");
}
```

I think that there could be a `HasLabel` interface implemented by all Components which have a label. That would simplify the above solution.

**Comment by Artur-** [comment]
Something like

```
/**
 * A component that supports a label.
 * <p>
 * A label is typically shown above or to the left of the component itself. In
 * Vaadin Framework 8, the term <code>caption</code> was used for a label.
 *
 * @author Vaadin Ltd
 */
public interface HasLabel extends HasElement {

    /**
     * Set the label of the component to the given text.
     * <p>
     * Any HTML is automatically escaped to prevent injection attacks.
     *
     * @param label
     *            the label text to set
     */
    default public void setLabel(String label) {
        getElement().setProperty("label", label == null ? "" : label);
    }

    /**
     * Gets the label of the component.
     *
     * @return the label of the component or <code>""</code> if no label has
     *         been set
     */
    default String getLabel() {
        return getElement().getProperty("label", "");
    }
}
```

would be useful.. Requires updates to the component generator etc

**Comment by pleku** [comment]
>Would this apply to buttons and icons as well? Is this about accessibility labels or just visual field labels?

I believe this was intended to the components with the `label` property that shows the visual field label.

Do you @jouni see this should also automatically map to the `aria-label` attribute ? I see that `vaadin-text-field` has the `aria-labelledby` attribute in the `input` element, but when the `label` attribute is not automatically mapped to `aria-label` there.

**Comment by jouni** [comment]
> Do you @jouni see this should also automatically map to the aria-label attribute?

Possibly. Requires testing (all our components with labels) that it does not interfere with announcing other pieces of content inside an element. With a quick test (macOS Safari & VoiceOver) it doesn’t seem to do harm.

**Comment by pleku** [comment]
OK. @tomivirkki I don't know where to create an issue for testing and then possibly implementing this to some of our web components with the `label` property.

This issue can be kept for detecting the `label` property in the generator and then adding the `HasLabel` mixin interface for those components in Java.

**Comment by pleku** [comment]
Lets keep this issue just for the server side mixin interface `HasLabel`

### Acceptance Criteria
Add `interface HasLabel extends HasElement` with methods
- `default void setLabel(String label) {getElement().setProperty("label", label); }`
- and getter for `label` property
- `default void setAriaLabel(String ariaLabel) { getElement().setAttribute("aria-label", ariaLabel); }`
- getter for `aria-label` attribute

Make the flow-component-generator map the `label` property to the `HasLabel` mixin interface. I don't think there is anything yet available for this.
- create a registry that maps a property to a mixin interface, see
https://github.com/vaadin/flow/tree/master/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry and then check this registry when generating API for properties in
https://github.com/vaadin/flow/blob/master/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java

**Comment by tomivirkki** [comment]
I don't why only the components that have a `label` property should have dedicated API for `aria-label`. For example, grid uses `aria-label` in some of the examples https://cdn.vaadin.com/vaadin-grid/5.3.3/demo/ even though it doesn't have a `label` property

**Comment by pleku** [comment]
Yes it would be a separate issue to add `aria-label`Java API to e.g. `Grid` and `Button`.

**Comment by vaadin-miki** [comment]
bringing this to attention, as I have yet another customer project in which having `HasLabel` would greatly help

**Comment by pleku** [comment]
As updated the acceptance criteria above https://github.com/vaadin/flow/issues/3241#issuecomment-470517630 the `aria-label` is not part of this and should be done separately as it needs a bit more thought. I think it can be added later on and doesn't need to be tied to this one.

**Comment by ovidiupopa91** [comment]
HI @pleku  I can work on this issue.

**Comment by pleku** [comment]
Thanks for the contribution @ovidiupopa91 !

Interface is added in Flow 3.2 and will be in Vaadin 17 but it is another story to take it into use in our components.

Basically all field components should get it, but it is an open question if those want to override the getter method and retain the existing behavior or not. If you're up for it @ovidiupopa91 , you can start with https://github.com/vaadin/vaadin-text-field-flow

**Comment by ovidiupopa91** [comment]
> Thanks for the contribution @ovidiupopa91 !
> 
> Interface is added in Flow 3.2 and will be in Vaadin 17 but it is another story to take it into use in our components.
> 
> Basically all field components should get it, but it is an open question if those want to override the getter method and retain the existing behavior or not. If you're up for it @ovidiupopa91 , you can start with https://github.com/vaadin/vaadin-text-field-flow

Hi @pleku . No problem :) Yes, I can start with https://github.com/vaadin/vaadin-text-field-flow. Will you open a new issue in the repository page?

**Comment by mvysny** [comment]
I see that the `HasLabel` interface has been created, *but nothing implements it* (not TextField, and most importantly not Checkbox which uses different label mechanism than the 'label' attribute), which makes the fix completely useless.
