### ISSUE TITLE
Add StreamResource shorthands to Anchor

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3243]
Currently, the user needs to create an `Anchor` instance without a `href` (or use a dummy `href` with the two-args constructor) and then do `anchor.getElement().setAttribute("href", myStreamResource)` for creating a link to a dynamically generated file.

We could introduce a an `Anchor(StreamResource href, String text)` constructor and an `setHref(StreamResource href)` overload to make this case easier to use. Similar shorthands could also be introduced for setting the `src` of `com.vaadin.flow.component.html.Image`.

**Comment by heruan** [comment]
Should the overload use `PropertyDescriptor` to set the attribute or `Element::setAttribute` would be fine? Using of `PropertyDescriptor` might be inconsistend since AFAIK there's no way to get the original `StreamResource` afterwards.

**Comment by heruan** [comment]
Plus, testing fails because it does not allow setter overloading with different argument type than the getter 😕

**Comment by Legioth** [comment]
I think using `setAttribute` is more appropriate than `PropertyDescriptor` since there won't be any getter.

I guess some exceptions would have to be added to the generic testing logic...
