### ISSUE TITLE
Spring @EventListener support in component

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#3252]
When building a PWA with Flow and Spring, I'd like my components able to react on server events using Spring's `@EventListener` and `@TransactionalEventListener`. For example:

```java
@Route("users")
public class UserList extends Grid<User> {

    // ...

    @EventListener
    public void onNewUser(NewUserEvent event) {
        UI.getCurrent().access(getDataProvider()::refreshAll);
    }

}
```

At the moment it seems like `@EventListener`-annotated methods in `@Route`-annotated components are not invoked when the observed event is published.

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/spring #272](https://github.com/vaadin/spring/issues/272) via [**ZenHub**](https://www.zenhub.com/)
