### ISSUE TITLE
flow-component-api-analyzer doesn't work properly on windows machine for new structured element

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#3254]
when i am using the analyzer on *new structured* element, it doesn't generate the `.json` file on Windows machine, but works fine with linux and Mac(maybe). 

  tested with two Windows and one Linux

**Comment by SomeoneToIgnore** [comment]
As mentioned earlier, the issue seems to be caused by https://github.com/vaadin/flow/blob/master/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L329

**Comment by ZheSun88** [comment]
related discussion was in slack https://vaadin.slack.com/archives/C6RAXJATF/p1515414342000177
