### ISSUE TITLE
UI.push() does not consider beforeClientResponse

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3256]
`UI.push()` contains a performance optimization that skips doing the actual push if nothing has changed. This logic is based on whether any node in the state tree has been marked as dirty, but it doesn't consider cases where no node is yet marked as dirty, but there is a `beforeClientResponse` that might cause a node to be marked as dirty. This can be observed by running only `DataProvider.refreshAll()` inside an `access` block.

This should preferably be fixed in a way that avoids doing the full push procedure in case when there are `beforeClientResponse` tasks in the queue but all of them are bound to state nodes that are currently not attached.

There are also some other pieces of data that cause data to be sent to the client but that are not taken into account in the push optimization logic. This includes at least pending `executeJavaScript` and added dependencies.

**Comment by Legioth** [comment]
A working workaround would be to do `anyAttachedComponent.getElement().getNode().markAsDirty()`.

**Comment by ROB-64** [comment]
Seeing this issue with calling function on polymer template. Function was not invoked until I set a property.
