### ISSUE TITLE
PolymerTemplate does not work with WebJars

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#3263]
Extending `PolymerTemplate` to create a component for a Polymer Web Component included in a WebJar does not work, as it throws e.g.

```
java.lang.IllegalStateException: Can't find resource 'frontend://bower_components/google-map/google-map.html' via the servlet context
com.vaadin.flow.component.polymertemplate.DefaultTemplateParser.getTemplateContent(DefaultTemplateParser.java:106)
com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:122)
com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:62)
```

Since the file is available if requested directly with the browser, I guess the way the parser look for it does not cope well with the WebJar exposing mechanism.

**Comment by caalador** [comment]
The template file directly from the servlet context as a resource. 
The problem here is that the actual file is not found under `bower_components/google-map/google-map.html` but is actually located under `webjars/google-map/{version.number}/google-map.html`

**Comment by Legioth** [comment]
We might have to provide an additional abstraction on top of `ServletContext.getResource()` that also takes webjars into account in the same way that the request serving logic does.

**Comment by heruan** [comment]
Note that #3643 did not fix this.

**Comment by caalador** [comment]
Would you happen to have a sample snippet?

**Comment by Legioth** [comment]
I got a similar stacktrace with the example project linked from https://github.com/vaadin/flow/issues/3738#issuecomment-376619865. I haven't looked into the issue further since it wasn't the stacktrace I was looking for in the context of that issue.

**Comment by heruan** [comment]
Producing the demo I noticed this happens only when depending on `flow-demo-helpers`, otherwise it works correctly so I guess it was just a dependency issue.
