### ISSUE TITLE
As a Flow user, I want to always see what's wrong with my app.

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#3270]
Currently users, if do not add slf4j logging implementation, may miss all Flow logging, including warnings and errors.

This may be bad when something is broken: without any logging it may be sad to look for a runtime issue like this one: https://github.com/vaadin/flow/issues/3216

It would be more user-friendly to detect logging implementations instead and fall back to `java.util.logging.*` if not found.

We should also print warning about the fallback cause.

Implementation example:
https://github.com/mongodb/mongo-java-driver/blob/12895970ae008b4d83378f79dc8fdd54208084c5/driver-core/src/main/com/mongodb/diagnostics/logging/Loggers.java

**Comment by Legioth** [comment]
So we should introduce our own logging facade just to determine which logging facade to use?

**Comment by SomeoneToIgnore** [comment]
Why not?

**Comment by Legioth** [comment]
Simplicity

**Comment by SomeoneToIgnore** [comment]
As you wish.

**Comment by Legioth** [comment]
Apparent lack of simplicity only means that we should think carefully about the overall ROI of this feature.
* Does it make sense from the user's point of view that logging works differently in different situations?
* Is this the suggested approach with a custom logging facade the simplest solution?

**Comment by jreznot** [comment]
If SLF4J does not find binding in classpath it prints error to stderr showing users that they should configure binding. Moreover, standard Vaadin Maven archetypes may be provided with one of the standard bindings such as slf4j-simple or logback. For advanced developers there is no problem to add slf4j binding to project, for novice - it will be enough to have standard binding in archetypes.

**Comment by pleku** [comment]
Looks like the current approach is fine.
