### ISSUE TITLE
Initial ComboBox.setValue doesn't work

### ISSUE THREAD

**Issue by henrikerola** [vaadin/flow#3274]
The following code doesn't set "Item 2" as a selected item:

```
ComboBox<String> comboBox = new ComboBox<>();
comboBox.setItems("Item 1", "Item 2");
comboBox.setValue("Item 2");
add(comboBox);
```
However, clicking on this button on the same page would select "Item 2":

```
Button button = new Button("Set value");
button.addClickListener(e -> {
  comboBox.setValue("Item 2");
});
add(button);
```

Tested with 10.0.0.alpha11.

**Comment by ZheSun88** [comment]
thought this is quite related to the component itself, so i will move this issue to its own repository. :-)

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-combo-box-flow #37](https://github.com/vaadin/vaadin-combo-box-flow/issues/37) via [**ZenHub**](https://www.zenhub.com/)
