### ISSUE TITLE
Please make Style.set() accept dash-separated CSS styles

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#3286]
When setting the style for an element in Flow, I want to use dash-separated CSS styles such as `flex-shrink`. This is in accordance with the following JS API:

```
document.getElementById("xyz").style["padding-top"] = "10px";
```

(Taken from https://stackoverflow.com/questions/5191478/changing-element-style-attribute-dynamically-using-javascript ).

JavaScript allows two notations: the `[]`/`setProperty` notation, and the dynamic property notation (e.g. element.style.flexShrink). Java does not have support for dynamic properties, thus the only way is to support setProperty which accepts dash-separated CSS styles.

Currently Flow rejects dash-separated CSS styles and fails with an exception; Flow expects camelCase but I believe that contradicts the JS API.

**Comment by Legioth** [comment]
As of https://github.com/vaadin/flow/pull/3272 that was merged yesterday, `Element.getStyle()` accepts both formats.
