### ISSUE TITLE
Get the application theme and replace the html imports for the bundler with theme ones

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#3288]
Make it possible to get the used theme from the class specified with the `@Theme(MyTheme.class)` annotation for the bundler in flow-maven-plugin and to get the theme html import to path used in url translation.

The theme import path only applies to files from (`@HtmlImport`) that have on the import path a march for the baseUrl specified in `MyTheme::getBaseUrl`.

If there are multiple different `@Theme` specified, things should explode with clear message on: _multiple themes are not supported, found this thing X from Y and Z from W_.

**Comment by denis-anisimov** [comment]
@caalador : I'm not familiar with the way the themes work at all.

So please clarify the ticket for me: as I see from the https://github.com/vaadin/vaadin-button e.g. the theme is imported inside the HTML file.
What should I do if I want to use theme other than `lumo` ?
From here https://github.com/vaadin/flow/blob/master/flow-documentation/theme/tutorial-built-in-themes.asciidoc I understood that the `Theme` class file should give a URL translation way which will be used to replace the original one with the URL that refers to the file whose content uses another theme.
Is this correct ?

The first sentence is clear :
>Make it possible to get the used theme from the class specified with the @Theme(MyTheme.class) annotation for the bundler in flow-maven-plugin and to get the theme html import to path used in url translation.

Means extracting somehow the theme from the application as a class.

The second sentence is not clear for me:
>The theme import path only applies to every (@HtmlImport) files that have the import matching the specified theme in a webjar.
Does it mean that:
- the theme should be imported by the component HTML file? So in the case of `vaadin-button` it's `vaadin-button.html` ? Does it mean I should scan the content of the HTML file?
- or it means that the translated URL for the HTML file _IMPORT_ should match (exists in the webjar)?
- any theme that we may to apply to the component should be a part of webjar?

The second question makes me confusing: how may I specify my own theme at all without webjar modification?

**Comment by caalador** [comment]
The base is that our components have the `@HtmlImport` annotation with the import that matches on the pattern `".*/src/vaadin-([\\w\\-]*).html"` Lumo for instance has the BaseUrl as `src/` which should be changed to `theme/lumo/` as per `Lumo::getThemeUrl`

On the fly we check that the target item exists in the servlet resources so that we don't change a possibly working import that matches to a faulty theme import.

webJars are strictly not needed as it works also from a local file that for vaadin-button would be `src/main/webapp/frontend/bower_components/vaadin-button/theme/myTheme/vaadin-button.html` in the application.

**Comment by denis-anisimov** [comment]
>The base is that our components have the @HtmlImport annotation with the import that matches on the pattern ".*/src/vaadin-([\\w\\-]*).html" Lumo for instance has the BaseUrl as src/ which should be changed to theme/lumo/ as per Lumo::getThemeUrl

OK, got it. The question was related to the fact that there is also https://github.com/vaadin/vaadin-button/blob/master/vaadin-button.html which imports the `lumo` theme directly.

>webJars are strictly not needed as it works also from a local file that for vaadin-button would be src/main/webapp/frontend/bower_components/vaadin-button/theme/myTheme/vaadin-button.html in the application.

Alright, the description is confusing then. So technically it doesn't matter whether the file is in the webjar or not but it should be in the end available as a file resource in the frontend directory.

Thanks!
