### ISSUE TITLE
Grid Column .setSortable() doesn't work for vaadin-server 8.2.0

### ISSUE THREAD

**Issue by tr3pek** [vaadin/flow#3298]
After upgrade from vaadin-server 8.1.7 to 8.2.0 some grid-related methods don't work as before.
Especially grid.getColumn(...).setSortable(false) and grid.getColumn(...).setResizable(false).
Despite setting some columns as not-sortable and not-resizable it is still possible to sort/resize them.

**Comment by pleku** [comment]
Issue moved to [vaadin/framework #10524](https://github.com/vaadin/framework/issues/10524) via [**ZenHub**](https://www.zenhub.com/)

**Comment by pleku** [comment]
Hello. Sounds like you've had issues with the Vaadin Framework version 8, not Vaadin Flow (part of Vaadin 10).

Vaadin Framework issues go to https://github.com/vaadin/framework, I've moved this issue to https://github.com/vaadin/framework #10524
