### ISSUE TITLE
Update Spring-boot version from M7 to 2.0 GA

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#3308]
Spring-boot 2.0.0.RC1 has been released and we should update `flow-spring-addon` and `flow-spring-boot-starter` to use it instead of 2.0.0.M7

for the release notes see: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-RC1-Release-Notes

**Comment by heruan** [comment]
> Spring-boot 2.0.0.RC1 has been released

Is it? The [milestone](https://github.com/spring-projects/spring-boot/milestone/80) is due Jan. 25th and I currently don't see published artifacts for RC1.

**Comment by Artur-** [comment]
Now available for real

**Comment by heruan** [comment]
RC2 is also available now.

**Comment by Legioth** [comment]
And GA is claimed for next week: https://twitter.com/snicoll/status/966355424260837381

**Comment by pleku** [comment]
We'll update for 2.0 final next week.

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/spring #270](https://github.com/vaadin/spring/issues/270) via [**ZenHub**](https://www.zenhub.com/)
