### ISSUE TITLE
Regression: `hidden` attribute is set to false when server instantiates the component

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3334]
Having this code, the button is finally shown (hidden attribute is removed) 

```
<vaadin-button id="foo" hidden>Foo</vaadin-button>

@Id("foo")
private Button foo;

```

**Comment by ZheSun88** [comment]
a short investigation with platform `10.0.0.alpha14`.

the `hidden` attribute can be only set via using `button.setVisible(true/false)` api, but if we set the attribute from the template file with `<vaadin-button id="foo" hidden>Foo</vaadin-button>` or `<vaadin-button id="foo" hidden="true">Foo</vaadin-button>`, the attribute will be removed, when server instantiates the component. 

for setting other attribute from template file, it works as expected. (tested with `disabled`).

**Comment by denis-anisimov** [comment]
Why does it remove the attribute when the server instantiates the component?
That's the question.

**Comment by denis-anisimov** [comment]
I know the reason. Let it be assigned to me to avoid wasting time from someone who doesn't familiar with the situation.
