### ISSUE TITLE
Update getting started tutorial

### ISSUE THREAD

**Issue by pekam** [vaadin/flow#3344]
https://github.com/vaadin/flow/blob/master/flow-documentation/introduction/tutorial-get-started.asciidoc

This tutorial has a link to a completed demo application, that is owned by our ex-SVP: https://github.com/hezamu/flow-tutorial/
It's depending on an out-dated version of Flow. We should decide what to do with this project.

Also, the tutorial imports Valo theme via html. It should be updated to use Lumo with current best practices.

These are just a couple of quick observations I made. There might be other out-dated stuff too.

**Comment by pleku** [comment]
>Also, the tutorial imports Valo theme via html. It should be updated to use Lumo with current best practices.

Has been done via https://github.com/vaadin/flow-and-components-documentation/pull/5
