### ISSUE TITLE
When using HotSwapAgent or a similar tool, I want to be able to add model fields without restart

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3346]
Currently if you add a setter to the model, you get
```
java.lang.AbstractMethodError: Method SomeModelClass$.setWebComponentUrl(Ljava/lang/String;)V is abstract
```
when trying to use it

**Comment by Legioth** [comment]
Most likely related to https://github.com/vaadin/flow/issues/3186

**Comment by Artur-** [comment]
Works when using https://github.com/HotswapProjects/HotswapAgent/tree/master/plugin/hotswap-agent-vaadin-plugin
