### ISSUE TITLE
Theme documentation page doesn't mention creating an app theme

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow#3347]
There is no mention on how to use Lumo and adding your own app styles. Also, the 'creating your own component theme' section is pretty confusing.

**Comment by pleku** [comment]
>There is no mention on how to use Lumo

This is very clearly stated in the docs.

> and adding your own app styles.

This was planned as partly with #2428 and #2807, but now it is a bit separate topic (compared to component theming), so closing those since the Valo/Lumo theme usage is there.

> Also, the 'creating your own component theme' section is pretty confusing.

Please create another issue for this and open up a bit more than just saying it is _pretty confusing_, thanks.

**Comment by tmattsso** [comment]
Well, it doesn't show an example of a style file or how to name it. It doesn't show how to set basic CSS properties for classnames you've given to your components. It doesn't show how to override a theme setting for example for all buttons. It doesn't discuss if it makes sense to split your style file into multiple files. 

Also, this sentence doesn't make any sense to me:

> you need to create a theme class that informs flow how to translate the base un-themed component html import to use your themed version.

This sentence doesn't make sense if I don't understand what HtmlImport does, and barely even then

> The getBaseUrl should return the part of the htmlImport that can be used to determine if it is an import that could be changed to a theme import. (for Vaadin Elements that is /src/)

Having to override getHeadInlineContents seems like a cumbersome way just to import files.

In all, I have no idea how to create an app theme based on this document. Remember, our customers will not have any clue on how the theme internals work; they just want to make their buttons red.
