### ISSUE TITLE
flow should update properties when element is detached from the dom

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3351]
Flow seems not being setting properties if the component is not used.

We need workarounds in date-picker and combo-box for the issue as is shown in the next block

```
public class ComboBoxForBinder<T> extends ComboBox<T> {
  @Override
  public void setValue(T value) {
    super.setValue(value);
    if (value != null) {
      getElement().setAttribute("value", getItemLabelGenerator().apply(value));
    }
  }
}
```

Seems related with https://github.com/vaadin/flow/issues/2930 but in this case is not specific of combo-box, it is also happening in date-picker, probably something to fix globally in flow instead of in component wrappers

**Comment by pleku** [comment]
I don't think this is closed

**Comment by caalador** [comment]
Does not reproduce with newest version of date-picker or combo-box.

**Comment by manolo** [comment]
Do you mean you cannot reproduce in Bakery for Flow master if you upgrade versions ?

**Comment by caalador** [comment]
Yes. Problem doesn't occur for the component itself nor in bakery when I tested.

**Comment by manolo** [comment]
Since we are upgrading the version of platform, I'll double check whether this has been fixed after that
