### ISSUE TITLE
Deploying an app on Tomcat 7.0.39 fails with "Skipping automatic servlet registration because there are no navigation targets annotated with @Route"

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3359]
Deploying seemingly any simple app on Tomcat 7.0.39 fails with the cryptic error about no `@Route`s even though there are routes. 

Deploying the same app on Tomcat 7.0.82 (latest 7) logs
`[localhost-startStop-1] INFO com.vaadin.flow.server.startup.ServletDeployer - Automatically deploying Vaadin servlet to /*` but when accessing the app gives `HTTP Status 500 - Servlet 3.1+ is required`

Seems like older Tomcat 7 versions have some issues with `ServletContainerInitializer`.

To make it clearer what is supported and what is not, the Servlet 3.1 detection logic should be moved somewhere earlier than `VaadinServlet` to also catch the cases where no servlet gets deployed.

**Comment by Legioth** [comment]
Should this be split to two separate issues, one about not finding `@Route` in Tomcat 7.0.39 and one about the late complaint about Servlet 3.1 support in Tomcat 7.0.82?

**Comment by Artur-** [comment]
I think the only fix needed is to check the servlet version as early as possible. Does not matter if older Tomcats can't find routes if the old servlet versions blocks deployment with a clear message before it even gets to scanning (or not scanning)
