### ISSUE TITLE
Name of target in flow-maven-plugin does not describe what it does

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3360]
It is quite hard to realize that you should use `transpile-production-files` if you do not care about IE11 but just want to bundle your files (if you should use that?)

**Comment by SomeoneToIgnore** [comment]
How would you expect to see it?

I see two ways: we can split target into two: one for transpilation, one for bundling or rename it to some global `flow-production-mode-build` step.

**Comment by Artur-** [comment]
If it does "all the things", then a name like `package-for-production` would make more sense.
