### ISSUE TITLE
It's difficult to know which version of flow-maven-plugin to use

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3363]
When creating a new project using Vaadin platform `10.0.0.alpha13`, it seems that I somehow need to know that I should use `flow-maven-plugin` `0.0.7` and with the upcoming `10.0.0.alpha14` I should use plugin `1.0.0.alpha18`. 

It does not really help in any way that the Flow Maven plugin is versioned with the same version as Flow because I do not typically want to specify the Flow version in my project (only the platform version).

**Comment by pleku** [comment]
How can we release Flow and the plugin when we don't yet know to which version of the platform do they go with ?

**Comment by Legioth** [comment]
Why do you need know which platform version they would go with when releasing? What if the same Flow or plugin version is used in multiple platform versions?

**Comment by pleku** [comment]
>Why do you need know which platform version they would go with when releasing?

I need to know it before release if I want to release it with the same version as the platform.

Or another option is to release it together with the platform with the platform version number. But then how can I make a Flow release when I cannot release the plugin to work with it ?

**Comment by pleku** [comment]
Also we might do features for the plugin that we want to release without even needing a platform or flow release. Currently it is a part of the Flow release so they get the same version, this was done so that we don't get unsync between those.

Anyways, any good solutions welcome, I do agree that it should be really easy for the users but also let's not make it unnecessarily complex for ourselves either.

**Comment by Artur-** [comment]
If we would do a parent pom in addition to a bom, this would be easy to do there. It would probably require a lot of other things though

**Comment by Legioth** [comment]
While it wouldn't directly help, the problem could be mitigated to some degree there would be metadata in Flow about which Maven plugin version it's supposed to be used with, and the plugin would check for this.

One step further might be to define two version numbers: one that describes the optimal version (i.e. the latest plugin version available for a given Flow release) and one version for the oldest plugin version that is still expected to be compatible (i.e. something that is manually updated whenever potentially incompatible changes are made).

We could then print a warning if there is a mismatch with the optimal version and outright fail (unless the user opts-in through a parameter) for incompatible versions.

**Comment by SomeoneToIgnore** [comment]
Seems to be not relevant anymore, since we have `vaadin-maven-plugin` now.
