### ISSUE TITLE
Summarize what is needed for production

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3365]
https://github.com/vaadin/flow/blob/master/flow-documentation/web-components/tutorial-flow-maven-plugin.asciidoc could use a summary in the beginning stating clear what needs to be done for a production deployment:
1. Bundle
2. Run in production mode, typically by including `flow-server-production-mode` (most people do not run an embedded server to which you give a system property)
3. Something else?

**Comment by Artur-** [comment]
If the plugin can somehow get `flow-server-production-mode` or similar included in the war automatically - even better

**Comment by pleku** [comment]
Closed with https://github.com/vaadin/flow-and-components-documentation/pull/92
