### ISSUE TITLE
Errors from bundled application

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3368]
Bundling https://github.com/Artur-/Solitaire using `mvn clean install -Pproduction` causes the following exceptions in the Chrome:

```
Uncaught ReferenceError: babelHelpers is not defined
```
Maybe  #3321 
```
Uncaught ReferenceError: Highcharts is not defined
```
Vaadin Charts is included through the `com.vaadin/vaadin` dependency but not used. Where does this come from?

**Comment by caalador** [comment]
ES6 problem fixed by #3368 for ticket #3321
