### ISSUE TITLE
ButtonRenderer throws exceptions on the client-side when used for Grid header

### ISSUE THREAD

**Issue by mac-at-vaadin** [vaadin/flow#3374]
When I setup Grid header to use ButtonRenderer I want it to not throw exceptions on the client side when user clicks on a button so that I am not confused why ButtonRenderer doesn't work but ComponentTemplateRender does.

Let's say, I have a column in `myGrid` that displays checkboxes, and as a header I want to have a button that, once clicked, toggles all the checkboxes.

Unfortunately, I cannot use ButtonRenderer for that, because it only allows me to use ItemClickRenderer. Instead I need to setup a ComponentTemplateRenderer which is counterintuitive – at first I wanted to use ButtonRenderer and didn't realise that ItemClickRenderer is meant for items/rows only. I ended up with code that was throwing client-side exceptions, even though server-side compiled fine.

This is the code I had to write:

```java
        myGrid.addColumn(
                new ComponentTemplateRenderer<>(
                        Checkbox::new,
                        (checkbox, item) ->
                        {
                            checkbox.setValue(item.isConfirmed());
                            checkbox.addValueChangeListener(event -> item.setConfirmed(checkbox.getValue()));
                        }
                )
        ).setHeader(new ComponentTemplateRenderer<>(
                Button::new,
                (button, o) -> {
                    button.setText("Toggle confirm for all");
                    button.addClickListener(event -> {
                       items.forEach( item -> item.setConfirmed(!item.isConfirmed()));
                       myGrid.getDataProvider().refreshAll();
                   });
                }));
```

This is the code I'd rather write:

```java
        myGrid.addColumn(
                new ComponentTemplateRenderer<>(
                        Checkbox::new,
                        (checkbox, item) ->
                        {
                            checkbox.setValue(item.isConfirmed());
                            checkbox.addValueChangeListener(event -> item.setConfirmed(checkbox.getValue()));
                        }
                )
        ).setHeader(new ButtonRenderer<Object>("Toggle", event -> {
            items.forEach(item -> item.setConfirmed(!item.isConfirmed()));
            myGrid.getDataProvider().refreshAll();
        } ));
```
but the above code will throw exceptions on the client side when I click on a button in the header.

Maybe rename ButtonRenderer to ButtonItemRenderer?

**Comment by caalador** [comment]
The issue on the bottom is that the ButtonRenderer is a template renderer which executes the script `"$0.%s = function(e) {Vaadin.Flow.sendEventMessage(%d, '%s', {key: e.model ? e.model.__data.item.key : e.target.__dataHost.__data.item.key})}"`

In the case where we are in the header the `__data` is empty so `item` returns `undefined` from which we try to take the `key` value which then fails.

This should perhaps be looked at after #3003 is resolved.
