### ISSUE TITLE
Rename the model converter concept to avoid confusion with Binder converters

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3382]
The names `@Convert` and `ModelConverter` for template models is slightly confusing for at least two reasons:
* The naming is similar to the converter functionality in `Binder`, but there is not functional relationship between the two concepts
* Conversion implies that both types would be used by application code, whereas in this case the concept of encoding for transport and decoding received values would be more appropriate.

For the encoding and decoding analogy, the logical phrase would be `codec`, although this word is mainly associated with audio or video formats. Since most model values are mainly transmitted from the server to the client and only occasionally in the other direction, it might be appropriate to refer to these as encoders that also occasionally take care of decoding.

The suggested base API would thus be:
```
public interface ModelEncoder<D, E extends Serializable> {
  Class<E> getEncodedType();
  Class<D> getDecodedType();

  E encode(D);
  D decode(E);
}

public @interface Encode {
  Class<? extends ModelEncoder<?, ?>> value();
  String path();
}
```

**Comment by pleku** [comment]
Don't forget to update the tutorials, which are at another repository.
