### ISSUE TITLE
Defining the theme for a super class of a view does not work

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3384]
```
@Theme(Lumo.class)
public class AbstractView extends Div {
```

```
@Route("Upload")
public class UploadView extends AbstractView {
```

Fails on deployment with

```
com.vaadin.flow.server.InvalidApplicationConfigurationException: Found configuration annotations that will not be used in the application. 
Move the following annotations to a single route or the top RouterLayout of the application: 
Non RouterLayout: test.AbstractView contains: Theme
```

**Comment by caalador** [comment]
Neither AbstractView nor UploadView is a RouterLayout nor do they define `@Route`.

**Comment by Artur-** [comment]
Added missing `@Route`, which is present on the view class

**Comment by pleku** [comment]
Why is not `AbstractView` actually abstract ? We could skip the error for `abstract class` and `interface` and instead just log on `trace` level.

The use case for having just one location for the `@Theme` for all views in the app is very valid. Same kind of goes for the `PageConfigurator` also. But is it too cumbersome to have a `RouterLayout` just for that ?

**Comment by heruan** [comment]
I'd find useful to have an `AbstractBaseLayout` with `@Theme` and `@Viewport` and also implementing `PageConfigurator`, and then have my `RouterLayout`s extending that class. Having a `RouterLayout` just for that it's lesser intuitive than using class hierarchy (where I can share fields, for example).

**Comment by pleku** [comment]
Should also update our `flow-component-base` to apply `@Theme(Lumo.class)` after this to make it apply the theme for all of out demos.
