### ISSUE TITLE
Excessive logging about RouteNotFoundError not having a @Theme annotation

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3385]
Whenever you refresh a simple app, the following is logged
```
[qtp1312966018-19] WARN com.vaadin.flow.component.internal.UIInternals - No @Theme defined for com.vaadin.flow.router.RouteNotFoundError
```

**Comment by caalador** [comment]
What are you refreshing?
That can only come if you get the exception navigation target RouteNotFoundError.

**Comment by Artur-** [comment]
Refreshing my only view in the app

**Comment by caalador** [comment]
Then please share app.

**Comment by Artur-** [comment]
Seems to come from `GET //localhost:8080/service-worker.js`, which happens because some other app has added a service worker for localhost

**Comment by heruan** [comment]
Best solution would be to add a service worker in Flow too :smile:

**Comment by pleku** [comment]
>Best solution would be to add a service worker in Flow too 

That is another topic, and it is quite easy to do that manually. But it could be made even easier..
