### ISSUE TITLE
Theme's common styles are not included in bundling

### ISSUE THREAD

**Issue by pekam** [vaadin/flow#3434]
For example imports for Lumo's `color.html`, `typography.html` etc. are just inlined to the bootstrap page

https://github.com/vaadin/flow/blob/master/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L41

Currently these files don't end up to the bundler.

**Comment by SomeoneToIgnore** [comment]
Might be good to add notes to bundling/theming documentation for stating that the contents of the method go to the bundle automatically.

**Comment by SomeoneToIgnore** [comment]
> Might be good to add notes to bundling/theming documentation for stating that the contents of the method go to the bundle automatically.

Won't be done: adjusting plugin to get the themes from the method requires lots of efforts.
Instead, changed the theming approach to using @HtmlImports, as discussed before.
This is adjusted in the documentation: https://github.com/vaadin/flow-and-components-documentation/pull/3
