### ISSUE TITLE
Note on docs that two-way binding doesn't work for array properties

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#3435]
Seems like `Array` properties are not kept in sync with server-side `TemplateModel`. For example:

```js
class Foo extends Polymer.Element {
    static get properties() {
        return {
            list: {
                type: Array,
                value: []
            }
        };
    }
    addItem() {
        this.push('list', 'foo');
    }
}
```
```java
interface FooModel extends TemplateModel {
    List<String> getList()
}
```
Calling `addItem()` won't send anything to the server (possibly related to #3399).

**Comment by heruan** [comment]
Seems like sync of arrays was intentionally left out in [SimpleElementBindingStrategy.java#L296](https://github.com/vaadin/flow/blob/8d5f537e0996f85b1ab31f9537bd92f20d936e73/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L296):

```java
if (mapProperty.getValue() instanceof StateNode) {
    // Don't send to the server updates for list nodes
    StateNode nodeValue = (StateNode) mapProperty.getValue();
    JsonObject obj = WidgetUtil.crazyJsCast(valueProvider.get());
    if (!obj.hasKey("nodeId")
            || nodeValue.hasFeature(NodeFeatures.TEMPLATE_MODELLIST)) {
        return;
    }
}

mapProperty.syncToServer(valueProvider.get());
```

Was this by design or just a temporary choice?

**Comment by Legioth** [comment]
Temporary choice based on expected complexity of design and implementation.

**Comment by heruan** [comment]
Got it. In the meantime I'd suggest to add a note in [`tutorial-template-list-bindings.asciidoc`](https://github.com/vaadin/flow-and-components-documentation/blob/master/polymer-templates/tutorial-template-list-bindings.asciidoc) to explain this "one-way only" binding from server to client, since one reading that may expect it to work out-of-the-box (i.e. user updates reflected on the server).

**Comment by pleku** [comment]
I agree. Let's have this issue as a bug for improving the documentation (which has been moved to https://github.com/vaadin/flow-and-components-documentation) and keep the original issue for the feature https://github.com/vaadin/flow/issues/2413
