### ISSUE TITLE
Maven plugin doesn't transpile everything

### ISSUE THREAD

**Issue by pekam** [vaadin/flow#3453]
From Bakery:
```javascript
// This code was generated by the transpiler before (polymer-cli)
for(var f in e)this.$.helper.appendChild(this._createHiddenElement(f,e[f]))

// This is the code generated now. It fails in IE because "element" is not defined and it is in "strict mode"
 for(element in b)this.$.helper.appendChild(this._createHiddenElement(element,b[element]))
```

The code is inside `frontend-es5/vaadin-flow-bundle.html` so it's served from the right place and is included in bundling.
The code is from `<iron-form>`:
https://github.com/PolymerElements/iron-form/blob/v2.0.0/iron-form.html#L250

Maybe the transpilation accidentally excludes some files?
Maybe it doesn't include js that is inside html-files?

It's also weird that in `for (element in json)` -> `for(element in b)` the variable name `element` is not minified, but `json` is.

**Comment by tuliogarcia** [comment]
Some more info.
This file:
```html
<html>
<script>
let stuff = ["1","2"]
for(longvarname in stuff) console.log(longvarname)
</script>
</html>
```

Becomes this is the bundled version:
```html
<div hidden="" by-polymer-bundler=""><script>"use strict";var stuff=["1","2"];for(longvarname in stuff)console.log(longvarname);</script></div>
```
Notice that:
* The code is changed from the original.
* It is invalid, because it is missing the "var" keyword in the for loop.
* It is not minified.

**Comment by SomeoneToIgnore** [comment]
We need to have a look at https://github.com/Polymer/polymer-cli/blob/master/src/build/build.ts or adjacent files and unrerstand what exactly `polymer-cli` had configured to make this happen and what we're missing.

**Comment by tuliogarcia** [comment]
I ran the same code snippet in the babel compiler online and it gave me the same result.

https://babeljs.io/repl/#?babili=false&browsers=ie%2010&build=&builtIns=false&code_lz=DYUwLgBAzmCuBm8IF4IG0BEBGDAaDATBgLoBQ8A9gE4AUwFAdgOYBuAhlQ2wLYgQCWDaHEQBKCAGNGUCqAB09JnUasOXXqNJA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=es2016%2Ces2015-loose&prettier=false&targets=&version=6.26.0&envVersion=1.6.2

So I guess babel is being applied and something else is needed to make it work in IE 11.

**Comment by SomeoneToIgnore** [comment]
Just checked out polymer-cli on the test project with example from Tulio: it produces the same output but without `"use strict"`, so maybe we won't be able to improve it any further then in https://github.com/vaadin/flow/pull/3456

Details:
```
tree
.
├── build
│   ├── polymer.json
│   └── test
│       ├── index.html
│       └── test.html
├── index.html
├── polymer.json
└── test.html
```

```
cat index.html 

```

```
cat test.html 
<html>
    <script>
        let stuff = ["1","2"]
for(longvarname in stuff) console.log(longvarname)
    </script>
</html>
```

```
cat test.html 
<html>
    <script>
        let stuff = ["1","2"]
for(longvarname in stuff) console.log(longvarname)
    </script>
</html>
```

```
cat build/test/test.html 
<html><head><script>var stuff=["1","2"];for(longvarname in stuff)console.log(longvarname);</script></head><body></body></html>
```
