### ISSUE TITLE
Designer templates and @Theme should work together

### ISSUE THREAD

**Issue by johannesh2** [vaadin/flow#3479]
When having an import to an unstyled version of Vaadin element in a template file, which is imported with `@HtmlImport` in an PolymerTemplate and when having `@Theme(Lumo.class)` annotation I expect all the elements to be shown as Lumo-styled. Currently those are displayed unstyled.

**Comment by vlukashov** [comment]
As a developer, I expect that the `@Using(Button.class)` annotation would have the same effect on theming as `@HtmlImport("frontend://bower_components/vaadin-button/src/vaadin-button.html")`. Currently `@Using()` also does not work.

**Comment by pleku** [comment]
Related discussion with proposal on technical solution https://vaadin.slack.com/archives/C6X43FE8M/p1517574511000347

**Comment by caalador** [comment]
For a `PolymerTemplate` in the `TemplateInitializer` we should check the html imports and add them as `@HtmlImport`s to `ComponentMetaData:DependencyInfo` so that the Theme rewrite will be done automatically for when the components are loaded the first time.

The probable place for this would be `ComponentMetaData:findDependencies` where we would get the imports for `PolymerTemplate` and add them as html imports.

**Comment by pleku** [comment]
Opening https://github.com/vaadin/skeleton-starter-flow/blob/master/src/main/webapp/frontend/src/example-template.html with designer and adding eg. `vaadin-text-field` to it will bring the raw import of `<link rel="import" href="../bower_components/vaadin-text-field/src/vaadin-text-field.html">`, which will not be overridden by Flow to the `/lumo/` themed one.

**Comment by pleku** [comment]
I tested this with platform alpha20 which had 1.0.0.alpha22 of Flow, and it still didn't work, so I'm not sure if it ever has.

**Comment by DiegoCardoso** [comment]
This does not seem to work. Was it closed by accident?

**Comment by denis-anisimov** [comment]
There is a PR for it.
It has been closed intentionally.
Please reopen with details how it doesn't work for you.

**Comment by DiegoCardoso** [comment]
For Bakery for Flow, we have added a workaround by adding `@HtmlImport` to some syles that were missing. For instance, at the login page, we added the lumo theme files for `vaadin-button`, `vaadin-text-field` and `vaadin-password-field`. 

At the corresponding template, we have added the unstyled import for each element. 

I was expecting that by removing the `@HtmlImport`s, Flow would then import them by default. But I am still getting the unstyled version of them when running in development mode, while it looks ok when running in production mode.

**Comment by caalador** [comment]
See: https://github.com/vaadin/flow/issues/3907
The fix for that will yet again fix this issue.

**Comment by caalador** [comment]
Functionality has now been tested with sample from 3907 and with bakery login view.

Parser url generator has tests that the relative paths get correctly normalized to a functional format.

Theme has additional test on that the translated url translates correctly.

**Comment by pleku** [comment]
@DiegoCardoso Bakery should remove all the themed imports and use instead the raw ones.

**Comment by DiegoCardoso** [comment]
I believe we are already using the raw imports, but only importing the themes files from the server, so I hope to remove them once the fix is released.
