### ISSUE TITLE
Flow property updates from client -> server are not aware of default values

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3496]
For an Element's boolean property that has a default value of `false`, the Element API will give a default value of `false`. This is the same in browser, since any boolean property is considered `false` until it is set to true.

Internally any property value is stored as `null` in the state tree for elements. 

When Flow is set to synchronize this property from server to client, if no explicit default value is set, then Flow will send an initial update for the value from client->server where the value is `false`.

`ElementPropertyMap` will check for the previous value from the state node, which is `null`, and then decides to fire a property change event for the value, event though the default has no actually changed.
https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java#L181

The client side should be context aware and not send any `false` boolean values to the server, unless the boolean property was explicitly `true` on the client side.

Same should apply for any other properties, there the default is `null` and no synchronization should happen if the value goes to something else. That is probably how it works, did not test.

**Comment by pleku** [comment]
A temporary workaround for this is to set the default values explicitly to `false` in the server side for boolean properties.

**Comment by Legioth** [comment]
> The client side should be context aware and not send any `false` boolean values to the server, unless the boolean property was explicitly `true` on the client side.

This is a slightly dangerous assumption to make. `false == null` is true, but not `false === null`. Depending on the context, the two values might or might not be equivalent.

**Comment by denis-anisimov** [comment]
Take care about `syncToServer` or `setValue` call for _EVERY_ model property regardless of the way how it's fixed .
Every model property should have value otherwise `SimpleElementBindingStrategy::handlePropertyChange` logic won't update property value because of the code : `elementProperties.hasPropertyValue(subProperty)`.

It might be that this code is outdated and is wrong already but you should be aware of it.

**Comment by pleku** [comment]
It seems that the workaround might be enough as a permanent solution since there has not been any updates to this issue in two years.

**Comment by guygoldwasser** [comment]
this issue still an issue. i am straggling use the setInvalid api with no success. also not so clear to me what is the workaround

**Comment by pleku** [comment]
@guygoldwasser can you please create a new issue that describes the problem and how to reproduce it. You can then point to this issue as _similar to #3496_ statement.
