### ISSUE TITLE
Add setEnabled with the generator

### ISSUE THREAD

**Issue by Wnt** [vaadin/flow#3506]
Because the `setDisabled` methods are defined in various classes (e.g. `GeneratedVaadinTextField`, `GeneratedVaadinComboBox`, `GeneratedVaadinButton`) , you need to write boilerplate like:
```java
private void setFieldsEnabled(boolean b) {
	// first two are TextFields, status is a ComboBox and rest are Buttons
	firstName.setDisabled(!b);
	lastName.setDisabled(!b);
	status.setDisabled(!b);
	delButton.setDisabled(!b);
	cancelButton.setDisabled(!b);
	saveButton.setDisabled(!b);
}
```
When ideally the method body would be like:
```java
Arrays.asList((Component)firstName, lastName, status, delButton, cancelButton,
	saveButton).forEach(Component::setDisabled(!b));
```
maybe `Component` is not the right place for that but instead some interface like `HasEnabledness`.

**Comment by pleku** [comment]
It is `HasEnabled` and it will be introduced in https://github.com/vaadin/flow/issues/3538.

Keeping this issue around for it being applied automatically by the component generator.

**Comment by pleku** [comment]
Will be applied for `HasValue` components after #3538, we cannot detect that when it should be applied out of the box to any web component.
