### ISSUE TITLE
listening to change event is not enough to notify changes to binder

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3509]
`change` event is now used in flow to notify value changes in client side, but `change` seems to be fired when user actively blurs the input. The problem, is that if you set `input.value = 'foo'` server is never notified unless the user visit the input by focusing it and blurring it.
This is a problem in tests because it's not easy to prepare the input to set the value and fire the change event.
Not sure if this is something that flow needs to cover (changing values from JS) or TB should be aware of it and fire the change event after setting any value.

Related with:
https://github.com/vaadin/flow/issues/3229

**Comment by pleku** [comment]
Fixed in latest TB https://github.com/vaadin/vaadin-components-testbench/releases/tag/1.0.0.alpha3
