### ISSUE TITLE
improve the development turnaround with IE11 and the flow-maven-plugin

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#3510]
As a developer, I want to have a 'development mode' support for IE11. Currently the flow-maven-plugin does not offer that option. The only way to test the app in IE11 is to run a full production build which is way too slow.

When using bower and polymer CLI it was possible to run only the transpilation step (skip minification and bundling). and just reload the page after modifying an HTML template. (Yes, I had to find the place where the transpiled templates end up, and modify them there). With the flow-maven-plugin the only way to apply changes that I know of is to run a full rebuild which means around 5 minutes to see the effects of a style change.

Some specific requirements:
 - config property to disable minification
 - serve from the filesystem or having incremental build (to have a really quick update cycle when changing a single HTML file)

**Comment by Artur-** [comment]
Development mode works for IE11 in V14
