### ISSUE TITLE
add support for `spring-boot:run` into flow-maven-plugin

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#3514]
As a developer I want to use the Spring Boot maven plugin to run my Flow app in the production mode (because running the `spring-boot:run` maven goal is easier then deploying a .war file to a servlet container, and because it's easier to debug the app started that way). Currently (with the version 1.0.0.alpha19 of the flow-maven-plugin) that requires extra configuration and manual action when re-building the app.

The flow-maven-plugin runs a Gulp build script and outputs production-ready frontend files into the folder defined in the `transpileOutputDirectory` configuration property (`${project.build.directory}/${project.build.finalName}/` by default).

When the app is packaged in a .war file, this would be the context root. That matches the default context paths for the frontend resources expected by Flow (see [`FRONTEND_URL_ES5_DEFAULT_VALUE`](https://github.com/vaadin/flow/blob/7d48dd6589710c8476c777b6d40179e735805501/flow-server/src/main/java/com/vaadin/flow/server/Constants.java#L77)). However, when the app is started with `spring-boot:run`, the context root is `src/main/webapp`, and Flow would search for frontend resources there.

When the app started with `jetty:run`, this can be worked around by instructing the Maven Jetty plugin to add extra resource folders to the context:
```xml
<plugin>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-maven-plugin</artifactId>
    <configuration>
        <webAppConfig>
            <resourceBases>
                <resourceBase>${project.build.directory}/${project.build.finalName}</resourceBase>
            </resourceBases>
        </webAppConfig>
    </configuration>
</plugin>
```
But there is no similar parameters for the Spring-Boot Maven plugin.

A semi-OK workaround for this issue is to configure the Flow Maven plugin to output the transpiled frontend code into a subfolder in `src/main/webapp` (`<transpileOutputDirectory>${frontend.directory}/build</transpileOutputDirectory>`), and then also override the default Flow settings for the frontend resource folders with `-Dvaadin.frontend.url.es5=context://frontend/build/frontend-es5/` and `-Dvaadin.frontend.url.es6=context://frontend/build/frontend-es6/`.

The problem with this workaround (apart from the fact that it adds generated code into the source folder) is that when running the flow-maven-plugin _in the second time_, the Gulp build script fails to clean the output folder (because it is outside of the Gulp's working directory):
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.049 s
[INFO] Finished at: 2018-02-08T11:32:33+02:00
[INFO] Final Memory: 48M/1469M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:flow-maven-plugin:1.0.0.alpha19:package-for-production (default) on project bakery-app-starter-flow-spring: Execution default of goal com.vaadin:flow-maven-plugin:1.0.0.alpha19:package-for-production failed: Transpilation with gulp has failed: 'gulp build_es6' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

That is, this workaround requires deleting the build output folder manually. Please improve the developer experience for this use case.

**Comment by tsuoanttila** [comment]
Would [`<folders>`](https://docs.spring.io/spring-boot/docs/current/maven-plugin/run-mojo.html#folders) work for this?

**Comment by vlukashov** [comment]
@tsuoanttila does not looks like that. The documentation says it adds more folders to the classpath, but apparently not to the context root. I've tried adding the `${project.build.directory}/${project.build.finalName}` folder and that did not add the resources from that folder to the context.

```xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <folders>
            <folder>${project.build.directory}/${project.build.finalName}</folder>
        </folders>
    </configuration>
</plugin>
```

**Comment by vlukashov** [comment]
I ended up using the default config for the flow maven plugin (outputs the transpiled frontend sources to `${project.build.directory}/${project.build.finalName}/frontend-es5` and `${project.build.directory}/${project.build.finalName}/frontend-es6`), and copy the frontend-esX folders into `src/main/webapp/` with the maven resources plugin.

With that approach both the .war context and the `mvn spring-boot:run` context have the frontend files where Flow expects to find them (`/frontend-es5` and `/frontend-es6`). Restarting the app with `mvn spring-boot:run` also works. But that's a manual configuration that ideally should not be there.

**Comment by SomeoneToIgnore** [comment]
Now the plugin is able to remove the external directories: https://github.com/vaadin/flow/pull/3540

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/spring #267](https://github.com/vaadin/spring/issues/267) via [**ZenHub**](https://www.zenhub.com/)
