### ISSUE TITLE
Styling buttons

### ISSUE THREAD

**Issue by ebatgerel** [vaadin/flow#3520]
I created a button and i don;t know how to style button. Any advice ? 
            
Button btn = new Button();
btn.setClassName("waa-toggle");
btn.setIcon(new Icon(VaadinIcons.MENU));

btn.getStyle().set("background", "transparent");

[Documentation](https://vaadin.com/docs/v10/flow/element-api/tutorial-dynamic-styling.html)

**Comment by pleku** [comment]
Hi. You can see an example on the theme variants available for button from the element examples. You can apply the variants with `button.getElement().setAttribute("theme", "primary");`

This should be made easier though. We should have
1. Convenience API on component level for the themable components with preferably the variants somehow available
2. Have a separate demo showcasing those
3. Mention there in the theming documentation

**Comment by marcushellberg** [comment]
IMO something like `button.setTheme(Lumo.Button.PRIMARY)` or similar would be vastly easier than the current approach.

**Comment by heruan** [comment]
Now there's `Element::getThemeList`, e.g. `button.getElement().getThemeList().add("primary")`, but I totally agree with @marcushellberg that a shortcut for themes in the Component API would be better (and a set of theme constants in the `Lumo` class too).

**Comment by marcushellberg** [comment]
Thanks. themeList is already an improvement, although I would rather not have to call getElement() to access it when I'm using the Java API.

**Comment by Legioth** [comment]
`ThemableMixin` suggested in https://github.com/vaadin/flow/issues/3663

**Comment by pleku** [comment]
Duplicate / superceded by https://github.com/vaadin/vaadin-button-flow/issues/45
