### ISSUE TITLE
`(TypeError) : Converting circular structure to JSON` when using `dom:repeat` 

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3530]
This code makes client side raise  `(TypeError) : Converting circular structure to JSON` when having a `dom:repeat` structure inside an element bound via the `@Id` annotation

This is the example code to reproduce:

```
        <vaadin-tabs id="tabs">
          <template is="dom-repeat" items="[1, 2, 3, 4, 5]">
            <vaadin-tab>[[item]]</vaadin-tab>
          </template>
        </vaadin-tabs>
```

```
    @Id("tabs")
    Tabs tabs;
```

Attached a ready to use project, unpack it and run `mvn jetty:run`

[repeat-tabs-issue.zip](https://github.com/vaadin/flow/files/1711846/repeat-tabs-issue.zip)

**Comment by heruan** [comment]
See also https://github.com/vaadin/vaadin-tabs-flow/issues/25

Don't know if this is a real `Tabs` issue or Flow's.

**Comment by pleku** [comment]
Need to verify after vaadin/tabs#25 is fixed.

**Comment by caalador** [comment]
Verified that this works after vaadin/vaadin-tabs-flow#25
