### ISSUE TITLE
Navigating to empty string does not work in Firefox

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#3531]
In Firefox pushing an empty state in History does nothing, e.g. `history.pushState(null, '', '')` won't change the location.

So `ui.navigateTo("")` won't work as excepted, e.g. it will show the component annotated with `@Route("")` without changing the location on the address bar.

This seems more a Firefox issue, but maybe Flow can apply some kind of workaround.

**Comment by vlukashov** [comment]
The same issue affects Safari on OS X (version 12.1)

**Comment by vlukashov** [comment]
This issue has been fixed as #5113 in Flow [1.0.10](https://github.com/vaadin/flow/releases/tag/1.0.10) and [1.4.3](https://github.com/vaadin/flow/releases/tag/1.4.3). Updating to the latest Flow version helped in my case.
