### ISSUE TITLE
Investigate memory consumption in Patient Portla

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#3536]
Use patient portal.
- Open patient list
- Make sure the `Grid` is shown and its data is loaded.
- Check the memory.
- Go to the analytics view and check the memory.

The memory in the analytics view should be much less than in `Grid` view ( do GC to measure).
The reason is : `Grid` with all its data is not referenced from the analytics view at all.
Which means it should not occupy the memory.

If the memory consumption inside analytics view is still big then find the reason why 
(find the root which keeps references to the `Grid` data object).
Create a ticket about this issue.

**Comment by denis-anisimov** [comment]
Patient portal doesn't have "memory leak" anymore (the memory consumption decreases after navigation from the view with `Grid` to the view which has no `Grid`): there are not anymore references to the `Grid` data  if the view doesn't show the `Grid`.

**Comment by sblommers** [comment]
How is this related to flow? Is there a repository using flow?
