### ISSUE TITLE
VerticalLayout's content overflows when inside a Dialog

### ISSUE THREAD

**Issue by Wnt** [vaadin/flow#3537]
VerticalLayout's content overflows when inside a Dialog

![screenshot from 2018-02-12 12-34-09](https://user-images.githubusercontent.com/886091/36093217-b28dbbcc-0ff2-11e8-8e54-2a5edc6e1fb7.png)

Here's the exact same component shown inside a SplitLayout. Here the content is not overflowing:

![screenshot from 2018-02-12 12-34-23](https://user-images.githubusercontent.com/886091/36093271-d1369738-0ff2-11e8-9f3b-b6108ce926c5.png)

Demo app: 
[test_app.zip](https://github.com/vaadin/flow/files/1716032/test_app.zip)

Use `mvn jetty:run` in the project root and navigate to http://localhost:8080 The problematic view can be opened by clicking on a cogwheel icon in the grid.

**Comment by Wnt** [comment]
Maybe it's caused by the fact that Dialog's child elements are inside `<vaadin-dialog-overlay>`'s shadow root and so the application's theme is not applied there?
https://github.com/vaadin/vaadin-dialog/issues/51

**Comment by ZheSun88** [comment]
with the latest components (__those components will be released later today or next week__), I can get the following behavior which should be correct for you

![image](https://user-images.githubusercontent.com/31067185/39036218-83387f66-4485-11e8-983f-bf4ae1371118.png)

@Wnt please verify it after you get the new released component. Issue closed for now and reopen if it is necessary
