### ISSUE TITLE
Add HasReadOnly interface and prevent value change events for read-only components

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3539]
We should add a `HasReadOnly` mixin interface that has getter and setter for `read-only` property.
We should add it to all of our components that have the `read-only` property and *prevent* any value change events originated from client side for components in read only state on the server side.

We should also prevent the change of the read-only property from client side when it has been enabled from server side. Probably we can just disable updating it always.

The value property for the component is determined by the `getClientValuePropertyName()` method in `HasValue`.

**Comment by pleku** [comment]
There needs to be a tutorial for this in the component features and link to that tutorial in the v8-v10 migration documentation.

**Comment by Legioth** [comment]
I don't think we should have any standalone `HasReadOnly` interface. Instead, it would be tied to whether `HasValue.getValue()` is allowed to change based on user-originated changes.

The current implementation doesn't enforce anything related to this on the state node or element level. Instead, `AbstractField` blocks `getValue()` from being updated for client-originated changes and reverts the presentation value to the previously set value. Alternative implementations of `HasValue` that are not based on `AbstractField` will have to explicitly implement their own logic for support for the readonly state.
