### ISSUE TITLE
Annotation to declare modules to include in custom-style

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#3541]
At the moment if I need a style module (e.g. `lumo-badge` from [vaadin-lumo-styles/badge.html](https://github.com/vaadin/vaadin-lumo-styles/blob/v1.0.0-beta1/badge.html)) I need to include it somewhere, e.g. in a `style.html` file which I need to import with `@HtmlImport`:

```html
<custom-style>
  <style include="lumo-badge">
    /* IE ignoring empty styles fix */
  </style>
</custom-style>
```

It would be simpler to have a `@CustomStyleModules({ "lumo-badge", "foo", "bar" })` or similar.

**Comment by pleku** [comment]
This has been made possible for `@CssImport`, which has the `include` property, so is this enough @heruan ?

https://vaadin.com/api/platform/14.0.14/com/vaadin/flow/component/dependency/CssImport.html

**Comment by samie** [comment]
Ok to close this one for now?

**Comment by pleku** [comment]
In case there is still something needed, I would expect a new issue or comments here to make the case for this now that `@CssImport` is available.
