### ISSUE TITLE
Define and test the intended way of getting frontend resources when both WebJars and bower.json are used in the project

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#3548]
Based on https://vaadin.slack.com/archives/C6X43FE8M/p1518522587000161

Given the project that has WebJar dependencies and same dependency in `frontend` directory (for instance, downloaded separately via bower), it's unclear what happens
* in development mode, when we look up the dependency files in runtime: which version will be picked? 
* in production mode build, when the `flow-maven-plugin` unpacks WebJars and copies `frontend` directory contents, which files should be picked?

We should either fail on each case or define which files should be picked.
Also, documentation should be adjusted to describe the cases.

**Comment by Legioth** [comment]
I think it would make sense to support both (though maybe require opt-in through a config param). The basic use case is probably if you want to pull in something that isn't available as a WebJar, while still using WebJars for the regular dependencies.

**Comment by Artur-** [comment]
For me, the use case so far has always been to override webjars with a Bower-version (in development), so the files can be edited when debugging.

**Comment by mcollovati** [comment]
Closing because compatibility mode is not supported anymore in the maintained Vaadin versions.
