### ISSUE TITLE
FileDownloader

### ISSUE THREAD

**Issue by tmbenhura** [vaadin/flow#3565]
There is no implementation of the FileDownloader extension or equivalent.

**Comment by heruan** [comment]
You can simply create a link and set its `href` attribute with a `StreamResource`, e.g.

```java
StreamResource resource = new StreamResource(fileName, () -> fileInputStream);
Anchor link = new Anchor(resource, "Download");
```

**Comment by tmbenhura** [comment]
Thanks. I am currently using a hidden iframe. How do you set the content disposition of the streamResource. In V8 it was:
`streamResource.getStream().setParameter("Content-Disposition", "attachment; filename=myfile.pdf");`

**Comment by pleku** [comment]
Thanks for the feedback. We should probably add an example of this to our documentation to make it more easily discoverable how to do this.

**Comment by johannest** [comment]
Please include an example of this into docs
