### ISSUE TITLE
Virtual children can't have its DOM structure changed when their parent is attached via @Id

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#3569]
This is the root cause of the bug https://github.com/vaadin/flow/issues/3513 (See the comments for more details on the investigation of it).

When a component contains virtual children, and the component itself is attached to the UI via `@Id` in a PolymerTemplate, that internal structure of the virtual children can't be changed (by adding or removing nodes, for instance).

This is clearly reproducible in Dialog and Notification components:

In Dialog, if this line https://github.com/vaadin/vaadin-dialog-flow/blob/0bc2d15116d270966a9608cbebf5a87e1ce05340/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L46 is changed to getElement().appendVirtualChild(container);, the bug reappears.

There is a integration test just for this bug: https://github.com/vaadin/vaadin-dialog-flow/blob/0bc2d15116d270966a9608cbebf5a87e1ce05340/src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithTemplateIT.java

This issue is probably also the root cause of https://github.com/vaadin/vaadin-grid-flow/issues/71

**Comment by pleku** [comment]
It seems that this has not been a huge issue for anyone and might be that it doesn't even manifest anymore.

In case it is important, I'd expect a new issue to be opened, closing this one.
