### ISSUE TITLE
More clear message about missing parameter for router link

### ISSUE THREAD

**Issue by haiwan** [vaadin/flow#3580]
Given: 
A navigation target which implements the HasUrlParameter. And the parameter is not optional
A router link to that navigation target, without specifying a parameter.
Expected:
Error message saying that parameter is missing or sth like this
Actual:
`Caused by: java.lang.IllegalArgumentException: Navigation target 'com.vaadin.training.layout.ex2.ApplicationLayout' requires a parameter and can not be resolved. Use 'public <T, C extends Component & HasUrlParameter<T>> String getUrl(Class<? extends C> navigationTarget, T parameter)' instead
	at com.vaadin.flow.router.Router.getUrl(Router.java:255)
	at com.vaadin.flow.router.RouterLink.setRoute(RouterLink.java:218)
	at com.vaadin.flow.router.RouterLink.<init>(RouterLink.java:136)
	at com.vaadin.training.layout.MainBody.<init>(MainBody.java:17)
	... 48 more
`

**Comment by svenruppert** [comment]
any news here ?

**Comment by caalador** [comment]
Closing issue as the exception in 14.5+ should look like `java.lang.IllegalArgumentException: Navigation target 'org.my.project.View' requires a parameter.` 
If this is still a problem in some version open a new issue with steps to reproduce and which version(s) it is in.
