### ISSUE TITLE
Bakery storefront view can't be shown in production mode using latest Flow snapshot

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3587]
Every time the storefont view is opened (after login), the following error is shown:
```
Failed to instantiate [com.vaadin.starter.bakery.ui.views.storefront.OrderEditor]: Constructor threw exception; nested exception is java.lang.IllegalStateException: There is no element with id='title' in the template file. Cannot map it using @Id'
```

Storefront view has 
```
	@Autowired
	public StorefrontView(OrderPresenter presenter, OrderEditor orderEditor) {
```

OrderEditor:
```
	@Id("title")
	private H2 title;
```

and the order editor template:
```
      <h2 id="title"></h2>
```

To reproduce:
1. Use `master`
2. Add
```
 <dependency>
     <groupId>com.vaadin</groupId>
     <artifactId>flow-server</artifactId>
     <version>1.0-SNAPSHOT</version>
 </dependency>
```
3. Run `mvn -Dvaadin.productionMode -U clean spring-boot:run`
4. Open http://localhost:8080 and login as admin@vaadin.com + admin

**Comment by denis-anisimov** [comment]
I'm not able to reproduce this.

Are you sure that `1.0-SNAPSHOT` doesn't overlap with some release version ?
I've excluded `flow-server` from everywhere and only then added 

```
<dependency>
     <groupId>com.vaadin</groupId>
     <artifactId>flow-server</artifactId>
     <version>1.0-SNAPSHOT</version>
 </dependency>
```

Works for me without any problem.

To exclude versions clash I've also excluded `flow` and added all `flow-*` jars with 1.0-SNAPSHOT version explicitly.
Works in the same way.

And I don't see any reason for the exception.
I will add tests for production mode but this is not a fix.
