### ISSUE TITLE
Comb the desert for framework changes that have been omitted when porting

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3592]
* https://github.com/vaadin/flow/issues/1220 and https://github.com/vaadin/flow/issues/1249 processed all Framework changes from https://github.com/vaadin/flow/commit/1147faa895382c1ed64f3334fd6a7ab8e3b550be (13 Jan 2016, the fork point between Framework and Flow) until https://github.com/vaadin/framework/commit/7f1cfd03d5b55f41ea911fcd53ce6fd168517cff (16 Feb 2017, arbitrary point on `master` between 8.0 and 8.1.0.apha1).
* https://github.com/vaadin/flow/issues/2883 processed changes from https://github.com/vaadin/framework/commit/de70699a93 (20 Mar 2017, first commit in `master` after tagging `8.1.0.alpha1`) to https://github.com/vaadin/framework/commit/7fb7f7d322 (24 Jul 2017, commit in `master` that is tagged as `8.1.0`).
  * **I cannot find any Flow issue that would indicate that anyone has looked at the 111 commits in master between https://github.com/vaadin/framework/commit/7f1cfd03d5b55f41ea911fcd53ce6fd168517cff and https://github.com/vaadin/framework/commit/de70699a93**
* https://github.com/vaadin/flow/issues/2884 processed changes between https://github.com/vaadin/framework/commit/bdb298bfb8c0e1930d0c33d0f5c3fd862e2980d6 (26 Jul 2017, in `master`, first commit after tagging `8.1.0`) and https://github.com/vaadin/framework/commit/83efc2d77e6cee5cc49eb1480577a1bfdc6b35b0 (20 Oct 2017, only on the `8.1` branch, tagged as `8.1.6`).
  * **`master` and `8.1` diverged at https://github.com/vaadin/framework/commit/0f64ae445bae3c6e7a0d7fee1b6db9717e3da59a (11 Aug 2017, between `8.1.1` and `8.1.2`)**
* https://github.com/vaadin/flow/issues/2885 processed changes between https://github.com/vaadin/framework/commit/f5d8dd7bf4 (25 Sep 2017, on `master` between `8.2.0.alpha1` and `8.2.0.alpha2`) and https://github.com/vaadin/framework/commit/607f94e892 (7 Dec 2017, only on the `8.2` branch, tagged as `8.2.0.rc1`).
  * **`master` and `8.2` diverged at https://github.com/vaadin/framework/commit/81b4dfb6728d9455c1db055156c6555b8aa4906b (17 Nov 2017, between `8.2.0.alpha3` and `8.2.0.beta1`)**

There are thus commits in two ranges on Framework `master` that might or might not be missing from Flow.
* https://github.com/vaadin/framework/compare/7f1cfd03d5b55f41ea911fcd53ce6fd168517cff...de70699a93 (111 commits)
* https://github.com/vaadin/framework/compare/0f64ae4...f5d8dd7 (185 commits)

At least in the latter case, some of the commits in that range might be processed because they have also been picked to the `8.1` branch and included from there, but anything that hadn't been picked to `8.1` would be missing, e.g. https://github.com/vaadin/framework/commit/bcf58e21450831c4956366222ee93af9e65d0034 (25 Sep 2017, commit on `master` between `8.2.0.alpha1` and `8.2.0.alpha2`)

Also, care should be taken when continuing porting newer changes to also include everything from `master` after the point when `8.2` was forked.

In the future, *only* changes that are on `master` should be ported. Instead of going through all commits up until the head of e.g. `8.3`, that batch should stop at https://github.com/vaadin/framework/commit/531320c5051b7f72c9d96c7826b5cd4f9dcaae67 which is the last commit before `master` and `8.3` diverged. This commit can be found by running `git merge-base origin/master origin/8.3`.

**Comment by ZheSun88** [comment]
okay, first, i will go through https://github.com/vaadin/framework/compare/7f1cfd03d5b55f41ea911fcd53ce6fd168517cff...de70699a93, these 111 commits, porting the related changes to flow

**Comment by ZheSun88** [comment]
Next, https://github.com/vaadin/framework/compare/0f64ae4...f5d8dd7, these 185 commits.

**Comment by ZheSun88** [comment]
Next, https://github.com/vaadin/framework/compare/8.2.0...8.3 there are 86 commits.
