### ISSUE TITLE
Flow Maven Plugin copies Bower and Polymer JSON files

### ISSUE THREAD

**Issue by oluwasayo** [vaadin/flow#3594]
When building a Flow application I want the plugin to exclude `bower.json` and `polymer.json` so that I do not have to delete them manually before packaging.

Regardless of the `<excludes>` configuration, Flow Maven Plugin still copies the two files to the production directories.

<img width="312" alt="screen shot 2018-02-22 at 14 02 59" src="https://user-images.githubusercontent.com/900868/36537873-18bccffc-17da-11e8-9161-5e858b233149.png">

**Comment by caalador** [comment]
As these are not copied in newer versions I'm closing this ticket.
