### ISSUE TITLE
Flow Maven Plugin preserves empty bower directories

### ISSUE THREAD

**Issue by oluwasayo** [vaadin/flow#3595]
When building a Flow application I want the plugin to delete empty production directories so that they do not get packaged in my deployment.

<img width="382" alt="screen shot 2018-02-22 at 13 45 37" src="https://user-images.githubusercontent.com/900868/36537943-5c8aed68-17da-11e8-94b8-46408cc77fa1.png">

**Comment by mcollovati** [comment]
Closing because compatibility mode is not supported anymore in the maintained Vaadin versions.
