### ISSUE TITLE
Vaadin components web jar URIs cannot be handled by the servlet if it's not mapped into the root 

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#3600]
The original ticket is #3301.
The investigation for it is tl;dr; so I decided to extract here the only issue.

The problem is : if we have servlet mapped to non-root then web jars won't be resolved for existing Vaadin components.

The example is:

```
@WebServlet(urlPatterns = { "/app1/*"}, name = "MyServlet1", asyncSupported = true)
@VaadinServletConfiguration(productionMode = false)
public class MyServlet1 extends VaadinServlet {
}
```
The text field is declared:
```
@HtmlImport("frontend://bower_components/vaadin-text-field/src/vaadin-text-field.html")
public abstract class GeneratedVaadinTextField<R extends GeneratedVaadinTextField<R>>
```

It's URI is the same as  `"context://frontend/bower_components/vaadin-text-field/src/vaadin-text-field.html"`.
And the `context` here is the servlet context.
So if we have `"/"` as the servlet context  (it doesn't matter actually what's exactly the servlet context)
then the servlet is mapped to URL like this: `http://server.com/app1`

But the web jar URI refers to `http://server.com/frontend/...`

It means that the servlet `MyServlet1` cannot serve web jar URL ever. As a result text field will not work unless there is _a dedicated servlet which handles web jar requests_.
This is how done our root context tests e.g.: we have `WebJarsServlet` which handles web jar URIs.

The question is: do we want to preserve this behavior and require to have a dedicated servlet for web jars in this situations ( and this needs to be documented) or we want to provide a way to handle this out of the box.

In the latter case it means that we need to do something with generate HTML import (like `@HtmlImport("frontend://bower_components/vaadin-text-field/src/vaadin-text-field.html")`).

Options are:
- change the meaning of `frontend://` schema. It may be relative to the `servlet context`+ `servlet path` instead of `servlet context` only.
- introduce one more schema which should be used in all our generated components instead of `frontend://` schema.
- keep things as is and require to have a dedicated servlet for web jars (which means that this ticket is invalid and won't be fixed).

There is one more aspect of this issue which is fixed (may be) here: #3590
Please read the very first comment in #3590 to understand what's going on there as well.

**Comment by denis-anisimov** [comment]
This functionality requires discussion and design decision.

@Legioth please take a look.

**Comment by Artur-** [comment]
Isn't this consistent with how FW8 works regarding `/VAADIN`?

If there could be multiple `frontend` folders for the same web application (WAR), then it would mean that you load the same files (e.g. Polymer.html) from multiple places and if you happen to show two UIs at the same thing, it would not work?

If you area not using webjars but Bower directly, you would not create multiple `bower.json` files either

**Comment by denis-anisimov** [comment]
Yes, it's consistent.

That's why there is an option: don't do anything (though it has to be documented).

But apparently it's far away from obvious since there is : #3301.

**Comment by Artur-** [comment]
Maybe a servlet should be autodeployed to `/frontend` if it is not mapped?

**Comment by denis-anisimov** [comment]
Which servlet ?
`WebJarServlet` (additional) ?

**Comment by pleku** [comment]
Whenever the user is adding another servlet or modifying the path for something else than the root path ("/"), they could be given the choices of:
- Automatically deploy another servlet for webjars mapped by default to `/frontend`
- Automatically make this servlet handle also the webjars by adding a proper url mapping to it, which is then context aware
- Not do anything automatically, but in case you have your own webjars servlet in some path, you want to rewrite urls for that path.
  - There should be an additional parameter for providing this path that we will use to rewrite the urls for webjars

We would thus add a mandatory parameter to `@VaadinServletConfiguration` named `webjarsServletMapping`, that takes an enum `WebjarsServletMapping` that has three types corresponding to the above behaviour:
- `WebjarsServletMapping.AUTOMATIC_THIS_SERVLET`
- `WebjarsServletMapping.AUTOMATIC_ANOTHER_SERVLET`
- `WebjarsServletMapping.MANUAL`

**Comment by pleku** [comment]
The feature in itself is an enhancement, but the missing documentation is a bug. At least the latter needs to be fixed before final.

**Comment by Artur-** [comment]
How is this only related to webjars? If I have an add-on with a `my.js` inside `META-INF/resources/frontend`, it should be available. It should also be transpiled and included in a bundle when in production. If I have templates, they are also inside `/frontend` and must be served even for an app mapped as `/app1/*`

Right now the static file serving is an integral part of `VaadinServlet`, so that is what you would need to deploy to `/frontend/*`, `/frontend-es5/*` and `/frontend-es6/*`


For what would a `webjarsServletMapping` parameter be needed?

**Comment by Artur-** [comment]
This is related to the comments in https://github.com/vaadin/flow/pull/3945 and also https://github.com/vaadin/flow/pull/3963

**Comment by mstahv** [comment]
Spotted this issue while going through various enhancement issues (and I'm probably missing something here), but what is the grand idea of the "frontend" directory in general? If that wasn't needed, the default servlet would do the serving without hassles for the stuff in META-INF/resources.

**Comment by pleku** [comment]
The `/frontend` directory is magical since it is the source for the files for transpilation. Thus in production, any frontend url is mapped to the correct resource version (es5 or es6) based on what the browser needs.

**Comment by pleku** [comment]
It should be possible to add a test for this in https://github.com/vaadin/flow/tree/master/flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui but should also be tested with production mode.
