### ISSUE TITLE
afterNavigation on the view is fired twice if there is a layout

### ISSUE THREAD

**Issue by bennewi** [vaadin/flow#3605]
When I annotate my view with 
`@Route(value = BakeryConst.PAGE_SUNBEAM)`

the afterNavigation method is invoked once, but when I change the class only as follows:

`@Route(value = BakeryConst.PAGE_SUNBEAM, layout = MainView.class)`
it is invoked twice

I want it to be invoked once in both situations

**Comment by pleku** [comment]
Please provide a minimal reproducible test case using eg. [skeleton fork](https://github.com/vaadin/skeleton-starter-flow).

**Comment by denis-anisimov** [comment]
This issue is very similar to #3614.

The description of the ticket doesn't contain the important detail: the view which is the navigated target is also inside the `MainView` instance.
So the issue is not localized most likely but I assume this is the case.
