### ISSUE TITLE
Add UI shorthand method for navigating with a parameter value

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3616]
Shorthand methods for navigating to a view type with and without parameters were not added to `UI` as part of https://github.com/vaadin/flow/issues/2918 because of the dependency on the old router implementation.

Those methods should be added at the latest when the old router API is removed, but it could imho be done already by making the methods throw a runtime exception unless the new router API is used. Retaining support for the old API is only done to serve some specific legacy cases so I think it's completely fine that some shorthands are broken in those cases.

**Comment by pleku** [comment]
Add two shorthand methods for `UI` about navigating to a given navigation target:
```java
void navigate(Class<? extends Component> navigationTarget) { ... }
<T, C extends Component & HasUrlParameter<T>> void navigate(
            Class<? extends C> navigationTarget, T parameter) { ... }
```

Should take a look at the tutorials if this could be used somewhere, instead of using `Router.getUrl(...)` methods.
