### ISSUE TITLE
BeforeEnterObserver javadoc is misleading

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3627]
```
Any com.vaadin.ui.Component implementing this interface will be informed when they are being attached to the UI.

During this phase there is the possibility to reroute to another navigation target.
```

This sounds like you could assume `getUI()` works when the method is called. It does not.

The method `beforeEnter` javadoc is completely unclear to me: `Method called before navigation to attaching Component chain is made`

If it is intentional that the component is not attached when `beforeEnter` is called, please state that clearly and also provide a reference to the interface/method you should use for initializing the view, the method called after it has been attached

**Comment by caalador** [comment]
This has been updated in #5614 if that version should have a better alternative please comment on this ticket with a suggestion or open a new ticket.
