### ISSUE TITLE
It should not be possible to reconfigure the `frontend` URL for dev mode

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3633]
When you create an add-on, you need a folder to put static files. This folder is `frontend` or `src/main/resources/META-INF/resources/frontend` in a Maven add-on project. 

If the user is allowed to reconfigure the `frontend` path for development mode to something else, the file won't be found and the add-on won't work.

Is there any reason to allow changing the frontend path for development? For production, the only seemingly good reason is to be able to deploy static files on a CDN. Are there more?

**Comment by SomeoneToIgnore** [comment]
Can you elaborate on how it's possible to reconfigure it?
I remember removing this possibility myself, will find a ticket in a while.

**Comment by SomeoneToIgnore** [comment]
Fixed in https://github.com/vaadin/flow/pull/3106
