### ISSUE TITLE
Unify usage of ServletContext.getResource* methods

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3643]
Currently, resource related methods from `ServletContext` are used throughout the internal implementation of Flow. This has several problems:
1. Most of the cases also have to take WebJars into account, but this is done in slightly different ways in each case, causing subtle differences and bugs (and duplicated-ish logic)
2. This ties the internal implementation to the servlet API, which is opposite to the purpose of existing abstractions such as `VaadinRequest` and `VaadinService`.

Instead, there should be a similar set of abstract methods in `VaadinService` that are implemented by `VaadinServletService` in a way that transparently handles WebJars.

**Comment by Legioth** [comment]
Might also consider integrating checking of dependency filters into the same logic to automatically deal with e.g. bundled resources.

**Comment by heruan** [comment]
Will this also fix #3263?

**Comment by caalador** [comment]
@heruan It should, but should be tested with an example.

**Comment by heruan** [comment]
In which commit was this closed?

**Comment by pleku** [comment]
>In which commit was this closed?

Very good question. There was https://github.com/vaadin/flow/pull/3646/files but after now looking at it, it doesn't touch this at all.

**Comment by pleku** [comment]
It was not in 1.0.0.beta4 though.

**Comment by caalador** [comment]
#3656 was a step in the direction where the direct usage of ServletContext was dropped.
About having the getResource methods automatically handle webJars is a trickier thing as in some cases it may create not wanted results so needs a bit of thinking.

**Comment by heruan** [comment]
The latest released beta is 3, right? So this is not fixed in beta 3, but will in 4?
