### ISSUE TITLE
Getting zero-height Grid

### ISSUE THREAD

**Issue by guttormvik** [vaadin/flow#3652]
When following the steps in [the flow tutorial getting-started](https://vaadin.com/docs/v10/flow/introduction/tutorial-get-started.html), I get a Grid that has height 100% in the <vaadin-grid> tag, but is calculated to 0 by browser, so it is invisible.

Changing height of tag to, for instance, 500px directly in browser, or in java code shows the expected rows.

MainView:
```java
public class MainView extends VerticalLayout {

    private CustomerService service = CustomerService.getInstance();
    private Grid<Customer> grid = new Grid<>();

    public MainView() {
    	
        grid.setSizeFull();

        grid.addColumn(Customer::getFirstName).setHeader("First name");
        grid.addColumn(Customer::getLastName).setHeader("Last name");
        grid.addColumn(Customer::getStatus).setHeader("Status");

        add(grid);

        updateList();
        
    }
    
    public void updateList() {
    	grid.setItems(service.findAll());
    }
    
}
```

vaadin.version: 10.0.0.beta1

project source: [my_flow.zip](https://github.com/vaadin/flow/files/1786946/my_flow.zip)

Screengrab:
![image](https://user-images.githubusercontent.com/14308285/37061634-584ca278-2194-11e8-96cf-d6fabeef12bb.png)

**Comment by ZheSun88** [comment]
Hi. sorry for the inconvenience. This issue has been fixed. but the documentation hasn't been updated afterwards. 

for now, you can remove the line `grid.setSizeFull();` and use `grid.setHeightByRows(true);` to make the grid work as expected. 

I am going to update the tutorial for this. Thanks for the feedback

**Comment by guttormvik** [comment]
Great,

If you are updating the tutorial, I guess you should also replace reference to " Skeleton Starter" with "Project Base"?

**Comment by ZheSun88** [comment]
Yes, there is a separate PR for that already. :)
