### ISSUE TITLE
Explicitly document that multiple children can be assigned to the same slot

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow#3671]
When writing/modifying a template I want to read documentation of how I can insert an arbitrary number of serverside Components / Elements into it. I can't use named Slots because I don't know how many components there are.

**Comment by Legioth** [comment]
Could you elaborate what it is that you're trying to achieve. Do you want to put each child into a distinct location inside the template? Are you aware that you can put many components into the same slot?

**Comment by OlliTietavainenVaadin** [comment]
I am aware of it now that I've discussed it with people, but I would like to have this information in the documentation somewhere, maybe https://vaadin.com/docs/v10/flow/polymer-templates/tutorial-template-components-in-slot.html
