### ISSUE TITLE
Remove confusing leftovers from the experiment with fluent component APIs

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3678]
See https://github.com/vaadin/flow/pull/3660#issuecomment-371395981

**Comment by knoobie** [comment]
Is there any open available discussion why the experiment "fluent component API" was discontinued? 

Or did you guys thought about using [lombok](https://projectlombok.org/) as tool to generate boilerplate code? For example the annotation [Builder](https://projectlombok.org/features/Builder)?

**Comment by pleku** [comment]
It wasn't public. But the TL;DR: conclusion was that when we want to add Fluent API, we want to add it properly. Eg. not by just making setters return the instance, but actually design and implement it once for everything.

The sad thing is that while we see there would be some value in the API for lots of users, it is still not a big priority and not that easy to prioritize it over many other features we have in the backlog.

I've heard of lombok but never gotten around to investigating it. Thanks for the tip.

**Comment by knoobie** [comment]
I can understand why you came to this conclusion and why you don't have it high up on your priority list! Thank you for the quick and open response!

Lombok: We you is it in every project. It's a lifesaver for the daily annoying tasks of a java developer dealing with Beans or other stuff with get/set.

**Comment by Legioth** [comment]
I fear that Lombok (or anything other approach based on generated sources) will cause confusing situations with subclasses if not everyone downstream also uses the same solution. It's really confusing if you can do `someComponent.setFoo("foo").setBar("bar")` but not `someComponent.setBar("bar").setFoo("foo")`.

**Comment by knoobie** [comment]
I can understand why I don't want to include it in such a huge framework like Vaadin or Flow. It really changes the way how to code and how the code looks. And yes, especially with subclasses it can be really tricky sometimes. Thanks for taking the time to answer!

**Comment by gilberto-torrezan** [comment]
The interface has been removed, and all generated components were updated.
