### ISSUE TITLE
Add support for filtering events that are sent to the server

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#3684]
When listening for key events, I may only be interested in one key like Enter or ESC. Having a way to filter the events already on the client would save us from unnecessary server roundtrips. 

Nonfunctional example code to get idea across
```java
textField.getElement().addEventListener("keyup", () -> {..}, "event.keyCode === 13");
```

**Comment by Artur-** [comment]
Seems pretty much like #468
