### ISSUE TITLE
Resources not found when running the .war embedded tomcat

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3689]
Out of the box, Spring Boot uses a public static void main entry-point that launches an embedded web tomcat server packaged into the `.war` file, thus running `java -jar target/my-app.war` launches the app. Tough,  flow seems unable to find resources packaged into the `.war` file. The same war deployed in a tomcat works as expected.

You can reproduce e.g. by checking out bakery and packaging it:

```
mvn package -Pproduction
java -jar target/bakery-*.war
```

The error in console is:
`Can't find resource 'frontend://src/views/login/login-view.html' via the servlet context'`

**Comment by deyaeddin** [comment]
I'm facing the same error when I changed the packaging to jar with Spring Boot 2.0, 
it's run fine with
> mvn spring-boot:run
but when I use:
> java -jar target/bakery-app.jar
I got the following error 

> ERROR 3103 --- [nio-8002-exec-2] c.v.flow.router.InternalServerError      : There was an exception while trying to navigate to 'login'
> 
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.thalesgroup.ife.dutyfree.dutyfreeframework.ui.views.login.LoginView': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.thalesgroup.ife.dutyfree.dutyfreeframework.ui.views.login.LoginView]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Can't find resource 'frontend://src/views/login/login-view.html' via the servlet context
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1232) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]

**Comment by docwho2** [comment]
I just ran into this as well.  This is the default behavior when you deploy to AWS Beanstalk.  But what AWS does by default is rename your WAR file to "application.jar" and then executes "java -jar application.jar".  Took me half a day to figure out renaming the WAR to JAR breaks everything.  I had simple views before, but now that I'm including HTML in the views I'm seeing the same errors.  I will change my deployment package to execute the WAR with mvn spring-boot:run until there is fix.

**Comment by Legioth** [comment]
Similar messages also observed with `mvn spring-boot:run` for the `vaadin_push.zip` project referenced in https://github.com/vaadin/flow/issues/3738#issuecomment-376619865.

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/spring #265](https://github.com/vaadin/spring/issues/265) via [**ZenHub**](https://www.zenhub.com/)
