### ISSUE TITLE
Flow doesn’t register a click for the <a> element when it happens on top of the nested <iron-icon> elements.

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#3697]
Not a certain issue, but according to feedback, it seems like Flow doesn’t register a click for the <a> element when it happens on top of the nested <iron-icon> elements.

This issue is originally from `Beverage-Starter-flow` with the navigate items' 'DeadZone' problem. (https://github.com/vaadin/beverage-starter-flow/issues/175) <- according to the comments, it reproduces every time

at the moment, there is a workaround for the starter to make it work https://github.com/vaadin/beverage-starter-flow/pull/185.

**Comment by pleku** [comment]
This is a relevant case when using routerlink that has icons inside.

**Comment by Legioth** [comment]
Could it be that the logic that detects `router-link` clicks doesn't take into account that the actual click target is inside a shadow root?

**Comment by heruan** [comment]
I'm experience the same issue when `RouterLink` is inside a `ComponentRenderer`, e.g. in `IronList`. Could it be related to this?

**Comment by pleku** [comment]
>I'm experience the same issue when RouterLink is inside a ComponentRenderer, e.g. in IronList. Could it be related to this?

Most likely the same case. Issue probably occurs either in https://github.com/vaadin/flow/blob/master/flow-client/src/main/java/com/vaadin/client/flow/RouterLinkHandler.java#L67 or https://github.com/vaadin/flow/blob/master/flow-client/src/main/java/com/vaadin/client/flow/RouterLinkHandler.java#L98.

**Comment by heruan** [comment]
This project replicates the issue: https://github.com/heruan/flow-test/tree/router-link

There is a component with a red `div` in the shadow DOM and a green `div` in the light DOM: when clicking on the green one the link behaves as it should (i.e. in-app navigation), while clicking on the red one it triggers a full navigation instead.

**Comment by pleku** [comment]
Since this is not reproducing with e.g. https://labs.vaadin.com/business/payments and there have not been any further reports about this, I don't think this issue is anymore valid. In case anyone runs into this, please create a new issue with the code/steps to reproduce the problem.
