### ISSUE TITLE
Vaadin Button component concatenate text from the flow template

### ISSUE THREAD

**Issue by dg0s** [vaadin/flow#3699]
I create a flow template with a vaadin-button inside using vaadin designer.
` <vaadin-button id="btn" theme="primary">
      Button 
    </vaadin-button>`

When I use setText in the companion java to assign a new text, the value is concatenated.
`btn.setText("Add");`

The text output is "Button Add".
The expected output should be "Add".

**Comment by pleku** [comment]
Hello and Thanks for the feedback!

This is a known issue and already tracked here: https://github.com/vaadin/vaadin-button-flow/issues/43
Please go +1 that one.

I'm closing this one as a duplicate.
