### ISSUE TITLE
Don’t add`scroll=auto` to body

### ISSUE THREAD

**Issue by jouni** [vaadin/flow#3701]
When creating an empty Flow application, I don’t want Flow to inject the `scroll="auto"` attribute to the page `<body>` element, so that it doesn’t send cause any unexpected side-effects, and possibly send unnecessary bytes to the client (not sure if that attribute is added by the bootstrap page or the client-side engine.

**Comment by caalador** [comment]
UI on creation does `getElement().setAttribute("scroll", "auto");`

**Comment by pleku** [comment]
I'm pretty sure it is mentioned in the documentation, so that needs to be updated too,

**Comment by pleku** [comment]
We should verify that eg. BB works as expected even after this change.

**Comment by Legioth** [comment]
Could maybe include a `scroll` parameter in `@BodySize` for the cases that still want to have it there?

**Comment by jouni** [comment]
> We should verify that eg. BB works as expected even after this change.

I don’t think this attribute does anything in the browsers we currently support.

> Deprecated in HTML5. Do not use.
https://html.com/attributes/body-scroll/

**Comment by jouni** [comment]
So I would not consider this as a breaking change even.

**Comment by denis-anisimov** [comment]
Didn't find any mention of this in tutorials.
If you know such place please let me know.
