### ISSUE TITLE
Improve how the Element API deals with existing content that the server doesn't know about

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3713]
An `Element` instance injected using `@Id` (potentially indirectly through `@Id` for a component) might have children in the actual DOM even though the server-side implementation isn't aware of. Even for non-`@Id` elements, there's also the theoretical possibility that the DOM has been modified from the client side through e.g. some JQuery plugin.

We should ensure hierarchy modifications done through the Element API on the server still make as much sense as possible despite there potentially being some unexpected children in the client-side DOM.

In particular, three cases are known to be problematic:
1) `Element.removeAllChildren()` should remove _all_ children, not only those that the server knows about. I'm not entirely sure about how to implement this since it goes all the way down to the `StateNode` layer where `clear()` on an empty `StateNodeNodeList` is a no-op. 
2) `Element.setText(String)` for a non-text node should remove always remove children (i.e. call `removeAllChildren()`), even if server-side information indicates that there's only a single text node that could thus be reused with changed contents.
3) `Element.appendChild(Element...)` should insert the new child after any pre-existing children. On the other hand, it might be expected that `insertChild(0, child)` would insert the new child before any pre-existing children. This is problematic since `appendChild(child)` maps to `insertChild(0, child)` for an element with no server-side children. If no good way of dealing with this can be found, it's still probably better to have `appendChild` work as expected.

Related to at least https://github.com/vaadin/vaadin-button-flow/issues/43 and https://github.com/vaadin/flow/issues/3699

**Comment by pleku** [comment]
Remember to clarify the javadocs of these methods to emphasize how they work in these cases too.

**Comment by pleku** [comment]
If you run into any failing tests for angular template, it is ok to remove that stuff.

**Comment by stefanuebe** [comment]
Will this also solve the problem, that you can't fetch the components by component.getChildren() or component.getElement().getChildren (and so on...)?

For example having a layout with some child components:
```
<vaadin-horizontal-layout id="layout">
	<vaadin-button>Edit</vaadin-button>
	<vaadin-button>Delete</vaadin-button>
</vaadin-horizontal-layout>
```

and accessing them inside my PolymerTemplate implentation

```
@Id("layout")
private HorizontalLayout layout;

private String someFunction() {
       layout.getChildren().forEach(...);
}
```

**Comment by Legioth** [comment]
@stefanuebe Nope. This approach is only about improving how changes from the server are applied in cases when there are elements present that the server didn't know anything about.

Making the full DOM structure available on the server is something that would have a significant impact on the memory consumption of every `PolymerTemplate` instance. We have identified a potential way of mitigating that problem, but the implementation effort would be quite high.

The focus of this issue is thus to fix 80% of the problems with 20% of the effort.

**Comment by stefanuebe** [comment]
This means it will not be implemented or just later?

**Comment by Legioth** [comment]
May be implemented in the future, but it's not on any roadmap.

**Comment by stefanuebe** [comment]
Ok, but we should not put this too far aside :)

Also please have in mind that there are some functions that relay on the dom tree, like Tabs.getSelectedTab(). This method currently throws always an exception when having the tabs defined in polymer. You may only react to a switch by getSelectedIndex() (which makes the Java having to know design details of the template).

> java.lang.IllegalArgumentException: The 'index' argument should not be greater than or equals to the number of children components. It was: 1
> 	at com.vaadin.flow.component.HasOrderedComponents.lambda$getComponentAt$0(HasOrderedComponents.java:127) ~[flow-server-1.0.0.beta3.jar:na]
> 	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_162]
> 	at com.vaadin.flow.component.HasOrderedComponents.getComponentAt(HasOrderedComponents.java:127) ~[flow-server-1.0.0.beta3.jar:na]
> 	at com.vaadin.flow.component.tabs.Tabs.getSelectedTab(Tabs.java:122) ~[vaadin-tabs-flow-1.0.0.beta1.jar:na]

**Comment by Legioth** [comment]
I created https://github.com/vaadin/flow/issues/3735 for making it possible to also access template information on the server.
