### ISSUE TITLE
Unregister pattern requires some solution to avoid memory leaks.

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#372]
There are many places where "unregister pattern"  is used for register/add listener (or add something that amy be cancelled) action.
It's implementation usually just returns a lambda which removes registered instance.
There is an issue with that approach : lambda refers indirectly to a number of some instances.
As a result this may lead to memory leaks if this "unregistration" reference is stored somewhere.

Some way is required to solve this issue.
- It can be done via resetting the reference in the end of request handling (there should be a way to get notification about it)
- Use some class with WeakReferences instead of lambdas as an "unregistrator". 
- Some common pattern which will allow do not think about it at all.

**Comment by pleku** [comment]
We nowdays have a way to do things once before the client response, but I don't recall any cases to do things right after the changes have been sent. I wonder if there is any use case for that if we have not yet added the support for that.

@denis-anisimov what do you think, is it still a risk that we could leak memory inside the framework somewhere by storing registration objects, or should we just close this issue and wait for concrete reports that indicate this problem exists ?

**Comment by denis-anisimov** [comment]
This is an enhancement.
And this is a feature request : something that would be nice to have but it's not supported anyhow.
Most likely we will never have time to implement this.
If this is a proper reason to close then let's close it.
