### ISSUE TITLE
Support query parameters in RouterLink

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#3720]
If I have a component which makes use of URL query parameters, I need an API to set them in `RouterLink`.

Now I need to do this:

```java
QueryParameters params = QueryParameters.simple(Map.of("foo", "bar"));
String url = UI.getCurrent().getRouter().get().getUrl(MyComponent.class);
Anchor link = new Anchor(url + "?" + params.getQueryString(), "link");
```

Whereas this would be easier:

```java
QueryParameters params = QueryParameters.simple(Map.of("foo", "bar"));
RouterLink link = new RouterLink("link", MyComponent.class);
link.setQueryParameters(params);
```

**Comment by Legioth** [comment]
Slightly related is that there are also plans for hooking up query parameters through the existing `HasUrlParameter` infrastructure.

This would mean that in cases when `foo` is the only parameter supported by the component, the above example could also work with existing API as `new RouterLink("link", MyComponent.class, "bar");`

**Comment by heruan** [comment]
Curious on how plans are designed for that, since at first it seems confusing to have the same interface for both path and query parameters; I would rather expect a new `HasQueryParameter` interface for that. Are these same plans also related to #2740?

**Comment by Legioth** [comment]
Path and query parameters are two different way of transmitting the same kind of data, so in most cases it would make sense to treat both in the same way.

The basic plan would be that you could put `@QueryParameter("foo")` in the same locations as e.g. `@OptionalParameter`. For this to be really meaningful, we would first have to implement some stuff for supporting more than one parameter per class (e.g. `HasUrlParameterPair` and a convention for mapping multiple parameters as `HasUrlParameter<BeanHoldingMultipleParameters>`).

The main challenge in #2740 is how the parent and the child can be aware of each other's parameter values in a typesafe way (and how to generate URLs). This is not directly relevant in the case of query parameters: it wouldn't even be a problem if both the parent and the child would define a query parameter with the same name (as long as the types aren't conflicting).

**Comment by heruan** [comment]
> Path and query parameters are two different way of transmitting the same kind of data […]

I was thinking about a JSON query parameter e.g. `foo={"bar":true}`, which is a type of data that is unlikely to be part of the path, but I understand the use case now. Thank you!
