### ISSUE TITLE
Grid is not displayed in FlexLayout

### ISSUE THREAD

**Issue by berndhopp** [vaadin/flow#3731]
When I put a Grid in a FlexLayout and call setSizeFull() for both components, the grid is not being shown. I was told that I need to call setHeightByRows(true) on the grid and that makes the grid appear, but the expected behavior is that the grid is being shown to begin with. It's absolutely counterintuitive this way and will lead to a lot of frustration on the user side. It is absolutely impossible to figure out what you need to do when your grid is not being shown. Please at least set heightByRows to true by default.

**Comment by caalador** [comment]
setHeightByRows is not the correct fix for this issue. the issue stems probably from the fact that your FlexLayout has no height and 100% of 0 == 0

**Comment by berndhopp** [comment]
my flexlayout has sizeFull. The problem came when I increased the version to 10.0.0.alpha22 and I was told to call setHeightByRows(true), which solved the issue.

**Comment by berndhopp** [comment]
this is what the dom looks like, you can see that both mainLayout and grid have height 100%, but the actual height of the grid is 0px.

![screen shot 2018-03-19 at 2 21 32 pm](https://user-images.githubusercontent.com/1919315/37649077-1511ebd8-2c31-11e8-9ac7-04ebf3a07dc7.png)

**Comment by caalador** [comment]
But what size does the div have that grid is in?
Also what is the calculated height of the main-layout div?
If you have a simple class which we could copy to skeleton starter it would be easier to debug this.

**Comment by pleku** [comment]
It looks to me this is the same issue as https://github.com/vaadin/flow/issues/3709, you don't have any size for the `<body>` element ? Meaning that 100% of 0 is 0.

**Comment by gilberto-torrezan** [comment]
Since [Flow 1.0.0.beta6](https://github.com/vaadin/flow/releases/tag/1.0.0.beta6), it's not needed to declare a `@BodySize` in the main layout anymore. When nothing is set, the application `body` is set to have `height = "100vh", width = "100vw"` by default.

When the body has a defined size, this bug doesn't happen.

I have added a test on Grid (https://github.com/vaadin/vaadin-grid-flow/pull/140 ) to make sure it doesn't break in the future.
