### ISSUE TITLE
Components mapped with @Id don't contain the id attribute on the server side

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#3733]
This is counter intuitive - the server-side knows about the Id of the component to be able to map it via `@Id`, but when the `getId()` method is invoked, an empty `Optional` is returned:

```java
@Id("myComponent")
private Div myComponent;

//...
myComponent.getId().isPresent(); // -> returns false
```

I would expect it to return the value that was used in the `@Id` mapping, instead of empty.

**Comment by denis-anisimov** [comment]
This is fixed in the latest versions.
