### ISSUE TITLE
Allow custom `PushConnection` implementations on both client and server side

### ISSUE THREAD

**Issue by mcollovati** [vaadin/flow#3752]
When running Vaadin on non servlet environments
I want to be able to provide a custom `PushConnection` both on client and server side
so that I'm free to choose the better communication stack for the environment.

My use case for this is running Vaadin Flow on Vert.x; Vert.x atmosphere
support does not seem to work very well whereas the OOB sockjs stack works fine.

In  flow-client `PushConnection` in `MessageSender` is hardcoded
to be a `AtmospherePushConnection` instead of using `GWT.create` as in Vaadin 8.
I suppose this is because now `AtmospherePushConnection` takes `Registry` as constructor parameter.

In Vaadin 8 I was able to replace client push implementation using `replace-with` 
in GWT module, but in flow this is no more possible.

It would be nice to have a `PushConnectionFactory` interface with 
a method like `PushConnection create(Registry)` that will be used in `MessageSender`
as follows

```java
pushConnectionFactory = GWT.create(PushConnectionFactory.class)
...
push = pushConnectionFactory.create(registry);
```

Having that it is possibile to create a custom client side engine with the wanted push technology.

Something similar should also be done server side because
also `PushConfigurationImpl` has an harcoded dependency to `AtmospherePushConnection`.
`UI.pushConfiguration` cannot be replaced without reflection tricks because it is a private field,
and, whereas one can do a `UI.setPushConnection(...)` this should be repeated after 
all invocations of `PushConfiguration.setPushMode`.

It would be nice to have also here a pluggable way to specify the `PushConnection` implementation, 
such as using a `ServiceLoader` or an attribute on `@Push` annotation or whatever

**Comment by pleku** [comment]
Hello. We see this as something that would be _nice to have, but not a priority_, at least not at the moment. If someone wants to contribute to this, we are however willing to help and merge such improvement.

**Comment by mcollovati** [comment]
I can submit a PR for the client part; for the server side I need some hint on the preferred way to  refactoring `PushConfigurationImpl` in order to replace the hardcoded  `new AtmosphererPushConnection(...)`

**Comment by Legioth** [comment]
I guess `PushConfiguration` might not necessarily even make sense in its current format since the available `Transport` alternatives might be completely different with a different underlying implementation?

That in turn might imply that a slightly more thorough redesign of the server-side API might be needed.

**Comment by mcollovati** [comment]
From my POV, limited to sockJS integration, available `Transport` alternative 
are exactly the ones I needed. In addition custom configurations could be easily 
configured via `PushConfiguration.setParameter`.
So maybe the missing piece is a hook to initialize `PushConfiguration` and
set a factory to create `PushConnection` custom implementation.

My proposal (based only on my needs :) ) is to:

- add `PushConfigurationInitializer : Consumer<PushConfiguration>` interface; 
  implementation class will be read from `@Push` annotation
- add method `PushConfiguration.setPushConnectionFactory(SerializableFunction<UI, PushConnection>)`
  and use function in `PushConfigurationImpl.setPushMode` in place of `new AtmospherePushConnection`
- apply `PushConfigurationInitializer` in `BootstrapHandler`

If you think this introduces to much complexity or it is a bad design I'll submit a PR for client side only as this is the point that is actually a blocker for my needs but has a lower impact on Flow .

```java
@Push(initializer=SockJSPushConfigurationInitializer.class)
public class MainLayout extends Div implements RouterLayout, PageConfigurator { ... }

class PushConfigurationImpl {

  def setPushConnectionFactory(pushConnectionFactory: SerializableFunction<UI, PushConnection>) {
    this.pushConnectionFactory = pushConnectionFactory;
  }

  def setPushMode(...) {
    ...
    ui.getInternals().setPushConnection(pushConnectionFactory.apply(ui));
    ...
  }
}

class DefaultPushConfigurationInitializer < PushConfigurationInitializer {

  def accept(pushConfiguration: PushConfiguration) {
    pushConfiguration.setTransport(Transport.WEBSOCKET_XHR);
    pushConfiguration.setFallbackTransport(Transport.LONG_POLLING);
    pushConfiguration.setPushMode(PushMode.DISABLED);
    pushConfiguration.setPushConnectionFactory(AtmospherePushConnection::new)
  }
}
class SockJSPushConfigurationInitializer < DefaultPushConfigurationInitializer {
  def accept(pushConfiguration: PushConfiguration) {
    super.accept(pushConfiguration);
    pushConfiguration.setParameter("...", "...");
    pushConfiguration.setPushConnectionFactory(SockJSPushConnection::new)
  }
}

class BootstrapHandler {
  def createAndInitUI(...) {
    ...
    PushConfiguration pushConfiguration = ui.getPushConfiguration();
    Optional<Push> push = context.getPageConfigurationAnnotation(Push.class);
    push.map(Push::initializer).map(ReflectTools::createInstance)
      .ifPresent(pushInitializer -> pushInitializer.accept(pushConfiguration))
    
    ...
  }
}
```

**Comment by Legioth** [comment]
@mcollovati The suggested approach seems sensible for now. We might still at some point want to do something more complex that wouldn't be restricted by what's in the the current `PushConfiguration` and `@Push` APIs, but I don't think now is a good time for doing that.

**Comment by mcollovati** [comment]
May I reopen this issue? I'm going to open a PR for server side `PushConnection` customization
