### ISSUE TITLE
Compress ClientEngine using Brotli

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3764]
With Brotli, the compressed size of the current ClientEngine would be 44089 bytes compared to 51651 bytes when compressed with gzip, i.e. a reduction by about 15%.

We should include the Brotli compressor into the ClientEngine build process so that a precompressed file is included in the built `.jar`, and then also update the file serving logic in `ResponseWriter. writeResponseContents()` to automatically send `.br` if feasible in the same way as the existing support for `.gz`.

We would still also have to retain support for gzip since Brotli isn't supported by some older browsers and it's only used over HTTPS.

**Comment by Legioth** [comment]
I haven't been able to find any sensible Java implementation of a Brotli encoder. There is https://github.com/google/brotli/tree/master/java which only does decoding and https://github.com/MeteoGroup/jbrotli which doesn't seem to have up-to-date native bindings for OS X.

On the other hand, it seems to work nicely to pipe the file contents through `Runtime.getRuntime().exec("brotli");` as long as the binary is installed on the machine that compiles the client engine.

As of today, the latest ClientEngine size numbers are slightly smaller than when I created the ticket: 45536 bytes with gzip and 38925 with Brotli.

**Comment by Legioth** [comment]
There is actually https://github.com/RyanHoldren/ResourceCompressor which is based on https://github.com/MeteoGroup/jbrotli which in turn does have up-to-date native bindings for OS X as well.

**Comment by pekam** [comment]
Reopening the issue as the fix was reverted for now in https://github.com/vaadin/flow/pull/4582. The reason is stated in the PR's comment.

**Comment by Legioth** [comment]
Superseded by https://github.com/vaadin/flow/issues/4583 which has more relevant information.
