### ISSUE TITLE
Potentially redudnant opened-changed events are sent to the server

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3772]
Any action in Flow makes just a request to server, but `navigate` requests twice.
The second request has very small payload `for(;;);[{"syncId":9,"clientId":9,"timings":[4121,5]}]` but it's very noticeable in slow networks.

In the next screenshot you can see how some actions produce one request, but those that changes the url make two. Note that the pushstate has been done with the first request, so second one seems unnecessary 

![navigation](https://user-images.githubusercontent.com/161853/37964098-9c225614-31c0-11e8-9d86-4c87d82af2c3.gif)

**Comment by Legioth** [comment]
This is not caused by `navigate` itself,  but rather by the `opened-changed` event that the server for some reason listens to.

**Comment by manolo** [comment]
Actually not only when navigating to views in dialogs, where listening to opened-changed, but also other navigation actions through the nav-bar are affected as showed in this screenshot

![navigation2](https://user-images.githubusercontent.com/161853/38025137-911c8f06-3287-11e8-9126-b365c52904ff.gif)


BTW, we are listening to opened-event until this PR is available in latest 

https://github.com/vaadin/vaadin-dialog-flow/pull/52

**Comment by Legioth** [comment]
The second case is also not directly caused by `navigate`, but instead by `@EventHandler` notifications for `setDetailsVisible` and `confirmUpdate`.

**Comment by Legioth** [comment]
It's recommended to also look at the request payload in addition to only the response payload for understanding why the request is being sent.

**Comment by manolo** [comment]
Good point, I'll open a task in bakery to check why those events are there and how to deal with them.
Let's leave this opened for a while until we investigate that in Bakery.
