### ISSUE TITLE
loading indicator should be customisable

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3779]
It should be nice if loading indicator can be replaceable by a custom element e.g. `vaadin-progress-bar`

Customisation might be using annotations like

```
@HtmlImport("frontend://bower_components/vaadin-progress-bar/vaadin-progress-bar.html")
@LoadingContent("<vaadin-progress-bar indeterminate theme="top"></vaadin-progress-bar>")
```

**Comment by Legioth** [comment]
What about Jouni's proposal: https://github.com/vaadin/flow/issues/3763

**Comment by pleku** [comment]
Closing this as a duplicate of #3763, we should focus all the possible use cases and wished to a single issue for now.
