### ISSUE TITLE
Iframe may not be added into template within a slot

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#3795]
See PR:
https://github.com/vaadin/flow-demo/pull/428

There is the `iframe` which is added into the `content` which is inside an element added into a slot of a template.
This `iframe` element doesn't appear unless some trick is used.
I've used a fake iframe invisible element added before the required `iframe`.
It looks like `iframe` element requires some async initialization (like web component) to be being added.

**Comment by denis-anisimov** [comment]
Update: the iframe appears in the DOM once its `src` attribute is set.
So may be this is not a bug.
The behavior is the same without template: angular version worked in the same way.

It's a bit confusing that `iframe` element doesn't appear in the DOM right away.
If I use invisible another `iframe`  then both of them appears in the DOM.
So may be it's still an issue but very low priority.

**Comment by pleku** [comment]
Due to lack of demand and the fact that this behaves as it should (?), closing this issue. If someone discovers this and it is a problem for you, please open a new issue with the use case elaborated.
