### ISSUE TITLE
Remove usage of VaadinRequest.getCurrent

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3802]
Most places where `VaadinRequest.getCurrent()` is called, uses the wrong assumption that a request is always available. This is not true for a background thread and NPEs will fly.

`VaadinServlet.resolveResource(String url)`:

```
        VaadinRequest request = VaadinRequest.getCurrent();
        VaadinSession session = VaadinSession.getCurrent();
        if (request == null || session == null) {
            /*
             * Cannot happen in runtime.
             *
             * But not all unit tests set it. Let's just return null.
             */
            return null;
        }
```

Sure it can happen in runtime, just call if from any other thread than a request thread.

This will help resolve issues like #3798, which is caused by a similar case in `resolveUrl`, where it is assumed that `VaadinRequest.getCurrent()` is not null and not even checked.

**Comment by pleku** [comment]
Sure if this can be `null`, then it ought to be returning `Optional` instead.
And if users don't check it and just use `get() `, I think the NPE is fine.

But since the NPE in #3798 is caused with FW internal code, maybe the removing would be the safe way.

**Comment by Artur-** [comment]
In a background thread there is never a ”current” request

**Comment by Legioth** [comment]
I think one relevant question is whether we want to have different API for different `getCurrent` methods?

For the "safe" ones that are only depending on correct `UI.getAccess` usage, I think the best alternative would be to throw a `IllegalStateException` (or a subclass) with a descriptive message (referring to `UI.access`). We should then also introduce a separate `hasCurrent` method that can be used for checking the situation without the ugliness and performance overhead of a try-catch.

For the "unsafe" ones that might fail even if using `UI.getAccess` properly, it might be good if the API  reminds the developer that there's the potential of something dangerous. This would imply returning `Optional` or throwing a checked exception. On the other hand, we might also want to avoid having different API for different `getCurrent` methods. In that case, the exception message for the "unsafe" methods could still be slightly more elaborate.
