### ISSUE TITLE
Provide a way for adding PWA specific configuration to bootstrap page

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3807]
In Bakery it's needed a customised bootstrap class in order to add the manifest, service worker and icons https://github.com/vaadin/bakery-app-starter-flow-spring/blob/master/src/main/java/com/vaadin/starter/bakery/app/CustomBootstrapListener.java#L16

There should be some annotations to make this easy to configure in the UI class similar to `viewport` or `bodysize` 

```
@BodySize(...)
@ViewPort(...)

@Manifest("my-manifest.json")  // default value should be manifest.json
@ServiceWorker("my-sw.js")   // default value might be sw.js
@Icon(size="192x192", path="icons/icon-192.png")
```

**Comment by Legioth** [comment]
Have you noticed that you don't have to use a bootstrap listener anymore. Instead, you can use `@Inline` or `PageConfigurator`, as described in https://vaadin.com/docs/v10/flow/advanced/tutorial-bootstrap.html.

Also related to  https://github.com/vaadin/flow/issues/3248.

**Comment by manolo** [comment]
Apparently `@Inline` only works with `JS` and `CSS`.

For service worker, the implementation should add some magic javascript code to register it, for icons I was thinking on having also some magic to include all variants per icon needed (icon, apple-touch-icon) 

Probably `@Inline` might work, for all cases instead of new annotations but needs more wrapping cases

**Comment by Legioth** [comment]
There's also a `Wrapping.NONE` that includes the inlined file as HTML (after taking it through JSoup to ensure there are no mismatched tags or other nasty stuff). This is used by default for file extensions other than `.js` or `.css`.

**Comment by pleku** [comment]
Related to #4273 #4274 and #4275
