### ISSUE TITLE
Add a tutorial for "How do I allow some user interaction for a disabled component"

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3813]
Details on how the feature works are in https://github.com/vaadin/flow/issues/3538#issuecomment-378172077

**Comment by denis-anisimov** [comment]
Sorry, the mentioned comment doesn't say anything to me about the way to allow some user interaction for disabled component.
May be it has been discussed during the planning session but since I wasn't there I'm not on the same page.

**Comment by pleku** [comment]
@denis-anisimov there is the follwing:
```
for all entry points that are affected by disabled, it should be possible to say it is OK to handle this communication even if the element is disabled. For declarative API there should be another boolean property for this. For methods there is another more specific overload. The cases are:
- property change (model sync), both declarative and element API
- dom events, both declarative and element API
- event handler, declarative API
- client delegate, declarative API
```

The actual implementation issue with design proposal is https://github.com/vaadin/flow/issues/3808
