### ISSUE TITLE
Create HasEnabled and apply it to selected mixin interfaces

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3816]
The `HasEnabled` interface extends `HasElement` and should consist of three methods:
```java
void setEnabled(boolean enabled) {
  // disable the state node
}
boolean isEnabled() { // read the disabled status, parent status applies }
```

As described in https://github.com/vaadin/flow/issues/3538#issuecomment-378172077, `HasEnabled` should be applied to the interfaces `HasValue`, `HasComponents` and `Focusable`.

**Comment by denis-anisimov** [comment]
It's done as described here.

But it introduces one (I think unexpected) issue:

`HasValue` doesn't extend `HasElement`.
After this change it extends it.

**Comment by pleku** [comment]
>HasValue doesn't extend HasElement.
After this change it extends it.

This is fine.
