### ISSUE TITLE
Dependencies order is not respected by the modern router functionality

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#3822]
We have a test `UidlWriterTest::parentViewDependenciesAreAddedFirst`.
The test works for the obsolete router and it checks that dependencies for parent layouts are loaded before dependencies for their children.

This test fails for the new Router: the leaf target layout dependencies are loaded first and then dependencies for parent after that.

Once the old router is removed this test won't work for the new router and it will be ignored.

I cannot find any ticket about this requirement: load parent dependencies first and then children dependencies.

So do : 
- either this needs to be fixed so that new router follows the same requirement.
- or the test should be just removed.

**Comment by pleku** [comment]
Unless someone thinks of a reason for why would the ordering matter, I think we don't have to care.

@paulroemer does it matter for the website ?

**Comment by denis-anisimov** [comment]
I'm quite not sure but it might be there was a reason why this order has been forced.
I vaguely recall that there was some issue related to HTML imports order.
May be it had some relations to bundling. May be not.
May be @vlukashov recall this ..?

May be this is not an issue already.

**Comment by vlukashov** [comment]
I do not recall the exact case why it was important for VC / the legacy router. However, when looking at the issue description now I am still confident that the order of loading dependencies matters: the dependencies for the parent layout should be loaded before those of a layout child.

The reasoning is that the parent layout does not know which exact child element is rendered (there is no dependency from the parent to the child), but the layout child always knows its parent (there is / can be a dependency from the child to the parent).

Here is the use case I think of:
```java
@JavaScript("global.js")
public class MainLayout extends Div implements RouterLayout {
}

@JavaScript("users.js")
@Route(value = "users", layout = MainLayout.class)
public class UsersView extends Div {
}
```

If the loading order is not maintained any dependency from users.js onto global.js would fail.

**Comment by pleku** [comment]
Thanks @vlukashov , I think that is very valid reasoning and thus we should fix this.

**Comment by pleku** [comment]
I don't understand how this is applicable anymore as the JS is loaded together in a bundle since 14 npm mode. Webpack takes care that things are loaded accordingly.
