### ISSUE TITLE
jetty:run no longer works when enabling production mode and there is no way to find out why

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3825]
Take any basic Flow app, start it with `mvn jetty:run` and it works as expected.

Add the Maven plugin for production mode and the app works as expected although you are not running in production mode as you might think because of #3824 .

Add `flow-server-production-mode` and the app no longer starts. The only error you get is
```
[qtp1192834021-67] INFO com.vaadin.flow.server.startup.BundleFilterInitializer - Bundling disabled: Flow bundle manifest '/frontend-es6/vaadin-flow-bundle-manifest.json' was not found in servlet context
```

As a user this tells me nothing. If I look in the target folder, I find a `frontend-es6/vaadin-flow-bundle-manifest.json` file. The error message also indicates that the app will work although bundling will not be used BUT it won't because it tries to load the files from a `frontend-es6` folder and that cannot be found either.

There should be some way for me as a user to find out that I need to run `mvn jetty:run-war` or do something else  to make it work. Or then `mvn jetty:run` should work also for production, out of the box

**Comment by pleku** [comment]
Instead of the current info message
```[qtp1192834021-67] INFO com.vaadin.flow.server.startup.BundleFilterInitializer - Bundling disabled: Flow bundle manifest '/frontend-es6/vaadin-flow-bundle-manifest.json' was not found in servlet context```
We should use `error` instead and suggest that you are using mayhaps `jetty:run` instead of `jetty:run-war` or maybe (test ?) `jetty:run-exploded`.

**Comment by johndevs** [comment]
Apparently now the manifest became mandatory even if you are not using Maven... 

Is this an oversight or why did the functionality change in beta?

**Comment by johndevs** [comment]
You might also want to re-write the ``Optional`` handling of the manifest in ``BundleFilterInitializer`` since the manifest is no longer optional @manolo
