### ISSUE TITLE
Remove Has*Listener interfaces to rename the *Notifier 

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#3829]
There are several `*Notifier` interfaces in the `com.vaadin.flow.component` package that should be renamed to `Has*Listeners`, to maintain name consistency among the interfaces.

In cases where there are both `*Notifier` and `Has*Listener` (such as `ClickNotifier` and `HasClickListeners`), the `*Notifier` class should be removed, and components that depend on them should be updated to use the `Has*Listeners`.

**Comment by Legioth** [comment]
Also seems that the different naming conventions have different event types (at least in the case of `ClickEvent`), and that those events have different `@EventData` definitions.

**Comment by Legioth** [comment]
`HasSize` implies that there are `getSize()` and `setSize()` methods, so `HasClickListeners` would imply that there are methods named `getClickListeners()` and `setClickListeners()`?

**Comment by gilberto-torrezan** [comment]
They could have, although it makes more sense to have just the `add` and `remove` methods. In that sense it feels like a `HasValue<List<Something>>` - you have the `setValue(List<Something>)`, but it would be more beneficial to have a `addValue(Something)`.

In other words - to me the `HasXyzListeners` behave just like a `HasXyzProperty`, where the value of the property is actually a collection of values.

**Comment by pleku** [comment]
I think for the observer pattern, thus far the naming convention used in Vaadin's Java products has been:
- `FooNotifier` for the observable, has the listener registration methods
- `FooEvent` for read-only data related to the observable
- `FooListener` for the observer

I don't know why we are deviating from this. My understanding is that probably by accident, since there was nobody in the team who was familiar or noticed the earlier design principles for observables, and thus the `HasFooListener` pattern was used.

**Comment by pleku** [comment]
The `HasFoo` mixin interfaces are another case, and those have been introduced at a later point (in early stages of Flow and FW8.0), and the naming works IMO sometimes quite well, sometimes not at all. Also some people don't like the `HasXyz` pattern at all. Some easy and some not so easy examples or converting the naming:
- `HasSize` -> `Sizeable`
    - it would be quite easy to convert and it is quite easy (or even better) understandable what it means.
- `HasStyle` -> `Styleable`
    - is not even proper english, but might still be understandable
- `HasComponents` -> `ComponentContainer`
    - would also match previous naming convention
- `HasDataProvider` -> ?
- `HasDynamicTitle` -> ?
- `HasText` -> ?
- `HasItems` -> ?
- `HasItemsAndComponents` -> `ItemAndComponentContainer` ?
    - this `extends HasComponents, HasItems` ... 
- `HasValue` -> `Field`
    - this would be against the design decision in FW 8 and introduce a breaking change for something we've promised to keep the same

I don't think we can change all the `HasFoo` interface names. The question is mostly about should we change any of them, and if we do, on what grounds ? There is no consistency in the examples above, for what type of API those interfaces have, it depends mostly on the purpose.

For consistency's sake, I would just keep on using the `HasFoo` naming.

**Comment by pleku** [comment]
Design decision:
- Rename the `Has*Listener` to `*Notifier`
    - make sure there are no overlaps between the current notifiers and has-interfaces
    - eg. kill `HasClickListeners` and the corresponding `ClickEvent` and replace with the ones for the current `ClickNotifier`
- Keep all other mixin interfaces as `HasThisAndThat`, for consistency and discoverability.
