### ISSUE TITLE
HasUrlParameter - setParameter method not executed

### ISSUE THREAD

**Issue by Shridhad** [vaadin/flow#3831]
I have PolymerTemplate which implements `HasUrlParameter` and overrides the `setParameter` method. But the method does not get executed on navigation.

```java
@Route("store")
@HtmlImport("views/storefront/vc-storefront-view.html")
@Tag("vc-storefront-view")
public class StorefrontView extends PolymerTemplate<TemplateModel> implements HasUrlParameter<String> {

	@Override
	public void setParameter(BeforeEvent event, @WildcardParameter String parameter) {
		System.out.println("Param " + parameter);
	}
}
```

In this case, I expect the method to be called on navigating to `/store` and sub routes. But, 
* I navigate to `/store` the page is rendered correctly, but the method `setParameter` is not executed.
* Sub routes don't work. i.e. `/store/abcd` returns 404.

**Comment by Shridhad** [comment]
This is no bug. It is issue with webpage project as it is still using legacy router.

**Comment by anikolv** [comment]
Facing the same issue. What webpage project and what legacy router, please give more detailed explanation. Its working with standart vaadin component but not working properly for polymer templates.

**Comment by Legioth** [comment]
@anikolv That's vaadin.com that that used to use the original Router implementation that was replaced by the current implementation around the times of Flow version 0.1.22. Please create a new issue with reproduction instructions if you're having an issue with anything that is nowadays part of Flow.
