### ISSUE TITLE
Push ui.access() not updating UI

### ISSUE THREAD

**Issue by boppleton** [vaadin/flow#3833]
In Vaadin 8, I am able to asynchronously update a Grid with incoming data using the access() method of UI, which locks the thread and performs the updates, then pushes them to the screen automatically without the client having to request it.

`access(() -> addMessage(message));`

I am trying to use vaadin flow now, and since the main class you start with doesn't extend UI, I am trying to do it like this:

`UI.getCurrent().access((Command) () -> addTrade(message))`

However it is not working, and you have to click somewhere on the page for the update to happen. I have the `@Push` annotation on my `MainView` class where i'm doing this, my servlet has `asyncSupported = true`, and i've tried other ways of getting UI like `getUI().get().access()'

**Comment by Artur-** [comment]
Probably solved by #3811, if not then a test case is needed

**Comment by Legioth** [comment]
You can try a workaround already now: `grid.getElement().getNode().markAsDirty();`.

**Comment by boppleton** [comment]
Turns out this is a confirmed bug, and the workaround from @Legioth works for now.  I believe #3811 will fix it but you can use the workaround for now.

**Comment by Legioth** [comment]
Assumingly fixed by https://github.com/vaadin/flow/pull/3811
