### ISSUE TITLE
HasValue should handle getValue/setValue automatically when possible

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3835]
When you integrate a web component using `HasValue`, there are defaults for the client side property to use and what event to listen to for updates BUT you have to implement `setValue` and `getValue` yourself even though they mostly follow the same pattern:

```
    public void setValue(Integer value) {
        if (!Objects.equals(value, getValue())) {
            getElement().setProperty(getClientValuePropertyName(), value);
        }
    }
    public Integer getValue() {
        return getElement().getProperty(getClientValuePropertyName(), "0");
    }

```
There is nothing in this implementation which is specific to my web component integration except the `0` default property value, which actually should match `getEmptyValue()`. Additionally this gives me the false feeling that I have now completed my `HasValue` implementation and it will just work. In practice, there is nothing that synchronizes the value from the client to the server although all the information is provided in `HasValue`

This could be improved by implementing #3834 so that the part of `HasValue` which is tied to the element is an  abstract class instead of an interface and
 * Define a constructor which requires the default value for the property so I realize I have to define it
 * Make the constructor set up value synchronization
 * Add default implementations for `setValue` and `getValue` based on the property
 * Add conversion methods between `V` and a type supported by `Element.setProperty`, e.g. `V fromProperty(propertyValue)` and similar `toProperty` with defaults that work for supported types

The goal would be to be able to support `HasValue` in any web component integration with an integer `value` property and a `value-changed` event without needing to define anything else but the default value.

**Comment by Legioth** [comment]
You also need to remember to add the right `@Synchronized` annotation: https://github.com/vaadin/flow/issues/3591

**Comment by Legioth** [comment]
There are now separate classes for that purpose: `AbstractField`,  `AbstractSinglePropertyField` and soon also `AbstractCompositeField`.
