### ISSUE TITLE
DatePicker format bug when choosing day above 12 with polish locale

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow#3836]
_From @lolytxd on April 5, 2018 13:37_

Vaadin version: 10.0.0.beta5

### Description
When I choose days from 1-12 date format is MM.dd.yyyy, but when i choose day above 12, eg. 13, then the date format is switching to dd.MM.yyyy and the component shows error, because it takes 13 as month.

### Actual outcome
Outcome, when i choose 12th of April from date picker:
![image](https://user-images.githubusercontent.com/11396254/38368305-4041e8d8-38e5-11e8-9ea3-2c5ce4ff7ec1.png)

Then when I click calendar icon:
![image](https://user-images.githubusercontent.com/11396254/38368328-4b92623a-38e5-11e8-9434-8c2e6cb02326.png)

Outcome, when i choose 13th of April from date picker:
![image](https://user-images.githubusercontent.com/11396254/38368418-88a2525c-38e5-11e8-80e9-8df46b61010f.png)

Then when I click calendar icon:
![image](https://user-images.githubusercontent.com/11396254/38368429-90a12b86-38e5-11e8-99e3-c1cbe7fa4a60.png)

When I manually write 4.13.2018 into input field and click enter, the date switches to 13.04.2018 and component shows error too, but when i write 4.13.2018 and then click somewhere on site, the date switches to 13.04.2018 but component doesn't show error.

### Steps to reproduce
For this example I used project from https://vaadin.com/start/v10-project-base and I changed vaadin-version in pom.xml ```<vaadin.version>10.0.0.beta5</vaadin.version>```

I changed MainView class like this:
```
@BodySize(height = "100vh", width = "100vw")
@HtmlImport("styles/shared-styles.html")
@Route("")
@Theme(Lumo.class)
@Push(transport = Transport.LONG_POLLING)
public class MainView extends VerticalLayout {

	public MainView() {
		DatePicker datePicker = datePicker("Data");
		datePicker.setLocale(new Locale("pl", "PL"));
		add(datePicker);
	}

	private DatePicker datePicker(String caption) {
		DatePicker datePicker = new DatePicker(caption);
		datePicker.getElement().getStyle().set("--lumo-space-m", "0px");
		datePicker.setI18n(new DatePickerI18n().setWeek("tydzień")
				.setCalendar("kalendarz").setClear("wyczyść")
				.setToday("dziś").setCancel("anuluj").setFirstDayOfWeek(1)
				.setMonthNames(Arrays.asList("styczeń", "luty", "marzec",
						"kwiecień", "maj", "czerwiec", "lipiec", "sierpień",
						"wrzesień", "październik", "listopad", "grudzień"))
				.setWeekdays(Arrays.asList("poniedziałek", "wtorek", "środa",
						"czwartek", "piątek", "sobota", "niedziela"))
				.setWeekdaysShort(Arrays.asList("niedz", "pon", "wt", "śr", "czw", "pt",
						"son")));
		datePicker.setWidth("calc(50% - .25rem)");
		return datePicker;
	}
}
```

### Browsers Affected
- [x] Chrome 65.0.3325.181 x64
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

_Copied from original issue: vaadin/vaadin-date-picker#530_

**Comment by pleku** [comment]
Issue moved to [vaadin/vaadin-date-picker-flow #57](https://github.com/vaadin/vaadin-date-picker-flow/issues/57) via [**ZenHub**](https://www.zenhub.com/)
