### ISSUE TITLE
DatePicker always shows error with polish locale

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow#3837]
_From @lolytxd on April 5, 2018 14:16_

Vaadin version: 10.0.0.beta5

### Description
When I choose day the component shows error.

### Actual outcome
When i choose 1st of April from date picker:
![image](https://user-images.githubusercontent.com/11396254/38371214-29edfbec-38ec-11e8-9632-7350a423da18.png)

When i choose 20th of April from date picker:
![image](https://user-images.githubusercontent.com/11396254/38371238-3bf688b8-38ec-11e8-91c7-5291beb8cf97.png)

With date picker opened:
![image](https://user-images.githubusercontent.com/11396254/38371258-45223db0-38ec-11e8-988d-e53ea8b5ece8.png)

### Steps to reproduce
For this example I used project from https://vaadin.com/start/v10-project-base and I changed vaadin-version in pom.xml ```<vaadin.version>10.0.0.beta5</vaadin.version>```

I changed MainView class like this:
```
@BodySize(height = "100vh", width = "100vw")
@HtmlImport("styles/shared-styles.html")
@Route("")
@Theme(Lumo.class)
@Push(transport = Transport.LONG_POLLING)
public class MainView extends VerticalLayout {

	public MainView() {
		DatePicker datePicker = datePicker("Data");
		datePicker.setLocale(new Locale("pl", "PL"));
		add(datePicker);
	}

	private DatePicker datePicker(String caption) {
		DatePicker datePicker = new DatePicker(caption);
		datePicker.getElement().getStyle().set("--lumo-space-m", "0px");
		datePicker.setI18n(new DatePickerI18n().setWeek("tydzień")
				.setCalendar("kalendarz").setClear("wyczyść")
				.setToday("dziś").setCancel("anuluj").setFirstDayOfWeek(1)
				.setMonthNames(Arrays.asList("styczeń", "luty", "marzec",
						"kwiecień", "maj", "czerwiec", "lipiec", "sierpień",
						"wrzesień", "październik", "listopad", "grudzień"))
				.setWeekdays(Arrays.asList("poniedziałek", "wtorek", "środa",
						"czwartek", "piątek", "sobota", "niedziela"))
				.setWeekdaysShort(Arrays.asList("niedz", "pon", "wt", "śr", "czw", "pt",
						"son")));
		datePicker.setWidth("calc(50% - .25rem)");
		return datePicker;
	}
}
```

### Browsers Affected
- [ ] Chrome
- [x] Firefox 59.0.2 x64
- [ ] Safari
- [x] Edge 41.16299.15.0
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

_Copied from original issue: vaadin/vaadin-date-picker#531_

**Comment by pleku** [comment]
Issue moved to [vaadin/vaadin-date-picker-flow #56](https://github.com/vaadin/vaadin-date-picker-flow/issues/56) via [**ZenHub**](https://www.zenhub.com/)
