### ISSUE TITLE
DatePicker setMin and setMax bug with polish locale

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow#3838]
_From @lolytxd on April 5, 2018 14:25_

Vaadin version: 10.0.0.beta5

### Description
When I set min or max on datePicker, the set range is incorrect. Component takes months as days and days as months.

### Actual outcome
I've chosen 1st of April 2018 from date picker in component "Date from", and in component "Date to" I've set min to value from component "Date from". The set range in component "Date to" is incorrect, because I can choose date before 1st of April till 4th of January.

![image](https://user-images.githubusercontent.com/11396254/38371678-55575fac-38ed-11e8-9b97-696e3f2cd78c.png)

### Steps to reproduce
For this example I used project from https://vaadin.com/start/v10-project-base and I changed vaadin-version in pom.xml ```<vaadin.version>10.0.0.beta5</vaadin.version>```

I changed MainView class like this:
```
@BodySize(height = "100vh", width = "100vw")
@HtmlImport("styles/shared-styles.html")
@Route("")
@Theme(Lumo.class)
@Push(transport = Transport.LONG_POLLING)
public class MainView extends VerticalLayout {

	public MainView() {
		DatePicker datePickerFrom = datePicker("Date from");
		DatePicker datePickerTo = datePicker("Date to");
		datePickerFrom.setLocale(new Locale("pl", "PL"));
		add(datePickerFrom);

		datePickerFrom.addValueChangeListener(e -> {
			datePickerTo.setMin(e.getValue());
		});

		datePickerTo.setLocale(new Locale("pl", "PL"));
		add(datePickerTo);

		datePickerTo.addValueChangeListener(e -> {
			datePickerFrom.setMax(e.getValue());
		});
	}

	private DatePicker datePicker(String caption) {
		DatePicker datePicker = new DatePicker(caption);
		datePicker.getElement().getStyle().set("--lumo-space-m", "0px");
		datePicker.setI18n(new DatePickerI18n().setWeek("tydzień")
				.setCalendar("kalendarz").setClear("wyczyść")
				.setToday("dziś").setCancel("anuluj").setFirstDayOfWeek(1)
				.setMonthNames(Arrays.asList("styczeń", "luty", "marzec",
						"kwiecień", "maj", "czerwiec", "lipiec", "sierpień",
						"wrzesień", "październik", "listopad", "grudzień"))
				.setWeekdays(Arrays.asList("poniedziałek", "wtorek", "środa",
						"czwartek", "piątek", "sobota", "niedziela"))
				.setWeekdaysShort(Arrays.asList("niedz", "pon", "wt", "śr", "czw", "pt",
						"son")));
		datePicker.setWidth("calc(50% - .25rem)");
		return datePicker;
	}
}
```

### Browsers Affected
- [x] Chrome 65.0.3325.181 x64
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

_Copied from original issue: vaadin/vaadin-date-picker#532_

**Comment by pleku** [comment]
Issue moved to [vaadin/vaadin-date-picker-flow #55](https://github.com/vaadin/vaadin-date-picker-flow/issues/55) via [**ZenHub**](https://www.zenhub.com/)
