### ISSUE TITLE
ClassCastException when using @EnableAsync in Spring

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#3843]
With Spring, if using `@EnableAsync` I'm starting getting cast exceptions e.g.
```
java.lang.ClassCastException: com.sun.proxy.$Proxy319 cannot be cast to
com.vaadin.flow.component.Component
```
but if I set `@EnableAsync(proxyTargetClass = true)` then all is working again.

I don't know what happens exactly here, but from the annotation docs I understand that the annotation changes the way *all* proxy are created—not just `@Async` annotated ones.

Don't know if this is something that should be fixed in Flow or just documented.

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/spring #261](https://github.com/vaadin/spring/issues/261) via [**ZenHub**](https://www.zenhub.com/)
