### ISSUE TITLE
Avoid confusingly ignored @ParentLayout

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3865]
`@ParentLayout` is only effective on classes that implement `RouterLayout`, but ignored in association with `@Route`. To help avoid confusing situations, we should either report a stray `@ParentLayout` as a deployment-time error with an error message referring to the `@Route` parameter, or alternatively change in which cases the annotation is considered so that the confusing situation could be avoided.

**Comment by Legioth** [comment]
Different users repeatedly bring up cases where the difference between `@ParentLayout` and the `layout` parameter in `@Route` has caused problems that are relatively hard to debug. I'd propose immediately making `@ParentLayout` supported in all cases and deprecating the `@Route` parameter. If both are defined, the `@Route` parameter should still be honoured to reduce the amount of unexpected changes.

**Comment by haiwan** [comment]
Just to add that another case of confusion is that @ParentLayout DOES work with Error View( a component that implements HasErrorParameter interface), but doesn't work with a normal view.

**Comment by bogdanudrescu** [comment]
We should really think well about how to design and fix this, because url templates are bringing some different semantics than those we already have.
