### ISSUE TITLE
Make it possible for Component constructors to known whether the instance is standalone or defined in a tempalte

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3879]
The previews shown when using Designer doesn't run any server-side logic, which means that there might be surprises for the user when the application is run with Flow and there is server-side initialisation logic in the Component class that makes things work in a different way than what is shown  in Designer. The same can also happen with a manually created template when toggling between using or not using `@Id` or `@Uses` for that particular component.

We cannot fully prevent this from happening, but we should make it easy for the component implementor to check whether the component is created as a standalone component or through a template through which the component might already be initialized.

This can be implemented based on the fact that in regular cases, the `Component()` super constructor will create a new `Element` instance, whereas the template-related cases will use a `ThreadLocal` to inject a precreated `Element` instance which is a virtual child of the template component. `Composite` might also require some special handling (and should thus at least require a test case of its own).

**Comment by pleku** [comment]
This should be documented in the upcoming web component integration documentation, as to "how to make your web component play nicely with designer and id-mapping". Also update `@Id` mapping (and  `@Uses`) documentation.

**Comment by Legioth** [comment]
Implementation detail: It might make sense to add some low-level API for checking whether an `Element` is a "real" child or a "virtual" child of its parent (assuming it has a parent at all).

**Comment by pleku** [comment]
Usage example, should be highlighted similarly in the documentation:
```java
public Wysiwyge() { initComponent() }
private void initComponent() { 
    if (!isTemplateMapped()) {
         // init all the DOM here
    }
}
```

**Comment by gilberto-torrezan** [comment]
Sorry, the status of the ticket was changed by the reviewer, it was moved before being ready.

As for the `web component integration documentation`, which file is that? I couldn't find it. Or is it still being created?

**Comment by pleku** [comment]
>As for the web component integration documentation, which file is that? I couldn't find it. Or is it still being created?

Yes, https://github.com/vaadin/flow-and-components-documentation/pull/75.
This is a minor thing though
