### ISSUE TITLE
Enabling/disabling polymer element works weird with `@Id` injected elements.

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#3882]
I have a polymer component with an injected components.
The polymer component is disabled from the very beginning.
Its injected component also becomes disabled.
That's OK.

But if I enable the polymer component the injected component doesn't become enabled.

See below the source code.

```java

@Tag("registration-form")
@HtmlImport("src/registration-form.html")
public class RegistrationForm extends PolymerTemplate<TemplateModel>
        implements HasEnabled {

    @Id
    private TextField name;

    @Id
    private Element enable;

    public RegistrationForm() {
        enable.synchronizeProperty("checked", "checked-changed",
                DisabledUpdateMode.ALWAYS);
        enable.addPropertyChangeListener("checked", this::handleEnabled);
        setEnabled(false);
    }

    private void handleEnabled(PropertyChangeEvent event) {
        setEnabled((Boolean) event.getValue());
    }

    @EventHandler
    private void register() {
        String userName = name.getValue();
        System.out.println("Register user with name='" + userName);
    }
}

```

```html
<link rel="import" href="/frontend/bower_components/polymer/polymer-element.html">
<link rel="import" href="/frontend/bower_components/vaadin-checkbox/vaadin-checkbox.html">

<dom-module id="registration-form">
    <template>
        <vaadin-text-field id='name'>{{name}}</vaadin-text-field>
        <vaadin-checkbox id='enable'>Accept License Agreement</vaadin-checkbox>
    </template>
    <script>
         class RegistrationForm extends Polymer.Element {
           static get is() {return 'registration-form'}
         }
         customElements.define(RegistrationForm.is, RegistrationForm);
    </script>
</dom-module>
```

**Comment by denis-anisimov** [comment]
Note that in the example above the `enable` is injected as an `Element` and should not update its `disabled` attribute ever (according to agreed impl).
But the `TextField` instance is injected as a component and it gets `disabled` attribute from the very beginning correctly and doesn't remove it when the polymer component becomes enabled.

**Comment by Legioth** [comment]
I guess this happens because all the logic for propagating changes is implemented based on `Element.getChildren()` instead of considering all child state nodes.

**Comment by caalador** [comment]
It's down on the stateNode side. The problem is that when state changes we inform all children, but the @Id is a virtual child of the template isn't it?

**Comment by denis-anisimov** [comment]
Yes, it's a virtual child.

Two things:
- if it's not notified anyhow then why it becomes disabled when the component is disabled from the very beginning.
- if it's notified then why it doesn't become enabled?

I'm fine with every behavior (though may be we may update the logic to care about virtual children as well) but it should be consistent: either it works or it doesn't work at all for virtual children.
