### ISSUE TITLE
TemplateRenderer cannot access enum properties / getter.

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#3886]
I want to add grid columns by using the TemplateRenderer as shown here: https://vaadin.com/docs/v10/flow/components/tutorial-flow-grid.html. with beta7. Works fine, except for enumerations. 

My bean type `Project` contains a property of type `ProjectPhase`, which is an enum with a property `text` (a human readable represenation) and a respective getter..

With the following line of code this should be added:
```
projectGrid.addColumn(TemplateRenderer.<Project>of("[[item.phase.text]]").withProperty("phase", Project::getPhase)).setHeader("Phase")
```

The header is shown correctly, the detail rows are empty. Changing the item reference to `[[item.phase]]`, the cell shows the usual string representation of the enumeration. 

Using the TemplateRenderer for "normal" class properties works well, like in this example (Customer class with a name property).

```
projectGrid.addColumn(TemplateRenderer.<Project>of("[[item.customer.name]]").withProperty("customer", Project::getCustomer)).setHeader("Customer")
```

```
public class Project extends StorageObject {
	// ...     
	private ProjectPhase phase;
	// ...
	public ProjectPhase getPhase() {...}
}

public enum ProjectPhase {
	//...
	private String text;
	// ...
	public String getText() {...}
}
```

**Comment by Legioth** [comment]
Enum values are always sent to the client as `Enum.name()` and not as generic beans. You can replace `Project::getPhase` with `project -> project.getPhase().getText()` if you want to send a custom textual representation to the client.
