### ISSUE TITLE
Custom URLs are incorrectly defined

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3892]
"A generic URI is of the form:

 scheme:[//[user[:password]@]host[:port]][/path][?query][#fragment]
"

Given e.g. a `frontend://foo.html` URL, this matches the form above BUT `foo.html` is the `host` part, not a `path` as it should be. 

This matters when you are trying to normalize URLs, such as `frontend://bar/../foo.html`, which you would expect to be normalized to `frontend://foo.html` but it will not as `bar` is a `host` and not part of the `path`.

The correct way to define the URLs would be `frontend:///bar/../foo.html` where the path part is then `/bar/../foo.html` and should still be interpreted as relative to the `frontend` location. If done this way, e.g. `URI.normalize()` would produce the expected result

**Comment by Legioth** [comment]
I don't believe the actual issue is fixed (i.e. that our design is incompatible with the URI spec). The only thing that is fixed is that we are working around the issues caused by that spec mismatch.

**Comment by Legioth** [comment]
A fix would mean that we would change to using e.g. `frontend:///` instead of `frontend://` throughout the entire framework, including all documentation and such.

**Comment by pleku** [comment]
What are the benefits from that? I don't see any gain, it would just unnecessarily complicate things for the users.

If necessary, we can add a mention of our ill practices to necessary parts in the documentation.

**Comment by Artur-** [comment]
I don't think we want to change the definition so I would consider this done
