### ISSUE TITLE
Cache result when parsing HTML dependencies

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3894]
The partly broken cache implementation in `HTMLDepedencyParser` is removed in #3893. It should be re-introduced in one way or another, perhaps so that dependencies are cached globally in a `<String,Set<String>>` import name (normalized) to a set of dependency imports and deduplication is taken care of elsewhere when loading resources

**Comment by pleku** [comment]
Deduplication is nowdays handled by Webpack for JS modules. Issues might arrise if there are somehow different versions loaded but that has nothing to do with this issue described here.

I'm ready to say we will not fix this for the 14 compatibility mode or Vaadin 10 as we have no shortage of more important things to do.
