### ISSUE TITLE
VAADIN Flow CDI

### ISSUE THREAD

**Issue by pmdeville** [vaadin/flow#3896]
As far as I understood CDI for vaasdn flow is not one of the priority. I am surprised this functionality is no longer part of the vaadin mainstream as of the vaadin 8.  It would be nice to still be able to consider JEE since there are still a lot of professional application that are using this techno.

**Comment by pleku** [comment]
CDI add-on for Flow is a priority, it just hasn't been the highest one thus far. There is a community made version already available https://github.com/kumm/flow-cdi-addon, and we are looking at working with the contributor to make it an official one.

Closing this as a duplicate for https://github.com/vaadin/flow/issues/456.
