### ISSUE TITLE
Test manually on supported servers 

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3897]

**Comment by Peppe** [comment]
Tested servers
- Apache Karaf 4.2.0
- Apache Tomcat 8.0.50
- Apache Tomcat 8.5.30
- Apache Tomcat 9.0.7
- IBM WebSphere Application Server 18 Liberty
- JBoss EAP 7.1
- Oracle WebLogic 12.2.1.3
- Paraya Micro 5.181
- Paraya Server 5.181
- Wildfly 8.2.1.Final
- Wildfly 9.0.2.Final
- Wildfly 10.1.0.Final
- Wildfly 11.0.0.Final
- Wildfly 12.0.0.Final
