### ISSUE TITLE
ClassCastException without casts in exception handlers

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3902]
An exception thrown as `throw new IllegalArgumentException(new NullPointerException())` will be matched by a handler implementing `HasErrorParameter<NullPointerException>` because of logic trying to (recursively) match `exception.getCause()` as well if no handler is registered specifically for the original exception. In this situation, `ErrorParameter<NullPointerException>.getException()` returns the `IllegalArgumentException` instance, which in turn causes an unexpected `ClassCastException` when assigning that instance to a field of type `NullPointerException`.

**Comment by Legioth** [comment]
From what I see, there are three potential ways out of this:
1. Only match handlers based on the original exception
2. If matching based on causes, then the cause should be passed to `HasErrorParameter` instead of the original exception
3. Remove the type parameter from `HasErrorParameter.getException()` and make it return `Exception` instead.

**Comment by pleku** [comment]
>3. Remove the type parameter from HasErrorParameter.getException() and make it return Exception instead.

This would be an easy fix not changing any behaviour at this point. There hasn't been much feedback about error views, though I would suspect that it is because lack of usage.

**Comment by Legioth** [comment]
Yet another alternative would be to combine 2. and 3. so that there are two methods in `ErrorParameter<T>`. One returns a potentially unwrapped `T` and the other returns the original exception without any generic type. If we do 3. now, we should preferably do it in a way that allows adding back a generic method with the expected exception.

**Comment by pleku** [comment]
As suggested, we'll do 2) and 3):
- use cause instead of the caught type for `ErrorParameter` type
- add the method `Exception getCaughtException()` to `ErrorParameter`.
