### ISSUE TITLE
Build and deploy Maven plugin docs

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3903]
The Maven plugin docs should be built and deployed, as you typically do with Maven plugins. 

http://maven.apache.org/guides/development/guide-plugin-documentation.html

"It is recommended that you let Maven generate the basic information for the plugin to make sure that that the basic information is always accurate and synchronized with the plugin implementation.

Documentation is generated by running

`mvn site`
It will generate a plugin site based on the information in the POM, src/site and other reporting plugins configured in the POM. The most important reporting plugin is the Maven Plugin Plugin which will generate the documentation for each plugin goal based on the mojo annotations. But in order for the generated site to be usable, the required information should be available to the Maven Site Plugin."

**Comment by Artur-** [comment]
https://vaadin.com/docs/v10/flow/migration/7-tools-integrations.htmls should refer to these docs

**Comment by pleku** [comment]
Related to #547

**Comment by pleku** [comment]
That we don't have any docs for the maven plugin.

**Comment by pleku** [comment]
Will be done for the platform plugin intstead https://github.com/vaadin/platform/pull/145
