### ISSUE TITLE
Need MenuBar component similar to the MenuBar from Vaadin 8

### ISSUE THREAD

**Issue by loefflefarn** [vaadin/flow#3908]
Hello,

I'm wondered about the remove of the `MenuBar` component. I used it for my navigation between the views in my UI. I need it because of sub `MenuItem`s. 

Would you reimplement it in Vaadin 10?

What are the reasons for the remove of the `MenuBar`?

Greetings!

**Comment by pleku** [comment]
We do have plans for making Java integration for the drop-down-menu https://vaadin.com/components/vaadin-dropdown-menu/html-examples/dropdown-menu-basic-demos, but it does not support hierarchical displaying of data at the moment.

>What are the reasons for the remove of the MenuBar?

For clarity, I want to emphasize that _we have not removed anything_, the framework and the component sets are totally new, we have just deemed `MenuBar` to not be a high priority for us to add at this point, or in the near future to be honest.

**Comment by loefflefarn** [comment]
A better one, in my case, for the navigation would be the [context-menu](https://vaadin.com/components/vaadin-context-menu). Can you also add a Java integration for this one?

**Comment by pleku** [comment]
Yes, we are going to the Java API for `vaadin-context-menu`. I would hope to get it done quite soon after V10 GA release, but I can't give any promises.

**Comment by pleku** [comment]
Just an update, there is already a `vaadin-context-menu` version `1.0.0.alpha1` that is compatible with V10, but will not be added to the platform, so you need to declare it separately in your dependency management. We are doing some additional fixes to it, to make it work better with `Grid` and are then going to release 1.0.0.beta1 version of it.

**Comment by pleku** [comment]
`ContextMenu` has been available since Vaadin 12, and hierarchy support for it is currently WIP for Vaadin 13.

The issue to follow for full MenuBar component is https://github.com/vaadin/vaadin-core/issues/208 but I'll keep this open for now for discoverability.

**Comment by pleku** [comment]
Menubar is available in Vaadin 14.
