### ISSUE TITLE
Deploying a Vaadin app to Tomcat in production mode broken

### ISSUE THREAD

**Issue by Peppe** [vaadin/flow#3919]
Deploying a Vaadin app to Tomcat 8.0.x, 8.5.x and 9.0.x  being built with production mode has some visual elements broken.

## Steps to reproduce
1) Download Beverage buddy from https://vaadin.com/start/v10-simple-ui
2) Build it with `mvn package -Dvaadin.productionMode`
3) mvn package -Dvaadin.productionMode
4) Download Tomcat and extract it
5) copy the built war to tomcat/webapps
6) go to tomcat/bin
7) `chmod +x catalina.sh` and `./catalina.sh run`
8) Open up the app in your browser at `http://localhost:8080/<name-of-your-war-file>`

## Broken parts
![screen shot 2018-04-16 at 14 52 36](https://user-images.githubusercontent.com/525503/38916404-ecf41d62-42ef-11e8-8981-8d0e74636ce5.png)

- Search bar textfield is missing background
- New review button is missing background
- Edit buttons are missing colors

![screen shot 2018-04-16 at 14 47 18](https://user-images.githubusercontent.com/525503/38916414-f721bb82-42ef-11e8-9d14-81403b6dc371.png)

- The dialog is missing the background
- All the components within the dialog is missing the background

**Comment by Peppe** [comment]
Tested within the ticket https://github.com/vaadin/beverage-starter-flow/issues/193. There might be more info.

**Comment by pleku** [comment]
Most likely caused wrong maven plugin version, same as https://github.com/vaadin/beverage-starter-flow/issues/204

**Comment by Peppe** [comment]
I took a new version today and retested prod and noprod with push on all three servers. Now the theme looks good so I guess the above mentioned fixed it. 

On my first run on 8.0 in production mode, I got a system error box in the top right corner with no error message in it. It probihited me from interacting with the app until I clicked on it. I have not been able to reproduce it again after that, but it might jump up to random end users...

**Comment by Legioth** [comment]
> On my first run on 8.0 in production mode, I got a system error box in the top right corner with no error message in it.

This might have happened because Tomcat had stored serialized an old HTTP session and it wasn't compatible with the new version. But there's no way to tell without reproducing.
