### ISSUE TITLE
Changing a template button text with Java when button defined in template appends the new text, instead of replacing it.

### ISSUE THREAD

**Issue by Peppe** [vaadin/flow#3921]
## Steps to reproduce
1) Download Beverage buddy from https://vaadin.com/start/v10-simple-ui
1) Edit ReviewsList.java#83 clickListener to `addReview.addClickListener(e -> addReview.setText("Updated")); `
1) `mvn jetty:run`
1) Open app in `http://localhost:8080` and click button `New Review` button

## Expected behaviour
Button says `Updated`.

## Actual behaviour
Button says `New Review Updated`

![screen shot 2018-04-18 at 10 21 09](https://user-images.githubusercontent.com/525503/38917119-6b6ac41e-42f2-11e8-881c-61b9a722ddc9.png)

## Versions
(unmodified from what was downloaded) 

<vaadin.version>10.0.0.beta7</vaadin.version>
vaadin-core 10.0.0.beta7
flow 10.0.0.beta6
vaadin-button-flow 1.0.0.beta4
vaadin-button 2.0.0-beta3

![screen shot 2018-04-18 at 10 24 39](https://user-images.githubusercontent.com/525503/38917220-bd636cbc-42f2-11e8-8bb3-86c5ca386a2c.png)

**Comment by caalador** [comment]
One note. Now that button setText also removes all it means that the `+` icon that is defined in the template will also be removed.
