### ISSUE TITLE
prod mode isn't working in safari 10

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/flow#3959]
Tested with 2ee9f37 of beverage-starter-flow.
Running `mvn clean jetty:run -Dvaadin.productionMode`
Test device was simulated iPad 5th generation, ios 10.3.1
Actual result:
* Plenty of client-side exceptions
* App didn't load
* Looks like this:
![image](https://user-images.githubusercontent.com/9820084/39049623-e8636732-44aa-11e8-8b8a-6b8372300f0f.png)

**Comment by alvarezguille** [comment]
App loaded properly in safari 9

**Comment by Artur-** [comment]
Probably caused by / related to https://github.com/Polymer/polymer-cli/issues/946

**Comment by pleku** [comment]
As [discussed](https://vaadin.slack.com/archives/C6RAXJATF/p1524646248000303), should update the dependency, build a local snapshot version of maven plugin, verify using the snapshot that lastest Beverage Buddy and Bakery works OK in _all the browsers_.

**Comment by SomeoneToIgnore** [comment]
Updated the `babel-preset-minify` to the latest version (`0.4.0`), this caused errors for `vaadin-charts-flow` in Chrome and `beverage-buddy` in IE11:

<img width="1680" alt="screen shot 2018-04-25 at 16 27 05" src="https://user-images.githubusercontent.com/2690773/39249130-9f6d48c2-48a6-11e8-857a-d2d117a953fa.png">
<img width="1792" alt="screen shot 2018-04-25 at 16 33 05" src="https://user-images.githubusercontent.com/2690773/39249131-9f8cba36-48a6-11e8-9d72-6b23ca2c4180.png">

Have also tried updating all the dependencies possible with the same result.

**Comment by ZheSun88** [comment]
I have seen the same view when i ran the BB with IE 11. And i thought it is a cache problem, because after i removed the project and restarted again, everything works as excepted.. need to be tested one more time.

**Comment by ZheSun88** [comment]
Test with *Ipad air 2* (IOS 10.3.3)
i have pushed a branch with updated dependency of `flow-maven-plugin`, both beverage buddy and vaadin-charts-flow are failed;

with https://caniuse.com/#feat=let, IOS 10.3 has a potential problem with let
```
let bindings in for loops are incorrectly treated as function-scoped instead of block scoped.

**Comment by ZheSun88** [comment]
This issue is getting larger than the ticket report, it affects not only Safari running on IOS 10, but also chrome and firefox (have tested positive with IOS 10.3).  Documentation is going to mention that and we are going to provide the `custom-elements-es5-adapter` for all the browsers that running on IOS 10.

**Comment by Artur-** [comment]
That is logical as all browsers on iOS use Safari 10 (i.e. webkit)

**Comment by ZheSun88** [comment]
Okay, then it is easier to understand for me now. Thanks Artur.
