### ISSUE TITLE
Cannot construct complex predicates with AND and OR

### ISSUE THREAD

**Issue by docwho2** [vaadin/flow#3969]
com.vaadin.flow.function.SerializablePredicate  extends the java.util.function.Predicate however when using AND or OR to generate compound type predicates, the DataProvider functions will not take them because the result is a regular predicate.  Need to define all the methods in those interfaces to also be serializable.  See https://github.com/danekja/jdk-serializable-functional/blob/master/src/main/java/org/danekja/java/util/function/serializable/SerializablePredicate.java for example.  In order to get around this I had to extend Vaadin interface as such:

import com.vaadin.flow.function.SerializablePredicate;
import java.util.Objects;

/**
 *
 * @author sjensen
 * @param <T>
 */
public interface MySerializablePredicate<T> extends SerializablePredicate<T> {

    default MySerializablePredicate<T> and(MySerializablePredicate<? super T> other) {
        Objects.requireNonNull(other);
        return (t) -> test(t) && other.test(t);
    }

    @Override
    default MySerializablePredicate<T> negate() {
        return (t) -> !test(t);
    }

    default MySerializablePredicate<T> or(MySerializablePredicate<? super T> other) {
        Objects.requireNonNull(other);
        return (t) -> test(t) || other.test(t);
    }

    static <T> MySerializablePredicate<T> isEqual(Object targetRef) {
        return (null == targetRef) ? Objects::isNull : object -> targetRef.equals(object);
    }
}

**Comment by elmot** [comment]
Fixed in Flow with #4148
