### ISSUE TITLE
It's not possible to force the flow-maven-plugin to use the nodejs version installed locally

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#3973]
Currently the `flow-maven-plugin` always downloads a nodejs version from internet when building, and completely ignores any nodejs version available in the machine.

This is useful to make sure the build is stable and consistent among different machines, but it should there be an option to skip the download and use whatever version is available locally, if the user wants so.

Related forum thread about the issue: https://vaadin.com/forum/thread/17046997

**Comment by knoobie** [comment]
This should be fixed by https://github.com/vaadin/flow/pull/4543, right?

**Comment by SomeoneToIgnore** [comment]
Indeed, nice catch, thanks!
