### ISSUE TITLE
The favicon on IE11 is only loaded in the first view

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#3981]
(First reported in this forum post: https://vaadin.com/forum/thread/17056496 )

The favicon is only loaded in the first view of the app. When changing pages (router targets), the favicon is gone. This can be reproduced with the Bakery starter:

![faviconie](https://user-images.githubusercontent.com/7464735/39174830-691c2f4a-47b1-11e8-80ab-f43c7ac6b565.png)

The code that adds the favicon is the following:

```java
@Override
public void configurePage(InitialPageSettings settings) {
	settings.addLink("shortcut icon", "favicon.ico");
	settings.addFavIcon("icon", "favicon.ico", "16x16");
}
```

This doesn't happen in other browsers.

**Comment by eriklumme** [comment]
I was not able to reproduce with IE11 in a VM, can someone confirm this is still a bug?

**Comment by pleku** [comment]
Closed unless someone is able to reproduce this and report here.

**Comment by imneeazmi** [comment]
![iefavicon](https://user-images.githubusercontent.com/22928748/42484632-7b4f14c8-8426-11e8-9222-3c553dc77746.png)

I was able to reproduce the error on the live version of Vaadin's bakery demo.
**IE Version:** 11.112.17134.0
