### ISSUE TITLE
Adding a new Vaadin component import to a template requires a server restart

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#4005]
1. Start from https://vaadin.com/start/v10-simple-ui
2. `mvn jetty:run`
3. Edit `reviews-list.html`
4. Add "Hello" after `<h2 id="header"></h2>` and refresh -> you see hello
5. Wrap "Hello" with `<vaadin-checkbox></vaadin-checkbox>`
6. Add `<link rel="import" href="../../../bower_components/vaadin-checkbox/src/vaadin-checkbox.html">`
7. Refresh -> you see *NO* checkbox
8. Restart the server and refresh -> you see a checkbox

**Comment by pleku** [comment]
This should be fixed in `2.0` for P3 based templates as Flow & webpack is automatically detecting added things.
