### ISSUE TITLE
Inconsistent API for QueryParameters

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#4006]
Citing javadocs:
```
    /**
     * Returns query parameters information with support for multiple values
     * corresponding to single parameter name.
     * <p>
     * Example: {@code https://example.com/?one=1&two=2&one=3} will result in
     * the corresponding map: {@code {"one" : [1, 3], "two": [2]}}
     *
     * @return query parameters information
     */
    public Map<String, List<String>> getParameters() {
        return parameters;
    }
```

Now, `queryParameters.getParameters().get("one")` will return `[1, 3]` and `queryParameters.getParameters().get("two")` will return `[2]`.

However, `queryParameters.getParameters().get("three")` will return not `[]`, but `null`.

**Comment by caalador** [comment]
Closing issue as parameters is a normal Map so it should return null for non existing key.
