### ISSUE TITLE
Grid data provider query has no order information when sorting by grid column header sort "button".

### ISSUE THREAD

**Issue by ghost** [vaadin/flow#4031]
I have a grid with a CallbackDataProvider and want to sort the shown data by clicking a grid column header sort icon. The sort icon is updated to the correct direction, but the query object, that is passed to my data provider does not contain a order info (list is empty). Doesn't work for any of the columns.

The grid is set in a polymer template and added through `@Id` injection. The data is shown correctly.

Grid injection
```
@Id("grid-expert")
private Grid<Person> gridWorktimesExpert;
```

Adding grid information
```
@Override
@Transactional
public void setParameter(BeforeEvent event, Long parameter) {
    // ...
    // Person column
    gridWorktimesExpert.addColumn(Person::getFullName)
                    .setHeader("Contractor")
                    .setFrozen(true)
                    .setSortable(true);
    // ... other sortable, not frozen columns columns
    
    // Setting data provider
    gridWorktimesExpert.setDataProvider(DataProvider.fromCallbacks(
                    query -> personRepository.findAll(DataProviderPageable.of(query)).stream(),
                    query -> (int) personRepository.count())
     );
}
```

**Comment by caalador** [comment]
In latest versions this works as expected and there is a new pageable functionality for spring. Closing issue, Please open new issue with steps if this still presists.
