### ISSUE TITLE
SPIKE: CDI add-on

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4039]
In timebox of one and half a day:
- Familiarize with the CDI add-on for Flow
- Use it in eg. Beverage Buddy and push the code for others to see
- Write a short documentation of the features and how they work, if they are any different to Spring add-on and if there is any weirdness etc.

-> After the timebox, give the example branch and document to the team and then let's have a meeting for discussion about the add-on

**Comment by denis-anisimov** [comment]
Here is the document :

https://docs.google.com/document/d/1rlR8cDAcgOc-0Y4vEFrGEQEKmM6X7344m4U8xC5ypi8/edit

There is a link to the beverage CDI based add-on.

**Comment by denis-anisimov** [comment]
Doc is created, project is created.
Presentation meeting held.
