### ISSUE TITLE
SPIKE: Familiarize how the flow maven plugin works, analyzer and generator works.

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4040]
The goal is to get some understanding of how to get started with moving the analyzer and generator to the maven plugin, and how some understanding on the different parts are executed currently.

**Comment by ZheSun88** [comment]
Short summary:
`webcomponent-analyzer`: read webcomponent API and transform to Json(json_metadata in flow-generated-components package). 
`code-generator`: read the json file from analyzer and produce the generated java class for each component.
`flow-maven-plugin`: at the moment, it is used for production mode only on transpilation, minimasation and bundling.

Starting steps:
As we can keep current behavior for now, it is okay to start with migrating the `gulpfile` from `analyzer` to `flow-maven-plugin`, the `lib` folder would be needed, too. 

one more thing:
according to https://github.com/gulpjs/gulp/issues/505 , gulp.strat() which is used in `analyzer` is not a supported api after 4.0, while flow-maven-plugin is using gulp-3.9.1 and analyzer is using "latest" (4.0.0??? ) then how does it work?
