### ISSUE TITLE
An empty Grid is shown if Grid is placed inside two nested VerticalLayouts

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#4055]
With following code only a gray vertical line is shown:

```
@Route("")
public class MainView extends VerticalLayout {

    public MainView() {

        VerticalLayout vl = new VerticalLayout();

        Grid<String> grid = new Grid<>();

        grid.addColumn(s ->"generated value").setHeader("generated column");

        vl.add(grid);

        add(vl);
    }

}
```

I'd expect at least something to be shown in such setup.

Tested with latest beta (vaadin version 10.0.0.beta8).

**Comment by ZheSun88** [comment]
The reason for causing this is the second VerticalLayout is missing `width`. a quick fix for this would be 
```java
vl.setWidth("100%");
```
let us see what we can do more for this

**Comment by mstahv** [comment]
Thanks dudes, this kind of small issues really makes a difference!
