### ISSUE TITLE
Shift-tab in dialog causes script error

### ISSUE THREAD

**Issue by martinisraelsen** [vaadin/flow#4056]
Hitting shift-tab to tab backwards in a dialog causes a script error. I experienced this in the bakery app as well as my own flow app.

To reproduce:
- Open dialog in bakery (e.g. products)
- Position cursor in price field
- Hit shift-tab

Observed behavior:
Whole screen is grayed out and a script error is shown. It's necessary to reload the page to get rid of the grayness.

Error Message in Safari is "Script Error"
Error Message in Chrome is "TypeError: Cannot read property 'focus' of undefined

Expected behavior:
Cursor moves backwards.

![screen shot 2018-05-02 at 2 35 37 pm](https://user-images.githubusercontent.com/6271003/39545401-bb1e3f98-4e16-11e8-9a75-b64b5400a812.png)
![screen shot 2018-05-02 at 2 38 45 pm](https://user-images.githubusercontent.com/6271003/39545402-bb37cd8c-4e16-11e8-99bb-1936a93ee502.png)

**Comment by denis-anisimov** [comment]
I'm not able to reproduce this neither in Chrome nor in Safari.

Could you please check the latest bakery version ?

If it still there please let me know the browser which you use (is it still Safari and Chrome ?), the bakery version.

**Comment by martinisraelsen** [comment]
Hi Denis,

I just downloaded the latest bakery app and still see the script error occurs Safari, Chrome and Firefox. I also tried online version of the bakery app but did not experience the problem there.

To make sure it wasn't old data or jar files, I purged the maven dependencies, as well as clear browser cache data data. Even trying opening the bakery app in private window. Still saw the error in all three browsers.

**Comment by denis-anisimov** [comment]
OK, I have a suspicion.
Which bakery app do you mean ?
Please give me a link.
Is it binary application which you just deploy ?
If you build it by yourself then are you talking about production mode ?

I will check one more time it locally....

**Comment by denis-anisimov** [comment]
Thanks to @Artur- , looks like I understand the issue now.
Looks like you are using this page to download the app : https://vaadin.com/start/v10-full-stack-spring

The app which you download in the result has outdated platform version `10.0.0.beta3`.
The most recent application uses `10.0.0.beta7` platform version (and I use this version to check the bug).
I still cannot reproduce the bug with `10.0.0.beta7` platform version.
So I suppose it's gone away.
Please wait when our pro tools team update the bakery application on `vaadin.com` site to the most recent version (will be already `beta9`) and then recheck it again.
Thanks.

**Comment by martinisraelsen** [comment]
@denis-anisimov ah good catch. Yes I had downloaded it from the full stack page. I tried updating to beta7 and could not reproduce the issue either.
