### ISSUE TITLE
Generating equals/hashCode in Eclipse for a bean used in a model causes all instances to be equal

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#4063]
Given a model
```
public interface MyModel extends TemplateModel {
List<MyBean> getItems();
}
```
and a bean
```
public class MyBean {

	private int id;
	private String text;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

}

```

If you generate `equals`/`hashCode` using Eclipse for the bean, based on `id`, you get:
```
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MyBean other = (MyBean) obj;
		if (id != other.id)
			return false;
		return true;
	}
```

When the bean is used in the model, all instance now `equals` each other as the fields values are never updated but used in `equals` and `hashCode`.

This is quite unexpected

**Comment by Legioth** [comment]
Can we do anything about this, other than document it and provide the missing helper for creating a real bean from a proxy?

**Comment by Artur-** [comment]
There is a related problem with the generated 
```
if (getClass() != obj.getClass())
```

It will never pass if you compare a `MyBean` from outside the model with a `MyBean` you get from the model, which is a proxy instance

**Comment by pleku** [comment]
We should just document this accordingly for template model tutorials and probably javadocs.
