### ISSUE TITLE
Add StyleGenerator to Grid as in V8

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4074]
I have a grid of calendar weeks and persons where I want to mark the current calendar week through css styles for a better recognition. Currently this is not possible (templates are not a suitable solution).

The request is to extend the `Grid` / `Column` API with some kind of "StyleGenerator" methods as in V8. This API should make it possible to:

1. set class names for a column (like `HasStyle` for `Column`) 
2. set class names for the rows based on a item (like `Grid.setStyleGenerator`  in V8)
3. set class names for single cells (like `Grid.Column.setStyleGenerator` in V8) 

Since all these method produce css class names, they should be usable in combination without problems. To have same names we could name it e.g. `ClassNameGenerator` instead of `StyleGenerator`

Usage examples for my use case
1. mark the current week in a timeline grid: `grid.addColumn("...").addClassName("current-week");`
2. mark persons, that are finished with their project work: `grid.setStyleGenerator(person -> person.isFinished() ? "finished" : null);`
3. mark persons, that are absent for a specific week `grid.addColumn("...").setStyleGenerator(item -> person.isAbsent() ? "absent" : null);`

**Comment by Legioth** [comment]
Issue moved to [vaadin/vaadin-grid-flow #185](https://github.com/vaadin/vaadin-grid-flow/issues/185) via [**ZenHub**](https://www.zenhub.com/)
