### ISSUE TITLE
Model update logic assumes model is never changed on the client

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#4080]
If you do a simple latency compensation on the client side for an added item, you might have something like
```
this.push("todos", {text: text});
this.$server.addTodo(text); // Send to server, may take some time to return
```

This ensures the client view is updated immediately and then should not change anymore when the server call returns, assuming the item was added and stored successfully there.

What happens is that you get duplicate items in the client side model, as the update logic only inserts the new item at a given index.

The same happens with delete, except that you delete two items: the correct immediately, the subsequent one when the server call returns.

**Comment by denis-anisimov** [comment]
I'm not sure I understand the issue.
So in this example 
```
this.push("todos", {text: text});
this.$server.addTodo(text);
```

the `text`  is `{text: text}`, right ?
And `addTodo`  on the server side is a method which adds an item to the model list of items, right ?
So there are two totally unrelated calls : one is on the client side and another one is the server side call.
And the reason why it has to add only one item is unclear for me.
How may the framework know that your intention was to add only one item ?
I would say that the code logically similar to 
```
this.push("todos", {text: text});
this.push("todos", text);
```
Which as expected adds to items to the list.
So the result is expected for me.

I understand your intention to update the client side immediately without waiting the server side but it looks like there should be some other code which should do this somehow.
