### ISSUE TITLE
InitialPageSettings.WrapMode javadoc should describe what is and what it is used for

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#4081]
It's hardly any information to know that it is `Content wrapping mode enum`.  If you remove what's obvious from the type and name, you are left with the info `Content`

If you look at e.g. `addInlineFromFile`, you can see that `@param type` is `dependency type`. Not related to wrapping at all?

**Comment by caalador** [comment]
Latest versions do not contain InitialPageSettings anymore. Closing issue
