### ISSUE TITLE
on-click event for vaadin-checkbox is fired before "checked" changes

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4087]
I have a event handler method registered for the on-click event of a vaadin-checkbox. The checkbox is not checked and gets clicked. This click is caught by my event handler method. When I access the state of the checkbox per `event.currentTarget.checked` the value is `false`. I would expect it here to be `true`, since the checkbox was checked by the user.

HTML
` <vaadin-checkbox checked="{{item.done}}" on-click="onTodoDoneClick"></vaadin-checkbox>`

JS
``` 
onTodoDoneClick(e) {
    (e.currentTarget.checked); // produces false when cb was checked and true when it was unchecked
}
```

**Comment by Artur-** [comment]
You probably want to listen on `checked-changed` if you want to know when the `checked` value changes, regardless of it is using the mouse or the keyboard.

**Comment by stefanuebe** [comment]
Changed it to `<... checked="{{item.done}}" on-checked-changed="..." ...>`. Now the event is fired at page loading for each checkbox when setting the init value for `checked`. Is this intended behavior? O.o

**Comment by stefanuebe** [comment]
Here is the complete template snippet
```
Open
        <div id="container-open">
            <sortable-list on-sort-finish="_onSortFinish" sortable=".sortable">
                <template is="dom-repeat" items="{{todos}}" filter="_isOpen">
                    <div id$="[[item.id]]" class="sortable">
                        <vaadin-horizontal-layout class="todo-row">
                            <vaadin-checkbox on-checked-changed="onTodoDoneClick"></vaadin-checkbox>
                            <vaadin-text-field readonly on-change="onTodoNameChange"
                                               on-keypress="_onKey"
                                               on-click="_onClick"
                                               on-blur="_onBlur" class="todo-name" value="{{item.name}}"></vaadin-text-field>
                        </vaadin-horizontal-layout>
                    </div>
                </template>
            </sortable-list>
        </div>


        Done
        <div id="container-done">
            <sortable-list on-sort-finish="_onSortFinish" sortable=".sortable">
                <template is="dom-repeat" items="{{todos}}" filter="_isDone">
                    <div id$="[[item.id]]" class="sortable">
                        <vaadin-horizontal-layout class="todo-row">
                            <vaadin-checkbox checked on-checked-changed="onTodoDoneClick"></vaadin-checkbox>
                            <vaadin-text-field readonly on-change="onTodoNameChange"
                                               on-keypress="_onKey"
                                               on-click="_onClick"
                                               on-blur="_onBlur" class="todo-name" value="{{item.name}}"></vaadin-text-field>
                        </vaadin-horizontal-layout>
                    </div>
                </template>
            </sortable-list>
        </div>
```

**Comment by Legioth** [comment]
Listening for click events is not a reliable way of detecting checkbox value changes for at least two reasons:
1) The change might still be canceled if any click handler does `preventDefault()`.
2) The user might change the checkbox value in other ways than by clicking, e.g. using the keyboard or a screen reader.

What is really needed is a `change` event that is fired whenever the value has changed because of user interaction: https://github.com/vaadin/vaadin-checkbox/issues/81

Until such feature is available, you'd most likely have to listen to `checked-changed` and somehow manually filter out the redundant events.
