### ISSUE TITLE
Template model List<> items are not updated on server side when changed on client side.

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4091]
I have a simple TemplateModel with a getter and setter for a List of items. These items are displayed with a polymer dom-repeat and can be edited by vaadin-text-fields. Expectation here is, that changed made on client side are transported back to server side to be handled in an event handler. 

Currently the items are unchanged. This reflects also back to direct calls of items in the handling method by `@EventData("event.model.item")` (or `@ModelItem` in short).

**Java**
```
public class TodoListDetailView extends PolymerTemplate<TodoListDetailView.Model> implements HasComponents, HasUrlParameter<Long> {
    @EventHandler
    private void handle() {
        // update repository
        System.out.println(getModel().getTodos());
    }

    public interface Model extends TemplateModel {
        @Encode(value = LongToStringEncoder.class, path = "id")
        @Encode(value = LongToStringEncoder.class, path = "list.id")
        void setTodos(List<Todo> list);

        List<Todo> getTodos();
    }
}
```

**Polymer**
```
<template>
        <template is="dom-repeat" items="{{todos}}">
            <vaadin-text-field on-change="handle" class="todo-name" value="{{item.name}}"></vaadin-text-field>
        </template>
</template>
```

Also see: https://github.com/vaadin/flow/issues/4086

**Comment by Legioth** [comment]
Might also be related to https://github.com/vaadin/flow/issues/4080

**Comment by pleku** [comment]
As a workaround, you should be able to use a `@ClientCallable public void update(Todo item) {...}` method and pass the updated item to that one.

**Comment by denis-anisimov** [comment]
I'm able to reproduce a bug.
I have an IT test which shows it.

**Comment by denis-anisimov** [comment]
Apparently this has never be implemented.
So it's kind of may be considered as a known limitation.
We are overriding `_propertiesChanged` polymer element method.
This method is never called when property is updated inside an item in the list.
I will try to see what we can do here.....

**Comment by denis-anisimov** [comment]
Additional info: on the client side two way databinding works as expected for arrays.

**Comment by denis-anisimov** [comment]
`_propertiesChanged` is called but it's called on the `dom-repeat` element   instead of element itself.
It causes some calls on the element itself (like `_flushProperties()`) but there is no info about changed item+property. It only possible to get the changed property which is in this case is array type (no item update).
