### ISSUE TITLE
Encoder does not support primitive types

### ISSUE THREAD

**Issue by Klaudeta** [vaadin/flow#4092]
Writing an encoder for an unsupported primitive type by using their corresponding Class Types throws exception:
`at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:182) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]`

Steps to reproduce:

1. Any X class object  with a primitive type field of long
2. Use the class into a TemplateModel and use some custom Encoder of type ModelEncoder<Long, String> on the field 

Encoding fails with the above exception

**Comment by denis-anisimov** [comment]
I will adjust logic so that it allows to count `long.class`  and `Long.class`  as compatible.

**Comment by Klaudeta** [comment]
You are right, setting the return class to long.class resolves the issue. Never the less it remains a bit intuitive to figure it out without someone helping you. I think it should somewhere be specified or mentioned about using ModelConverter with primitive types by using their counterpart clasess (Long, Integer)
