### ISSUE TITLE
b8 Scroll bar on grid does not disappear when grid.setHeightByRows(true)

### ISSUE THREAD

**Issue by mickoyuh** [vaadin/flow#4093]
Website feedback: "The scrollbar appears and scrolls all of a few pixels."

After fixing this, please close the issue on website external Github  https://github.com/vaadin/vaadin.com/issues/20

**Comment by pleku** [comment]
This is a very unclear issue and if it persists, a new one with proper reproduction instructions should be opened to repository vaadin/vaadin-grid-flow
