### ISSUE TITLE
URI normalization fails for frontend://components/../components/js/hash-actions.html

### ISSUE THREAD

**Issue by paulroemer** [vaadin/flow#4096]
Input: `frontend://components/../components/js/hash-actions.html`
Expected result is `frontend://components/js/hash-actions.html`
Actual result is `frontend://hash-actions.html`

in `HtmlDependencyParser::toNormalizedURI()`.

What might be the issue:
```
            if (normalized.getPath().startsWith("/../")) {
                return normalized.toString()
                        .replaceAll(normalized.getHost() + "/../", ""); // uses replaceAll which expect a regex
            }
```

What will be executed in the end:
```
"frontend://components/../components/js/hash-actions.html".replaceAll("components/../", ""); // wrong result: frontend://hash-actions.html
```

My guess is that you should only use `replace()` instead of `replaceAll`. But there seem to be tests for the normalization that check the special `/../`.

**Comment by Haprog** [comment]
Thanks for the quick fix @Artur-!
