### ISSUE TITLE
Apps don't open inside iOS Safari WKWebView

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4116]
Flow apps don't open with an iOS device using an app internal browser (not a "real" browser). Eg. trying to open vaadin.com links inside Linkedin or Facebook app doens't work. Apparently, links work via the Twitter app.

The iOS apps should be using [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) for viewing the content ([UIWebView](https://developer.apple.com/documentation/uikit/uiwebview) is deprecated)

**Comment by knoobie** [comment]
>  Also, vaadin.com does not open in Firefox app for iOS (I don't think it's using WKWebView): it gets stuck with the dark background and the green spinner.

Same with the **Google App** itself! The main entry for developers / customers who search on mobil e for vaadin.

**Comment by denis-anisimov** [comment]
Do I need iOS device to see what's going on there ?

**Comment by pleku** [comment]
>Do I need iOS device to see what's going on there ?
Most likely unless there are some development tools that allow you to test things with `WKWebView` in macOS. I would not count on it, it used to be so that you need to pay $ to even be able to develop for iOS using xCode, but that was like a decade agp.

**Comment by denis-anisimov** [comment]
OK, thanks. Then someone else who has access to it should take this ticket.

**Comment by caalador** [comment]
At least Flow skeleton starter works through the Facebook application.
Also button press works from there.

**Comment by caalador** [comment]
Skeleton also works through FireFox app on ios.

**Comment by caalador** [comment]
BeverageBuddy works with iOS Facebook and FireFox

**Comment by caalador** [comment]
Vaadin.com works when running it locally using jetty:run
