### ISSUE TITLE
Build issues using GitLab CI

### ISSUE THREAD

**Issue by DimitriLubenski** [vaadin/flow#4122]
- Description of the bug
while building the vaadin flow from the GitLab CI using the production mode there are issues in connecting the yarnpkg.com which is perfectly pingable.

The --network-concurrency 1 should fix this issue, but there is no way to pass this parameter to the yarn. 

`
[INFO] Installing Yarn version v1.6.0
[INFO] Downloading https://github.com/yarnpkg/yarn/releases/download/v1.6.0/yarn-v1.6.0.tar.gz to /builds/login-ops/hlp-resource-manager/target/cache/yarn-v1.6.0.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
May 15, 2018 12:54:50 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Sat, 15 May 2038 12:54:50 -0000; secure; HttpOnly". Invalid 'expires' attribute: Sat, 15 May 2038 12:54:50 -0000
[INFO] Unpacking /builds/login-ops/hlp-resource-manager/target/cache/yarn-v1.6.0.tar.gz into /builds/login-ops/hlp-resource-manager/target/node/yarn
[INFO] Installed Yarn locally.
[INFO] Running 'yarn install' in /builds/login-ops/hlp-resource-manager/target
[INFO] yarn install v1.6.0
[INFO] [1/4] Resolving packages...
[INFO] [2/4] Fetching packages...
[ERROR] error An unexpected error occurred: "https://registry.yarnpkg.com/babel-helpers/-/babel-helpers-6.24.1.tgz: connect EHOSTUNREACH 104.16.59.173:443".
`
- Minimal reproducible example

Using the standard showcase project to reproduce. Tested with flow-maven-plugin / 1.0.0.beta7 on vaadin flow 10.0.0.beta10. Setting the yarn version to the latest v1.6.0 does not help.

- Expected behavior
The build should work (an option to pass yarn parameters might help to mitigate this sort of issues)
- Actual behavior
The build cannot be performed.

**Comment by denis-anisimov** [comment]
`yarnNetworkConcurrency` parameter is available to configure network concurrency
