### ISSUE TITLE
Wrong context-root on push requests

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#4123]
When running in WildFly 12, push does not work and I see many 404 errors in the browser console when requesting this URL:

```
http://localhost:8080/vaadinServlet/?v-r=push&v-uiId=15&v-pushId=130210b1-368b-4c5a-9b96-85cc12a24640&X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.3.2.vaadin1-javascript&X-Atmosphere-Transport=long-polling&Content-Type=application%2Fjson%3B%20charset%3DUTF-8&X-atmo-protocol=true&_=1526399693656
```

The problem is that the app context-root is `http://localhost:8080/name-of-the-app/` so the URL requested by Vaadin is incorrect.

**Comment by Artur-** [comment]
Potential workaround would be `ui.getPushConfiguration().setPushUrl("context://vaadinServlet/");`
