### ISSUE TITLE
@Theme not found for route targets subclassed by CDI

### ISSUE THREAD

**Issue by kumm** [vaadin/flow#4140]
CDI ( maybe other DI frameworks too ) may instantiate a generated subclass of the route target even for dependent ( or pseudo scoped ) beans. This way it can handle interceptors, or decorators.
UIInternals.updateTheme use the runtime class to find a theme, but inside route registry themes are stored by classes scanned at startup. 
The result is a lost theme with 'No @Theme defined' warning for the generated class.

**Comment by pleku** [comment]
We see this mostly being an internal thing that we should fix, not blocking RC but we will fix it shortly afterwards.

**Comment by Legioth** [comment]
Fix should be relatively straightforward. Just go recursively through the parent types until encountering one that either has a theme or has `@NoTheme`, and complain only if reaching `Component.class` without finding either.

**Comment by pekam** [comment]
Hi @kumm!
This issue should be fixed with https://github.com/vaadin/flow/pull/4231. I haven't tested with CDI though, so please re-open this or create a new issue if you still have trouble with the upcoming rc2 version, which includes the fix.
