### ISSUE TITLE
IOException: Broken pipe with IntelliJ embedded Tomcat

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#4143]
When starting the [Beverage Buddy](https://github.com/vaadin/beverage-starter-flow) with Tomcat 9.0.6, BB starts properly but Tomcat prints out `IOException: Broken pipe` to the log (see this gist for a full log: [log](https://gist.github.com/mvysny/61f0bc05cbd15f1c4bd1e5ccfb80e011) ).
With Tomcat 8.5.27 the exception is slightly different: [log](https://gist.github.com/bleppard/d0521fc6027a05a4f3124a5134a77f31)

I thought this to be some integration issue for Tomcat + Flow, however weird thing is that when I try to start the [Skeleton Starter](https://github.com/vaadin/skeleton-starter-flow) using Tomcat 9.0.6, the exception does not show in the log. I thought this is because of Beverage Buddy fetching Polymer templates from the server, but the exception is also present for the [Kotlin port of Beverage Buddy](https://github.com/mvysny/beverage-buddy-vok) which does not use Polymer Templates at all.

**Comment by pleku** [comment]
Tomcat was working a while back https://github.com/vaadin/beverage-starter-flow/issues/193 (had other issues that were fixed), so seems like we have some regression.

**Comment by mvysny** [comment]
Sorry, I wasn't clear enough. BB starts and works properly. It's just that Tomcat logs abovementioned nasty exceptions.

**Comment by pleku** [comment]
Right, thanks for the clarification. Lets take a look at what exceptions about anyways

**Comment by mikotin** [comment]
Tested beverage buddy with Apache Tomcat/9.0.8 (windows) and Apache Tomcat/8.5.14 (linux) without exceptions, will test with the exact versions

**Comment by mikotin** [comment]
Versions Tomcat 9.0.6 and Tomcat 8.5.27 also tested without given exception. This might be something to do with deploy setup with IntelliJ,
@mvysny could you make sure that given project (beveragebuddy) is undeployed before it's gets deployd (by intellij) ?

**Comment by mvysny** [comment]
@mikotin you're right! When I just drop the `beverage-buddy-vok.war` into Tomcat's webapps and access `localhost:8080/beverage-buddy-vok`, no exceptions are printed out. But if I run Tomcat from Intellij, the `IOException: Broken pipe` is shown. Tested it with Tomcat 9.0.8 on Linux.

**Comment by caalador** [comment]
Closing issue as BevrageBuddy is archived and this has not been noted with other projects.
