### ISSUE TITLE
Fix javadocs warnings

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4151]
Run `mvn javadoc:javadoc -Pvalidation` (I think), and fix all the javadocs warnings in modules that are published as user facing artifacts (see vaadin-core platform dependency).

**Comment by eriklumme** [comment]
I will attempt to fix these

**Comment by pleku** [comment]
>@pleku hopefully fixed in #4222

We should add the maven checkstyle plugin to verify that, but not a priority.
