### ISSUE TITLE
Add bom for Flow project

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#4153]
A bom for Flow would simplify e.g. the build script of vaadin-spring and it would make it easier to override the version of Flow used in a project (e.g. use everything else from vaadin-bom, but use a development version of Flow).

**Comment by Artur-** [comment]
Something like https://github.com/vaadin/flow/blob/master/flow/pom.xml ?

**Comment by Legioth** [comment]
`flow/pom.xml` seems to be missing at least `flow-data`.

**Comment by mstahv** [comment]
That seems to be coming from vaadin-bom, I have no idea though what is in there, so defining flow version alone might work for my current case.

**Comment by gilberto-torrezan** [comment]
Fixed by https://github.com/vaadin/flow/pull/4667
