### ISSUE TITLE
Flow Beta12 templates broken for list of beans

### ISSUE THREAD

**Issue by oluwasayo** [vaadin/flow#4181]
When using `flow-server:1.0.0.beta12` (to be more specific, starting from [here](https://github.com/vaadin/flow/commit/97ecf87722c9a0304eb807b17e84526d6cfacef1)) with a template containing a property which is a list of beans, data binding doesn't work as expected.

Steps to reproduce:
- Clone https://github.com/oluwasayo/skeleton-starter-flow (commit [permalink](https://github.com/oluwasayo/skeleton-starter-flow/tree/da166811f924f4de3865d4f5118163ee539b2ac8))
- Run `mvn jetty:run`
- Click repeatedly on the button and observe the title change
- Observe a broken template below the title which doesn't get inflated
- Change `flow.version` in `pom.xml` to `1.0.0.beta11`
- Run again as done above 
- Observe that title and repeated template (list of 10 persons) work as expected

Expected (Beta11)
<img width="273" alt="screen shot 2018-05-28 at 10 53 42 am" src="https://user-images.githubusercontent.com/900868/40604042-6b1d2cb6-6266-11e8-87af-2a02dbcce7db.png">

Actual (Beta12)
<img width="293" alt="screen shot 2018-05-28 at 10 54 11 am" src="https://user-images.githubusercontent.com/900868/40604053-772caf04-6266-11e8-9efa-fc4a79caee69.png">

**Comment by ZheSun88** [comment]
Issue cannot be reproduced. 

with the provided code, it is using `platform` 10.0.0.beta10 and `flow-server` 1.0.0.beta12, which doesn't match with the `flow-client` 1.0.0.beta10.
