### ISSUE TITLE
UI Element doesn't fire detach event on `UIInternals::setSession(null)`

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4197]
See similar ticket : #4178 which is fixed by the #4183.
The fix just goes through all the children and fires a component detach event.

The problem is: `UI` `Element` instance doesn't fire detach event.
As a consequence children `Element`s also doesn't fire it.
The logic in `Element` (in `StateNode` actually) should fire the detach event for all descendants once the parent (`StateNode`) is detached . So it's all about the correct detach for the `UI` `Element`.

But the fix requires a test for detach event for children as well as for the `UI` element itself.

**Comment by ujoni** [comment]
Released in Flow versions:
- `1.0.13`
- `1.4.8`
- `2.0.6`
