### ISSUE TITLE
ExpireSessionIT fails or succeeds depending on the order the tests are run

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#4200]
The method `ExpireSessionView.enableSessionExpiredNotification` modifies the global state of `VaadinService`. If the test that runs `enableSessionExpiredNotification` is executed first, then the other test which expects a refresh instead of a notification will fail.

**Comment by pekam** [comment]
https://teamcity.vaadin.com/project.html?projectId=Flow&testNameId=738211818147160772&tab=testDetails

It has now passed every time after https://github.com/vaadin/flow/pull/4190 resetting the state in an `@After` method.

I'm closing this. Let's reopen if we later notice that the issue still exists after all.
