### ISSUE TITLE
Invalid URL give 500/stacktrace instead of 404 response

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#4206]
Steps to reproduce (Option 1): 

1. Navigate to `<your-server>/%3faaa`
2. Observe `InvalidArgumentException: Location '?aaa' is incorrect, it cannot start with ?symbol`

Steps to reproduce (Option2):

1. Navigate to `<your-server>/<valid-route>%3faaa`
2. Observe `InvalidArgumentException: Location string can not contain query parameters in this constructor`

Expected behaviour in both cases: 404 Not Found

Side question: what is the purpose of this in `Location.java`?

```java
            ... if (uri.getRawPath().contains("..%2F")
                    || uri.getRawPath().endsWith("%2F..")
                    || uri.getRawPath().equals("..")) {
                // the actual part that we do not support is '../' so this
                // shouldn't catch 'el..ement' nor '..element'
                throw new IllegalArgumentException(
                        "Relative path cannot contain .. segments");
            }
```

**Comment by mikkoi-vaadin** [comment]
Any plans to get this fixed? This happens a few times a week on our website so not urgent, but would be nice to have it fixed.

**Comment by fluorumlabs** [comment]
There is (Option 3) to trigger that issue: have a `router-link` with `href="?aaa"`. 

Steps to reproduce: 
1. Navigate to http://flow.app.fi/demo-static-menu-router-1.0.0/
2. Using dev.mode change any of router links to `?aaa`.
3. Click the edited link

This becomes a problem with user generated content (imagine blog post linking to https://vaadin.com/?utm_campaign=blabla&utm_source..)

**Comment by pleku** [comment]
@mikkoi-vaadin bumped priority
