### ISSUE TITLE
Modifying the DOM in an attach or detach listener might cause inconsistent results

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#4209]
When an attach listener makes modifications to the DOM, there can be situations where the attach happens twice (leading to a server-side `Can't change id once it has been assigned`) or never happens (leading to a client-side `Node -1 is already registered`). The exact result will vary depending on the relative DOM positions between the node with the attach listener and the newly attached node.

Something similar will most likely also happen detaches, or combinations where an attach listener detaches something or vice versa.

As a workaround, an attach or detach listener can defer the DOM modification using `beforeClientResponse`.

**Comment by heruan** [comment]
This happens also with other modifications than attach/detach, e.g. implementing `LocaleChangeObserver` and modifying text nodes in `onLocalChange`.

**Comment by Legioth** [comment]
> This happens also with other modifications than attach/detach, e.g. implementing `LocaleChangeObserver` and modifying text nodes in `onLocaleChange`.

This is a direct effect of the way `onLocalChange` is called from the same part of the attach handling through `ComponentUtil.onComponentAttach(Component, boolean)`.

**Comment by heruan** [comment]
Any chance to "promote" this to [**1.0.1**](https://github.com/vaadin/flow/milestone/93)? The workaround works but it quickly become tricky to bring that along all the modules.

**Comment by pleku** [comment]
Yes, once this is fixed, it ought to be backported to Flow 1.0 if there is no API or behavior change.

**Comment by heruan** [comment]
Any update on this? I can't wait to get rid of all the `beforeClientResponse` I'm using 🙂

**Comment by poczenorbert** [comment]
What is the exact workaround for this issue, please?

I got following exceptions:

`java.lang.IllegalArgumentException: Not in the list
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeChild(AbstractNodeStateProvider.java:113) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.dom.Node.removeChild(Node.java:329) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.dom.Element.removeFromParent(Element.java:565) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.dom.Node.insertChild(Node.java:246) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.dom.Node.appendChild(Node.java:141) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.data.provider.AbstractComponentDataGenerator.registerRenderedComponent(AbstractComponentDataGenerator.java:111) ~[flow-data-1.0.5.jar:na]
	at com.vaadin.flow.data.provider.ComponentDataGenerator.generateData(ComponentDataGenerator.java:80) ~[flow-data-1.0.5.jar:na]
...
at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:347) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:334) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:179) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:119) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1486) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:300) [flow-server-1.0.5.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.31.jar:8.5.31]
...`

**Comment by Legioth** [comment]
@poczenorbert Your case is at least indirectly caused by the fact that the same `MyEditForm` instance would still be attached to the closed dialog. This is still something that isn't supposed to cause problems, but the situation is apparently problematic because of this issue.

You can try working around the issue by removing the `@UIScope` annotation from `MyEditForm` or by doing something like `myDialog.remove(myEditForm)` in the close handler.

**Comment by johannest** [comment]
Another example where the issue is present and easily reproducible: https://github.com/johannest/bevbuddy-test/blob/grid-detail-issue/src/main/java/com/vaadin/starter/beveragebuddy/ui/views/categorieslist/CategoriesList.java
https://github.com/johannest/bevbuddy-test/blob/grid-detail-issue/src/main/java/com/vaadin/starter/beveragebuddy/ui/views/categorieslist/CategoryDetail.java

When having a grid detail row component as @UIScope:d or @Scope("prototype")  for example to allow @Autowired to be used inside the component

**Comment by johannest** [comment]
More information about the issue. It is reproducible also without Spring. Pushed even simplified example into the repository mentioned above. 

Steps to reproduce: Navigate to categories, open a details row for a grid row, open another details row for some other grid row, navigate to reviews.

**Comment by caalador** [comment]
Well for the buddy problem I can replicate the issue, but it would seem to be a problem in `AbstractComponentDataGenerator` as when I click open N details rows I get `registerRenderedComponent` for clicked row with the same moving component.

This is a problem as nothing ever removes the added key from the renderedComponents map and thus we get the situation that we have multiple times the same component for different keys there. 

See image
<img width="561" alt="screen shot 2018-10-18 at 14 47 38" src="https://user-images.githubusercontent.com/2726090/47152726-24696c80-d2e6-11e8-9a6f-d22d80f968e1.png">

And then we will be removing the same component multiple times leading to `Not in the list` exception in `AbstractNodeStateProvider`.

With new created components this is not an issue, but the `Grid:itemDetailsDataGenerator` map does get "polluted" with components that should probably have been thrown away.

**Comment by Legioth** [comment]
The client-side `Node -1 is already registered ` error can be reproduced in this way:
```
Span first = new Span("First");
Span middle = new Span("Middle");
Span last = new Span("Last");

middle.addAttachListener(event -> first.add(last));

add(new Div(first, middle, last));
```

The server-side `Can't change id once it has been assigned` error can be reproduced by changing the attach listener to `last.addAttachListener(event -> middle.add(first))`.

I accidentally also discovered a server-side assertion error using `middle.addAttachListener(event -> last.add(first))`. There might be other interesting permutations hiding there if someone would bother to enumerate and test them all. It's also possible that even more error conditions can be found when using a detach listener instead or in a setup where some components are attached already before attaching (or detaching) the component with the listener.

**Comment by heruan** [comment]
Any update on this? A fix would be greatly appreciated, we have many apps growing and the codebase begins to be cluttered by

```java
addAttachListener(event -> event.getUI().beforeClientResponse(this, context -> { ... }))
```

This is another case where this happens, not sure if this is related with the ones already analyzed:

```
public Foo extends Div {

    private final Tabs tabs = new Tabs();

    public Foo() {
        add(new H1("Foo"));
        // setup Tabs, but not add it
    }

    public Tabs getTabs() {
        return tabs;
    }

}

public Bar extends Div {

    public Bar() {
        var foo = new Foo();
        var tabs = foo.getTabs();
        add(tabs, foo);
        // throws IllegalStateException: Can't change id once it has been assigned
    }

}
```

**Comment by mvysny** [comment]
This also happens quite a lot when I replace Pekka's Checkbox Group with Vaadin 12 one.
