### ISSUE TITLE
Proposal: introduce the concept of a native DataProvider filter

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#4216]
When I implemented a concrete implementations of Vaadin `DataProvider` (the `JpaDataProvider`, the `EntityDataProvider` and `SqlDataProvider` data provider implementations) it became clear that those data providers can't simply accept any type of filters: for example `SqlDataProvider` can only accept filters that can be turned into valid SQL92 where clauses. Another example would be a `JPADataProvider` which can only accept JPA Criteria API classes. Neither of those data providers are for example able to accept a `String` filter (as provided by the ComboBox) since it's not clear what kind of matching is to be used, and which columns should be matched. Also, nosql data providers will introduce their own set of filters which would be quite incompatible with SQL-based data providers.

I believe it would be useful to introduce a concept of filters that are native to a particular DataProvider implementation:

* `JPADataProvider` would only accept JPA Criteria API classes;
* `SqlDataProvider` would introduce its own set of filters it accepts
* `MongodbDataProvider` would introduce its own set of filters it accepts
* `ListDataProvider` accepts a `SerializablePredicate<T>` as its filter
* An app-proprietary `RestDataProvider` using proprietary set of filters to fetch data

It would make no sense to try to convert Mongodb filters into `SqlDataProvider` and vice versa, therefore there should be no such support from the `DataProvider`.

Originally it was believed that, given a proper converter, a DataProvider could be able to use foreign filters (for example filters produced by Vaadin components - ComboBox provides search text as typed in by the user as `String`). However, it is not clear how to match `String` against a SQL table or a JPA entity. Also, the matching may tend to differ for different usage scenarios: say, one ComboBox shows entity Person while another shows entity Address and both of those entities are produced by the `JPADataProvider`.

That's why ComboBox employs call-site filter conversion: it implements (Vaadin8) `HasFilterableDataProvider.setDataProvider(DataProvider, SerializableFunction)` and requires the user to provide a proper String->F converter for every `ComboBox`.

I would therefore propose to introduce the concept of native filters into the DataProvider javadoc. This will allow us to rewrite `DataProvider.withConfigurableFilter()` to only combine filters of type F and produce a filter of type F. That would make the function way simpler to use since it will use two generic parameters instead of four. This would also make the filter conversion in `DataProvider` unnecessary.

**Comment by mvysny** [comment]
Another use-case of component-specific filters is the filter bar in a Grid. A `FilterFactory` is used, which simply produces less-than, equals, greater-than filters compatible with given DataProvider, and has the capability to `and` them. The produced filter is then set to the `DataProvider` (which must be `ConfigurableFilterDataProvider`). The `ConfigurableFilterDataProvider` would also be simplified, by dropping of the `Q` generic parameter.

**Comment by mvysny** [comment]
The main advantage of the 'native filter concept' is the simplification of the current API, and clearing out the concept of how `F` works together with `DataProvider` and what kinds of filters are accepted.

**Comment by mvysny** [comment]
Related to https://github.com/vaadin/vaadin-combo-box-flow/issues/17

**Comment by Legioth** [comment]
One aspect that seems to be missing is that there are typically two different potential "sources" of filters: components (e.g. `String` from `ComboBox`) and set from application logic through a `setFilter` method. In the end, the actual data provider implementation should only get one single instance as a typed `getFilter()` return value from the provided query instance.

One typical case where you'd need something like `ConfigurableFilterDataProvider` with two different filter types is if you have a `ComboBox` for selecting a department, and then another `ComboBox` for selecting an employee from the selected department. In that case the data provider  filter type for the employee selector is `String`, the type for the `setFilter` method is `Department` and there needs to be application-specific logic that creates a suitable JPA Criteria predicate based on those two values. This is thus a `ConfigurableFilterDataProvider<Employee, String, Department>` that wraps a "native" `DataProvider<Employee, javax.persistence.criteria.Predicate>` instance.

Another case to take into account is if the "native" filtering type of the backend is only a single "atomic" value, e.g. a Spring Data Repository method like `List<Employee> findByFirstName(String firstName, Pageable pageable)`. In that case, the filter must come from either the component or the application, but it shouldn't be valid for each side to set its own filter. The native type of such a data provider would be `DataProvider<Employee, String>`. This type could be used be used directly with a `ComboBox`, but it doesn't have a `setFilter` method.

To get an instance with a  `setFilter(String)` method, the developer can do `ConfigurableFilterDataProvider<Employee, Void, String> configurableProvider = originalProvider.withConfigurableFilter()`. The resulting type extends `DataProvider<Employee, Void>` which means that `null` is the only valid filter value from the component. The data provider would thus not usable with a `ComboBox` implementation that expect to be able to pass a `String` filter when querying for items. The type parameters for this case could be simplified with a dedicated type with the type parameters `<Employee, String>`, thus keeping the `Void` out of view. The question in that case would be how this type should be named to distinguish it from the three-parameter variant that is needed for the previous example with `<Employee, String, Department>`.

**Comment by Legioth** [comment]
If the `withConvertedFilter()` method would be dropped, it would mean that the UI logic that e.g. configures a `ComboBox` would also have to be concerned with backend technologies such as JPA. This would to some degree be against the separation of concerns that many architectures try to maintain.

By having both `DataProvider.withConvertedFilter(SerializableFunction)` and `HasFilterableDataProvider.setDataProvider(DataProvider, SerializableFunction)`, the application developer can choose in which part of the code they want to do the conversion.

**Comment by mvysny** [comment]
> If the withConvertedFilter() method would be dropped, it would mean that the UI logic that e.g. configures a ComboBox would also have to be concerned with backend technologies such as JPA. This would to some degree be against the separation of concerns that many architectures try to maintain.

I agree, let's keep `withConvertedFilter()`

>  two different potential "sources"

I see, so `ConfigurableFilterDataProvider<Employee, String, Department>` allows to set filters from two different sources: a String search filter, and a programmatic `setFilter(Department)`, probably ANDing those two. The thing is that it only supports 2 filters; if a programmer would like to further restrict the list (say for only Departments which are 'ACTIVE' - whatever that means ;) then it's hard. Possible, but hard. Also, the `withConfigurableFilter()` seem to have lost of responsibilities (both filter conversion and combining) which may be overwhelming for the programmer.

I am toying with an idea to make the API more stream-y or reactive-y: introduce methods which allow you to build a pipeline, starting from a `JPADataProvider`, adding very simple blocks as necessary. Those blocks would be responsible for one functionality only:

* A filter converter
* A filter combiner
* A fixed unremovable filter (say you want to produce a DataProvider which always limits rows based on a condition, say, only Articles from a particular Author)
* A sorter maybe, providing some sort of default sorting

Let me come up with a bunch of examples please.

**Comment by mvysny** [comment]
An example usage of the proposal, not by any means complete:

```
// creates a data provider providing all employees, by default sorted by employee name.
DataProvider<Employee, JPAFilter> allEmployees = JPADataProvider.of(Employee.class).sortedBy("name", ASC);
// always applies given filter, creating a DP which only shows 'active' employees. An unremovable filter if you will.
// we'll need a filter combiner here though; it's easy to achieve with Kotlin extension methods but not sure how to do this with Java
DataProvider<Employee, JPAFilter> onlyActiveOnes = allEmployees.withFilter(JPAFilter.eq("isActive", true));
// the JPAFilter is an abstract superclass which takes Root<?> and produces Predicate: https://github.com/mvysny/vaadin-on-kotlin/blob/master/vok-framework-jpa/src/main/kotlin/com/github/vok/framework/JPADataProvider.kt

ConfigurableDataProvider<Employee, JPAFilter> employeesFromDepartment = allEmployees.withConfigurableFilter();
// now you can set employeesFromDepartment.setFilter(JPAFilter.eq("department", dept.id));
// or, you could even do:

ConfigurableDataProvider<Employee, Department> employeesFromDepartment2 = employeesFromDepartment.withConvertedFilter(dept -> JPAFilter.eq("department", dept.id));
// and now you can set employeesFromDepartment2.setFilter(someDepartment); to filter

// going further to filter with String, the variable naming is a bit dumb. We need to call withConfigurableFilter() which forks the original DP so that setting filter to
// employeesFromDepartment2 and setting filter to employeesFromDept won't collide and won't overwrite filters.
// This is however quite hard to explain and highly error-prone. The easiest way around this is to simply have all DataProviders with configurable filter; then every chain method
// would simply produce a new DataProvider and the filters would not be overwritten.
ConfigurableDataProvider<Employee, String> stringMatchedEmployees = employeesFromDepartment.withConfigurableFilter().withConvertedFilter(searchString -> JPAFilter.ilike("name", "%" + searchString +"%"));

// done. Now we can set stringMatchedEmployees to one ComboBox, employeesFromDepartment2 to another.
```

**Comment by mvysny** [comment]
Now that we're discussing this, I guess the better title for this bug report would be "proposal: revamp the DP to have more stream-y API, and make all DPs to be ConfigurableFilterDataProviders" :)

**Comment by Legioth** [comment]
Everything in your suggestion assumes that filters _can_ be combined. This is true for `JPAFilter`, but problematic with something like a `findByFirstName(String name)` Spring Data Repository.

The current design with two different filter type parameters in `ConfigurableFilterDataProvider` is as it is exactly because the API cannot assume that filters can be combined.

One way of dealing with this is that e.g. `withFilter` is only exposed a special `CombineableFilterDataProvider` subtype. From this follows that e.g. `withConfigurableFilter()` should return something like `ConfigurableCombineableFilterDataProvider` if called on a `CombineableFilterDataProvider`, but only `ConfigurableFilterDataProvider` when called on a "regular" `DataProvider`. All other wrapper methods (e.g. `withConvertedFilter`) would at the same time also have to be overwritten to return the more flexible data provider type. I have prototyped this approach, and it turned out to be such a big mess that the current complexity with three different overloads of `withConfigurableFilter()` and two different filter type parameters feels like a stroll in the part.

**Comment by mvysny** [comment]
I see your point. It seems that the API is hitting Java limitations and can't be done in a clean and simple manner. We would need extension methods to introduce `withFilter()` for particular filter types, but that's Kotlin-only. I guess there is nothing we can do, please feel free to close as won't fix.
