### ISSUE TITLE
Spike on OSGi support

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4218]
We need to come up with initial list of features and things to do to add OSGi support for Flow.
There should be less things to do than what we did with FW8 (https://github.com/vaadin/framework/issues/8831) because we don't have similar theming, custom widgetset nor `UIProviders`... there is some discussion on what is needed in the issue https://github.com/vaadin/flow/issues/455

**Comment by QNENet** [comment]
These links might be of some value during your investigation.
https://www.youtube.com/watch?v=Up0vMRANLG4
https://github.com/njbartlett/modconf2016-workshop

**Comment by denis-anisimov** [comment]
Thanks.
