### ISSUE TITLE
DatePicker always shows error with polish locale (Firefox)

### ISSUE THREAD

**Issue by lolytxd** [vaadin/flow#4223]
Vaadin version: 10.0.0.rc1

### Description
When I choose any date from date picker or write it by myself, component always shows error on Firefox.

### Actual outcome
When I choose any date from date picker:
![image](https://user-images.githubusercontent.com/11396254/40917255-db329d46-6802-11e8-875d-29c2a16574de.png)

With date picker opened:
![image](https://user-images.githubusercontent.com/11396254/40917279-ec41a3fc-6802-11e8-9a88-627429bc863d.png)

### Steps to reproduce
For this example I used project from https://vaadin.com/start/v10-project-base

I changed MainView class like this:
```
@HtmlImport("styles/shared-styles.html")
@Route("")
public class MainView extends VerticalLayout {

	public MainView() {
		DatePicker datePickerFrom = datePicker("Date from");
		DatePicker datePickerTo = datePicker("Date to");
		add(datePickerFrom);
		add(datePickerTo);
	}

	private DatePicker datePicker(String caption) {
		DatePicker datePicker = new DatePicker(caption);
		datePicker.getElement().getStyle().set("--lumo-space-m", "0px");
		datePicker.setI18n(new DatePickerI18n().setWeek("tydzień")
				.setCalendar("kalendarz").setClear("wyczyść")
				.setToday("dziś").setCancel("anuluj").setFirstDayOfWeek(1)
				.setMonthNames(Arrays.asList("styczeń", "luty", "marzec",
						"kwiecień", "maj", "czerwiec", "lipiec", "sierpień",
						"wrzesień", "październik", "listopad", "grudzień"))
				.setWeekdays(Arrays.asList("poniedziałek", "wtorek", "środa",
						"czwartek", "piątek", "sobota", "niedziela"))
				.setWeekdaysShort(Arrays.asList("niedz", "pon", "wt", "śr", "czw", "pt",
						"son")));
		datePicker.setWidth("calc(50% - .25rem)");
		return datePicker;
	}
}
```

### Additional informations
Despite the fact, that component always show error, polish date format is DD.MM.YYYY. Example: 04.06.2018 is proper date, 4.06.2018 isn't proper date in Poland.

### Browsers Affected
- [x] Firefox 60.0.1 x64
- [x] Edge 42.17134.1.0

**Comment by ZheSun88** [comment]
This should be related to the same issue in the ticket #4224 , which you can take as an reference from the comment there.

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-date-picker-flow #90](https://github.com/vaadin/vaadin-date-picker-flow/issues/90) via [**ZenHub**](https://www.zenhub.com/)
