### ISSUE TITLE
Automatic Flow tests for OSGi

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4227]
@denis-anisimov commented on [Mon Jun 04 2018](https://github.com/vaadin/flow-and-components-documentation/issues/173)

Similar task for FW: https://github.com/vaadin/framework/issues/8594

Note that the implementation of the task in FW contains only smoke tests and also tests 
custom GWT widgetset which is not applicable for Flow.

It would be nice to run the same tests in the `flow-tests` module in OSGi container.
At least `flow-tests/test-root-context`.

But I'm not sure whether it's possible.
At least smoke tests and test which validates all OSGi specific functionality implemented in Flow should be provided.

**Comment by denis-anisimov** [comment]
We need a way to test Flow with OSGi somehow from the very beginning.
So this task needs to be done almost immediately even though we won't be able to merge it for some time because of issues in OSGi (it doesn't work currently that's the reason why we are doing it).
The branch with the way of testing should be available remotely so anyone can use it to check the current state of OSGi support.

**Comment by pleku** [comment]
Candidates for the application server are Apache Felix, Apache Karaf and Payara server (?). We can first test automatically with one server, and later add tests for other servers.

**Comment by pleku** [comment]
The framework has an IT with Karaf, found here: https://github.com/vaadin/framework/tree/master/test/servlet-containers/karaf

**Comment by QNENet** [comment]
Karaf is a customized container whereas Felix is general and applicable to a much larger audience.
Without commenting on using Karaf for IT it would be of value to use Felix as the main container for future OSGi documentation and tutorials etc..

**Comment by denis-anisimov** [comment]
At the moment we are lacking OSGi compatible artifacts at all: we don't have proper manifests for our flow jar files.
It's not possible to do anything at all for OSGi without bundles which are jar files with correct manifest declarations.
It means that this issue is blocked by the #4232.
Technically there is no immediate need to make it exactly as it's said in the ticket but since we don't have proper manifests anyway we should fix this ticket anyway firstly.

I'm going to use the same plugin as FW uses: `bnd-maven-plugin`.
There  a felix plugin `maven-bundle-plugin`  which does similar thing but its configuration is provided inline in the `pom.xml`.
Since we need individual config for many modules I would prefer to avoid the plugin duplication and have a rather separate file for the manifest instead if inlining.

**Comment by stbischof** [comment]
<bnd><![CDATA[
-exportcontents:\
 org.example.api,\
 org.example.types
-sources: true
]]></bnd>

**Comment by denis-anisimov** [comment]
There is nightly build configuration "Flow Felix Jetty OSGi Boot Integration Tests" on bender.
