### ISSUE TITLE
How to start a file download in vaadin flow without button?

### ISSUE THREAD

**Issue by onlyZohar** [vaadin/flow#4241]

**Comment by heruan** [comment]
You can use for example an [`Anchor`](https://github.com/vaadin/flow/blob/643b947fab2e2a8b559dd431e45ea7d60fb93947/flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java#L76) with a `StreamResource`, e.g.

```java
var resource = new StreamResource("picture.png", (out, session) -> /* write to out */);
new Anchor(resource, "Download!");
```

**Comment by onlyZohar** [comment]
But my file content is dynamic. One of my hopes is that when I click the button, the corresponding file stream is generated.

**Comment by ZheSun88** [comment]
This [documentation](https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/advanced/tutorial-dynamic-content.asciidoc#dynamic-content) might help you with your question. 

NOTE: **please using [vaadin/forum](https://vaadin.com/forum) for asking non-bug related questions**. This issue will be closed.
