### ISSUE TITLE
Improve scroll position ITs for IE11

### ISSUE THREAD

**Issue by pekam** [vaadin/flow#4263]
Scroll position tests in `com.vaadin.flow.uitest.ui.scroll` are quite flaky on IE11. Some tests have both passed and failed in different builds.

There might be only one pixel difference, like `expected y scroll position <337> but was <338>`. Adding some margin to the expected value would fix these cases.

There is also a case with a bigger difference: `<2221>` vs `<2003>`. 

Couple of the tests check that the scroll position is restored when navigating, but apparently IE11 doesn't do that:
```
Unexpected y scroll position
Expected: is <400>
     but: was <0>
```

**Comment by denis-anisimov** [comment]
The #4294 PR introduces a delta to fix small pixels difference.
The bigger difference should be investigated separately. It depends in the test logic: whether this is acceptable/bad test or it's a bug in the product.

The same thing is for not preserved scroll position: 0 is definitely not OK. It means that there is a bug somewhere which needs to be fixed separately.

**Comment by denis-anisimov** [comment]
To proceed with this ticket one of the following needs to be done:
- Every failing test should be written here with the exact error
- Every such test requires its own approach to fix it. So we need to detect all of them, list them and may be even have a separate ticket for each of them.
- I personally don't know how to run IE11 tests. If we have TC task for IE11 test then this info should be provided somehow. Also : is there a way to run the IE11 tests locally (I mean via maven. I understand that I may run the server and check how the UI works manually via IE11 though I don't have it and I will need to setup virtual machine for this).

**Comment by pekam** [comment]
I created this bug ticket: https://github.com/vaadin/flow/issues/4309
Closing this one.
