### ISSUE TITLE
Replace findInShadowRoot() calls with TestBench Element Queries

### ISSUE THREAD

**Issue by pekam** [vaadin/flow#4265]
Flow's own implementation in `TestBenchHelpers` for finding elements inside shadow dom does not work for polyfilled browsers, because of https://github.com/SeleniumHQ/selenium/issues/5470

With TestBench 6 queries we don't need that helper method anymore, as the queries also find elements inside shadow dom:

```
LabelElement labelInShadow = $(DivElement.class)
        .id("element-with-shadow").$(LabelElement.class)
        .id("label-in-shadow");
```
and it should avoid the issue with polyfills (need to check if it fixes some IE11 tests)

**Comment by denis-anisimov** [comment]
Splited out:

getInShadowRoot():

java/com/vaadin/flow/uitest/ui/template/RouterLinksIT.java
com/vaadin/flow/uitest/ui/template/collections/ClearListIT.java
java/com/vaadin/flow/uitest/ui/template/collections/ListBindingIT.java
com/vaadin/flow/uitest/ui/template/collections/ListInsideListBindingIT.java
com/vaadin/flow/uitest/ui/template/imports/LazyWidgetIT.java
java/com/vaadin/flow/uitest/ui/template/UpgradeElementIT.java
com/vaadin/flow/uitest/ui/template/UpdatableModelPropertiesIT.java
com/vaadin/flow/uitest/ui/template/TwoWayPolymerBindingIT.java
com/vaadin/flow/uitest/ui/template/TemplatesVisibilityIT.java
com/vaadin/flow/uitest/ui/template/TemplateInTemplateWithIdIT.java
com/vaadin/flow/uitest/ui/template/TemplateInTemplateIT.java
vaadin/flow/uitest/ui/template/TemplateHasInjectedSubTemplateIT.java
java/com/vaadin/flow/uitest/ui/template/SubPropertyModelIT.java
com/vaadin/flow/uitest/ui/template/RestoreViewWithAttachedByIdIT.java
com/vaadin/flow/uitest/ui/template/PropertiesUpdatedBeforeChangeEventsIT.java
com/vaadin/flow/uitest/ui/template/PolymerPropertyMutationInObserverIT.java
com/vaadin/flow/uitest/ui/template/PolymerPropertyChangeEventIT.java
com/vaadin/flow/uitest/ui/template/PolymerPropertiesIT.java
com/vaadin/flow/uitest/ui/template/PolymerModelPropertiesIT.java
com/vaadin/flow/uitest/ui/template/PolymerDefaultPropertyValueIT.java

findInShadowRoot():

com.vaadin.flow.uitest.ui.frontend.FrontendProtocolIT
com/vaadin/flow/uitest/ui/template/collections/TwoWayListBindingIT.java
com/vaadin/flow/uitest/ui/template/collections/ModelListIT.java
com/vaadin/flow/uitest/ui/template/collections/ListInsideListBindingIT.java
com/vaadin/flow/uitest/ui/template/collections/ListBindingIT.java
com/vaadin/flow/uitest/ui/template/collections/ClearListIT.java
com/vaadin/flow/uitest/ui/template/TemplateWithConnectedCallbacksIT.java
com/vaadin/flow/uitest/ui/template/TemplateMappingDetectorIT.java
com/vaadin/flow/uitest/ui/template/InjectScriptTagIT.java
com/vaadin/flow/uitest/ui/template/ClearNodeChildrenIT.java
com/vaadin/flow/uitest/ui/template/ChildOrderIT.java
com/vaadin/flow/uitest/ui/template/BeanInListingIT.java
com/vaadin/flow/uitest/ui/template/BasicTypeInListIT.java

Those can be taken by someone else.

**Comment by denis-anisimov** [comment]
Here is the initial part : https://reviewable.io/reviews/vaadin/flow/4299

**Comment by denis-anisimov** [comment]
I will take those for now:

java/com/vaadin/flow/uitest/ui/template/RouterLinksIT.java
com/vaadin/flow/uitest/ui/template/collections/ClearListIT.java
java/com/vaadin/flow/uitest/ui/template/collections/ListBindingIT.java
com/vaadin/flow/uitest/ui/template/collections/ListInsideListBindingIT.java
com/vaadin/flow/uitest/ui/template/imports/LazyWidgetIT.java
java/com/vaadin/flow/uitest/ui/template/UpgradeElementIT.java
com/vaadin/flow/uitest/ui/template/UpdatableModelPropertiesIT.java
com/vaadin/flow/uitest/ui/template/TwoWayPolymerBindingIT.java
com/vaadin/flow/uitest/ui/template/TemplatesVisibilityIT.java
com/vaadin/flow/uitest/ui/template/TemplateInTemplateWithIdIT.java
com/vaadin/flow/uitest/ui/template/TemplateInTemplateIT.java
vaadin/flow/uitest/ui/template/TemplateHasInjectedSubTemplateIT.java

**Comment by ZheSun88** [comment]
the FindInShadowRoot part https://github.com/vaadin/flow/pull/4300/

i will take the left from denis:

java/com/vaadin/flow/uitest/ui/template/SubPropertyModelIT.java
com/vaadin/flow/uitest/ui/template/RestoreViewWithAttachedByIdIT.java
com/vaadin/flow/uitest/ui/template/PropertiesUpdatedBeforeChangeEventsIT.java
com/vaadin/flow/uitest/ui/template/PolymerPropertyMutationInObserverIT.java
com/vaadin/flow/uitest/ui/template/PolymerPropertyChangeEventIT.java
com/vaadin/flow/uitest/ui/template/PolymerPropertiesIT.java
com/vaadin/flow/uitest/ui/template/PolymerModelPropertiesIT.java
com/vaadin/flow/uitest/ui/template/PolymerDefaultPropertyValueIT.java

**Comment by ZheSun88** [comment]
the left part are done : https://github.com/vaadin/flow/pull/4301
