### ISSUE TITLE
Enable production mode in flow-test-root-context

### ISSUE THREAD

**Issue by pekam** [vaadin/flow#4266]
We need to be able to transpile the resources to run the tests on IE11.

This is waiting for https://github.com/vaadin/flow/issues/4262

There might be issues with finding a proper `transpileEs6SourceDirectory` that works for all resources, as discussed in a comment in the Epic ticket.

**Comment by denis-anisimov** [comment]
#4282 is related to the task but I think we may workaround it via fixing #4280 and extract the module into the `frontend`  folder.
So #4280 may be considered as a part if this ticket.
