### ISSUE TITLE
Splash screen for an installed app

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4274]
When opening a Flow app from my home screen, I want it to show a splash screen to the user, so that the UX is nice and I want to keep on using the app

### Acceptance Criteria
- All V10/V11 starters from vaadin.com/start have a splash screen that shows
  - app name
  - icon
  - background colour
- It is easy to configure these parameters from server side Java code
  - this is documented with examples of using dynamic and non-dynamic approach

**Comment by Legioth** [comment]
> this is documented with examples of using dynamic and non-dynamic approach

Dynamic in what sense? Isn't the point with a splash screen that it should be shown at once without having to wait for a server round trip?

Might also consider to only rely on the functionality provided  by the platform based on data from the app manifest: https://developers.google.com/web/fundamentals/web-app-manifest/#splash-screen
