### ISSUE TITLE
Default offline view 

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4275]
When building an app with Flow, I want it to have a default offline page, so that I can easily customize it for my needs without understanding how to add it myself
- when opening the app offline, the offline page is shown
- connection drop is handled in another issue #3778

### Acceptance Criteria
- All V11 starters have a default offline view that I can start to customize myself
- The offline view is easily defined with one annotation from Java
- There is documentation on how to add the offline view

**Comment by Legioth** [comment]
> The offline view is easily defined with one annotation from Java

Where would that annotation be placed? The default cause would probably be on the application's main layout class, but what should be done if there are multiple main layout classes?

An alternative might be to always use e.g. an `offline.html` file if it's present. The benefit of this approach would be that it's definitely the same for the entire application regardless of how many main layout classes are used.
