### ISSUE TITLE
Too complex polymer template causes exception if contained in dialog and opened twice

### ISSUE THREAD

**Issue by samulivaadin** [vaadin/flow#4283]
We have a weird issue with polymer component in a dialog. If its opened twice we get exception: “Assertion error: Don’t know how to convert node without map or list features”. It is probably connected to polymer template model, because if the model interface contains just simple string field it works fine, but if there is list of any objects it starts to fail. Even List<String> as a field type causes this to happen.

This started happening after updating to RC1 and still happens with RC3

PolymerTemplate is added to Dialog in server side and shown by calling Dialog.setOpened. 

Following code snippet demonstrates model used. With only name as field everything works fine.

`public interface Model extends TemplateModel {
		//List<String> getFail();
	       //void setFail(List<String> alternatives);
		String getName();
		void setName(String name);
    }`

**Comment by onuridrisoglu** [comment]
A very similar issue we faced is: if we have a view as UIScoped SpringComponent and has a String variable in Model and its value is updated by a text-field, as can be seen in the below code snippet:
`public interface OrdersFilterModel extends TemplateModel {`
`    void setSearchKey(String searchKey);`
`    String getSearchKey();`
`}`

`<vaadin-text-field id="searchBy" value="{{searchKey}}" class="search" placeholder="Search orders" label="Search" ><iron-icon slot="prefix" icon="vaadin:search"></iron-icon></vaadin-text-field>`

The first time the view is opened, everything works fine. But when we navigate the same view the second time, the changes text field doesn't update the searchKey attribute anymore.

We also trigger a custom event after updates. We can see that java side is triggered after the event, but the value of the searchKey keeps the same.
