### ISSUE TITLE
Sending "<!-- <script>" to the client breaks the whole view

### ISSUE THREAD

**Issue by paulroemer** [vaadin/flow#4285]
Hey guys, we found a quite serious bug in Flow especially for data the user can input:

If you send "<!-- <script>" for example via template model to the client, the whole page is broken. 

To reproduce just clone the simple flow skeleton starter and apply the change below:

```diff --git a/src/main/java/com/vaadin/starter/skeleton/ExampleTemplate.java b/src/main/java/com/vaadin/starter/skeleton/ExampleTemplate.java
index eafedbc..3753118 100644
--- a/src/main/java/com/vaadin/starter/skeleton/ExampleTemplate.java
+++ b/src/main/java/com/vaadin/starter/skeleton/ExampleTemplate.java
@@ -23,7 +23,7 @@ public class ExampleTemplate extends PolymerTemplate<ExampleModel> {
 
     public ExampleTemplate() {
         // Set the initial value to the "value" property.
-        getModel().setValue("Not clicked");
+        getModel().setValue("<!-- <script>");
     }
 
     /*
```

**Comment by fluorumlabs** [comment]
Note: according to my observation, that is not limited to template model properties only. For example, this `https://bakery-flow.demo.vaadin.com/%3C!--%20%3Cscript%3E` shows the same behaviour

**Comment by fluorumlabs** [comment]
Update: that can also be used to inject malicious JavaScript

**Comment by Legioth** [comment]
Related to https://github.com/vaadin/flow/commit/5dc4ba1c200349a88ff3d1aa25f891d6d424bda3
