### ISSUE TITLE
Add Java API for <iframe>

### ISSUE THREAD

**Issue by Wnt** [vaadin/flow#4302]
Add Java API for `<iframe>` into `com.vaadin.flow.component.html`.
AFAIK currently developers would need to introduce an iframe component themselves, e.g.

```java
@Tag("iframe")
public class Iframe extends HtmlComponent
```
and write API like `setSource` themselves.

Once the API has been added, update the corresponding row in the migration table:
https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/migration/5-components.asciidoc

**Comment by youness-teimoury** [comment]
Hi!
I don't guess that might be as easy as that.

My Iframe class looks like;
`
@Tag("iframe")
public class Iframe
        extends HtmlComponent {

    public Iframe(String url) {
        getElement().setAttribute("src", url);
    }
}
`
and the iframe tag looks like this (passing url as google link)
`<iframe src="https://www.google.com/"></iframe>`

But what I get on my browser is 
`www.google.com refused to connect.`

**Comment by pleku** [comment]
Shipped in V13
