### ISSUE TITLE
Add Java API for <object>

### ISSUE THREAD

**Issue by Wnt** [vaadin/flow#4303]
Add Java API for `<object>` into `com.vaadin.flow.component.html`.
AFAIK currently developers would need to introduce an object component themselves, e.g.

```java
@Tag("object")
public class Object extends HtmlComponent
```
and write API like `setSource` themselves.

Once the API has been added, update the corresponding row in the migration table:
https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/migration/5-components.asciidoc

**Comment by Legioth** [comment]
Should be observed that `Object` might not be the best name of the class since it conflicts with `java.lang.Object`.
