### ISSUE TITLE
Add support for listening to window resize events

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#4312]
Previous Vaadin versions have included a way to listen for window resize events. Flow should also support it. 

Example use case: 
I want to swap a big grid for an overview chart for mobile users without having to have both in the DOM and hide/show them in CSS.

**Comment by mstahv** [comment]
This and especially #4320 in older Vaadin versions used to be the backbone of adapting your application to different devices. For Java developer it is pretty hard to accomplish anything thing without these features. Related blog post https://vaadin.com/blog/rwd-pj-responsive-web-design-in-plain-java

**Comment by pleku** [comment]
For reference: https://developer.mozilla.org/en-US/docs/Web/Events/resize

### Acceptance Criteria
- There is a server side API for getting the resize events with the data on the changed size
    - Since the events are fired quite often, it would make sense to not send every single one of those to the server, but instead use a delayed/lazy/debouncing setting for those.
    - For registering the listener on the server side, there is no design, so the design of that is part of this issue and should be DX tested
- There needs to be a tutorial for this, under a new section called "Browser features and events" or such 
  - move the javascript execution part under this

**Comment by pleku** [comment]
For testing, there is probably a test in the framework that verifies that the feature works.

**Comment by denis-anisimov** [comment]
>move the javascript execution part under this

Could you please clarify this? Which JS do you mean ?

**Comment by pleku** [comment]
@denis-anisimov move this tutorial also there https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/advanced/tutorial-execute-javascript.asciidoc

**Comment by denis-anisimov** [comment]
Ah, OK, thanks!
