### ISSUE TITLE
ComponentRenderer and Grid selection Bug

### ISSUE THREAD

**Issue by bisam-rd** [vaadin/flow#4313]
__Description of the bug__

We faced an issue to select a row when we use a `ComponentRenderer`.

In the following example, it's quite tricky to select a row via the second column.

```java
Grid<Person> grid = new Grid<>();
grid.setDataProvider(new ListDataProvider<Person>(persons));

grid.addColumn(person -> person.name)
     .setHeader("col 1 (works)");

grid.addColumn(new ComponentRenderer<>((person)-> new Label(person.name)))
     .setHeader("col 2 (bug)");
```

We suspect that the `ComponentRenderer` 'consume' the click event. Using the dev console of chrome, we did not observe any event sent to the backend.

Bug observed in __v10.0.0-rc5__

**Comment by mmerruko** [comment]
I took a look at this issue and this is coming from the `vaadin-grid` web component specifically you can take a look at the method `_isFocusable(target)` https://github.com/vaadin/vaadin-grid/blob/master/src/vaadin-grid-cell-click-mixin.html.

This will dispatch a `cell-activate` event on click if the clicked element is not `focusable` according to its criteria, and `label` is focusable according to the method. This is not related to the `ComponentRenderer` as such, you get the same result if you use a `TemplateRenderer` and render a full-width label. You only get selection changes when you click the edge of the column where the padding space is.

As a solution if you have more complex components that have an impact on the selection you could select the row programmatically.

**Comment by heruan** [comment]
@bisam-rd Is there a specific reason for which you are using `Label`? Note that `Label` will produce a `<label>` element for form fields; maybe `Text` or `Span` could be better choices.
