### ISSUE TITLE
Using Theming Variants for components should be easy

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4318]
`When building UIs with component APIs, I want to use a high level API for customizing the look and feel of the components that my IDE can autocomplete for me, so that I can be productive`

Currently in V10 it is required to use either the `ThemeList` mixin interface API or the Element API to access the `theme` attribute. The applicable theme variants for the components are not specified in anywhere in Java code.

### Acceptance Criteria
- For all component integrations that have either Lumo or Material theme variants
  - there must be a component level API for setting the variants
  - all applicable variants must be available somehow in Java
     - Must be autocompletable for that specific component, and preferably should make sure that the used theme has that variant (Lumo/Material)
- The documentation is updated to have examples on how to use the variants and where the variants are available (in Java)
- The component demos highlight the usage of different variants
  - Can be limited to only eg. Lumo theme, or whatever is active on that page, because the HTML examples also showcase the Lumo variants

**Comment by SomeoneToIgnore** [comment]
Variants support is added to the generator, the components have been regenerated.

What's left:
* put the generated files into each component repo
* update components that are not generated 
* update the documentation
* update the demos

Before proceeding with the task, it might make sense to wait until components with Material theme are used in generator so that all the components have variants for both themes.

**Comment by SomeoneToIgnore** [comment]
`vaadin-ordered-layout-flow` does not extend autogenerated class and does not implement `HasTheme`. 
He also has special methods for setting all three theme variants and for accessing `theme` attribute contents.

Hence, in order not to duplicate the API, no variants added.

https://github.com/vaadin/vaadin-ordered-layout-flow/pull/71/

**Comment by ZheSun88** [comment]
related APIs has been added and demos have been added to components too. 
documentation about using theme variant : https://github.com/vaadin/flow-and-components-documentation/commit/b214e4105dcfe5f5637481e18d3cad3e5f347814

ready to finish this ticket
