### ISSUE TITLE
Improve IE11 tests

### ISSUE THREAD

**Issue by pekam** [vaadin/flow#4319]
We still have a lot of failing tests in the Nightly IE11 build in bender that are currently muted. Many of the test cases probably need just some adjustment to work with IE11 and fixing those would improve our test coverage. Some tests might even reveal real bugs.

There's already at least one bug ticket about the failing tests: https://github.com/vaadin/flow/issues/4309

The test module structure is currently as follows:
- `test-root-context` is configured to run the maven plugin with transpilation when running the IE11 Nightly tests in BrowserStack, or locally with `-PproductionMode`
  - so this module should contain everything that has es6 javascript.
- `test-dev-mode` is similarly structured, but all the tests that either don't work with the maven plugin or are testing stuff that works only in dev mode, should go here
  - there are also some kinda production mode tests, which just use a servlet with the parameter `productionMode=true` but don't run the maven plugin

**Comment by pleku** [comment]
At the moment improving the IE11 regression testing is not a priority, and probably it will not be. Closed ticket.
