### ISSUE TITLE
JavaDoc deprecations mention Vaadin 7

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#4341]
https://demo.vaadin.com/javadoc/com.vaadin/vaadin-core/10.0.1/deprecated-list.html

Why are there any deprecations if Vaadin 10 is the first public release?

**Comment by Legioth** [comment]
The `As of 7.0.` deprecations are obviously from code inherited from Vaadin 7 that has been intended to be removed, but nobody has had the time to do it. Those deprecations are thus valid, but maybe slightly confusingly documented.

The two remaining deprecations are about API that was removed quite late in the beta period (or was it even between the last beta and the first rc?), so for them we chose to keep the old API there to avoid breaking things for users updating from one beta to another. Those are thus also fully valid.
