### ISSUE TITLE
Please enable CDI in Vaadin 10

### ISSUE THREAD

**Issue by doggy-dev** [vaadin/flow#4344]
I was investigating the update of our JavaEE application from vaadin 7 to vaadin 10 as I read that[ CDI is not supported yet](https://vaadin.com/docs/v10/flow/migration/7-tools-integrations.html). As I have @Inject in virtually every class in the application there is no way I can move to 10 without CDI support.

Please enable CDI support in Vaadin 10.

**Comment by denis-anisimov** [comment]
The `master` branch in the add-on repository contain V10 CDI implementation:
https://github.com/vaadin/cdi/tree/master

There is no yet any official release of the add-on but there is a snapshot which you may already use
https://oss.sonatype.org/content/repositories/vaadin-snapshots/com/vaadin/vaadin-cdi/10.0-SNAPSHOT/

**Comment by doggy-dev** [comment]
Thank you. I'll try it. 
May be you could update the page I linked that there ist a module for Vaadin 10.

**Comment by Legioth** [comment]
We should update the documentation once there is actually a non-snapshot release that contains the new integration.

**Comment by LeshaRB** [comment]
Are there examples of how to work V10 CD?
