### ISSUE TITLE
Set grid visibility with push mode long polling breaks client side

### ISSUE THREAD

**Issue by samulivaadin** [vaadin/flow#4353]
Set Grid visibility inside DataProvider.addDataProviderListener and browser will start to shove json exceptions in a continuous loop. It seems to be happening only with @Push(transport = Transport.LONG_POLLING)

Tested with Vaadin 10.0.1

**Comment by samulivaadin** [comment]
[longpollingbug.zip](https://github.com/vaadin/flow/files/2161934/longpollingbug.zip)

Sample project is based on starter project

**Comment by mlopezFC** [comment]
I hit the same problem in a different project. It seems that this is related to changing the visibility of a component to "false" and then changing a property or adding a component. I'm attaching a minimal sample project that reproduces this problem. A workaround is just to use a different mechanism to hide the component, like css style property `display:none;`
[visiblefalseproblem.zip](https://github.com/vaadin/flow/files/2163909/visiblefalseproblem.zip)
