### ISSUE TITLE
Edge loading time - extremly slow because of 100% CPU load for seconds

### ISSUE THREAD

**Issue by andreasbean** [vaadin/flow#4358]
I have created a simple flow app which takes 15 seconds to load in the Edge browser. With Google Chrome it takes less than a second.

You can easily reproduce the issue with the bakery flow demo. The CPU is at maxed out for seven seconds. This happens also on the windows phone. Please fix this issue as soon as possible.

[Bakery Flow](https://bakery-flow.demo.vaadin.com/login)

![flow-edge-load](https://user-images.githubusercontent.com/40847723/42303075-66d99f64-801f-11e8-85d4-00155fe25214.png)

**Comment by andreasbean** [comment]
Please comment this issue

**Comment by andreasbean** [comment]
any progress?

**Comment by pleku** [comment]
Sorry for lack of response, but we haven't had the time for this due to other priorities and limited resources due to summer vacations.

At the moment it looks like we will be able to investigate this further in the upcoming sprint, so hopefully we'll have some details on this in two weeks.

**Comment by mikotin** [comment]
There's an issue with using IE developer tools and especially in performance profiling.

It's known that Edge is a bit slower than chrome, 'cause of polyfill, but the IE developer tool makes the slow down extreme. So the Edge itself works well, but the profiling / developer tools makes issues to performance.

We did a test with edge with and without using profiler (result video as a gif attached)

Going through that video we can have following results (manually checked timestamps so they are not exact):

|IE Edge (without dev tools)|IE Edge with performance profiling|action|difference|
|:------:|:------:|:----:|:----:|
|2.12|13.01|total login time|~x6.1|
|0.99|3.86|total item opening time|~x3.9|
|0.11|1.07|total item closed time|~x9.7|
|3.21|9.18|total charts nav+drawing time|~x2.9|
|0.95|2.11|total users view navigated|~x2.2|
|0.95|1.88|total user opened|~x2.0|
|0.17|1.85|Total user closed|~x10.9|
|0.85|0.99|total products view|~x1.1|
|0.14|0.95|total product clicked|~x6.8|
|0.18|0.91|total product editor closed|~x5.1|
|2.00|9.11|total logged out|~x4.55|



![edge-test-gif](https://user-images.githubusercontent.com/19262966/45354819-57be2a80-b5c7-11e8-8eb1-75e5191112d7.gif)

**Comment by pleku** [comment]
I can't see what we could do at this point specifically to Edge to try to improve the performance. I'd like to get concrete performance issues that are more easier to investigate the improve on like https://github.com/vaadin/flow/issues/4532. And for Edge any performance issues should be observed without the development tools open (like end users).
