### ISSUE TITLE
ComboBox clear doesn't work

### ISSUE THREAD

**Issue by andreasbean** [vaadin/flow#4359]
I have a combobox with values (tags) which can be added to the user profile. When the user enters a text then list of possible values is filtered, which is great. After selecting a value the text of the combobox should be cleared so that the placeholder is shown again and the box is ready for the next search.
Unfortunately the `clear()` doesn't work. After calling `clear()` the box is not empty, instead the item index is inserted into the box.

```
ComboBox<String> combo = new ComboBox<>("Add tags to your profile");
combo.setItems(items);
combo.setWidth("100%");
combo.setPlaceholder("type to search");
combo.setAllowCustomValue(true);

combo.addValueChangeListener(event->{
      combo.clear();
});
```

Vaadin Flow version is 10.0.1

**Comment by gilberto-torrezan** [comment]
Issue moved to [vaadin/vaadin-combo-box-flow #105](https://github.com/vaadin/vaadin-combo-box-flow/issues/105) via [**ZenHub**](https://www.zenhub.com/)
