### ISSUE TITLE
Gradle Plugin

### ISSUE THREAD

**Issue by joelhandwell** [vaadin/flow#4389]
I tried to look use gradle for vaadin flow development and was using [devsoap/gradle-vaadin-flow](https://github.com/devsoap/gradle-vaadin-flow) created by @johndevs so far.

However I saw [a comment in maven plugin](https://github.com/vaadin/flow/blob/40a89b9998c35073db06f4a1073bb56b84835027/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/production/ProductionModeCopyStep.java#L47:78) on class ```com.vaadin.flow.plugin.production.ProductionModeCopyStep``` says following: 

> Note: this class is intended to be independent from Maven dependencies so that it can be reused in Gradle plugin in future.

In the future devsoap/gradle-vaadin-flow will be merged into this vaadin/flow repo or different gradle plugin is planed to be made?

Poking @SomeoneToIgnore 

Related with https://github.com/vaadin/flow/pull/3311

**Comment by SomeoneToIgnore** [comment]
Hi.

<a href="https://github.com/devsoap/gradle-vaadin-flow">devsoap/gradle-vaadin-flow</a> is exactly what should be used in Gradle.

Thanks for the finding, have created a PR that removes the confusing lines: https://github.com/vaadin/flow/pull/4391
