### ISSUE TITLE
HasDataGenerators interface shouldn't have a `removeDataGenerator` method.

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#4401]
@gilberto-torrezan commented on [Mon Jul 16 2018](https://github.com/vaadin/vaadin-grid-flow/issues/260)

The `addDataGenerator` method already returns a `Registration` object, that can be used to remove the `DataGenerator`. 

Having a `removeDataGenerator` is redundant.

**Comment by Legioth** [comment]
Preferably, the method should be marked as deprecated now and then removed later on.

**Comment by pleku** [comment]
Will be fixed by #7240
