### ISSUE TITLE
Couldn't find route for

### ISSUE THREAD

**Issue by LeshaRB** [vaadin/flow#4411]
I try use this example
https://github.com/christoph-frick/try-springboot-vaadin-flow

All work fine
But when I try to use instead of Groovy, Java I receive an error

```
 Could not navigate to ''

Reason: Couldn't find route for ''

Available routes:

This detailed message is only shown when running in development mode.
```

**Comment by pekam** [comment]
Hi!

Your description is about using a particular application which is not by the Vaadin team, and which you have transpiled from one JVM language to another. It doesn't provide any information about a bug or a missing feature in the Flow framework.

Please use some of our official starters to create a new Java application: https://vaadin.com/start
Those should work fine.

I'm closing this issue but feel free to provide more detailed description if you still think there is an issue in the framework.
