### ISSUE TITLE
OSGi: enable root-context tests

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4420]
#4416 as a fix for #4227 adds IT tests for OSGi.
There are a number of failing tests which are disable via category `IgnoreOSGi`.
All tests should be fixed at some point and enabled in the end.

All tests may be divided into  several categories:
- template related tests. Templates requires `polymer`  webjar. Webjars don't work because of #4413.
- push related tests. Currently they don't work because Jetty server in Felix is not properly configured for Push. Push should be configured and tests should be enabled.
- other tests which fails. The reason should be investigated. Issues should be fixed and tests should be enabled.

I will create a ticket for every category.

**Comment by mcollovati** [comment]
Compatibility mode support, that is required by OSGi add-on, is not supported anymore.
