### ISSUE TITLE
Component generator generates remove methods which remove slot attribute value

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4429]
The reason of the bug is : https://github.com/vaadin/vaadin-button-flow/issues/73

The bug is fixed but the current behavior with generated components in reality introduces a confusing behavior:
- If I use methods like `addToSuffix` from the generated component (`Button` is an example here) then it's OK to remove the `slot` attribute because it has been added by our internal code.
- If I as an app developer set the `slot`  attribute value explicitly via Element API then I don't expect any action with this attribute at all and its removal is confusing for me.

Methods like `removeAll`  or `remove` should remove `slot`  attribute only if it has been set via the component API methods and not if it has been set explicitly be the developer (quite tricky to detect that actually).

**Comment by caalador** [comment]
Closing issue as Component generator is not in use anymore and has been removed from the project.
