### ISSUE TITLE
setVisibility functionality(Vaadin 10.0.2) causes type errors in the client side 

### ISSUE THREAD

**Issue by DiegoSanzVi** [vaadin/flow#4448]
# setVisibility functionality(Vaadin 10.0.2) causes type errors in the client side 
### Description
Type errors messages appear on the browser's client screen when setVisibility is used to show and hide the pages associated with tabs.

This error only happens on Vaadin 10.0.2.  On Vaadin 10.0.1, it works perfectly.

Here, it is a link  of the original problem posted on the forum( code and images included).

https://vaadin.com/forum/thread/17186064/typeerror-exception-when-switching-between-tabs

**Comment by pekam** [comment]
This PR caused the issue: https://github.com/vaadin/flow/pull/4397

**Comment by gilberto-torrezan** [comment]
Have managed to come up with a small code that reproduces the problem:

When setting the visibility of a parent component of the Grid, the once invisible Grid doesn't have its connector loaded, and it crashes when the server sends the first commands to it. This code reproduces the bug:

```java
Grid<String> grid1 = new Grid<>();
Grid<String> grid2 = new Grid<>();

Div parent1 = new Div(grid1);
Div parent2 = new Div(grid2);

parent2.setVisible(false);

// clicking on the button crashes the client-side
add(parent1, parent2, new NativeButton("Toggle visibility", event -> {
    parent1.setVisible(!parent1.isVisible());
    parent2.setVisible(!parent2.isVisible());
}));
```
(No items are columns are needed to reproduce the bug. Also, this is not related to the Tabs component)

But this bug doesn't happen if the visibility is applied directly to the Grid (not to its parent). For example:

```java
Grid<String> grid1 = new Grid<>();
Grid<String> grid2 = new Grid<>();

grid2.setVisible(false);

// clicking on the button toggles the visibility without errors
add(grid1, grid2, new NativeButton("Toggle visibility", event -> {
    grid1.setVisible(!grid1.isVisible());
    grid2.setVisible(!grid2.isVisible());
}));
```
