### ISSUE TITLE
Router-Link for embedded Elements

### ISSUE THREAD

**Issue by Firestorm87** [vaadin/flow#4449]
Actually Router-Links could only be created with Strings (text) as subelement on Java-Side.
public RouterLink(String text, Class<? extends Component> navigationTarget)
results in
`<a href="https://www.w3schools.com">w3schools</a>`

I would like to have an API to embed other elements like images.
`<a href="https://www.w3schools.com">
     <img border="0" alt="W3Schools" src="logo_w3s.gif" width="100" height="100">
</a>`

**Comment by Legioth** [comment]
`RouterLink` implements the `HasComponents` mixin interface which includes an `add(Component... components)` method that can be used for adding non-text content. We haven't added any shorthand constructor for this case based on the assumption that it's a relatively uncommon case.

You would instead have to use one of the existing constructors that require a `text` String and then optionally use `removeAll()` to remove the text. The code would thus be something like this:
```
RouterLink myLink = new RouterLink("", TargetView.class);
myLink.removeAll();
myLink.add(myImage);
```
