### ISSUE TITLE
setDateStyle is missing on DateField and AbstractDateField

### ISSUE THREAD

**Issue by invader35** [vaadin/flow#4451]
The method for setting the style of a single date is missing in Vaadin 10.0.2 but was present in the DateField implementation of Vaadin 8.5.0.

We used it to indicate if there is data available for a date to allow the user faster fitlering with the date field.

**Comment by pekam** [comment]
Issue moved to [vaadin/vaadin-date-picker-flow #120](https://github.com/vaadin/vaadin-date-picker-flow/issues/120) via [**ZenHub**](https://www.zenhub.com/)

**Comment by pekam** [comment]
Hi and thanks for the issue!

This repository contains only the core Flow framework, and all the components have their own repositories. That's why I moved this issue to the `vaadin-date-picker-flow` component repo.
