### ISSUE TITLE
CSRF request not going through specified mapping

### ISSUE THREAD

**Issue by maciej-plonka** [vaadin/flow#4464]
With specified, in application.properties, url mapping for vaadin it still sends CSRF request mapped at "/" instead of "/admin".
application.properties:
```
vaadin.servlet.urlMapping=/admin
vaadin.servlet.resources=/admin
```

Current fix in Spring @Controller:
```Java
@PostMapping("/")
    public String forwardVaadinCSRF(@RequestParam("v-uiId") String v1, @RequestParam("v-r") String v2){
        return "forward:/admin?v-uiId=" + v1 + "&v-r=" + v2;
    }
```

**Comment by mcollovati** [comment]
The current Vaadin spring implementation correctly handles configured URL mapping.
The configuration nowadays is `vaadin.url-mapping`, for example `vaadin.url-mapping=/admin/*`

To be noted that the mapping should end with an `/*`
