### ISSUE TITLE
Component analyzer produces wrong json file when the `parentClassData ` is undefined

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#4477]
This issue occurs when generates code for `vaadin-time-picker`:

If `vaadin-time-picker` is the only dependency in the bower.json, the `parentClassData` of sub-element `vaadin-time-picker-text-field` is undefined. This causes the wrong analysis. the produced the json file contains the content for actual parent `vaadin-text-field`. 

at the end, the produced the java file has wrong extension from `AbstractSinglePropertyField` instead of `GeneratedVaadinTextField`.

**Comment by caalador** [comment]
Closing issue as the generator is not used anymore nor is it a part of the project.
