### ISSUE TITLE
Component generator generates code with wrong extension and without import 

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#4479]
This issue occurs when generates code for `vaadin-time-picker` 1.0.0.beta1, This issue should follow the 
https://github.com/vaadin/flow/issues/4477
there is a sub-element `vaadin-time-picker-text-field`, when generating the code, the file has compilation error, because the signature of the file is 
```
public abstract class GeneratedVaadinTimePickerTextField<R extends GeneratedVaadinTimePickerTextField<R>>
        extends GeneratedVaadinTextField<R> implements HasStyle {
```
which is wrong, as the parent should take two parameters like `GeneratedVaadinTextField<R, T>`

one extra: there is no import for the textfield.

that is a special case for now, because the `time-picker-text-field`  https://github.com/vaadin/vaadin-time-picker/blob/master/src/vaadin-time-picker-text-field.html#L7 has a link import for other vaadin-elements

**Comment by caalador** [comment]
Closing issue as the generator is not used anymore nor is it a part of the project.
