### ISSUE TITLE
Element.callFunction does not allow call of element's functions with client side parameters

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4480]
I have the following JS call that I want to execute on client side for an server side element:
```
Page page = getUI().get().getPage();
page.executeJavaScript("$0.addEventListener('dragover', e => e.preventDefault())", component);
```

This works without problems, but has the disadvantage, that I need to call it either in `onAttach` or via `getElement().getNode().runWithAttached()`. 

To use a simpler out of the box API I want to use the built in method `Element.callFunction` to add my client side event listener. This is not possible, since otherwise than in `Page.executeJavaScript` I am only allowed to present a function name (instead of a function call). When I want to pass in client side parameters like my event handler lambda, Flow throws an error. 

My request is, that the method `callMethod` should be a convenience wrapper of the Page.exectureWrapper that allows the definition of the parameters by the developer:

```
component.getElement().callFunction("addEventListener('dragover', e => e.preventDefault())");
```

**Comment by Legioth** [comment]
How can the implementation of `callFunction` know whether the first parameter is the name of a function or a JS snippet to evaluate?
How would additional parameters (i.e. the current ` Serializable... arguments`) be interpreted when the parameter list is already provided inline in the string?

**Comment by stefanuebe** [comment]
I would assume this issue as outdated, the above requested code can easily be done via Element.executeJs, which automatically takes care of wrapping the call into runWhenAttached and allows the definition of client side parameters together with the usage of passed server side elements ($0, $1, etc).
