### ISSUE TITLE
OSGi: none of our component is OSGi compatible

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4491]
Technically this issue should be created for every our flow component (like `vaadin-flow-button`).

Non of our component is currently OSGi compatible.
In reality they won't work anyway since their webjar dependency is not OSGi compatible (see a separate issue) but we still need jar files with server side Java code being OSGi bundles.

So we should generate manifest for every component and include it into the Jar file so it becomes a bundle.

I think we should make a common config for this in `flow-base-component` module which is a parent for every component.
Similar thing is already done for Flow via `bnd-maven-plugin` .
So it can be copied from there.
Component just need to have its `bnd.bnd` file in the repo.

**Comment by pleku** [comment]
Superseded by #4630
