### ISSUE TITLE
TextRenderer always renders content using components

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#4503]
`TextRenderer` doesn't implement `BasicRenderer`, which means that the content will always be rendered as a component (i.e. using `<flow-component-renderer>`) instead of a much more efficient template approach.

`TextRenderer` is mostly redundant since e.g. `Grid` and `IronList` have shorthand APIs for defining a `T -> String` callback that is rendered using a regular template, but there is still the chance that someone by accident uses it instead of the template based shorthand. This situation would cause unexpected overhead and even some bugs in cases such as https://github.com/vaadin/vaadin-iron-list-flow/issues/54.

**Comment by denis-anisimov** [comment]
So what is the expected resolution ?
Should `TextRenderer` be removed completely ?
Or its implementation should be changed?
Or something else ?

**Comment by Legioth** [comment]
If `TextRenderer` serves no purpose, then it can be removed. Otherwise, I would expect it to be modified to work in a more efficient way (which I assume would mean changing it into a `BasicRenderer` so that template-based rendering would be used when appropriate).

**Comment by caalador** [comment]
The TextRenderer is in the flow-components repository now and it extends BasicRenderer now. Closing issue.
