### ISSUE TITLE
Dialog does not reveice key events.

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4518]
I want to implement a simple confirm dialog with a primary button, that is clicked, when the user press the enter key. For that I extended the class Dialog, implement KeyNotifier and add a listener for the key down event. 

The listener is never called. 

I tried the same with `getElement().addEventListener("keydown", ...)`, same result, nothing happens. 

The following code is somehow a workaround for the dialog.
```
public class DialogImpl extends Dialog {
    private void init() {
        // ...
        getElement().getNode().runWhenAttached(ui -> {
		DomListenerRegistration keydown = ui.getElement().addEventListener("keydown", event -> finalSelectedPrimaryButton.click());
		addDetachListener(event -> {
			keydown.remove();
		});
	});
    }
}
```

Nevertheless, it should work somehow easier to react with a dialog on key events.

**Comment by Legioth** [comment]
The problem is that the contents of the dialog will not be a child of the actual dialog element in the DOM. This is done because of the way the `<vaadin-dialog>` web component is intended to be used inside some other web component (i.e. when not using Flow), while still avoiding that e.g. `overflow: hidden` on the outer web component would cause the dialog itself to be cut off. I don't know if there's anything that we can actually do about this.

**Comment by Legioth** [comment]
One potential workaround might be to register the listener globally (i.e. for the `UI`)  instead of only in the scope of the dialog component. In that case, you should also remember to add logic that unregisters the listener once the dialog is closed.

**Comment by Springrbua** [comment]
@Legioth thanks for the information, it seems to work.

My code:
`ComponentUtil.addListener(UI.getCurrent(), KeyDownEvent.class, event -> System.out.println("KeyDown"))`

This returns a `Registration`, which needs to be `remove`d in `onDetach`

**Comment by bogdanudrescu** [comment]
Does `Shortcuts` work for this? I also don't see any `Shortcuts` UI test covering `Dialog`.

**Comment by pleku** [comment]
Since Vaadin 14.5 this is fixed for `Shortcuts` when they target a `Dialog` component.
