### ISSUE TITLE
Opening editor takes 7 seconds

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4532]
@marcushellberg commented on [Fri Aug 10 2018](https://github.com/vaadin/beverage-starter-flow/issues/233)

Opening the editor window for the first time takes an unreasonably long time. It gives a bad impression of Vaadin in my opinion. 

Of the 7 seconds, 5 are spent on the server. See attached screenshot and chrome perf recording.

<img width="466" alt="screen shot 2018-08-10 at 9 52 18 am" src="https://user-images.githubusercontent.com/883698/43965360-a4321342-9c84-11e8-85df-4630e7cb3cef.png">

https://transfer.sh/3jOrC/bb-open-editor.json

---

**The issue has been originally created in beverage repo. But this is a generic performance issue with `com.vaadin.flow.component.internal.ComponentMetaData.findDependencies` method execution (see comments from Leif below). So this needs design and a proper solution since at the moment there is no obvious way how to solve it. We are doing everything possible at the moment: cache the result but it's necessary to run it a least one time.**

---

@denis-anisimov commented on [Sat Aug 11 2018](https://github.com/vaadin/beverage-starter-flow/issues/233#issuecomment-412253658)

Steps to reproduce?

Does it happen with an empty dialog and just calling it `open` method ?

---

@marcushellberg commented on [Sun Aug 12 2018](https://github.com/vaadin/beverage-starter-flow/issues/233#issuecomment-412313682)

1. Download latest starter from vaadin.com/start
2. Run app
3. Click edit on any beverage

---

@denis-anisimov commented on [Sun Aug 12 2018](https://github.com/vaadin/beverage-starter-flow/issues/233#issuecomment-412322529)

OK, thanks.

---

@denis-anisimov commented on [Wed Aug 15 2018](https://github.com/vaadin/beverage-starter-flow/issues/233#issuecomment-413164057)

True, the very first time the dialog loading takes very long time.
Every subsequent call of any other dialog works well.

---

@denis-anisimov commented on [Wed Aug 15 2018](https://github.com/vaadin/beverage-starter-flow/issues/233#issuecomment-413168976)

There is no any explicit performance issues on the server side when the dialog is requested being opened.
All server side logic is executed right away.
The problem is the dialog content: it has many components which have not been loaded anyhow previously.
Here is the attached image of the resources that are loaded on dialog load request:

<img width="825" alt="screen shot 2018-08-15 at 2 16 22 pm" src="https://user-images.githubusercontent.com/11425472/44145943-1a181c18-a096-11e8-8ce9-0121b97afcb3.png">

So I guess the reason of the behavior: is the first time loading a bunch of remote resources from webjars.
That's why it doesn't happen any subsequent time.

I don't see what we can do in general here.
May be something in this specific case preload some components which are expected to be used anyway because most likely a user will open some dialog...

---

@Legioth commented on [Wed Aug 15 2018](https://github.com/vaadin/beverage-starter-flow/issues/233#issuecomment-413191767)

The time it takes to load the HTML imports isn't the main problem. There's a significant time spent in the UIDL request: 2.10s now when I tested it. After a couple of repetitions to let the JVM and any of Flow's own caches to warm up, the server-side time goes down to around 100ms on my machine. This  is still quite much compared to the initial view which takes around 50ms of server-side time for both generating UIDL and producing the HTML page.

![screen shot 2018-08-15 at 16 06 43](https://user-images.githubusercontent.com/1294657/44149556-3b7d62e6-a0a5-11e8-9757-578d250aa73a.png)

---

@Legioth commented on [Wed Aug 15 2018](https://github.com/vaadin/beverage-starter-flow/issues/233#issuecomment-413196374)

According to JProfiler, most of the time is spent in `com.vaadin.flow.component.internal.ComponentMetaData.findDependencies`. The result of this is cached so it only happens the first time the code is run after the application has been started.

Out of the time spent in that method, about 60% is spent in `javax.servlet.ServletContext.getResourceAsStream`, which basically does IO to read and unzip files from inside various webjars.

---

@denis-anisimov commented on [Wed Aug 15 2018](https://github.com/vaadin/beverage-starter-flow/issues/233#issuecomment-413199905)

Well, I was able to reduce the opening time via just adding lazy pre-load of the components.

`findDependencies` is more tricky since it's needed to be called and this is the server-side time during the request.
The only way how it may be reduced is creating a background thread which collects dependencies and put them into the cache before the dialog is even opened....

---

@Legioth commented on [Wed Aug 15 2018](https://github.com/vaadin/beverage-starter-flow/issues/233#issuecomment-413201275)

One approach for `findDependencies` might be to whitelist dependencies that we know might be encountered, but that are not necessary to parse through since we know that nothing of interest will be found through them.

---

@Legioth commented on [Wed Aug 15 2018](https://github.com/vaadin/beverage-starter-flow/issues/233#issuecomment-413201637)

To make things even more advanced, we could even automatically precompute the dependencies for each of our components and include a manifest in the .jar file.

---

@marcushellberg commented on [Wed Aug 15 2018](https://github.com/vaadin/beverage-starter-flow/issues/233#issuecomment-413212902)

@denis-anisimov's solution is OK in the context of this demo. But ideally, we would come up with a solution where a developer doesn't accidentally introduce this kind of slowness into their app by just using our APIs as documented. 

---

@denis-anisimov commented on [Wed Aug 15 2018](https://github.com/vaadin/beverage-starter-flow/issues/233#issuecomment-413267486)

True, true.

But there are real reasons behind that behavior.
So it requires a serious design in Flow to avoid such issues.

**Comment by denis-anisimov** [comment]
I've moved this ticket into Flow repo since it's a generic performance issue which needs to be solved generically.

**Comment by Legioth** [comment]
It seems that the main contributor to the delay is parsing through lots of WebJars in order to find a full HTML import dependency graph for all components in the view. This in turn is only needed in order to detect HTML imports that might need to be subjected to a rewrite by the currently used theme. This inspection is only needed for components that use our `ThemableMixin`, or for the application's own templates that directly or indirectly import such components.

In practice, there are two problems:
1. We're spending lots of time parsing files that we can up-front know that they won't contain anything related to theming, e.g. `frontend://bower_components/polymer/polymer-element.html`
2. The same transitive dependencies are parsed multiple times. E.g. `frontend://bower_components/polymer/polymer-element.html` is parsed 7 times when opening the edit dialog in Beverage Buddy.

**Comment by denis-anisimov** [comment]
There was a logic which prevents parsing the same file during dependency traversal.
But it was buggy and has been removed.

`polymer-element.html` can be hardcoded so that it's never parsed.
About other files: you never can say whether it contains a theme or not.

Theme doesn't have to be made by us. It can be custom theme with any convention used for naming.
So I don't see how we can make a proper blacklist .

**Comment by Legioth** [comment]
Filtering out anything that starts with `frontend://bower_components/polymer/` would already eliminate around 80% of all files that are currently parsed.

**Comment by denis-anisimov** [comment]
That's my point.

**Comment by Legioth** [comment]
We can be really sure that `frontend://bower_components/polymer/` won't contain anything that would be related to themes. Only blacklisting that one and nothing else would by itself improve performance by 80%.

If there are still performance problems after fixing the caching and blacklisting `frontend://bower_components/polymer/`, then we might evaluate whether we could somehow also blacklist (or precompute) more stuff, but until that, I don't think any more blacklisting would be necessary.

**Comment by denis-anisimov** [comment]
Agreed.
OK, let's start with that and exclude everything inside `frontend://bower_components/polymer/`

**Comment by mstahv** [comment]
Just saw this issue in an app that I have been trying to upgrade to V10. Also this is an issue in our "skeleton starters" starters, now that I just changed them to use Notification 😊

**Comment by pleku** [comment]
With the current fixes done for this I consider this issue to be fixed as the performance has been improved significantly enough. Most of the fixes have been backported to V10 and released. Remaining ones are included in Vaadin 12.
