### ISSUE TITLE
CDI support and test

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#456]

**Comment by pleku** [comment]
Will be included in V11, the add-on code will be in https://github.com/vaadin/cdi

**Comment by pleku** [comment]
Can be used in V10+, see https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/cdi/tutorial-cdi-basic.asciidoc for instructions or grab the CDI starter from https://vaadin.com/start

Tutorial will go live closer to V12.
