### ISSUE TITLE
VaadinSession setErrorHandler crash/block view/UI

### ISSUE THREAD

**Issue by claspina** [vaadin/flow#4560]
I wrote my own custom error handler for the UI in Vaadin flow. But when I throw the exception my view crash and not show my human readable error message.

I did this in other application using Vaadin 8 and works perfectly. The idea its throw a AppException in my backend services like:

- Product not found
- Incorrect value for field "XXX"
- Not available stock for the product.
- etc.

And then **show a system notification**

            public static void setDefaultErrorHandler(ErrorEvent errorEvent) {

                Throwable t = DefaultErrorHandler.findRelevantThrowable(errorEvent.getThrowable());

                String message;
                if (t != null) {
                    message = t.getMessage();
                } else {
                    message = "";
                }

                log.error(message, t);

                AppException appException = getCauseOfType(t, AppException.class);
                if (appException != null) {
                    NotificationBuilder.exception(appException.getCode(), appException.getMessage());
                    return;
                } else {
                    NotificationBuilder.exception(UNKNOW_ERROR, (message == null ? "" : message));
                    return;
                }
            }

            private static <T extends Throwable> T getCauseOfType(Throwable th, Class<T> type) {
                while (th != null) {
                    if (type.isAssignableFrom(th.getClass())) {
                        return (T) th;
                    } else {
                        th = th.getCause();
                    }
                }
                return null;
            }

And this is how I set the custom error handler:

            @PostConstruct
            public void configBaseView() {
                VaadinSession.getCurrent().setErrorHandler(Util::setDefaultErrorHandler);
            }

In the view show this:

[![enter image description here][1]][1]

> **Note:** 
Debugging the application, seeing the code it's running, looks the method its called for some reason not show the notification.

  [1]: https://i.stack.imgur.com/WgS4b.png

**Comment by Artur-** [comment]
Possibly the same as #801 and resolved by #4529
