### ISSUE TITLE
Add API for getting the current view

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow#4565]
Currently, in order to get the active view path, you will need to go through `UI.getCurrent().getInternals().getActiveViewLocation()`. I don't feel comfortable relying on the UIInternals `which are intended for internal use`, so there should be a public method in UI to get this information instead. This way, if the internal implementation changes, the UI class just needs to keep up and the change will be transparent to the consumers.

**Comment by mstahv** [comment]
@OlliTietavainenVaadin, question, if you happen to remember the details, did you mean with view here "Location" (returned by UI.getCurrent().getInternals().getActiveViewLocation()), or the actual view object (or class)? 

I don't remember that I would have needed the "Location"/url, but I remember I have couple of times tried to find out a way to get the active view in a parent layout that implements some sort of menu or breadcrumbs.

**Comment by OlliTietavainenVaadin** [comment]
Yes, it's the view object. You can retrieve the rest based on it.

**Comment by mvysny** [comment]
At the moment I have the following code to obtain the current view class. It looks really tricky, so there definitely should be a better way to do it - e.g. make `AfterNavigationEvent.getActiveChain()` available from `UIInternals` or UI directly.

```kotlin
public val currentPath: String? get() =
    UI.getCurrent()?.internals?.activeViewLocation?.pathWithQueryParameters

/**
 * Returns the current view
 */
public val currentView: Class<out Component>? get() {
    var path: String = (currentPath ?: return null).trim('/')
    // remove any query parameters
    path = path.substringBefore('?')
    val registry: RouteRegistry = UI.getCurrent().internals.router.registry
    val segments: List<String> = path.split('/')
    for (prefix: Int in segments.size downTo 1) {
        val p: String = segments.subList(0, prefix).joinToString("/")
        val s: List<String> = segments.subList(prefix, segments.size)
        val clazz: Class<out Component>? = registry.getNavigationTarget(p, s).orElse(null)
        if (clazz != null) {
            return clazz
        }
    }
    return null
}
```

**Comment by mstahv** [comment]
Wrote a prototype that basically just takes the element 0 from "the active chain" if available. Would this suit for your cases? : 

    UI.getCurrent().getCurrentRoute().ifPresent(route -> {
        Notification.show("Current route class " + route.getClass());
    });

BTW. The "active chain" has no documentation at all so I had to inspect that in which order with debugger 😊

**Comment by mvysny** [comment]
Thank you @mstahv that would be awesome! Damn I completely overlooked UIInternals - thanks for the great tip! This code also does the trick: `UI.getCurrent().getInternals().getActiveRouterTargetsChain().get(0).getClass()`

**Comment by mstahv** [comment]
Pushed the solution to a draft PR and modified some existing unit tests to cover it.

The lingo we have been using on this area is quite messed up so I'm not convinced the proposed method name is to best one. Dropping some alternatives for discussion:

```
getCurrentRoute(); // currently in PR
getActiveRoute();
getCurrentRouterTarget();
getActiveRouterTarget();
getCurrentRouteTarget();
getActiveRouteTarget();
getCurrentView();
getActiveView();
```

They all see bad somehow, but I guess all of them would still be easier to discover than the proposed workarounds.

**Comment by Artur-** [comment]
The pattern `getCurrent` is what is used for getting the current servlet, service, UI, session etc. In some cases where it is not possible to add `getCurrent` to the proper class, the pattern `getCurrentNaNa` is used. So the most logical would be `Route.getCurrent()` but that does not work. `Router.getCurrentRoute()` could work. `UI` is most often not the best place to put new API and chaining `getCurrent` methods should never be necessary

**Comment by mstahv** [comment]
`Router.getCurrentRoute()` looks very good on paper and it crossed my mind, but I ditched the idea as Router is practically internal API that Vaadin developers never (?) use directly.

UI on the other hand is used for programmatic navigation between views, so I find that to be the most natural place, even though I know there has been wishes to get rid of that concept altogether since V10/flow (not seeing that it would actually happen).

From my yesterdays list of potential other names, `getActiveNavigationTarget` was missing. "navigation target" has been existing in our lingo already and it would be symmetrical with navigate methods that are commonly used via UI. I'll update my list and mark that as the primary candidate.

**Comment by samie** [comment]
`Route.getCurrent()` sounds identical to `UI.getCurrent()`, but also like to advocate API symmetry for read and write. In this case that would be mean `UI.setCurrentRoute` (i.e. `UI.navigate` and all the variants) and `UI.getCurrentRoute`... also worth considering is it enough to have: `UI.getRoute` and `UI.setRoute`?

**Comment by mstahv** [comment]
UI.setCurrentRoute kind of exists in UI already (`UI.navigate(...)`). I see why `setCurrentRoute` or similar hasn't been used there as there is a high chance that setting finally doesn't happen. Maybe the verb in the new method should not be get, but e.g. `UI.findCurrentRoute` (or any any of the many alternatives like View/NavigationTarget/whatever) 🤔

**Comment by mstahv** [comment]
Returning Optional would also be more natural with `find`.

**Comment by mstahv** [comment]
Maybe current/active is not needed either if using find verb instead of get. Updated the list of candidates above (and my new favourite).

**Comment by samie** [comment]
Do we have any real life application code where this would be used? I'm thinking something like "checking if we are on the right view" in our shared UI logic as well as navigating to different views based on current view and some state (e.g. logged in).

**Comment by mstahv** [comment]
I don't have those at least because the method has not been available and I have had to implement bizarre workarounds (maintaining view stack myself). You can do that yourself easily if you implement after navigation listeners that highlights active menu item (in some menu that you implement yourself) or for example updates some header text in parent layout based on the current view.

**Comment by mstahv** [comment]
@mvysny probably can send you some other use cases.

**Comment by mstahv** [comment]
We discussed the naming with a small team of community during todays Discord "office hour". Ended up with getCurrentView after all (now changed in the PR). View sounds more natural than "navigation target", get is something that people might use to filter/sort autocompletion in IDE and current more natural than active. Also, we should trust the intuition and the only place where it was not spoiled was by @OlliTietavainenVaadin when creating this issue 😎

**Comment by mstahv** [comment]
I'm up for good other suggestions (with valid arguments), but turning the draft PR into actual one now.

**Comment by mstahv** [comment]
BTW. Slightly related, maybe we should change the parameter names in UI.navigate methods form navigationTarget -> view 🤔 There is still kind of an argument for that naming though as the parameter is the class and it only becomes the view when framework creates an instance of that. All so complex...

**Comment by knoobie** [comment]
I would be interested in the current view for e.g. my support overlay to know from where it was opened. At the moment my overlay button implements navigation observer and stores the currently active view / route. 

I'm fine with any name, but please don't use optional 😅

**Comment by mstahv** [comment]
Finally @knoobie, I was waiting for your insightful comments :-) I wouldn't like the optional either, but I'm done fighting about that. Maybe I'll add a comment for a flow team that would love to drop it if allowed 🤓
