### ISSUE TITLE
Allow nested layouts and routes using only @Route

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#4566]
I would like to achieve this routing using `@Route`

![screen shot 2018-08-30 at 9 56 02](https://user-images.githubusercontent.com/29859656/44834846-f4cdaa80-ac3a-11e8-84b8-8610c65f4110.png)

The ideal case would be
```
@Route(layout = Root.class)
public class Foo implements RouterLayout {
```
and
```
@Route(layout = Foo.class, relative = true)
public class Bar {
```

In reality, it requires hardcoded URLs, and for Foo to also declare `@ParentLayout`.
Without `@ParentLayout(Root.class)`, it does not show correctly when navigating to `Bar`.
Without `@Route(layout=Root.class` it does not show correctly when navigating to `Foo`.

**Comment by pleku** [comment]
I'm closing this as it is partly done - you can configure the layout in the `@Route` annotation and in case you don't want to hardcode URLs - you can add the views dynamically. In case there is something additional needed, anyone can create a new issue and describe the use case there.
