### ISSUE TITLE
Potential security vulnerability warning in flow-webcomponent-api-analyzer/package-lock.json

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#4572]
`lodash` version in https://github.com/vaadin/flow/blob/master/flow-components-parent/flow-webcomponent-api-analyzer/package-lock.json should be upgraded.

**Comment by Legioth** [comment]
The dependency in question is only used by the API analyzer that is used internally to create generated baseline classes for the components' Java APIs. The dependency is not directly used by applications.
