### ISSUE TITLE
Add Multi Select capabilities to binder

### ISSUE THREAD

**Issue by vwiencek** [vaadin/flow#4581]
I think it would be interesting to have add a `List` or `Set` binding to `BeanValidationBinder` objects.

The use case is the following
```java
@Entity 
public class User {
      @ManyToMany
      private Set<Role> roles

      /** rest of the class**/

}
```

then in a view

```java
public class MyView extends Div {
      MultiSelect<Role> myMultiSelectCombo = ...

}
```

We should be able to have 

```java
binder.bind(myMultiSelectCombo, "roles")
```

or

 ```java
binder.forField(myMultiSelectCombo).bind(...)
```

And all benefits from binder (hasChanges, read, write ...) enabled on Collections

**Comment by heruan** [comment]
Isn't this already supported? I'm doing this right now:

```java
var multi = grid.asMultiSelect();
binder.forField(multi).bind(User::getRoles, User::setRoles);
```

**Comment by vwiencek** [comment]
oh my god
Thanks. I was in the dark, now I see

**Comment by Legioth** [comment]
This is indeed already supported, and it's not even through any feature in Binder, but rather because components with multi select functionality have a value type of `Set<T>`. See https://stackoverflow.com/a/52000500/2376954 for a more detailed explanation.
