### ISSUE TITLE
Determine how to re-enable Brotli compression

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#4583]
#4556 was reverted because it interfered with the built-in on-the-fly compression in Tomcat 8.x which still applies gzip compression to the response, thus making it double compressed even though the response header implies that it's only gzipped.

Compression is not enabled by default in Tomcat, but for instance Bakery has `server.compression.enabled=true` in `application.properties` which enables the feature. The same setting works fine with the embedded Jetty and Undertow servers since their built-in compression features properly handle the case.

We could make serving of precompressed Brotli files configurable, but then we'd also have to decide which way should be the default, or alternatively make the default setting vary depending on whether Tomcat 8.x is detected from the classpath.

**Comment by knoobie** [comment]
Is that related to Tomcat 8.x or Tomcat 9.x as well?

**Comment by Legioth** [comment]
Detecting Tomcat 8.x is easy:`servletContext.getServerInfo().startsWith("Apache Tomcat 8.");`.

Figuring out the compression settings is a little bit tricky. It seems like one working approach would be to query for MBeans with the name `Tomcat:type=ProtocolHandler,port=*` and then check the `compression` attribute value for each of them to look for the value `"on"` or `"force"`.

**Comment by Legioth** [comment]
@knoobie Based on reading the code, Tomcat 9.x is fine, but I haven't yet tested that in practice.

**Comment by Legioth** [comment]
I've crated a new PR that requires explicit opt-in to use precompressed Brotli files in https://github.com/vaadin/flow/pull/4739. I've created https://github.com/vaadin/flow/issues/4740 for making it used by default.
