### ISSUE TITLE
11.0.0 Tabs Broken

### ISSUE THREAD

**Issue by martinisraelsen** [vaadin/flow#4586]
In 11.0.0.beta3 and 11.0.0 final release polymer tabs no longer sends an event when tabs are changed and the text "Tab changed" is never displayed.

```
  tabs.addSelectedChangeListener(e -> {
         System.out.println("Tab changed");
      });
```

Seems that it could be a regression of https://github.com/vaadin/flow/issues/4564#issuecomment-418973980

Attached is html and java zipped.

[brokentabs.zip](https://github.com/vaadin/flow/files/2357240/brokentabs.zip)

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-tabs-flow #75](https://github.com/vaadin/vaadin-tabs-flow/issues/75) via [**ZenHub**](https://www.zenhub.com/)
