### ISSUE TITLE
Grid multi select() method should be available with Iterable parameter

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4588]
Currently the `select` method of the interface `MultiSelect` only provides a varargs parameter. When the dev wants to select all items of the grid, the following code is necessary to obtain that:

```
public abstract class SelectWindow<BEAN extends Serializable> {
    Collection<BEAN> items;
    //...
    private void foo() {
        grid.asMultiSelect().select((BEAN[]) items.toArray())
    }
    //...
}
```

Since the select method converts the array internally to a list this is an unnecessary operation. Request is, that select and deselect should also be available with Iterable as parameter.

**Comment by Legioth** [comment]
I can offer two workarounds:
* If you have a `Set`, you can also do `grid.asMultiSelect().setValue()`.
* Another way is to manually select each item: `items.forEach(grid::select)`.

I'd say that instead of accepting `Collection`,  we should be even more generic and accept `Iterable`.
