### ISSUE TITLE
HTTP2 support

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#459]

**Comment by hons82** [comment]
Is http2 something that is still on the table somehow?

**Comment by Legioth** [comment]
If you servlet container supports HTTP/2, then HTTP/2 will be used regardless of Vaadin.

It has turned out that the benefits from using HTTP/2 Push are very small so that's not something we're considering to do anything for. Other than that, there isn't anything in HTTP/2 that would benefit from explicit support in the framework.
