### ISSUE TITLE
Route target instances are created before beforeEnter is called

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#4595]
A recommended approach for security (as seen in Spring Bakery) is to deny access to a route target in the `beforeEnter` method of  a `BeforeEnterObserver`.

However, at this point, the route target instance has already been created.

This is a potential security issue if care is not taken to avoid executing code that requires authorization in the constructor. It also causes unnecessary overhead.

**Comment by eriklumme** [comment]
One issue I thought of is that how will the beforeEnter method of the view you are navigating be called in this case? Or should it not be called?

@Legioth suggested that missing instances are created one by one starting from the top.

I believe this would imply that first all `BeforeEnterListeners` are executed. If the result of that is `TransitionOutcome.FINISHED`, then the `BeforeEnterObserver`s would be executed one by one, and instances only created as needed. This would imply that a possible `beforeEnter` method of the view you are navigating to would be executed, if no observer before that stopped the navigation.

The code for this is in `AbstractNavigationStateRenderer` on line 206. The `EventUtil.collectBeforeEnterObservers(...)` and `executeBeforeEnterNavigation(...)` methods must somehow execute in parallel.

 If I have the time I can take a stab at this.

**Comment by Springrbua** [comment]
I just noticed, that `setParameter` of `HasURLParamter` will be executed before the global `BeforeEnterListener`, registered for the `UI`.
The `setParameters` method is called in [AbstractNavigationStateRenderer#hanlde(NavigationEvent) Line 193](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java#L193), while the `BeforeEnterHandler`s are called in [Line 208](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java#L208).
In my opinion at least the order of those 2 hooks should be switched.

**Comment by epricer** [comment]
I was able to temporarily work around this by registering a BeforeLeaveListener with a @ListenerPriority(Integer.MIN_VALUE). 

I don't think that this is the intended location for such logic, and  suggest that a better / easier solution than changing the BeforeEnterEvent behavior and dealing with the issues that @eriklumme mentioned: there could be a new type of event (AfterLeave? MidNavigation?) fired between the [BeforeLeaveEvent and BeforeEnterEvent](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java#L182).
