### ISSUE TITLE
If you click an invalid marked textfield,dont write anything after that, click outside. You can see the textfield marked val'd!

### ISSUE THREAD

**Issue by emrephi** [vaadin/flow#4597]
TextField Validation Bug:
- Enter an invalid text into a TextField.
- Click outside and see the TextField marked as invalid.
- Click into the TextField and don't make any change
- Just click outside and you can see. The TextField marked as valid!

**Comment by ZheSun88** [comment]
Hi, Thanks for the report.  Do you integrate the textField with `binder` for this issue? As I cannot reproduce this issue with pure web-component or the Java component.  You could try it here  https://vaadin.com/components/vaadin-text-field/ with either `Java example` and `Html example`. 

But we have a similar issue when integrating `text-field` with `binder`  https://github.com/vaadin/flow/issues/3230

Could you confirm this? Thanks

**Comment by emrephi** [comment]
Hi, Yes. I integrate the textField with `binder `for this issue?

At:
https://vaadin.com/components/vaadin-text-field/ 
`Java example` has not `textfield `with `binder `example.

I think the main problem is that:
As you said at #3230: if former `Invalid `state is `true `and there is not value change event, the `Invalid `should stay `true `still.

**Comment by Klaudeta** [comment]
The issue is triggered when the field is bound as both required and with a custom validator. It looks like the required valid state overrides the custom validation invalid state

[3230-custom-validator-removed-onblur.zip](https://github.com/vaadin/flow/files/2879443/3230-custom-validator-removed-onblur.zip)

**Comment by Klaudeta** [comment]
Fixed as a result of fixing [vaadin-text-field/issues/321](https://github.com/vaadin/vaadin-text-field/issues/321)
