### ISSUE TITLE
SplitLayout addToPrimary/addToSecondary should be renamed to setPrimary/setSecondary

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#4599]
It is extremely confusing that
```java
addToPrimary(one, two);
```
and
```java
addToPrimary(one);
addToPrimary(two);
```
are not equivalents. Moreover even JavaDoc says `Sets the given components to the primary split of this layout`

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-split-layout-flow #41](https://github.com/vaadin/vaadin-split-layout-flow/issues/41) via [**ZenHub**](https://www.zenhub.com/)
