### ISSUE TITLE
The current `addComponentAtIndex()` has inconsistent behavior with previous vaadin versions

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#4600]
The handling of out of bounds indices of the current implementation of `addComponentAtIndex(index, component)` method is incorrect/unnecessary. 

according to Leif, the previous vaadin version will throw an `IndexOutOfBoundsException` instead of doing the logic as it is now ,it can cause unexpected behavior for the users, i.e.
```
when `parent.addComponentAtIndex(10, a); parent.addComponentAtIndex(9, b)` would lead to `a` being either before or after `b` depending on how many children `parent` had previously.
```

we should remove the current logic of handling of out of bounds indices and keep it the same as previous ones. 

------------------------------------------------------------
there are some other components using the same implementation on it own, which need to revisit and fix separated: 
- dialog
- notificatoin
- contextMenu

**Comment by denis-anisimov** [comment]
`ContextMenu` has no its own logic for `addComponentAtIndex`.
It implements mixin `HasComponents` and inherits `addComponentAtIndex` impl.

**Comment by ZheSun88** [comment]
@denis-anisimov check here, https://github.com/vaadin/vaadin-context-menu-flow/blob/master/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java#L276...L288

are you using the latest snapshot?

**Comment by denis-anisimov** [comment]
Right, I've been looking into `ContextMenu` class only.
