### ISSUE TITLE
setHidden() and setHidable() missing in Column

### ISSUE THREAD

**Issue by rmuller** [vaadin/flow#4608]
https://vaadin.com/docs/v11/flow/components/tutorial-flow-grid.html mentions the use of 
`setHidden()` and `setHidable()` in `Column`.  These methods do *not* exists in Vaadin Flow 11.

Environment:
- Java 8_181
- Vaadin Flow 11.0.0
- Maven 3.5.2, using com.vaadin:vaadin-bom:11.0.0

Also see https://vaadin.com/api/platform/11.0.0/com/vaadin/flow/component/grid/Grid.Column.html

**Comment by denis-anisimov** [comment]
I've created the issue in the client side Grid repo for the `hidable` property: https://github.com/vaadin/vaadin-grid/issues/1431

**Comment by denis-anisimov** [comment]
Wrong repo. I will move the issue to the correct repo.

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/vaadin-grid-flow #340](https://github.com/vaadin/vaadin-grid-flow/issues/340) via [**ZenHub**](https://www.zenhub.com/)
