### ISSUE TITLE
Problematic method signature of Component#getTranslation

### ISSUE THREAD

**Issue by rmuller** [vaadin/flow#4610]
`Component` has to methods for i18n:

+ `public String getTranslation(String key, Object... params)`
+  and `public String getTranslation(String key, Locale locale, Object... params)`

The second method signature is problematic:

+ You expect `public String getTranslation(Locale locale, String key, Object... params)` (consistent with the shorter version)
+ What about `getTranslation("Current Locale is {0}", Locale.ENGLISH)` ?

**Comment by enver-haase** [comment]
While we are at it.
Can we please change "String key" to "CharSequence key"?
I would much prefer to be able to have my own "I18nKey" class (implements CharSequence) and use that throughout.

Alternatively, such a class could be provided by the Platform, but that would now be an incompatible change (which my suggested edit is not!).

**Comment by Legioth** [comment]
>  but that would now be an incompatible change (which my suggested edit is not!).

Your suggested change is compatible only if you assume that no subclass has overridden that method.

**Comment by pleku** [comment]
Unless I'm missing something, it should be possible to just add
```java
public String getTranslation(Locale locale, String key, Object... params) { ... }
```
and deprecate the problematic `public String getTranslation(String key, Locale locale, Object... params)` with in favor of the new method.

**Comment by enver-haase** [comment]
While I cannot quite remember what my use case was back then about having CharSequence instead of String, here's a chance to incorporate this, too.
I guess I wanted to be able to introduce some kind of type safety, and since String is 'final' I could not use my new type here, directly.

**Comment by enver-haase** [comment]
> > but that would now be an incompatible change (which my suggested edit is not!).
> 
> Your suggested change is compatible only if you assume that no subclass has overridden that method.

I meant, in the new method which due to its non-existence cannot yet have been overridden.
