### ISSUE TITLE
Spike: investigate proper way to support static resources in OSGi

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4614]
Related to #4230 . Need figure out a way for this that works for static resources.

**Comment by pleku** [comment]
Maybe (?) related improvement for OSGi resources handling in Framework 8 https://github.com/vaadin/framework/pull/11166

**Comment by denis-anisimov** [comment]
See some preliminary comments here:

https://github.com/vaadin/flow/issues/4230#issuecomment-423756022

**Comment by denis-anisimov** [comment]
`org.osgi.service.http.context.ServletContextHelper` is available only as a part of Http Whiteboard bundle.
So it shouldn't work with WAB since normally there is no any knowledge and dependency to it.
