### ISSUE TITLE
Verify if push works for non-root context

### ISSUE THREAD

**Issue by elmot** [vaadin/flow#4623]
Test with all the push transport channels we have.

**Comment by pleku** [comment]
We have already an issue reported that it won't work https://github.com/vaadin/flow/issues/4619#issuecomment-422372844 but that can be addressed separately

**Comment by denis-anisimov** [comment]
There are PUSH tests in Spring and CDI ( CDI is a copy and may be modified from the Spring test).
So may be it can be copied almost as is from there.

**Comment by elmot** [comment]
Resolved by #4646
