### ISSUE TITLE
Spike: Investigate the best approach for serving webjars when there are multiple servlets for the same app

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4625]
Related to #3600. Eg. the user has public app at "/" servlet context and another servlet  "/private". Or there are two servlets, neither being mapped to root (since there is something else there), "/app1" and "/app2".

Serving webjars should ideally work in both above cases without any further configuration.

The goal of this spike is to describe why it is broken now and how we could solve it.

**Comment by SomeoneToIgnore** [comment]
Two separate problems were discovered:

1. pwa files from `flow-server` were served from non-static Vaadin directory hence were incorrectly treated by `StaticFileServer`. 
Files moved into a proper directory, tests are missing so no PR yet.

2. missing frontend files are in the servlet context resource paths.
For those, a standalone servlet will be automatically registered.
The prototype is made currently, missing a possibility to turn the behavior off and production mode support, will be continued as part of https://github.com/vaadin/flow/issues/3600
