### ISSUE TITLE
OSGi: Make all Flow components OSGi compatible

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4630]
Neither of our Flow component is OSGi compatible: meaning they have no manifest file 
and can't be deployed to OSGi.

Note that there is a known issue with webjars: they are also not OSGi compatible.

We will need to solve this somehow. Depending on the way of solving issue with webjars this ticket may not be needed at all.

BUT one of the way of fixing an issue with webjars is: repackage all webjar resources into an application itself and make them application static resources.

In this way the webjar issue is not an issue anymore but we still have an issue with Java Flow component jar: it's not a bundle at all.

The only solution with webjars when we don't need our Flow components be OSGi compatible: the full repackaging of webjars + Java code. In this case the resulting jar may have the OSGi compatible manifest and we don't need to care about every specific component jar.

I doubt that this solution is feasible: if we produce a one (repackaged)  jar with all code + webjar resources then we will need to solve somehow an issue with publishing resources as a static resources.

The resources can be made available via HTTP (by registering them via HTTP service) BUT I don't see at the moment a way to make them available for Servlet Context. And our code relies on availability the HTML import files via Servlet context.

This issue with the servlet context for the external bundle is under investigation and there is no yet the final info.
But anyway, I would like to have this issue opened since the simple repackaging of webjars and exposing them as static web resources is already working approach. But if we want to use Flow component with this approach we have to make them OSGi compatible bundles.

**Comment by pleku** [comment]
> But if we want to use Flow component with this approach we have to make them OSGi compatible bundles.

Is it possible to make this happen by adding the configuration to https://github.com/vaadin/flow-component-base as it is the parent of all the components ? If that bundle presumes that the application itself handles unpacking of webjars->static resources.

**Comment by pleku** [comment]
>Looks like you are talking about making a configuration which allows to get webjars also working in OSGi along with the component.
Nope - I was not referring to the webjars, only just to make the components Java integrations have the OSGi manifest (and thus be a compatible bundle) by having configuration just in the parent module.

**Comment by denis-anisimov** [comment]
OK.

We can try it. I'm not sure.
`bnd` file supports variables. So we can set manifest entry value to expressions based on pom parameters.

But if we want to set some non generic value ( for some reason) then we will need to have  personal `bnd` file in the component repo.

**Comment by pleku** [comment]
As agreed, the first step will be to add the OSGi manifest to make the component jars OSGi compatible.

Second step (not part of this issue) will be to take care of the static resources that some components also include (like grid, date-picker, combo-box). For now those can be handled by unpacking the static resources in the application project.

### Acceptance Criteria
The 1.2-SNAPSHOT version of every component (2.1 for vaadin-grid-flow) is a OSGi compatible jar.
