### ISSUE TITLE
Custom UI does not work as RouterLayout

### ISSUE THREAD

**Issue by elmot** [vaadin/flow#4638]
`java.lang.IllegalStateException: Can't set the parent of the tree root` exception is thrown when a custom UI is used as a `RouterLayout`,

*Example*
```java
public class RootUI extends UI {

    @WebServlet(urlPatterns = "/", name = "UIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = RootUI.class, productionMode = false)
    public static class ContextServlet extends VaadinServlet {

    }

    @Route(value = "",layout = RootUI.class)
    public static class RoutedSpan extends Span {
        public RoutedSpan() {
            super("Something inside");
        }
    }
}
```

*Expected behavior*
UI implements RouterLayout => Should work.

*Actual behavior*
 - The exception is thrown
 - Exception message does not bring any information to the developer. Even if this bug is fixed, the same exception might be thrown in another situation, and the developer is going to be very frustrated.

**Comment by pleku** [comment]
Since this issue has not really gained traction, I'm closing this as a won't fix.

Feel free to comment here or open a new one and explain why this would be critical for you.
