### ISSUE TITLE
HasComponents#remove is not fully consistent with its javadoc and log messages

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/flow#4662]
https://github.com/vaadin/flow/blob/f926f4f3ab856b394b5989162e083ce5042611e3/flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java#L54-L80

Javadoc says
>      @throws IllegalArgumentException if any of the components is not a child of this component

But if a component has null parent there is no `IllegalArgumentException`

Also early return if component to remove has no parent will behave differently if calling with varargs and component with no parent is placed on different positions
* if first component has no parent it's no-op
* if component without parent is in the middle some children are removed

**Comment by mvysny** [comment]
I've just got bitten by this bug, basically I have a ComboBox in a form which shows different edit components based on its value. When the ComboBox is flipped, remove(editor1, editor2, editor3) is called but it's a no-op since editor1 is not present in the form...
