### ISSUE TITLE
Unable to create an app without using Router

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#4663]
For a simple app, I want to create my custom UI class and not use `Router` at all. I do not want any logic connected to the browser location and definitely do not want to trigger server requests or routing even if somebody changes the location using e.g. `history.pushState`

Based on `UIInternals.getRouter()` javadoc, it is ok to not have a router and return null from that method. If you however override `UI.getRouter()` and return null, then you will get NPEs from here and there. 

What is the correct way of accomplishing this?

**Comment by pleku** [comment]
This used to be possible by replacing the `HistoryChangeHandler` in `History` which is accessible via `UI::getPage`->`Page::getHistory` `History::setHistoryStateChangeHandler`. Not sure if it is broken somehow now with the client side router integration.

But as this is not a documented feature and it is not something that is requested and thus supported out of the box, I'm closing this issue as _won't fix_. In case someone needs this, please open a new issue describing the use case.
