### ISSUE TITLE
Page reload loop with 12.0.0.alpha2

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#4664]
After updating to 12.0.0.alpha2 (from 11) I'm experiencing page reload loops: the page keeps reloading indefinitely with this message in the console:

```
Response didn't contain a server id. Please verify that the server is up-to-date and that the response data has not been modified in transmission.
```

I'm using the Spring addon, so I tried to reproduce this in a simple app but it doesn't happen, so it should be something related to something specific to the app where this happens.

Any idea of what may have changed in 12 causing this?

**Comment by heruan** [comment]
Not sure how to identify the server response causing this, since the network requests are a lot. Can I disable automatic reload of the page on error? This might help me to identify the last received response.

**Comment by gilberto-torrezan** [comment]
Hi @heruan,

I just tested with the [Project Base with Spring](https://github.com/vaadin/skeleton-starter-flow-spring) from master branch, just changing the `vaadin.version` to `12.0.0.alpha2` in the `pom.xml`, and I couldn't reproduce the error.

Can you share a sample code where the error appears?

**Comment by heruan** [comment]
Thank you @gilberto-torrezan but I cannot reproduce on a sample code, so it should be something specific to my main app. I manage to identify the last request before the page reloads:

```
POST /?v-r=uidl&v-uiId=0 HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Content-Length: 206
Pragma: no-cache
Cache-Control: no-cache
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Content-type: application/json; charset=UTF-8
Accept: */*
Referer: http://localhost:8080/
Accept-Encoding: gzip, deflate, br
Accept-Language: en
Cookie: JSESSIONID=F969E478DA3C0EFE7076B832E398DFCB

{"csrfToken":"9e7b98cd-c329-4bea-bca1-f94453a71e88","rpc":[{"type":"publishedEventHandler","node":10,"templateEventMethodName":"updateSelectedTab","templateEventMethodArgs":[true]}],"syncId":0,"clientId":0}

HTTP/1.1 200
Set-Cookie: JSESSIONID=DCB5C7EE14CC729610C736C2AFC359AB; Path=/; HttpOnly
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: DENY
Content-Type: application/json;charset=UTF-8
Content-Length: 42
Date: Thu, 04 Oct 2018 10:31:51 GMT
```

In the response data tab, Chrome says: "Failed to load response data".

What I notice here is the `JSESSIONID` changing without reason, I'll double check that.

**Comment by heruan** [comment]
I've found the problem: enabling PWA in 12 will install a service worker which is requested by the browser in a special way, which is not intercepted by a Chrome plugin I'm using to add headers to the requests: the service worker request was then missing an header I use to select the current tenant and the session was invalidated, thus reloading the page (and creating the loop).

I spotted this downgrading to 11 and noticing the same loop, since once installed the service worker is still requested by the browser—no matter if the `@PWA` annotation was removed!
