### ISSUE TITLE
Specify when to send events to server( after delay, every Nth event, ...)

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#467]
- DOM event listeners
- Synchronized properties

**Comment by heruan** [comment]
Any update on this? We are using text fields with listeners to filter grids and typing a single word ends up triggering the action (e.g. a SQL query) for each typed character.

**Comment by Legioth** [comment]
As discussed on Gitter:

One quite easy fix is to copy the `ValueChangeMode` concept from FW8 as a high level API for specific built-in components. This would be quite easily done and would probably resolve most of the issues.

The other part is to provide generic and flexible low level support that can be used together with features such as `Element::addEventListener`, `Element::synchronizeProperty` and `@EventHandler`. This requires some additional design to ensure that the resulting implementation is flexible enough for most conceivable cases.

**Comment by pleku** [comment]
For `TextField`, `PasswordField` and `TextArea` we are planning to do https://github.com/vaadin/flow/issues/3229 for now. This issue does is still valid, but not currently in the backlog for V10.

**Comment by Legioth** [comment]
It might be natural to implement a common low level feature that handles both asynchronous event sending and filtered event sending. Some thoughts on that in https://github.com/vaadin/flow/issues/468#issuecomment-366971657 that covers the filtering aspect.

**Comment by Legioth** [comment]
These are my conclusions  based on some prototyping and looking into what other frameworks provide:
* The fluent API based on a custom `Registration` subtype that I suggested in #468 seems to make sense
* Using an "asynchronous filter" based on `Promise` that I suggested in #468 is not practical because of the way the handler always needs information from the previous invocation. It would be much more practical to instead provide a couple of hardcoded modes.
* There are three typical modes of operation when it comes to controlling timings related to event handling. They are all based on a timeout duration and different variations of when to send something to the server.
  * Trailing edge debounce: Events are ignored until the timeout duration has passed without any further events. At that point, the latest event is sent to the server. This is useful for e.g. text input where the server wants to know the text only after the user has stopped typing.
  * Leading edge debounce: An event is sent to the server immediately, but no further events are sent until there has been one timeout duration without any new events. This is useful for e.g. button clicks where the server immediately wants to know about the events, but accidental repetitions should be ignored.
  * Throttling: An event is sent immediately, and then once every timeout period as long as events are still fired. This is useful e.g. for showing feedback to the user while a slider is being dragged.
* We could allow configuring on the registration which of these three types of events to listen to. Furthermore, the throttling case might in some cases benefit from from having information in each event sent to the server about whether this is the first, intermediate or last event in a sequence. 
  * There's also a special case of being interested in both the leading and the trailing edge, but not any intermediate updates. We could offer a low-level API for describing a set of conditions to listen for instead of only allowing one per registration, but on the other hand the same case can also be handled by registering a separate listener for both of the cases.

**Comment by Legioth** [comment]
Still pending documentation updates.

**Comment by Legioth** [comment]
Documentation in https://github.com/vaadin/flow-and-components-documentation/pull/93

**Comment by oliveryasuna** [comment]
> It's not a blocker, we're currently doing the debounce ourselves, but that means we have an intermediate step in JS before calling server

I know this is old, but I am curious how you achieved this? Did you override the Vaadin web components or something?

**Comment by Legioth** [comment]
> Did you override the Vaadin web components or something?

One way is to use e.g. `executeJs` to manually add a listener for the event you're interested in and then having that listener fire a DOM event with a different name and make the server-side part listen for that event instead of the original event.
