### ISSUE TITLE
Create another testing module for OSGi which uses different web container

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4672]
There is already OSGi tests which are done inside https://github.com/vaadin/flow/tree/master/flow-tests/servlet-containers/felix-jetty

Those tests should be kept as is. May be they will be removed later at some point. 
But they should be preserved until we have another tests.

The existing tests use `jetty-osgi-boot` servlet container implementation (it allows to discover routes at least).

But this _servlet container_ doesn't provide an HTTP service implementation.
This service is needed to handle resources from other bundles (at least `flow-client`  has such case).

There is a custom HTTP service implementation inside `flow-test-root-context`  module.
This service allows to register external resources but it's implemented via creating a different Servlet every time when the resource is registered.

It means at least that `ServletContext`  for the application servlet won't be able to find the external resources.

So we should use another web container inside OSGi container which provides HTTP service and _MAY BE_ makes the registered resources available via `ServletContext` of the original servlet.

There are several options:
- Apache Felix OSGi container can be reused but _another_ Servlet container should be used inside it.
- Use ready-made Apache Karaf OSGi container which is bundled with web container already.

**Comment by pleku** [comment]
Here is the Karaf test module from Framework https://github.com/vaadin/framework/tree/master/test/servlet-containers/karaf

**Comment by pleku** [comment]
Concluded that we'll try to switch to Karaf but have to download it run it from command line instead of using the Maven way which doesn't work. This is done already for FW 8 for running it.

**Comment by denis-anisimov** [comment]
`felix-jetty` is used instead of Karaf as a result.
I was not able to make Karaf and Flow work in automated tests (with required bundles autodeploy).
Here is the draft for Karaf which can be used for further improvement: https://github.com/vaadin/flow/tree/KARAF-OSGi-container
It at least downloads Karaf distribution and unpack it properly. The remaining things are:
- deploy all the required bundles correctly (now Karaf is going mad when it's started with all the bundles in its `deploy` folder)
- start Karaf properly (see above: Karaf is totally broken when it's started with all the bundles).
