### ISSUE TITLE
MenuBar component

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4694]
Replacement component for the old menubar component from framework https://demo.vaadin.com/sampler/#ui/interaction/menu-bar

This issue is just for tracking progress/timeline/plans for now, the actual implementation will be in the web component repository and component's Flow integration repository.

**Comment by heruan** [comment]
I'd suggest a more versatile name, such as `MenuButton` or `ButtonDropdown` since I've often seen FW8's `MenuBar` used with a single item as a button with drop-down actions.

**Comment by pleku** [comment]
>I'd suggest a more versatile name, such as MenuButton or ButtonDropdown since I've often seen FW8's MenuBar used with a single item as a button with drop-down actions.

I would expect us to have a `PopupButton` component at some point. It is basically just combining `Button` and `ContextMenu`/`Overlay` so that the pop-up is like drop-down, but always visible and allows you to put anything inside it. That or drop-down-menu (now renamed to select) can be the basis for the menu bar component, which IMO should have quite high level API for defining hierarchical menu structures with multiple popups etc that is specific for menus.

**Comment by knoobie** [comment]
Would be awesome if the new MenuBar would be accessible out of the box. 

https://www.w3.org/WAI/tutorials/menus/

FYI: There are two types of menus "Fly-out Menus" and "Application Menus" - both have different types of keyboard handling.

**Comment by pleku** [comment]
Superseded by https://github.com/vaadin/vaadin-core/issues/208
