### ISSUE TITLE
There is a logic issue in the RouteRegistryInitializer class related to PWA

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4700]
`RouteRegistryInitializer` has a call `validatePwaClass`.
The latter method assumes that the class from the parameter collection always has `Route` annotation.
But in the `onStartup` method this method receives not filtered initial `classSet` which shouldn't be used as is but instead filtered `routes` collection should be used.
The latter collection contains only classes with `Route`  annotation.

**Comment by pleku** [comment]
Not sure on the technical side, but just to clarify: the `@PWA` annotation can also be used in root layouts

**Comment by denis-anisimov** [comment]
`validatePwaClass` class calculate root layout based on Route class.

There is a code:
```
Route routeAnnotation = route.getAnnotation(Route.class);
            if (!UI.class.equals(routeAnnotation.layout())) {
```

It assumes there is a `Route` annotation for the class. Otherwise it will just throw NPE.

**Comment by caalador** [comment]
The main problem is actually that it uses `classSet` not the validated `routes` Set.
Even though `classSet` should always contain `@Route` as `@RouteAlias` can not be on its own.
