### ISSUE TITLE
OSGi: Take care about dynamically changed routes (and other initial data)

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4710]
Now when we collect routes and other data based on the ServletContextInitializers we should updates the data when bundles are deactivated.

Currently the route registry is initialized once and it becomes immutable so the routes are never changes after this.

But in OSGi bundles may be activated/deactivated on fly.
It means that we should update the data in registries.

There is already logic which tracks the classes via bundle lifecycle.
And every time when the registry is initialized it used the actual data.
But now we should update the registries during lifecycle (not use only the data once in the initialization).

The simplest approach would be to use the singleton registry which is returned for every servlet context which is not immutable but updates its data every time when bundles changes.

But it won't allow to use built-in Servlet context initializers if Web server inside OSGi allows this (there are some web servers which allows this).
So we should be aware on possibility to initialize RouteRegistries in a usual way **BUT** also modifies those data on the fly during bundles lifecycle.
May be the current approach should be kept but the registries should be modified once new data is set into the data collector (fake OSGi route registry which only collects the data).

Also don't forget about other ServletContextIntializers (there are not only routes!)

**Comment by pleku** [comment]
### Use case
When buiding an app in OSGi environment, I dynamically register routes when another bundle is added, so that I can trigger new features for my app on the fly

### Acceptance Criteria
- There is a tutorial for this in our OSGi documentation that shows how this can be achieved (if it needs anything specific from the application developer)

**Comment by denis-anisimov** [comment]
There are several notes to consider here:
- see this comment: https://github.com/vaadin/flow/issues/4808#issuecomment-442078326
- OSGi registry should not be "immutable" (as it's done now allowing  initialization only once). Every time when data is changed (now it's in `OSGiDataCollector` ) every OSGi registry instance should be updated with the new routes
- currently `doInitOSGiRoutes`  is not thread safe: if several threads requests routes at the same time and registry is not initialized yet then `registerNavigationTargets` may be called simultaneously. As a result one of the `routes.compareAndSet` calls will fail. This won't break the internal state but the exception will be thrown. This issue is not a serious thread safety issue (since the internal state remains consistent) but it causes an exception. Again this is a consequence of expected "immutability".
- current implementation tries to be aware of regular bootstrap route initialization via standard `ServletContainerInitializer` way. It seems it's just not possible to keep this way of initialization: since we want be able to update scanned classes dynamically the routes which are discovered by the standard `ServletContainerInitializer` mechanism will be just replaced with the classes which are found at the current moment. So it looks like we just should just ignore this mechanism completely in OSGi case.
