### ISSUE TITLE
Anchor.setHref("") wrong behaviour

### ISSUE THREAD

**Issue by kuvalda07** [vaadin/flow#4711]
In Vaadin 11 API Doc it's said:
public void setHref(String href)
Sets the URL that this anchor links to.
Parameters:
href - the href to set, or "" to remove the href value

But, actually, it sets href attribute with an empty string, so it fires downloading of an empty resource, when is used for downloading resources.

Workaround: Manually remove href attribute.
`downloadAnchor.getElement().removeAttribute("href");`

**Comment by caalador** [comment]
The javadoc should be updated as the functionality has been changed in #2718 for use case #2704

**Comment by kuvalda07** [comment]
May be, some removeHref() method should be added?
So, it could be done without direct access to DOM.

**Comment by denis-anisimov** [comment]
Sure.
It's already added.
Will make a PR in a few seconds.
