### ISSUE TITLE
Add background for "Server connection lost, trying to reconnect..." message

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#4712]
platform 12.0.0.alpha4

Expected: a legible error message on server connection failure
Actual: 
<img width="1792" alt="screen shot 2018-10-21 at 1 29 18 pm" src="https://user-images.githubusercontent.com/883698/47272121-b1eecb80-d535-11e8-887f-a3d5dd475bf2.png">

**Comment by pleku** [comment]
The _connection lost, trying to reconnect_ dialog has been revised in V19 and it does now how a background. 

![image](https://user-images.githubusercontent.com/1478381/112831838-2c27c080-909d-11eb-8125-6b32c8404aef.png)
