### ISSUE TITLE
Allow navigating to an error view when an exception occurs after a page is loaded

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#4715]
By implementing `HasErrorParameter<T extends Exception>`, exceptions can be handled if they occur during navigation.

However, it would sometimes be convenient to re-use them even if an exception occurs after navigating, at least to avoid showing the error notification when an unhandled exception occurs.

Even if an error handler is set on the VaadinSession, it is not possible to navigate to an error view from there. Also, the error notification is still shown.

**Comment by TatuLund** [comment]
Is this related to this https://github.com/vaadin/flow/issues/4549 issue?

**Comment by eriklumme** [comment]
From a quick look, yes, the same core issue that exceptions that do not happen during navigation will not trigger the error view.

**Comment by knoobie** [comment]
@mshabarov when this gets implemented: 

Just a note: I would suggest that this only takes precedence for "concrete" exceptions. 

Example: 

We have a general HasErrorParameter<Exception> that is used for all exceptions that occure whole still in navigation as "last resort" exception handler as recommended by OWASP and required by the BSI (German security agency) therefore this would literally grab all exceptions while using the application, making the default ErrorHandler interface useless, which is as well the last resort exception handler while using the app (clicking buttons etc) and really important, especially when the other ticket regarding what component triggered the error is considered / implemented. 

Soooo... Long story short: 
- HasErrorParameter<ConcreteBusinessException> --> handle it 
- HasErrorParameter<Exception> --> don't handle it outside of the router circle
