### ISSUE TITLE
Test automatically on all supported servers

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#472]

**Comment by torok-peter** [comment]
Related commits to Fw8:
* https://github.com/vaadin/framework/commit/3cbd834842319d151d9248706bc14e14a3abca42
* https://github.com/vaadin/framework/commit/4ac4b62434ab48fdb7d3ca9c479383d4242062aa
* https://github.com/vaadin/framework/commit/a8f23e84a0fbb5da515cacffb8f5a85fd4c21694

**Comment by mshabarov** [comment]
I propose to make a separate tickets for certain servers instead, for instance OpenLiberty, WebSphere etc.
