### ISSUE TITLE
Support loading ES modules

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#4728]
It is not possible to load ES modules with the current `@JavaScript` annotation. The script needs to be loaded with `type="module"` to allow the use of module features. 

Please add support for loading ES modules with the annotation.

**Comment by Legioth** [comment]
Related to https://github.com/vaadin/flow/issues/3527 and https://github.com/vaadin/flow/issues/4561.

**Comment by pleku** [comment]
`JsModule` has been available since Flow `2.0`.
