### ISSUE TITLE
HighlightCondition for matching default route

### ISSUE THREAD

**Issue by kjordan2001** [vaadin/flow#4730]
locationPrefix in HighlightCondition won't work for the default route "" since startsWith will match that as the start to any String.  It seems like it needs to check if the Route value is empty and if the event location path is also empty like:
`link.getHref().isEmpty() ? event.getLocation().getPath().isEmpty() : event.getLocation().getPath().startsWith(link.getHref())`

**Comment by mvysny** [comment]
Actually the prefix matching will fail in multiple cases: if you have a view mapped to foo and foo/bar and navigate to foo/bar, both views will be highlighted. This complicates further if the views have parameters.

The only reliable way is to get the view class from the AfterNavigationEvent.getActiveChain(0).getClass() and compare that against the link target.

**Comment by pleku** [comment]
While the code to reproduce this issue is missing, it should be possible test it with `RouterLinkTest`.

**Comment by denis-anisimov** [comment]
The ticket is about `HighlightConditions::locationPrefix` method.
