### ISSUE TITLE
Get path info from VaadinRequest in PwaHandler

### ISSUE THREAD

**Issue by mcollovati** [vaadin/flow#4733]
In PwaHandler path info is taken from `HttpServletRequest` after doing an explicit cast of `VaadinRequest` to `VaadinServletRequest`.

https://github.com/vaadin/flow/blob/50b22c5cad4122c33ea8f6a42e4381423be10c33/flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java#L127-L128

Since `VaadinRequest` exposes `getPathInfo` method there should no need for cast; this way `PwaHandler` could be used as is also on non servlet environments

**Comment by QNENet** [comment]
Flow 1.2.3
I am experimenting with the OSGi basic project and having a problem with PWA.
In the method https://github.com/vaadin/flow/blob/50b22c5cad4122c33ea8f6a42e4381423be10c33/flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java#L127-L128
Line 128 returns null when at the "" route, this causes an exception in my case.
Is returning null to be expected?

**Comment by mcollovati** [comment]
May I close this issue? The change seems to be already merged

**Comment by denis-anisimov** [comment]
Yes, of course.
It's not an issue anymore and you may close your issues generally .
