### ISSUE TITLE
Determine how to enable Brotli compression by default

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#4740]
This is a follow-up to #4583 which introduces opt-in support for Brotli compression. Brotli compression should be enabled by default in cases where we can assume there won't be any interference issues similar to those that caused https://github.com/vaadin/flow/pull/4556 to be reverted.

In order to do that, these steps are needed:
* Introduce a third configuration parameter option so that `true` always uses precompressed files, `false` never uses, and a new `auto` configuration uses unless we can detect a situation where there will be interference. `auto` is used by default if no specific value is defined for the application.
* When `auto` mode is in use, look for Tomcat 8.x with built-in precompression e.g. based on the findings documented in https://github.com/vaadin/flow/issues/4583#issuecomment-418683599.
* Test with all other supported servlet containers. In particular, look for any built-in configuration options for enabling compression similar to the incompatible option in Tomcat 8.x and test with such options enabled.

**Comment by Artur-** [comment]
How about we just do not support Brotli for Tomcat 8 and use Brotli for other servers. Unless the latest Tomcat 8 is fixed, then we just enable it. Then if you are using a broken server, you can disable it

**Comment by Artur-** [comment]
Spring Boot nowadays uses Tomcat 9.x by default and there I do not see any issues when using Vite with Brotli compressed resources and
```
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
```

It is not possible to downgrade to using Spring Boot 2.5  + Tomcat 8.5.72 either so it cannot be tested
```
The following method did not exist:
    'void org.apache.tomcat.util.modeler.Registry.disableRegistry()'
```

**Comment by Artur-** [comment]
Also tested Jetty and Undertow - no issues
