### ISSUE TITLE
Reconsider OSGi versioning

### ISSUE THREAD

**Issue by elmot** [vaadin/flow#4744]
All Flow projects at the moment use OSGi (Bundle-Version manifest tag) version of form *1.2.3*. That does not guarantee bundle uniqueness if an OSGI container have pre-release and final bundle versions deployed simultaneously. In case of OSGi approach that may lead to hard-to-detect problems even in production systems. We may use versioning like *1.1.3.20180102* which should work much better.
For OSGi versioning see https://bnd.bndtools.org/chapters/170-versioning.html, §9.2
see `${parsedVersion.osgiVersion}` maven property

**Comment by pleku** [comment]
This works fine in eg. FW 8, so what we have now is broken.
All the following things should work
- snapshots: eg. 1.2.0-SNAPSHOT -> 1.2.0.20181030 (number id as the fourth one)
- prereleases: 1.2.0.alpha1 -> 1.2.0.alpha1
- final releases 1.2.0 -> 1.2.0 (this is fixed now)

**Comment by pleku** [comment]
Just verified that it works correctly for Flow already, just need to verify for the component Java integrations too (flow-component-base).

**Comment by mehdi-vaadin** [comment]
flow-component-base uses Felix maven bundle plugin that has a different behavior from bnd-maven-plugin in terms of generating bundle version. So, in flow components, we will have bundle versions like `1.2.0.SNAPSHOT`, `1.2.0.alpha1` and `1.2.0.1`.

**Comment by mehdi-vaadin** [comment]
We should check the version sorting mechanism of OSGi to make sure that for example `1.2.0.0` is considered bigger than `1.2.0.SNAPSHOT`.

**Comment by pleku** [comment]
Unlike falsely claimed here, everything is apparently working like it should and how has been done previously in the framework.

Only difference is now with snapshots, eg. 1.0-SNAPSHOT is released as
- 1.0.0.20181102 for Flow artifacts
- 1.0.0.SNAPSHOT for component Java integrations

This is fine. Final releases and prereleases work consistently everywhere, and the same as before. If someone wants to mix snapshot and release/prerelease versions of the components in an OSGi environment, then we can revisit this.
