### ISSUE TITLE
Project base for Flow and OSGi

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4748]
A project base based on the vanilla Flow project base, that produces an OSGi web application bundle of the Flow application.

The name of the repository should be `base-starter-flow-osgi`. 

This should end up in vaadin.com/start too, which requires that the necessary metadata is added to the `website-content` GitLab repository. Most of that is a copy from any of the other project bases.

The testing of the starter should ideally happen in the `flow-starters` repository, but for now it is fine to test manually.

**Comment by pleku** [comment]
For example on how to test this manually, you can take a look at #4672

**Comment by denis-anisimov** [comment]
We don't have a functionality which autoregister a `VaadinServlet` instance for OSGi.
See #4796.
This can be done as a part of the project base though.
There are also a couple of tickets for servlet registration via Http Whiteboard spec.
#4797 and #4367.
Both of them can be workarounded right in the project. But I think #4797 can be done beforehand (should be easy).

Current OSGi testing infrastructure uses `felix-jetty`  which doesn't register `@WebServlet` servlets from the WAB for some reason (at least out of the box). So in case of reusing testing infrastructure without changes we should register the app servlet via `HttpService` or HTTP whiteboard spec.
This way will require fixes for the issues mentioned above.

**Comment by denis-anisimov** [comment]
The simplest project uses `flow-component-renderer`  web resource from `flow-data` which is not registered.

So #4807 should be done first.

**Comment by denis-anisimov** [comment]
#4809 is one more issue which is needed for this ticket.
Though the project can be done without the fix. It affects only L&F of the application.
