### ISSUE TITLE
SPIKE: generic DnD for components

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4770]
The API for the standard HTML5 DnD should be mostly if not completely the same as in Framework 8.1+, but since we don't have the extension concept in Flow, there should be an alternative way for it. Thus, there needs to be an API for making any component drag source or a drop target.

(Implementation details: is quite certain that both "extensions" should include connectors to the client side and register those to the component as generic `dragSourceConnector` and `dropTargetConnector` is that handle the DnD interaction without the component knowing anything about it. It might be possible to create `drag source` without the connector with just using Element API from server side, but the _drop target_ needs to be able to execute the server side set acceptance criteria for the dragover/drop events, so that requires a connector.)

(More implementation details: since the framework automatically provided hooks for the extensions to cleanup when the component is detached/attached again, so we need to make sure that the extension doesn't cause the component to stay in memory when it shouldn't anymore.)

Generally it should be quite straight forward to start adding API to the _drag source_, _drop target_ and _file drop target_ based on what we have in Framework 8 as it is based on the standard.

The only thing that needs investigation is the testing: can we test the DnD features with Testbench (Selenium) with headless Chrome, or how can we create regression tests for this. This didn't work before with PhantomJS.

This spike should verify that testing is possible, and as part of that output an initial draft version of `DragSource` and `DropTarget` in a branch/PR.

**Comment by denis-anisimov** [comment]
`new Actions(getDriver()).dragAndDrop(source, target).build().perform();`  doesn't work neither in Chrome nor in FF.

**Comment by denis-anisimov** [comment]
This way :
`new Actions(getDriver()).moveToElement(source, 2, 2).clickAndHold()
                .moveToElement(target, 5, 5).release().build().perform();`
doesn't work either for both of them.
