### ISSUE TITLE
 Failed to install required frontend dependencies

### ISSUE THREAD

**Issue by DinuMihnea** [vaadin/flow#4771]
```
Failed to install required frontend dependencies: Could not download Node.js from: https://nodejs.org/dist/v8.11.1/win-x64
/node.exe: Could not download https://nodejs.org/dist/v8.11.1/win-x64/node.exe: Connect to nodejs.org:443 [nodejs.org/104.20.23.46, nodejs.org/104.20.22.46] failed: Conn
ection refused: 
```

When I am trying to build for production the Vaadin Flow app using vaadin-maven-plugin, it's can't download the nodejs dependency.
I configured the **proxy settings** for my installed NodeJs (the same version 8.11.1) in .npmrc file, but maven plugin does not found them.

I use 11.0.0 version of Vaadin.

**Comment by SomeoneToIgnore** [comment]
Closing this due to no further responses, feel free to comment if something is unclear.

**Comment by DinuMihnea** [comment]
Confirm closing, Thanks!
