### ISSUE TITLE
ArrayIndexOutOfBounds when setting up hidden Button

### ISSUE THREAD

**Issue by wfischlein** [vaadin/flow#4772]
When setting the visibility of a Button to enabled/disabled plus changing the text, and icon when the Button is disabled I ger the attached exception:
[stacktrace.txt](https://github.com/vaadin/flow/files/2566897/stacktrace.txt)

To reproduce download, unpack and mvn jetty:run this project
[my-starter-project.zip](https://github.com/vaadin/flow/files/2566894/my-starter-project.zip)

Then open localhost:8080 and find two radios 'First Element', 'Make me crash'  and a checkbox 'No initial crash'.

Click on  'Make me crash'. Expected: Radio selected, silence in the log
Found: Exception in the log as attached and a warning in the browser (Internal error blah blah)

reload the page, check 'No initial crash' -> a button 'Horst' appears
click 'Make me crash': No crash, instead the button gets updated accordingly with an up arrow and a label 'Up'
click 'First Element' - still all fine, the button disappears
Now as it is hidden the next click on Make me crash makes it crash again
(expected: nothing evil)

**Comment by caalador** [comment]
This doesn't reproduce anymore with v14.1.21
Will close as fixed, if this happens again please open a new ticket with detailed information for replication.
