### ISSUE TITLE
TextField#setPreventInvalidInput(true) does not work when turning on the required indicator

### ISSUE THREAD

**Issue by duy-ng-12354** [vaadin/flow#4814]
Hi,

I am trying to prevent invalid input from end-user by using the example in https://vaadin.com/components/vaadin-text-field/java-examples. It works well if I implement my text field the same as in the example. However, when I call the method TextField#setRequiredIndicatorVisible(true), the input restriction does not work anymore.

**Working codes:**
```
TextField dollarField = new TextField("Dollars");
dollarField.setPattern("[0-9]*");
dollarField.setPreventInvalidInput(true);
```

**Non-working codes:**
```
TextField dollarField = new TextField("Dollars");
dollarField.setPattern("[0-9]*");
dollarField.setPreventInvalidInput(true);
dollarField.setRequiredIndicatorVisible(true); // looks like it causes the issue
```

In addition, when I use the **Binder#asRequired(...)**, the method **setPreventInvalidInput** also does not work.
```
binder.forField(dollarField).asRequired("Cannot be blank")...
```
However, when I use another kind of validator, the input restriction works as expected
```
binder.forField(dollarField)
                .withValidator(value -> StringUtils.isNotBlank(value), "Cannot be blank")...
```

I am using vaadin 11.0.2.

Please help to take a look.

**Comment by mehdi-vaadin** [comment]
This bug exists in Vaadin 12 as well.

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/vaadin-text-field-flow #142](https://github.com/vaadin/vaadin-text-field-flow/issues/142) via [**ZenHub**](https://www.zenhub.com/)
