### ISSUE TITLE
Vertical Splitter in Edge and Firefox (Vaadin 10)

### ISSUE THREAD

**Issue by OlgaIOn** [vaadin/flow#4816]
Vertical Splitter is displayed incorrectly in Edge and Firefox:

(![verticalsplitter](https://user-images.githubusercontent.com/45284497/49024716-71204d00-f19a-11e8-8cec-36f01e169d98.png))

**Comment by OlgaIOn** [comment]
Hi @pleku . Yes, it is SplitterLayout. 
Primary split contains Grid, secondary split contains TextArea, SplitterPosition - 50.0

Browser:
-  Firefox Quantum (Linux Mint)
-  Edge (Windows 10)

**Comment by pleku** [comment]
Issue moved to [vaadin/vaadin-split-layout #125](https://github.com/vaadin/vaadin-split-layout/issues/125) via [**ZenHub**](https://www.zenhub.com/)

**Comment by pleku** [comment]
Moved the issue to the vaadin-split-layout web component repository.
