### ISSUE TITLE
Add helper for automatically highlighting the active item in a menu

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#482]
Automatically highlighting the active part in e.g. a menu hierarchy can already be done manually by making the menu or individual links implement `AfterNavigationObserver` and then manually toggle a css classname or an attribute.

In the general case, menu items can be represented by any kind of component and there can also be arbitrary logic for when a section is considered to be active. In practice, the menu items are usually `RouterLink` components and the hierarchy is either defined based on the URL structure or sharing a common `RouterLayout` (though in most cases the topmost layout is shared among the entire application).

We could add helper API to `RouterLink` for the common cases and ensure the documentation also contains an example of how this is done manually.

**Comment by Legioth** [comment]
Some ideas on what the API in `RouterLink` could look like:

```
// Low level flexible API based on BiPredicate<RouterLink, AfterNavigationEvent>
someLink.setActiveCondition((link, event) -> event.getLocation().getPath().startsWith("foo"));

// Helper for creating conditions
someLink.setActiveCondition(ActiveConditions.sameLocation()); // This could be used by default?
someLink.setActiveCondition(ActiveConditions.locationPrefix());
someLink.setActiveCondition(ActiveConditions.locationPrefix("foo"));
someLink.setActiveCondition(ActiveConditions.hasLayout(SomeLayout.class));

// Configuring how active is represented
someLink.setActiveClassName("link-active"); // default is null
someLink.setActiveAttribute("link-active"); // default is "active"
```

**Comment by caalador** [comment]
The name `setActive` sounds like having it as false means that it is disabled and will not give events.
Does it actually disable the link or is it just a styling?

**Comment by Legioth** [comment]
My assumption is that it only affects styling. The link would still be usable.

Any other ideas on the naming?

**Comment by caalador** [comment]
`setHighlightCondition` or `setStyleCondition`

for a `setStyleCondition` it could be usable as `someLink.setStyleCondition(StyleCondition, String activeClassName)` or the like so you could have different styles for different conditions.

**Comment by Legioth** [comment]
Being forced to explicitly define a classname with no default available sounds like boilerplate that is only there to support a quite theoretical case of having multiple conditions. It's always possible to achieve the same result with an explicit `AfterNavigationObserver`, so this helper API doesn't have to cover all potential cases.

I'll change my proposal to use `highlight` instead of `active`.

**Comment by heruan** [comment]
How should the `RouterLink` be notified of the `AfterNavigationEvent`?

**Comment by Legioth** [comment]
Anything that is currently attached to the component tree will receive navigation events if they implement the appropriate interface.
