### ISSUE TITLE
Flow component generator: disallow to set property whose name is a client side function name

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4824]
I'm not sure whether this is a current behavior or not but I expect there is nothing preventing me from setting a property with an existing function name.

E.g. "ready" callback for Polymer template.

If I have a `Component`/ `Element` then I may do:
```
component.getElement().setProperty("ready","abc");
```

This may break the client side component functionality.
We can't prevent every possible function here for an arbitrary HTML element since we don't know which methods it has.
But what we can do for sure (since we already have a component generator): collect all functions declared for a client side polymer element and disallow updating any property whose name is a function name.

It can be done already now via a property listener which throws an exception.
Or may be we can add an additional functionality to the `ElementPropertyMap` feature to listen changes of any property. 
Then it may be just one listener which throws an exception if only a property is in the set of function names (may be if this change happens only form the server side).

**Comment by pleku** [comment]
Probably could make sense to do, but as the component generator has been internally "depricated", this feature will never be.
