### ISSUE TITLE
Component generator: theme variant enumeration should have overriden `toString` method

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4840]
Here is the result of the generated class:
```
@Generated({ "Generator: com.vaadin.generator.ComponentGenerator#1.2-SNAPSHOT",
        "WebComponent: Vaadin.ButtonElement#2.1.0", "Flow#1.2-SNAPSHOT" })
public enum ButtonVariant {
    LUMO_SMALL("small"), LUMO_LARGE("large"), LUMO_TERTIARY(
            "tertiary"), LUMO_TERTIARY_INLINE("tertiary-inline"), LUMO_PRIMARY(
                    "primary"), LUMO_SUCCESS("success"), LUMO_ERROR(
                            "error"), LUMO_CONTRAST("contrast"), LUMO_ICON(
                                    "icon"), MATERIAL_CONTAINED(
                                            "contained"), MATERIAL_OUTLINED(
                                                    "outlined");

    private final String variant;

    ButtonVariant(String variant) {
        this.variant = variant;
    }

    /**
     * Gets the variant name.
     *
     * @return variant name
     */
    public String getVariantName() {
        return variant;
    }
}
```

`toString`  is not overriden and it returns the same as `name()`  which is just enum name (uppercase normally).
It's convenient to override `toString()` and return `getVariantName()`.

**Comment by denis-anisimov** [comment]
`name()`  should not be overriden. It always allows to show an enumeration name.

I don't really care about the name of enumeration. It can be any name. The important thing in this case is what the string it's based on. The application logic is made based on this string value not enumeration name.
So I would like to see meaningful name in `toString`. There is always `name()` if I need the enumeration name.

**Comment by Legioth** [comment]
So what is the use case? In which kind of situation would `toString()` be used at all, and why would e.g. `icon` be more useful than `LUMO_ICON` in that situation?

**Comment by denis-anisimov** [comment]
`getVariantName()` is something that I need to learn when I use `ButtonVariant` enum.
Which means I need to go to this class and find this method.
`toString()` always exists. I want to use `toString()` instead of `getVariantName()`.
That's the usecase.

**Comment by Legioth** [comment]
Basic use case in application code is `myButton.addThemeVariants(ButtonVariant.LUMO_PRIMARY);`. No need for the application developer to learn about `getVariantName()` there.

**Comment by denis-anisimov** [comment]
Such need exists in unit tests. Writing them using `toString()` much faster than learning tricky method names.
