### ISSUE TITLE
AbstractAppRouterLayout and @HtmlImport

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4843]
### Description
It seems like the `@HtmlImport` annotation is ignored for `AbstractAppRouterLayout` subclasses. I tried to load custom styles as usual by adding the annotation, but the import is not added to the dom. When using a plain router layout, everything works as expected.

### Sources
``` 
@HtmlImport("frontend://styles/styles.html")
public class ApplicationRouterLayout extends AbstractAppRouterLayout {
   ...
}
```

```
@HtmlImport("frontend://styles/styles.html")
public class PlainRouterLayout extends VerticalLayout implements RouterLayout {
   ...
}
```

```
<link rel="import" href="../bower_components/polymer/lib/elements/custom-style.html">

<custom-style>
    <style>
        html {
            --lumo-primary-color: red !important;
        }
    </style>
</custom-style>
```

### Workaround
The html import can be set by using an attachListener for the appLayout instance in the configuration methd.

```
public class MainLayout extends AbstractAppRouterLayout {
    @Override
    protected void configure(AppLayout appLayout, AppLayoutMenu menu) {
        appLayout.addAttachListener(event -> {
            event.getUI().getPage().addHtmlImport("frontend://styles/styles.html");
        });
        ...
    }
    ...
}


```

**Comment by denis-anisimov** [comment]
What is ` AbstractAppRouterLayout` ?
Flow doesn't have such class. 
Do you use a wrong project for the issue ?

**Comment by stefanuebe** [comment]
Full class name is com.vaadin.flow.component.applayout.AbstractAppRouterLayout (implements RouterLayout). It is used in the Bakery Starter.

**Comment by denis-anisimov** [comment]
> It is used in the Bakery Starter.

Very good.
Then this should go to the bakery stater.

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/bakery-app-starter-flow-spring #718](https://github.com/vaadin/bakery-app-starter-flow-spring/issues/718) via [**ZenHub**](https://www.zenhub.com/)
