### ISSUE TITLE
OSGi : themes support

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4847]
Themes are defined in the separate bundles.

I see at least one problem at the moment: we have autodetection for `Lumo`  via `Class.forName`.
I expect that this doesn't work in OSGi at all.

Another issue is : we are instantiating theme classes using reflection. This also may be broken in OSGi (though I'm not sure since the class is exported properly). May be this is not an issue and it works as expected.

We need tests for `Lumo` and `Material` themes for OSGi ( at the moment we have no any tests at all for those themes).
We have only generic theme functionality tests and they are in the separate test module which is not executed in OSGi tests.

**Comment by pleku** [comment]
As a workaround, the `@Theme(Lumo.class)` can be used.
