### ISSUE TITLE
Manipulate localStorage

### ISSUE THREAD

**Issue by KrifaYounes** [vaadin/flow#4852]
It's possible to manipulate the localStorage with vaadin-11 in Java ? 
Thanks

**Comment by denis-anisimov** [comment]
Is it a question ?

This is an issue tracker. Please make only tickets here.
There is a forum for questions https://vaadin.com/forum/.

There is no server side Java API for local storage.
But you may call JavaScript on the client side to deal with it directly.

**Comment by KrifaYounes** [comment]
ok thanks yes I did it with javascript
