### ISSUE TITLE
I want to add a listener for changes in RouteRegistries

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#4854]
As a developer to handle a dynamic menu I want to be able to add a listener
that is invoked for any additions or removals of routes to/from any RouteRegistry.

I would expect to get the information which registry had a change and what 
routes were removed/added

**Comment by pleku** [comment]
For dynamic case, you are probably interested in any additions/removals that apply for the _current_ session (or UI if that is ever implemented). So the question is that should the registration be done both global and session level or should you just be able to do it in session level and get events for global changes too ?

**Comment by caalador** [comment]
I might well be interested in changes for the global scope also.
Thats why the event.getSource should return the RouteRegistry for which the change was, so right now either application or session registry.
