### ISSUE TITLE
Lumo dark variant is not applied for 404

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/flow#4855]
I have 
`CustomRouteNotFoundError extends RouteNotFoundError` 
with parent layout, which has
`@Theme(value = Lumo.class, variant = Lumo.DARK)`

Non existing page has Lumo light, but all the other pages with the same parent layout are dark

NOTE:
If I would have a view which accepts root route with parameter (for example `HasUrlParameter<Long>`, not necessarily string), then dark variant is applied.

I'm using vaadin12

**Comment by caalador** [comment]
Coul not reproduce anymore with 14.1.20 Dark theme was applied for error view.
