### ISSUE TITLE
Prove (and make some DX test as a result) dynamic route registration in our tests

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4858]
Our tests use static `@Route` annotations with ugly fragile hardcoded class FQN route path.

Remove all `@Route`  annotations and register routes programmatically instead in the application scope using classes FQNs.

This will prove dynamic routes registration and allow to DX test it as a result.
Make a ticket if you find any usability issue with this .

**Comment by pleku** [comment]
I think it is two different things to do a good DX test for the dynamic routing, than to change how our internal tests are routed.

**Comment by denis-anisimov** [comment]
Good DX tests can be a separate issue.
Initially our test have been done without `Route`  annotation.
Then we had to use `@Route` because there was no other good way.
Now we should change  it back using dynamic routes. It will immediately shows basic mistakes in design/implementation.
This is quite good way to smoke test this impl.

Proper DX testing is out of scope of this issue.
