### ISSUE TITLE
Custom SpringServlet throws exception during start

### ISSUE THREAD

**Issue by msoltes** [vaadin/flow#4859]
**- Description of the bug**
Spring boot app with custom SpringServlet throws an exception during server startup.
Problem occurs only with Vaadin version 12.0.0 and works with version 11.0.4.

**- Minimal reproducible example**
1) Using @ServletComponentScan annotation on main class of Spring boot. 
2) Create Custom servlet:

> @WebServlet(urlPatterns = "/*", name = "customVaadinServlet", asyncSupported = true)
> @VaadinServletConfiguration(productionMode = false)
> public class CustomServlet extends SpringServlet implements SessionInitListener, SessionDestroyListener {
> 
>     /**
>      * VAADIN 12.0.0 - exception
>      */
>     public CustomServlet(ApplicationContext context, boolean forwardingEnforced) {
>         super(context, forwardingEnforced);
>     }
> 
>     /**
>      * VAADIN 11.0.4 - works fine.
>      */
>     /*public CustomServlet(ApplicationContext context) {
>         super(context);
>     }*/
> }
> 

**- Expected behavior**
No exception and server started as in Vaadin version 11.0.4

**- Actual behavior**
Exception thrown:

> Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name '(inner bean)#6c74e8f6' defined in file [/Users/xxx/development/private/vaadin/websocket/target/classes/com/xxx/example/websocket/utils/CustomServlet.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'boolean' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
> 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
> 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
> 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:312) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
> 	... 58 common frames omitted
> Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'boolean' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1644) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1203) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1164) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
> 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
> 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
> 	... 64 common frames omitted

- Versions:
    - Vaadin / Flow version - 12.0.0
    - Java version - 8
    - OS version - Mac os x Sierra

**Comment by denis-anisimov** [comment]
Hi, I don't see this as a bug.

`11.0` version has one argument  `SpringServlet` CTOR:  `public SpringServlet(ApplicationContext context)`.

When you override it as is the application context may be autoinjected.
That's why everything works fine.

`SpringServlet` in `12.0` has two arguments CTOR. And your custom servlet just makes the same CTOR without any changes.
The second argument is  `boolean` and can't be injected. This is what the exception about.

So if I want to override the servlet in this way that you should care about the autowired parameters by yourself.

The second parameter says whether the servlet is mapped to the root or not. Since in your case the mapping is `"/*"` you should just pass `true` .
So just make one argument CTOR which calls super with the `true`  as the second argument.
