### ISSUE TITLE
Expose browser screen DPI/pixel ratio to server

### ISSUE THREAD

**Issue by piemmm** [vaadin/flow#4864]
Hi! It would be very useful to have access to the screen DPI(or pixel ratio) when dealing with screen size

There's an api for it: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

This is useful when you are dealing with retina or other special high-dpi displays

**Comment by pleku** [comment]
Related to https://github.com/vaadin/flow/issues/4320

**Comment by pleku** [comment]
This could be now added using the `ExtendedClientDetailsReceiver receiver)` similarly as other data added in #5564

**Comment by pleku** [comment]
Closed by #5900
