### ISSUE TITLE
Import shared between theme and regular component is loaded twice

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#4872]
If any `@HtmlImport` defined for the used `AbstractTheme` is also directly or indirectly imported from some other part of the application (e.g. a custom style module that explicitly imports `vaadin-lumo-styles/sizing.html`), then there will be two `<link rel="import">` elements for that file in the generated bootstrap html.

Can be reproduced e.g. by adding `@HtmlImport("bower_components/vaadin-lumo-styles/sizing.html")` to `MainView` in the skeleton starter.

**Comment by denis-anisimov** [comment]
I guess that doesn't break anything ?
So it's just some improvement/enhancement rather than a bug ?

**Comment by Legioth** [comment]
I'm not aware of anything being directly broken by this. It just looks weird, makes the response body bigger than necessary and might make debugging slightly more difficult in some special cases.

**Comment by denis-anisimov** [comment]
OK, I make it an enhancement then.

**Comment by Legioth** [comment]
This might in some cases cause surprises because the relative ordering between theme imports and other imports might vary depending on whether the "extra" import is included or not.

**Comment by pleku** [comment]
I expect this has been already fixed for npm mode at least.
