### ISSUE TITLE
Run DX test based on keyboard shortcut tutorials

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4874]
Based on API draft in #4870 and vaadin/flow-and-components-documentation#366

**Comment by ujoni** [comment]
The current newest test plan is here:
[DX test plan](https://docs.google.com/document/d/1Av7Ty460m6fohzKQzzzUG6Ak6NTCjDt6OSAaIyPJqG0/edit#)

The results (incomplete) are here:
[DX test results](https://docs.google.com/document/d/1gtpAqwYIW7vb1CaV6Z-0dFYTu1AgjcrpeNVwjka33nM/edit#)
