### ISSUE TITLE
Navigation state renderer should resolve dynamic routes

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#4883]
At the `getNavigationEvent` uses the static method `Router.resolve` which requires a navigation target class with an `@Route` annotation.

This should be changed so that the url is gotten from the registry using `getTargetUrl(Class<? extends Component>)`.

**Comment by denis-anisimov** [comment]
Looks like this is a duplicate of already fixed ticket: there is no `getNavigationEvent` in the `NavigationStateRenderer` class and `Router::resolve`  is deprecated and not used anymore from anywhere.
