### ISSUE TITLE
flow-maven-plugin might not work with new Node versions

### ISSUE THREAD

**Issue by DiegoSanzVi** [vaadin/flow#4888]
There was a support ticket, in which there was an error when he tried to deploy the application with the Maven profile `productionMode`.

He was behind a corporate firewall/proxy.

His configuration was correct, using `<autodetectTools>true</autodetectTools>` and `<ignoreMavenProxies>false<ignoreMavenProxies>` . He also defined the proxy configuration in the `settings.xml` file of maven and in the `.yarnrc` and `.npmrc` files.

According to him, the nodejs-Version was the problem: 

**"I found out, that the nodejs-Version was the problem. I used nodejs-11 and had all the problems. Now I switched back to nodejs-8.11.1 and all the problems vanished."**

It would be nice to check this, or at least save this issue as a reference just if this happens again in the future.

**Comment by web-padawan** [comment]
Refer to the [Node support](https://polymer-library.polymer-project.org/3.0/docs/tools/node-support) document. In short: LTD versions are supported, currently 8.x and 10.x. Node version 11 is not LTS, and is not guaranteed to work

**Comment by igormilina** [comment]
I'm having similar problem with vaadin-maven-plugin, but I'm not sure if it is related to this issue. Bundling for production with node 8.9.0 x64 on windows works without errors (also behind a corporate proxy), but using LTS version 10.15.2 gives "ReferenceError: internalBinding is not defined" error. Full log is attached. Plugin is configured like so:
`	<plugin>
		<groupId>com.vaadin</groupId>
		<artifactId>vaadin-maven-plugin</artifactId>
		<version>12.0.7</version>
		<configuration>
			<nodePath>c:/Program Files/nodejs/node-10.15.2/node.exe</nodePath>
			<autodetectTools>true</autodetectTools>
			<ignoreMavenProxies>false</ignoreMavenProxies>
		</configuration>
		...
`
[errorlog.txt](https://github.com/vaadin/flow/files/2929744/errorlog.txt)
