### ISSUE TITLE
Refactor RouteUtil methods

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#4892]
`RouteUtil` contains methods for handling route annotations.

These should be gone through and moved/made protected/private.

Some methods that do not handle annotations and are used from the `AbstractNavigationStateRenderer` should be moved away.

**Comment by pleku** [comment]
All the existing public methods should be marked as deprecated and to be removed in V15.

**Comment by caalador** [comment]
To get the actual parent layouts you should use `RouteRegistry:getRouteLayouts` as that will contain the actual registration for the route.

Also the correct registry to use would be `ui.getRouter().getRegistry()`
