### ISSUE TITLE
Transparent Notification Theme

### ISSUE THREAD

**Issue by appreciated** [vaadin/flow#4913]
#### Description
Can we have a Notification Theme (or something similar), that is simply transparent and has no margin/padding/box-shadow.
This would make it super convenient to show custom styled Components as a Notification.

#### Code example
```
HorizontalLayout hl = new HorizontalLayout(new Label("My custom Notification"));
Notification notification = new Notification(hl);
notification.setDuration(-1);
notification.setPosition(Notification.Position.BOTTOM_END);
notification.getElement().getStyle().set("background", "red");
notification.setOpened(true);
```
#### Current behavior
The red background will always be shown inside the Notification Card. 

#### Desired usage
```
...
notification.setTheme(Notification.THEME_TRANSPARENT)
...
```
The component should then be shown on the UI without any additional styles.

**Comment by web-padawan** [comment]
This issue was moved to vaadin/vaadin-notification#98
