### ISSUE TITLE
Add ClickLIstener support to Image

### ISSUE THREAD

**Issue by dve** [vaadin/flow#4915]
Nearly all flow-html-components support adding ClickListers, but not the `Image` one. Clicking on an image for e.g. showing it in a bigger size is a common use case - so it should be added.

**Comment by Legioth** [comment]
This can be worked around by creating an empty class like `public class ClickableImage extends Image implements ClickNotifier<ClickableImage> {}`. Optionally, delegates for any used constructors can also be added to the class.

**Comment by pleku** [comment]
Should be fairly easy to do by adding the `implements ClickNotifier` which should be all that is needed - I'm not sure if even automated UI test would be required as there is none for the other components.

**Comment by dve** [comment]
@Legioth thanks for the quick hit - I've done that. But it would be nicer to have this in the core
