### ISSUE TITLE
Create WebComponent handlers

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#4918]
Create request handlers for handling WebComponent requests.

- WebComponentBootstrapHandler
- WebComponentElementProvider

No handler should be registered on Service init if no WebComponents exist in registry.

Initialisation of WebComponetUI should be made so that there is only one instance created for a view containing WebComponents. In the prototype this was done with
`<link rel="import" href="sswcui.html">` that works as the browser will only request the first instance, but will fail after moving to polymer3 and JS modules

**Comment by Legioth** [comment]
> Initialisation of WebComponetUI should be made so that there is only one instance created for a session.

How would that work if the user has multiple browser tabs open?

**Comment by caalador** [comment]
Updated to for a view as it should be per view not per webcomponent.
