### ISSUE TITLE
Create a WebComponent html generator

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#4920]
Generator should be able to create the WebComponent html that is served to the client by `WebComponentElementProvider`.

- needs to support on the fly generation and to file for bundling
- properties are generated from `@WebComponentProperty` annotated Fields and Methods
- attribute data on the element should be synced to the server.
- Element ID needs to be stored on the client side UI element so that Flow finds it

**Comment by Legioth** [comment]
At what point would that HTML be generated? I just realized that the HTML needs to be transpiled for it to work with IE11 since it uses ES6 classes.

**Comment by caalador** [comment]
At before transpilation in the maven plugin.
