### ISSUE TITLE
FormLayout width depends on the number of rows it contains; goes to 100% with 3 or more rows

### ISSUE THREAD

**Issue by sergetania** [vaadin/flow#4924]
This issue prevents the FormLayout to have undefined width. When the width of the layout is not defined, it correctly fits the content with a single row of fields it contains. Adding another rows increases the width of the layout and the third row always makes the layout extend to 100%. You can see this behavior in the series of attached snapshots. It is easily reproduced with the code below, please comment out fields to see how it changes the width of the layout.

`public class FormTestView extends VerticalLayout {

	public FormTestView() {

		addFormLayout();
	}

	private void addFormLayout() {

		FormLayout form = new FormLayout();
		add( form );
		TextField firstName = new TextField();
		form.addFormItem( firstName, "First Name" );
		TextField lastName = new TextField();
		form.addFormItem( lastName, "Last Name" );
		TextField email = new TextField();
		form.addFormItem( email, "Email" );
		firstName = new TextField();
		form.addFormItem( firstName, "First Name 2" );
		lastName = new TextField();
		form.addFormItem( lastName, "Last Name 2" );
		email = new TextField();
		form.addFormItem( email, "Email 2" );
	}
}
`

Versions:
    - Vaadin / Flow - 12.0.3
    - Java version - 1.8.0_172
    - OS version - Windows 10 Pro
    - Chrome -  71.0.3578.98 (Official Build) (64-bit)

![1row](https://user-images.githubusercontent.com/6865214/50700591-ee03d980-1018-11e9-862b-3d6b9e49dd2f.PNG)
![2rows](https://user-images.githubusercontent.com/6865214/50700595-f0663380-1018-11e9-9252-db3703dabee0.PNG)
![3rows](https://user-images.githubusercontent.com/6865214/50700604-f4925100-1018-11e9-9c56-1075cf47e914.PNG)

**Comment by denis-anisimov** [comment]
This is the pure client side issue.
I've created a ticket for it in `form-layout` repo : https://github.com/vaadin/vaadin-form-layout/issues/103

**Comment by sergetania** [comment]
Do we now have to wait for the new issue to be picked up all over again? That sucks!

**Comment by denis-anisimov** [comment]
>That sucks!

That's true.

I will try to enforce work on it. Though this is another team.

**Comment by sergetania** [comment]
Thanks, Denis! Appreciate the help!

**Comment by sergetania** [comment]
Denis, I can't prioritize this new issue because I can't select the Vaadin Form Layout repository on the warranty page. Any ideas what to do? Thanks!

**Comment by denis-anisimov** [comment]
@pleku has notified our support that this is such issue.
I hope it will be fixed soon.
I've also notified components team about the client side ticket https://github.com/vaadin/vaadin-form-layout/issues/103
I hope it also will be taken soon.

**Comment by sergetania** [comment]
Thank you!
