### ISSUE TITLE
WebBrowser.getTimezoneOffset() always returns 0

### ISSUE THREAD

**Issue by jennybou** [vaadin/flow#4941]
Version 12.0.0

WebBrowser.getTimezoneOffset() always returns 0.  The timezoneId is null also.

I checked using JavaScript that the browser (Chrome) is providing the offset so it seems to be a Vaadin bug.

**Comment by bogdanudrescu** [comment]
I could reproduce that request parameters `v-sw`, `v-tzo`, `v-tzid` which are required to set the timezone on server are missing from the HttpServletRequest.

**Comment by Legioth** [comment]
Duplicate of #3657
