### ISSUE TITLE
Blank screen and JavaScript syntax errors in IE11

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow#4944]
_From @evmatt on January 9, 2019 12:49_

When running a Vaadin application in IE11 the user sees only a blank white screen. The issue only occurs when using the Material theme and does not occur with the Lumo theme. The issue does not occur in browsers other than IE11.

In the IE11 console, 3 errors are seen. All are `SCRIPT5022: SyntaxError` originating in the file style-properties.js at line 30,3. Below is the context, lines 26 to 31.
```
const matchesSelector = function(selector) {
  const method = this.matches || this.matchesSelector ||
    this.mozMatchesSelector || this.msMatchesSelector ||
    this.oMatchesSelector || this.webkitMatchesSelector;
  return method && method.call(this, selector);
};
```

_Copied from original issue: vaadin/vaadin-material-styles#83_

**Comment by web-padawan** [comment]
There should not be `const` in the resulting output, so it looks like at least some code is not transpiled to ES5. Are you running the Vaadin application in production mode?

**Comment by web-padawan** [comment]
_From @evmatt on January 9, 2019 13:7_

The Vaadin application is being run in production mode, and the Vaadin version being used is 12.0.0. Other files do appear to be transpiled to ES5 as style-properties.js is the only source file causing problems. `const` appears throughout the whole of style-properties.js so it appears that the whole file is missed during transpilation.

**Comment by web-padawan** [comment]
Moved the issue here, as I assume it might be related to Flow rather than Material theme itself.
Note: the `style-properties.js` mentioned above is from `shadycss`.

**Comment by pleku** [comment]
>Moved the issue here, as I assume it might be related to Flow rather than Material theme itself.
Note: the style-properties.js mentioned above is from shadycss.

IIRC some versions of shadycss have had some issues when running production mode as the code has not been transpiling properly for ES5.

I'm able to replicate the issue with using e.g. the bookstore starter V12 version and switching it to use `Material` theme. Flow is not bringing in `shadycss` nor is `vaadin-material theme` Flow integration.

The version for `shadycss` is declared here https://github.com/vaadin/platform/blob/12.0/versions.json#L17 so should I move this issue to vaadin/platform instead ?

**Comment by web-padawan** [comment]
The following versions of `shadycss` webjar are based on Bower again:
https://dl.bintray.com/webjars/maven/org/webjars/bowergithub/webcomponents/shadycss/1.8.0/
https://dl.bintray.com/webjars/maven/org/webjars/bowergithub/webcomponents/shadycss/1.7.1/
so we might want to update platform accordingly

the previous one is broken: https://dl.bintray.com/webjars/maven/org/webjars/bowergithub/webcomponents/shadycss/1.5.2/
