### ISSUE TITLE
Add shorthand for creating an Input component with a specific type

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#495]
`new Div("password"`) would be confusing because most other component constructors taking a 
String parameter use the value as text content.

**Comment by mshabarov** [comment]
In flow-components we have currently a few input components. It's not clear what is the intention of this issue.

**Comment by Legioth** [comment]
The idea would be to make it easier to create an `Input` instance that corresponds to e.g. `<input type=password>` instead of 
```
Input myInput = new Input();
myInput.setType("password");
```

(I updated the description to fix a typo that made it difficult to understand (`Div` -> `Input`))
