### ISSUE TITLE
beforeLeave(BeforeLeaveEvent event) called twice 

### ISSUE THREAD

**Issue by masbaehr** [vaadin/flow#4958]
Hi, i noticed this behaviour BeforeLeaveObserver is called twice when navigating away to a different route

Version used:
compile group: 'com.vaadin', name: 'vaadin', version: '12.0.3'
 
Can be easily reproduced with this code:

```java

import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.router.BeforeLeaveEvent;
import com.vaadin.flow.router.BeforeLeaveObserver;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.spring.annotation.UIScope;


@Route("test")
@UIScope
public class TestView extends Div implements BeforeLeaveObserver {
	 
	@Override
    public void beforeLeave(BeforeLeaveEvent event) {
		System.out.println("beforeLeave");   
    }
    
	public TestView(){
        Button btn = new Button("navigate");
        btn.addClickListener(listener -> {
            UI.getCurrent().navigate("");
        });
        add(btn);
        System.out.println("TestView");	
	}

}

```
Console: output
```
TestView
beforeLeave
beforeLeave
```
This might help to find the cause: 

![image](https://user-images.githubusercontent.com/38694044/51185427-626f3000-18d7-11e9-9bf0-36d10b1fee7f.png)

**Comment by caalador** [comment]
In the second stack you have a `reroute` which will create new events as everything will be run  again as the stacks change.

At least with just the sample I'm not receiving duplicate events for a Spring application, there must be something else that you have that runs the reroute.

**Comment by masbaehr** [comment]
Sorry yeah.. you are probably right the navigation target has a re-route but still i don't get why beforeLeave is called twice, as it already has "left"? 

```java
@Route("test")
@UIScope
public class TestView extends Div implements BeforeLeaveObserver {
	 
	@Override
    public void beforeLeave(BeforeLeaveEvent event) {
		System.out.println("beforeLeave TestView");   
    }
    
	public TestView(){
        Button btn = new Button("to -> test2");
        btn.addClickListener(listener -> {
            UI.getCurrent().navigate("test2");
        });
        add(btn);
        System.out.println("TestView");	
	}

}
//------------
@Route("test2")
@UIScope
public class TestView2 extends Div implements BeforeEnterObserver  {
    
    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        System.out.println("beforeEnter TestView2");
        boolean loggedIn = false;
		if(!loggedIn){
            event.rerouteTo("test");
        }
  	}
    
      
	public TestView2(){
        Button btn = new Button("to -> test");
        btn.addClickListener(listener -> {
            UI.getCurrent().navigate("test");
        });
        add(btn);
        System.out.println("TestView2");	
	}

}
```

**Comment by caalador** [comment]
In this case we are leaving and the second view we are comming to says BeforeEnter that we want to go to another view. So in this case we have not left yet and the first BeforeLeave handler gets a new event with new data.

This is as expected as perhaps the first navigation to "test2" is ok but the redirected "test" is not ok and Test can no handle this new navigation differently.

**Comment by pleku** [comment]
If I understood correctly, this works as designed. Please comment here or create a new issue if not so.
