### ISSUE TITLE
Flow OSGi bundle will not run in OSGi enRoute Environment

### ISSUE THREAD

**Issue by QNENet** [vaadin/flow#4968]
Refer to comment in #4853

**Comment by QNENet** [comment]
#5017 is relevant
We would love to be able to use Vaadin 10+ in a general OSGi environment soon

**Comment by denis-anisimov** [comment]
Please provide the steps to reproduce.
I can't see any properly reported issue in this ticket.

**Comment by QNENet** [comment]
The comment I made  re #4853 is relevant but as Vaadin has moved on to use bnd in the OSGi base starter the issue no longer needs investigation.
