### ISSUE TITLE
Shortcuts: Add the ability to create focus and click shortcuts with a custom owner

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#4973]
The current shortcut API does not allow the developer to define the `owner` of a _click_ or _focus_ shortcuts. These shortcuts are always owned by the `UI` instance. 

Having the ability to define the owner of these shortcuts would allow the developer to define the _active scope_ of the shortcut. 

For example, the developer might want to add `Enter` as the click shortcut for a button, and the same key for another button which is located deeper (or adjacent) on the DOM tree. Since the developer does not have the ability to change the owner, both buttons will be triggered every time the user hits `Enter`.

**Comment by pleku** [comment]
### Acceptance Criteria
- Add overrides to `Focusable` interface which take in the "owner" component, which is the component to register the shortcut listener on
- Add a note to the shortcuts tutorial about being able to customize the owner to something else than the `UI` using these methods
