### ISSUE TITLE
No exception or warning when setting a disallowed Style

### ISSUE THREAD

**Issue by appreciated** [vaadin/flow#4975]
When setting a value for a css property flow will not inform the user that the style wasn't passed to the Client. 
```
Div div = new Div();
div.getStyle()
        .set("display", "-ms-grid");
add(div);
```
If the value could not be set, for any reason, let the user know. 
Maybe by a Warning, Exception or a Runtime Exception?

**Comment by appreciated** [comment]
Probably related to #4976

**Comment by Legioth** [comment]
I don't think there's very much we can do about this based on my observation that it's the browser that silently ignores the value. This means that the only thing we could do would be to add client-side logic that reads back the value after assigning something, and then logging a warning in the client-side console if the value has changed. The server cannot up-front know which values any specific browser will accept, so there's no good chance of throwing an exception on the Java side.

**Comment by pleku** [comment]
While it would be great to have something for this, I think the only thing that people would notice is the error on server side and that would require validating the set css on the server side, and I just don't see us doing this.

It would be great to have better support for this, but I don't see it ever being a big enough priority for us to do it. So thanks for the issue, but I'm closing this one as won't fix.
