### ISSUE TITLE
Basic Theme handling for Embedded Flow

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#4984]
Investigate how Theme should/can be handled for SSWC? 

ApplicationConstant to be read from the DeploymentConfiguration as annotation based initialization is not functional?

Requirements
- All served WebComponents should have the same theme for the UI
- For Vaadin components used in a WebComponent some theme needs to always be used. (non themed components are not usable as is in many cases)

**Comment by caalador** [comment]
On the `the app/page it is embedded into might be using either of those.` there is the part where we support having server-side vaadin components that are served with the component.
So if the other side hasn't taken into account that you use vaadin-button and imported a theme for that then we would serve the base which has no theme and looks like... well.

Note that this ticket is for the pre Polymer3 version that uses html imports.

**Comment by pleku** [comment]
The initial version can support just one theme that should be defined for the SSWC(s) in the project.

We can later on look at thing like trying to figure out what should be used, or if there should be away to request the SSWC with certain theme, like `.../my-sswc.html?theme=material`

**Comment by Legioth** [comment]
One additional complication is that SSWC needs to have access to the bundle map of the hosting page. Otherwise, it cannot know how to rewrite imports to use the production bundle used by the hosting page.

**Comment by pleku** [comment]
>One additional complication is that SSWC needs to have access to the bundle map of the hosting page. Otherwise, it cannot know how to rewrite imports to use the production bundle used by the hosting page.

I'm not sure if I understand this correctly, but still I'm going to ask _why would we need this_ ?
I think anyone using a Flow web component (see what I did there) could simply just choose to have its own bundle or have the contents as part of the hosting page bundle.

**Comment by Legioth** [comment]
I guess my concerns are actually more related to https://github.com/vaadin/flow/issues/5008 than to theme handling.

**Comment by pleku** [comment]
To recap, the open question is that _how can I define my app to use Material or no theme_. By default, Lumo is used now if it is available.

So for this issue, we'll just look at reading the theme annotation and using that like it should be used for modifying the imports.

**Comment by pleku** [comment]
Implementation details:
- WebComponentBootstrapHandler creates a WebComponentUI
- WebComponentUI currently uses Lumo if it available
- it should scan the actual web component class for theme annotation, or then use lumo if available
