### ISSUE TITLE
Add Dependency annotation or Dependency.Type.META for dynamically adding Meta tags to page HTML

### ISSUE THREAD

**Issue by StevenBerdak** [vaadin/flow#4994]
Currently I am having trouble finding a solution to load meta tags dynamically to facilitate image meta data for Facebook share of a page's content. This would be very helpful to have.

**Comment by Legioth** [comment]
This seems to be a duplicate of https://github.com/vaadin/flow/issues/4912.

Depending on circumstances, the workaround suggested in https://github.com/vaadin/flow/issues/4912#issuecomment-451391725 might help in this case.
