### ISSUE TITLE
Combobox in Dialog breaks focus handling

### ISSUE THREAD

**Issue by dogInTheWok** [vaadin/flow#4995]
When opening a dialog with comboboxes, confirming them via Return-Key messes up focus handling. The dialog does not respond and one can close it only by pressing Tab key until "Close"-Button (cross in upper right corner) is in focus and confirming with Return. Closing via ESC-Button does not work.

Here is an example for reproduction:

    Button openDialog = new Button("Open Dialog");
    openDialog.addClickListener(e->{
      Dialog dialog = new Dialog("test dialog");
      dialog.setCloseOnEsc(true);
      ComboBox box2 = new ComboBox("Box0", 1,2,3);
      ComboBox box3 = new ComboBox("Box1", 1,2,3);
      dialog.add(box2, box3);
      dialog.open();
    });

Steps for reproduction:
- open dialog
- focus combobox
- type "2"
- confirm via enter key
- use mouse to focus other combobox
- use mouse to select e.g. "1"
- click alternating in first and second combobox via mouse. After ~4 times, the dialog and its components have lost focus and do not respond to mouse or keyboard input anymore 

Version: Vaadin Flow 12
OS: Ubuntu 18.04
Java 8
Browser: Firefox as well as Chromium in various versions (e.g. Firefox 63)

**Comment by TatuLund** [comment]
Is this same issue as https://github.com/vaadin/vaadin-combo-box-flow/issues/139 ?

**Comment by OlliTietavainenVaadin** [comment]
Reproduces in Chrome 71 on Windows. Fixed here? https://github.com/vaadin/vaadin-overlay/pull/138

**Comment by web-padawan** [comment]
The related issue vaadin/vaadin-dialog#123 has been fixed by vaadin/vaadin-overlay#137 and there has been few more fixes in overlay, included to V12 and V13 platform releases. 

I'm closing this issue as fixed. Please add your comments if you are still able to reproduce it.
