### ISSUE TITLE
ComponentEventBus.fireEvent() relies on event class which doesn't have to be registered event type

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#500]
ComponentEventBus.addListener() accepts Class<T> as an event type and listener for this event type.

But Class<T> parameter may be a superclass for the events. So any subclass should be accepted in fireEvent() method as suitable event to notify registered listeners via above addListener() method.

But it's not true: fireEvent() calls event.getClass() for its argument and tries to find listeners for this type only. So if event is subclass then event won't be fired.

**Comment by pleku** [comment]
Due to low demand of this feature / refactoring, 

No.
