### ISSUE TITLE
Make it possible to give UI element id through the initial request

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#5007]
To set the `WebComponentUI` element to a specific element it should be made possible to give the element id through the initial component request.

By default it is the `<body>`. The `WebComponentUI` provides the connection for the server for the Flow client engine.

**Comment by pleku** [comment]
Decided that we don't need this for now - this would be required if for some reason you have multiple sources of Embedded Flow applications, which means that you need to have separate places for the server callbacks.

**Comment by pleku** [comment]
I think this is either done or not needed anymore.
