### ISSUE TITLE
Client-side should be informed of server url for WebComponents

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#5027]
When requesting for `/web-component/web-component-ui.html` the `WebComponentBootstrap` handler should send to the client the actual  service url so the client can set the correct service url instead of the default `conf.setServiceUrl(WidgetUtil.getAbsoluteUrl("."));` in `com.vaadin.client.bootstrap.Bootstrapper`.

This is due to the fact that the server will probably not match the '.' path but be on another path all together.

**Comment by pleku** [comment]
The server serving the web component can be anywhere, even in another server.
