### ISSUE TITLE
Upload does not fire finished event on Vaadin 12.0.5

### ISSUE THREAD

**Issue by pbaris** [vaadin/flow#5039]
I've created a simple view with an Upload component, but the finished event never fired. The rest of the events have been fired.

    @Route(value = "")
    public class Main extends VerticalLayout {

        public Main() {
            MultiFileMemoryBuffer buffer = new MultiFileMemoryBuffer();
            Upload upload = new Upload(buffer);
            upload.addFinishedListener(e -> System.out.println("Finished"));
            add(upload);
        }
    }

**Vaadin:** 12.0.5
**Java:** 1.8.0_201
**OS:** Ubuntu 18.04.1 LTS
**Browser:** Firefox Quantum 65.0, Google Chrome 72.0.3626.96

**Comment by ericmartinezr** [comment]
@pbaris this was fixed in https://github.com/vaadin/vaadin-upload-flow/pull/110 which was released with [12.0.6](https://github.com/vaadin/platform/releases/tag/12.0.6).
