### ISSUE TITLE
Enable running webpack statistics on startup/change

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#5043]
When starting the project we should run the statistics for the webpack setup to be able to get the templates for `@Id` usage in `DefaultTemplateParser`.

The statistics json file should be available for flow-server when running the application.

**Comment by Legioth** [comment]
Isn't this only needed for production builds?

**Comment by caalador** [comment]
Could be, but so far I've not gotten the webpack dev server to serve raw js files.
