### ISSUE TITLE
Create and add the request handler proxy

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#5046]
When running in development mode we should ask for the files from the 
webpack-dev-server and this should be made by adding a `RequestHandler` to Flow
that redirects the file request to the dev-server.

This handler should only be added to handlers if we run in NPM mode and are in development mode.

- How do we know that the request is for the js import and should be handled by the dev-server?

**Comment by Legioth** [comment]
> How do we know that the request is for the js import and should be handled by the dev-server?

My guess is that we delegate if the file extension is `.js` and the file is not found from the servlet context.
