### ISSUE TITLE
DX testing Embedding Flow

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5048]
## Test environment:
- Project without Flow (target for exported components)
- Skeleton starter (where the exportable components are created)

## Tasks
1. embed Skeleton starter onto the target page
2. send a boolean value from the embedding app to the server, which changes the button's label
3. when the user clicks the button, expose the text field value to the embedding app

**Comment by ujoni** [comment]
DX test report:
https://docs.google.com/document/d/1FHewjChVYiOhm9riJJWnTDSl3t0tJMkxeCPTDG19uXM/edit
