### ISSUE TITLE
flow-component-renderer prevents content to take full size

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/flow#5056]
The issue was first noticed using `Notification` object, but it may affect other usages of `flow-component-renderer`.

If I have a `Notification` like:

```java
Notification notification = new Notification();
notification.setPosition(Notification.Position.TOP_STRETCH);

...

notification.open();
```

And add a `HorizontalLayout` as such:

```java
HorizonalLayout layout = new HorizontalLayout();
layout.setSizeFull();
layout.add(/* some content */);

notification.add(layout);
```

I expect that my `layout` to take the full available width of `notification`, but rather `flow-component-renderer` prevents it from doing so:

![screenshot 2019-02-13 at 13 19 29](https://user-images.githubusercontent.com/262432/52708112-0d840f80-2f92-11e9-8d36-da3a2848fe26.png)

I believe that `flow-component-renderer` should allow its children use the available space of its parent.

I was able to workaround this by adding a `custom-style` and targeting `flow-component-renderer` to use `width: 100%`.

Tested with platform `13.0.0.beta1`.

**Comment by pleku** [comment]
I think this is a fix that should be released at minimum in a minor release since it might change behavior for existing applications.
