### ISSUE TITLE
SSWC+Push : pushUrl should be derived from service URL

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5061]
If you use a `VaadinServlet` mapped to non-root URI then you have to specify `pushURL` parameter like it's done here in this integration test for web component & push:
https://github.com/vaadin/flow/pull/5059/files#diff-2e72470e10290e632f8d89fcbcf57fb1R25

This is far from obvious and I expect this should not be needed if you are using a normal Vaadin application (not embedded one) without SSWC.

Normally the `pushURL`  value is `""` end it's calculated based on the application URL.
When you embed a Vaadin application then the main application URL differs from the embedded Vaadin application URL.
And `pushURL` should be calculated based on `serviceURL`, not on the main application URL.

I see several places where `pushUrl`  is involved.
- First of all, by default, its value is `""` (in the `DefaultDeploymentConfiguration`)
- Then it's sent via `PushConfigurationMap`
- It's set in the `AtmospherePushConnection` CTOR.

In the latest case there is a code:

```
if (getPushConfiguration().getPushUrl() != null) {
    url = getPushConfiguration().getPushUrl();
} else {
    url = registry.getApplicationConfiguration().getServiceUrl();
}
```

But  `getPushConfiguration().getPushUrl()` is never `null` since it's set by default to an empty string.
As a result, the first branch is always used.

I'm not sure that `AtmospherePushConnection`  is the correct place to fix it.
The problem, in the end, is in the websocket URL which is `ws://%pushURL%/xxxx`.
I'm not sure how it's derived from the server side URL.
It might be also that the URL should be set on the server side in case of SSWC.

But I expect that `pushURL` should not be set at all since it will be even more complicated in case embedded Vaadin application is installed on the external URL (vs deploying embedded Vaadin application as a part of the main application via dedicated mapping).
This URL should be somehow derived from the embedded Vaadin application service URL.
This situation is quite similar to #5027 and  #5044.

**Comment by pleku** [comment]
"The service URL is already sent to the client side, and it could be used from there. But the push url should be calculated based on that and configured properly. You just need to find the correct place to fix it."

### Acceptance Criteria
The user should not have to know anything about push urls when using `@Push` and embedding the application as a web component. It should just work.
