### ISSUE TITLE
NPE in KeyUpEvent on 13.0.0.beta2

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#5092]
Just updated to 13.0.0.beta2 and a field which was working on beta1 started getting NPE in its key-up listener:

```
textField.addKeyUpListener(Key.ENTER, event -> { ... });
```

throws:

```
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221) ~[na:na]
	at com.vaadin.flow.component.Key.of(Key.java:2716) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.component.internal.KeyboardEvent.<init>(KeyboardEvent.java:84) ~[flow-server-1.4.0.jar:1.4.0]
	at com.vaadin.flow.component.KeyUpEvent.<init>(KeyUpEvent.java:73) ~[flow-server-1.4.0.jar:1.4.0]
	... 114 common frames omitted
```

Not sure what changed between beta1 and beta2 in this regard 😕

**Comment by heruan** [comment]
I've investigated on this a bit more and this is how to trigger it:

1. the field should have a slotted native input element, e.g.
```java
var field = new TextField();
var input = new Input().getElement();
input.setAttribute("slot", "input");
field.getElement().appendChild(input);
```
(this is to enable browser form managers)

2. let the browser save the input field once;

3. reload the page: the browser completes the fields, but if you focus one of them you get the exception!

See [KeyUpListenerError.java](https://github.com/heruan/vaadin-spring-demo/blob/cf21e01eb79054fa31dcc79d9995434b868787f1/src/main/java/to/lova/vaadin/spring/KeyUpListenerError.java) to replicate.

**Comment by heruan** [comment]
Any update on this?

**Comment by heruan** [comment]
Not sure what "top3" is, but I'm sure it's pretty nasty because it floods the log in production. Am I using the component wrong? The goal is to let the browser password manager work, and this is the only way I've found so far.

**Comment by heruan** [comment]
Still in latest 13 stable and 14 alpha. Any ETA?

**Comment by denis-anisimov** [comment]
>See KeyUpListenerError.java to replicate.

Can't use it since there are no steps to reproduce it with this code.

>let the browser save the input field once; 

how ?
The code contains two fields only : text field and password field.
No any action which I may use to save.

**Comment by heruan** [comment]
@denis-anisimov With "save" I mean the browser password manager which kicks in automatically: just type on both fields and press enter (if nothing happens, try adding a button).

**Comment by denis-anisimov** [comment]
Nothing happens with button, nothing happens without button.

**Comment by heruan** [comment]
Adding also

```java
textInput.setAttribute("autocomplete", "username");
passwordInput.setAttribute("autocomplete", "current-password");
```

finally triggers this (tested in two different machines). So the complete code to reproduce is:

```java
public class KeyUpListenerError extends VerticalLayout {

    public KeyUpListenerError() {
        var textField = new TextField();
        var textInput = new Input().getElement();
        textInput.setAttribute("slot", "input");
        textInput.setAttribute("autocomplete", "username");
        textField.getElement().appendChild(textInput);
        textField.addKeyUpListener(Key.ENTER,
                event -> Notification.show("Key.ENTER Pressed!"));

        var passwordField = new PasswordField();
        var passwordInput = new Input().getElement();
        passwordInput.setAttribute("slot", "input");
        passwordInput.setAttribute("autocomplete", "current-password");
        passwordField.getElement().appendChild(passwordInput);
        passwordField.addKeyUpListener(Key.ENTER,
                event -> Notification.show("Key.ENTER Pressed!"));

        this.add(textField, passwordField,
                new Button("Login", event -> Notification.show("Logged in!")));
    }

}
```

**Comment by denis-anisimov** [comment]
This code doesn't allow to reproduce this issue either.

May be it's because versions.

Could you please provide a project archive which I may use as is to reproduce ?

**Comment by peholmst** [comment]
I have not been able to reproduce this either. For the NPE to show up, the `key` should be missing from the key-up event. What browser and version are you using?

**Comment by heruan** [comment]
With the project at https://github.com/heruan/vaadin-spring-demo I can reproduce the issue with the latest Chrome and Vaadin 14 RC1. It happens when the browser autofills the fields, is that happening on your side? It could be that the browser has no saved values for `localhost:8080`? I'm not sure how you can trigger the browser to save the field values, but the exception happen when the fields are autofilled.

![keyup-listener-gifsicle](https://user-images.githubusercontent.com/851745/60190352-cad11e80-9832-11e9-87f5-c4c9dfc808ec.gif)

**Comment by peholmst** [comment]
Now I managed to reproduce it. I first tried out your code in a separate non-Spring project and ran it using Jetty and then everything worked. When I ran the project through Spring, the exception occurred. I will now start to investigate further what could be causing this.

**Comment by peholmst** [comment]
Actually, the exception occurs in non-Spring projects as well. It just isn't logged anywhere so you can't tell unless you happen to have a breakpoint in the right spot. The client is sending an empty `keyup` event to the server, which then causes the exception.
