### ISSUE TITLE
Checkbox component is shown in Grid column only during first visit to a page.

### ISSUE THREAD

**Issue by vlipovetskii** [vaadin/flow#5104]
Checkbox component is shown in Grid column only during first visit to a page.
addComponentColumn is leveraged to add Checkbox.
This bug is only in Google Chrome 72. 
There is no such a bug in Firefox, Edge, Google Chrome 71

**Comment by Legioth** [comment]
Duplicate of #5025.

The fix for this issue is included in Vaadin 10.0.11, 12.0.7 and 13.0.0.beta2.
