### ISSUE TITLE
Remove dynamic ES imports from Client and Bootstrap code.

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5119]
Imports are handled in the `main.js` which is read by webpack and produces an `index.js` bundled file.

We should not remove the `@JsModule` annotation that will be used in the future for updating the `main.js` in the maven plugin

**Comment by caalador** [comment]
Actually should this be removed at all. The functionality should still be there as how else do you create a type module script tag?
This will be fine as in 5121 I'll add a dependency filter that removes all JsModule imports and replaces them with only the index.js/index.es5.js module as a Type.JS_MODULE
