### ISSUE TITLE
Vaadin 12 - yarn throws E2BIG (ERROR_META_EXPANSION_TOO_LONG)

### ISSUE THREAD

**Issue by Duncol** [vaadin/flow#5135]
Hi everyone, after upgrading Vaadin 10 into Vaadin 12 I've encountered problem mentioned above.
Thing is happening regarding Jenkins pipeline, but this seems like an internal Vaadin phase. I've found out that it might be caused by NOTICE file and 'noticeText' in package.json, however it seems that yarn guys fixed this already https://github.com/yarnpkg/yarn/pull/5666 .

Yarn version: 
  1.6.0

Node version: 
  8.11.1

Platform: 
  linux x64

```
Trace: 
  Error: /data/jenkinspl/workspace/my-project-branch/target/node_modules/iltorb: spawn E2BIG
      at _errnoException (util.js:1022:11)
      at ChildProcess.spawn (internal/child_process.js:323:11)
      at Object.exports.spawn (child_process.js:502:9)
      at /data/jenkinspl/workspace/my-project-branche/target/node/yarn/dist/lib/cli.js:30262:24
      at new Promise (<anonymous>)
      at new F (/data/jenkinspl/workspace/my-project-branch/target/node/yarn/dist/lib/cli.js:23469:28)
      at /data/jenkinspl/workspace/my-project-branch/target/node/yarn/dist/lib/cli.js:30261:12
      at run (/data/jenkinspl/workspace/my-project-branch/target/node/yarn/dist/lib/cli.js:41698:7)
      at BlockingQueue.maybePushConcurrencyQueue (/data/jenkinspl/workspace/my-project-branch/target/node/yarn/dist/lib/cli.js:41713:7)
      at BlockingQueue.shift (/data/jenkinspl/workspace/my-project-branch/target/node/yarn/dist/lib/cli.js:41708:10)
```

UPDATE: Checked with Windows 10 64bit and the problem does not occur.

**Comment by denis-anisimov** [comment]
This looks similar to https://github.com/vaadin/flow/issues/4907
Could you please check which JVM is used on Jenkins ?

**Comment by Duncol** [comment]
> This looks similar to #4907
> Could you please check which JVM is used on Jenkins ?

Apache Maven 3.3.9
Java version: 1.8.0_131-b11
NPM version: 3.10.10
NodeJs version: v6.10.2

Is this sufficient?

**Comment by denis-anisimov** [comment]
Thanks for the info but is your JVM 32-bit or 64-bit (and I think your box is 64 bit)?

**Comment by Duncol** [comment]
> Thanks for the info but is your JVM 32-bit or 64-bit (and I think your box is 64 bit)?

Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by denis-anisimov** [comment]
OK, thanks. IT seems this is not related to the #4907.

**Comment by Duncol** [comment]
So is there any plan on resolving this in near future?

**Comment by TomaszRumpca** [comment]
Hello, any updates on the aforementioned issue? Can we expect some fix?

**Comment by mcollovati** [comment]
Closing because compatibility mode is not supported anymore in the maintained Vaadin versions.
