### ISSUE TITLE
Blank screen and JavaScript syntax errors in IE11 when using Material theme

### ISSUE THREAD

**Issue by evmatt** [vaadin/flow#5140]
This bug appears to be similar to #4944. When running an application in production mode on Vaadin 12.0.7, which [should incorporate ](https://github.com/vaadin/flow/releases/tag/1.2.5) the fix for #4944, the user sees a blank screen in IE11. Three JavaScript SyntaxErrors appear in the console on loading the page, all from the file `style-properties.js`. On inspecting this file ES6 keywords such as `const` are seen, so it appears that there is a failure in transpilation from ES6 to ES5 during the build process. This only occurs when using the Material theme, the Lumo theme works as expected.

I have been able to reproduce this bug using the Beverage Buddy starter pack running 12.0.7 when using the Material theme. When running the starter pack the errors arise from the `webcomponents-lite.js` file rather than `style-properties.js`.

**Comment by ZheSun88** [comment]
Issue confirmed.
Bug can be reproduced by running production build on beverage-start using `material` theme, though I didn't see a js error.

**Comment by pleku** [comment]
Issue moved to [vaadin/vaadin-material-styles #85](https://github.com/vaadin/vaadin-material-styles/issues/85) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Haprog** [comment]
Fixed. See: https://github.com/vaadin/vaadin-material-styles/issues/85#issuecomment-498998856
