### ISSUE TITLE
Make it possible to include JS from jar files

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#5145]
JavaScript files included in an add-on jar file should be available for webpack so that it will be included in the production bundle and so that it can import other JS modules e.g. from `node_modules`. This covers both `@JavaScript` and `@JsModule`.

One idea on how to implement this is that the Maven plugin looks for such files and copies them into some location that webpack is configured to use as input.

**Comment by pleku** [comment]
As a component / application developer, for any local modules or modules from `.jar` files in the class path, I would expect to the contents of `src/main/resources/META-INF/frontend/` be available for the application.

So all template and connector files should be placed there.
