### ISSUE TITLE
Create an example on embedding a Calendar Flow application as a web component using the WebComponent annotation

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#5150]
Use the `WebComponent` annotation approach for exporting a calendar app as a web component. This is a similar example to Petclinick OwnerForm in https://github.com/denis-anisimov/spring-petclinic/tree/web-component but more standalone use case showing a different approach than #5149

**Comment by ujoni** [comment]
Testing

**Comment by ujoni** [comment]
Annotation approach (uses the current API as much as possible):
https://github.com/ujoni/skeleton-starter-flow/blob/thin-web-component-trials/src/main/java/com/vaadin/starter/skeleton/ServerSideFullCalendar.java
