### ISSUE TITLE
DX test editing templates experience with npm 

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5161]
1. Clone the beverage buddy starter with branch 2.0
2. run the project
3. edit the reviews-list.js template to add a new button (or any component that already is available) that prints a message to the server console when clicked

**Comment by caalador** [comment]
"Validate that npm p3 development mode can be started from a clean pull"

Before DX test start
1. Check that you have installed
    - java 8
    - maven
    - Node.js
    - npm

DX test:
1. Clone Beverage-starter-flow
    - checkout branch 2.0
2. Run the 2.0 branch of beverage buddy
3. edit `reviews-list.js`
    - add a new button to the template
        - button should log to the console.

**Comment by caalador** [comment]
DX test document. 
https://docs.google.com/document/d/1syvTX2zEjWyH5tQICcnOdG7oH3fwLcQNBAstw6qQaAo/edit#

Update as DX tests are run.
tests run so far include 1 PD  member with a Mac

Try to get at least one Windows user from services side.

**Comment by bogdanudrescu** [comment]
Got one services user. Doc is updated. Had to run against 2.0.

**Comment by pleku** [comment]
Still need to test again with:
- [ ] a Windows user
- [ ] a Mac user
- [ ] a Linux user (any)
