### ISSUE TITLE
DX test the experience of including and using a npm based component add-on to a project

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5162]
Prerequisites: any developer with Java 8, Maven and node&npm installed 

Test the experience of taking an add-on into use in the project.

Setup:
1) clone https://github.com/vaadin/beverage-starter-flow/tree/addon-dx branch
2) run `mvn jetty:run` on the project and open app in browser to validate that it works

Task:
Add a `PaperSlider` to the `CategoryList` with Java.
The dependency information is 
```xml
        <dependency>
            <groupId>org.vaadin.addon</groupId>
            <artifactId>paper-slider-flow</artifactId>
            <version>1.0.0</version>
        </dependency>
```

The documentation is in: https://github.com/vaadin/flow-and-components-documentation/tree/2.0/documentation/web-components

**Comment by martaolszewskatusiek** [comment]
Test results: https://docs.google.com/document/d/1phI4waMrih6zaNEguymycJbxntpDUOOS5PInxq7LXV4/edit
