### ISSUE TITLE
Allow moving components from one UI to another UI

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5165]
Use case:
_When building a Flow application that is opened through another desktop/web application, I want to reuse the whole component tree from an existing opened browser window/tab, so that I can perfect the UX of my app by keeping the same UI component states without having to write lots of boilerplate for recreating the UI and the state_

Currently this is not possible by design because components cannot be moved from one state tree to another, as it has been considered a programmer error to do so.

In this use case, the old UI where the components are detached from, should be killed either with
- pushing a notification that this browser window/tab can be closed
- waiting for the first round trip triggered by user interaction to announce that the UI has been inactivated

I think it is fine to let the programmer to handle the "killing" of the old UI; but the feature for moving components from one state tree to another (from UI to another UI) should probably be built in a way that still prevents developers from accidentally doing it with having e.g. wrongly scoped beans in their applications. So IMO it should only be possible with some special API, and not just open the door for randomly moving component (state tree nodes) between different UI instances.

**Comment by Legioth** [comment]
I agree that disposing the old UI is completely outside of the scope of this issue. It might not be the most common case, but there is still the possibility that only some part of the old UI are moved out while still keeping the rest of that UI functional.

One observation is that with this feature present, it would probably be possible to implement something along the lines of `@PreserveOnRefresh` without any changes to the bootstrapping logic. In that way, a new UI would still be created, but that UI would initially only contain logic to send `window.name` back to the server. As a response to that request, the actual contents of the UI would either be initialized or adopted from an existing UI with the same `widow.name`.

**Comment by pleku** [comment]
Very good point, thus related to #3522

**Comment by pleku** [comment]
Fixed with #5445.

Can be used with `component.getElement().removeFromTree()`
