### ISSUE TITLE
ForwardTo does not work without a BeforeEnterObserver

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#5173]
Consider the following code

    @Route("forward")
    public class ForwardView extends VerticalLayout implements HasUrlParameter<String>, AfterNavigationObserver {
    
        @Override
        public void setParameter(BeforeEvent event, String parameter) {
            event.forwardTo(BackView.class);
        }
    
        @Override
        public void afterNavigation(AfterNavigationEvent event) {
            System.out.println("Navigated to ForwardView " + event.getLocation().getPath());
        }
    }

### Steps to recreate

Navigate to `forward/test`

### Expected result

`ForwardView#afterNavigation` is not called

### Actual result

`ForwardView#afterNavigation` is called, no forwarding takes place

### With BeforeEnterObserver

We can add a `BeforeEnterObserver` as such

    @Route("forward")
    public class ForwardView extends VerticalLayout implements HasUrlParameter<String>, AfterNavigationObserver, BeforeEnterObserver {
    
        @Override
        public void setParameter(BeforeEvent event, String parameter) {
            event.forwardTo(BackView.class);
        }
    
        @Override
        public void afterNavigation(AfterNavigationEvent event) {
            System.out.println("Navigated to ForwardView " + event.getLocation().getPath());
        }
    
        @Override
        public void beforeEnter(BeforeEnterEvent event) {
    
        }
    }

Forwarding now behaves correctly, upon navigating to `forward/test`, we are forwarded to `back` and `ForwardView#afterNavigation` is not called.

### Version info

Chrome  71.0.3578.98
Platform 13.0.0.beta3

**Comment by caalador** [comment]
Implementation of forwardTo has missed the  possible addition of forward in notifyNavigationTarget and only reroute target is checked and acted upon.

For position of missing implementation see `AbstractNavigationStateRenderer:l196`

**Comment by bogdanudrescu** [comment]
Fixed by https://github.com/vaadin/flow/pull/8170, PR https://github.com/vaadin/flow/pull/9030 adds the unit test.
