### ISSUE TITLE
After forwarding using forwardTo, parameters are missing from Location object

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#5174]
Consider the following code

    @Route("forward")
    public class ForwardView extends VerticalLayout implements HasUrlParameter<String>, AfterNavigationObserver, BeforeEnterObserver {
    
        @Override
        public void setParameter(BeforeEvent event, String parameter) {
            if (parameter.equals("one")) {
                event.forwardTo("forward", "two");
            }
        }
    
        @Override
        public void afterNavigation(AfterNavigationEvent event) {
            System.out.println("Navigated to ForwardView " + event.getLocation().getPath());
        }
    
        @Override
        public void beforeEnter(BeforeEnterEvent event) {
    
        }
    }

### Steps to recreate

1. Navigate to `forward/two`
2. Navigate to `forward/one`

### Expected results

1. The message `Navigated to ForwardView forward/two` is printed
2. The message `Navigated to ForwardView forward/two` is printed

### Actual results

1. The message `Navigated to ForwardView forward/two` is printed
2. The message `Navigated to ForwardView forward` is printed

### Additional comment

When a navigation event is forwarded, the `Location` is created in `AbstractNavigationStateRenderer#getNavigationEvent`, which in turn uses `RouteConfiguration#getUrlBase`, and as such, URL parameters are not added to the `Location`.

### Versions

Chrome 71.0.3578.98
Platform 13.0.0.beta3

**Comment by TatuLund** [comment]
I think this is somehow related to navigation target not changing. I found a workaround using proxy view, i.e. forwardTo proxy view with the new parameter and from proxy view back original one with the new paramter it works.
