### ISSUE TITLE
Update Embedding Flow app example (Petclinic) to use the new API

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5179]
Update https://github.com/denis-anisimov/spring-petclinic/tree/web-component based on #5176

**Comment by denis-anisimov** [comment]
Cannot be done until Spring add-on is able to handle `WebComponentConfigurationRegistryInitializer` properly.

**Comment by denis-anisimov** [comment]
https://github.com/denis-anisimov/spring-petclinic/pull/new/wc-exporter
