### ISSUE TITLE
Detect and enable @Push from WebComponentExporter class

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5194]
The value to deliver is to enable the user to define whether or not push should be enabled for the embedded Flow web component (Servlet).

### Acceptance Criteria
Provide a way for the user to specify how to enable push so that they don't have to register a servlet just to make it happen (#5070).
Add a mention of this to the documentation.

**Comment by Legioth** [comment]
There are actually two parts of enabling push. The first step is that Atmosphere should be enabled on the servlet level. The second step is that `ui.getPushConfiguration().setPushMode(PushMode.AUTOMATIC)` should be run for any appropriate UI instance.

**Comment by Legioth** [comment]
This case is quite similar to handling of `@Theme`. In both cases, we have two different places that represent the "root" of an "application" and that can have various annotations used for configuring the "application". Might make sense to somehow unify these concepts in the implementation.

**Comment by pleku** [comment]
>This case is quite similar to handling of @Theme. In both cases, we have two different places that represent the "root" of an "application" and that can have various annotations used for configuring the "application". Might make sense to somehow unify these concepts in the implementation.

Yes, agreed that if the annotations are present on the `WebComponentExporter`, then those should be used from there. Otherwise those come from the exported component (if present there).

**Comment by Legioth** [comment]
> Otherwise those come from the exported component (if present there).

What's the point of that? Wasn't the main point of introducing the `WebComponentExporter` API that the component implementation could remain "pure", i.e. not in any way related to being exported as a web component.

**Comment by pleku** [comment]
>What's the point of that? Wasn't the main point of introducing the WebComponentExporter API that the component implementation could remain "pure", i.e. not in any way related to being exported as a web component.
If the component uses `@Push` and relies on that to work, why should one have to duplicate the `@Push` annotation in the exporter in order to make the component to work as exported web component ?
I think it should be possible to override the configuration in the exporter, but if there is nothing specified in the exporter, then what ever the exported component specifies, is used instead.

**Comment by pleku** [comment]
>What's the point of that? Wasn't the main point of introducing the WebComponentExporter API that the component implementation could remain "pure", i.e. not in any way related to being exported as a web component.

>If the component uses @Push and relies on that to work, why should one have to duplicate the @Push annotation in the exporter in order to make the component to work as exported web component ?
I think it should be possible to override the configuration in the exporter, but if there is nothing specified in the exporter, then what ever the exported component specifies, is used instead.

Taking a step back. Updated the issue description.

**Comment by Legioth** [comment]
`@Push` is not supported on arbitrary components, but only on the component that is used as a topmost router layout.
