### ISSUE TITLE
Create basic webpack.config.js

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5203]
We should give an easy way to create webpack config to the user, `flow-maven-plugin` might create it if not found. At the same time needs to update needed dependencies (webpack, babel, etc)

**Comment by pleku** [comment]
This is a must have for all new projects and should also be generated by the migration tool for the projects that are migrated.

The developers should not have to worry about adding the needed dependencies like babel.

**Comment by pleku** [comment]
Unless the file exists, the Maven plugin creates it based on a default template we have that works well with Flow. The user can then configure it further if they want.
