### ISSUE TITLE
dev-mode perf: do not import unused components

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5214]
We should not import in `main.js` file all those components in the classpath  that are not actually used in the app

**Comment by pleku** [comment]
We will want to look at this later on so we could at least have some optimization available for the user to get started on not having to import all the components. It will be quite complex to try to find all the used components from Java, from imported modules, local modules and go through all the transitive imports for those.

**Comment by pleku** [comment]
One option would be to not reimport anything that the user has commented out in the `main.js` - this would be considered as exclusions.

**Comment by pleku** [comment]
Superseded by #5467
