### ISSUE TITLE
update production build documentation basic documentation

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5238]
Update https://github.com/vaadin/flow-and-components-documentation/blob/2.0/documentation/production/tutorial-production-mode-basic.asciidoc

`bowerMode` stuff doens't need to shown anymore.

**Comment by bogdanudrescu** [comment]
We should also:
update https://github.com/vaadin/flow-and-components-documentation/blob/2.0/documentation/production/tutorial-production-mode-advanced.asciidoc 
https://github.com/vaadin/flow-and-components-documentation/blob/2.0/documentation/production/tutorial-production-mode-customising.asciidoc
