### ISSUE TITLE
update documentation on how to customize the production bundle

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5239]
Update https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/production/tutorial-production-mode-customising.asciidoc on how to:
- start to manually maintaining the `main.js`, so that Flow doesn't touch it anymore or touches another file

**Comment by bogdanudrescu** [comment]
We're always updating the file at the moment, however there is #5214, but it refers to unused imports. Question is what's the benefit for manually maintaining `main.js` and maybe `packages.json` as well?

**Comment by Legioth** [comment]
> Question is what's the benefit for manually maintaining `main.js` and maybe `packages.json` as well?

Right now, the main benefit would be to work around bugs in the logic that generates those files.

In the future, the benefit is that it enables creating applications where some parts are managed by Flow and other parts are using whichever general frontend development framework that someone wants to use.

**Comment by manolo** [comment]
Added this to the Acceptance criteria in https://github.com/vaadin/flow/issues/5537.
Let's close this and track this in the other.
