### ISSUE TITLE
DX test production build experience

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5243]
Prerequisites:
- the candidate has Maven, Java 8 and node installed.
- the candidate is able to git clone and checkout the beverage-buddy branch `2.0` and run it

The task is to ask the candidate to package the application for production.

Documentation is available in https://github.com/vaadin/flow-and-components-documentation/blob/2.0/documentation/production/tutorial-production-mode-basic.asciidoc

**Comment by martaolszewskatusiek** [comment]
Test results: https://docs.google.com/document/d/1gpXpqj6N2bSA8_r8a5_Xnp8rYABKcVi1lR4luLeiOZU/edit?ts=5cb068e2
