### ISSUE TITLE
Rendered font is different when application is run in development and in production

### ISSUE THREAD

**Issue by igormilina** [vaadin/flow#5248]
- Description of the bug:
I have vaadin application that uses default lumo theme. When run in development 
 (productionMode=false) resolved font on web page is Segoe UI, which is expected as I don't have Roboto font installed locally. 
But when productionMode is set to true and application is bundled, then resolved font on web page will be Roboto because framework is including Roboto web font from google fonts.
Forum discussion of this issue: https://vaadin.com/forum/thread/17482391/fonts-bolder-in-production-mode

- Expected behavior
Font in web application should be the same (consistent) when run in development and in production.

- Actual behavior
In development mode rendered font is: Segoe UI, but in production rendered font is: Roboto, so application look different.

- Versions:
    - Vaadin / Flow version: 13.0.1 (and lower)
    - Java version: 1.8
    - OS version: Windows 10
    - Browser version: Chrome 72.0.3626.121 (64bit), Firefox 65.0.2 (64-bit)

**Comment by igormilina** [comment]
I have just re-tested this with Vaadin version: 14.0.1 (using npm mode) and it seems that issue has been resolved.

**Comment by pleku** [comment]
>I have just re-tested this with Vaadin version: 14.0.1 (using npm mode) and it seems that issue has been resolved.

Great to hear it was resolved, thanks for the update.
