### ISSUE TITLE
Embedded web components: implement the ability to push property updates to client

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#5259]
Currently, properties are only synchronized to one direction: from client to server. Implement synchronization from server to client.

Currently, `InstanceConfigurator` receives a reference to a `WebComponent`, which is proposed to look like this:

```java
public interface WebComponent<C extends Component> extends Serializable {
    <P extends Serializable> void setProperty(
            PropertyConfiguration<C, P> propertyConfiguration, P value);

    <P extends Serializable> P getProperty(PropertyConfiguration<C, P> propertyConfiguration);
}
```

Either provide implementation to `WebComponent` or _find another way_.

**Comment by pleku** [comment]
### Acceptance Criteria
The value to deliver is to be able to send property updates to the client. This might be anything that the embedding application is interested in, like alarming the user about a new message pushed by the server.
Add a tutorial that shows how to update the property value. The example can be for instance about _number of unread messages_.

**Comment by ujoni** [comment]
Should we split up the embedding tutorial somewhat? It is starting to get quite large? 

We could have the current tutorial (with @denis-anisimov's fireEvent additions) as a separate, large tutorial, but lift separate issues as their own topics, something like:
- Exporting `Component` as a web component
  - define properties
  - write properties
- Firing custom events
- Enabling push for embedded components
- Full embedded example

Or is that too much separation?

**Comment by pleku** [comment]
>Should we split up the embedding tutorial somewhat? It is starting to get quite large?

Less is more. I'm fine with splitting it up.
