### ISSUE TITLE
Anchor produces a different URL when the router-link attribute is set

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#5274]
Consider clicking each of the links in the following code, both of which lead to a component with a string parameter

    String url = RouteConfiguration.forApplicationScope().getUrl(RouteView.class, "åäö");

    Anchor anchor = new Anchor(url, "Anchor");

    Anchor routerAnchor = new Anchor(url, "Router anchor");
    routerAnchor.getElement().setAttribute("router-link", true);

### Expected result

Both links produce the parameter `åäö`

### Actual result

The first produces `åäö`, the second produces `%C3%A5%C3%A4%C3%B6`

### Versions

Platform 13.0.0
Chrome 72.0.3626.121

**Comment by caalador** [comment]
Could not reproduce with 14.1.21.
Please comment with more information or open a new ticket if problem persists in some way.

**Comment by caalador** [comment]
Noted problem description in #5275
Keeping this closed as the root issue is the same that router-link url encoding is not unencoded for set parameter.
