### ISSUE TITLE
Combobox issue when allowing custom values

### ISSUE THREAD

**Issue by andreasbean** [vaadin/flow#5286]
How to reproduce:

Create a combox and set items. Additionally setAllowCustomValue(true)

Now, if you enter a text in the TextField everthing works until you select an item for the first time. After selecting an item its not possible to change the text anymore because after filtering the text is replaced by the last selected item.

I have tracked down the issue to the file vaadin-combo-box-mixin.html

```
_selectedItemChanged(selectedItem, itemLabelPath) {
      if (selectedItem === null || selectedItem === undefined) {
        if (this.filteredItems) {
          if (!this.allowCustomValue) {
            this.value = '';
          }
          this._updateHasValue(this.value !== '');
          this._inputElementValue = this.value;
        }
```

fix it by changing

```
_selectedItemChanged(selectedItem, itemLabelPath) {
            if (selectedItem === null || selectedItem === undefined) {
                if (this.filteredItems) {
                    if (!this.allowCustomValue) {
                        this.value = '';
                        this._updateHasValue(this.value !== '');
                    }
                }
```

Please fix this as soon as possible and test the ComboBox with custom values better than in the past. I'm getting a bit tired with the ComboBox issues at the moment because I'm waiting for a working version for at least a year now and if one issue is fixed another one is introduced. Please make sure that the ComboBox with custom values will be working in the near future.

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/vaadin-combo-box #788](https://github.com/vaadin/vaadin-combo-box/issues/788) via [**ZenHub**](https://www.zenhub.com/)
