### ISSUE TITLE
Use a better default production build output location for jar packaging

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#5293]
Right now, there's a hardcoded case in `PackageForProductionMojo` that uses `${project.build.outputDirectory}/META-INF/resources` as the default value for `transpileOutputDirectory` iff the project packaging is `jar` and `vaadin-spring-boot-starter` is included as a dependency. In all other cases, `${project.build.directory}/${project.build.finalName}` is used.

The default setting is basically never he right alternative for `jar` packaging since the contents of that directory is by default not even included in the produced `.jar` file. This causes confusion as can be seen in e.g. https://stackoverflow.com/q/55196878/2376954.

I would propose to either use `${project.build.outputDirectory}/META-INF/resources` for all `jar` packaging modules regardless of whether `vaadin-spring-boot-starter` is used, or alternatively make the plugin throw an exception with a helpful message in case `jar` packaging is used but no explicit `transpileOutputDirectory` configuration has been defined.

**Comment by SomeoneToIgnore** [comment]
Closed via https://github.com/vaadin/flow/pull/5371
