### ISSUE TITLE
13.0.1-Handling User Events: Add Event Data to server-side event dows not work

### ISSUE THREAD

**Issue by gianluca-valentini** [vaadin/flow#5303]
Hi,
I'm using Vaadin 13.0.1. When i try to add Event Data to server-side event as described in [tutorial](https://vaadin.com/docs/v13/flow/polymer-templates/tutorial-template-event-handlers.html) it does not work.
Using it to have the selected item as an object in the event handler I have always it as empty:

> Message [text=null]

To reproduce this scanario just use the tutorial to send Message item from client to server

**Comment by caalador** [comment]
This is because the Message object is a proxy object.
You need to use the getter to get the actual value so `message.getText()`

**Comment by gianluca-valentini** [comment]
Thanks a lot @caalador
