### ISSUE TITLE
Spike: Investigate how to allow moving components from one UI to another

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5316]
It should not be possible by default, meaning that one cannot simply move a component from one UI to another with the basic API of e.g.
```
Button button = new Button();
layout.add(button);

// another UI instance has been created
getUI().add(button); // this should still explode like it does now
```

There should be an explicit way of allowing the component (on the low level an element & state node) to be detached from another UI&state tree. Something like (but not really):
```
button.detachFromThisUI() ?
theFirstUI.detachComponentFromUI(button) ? // this should be recursive, all children should be detached too
// something else ...
getUI().add(button); // this will work, because of the explicit unregistering of the component from the previous UI it was a part of
```

The goal of the spike is to come up with a suitable API for this and prototype it in operation, meaning that you showcase how the user can attach existing UI contents to a newly created UI using the API.

**Comment by joheriks** [comment]
Noting that a difference compared to @PreserveOnRefresh is that attach and detachlisteners will be called for the moved components.
