### ISSUE TITLE
parsing `stats.json` to get bindings does not work anymore

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5317]
checkout beverage 2.0 and run `mvn jetty:run`, it fails with the error `java.lang.UnsupportedOperationException: NAME _templateObject 51 [length: 15] [source_file: ./src/views/reviewslist/reviews-list.js] is not a template literal string node` meaning that the source fragment in the object named as `"name": "./src/views/reviewslist/reviews-list.js?babel-target=es6"`   has been transpiled and it starts with `"source": "import _taggedTemplateLiteral from` instead of `import { PolymerElement } from '@polymer/polymer/polymer-element.js';`

**Comment by caalador** [comment]
Yesterday babel core was `"version": "7.2.3"` and  today it resolves to `"version": "7.4.0"``
