### ISSUE TITLE
When generating webpack.config.js consider parse it to set the `target` folder

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5321]
Only the `target` folder can be synchronised with the user's maven configuration by considering the `${project.build.directory}` available by the `flow-maven-plugin`

We need to consider that it's still not enough because 
1.- The full path for generating the webpack stuff is defined by default as `target/generated-frontend`, hence there is a random part in the path that can be defined by the user and break build.
2.- User should define the path in `maven-war-plugin` in their custom `pom.xml` as `<directory>${project.build.directory}/generated-frontend</directory>`  instead of `<directory>target/generated-frontend</directory>`
3.- User also needs to have defined the source in `jetty-maven-plugin` using the variable, mean `<webAppSourceDirectory>${project.build.directory}/generated-frontend</webAppSourceDirectory>` instead of `<webAppSourceDirectory>target/generated-frontend</webAppSourceDirectory>`
4.- it only fixes one of all possible issues that the user can cause: the `target`  folder, but we cannot fix other folders the user might want to configure like `/frontend` folder, `/build/` webcontext for the generated stuff, or the `generated-frontend` part in the target webpack folder.
5.- `target` folder is quite common in maven projects, and users don't use to change it.
6.- parsing the file needs some effort to correctly parse the JS file and do the substitution of a variable defined as a convention. Hence we cannot do random changes to the template file without respecting that convention

This issue is to cover unfinished work in https://github.com/vaadin/flow/pull/5234

**Comment by pleku** [comment]
We should make sure that both `war` and `jar` packaging work automatically based on what is defined as the packaging for the module in the pom.xml.

Similarly to what is done now for the bower mode for production mode, we should just use the correct target location for the frontend resources based on the packaging determined by our Flow Maven plugin.

For `jar` packaging it is by default `/target/classes/META-INF/resources` where `target` is `${project.build.directory}`
For `war` packaging it is by default `/target/${project.build.outputDirectory}/` like `\target\bookstore-starter-flow-ui-1.0-SNAPSHOT`

To be continued...

**Comment by Legioth** [comment]
Slightly related: https://github.com/vaadin/flow/issues/5293

**Comment by SomeoneToIgnore** [comment]
> Slightly related: #5293

Done in https://github.com/vaadin/flow/pull/5371/files#diff-41a5ba84e060a6d2766ca0de02da99f2R62

will add a meta info into the PR to close this ticket also.
