### ISSUE TITLE
Change how embedded web component instance can be configured

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#5332]
Current exporter approach goes like this:

```java
public class MyExporter implements WebComponentExporter<MyComponent> {
   public void define(WebComponentDefinition definition) {
      definition.addProperty("property", "default value");

      definition.setInstanceConfigurator((webComponent, component) -> {
         component.registerSomeChangeListener(change -> webComponent.fireEvent("custom-change", change);
         // other callbacks
      });
   }
}
```

The proposal is to list configuration functionality from `setInstanceConfigurator` method to the exporter level:

```java
public class MyExporter implements WebComponentExporter<MyComponent> {
   public void define(WebComponentDefinition definition) {
      definition.addProperty("property", "default value");
   }

   public void configure(WebComponent webComponent, MyComponent component) {
      component.registerSomeChangeListener(change -> webComponent.fireEvent("custom-change", change);
      // other callbacks
   }
}
```

This approach requires the developer to save the property handles as instance variables on the exporter (for accessing those properties by reference in the `configure` method). But is also makes the configure (or, `setInstanceConfigurator`) method easier to encounter and lessens the depth of the callback stack.

**Comment by pleku** [comment]
As discussed, the method should *not* have a default implementation in the exporter interface.

The documentation and the petclinic example should be updated as those will be broken.

**Comment by ujoni** [comment]
Issues #5353 is related in the sense that it also aims to modify how  `WebComponentExporter` is defined and used.
