### ISSUE TITLE
 Vaadin downloader (via StreamResource) replaces spaces ' ' with '+'

### ISSUE THREAD

**Issue by vlipovetskii** [vaadin/flow#5360]
File name, which contains '+' is not handled by downloader properly, since Vaadin downloader  (via StreamResource) replaces spaces ' ' with '+' and interprets '+' not as a regular character.

**Comment by ZheSun88** [comment]
Hi, thanks for reporting this issue, Do you mind to provide us a sample project to test?

**Comment by vlipovetskii** [comment]
Please find sample project https://github.com/vlipovetskii/vaadin-issue-5360-prj

**Comment by jcgueriaud1** [comment]
Is "+" the only special character that should be avoided for the name of StreamResource ? 

If you replace:
```
 StreamResource resource = new StreamResource("image.svg",
            () -> getImageInputStream(name));
```
to 
```
StreamResource resource = new StreamResource("image++.svg",
            () -> getImageInputStream(name));
```
(from the documentation: https://vaadin.com/docs/v14/flow/advanced/tutorial-dynamic-content.html#using-code-streamresource-code )
Then you will have a 404 error. (code to reproduce in Vaadin 14.1.27)

```
@Route
public class MainView extends VerticalLayout {

    public MainView() {
        Input name = new Input();

        Element image = new Element("object");
        image.setAttribute("type", "image/svg+xml");
        image.getStyle().set("display", "block");

        NativeButton nativeButton = new NativeButton("Generate Image");
        nativeButton.addClickListener(event -> {
            StreamResource resource = new StreamResource("imagåäöé with space.svg",
                    () -> getImageInputStream(name));
            image.setAttribute("data", resource);
        });

        getElement().appendChild(name.getElement(), image,
                nativeButton.getElement());
    }

    private InputStream getImageInputStream(Input name) {
        String value = name.getValue();
        if (value == null) {
            value = "";
        }
        String svg = "<?xml version='1.0' encoding='UTF-8' standalone='no'?>"
                + "<svg  xmlns='http://www.w3.org/2000/svg' "
                + "xmlns:xlink='http://www.w3.org/1999/xlink'>"
                + "<rect x='10' y='10' height='100' width='100' "
                + "style=' fill: #90C3D4'/><text x='30' y='30' fill='red'>"
                + value + "</text>" + "</svg>";
        return new ByteArrayInputStream(svg.getBytes(StandardCharsets.UTF_8));
    }

}
```

**Comment by jcgueriaud1** [comment]
Special characters I found that are not working:
* / that will throw java.lang.IllegalArgumentException: Resource file name parameter contains '/'
* \ that will result to a HTTP 400 error

Perhaps, a list of *forbidden* characters should be added to the javadoc.

**Comment by ajgassner** [comment]
@jcgueriaud1 it's in general a good idea to escape or clean complex file names before generating an uri, see e.g. https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names 

This shouldn't be handled by flow IMHO.

**Comment by ajgassner** [comment]
@caalador I just upgraded to Vaadin 16 and in conjunction with Spring (Boot) file downloads with files containing one or more spaces are broken, bad request. I think we have to reopen the issue.

**Comment by caalador** [comment]
Can you get it to reproduce with `StreamResourceView.java` now there is only the special file `file+.jpg`

Also I would open a new ticket with steps to reproduce.

**Comment by caalador** [comment]
Adding to the test:
```
        StreamResource spaceResource = new StreamResource("file .jpg",
                () -> new ByteArrayInputStream(
                        "foo".getBytes(StandardCharsets.UTF_8)));
        Anchor spaceDownload = new Anchor("", "Download file .jpg");
        spaceDownload.setHref(spaceResource);
        spaceDownload.setId("space-link");
```
Works as expected. The space in the name didn't break.

**Comment by ajgassner** [comment]
see https://github.com/vaadin/flow/issues/8500

**Comment by AB-xdev** [comment]
We are experiencing similar problems on V14 LTS:

There seems to be a malfunction when the StreamResource gets retrieved:
The URI seems to be not correctly escaped when retrieving the resource.
Registering:
![grafik](https://user-images.githubusercontent.com/45384811/84473497-7617f500-ac89-11ea-9626-4dbb3b2da6e2.png)
Retrieving:
![grafik](https://user-images.githubusercontent.com/45384811/84473516-7e703000-ac89-11ea-8454-2d6da5f0c087.png)

Does this issue also fix this problems?  (looks like there are still problems → #8500)
Will this "fix" get backported to V14?

**Comment by caalador** [comment]
It should hopefully be coming in the next 14.2 version.
