### ISSUE TITLE
Current WebComponentExporter doesn't work with @Theme(value = Lumo.class, variant = Lumo.DARK)

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#5372]
The current implementation is missing the logic on handling the variant part.

In other words, if I use `@Theme(value = Lumo.class, variant = Lumo.DARK)` on the exporter,  the embedded app is using `Lumo.light` Theme, instead of `Lumo.dark`.

**Comment by denis-anisimov** [comment]
This should be done after the https://github.com/vaadin/flow/pull/5369 PR.
It introduces a subclass of `BootstrapContext` whose method `getTheme` should be overridden to fix the ticket.

**Comment by pleku** [comment]
Whenever a variant or theme attribute is used, it should be written to the generated web component element, not to the `html` element like in stand-alone application case.
