### ISSUE TITLE
Consider `@NoTheme` when writing `main.js` imports file, and `@Theme` at root level 

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5380]
Right now when generating `main.js` we consider the first `@Theme` annotated view found in the classpath, otherwise we add `Lumo` but `@NoTheme` annotation is not considered at all.
See https://vaadin.com/docs/v13/flow/theme/application-theming-basics.html

**Comment by manolo** [comment]
Note that for being coherent with the documentation, and v13 implementation we need to consider `@Theme` at root navigation level. Right now the implementation just takes the first `@Theme` annotation found in the classpath.

**Comment by SomeoneToIgnore** [comment]
Fixed via https://github.com/vaadin/flow/pull/5486
