### ISSUE TITLE
vaadin-maven-plugin doesnt use Maven proxy setting

### ISSUE THREAD

**Issue by garehira** [vaadin/flow#5381]
Ia m using vaadin-maven-plugin for Vaadin 13.0.1 app. Without proxy it works fine. Now I need to configured a proxy and did so as advised in https://github.com/vaadin/flow/issues/4771
(using Maven proxy settings)
However the plugin ignores the proxy settings and keeps on saying 'No proxies configured'. 
My expectation is that the plugin uses the maven proxy fo download.

[INFO] --- vaadin-maven-plugin:13.0.1:package-for-production (default) @ eh-cep-exportmodule ---
[WARNING] The translated URL 'frontend://bower_components/vaadin-upload/theme/lumo/vaadin-upload-file.html' has no corresponding file on the filesystem, the file is addressed by path='...'
[INFO] Installing node version v8.11.1
[INFO] Downloading https://nodejs.org/dist/v8.11.1/win-x64/node.exe to R:\gitnew\exportmodule\ExportModule\target\cache\node-v8.11.1-win-x64.exe
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly

**Comment by slatequarry** [comment]
Setting parameter "ignoreMavenProxies" to false works for me.

<plugin>
	<groupId>com.vaadin</groupId>
	<artifactId>vaadin-maven-plugin</artifactId>
	<version>${vaadin.version}</version>
	<configuration>
		<ignoreMavenProxies>false</ignoreMavenProxies>
	</configuration>
	<executions>
		<execution>
			<goals>
				<goal>copy-production-files</goal>
				<goal>package-for-production</goal>
			</goals>
		</execution>
	</executions>
</plugin>

**Comment by garehira** [comment]
Thansk for your hint, slatequarry. It works now.

**Comment by pleku** [comment]
There is an issue about improving the documentation about parameters #5430 .
