### ISSUE TITLE
Binder.removeBinding issue

### ISSUE THREAD

**Issue by nbabb** [vaadin/flow#5384]
In Vaadin flow 1.0.5, I have several fields bound to a Binder instance. When I remove a binding (where there are still other bound properties) it is calling unbind. It seems like it should only call unbind when the count of bound properties is zero? Here is the code.

```
public void removeBinding(String propertyName) {
    Objects.requireNonNull(propertyName, "Property name may not be null");
    Optional.ofNullable(boundProperties.get(propertyName))
            .ifPresent(Binding::unbind);
}
```
I end up receiving errors after I remove the binding

java.lang.NullPointerException: This Binding is no longer attached to a Binder
at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[na:na]
at com.vaadin.flow.data.binder.Binder$BindingImpl.validate(Binder.java:1027) ~[flow-data-1.0.5.jar:na]

from my other bound fields that are still using the binding.

Perhaps I'm misunderstanding how this should work?  See https://github.com/vaadin/framework/issues/11280 for reference

**Comment by ZheSun88** [comment]
The first thing i would suggest you is updating your flow version to the latest ones, ( if you are using flow separately, the version number is `1.0.10`). could you try with that one?

**Comment by atistrcsn** [comment]
>  [vaadin/framework#11280](https://github.com/vaadin/framework/issues/11280)

The WorkaroundBinder mentioned in @lulnope's answer is actually a good temporary solution.
It should be included in a bugfix. I don't have experience how to prepare one.

**Comment by denis-anisimov** [comment]
Looks like this is a bug in `Binder`.

Refer to https://github.com/vaadin/framework/issues/11280#issuecomment-474470510 to fix it:

The issue is located in `Binder` class in its `protected void removeBindingInternal(Binding<T, ?> binding)` method. Currently it looks as follows:
```
protected void removeBindingInternal(Binding<BEAN, ?> binding) {
        if (bindings.remove(binding)) {
            boundProperties.entrySet()
                    .removeIf(entry -> entry.getValue().equals(binding));
        }
    }
```
it's missing: `changedBindings.remove(binding)`
which should resolve this error:
`java.lang.NullPointerException: This Binding is no longer attached to a Binder`
