### ISSUE TITLE
When updating my project to 14, I should be able to run it without changing anything else than version

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5406]
Updating to 10-13 to 14 should be a version bump for Flow projects (there might be some changes in Java APIs, those are a separate thing). 

This means that we should automatically detect when the project still runs on webjars/p2/htmlimports instead of npm/p3/jsmodules. This should be the case for both, development time and production mode.

Acceptance criteria:

- [ ] Changing version of Platform to 14 should keep bower mode for old projects.
- [ ] Default mode is npm.
- [ ] Automatic detection for bower projects (if frontend folder exists).
- [ ] In case automatic detection fails a meaningful message should be provided. 
- [ ] There is a way to explicitly set bowerMode property which ignores the default and automatic detection.

**Comment by Juchar** [comment]
I did update my pom version of Vaadin from `13.0.6` to `14.0.0.beta1`.
When starting the application locally in debug mode I am now getting the following message:
```
** WARNING **  Vaadin is running in BOWER MODE.

By default Vaadin should run in npm mode but this project is not
properly configured.

To disable this message, migrate your project to 'npm' or set the
property 'vaadin.bowerMode' to 'true'
```
I am not really sure about what "not properly configured" means, neither did I find any documentation.
Is there something I can have a look at?

**Comment by pleku** [comment]
@Juchar sorry for the confusing message - your project is correctly configured and running the "legacy bower/webjars mode" which is still supported in 14. So you don't need to worry about it.

The message is being adjusted for beta 2.

**Comment by Juchar** [comment]
@pleku Thanks for clarifying. You say that it runs in **legacy** mode - what would be the non-legacy mode and how to activate it?

**Comment by Legioth** [comment]
> You say that it runs in legacy mode - what would be the non-legacy mode and how to activate it?

Vaadin 14 will support two different modes related to how client-side dependencies are managed:
* Bower, HTML imports and Polymer 2
* npm, JS Modules and Polymer 3

npm mode is the new default mode that we recommend for all new projects. 

Bower mode is the "legacy" mode that should work the same way as in Vaadin 10 - 13. This mode will no longer be supported starting from Vaadin 15.

There will be an automated tool and documentation for how to migrate an existing application from Bower mode to npm mode, but those parts are still missing.
