### ISSUE TITLE
Unfullfilled requests under Edge

### ISSUE THREAD

**Issue by appreciated** [vaadin/flow#5408]
When running the V13 [Project Base](https://vaadin.com/start/latest/project-base) via `jetty:run` without any changes using Edge (44.17763.1.0). 
Six requests fail with a 404 Error Code:
* http://127.0.0.1:8080/frontend/bower_components/webcomponentsjs/%20[synthetic:util/global]		
* http://127.0.0.1:8080/frontend/bower_components/webcomponentsjs/%20[synthetic:util/defineproperty]
* http://127.0.0.1:8080/frontend/bower_components/webcomponentsjs/%20[synthetic:es6/symbol]
* http://127.0.0.1:8080/frontend/bower_components/webcomponentsjs/%20[synthetic:es6/util/makeiterator]
* http://127.0.0.1:8080/frontend/bower_components/webcomponentsjs/%20[synthetic:es6/util/arrayfromiterator]
* http://127.0.0.1:8080/frontend/bower_components/webcomponentsjs/%20[synthetic:es6/util/arrayfromiterable] 

This causes at least in the Project Base no further issues, but may cause some confusion when debugging an issue under Edge.

**Comment by pleku** [comment]
I think those are related to source maps, and I'm a bit unclear what we would want to or could do to those.

**Comment by pleku** [comment]
https://github.com/GoogleChromeLabs/tti-polyfill/issues/8
