### ISSUE TITLE
Spring boot applications built in production mode do not work in jar packaging

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#5416]
The usual way of packaging the Spring Boot applications is an executable jar file.

* Take `master` branch of a https://github.com/vaadin/skeleton-starter-flow-spring/ project.

* Build the project in the production mode:
`mvn clean package -Dvaadin.productionMode`

* Launch the application: 
`java -jar ./target/spring-skeleton-1.0-SNAPSHOT.jar -Dvaadin.productionMode`
or 
`java -jar ./target/spring-skeleton-1.0-SNAPSHOT.jar` (should work also due to the `flow-server-production-mode` dependency present in the project's dependencies.

* Open the application page.

Expected: an app is launched in a production mode.
Actual: the app is launched in a development mode, log contain:
```
===========================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
===========================================================
```

Network tab shows that instead of a bundle, separate js/html/css files are imported:
<img width="930" alt="image" src="https://user-images.githubusercontent.com/2690773/55558283-65b6d280-56f4-11e9-9e0f-a16b0a0cbe9d.png">

If you add `vaadin.productionMode = true` into the `application.properties`, rebuild the app in the production mode and relaunch it, everything works correctly:

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/2690773/55558470-d4942b80-56f4-11e9-8bbe-cd6aba512509.png">

**Comment by Legioth** [comment]
I suspect the reason is that the web fragment from `flow-server-production-mode` is either not included or then not picked up by the embedded server. One potential alternative approach would be to instead include a file such as `vaadin.production` on the classpath and supplement our logic for checking whether production mode is enabled to also look for the existence of that file.

**Comment by vcvuwac** [comment]
@SomeoneToIgnore
In my case, Order of Java options was the cause.
You shoule try to change the order as the following.
`java -Dvaadin.productionMode -jar ./target/spring-skeleton-1.0-SNAPSHOT.jar`
