### ISSUE TITLE
Java class which extend PolymerTemplate should have acces to Ids

### ISSUE THREAD

**Issue by bsutton** [vaadin/flow#5428]
When building a Java class that inherits from PolymerTemplate the java class should be able to access a component's ID using Element.getId();

Given that the PolymerTemplate is parsing the html template it will have access to all element id's and as such it should be easy to pull them into the Element.

The specific use case I have is in building a client side Wizard.
As the wizards transitions from page to page using javascript I need to notify the Java class what page I'm about to transition to.
The easiest way to do this is to have the javascript call the java class and pass the element id of the page being transitioned to.
The problem is that in the java code when it gets the id, Element.getId() returns an empty optional.

e.g

I have a polymer template with an element.

```
<wizard-controller>
<template>
	<div id="page1"></div>
	<div id="page2"></div>
	...
```

I have a java class that binds to a number of elements

```
@Id("page1")
Div page1;

@Id("page2")
Div page2;

```

The template sends me an event which includes the id of the element that generated the event

```
	this.$server._onNext("page1");
```

The java code accepts the onNext call and needs to match the passed Id to the appropriate page
```
	@ClientCallable
	public void _onNext(String pageId)
	{
		if (page1.getId().equals(pageId))
			page1.doSomething();
		else if (page2.getId().equals(pageId))
			page2.doSomething();
	}

```

The problem is that 'getId()' returns an empty optional, so the above code doesn't work.

Version: vaadin 12
Java 9
OS: ubuntu 18.04

**Comment by denis-anisimov** [comment]
closed by #8957
