### ISSUE TITLE
Document npm maven goals somewhere

### ISSUE THREAD

**Issue by bogdanudrescu** [vaadin/flow#5430]
Where shall we document them. Current production builds which works for bower are documented in https://github.com/vaadin/flow-and-components-documentation/blob/2.0/documentation/production/tutorial-production-mode-advanced.asciidoc and although npm goal(s) is(are) used for production too they aren't used only for production.

**Comment by pleku** [comment]
Should be covered as part of https://github.com/vaadin/flow/issues/5240
