### ISSUE TITLE
FormLayout fields dynamically added at runtime are not positioned correctly

### ISSUE THREAD

**Issue by martinisraelsen** [vaadin/flow#5446]
When I add a FormLayout/FormItem dynamically, some of the last elements are not always positioned correctly. Resizing the screen will cause the fields to be repositioned to their correct location.

I've seen this happen in Safari on V12 and V13. I have not been able to reproduce the issue on other browsers. Vaadin V10 and V11 doesn't appear to have this bug either. It's possible that it's a Safari bug rather than a Vaadin bug, but then I would expect it to also happen consistently with V10 and V11.

I have attached a Vaadin starter project that has the error. To reproduce the error, run the project with jetty:run and open the app in Safari. Click "Add line" until a row appears without the select field and the button.

Also included a few screenshots etc.

![Screen Shot 2019-04-09 at 8 29 56 AM](https://user-images.githubusercontent.com/6271003/55809673-f18d7d80-5aab-11e9-8711-2575dfbc90ca.png)
![Screen Shot 2019-04-09 at 8 30 19 AM](https://user-images.githubusercontent.com/6271003/55809689-f6eac800-5aab-11e9-8c30-115b1f87fe2c.png)

![formlayout position error](https://user-images.githubusercontent.com/6271003/55809824-36191900-5aac-11e9-8baf-e85bfbe7cfd3.gif)
[Vaadin-Appstarter.zip](https://github.com/vaadin/flow/files/3059561/Vaadin-Appstarter.zip)

**Comment by martinisraelsen** [comment]
Here's an updated app that exhibits both this issue and the layout issue reported in https://github.com/vaadin/flow/issues/4530 (which may or may not be the same).

To reproduce this layout issue, run with jetty, open in Safari. Click "Add User" followed by "Add User". The second time all fields are missing, but will show up if you resize the window or click inside one of the (missing) fields.

[Vaadin-Appstarter.zip](https://github.com/vaadin/flow/files/3077769/Vaadin-Appstarter.zip)

**Comment by martinisraelsen** [comment]
@ZheSun88 Perhaps this issue should be logged in https://github.com/vaadin/vaadin-form-layout? Are you able to move it over?

**Comment by ZheSun88** [comment]
@martinisraelsen Hi, sure I will move it there. :-)

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-form-layout #110](https://github.com/vaadin/vaadin-form-layout/issues/110) via [**ZenHub**](https://www.zenhub.com/)
