### ISSUE TITLE
Allow Flow application to work in application container in development mode

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#5452]
Before Flow 2.0, the Flow app could be run in the development mode in any servlet container.
Steps were the following:
* `mvn package` to build a jar/war/ear
* deploy it to the servlet container and open the app page

Everything works, can try it out on `beveragebuddy`, for instance.

Current Flow 2.0 does not allow this, causing errors described in a ticket: https://github.com/vaadin/flow/issues/5398

It would be nice not to introduce such regression and allow users to run the application in the development mode.

In order to do this, the following steps should be made:
* all file generation logic from `DevModeInitializer` should be moved into `flow-maven-plugin`.
This includes: `NodeUpdatePackages` and `NodeUpdateImports` classes, they should not be present in `flow-server` and moved entirely into `flow-maven-plugin`.

* The logic that starts the `DevModeHandler` should be reworked: it should not be started if the application is launched if the application is started in the servlet container

Also note that moving the file generation logic into `flow-maven-plugin` entirely will fix the https://github.com/vaadin/beverage-starter-flow/issues/334 issue.

**Comment by pleku** [comment]
Fixed with #5468
