### ISSUE TITLE
Precompress npm production files using Brotli

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#5453]
In Bower mode, the production build for Beverage Buddy produces a 874 KB `vaadin-flow-bundle-xyz.html` file, and then also a 230 KB gzip file and a 180 KB brotli file.

The npm production build only gives a `index.js` that is 964 KB, but no precompressed files. As gzipped, it would be 241 KB and with brotli, it shrinks to 185 KB.

We should enable precompressing to gzip and brotli also for npm builds.

(It might also be useful to look into why the npm files produced by webpack are slightly bigger than what we got out of `polymer build` with Bower, but that's probably a separate issue).

**Comment by qtdzz** [comment]
I've investigated the compression as a part of another task. I found some information which might be helpful for this issue:
- The default generated webpack.config needs to use the compression plugin to precompressed files (https://github.com/webpack-contrib/compression-webpack-plugin)
- Webpack only minifies the JS code but not the html inside tagged template literal, so we can minify all them in the same way as https://github.com/vaadin/base-starter-connect/pull/34

**Comment by pleku** [comment]
The gzipping has been enabled for production mode using compression-webpack-plugin, using Brotli would need additional work.

**Comment by pleku** [comment]
This should not be a big thing to do, but it is not a priority for now. If someone wants Brotli compression, please comment in this issue.

**Comment by mcollovati** [comment]
Closing because compatibility mode is not supported anymore in the maintained Vaadin versions.
In addition, Vite build provides brotli compression
