### ISSUE TITLE
Strong caching for npm production files

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#5456]
When using Bower mode, the production mode bundle file name contains a hash of the file contents. This makes it possible to serve the file with strong cache headers since the name will change if the contents change.

The same is currently not available for npm mode, where the name is always `index.js` (or `index.es5.js`).

**Comment by Artur-** [comment]
While strong caching is nice, the lack of the hash causes the old version of `index.js` to be loaded after you have deployed a new version (it is served with `Cache-Control: max-age=3600`). A hard reload works around the problem but you hardly can ask all your users to do a hard reload.

I would consider this a blocker for any application to be deployed to production.
