### ISSUE TITLE
not recognized error of 'node' despite of 'nodePath' prameter for production build

### ISSUE THREAD

**Issue by vcvuwac** [vaadin/flow#5463]
Production build fails if you configured `nodePath` and `yarnPath` in pom.xml and haven't add any `node` to PATH.
Not recognized error of `node` occurs on Windows because `yarn -v` is [executed](https://github.com/vaadin/flow/blob/master/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FrontendToolsLocator.java#L90) before `node` is [added to PATH](https://github.com/eirslett/frontend-maven-plugin/blob/master/frontend-plugin-core/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/ProcessExecutor.java#L119) by frontend-maven-plugin.

**Comment by joheriks** [comment]
Please upgrade to Vaadin 14 series. Yarn is no longer required for the production build.
