### ISSUE TITLE
StreamResource should have method for setting "Content-Disposition" response header

### ISSUE THREAD

**Issue by igormilina** [vaadin/flow#5471]
StreamResource currently have methods for setting response headers for contentType and cacheTime.

It would be useful if we could set content disposition also. This could, for example, be used to force download of dynamic content (instead of opening it in browser) with header: Content-Disposition: attachment; filename="filename.jpg".

Content disposition could be set with dedicated method ```setContentDisposition(String value)``` or more generic ```setHeader(String name, String value)```?

**Comment by walindner** [comment]
We used this feature/option in vaadin 8, too, and its hard to restructure code in the flow migration.
