### ISSUE TITLE
Update Bakery starter to Flow 2.0 and npm

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5487]
Splitting of the production build is split outside this #5241.

**Comment by manolo** [comment]
Blocked until bakery is updated to latest version of app-layout https://github.com/vaadin/bakery-app-starter-flow-spring/issues/769

**Comment by manolo** [comment]
There is a branch with the initial work https://github.com/vaadin/bakery-app-starter-flow-spring/tree/mcm/npm/migrate

**Comment by pleku** [comment]
AppLayout issue has been fixed so this is not blocked anymore.
