### ISSUE TITLE
OSGI loading view from a different bundle

### ISSUE THREAD

**Issue by Braus** [vaadin/flow#5491]
Version: Vaadin Flow 13

Hey everyone,

So I found an issue that extends an already existing issue. loading static resources in the designer currently doesn't work as expected. For this to work you need to put the resources (.html pages) in the root instead.

Not ideal but it works. for applications in one jar. However as an OSGI developer i'm not interested in putting all views in one project/jar. I want to put every view in a different jar. This has advantages as described by the OSGI standard.

So I created another project and added just a view and exported it as service. Then I go to the page through the URL and it seems to exist. it doesn't however load the .html page. I also found the reason why.

So we have bundle a with some .html files and bundle b with a .html file corresponding to that url, lets say if you go to localhost:port/example it loads bundle b with it's .html file. We expect that it loads the .html in it's own bundle, but instead it tries to get the .html file in bundle a. 

Going through this with the debugger we see that it only checks the context of bundle a and not b, (bundle b is a view which is displayed in the slot tag in bundle a).

Is it possible to solve this in the future and get a workaround for this issue now?

Kind regards,

**Comment by denis-anisimov** [comment]
Unfortunately I don't understand the ticket.

What does mean :  `but instead it tries to get the .html file in bundle a`.
Who is trying ?
I guess you are talking about polymer template files.
The files should be available via Servlet context and via HTTP.
And it's responsibility of the developer to make them available.
To make them available via HTTP one should implement https://github.com/vaadin/flow/blob/2.4/flow-osgi/src/main/java/com/vaadin/flow/osgi/support/OsgiVaadinStaticResource.java.
To make them available via Servlet context one may repackage all the resources in one bundle ( this is what you are trying to avoid as I understand) or customize the `ServletContext`  via `ServletContextHelper`  e.g.

Totally different way is used in Flow `6.0`  with npm mode.

I don'' see what can be done here.
If you still see issues please provide the exact steps to reproduce.
