### ISSUE TITLE
Cannot Redirect on Logout using Documented Logic

### ISSUE THREAD

**Issue by mpilone** [vaadin/flow#5492]
I'm attempting to redirect the user to a new page on logout using the logic from the Flow documentation:
```
Button button = new Button("Logout", event -> {
            // Redirect this page immediately
            ui.getPage().executeJavaScript(
                        "window.location.href='logout.html'");

            // Close the session
            ui.getSession().close();
        });
```

I can see the response to execute the JS sent to the browser, it is either not executed or something else is preventing it from actually navigating. It seems like either the documentation is wrong or there is a bug on the client side.

Configuration:
- Push: long polling
- Flow: 1.4.2
- Vaadin: 13.0.2
- Chrome: 73.0.3683.103

Test case attached.
[Bug 5492 Test Case.zip](https://github.com/vaadin/flow/files/3080999/Bug.5492.Test.Case.zip)

**Comment by TatuLund** [comment]
Has this been retested after #2210 and #4071 fixes?

**Comment by mpilone** [comment]
We retested this and the logic appears to work now with the other fixes.

However we did find that you'll still get an error/warning notification on the client side if you call ui.close(). For example:
```
ui.getPage().executeJs(String.format("window.location.href='%s'", url));
ui.getSession().getSession().invalidate();
ui.close();
```
I think it is OK to just remove the ui.close() call and let the UI get cleaned up eventually by the framework now that the session has been marked as expired but I'd like confirmation on that. There is a "// FIXME Send info to client" in UI.close() so maybe this is a known issue and the method should be avoided.

**Comment by mehdi-vaadin** [comment]
>I think it is OK to just remove the ui.close() call and let the UI get cleaned up eventually by the framework now that the session has been marked as expired but I'd like confirmation on that. 

It's correct. You don't need to call `UI::close` directly. When the session is destroyed all the associated UIs are closed by Vaadin.

**Comment by mehdi-vaadin** [comment]
### Acceptance criteria
- The [_Closing a Session_](https://vaadin.com/docs/v14/flow/advanced/tutorial-application-lifecycle.html#application.lifecycle.session-closing) section in the Application Lifecycle document should be fixed.

**Comment by denis-anisimov** [comment]
The documentation doesn't mention `UI::close` on logout.
There is only session close:
`ui.getSession().close();` 
And I didn't see any error on this code execution.

So it seems there is nothing to fix here: neither in Flow code (works as expected) nor in documentation since it shows the code which works.

Please let me know if I missed something.
