### ISSUE TITLE
Clarify PolymerTemplate limitations

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#5496]
The javadoc of `PolymerTemplate` states
```
Note that the injected element will have functional limitations on the server side.
```

What does this mean? How does this affect me? Is there more info available somewhere? The current form does not really give any info on what to do and what to avoid.

**Comment by mehdi-vaadin** [comment]
There is a section [Known limitations when using Templates](https://vaadin.com/docs/v14/flow/polymer-templates/tutorial-template-intro.html#known-limitations-when-using-templates) in the docs. We should add a link to it to PolymerTemplate's Javadoc.
