### ISSUE TITLE
Allow VaadinService to store attributes

### ISSUE THREAD

**Issue by vaadin-miki** [vaadin/flow#5500]
Needed for #4760 when using embedded web components.

Currently context-dependent attributes are stored by assuming `VaadinRequest` is a `VaadinServletRequest`, obtaining `ServletContext` from it and using `getAttribute` and `setAttribute`. This will not work with portlets.

Add `getAttribute` and `setAttribute` to `VaadinService`, so that attributes are stored in the context, e.g. through an internal wrapper that is created in the subclasses of `VaadinService`, or abstract methods in `VaadinService` that are overwritten in subclasses.

**Comment by pleku** [comment]
Decided that we don't need this for the portlets, there is already `VaadinContext` which stores the attributes.
