### ISSUE TITLE
DX test new theming proposal for p3

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5501]
Prerequisites:
- Candidate is familar with theming web components (polymer 2)
- Candidate can clone the https://github.com/vaadin/skeleton-starter-flow/tree/2.0
- Candidate has some IDE for editing Java & CSS

Task: 
Customize the application with the help of the documentation https://github.com/vaadin/flow-and-components-documentation/tree/mcm/npm/doc-theme/documentation/theme
1) change the application background color and font used
2) change the Vaadin text field default width to 20em (`--vaadin-text-field-default-width`)
(we are going to presume that things would work even though nothing is implemented (or add some boilerplate code for the starter))

**Comment by martaolszewskatusiek** [comment]
Results of DX tests: https://docs.google.com/document/d/1zzI-Ds8cQm1dwFioKIa11LbQ6kY5wOquvgRidOqd7BY/edit
