### ISSUE TITLE
Dynamically registered routes are not analyzed for frontend dependencies

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#5509]
Take https://github.com/vaadin/bookstore-starter-flow `2.0` branch with Flow 2.0

Open the sources, remove the annotation below the `// TODO remove this annotation, it's a stub added to override the https://github.com/vaadin/flow/issues/5509` line.
Build and launch the app, open the admin panel.

Expected: everything works
Actual: `ironListConnector.js` is missing

Reason: it does not get into `target/frontend/generated-flow-imports.js` webpack file that contains all the resources that we need to bundle.

This happens due to the logic in https://github.com/vaadin/bookstore-starter-flow/blob/2.0/bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/authentication/LoginScreen.java#L83 and https://github.com/vaadin/bookstore-starter-flow/blob/2.0/bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/MainLayout.java#L57 that registers the `AdminView` route dynamically.
Seems like the current Flow analyzer approach is capable of analyzing the static routes only (the ones that are annotated with `@Route` annotation): 
https://github.com/vaadin/flow/blob/2.0/flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendDependencies.java#L211

**Comment by Legioth** [comment]
A potential workaround for this case might be to add `@Route(value=VIEW_NAME, registerAtStartup = false)` to `AdminView`,

For a proper-ish fix, I guess we should ensure that class literals referenced in the analyzed bytecode should explicitly be inspected for inclusion when generating `main.js`.

There will probably also be other cases when, for one reason or another, the bytecode traversal logic misses something that should be considered. For such cases, I would propose that all `@JsModule` annotations that are found from the classpath but not reachable by traversing are dumped in a separate `mainUnreached.js` file or similar, and then `main.js` has a dynamic `import()` for that file that Flow's server-side would trigger loading whenever encountering any `@JsModule` that wouldn't be covered by the regular `main.js`. This kind of functionality is quite similar to what would be needed for #2946 and something more user-friendly beyond #5239.

**Comment by manolo** [comment]
Are there other ways to register routes?
For this case as @Legioth suggests we can add new routes to the scanner each time it detects in the bytecode a call to the method `setRoute(String, Class, Class) `

**Comment by Legioth** [comment]
In the generic case, the bytecode scanner cannot know anything about what is passed to any method such as `setRoute`. In some cases, the reference is indeed hardcoded, but there might also be cases when the `Class` instances are found using reflection.

The hardcoded cases should preferably be taken care of by the bytecode scanner not based on any special knowledge about `setRoute`, but rather by considering classes that are referenced as a class literal (i.e. `AdminView.class` in the source, regardless of in which context it's used).

**Comment by mehdi-vaadin** [comment]
The workaround should be added to the migration guide until this issue is fixed.
