### ISSUE TITLE
NpmPackage::version is confusing

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5552]
```
/**
     * Defines the NPM package version. By default the latest version is used.
     *
     * @return NPM package version
     */
    String version();
```

There is no default value for `version`. So which default is mentioned in the javadocs?
Should it have a default value or javadocs should be updated ?

**Comment by caalador** [comment]
The JavaDoc should be updated to reflect that version is a required field and also to note the accepted version fromat x.x.x or x.x.x-something
