### ISSUE TITLE
flow-server's transitive dependency closure-compiler breaks other project

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#5554]
`flow-server` uses `closure-compiler` dependency to parse Polymer 3 templates to get the template part out of them.

Current project set-up breaks Spring based applications.
Here's why:

The dependency has other transitive dependencies defined in its parent pom, such as Guava and Gson.
Also, `closure-compiler` jar has all *.class files from the transitive dependencies packed in the same jar: even if we exclude the transitive dependencies in Maven, they are not going anywhere from the jar.

We cannot have those transitive dependencies in the `flow-server`, since this might break some apps that have other version of Guava/Gson/etc. included.
We've already removed Guava from Vaadin some time ago.
Hence we exclude the transitive dependencies, but the packed *.class files stay in the jar.

Spring Boot detects those *.class files in the classpath and tries to initialize things, but fails, because of Gson version mismatch.

**Comment by SomeoneToIgnore** [comment]
As an alternative, google has `closure-compiler-unshaded` jar that has no extra packed *.class files.
But it's impossible to exclude the transitive dependencies from that one - those are actually used in the `closure-compiler` and it fails to work without them (the other version, with the `*.class` files works because of those files).

**Comment by caalador** [comment]
One suggestion to break clear from closure would be in:
https://github.com/vaadin/flow/tree/issues/5609_no_closure

At least the current spring project works with it.
