### ISSUE TITLE
Sometimes generated index.js can't be used in application

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5568]
Use this PR to check the behavior : https://github.com/vaadin/vaadin-button-flow/pull/129
(or just `master` branch `vaadin-button-flow` since it's merged).

Use __`demo`__  (not it tests module!).
Run jetty and open the demo.

There is a client side exception: `(ReferenceError) : Prism is not defined`.
It happens because `index.js` is not executed for some reason (it should define `Prism`).
Note that it's loaded (Http code 200).
But for some reason network tabs says `ERR_CONNECTION_RESET`.

I guess it's because its size: ~ 3MB.
May be it's too big for JS code and browser refuses to execute such a big script.

Anyway the demo is not working for whatever reason related to the generated `index.js`. 
I'm pretty sure this is a bug in NPM integration.

**Comment by bogdanudrescu** [comment]
This `index.js` has 3.2 MB, it's generated on `vaadin-combo-box-flow-integration-tests`, and browser loads it.

![image](https://user-images.githubusercontent.com/1041394/57063531-3fbd2780-6ccc-11e9-9ecb-a8d5c57dc5ac.png)

**Comment by manolo** [comment]
This is due to the problem described in #5638, closing in favor of the other
