### ISSUE TITLE
npm module is still in package.json after removing @NpmPackage

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#5569]
Steps to reproduce:
1) Get a fresh copy of Beverage Buddy
2) `mvn jetty:run`, notice that there is no `vaadin-charts` in `package.json`
3) Add `@NpmPackage(value = "@vaadin/vaadin-charts", version = "6.2.2")` to `MainLayout`
4) `mvn jetty:run`, notice that `vaadin-charts` has been added to `package.json`.
5) Remove the `@NpmPackage` annotation
6) `mvn jetty:run`, notice that `vaadin-charts` is still present in `package.json`.

Expected outcome is that `vaadin-charts` would no longer be present in the project after removing the annotation.

**Comment by pleku** [comment]
While this is confusing, to my understanding the `vaadin-charts` will not end up in the `index.js` as long as it is not used anymore in the app.

I wonder what will happen, if after the steps 1-6 from above, the user adds the charts again via `pom.xml` or another `@NpmPackage` but another version, will the `package.json` entry be updated or will it contain duplicate entry ?

**Comment by Legioth** [comment]
Yes, `index.js` will not be affected. What will be affected is that `node_modules` will be bigger and take longer to populate after doing a clean checkout. This might not be a problem for any single dependency, but those things have a tendency to accumulate.

I don't think the logic that updates `package.json` has any way of knowing whether a dependency was just updated or if it has been missing from `pom.xml` in between, so my assumption is that the entry in `package.json` would be updated in exactly the same way as if just updating to a newer version without removing in between.

**Comment by Legioth** [comment]
This was fixed by the change that introduced `@vaadin/flow-deps`.
