### ISSUE TITLE
mvn install fails when building npm project without internet connection

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#5575]
Running `mvn install` on an `npm` project which should not need to download/update dependencies fails, if the build machine does not have an internet connection.

### Steps:
1. get _skeleton-starter-flow_  and checkout branch _2.0_
2. run `mvn install` with internet connection
3. re-run `mvn install` without internet connection

#### Expected result:
Build is successful since all dependencies are up to date

#### Actual result:
```
[ERROR] Failed to execute goal com.vaadin:flow-maven-plugin:2.0-SNAPSHOT:build-frontend (default) on project project-base: Execution default of goal com.vaadin:flow-maven-plugin:2.0-SNAPSHOT:build-frontend failed: java.net.UnknownHostException: raw.githubusercontent.com: Unknown host raw.githubuser
content.com -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by manolo** [comment]
There is a known temporary hack which will be removed once all vaadin flow components are migrated to NPM https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdatePackages.java#L186

See https://github.com/vaadin/flow/issues/5535

**Comment by ujoni** [comment]
Alright. Closing.
