### ISSUE TITLE
`iron-list-flow` connector does not work in production mode

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#5578]
Take https://github.com/vaadin/bookstore-starter-flow/pull/122 or, if it's merged, take `2.0` branch.

Build and launch the app in the production mode:
`mvn clean install` in the root of the project
then, in the `bookstore-starter-flow-ui` module:
`mvn package -Dvaadin.productionMode`
`mvn jetty:run-exploded` 

Then open the admin page.

Expected: the page shows categories, `Add new category` button works.
Actual: no existing categories displayed, button does nothing.

No errors in the browser console, so needs investigation.

**Comment by bogdanudrescu** [comment]
Not reproducible.
