### ISSUE TITLE
webpack.config.js should update the project name in `webappFolder` on every run

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#5580]
Take vaadin/bookstore-starter-flow#122 (or 2.0 branch if it's merged), change the project name or project version, run the generation `mvn clean package`, open the webpack.config.js.

Expected: `webappFolder` is the same as the actual project output.
Actual: old version is stored.

This alsp has huge impact on the starters that can be named differently hence we need to have the file updated every time we rebuild the project.

**Comment by SomeoneToIgnore** [comment]
Had done a spike [PR](https://github.com/vaadin/flow/pull/5587) ([branch](kb/5580_always-update-webpack))

Results: current implementation is blocked by the fact that `mvn jetty:run` overwrites the correct config (generated by the plugin) with the wring data.

This happens due to the hard-coded default value:
https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java#L107

This value should be different and also depend on the project packaging different from `jar` and `war`.
This value is correctly determined by the `flow-maven-plugin`, but no current ideas on how to do this in runtime (considering the case when the project can be run from the ide, with no actual artifact present)

Needs further investigation.

**Comment by pleku** [comment]
>This alsp has huge impact on the starters that can be named differently hence we need to have the file updated every time we rebuild the project.

@SomeoneToIgnore But when the starter is generated, it will not have this file yet there ?

**Comment by SomeoneToIgnore** [comment]
No, not the first time.
But if the version or the project name is changed after the generation — nothing will be updated.

**Comment by pleku** [comment]
>But if the version or the project name is changed after the generation — nothing will be updated.

That makes it drastically less critical IMO as people get to decide the name for the starter when they start the project. But it is still quite inconvenient and annoying and should be fixed at some point.

**Comment by manolo** [comment]
The definitive solution should be `webpack.config.js` being created/updated in the `flow-maven-plugin#validate` goal. Therefore when jetty is run the file always exists and has been updated.

I would make the goal create the file if missing, or update if the output folder changed due tu version, packaging type etc.

In order to modify the correct line, I would make it easily to locate in the file, and meaningful enough so as the user knows that he should not change it.

```
// constant updated when flow-maven-plugin validate goal is run
mavenOutputFolderForFlowBundledFiles =  .... ;
```

the maven plugin should be configurable:
```
<configuration>
  <createWebpack>always, never, update</createWebpack>
</configuration>
```
