### ISSUE TITLE
Development mode could automatically refresh style updates

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#5617]
Vaadin could help developer so that it automatically applies new styles to the host page when run in development mode. This would allow developer to keep browser window in a separate screen and see results of their CSS change without leaving their developer environment and doing a manual reload.

A simple solution for this is presented in a community blog post: https://phauer.com/2019/vaadin-10-sass-integration-css-refresh/

**Comment by Legioth** [comment]
I think we'll get that functionality for free for npm mode if we implement #5538 since webpack would then take care of watching for changes and triggering reloads.

**Comment by pleku** [comment]
We've implemented #5538 but there is no automatic reload.

**Comment by Legioth** [comment]
Automatic reload was disabled at some point during development of the npm functionality since it interfered with our tests. Let's use https://github.com/vaadin/flow/issues/607 to track efforts for getting it back again.
