### ISSUE TITLE
JsModule for vaadin-icons is not loaded when using VaadinIcon enum

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/flow#5619]
When adding an icon with `VaadinIcon.CALENDAR.create()` js module for vaadin icons is not imported and as a consequence module for iron-icon is not loaded either.

As a workaround `new Icon(VaadinIcon.CALENDAR)` works

**Comment by Artur-** [comment]
The same for `Notification.show("Hello")` vs `new Notification()`
