### ISSUE TITLE
multiple @NpmPackage annotations on the same class are ignored

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#5628]
Steps to reproduce:
1) Get a fresh copy of Beverage Buddy
2) `mvn jetty:run`, notice that there is no `vaadin-charts` in `package.json`
3) Add `@NpmPackage(value = "@vaadin/vaadin-charts", version = "6.2.2")` to `MainLayout`
4) `mvn jetty:run`, notice that `vaadin-charts` has been added to `package.json`.
5) Add `@NpmPackage(value = "@vaadin/vaadin-cookie-consent", version = "1.1.1")` to `MainLayout`
6) `mvn jetty:run`, notice that `vaadin-cookie-consent` has not been added to `package.json`.

Expected outcome is that both `vaadin-charts` and `vaadin-cookie-consent` would be present in the generated `package.json` file.

**Comment by vlukashov** [comment]
Workaround: run `mvn package` first. It generates a correct `package.json` file, then run `mvn jetty:run` without issues.

**Comment by vlukashov** [comment]
`DevModeInitializerer` [queries](https://github.com/vaadin/flow/blob/70171337becee5def06ec16110397e4f874657e5/flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java#L53) for all classes annotated with `@NpmPackage`, but does not query for classes annotated with [`@NpmPackage.Container`](https://github.com/vaadin/flow/blob/70171337becee5def06ec16110397e4f874657e5/flow-server/src/main/java/com/vaadin/flow/component/dependency/NpmPackage.java#L42) which is actually set on a class when the `@NpmPackage` annotation is repeated.

**Comment by Legioth** [comment]
If that is the case, then you can as a workaround declare multiple dummy classes that each only has one `@NpmPackage` annotation.

**Comment by caalador** [comment]
**Acceptance criteria:**
- DevModeInitializer should also handle the `NpmPackage.Container.class`
- This should be tested with an IT test module where we have for instance 2 paper npm classes on the same class and they should then be available for use on runtime. This maven plugin for this module should only use the `prepare-frontend` goal.
