### ISSUE TITLE
Warn if the produced webpack artifact will not be used

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#5633]
If you happen to have a `src/main/webapp/build/index.js` file in the project, then it will overwrite the `build/index.js` artifact produced by webpack (flow-maven-plugin first generates output, then maven-war-plugin overwrites it with what is in src/main/webapp). While this is unlikely to happen very often, the earlier Flow versions generated the build output into `src/main/webapp` so for old projects you could run into this. 

It would be reasonable to warn the user that the project won't work if this happens.

#5631 would also help for this

**Comment by ujoni** [comment]
Implementation has changed and this should no longer be an issue.
