### ISSUE TITLE
@NpmPackage dependencies are not included in package.json

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#5653]
There seems to be multiple ways that `package.json` can be constructed. 

If you do `mvn install` which runs the maven plugin, then a correct package.json is generated with all the specified dependencies.

If you do `mvn jetty:run`, which does not run the maven plugin, you get a package.json without the specified `@NpmPackage` dependencies.

**Comment by Artur-** [comment]
Tested with https://github.com/Artur-/flow-lit but that is using a Flow build from the `lit-element` branch.

When running `jetty:run`, the output is
```
[main] INFO dev-updater - Creating a default /Users/artur/Documents/workspace/labs/flow-lit/package.json
[main] INFO dev-updater - Added @vaadin/vaadin-login@=1.0.0 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-button@=2.1.5 dependency.
[main] INFO dev-updater - Added @polymer/polymer@=3.1.0 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-app-layout@=2.0.0 dependency.
[main] INFO dev-updater - Added webpack-babel-multi-target-plugin dependency.
[main] INFO dev-updater - Added copy-webpack-plugin dependency.
[main] INFO dev-updater - Added webpack-cli dependency.
[main] INFO dev-updater - Added webpack dependency.
[main] INFO dev-updater - Added webpack-dev-server dependency.
[main] INFO dev-updater - Running `npm install` ...
```

then later on
```
[webpack] ERROR  - ERROR in ./main-view.js
[webpack] ERROR  - Module not found: Error: Can't resolve 'github-corner' in '/Users/artur/Documents/workspace/labs/flow-lit/frontend'
[webpack] ERROR  -  @ ./main-view.js 40:0-23
[webpack] ERROR  -  @ ../target/frontend/generated-flow-imports.js
[webpack] ERROR  -  @ multi ../node_modules/webpack-dev-server/client?http://localhost:60798 ../target/frontend/generated-flow-imports.js
```

**Comment by Artur-** [comment]
If I run `mvn clean install` instead, then the output is
```
[INFO] Creating a default .../flow-lit/package.json
[INFO] Added github-corner@=2.0.3 dependency.
[INFO] Added lit-element@=2.1.0 dependency.
[INFO] Added @vaadin/vaadin-login@=1.0.0 dependency.
[INFO] Added @vaadin/vaadin-button@=2.1.5 dependency.
[INFO] Added @polymer/polymer@=3.1.0 dependency.
[INFO] Added @vaadin/vaadin-app-layout@=2.0.0 dependency.
[INFO] Added webpack-babel-multi-target-plugin dependency.
[INFO] Added copy-webpack-plugin dependency.
[INFO] Added webpack-cli dependency.
[INFO] Added webpack dependency.
[INFO] Added webpack-dev-server dependency.
[INFO] Running `npm install` ...
```

**Comment by Artur-** [comment]
Seems to me like at runtime, Flow only scans classes annotated with `@Route` and not any other component class annotated with `@NpmPackage` because if I move the `@NpmPackage` annotations to the `@Route` class, then it works as expected

**Comment by manolo** [comment]
I checked out the project the `github-corner-java` and installed it, checked out `lit-element` rebased it and installed it, finally checked out the `flow-lit` (needed to change the corner version to snapsthot)

- `mvn clean jetty:run` and it worked ok
- `mvn clean package` then I changed to target folder and run `java -jar path_to_jetty/jetty-runner.jar flow-lit.war` and it run in legacy bowerMode, failing.
- Forcing npm by running `java -Dvaadin.bowerMode=false -jar path_to_jetty/jetty-runner.jar flow-lit.war ` worked fine

**Comment by manolo** [comment]
@Artur- any issue with this, I think it does not happen anymore can I close?

**Comment by Artur-** [comment]
Seems to work now
