### ISSUE TITLE
@JsModule annotation is ignored for classes implementing HasErrorParameter

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#5659]
Consider the following `PolymerTemplate`

    @Tag("my-template")
    @JsModule("src/my-template.js")
    public class MyTemplate extends PolymerTemplate<TemplateModel> implements HasErrorParameter<NumberFormatException> {
        @Override
        public int setErrorParameter(BeforeEnterEvent beforeEnterEvent, ErrorParameter<NumberFormatException> errorParameter) {
            return 0;
        }
    }

If not referenced elsewhere, the template `my-template.js` is not included in the build.

### Steps to reproduce

Add the class above to a project and build it

### Actual results

The template `my-template.js` is not included in the build

### Expected results

The template `my-template.js` is included in the build

**Comment by denis-anisimov** [comment]
This should not be an issue anymore in the latest Flow (`2.1.0.rc1`).

- In dev mode the full classpath scanning is used which discover all the annotation in the CP regardless if reachability
- in the production mode byte code scanner is still used but in case component has imports which has not been discovered by the byte code scanner the fallback chunk will be loaded and component will work.

To be able to get it working for `2.0`  releases I may just add `HasErrorParameter` interface as an entry point. That may increase scanning time.
