### ISSUE TITLE
Fix Java 11 build tests

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#5668]
FrontendDependenciesTest all fail on `setup()` with 
`Can not set static final java.lang.String field com.vaadin.flow.server.frontend.FrontendDependencies.LUMO to java.lang.String`

 NodeUpdateImportsTest and  NodeUpdatePackagesTest all fail on
```
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at com.vaadin.flow.server.frontend.NodeUpdateTestUtil.getClassPath(NodeUpdateTestUtil.java:60)
```

Acceptance criteria:
- Flow sources should compile using Java 11
- Tests should be run

**Comment by manolo** [comment]
@caalador  Shouldn't this be closed apparently the PR fixing this is already merged
