### ISSUE TITLE
Make OSGi work with npm mode

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5671]
We have tests for OSGi.

Currently tests are executed in bower mode.
We need to check npm mode (at least one way: dev or production but may be both).

We should create an additional TC build task for NPM mode or run both NPM and bower in the same TC build task to validate both modes at the same time.

**Comment by denis-anisimov** [comment]
Prerequisite is #5689

**Comment by denis-anisimov** [comment]
Acceptance Criteria:
- There is one more `pom` file in `flow-tests/servlet-containers/felix-jetty` project which allows to test NPM mode
- At least one (if not possible to test both) mode should be tested: `dev` or `production`.
- There is one more step in TC nightly build which runs this validation in addition to validation in bower mode (may be another TC nightly build job : what suites best).
- Some tests which don't make sense for NPM mode should be disabled (there is already `IgnoreNPM` category for this).
- Most of the tests should be run via TC task and should not fail.

Considerations:
- There are many issues at the moment with IT tests.
- The first couple of issues are: https://github.com/vaadin/flow/issues/5726 and https://github.com/vaadin/flow/issues/5727
- Once they are fixed there is one more issue : https://github.com/vaadin/flow/issues/5728
- The issues above are required to be able to make the (existing) tests running for OSGi
- The current impl of `Dev mode` is not aware of OSGi at all. `DevModeInitializer`  is a `ServletContainerInitializer` which has general issues in OSGi but it should work somehow currently. The problem in its `onStartup`  method which does this : `context.getServletRegistrations().values();`. The context here is the fake one and there is no any servlet registration so it just doesn't do anything. It either needs to be fixed or completely refactored/rewritten taken into account: https://github.com/vaadin/flow/issues/5735 and https://github.com/vaadin/flow/issues/5736.
- The main test bundle (jar) : `flow-test-root-context-ui.jar` can't be used for testing since it doesn't contain `frontend` folder with js module files (it has old `frontend` folder which contains HTML files). There is already `pom-npm.xml`  in `test-root-context  module which is intended to be used for testing NPM. I suggest to modify it to produce required artifacts for testing in NPM in OSGi: generate another bundle with `frontend` folder in the proper location (the currently known information for me is: it should be inside `META-INF/resource` folder inside jar). The resulting bundle should be used in another `pom-npm` for `felix-jetty`  module as a dependency. I have already branch that does it. Ask me details in case of any questions.
- Would be good to test both dev and production mode (with different pom files) if it's possible. But : first we need fixes for above bugs, we need dev mode working in OSGi. So may be another ticket is required for another mode.

**Comment by pleku** [comment]
Since we are also interested in making other changes for OSGi in the near future, we are postponing OSGi support for _npm mode_ in Vaadin 14 - meaning that it will be added in a later minor.

Existing Vaadin 12-13 OSGi projects can move to Vaadin 14 by keeping using the `bowerMode`. 

We have planned to improve the OSGi support for 14 a later minor release, related to:
- Fix enRoute issues and validate using it https://github.com/vaadin/flow/issues/4968 
- Allow using Vaadin components as OSGi services https://github.com/vaadin/flow/issues/5125
- Add examples of #5125 https://github.com/vaadin/base-starter-flow-osgi/issues/25

**Comment by denis-anisimov** [comment]
This is done with proper OSGi support (except dev mode).
`2.5`  has a feature branch where this is implemented.
`6.0`  Flow has separate osgi support in `osgi` repo and tests are done there.

There is a separate ticket for dev mode .
So I consider this as done.
