### ISSUE TITLE
Fix how to apply @Theme for template .js imports that are not declared in Java

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5672]
Related to https://vaadin.slack.com/archives/C6X43FE8M/p1557746735382800

The issue description is:

- Assume you have your own template file which uses some client side component (let it be `vaadin-button`).
- You don't have any `vaadin-button` usage on the client side.
- So your P3 template file is the only place where `vaadin-button` is used and it's imported there via `import '@vaadin/vaadin-button/src/vaadin-button.js';`
- Now you have `@Theme(Lumo.class)`  annotation in your project and you want to apply `Lumo` theme.

The result is: the button will be unthemed because it's imported from `vaadin-button/src/vaadin-button.js`  path. But Lumo theme path is `vaadin-button/vaadin-button.js` .
The expected result is: button is themed whcih means its path is somehow rewritten to themed path.

**Comment by Legioth** [comment]
One approach that would also be useful outside of the context of Flow would be to have a webpack plugin or similar that rewrites all imports regardless of where they are located.

**Comment by manolo** [comment]
problem is how to handle specific user logic in the `String translateUrl(String url)`

**Comment by Legioth** [comment]
In that case, we would not support `translateUrl` defined in Java, but instead offer something similar based on JavaScript.

**Comment by manolo** [comment]
ok, if we can change the API so as the user needs to change their custom theme hacks with something that works in JS the best option obviously is a plugin in webpack able to do the work based in some file that java leaves in generated folder `target/frontend/app-theme-handler.js`

**Comment by denis-anisimov** [comment]
The current suggestion to fix this is:

- There is logic which goes through all `@JsModule` annotations (scans everything) and collect the paths. Those paths will be written in the end into some file.
- There should be already logic which rewrites the path according to theme (but it only works for the "top level path" which is inside `@JsModule`  annotation).
- For some paths (should we care about all the paths or only about "custom paths" which contains custom templates ? ) we should parse the template file.
- The parser should have custom logic and care only about top lines which are `import` statements (of course it should ignore comments).
- For every imported path we should check whether it's possible to apply theme to the path (so the resulting file exists on FS). If there is themed path then write it also in the same way as on the step 2.
- Note: don't rewrite the template file itself anyhow. Only add one more rewritten path into the generated file.

**Comment by bogdanudrescu** [comment]
One solution to this may be to set `window.Vaadin.Theme` in the beginning of `generated-flow-imports.js` and then in `@vaadin/vaadin-button/vaadin-button.js` to use it and webpack should pick the correct import:

```
if (window.Vaadin.Theme) {
  import './theme/' + window.Vaadin.Theme + '/vaadin-button.js';
} else {
  import './theme/lumo/vaadin-button.js';
}
```

Anyway I think it's worth setting `window.Vaadin.Theme` orso.

**Comment by web-padawan** [comment]
@bogdanudrescu please not that `import` statements in ES modules do not work that way:

1. The `import` statement only accepts strings, no dynamic parts allowed

2. The `import` statement must be on the top level and can't be inside `if`.

So you could only do that with dynamic imports:
```js
import('./theme/' + window.Vaadin.Theme + '/vaadin-button.js');
```

**Comment by denis-anisimov** [comment]
Sorry , solution for what ?
There is already a PR for that.
