### ISSUE TITLE
Update Embedding Vaadin tutorial for Flow 2.0

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#5673]
The current Embedding Vaadin tutorial material is written mostly for bower-mode Vaadin. While the outward changes aren't large, there are a few changes.

- Importing a js module
- Theme discovery (The maven-plugin fails the build in npm mode, if multiple themes are discovered. This is how bower mode works, but for a time, it was different for the npm mode)
- Normal npm project structure changes

**Comment by ujoni** [comment]
Seems like the ticket for updating the embedding tutorial as a result of the dx testing has gone missing.

The gist of it was, that the first part of the tutorial (a full example) is too extensive and does not describe the feature - just how to do it. The example should either be split up a little, or an introduction page should be added to the tutorial.

Another missing piece of information is the limitations of the embedding feature. For example, navigation does not work in the embedded apps. These limitations should be outlined by the introductions (or soon after) so that the user can evaluate whether this feature is something they can use without doing an extensive investigation themselves.

**Comment by ujoni** [comment]
> "you can embed Flow to into a non-Vaadin Application."

1) Is it so that it wouldn't work in a V8- app? If so, why?
2) When should we expect to have Flow-into-Flow support? Asking for a friend

DO:
Both 1 and 2 are doable. Should be clarified. Should an example be provided?

**Comment by ujoni** [comment]
### Acceptance criteria:
- Tutorial is updated to match Flow 2.0 embedding feature:
  - Importing js module
  - API usage in tutorial matches the current implementation (`configureInstance` is now protected).
- A subsection details how embedding works in compatibility mode
- Tutorial outlines the limitations involved when embedding a Vaadin application in a separate subsection

**Comment by denis-anisimov** [comment]
@ujoni , just want to confirm the current state of SS web components with NPM:
- there is any difference between embedding app in production mode and dev mode, right ?
- as a result the production mode section can be removed completely (for npm and moved into compatibility tutorial for bower mode).
- there are no differences in themes (in bower mode and npm mode): this is verified. We have the same logic now : if application declares two different themes then build fails in NPM.

**Comment by ujoni** [comment]
- From user's point of view, there is no difference between development mode and production modes, when embedding applications - the components are included the same way.
- Correct, the production mode bits can be moved to compatibility chapter
- Yeah. Though I doubt the duplicate theme is verified with a test currently, since it fails at build time for all but bower-development mode which fails at startup, I think :\
