### ISSUE TITLE
Add IT tests for starters 

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#5686]
Flow starter projects need integration tests for validation whether V13 bower mode and V14 npm mode work.

https://bender.vaadin.com/project.html?projectId=Flow_StarterTests&tab=projectOverview

### Step 1)
Define what is acceptable coverage for the starters, so that the implementation is repeatable.
**Result:**
Acceptance criteria which can be used for all the starters' ITs
- Has IT profile so that normal users do not require Testbench license

Scavenge tests from here: https://github.com/vaadin/flow-starters and then remove the repository.

### Step 2)
Add ITs to the master branch.

Starters:
- [x] flow base starter - Joni
- [x] spring base starter - Johannes
- [x] cdi base starter - Johannes
- [x] component add-on starter - Johannes
- [x] beverage buddy - Mehdi, Johannes
- [x] bookstore - Johannes

### Step 3) 
Pick the ITs to V13 branch, and make sure the tests work

Starters:
- [x] flow base starter
- [x] spring base starter
- [x] cdi base starter
- [x] component add-on starter
- [x] beverage buddy
- [x] bookstore

**Comment by ujoni** [comment]
My current branch for adding IT and pom stuff on skeleton-starter:
https://github.com/vaadin/skeleton-starter-flow/tree/5686_add_ITs

It has a problem:
Running `mvn verify` does not work. It receives "404 - No context on this page matched or handled the request". It was working at one point, but then I attempted to move some of the build configurations under the `integration-tests` profile - and it broke again. 

My aim was to exclude `com.vaadin.starter.skeleton.it` from the normal IT test run, an include it back in the profile. Having the the testbench dependency in the profile will break compile step, which is not a nice experience. My understanding is that the compile step does not require testbench license, so it should be kind of fine to have the dependency mixed with the other dependencies, as long as the tests themselves are not ran outside of the profile.

**Comment by joheriks** [comment]
My stab at it for component starter:
https://github.com/vaadin/component-starter-flow/tree/5686-integration-tests

I added the `maven-failsafe-plugin` and jetty start-stop execution under the `integration-tests` profile. In this way  tests with suffix `*IT` are only run when that profile is active. Anything that could be wrong with this approach?
