### ISSUE TITLE
Validate version bump from 13 to 14

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#5687]
The user wants to update from Vaadin 13 to Vaadin 14 and expects that everything keeps working.

Create TeamCity (bender) validation tasks which catch potential breakages in this process.

Suggestion:
- Checkout V13 branches of starters that have ITs
- Bump version to 14
- Run ITs

Note: make sure that both `dev` and `prod` modes work

**Steps**
- Cherry-pick tests for v13 branches
- Add bender task for each starter so that it 
  - they trigger after framework snapshots
  - checks out branch v13
  - uses 14.0-SNAPSHOT of platform

**Comment by ujoni** [comment]
Project is here:
https://bender.vaadin.com/admin/editProject.html?projectId=Flow_VersionBumpValidationFrom13to14

**Comment by bogdanudrescu** [comment]
We need to pick the ITs into V13 branch for starters.
