### ISSUE TITLE
Page::addHtmlImport adds html imports in Flow 2.0 npm mode

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#5692]
The `Page` class's methods related to html imports give no indication that they are not supported in npm mode. They simply add the requested import onto the page.

The methods should
- be deprecated (as with anything related to html imports in Flow 2.0)
- either
  - throw an exception
  - or use the same work-around as for `@HtmlImport` annotation (for now)

**Comment by pleku** [comment]
>Mark the method as deprecated to be removed in v15
This is a bit problematic since it is still perfectly fine to use the method in bower mode. We didn't deprecate the `@HtmlImport` annotation either, so lets not do it for this method either. Forcing users to use deprecated code is not nice.

**Comment by ujoni** [comment]
### Acceptance criteria:
- In compatibility mode, should work as before
- In npm mode, throw an exception which informs the user that they can either
  - add an annotation instead of dynamic loading
  - run in compatibility mode
