### ISSUE TITLE
Grid broken in 14.0.0.b1?

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#5696]
I tried to migrate the Simple App (Vaadin Starters) to V14 beta1. The application starts up as normal (beside the bower / npm warning).

After logging in, the UI gets redirected to the default page. There the grid is missing and a bunch of error messages pop up.

Some console error examples (Chrome)
```
client-5B44EA78EA65C9AA94E2163A65E14674.cache.js:196 TypeError: Cannot read property 'ItemCache' of undefined
KB @ client-5B44EA78EA65C9AA94E2163A65E14674.cache.js:196
gridConnector.js:11 Uncaught TypeError: Cannot read property 'ItemCache' of undefined
    at gridConnector.js:11
client-5B44EA78EA65C9AA94E2163A65E14674.cache.js:983 Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
qt @ client-5B44EA78EA65C9AA94E2163A65E14674.cache.js:983
client-5B44EA78EA65C9AA94E2163A65E14674.cache.js:196 (TypeError) : Cannot read property 'initLazy' of undefined
KB @ client-5B44EA78EA65C9AA94E2163A65E14674.cache.js:196
...
```

**Comment by ttsanton** [comment]
I want to chime in and say that I am encountering this issue as well and posted about it on the [Fourm](https://vaadin.com/forum/thread/17665681/14-0-0-alpha4-grids-not-loading-itemcache-is-undefined-and-0-connector).

**Comment by ericmartinezr** [comment]
I had the same problem with 14.beta1, and I found a workaround in the [pom.xml](https://github.com/vaadin/beverage-starter-flow/blob/master/pom.xml#L95) example

**Comment by stefanuebe** [comment]
@ericmartinezr works as a temporary solution, thanks for the idea :)

**Comment by Artur-** [comment]
https://github.com/vaadin/vaadin-grid-flow/pull/650 should solve this
