### ISSUE TITLE
Add an annotated class with the shrink dependency to platform `vaadin.jar` and `vaadin-core.jar`

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5700]
`vaadin.jar` and `vaadin-core.jar` should include a class annotated with NpmPackage

```
package com.vaadin.shrinkwrap;
import com.vaadin.flow.component.dependency.NpmPackage;
@NpmPackage(value = "@vaadin/vaadin-core-shrinkwrap", version="14.0.0-beta1")
public class VaadinCoreShrinkwrap {
}
```

Then we can remove the hardcoded shrink in `TaskUpdatePackages` 

Adding this plugin to the pom https://github.com/vaadin/platform/blob/master/vaadin-core/pom.xml should work

```
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/*.java</include>
                </includes>
            </resource>
        </resources>
```

**Comment by pleku** [comment]
One important aspect that the description missing is _why_ it should be done ? Why should it be necessary to add it ?

**Comment by manolo** [comment]
The reason to have this in platform are:
-  flow automatically pins versions for all vaadin components by depending on `vaadin.jar` or `vaadin-core.jar`
- we don't need to maintain any hardcoded dependency in the flow code
- versions are automatically updated when platform release happens
