### ISSUE TITLE
DnD data

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#5707]
In V8 it was possible to set a object as "drag data" in the start event, that was then available in the drop event of the target. It's not necessary to have dnd working in a Vaadin application, but makes life easier, since the outside does not need to know anything about dragged data (so no extra fields needed).

Wish is to have at least simple methods `void setDragData(Object)` / `<T> T getDragData()` for server side purposes.

**Comment by pleku** [comment]
There are the `setData` methods in `ComponentUtil` for this purpose. Another alternative is to store things to the `VaadinSession`. 
https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java#L524

The `flow-dnd` add-on module, which is available as `2.0.0.rc1` but not added to the platform (`vaadin-core`), uses the `setData` and provides API in the `DragStartEvent` and `DropEvent` to access the data https://github.com/vaadin/flow/blob/master/flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragStartEvent.java#L70
https://github.com/vaadin/flow/blob/master/flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DropEvent.java#L81
