### ISSUE TITLE
JsModule annotation should allow omitting the .js

### ISSUE THREAD

**Issue by mhosio** [vaadin/flow#5708]
Currently the JsModule annotation requires the .js -suffix. However, when importing modules in front-end projects, you can omit that. Could you make flow add that suffix in case the specified file name does not exist?

Example of an import without the .js suffix that works in a front-end project
https://www.webcomponents.org/element/@openlayers-elements/maps

Expected behavior: Both formats should work
```
@JsModule("@openlayers-elements/core/ol-map.js")
@JsModule("@openlayers-elements/core/ol-map")
```

Actual behavior: Only the first one is allowed.

**Comment by Artur-** [comment]
I don't think we should do anything else with the string than copy it to a file read by webpack. In a JS module, you can also write `import "@vaadin/vaadin-button"`, and it imports the main file from the module. You can also customize this with the webpack config and there is no way for an external party to know about that configuration

**Comment by manolo** [comment]
I think because of the converstions we used to do  from `HtmlImport` to `JsModule` when we didn't have components migrated there were some regular expressions applied to remove `.html` and add `.js`, will investigate this
