### ISSUE TITLE
Project should not generated files in the @vaadin namespace

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#5710]
The `@vaadin` namespace is meant for modules published by Vaadin. The project files are not published by Vaadin so they do not belong inside `node_modules/@vaadin`

**Comment by manolo** [comment]
What is the technical issue here? what should be instead ?

**Comment by bogdanudrescu** [comment]
Should we at least have only one entry point instead of 2, `flow-deps` and `flow-frontend`? `flow-deps` should be enough.

**Comment by bogdanudrescu** [comment]
Changing `@vaadin` structure from flow is somehow a semantic issue regarding the scope of the folder which as @Artur- mention as `is meant for modules published by Vaadin`.
