### ISSUE TITLE
flow-maven-plugin:build-frontend takes a lot of time until a first message appears

### ISSUE THREAD

**Issue by bogdanudrescu** [vaadin/flow#5712]
`mvn clean install -DskipTests` on `vaadin-grid-flow`. After the first log line referring `build-frontend` it takes quite some time until the log starts to continue. Scanning classes is surely be the reason of that time, but at least some progress should be indicated, unless we optimise the scan time.

```
[INFO] --- flow-maven-plugin:2.0-SNAPSHOT:build-frontend (default) @ vaadin-grid-flow-integration-tests ---
[INFO] Added "@vaadin/vaadin-ordered-layout": "1.1.0" line.
[INFO] Added "@vaadin/vaadin-grid": "5.4.0" line.
[INFO] Added "@vaadin/vaadin-button": "2.2.0" line.
[INFO] Added "@vaadin/vaadin-date-picker": "4.0.0" line.
[INFO] Added "@vaadin/vaadin-text-field": "2.4.3" line.
[INFO] Added "@vaadin/vaadin-combo-box": "5.0.1" line.
[INFO] Added "@vaadin/vaadin-core-shrinkwrap": "v14.0.0-alpha3" line.
[INFO] Added "@vaadin/vaadin-list-box": "1.1.0" line.
[INFO] Added "@vaadin/vaadin-checkbox": "2.2.7" line.
[INFO] Added "@vaadin/vaadin-item": "2.1.0" line.
[INFO] Added "@vaadin/vaadin-context-menu": "4.3.5" line.
[INFO] Added "@vaadin/vaadin-radio-button": "1.2.0" line.
[INFO] Added "@vaadin/vaadin-lumo-styles": "1.5.0" line.
[INFO] Added "@vaadin/vaadin-material-styles": "1.2.2" line.
[INFO] Updated npm /Users/bogdan/work/workspace-vaadin/flow-component-base/vaadin-grid-flow/vaadin-grid-flow-integration-tests/target/frontend/package.json.
[INFO] Running `npm install` ...
```

**Comment by ujoni** [comment]
Validate, that something useful is printed right away, then close.

**Comment by manolo** [comment]
It should not be executed `mvn clean install -DskipTests` in grid but `mvn clean install -DskipTests -Drelease` so as integration tests are not build nor installed.

Anyways, right now,  when maven plugin runs `npm install` there is a message informing that the command is going to be executed, and the standout is directly read and written to the console, so user can see the progress of npm.

Related with scanning, it takes only 953ms, and now there is a previous message  that informs that scanning is going to happen.

When running demo or IT in dev-mode the webpack server imforms that it’s going to run, there is not progress until the command outputs the entire message, but there is a previous message `Running webpack … ` informing that it’s going to be run, and the process normally takes few seconds.

Therefore this is not an issue anymore
