### ISSUE TITLE
Application (IT tests) doesn't work in dev mode 

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5728]
Related to #5726 

The same steps to reproduce except that branch from PR #5725 should be used.
This branch contains a workaround which allows to avoid 404 for resources in the `build` directory.

So
- Build Flow.
- go into `flow-tests/test-root-context`.
- run `mvn -f pom-npm.xml jetty:run`
- Open e.g. `http://localhost:8888/view/com.vaadin.flow.uitest.ui.template.EmptyListsView`.

The result is : `index.js` has status `failed`(in the Chrome network tab). So it's not executed. And view doesn't contain the expected content (doesn't really matter what the expected content is): `empty-list` is empty and has no any shadow root inside it.
The expected result: `index.js` is successfully loaded and executed. `empty-list` element is properly initialized.

**Comment by denis-anisimov** [comment]
Node that tests are passing with a workaround in PR #5725:
https://teamcity.vaadin.com/viewLog.html?buildId=49256&tab=buildResultsDiv&buildTypeId=Flow_FlowPullRequestsExtendedWithNpm

**Comment by bogdanudrescu** [comment]
index.js 404 is duplicate of #5740 and #5726

However after applying the fix in https://github.com/vaadin/flow/pull/5779 I still get this:
```
Uncaught ReferenceError: Polymer is not defined
    at eval (MixinInjectsElement.js?bc1e:5)
    at Module../MixinInjectsElement.js?babel-target=es6 (index.js:1428)
    at __webpack_require__ (index.js:20)
    at eval (generated-flow-imports.js?b518:1)
    at Module.../target/frontend/generated-flow-imports.js?babel-target=es6 (index.js:1092)
    at __webpack_require__ (index.js:20)
    at index.js:84
    at index.js:87
```

**Comment by denis-anisimov** [comment]
With the current state of the source code : 
- all JS are loaded successfully
- `MixinInjectsElement`  JS module had an error which broke the `index.js` (which is not `index.js` anymore) load. Once it's fixed everything works fine.

So I'm closing this as worksforme. (referenced PR os closed and its branch is removed).
