### ISSUE TITLE
CSS custom properties for Lumo, defined in a JS module, get overridden by the Lumo import

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#5729]
### Description

When creating a JS module to override some Lumo CSS properties, similarly to how Beverage Buddy and Bakery create stylesheets, and importing it in the root layout using `@JsImport(...)`, the properties are overridden by Lumo.

The load mode of the annotation does not seem to make a difference.

### Steps to reproduce

Create the file `/frontend/styles/styles.js` with the following content

    import '@polymer/polymer/lib/elements/custom-style';
    const $_documentContainer = document.createElement('template');
    
    $_documentContainer.innerHTML = `
    <custom-style>
        <style>
            html {
                --lumo-primary-color: red;
            }
        </style>
    </custom-style>
    `;
    
    console.warn("Working");
    document.head.appendChild($_documentContainer.content);

And import it in a view (or root layout) as such

    @Route("")
    @JsModule(value = "styles/styles.js")
    public class MainView extends VerticalLayout {}

### Actual results

`--lumo-primary-color` has the value defined in Lumo.

### Expected results

`--lumo-primary-color` has the value defined in our `styles.js`.

### Versions:

Platform 14.0.0.beta1
Chrome 73.0.3683.103
Windows 10

**Comment by jouni** [comment]
If you want to override a custom property, you should also make sure it’s available before you try to override it.

So, as a workaround, you should import `'@vaadin/vaadin-lumo-styles/color.js';` in `styles.js`.

**Comment by ujoni** [comment]
**Triage - Proposed solution:**
Reorder lines in  `generated-flow-imports.js` so that imports generated from `Theme`s are before all imports that can potentially alter those themes. Collect different annotations to separate sets and write the sets to the import file in the correct order.
