### ISSUE TITLE
NPM mode doesn't work with a servlet mapped to non-root URI

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5740]
Steps to reproduce:
- checkout https://github.com/vaadin/skeleton-starter-flow
- open project and add a new servlet which is mapped to some non root URI (see below an example)
- run the project (e.g. using a command line `mvn jetty:run`)
- open the correct URL (which has correct mapping) in your browser
- check that neither `index.js` nor `webcomponents-loader.js` are loaded (404 for both).

Expected: both URLs work and as a consequence the application works
Real result: URLs don't work and the application is broken.

```
@WebServlet("/xx/*")
public class MyServlet extends VaadinServlet {

}
```

**Comment by manolo** [comment]
As conclusion of a design discussion we conclude that we should fix this in this way
- Make webpack put files in the classpath.
- The recomended location is in a tree structure inside `/VAADIN`
- Make vaadin servlet for static files  serve files from the class path to cover this
- Add some rules for not serving anything else that the bundled files
- Make sure that appropriate headers are set when serving `.cache.` suffixed files

**Comment by denis-anisimov** [comment]
Be aware of https://github.com/vaadin/flow/issues/5795 also: if we serve the generated static resources via servlet (as a solution for this ticket) then #5795 will be fixed as well (check it via IT tests which currently override the web app folder: just don't override it)
