### ISSUE TITLE
WARNING about using frontend in JsModule is wrong

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5750]
Use e.g. Combobox repo.
https://github.com/vaadin/vaadin-combo-box-flow/blob/master/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java has no @JsModule with `frontend` as a schema.
But if you try to build integration test module it will give a warning:
```
Do not use the 'frontend://' protocol in '@JsModule', changing 'frontend://comboBoxConnector.js' to './comboBoxConnector.js', please update your component.
```

As mentioned above: there is `@JsModule("frontend://comboBoxConnector.js")` but there is 
`@Js@JavaScript("frontend://comboBoxConnector.js")`.

The warning should not be misleading at least.
And it seems it's just wrong: there should not be such warning at all.

**Comment by pleku** [comment]
I'm pretty sure this has been changed already months ago.
