### ISSUE TITLE
Add method to get URL of target with parameter

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#5755]
Now that [`Router#getUrl(Class, Object)`](https://vaadin.com/api/platform/13.0.7/com/vaadin/flow/router/Router.html#getUrl-java.lang.Class-T-) has been deprecated, there is [`RouteRegistry#getTargetUrl(class)`](https://vaadin.com/api/platform/13.0.7/com/vaadin/flow/server/RouteRegistry.html#getTargetUrl-java.lang.Class-) but no overload with a parameter.

**Comment by heruan** [comment]
This is what the deprecate `Router#getUrl` method does:

```java
RouteRegistry registry = router.getRegistry();
RouteConfiguration configuration = RouteConfiguration.forRegistry(registry);
String url = configuration.getUrl(MyTarget.class, myParam);
```

Why it has been deprecated? It's a useful shortcut to get an URL from the current registry.

**Comment by TatuLund** [comment]
Is this related to this problem https://github.com/vaadin/flow/issues/5388 ?

**Comment by heruan** [comment]
I see these as two distinct issue, but when dynamic routes were introduced many things changed and I have to readapt my logic.

This issue is for knowing why that method has been deprecated and which is the right way now to get the URL of a component with parameters.

**Comment by caalador** [comment]
The deprecation is due to the realisation that Router is basically an internal class with implementation details. 
Also the recommended way to use the new registries is through the `RouteConfiguration` helper class in all cases.
Basically you would want to run `RouteConfiguration.forSessionScope().getUrl(MyTarget.class, myParam)` (if you are inside a request thread and VaadinSession.getCurrent() exists)

**Comment by heruan** [comment]
Thank you @caalador for the feedback. I was confused since I've found a non-deprecated path to the same login in a deprecated method, so if `Router` is an internal class then also `UI#getRouter` should be deprecated.

> Also the recommended way to use the new registries is through the `RouteConfiguration` helper class in all cases.

This answers my question then, thank you!
