### ISSUE TITLE
Push don't works after redirection to the annotated page

### ISSUE THREAD

**Issue by abierlerxdev** [vaadin/flow#5759]
I found out that the the ```@Push```-Annotation is not working in a Route-Compoent, after getting redirected from another Route-Component that doesn't has a ``@Push``-Annotation

### How to reproduce
The MainView:
```
@Route("main")
@Push
public class MainView extends Div
{
	
	private final Button button;
	
	public MainView()
	{
		// a simple Button that runs handleClick
		button = new Button("Test", this::handleClick);
		
		this.add(button);
	}
	
	private void handleClick(final ClickEvent<Button> event)
	{
		final UI currUI = UI.getCurrent();
		
		// Run something async
		CompletableFuture.runAsync(() ->
		{
			
			// Simulate work e.g. fetching data from database
			try
			{
				Thread.sleep(1000);
			}
			catch(final InterruptedException e)
			{
				e.printStackTrace();
			}
			
			// Access the UI where the call was coming from
			currUI.access(() ->
			{
				// Execute JS
				UI.getCurrent().getPage().executeJavaScript("console.warn('******HI Timing: "+LocalTime.now()+"');");
			});
			
		});
	}
}
```

The LoginView:
```
//No push annotation here
@Route("")
public class LoginView extends Div
{
	public LoginView()
	{
		final Button b = new Button("I logged in successfully. Bring me to Main",this::handleLoginClick);
		
		this.add(b);
	}
	
	private void handleLoginClick(final ClickEvent<Button> event)
	{
		UI.getCurrent().navigate(MainView.class);
	}
}
```

Deploy the code onto a server.
Open your browser and open the browser console with ``F12``

### When it works as it should
Directly goto the MainView
1. Navigate to ``<DeploymentURL>/main``
2. After the page loaded clear your browser console
3. Click "Test"
4. After a waiting second the browser log should contain the following
![grafik](https://user-images.githubusercontent.com/45384811/58307373-bdbdab80-7dfe-11e9-9202-847d5f88bef9.png)

### When it doesn't works as it should
First goto the LoginView then get programmatically redirected to MainView
1. Navigate to ``<DeploymentURL>`` (-> ``LoginView``)
2. Click "I logged in successfully. Bring me to Main"
3. You get redirected to ``<DeploymentURL>/main`` -> ``MainView``
4. After the page loaded clear your browser console
5. Click "Test"
6. Now no JavaScript Message occurs in the console log:
![grafik](https://user-images.githubusercontent.com/45384811/58307627-8996ba80-7dff-11e9-8e80-b0594b8fe458.png)
7. But after clicking the button a secound time you see the message from the first click:
![grafik](https://user-images.githubusercontent.com/45384811/58307687-c8c50b80-7dff-11e9-92e3-0546a040e593.png)
8. So push is not enabled even though ``@Push`` is written clearly over ``MainView``

### Workaround
Write ``@Push`` over ``LoginView``

### Testing Environment
* Vaadin-Flow 13.0.7
* Java 8
* Windows 10 / WildFly 15
* Tested browsers:
   * Mozilla Firefox 67
   * Google Chrome 74

**Comment by ujoni** [comment]
Verified on `13.0.7` and `14.0-SNAPSHOT (18.6.2019)`

**Comment by Legioth** [comment]
As a workaround, you can programmatically enable push in the views that need it by running `UI.getCurrent().getPushConfiguration().setPushMode(PushMode.AUTOMATIC)` in some appropriate place.

**Comment by denis-anisimov** [comment]
The bug is still valid for the latest version.
