### ISSUE TITLE
Webpack started from servlet does not include exported web components

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#5771]
When running `mvn install` on a project with exported web components, `target/frontend/generated-flow-imports.js` contains
```
import './product-listing.js';
import './product-details.js';
```
or similar imports for each component.

If you only run e.g. `mvn jetty:run`, then `target/frontend/generated-flow-imports.js` is missing the imports (the files are not generated either) and no exported web component works

**Comment by ujoni** [comment]
It seems that I am slow on the uptake - this issue is due to #5655, if the expected behavior in the ticket is correct.

**Comment by Artur-** [comment]
How is this related to multi module projects? This is related to the fact the the web component files are only ever generated from the plugin and not when running webpack from the servlet

**Comment by ujoni** [comment]
Sorry. In my haste to course correct the potential fix to a more sensible place, I only saw the parallels in completely ignored the multi-module part of the ticket.
