### ISSUE TITLE
Don't try to resolve routes from /build

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#5773]
There are a couple of locations, e.g. `/VAADIN/static/` and the Bower-mode frontend directories, that are only supposed to contain static-ish files and never any navigation targets. For those URLs, Flow has custom logic that serves the servlet engine's own 404 page instead of using Flow's 404 view.

`/build/` (or whatever location has been configured to be used instead) should also be handled in this way when npm mode is used.

**Comment by pleku** [comment]
Probably related to https://github.com/vaadin/flow/issues/5590

**Comment by mehdi-vaadin** [comment]
One solution could be moving `/build/` to `VAADIN` or `/VAADIN/static/`.

**Comment by Legioth** [comment]
Another solution would be to just add a check for `/build` to the same place that currently checks for `/VAADIN/static`.
