### ISSUE TITLE
/frontend serves the / navigation target in npm mode

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#5775]
Using Flow 2.0 rc2 with either the Skeleton starter or Beverage Buddy in npm mode, opening http://localhost:8080/frontend/ in the browser shows the `@Route("")` view. Other similar URLS, e.g. http://localhost:8080/frontend2/ show the expected Flow 404 page.

**Comment by OlliTietavainenVaadin** [comment]
This happens in Bower mode as well, and in earlier versions.

**Comment by abierlerxdev** [comment]
With production mode enabled, there is also a problem when you open <BASE-URL>/myapp/frontend (<-- no / at the end!)
![grafik](https://user-images.githubusercontent.com/45384811/60243614-e4b54480-98b8-11e9-9db5-538cc180d6b2.png)

**Comment by ujoni** [comment]
Released in `1.4.7` and `2.0.3`
