### ISSUE TITLE
@NoTheme not working in Vaadin 14 beta2

### ISSUE THREAD

**Issue by jouni** [vaadin/flow#5777]
Steps to reproduce:

1. Download project base from vaadin.com/start (“Plain Java, if that makes any difference)
1. Add the `@NoTheme` annotation to `MainView.java`
1. Run `mvn jetty:run`, go to `localhost:8080`

**Expected result**: Button without any styles.

**Actual result**: Lumo themed button.

The same steps produce the expected results with Vaadin 13.

**Comment by caalador** [comment]
This is interesting in that `@NoTheme` defines itself as `Defines that the class shouldn't log for missing theme.`
where as the actual functionality is `if (!AnnotationReader.getAnnotationFor(target, NoTheme.class).isPresent()) { return Lumo if present; }`

When fixing this also the NoTheme javaDoc should be updated to reflect this functionality as now it says that it just doesn't log an exception for missing theme.

**Comment by denis-anisimov** [comment]
This is very good point !!!!
I've also been confused by this fact all the time but forgot to ask/create an issue.

**Comment by pleku** [comment]
This will be covered by #5762

**Comment by denis-anisimov** [comment]
PR https://github.com/vaadin/flow/pull/5788 should fix this.
But this PR ( at least currently) doesn't contain an IT test for `@NoTheme` case.
IT test should be provided.

**Comment by denis-anisimov** [comment]
Blocked by #5788
