### ISSUE TITLE
In case a classloader doesn't load abstract classes super NpmPackage is not found

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#5780]
When running the frontend dependencies not from maven the compute packages misses classes that have the `NpmPackage` defined in a superclass only in cases where the classloader only loads non abstract classes.

With the test classes:
```
    static class ComponentExtending extends GeneratedComponent {

    }

    @Tag("component-extends")
    @NpmPackage(value = "@vaadin/component-extended", version = "2.1.0")
    static abstract class GeneratedComponent extends Component {

    }
```

It would be expected that the test:
```

    @Test
    public void should_visitSuperNpmPakageAnnotations() throws Exception {
        FrontendDependencies deps = create(
                FrontendDependenciesTestComponents.ComponentExtending.class);
        assertEquals(1, deps.getPackages().size());
        assertTrue(deps.getPackages().containsKey("@vaadin/component-extended"));

        assertEquals("2.1.0", deps.getPackages().get("@vaadin/component-extended"));
    }

```
 would work as the NpmPackage is defined and should be found as an annotation.

This is especially critical when many of our own components have the annotation in the abstract GeneratedComponent class so the class visitor will never flag those as having the `NpmPackage` annotation.

Also NpmPackage should probably be marked as `@Inherited`

**Comment by pleku** [comment]
>When running the frontend dependencies not from maven the compute packages misses classes that have the NpmPackage defined in a superclass only in cases where the classloader only loads non abstract classes.

So, _not from maven_ means projects that are not using Maven ? Or just running unit tests from IDE ?

>Also NpmPackage should probably be marked as @Inherited

The case for `@JsModule` is that it is not inherited, but documented as "the possible parents or interfaces are scanned for this annotation anyway".

**Comment by Legioth** [comment]
I'm quite sure "classloader" is the wrong term here. I suspect this is related to classpath scanning performed for our `ServletContainerInitializer`s or the corresponding logic in Spring.

If adding `@Inherited` makes non-abstract subclasses be considered in those cases, then that seems like an appropriate fix.

**Comment by caalador** [comment]
With adding the ingerited I get for the `ClassPathScanningCandidateComponentProvider` in Spring the expected (probably all?) classes, but then the problem is that the parent classes are not added to the Set<Class<?>> that is then used through the DefaultClassloader implementation which does find the annotation, but then the visitor doesn't get the annotation as it's not on the main class.

**Comment by Legioth** [comment]
So we need to also explicitly pass all super classes to the bytecode visitor?

**Comment by Legioth** [comment]
Even more safe might be to ensure the visitor always looks at super classes since I suspect there might also be other similar cases with other annotations.

**Comment by caalador** [comment]
I also think the visitor should check super classes.
