### ISSUE TITLE
Component's JsModule not discovered if used in UIInitListener in VaadinServiceInitListener

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/flow#5792]
In bakery the offline banner is added during UI Init
```
@Override
public void serviceInit(ServiceInitEvent event) {
    event.getSource().addUIInitListener(uiEvent -> {
        final UI ui = uiEvent.getUI();
        ui.add(new OfflineBanner());
        ui.addBeforeEnterListener(this::beforeEnter);
    });
}
```

Actual result is
>Frontend dependencies have not been analyzed for com.vaadin.starter.bakery.ui.components.OfflineBanner

Adding a dummy reference in a route workarounds the issue

**Comment by ujoni** [comment]
### Acceptance criteria:
- `@JsModule` annotations are discovered from `VaadinServiceInitListeners`
- Make init listeners a special case, adjacent to `@Route` scanning
