### ISSUE TITLE
Delay calling property change listeners for exported web components until the initial values are known

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#5794]
When you have

`<simple-chat room='foo'>` on your web page and

```
    public static class Exporter extends WebComponentExporter<SimpleChatComponent> {

        public Exporter() {
            super("simple-chat");
            addProperty("room", DEFAULT_ROOM).onChange((component, value) -> {
                component.setRoom(value);
            });
        }
```

You would expect `setRoom` to be called only once with the value `"foo"`. 

If you have
```
<simple-chat>
```

You would expect `setRoom` to be called only once with the value `DEFAULT_ROOM`.

Right now `setRoom` is called once or twice, depending on whether the attribute has a value or not. This makes it impossible to know when you should e.g. add the chat history to the web component. If you do it when `setRoom` is called, you will populate `<simple-chat room='foo'>` with the chat history for `DEFAULT_ROOM` first, and then correct it to the `foo` history.

**Comment by Legioth** [comment]
Slightly related is that it seems that there's currently two separate round trips: One that informs the server that a custom element has been attached and another one that delivers the property values. If both those would be included in the same round trip, then this issue would most likely also be easier to fix, in addition to avoiding some overhead.

**Comment by caalador** [comment]
**Acceptance criteria:**

- Element attach should send all property values.
- Initial value should never be default if a client-side value has been set as an attribute.

**Comment by ujoni** [comment]
For who's looking:

The line [WebComponentExporter.java#L362](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/WebComponentExporter.java#L362) is responsible for instantly pushing in the default value for properties, when the `Component` and its binding is created.
