### ISSUE TITLE
Verify a workaround and fix components to avoid a warning about frontend protocol used in @JavaScript

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5797]
See the original ticket: https://github.com/vaadin/flow/issues/5615
There is a suggestion from Leif to make a workaround in our components: 

```
I believe that those could be fixed simply by doing like it says in the warning message. Something like @JavaScript("./gridConnector.js") would be exactly what we want for npm mode. For Bower mode it would be interpreted as frontend://./gridConnector.js since that's the default protocol. That in turn would most likely do exactly the same as the current frontend://gridConnector.js.
```

So this needs to be verified that it works (no warning if it's applied).
And if it works go through all the components that shows this warning and fix them (normally the components have a connector)

**Comment by manolo** [comment]
Tested the workaround in a component, and in `bower-dev-mode` it works fine, but in `bower-prod-mode` it still tries to get the file from the server causing a `not-found` error in browser console.

Therefore, removing the warning from server when the `frontend://` protocol is in a `JavaScript` annotation, keeping it when in a `JsModule`.
