### ISSUE TITLE
jetty:run hot-reload does not work in starters after IT addition

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5799]
e.g. in skeleton-starter-flow it might be broken at this point https://github.com/vaadin/skeleton-starter-flow/pull/167/files#diff-600376dffeb79835ede4a0b285078036L107

**Comment by joheriks** [comment]
Jetty `scanInterval` configuration parameter again set to a positive value `skeleton-starter-flow`, `beverage-starter-flow` and `bookstore-starter-flow`.
