### ISSUE TITLE
Make `npm-dev-mode` tests work in CI

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5809]
For some random reason tests in npm-dev-mode do not work in TC.
Some causes might be ports in docker images, resources, etc.
An identified issue is that we should stop webpack servers when the test finishes, instead of when the vm exits

**Comment by denis-anisimov** [comment]
NPM dev mode is working for me ( at least for one specific test) on TC.
The only issue which I've seen is another ticket: https://github.com/vaadin/flow/issues/5805
But the latter ticket doesn't relate to this one anyhow except you should be aware of that.

My test for themes is working on TC in dev mode fine.

**Comment by manolo** [comment]
This should not be closed until we fix what is said in the description:
`An identified issue is that we should stop webpack servers when the test finishes, instead of when the vm exits` 

We cannot have as many webpack-dev-server running in CI as tests run until the entire reactor finishes , and even after that they could keep listening. They will cause lack of resources in CI nodes, and problems in multi-pom modules, or modules that need to be packaged or installed after testing because webpack is changing filesystem content while running
