### ISSUE TITLE
NPM: If Lumo theme is the default theme then its styles are not applied.

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5812]
Steps to reproduce:
- make a project with Lumo in classpath
- use the code below 
- see the result in the browser
- expected result: link has not black color (the black color is the default without theme).
- the actual result : link has black color.

```
@Route("")
public class NoThemeComponentView extends Div {

    public NoThemeComponentView() {
        Anchor anchor = new Anchor();
        anchor.setText("link");
        add(anchor);
    }
}
```

`Lumo`  theme should be applied since it's default theme. In fact there is at least one `custom-style` element added into the `head`. But there should be many of them and apparently the style for the link is not applied.

The difference can be easily seen with this source code:
```
@Route("")
@Theme(Lumo.class)
public class NoThemeComponentView extends Div {

    public NoThemeComponentView() {
        Anchor anchor = new Anchor();
        anchor.setText("link");
        add(anchor);
    }
}
```

The results should be exactly the same. But they are not.

**Comment by ujoni** [comment]
It would seem that components under `com.vaadin.flow.component.html.*` are not treated as themed components. Adding a a `Button` onto the page will enable `Lumo` theme, even if there is no `@Theme` annotation. I think the class scanner treats a components without themed components as empty pages.

**Comment by ujoni** [comment]
My initial guess seems to be flawed. I am trying out things in `skeleton-starter-flow` and as I iterated earlier, adding `Button` to the layout will fix the theming of the `Anchor`. But the resulting `generated-flow-imports.js` is
```
const div = document.createElement('div');
div.innerHTML = '<custom-style><style include="lumo-color lumo-typography"></style></custom-style>';
document.head.insertBefore(div.firstElementChild, document.head.firstChild);
import '@vaadin/vaadin-ordered-layout/theme/lumo/vaadin-vertical-layout.js';
import '@vaadin/vaadin-button/theme/lumo/vaadin-button.js';
```
only the the last row is different when comparing to a layout with only the `Anchor` present.

Also, `FrontendDependencies` class does carry `Lumo` theme within itself when only `Anchor` is present, so the theme is lost some time later.

**Comment by ujoni** [comment]
Adding the theme annotation `@Theme(Lumo.class)` to the view brings the following additions to the `generated-flow-imports.js` file:
```
import '@vaadin/vaadin-lumo-styles/typography.js';
import '@vaadin/vaadin-lumo-styles/style.js';
import '@vaadin/vaadin-lumo-styles/spacing.js';
import '@vaadin/vaadin-lumo-styles/sizing.js';
import '@vaadin/vaadin-lumo-styles/icons.js';
import '@vaadin/vaadin-lumo-styles/color.js';
```
These are almost the same imports that `vaadin-button-styles.js` contains.

**Comment by ujoni** [comment]
Alright, the problems is as follows:
When `FrontendDependencies` crawls through all the `@Route` annotated classes, it calls `private EndPointData visitClass(String className, FrontendClassVisitor.EndPointData endPoint)` on all those annotated classes. If the annotated class is also annotated with `@Theme` (and the route is root) it will recursively call `visitClass` on that theme, which eventually adds all the extra fluff into `generated-flow-imports.js`.

If we are rolling with default theme, this will not happen. Instead, `void computeApplicationTheme(HashMap<String, EndPointData> endPoints)` will simply call `getLumoTheme()` and assign that as the selected theme, without visiting the theme class.

To fix this, `FrontendDependencies` would need to visit the loaded default theme class.
