### ISSUE TITLE
Show a warning when `webpack.config.json` is an old version

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5823]
When `prepare-build` is run, we should show a notice to the user if the `webpack.config.json` template has important changes since the last time the user generated the file.
This can be done by adding a version tag to the generated file and template to keep in sync.

Related with https://github.com/vaadin/flow/issues/5790

**Comment by Legioth** [comment]
This assumes two things:

1. The user will actually notice the warning (see https://github.com/vaadin/flow/issues/5820). 
2. The user knows what to do based on the warning. This is especially tricky for those users who have their own customizations of the config file.

**Comment by caalador** [comment]
Issue was resolved by #5790 as we now have webpack.generated.js that is kept up to date at all times.
