### ISSUE TITLE
Scripts containing // comments are not correctly handled when generating the web component UI

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#5838]
It seems like newlines are stripped from script content when creating the UI for embedded web components. If the normal bootstrap page contains 
```
<script>
// Hello
console.log("hello");
</script>
```
then the generated bootstrap will contain
```
<script>
// Hello console.log("hello")
</script>
```

which is not exactly the same thing

**Comment by Legioth** [comment]
How is this reproduced? What do you to to end up with `//` comments in the script content?

**Comment by Artur-** [comment]
I have no idea how to reproduce this and it is not important to me in any way so let's close it
