### ISSUE TITLE
Unable to run `npm install` with latest Ubuntu LTS Node+npm

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#5841]
From https://github.com/vaadin/full-stack-starter/issues/26

Ubuntu LTS ships with 
node v8.10.0 and npm v3.5.2

if you try `npm install` with these, it fails because the generated file `target/frontend` cannot be installed for the reason `No version provided in package.json`. If this is the only reason that you need a newer npm, maybe we should rather add the version in the generated file

**Comment by caalador** [comment]
Should investigate if the only failure with using an old version of npm is the missing version in the generated package.json

**Comment by Artur-** [comment]
By adding 
```
"version": "1.0.0"
```

to `target/frontend/package.json`, I am able to start Beverage Buddy on Ubuntu with default node and npm
