### ISSUE TITLE
GridPro throws typerror when clicking within Grid nut not on a row

### ISSUE THREAD

**Issue by Braus** [vaadin/flow#5845]
Hi everyone,

I'm using GridPro, but I had to swap it with a normal Grid because GridPro is sensitive to throw typerrors as seen in the attached image. This bug occurs either when I click the GridPro many times or when I click below the last row in the grid.

I create the GridPro using java.

![image](https://user-images.githubusercontent.com/48833301/58944783-cad58580-8782-11e9-8bd0-a65fd05a15b1.png)

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/vaadin-grid-pro-flow #57](https://github.com/vaadin/vaadin-grid-pro-flow/issues/57) via [**ZenHub**](https://www.zenhub.com/)
