### ISSUE TITLE
Call "bower" mode Vaadin 13 compatibility mode

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#5856]
It would be much clearer if "bower mode" was called Vaadin 13 compatibility mode and instead of saying
```
====================================================================
Vaadin is running in BOWER mode.
This mode will be unsuported in future Vaadin versions.
====================================================================
```
the message would be something like
```
====================================================================
Running in Vaadin 13 (Flow 1) compatibility mode

This mode uses webjars/Bower for client side dependency management and HTML imports for dependency loading.

The default mode in Vaadin 14+ (Flow 2+) is based on npm for dependency management and JavaScript modules for dependency inclusion.

See http://vaadin.com/docs for more information
====================================================================
```

**Comment by joheriks** [comment]
Code referring to Bower mode , e.g. `DeploymentConfiguration#isBowerMode`, should also get at least their JavaDocs updated that Bower mode equals compatibility mode.

**Comment by pleku** [comment]
The docs link on the log message could be eg. `https://vaadin.com/docs/v14/flow/migration-14/overview.html` once the migration guide for 14 is written.

**Comment by enver-haase** [comment]
Great, that removes the "unsuported" typo in 14.0.0.beta2 too.
