### ISSUE TITLE
Make WebComponentExporter.configureInstance non-abstract

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#5857]
Currently, you need to provide an empty
```
        @Override
        public void configureInstance(WebComponent<BlogAdmin> webComponent, BlogAdmin component) {
        }
```
for all exported simple components. 

The method should be made optional and the constructor/class javadoc should tell about the method and what it can be used for.

**Comment by denis-anisimov** [comment]
The decision was: 
- make method `protected`.
- keep it `abstract` (so people have to implement it).
This is fixed via the PR.
