### ISSUE TITLE
Fix failing tests in NPM mode

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5865]
There are a number of `flow-test-root-context` tests which are failing in NPM mode (see below):

LongPollingMultipleThreadsIT, 
            LongPollingPushIT, RouteNotFoundIT, WebComponentsIT, EmptyListsIT, 
            InjectedElementInsideMixinBehaviorIT, TemplateHasInjectedSubTemplateIT, 
            TemplateInTemplateIT, UpgradeElementIT, DebounceSynchronizePropertyIT, 
            ChangeModeIT, LoadingIndicatorIT,TimingInfoReportedIT, ValueChangeModeIT.

- Investigate reason
- Fix the test of broken functionality
- Enable the test

**Comment by denis-anisimov** [comment]
Currently they are excluded in  `pom-npm.xml` via  `<exclude.it.tests>` property.

The PR is : https://github.com/vaadin/flow/pull/5859

**Comment by bogdanudrescu** [comment]
https://vaadin.slack.com/archives/C6RAXJATF/p1560157648058100
