### ISSUE TITLE
tooltipsText is plain text only and is not displayed if isEnabled = false

### ISSUE THREAD

**Issue by vlipovetskii** [vaadin/flow#5903]
I leverage this code 
`var HasElement.tooltipsText: String?
    get() = element.getProperty("title")
    set(value) {
        element.setProperty("title", value)
    }
`
to set tooltipsText for the components e.g. button.
I want to explain why a button is disabled.
Unfortunately,  tooltipsText is not displayed if the component (e.g. button) is disabled.

Please find the sample project https://github.com/vlipovetskii/vaadin-issue-0003-prj
and 
screenshot

![disabled component-tooltips are not displayed](https://user-images.githubusercontent.com/19362031/59452655-dfff8380-8e16-11e9-8a17-ae293b3e450f.png)

**Comment by pleku** [comment]
It seems that the native button indeed shows the tooltip when disabled https://jsfiddle.net/pqx1cgsm/

If our `Button` / `<vaadin-button>` works differently, then this issue should be in that particular component repository.

@vlipovetskii what components are you not seeing the tooltip in when using `setEnabled(false)` from Flow ?

**Comment by vlipovetskii** [comment]
This is Button / <vaadin-button>. How to move the issue to Button repository ?

**Comment by pleku** [comment]
Issue moved to [vaadin/vaadin-button #132](https://github.com/vaadin/vaadin-button/issues/132) via [**ZenHub**](https://www.zenhub.com/)
