### ISSUE TITLE
Thread locking issue when setting DataCommunicator sorting

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#5908]
I'm experiencing a locking issue, ~~but just in Chrome (75.0.3770.80)~~: when loading a page the first time, all runs smoothly; the second time, the request hangs. ~~This does not happen with Firefox or Safari.~~

Chrome network tab on refresh:

<img width="1918" alt="Screenshot 2019-06-14 at 12 46 32" src="https://user-images.githubusercontent.com/851745/59504158-978da780-8ea2-11e9-9587-b1fd705c6022.png">

JProfiler thread view (in red the locked thread):

<img width="943" alt="Screenshot 2019-06-14 at 12 38 57" src="https://user-images.githubusercontent.com/851745/59504169-a07e7900-8ea2-11e9-9795-7a872d41d308.png">

Eclipse stack for the locked thread:

<img width="692" alt="Screenshot 2019-06-14 at 12 39 59" src="https://user-images.githubusercontent.com/851745/59504193-b55b0c80-8ea2-11e9-81ed-ad698ea5f0ea.png">

I'm on V14 beta3 (it happens also with beta2). How can I further debug this?

**Comment by Artur-** [comment]
That looks like a normal UI thread waiting for the session lock before starting to process the request. A thread dump would probably tell you who is holding the lock and what that thread is doing

**Comment by heruan** [comment]
Thank you for the hint! So I've found this happens after a Spring async event-listener push something to the UI thread. For example:

```java
@Route
public class MyComponent extends Div {

    public MyComponent(MyService myService) {
        var flux = service.flux();
        // This is org.github.legioth.accessor.Accessor
        Accessor.ofConsumer(this::refresh)
                .withSubscriberAndUnsubscriber(flux::subscribe, Disposable::dispose)
                .bind(this);
    }

    public void refresh(MyBean bean) {
        // does things
    }
}

@Service
public class MyService {

   private final Set<FluxSink<MyBean>> sinks = ConcurrentHashMap.newKeySet();

    public Flux<MyBean> flux() {
        return Flux.create(sink -> {
            sinks.add(sink);
            sink.onDispose(() -> sinks.remove(sink));
        });
    }

    @Async @TransactionalEventListener
    public void myEventListener(MyEvent event) {
        var myBean = event.getSource();
        sinks.forEach(sink -> sink.next(myBean));
    }
}
```

When the event listener is invoked, it correctly updates the UI but then any subsequent request hang. I guess I need to release something somewhere on my own?

**Comment by Legioth** [comment]
So what happens here is that there is that the `exec-6` thread tries to acquire the lock for a session that is currently locked by some other thread. At the same time, that other thread is not releasing that lock. This might be either because that thread is waiting for something else (e.g. a lock that is held by the `exec-6` thread) or because that other thread has "forgotten" to release the lock.

In either case, the key to figuring out what goes on is to figure out which other thread is holding on to that lock and then as a next step why. If you do a thread dump of the JVM, you will see something like `waiting on condition [0x000070000e45b000]` for the blocked thread. You can then search for the same identifier in the thread dump to find which thread is holding that lock. With a little luck, the current stacktrace of that thread will tell you what's going on. If that is not the case, then you have a case of forgetting to release a lock. In that case, you have some ugly detective work to do to find out where that happens. Even then, it might be helpful to know the name of the thread to slightly limit the search.

**Comment by heruan** [comment]
Thank you @Legioth! I've got the dump and I see

```
"http-nio-8080-exec-10" #58 daemon prio=5 os_prio=31 cpu=1534.28ms elapsed=793.58s tid=0x00007ffd471da800 nid=0x12c03 waiting on condition  [0x000070000cc86000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.2/Native Method)
	- parking to wait for  <0x00000007085e7540> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.2/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.2/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.2/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.2/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.2/ReentrantLock.java:267)
	at com.vaadin.flow.server.VaadinService.lockSession(VaadinService.java:796)
	...
```

but unfortunately `0x000070000cc86000` isn't anywhere else on the dump. I guess the lock is related to the push operation, right? I've really no clue where to start my detective work to find who's not releasing, since I'm not locking anything 🕵

**Comment by Legioth** [comment]
I might have mislead you. You need to look for the other identifier, i.e. `parking to wait for  <0x00000007085e7540>`.

**Comment by heruan** [comment]
Great! Then I have that identifier referenced as "Locked ownable synchronizers" at

```
"http-nio-8080-exec-2" #50 daemon prio=5 os_prio=31 cpu=8007.27ms elapsed=793.58s tid=0x00007ffd4922e800 nid=0x13a03 waiting on condition  [0x000070000c46b000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.2/Native Method)
	- parking to wait for  <0x00000007156f4730> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.2/LockSupport.java:234)
	...

   Locked ownable synchronizers:
	- <0x0000000705b9e718> (a java.util.concurrent.ThreadPoolExecutor$Worker)
	- <0x00000007085e7540> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
```

which is in turn `parking to wait for  <0x00000007156f4730>`, but `0x00000007156f4730` isn't really anywhere else 🤦‍♂

**Comment by Legioth** [comment]
Are you sure that's the right thread? I'm slightly confused since one stacktrace goes through `LockSupport.park` and the other one through `LockSupport.parkNanos`.

**Comment by heruan** [comment]
What do you mean by "right thread"? The screenshots come from a different run then the thread dumps, so the hanging thread is different.

I'm still on this but ultimately I don't think this is related to Spring nor to push. This seems to happen when an *hidden* grid column has an `img` tag whose URL is from a `StreamResource`: this happens *only* if the column is hidden (`column.setVisible(false)`). I see there is some locking in `StreamResource`: is it possible that if the column is hidden then the lock is acquired but not released?

Also, since I'm pulling the stream from a database, sincerely I'm not even sure this is Vaadin bug. I'm investigating on it.

**Comment by Legioth** [comment]
I observed that the full-ish stacktrace that initially showed as stuck on `LockSupport.park` whereas the last partial stacktrace that you showed was going through `LockSupport.parkNanos` instead. Since you didn't show the full stacktrace from that case, I was wondering whether that stracktrace was actually from a genuinely stuck thread?

Involving `StreamResource` into the discussion makes things more interesting. It does some locking but I cannot spot anything that would be obviously wrong there either. One thing you could do is to ensure that your `StreamResource` logic actually completes, e.g. by adding logging when specific methods are entered and exited and ensuring that those add up. The relevant key methods are `StreamResource.getWriter()` and then depending on the `requiresLock` setting on the stream factory also the factory's `createInputStream` method and `read` in the returned input stream.

**Comment by denis-anisimov** [comment]
I didn't go into details of the ticket but please note:
- deadlock happens _only_  if there are _two_ resources (lock monitors) are acquired 
- lock for these resources should be acquire in the different order (there is one thread where one resource is locked first and another resource is acquired (or waiting for releasing) and another thread with the opposite order).

Vaadin framework as only one lock (per session). So there should be some additional lock somewhere outside of framework.

**Comment by denis-anisimov** [comment]
To be able to work on this ticket we need either:
- exactly detected why deadlock happens: which threads acquire locks in which resources in which classes
- the project where we may reproduce this.

**Comment by heruan** [comment]
This is driving me crazy. I guess I've now excluded push and even `StreamResource` from the equation, as this is happening regardless of those. While I'm trying to reproduce in a stripped-down project, I'm leaning to some kind of locking involving the binder and renderers; I'll try to explain in detail.

This is happening in a `Grid` and it happens only with a component-renderer column. This is the renderer:

```java
public class UserBadgeRenderer extends ComponentRenderer<UserBadge, User> {

    private final String[] themes;

    public UserBadgeRenderer(String... themes) {
        this.themes = themes;
    }

    @Override
    public UserBadge createComponent(User item) {
        return new UserBadge(this.themes).setUser(item);
    }

    public <T> ValueProvider<T, UserBadge> compose(
            Function<T, UserPicture> before) {
        return t -> new UserBadge(this.themes).setUser(before.apply(t));
    }
}
```

and this is the component:

```java
public class UserBadge extends Badge {

    private final Binder<User> binder = new Binder<>();

    private final Span name = new Span();

    public UserBadge(String... themes) {
        this.binder
                .forField(new ReadOnlyHasValue<>(this.name::setText))
                .bind(User::getFullName, null);
        this.add(this.name);
        this.withTheme("chip", themes);
    }

    public UserBadge setUser(UserPicture user) {
        this.binder.setBean(user);
        return this;
    }
}
```

and this is how I'm adding the column to the grid:

```java
Grid<Ticket> grid = new Grid<>();
grid.addComponentColumn(
        new UserBadgeRenderer().compose(Ticket::getUser));
```

All works smoothly at first load, but a refresh hangs immediately at:

<img width="999" alt="Screenshot 2019-06-28 at 10 29 55" src="https://user-images.githubusercontent.com/851745/60328993-b2c2e180-998f-11e9-85c1-ea360ad70921.png">

Then I tried to:

- remove the column: the issue doesn't happen;
- remove `this.add(this.name)` from `UserBadge`: the issue doesn't happen;
- leave the `Span`, but remove the binding: the issue doesn't happen.

So, it happens when `UserBadge` has `Span` which is bound. Any idea?

**Comment by heruan** [comment]
I've removed my last comment, as it was totally misleading. I've finally found the single line of code that causes the hang/lock:

```
grid.getDataCommunicator().setBackendSorting(sortOrders);
```

Commenting that line, all load fine. I'm now trying to replicate in a small project.

See also https://github.com/vaadin/vaadin-iron-list-flow/issues/88

**Comment by heruan** [comment]
Let me close this for now, I'll reopen if I'll be able to reproduce.
