### ISSUE TITLE
Template in template functionality is broken in NPM mode

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5916]
- Use attached project made on top of skeleton starter.
- Run it.
- open the initial page
- exception is thrown which says that `child-template`  element is not found.

That works in bower mode.
I think there is some issue in template parser : most likely the path (which consists of elements indices) is calculated wrong.

Here is the template code of the parent module just for quick reference :
```
static get template() {
        return html`
           <div>Parent Template</div>
            <div>
            <div>Placeholder</div>
            
            <child-template id="child">
            
            </div>
            <style>
    
                parent-template {
                    width: 100%;
                }
            </style>
    `;
      }
```

You may also find it in the attached project.

**Comment by denis-anisimov** [comment]
[skeleton.tar.gz](https://github.com/vaadin/flow/files/3295519/skeleton.tar.gz)

**Comment by denis-anisimov** [comment]
NPM Parser returns the following content for the element:
```
<template>
 <div>
  Parent Template
 </div>
 <div>  
 </div>
 <div>
  Placeholder
 </div>
 <child-template id="child"> 
 <style>
    
                parent-template {
                    width: 100%;
                }
            </style>
</template>
```

It is wrong since the second `div` is a parent for two elements (`div` and `child-template`).
Even though the original code is a bit wrong (there is no closing `</child-template>` tag) it still works wrong with the correct template content.

**Comment by denis-anisimov** [comment]
NPM Parser returns the following content for the element:
```
<template>
 <div>
  Parent Template
 </div>
 <div>  
 </div>
 <div>
  Placeholder
 </div>
 <child-template id="child"> 
 <style>
    
                parent-template {
                    width: 100%;
                }
            </style>
</template>
```

It is wrong since the second `div` is a parent for two elements (`div` and `child-template`).
Even though the original code is a bit wrong (there is no closing `</child-template>` tag) it still works wrong with the correct template content.

**Comment by denis-anisimov** [comment]
As a result the path sent to the client is `[3]`  (arrays with only one element).
But in fact it should be `[1,1]`.

**Comment by Legioth** [comment]
Does it work correctly if the `<child-tempalte>` element is properly closed?

If that is the case, then it would seem like JSoup uses different strategies for dealing with invalid HTML depending on how the content is parsed.

**Comment by denis-anisimov** [comment]
No it doesn't.

>Even though the original code is a bit wrong (there is no closing </child-template> tag) it still works wrong with the correct template content.

The problem is not in JSoup.
I think I found the line which produces a wrong content in out code.
