### ISSUE TITLE
"Run on server" or running Sprint Boot Application class runs compatibility mode in 14

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#5927]
1. Download https://vaadin.com/start/pre-release/project-base (plain-java)
2. Import into eclipse as "Import an existing Maven project"
3. Select Debug As -> Debug on Server and choose your installed Tomcat server
4. Open http://localhost:8080/project-name

Server logs:
```
[http-nio-8080-exec-6] WARN com.vaadin.flow.server.DefaultDeploymentConfiguration - 
====================================================================
Running in Vaadin 13 (Flow 1) compatibility mode.

This mode uses webjars/Bower for client side dependency management and HTML imports for dependency loading.

The default mode in Vaadin 14+ (Flow 2+) is based on npm for dependency management and JavaScript modules for dependency inclusion.

See http://vaadin.com/docs for more information.
====================================================================
```

Expected: The application is started in Vaadin 14 mode

Tested with latest snapshot

**Comment by Artur-** [comment]
This can be partly made to work by setting the lifecycle metadata to
```
    <pluginExecution>
      <pluginExecutionFilter>
        <goals>
          <goal>prepare-frontend</goal>
          <goal>build-frontend</goal>
        </goals>
      </pluginExecutionFilter>
      <action>
        <execute>
          <runOnConfiguration>true</runOnConfiguration>
        </execute>
      </action>
    </pluginExecution>
```

This would cause the goals to be run on project import and on full rebuild BUT there does not seem to be a way to cause the project to be refreshed after running the goals. Unless you refresh manually, it still won't work to do `run on server`

**Comment by pleku** [comment]
Basically the same thing happens when running a Spring Boot with starting the `main` method in `Application` class from any IDE or command line. The `prepare-frontend` goal is not executed, and the project runs in compatibility mode and fails with (14.0-SNAPSHOT):
```
...
This typically mean that you have started the application without executing the 'prepare-frontend' Maven target.
If you are using Spring Boot and are launching the Application class directly, you need to run "mvn install" once first or launch the application using "mvn spring-boot:run"
...
```

**Comment by denis-anisimov** [comment]
The suggestion for this is:

Do investigation on moving logic from the maven plugin into server initialization.

What we want is: it should be possible to start application without executing maven at all.
Right now we need maven goal `prepare-frontend` to be able to run `npm` mode.

The logic which is implemented as a part of `prepare-frontend`  should be executed at servlet initialization phase if project is executed in npm mode (how to enable npm mode is another question, right now you may use explicit property which enables npm mode).

I believe the logic can be added as a part of `ServletContainerInitializer`  .

Check : whether this is possible at all.
That's the first part.

Another part is : investigate whether it's possible to avoid running this logic at the server initialization phase if it has been already executed by maven.
It allows to use maven and don't spend any additional time during the server start (servlet initialization phase) if it has been already done by maven.
If it has not been done by maven (maven has not been executed at all) then servlet initializer will do its work. If maven has been executed then then the application doesn't do anything extra.

**Comment by caalador** [comment]
Setting the project to NPM mode we only need to have the `flow-build-info.json`  on the classpath as `META-INF/VAADIN/config` this could be in the project `/src/resources/META-INF/VAADIN/config/flow-buuld-info.json` with the content
```
{
  "compatibilityMode": false,
  "productionMode": false
}
```
Which would make the project always work in npm development mode and the token file could still be updated by the maven goals as needed.

The missing part is generating `target/frontend/package.json` that is used from the project package.json through: "@vaadin/flow-deps": "./target/frontend"

**Comment by caalador** [comment]
Could start the Spring base starter without using maven by:
 - Adding the flow-build-info.json to resources
 - Running the flow server with the following patch applied:
```
diff --git a/flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java b/flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
index 6f8b203e1cf650d80a740cdf9bc8b9989ec10446..675283d26392fd149bf667076db71aec594c7e93 100644
--- a/flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
+++ b/flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
@@ -22,12 +22,14 @@ import javax.servlet.ServletRegistration;
 import javax.servlet.annotation.HandlesTypes;
 
 import java.io.File;
+import java.io.IOException;
 import java.io.Serializable;
 import java.util.Arrays;
 import java.util.Collection;
 import java.util.HashSet;
 import java.util.Set;
 
+import org.apache.commons.io.FileUtils;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
@@ -160,18 +162,27 @@ public class DevModeInitializer
                 builder.npmFolder);
         for (File file : Arrays.asList(
                 new File(builder.npmFolder, PACKAGE_JSON),
-                new File(builder.generatedFolder, PACKAGE_JSON),
-                new File(builder.npmFolder, WEBPACK_CONFIG),
-                builder.generatedFolder)) {
+                new File(builder.npmFolder, WEBPACK_CONFIG))) {
             if (!file.canRead()) {
                 log().warn("Skipping DEV MODE because cannot read '{}' file.",
                         file.getPath());
                 return;
             }
         }
+        if(!builder.generatedFolder.exists()) {
+            try {
+                FileUtils.forceMkdir(builder.generatedFolder);
+            } catch (IOException e) {
+                e.printStackTrace();
+            }
+        }
+
+        boolean createPackageJson = !new File(builder.generatedFolder, PACKAGE_JSON)
+                .exists();
 
         Set<String> visitedClassNames = new HashSet<>();
-        builder.enablePackagesUpdate(true).enableImportsUpdate(true)
+        builder.createMissingPackageJson(
+                createPackageJson).enablePackagesUpdate(true).enableImportsUpdate(true)
                 .runNpmInstall(true).withEmbeddableWebComponents(true)
                 .collectVisitedClasses(visitedClassNames).build().execute();
```
