### ISSUE TITLE
Production Mode

### ISSUE THREAD

**Issue by amahdy** [vaadin/flow#5929]
Steps to reproduce:

- Download started (Vaadin 14 Beta 2) https://vaadin.com/start/pre-release/project-base
- `mvn package -Pproduciton-mode`
- `mvn jetty:run -Pproduction-mode`

Results:
From browser console:

`Vaadin.developmentMode` returns `true`

**Comment by caalador** [comment]
Please retry with 14.0.0.beta3

**Comment by Legioth** [comment]
Also, the profile was renamed to `production` instead of `production-mode` right before beta2. Please use the updated profile name.

**Comment by caalador** [comment]
Closing issue as old. Please open a new ticket if this still happens.
