### ISSUE TITLE
Clean project

### ISSUE THREAD

**Issue by amahdy** [vaadin/flow#5930]
I need to be able to re-create the `webpack.config.js` file using `mvn clean` or similar.

Steps to reproduce:
- Use a Vaadin 14 with wrong `frontend` folder location (place it inside `webapp` folder.
- `mvn package jetty:run`
Result: runtime errors because the front-end plugin can not handle the bower files.
- `mvn clean`
- `mvn package jetty:run`
Result: same errors.

Workaround:
Manually delete `webpack.config.js` then `mvn clean` then `mvn package jetty:run`.

**Comment by caalador** [comment]
The frontend folder shouldn't matter for webpack compilation.
Is this for an older project version with an old webpack.config.js left?

In Flow 2.0 final the webpack.config.js will be user configurable and there will be a webpack.generated.js
that will always be regenerated to the latest flow required state.

So for final you will need to once more remove webpack.config.js manually.

**Comment by pleku** [comment]
The release notes for 2.0.0 final and 14 final will have a disclaimer that the file `webpack.config.js` should be deleted for any project made with 14 prerelease versions. Then it will just work.
