### ISSUE TITLE
Modulizer investigation 

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#5941]
Outline the steps required for Modulizer to be able to migrate compatibility mode Vaadin 14 project to _normal_ mode Vaadin 14 project.

Find out what are the imports Modulizer is not able to handle and should be reported to the user by the migration tool (once that exists).

Identify and collect steps that can be automated and draft a document with those steps available for the person/people implementing the migration tool.

Epic #5037

**Comment by ujoni** [comment]
### Acceptance criteria
- User following the steps is able to run Modulizer and migrate their project (as far as modulizer is able to, at least)

**Comment by manolo** [comment]
- maven goal which user can run manually `mvn flow:migrate-bower-npm`
- maven goal will perform these steps:
  - visit java sources and generate a proper bower.json file
  - create a temporary `target/migration` folder with `bower.json` `package.json` and `*.html` P2 template files
  - run `npm install` so as modulizer and other tools are installed in the temporary folder
  - run `node modulizer` so as a new `package.json` with dependencies and `*.js` P3 template files are generated
  - `*.js` files are moved to `/frontend`
  - `@JsModule` annotations are added to `src/main/java/**/*.java` files
  - Dependencies are read from  `package.json` and `@NpmAnnotations` added to `src/main/java/**/*.java` files
- Now the user can add the `prepare-frotend` and `buid-frotend` goals to their pom.xml

**Comment by Legioth** [comment]
It could be noted that the first steps about visiting sources and collecting everything into something like `target/migration` is very close to what the production build already does. Might make sense to reuse relevant parts of that implementation.

**Comment by manolo** [comment]
As reference, I used this gist for migrating couple of starters
https://gist.github.com/manolo/422f85369a3cabfc2090dc69ec471129

**Comment by denis-anisimov** [comment]
https://docs.google.com/document/d/1bLVAq6ZFjUwJvjRWVc7FZfvve6qa5GnCve4OgaX6MPo/edit#
