### ISSUE TITLE
Create a validation task in Bender for migrating Beverage buddy

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#5942]
Task migrates Beverage Buddy from Vaadin 14 compatibility mode to Vaadin 14 npm mode and validates the migration.

Runs after updates to Beverage Buddy, the Migration Tool, or Flow.

Depends on the actual Migration Tool implementation.

Epic #5037

**Comment by denis-anisimov** [comment]
The task is created bu it fails because migration tool has some issues (which are already fixed via PR waiting for review).

**Comment by denis-anisimov** [comment]
"Migrate beverage-starter-flow V13 to V14" job is added into bender under "Starters Tests/Version bump validation from 13 to 14"
