### ISSUE TITLE
JavaScript on root route gets run even when launching app on a different route

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#5945]
Vaadin 14 beta 3. Created with `vaadin init --pre`

Description:
1.  I have `@JsModule("src/foo.js")` on the component marked with `@Route` (empty value).
2. I open a new browser window and navigate to `localhost:8080/foo`, not using a parent layout.
3. JS code imported on the root component gets run

The same happens with `@JavaScript` in step 1.

Expectation:
I would expect JS code only to get loaded when I navigate to the route where I have imported it.

**Comment by denis-anisimov** [comment]
Right.
This is really confusing.

The current behavior is what happens in NPM mode.
In the compatibility mode it works as expected (`@JavaScript` is executed only when a navigation target is activated).

I'm not sure what should be done with this. I understand that we actually treat `@JavaScript` in NPM mode like `@JsModule`. But this is rather an implementation detail.
This behavior should not be confusing at least.
No idea how it should behave in the result.

**Comment by denis-anisimov** [comment]
Even though this is "expected" (known according to the current implementation) the behavior is confusing.
So even if the behavior itself is not a bug we should find a way to inform a user about the current behavior of `@JavaScript`. So I mark this as a bug.

**Comment by Legioth** [comment]
This is also the way it worked in previous Vaadin versions, with the difference that it was only apparent in production mode when the full bundle was loaded but not during development. In that regard, the current behaviour is actually preferable since it makes the situation apparent also in development mode.

**Comment by mehdi-vaadin** [comment]
### Acceptance criteria
The current behavior should be mentioned in the tutorial `importing-dependencies/tutorial-importing.html` and the Javadocs of `JavaScript` and `JsModule`.

**Comment by marcushellberg** [comment]
So does Vaadin not support code splitting by route at all?

**Comment by manolo** [comment]
That is something to implement in the future, it will cover probably this case, unless `foo.js` is in two routes and could be eventually loaded in a common chunk at some point, we need to test how webpack does that. Related with #5537

**Comment by Legioth** [comment]
> So does Vaadin not support code splitting by route at all?

"Manual" code splitting is supported with Bower mode by defining fragment contents in the maven plugin configuration using `<fragments>`, as can be seen e.g. in Bakery for Vaadin 10 - 13.

For npm mode, nothing such is currently implemented, but it is surely planned to be added at some point.

**Comment by joheriks** [comment]
Will use the above acceptance criteria (document current behavior).
