### ISSUE TITLE
app does not start in 30 seconds after adding the org.bouncycastle:bcprov-jdk15on dependency (Spring Boot skeleton)

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#5960]
Vaadin 14.0.0.rc1

Adding the `org.bouncycastle:bcprov-jdk15on:1.62` dependency to `skeleton-starter-flow-spring` increases the application start time by about 5 minutes (292 seconds instead of 10 seconds).

**Steps to reproduce:**
 1. clone the base starter from `https://github.com/vaadin/skeleton-starter-flow-spring.git`
 2. package the app with `mvn clean package`
 3. start the app with `mvn spring-boot:run`
 4. see the baseline app start time
    `Started Application in 9.918 seconds (JVM running for 10.403)`
 5. add the `org.bouncycastle:bcprov-jdk15on:1.62` dependency to `pom.xml`
    ```xml
    <dependency>
        <groupId>org.bouncycastle</groupId>
        <artifactId>bcprov-jdk15on</artifactId>
        <version>1.62</version>
    </dependency>
    ```
 6. package the app again with `mvn clean package`
 7. start the app with `mvn spring-boot:run`
 8. see that the app start hangs after printing this line to the log:
    `INFO 5550 --- [  restartedMain] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1340 ms`
    At that point the app process consumes 100% CPU and does not produce any visible output. The web app is not responding on the port 8080.
 8. wait for about 5 mintues
     It took me a while to realize that the app is just being slow. The first few times I've killed the process thinking that it just hanged. I assume not many would wait for 5 minutes.
 9. see that the app starts
    `Started Application in 291.911 seconds (JVM running for 292.348)`

**Investigation:**
Setting the log level to `TRACE` reveals that the startup seems to be spending time scanning the class path. When the process starts consuming 100% CPU, there is a constant stream of log entries like
```
TRACE 5625 --- [  restartedMain] ssPathScanningCandidateComponentProvider : Scanning URL [jar:file:/Users/viktor/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.62/bcprov-jdk15on-1.62.jar!/org/bouncycastle/asn1/ess/ESSCertIDv2.class]
TRACE 5625 --- [  restartedMain] ssPathScanningCandidateComponentProvider : Ignored because not matching any filter: URL [jar:file:/Users/viktor/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.62/bcprov-jdk15on-1.62.jar!/org/bouncycastle/asn1/ess/ESSCertIDv2.class]
```

**Comment by vlukashov** [comment]
`org.bouncycastle:bcprov-jdk15on` is a library that provides the cryptographic primitives necessary to implement Web Push in the app. There might be other libraries to do that, but this seems to be a popular choice.

This issues basically makes it not feasible to implement Web Push in a Vaadin 14 app.

**Comment by pleku** [comment]
Can you please test by using latest Flow 2.0-SNAPSHOT?
It has optimized the scanning #5932.

Otherwise, we can blacklist this library but it starts to be easier to just add a blacklisting as a feature.

**Comment by vlukashov** [comment]
With Flow 2.0-SNAPSHOT the issue is still there.

**Comment by caalador** [comment]
This is purely a spring issue in that the collection of classes is not done through the servlet, 
but through springs classpathscanner functionality.

Added a feature to allow blacklisting extra packages from the scanner as we can't anticipate everything that is not of interest nor can we select everything that would be of interest.
