### ISSUE TITLE
Serialization issues as soon as Grid added to application

### ISSUE THREAD

**Issue by alump** [vaadin/flow#5973]
**Setup:**
Java 12.0.1, Maven 3.6.1, MacOS 10.14.5, Intellij IDEA 2019.1

**Steps:**
1. Pull RC1 Spring Boot starter from https://vaadin.com/start/pre-release/project-base
2. Start it with `mvn spring-boot:start`
3. Verify application has started
4. Add Grid to MainView class `Grid<String> grid = new Grid<>(); add(grid);`
5. Rebuild project to cause spring dev tools to restart app

**Expected outcome:**
Application starts without exceptions

**Actual outcome:**
Grid brings in some classes that are serializable? And this causes exceptions when application starts.

```
2019-06-25 13:36:05.551 ERROR 20856 --- [  restartedMain] o.a.catalina.session.StandardManager     : Exception loading sessions from persistent storage

java.io.InvalidObjectException: ReflectiveOperationException during deserialization
	at java.base/java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:241) ~[na:na]
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor65.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
...

Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
	at java.base/java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:239) ~[na:na]
	... 217 common frames omitted
Caused by: java.lang.ClassCastException: class java.lang.invoke.SerializedLambda cannot be cast to class com.vaadin.flow.dom.PropertyChangeListener (java.lang.invoke.SerializedLambda is in module java.base of loader 'bootstrap'; com.vaadin.flow.dom.PropertyChangeListener is in unnamed module of loader 'app')
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.$deserializeLambda$(ElementPropertyMap.java:48) ~[flow-server-2.0.0.jar:2.0.0]
	... 222 common frames omitted
```

UPDATE: Exception is different now in latest RC versions, see comments!

**Comment by RapidClipse** [comment]
Seems to be a serialization problem in ElementPropertyMap.
If you run
```java
try
{
	final VerticalLayout root = new VerticalLayout();
	root.add(new Checkbox());
	
	final ByteArrayOutputStream bout = new ByteArrayOutputStream();
	try (ObjectOutputStream oout = new ObjectOutputStream(bout))
	{
		oout.writeObject(root);
	}
	try (ObjectInputStream in = new ObjectInputStream(
			new ByteArrayInputStream(bout.toByteArray())))
	{
		in.readObject();
	}
}
catch(final Exception e)
{
	e.printStackTrace();
}
```
following exception is thrown

```
java.lang.invoke.SerializedLambda cannot be cast to com.vaadin.flow.dom.PropertyChangeListener
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.$deserializeLambda$(ElementPropertyMap.java:48)
	... 118 more
```

**Comment by alump** [comment]
This still happens in rc5, I think this should be fixed before final. And code throwing exceptions doesn't give good image.

**Comment by denis-anisimov** [comment]
It's very possible that I have something wrong with my setup and current Java selected.
But I'm not able to reproduce the issue, sorry :(

The code which I use:

```
Button button = new Button("Click me",
                e -> Notification.show(bean.getMessage()));
        add(button);

        System.out.println(System.getProperty("java.version"));

        Grid<String> grid = new Grid<>();
        add(grid);
```

No exceptions, both components are shown in the browser.

The Java version output is : `12.0.2` (not `12.0.1` but if it matters then this is a Java bug in `12.0.1`).
So I would say that the app is running using Java 12.
As I said: I trust that the exception is a real one. So it's highly possible that my setup is not that required for the ticket.
But I don't know how to make a proper setup to reproduce the issue.

Only one suggestion in my mind:
may be it somehow relates to IDE ? 
Could you try to `run mvn spring-boot:run` from the command line ?
Is the result the same ?

**Comment by alump** [comment]
Rebuild the project and let's it restart, then issue happens when Tomcat embedded in Spring Boot run is trying to deserialize the sessions.

**Comment by caalador** [comment]
Using RC6 I got some java cast exceptions with 12/corretto 11, but the application still worked after the devtool restart.
Updating spring-boot-starter-parent to <version>2.1.6.RELEASE</version> made even these exceptions go away. made a PR to starter to udate spring

**Comment by alump** [comment]
Application works with these, but sessions serialization/deserialization fails, and this is ugly developer experience, as all you need is to have grid on you app.

**Comment by caalador** [comment]
If you still get the exception there must be something extra as I can't replicate it at all. I get no exceptions after updating the spring version.

**Comment by alump** [comment]
1. Get Spring Boot starter from https://vaadin.com/start/pre-release
2. Import to IDEA as Maven Project (IDEA 2019.1, Embedded Maven, Corretto 11 JDK)
3. Add line `add(new Grid<String>());` to MainView class' constructor
4. Run Maven target `spring-boot:run`
5. Wait application to start
6. Open page on browser http://localhost:8080
7. Return to IDEA, and change "Click Me" to "Click Me 2" on button at MainView and save file
8. Click "Build Project" on IDEA

Now when app restarts it will throw the exception:

> java.lang.ClassCastException: class java.io.NotSerializableException cannot be cast to class java.io.ObjectStreamClass (java.io.NotSerializableException and java.io.ObjectStreamClass are in module java.base of loader 'bootstrap')
> 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1766) ~[na:na]
> 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060) ~[na:na]
> ...

**Comment by caalador** [comment]
Can't replicate by running the project, but with the junit test
```

    @Test
    public void testLayoutSerialization() throws IOException, ClassNotFoundException {
            final Div root = new Div();
            root.add(new Input());

            final ByteArrayOutputStream bout = new ByteArrayOutputStream();
            try (ObjectOutputStream oout = new ObjectOutputStream(bout))
            {
                oout.writeObject(root);
            }
            try (ObjectInputStream in = new ObjectInputStream(
                    new ByteArrayInputStream(bout.toByteArray())))
            {
                in.readObject();
            }
    }
```

it reliably fails with 
```
Caused by: java.lang.ClassCastException: java.lang.invoke.SerializedLambda cannot be cast to com.vaadin.flow.dom.PropertyChangeListener
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.$deserializeLambda$(ElementPropertyMap.java:48)
	... 146 more
```

**Comment by denis-anisimov** [comment]
Doesn't relate to Java version. Fails also with JDK 8.

**Comment by denis-anisimov** [comment]
This code  doesn't fail:

```
final Div root = new Div();
        Grid<String> input = new Grid<>();
        root.add(input);

        final ByteArrayOutputStream bout = new ByteArrayOutputStream();
        try (ObjectOutputStream oout = new ObjectOutputStream(bout)) {
            oout.writeObject(root);
        }
        try (ObjectInputStream in = new ObjectInputStream(
                new ByteArrayInputStream(bout.toByteArray()))) {
            in.readObject();
        }
```

**Comment by denis-anisimov** [comment]
If nobody may reproduce the issue with Spring and Grid, I would like to ask @alump :

- open your project in IDE
- set a breakpoint to `ElementPropertyMap::addPropertyChangeListener` .
- collect all the `PropertyChangeListener` instances which are added via `addPropertyChangeListener` 
- let us know the classes: they are lambdas but at least the will contain the enclosing class which allows us to understand where exactly to look for it.

Or you may somehow identify the breaking listener by yourself: I've just excluded listener and checked what happened.
I recall there is a way to find the exact pointer with serialization via some Java flag or something else.
@Artur- knows about it. I was not able to google this.

**Comment by denis-anisimov** [comment]
https://stackoverflow.com/questions/1660441/java-flag-to-enable-extended-serialization-debugging-info

**Comment by denis-anisimov** [comment]
We have 3 different scenario/issues here:
- the first one is related to `Grid` and `class java.lang.invoke.SerializedLambda cannot be cast to class com.vaadin.flow.dom.PropertyChangeListener`. Originally reported
- The second one is the same exception related to every component which extends `AbstractSinglePropertyField`. This is genuine issue. It may be reproduced, there is a reliable unit test for this. Needs to be fixed.
- the last one related to `Grid` and `java.lang.ClassCastException: class java.io.NotSerializableException cannot be cast to class java.io.ObjectStreamClass` . This one comes again from Sami and this is a different than the original one.

It seems nobody except Sami is able to reproduce the first one. I can't even nmake a theoretical suggestion why it may happen.

I'm going to fix the second one.

The third one: I've seen it once. I believe this is the same exception which Mikael has seen. Because it doesn't break the application anyhow.

So as a result even though I'm not comfortable with this approach but the fix will be done for `class java.lang.invoke.SerializedLambda cannot be cast to class com.vaadin.flow.dom.PropertyChangeListener` though may be the fix won't be a part of the original description (that's why we need the exact steps to reproduce to avoid fixing unrelated issues).

**Comment by alump** [comment]
Ok, i considered my issue being failure to deserialize, not any specific exception. So maybe we can say that original exception doesn't happen anymore, but it's new exception now.

**Comment by denis-anisimov** [comment]
Hmm....
I would  may be create another ticket.
This one becomes hard to track related to 

```
java.lang.ClassCastException: class java.io.NotSerializableException cannot be cast to class java.io.ObjectStreamClass (java.io.NotSerializableException and java.io.ObjectStreamClass are in module java.base of loader 'bootstrap')
at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1766) ~[na:na]
at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060) ~[na:na]
```

I've mede a fix for exception related to property change listener in `ElementPropertyMap`.
It fixes any component which extends `AbstractSinglePropertyField`.
_And_  I've extended the serialization test base class to check serializability of any component inside a container. It seems only this scenario causes the issue. We didn't have such scenario before.
This test exists in every our component (via extending the base class)  so we should be able to catch this exception if it happens in any other component including `Grid`.

`class java.io.NotSerializableException cannot be cast to class java.io.ObjectStreamClass` is a different one. 
And what's important it doesn't break the application anyhow.
Also it might be that this exception is related to Spring.

So I would suggest to make another ticket in Spring for this exception. I don't have even reliable steps to reproduce it :(
