### ISSUE TITLE
Enable test-mixed modules

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5974]
There is only one test in `test-mixed` modules (it's plural because there are several pom files).
All those modules are now excluded from the build because the single test is not stable.
Investigate what's going on with the test (it passes locally but sometimes it doesn't pass on TC randomly.)
The number of unsuccessful  execution is quite big.

The test should be enabled because it tests basic functionality in all modes considering a non-root mapping.

**Comment by caalador** [comment]
Enabled in #6173
