### ISSUE TITLE
Adding a new grid from within an UI.access produces client side errors

### ISSUE THREAD

**Issue by Klaudeta** [vaadin/flow#5986]
- Vaadin 14.0.0.rc1 (Flow 2.0.0)
- Push enabled (LONG-POLLING)
- Spring Boot application

Use case to reproduce the issue:

```
public class TestDialog extends Notification {

    public TestDialog() {
    }

    private void loadGrid() {

                getUI().get().access(() -> {
                    Grid<MyUser> grid = new Grid<>();
                    grid.setWidth("400px");
                    grid.setHeight("300px");
                    grid.addColumn(MyUser::getEmail).setHeader("Email");
                    add(grid);
                });
    }

    @Override
    protected void onAttach(AttachEvent attachEvent) {
        super.onAttach(attachEvent);
        loadGrid();
    }

    public static class MyUser{
        private String email;

        public String getEmail() {
            return email;
        }
    }
}
```
```
@Route
@Push(transport = Transport.LONG_POLLING)
@PWA(name = "Project Base for Vaadin Flow with Spring", shortName = "Project Base")
public class MainView extends VerticalLayout {

    public MainView() {
        Button button = new Button("Click me",
                e -> {
                    new TestDialog().open();
                });
        add(button);
    }

}
```

Once the notification containing the dialog is opened there are a bunch of browser console errors like:

<img width="565" alt="Screenshot 2019-06-27 at 9 31 01" src="https://user-images.githubusercontent.com/31614592/60242458-678cce00-98be-11e9-8d56-335ef7581b2c.png">
<img width="797" alt="Screenshot 2019-06-27 at 9 30 55" src="https://user-images.githubusercontent.com/31614592/60242459-678cce00-98be-11e9-8c97-bfce029bda4c.png">

**Comment by Lukasz-Bialy** [comment]
Hey guys, same problem in my project. When i reload page i sometimes get this message, like 1 out of 3 times. Are you planning to fix this in near future, i am asking because i would like to know if i should use other components or just wait.

**Comment by denis-anisimov** [comment]
Cannot reproduce it with 16.0.0.rc1.
Will try lower versions...

**Comment by denis-anisimov** [comment]
Cannot reproduce it with `14.1.21` either.
Please use the latest version.
