### ISSUE TITLE
Newly added Vaadin Component might be missing frontend files

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#5991]
If the user adds a Vaadin component to a starter that is not previously present and does not run `mvn install` but simply uses `mvn jetty:run`, the added component won't have frontend resources. 

**Steps to replicate:**
 - clone `vaadin-skeleton-starter-flow`
 - test it by running `mvn jetty:run`
 - adds new component (such as the `Tabs`) to `MainView`
 - runs again with `jetty:run` -> BAM! No styles for `Tabs`
    - `npm install` has not been run and the npm modules for `Tabs` are not downloaded

**Comment by mstahv** [comment]
I can reproduce this on a Spring Boot project too.

**Comment by mehdi-vaadin** [comment]
It may be the same as #6029.

**Comment by mehdi-vaadin** [comment]
It has been fixed in `14.0.0.rc5`.
