### ISSUE TITLE
client.productionMode is not defined when development-mode-detector is executed

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/flow#5994]
currently there is an issue in the integration of vaadin-development-mode-detector and flow

the detector checks for `productionMode` in all `Vaadin.Flow.clients`, but the check is done too early while client is initializing and `productionMode` is not yet defined

this results license checks dialogs and usage statistics pings caused by wrong detection of `Vaadin.developmentMode`

**Comment by manolo** [comment]
The origin of this is that we are bundling frontend in devMode, which means that it minimizes by default, removing the `maybeGatherAndSendStats` content. So even though dev mode is defined it executes an empty function.

Possible solutions:
- set `minimize: false` when in devmode in webpack config file
- change the generated import file to use a non commented detector when we detect the import in devmode

**Comment by alvarezguille** [comment]
Also check that when running production mode in localhost it's correctly detected as production mode

**Comment by manolo** [comment]
@Artur- I'm implementing first approach which seems the simplest, do you have any preference? 

Probably second give us more options to for instance delay the load of stats if devMode takes a while to be available, or even initialise the stats in flow to fix https://github.com/vaadin/flow/issues/6020

**Comment by manolo** [comment]
Made more investigations and 
- minimisation is not an issue when in dev mode, only was happening in projects where they override `-d` flag with `—debug` which was the one I used for debugging
- Stats and License checker are working fine in jetty projects
- The issue only comes in spring, when the webcomponent detector is run, the client is still initializing
