### ISSUE TITLE
How can I bring local javascript files with latest version 2.0.0

### ISSUE THREAD

**Issue by rob-64** [vaadin/flow#6006]
Only external js files are being loaded in latest version; is it no longer possible to bring local javascript files?

    - Vaadin / Flow version 2.0.0
    - Java version 8

**Comment by mehdi-vaadin** [comment]
It is possible. Which directory is your JavaScript file located in? Would you please share more details? 
Also, take a look at [this](https://vaadin.com/forum/thread/17753553/17754122) and see if you have the same issue and if the suggested workaround works for you or not.
