### ISSUE TITLE
Polymer 3.3.0 breaks Flow

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#6009]
See the detailed explanation what's going on here:
https://github.com/vaadin/flow/issues/5966#issuecomment-507232485

There are things to do:
- make a quick fix for `PolymerTemplate` class which allows to avoid unnecessary `shadowRoot`  creation. That will fix immediately a lot of cases (along with beverage) .
- understand what to do with `attachShadow` method . This is `Element` API and it may be called by the app developer explicitly. In case of Polymer element it may cause the same issue as we have now. Most likely there is no need to create a shadow root for polymer element at all so this method can be no-op. But it should be possible to add something to the shadow root. And since it may be not available at the `attachShadow`  call we should postpone somehow operations with shadow root when it becomes available. This is true for polymer elements. For other elements there should not be changes I believe.

It can be just a bug in Polymer `3.3.0`  : it doesn't reuse the existing shadow root.

Feel free to create a separate ticket for shadow root only issue.

**Comment by heruan** [comment]
Any update on this? I'm writing components with TypeScript and Polymer 3.3.0 has decorators, e.g. `@property` which helps a lot!

**Comment by heruan** [comment]
Sorry for asking again, but it's becoming hard to avoid Polymer 3.3.0 leaking from dependencies. Any update or WIP?

**Comment by pleku** [comment]
I've bumped the priority - I hope we'll get to this in this / next week.

**Comment by denis-anisimov** [comment]
I consider this as a bug in Polymer `3.3.0`.
Here is the ticket https://github.com/Polymer/polymer/issues/5604.

I think there will be too many changes on the client side to workaround this.
So let's don't do anything regarding the second item (fix `attachShadowRoot` behavior) until we know that this won't be fixed in Polymer.

I will do here only the first item which should fix our `PolymerTemplate`  code so that we avoid unnecessary shadowRoot creation.

**Comment by denis-anisimov** [comment]
PR: https://github.com/vaadin/flow/pull/6889

It makes a workaround for Polymer `3.3.0` in its current state.
There is still may be an issue if you are using `attachShadowRoot` Element API method.
This is not fixed: this should be fixed on Polymer side (see ticket above).
So since Polymer `3.3.0`  is not really ready I didn't switch Polymer version.
It's still `3.2.0`  (hardcoded).
But I've added a parameter which can be used :
- in dev mode `devmode.polymer.version` parameter can be used in a deployment config to specify the polymer version
- `polymerVersion`  config parameter for maven plugin. You may specify a value via this property if you build the project production.

Tested with beverage: it works without problems.
