### ISSUE TITLE
Lumo.DARK not applied for templates

### ISSUE THREAD

**Issue by ripla** [vaadin/flow#6017]
Using Vaadin 14.0.0.rc3, it seems that the `Lumo.DARK` theme setting is not applied when using templates and AppLayout.

## Steps to reproduce
1. Go to https://start.vaadin.com
2. Change the theme to dark
3. Download and run

## Expected behaviour
The view is shown with the dark theme

## Actual behaviour
The view is shown with the light theme

## Versions
Vaadin 14.0.0.rc3, Java 1.8.0_202, macOS 10.14.5, Chrome

**Comment by mehdi-vaadin** [comment]
It happens when the theme is set on the layout class. The minimal code to reproduce this is the following.
```
@Theme(value = Lumo.class, variant = Lumo.DARK)
public class MainLayout extends Div implements RouterLayout {
}

@Route(value = "", layout = MainLayout.class)
public class MyView extends Div {
    public MyView() {
        add(new Button("Don't click me!"));
    }
}
```

**Comment by ujoni** [comment]
As further information, themes do work (`Material` loads) but the variant does not work.
