### ISSUE TITLE
Flow stats do not work if there is no vaadin component in the UI

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#6020]
Creating a flow project with no vaadin components, implies that flow stats not work because the statistics stuff in client side is only imported when there is a component extending the vaadin-element-mixin

**Comment by pleku** [comment]
Being realistic, I have hard time believing this would ever be an issue. One would be only using Flow with custom component set or only html components ?

**Comment by denis-anisimov** [comment]
Looks like this ticket is not valid anymore since we have our IT tests in Flow projects which are executed in both modes: production and dev and they passes.
We don't have any Vaadin component in those tests used.

So I'm closing this ticket.
Please reopen it if it's still valid.
