### ISSUE TITLE
Running Spring Boot app from Application class fails in npm compilation issue

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#6026]
Mac, JDK 11 or 12, Vaadin 14.0.0.rc3, npm 6.8

1. Download Spring Boot starter from vaadin.com/start
1. Import to IntelliJ
1. Execute Application class

The execution log says:

```
7-05 10:02:42.722 ERROR 12919 --- [        webpack] dev-webpack : ERROR in ../target/frontend/generated-flow-imports.js
2019-07-05 10:02:42.722 ERROR 12919 --- [        webpack] dev-webpack : Module not found: Error: Can't resolve '@vaadin/flow-frontend/flow-component-renderer.js' in '/Users/mstahv/Downloads/my-starter-project-18/target/frontend'
2019-07-05 10:02:42.722 ERROR 12919 --- [        webpack] dev-webpack  :  @ ../target/frontend/generated-flow-imports.js 13:0-58
2019-07-05 10:02:42.722 ERROR 12919 --- [        webpack] dev-webpack : 
2019-07-05 10:02:42.722 ERROR 12919 --- [        webpack] dev-webpack : ERROR in ../target/frontend/generated-flow-imports.js
2019-07-05 10:02:42.722 ERROR 12919 --- [        webpack] dev-webpack  : Module not found: Error: Can't resolve '@vaadin/flow-frontend/flow-component-renderer.js' in '/Users/mstahv/Downloads/my-starter-project-18/target/frontend'
2019-07-05 10:02:42.722 ERROR 12919 --- [        webpack] dev-webpack :  @ ../target/frontend/generated-flow-imports.js 13:0-58
2019-07-05 10:02:42.722 ERROR 12919 --- [        webpack] dev-webpack  : ℹ ｢wdm｣: Failed to compile.
2019-07-05 10:02:42.723 ERROR 12919 --- [        webpack] dev-webpack : 
------------------ Frontend compilation failed. -----------------
```

The application still starts (should probably just die at that point), but when navigating there with a browser, there is nasty JS exceptions on the screen.

Running a priming build (mvn install) fixes the issue.

**Comment by jcgueriaud1** [comment]
Got the same error using a plain Java project from the starter (14RC4).
Steps to reproduce:
- Download a Plain Java project from the app starter
- run mvn package (or mvn install)
Got this error:
Can't resolve '@vaadin/flow-frontend/flow-component-renderer.js?babel-target=es6

Run mvn jetty:run , the app is running.

**Comment by johndevs** [comment]
I am getting the same when trying to use the following ``package.json``:

```json
{
    "dependencies": {
        "@polymer/iron-icon": "3.0.1",
        "@polymer/iron-list": "3.0.2",
        "@polymer/paper-slider": "0.0.3",
        "@vaadin/vaadin-accordion": "1.0.1",
        "@vaadin/vaadin-app-layout": "2.0.2",
        "@vaadin/vaadin-button": "2.2.1",
        "@vaadin/vaadin-checkbox": "2.2.10",
        "@vaadin/vaadin-combo-box": "5.0.6",
        "@vaadin/vaadin-context-menu": "4.3.12",
        "@vaadin/vaadin-core-shrinkwrap": "14.0.0-rc7",
        "@vaadin/vaadin-custom-field": "1.0.6",
        "@vaadin/vaadin-date-picker": "4.0.3",
        "@vaadin/vaadin-details": "1.0.1",
        "@vaadin/vaadin-dialog": "2.2.1",
        "@vaadin/vaadin-form-layout": "2.1.4",
        "@vaadin/vaadin-grid": "5.4.6",
        "@vaadin/vaadin-icons": "4.3.1",
        "@vaadin/vaadin-list-box": "1.1.1",
        "@vaadin/vaadin-login": "1.0.1",
        "@vaadin/vaadin-material-styles": "1.2.3",
        "@vaadin/vaadin-menu-bar": "1.0.3",
        "@vaadin/vaadin-notification": "1.4.0",
        "@vaadin/vaadin-ordered-layout": "1.1.0",
        "@vaadin/vaadin-progress-bar": "1.1.2",
        "@vaadin/vaadin-radio-button": "1.2.3",
        "@vaadin/vaadin-select": "2.1.5",
        "@vaadin/vaadin-split-layout": "4.1.1",
        "@vaadin/vaadin-tabs": "3.0.4",
        "@vaadin/vaadin-text-field": "2.4.8",
        "@vaadin/vaadin-time-picker": "2.0.2",
        "@vaadin/vaadin-upload": "4.2.2"
}  
```

And manually running ``webpack build``.

What package is ``'@vaadin/flow-frontend/flow-component-renderer.js'`` (could not find it in NPM) and why does some component depend on that and some on ``'flow-component-renderer.js'``?

Combobox uses https://github.com/vaadin/vaadin-combo-box-flow/blob/0544b9ebddd8b015827dd7fc4b00cac1719b94aa/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L86

While Grid uses https://github.com/vaadin/vaadin-grid-flow/blob/5db69b600f45271ad5ed84dcc70e5417ebb96743/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java#L129

And finally ContextMenu uses https://github.com/vaadin/vaadin-context-menu-flow/blob/4c2514bf37400d3d070500773a7164513fa93244/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java#L48

Please unify the imports to use one path notation.

**Comment by Legioth** [comment]
`@vaadin/flow-frontend` is a locally generated package based on frontend files that are present inside .jar files on the classpath. The build plugin needs to extract those files into the local file system and add a `package.json` in the same directory so that npm and webpack can find the files.
