### ISSUE TITLE
ListBox missing setCaption

### ISSUE THREAD

**Issue by bsutton** [vaadin/flow#6033]
I'm using vaadin 14 rc3 and the ListBox component with a data provider.

I was expecting to find a method that allows me to set the caption of each item supplied by the provider. The closest I could find was the render which appears to be complete overkill for a caption.

Expected

```
        UserDao daoUser = new UserDao();
    	List<User> users = daoUser.getAllUsers();
    	
    	colleaguesField.setDataProvider(new ListDataProvider<User>(colleagues));

    	colleaguesField.setCaption(user -> user.getName());
```

**Comment by mehdi-vaadin** [comment]
Issue moved to [vaadin/vaadin-list-box-flow #53](https://github.com/vaadin/vaadin-list-box-flow/issues/53) via [**ZenHub**](https://www.zenhub.com/)
