### ISSUE TITLE
V14.rc3 unable to package project

### ISSUE THREAD

**Issue by mkortel** [vaadin/flow#6051]
Version 14.0.0.rc3 (SimpleApp stater)
After unpacking the project, when I run following commands I get and error:
mvn com.github.eirslett:frontend-maven-plugin:1.7.6:install-node-and-npm -DnodeVersion="v10.16.0"
mvn package (or mvn install)
[INFO] Running webpack ...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:44 min
[INFO] Finished at: 2019-07-11T10:17:40+03:00
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:14.0.0.rc3:build-frontend** (default) on project kellonhuolto: Execution default of goal com.vaadin:vaadin-maven-plugin:14.0.0.rc3:build-frontend failed: Webpack process exited with non-zero exit code.
[ERROR] Stderr: 'You have installed webpack-cli and webpack-command together. To work with the "webpack" command you need only one CLI package, please remove one of them or use them directly via their binary.'

npm ls webpack-command
`-- (empty)
npm ls -g webpack-command
`-- (empty)
npm ls webpack-cli
`-- webpack-cli@3.3.0
npm ls -g webpack-cli
`-- (empty)

webpack-cli is installed locally and webpack-command is not installed

**Comment by Legioth** [comment]
Could it be that your project uses some dependency that installs `webpack-command` locally for the project (i.e. `npm ls` without the `-g` flag) rather than globally? I also think there is a possibility that `webpack-command` installed inside a `node_modules` inside a parent directory might be picked up.

If you indeed have a `webpack-command` somewhere, then I guess the problem could be solved if Flow would run the `webpack-cli` binary instead of the generic `webpack` binary. If this isn't the case, then it would be good to first understand what it is that triggers the error message in your particular case but not for others.

**Comment by denis-anisimov** [comment]
Hi, we have never faced with this issue.
So it's hard to find even a theoretical way to reproduce.
Looks like this happens due a specific of your local set up so we need a help from you and additional info.

Could you please answer the question from [above](https://github.com/vaadin/flow/issues/6051#issuecomment-512749194) ?

Some background: the error message comes from webpack, this is not what we check and generate.
So it means that this is a generic webpack issue specific to your env.
And there is no way for us to find a reason without your environment.
So if there is no bug in webpack then there is somewhere `webpack-command`  and the only question is where?

**Comment by mkortel** [comment]
Hi,
npm -g doesn't show webpack-command to be installed either.
The original project was located in c:\users\marko\eclipse-workspaces\test1 and after I moved it into c:\data\test1 it works fine. 
Can hyphen in the path cause this?

**Comment by denis-anisimov** [comment]
You may try to move (or just copy) it again into a path with hyphen...
It's hard to say: as I've mentioned this is the webpack code. It might be that there is just a bug inside webpack ...

**Comment by denis-anisimov** [comment]
Does `eclipse-workspaces` have any node_modules ?

**Comment by Legioth** [comment]
You can easily test the hyphen hypothesis by renaming `c:\data\test1` to e.g. `c:\data\eclipse-workspaces\test1`.

Another potential explanation is that there is a `node_modules` directory containing `webpack-command` in some parent directory, e.g. `c:\users\marko\`.

**Comment by denis-anisimov** [comment]
No response from the reporter.
So I suppose this is an issue with a local setup.
Closing it.
