### ISSUE TITLE
Redo DevModeHandlerStopTest

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#6053]
`DevModeHandlerStopTest` is ignored at the moment.
It freezes Java 11  validation build.
Also it freezes PR validation sometimes.

The test takes a lot of time even when it works as it should.

Redo the test and enable it.
Try to avoid HTTP communication if it's possible.

The network communication is the reason of test freeze:

```
 Running com.vaadin.flow.server.DevModeHandlerStopTest
[19:28:27][Step 3/3] The build Nightly::Flow Java 11 Nightly #253 {buildId=72553} has been running for more than 200 minutes. Terminating...
[19:28:27][Step 3/3] Execution timeout
```

**Comment by denis-anisimov** [comment]
This is a bug somewhere which results as a bug in our validation process.
Even though it's an internal thing we are lacking an important test for now until this fixed.

**Comment by mshabarov** [comment]
`DevModeHandlerStopTest` doesn't exist anymore.
