### ISSUE TITLE
Build: bower resources requested from npm project

### ISSUE THREAD

**Issue by gsedlacz** [vaadin/flow#6073]
I currently try to migrate a plugin from bower to npm.
So I tried adding it to another project but from then on the projects frontend started requesting resources from bower URLs.

Setup: 
1. Starter project (using vaadin 14.0.0.rc5) 
2. My plugin (using vaadin 14.0.0.rc5)

The plugin itself requires an npm package using the @NpmPackage Annotation.
The build log lists the npm dependency correctly. 

Java version: Dcevm-11.0.1+8
OS: Win 10 1903
Browser: Chrome & FF 

![image](https://user-images.githubusercontent.com/33100708/61231618-c2cb1700-a72c-11e9-9f22-99a3ad3515de.png)

tooltip.js is a custom file included in the plugin that was requested correctly.

**Comment by denis-anisimov** [comment]
Sorry, I don't understand anything.

Please provide exact steps to reproduce: the steps which I may use without any additional information to reproduce the same behavior.
Expected result.
Actual result.

Would be nice to attach project(s) which I may use to reproduce.

**Comment by gsedlacz** [comment]
The issue was on my end. I used the code below to define a npm dependency but webpack failed to resolve the `@JsModule` part.
```java
@NpmPackage(value = "tippy.js", version = "4.3.4")
@JsModule("./tippy.js/esm/index.all.min")
@JavaScript("./js/tooltip/tooltips.js")
@Tag("div")
public class TooltipsJsProvider extends Component {}
```
