### ISSUE TITLE
Task copying frontend resources does not visit the full classpath (dev-mode 2.0.3) 

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#6074]
### Issue
- clone `bookstore-starter-flow` project
- update platform version to 14.0.0.rc5
- when in the root folder run `mvn install -DskipTests`
- move to the bookstore-starter-flow-ui and run `mvn jetty:run`
- you can see that `web-pack-dev-server` fails because it does not find connectors in `node_modules/@vaadin/flow-frontend`

### Cause

`TaskUpdatePackages` cleans the `node_modules` folder because platform version changed, but `TaskCopyFrontendFiles` does not copies all the files since apparently the system property `java.class.path` does not include all the jars in the application classpath.

In my local only one jar was passed `/usr/local/Cellar/maven/3.6.0/libexec/boot/plexus-classworlds-2.5.2.jar` which obviously is not the classpath of the application. The servlet container does not set the system property appropriately, and we need to figure out the jars used in the app from the class loader 

### Workaround

run `mvn prepare-package` before running `mvn jetty:run` the first time. It needs to be run again after cleaning or changing dependencies

**Comment by caalador** [comment]
The question is why would you use maven without using the maven plugin?
The runtime copying is only for when the application is started from an ide that actually adds the dependencies to the property (maven doesn't do this).

I expect the problem is that the copyResources step is in `BuildFrontend` and not in `PrepareFrontend`

**Comment by Legioth** [comment]
https://github.com/vaadin/flow/pull/6083 will also be needed before this issue can be properly closed.
