### ISSUE TITLE
DevModeServletContextListener.contextInitialized() very slow performance

### ISSUE THREAD

**Issue by ggecy** [vaadin/flow#6082]
I am trying to migrate our project to vaadin 14.0.0.rc5. When compared to vaadin 13, the startup takes over twice the time, it takes several minutes while before it started within a minute. The biggest culprit seems to be be the scanning of large number of classpath resources in development mode in DevModeServletContextListener.contextInitialized(), on the following lines:
```
// Handle classes Route.class, NpmPackage.class,
// WebComponentExporter.class
Set<String> allClasses = Collections.singleton("");
Set<Class<?>> classes = findByAnnotation(allClasses, customLoader,
            Route.class, NpmPackage.class).collect(Collectors.toSet());
```

The customLoader loads over 43 000 resources since it scans all packages except those in blacklist and there is no way to restrict which packages to scan in the first place. We have thousands of packages in code itself and in dependencies and adding them all to blacklist would be next to impossible. There should be a way to restrict which resources are inspected instead of scanning all of them.

    - Vaadin / Flow version - 14.0.0.rc5
    - Java version - 11
    - OS version - Windows 10

**Comment by denis-anisimov** [comment]
Right, we have improved the start up time issue regarding scanning since `beta`.
But apparently this is still an issue.

We are considering to add white list in addition to black list.

Also it would be helpful if you may provide packages that you use in the project and they should be blacklisted. If they are general enough we may include them into black list out of the box.

**Comment by caalador** [comment]
Acceptance criteria:
- There is a white-list that will be exclusively used for package scanning if given.
- When having a white-list, the black-list should not be used.
- White-list should be configurable through application.properties and maven or system/application property
- white-list functionality should be added to the documentation: https://github.com/vaadin/flow-and-components-documentation/blob/29faa10493d33e577246e1e60aeee51ca07b32e6/documentation/spring/tutorial-spring-configuration.asciidoc#special-configuration-parameters

**Comment by ggecy** [comment]
> Right, we have improved the start up time issue regarding scanning since `beta`.
> But apparently this is still an issue.
> 
> We are considering to add white list in addition to black list.
> 
> Also it would be helpful if you may provide packages that you use in the project and they should be blacklisted. If they are general enough we may include them into black list out of the box.

Hi, I tried to extract all directory paths from all jars (from version before migration to vaadin 14, so there are some webjars in there). See attachment.

[directories_from_all_jars.txt](https://github.com/vaadin/flow/files/3401137/directories_from_all_jars.txt)

**Comment by denis-anisimov** [comment]
Thank you 👍
