### ISSUE TITLE
CssImport annotation could mention from where it trying to find css files given to it

### ISSUE THREAD

**Issue by alump** [vaadin/flow#6086]
Right now there is no mention in JavaDoc of CssImport annotation from where it will try to locate those files given.

I do get error:

>   Failed to find the following css files in the `node_modules` or `/frontend` tree:
>       - foobar.css
>   Check that they exist or are installed.

So error kinda helps, but to avoid people first doing it wrong, maybe JavaDoc could also mention this. Or this some dynamic thing that is different depending on project mode (bower/npm) and because of that it's not mentioned at all?

Also as JavaDoc doesn't mention any limitations, are all these 4 different modes valid for both Polymer2/Bower and Polymer3/NPM applications?

Same JavaDoc is also missing `@since` part. I assume it should be defiend as it is for other annotations from same package.

**Comment by denis-anisimov** [comment]
I've fixed the javadocs in a PR.
I will create another ticket about `since` because I don't know how they are handled nowadays: should be add an empty `since`, should we add a proper `since` or should we add anything at all.
It will be better to have a separate discussion about this.

**Comment by denis-anisimov** [comment]
Another ticket for `since`  is created : https://github.com/vaadin/flow/issues/6155
