### ISSUE TITLE
Editing a template doesn’t load components

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#6087]
https://github.com/vaadin/designer/issues/2087

**Comment by mehdi-vaadin** [comment]
I couldn't reproduce this issue in IntelliJ IDEA. It works as expected. I'll try with Ecplise and Vaadin designer.

**Comment by mehdi-vaadin** [comment]
It seems that the problem is on the designer's side. https://github.com/vaadin/designer/issues/2087#issuecomment-512759222
So, I'm closing this ticket.

**Comment by Legioth** [comment]
This is not a problem in Designer, but rather a the same issue as https://github.com/vaadin/flow/issues/6098.
