### ISSUE TITLE
V14rc6 DatePicker and Text Area have no styles if added from designer to polymer 3 template

### ISSUE THREAD

**Issue by Skrikjo** [vaadin/flow#6098]
Steps to reproduce:
* download starter for spring app
* add new view:
```
package com.packagename.myapp.spring;

import com.vaadin.flow.component.Tag;
import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.polymertemplate.PolymerTemplate;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.templatemodel.TemplateModel;

@Tag("other-view")
@JsModule("./src/other-view.js")
@Route("other")
public class OtherView extends PolymerTemplate<TemplateModel> {
}

```
* create new template with designer and drag and drop datepicker and text area. here is generated code:
```
import {html, PolymerElement} from '@polymer/polymer/polymer-element.js';
import '@vaadin/vaadin-date-picker/src/vaadin-date-picker.js';
import '@vaadin/vaadin-text-field/src/vaadin-text-field.js';
import '@vaadin/vaadin-button/src/vaadin-button.js';

class OtherView extends PolymerElement {

    static get template() {
        return html`
<style include="shared-styles">
                :host {
                    display: block;
                }
            </style>
<vaadin-date-picker></vaadin-date-picker>
<vaadin-text-field label="Make a wish" placeholder="Placeholder"></vaadin-text-field>
<vaadin-button theme="primary">
  Primary 
</vaadin-button>
<vaadin-button theme="primary success">
 GOOD! 
</vaadin-button>
<h3>That is an other view </h3>
`;
    }

    static get is() {
        return 'other-view';
    }

    static get properties() {
        return {
            // Declare your properties here.
        };
    }
}

customElements.define(OtherView.is, OtherView);
```

* run app and go to /other
Result: date picker and textfield are there but have no styles:
<img width="602" alt="Screenshot 2019-07-18 at 16 01 57" src="https://user-images.githubusercontent.com/42034381/61459442-660e6d00-a975-11e9-89d0-2039e5953785.png">

dependency is in pom:
```
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-date-picker-flow</artifactId>
        </dependency>
```

Note:  After adding DatePicker to MainView in java,  styles are loaded to other-view as well so all working as expected

**Comment by denis-anisimov** [comment]
Does the initial project has `Lumo`  in the classpath ?
It looks like the same as the issue which has been already (kind of) fixed: https://github.com/vaadin/flow/issues/5672

**Comment by denis-anisimov** [comment]
>I think it's the same issue as vaadin/designer#2087. I'm closing this issue. Please reopen it if you think it's different.

Better to close another one since this is a good issue: it contains the steps to reproduce the issue without designer.

**Comment by Legioth** [comment]
> Does the initial project has Lumo in the classpath 

I tested with Beverage Buddy, which indeed has Lumo on the classpath. If I add e.g. a `<vaadin-button>` to the template instead, then that button will be styled with Lumo because it's also used from the Java code which does trigger loading the right style module.
