### ISSUE TITLE
npm build: bower resources requested from npm project in Eclipse with Wildfly (using JBoss Tools)

### ISSUE THREAD

**Issue by gsedlacz** [vaadin/flow#6103]
Under the circumstances described below Vaadin goes into compatibility mode (bower) despite the lack of bower resources described in the pom.xml. This is not a general problem with Wildfly as deploying a non exploded war (the result of `mvn package`) works perfectly fine.

To me this bug is dealbreaker for Vaadin 14 and npm as this setup provided me with hot code and resource replacement.

- Minimal reproducible example:
  1. Download the V14 Vaadin starter project:
![image](https://user-images.githubusercontent.com/33100708/61579080-b36b1580-ab00-11e9-96f6-717ded5a1c6a.png)
  2. Import as Maven project in Eclipse
  3. Install Wildfly 16 and configure it with Eclipse (JBoss Tools)
  4. `$ mvn clean package` on the project
  5. Add add the project to your Wildfly
    * Go to the 'Server' view
    * Right click your Wildfly server
    * Select 'Add and Remove...'
    * ![image](https://user-images.githubusercontent.com/33100708/61579086-c54cb880-ab00-11e9-9ed7-18c785963d67.png)
  6. Start your Wildfly from within the IDE
- Expected behavior:
  Vaadin should request resources created during the npm-based build
- Actual behavior:
  Vaadin for some reason goes into compatibilty mode and requests bower resources (see: image at the bottom)
- Eclipse version: 2019-06 (4.12.0) Build id: 20190614-1200
  - Vaadin Plugin for Eclipse 4.0.2
  - JBoss Tools 4.12.0.Final
- Vaadin / Flow version: 14.0.0.rc6
- Java version:
  1. Java 11 Adopt JDK
  2. Java 11 DCEVM

1 Adopt version:

``` cmd
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
```

2 DCEVM version:

``` cmd
HOTSWAP AGENT: 14:32:37.612 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.3.1-SNAPSHOT} - unlimited runtime class redefinition.
HOTSWAP AGENT: 14:32:37.857 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, JdkPlugin, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, Seam, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin, Wicket, CxfJAXRS, FreeMarker, Undertow]
Starting HotswapAgent 'C:\SDK\Java\dcevm\dcevm-11.0.1+8\lib\hotswap\hotswap-agent.jar'
openjdk version "11.0.1.6" 2018-12-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1.6+8-201904021629)
Dynamic Code Evolution 64-Bit Server VM AdoptOpenJDK (build 11.0.1.6+8-201904021629, mixed mode)
```

- OS version: Windows 10 (1903 - 18362.239)
- Browser version: 
  1. Chorme (75.0.3770.142)
  2. Firefox (68.0.1)

![image](https://user-images.githubusercontent.com/33100708/61579126-7ce1ca80-ab01-11e9-9a72-6a0f268c0407.png)

This is basically a simplified version of [this ticket (#6073)](https://github.com/vaadin/flow/issues/6073) as I initially thought the problem was caused by some more special circumstances.

**Comment by joheriks** [comment]
Does the problem get solved if you ask Eclipse to refresh the project files (F5) after `mvn package` and before adding the module exploded to Wildfly? The problem seems to be that `flow-build-info.json` (which configures npm mode by setting `vaadin.compatibilityMode` to false), does not get copied to `$WILDFLY_HOME/standalone/deployments/my-starter-project-2.0-SNAPSHOT.war/WEB-INF/classes/META-INF/VAADIN/config/`.

**Comment by gsedlacz** [comment]
Yes, it does! 
But as soon as I update the maven project manually from within Eclipse the project is broken again.
Refreshing doesnt help from then on. 

![image](https://user-images.githubusercontent.com/33100708/61659597-19ee6000-acc8-11e9-9a9b-e499bd8607ab.png)

**Comment by joheriks** [comment]
We are currently looking into how to reliably detect the right mode to start in. As a workaround, after updating the maven project in Eclipse, you can manually run the maven goal `prepare-package` via run configuration. In this run configuration, enable Refresh -> Refresh resources upon completion, then Wildfly will pick up the changes.

**Comment by gsedlacz** [comment]
Thank you for replying this quick.
Ill give it a try tomorrow.

**Comment by joheriks** [comment]
From Flow 2.0.6 (platform 14.0.0.rc8 once released), the Vaadin Maven plugin automatically runs `prepare-frontend` goal (which in turn copies `flow-build-info.json` to the deployment classpath) when the project is updated in Eclipse.
