### ISSUE TITLE
Html component can only be used once per instance

### ISSUE THREAD

**Issue by akovac35** [vaadin/flow#6104]
Suppose you have the following code, Flow 14 rc6:

```
public class ApplicationView extends AppLayout{

	Html helpContentsHtml = new Html("<span>Pozdravno <b>besedilo</b> oz. kaj drugega.</span>");
	public Dialog helpDialog = new Dialog();

	public ApplicationView() {
		super();
		helpDialog.add(helpContentsHtml);
		setContent(helpContentsHtml); // Causes Dialog to not display Html component
		helpDialog.open();
	}
}

```

The Dialog will not display HTML if Html component was already added to some other component.

**Comment by joheriks** [comment]
As `Html` is a `Component` it can only be owned by a single container at a time. The `setContent` call transfers the component `helpContentsHtml` to `ApplicationView` and away from the dialog.
