### ISSUE TITLE
No server request when clicking back button from programmatically updated URL 

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#6107]
To reproduce:
- Unzip and start the attached application: `mvn spring-boot:run`
- Open `http://localhost:8080/editor/1?queryvalue=foo`
- Click the button `Change query parameter` to navigate to `http://localhost:8080/editor/1?queryvalue=bar`.
- Click back button

Actual outcome: No network activity when clicking back button

Expected outcome: `http://localhost:8080/editor/1?queryvalue=foo` is requested from server

[querynavigation.zip](https://github.com/vaadin/flow/files/3419212/querynavigation.zip)

Browsers: Safari, Edge, Chrome, and Firefox

**Comment by bbaumgartner** [comment]
Thank you!

**Comment by ujoni** [comment]
Fix in Flow versions:
- `1.0.13`
- `1.4.8`
- `2.0.6`
