### ISSUE TITLE
As a developer I want to use server-side components from a template so that I can layout my entire application through HTML

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#611]
It should be possible to include a server-side component based on a Java class into a HTML template. It shouldn't matter whether the component is a `Template`, a `Composite` or directly based on an `Element`.

One practical example of this is to use a date picker component that is implemented as a server-side composite using three `<select>` elements; one for the year, one for the month and one for the day of the month.

Initial design thoughts:
- The Java API of the component defines how it can be configured declaratively
  - Any setter in the component's API is available as a bindable property. The setter is run whenever the value of the binding changes.
    - What happens when binding to properties without a corresponding setter? Exception? Binding as a regular property on the root element? Silently ignored? Separate binding syntax for element properties and bean properties? The binding is always tied to an element property, and the actual feature is that the Java setter is run when the property value is changed?
  - The component API can somehow define how children defined in the template should be passed to the component.
    - Might cause surprises with theming if the DOM structure does not match the structure in the HTML file (i.e. because the component implementation wraps children in an additional element so that `.parent > .child` does not match.
  - Should declarative event handlers somehow be mapped to `ComponentEventListener`?
- One consequence of defining bindings relative to the server-side Java API is that e.g. latency compensation with client-side model updates will not be effective for bindings to that component.
- This does effectively replicate the mechanism of a Web Component, but implemented on the server instead of the client.
  - Might actually want to define a component used in this way as a custom element with its own internal DOM inside the shadow DOM? This might require some fundamental changes to the framework.
- What is the template syntax for including a server-side component based on a Java class? How to avoid conflicts with actual web components? How to avoid writing the fully qualified class name into the template?

**Comment by pleku** [comment]
This is still valid but has not gained traction.

**Comment by Artur-** [comment]
Isn't this what you would do with `<slot>` in the template and `add(myComponent)` in Java?

**Comment by pleku** [comment]
>Isn't this what you would do with <slot> in the template and add(myComponent) in Java?

I don't know. If someone runs into this and cares enough, they will open a new enhancement issue.
