### ISSUE TITLE
Typo in dom.Element?

### ISSUE THREAD

**Issue by zanonmark** [vaadin/flow#6117]
I refer to [Element](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/dom/Element.java): should `innertHTML` (line 79) be `innerHTML` instead?

Thanks,
MZ

**Comment by Legioth** [comment]
Yes. Thanks for noticing. Will be fixed by https://github.com/vaadin/flow/pull/6118.
