### ISSUE TITLE
Add NPM content for flow-client initialisation

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6130]
When bootstrapping a Vaadin 15+ app from client-side code, I want to import the relevant APIs from the ~~`@vaadin/flow`~~  ~~`@vaadin/flow-deps`~~  `@vaadin/flow-frontend`  npm package, so that it looks and feels like any other client-side dependency of my app.

Example:
```js
// The @vaadin/flow package is small (few kBs)
import {Flow} from '@vaadin/flow-deps';

// This does not load Flow yet, only sets the config
const flow = new Flow({ ... });

// This loads Flow and lets it take over the page
flow.start();
```

The package should include TypeScript type definitions for all public APIs (`d.ts` files)

DoD
 - Scaffolding of the package with `package.json` and `flow.js` with the exported class defined and empty methods of the API
 - update pom.xml so that `mvn verify` runs tests (intern). The test verifies that the sample snippet above compiles and runs.
 - no publishing to npm at the moment (packaging into .jar and using ~~`@vaadin/flow-deps`~~  `@vaadin/flow-frontend` instead)
 - the changes should be done to the flow-client module

**Comment by vlukashov** [comment]
npm does not have snapshots.
For projects relying on Java snapshot builds of Flow, the dependency on`@vaadin/flow` needs to get resolved some other way than relying on npm. The proposal at this point is to use the approach from `@vaadin/flow-deps` and let it take the npm package contents from the flow-client.jar file.

**Comment by manolo** [comment]
Notice that flow copies to `@vaadin/flow-frontend`
