### ISSUE TITLE
Create a IndexHtmlRequestHandler, able to return an index.html based on a template

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6135]
When opening a Vaadin 15+ app, I want the response to my HTTP GET request to come from a new `IndexHtmlRequestHandler` (rather than from the V14 `BootstrapHandler`), so that the response is based on an `index.html` file, and does not include the server-side app bootstrap code as in V10-14.

- It would change the baseHref and update script tags
- It should cover returning index when routes defined in client side (like vaadin-frontend-server does)
- It should handle requests for "routes" (e.g. no file extension) but shouldn't interfere with requests for static resources such as images (so that you either get the resource or a plain 404 response)
- It should take the index.html file that webpack copies to the build folder in production, but in devmode it should request the file from webpack-dev-server. This prevents restarting servlet container unnecessarily when index.html is modified
- If [BootstrapHandler mode](https://github.com/vaadin/flow/issues/6136) is enabled, it delegates the handling to the old BootstrapHandler instead.

**Comment by qtdzz** [comment]
>It should cover returning index when routes defined in client side (like vaadin-frontend-server does)

>It should handle requests for "routes" (e.g. no file extension) but shouldn't interfere with requests for static resources such as images (so that you either get the resource or a plain 404 response)

To clarify this, for now, the `IndexHtmlRequestHandler` should completely ignore requests with an extension instead of checking its existence and returning the `index.html` if it doesn't exist (like `vaadin-frontend-server`)

**Comment by qtdzz** [comment]
Fixed by #6167
