### ISSUE TITLE
Ensure bootstrapping compatibility with V14

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6136]
When upgrading a Vaadin app from V14 to V15, I want the response to my HTTP GET request to come from the V14 `BootstrapHandler`, so that the existing server-side bootstrapping keeps working and I do not have to rewrite the app to use client-side bootstrapping.

- add a `clientSideBootstrap` property (Servlet parameter) similar to `compatibilityMode` 
- the default value of `clientSideBootstrap` is false (use server-side bootstrapping)
- keep the existing `BootstrapHandler` (if clientSideBootstrap is false)
- the Maven plugin needs to know that property as well (thus, it needs to be a maven property that's put to the token file)
- that will have all the same problems as the npm model property (not set if started e.g. directly from Eclipse)

**Comment by qtdzz** [comment]
The property was added in #6167.
#6186 finalizes it by using the property to generate proper webpack config for the new mode.
