### ISSUE TITLE
Create documentation structure for client-centric features

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6141]
When adding client-side bootstrapping, client-side routing, TypeScript views, Connect, and other client-side centric features to Vaadin, as a Vaadin core developer, I want to have a high-level table of contents or a documentation outline so that it's clear what documentation needs updating and where to add / modify doc articles.

- Create the ‘table of contents’ level of detail
- Specific details of each feature are documented in scope of each ticket separately

**Comment by qtdzz** [comment]
Here is how I think we can add CCDM documentation

* CCDM architecture and its big picture might be fit in a new section inside "Introduction to Vaadin Flow", (similar to the old Flow architecture)

* CCDM is probably worth a separate section (as a sibling of "Overview", "Introduction", ...):
    * Introduce more about the new mode (why it exists? when people should use it instead of the current approach) and how to enable it
    * Introduce about the client-side bootstrapping
        * index.html content is available in frontend folder
        * `@vaadin/flow` package
    * Introduce briefly about vaadin-router and how the client-side routing works
    * How to migrate from v14 to this version without breaking the application
    * (Tutorial): how to combine vaadin-flow and vaadin-connect?

* A new section could be mentioned in "Router and Navigation" section:
    * What happens to the old `@Route` when using client-side routing
    * How to use `RouterLayout` in server side for client-side view and vice versa.

* Modifying the index html response with listeners could be mentioned in "Modifying bootstrap page" inside "Advanced Topics"

As Viktor pointed out, for now, **it is not clear** where the documentation should be but at least we can start with the content of the second bullet.

**Comment by vlukashov** [comment]
done in https://github.com/vaadin/flow-and-components-documentation/pull/984
