### ISSUE TITLE
Add onFirstAttach or similar method to promote best practices

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#6146]
It can be considered a bad practice to initialize components in the constructor, because

1. A component might be created, but never used, especially when using dependency injection.
2. When handling route security in `beforeEnter`, route target instances are already created, see #4595 

An alternative approach is to initialize components in `onAttach`. However, some of the initialization logic should only be executed once per component.

While it is straightforward to keep track of if `onAttach`  has already been called, by adding a `onFirstAttach` or similar method, that is guaranteed to be called at most once per component by the Flow framework, there would be a more obvious place to put this kind of code.

Edit: There is `attachEvent.isInitialAttach()` which makes it trivial to check in `onAttach`, so it's mostly a matter of taste if a method like my suggestion should exist.

**Comment by denis-anisimov** [comment]
>Edit: There is attachEvent.isInitialAttach() which makes it trivial to check in onAttach, so it's mostly a matter of taste if a method like my suggestion should exist.

Exactly.

I think an extra method will jus complicate the API : it becomes hard to understand why those methods are needed.

I would suggest to close the ticket since there is already required functionality.
