### ISSUE TITLE
Goal prepare-package hangs in RC7

### ISSUE THREAD

**Issue by vonloxley** [vaadin/flow#6181]
## Description of the bug
The build-process hangs at the goal `prepare-package`. If we kill `node` three times it continues until `Running npm install` then one needs to kill node again. Aftrer that it works flawlessly.  Please see the attached log [killingnode.txt](https://github.com/vaadin/flow/files/3471354/killingnode.txt). Other people have the [same problem](https://vaadin.com/forum/thread/17779813/build-hangs-on-vaadin-maven-plugin-execution)

We do have a proxy in our company, but it is configured correctly in Java/Maven and we didn’t have any problems until 2019-08-05. The networking department assured me that there were no changes to proxy/firewall/etc.

Just tell me if I can be of any assistence.

## Minimal reproducible example
- Starter project
- downloaded today
- version14
- CDI and Java EE

## Expected behavior
The project build after typing `` mvn package``
## Actual behavior
The build hangs at prepare-package.

## Versions
- Vaadin / Flow version 14
- Java version javac 12.0.2
- OS version Windows 10
- Node 10.16.1 (Node 10.16.0 doesn’t wor either.)
- Browser version (if applicable) N/A

**Comment by caalador** [comment]
At the point you need to kill node 3 times we do a version check for node and npm using `node --version` and `npm --version`, but I can't find a 3rd instance that would call for node.

`npm install` is already in the build-frontend mojo as prepare doesn't do a npm install step.

What maven version are you using? 
Also did it break between a version change (from rc6 to rc7) or just stop functioning suddenly?
What if you run `node --version` in a command window does it terminate as expected?

**Comment by vonloxley** [comment]
Hi there, thanks for answering.

I tried with Maven 3.3.9 and 3.6.1. The node/npm version checks work fine for me:
```
C:\Windows\System32>node --version
v10.16.1

C:\Windows\System32>npm --version
6.9.0

C:\Windows\System32>
```
```
C:\Temp\a>npm install uglify-js
npm WARN saveError ENOENT: no such file or directory, open 'C:\Temp\a\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Temp\a\package.json'
npm WARN a No description
npm WARN a No repository field.
npm WARN a No README data
npm WARN a No license field.

+ uglify-js@3.6.0
added 3 packages from 38 contributors and audited 3 packages in 1.199s
found 0 vulnerabilities


C:\Temp\a>dir
 Datenträger in Laufwerk C: ist system
 Volumeseriennummer: 7E05-B896

 Verzeichnis von C:\Temp\a

07.08.2019  11:04    <DIR>          .
07.08.2019  11:04    <DIR>          ..
07.08.2019  11:04    <DIR>          node_modules
07.08.2019  11:04               915 package-lock.json
               1 Datei(en),            915 Bytes
               3 Verzeichnis(se), 367.541.350.400 Bytes frei

```
I recounted the killings and it definitely takes 3 kills (and one after npm install in build-frontend).

It stopped working suddenly, which is why I suspected a network snafu first. However, as all downloads work I’m not so sure about that. We used RC7 the whole time.

We will be trying to test the build on a windows machine without proxy later. However, I feel that the vaadin-build-process should work through a corporate proxy.

**Comment by caalador** [comment]
Are you able to run the following program:
```
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class Version {
    public static void main(String args[]) throws Exception {
        ProcessBuilder processBuilder = new ProcessBuilder("npm.cmd", "--version");

        Process process = null;
        try {
            process = processBuilder.inheritIO().start();
            int errorCode = process.waitFor();
            try (BufferedReader br = new BufferedReader(
                    new InputStreamReader(process.getInputStream()))) {
                System.out.println(br.lines());
            }
            if (errorCode != 0) {
                System.out.println("Error");
                return;
            } else {
                System.out.println("success");
            }
        } catch (InterruptedException | IOException e) {
            System.out.println(e);
        } finally {
            if (process != null) {
                process.destroyForcibly();
            }
        }
    }
}
```
This should be close to what the plugin also executes.
npm.cmd could also be given as `"C:\\Program Files\\nodejs\\npm.cmd"`

**Comment by vonloxley** [comment]
This worked without problems:
```
C:\Temp\tt>javac Version.java

C:\Temp\tt>java Version
6.9.0
java.util.stream.ReferencePipeline$Head@58372a00
success

C:\Temp\tt>
```

**Comment by caalador** [comment]
I guess chaning `npm.cmd` to `node.exe` also works without a problem.

**Comment by vonloxley** [comment]
Yep:
```
C:\Temp\tt>java Version
v10.16.1
java.util.stream.ReferencePipeline$Head@58372a00
success
```

We tried on a Windows-PC that doesn’t have to go through a proxy and the build works on this computer. So the problem is proxy related. What bugs me is that it worked lat week. Our proxy-configuration is quite good and I don’t see why it shouldn’t work. We do configure the proxy in:
# Maven (settings.xml)
# Node (.npmrc)
# Java (run with `-DproxySet=true -DproxyHost=… -DproxyPort=…`)

**Comment by caalador** [comment]
Found this that would point to a PATH fault and npm hanging due to that.

https://stackoverflow.com/questions/28384040/npm-install-does-nothing-how-make-it-work/29806771#29806771

**Comment by caalador** [comment]
Apparently setting https://docs.npmjs.com/misc/config#strict-ssl to false may fix this issue. At least it was the case for another who had the same problem.

**Comment by vonloxley** [comment]
Hi caalador!

I checked the temp-path and it is not the issue here. I am certainly not going to unset strict-ssl. This might be necessary if your anti-virus or proxy breaks up your ssl-connections and presents you with an untrusted certificate but this is not the case here.

I’ll wait for #6502 to be (pre-)released and give feedback then.

**Comment by vonloxley** [comment]
#6502 doesn't fix the problem.

I hunted the hang down to `FrontendUtils.java`:
```
        try {
            file = defaultLocation == null
                    ? frontendToolsLocator.tryLocateTool(cmd).orElse(null)
                    : Optional.of(new File(baseDir, defaultLocation))
                            .filter(frontendToolsLocator::verifyTool)
                            .orElseGet(() -> frontendToolsLocator
                                    .tryLocateTool(cmd).orElse(null));
            LoggerFactory.getLogger(FrontendUtils.class).debug("3.2");
        } catch (Exception e) { // NOSONAR
            // There are IOException coming from process fork
        }

```
but don’t have more time for debugging today. Does this help?

**Comment by caalador** [comment]
Yes 6502 does seem to have a similar problem with the readLine hanging.
We made a change so that we do not use buffered reader at all as we want 
in this case always read the whole input so we changed the implementation in #6513

**Comment by vonloxley** [comment]
#6513 doesn’t do it for me either :(.
The process hangs for 5 minutes in `private Optional<CommandResult> executeCommand(boolean logErrorOnFail, String... commandParts)`at `String stream = IOUtils.toString(process.getInputStream(), StandardCharsets.UTF_8);`. 

The command run was `[C:\Program Files\nodejs\npm.cmd, -v]`, the return-value: `[6.9.0]`, which is absolutely allright.

**Comment by vonloxley** [comment]
Stefan Apelt found the [solution](https://vaadin.com/forum/thread/17779813/17930518).

NPM makes a version check over the internet on _every_ invocation and ignores it’s proxy setting. One can diabale this check with the environment-variable `NO_UPDATE_NOTIFIER=1`.

Would it be possible, to include this setting in the maven plug-in to reduce build-time and support people behind corporate proxies?

**Comment by pleku** [comment]
@vonloxley definitely we need to address this, thanks for sharing the finding.

**Comment by caalador** [comment]
That's a good find. We really don't need npm to do anything extra for `npm -v`, especially not a call out to check for updates.
