### ISSUE TITLE
Vaadin Flow OSGI starter webapp bundle, does not start in karaf 4.2.6

### ISSUE THREAD

**Issue by redshift72** [vaadin/flow#6184]
I downloaded the Vaadin flow for OSGI starter example. I imported it into Eclipse and built it with maven.   When I deploy  in karaf 4.2.6, it doesn't start.
In karaf log: 
Error executing command: Error executing command on bundles:
	Error starting bundle 196: Unable to resolve my-starter-project [196](R 196.1): missing requirement [my-starter-project [196](R 196.1)] osgi.wiring.package; (&(osgi.wiring.package=com.vaadin.flow.component)(version>=1.4.0)(!(version>=2.0.0))) Unresolved requirements: [[my-starter-project [196](R 196.1)] osgi.wiring.package; (&(osgi.wiring.package=com.vaadin.flow.component)(version>=1.4.0)(!(version>=2.0.0)))]

vaadin 13.0.11 
flow-server 1.4.7
Apache karaf 4.2.6 
openjdk version "1.8.0_212"
OS linux ubuntu LTS 16.04

**Comment by pleku** [comment]
I'm going to merge this issue into #6525 which is a later issue but for 14 and considered as an enhancement at this point.
