### ISSUE TITLE
Version bump from 13 to 14 is broken because of not setting compatibilityMode explicitly

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#6188]
Minimal reproducing instructions:
- Checkout v13 branch
- Bump `vaadin.version` to `14.0-SNAPSHOT`
- Add `flow-server-compatibility-mode` dependency like this
```
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>flow-server-compatibility-mode</artifactId>
    <version>2.0.6</version>
</dependency>
```
- Run `mvn spring-boot:run`

Expected behavior:
The app works.

Actual Behavior:
It gives the following error:
```
java.lang.IllegalStateException: Unable to determine mode of operation. 
To use npm mode, ensure 'flow-build-info.json' exists on the classpath. 
With Maven, this is handled by the 'prepare-frontend' goal. 
To use compatibility mode, add the 'flow-server-compatibility-mode' dependency.
```

Setting `vaadin.compatibilityMode` explicitly to `true`, e.g. in `application.properties`, solves the problem.
[Verify version bump on skeleton-starter-flow-spring](https://bender.vaadin.com/viewType.html?buildTypeId=Flow_VersionBumpValidationFrom13to14_VerifyVersionBumpOnSkeletonStarterFlowSprin) build in TeamCity should also be fixed.

**Comment by joheriks** [comment]
Decided to set the property `vaadin.compatibilityMode` explicitly in Spring starter. Need to update the error message to inform about this requirement.

**Acceptance criteria:**
- The exception raised by `DefaultDeploymentConfiguration` should include a line informing users that Spring applications requires to set `vaadin.compatibilityMode` in ` application.properties`.

**Comment by joheriks** [comment]
All criteria check out.
