### ISSUE TITLE
location.getPathWithQueryParameters() should return empty string if there is no path

### ISSUE THREAD

**Issue by Ansku** [vaadin/flow#6195]
Class `com.vaadin.flow.router.Location` contains method `getPathWithQueryParameters()` that returns `.` in the case that there is no path. This is a workaround for a previous issue that caused incorrect navigation in some cases. The workaround should be moved to its own method, so that this method can return just an empty String like `getPath()` and `getQueryParameters()` already do. The workaround is needed for classes `com.vaadin.flow.component.UI`, `com.vaadin.flow.component.page.History`, and `com.vaadin.flow.router.Router`, as well as various tests.

**Comment by mehdi-vaadin** [comment]
See the related discussion in Slack [here](https://vaadin.slack.com/archives/C6X43FE8M/p1565168161245300).

**Comment by denis-anisimov** [comment]
`getPathWithQueryParameters` delegates directly to the `getPath` method currently.
So it works same way as `getPath`.
The ticket says that `getPath` works already in the expected way.
So this is not an issue anymore.

I can confirm that `new Locaiton("").getPathWithQueryParameters()`  returns an empty string and not ".".
