### ISSUE TITLE
Load order guarantee of @JavaScript (broken) and @JsModule annotations

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#6198]
In Vaadin 13, if I add the following `@JavaScript` annotations to a view:
```
@JavaScript("javascript/a.js")
@JavaScript("javascript/b.js")
@JavaScript("javascript/c.js")
```
they are loaded in the order of annotations. This is a documented feature (https://vaadin.com/docs/v13/flow/importing-dependencies/tutorial-ways-of-importing.html).

In Vaadin 14 (rc7), the order is arbitrary because of the way entries in `flow-generated-imports.js` are handled. Console output (each JS file `console.warn`s filename and containing directory) for the above:

<img width="355" alt="Screenshot 2019-08-07 at 19 43 30" src="https://user-images.githubusercontent.com/2838896/62641392-202d3f00-b94c-11e9-9949-5db85efc5fb6.png">

Expected behavior: The load order is consistent with the annotation order.

The same arbitrary order applies to `@JsModule` annotations. These should also be internally ordered according to the annotation order.

When designing, need to make decision whether we also want to provide load order guarantee between interleaved `@JsModule` and `@JavaScript` annotations. In V13, there is no order guarantee between different annotation types (e.g. `@StyleSheet` and `@JavaScript`).

Example project attached. 
[v14starter.zip](https://github.com/vaadin/flow/files/3478070/v14starter.zip)

(This issue is not present in Vaadin 14 in compatibility mode)

**Comment by TheSilentHorizon** [comment]
Is this eventually related with the problem i have? When i add a Vaadin Component, i hadnt use before, my whole project seems to have Javascript Issues. I can resolve this issue only by:

- deleting npm_modules
- delteing package-lock.json
- run "mvn clean package"

Related error and webpack-config.js

> > Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-text-field" has already been used with this registry
> 
> On my login page, my vaadin checkbox did also disappear because of this, so i think its somewhat related.
> 
> Also, here are my flow-imports.js . ComboBoxConnector has been put for whatever reason to the end.
> 
> ```
> 
> `import '@vaadin/vaadin-lumo-styles/icons.js';
> import '@vaadin/vaadin-lumo-styles/spacing.js';
> import '@vaadin/vaadin-lumo-styles/typography.js';
> import '@vaadin/vaadin-lumo-styles/style.js';
> import '@vaadin/vaadin-lumo-styles/color.js';
> import '@vaadin/vaadin-lumo-styles/sizing.js';
> import '@vaadin/vaadin-text-field/theme/lumo/vaadin-password-field.js';
> import 'jquery-sparkline/jquery.sparkline.js';
> import 'popper.js/dist/popper.min.js';
> import 'sticky-kit/dist/sticky-kit.js';
> import 'bootstrap-v4-rtl/dist/js/bootstrap.js';
> import '@vaadin/vaadin-text-field/theme/lumo/vaadin-email-field.js';
> import 'jquery-slimscroll/jquery.slimscroll.js';
> import 'node-waves/dist/waves.js';
> import '@vaadin/vaadin-combo-box/theme/lumo/vaadin-combo-box.js';
> import '@vaadin/flow-frontend/comboBoxConnector-es6.js';
> import '@vaadin/vaadin-text-field/theme/lumo/vaadin-text-field.js';
> import '@vaadin/vaadin-notification/theme/lumo/vaadin-notification.js';
> import '@vaadin/vaadin-icons/vaadin-icons.js';
> import '@vaadin/vaadin-dialog/theme/lumo/vaadin-dialog.js';
> import '@vaadin/vaadin-button/theme/lumo/vaadin-button.js';
> import '@vaadin/flow-frontend/flow-component-renderer.js';
> import '@vaadin/vaadin-checkbox/theme/lumo/vaadin-checkbox.js';
> import 'Frontend/custom.js';
> import 'Frontend/horizontal/js/sidebarmenu.js';
> import 'Frontend/horizontal/js/custom.js';
> import '@vaadin/flow-frontend/comboBoxConnector.js';`
> ```

**Comment by joheriks** [comment]
@TheSilentHorizon If possible, can you package a minimal project that will cause the above mentioned error when a new component is added (and also mention which component). The issues are likely related, but having a reproducible example would be of great help.

**Comment by TheSilentHorizon** [comment]
@joheriks tried so far reproducing it on a new project. On RC9 no luck so far, i try it on rc7 later if it might have been fixed already.

**Comment by joheriks** [comment]
@TheSilentHorizon Thanks! rc7 is good, need the reproducible primarily to determine if this related to the imports ordering or is another new / known issue.

**Comment by joheriks** [comment]
**Acceptance criteria:**

- Imports in `flow-generated-imports.json` are ordered consistently with the annotations in each class
- Between annotations of different classes, no order guarantee is provided
- All `@JsModule` imports precede `@JavaScript` imports
