### ISSUE TITLE
Activating compatibility mode via command line parameter is not possible with SpringBoot application

### ISSUE THREAD

**Issue by paulroemer** [vaadin/flow#6205]
Spring Boot: 2.1.5.RELEASE
Vaadin 14 RC9

I am in the middle of migrating a V13 application to V14 and gave the compatibility mode a try. I understand from the documentation that I have to set the property `vaadin.compatibilityMode=true`. This only works when you specify it in the `application.properties`. But not when you define it as parameter on the command line like:
```
mvn spring-boot:run -Dvaadin.compatibilityMode=true
```
it does not work and complains "Unable to determine mode of operation...". SpringBoot devs will expect that to work.

**Comment by paulroemer** [comment]
Super ugly but at least it works:
```
mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Dvaadin.compatibilityMode=true"
```

**Comment by caalador** [comment]
- [ ] Add Spring default folders to be checked: "src/main/resources/META-INF/resources", "src/main/resources/public", "src/main/resources/static", "src/main/resources/resources"
- [ ] When executing `MigrateMojo::getResources` check for all "default" folders that they exist and only add those that exist.
- [ ] Log folders that we will check
- [ ] If no folders exist inform user to give the `resources` parameter.
