### ISSUE TITLE
A disabled component in the template is not disabled in the Java code

### ISSUE THREAD

**Issue by vaadin-kim** [vaadin/flow#6206]
I have a disable button, such as ` <vaadin-button id="foo" disabled>Foo</vaadin-button>`
However, when I inject it into my Java class using `@Id Button foo;`, its enabled property will be true

```
// This returns true
foo.isEnabled();
```

Version: Vaadin 14 rc9

**Comment by mehdi-vaadin** [comment]
According to this document [Binding Components from a PolymerTemplate](https://vaadin.com/docs/v14/flow/polymer-templates/tutorial-template-components.html)
> So server side Component/Element read methods are not always in sync with the client-side. But you still may use mutation API methods from the server side like appendChild/setProperty/setAttribute. Getter methods returns values which have been set from the server side only.

So, `disabled` attribute is by design not synced between client-side and server-side.
