### ISSUE TITLE
Vaadin bakery app license

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/flow#6217]
I have downloaded the source code for vaadin bakery app. It uses commercial components. However, if I remove those component from the code(if possible at all), can I use the code and distribute it without violating any license?

Thanks

**Comment by pleku** [comment]
It seems the exact same question has been asked and answered already here https://stackoverflow.com/questions/57449766/a-question-of-vaadin-starter-pack-license (and the answer is NO).

In future, please use https://vaadin.com/forum for questions instead of opening issues for the framework.

**Comment by sudipta1411** [comment]
Thanks
