### ISSUE TITLE
Client-side routing

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6218]
When building a Vaadin app, as a Java developer willing to learn TypeScript, I want to have a Maven-like project structure where I create views and define routes in TypeScript and have the app running, so that I can be productive quicker and do not have to figure out how to setup the TypeScript compiler, Webpack, Live Reload, etc. While doing so I want the added routes to co-exist with, and follow the same navigation life cycle as the Java-defined routes.

**Comment by haijian-vaadin** [comment]
beta is out
