### ISSUE TITLE
Browser error: trying to start a new request while another is active

### ISSUE THREAD

**Issue by postojna** [vaadin/flow#6230]
I have a javascript function:

var pos = $canvasDiv.parent().position();
var ww = $canvasDiv.children().first().innerWidth();
var hh = $canvasDiv.children().first().innerHeight();
$serv.setWindowDimensions(id, pos.left, pos.top, ww, hh);
setTimeout(function() {
     var pos = $canvasDiv.parent().position();
     if (pos.left !== undefined && pos.top !== undefined) {
     $serv.setWindowPosition(id, pos.left, pos.top);
}}, 100);

$canvasDiv is a canvas object.
Under the timeout function I radomly got an error "Trying to start a new request while another is active". How to know when the another request is still active?

I'm using Chromium version 73.0.3683.75 on Debian 9.10.

**Comment by caalador** [comment]
There exists a published method on the client `client.isActive()` that gives the active state.

 - The client is stored to `Vaadin.Flow.clients[app-id]` 
 - The app Id is in `Vaadin.Flow.getAppIds()` and should be parsed as `appId.substring(0, appId.indexOf('-'));` 

so for the appId `ROOT-2521314` the call would then be `Vaadin.Flow.clients.ROOT.isActive()`

**Comment by ujoni** [comment]
@postojna Was this answer helpful to you or are you still having the issue?

**Comment by mehdi-vaadin** [comment]
In case your problem persists, please open a new issue with more information.

**Comment by gianluca-valentini** [comment]
Hi, 
I'm using Vaadin 13.0.13 and I have the same problem.
With java code I use com.google.common.eventbus.EventBus to schedule some events for number update.

`
@Subscribe
public void message(CounterBean bean) {

while (true) {
  ui.access(() -> {
    alertCard.refresh(bean);
  });
}
`

Using this code I have this issue on browser view
![image](https://user-images.githubusercontent.com/3224592/66051149-b639ac00-e52e-11e9-89fc-16e95f791adc.png)

**Comment by caalador** [comment]
Hi gianluca

Could you post an issue with a small sample project that showcases the exception
so we can see what goes wrong.

In the original case he was trying to make a server call from the client which
happened to happen while a request was active. In your case it seems like we
are handling events on the server.

**Comment by gianluca-valentini** [comment]
Hi @caalador 
I identify the error in a Vaadin chart usage. The [SplineUpdatingEachSecond](https://charts.demo.vaadin.com/SplineUpdatingEachSecond). This chart is present on the main one.
So the issue is caused by the internal threat execution. 
I don't now why but if I increase the delay chart start it works fine.

The difference is the chart data load that are not random by loaded by ReST API
