### ISSUE TITLE
Edge requires polyfill when embedding web components

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#6231]
When using either Chrome or Firefox (Vaadin 14, NPM mode), embedding a component requires only the web component module loading:

```html
<!DOCTYPE html>
<html>
    <body>
        <script type='module' src='http://localhost:9999/web-component/my-component.js'></script>
        <my-component></my-component>
    </body> 
</html>
```

The functionality is different on Edge browser - it requires `webcomponent-loader.js` polyfill to be present:
```html
<!DOCTYPE html>
<html>
    <body>
        <script type='module' src='https://unpkg.com/@webcomponents/webcomponentsjs@2.2.10/webcomponents-loader.js'></script>
        <script type='module' src='http://localhost:9999/web-component/my-component.js'></script>
        <my-component></my-component>
    </body> 
</html>
```

Either all browsers should require the polyfill or none should. Currently, the polyfill is provided in NPM mode, but not in compatibility mode.

**Comment by Artur-** [comment]
webcomponentsjs needs to be loaded before any other scripts on the page so it cannot really be provided by the web component

**Comment by pleku** [comment]
I think it should be enough to document that you need to have it added to the page yourself. Since it is most likely served by the Vaadin app, the user could mayhaps add it from there if they don't want to host it anywhere else.

**Comment by Artur-** [comment]
Yes. Edge will also work without it once it is based on Chromium
