### ISSUE TITLE
flow fails to serve static resources from latest webjars

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/flow#6241]
latest webjars do not include listing for directories, only for files 
https://github.com/webjars/webjars/issues/1863
![image](https://user-images.githubusercontent.com/9820084/62961763-0e451380-be06-11e9-92e8-8bc89e416bee.png)

current static file serving mechanism is checking for existence of directory and not of the requested file

**Comment by caalador** [comment]
The static file serving should work fine as the request is for the full path with filename, but building the production mode depends on finding the path `META-INF/resources/webjars/` in the JAR files that are scanned.
