### ISSUE TITLE
In multi-module projects, other module resources are not visited by TaskCopyFrontendFiles

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#6242]
When you run tests from parent folder in multi-module projects, without running `mvn install` just mvn compile, the project with tests is unable to locate resources from other modules because they are added to the classpath as folders, not as `.jar` files.

In CCDM we are adding resources like `META-INF/resources/frontend/Flow.js` to the `flow-client.jar`  which is discovered in the `DevModeInitializer#getJarFilesFromClassloader` when run in CI servers as  `file:/opt/agent/work/a69251da2b2bb9e9/flow-client/target/classes/META-INF/resources/frontend`,  which does not meet the regular expression `.*file:(.+\.jar).*` .

As reference the Jetty information about its classpath also reports the `flow-client` as a folder instead of a jar

`[INFO] Started o.e.j.m.p.JettyWebAppContext@41e8efae{/,[file:///opt/agent/work/a69251da2b2bb9e9/flow-tests/test-ccdm/target/webapp-tmp/, jar:file:///opt/agent/work/a69251da2b2bb9e9/flow-server/target/flow-server-1111.2.3-SNAPSHOT.jar!/META-INF/resources, jar:file:///opt/agent/work/a69251da2b2bb9e9/flow-data/target/flow-data-1111.2.3-SNAPSHOT.jar!/META-INF/resources, file:///opt/agent/work/a69251da2b2bb9e9/flow-dnd/target/classes/META-INF/resources/, file:///opt/agent/work/a69251da2b2bb9e9/flow-client/target/classes/META-INF/resources/, jar:file:///opt/agent/work/a69251da2b2bb9e9/flow-push/target/flow-push-1111.2.3-SNAPSHOT.jar!/META-INF/resources],AVAILABLE}{file:///opt/agent/work/a69251da2b2bb9e9/flow-tests/test-ccdm/target/webapp-tmp/}`

**Comment by flefebure** [comment]
Hi,
We are migrating a multimodule project from Vaadin 7 to Flow 14 and are impacted here (impossible to handle module resources in dev-mode)
Can we hope for a merge of this ticket in master ?
