### ISSUE TITLE
Define a logical location for frontend files in add-ons

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#6272]
With the current implementation (#5577, #5584), add-ons are supposed to put files that should be processed by webpack in `/META-INF/resources/frontend/` inside the add-on jar file. This is a quite weird location since `/META-INF/resources/` inside a web fragment jar corresponds to `/src/main/webapp/` in a war project, which isn't a location you should use for files that should be processed by webpack.

I would suggest that we retain support for the currently supported location for backward compatibility reasons, but then introduce a new location and ensure all documentation and examples refer to that location. The new location could be something like `/META-INF/frontend/`, or some variation that adds slightly more specificity to avoid the risk of naming conflicts.

**Comment by mehdi-vaadin** [comment]
Although it's a breaking change, the fix should be ported back to Flow 2.0 and be included in Vaadin 14.0.

**Comment by Legioth** [comment]
This is not a breaking change if it's done as I suggested:

> retain support for the currently supported location for backward compatibility reasons, but then introduce a new location and ensure all documentation and examples refer to that location.

**Comment by heruan** [comment]
Great to hear this is being discussed! But, is currently supposed to work placing files in `META-INF/resources/fronted` for Webpack to find them? I'm having issues with that, for example having a dependency with

```java
@Tag("my-component")
@JsModule("./my-component/my-component.js")
public class MyComponent extends Component {}
```
with the JS source in `META-INF/resources/frontend/my-component/my-component.js`, when running the `build-frontend` mojo on the main app I get this error:

```
Failed to find the following imports in the `node_modules` tree:
    - @vaadin/flow-frontend/my-component/my-component.js
If the build fails, check that npm packages are installed.
```

Also reported here: https://github.com/vaadin/flow/issues/6279#issuecomment-524222038

**Comment by heruan** [comment]
Great having this discussed! I'm currently porting some add-ons to NPM modules and also trying to adopt TypeScript, and I was wondering if the `META-INF/resources` location was still the best fit.

**Comment by mehdi-vaadin** [comment]
Fixed by https://github.com/vaadin/flow/pull/6362 and https://github.com/vaadin/flow-and-components-documentation/pull/795.
