### ISSUE TITLE
Vaadin for TypeScript (MVP)

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6275]
When creating applications with Vaadin, as a developer, I want to write client-side code in TypeScript so that I can stay close to the target platform (the browser), it is easy for me to use any of the native Web platform features directly (including Service Workers and offline support), and my code is automatically type-checked.

When adding TypeScript client-side code to existing Vaadin apps, I want it to be an optional addition to existing `@Route`-based server-side routes and full Java or `PolymerTemplate`-based views, so that it can be used in existing apps when and where necessary without major app restructuring.

When writing TypeScript client-side code in Vaadin apps, I want a complete full-stack project and a seamless end-to-end development experience with client-side code in TypeScript and server-side code in Java so that I can focus on the app features and have all needed tooling set up for me out of the box (zero Webpack / TypeScript / Node configuration).

**Comment by heruan** [comment]
A smooth TypeScript development with Vaadin would be awesome. Worth noting `LitElement` has a native TypeScript support, e.g. using [decorators](https://lit-element.polymer-project.org/guide/start#use-litelement-typescript-decorators).

**Comment by Artur-** [comment]
Marcus created a nice example of TS + Lit https://github.com/marcushellberg/vaadin-lit-typescript

**Comment by haijian-vaadin** [comment]
beta it out
