### ISSUE TITLE
When creating a view with user selected background color I want to be able to bind the style to a value in the model so that the end user can see the chosen background color

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#628]
`<div [style.width]="mySizeIncludingUnit">`
`<div [style.width.px]="mySizeWithoutUnit">`

Binds style property `width` to the result of expression mySize in pixels. Units are optional.

Suggested sub tasks:
- Parse template into a new Map<String, BindingValueProvider> in ElementTemplateNode
- Update TemplateElementStateProvider.getStyle to return an instance that is backed by these bindings  (an old instance returns new values if the model is updated).
- Send the template mappings to the client and bind it to update `element.style`  when the model changes.
- Update demo-website to toggle an active class on the currently active menu item
- Write a tutorial about controlling styling from templates (or supplement the tutorial about `[class.foo]` bindings.
- Update the basic binding tutorial to also mention this type of binding

**Comment by pleku** [comment]
Closing as an old issue that has not gained traction.
