### ISSUE TITLE
Escape key after session expiration doesn't reload the page

### ISSUE THREAD

**Issue by mpilone** [vaadin/flow#6284]
I'm running into an issue when a user's session expires and they use the ESC key to reload the page per the app error notification. However the application doesn't reload even though Firefox thinks it navigated to the view. The app error dialog remains. Clicking on the notification does properly load the page but the ESC key does not.

To reproduce the issue:

1. Load the attached view in Firefox (also appears to happen in Chrome).
2. Open the browser developer tools and go to the Network view
2. In Firefox, Go to Preferences->Privacy & Security->Cookies and Site Data->Manage Data...
3. Remove the cookies for the site you're loading the view from (e.g. localhost)
4. Click the button in the view. This should open the app error notification telling the user to click the notification or press ESC to reload.
5. Press ESC.
6. When running without push enabled, nothing appears to happen. When running with push enabled, the Network view shows Atmosphere requests fire off as quickly as possible. The page doesn't reload and eventually your CPU fan will fire up.

The attached view has the push annotation commented out to make it simpler. In this configuration, the ESC key doesn't seem to do anything even though Firefox says it is navigating to the view.

With the push annotation enabled, the ESC key still doesn't appear to do anything and Atmosphere starts firing off requests and spikes the CPU.

In the console logs, I see tons of:
```
GEThttp://localhost:8034/dashboard/?v-r=push&v-uiId=0&v-pushId=b9cfa0fb-42c1-416c-81b4-5e69df8f3cde&X-Atmosphere-tracking-id=56c101e1-8973-407f-ae53-2beee5ddb447&X-Atmosphere-Framework=2.3.2.vaadin1-javascript&X-Atmosphere-Transport=long-polling&X-Atmosphere-TrackMessageSize=true&Content-Type=application%2Fjson%3B%20charset%3DUTF-8&X-atmo-protocol=true&_=1566244617354
[HTTP/1.1 200 OK 1ms]
Mon Aug 19 2019 15:56:57 GMT-0400 (Eastern Daylight Time) Atmosphere: ajaxRequest.onreadystatechange, new state: 2 vaadinPush.js:3259:28
Mon Aug 19 2019 15:56:57 GMT-0400 (Eastern Daylight Time) Atmosphere: ajaxRequest.onreadystatechange, new state: 3 vaadinPush.js:3259:28
Mon Aug 19 2019 15:56:57 GMT-0400 (Eastern Daylight Time) Atmosphere: ajaxRequest.onreadystatechange, new state: 4 vaadinPush.js:3259:28
Mon Aug 19 2019 15:56:57 GMT-0400 (Eastern Daylight Time) Atmosphere: Firing onMessage vaadinPush.js:3259:28
JSON parsing took 0ms client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:184:20
Received push (long-polling) message: for(;;);[{"meta":{"sessionExpired":true}}] client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:184:20
Response didn't contain a server id. Please verify that the server is up-to-date and that the response data has not been modified in transmission. client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:963:127
Ignored received message because application has already been stopped client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:963:394
Mon Aug 19 2019 15:56:57 GMT-0400 (Eastern Daylight Time) Atmosphere: Firing onMessage
```

The actual push responses look like:
```
42|for(;;);[{"meta":{"sessionExpired":true}}]
```

The Atmosphere part of this ticket, when push is enabled, may be related to #4072 but the fact that ESC doesn't work even without push makes me think this is a slightly different issue than that and we're just seeing that bug on top of this one.

This is a pretty bad user experience in either case. The ESC button should either work just like clicking on the notification or the notification text should be changed to avoid telling the user to take an action that either doesn't work or pins their CPU with push reconnect requests.

Firefox 68.0.1 or Chrome 76.0.3809.100
Vaadin 13.0.7
Jetty 9.4.19.v20190610

[Bug4072View.java.zip](https://github.com/vaadin/flow/files/3517555/Bug4072View.java.zip)

**Comment by denis-anisimov** [comment]
Confirmed.
Click on the error box reloads the page. ESC doesn't do anything.

**Comment by denis-anisimov** [comment]
I see the code in the `SystemErrorHandler::handleUnrecoverableError`  which handles click and ESC in the same way.
And I see that ESC tries to do something.
But if you open a browser inspector then an attempt to open the URL has status `(canceled)`
