### ISSUE TITLE
On 14.0.1, Version.getFullVersion() reports Flow as 2.0.7 instead of 2.0.8

### ISSUE THREAD

**Issue by zanonmark** [vaadin/flow#6285]
As per subject, the 14.0.1 release brings an update to Flow: 2.0.8 in place of 2.0.7.
However, Version.getFullVersion() still reports the old version.

Thanks,
MZ

**Comment by caalador** [comment]
Are you certain that all dependencies have refreshed and flow is not defined by itself?
When testing fullVersion on 14.0.1 in base starter I get the version 2.0.8 as expected.

**Comment by zanonmark** [comment]
It is showing as 2.0.8 now. I'm quite sure I did a `mvn -U clean`, but I might be wrong...

Closed - Thanks,
MZ
