### ISSUE TITLE
Immediately detach the old UI when the browser tab is closed or refreshed

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#6293]
The [Beacon API](https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API) is now relatively widely available, making it possible to propagate an unload event to the server when a tab is closed/refresh without affecting user experience.

This could be used to close UIs on close/refresh immediately, without waiting for expiration due to missed heartbeats. This has the potential to improve performance, primarily by decreasing memory consumption.

The heartbeat expiration or similar is still needed for when the unload event can not be propagated to the server, e.g. when the user loses network connectivity.

**Comment by pleku** [comment]
Now with Flow 3.0 and Vaadin 15, the needed API is available in all the supported browsers as IE11 and Safari 11 are not supported anymore.

For Vaadin 14, this could be maybe considered backported as an "experimental" feature that can be enabled. Not sure if there is any trouble for users if UIs are cleaned up eagerly for some browsers, but not all.

**Comment by Legioth** [comment]
We've implemented a Beacon handler as part of Collaboration Engine. It would be great if it could be moved over to the core framework instead.

**Comment by mstahv** [comment]
Started drafting this feature in https://github.com/vaadin/flow/pull/16657

**Comment by Legioth** [comment]
> Is it possible to distinguish between closing a tab or refreshing it via the Beacon handler?

No. The trigger for sending a Beacon request is the `unload` event that is fired by the browser in both cases. There are probably privacy reasons for why the browser doesn't let the page know what the user is doing next.

**Comment by danielzweng** [comment]
This feature seems to work in every browser at the moment, except Firefox. Any suggestions what could cause this issue?

Using Vaadin 24.3

Tested browsers:
- Chrome 124 (Win 11)
- Edge 124 (Win 11)
- Firefox 125 (Win 11 & MacOS Ventura 13.6.6)

**Comment by mcollovati** [comment]
Could be related to https://github.com/vaadin/flow/issues/19305#issuecomment-2095273857
