### ISSUE TITLE
shortcuts: shortcut bound to an actuating key may cause an action to trigger twice

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#6312]
If the shortcut is bound to a key that actuates an action on a component (such as `Enter` on a button), the components actuation happens twice when the component is focused.

**Steps to reproduce:**
- Get skeleton-starter-flow
- Add line `button.addClickShortcut(Key.ENTER);` after button creation
- Run the application (`mvn jetty:run`)
- Go to http://localhost:8080/
- Hit `Tab` to get the button focused
- Hit `Enter` 

**Expected result:**
Only one notification is shown.

**Actual result:**
Two notifications are shown.

**Comment by denis-anisimov** [comment]
It's not clear for the description but it seems this is quite specific for `Key.ENTER` .

**Comment by denis-anisimov** [comment]
Duplicate of #8037.
