### ISSUE TITLE
@PreserveOnRefresh producing JS error

### ISSUE THREAD

**Issue by KasparScherrer** [vaadin/flow#6337]
Using Vaadin 14.0.0

When I add the `@PreserveOnRefresh` annotation on my MainView, then there is a JavaScript error shown `Cannot read property 'undefined' of undefined` when I refresh the page.

![console screenshot](https://i.imgur.com/aKFmzYF.png)

I have many different Components on my view so I don't know which one is causing this problem. I have ComboBoxes too, which IIRC were causing issues with preserve on refresh during rc versions of 14.   

The Components on my view are:
`Grid`, `Button`, `Upload`, `ComboBox` , `Select`, `TextField`, `NumberField`.

Now before I go ahead and make a minimal example project for this issue I wanted to ask if this is already known or if somebody maybe already has an idea which component might be the culprit?

**Comment by KasparScherrer** [comment]
The Upload is not working anymore after the refresh, but the ComboBoxes are still working. I assume that the Upload is the culprit of my issue.

Before refresh, the Upload worked.  

After refreshing, when trying to Upload: console error:  
![upload console error](https://i.imgur.com/TU3fNLT.png)  

Error visualisation in View:
![upload error visual](https://i.imgur.com/UrQuE8v.png)

**Comment by KasparScherrer** [comment]
Okay, so I have put a single Upload component into a test view. Here is what I found out:

The Upload Component is not causing the `Cannot read property 'undefined' of undefined` Error.  But neither does it work after refreshing the page. This is not the problem that I want to address right now so I opened another issue for this. As soon as I find out what component caused my JS error I will post a minimal View example with it.

```
@Route(value = "Test")
@PreserveOnRefresh
public class TestView extends VerticalLayout {
    public TestView(){
        add(new H4("Test View"));
        addUpload();
    }
    private void addUpload() {
        Upload upload = new Upload(new MultiFileMemoryBuffer());
        upload.setUploadButton(new Button("Test Upload", VaadinIcon.UPLOAD.create()));
        upload.setDropAllowed(false);
        upload.addSucceededListener(event -> {
            Notification.show(String.format("Upload succeeded. Filename: '%s'", event.getFileName()));
        });
        add(upload);
    }
}
```

**Comment by ujoni** [comment]
Thansk @KasparScherrer for submitting this issue. It is new to us, so any extra information is worth it.

I tried to reproduce the issue following these steps:
- clean project from skeleton-starter-flow
- added `Upload` (no errors)
- added `ComboBox` (no errors)
- added `Grid`  (no errors)

I was using a slightly newer version of Vaadin Plarform, `14.0.1` so I'll go back later and try to replicate with `14.0.0`.

**Comment by KasparScherrer** [comment]
I am still trying to narrow down the culprit component, but so far none of the stated components are causing the error when put alone in a view. I'm pretty sure it's something else, and I will update here as soon as I have found out more about this myself.

**Comment by KasparScherrer** [comment]
I found it! It was my language selection - a Select component. It itself does not cause this error alone, but the fact that I redefine it's renderer upon a LocaleChangeEvent is causing this. That's why I did not find it earlier when I put my language selection alone in my test view - I did not implement LocaleChangeObserver there. 

I need to redefine the renderer so that it updates it's translations

Here is my TestView with the Language Selection:

```
@Route(value = "Test")
@PreserveOnRefresh
public class TestView extends VerticalScrollLayout implements LocaleChangeObserver {
    private Select<Locale> langSelect;
    // you might want to add your own Locale here for `langSelect.setValue(UI.getCurrent().getLocale())` to work
    private final Locale[] SUPPORTED_LANGUAGES = {new Locale("de"), new Locale("fr"), new Locale("en")};

    public TestView(CarOverviewRepository carOverviewRepository){
        add(new H4("Test View"));

        langSelect = new Select<>();
        langSelect.setEmptySelectionAllowed(false);
        langSelect.setRenderer(new ComponentRenderer<>(item -> new Span(item.getLanguage())));
        langSelect.setItems(SUPPORTED_LANGUAGES);
        langSelect.setValue(UI.getCurrent().getLocale());
        langSelect.addValueChangeListener(change -> UI.getCurrent().setLocale(change.getValue()));
        add(langSelect);

        setPadding(true);
    }

    @Override
    public void localeChange(LocaleChangeEvent event) {
        // removing langSelect.setRenderer() here makes the JS error disappear!!
        langSelect.setRenderer(new ComponentRenderer<>(item -> new Span(item.getLanguage())));
        langSelect.setValue(event.getLocale());
    }
}
```
I have removed quite a bit of logic from the renderer, to make this a more minimal code sample. [You can see my actual implementation on stackoverflow](https://stackoverflow.com/a/53763977/3441504). The thing is that I *need* to redefine the renderer in the `localeChange` so I can change the displayed language names.

**Comment by KasparScherrer** [comment]
When I said that I **need** to redefine the renderer - what I actually meant is that I need to refresh the items or "reapply" their renderer - the renderer itself has no changes, but it will yield different results because of the usage of `getTranslation() within`. But because the method Select.refreshItems() is private, I resorted to just redefining the renderer which will call `refreshItems()`. 

By going through other Components where I update translated Strings, I found my code for Grid retranslation of Component-Rendered columns: `grid.getDataProvider().refreshAll();`. Select has a DataProvider as well so I tried the same approach here. 

But that somehow doesn't work as now I get a NullPointerException from the `BootstrapPageBuilder`!  
```
[INFO] 	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.getBootstrapPage(BootstrapHandler.java:517)

(BootstrapHandler.java line 517 reads:)
html.attr("lang", context.getUI().getLocale().getLanguage());
```
  
I debugged this, and what I believe is what happens is: `select.getDataProvider().refreshAll();` will clear value of the `select`, which in turn will trigger the selects valueChangeListener that sets a new Locale (null in this case). This will trigger the locale change again, but this time the valueChangeListener will not trigger as it was null before. In the end, the BootstrapHandler wants to write Locale.getLanguage() into html but Locale is null.

-------

I have 2 propositions to fix this issue.  

1) fix the `updateItem()` function on the `Select` class, somewhere in there must be the code that causes my JS error. It might also be in the executed JS `this._updateValueSlot()`. This fix will probably be pretty small, as everything still works as intended even though there is a JS error. If you're doing this, it would be cool if you also made `refreshItems()` public so I don't have to misuse `setRenderer()` to reach it.

2) By making it possible to *remove* a valueChangeListener from the Select, I could remove that listener before calling `select.getDataProvider().refreshAll();` and add it again afterwards. This would stop the (indirectly) recursive call of `localeChange()` and should make it work, as using this approach the bugged method `Select.updateItem()` is never called. 

Needless to say, I like the first proposition way more.

**Comment by ujoni** [comment]
Thank you @KasparScherrer for spending all this effort for investigating this issue.

Meanwhile, you can try to alter your approach and maybe get forward.
Instead of refreshing the rendered, use `DataProvider` to refresh items:
```java
    @Override
    public void localeChange(LocaleChangeEvent event) {
        String value = select.getValue();
        select.getDataProvider().refreshAll();
        select.setValue(value);
    }
```
Due to how `Select` [currently works](https://github.com/vaadin/vaadin-select-flow/issues/40), I added the code for resetting of `Select`'s value.

In addition, due to a [bug with `@PreserveOnRefresh`](https://github.com/vaadin/flow/issues/6357), use `Session` to store the locale instead of `UI` - otherwise the locale won't be retained through refresh.

```java
    UI.getCurrent().getSession().setLocale(Locale.FRANCE);
```

**Comment by KasparScherrer** [comment]
As described in my last comment, I already tried `select.getDataProvider().refreshAll()` but this caused NPE because it set the value of select to null, which sets the Locale in the Session/UI to null because of the valueChangeListener of my select. I would have to remove that valuechangelistener before. that is not possible.

I also already found out about setting the locale of the Session instead of the UI and have [edited my So post](https://stackoverflow.com/a/53763977/3441504).

**Comment by denis-anisimov** [comment]
Note for myself: it seems that the problem is caused by the initial request when refresh is done.
If I change the code to set the renderer in a button click listener then error doesn't happen after refresh.
So the bug is caused by the `LocaleChangeObserver` implementation.

**Comment by denis-anisimov** [comment]
The issues is caused by this line in the `select`  JS:
`const selected = this._items[this._menuElement.selected];` (inside `_updateValueSlot`  method call which is initiated by JS execution made form Java side from `Select::updateItem` .

**Comment by denis-anisimov** [comment]
OK, the issue is not related to `@PreserveOnRefresh`  anyhow.
It's a bug in `Select` component.

Can be reproduced with this test class:

```
@Route(value = "Test")
public class TestView extends VerticalLayout {
    private Select<String> select;

    public TestView() {
        select = new Select<>();
        select.setRenderer(new ComponentRenderer<>(item -> new Span(item)));
        select.setItems("a", "b", "c");
        select.setValue("a");
        add(select);

        Button remove = new Button("Remove", event -> {
            remove(select);
            Button add = new Button("add", ev -> {
                add(select);
                select.setRenderer(
                        new ComponentRenderer<>(item -> new Span(item)));
            });
            add(add);
            remove(event.getSource());
        });
        add(remove);
    }

}
```

**Comment by denis-anisimov** [comment]
I will move the ticket in the proper repository.
This ticket I will close since it has a long list of comments related to `@PreserveOnRefresh`  which is not the cause at all.
I will add a link to this ticket.

**Comment by denis-anisimov** [comment]
Moved to https://github.com/vaadin/vaadin-select-flow/issues/43
