### ISSUE TITLE
Allow use of new components to be hot deployed

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#6342]
When using a system such as HotSwapAgent, JRebel or Java's built-in hot code replace that allows code changes to be applied, it is possible that new `@JsModule` or `@CssImport` annotations become reachable even though the servlet context isn't redeployed. In this situation, the component would not work because its client-side dependency would not be loaded.

There is already logic in that detects that situation in development mode by keeping track of which classes have been considered when `generated-flow-imports.js` was generated: https://github.com/vaadin/flow/blob/17192157649fe2ce92101c99d11c65aa86ca20b3/flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java#L184-L191

This logic could be enhanced so that instead of directly logging a warning, it would instead rerun the scanner. If rerunning causes the encountered class to be among the discovered ones, then it would silently be used. If rerunning doesn't pick up the target class, then the same message as now would be logged.

If implemented in this way, it would be good to also keep track of classes for which a rescan didn't help to avoid rescanning again and again for the same case. It might also make sense to limit the rescanning to only happen once per round trip to avoid multiple rescans if there are multiple classes that are genuinely missing. It would also be necessary to prevent multiple rescan operations from happening at the same time.

It would most likely be acceptable to keep using the same entry points (e.g. `@Route` classes) that were originally used when the servlet context was first started. This would mean that you'd still have to perform a regular servlet context redeploy (or simply restart the server) after adding a new `@Route` class. It might also be possible to offer an API that e.g. HotSwapAgent integration could use to inform the scanner about new `@Route` classes and such, but that might be out of scope for this ticket.

**Comment by manolo** [comment]
What I don't see here is when the hot-deploy solution triggers this validation, in jetty or spring-boot it's done when servlet context is restarted, but for Rebel or HotSwapAgent we need some signal.

**Comment by Legioth** [comment]
The way I see it, there are two potential alternatives:
1) Trigger a rescan whenever encountering a component class with a `@JsModule` or `@CssImport` annotation that wasn't considered by the previous scan. We already have logic that detects that situation to be able to log a message about the situation.
2) Have JRebel or HotSwapAgent give a notice whenever any class has been changed. The first challenge with this approach is that it requires custom integration for each hotswap solution and it won't work with the JVM's own hot code replace since that one doesn't give any such notifications. The other challenge is that I'm not sure what we would do with information that `Foo.class` and `Bar.class` have changed. How do we know whether those changes are a reason to trigger rescanning? 

The first approach seems simple but a little crude. The second approach seems to be academically correct but limited in practice.

**Comment by Legioth** [comment]
There is one problem with my suggested approach: If the missing component isn't used on the initially loaded page, then the discrepancy will be detected after the page has already been loaded with the old bundle. This in turn means that I'd have to do a "magical" second reload in the browser before it actually works.

**Comment by denis-anisimov** [comment]
Generally it works because full classpath scanning is used nowadays for dev mode.
That allows to find all the resources and include them into the bundle from the very beginning.

So the basic scenario works for:
- JRebel with one bug which I will make separately
- Hotswap doesn't work at all (different ticket)
- scanning interval (jetty), Spring dev tools.

Basic scenario:
- have e.g. skeleton starter project
- it uses Vaadin platform
- if you add any _existing_ Vaadin component to the  `MainView` then it will be shown.

The same scenario works if you already have a frontend js module file but you make a new Java class with the existing JS module for scanning interval and Spring dev tools.

But it doesn't work for JRebel for some reason. That's a separate issue. I will create a ticket.

**Comment by denis-anisimov** [comment]
The ticket for JRebel and new template : https://github.com/vaadin/flow/issues/7186
