### ISSUE TITLE
Migration documentation should mention the need of @Uses in certain cases

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/flow#6358]
The following code will work in Vaadin 13, but not in Vaadin 14 (the icon will not be shown in V14):

```
@Route
@PWA(name = "My Application", shortName = "My Application")
public class MainView extends VerticalLayout {

    public MainView() {
        try {
			add((Component) Class.forName("org.vaadin.test.CustomComponent").newInstance());
		} catch (InstantiationException | IllegalAccessException | ClassNotFoundException e) {
			e.printStackTrace();
		}
    }
}

class CustomComponent extends VerticalLayout {

	public CustomComponent() {
		add(VaadinIcon.VAADIN_H.create());
	}
}
```
This can be solved by adding `@Uses(Icon.class)`.

Basically any UI that is generated or obtained dynamically, and containing any Vaadin component that is not used in the view annotated with `@Route` will generate just the tags, without the webcomponent implementation and will only produce a warning like this in the logs:

`WARN com.vaadin.flow.server.startup.DevModeInitializer - Frontend dependencies have not been analyzed for com.vaadin.flow.component.icon.Icon. To make the component's frontend dependencies work, you must ensure the component class is directly referenced through an application entry point such as a class annotated with @Route.
`

If the application being migrated is large, with a verbose log, trying to figure out why this is happening could be hard. At least there should be a explicit mention in the migration guide that `@Uses` could be necessary with dynamic UI content.

**Comment by denis-anisimov** [comment]
I think we should also extend the warning message with `@Uses` mention as a possible solution for the issue (apart of extending documentation).

**Comment by enver-haase** [comment]
See:
https://github.com/Artur-/micro-front/blob/master/bundle/src/main/java/org/vaadin/artur/microfront/bundle/Bundle.java

Having this class in your project, unused, should fix the problem as a work-around.

That said -- why not (at least in development mode) include all the components, why be frugal and scan and try to not include everything?

**Comment by denis-anisimov** [comment]
This should not be a problem anymore:
- in dev mode by default full classapth scanning strategy is used to discover all components to include them into the bundle.
- in production mode we still use by default byte code scanning but there is a fallback.
