### ISSUE TITLE
Webpack server is incorrectly reused in a multi-module project when running integration tests

### ISSUE THREAD

**Issue by haiwan** [vaadin/flow#6359]
[Vaadin10+-Intro.zip](https://github.com/vaadin/flow/files/3558473/Vaadin10%2B-Intro.zip)
It's a project with 2 sub-modules, exercises and solutions. The exercises module has a very simple view which contains only a button. The solutions module has a simple form which includes a date picker. When running integration tests, the first module passes, the second module fails, which you can see from the attached screenshot.
![MainView_linux_chrome_76](https://user-images.githubusercontent.com/3388675/63997085-1db2a500-cb06-11e9-8abf-aed3105b1cbd.png)

To reproduce:
1. Install Docker
2. Clone this project `https://github.com/jtomass/selenium-docker-local`
3. Run `docker-compose up` in the selenium-docker-local directory
4. Unzip the attached the project, run ```mvn verify -Pgitlab-it -Dcom.vaadin.testbench.Parameters.hubHostname=localhost``` in the root directory.

**Comment by denis-anisimov** [comment]
See also https://github.com/vaadin/flow/issues/6351.
May be it's related.

**Comment by haiwan** [comment]
Also verified that it works fine with Vaadin 13.0.13

**Comment by denis-anisimov** [comment]
I'm closing this since it works in the latest version.
Please reopen or let me know if it doesn't work in the modern versions.
