### ISSUE TITLE
Create a tutorial on how to add a TypeScript view to a V14 app

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6365]
When learning about TypeScript support in Vaadin, I want to see a step-by-step tutorial on how to add a TypeScript view to an existing Vaadin 14 application so that I have a working example on how to do that, and it becomes easier for me to add TypeScript views to my own Vaadin application.

DoD:
 - there is an "Adding TypeScript views to a Vaadin 14 app" tutorial on the https://vaadin.com/learn/tutorials page (e.g. https://vaadin.com/learn/tutorials/adding-typescript-views-to-a-vaadin-14-app)
 - the tutorial gives step-by-step instructions and includes code snippets that show how to take a Vaadin 14 app with server-side views, upgrade it to Vaadin 15, and add a client-side view to it
 - the tutorial may use the [Beverage Starter](https://vaadin.com/start/lts/simple-ui) app as the starting point to add a TypeScript view to

As a reference see the [Building a dynamic web form with validation](https://vaadin.com/learn/tutorials/dynamic-web-forms-with-validation-in-java) tutorial.

**Comment by platosha** [comment]
See the PR: https://github.com/vaadin-learning-center/learning-content/pull/152
