### ISSUE TITLE
Application fails to deploy from Eclipse due to a timeout

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#6369]
With 14.0.2, if you try to deploy application directly to Tomcat via Eclipse's server integrations, the application startup is so slow (npm magic going on) that it gets killed due to a timeout. Tried with basic app starter.

<img width="425" alt="Screenshot 2019-09-01 at 19 02 23 " src="https://user-images.githubusercontent.com/1478052/64079246-10580f00-ccee-11e9-97a5-50d072af276d.png">

**Comment by caalador** [comment]
This is fixed by having npm packages installed before starting from the server.
We can't really do much for running install before server startup.

**Comment by denis-anisimov** [comment]
The suggestion here is:
run preparation steps (including (p)npm install ) and webpack dev server in a separate thread so it doesn't block the server (and app) startup.
Then we will need to handle not yet started webpack server properly.
