### ISSUE TITLE
Portlet UI state is preserved on refresh

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#6373]
_When there is a refresh request from the browser (caused by the Portal or User), the Vaadin Portlet state is not lost, so that the user doesn't lose all their changes_

This is part of Portlet 2.0 support #4760.

Even though Portlet 3.0 support has JS API for supporting updating the portlet without complete refresh, the [docs](https://msnicklous.github.io/portletspec3/apidocs/docfiles/jsdoc/portlet.html) say:
>However, regardless of whether the state change was initiated by setting parameters or through a portlet action, the portal may respond by completely refreshing the page. The portal may do so in order to support portlets that are affected by the state change but do not participate in the portlet client-side support, or for implementation-specific reasons.

This means that the using clients side API doesn't not guarantee that the portlet does not do a full refresh, so preserving the state should happen still in 3.0.

**Comment by ujoni** [comment]
### Acceptance criteria:
- [ ] Contents of Vaadin Portlets should be preserved automatically. The developer should not need to add any annotation nor special configuration.
- [ ] Portlet Support has integration tests that validate this feature
  - View mode change might cause a component that the user added for the specific mode to be "preserved" for another view mode, when the page refresh happens in conjunction with the mode change. If that is the case, fix/document.

**Comment by joheriks** [comment]
The following should be checked by ITs:
- Add two portlets with IPC to the same portal page
- Open portal page in one browser:
  - change the state of one of the portlets 
  - refresh the window
  - verify that the state is preserved and that IPC still works
- Open portal page in two browser windows
  - refresh both windows
  - check that IPC works in both windows
