### ISSUE TITLE
Safari page loading freeze issue

### ISSUE THREAD

**Issue by m-emelchenkov** [vaadin/flow#6393]
Hi, developers! I faced into a strange bug with Safari 12.1.2 on macOS High Sierra 10.13.6.
I have two same installations of a Vaadin app on two different servers in the same data center. Both web servers access is protected by client certificates. I can open one web interface without any issues. But the second web interface works for the first several minutes after cleaning browser caches and restarting the browser, then it stalled as on attached picture. I tried many things: removing certificates from Keychain, clearing cache multiple times, restarting the app service on the server and so on. Vaadin app on one of the servers stop responding. It happens with Vaadin 13-14 versions + latest Spring Boot. No problems in Chrome. Do you have ideas what specifically wrong with Safari, what to check? (No, I don't use WebSockets, only long polling, because Safari does not support WebSockets within client certificates mode). Both servers are Ubuntu 18.04 with OpenJDK 11 with all the latest updates.
![Untitled](https://user-images.githubusercontent.com/7569252/64246519-9904c400-cf15-11e9-9d86-acef2d64faa6.png). It's very strange to me because the first server's web interface always opens fine, but the second stops working, and they are identical...

**Comment by denis-anisimov** [comment]
Hi, is it possible to make a sample project to reproduce the issue ?
I'm not familiar with Safari dev tools: is it so that it tries to load `webcomponents-loader.js` ?
Can you access to that URL within a new browser tab ?

As I understand the image shows V13 application , right ?

**Comment by m-emelchenkov** [comment]
Hi Denis! Unfortunately, I have no ideas how to reproduce it. The second server works fine. I suppose, if I'll build some virtual environment, it will work too. Right now, for several hours it worked fine, then stops working in a bit different way: for a several dozens seconds it could not load anything, then loaded client-....cache.js, vaadinPush-min.js and stuck again on webcomponents-loader.js. Yes, I can open webcomponents-loader.js directly in a new browser tab, and it asks for a client certificate for this tab (indeed, it should not, because the certificate was already chosen). I chose it again. And after it I can successfully reload the app. Currently, I use Vaadin 14, but it was the same situation for 13. I could be wrong, but, it seems, it is not a Vaadin problem, and problem of Safari. Thanks for pointing me to open webcomponents-loader.js separately, it helped me to understand what happens. Safari, for sure, has bugs, I even reported some of them to Apple and they were never been fixed, because Apple does not fix bugs which does not affect large group of people—in other words, they don't really interested in fixing something rarely happened. I suppose, it could be a such bug with client certificates which happened with some unknown conditions.

**Comment by denis-anisimov** [comment]
>Yes, I can open webcomponents-loader.js directly in a new browser tab, and it asks for a client certificate for this tab (indeed, it should not, because the certificate was already chosen).

I think this is the problem. Since this script is included on the page it should be loaded without any interaction. And since it requires cert accept it stucks.

>but, it seems, it is not a Vaadin problem, and problem of Safari. 

I think so.
