### ISSUE TITLE
Document how to preserve beans with @RouteScope when migrating from v7/v8

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#6395]
Prerequisites: 
we have ticket https://github.com/vaadin/spring/issues/473 and https://github.com/vaadin/cdi/issues/293 which are about not preserving UIScopes beans on refresh.

The tickets are in fact consequence of confusion.
But the main idea is still valid: the developer want to preserve on refresh the whole `UI`  instance (instead of specific components) and expects that UIScoped beans are preserved.

`@PreserveOnRefresh`  doesn't fit the expectations and there is a reason for this: it's attached not the a `UI`  instance but rather for a specific route target/component. So it may not work preserving UI beans since one route target may be preserved and another may be not.

What we need is: a way (most likely not via an annotation since we don't recommend to use your own UI instances) to make `UI`  to be preserved on refresh. It may be a (deployment) config parameter or something else.
The way how it works: the whole UI is preserved on refresh (the instance doesn't have to be preserved but all ui scoped beans should be preserved): the ui scope should stay the same when UI is refreshed.

**Comment by TatuLund** [comment]
This is related to https://github.com/vaadin/flow/issues/6287

**Comment by mkn1988** [comment]
Hi,
I'm currently running into this exact issue. Any idea yet, when you'll start working on it?
Greetings,
Max

**Comment by thigg** [comment]
One usecase is to store data per tab, for example having seperate login sessions for each tab.
In Vaadin 8 this was commonly done via the UI class.

https://vaadin.com/forum/thread/17810577/17812148 presents a hack, which has several problems. 
For one, you need to have an additional root layout for all your views (which is incompatible with AppLayout, because it doesnt like to be a nested layout).
A way to store data which corresponds to a tab without binding it to a specific component would be nice.

**Comment by pleku** [comment]
We've decided that this is not worth it - it would be tricky to implement technically which would make the ROI very low.
And we don't want to start to encourage using a custom UI anyway.

Instead you should use other means of storing data to be preserved in the UI - like in case of using CDI/Spring DI - use a `@RouteScope` bean that is tied with `@RouteScopeOwner` to the root layout that has the `@PreserveOnRefresh`.

### Acceptance Criteria
- [ ] For now the idea is to just update the migrating from v7/v8 documentation (latest, v14 branches) to highlight that storing data needs to happen elsewhere than in the UI.

**Comment by Frettman** [comment]
It's still unfortunate if not downright detrimental that `@PreserveOnRefresh` and `@UIScope` are effectively mutually exclusive now. If any library or add-on wants to be usable with `@PreserveOnRefresh` it cannot use `@UIScope` (or just store stuff in the UI object). But the combination of `@RouteScope` and `@RouteScopeOwner` (or any other shared location) is application-specific and therefore not usable in libraries or add-ons. E.g. I have an add-on that provides an event bus for session and UI scopes. It simply will not work with `@PreserveOnRefresh`.
As `@UIScope` seems much more valuable to me, I have pretty much given up on `@PreserveOnRefresh`. At least for now.
