### ISSUE TITLE
No warning nor deprecation for HtmlImport in Flow 2.0 npm mode.

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow#6401]
- Description of the bug

I am migrating a Flow 1 application and these leftovers should really be caught

- Minimal reproducible example

Any View (@Route annotation) that is also annotated @HtmlImport

- Expected behavior

I get deprecation warnings in the IDE and an expection during runtime.

- Actual behavior

Don't know. Seems not to be executed. Does not care about file that should be imported but does not exist.

- Versions:
    - Vaadin / Flow version
Vaadin 14.0.3
    - Java version
Java 8
    - OS version
Windows 10
    - Browser version (if applicable)
any

**Comment by Legioth** [comment]
Related discussion in another thread: https://github.com/vaadin/flow/issues/6279#issuecomment-527883703

**Comment by pleku** [comment]
Continuing discussion from the ^ mentioned issue here, when running npm mode, we probably should throw for any usage of `addHtmlImport()`. But I'm not sure if it is worthwhile to add additional scanning for usage of `@HtmlImport` for files that don't have any other annotations, or to check for all `@HtmlImports` and try to locate the file ? Wouldn't that also slow down all projects that have been migrated properly.

Another option would be to actually deprecate `@HtmlImport` and the related methods in an upcoming 14.x minor release, even though we cannot remove those during the 14 series.

**Comment by ujoni** [comment]
### Acceptance criteria:
- [ ] During runtime, log for all discovered components that only have `@HtmlImport` and no `@JsModule` annotations
  - Only in npm mode
  - The information needs make the user understand that `@HtmlImport` cannot be used in npm mode and what are the things they need to do to get rid of this error
  - The `@HtmImport`-only components are ignored
- [ ] Make the javadoc documentation for the `@HtmlImport` reflect these changes
- [ ] Run platform smoke tests against the new build to see whether any of our Components break

**Comment by mehdi-vaadin** [comment]
> The @HtmImport-only components are ignored
- What does it mean? How should we "_ignore_" a component? Should we ignore its `@Route` annotation if it has one? What if it's added to another component? At the moment, the annotation is ignored in the npm mode no matter if it's alone or along with a `@JsModule` annotation.

**Comment by mehdi-vaadin** [comment]
The [code](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java#L195) that apparently maps `@HtmlImport` to `@JsModule` as a temporary solution (See https://github.com/vaadin/flow/issues/5076) doesn't work anymore and will be removed as a part of the fix of this issue.

**Comment by mvysny** [comment]
It's so easy to forget that HtmlImport is ignored in the npm mode. It would be great if Vaadin would print a warning message when a HtmlImport-annotated component is attached to the UI, when it's lacking NpmPackage and JsModule
