### ISSUE TITLE
vaadin.whitelisted-packages runs unexpected "npm install"

### ISSUE THREAD

**Issue by estronque** [vaadin/flow#6404]
- Description of the bug:
If we set the 'vaadin.whitelisted-packages' property, it is always executed 'npm install' whenever a test through maven is triggered.

- Expected behavior:
If there is no change in the code, the second time 'mvn test' is executed, it should not be executed 'npm install'.

- Investigation:
After debugging the vaadin internal code, we have seen that the variable 'Map<String, String> deps' if the 'execute' method in class 'TaskUpdatePackages' does not contain 'vaadin-shrinkwrap' and the variable 'JsonObject packageJson' of the same method does contain it. This leads to a cleanup execution (deletion of the package-lock.json file) at the 'updatePackageJsonDependencies' method.

- Versions:
    - Vaadin: 14.0.2 
    - Flow version: 2.0.8
    - Java version: openjdk version "11.0.4" 2019-07-16
    - OS version: 
Linux eurm-XPS-15-9550 4.15.0-60-generic #67~16.04.1-Ubuntu SMP Mon Aug 26 08:57:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by denis-anisimov** [comment]
Confirmed.

Can reproduce.
Use `skeleton-starter-flow-spring`.
set `vaadin.whitelisted-packages=com/vaadin/starter/skeleton`.

As a result : `frontDeps.getPackages()`  inside `TaskUpdatePackages::execute` doesn't contain shrinkwrap node package.
And it will be removed from app package json (generated json) inside `updatePackageJsonDependencies`  method.
The removal will trigger `ensureReleaseVersion` which won't find shrinkwrap and trigger `cleanUp`.
Which is bad and the essence of the issue.
`shrikwrap` should be in the  `frontDeps.getPackages()`   regardless of 'vaadin.whitelisted-packages' property value.


(NOTE: everything works fine if there is no 'vaadin.whitelisted-packages' property. I have no idea how it affects NPM packages).

**Comment by ujoni** [comment]
Alright. It seems, at least with the white-list used by @denis-anisimov, that a class `com.vaadin.shrinkwrap.VaadinCoreShrinkWrap` gets excluded. If that happens, the shrinkwrap information won't end up in the packages, and cleaning is performed. I think the easiest fix here is to adjust the default white-list in Flow's Spring integration.

**Comment by denis-anisimov** [comment]
I think it's unbelievable lack that `com.vaadin.shrinkwrap.VaadinCoreShrinkWrap` won't be excluded by a custom white list.

So we just need hardcode this package/class so that it's always used.

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/spring #489](https://github.com/vaadin/spring/issues/489) via [**ZenHub**](https://www.zenhub.com/)
