### ISSUE TITLE
Unable to navigate server to server with vaadin-router

### ISSUE THREAD

**Issue by qtdzz** [vaadin/flow#6406]
## Steps to reproduce
1. Add another server view, e.g. `MyView` with route `my-view`, in beverage buddy `ccdm` branch
2. Add a link to `my-view` in `main-layout.ts`
3. Run the application in `clientSideMode`
4. Navigate to `my-view` from ReviewList view or vice versa
## Actual behavior
Cannot navigate between server views
## Expected behavior
Should be able to navigate between server views

## Discuss
The problem is that after PR #6361, the flow clientside only calls server side to update the container in `onBeforeEnter`. However, the current `vaadin-router` won't trigger any events if the element returned from `action` is the same. It's exactly the case of `flow.route`. We always return the same instance of `flow-container`, so that `vaadin-router` ignores all the lifecycle events, which makes the container stay the same. 
I have talked with Leif and Viktor, the conclusion is that for now, we should create a different container for each navigation to make it work and improve the reusability later.

**Comment by manolo** [comment]
IMO router should call events when the element is the same but routing info is different.
Adding a new container is an extra work that could have other problems, for instance we need to configure correctly flex in all the DOM tree, etc.
I would fix this issue in router instead

**Comment by qtdzz** [comment]
This bug should be fixed in vaadin-router instead. Closed in favor of https://github.com/vaadin/vaadin-router/issues/387
