### ISSUE TITLE
Npm dev mode in 14.0.3 slower than in 14.0.2

### ISSUE THREAD

**Issue by igormilina** [vaadin/flow#6416]
- Description of the bug

I'm experiencing massive slowdown when running application in dev-mode in version 14.0.3 compared to 14.0.2. Everything else in the application is the same.

Version 14.0.2: Deploy took 53,711 milliseconds
Version 14.0.3: Deploy took 109,500 milliseconds

There is noticable difference in number of classes visited (and this is performed twice during application startup):
Version 14.0.2: dev-updater - Visited 2772 classes. Took 5886 ms.
Version 14.0.3: dev-updater - Visited 4104 classes. Took 34022 ms. (!)

(Project has "vaadin.whitelisted-packages" set to just application web package)

- Expected behavior
Application startup time should be similar to previous version (or hopefully faster).

- Actual behavior
Application startup is 2x slower.

- Versions:
    - Vaadin / Flow version: 14.0.3
    - Java version: 11
    - Spring boot: 2.1.7
    - Server: Tomcat 9
    - OS version: Win10 x64
    - Browser version (if applicable): -

**Comment by denis-anisimov** [comment]
Performance issue.
Apparently there are changes in the logic which increased the number of visited classes.

**Comment by caalador** [comment]
Hi a couple of questions for this issue.

How are you starting the server? At least running `mvn spring-boot:run` I only get one `Visited xyz classes` not two 
v14.0.3 -  1.226s

**Comment by igormilina** [comment]
I forgot to mention that application is packaged as a normal war and deployed on Tomcat 9. The first "class visit" occurs before spring boot startup, and the second class visit occurs after spring startup. That behaviour is the same as before 14.0.3 and the application is running fine on both versions.
I can attach startup log if necessary.

**Comment by caalador** [comment]
Hi the logs would be appreciated perhaps that would give a better understanding.
Also have you tested 14.0.4 if it's any better from 14.0.3

Also could you give the time you have for starting https://vaadin.com/start/latest/full-stack-spring so we would have some references on the performance.

**Comment by caalador** [comment]
Also in the case where you deploy externally it would be advisable to add the ´build-frontend` goal to the vaadin maven plugin or do a production build so we don't start the development server for the war on tomcat.

**Comment by denis-anisimov** [comment]
>They do not touch the classvisitor in any way.

Yes, this is a good note. Please be aware of that.

But what I'm suggesting is : exclude the entry point (the `VaadinServiceInitListener` impl).
So  that it won't be found by Spring scanner and as a result classvisitor won't know about it.

**Comment by igormilina** [comment]
As I can see, setting property "vaadin.whitelisted-packages" has no effect on finding endpoints in subtypes of VaadinServiceInitListener. The framework will find and visit my VaadinServiceInitListener in whatever package it's in. (I already have that property set to just application package that contains views, and it does have great effect on application startup time - without it, startup time is 5 minutes).

Currently, I used an ugly workaround - in my VaadinServiceInitListener I use reflection to create one of my core classes (this is the class that has eclipselink and spring references) and invoke a method on it. That way class visitor cannot visit this class, as it is not directly used. 

I still think there should by a way to control which or how classes/packages are visited. But this would be another issue.

So, I think this issue can be closed as invalid, as version 14.0.3 is not slower than 14.0.2. The issue is generally related to class visitor mechanism, that unnecessary makes visit to too many classes, and it just happened that I stumbled on this in 14.0.3.

**Comment by denis-anisimov** [comment]
>As I can see, setting property "vaadin.whitelisted-packages" has no effect on finding endpoints in subtypes of VaadinServiceInitListener.

I would say this is a bug.
I think if your `VaadinServiceInitListener`  impl is inside a package which is not in the white-list then it should not be found.
The whole point of white list at the moment is to reduce the number of classes to scan for endpoints.
It doesn't affect anyhow the byte code scanning.
Do you use the correct white list value ? (as far as I remember it uses slashes in package names, not dots).

>I still think there should by a way to control which or how classes/packages are visited. But this would be another issue.

Yes, that's another issue. We are considering avoiding the byte code scanning at all (at least for dev mode) currently because of such performance issues.

>So, I think this issue can be closed as invalid

Please close it if you think so.

I would recommend to make sure that white list doesn't help you to exclude impls of `VaadinServiceInitListener`  and make a ticket about this if it really doesn't work.

**Comment by caalador** [comment]
Hi.

We have ticket #6462 which we would expect to fix this as we would in essence for development mode skip the class visiting all together by default.

**Comment by igormilina** [comment]
> I would recommend to make sure that white list doesn't help you to exclude impls of `VaadinServiceInitListener` and make a ticket about this if it really doesn't work.

I've double checked and it really doesn't work. I've opened #6473, but I guess it's low priority if mentioned #6462 it on its way. 

Anyways, I'm closing this issue as it turns out that the problem is not related to issue title.
