### ISSUE TITLE
Compiling Multi-Module Project Throws IllegalStateException: Failed to Update the Flow Imports File

### ISSUE THREAD

**Issue by bshue** [vaadin/flow#6419]
Corresponding Vaadin Forum Thread: https://vaadin.com/forum/thread/17818912/vaadin-14-trouble-compiling-multi-module-project-with-maven

We have a multi-module project that's built with Maven. 

Running "mvn clean install" on the parent project works just fine. All modules compile without error.

Module A is based on the Bakery starter app.

Module B is a custom web component based on the following instructions:

https://vaadin.com/docs/v14/flow/web-components/creating-an-in-project-web-component.html

Module A imports the web component from Module B.

When I try running "mvn spring-boot:run" on Module A, I get the following error:

2019-08-30 09:02:50.946 ERROR 10984 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception sending context initialized event to listener instance of class [com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener]

java.lang.IllegalStateException: Failed to update the Flow imports file 'C:\**_Module-B_**\target\frontend\generated-flow-imports.js'
        at com.vaadin.flow.server.frontend.TaskUpdateImports.execute(TaskUpdateImports.java:128) ~[flow-server-2.0.7.jar:2.0.7]
...
Caused by: java.lang.IllegalStateException:

  Failed to find the following css files in the `node_modules` or `/frontend` tree:
      - ./styles/**_Module-A-_**styles.css
  Check that they exist or are installed.

To work around this, I copied the .css file from Module-A to Module-B. Now, "mvn spring-boot:run" works, but I shouldn't have to do this. Module-A's stylesheet should only be in Module-A.

Thanks for your time,

Bryan

**Comment by denis-anisimov** [comment]
Hi, 
do you have any special (maven) configuration in your module B? (or A)

I'm worried about `java.lang.IllegalStateException: Failed to update the Flow imports file 'C:**Module-B**\target\frontend\generated-flow-imports.js'` it refers to module B but it's just a dependency in the classpath of module A.
It should not have any `generated-flow-imports.js`  since only module A is the web application.
The `generated-flow-imports.js`  is generated only for the web app if the configuration done correctly.

Could you please post here the content of your `module B` pom.xml file ?

**Comment by bshue** [comment]
Denis,

Thanks for taking a look. To be honest, I don't have a firm grasp on what maven is doing here. It's quite possible that we have a mis-configuration in our poms.

Attached is the pom.xml from "Module-B". This is the web component that's being imported into "Module-A".

I believe we only made minor changes to this file (adding the <parent> pom, <name>, etc.). We used the following starter package (https://vaadin.com/start/lts/component).

<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>OpenLayersMap</artifactId>
    <packaging>jar</packaging>
    <name>OpenLayersMap</name>
    <description>Integration of OpenLayers for Vaadin platform</description>
    
    
	<parent>
		<artifactId>Iris</artifactId>
		<groupId>gov.noaa.nws</groupId>
		<version>7.0.0</version>
	</parent>

    <properties>
        <drivers.dir>${project.basedir}/drivers</drivers.dir>
    </properties>

    <build>
        <defaultGoal>jetty:run</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <index>true</index>
                        <manifest>
                            <addClasspath>false</addClasspath>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                        </manifest>
                        <manifestEntries>
                            <Vaadin-Package-Version>1</Vaadin-Package-Version>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-maven-plugin</artifactId>
                <version>${vaadin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-frontend</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>${jetty.version}</version>
                <configuration>
                    <scanIntervalSeconds>3</scanIntervalSeconds>
                    
                    <useTestScope>true</useTestScope>
                    <supportedPackagings>
                        <supportedPackaging>jar</supportedPackaging>
                    </supportedPackagings>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>directory</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-assembly-plugin</artifactId>
                        <version>3.1.0</version>
                        <configuration>
                            <appendAssemblyId>false</appendAssemblyId>
                            <descriptors>
                                <descriptor>assembly/assembly.xml</descriptor>
                            </descriptors>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>single</goal>
                                </goals>
                                <phase>install</phase>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>3.0.1</version>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>3.0.1</version>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <quiet>true</quiet>
                            <additionalparam>-Xdoclint:none</additionalparam>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        
        <profile>
            <id>production</id>
            <properties>
                <vaadin.productionMode>true</vaadin.productionMode>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>com.vaadin</groupId>
                    <artifactId>flow-server-production-mode</artifactId>
                </dependency>
            </dependencies>
            
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.vaadin</groupId>
                        <artifactId>vaadin-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>build-frontend</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>integration-tests</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.eclipse.jetty</groupId>
                        <artifactId>jetty-maven-plugin</artifactId>
                        <version>${jetty.version}</version>
                        <configuration>
                            <scanIntervalSeconds>0</scanIntervalSeconds>
                            <supportedPackagings>
                                <supportedPackaging>jar</supportedPackaging>
                            </supportedPackagings>
                            <stopKey>${project.artifactId}</stopKey>
                            <stopPort>8081</stopPort>
                        </configuration>
                        <executions>
                            <execution>
                                <id>start-jetty</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>start</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>stop-jetty</id>
                                <phase>post-integration-test</phase>
                                <goals>
                                    <goal>stop</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>com.lazerycode.selenium</groupId>
                        <artifactId>driver-binary-downloader-maven-plugin
                        </artifactId>
                        <version>1.0.17</version>
                        <configuration>
                            <onlyGetDriversForHostOperatingSystem>
                                true
                            </onlyGetDriversForHostOperatingSystem>
                            <rootStandaloneServerDirectory>
                                ${drivers.dir}/driver
                            </rootStandaloneServerDirectory>
                            <downloadedZipFileDirectory>
                                ${drivers.dir}/driver_zips
                            </downloadedZipFileDirectory>
                            <customRepositoryMap>
                                ${project.basedir}/drivers.xml
                            </customRepositoryMap>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>selenium</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>2.22.2</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <trimStackTrace>false</trimStackTrace>
                            <enableAssertions>true</enableAssertions>
                            <systemPropertyVariables>
                                
                                <webdriver.chrome.driver>
                                    ${webdriver.chrome.driver}
                                </webdriver.chrome.driver>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
                    <plugin>
                        <artifactId>maven-resources-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                
                                <id>copy-test-to-classes</id>
                                <phase>process-test-classes</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                                    <resources>
                                        <resource>
                                            <directory>${project.build.testOutputDirectory}</directory>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>


If it helps, here is an excerpt from "Module A's" pom.xml:

<dependencies>
		...
		<dependency>
			<groupId>gov.noaa.nws</groupId>
			<artifactId>OpenLayersMap</artifactId>
			<version>7.0.0</version>
		</dependency>
                ...
</dependencies>

Thanks for your help.

**Comment by bshue** [comment]
Let's try that again. Excerpt from Module-A's pom.xml:

```
<dependencies>
	...
	<dependency>
		<groupId>gov.noaa.nws</groupId>
		<artifactId>OpenLayersMap</artifactId>
		<version>7.0.0</version>
	</dependency>
	...
</dependencies>
```

**Comment by denis-anisimov** [comment]
I see in your `module B``pom.xml` `vaadin-maven-plugin` usage.
You don't need to use it in a module which is not a web app module.
Your `module B`  is just a jar module. It knows nothing about web things.
And it should not use anything related to web : `vaadin-maven-plugin` , `jetty` , so on.
You just should package it properly as a Jar file (if you have any resources that needs to be used in web they should be in `META-INF/resources/frontend`).

Then all the configuration related to web should be done only in one module: `module A` which as I understand your web app module.

I'm pretty sure that this is the reason why you have this exception.

**Comment by bshue** [comment]
Ahh...

I just assumed the vaadin-maven-plugin / jetty stuff in my pom.xml was there for development / testing purposes.

I cleared out Module-B's pom.xml to simply build a jar. No IllegalStateException when running "mvn spring-boot:run" on Module-A.

Thank you, Denis, for your time. It's much appreciated. This ticket can be closed/rejected.

Bryan
