### ISSUE TITLE
Bundle containing all frontend resources

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#6425]
Use all resources on the classpath rather than finding out what is actually used in development mode. We assume here that scanning through everything on the classpath is faster than a scan that takes reachability into account. In production mode, the current approach will be retained (bundle will only contain actually used resources).

Advantages:
- No more repeating bytecode traversing helps significantly with Spring projects
- Jrebel / HotSwap will work when adding component that was not previously used

Disadvantages:
- Different bundles in dev and prod mode is not optimal

Results:
- We have a full bundle generation approach running
- Benchmarking the application startup time with this approach
- Can we notice that a new view with frontend dependencies has been added during a redeployment?

**Comment by denis-anisimov** [comment]
Current measurements with bakery on my machine:
- Search for classes with annotations took 2 seconds
- Search for subclasses took 4 seconds ( includes search for WebComponentExporter, UIInitListener, VaadinServiceInitListener) .
- Search for all classes took 7 seconds.

Preliminary analysis: every time when we add a new "entry point" (like `UIInitListener`) we increase the time for one second.

Scanning classes: 
- Visited 1244 classes. Took 987 ms.

So in fact scanning (at least in bakery) doesn't take too much time.

But I assume if we reduce the number of "entry points" replacing search for several known "entry points" to just  `NpmPackage` and   `JsModule` then we will reduce time significantly (will see).
