### ISSUE TITLE
Missing shadow-roots on injected Components

### ISSUE THREAD

**Issue by PascalSchoe** [vaadin/flow#6437]
[vaadin-14-project.zip](https://github.com/vaadin/platform/files/3600541/vaadin-14-project.zip)
Hello,
we have noticed some difficult behaivor, regarding injected Components. It started after migrating to vaadin 14. I have created a demo project to illustrate this bug (?).

# Description of the problem
The problem seems to occur when injecting a component via Interface. The injection works fine for the content but somehow the shadow-root gets lost and thus there are no styles on this element. 

But if we inject an implementation of this interface everything works just fine.

## About this project
This project is an simplification of a webgui which is running within a *docker-container*. We are using *Thorntail*. The configuration is taking place within the *pom.xml*.

We are only developing against the newest Chrome browser.

## Requirements
You need Docker on your machine.

## Starting the Project
```bash
$ mvn clean package
```

## How to reproduce this problem
To reproduce this behaivor please open the **MainUI-class** and toggle  the comments line **36** and **37**.

You can furthermore observe if you  use the implementation of the Components everything works fine as described before. But if you click one of the buttons no Notification is shown. If you inspect the DOM you will find it is there but like before just the tag without shadow-root. This can be fixed by uncommenting line **39**.

**Comment by Legioth** [comment]
As a workaround, you can use the `@Uses` annotation on e.g. `MainUI` to explicitly define components that should be considered when determining what to include.

**Comment by PascalSchoe** [comment]
Ok thanks for your reply! So it's a feature and not a bug :-) Shall I close this issue?

**Comment by Legioth** [comment]
It's a feature with some bugs in the underlying thinking.

Let's keep this issue open for tracking progress towards dealing with those underlying issues.

**Comment by mehdi-vaadin** [comment]
@PascalSchoe it seems that this issue has been fixed and can't be reproduced with 14.1.20. Could you please verify it?

**Comment by mehdi-vaadin** [comment]
@PascalSchoe, since we haven't heard from you and the issue seems to be resolved, I'm closing this. Please create a new issue if you still have this problem.
