### ISSUE TITLE
IE11 flex issues with FormLayout, contents overflows the screen

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow#6439]
When a FormLayout is nested inside of an HorizontalLayout, the form content is not adjusted, and it overflows the screen.

Minimal reproducible example:
```
public MainView() {
	Button button = new Button("BUTTON");
	button.setWidth("150px");
		
        add(new HorizontalLayout(
            createFormLayout(),
            new Upload(),
            button));
    }
    
    private Component createFormLayout() {
    	FormLayout form = new FormLayout();
    	form.setResponsiveSteps(new FormLayout.ResponsiveStep("250px", 1));

    	ComboBox<String> combobox1 = new ComboBox<>();
    	combobox1.setWidth("100%");
    	form.addFormItem(combobox1, "Combobox 1");
    		
    	ComboBox<String> combobox2 = new ComboBox<>();
    	combobox2.setWidth("100%");
    	form.addFormItem(combobox2, "Combobox 2");

    	RadioButtonGroup<String> radioButtonGroup = new RadioButtonGroup<String>();
    	radioButtonGroup.setItems("item1", "item2", "item3");    		
    	form.addFormItem(radioButtonGroup, "Radio Buttons");

    	DatePicker datePicker = new DatePicker();
    	datePicker.setWidth("100%");
    	form.addFormItem(datePicker, "Date Picker");

    	Checkbox checkbox1 = new Checkbox();
    	form.addFormItem(checkbox1, "Checkbox 1");
    	
    	Checkbox checkbox2 = new Checkbox();
    	form.addFormItem(checkbox2, "Checkbox 2");

    	Button button = new Button("BUTTON");
    	form.addFormItem(button, "");
    	return form;
    }
```

Expected behavior: content does not overflow, as in Chrome:
![image](https://user-images.githubusercontent.com/11554739/64726573-5317a500-d4ad-11e9-93c6-eb979d8bd841.png)

Actual behavior in IE11:
![image](https://user-images.githubusercontent.com/11554739/64727655-af7bc400-d4af-11e9-81f6-af0c1d9c3dc9.png)

Versions: Vaadin 14.0.4, IE11.885.17134.0, Chrome 76.0.3809.132, Lumo theme

**Comment by TatuLund** [comment]
This behavior is due to IE11 been more picky about "correct" (matter of opinion) layout settings.

If I modify the main view as follows, it works

```
public MainView() {
    	Button button = new Button("BUTTON");
    	button.setWidth("150px");
    	FormLayout form = createFormLayout();
    	Upload upload = new Upload();
    	HorizontalLayout horiz = new HorizontalLayout(form, upload, button);
    	horiz.setWidth("100%");
        add(horiz);
    }
```

I.e. if the width of the horizontal layout is undefined, IE11 does not like it in this case, but other browsers seem to cope with situation.

**Comment by pleku** [comment]
This issue is not valid for /flow. If it is a problem with `FormLayout` it should be recreated to another repository. Instead of moving the issue, I'm closing this as it might be fixed already. In case someone runs into this, please create a new issue to the web component mororepo.
