### ISSUE TITLE
Manual install of babel-cli needed

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow#6441]
I am running on Windows 10, npm 6.9.0 and 6.9.3 tested.
In both cases, when I have a fresh git checkout without any "node_modules" the build fails.
I have to enter the project directory and do "npm install babel-cli".
And also "acorn" and "mkdirp" and "babel-loader@7" and "babel-core" must be installed manually.

**Comment by mehdi-vaadin** [comment]
Does the `vaadin-maven-plugin` always run `prepare-frontend` goal? Can you share the pom.xml with us (at least the plugin part)?

**Comment by enver-haase** [comment]
Plugin is inherited from parent pom and looks like:

 <plugin>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-frontend</goal>
                            <goal>build-frontend</goal>
                        </goals>
                        <phase>compile</phase>
                    </execution>
                </executions>
            </plugin>

**Comment by enver-haase** [comment]
Please close.
I realised that I was executing "build-frontend" in development mode, of course without depending on  flow-server-production-mode .
I do not use production mode so removing "build-frontend" fixed it for me.
