### ISSUE TITLE
CCDM: Supply default index.html and index.ts for Java-only use

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#6442]
To improve backwards compatibility with old Java-only applications, there should be default implementations of `index.html` and `index.ts` which are used if the application doesn't provide their own versions of those files and there are `@Route` annotated classes on the classpath.

I'm not sure whether it would be better to actually add those files to the project directory (i.e. similarly to `/package.json`) or whether they should be treated as transient generated files (i.e. similarly to `generated-flow-imports.js`).

The main benefit of adding the files to the project directory is the the developer will get baselines for adding their own tweaks. The main drawback is that the old version will remain in use after make updates to the default contents.

**Comment by manolo** [comment]
It should generate a default `/tsconfig.json` otherwise `index.ts` would be unusable

**Comment by vlukashov** [comment]
discussed f2f:
 - generate `index.html` into the `target` folder (if absent in `frontend`)
 - generate index**.js** into the `target` folder (if absent in `frontend`)
    For auto-generated code type checking is not important, and not using TS means we do not need to generate a tsconfig file in this case.
 - if `index.ts` is present in the `frontend` folder but there is no `tsconfig.json`, generate tsconfig into the `frontend` folder
 - when generating tsconfig.json` add a comment that the file is auto-generated and should be committed into the VCS (TS config file allows comments even though it's a `.json` file)
