### ISSUE TITLE
UI id # 0 is initialized twice (or instantiated twice?) when `@PWA` annotation disabled

### ISSUE THREAD

**Issue by basil-bourque** [vaadin/flow#6454]
- Description of the bug

With a basic Vaadin Starter app, adding only the code needed to listen to[ `UIInitEvent`](https://vaadin.com/api/platform/14.0.4/com/vaadin/flow/server/UIInitEvent.html), and while disabling the [`@PWA`](https://vaadin.com/api/platform/14.0.4/com/vaadin/flow/server/PWA.html) annotation on the `MainView`, Vaadin 14.0.4 emits *two* `UIInitEvent` events for a `UI` object whose is numbered zero.

- Minimal reproducible example

On the [Vaadin Starter](https://vaadin.com/start/latest) page, create a new Vaadin 14.0.4 project using the "Plain Java Servlet" option.

Add a class to listen for `VaadinServiceInitListener`, wherein we register a listener for `UIInitEvent`.

    package work.basil.example.bug;

    import com.vaadin.flow.server.ServiceInitEvent;
    import com.vaadin.flow.server.UIInitEvent;
    import com.vaadin.flow.server.VaadinServiceInitListener;

    import java.time.Instant;
    import java.util.UUID;

    public class ApplicationServiceInitListener
            implements VaadinServiceInitListener
    {

        @Override
        public void serviceInit ( ServiceInitEvent serviceInitEvent )
        {
            System.out.println ( "BASIL - ServiceInitEvent." + Instant.now () );

            serviceInitEvent.getSource ().addUIInitListener (
                    ( UIInitEvent event ) -> {
                        System.out.println ( "BASIL - UIInitEvent. UI id # " + event.getUI ().getUIId () + ". " + Instant.now () + ". Incident # " + UUID.randomUUID () +".");
                    } );
        }

    }

Register that class with the Java Service Provider Interfaces (SPI) facility.

1) In the `resources` folder of the Vaadin web app, create nested folder `META-INF`.
2) In that `META-INF` folder, create nested folder `services`. 
3) In that `services` folder, create a file named exactly: `com.vaadin.flow.server.VaadinServiceInitListener`.
4) In that file write the fully-qualified name of the class created above. For example: `work.basil.example.bug.ApplicationServiceInitListener`. 

Run the web app:

1) Quit your web browser, to avoid the bug where Web Service Workers hang around longer than they should.
2) Run your Vaadin web app with the bundled Jetty Maven action.
3) Launch your web browser, pointing to `localhost:8080`. 

You will see no bug. You will see console output like this:

>BASIL - ServiceInitEvent.2019-09-14T22:55:50.814552Z
>BASIL - UIInitEvent. UI id # 0. 2019-09-14T22:55:50.985629Z. Incident # 9d970202-e80c-4d64-9a8d-c3b52dea7356.

Quit your web app and web browser. To provoke the bug, go to `MainView` class. Disable the `@PWA` attribute.

    …
    @Route ( "" )
    //@PWA ( name = "Project Base for Vaadin", shortName = "Project Base" )
    public class MainView extends VerticalLayout
    …

Do a Maven `clean`. Launch the app in bundled Jetty again. Launch your web browser. You will see the bug, two `UIInitEvent` events for UI id # 0. The different randomly-generated UUID values demonstrate that it is not a problem with the console output merely being duplicated. We know the `UIInitEvent` listener is running twice.

>BASIL - ServiceInitEvent.2019-09-14T23:01:56.519118Z
>BASIL - UIInitEvent. UI id # 0. 2019-09-14T23:01:57.095880Z. Incident # fa23e791-b653-4f41-8199-e2de430f6128.
>BASIL - UIInitEvent. UI id # 0. 2019-09-14T23:01:57.109201Z. Incident # 829b82ef-8e26-4164-9e94-78cedaeb3200.

- Versions:
    - Vaadin / Flow version: 14.0.4
    - Java version: Java 13 beta, OpenJDK Runtime Environment (build 13+33)
    - OS version: macOS Mojave 10.14.6
    - Browser version: Chrome 77.0.3865.75. Also seen in Safari 12.1.2 (14607.3.9). 

« fin »

**Comment by caalador** [comment]
This only seems to happen if I happen to have a service worker still registered for localhost.

If you after running it with PWA go to `Inspector` > `Application` and remove the service worker then only the expected single UI init happens

**Comment by ujoni** [comment]
I guess this is somewhat related to 
- When @PWA annotation is not present, Vaadin service worker should be disabled #6394
- Ability to control service worker installation in @PWA #6548

**Comment by web-devel** [comment]
Also, it may be a good idea to handle localhost specifically, like, for example create-react-app [does](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template-typescript/src/serviceWorker.ts#L45 )

**Comment by joheriks** [comment]
This is a bug, there should be no need to create UI and request handler when a stray service worker requests `sw.js` for a non-PWA app. This could be identified by looking for the header `Service-Worker` and  if found, denying the request without going into `BootstrapHandler` and consequently initializing a UI.

**Comment by bogdanudrescu** [comment]
I found this problem several times where a `GET /sw.js` will result in a new `UI` instance and all that comes with it. This is certainly a bug. It is mostly annoying on debugging when the breakpoint triggers on the `sw.js` request on a different `UI` than expected.

**Comment by pekam** [comment]
Possibly related:
When opening Chrome dev tools on Vaadin 14 app, a new server-side UI is initialized. I noticed it because the constructor of my view class ran again. The request that got handled was `GET /` (so not service worker).

Browser info: `Chromium Version 81.0.4044.122 (Official Build) Built on Ubuntu , running on LinuxMint 19.1 (64-bit)`
