### ISSUE TITLE
@Push with websocket method fails with load balancer

### ISSUE THREAD

**Issue by letrthang** [vaadin/flow#6456]
**- Description of the bug:**
when server is configured with load balancer and @Push enable with websocket method, it throws error message:

"

> Firefox can’t establish a connection to the server at wss://neonplatform-unexpected-kangaroo.cfapps.io/PUSH?v-uiId=0&v-pushId=1b167984-e296-4e4a-8625-a59d1a9dc4b9&X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.3.2.vaadin1-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json;%20charset=UTF-8&X-atmo-protocol=true

."

> Websocket closed, reason: Connection was closed abnormally (that is, with no close frame being sent). - wasClean: false vaadinPush.js:1:40213
Websocket failed on first connection attempt. Downgrading to long-polling and resending vaadinPush.js:1:40213
Sun Sep 15 2019 18:08:26 GMT+0700 (Indochina Time) Atmosphere: offline event vaadinPush.js:1:40213

- Versions:
    - Vaadin / Flow version: 14
    - Java version: 1.8
    - OS version: Linux, Tomcat
    - Browser version (if applicable): chrome + Firefox
<img width="960" alt="push_error" src="https://user-images.githubusercontent.com/13396193/64920739-0c93b480-d7e5-11e9-8840-97543e97b940.PNG">

this issue post to vaadin forum:
[url](https://vaadin.com/forum/thread/17829173/vaadin-push-error-on-load-balancer)

**Comment by caalador** [comment]
Does the load balancer always redirect to the same server for the whole of the session and not switch targets at times?

Does the balancer support websockets for multiple servers?

**Comment by letrthang** [comment]
LB supports for multiple servers. we config LB to sticky session so LB could always  redirect to the same server for the whole of the session. 
This issue is vaadinPush.js _cannot connect to server_. We also have our a customized JavaScript file to access the server via websocket and it works fine with our LB.

**Comment by letrthang** [comment]
![image](https://user-images.githubusercontent.com/13396193/66267242-126b3b80-e861-11e9-8c5c-c987718f401e.png)

above error message on Chrome

**Comment by letrthang** [comment]
upgrade to vaadin 14.0.8, issue no longer happen.
also server url changed to https://neonplatform.com ( removed www)
