### ISSUE TITLE
prepare materials for a client-side routing DX test

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6467]
The scope for DX tests: **client-side views and routing + client-server routing fallback**.
This DX test should include the following steps:
 - Create a project with TypeScript views using start.vaadin.com (staging environment)
    This step would tell how discoverable is the TypeScript feature on start.vaadin.com, and how usable it is.
 - Start the project
    This step would tell if the project structure creates confusion or not, is it clear how to start the project, and how reasonable are first and repeat build times.
 - Modify an existing TypeScript view
    This step would show how easy is it to find the place to change, and to make modifications to TypeScript code, and what's the reload time (until the change is visible in the running app)
 - Add a view in TypeScript
    This step would show if client-side views can be used, and has sufficient documentation.
 - Add a new client-side route
    This step would show if client-side routing can be used, and has sufficient documentation.
 - Add a new server-side view + route
    This step would show if the fallback from client-side routes to server-side can be used, and has sufficient documentation.
 - Set a breakpoint in TS (optional, if time permits)
    This step would show the DX of debugging TypeScript code. Would developers know how to do that? Would that be more / less / about the same DX as debugging the Java code?

DoD:
 - create a testing plan (document for the person running the tests) and link it to this ticket
 - create a testing script (document that's given to the testers) and link it to this ticket

See the [Flow's basic DX plan template](https://drive.google.com/open?id=1RygaEa7xfxh9gbsD0RYVupU9hqV2QgxEwpBV-XcTJQk) and [dynamic route registration DX material](https://drive.google.com/open?id=1KnDqfnlfAI3Ehk4bSqfHM9Zbwc1JbLzK) for examples.

**Comment by platosha** [comment]
Test plan: https://docs.google.com/document/d/108TGoSrozSOyHtxkNahGKmccTlH7kBuanU2JNWivYyQ/edit?usp=sharing

Test scenario: https://docs.google.com/document/d/1hIELnHUZ881I7TEAQImo14tPe3vx0PMkRlx_5JlQ62I/edit?usp=sharing
