### ISSUE TITLE
prepare materials for a migration and client-side bootstrapping DX test

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6468]
The scope for DX tests: **client-side bootstrapping + migration from V14**.
This DX test should include the following steps:
 - Follow the [tutorial](https://github.com/vaadin/flow/issues/6365) to add a client-side view to a V14 app
 - Add a splash screen to a Flow app
    This tests the `flow.start()` API
 - Add a dynamic meta-tag into the index.html response
    This tests the `IndexHtmlRequestHander` API

DoD:
 - create a testing plan (document for the person running the tests) and link it to this ticket
 - create a testing script (document that's given to the testers) and link it to this ticket

See the [Flow's basic DX plan template](https://drive.google.com/open?id=1RygaEa7xfxh9gbsD0RYVupU9hqV2QgxEwpBV-XcTJQk) and [dynamic route registration DX material](https://drive.google.com/open?id=1KnDqfnlfAI3Ehk4bSqfHM9Zbwc1JbLzK) for examples.

**Comment by platosha** [comment]
Plan: https://docs.google.com/document/d/1CPQ_TPhJ2ANNnf1pdyS0mCjQ7T4aEsdQhKac-jR2rLc/edit?usp=sharing

Script: https://docs.google.com/document/d/1Ayw6ZGD6oe9mfmrMIDEqUHwxLxNhgxlOWWYimATYvng/edit?usp=sharing
