### ISSUE TITLE
VaadinServiceInitListener included in dev mode class visit even it doesn't match package whitelist

### ISSUE THREAD

**Issue by igormilina** [vaadin/flow#6473]
- Description of the bug
In our project, spring boot's application.properties property "vaadin.whitelisted-packages" is set to include only our package with view classes. The configuration is working as expected - startup time have decreased from 5 minutes to 50 seconds after this property was set.

We also have custom VaadinServiceInitListener class in our project. This class is in package that is not listed nor subpackage of package "vaadin.whitelisted-packages". Framework, during startup in dev mode, still find and visit this class, which is not supposed to do.

- Expected behavior
Framework should not visit custom VaadinServiceInitListener impl class if its package is not listed in "vaadin.whitelisted-packages" property

- Actual behavior
Class is visited during startup.

- Versions:
    - Vaadin / Flow version: 14.0.4
    - Java version: 11
    - OS version: Win10 x64

**Comment by caalador** [comment]
To be noted for this the whitelist and blacklist features are only for Spring classpath scanning and to have those extended to flow core it would be a new feature.
For the classpath scanning in dev mode we are currently working on #6462 which should fix this for development mode by not using byte scanning at all when collecting the component imports.

**Comment by igormilina** [comment]
Startup time has greatly improved since this issue was open (especially in 14.4.0), so it is no longer relevant. Closing.
