### ISSUE TITLE
Collect all dependencies without byte code scanning in dev mode

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#6480]
Part of #6462 

To make startup faster in development mode, we should generate the
`generated-flow-imports.js` file using the components found during
annotation scanning and skip byte code scanning. The production mode should keep the current method.

### Acceptance criteria
- [x] The performance improvement should be verified with a relatively big project
- [x] Dependencies should be collected without byte code scanning
- [x] Production mode should stay the same as it is

**Comment by denis-anisimov** [comment]
I'm using (plain) skeleton starter project.
I've added two deps: eclipse link and deeplearning4j-core:

```
<dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>eclipselink</artifactId>
            <version>2.7.4</version>
        </dependency>

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>0.9.1</version>
        </dependency>
```

As a result the project classpath has a huge number of classes.
Here are the results of the execution this project:

Full classpath scanner (`2.1` SNAPSHOT with applied PR):
- Scanning elapsed time=1076ms
- Visited 87 classes. Took 25 ms.

Byte code scanner (`2.0` SNAPSHOT):
Scanning elapsed time=1162ms
Visited 4376 classes. Took 4575 ms.

Discovering phase is around 20 times better.
And even scanning (which is done by the web container) is a bit better.
