### ISSUE TITLE
Allow user to switch between "mega bundle" mode and byte scanning mode

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#6481]
Part of #6462
Blocked by #6480 

User should be able to switch between the two modes of collecting front-end dependency imports, those two modes being "the mega bundle" and byte code scanning.

### Acceptance criteria
- [ ] User is able to enable byte scanning for development mode
  - System property/application property/web.xml 
- [ ] User is able to enable "mega bundle" for production mode
  - Maven plugin option
  - Allows for a fine-grained pom management with faster builds
  - Fallback bundle is not needed if production mode is using "mega bundle" but that is probably a separate improvement
- [ ] Document the new parameter

**Comment by joheriks** [comment]
Documentation PR pending: https://github.com/vaadin/flow-and-components-documentation/pull/824

**Comment by mvysny** [comment]
The switch is called `devmode.optimizeBundle` and is documented at https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-advanced.html
