### ISSUE TITLE
DevModeHandler is not serializable

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#6489]
`DevModeHandler`  is declared `Serializable` but it's not.
It contains `transient` `Process`  field but there is no code which restored the value of this field.
Values of non-transient fields of `Serializable` class are restored automatically by Java serialization mechanism.
`transient`  fields will get `null`  as a value.
It means that the value should be either lazy (there should be a code which checks whether it's `null` and set a value for it) or `readObject`  method from Java serializable mechanism should be used.

There are a number of issues with `DevModeHandler` class actually besides `transient` `Process`  field.
E.g. `port` field in most cases is autoassigned via `getFreePort()` .
It means that its value cannot be serialized since when it's deserialized the port may be already occupied by another process.
So it should be `transient`  semantically even though it's possible to serialize `int`.

I've added one more  `transient` filed without any restoration logic as a part of https://github.com/vaadin/flow/pull/6487 PR since `DevModeHandler`  is not serializable already.
I'm not even sure whether this class should be serializable at all in fact.

So :
- understand whether `DevModeHandler` should be serializable or not
- exclude it from serializable tests if not and remove `implements Serializable`.
- make it properly serializable if it should be serializable.

Keep in mind: Java deserialization doesn't call CTOR. It means you may not rely on initialization logic made in the CTOR.

**Comment by ujoni** [comment]
I don't think it should be `Serializable`. Or rather, my understanding is that we want to serialize certain objects to facilitate state-transfer; sessions being flung from a node to another and such. I don't see how that would require `DevModeHandler` to implement `Serializable`.

But maybe I don't know all the expected use-cases we have. Thoughts @caalador ?

**Comment by caalador** [comment]
I don't see what we would gain by having DevModeHandler as serializable.

**Comment by denis-anisimov** [comment]
I'm pretty sure that the only one reason why it's serializable at the moment: the serializable tests are failing if it's not.
So the author was either too lazy to find the proper test and exclude the class or didn't know how to do it. Making a class serializable (even if it's effectively not) is just easier.

**Comment by denis-anisimov** [comment]
Note : `DevModHanlder` field `devmodeHandler` is used inside `VaadinServlet` .
`VaadinServlet` should be serializable.
I don't see why there is a need to keep it as a field there in fact: `DevModHanlder` 
 has a static `getDevModeHandler` which may be used to access to the instance.

On the other hand if there is a real need to serialize and deserialize the whole servlet and a service then `DevModHanlder`  should be serializable which means that it should be designed so that it starts (or reuse properly) dev server.
