### ISSUE TITLE
Flow's StreamResource may not download full file

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#6494]
`StreamResource.Pipe.copy()` method uses this loop to copy streams:

```
            while ((n = read(session, source, buf)) > 0) {
                out.write(buf, 0, n);
            }
```

However `read` can return 0 as a valid result (e.g. when socket has no data) and thus can make the loop break sooner than EOF.

The fix is to use >= 0 and if 0 is returned then read a single byte to enforce the read (yeah it's a poor design of InputStream), or use Java 8's stream copy methods.

**Comment by denis-anisimov** [comment]
Good catch, thanks.
My bad.

>or use Java 8's stream copy methods.

`read` method may be protected by the session lock. So this is not a proper replacement in this case.
Easy to fix. Will do it shortly.

**Comment by mvysny** [comment]
Ah right, they must have changed the javadoc of InputStream since now read(byte[]) contains this important clause:

> there is an attempt to read at least one byte.

(it wasn't there before in Java 5 I think). So it's not necessary to call `int read()`. Good. The fix looks good to me.
