### ISSUE TITLE
Improve run time on CI environments (testbench, bender)

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#6509]
Current PR validation builds take 40-50 minutes to complete, which is an unacceptable time for a CI build (especially since the pipelines is used by Component builds too).

Reduce the build type by
- [ ] [Enabling npm package prefix](https://stackoverflow.com/questions/14742553/how-to-set-custom-location-for-local-installation-of-npm-package) in order to avoid downloading packages multiple times (potentially temporary, if pnpm is introduced)
- [ ] define an implement #6049

**Comment by denis-anisimov** [comment]
I've modified a PR validation build to use npm package prefix.
It didn't speed up the build anyhow.
So it seems it has no any sense to use it.

Since the second item is already existing #6049 ticket I would suggest to close this ticket.
