### ISSUE TITLE
Run `npm install` after adding entries to the top-level package.json file

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#6514]
Launching the project after updating from a slightly older `2.1-SNAPSHOT` will add `compression-webpack-plugin` to the project's top-level `package.json`. The problem is that there isn't anything that does `npm install` after this, leading to unexpected error messages when webpack starts up.

**Comment by Legioth** [comment]
The same will also happen if updating from Flow 2.0.12 to Flow 2.0.13 without also at the same time updating the platform version or otherwise making changes that affect `/target/frontend/package.json` and through that have `npm install` triggered.

**Comment by caalador** [comment]
In practice this would mean to removing the hash from the main package.json if a dev dependency is added as it is the internal package.json execution that finally checks if we need to execute `npm i` or not.

**Comment by Legioth** [comment]
That makes little sense from a semantical perspective, but I can see how that would be a practical way of making it work in practice.

I'd recommend that instead of simply removing the hash, it would be replaced with a dummy value that explains its purpose in case there's something weird going on in the project setup so that the second part of the process that writes a new hash there never happens.
