### ISSUE TITLE
NoTheme inconsistency : we have built-in annotated classes in Flow which means that no other theme can be used

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#6522]
`com.vaadin.flow.router.InternalServerError` and `RouteNotFoundError` class has `@NoTheme`.

This has no any sense since we have logic in the framework which checks that there is only one theme is defined for the application. This logic includes a check for `@NoTheme`: if it present then it's considered semantically as a theme annotation which means theme may not be used at all, so there can't be another team in the same application.

As a result the logic is totally broken since every application has `flow-server`  as a dependency and it  has at least two components annotated with `@NoTheme` which means not other team may be used.
Everything works because currently we are using byte code scanning strategy to identify frontend resources and themes with entry points which include neither `InternalServerError` nor `RouteNotFoundError` : this is just one more bug among others with byte code scanning approach.

The problem becomes evident with a full classpath scanning strategy. Those classes are found and the semantic which we want to have always make an application non-themed or it breaks if the theme is specified explicitly.
I've excluded those two classes here: https://github.com/vaadin/flow/pull/6521/files#diff-f03ce68f8cd695c752d0ce292b99464bR268.
But it really has not sense to keep them with  @NoTheme`  annotation and has this code as a workaround.

I assume the classes has been annotated in old days when @NoTheme` meant that the absence of the theme should not log a warning/error. 
But its semantic has changed with meaning: no theme should be used at all nowadays.
And it has no sense to have two built-in views with this annotation which always makes an app either broken or no themed.

**Comment by caalador** [comment]
As discussed previously the `@NoTheme` annotation was for marking that a route stack doesn't contain a theme and we shouldn't try to resolve (default theme) or notify of missing theme annotation for said class.

Now that the annotation usage has changed any NoTheme annotations for core classes should be removed as those are wrong for the new use case of the annotation.
