### ISSUE TITLE
Application fails to reload after change in code in 14.0.6

### ISSUE THREAD

**Issue by nemojmenervirat** [vaadin/flow#6531]
- Description of the bug
When you change anything in code (add space...) aplication fails to reload with exception `java.lang.IllegalStateException: webpack-dev-server port '52292' is defined but it's not working properly`. It happens only after you open application in browser. Prior to opening in browser you can change code and everything reloads fine. Everything works fine when I change back to 14.0.5.

- Minimal reproducible example
Download Spring Boot starter. Start application by running Application.java in Eclipse. Open in browser localhost:8080. Open Application.java and add space and save file.

- Expected behavior
Application reload successfully.

- Actual behavior
Application fails to reload with exception
`java.lang.IllegalStateException: webpack-dev-server port '52292' is defined but it's not working properly`

- Versions:
    - Vaadin / Flow version 14.0.6
    - Java version 1.8.0_221
    - OS version Windows 10
    - Browser version (if applicable) Chrome latest

**Comment by caalador** [comment]
Hi.
Sorry for this mistake, this should be fixed with https://github.com/vaadin/flow/pull/6528
We are currently running validation builds to verify that this doesn't 
kill webpack dev server too eagerly, but also doesn't leave instances running.

**Comment by nemojmenervirat** [comment]
Hi,
Mistakes happens :)
Thank you for information and for fast response on issue.

**Comment by pleku** [comment]
This should be fixed in 14.0.7 released today.
