### ISSUE TITLE
Converter JavaDoc/signature confusion

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#6571]
Every time I write a [`Converter`](https://github.com/vaadin/flow/blob/94fc280c3c176a2314b073711d6407cc192ac7af/flow-data/src/main/java/com/vaadin/flow/data/converter/Converter.java) I get much in confusion:

1. the JavaDoc on method `convertToModel` states:

> Converts the given value from model type **to presentation** type.

2. the JavaDoc on method `convertToPresentation` states:

> Converts the given value from presentation type **to model** type.

Should I trust the method name or the JavaDoc? 🤔

**Comment by ujoni** [comment]
The method names (and their return types) are correct. Thanks for the report!
