### ISSUE TITLE
Implement a new type of dependency which may be loaded dynamically

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#6577]
Part of this ticket: 
https://github.com/vaadin/flow/issues/6482

Add `Page:loadDependency` (or use some other method name) which accepts a JS String and has semantic similar to `executeJS`. It will require modifications on the server side, specific dependency type, modifications on the client side. 

The assumption for the method is: JS string returns a `Promise`.
This requirement needs to be forced somehow (check the return type on the client side, log an error at least on the client side and may be send this error to the server to throw an exception if the return type is not `Promise` ).

On the client side: 
- the dependency script should be executed as any other dependency , before executing anything else (no other message processing should be started before dependency is added).
- use `Promise`  and add an action when it's done to be able to postpone _ANY_ other executions (use `DependencyLoader` `startEagerDependencyLoading()/endEagerDependencyLoading()` methods to track when dependency is loaded).
- the above item guarantees that nothing will be executed until this dependency type is loaded.
- make GWT unit tests if possible for this functionality
- as said above: report (at least via error on the client side and preferable send a message to the server) if the return type of the JS expression is not `Promise` (throw on server in this case, add a unit test for this).

**Comment by mehdi-vaadin** [comment]
@denis-anisimov My understanding is that it's an internal method and we don't need to expose it to the user. Is it ok if I add it to `UIInternals` class?

**Comment by denis-anisimov** [comment]
That's a hard question.
At the moment there are no other usecases for this method. So it may be safely added to the `UIInternals` class for now.
There is a request from Leif about generic loader https://github.com/vaadin/flow/issues/6482#issuecomment-533163439.
But it doesn't say whether it should be a public or not.

Let's make it internal method for now and we may decide to expose it via `Page` later on via delegating to the `UIInternals` class call.
