### ISSUE TITLE
create a BootstrapHandler to IndexHtmlResponseHandler migration doc

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6584]
When migrating from a V10-14 app to V15 client-side bootstrapping I want to have docs describing how to replace the old API calls with the new ones so that I do not have to guess that from the API reference.

**Comment by haijian-vaadin** [comment]
already mentioned in https://vaadin.com/docs/v15/flow/typescript/upgrading-from-vaadin14.html
