### ISSUE TITLE
Only load the project flow-build-info

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#6616]
When loading the flow-build-info.json file in `DeploymentConfigurationFactory::readBuildInfo`
only the projects own build info file should be taken into account.

At the moment if the projects build info is missing the build info may be taken
from a add-on jar that has by mistake added it to the jar package.

**Comment by Legioth** [comment]
How can we know which one is the project's own?

**Comment by caalador** [comment]
That's the question that needs answering.
Would the URL resource contain full path data so we could check that the regex `".*file:(.+\\.jar).*"` doesn't match the result?... except that wouldn't then work when running a Spring fat jar
