### ISSUE TITLE
Accept setting data-provider of subclasses

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#6617]
Not sure if I'm missing some Java generics basics, but why it isn't possible to set a `DataProvider<Bar, ?>` to a `ComboBox<Foo>`, if `Bar extends Foo`?

In other words, can the signature of `HasDataProvider#setDataProvider` be changed from:

```java
void setDataProvider(DataProvider<T, ?> dataProvider);
```

to

```java
void setDataProvider(DataProvider<? extends T, ?> dataProvider);
```

? It would *really* simplify the codebase, since now I need a DP for every subtype I have.

**Comment by denis-anisimov** [comment]
Looks like the suggestion should work .

**Comment by knoobie** [comment]
@pleku can this be reopened and tagged with dataprovider as enchanment you mentioned in gitter? :)

**Comment by pleku** [comment]
@knoobie sure - but this is not a priority in itself and we will not break all data provider components just because of this. In case we need to make breaking things anyway, then we can include this too, but otherwise this is a secondary priority.

For any new added API, we will take this into account and not tie the type parameter like we did earlier.

**Comment by jhult** [comment]
Based on the DataProvider improvements that are being done in #8054, I'm not sure this is still relevant.

@pleku and @knoobie, any further thoughts here?

**Comment by pleku** [comment]
As now we went with _not breaking any existing data providers_ and partly _hiding the data provider as an abstraction level_ so one does not have use a data provider to set the data to the component (either in-memory or lazy). So while it is still fine to use data providers, it is not mandatory and thus I don't see this breaking change happening as it would further complicate things.
