### ISSUE TITLE
There is a pwa prompt button in the dom even in non-pwa apps

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow#6621]
The issue manifests for example with TestBench tests where you try to select a `<button>` from your test UI by tag name: `findElement(By.tagName("button"))`

Previously this query found the single button you had in the test UI. After some recent changes, it returns the `<button id="pwa-promptip">Install</button>` that seems to be in the dom even with non-pwa apps.

**Comment by denis-anisimov** [comment]
I cannot reproduce it with the `14.0.7` and also with `14.1-SNAPSHOT`.
I'm using https://github.com/vaadin/skeleton-starter-flow for this:
- checkout
- remove `@PWA`  annotation
- run the project
- check that there is no any `button` element in the DOM : `document.querySelectorAll('button')` returns an empty list.

So could you please provide steps to reproduce ?

**Comment by tomivirkki** [comment]
It used to reproduce with:
- Checkout vaadin-combo-box-flow
- mvn install
- Run `mvn jetty:run` under integration tests
- Open http://localhost:9998/set-items-later
- `document.querySelector('button')` used to return the problematic button

Now, with the latest dependencies it seems to work properly again 👍
