### ISSUE TITLE
Generated NPM packages files break the starter

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#6626]
Since this afternoon, the generated `package.json` and `package-lock.json` break some components.

To reproduce:

1. download a starter from https://vaadin.com/start
2. add a `PasswordField` to the main view
3. delete `package.json` and `package-lock.json`
4. run the app

What I get is:

<img width="288" alt="Screenshot 2019-10-04 at 18 51 28" src="https://user-images.githubusercontent.com/851745/66225150-03a54d00-e6d8-11e9-97d7-93a0cb5a6640.png">

Notice the unstyled `PasswordField`, but also `Select` is broken and others too.

**Comment by heruan** [comment]
Got it: it's `vaadin-themable-mixin` version 1.5.0, releases yesterday, who breaks the theming. Workaround: pin it at 1.4.4 with e.g.

```
npm install @vaadin/vaadin-themable-mixin@1.4.4
```

**Comment by lucastanzani** [comment]
Yeah, I noticed that too: https://github.com/vaadin/vaadin-text-field-flow/issues/234

**Comment by heruan** [comment]
Fixed in https://github.com/vaadin/vaadin-themable-mixin/releases/tag/v1.5.1
