### ISSUE TITLE
Listeners for attach/detach on Composites are not invoked

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#6628]
Listeners added to a `Composite` via `addAttachListener`/`addDetachListener` are not invoked when the component is attached/detached.

A workaround is to fallback to the Element API:

```java
composite.getElement().addAttachListener(myAttachListener);
composite.getElement().addDetachListener(myDetachListener);
```

**Comment by denis-anisimov** [comment]
Is it still an issue ?
I cannot reproduce this with the `master`  branch and with `2.2` .
Seems it's already fixed.

Could you please confirm , @heruan ?
