### ISSUE TITLE
Fallback imports may end up in normal import file when they should not (2.1.0.beta2)

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#6634]
If user runs `mvn ... -Ddevmode.optimizeBundle`, the generated fallback import file ends up in `/target/frontend`. Now, if the user runs the same command without cleaning and without the `-D` flag, the fallback import file will be included in `flow-generated-imports.js` as it is treated like an exported web component. 

Note: in compatibility mode, the exported web components are placed into a separate folder under `target/frontend`, but in npm mode, they are place directly into `target/frontend`.

**Comment by denis-anisimov** [comment]
The fallback file is excluded specifically if the full CP scanner is used when the main file is generated.
But this happens only when two scanners participate in files generation.
If only one scanner is used then only the main generated file is excluded.
Two ways of fixing:
- move the fallback to some other location
- change the logic which excluded the fallback generated file unconditional: the file should be always excluded using it's name (which is hardcoded).

I would go with the less error-prone way : the second one.
