### ISSUE TITLE
Missing comments on theming variants

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#6637]
All component theming variant enum items are missing comments. While most of them can be seen as self explaining, there are some that are not (for instance MenuBarVariant.LUMO_ICON). 

Beside that we should of course try to have our api docs as complete as possible :)

**Comment by pleku** [comment]
While the variants used to be generated by the component generator (which was in /flow repository), they are not generated anymore and are not considered to be part of Flow but the specific component integration where the variants also reside.

I'm closing this issue, but as I agree that there should be javadocs on the variants describing what those do, I'll let @tomivirkki and @alvarezguille that we have this issue.
