### ISSUE TITLE
Page reload speed is bad with 14.1-SNAPSHOT

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#6650]
Reloading page can take anything between 1 and 3 seconds when using 14.1-SNAPSHOT, or Flow 2.1-SNAPSHOTs. The timings have been taken with skeleton-starter.

**Development mode:**
![image](https://user-images.githubusercontent.com/45562391/66474501-1fbf3a80-ea9a-11e9-8563-ae5d17c24d0e.png)

DOMContentLoaded: 1.96s, Load: 2.1s

**Production mode:**
![image](https://user-images.githubusercontent.com/45562391/66474368-da027200-ea99-11e9-8fbf-652cdc5cb6b7.png)

DOMContentLoaded: 1.02s, Load: 1.1s

Content paint takes a long while in the development mode. Since development mode does not minimize the bundle in any way, it is slow to load.

**Comment by ujoni** [comment]
Using the latest build from master does not seem to have a tangible effect on the load times, either. So given a fresh environment, the loading seems to be around what is stated on the ticket.

**Comment by ujoni** [comment]
14.0.8 load times:

**Development mode:**
![image](https://user-images.githubusercontent.com/45562391/66476746-08368080-ea9f-11e9-92eb-c25c9bc81a2f.png)

DOMContentLoaded: 565ms, Loaded: 676ms

**Production mode:**
![image](https://user-images.githubusercontent.com/45562391/66476863-49c72b80-ea9f-11e9-8f8f-2e76643dcd30.png)

DOMContentLoaded: 444ms, Loaded: 533ms

**Comment by mehdi-vaadin** [comment]
After #6648 is merged, reload speed will be better. Load time for development mode will be:

![image](https://user-images.githubusercontent.com/32511762/66483606-18a22780-eaae-11e9-9ced-6024f862a44b.png)

DOMContentLoaded: 1.13 s, Load: 1.21 s

The main cause of the slowness was a `replaceAll` in `FrontendUtils.streamToString` [here](https://github.com/vaadin/flow/commit/d84e58c6b2d38bfeaaff88e3ae1268f91234e59c#diff-b197f606f3f72d13f6d8812de2eaf7d5R308) which takes a long time for a big file.
