### ISSUE TITLE
Retrieving VaadinSession in different ways gives a different result

### ISSUE THREAD

**Issue by markhm** [vaadin/flow#6666]
When trying to handover an object via the VaadinSession between two views, I have just witnessed the following in Vaadin 14.0.7.

**Variant A - Does not work (-> NoSuchElementException at session.getAttribute(..) )**
```
    // View A1
    VaadinSession session = getUI().get().getSession();
    session.setAttribute(MyObject.class, myObject);
    ....
    // View A2
    VaadinSession session = getUI().get().getSession();
    MyObject myObject = session.getAttribute(MyObject.class);
```

---------
**Variant B - Works as expected**
```
    // View B1
    VaadinSession session = VaadinSession.getCurrent();
    session.setAttribute(MyObject.class, myObject);
    ....
    // View B2
    VaadinSession session = VaadinSession.getCurrent();
    MyObject myObject = session.getAttribute(MyObject.class);
```
-------

macOS 10.15 Catalina (latest)
openjdk-13.jdk
Chrome (latest)

**Comment by denis-anisimov** [comment]
Could you please provide a code that I may use to reproduce an issue ?

I don't understand how `NoSuchElementException` can be thrown on `session.getAttribute`.
The exception class is used to throw an exception during iterations and `session.getAttribute` delegates to `HashMap`  and I can't see how it may happen.

You may use https://github.com/vaadin/skeleton-starter-flow to make a project which I may use to reproduce.
Or please provide at least the full stacktrace of the exception.

**Comment by markhm** [comment]
Thank you, Denis. I've just investigated a bit more and learned the following.

In my View (which extends `VerticalLayout`), I get the session via: `VaadinSession session = getUI().get().getSession();`

For `getUI()`, the result is `Optional<UI>`, but the `UI` is not available. 

`getUI()` tries to get the `UI` via `getParent()` and for some reason, the view is not attached at this time.

I note that try to get the session from within `beforeEnter(BeforeEnterEvent ..)`, but this is also the case when I get the session via `VaadinSession.getCurrent();`. As mentioned, all works well when I get the session via `VaadinSession.getCurrent();`

Does this provide enough info?

**Comment by denis-anisimov** [comment]
So the  `NoSuchElementException` is thrown when you call  `getUI().get()` (which has no any relation to the session and its attributes), right ?

There is no context in the code but I assumes you are calling this code inside some component constructor.

In this case it's expected that `getUI()` returns an empty `Optional` and it's not a bug.
You are making a wrong assumption that the component is attached when you construct it.
Component becomes attached only when it's attached to the tree ( so when it has a parent and its parent is also attached).
Only when the component is attached its method `getUI()` returns non-empty `Optional`.
To be able to get `UI` via `getUI` at the proper time you may call it inside `onAttach` method implementation of your component.
And if you need it to be called only once (like in CTOR, not on reattached) you should check the `AttachEvent::isInitialAttach`.

**Comment by markhm** [comment]
Thank you for elaborating. 

Note that I do not call this method in a component constructor, but in its implementation of `beforeEnter(BeforeEnterEvent..)`. I see now that the call order is: `constructor`, `beforeEnter(..)`, `onAttach(..)`, `afterNavigation(..)`. 

My use case is that before a user enters this particular view, I need to check if a certain data object is available. If not, I reroute to back another view.

My assumption that this was the correct way to do this was based on what I read in the first two lines of the [Routing Lifecycle / BeforeEnterEvent description](https://vaadin.com/docs/v14/flow/routing/tutorial-routing-lifecycle.html#beforeenterevent). It seems slightly less logical that a session is not yet available here, since quite often you would get this from the session, right...? Of course, I now note line three, where it is mentioned that the `BeforeEnterEvent` event is fired 'before .. attaching components'.

What caused confusion on my side - and was the reason for creating this issue - is that at the exact same place in `beforeEnter(..)`, I do get a correct session via: `VaadinSession.getCurrent()`. I did not look into it, but it trust this method attaches the component from which this is called somewhere underwater.

If you state all works as intended, let's not spend anymore time on it. At least I hope such feedback helps to understand the expectations of someone who is fairly new to the framework. Thanks again...! 

Please close after you have made any last comments.

**Comment by denis-anisimov** [comment]
>It seems slightly less logical that a session is not yet available here, since quite often you would get this from the session, right...

Yes and no.

`getUI()`  which is the cause of your issue is not about the session.
`getUI()` returns an empty `UI`  for the component because it's not attached yet.
The session is available at this point: you are right.
But you can't use `getUI().get().getSession`  to access it because of the reasons above.

Instead you should use the `BeforeEnterEvent`  which you have in your `beforeEnter` method.
The event has method `getUI()`  and it should return a `UI`  instance which you may use to access the session. In that way the session is available.

`getUI` in the component is a bit confusing, yes: it's bad when the getter method behavior depends  on an object state and returns different values . But this is a convenient method.
