### ISSUE TITLE
iOS 13 isn't properly detected on iPad

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow#6671]
```java
boolean ios = UI.getCurrent().getSession().getBrowser().isIOS();
add(new H1("ISIOS: " + ios));
```
This produces "ISIOS: true" on iOS 13 iPhone but "ISIOS: false" on iOS 13 iPad.
[Related fix to vaadin-grid](https://github.com/vaadin/vaadin-grid/pull/1671/files#diff-fa0c294fc77193488b21e163be2935a0L368-R369)

**Comment by blafoo** [comment]
The detection of the operation system relies on the user-agent reported by the browser.

For iOS 13 on the iPad it is:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15

So, with iOS 13 the different devices can't be distinguished any more. They are just "MacOSX"

**Comment by pleku** [comment]
Related to #6983

It seems that now we cannot even trust detecting `isIOS()` to get the value correct when an iPad with iOS 13 (or newer) is used.

So we should probably deprecate `isIOS` from `WebBrowser` and `BrowserDetails` and instead add the similar check as `vaadin-grid` has to `ExtendedClientDetails`.
