### ISSUE TITLE
make the flow-server dependency on Spring optional

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6701]
When creating a project with Vaadin 15 I do not want to automatically get a Spring dependency in my class path. If I do not have a Spring dependency in my project, I want all parts of Vaadin 15 to work just fine, except Vaadin Connect which requires Spring.

When using the `@VaadinService` annotation in a project that does not have a Spring dependency I want to get a build-time warning telling that this feature currently requires Spring, and that I should add a Spring dependency myself.

Implementation note: use the `<scope>provided</scope>` for all Spring dependencies added in https://github.com/vaadin/flow/pull/6672.

**Comment by Legioth** [comment]
> build-time warning

I would suggest a deploy-time warning instead since we have zero impact over the build in some peculiar situations like when someone imports a project into IDEA and launches the application through a `main` method or deploying it to a configured server without using Maven.
