### ISSUE TITLE
Print line number and template name in case of a parser error

### ISSUE THREAD

**Issue by paulroemer** [vaadin/flow#673]
The bigger the template, the more complicated it is to find the correct line causing the parser error. Please extend the exception output in something like

```
Caused by: java.lang.IllegalArgumentException: Unsupported node type: org.jsoup.nodes.Comment in <template name>:<line number>
```

**Comment by pleku** [comment]
Still valid but has not gained traction, thus closing.

Would be anyway recommend to use designer instead of hand crafting the templates, which should help with this (but not solve).
