### ISSUE TITLE
Path issue when configuring production build to use maven loaded yarn

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow#6730]
I configured project to download node and yarn with frontend-maven-plugin

https://github.com/TatuLund/devday-demo-flow/blob/master/pom.xml#L129

and

https://github.com/TatuLund/devday-demo-flow/blob/master/pom.xml#L218

This part works fine

Next step is to configure the vaadin-maven-plugin to use these 

https://github.com/TatuLund/devday-demo-flow/blob/master/pom.xml#L236

But yarn fails to execute due path issue

Hence I needed as workaround to configure custom yarn.cmd in project

https://github.com/TatuLund/devday-demo-flow/blob/master/pom.xml#L241

which contains absolute path to the command, see

https://github.com/TatuLund/devday-demo-flow/blob/master/yarn.cmd

My expectation was that no such tweak is needed in configuration

**Comment by caalador** [comment]
Is there a specific reason to install yarn using the `frontend` plugin?
Compatibility mode will use the `frontend` plugin to install node and yarn automatically.
The setting the path or autosearch is for when you have a preinstalled version that you want to use
or can't use the frontend plugin download.

**Comment by mcollovati** [comment]
Closing because compatibility mode is not supported anymore in the maintained Vaadin versions.
