### ISSUE TITLE
NullPointerException in ServerRpcHandler, getErrorHandler() returns null.

### ISSUE THREAD

**Issue by michallichvar** [vaadin/flow#6737]
https://github.com/vaadin/flow/blob/c81447b1c8ba476d6a205ea8aa23d542065d69ad/flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java#L383

throwable message: Serialized class sk.geneton.gims.frontend.remote.ServicesWrapper must implement java.io.Serializable
 field: sk.geneton.gims.frontend.views.RequestView.servicesWrapper
 field: sk.geneton.gims.frontend.views.RequestView$1.this$0

stack:
handleInvocationData:383, ServerRpcHandler (com.vaadin.flow.server.communication)
lambda$handleInvocations$1:359, ServerRpcHandler (com.vaadin.flow.server.communication)
accept:-1, 1675760724 (com.vaadin.flow.server.communication.ServerRpcHandler$$Lambda$948)
forEach:1249, ArrayList (java.util)
handleInvocations:359, ServerRpcHandler (com.vaadin.flow.server.communication)
handleRpc:301, ServerRpcHandler (com.vaadin.flow.server.communication)
synchronizedHandleRequest:87, UidlRequestHandler (com.vaadin.flow.server.communication)
handleRequest:40, SynchronizedRequestHandler (com.vaadin.flow.server)
handleRequest:1540, VaadinService (com.vaadin.flow.server)
service:246, VaadinServlet (com.vaadin.flow.server)
service:95, SpringServlet (com.vaadin.flow.spring)
service:750, HttpServlet (javax.servlet.http)
internalDoFilter:231, ApplicationFilterChain (org.apache.catalina.core)
doFilter:166, ApplicationFilterChain (org.apache.catalina.core)
invoke:712, ApplicationDispatcher (org.apache.catalina.core)
processRequest:459, ApplicationDispatcher (org.apache.catalina.core)
doForward:352, ApplicationDispatcher (org.apache.catalina.core)
forward:312, ApplicationDispatcher (org.apache.catalina.core)
handleRequestInternal:141, ServletForwardingController (org.springframework.web.servlet.mvc)
handleRequest:177, AbstractController (org.springframework.web.servlet.mvc)
handle:52, SimpleControllerHandlerAdapter (org.springframework.web.servlet.mvc)
doDispatch:1039, DispatcherServlet (org.springframework.web.servlet)
doService:942, DispatcherServlet (org.springframework.web.servlet)
processRequest:1005, FrameworkServlet (org.springframework.web.servlet)
doPost:908, FrameworkServlet (org.springframework.web.servlet)
service:665, HttpServlet (javax.servlet.http)
service:882, FrameworkServlet (org.springframework.web.servlet)
service:750, HttpServlet (javax.servlet.http)
internalDoFilter:231, ApplicationFilterChain (org.apache.catalina.core)
doFilter:166, ApplicationFilterChain (org.apache.catalina.core)
doFilter:53, WsFilter (org.apache.tomcat.websocket.server)
internalDoFilter:193, ApplicationFilterChain (org.apache.catalina.core)
doFilter:166, ApplicationFilterChain (org.apache.catalina.core)
doFilterInternal:99, RequestContextFilter (org.springframework.web.filter)
doFilter:109, OncePerRequestFilter (org.springframework.web.filter)
internalDoFilter:193, ApplicationFilterChain (org.apache.catalina.core)
doFilter:166, ApplicationFilterChain (org.apache.catalina.core)
doFilterInternal:92, FormContentFilter (org.springframework.web.filter)
doFilter:109, OncePerRequestFilter (org.springframework.web.filter)
internalDoFilter:193, ApplicationFilterChain (org.apache.catalina.core)
doFilter:166, ApplicationFilterChain (org.apache.catalina.core)
doFilterInternal:93, HiddenHttpMethodFilter (org.springframework.web.filter)
doFilter:109, OncePerRequestFilter (org.springframework.web.filter)
internalDoFilter:193, ApplicationFilterChain (org.apache.catalina.core)
doFilter:166, ApplicationFilterChain (org.apache.catalina.core)
doFilterInternal:200, CharacterEncodingFilter (org.springframework.web.filter)
doFilter:109, OncePerRequestFilter (org.springframework.web.filter)
internalDoFilter:193, ApplicationFilterChain (org.apache.catalina.core)
doFilter:166, ApplicationFilterChain (org.apache.catalina.core)
invoke:202, StandardWrapperValve (org.apache.catalina.core)
invoke:96, StandardContextValve (org.apache.catalina.core)
invoke:490, AuthenticatorBase (org.apache.catalina.authenticator)
invoke:139, StandardHostValve (org.apache.catalina.core)
invoke:92, ErrorReportValve (org.apache.catalina.valves)
invoke:74, StandardEngineValve (org.apache.catalina.core)
service:343, CoyoteAdapter (org.apache.catalina.connector)
service:408, Http11Processor (org.apache.coyote.http11)
process:66, AbstractProcessorLight (org.apache.coyote)
process:853, AbstractProtocol$ConnectionHandler (org.apache.coyote)
doRun:1587, NioEndpoint$SocketProcessor (org.apache.tomcat.util.net)
run:49, SocketProcessorBase (org.apache.tomcat.util.net)
runWorker:1142, ThreadPoolExecutor (java.util.concurrent)
run:617, ThreadPoolExecutor$Worker (java.util.concurrent)
run:61, TaskThread$WrappingRunnable (org.apache.tomcat.util.threads)
run:745, Thread (java.lang)

**Comment by caalador** [comment]
Have you set an error handler? as by default there should always be a `DefaultErrorHandler` set.

**Comment by michallichvar** [comment]
Hello
ErrorHandler was set to autowired bean in constructor, where was not yet
initialized, therefore null. I didnt know that when posting bug. My
mistake. But might happen.

Michal

Dňa št 24. 10. 2019, 7:56 caalador <notifications@github.com> napísal(a):
