### ISSUE TITLE
The frontend directory in the build directory is problematic

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#6749]
The Maven plugin creates a `package.json` and runs NPM, which creates a `package-lock.json`; these files should be versioned to ensure replicable builds, but this is problematic as they both contain references to the Maven build directory: the directory defaults to `./target`, but in some environments can be configured differently (for example in CI/CD runners).

As discussed in https://github.com/vaadin/flow/issues/6739, if the main reason for placing the `frontend` directory inside the build directory is to have it cleaned on `mvn clean`, this could also be achieved binding a plugin goal to the `clean` phase which deleted the `frontend` directory, even if placed in the project's root; similarly, such goal could also remove the `node_modules` directory.

**Comment by Legioth** [comment]
Would it be possible as a workaround to add `/target/` as a symlink to the actual build directory?

**Comment by heruan** [comment]
The workaround I'm using is not committing NPM files, so they are generated with the correct build directory; I prefer this for now than a symlink (for which I need to check which is the build directory first, not always easy).

**Comment by pleku** [comment]
Now starting from Flow 2.2.0.alpha7 and Vaadin 14.2.0.alpha2 (today/tomorrow), there should be no reference to `/target` in the package.json / package-lock.json or the pnpm-lock.yaml file.

I'm not sure what should be done with the `node_modules`, if you don't commit that folder (like you IMO should not), then it will be downloaded every time. With `pnpm`, I'm not sure if it will be able to cache anything as I'm not an expert on those and https://pnpm.js.org/en/continuous-integration doesn't elaborate. 
If you don't commit `package.json` and `pnpm-lock.yaml`, those will be regenerated, but I'm not sure how much that might have effect on having reproducible builds. I think it should be more stable than with just npm.

**Comment by heruan** [comment]
Thanks Pekka, I'll try 14.2 then. Of course `node_modules` shouldn't be versioned, but `package.json` and the lock file should and they no more contain references to build-time files it should work!

**Comment by pleku** [comment]
Ok. Also, I just want to warn that the pnpm support has some issues when installed locally (by Flow) #7183, so it might be still a bit rough ride, but it will be better early next decade.

**Comment by pleku** [comment]
I consider this now fixed in 2.2 where both _pnpm_ (default) and _npm_ will not have a second `package.json` file. There is only the one in project root. So there is no dependency to `/target` which is removed by `mvn clean`.
