### ISSUE TITLE
Deprecate MultiSelectionEvent.getNewSelection

### ISSUE THREAD

**Issue by pekam** [vaadin/flow#6756]
The class has three methods for the same thing:
```java
Set<T> getValue()
Set<T> getAllSelectedItems()
Set<T> getNewSelection()
```
The first two are inherited, but `getNewSelection` exists only in `MultiSelectionEvent`.

Another reason to deprecate it is that the naming can cause confusion. We got feedback that a user expected the method to return the newly added items (compared to the old selection), i.e. what `getAddedSelection` returns.

JavaDocs should suggest to use `getAllSelectedItems` or `getValue` instead.

**Comment by pekam** [comment]
Same should be done for Vaadin 8 as well: https://github.com/vaadin/framework/issues/11756

**Comment by pleku** [comment]
### Acceptance Criteria
- Deprecate the method as described above and claim that it will be removed in a later major version
- Recommend another method to use as described above
