### ISSUE TITLE
Production mode not recognized after building a prod package and running as standalone Spring Boot JAR

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow#6759]
did production mode build
DevModeHandler(?) fails on startup java.lang.RuntimeException: Unable to initialize Vaadin DevModeHandler
add -Dvaadin.productionMode when running the JAR, then it works.

that param is added in the production build maven conf, but not transferred to the actual running JAR...

**Comment by christian-ehmke** [comment]
Hi @tmattsso,

maybe our issues are related. In my case it is still not working. See https://github.com/vaadin/platform/issues/933

**Comment by caalador** [comment]
What project from which source?
Which platform version?

This most likely relates to https://github.com/vaadin/spring/issues/503 & https://github.com/vaadin/flow/issues/6657

**Comment by tmattsso** [comment]
I started from the Spring skeleton, platform 14.0.10

**Comment by caalador** [comment]
This issue should be ok in 14.0.11 (expecting spring to read the web.xml fragment)
Current workaround to get production mode jar is adding to `application.properties` `vaadin.productionMode=true`

**Comment by ujoni** [comment]
We need to add a `flow-build-info.json` to `flow-server-production-mode` to be able to tell apart situations where we are running in development mode without vaadin addon, but we depend on a addon built in production mode vs. situation where we are in fact in production mode, running a jarjar.

**Comment by caalador** [comment]
Well it's more like we need a known file that's always in a jar so we can see if it's positioned inside a jar or inside a jar inside a jar.
Feels like we might need the help of Dom Cobb or something.
