### ISSUE TITLE
Edge browser after refresh losing fonts

### ISSUE THREAD

**Issue by Aurimke** [vaadin/flow#6776]
Hi, we using Vaadin Flow 14.0.2 and in css having fonts setup:
@font-face {
font-family: 'Roboto';
src: url('fonts/Roboto-Regular.ttf');
}

Fonts are in folder: src/main/resources/META-INF/resources/fonts
Microsoft Edge 44.18362.387.0 after refresh can not find fonts. If refresh was done on page with path it is trying to search fonts in /path/fonts/... instead on /fonts.

**Comment by caalador** [comment]
Could you update the issue details with reproducible steps, also used versions.
Mnimal project that showcases the issue would also be good.

**Comment by Aurimke** [comment]
Hi, we using Vaadin Flow 14.0.2 and in css having fonts setup: 
@font-face {
    font-family: 'Roboto';
    src: url('fonts/Roboto-Regular.ttf');
}

Fonts are in folder: src/main/resources/META-INF/resources/fonts
Microsoft Edge 44.18362.387.0 after refresh can not find fonts. If refresh was done on page with path it is trying to search fonts in /path/fonts/... instead on /fonts.

**Comment by caalador** [comment]
Is this run in compatibilityMode or using webpack compilation?
Is the css loaded using `@StyleSheet` or inside a template?
The loading on a page with a path just means that there has been a navigation away from root path?

Could you try updating to 14.0.11 to see if the issue persists?

**Comment by Aurimke** [comment]
No, not in compatibilityMode. Jar with embedded tomcat (spring boot). The same with production build and dev.
Loaded using @CssImport on main layout.
Yes, if refreshing on root path then fonts working if navigating somewhere else and refreshing it is looking for fonts in wrong path.
I just tested with 14.0.10 and it has the same problem. (Other browsers not having this problem)

**Comment by caalador** [comment]
I can't get it to replicate. would you happen to have a simple project with the font css and 2 views that replicate the problem?

**Comment by Aurimke** [comment]
I can try to create simple project another day but I just now understand what problem is only with paths with path variables (movie/5).
root/movie - working
root/movie/5 - losing fonts (Only Edge browser)
root/movie?id=5 - working

P.S. We using HasUrlParameter<Long> implementation.

**Comment by caalador** [comment]
Have you tried with `src: url('/fonts/Roboto-Regular.ttf');` instead of `src: url('fonts/Roboto-Regular.ttf');`

**Comment by Aurimke** [comment]
Hi, thanks working with symbol "/".
