### ISSUE TITLE
14.1.0.alpha4 causes unexpected webpack logs bloat for n>1 startups

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#6779]
1) Using Bakery and  `14.1.0.alpha4`
2) run the app once with `spring-boot:run`
3) stop app
4) run again and again and get 700 lines of unexpected log bloat:
https://vaadin.slack.com/archives/C6RAXJATF/p1571917559172700?thread_ts=1571917544.172600&cid=C6RAXJATF

If you do a `clean spring-boot:run` then the bloat is gone.
There should not be this bloating of logging, we need to understand what is going on and fix it.

**Comment by caalador** [comment]
What versions of Java, npm, node?
Doesn't happen with
npm -v :: 6.9.0
node -v :: v10.16.3
java --version :: Corretto-11.0.4.11.1

**Comment by pleku** [comment]
node 12.13.0 (LTS)
npm 6.12.0
openjdk 11.0.4 2019-07-16

Apparently @martaolszewskatusiek had the same experience, don't know what version she had

**Comment by caalador** [comment]
Yes replicates after updating to latest node 12.13

**Comment by martaolszewskatusiek** [comment]
I had:
node: 10.16.0
npm: 6.9.0
jdk-12.0.1

**Comment by caalador** [comment]
Also windows all the way?

**Comment by martaolszewskatusiek** [comment]
Yes, Windows machine.

OS: Win10, 
IDE: Eclipse Version: 2019-03 (4.11.0), 
Browser: FF 69.0.3

**Comment by caalador** [comment]
Noted that Bakery is hardcoded to use flow-maven-plugin which is versioned as 2.0-SNAPSHOT
Did you notice to update the plugin to be vaadin-maven-plugin with the version 14.1.0.alpha4?

Haven't now been able to replicate bug in windows environment.

**Comment by martaolszewskatusiek** [comment]
I could not find 2.0-SNAPSHOT anywhere in my POM file. And I chaged the vaadin version to:
`<vaadin.version>14.1.0.alpha4</vaadin.version>`, since the original version was `<vaadin.version>14.0.7</vaadin.version>`

**Comment by caalador** [comment]
At least the latest master defines for me in the pom.xml on line 268
```
                <plugin>
                    <groupId>com.vaadin</groupId>
                    <artifactId>flow-maven-plugin</artifactId>
                    <version>2.0-SNAPSHOT</version>
                </plugin>
```
Also the plugin used should be vaadin-maven-plugin not flow-maven-plugin

**Comment by caalador** [comment]
And now it started to reproduce all the time...

**Comment by martaolszewskatusiek** [comment]
Unfortunately, I could not find the`flow-maven-plugin` anywhere in POM (I ended up doing Ctrl+F, since I could have overseen it). 
I downloaded the Bakery via vaadin.com/start webpage on Monday (28th Oct). It was with Vaadin version 14.0.7 originally.

**Comment by martaolszewskatusiek** [comment]
Re-tested Bakery with V14.1.0.alpha5. Webpack is very verbose:
```
![image](https://user-images.githubusercontent.com/48911718/67935285-2ee56400-fbd2-11e9-8d10-ce3896cc1030.png)
```

**Comment by martaolszewskatusiek** [comment]
One more attempt.

1. Removed node_modules and 4 other magical webpack / json files. 
2. Re run. 
3. Got very neat webpack log in the console.
4. App displays and runs in localhost:8080
5. Stop server
6. Iterate on steps 2-5. 

Could not reproduce the huge webpack output (even after restarting Eclipse and not removing node folder).

**Comment by pleku** [comment]
Cannot reproduce it anymore with `14.1.0.alpha5`

:godmode:  closing the issue for now
