### ISSUE TITLE
PushHandler::sendRefreshAndDisconnect does not cause detach event

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#6781]
When `sendRefreshAndDisconnect` is called on `PushHandler`, it does not raise `onDetach` event for UIs nor attached components. This can cause code which relies on `onDetach` to release resources to fail and cause memory leaks.

**Comment by denis-anisimov** [comment]
Could you please provide more info about this ?
What does `sendRefreshAndDisconnect` do ?

I see that it sends some response to the client side. This response includes an app error message.
Doesn't client initiate UI disconnect when it receives this message itself ?
Are you sure that the client doesn't do anything (in regards to response to the server side) on this message ?

**Comment by pleku** [comment]
My assumption is that if the client reacts to the disconnect message, sooner or later there will be heartbeats missed by the server and in the end the UI should be detached and garbage collected etc.

To my understanding, even normal server errors that cause a similar situation (critical error is shown in the UI), the UI is not detached immediately but instead later on.

Closing this issue as invalid.
