### ISSUE TITLE
If stats.json is not gotten in dev mode inform user where to check.

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#6785]
If in development mode stats.json or getStatsAssetsByChunkName can not be gotten from
webpack-dev-server then the exception shouldn't be a NPE but a custom exception
with a message informing the user where to check for the webpack output logs.

note also #6784

**Comment by pleku** [comment]
The error message should mention that 
a) in development mode, either webpack has not started or it hasn't output a template file that it is trying to find foobar.js
b) in production mode, should mention that something has gone in _what_ and maybe _why_ 

@caalador can you edit this message with better templates for the error messages ?

**Comment by caalador** [comment]
Template for case a) development mode the exception should note:
```
Webpack-dev-server couldn't be reached for the chunk name assets.
Check the startup logs for exceptions in running webpack-dev-server.´
If server should be running in production mode check that production mode flag is set correctly.
productionMode = {config.isProductionMode}, enableDevServer = {config.isDevServerEnabled}
```
b) calling this in  production mode should never happen and we are actually running in development mode
