### ISSUE TITLE
tsconfig is not generated in connect project

### ISSUE THREAD

**Issue by qtdzz** [vaadin/flow#6790]
tsconfig.json is not generated if the project uses the default generated `index.js` and has `@VaadinService`. The `.ts` services will be generated but if there is no `tsconfig.json`. Then TypeScript compiler could throw compilation errors while compiling the whole disk instead of only `frontend` folder.

**Comment by vlukashov** [comment]
Now the default is always `index.ts`, so this can be closed.
(changed in https://github.com/vaadin/flow/pull/7119)
