### ISSUE TITLE
Vaadin 14 BrowserDetails not work in iOS 13.2 on iPad

### ISSUE THREAD

**Issue by jreina2s** [vaadin/flow#6802]
Vaadin 14 BrowserDetails to detect the device for eg. no longer work in iOS 13.2

**Comment by mehdi-vaadin** [comment]
@jreina2s how can I reproduce this bug? What exact problem do you have? I tried the following code and it works correctly in iOS 13.2.2.
```Java
Button button = new Button("Click me",
        event -> {
            getUI().get().getPage().retrieveExtendedClientDetails(extendedClientDetails -> {
                System.out.println(VaadinSession.getCurrent().getBrowser().getBrowserApplication());
                System.out.println(VaadinSession.getCurrent().getBrowser().getBrowserMajorVersion());
                System.out.println(VaadinSession.getCurrent().getBrowser().getBrowserMinorVersion());
                System.out.println(VaadinSession.getCurrent().getBrowser().getAddress());

                System.out.println(extendedClientDetails.getBodyClientWidth());
                System.out.println(extendedClientDetails.getDevicePixelRatio());
                System.out.println(extendedClientDetails.getScreenWidth());
                System.out.println(extendedClientDetails.getWindowInnerWidth());
                System.out.println(extendedClientDetails.getWindowName());
            });
        }
);
add(button);
```

**Comment by jreina2s** [comment]
@mehdi-vaadin i tested following code:

`BrowserDetails details = new BrowserDetails(request.getHeader("User-Agent").toLowerCase());
if (details.isIPad()) {
	...
}`

That code not work with iPad

**Comment by mehdi-vaadin** [comment]
Thanks for the update. Apparently, the root cause is that the Request Desktop Website option for Safari is enabled for all websites by default in iOS 13 on iPad. See [this](https://stackoverflow.com/questions/58019463/how-to-detect-device-name-in-safari-on-ios-13-while-it-doesnt-show-the-correct). [This comment](https://stackoverflow.com/a/58064481/5613292) can be used to fix this issue.

**Comment by mehdi-vaadin** [comment]
With the Request Desktop Website option for Safari enabled for all websites, the `user-agent` header is the same for Safari on Mac and Safari on iOS. A workaround is to call `Page.retrieveExtendedClientDetails` to get `ExtendedClientDetails` and detect iOS based on `ExtendedClientDetails.isTouchDevice`. The complete workaround could be something like the following.
```Java
UI.getCurrent().getPage().retrieveExtendedClientDetails(extendedClientDetails -> {
    WebBrowser webBrowser = VaadinSession.getCurrent().getBrowser();
    if (webBrowser.isIPad() || (webBrowser.isMacOSX() && extendedClientDetails.isTouchDevice())) {
        add(new Paragraph("It's an iPad!"));
    } else {
        add(new Paragraph("It's not an iPad!"));
    }
});
```

**Comment by mehdi-vaadin** [comment]
### Acceptance criteria
- [ ] The `isIPad` method should be deprecated in all supported versions, 10, 14.0 and 14.1 
    - [ ] For 10 the deprecation message needs to warn that it will return the wrong value for iPad running ios13.
    - [ ] For 14.0 and 14.1 it should in addition point to `ExtendedClientDetails::isTouchDevice` that is needed for figuring out whether it is iPad or not. The right expression to check is `(isIPad() || isMacOSX() && isTouchDevice())`. See the workaround in the [previous comment](https://github.com/vaadin/flow/issues/6802#issuecomment-555031749).
- [ ] A disclaimer should be added to `WebBrowser` class that things there are not 100 % reliable
- [ ] `isIPad` method should be added to `ExtendedClientDetails` in Flow 2.2 and fix the deprecation message to use that instead for reliable detecting of the used device. (adding `navigator.platform` probably makes sense)
