### ISSUE TITLE
Please add iframe.reload()

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#6808]
I am implementing a webpage editor and the preview of the webpage in an iframe. I'd like to be able to reload iframe contents programatically whenever the editor contents change.

Please add `public void Iframe.reload()` method which would simply call `getElement().executeJs("this.contentWindow.location.reload()")`.

**Comment by pleku** [comment]
@mvysny just to make it clear:
a) the iframe will not work if the `src` is first empty and then set to a valid value ?
OR a) works but
b) the iframe will not work if the `src` is first empty and then set to a valid value and `...reload()` is called ?

**Comment by mvysny** [comment]
Hi, the latter one, b)

**Comment by pleku** [comment]
Interestingly, it seems that is how `<iframe>` behaves always, as can be tested here https://jsfiddle.net/bwjzkgeu/3/

So the proposed implementation above for `reload` method will not work if the `src` is set during the same roundtrip. We could check whether the `src` has changed before commiting the `executeJs`  call to the client side, but that requires quite a lot of non-trivial code to be added for such a obscure feature...

BUT, resetting the `src` attribute by the way seems to always cause the `<iframe>` to update, even when the value is the same. The thing just is that Flow will notice that the value has not changed and thus block the unnecessary change to client. So the following implementation could work:

```java
public void reload() {
    getElement().executeJs("this.src = this.src");
}
```
As the executeJS calls are always executed in the end after all other updates, the problematic case would only maybe cause extra blinking in the iframe if the developer does the _mistake_ of calling both `setSrc` and `reload()` during the same roundtrip. To avoid this, the javadocs for both methods should describe the behavior.

### Acceptance Criteria
- Introduce the method as described above, add unit and ITs to it
- Clarify the javadocs on `setSrc` that the value doesn't need to be reset but calling `reload()` should enough.
