### ISSUE TITLE
V14+ application doesn't work on Safari 10

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#6817]
## Steps to reproduce the bug
1) use any of our starters (tested with `skeleton-starter-flow`, `beverage-buddy` and `bakery`)
2) run `mvn clean jetty:run` and navigate to the view page

## versions for testing
Device: Ipad Air 2
Browser: Safari
OS: IOS 10.3.3
Vaadin Version: V14.0.0+ (V13 application is running correctly) 

### dev mode
![Image from iOS (2)](https://user-images.githubusercontent.com/31067185/68012367-80edbe80-fc92-11e9-94b4-770a6c8e4441.jpg)
![Image from iOS (3)](https://user-images.githubusercontent.com/31067185/68012376-864b0900-fc92-11e9-8191-a9cc110895f9.jpg)

### production mode
![Image from iOS (4)](https://user-images.githubusercontent.com/31067185/68012588-1ee18900-fc93-11e9-8bca-1f043858458e.jpg)
![Image from iOS (5)](https://user-images.githubusercontent.com/31067185/68012593-22751000-fc93-11e9-917e-f83b7b009e97.jpg)

## wild guess
polyfill is loaded correctly under npm mode.

**Comment by procterm** [comment]
We are also experiencing this problem on Vaadin 14.0.5, where Radio Buttons are not displayed on an iPad 2 running iOS 10.3.4.

**Comment by caalador** [comment]
Is this a problem with v14 compatibility and npm or only one of the modes?

**Comment by ZheSun88** [comment]
I don't think it is related to the compatibility mode. unless we use that mode for our starters by default.

**Comment by procterm** [comment]
We are not using compatibility mode.

**Comment by joheriks** [comment]
The scope of this ticket is to fix only for production mode, and not development mode using `webpack-dev-server`. As Safari 10 does not handle variable scopes correctly inside an `eval`, another `devtool` value than the default `cheap-module-eval-source-map` which uses `eval` must be set. If you are developing on Safari 10, you can pass e.g. `-d --devtool cheap-module-source-map` for the `devmode.webpack.options` servlet parameter (the default mode will not be changed as this increases webpack startup and redeployment time).
