### ISSUE TITLE
add support for 'magic' parameters in Vaadin Service methods

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6848]
When creating a `@VaadinService` method I want to access the metadata of the current request such as the user principal, the user roles, the request and response objects so that I can use that data in the method implementation: e.g. return the current user's name.

One way to get that access is to rely on static getters like `VaadinRequest.getCurrent()`:
```java
@VaadinService
public class HelloService {
    public String hello() {
        Principal principal = VaadinRequest.getCurrent().getUserPrincipal();
        return String.format("Hello, %s", principal.getName());
    }
}
```

Another way is to declare all dependencies as additional method parameters and rely on the Vaadin Connect request handler to provide them when the service method is invoked:
```java
@VaadinService
public class HelloService {
    public String hello(Principal principal) {
        return String.format("Hello, %s", principal.getName());
    }
}
```
NOTE: the generated TS code for both cases is the same, i.e. the additional parameters provided by the Vaadin Connect request handler are transparent for the client code.

There is a potential issue with overloaded methods. It would be possible to create two distinct methods in Java that would be mapped to the same method in TypeScript. That should be treated as a build-time error by the TS generator.
```
public String hello(Principal principal) {
    return String.format("Hello, %s", principal.getName());
}

public String hello() {
    return "Hello, anonymous";
}
```

DoD:
 - the following magic parameters are supported: `Principal` (more may be coming later)
 - the TS generator fails the build if there are overloaded methods with and without the magic parameters
 - the documentation is updated
    - there is a reference doc explaining what are magic parameters, which parameters are supported, and when can the build fail because of overloaded methods
    - there is an addition to the security 'how-to' page that shows how to implement a custom ACL rule based on an injected Principal instance

**Comment by haijian-vaadin** [comment]
Closing this one, in favor of #7488
