### ISSUE TITLE
Frontend dependencies have not been analyzed for <X>

### ISSUE THREAD

**Issue by mkn1988** [vaadin/flow#6850]
Following up thread [14+ NPM mode - com.vaadin.flow.component.internal.ComponentMetaData - Front](https://vaadin.com/forum/thread/17765421) in in the Vaadin Forum, the issue that frontend dependencies are not analysed for dynamic content still existst.

The problem:
Dynamically created components are not analysed for their dependencies, so that webpack might not send necessary javascript to the browser.
On the server (in development mode) the following message appears:

> Frontend dependencies have not been analyzed for com.vaadin.flow.component.textfield.TextField. To make the component's frontend dependencies work, you must ensure the component class is directly referenced through an application entry point such as a class annotated with @Route.

I created a minimum working example on [github](https://github.com/mkn1988/MWE_frontend_dependencies). Run it as a standard spring boot app, go to localhost:8080 and press the button.

Versions:
Vaadin: 14.0.12
Java: 1.8.0_212
OS: Windows 10 Enterprise
Browser: Chrome Version 78.0.3904.87 (64-Bit)

**Comment by ujoni** [comment]
Hi @mkn1988!

This problem should be resolved in our up coming 14.1 minor line. You can try `14.1.0.beta1` release from https://maven.vaadin.com/vaadin-prereleases/ to see, if that resolves your problem.

Unfortunately, the fix is not compatible with 14.0 maintenance releases.

**Comment by mkn1988** [comment]
Hi @ujoni 

True, the problem seems to be fixed in `14.1.0.beta1`.

Thanks for the quick resolution!
