### ISSUE TITLE
migration tool converts element>element selectors to element gt; element

### ISSUE THREAD

**Issue by voodoohoo** [vaadin/flow#6854]
```
   vaadin-tab.enable-rotation > .rotation-wrapper-outer > .rotation-wrapper-inner > .rotatable-label {
  ...
    }
```
becomes

```
    vaadin-tab.enable-rotation &gt; .rotation-wrapper-outer &gt; .rotation-wrapper-inner &gt; .rotatable-label {
	...
	}
```

**Comment by denis-anisimov** [comment]
Could you please provide the full source code which is affected?

Do you refer to the polymer template module  file or css file ?

Migration tool uses internally Modulizer . So it most likely a Modulizer bug. You may create a ticket there right away.

**Comment by voodoohoo** [comment]
**Before migration**

<pre>
<link href="shared-styles.html" rel="import">

<custom-style>
  <style>
    .tabsheet {
      padding: 0px 0px 0px 0px;
      margin: 0px 0px 0px 0px;
    }

    vaadin-tabs + .tabcontent,
     .tabsheet > .tabcontent {
      padding: 0px 0px 0px 0px;
      margin: 5px 0px 0px 0px;
      background-color: var(--lumo-shade-5pct);
      height: 100%;
    }

    vaadin-tab.enable-rotation {
      width: 3.5em;
      margin-bottom: 1em;
    }

    vaadin-tab.enable-rotation > .rotation-wrapper-outer {
      display: table;
    }

    vaadin-tab.enable-rotation > .rotation-wrapper-outer > .rotation-wrapper-inner {
      padding: 50% 0;
      height: 0;
    }

    vaadin-tab.enable-rotation > .rotation-wrapper-outer > .rotation-wrapper-inner > .rotatable-label {
      display: block;
      transform-origin: top left;
      transform: rotate(-90deg) translate(-100%);
      margin-top: -50%;
      white-space: nowrap;
      cursor: pointer;
    }
  </style>
</custom-style>
</pre>

**After migration**

<pre>
import './shared-styles.js';
const $_documentContainer = document.createElement('template');

$_documentContainer.innerHTML = `<custom-style> 
  <style>
    .tabsheet {
      padding: 0px 0px 0px 0px;
      margin: 0px 0px 0px 0px;
    }

    /* Wenn tabcontent direkt nach vaadin-tabs vorkommt */
    vaadin-tabs + .tabcontent,
    /* Wenn tabcontent wird über vaadin-tabs platziert */
     .tabsheet &gt; .tabcontent {
      padding: 0px 0px 0px 0px;
      margin: 5px 0px 0px 0px;
      background-color: var(--lumo-shade-5pct);
      height: 100%;
    }

    vaadin-tab.enable-rotation {
      width: 3.5em;
      margin-bottom: 1em;
    }

    vaadin-tab.enable-rotation &gt; .rotation-wrapper-outer {
      display: table;
    }

    vaadin-tab.enable-rotation &gt; .rotation-wrapper-outer &gt; .rotation-wrapper-inner {
      padding: 50% 0;
      height: 0;
    }

    vaadin-tab.enable-rotation &gt; .rotation-wrapper-outer &gt; .rotation-wrapper-inner &gt; .rotatable-label {
      display: block;
      transform-origin: top left;
      transform: rotate(-90deg) translate(-100%);
      margin-top: -50%;
      white-space: nowrap;
      cursor: pointer;
    }
  </style> 
 </custom-style>`;

document.head.appendChild($_documentContainer.content);

</pre>

Unfortunately the **'&gt;'** are also replaced within the code blocks (at least in the preview)
All **'&gt;'** element selectors are changed to **'>'**

**Comment by denis-anisimov** [comment]
I can see the styles file content from the original message.
But I would like to see the project structure and what should I do to see the described behavior.
So please either attach a project which I may use to reproduce the issue or use https://github.com/vaadin/skeleton-starter-flow project as a base and steps which I should use to modify it to get the behavior.

**Comment by voodoohoo** [comment]
I tried it with the old Vaadin-v12 BuddyApp sample but can't reproduce it anymore. The styles are  correctly converted now.

**Comment by denis-anisimov** [comment]
So can I close the ticket ?

**Comment by voodoohoo** [comment]
Yes, I think so. I also tried it with a v12 starter and I cannot reproduce it. :-/

**Comment by denis-anisimov** [comment]
OK, thanks.
