### ISSUE TITLE
Drop ES5 (IE11, old Safari) support in Flow 3.0+

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#6856]
As decided and explained here https://vaadin.com/blog/vaadin-14-is-the-last-major-version-to-support-ie11, Flow 3.0+ will not support IE11. 

What needs to be done for this:
- [x] Make sure that an app opened with IE11 & older Safari versions shows the "browser too old" page
  - Only newest major Safari version should be supported, anything less than that should go to Unsupported Browser page (regardless if newer versions support ES6)
- [x] Do not transpile client side to ES5
  - Drop extra babel dependencies
  - Drop any IFs in Java for checking if ES5 is supported
  - Drop any URL resolving related to ES5
  - Drop plugin-transform-block-scoping from webpack
- [x] Make sure docs do not mention anything specific to IE11 (or old Safari)
- [x] Do not run tests on IE11

**Comment by pleku** [comment]
According to https://caniuse.com/#feat=es6-module-dynamic-import we would need ES5 transpilation (or something else) to have dynamic import support for Safari 10. 

So this would mean that we don't support older Safari than 11.1, and we should drop the no-module polyfill https://caniuse.com/#feat=es6-module.

**Comment by pleku** [comment]
Also to clarify from #7244, currently the minimum supported Safari version ought to be 12.

**Comment by denis-anisimov** [comment]
IE11 tests have not been run against CCDM branch but they are removed anyway (so there is no anymore IE11 validation even in the master branch).

Done and done.
