### ISSUE TITLE
Allow TemplateRenderer to render HTML

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#6881]
Say that I have the following renderer in my Grid column:
```
TemplateRenderer.of("<span>[[item.preview]]</span> <button delete yadda yadda>").withProperty("preview", it -> it.someHtml())
```
I'd like the html to render as html; currently unfortunately the HTML is rendered escaped in the Grid column. Thanks!

**Comment by mvysny** [comment]
The only workaround I found is to use ComponentRenderer + Html which is slower than TemplateRenderer.

**Comment by web-padawan** [comment]
Here is a workaround available in Polymer to do this, mentioned in https://github.com/Polymer/polymer/issues/2320#issuecomment-156248429

```
<span inner-h-t-m-l="[[item.preview]]"></span>
```

**Comment by mvysny** [comment]
That is an awesome workaround, thank you. Actually I'd even consider this a solution; if you agree, please feel free to close this issue.

**Comment by web-padawan** [comment]
Closing per above comment and because it's how Polymer works (not really specific to Flow).
