### ISSUE TITLE
Improve formatting of generated variant sources

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#6882]
Currently the generated sources for GridVariant looks like this:

![Screenshot from 2019-11-08 08-47-33](https://user-images.githubusercontent.com/254091/68456510-a173c680-0206-11ea-9e69-3c63dc4f2980.png)

The formatting of generated sources looks super weird and is hard-to-read. Vaadin 14.0.12.

**Comment by pleku** [comment]
The generator is not used anymore. If you think it is worthwhile to fix the formatting for the file, you can just do it in the component integration repository.

**Comment by mvysny** [comment]
I'm sorry but I perceive this as quite arrogant. Yes I think it's worthwhile, and no, I have other things to do.
