### ISSUE TITLE
Hotswap Agent support for Vaadin 15

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6893]
When developing Vaadin 15 apps, I want to use [Hotswap Agent and DCEVM](https://github.com/HotswapProjects/HotswapAgent), so that I can see the changes I make to the Java code in the running app quicker (without the app restart).

There is a [Vaadin plugin](https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-vaadin-plugin/README.md) for Hotswap Agent, but it does not support Vaadin 15.

**Comment by haijian-vaadin** [comment]
Could this be closed now with our live reload feature from Flow?

**Comment by vlukashov** [comment]
After the https://github.com/HotswapProjects/HotswapAgent/pull/341 PR is merged, HotSwap Agent 1.4.1 supports Vaadin 14 and 15.

Related to https://github.com/vaadin/flow/issues/7792 and https://github.com/vaadin/flow/issues/7832.
