### ISSUE TITLE
Enable stats.json and build-info fallback chunks to be gotten from elsewhere

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#6902]
When wanting to run Flow projects as multimodule/microservice there should be a
feature that allows getting flow-build-info fallbackchunk data and needed information
from stats.json from another place/service.

The current build requires these to be in the classpath. The important parts that should be
enabled would be getting the assetChunks from stats.json (perhaps also template source?) and the "chunks" JsonObject from flow-build-info.json

The endpoint could be read from the flow-build-info.json so that for these project one could just add the flow-build-info.json file to `main/src/resources/META-INF/VAADIN/config/flow-build-info.json` with the contents:
```
{
  "compatibilityMode": false,
  "productionMode": true,
  "enableDevServer": false,
  "frontendData": 'some way to access frontend data'
}
```

This would also let us have the bundles built with the has as the bundle name would be served from data in stats.

**Comment by pleku** [comment]
Decided to continue by researching for how a configuration could help solve the automagic detection of frontend build output from another module.

```When building portlets/micro frontends, I don't want to rebuild frontend files in all modules, but instead just use the build data from the _bundle_ module by specifying a configuration, so that I don't have to read a lot of documentation on how to setup the build to manually copy files_

**Comment by pleku** [comment]
Went with the route of optimizing stats.json #6919 and then retrieving it via HTTP from the bundle portlet/micro frontend
