### ISSUE TITLE
Enable getting stats.json from an external service

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#6923]
There should be the possibility get `stats.json` from an external service (different war on same server).

This data should be read from the `flow-build-info.json` that if the property `externalStatsFile=true` or `externalStatsUrl="/my-location/stats.json"` is given would automatically put the flags: 
- productionMode=true 
- enableDevServer=false
- compatibilityMode=false

This will enable adding `src/main/resources/META-INF/VAADIN/config/flow-build-info.json` with the single configuration.

Giving the externalStatsFile we would check for the current host for a default package e.g. `{Host}/vaadin-static-files/VAADIN/config/stats.json`

Giving the externalStatsUrl we would use that as the stats file location so for a relative url `/my-stats/stats.json` we would use the current host and for `http://my-server.com/bundle/stats.json` we would use the full given URL

**Comment by pleku** [comment]
For now it would be fine to force the user to add the configuration to `flow-build-info.json`.
Later on we might have to enable setting this in another, more convenient, way.

**Comment by Artur-** [comment]
I found this by looking at the code. WHY should this be possible?

**Comment by caalador** [comment]
Portlets
