### ISSUE TITLE
Demo: Multimodule OSGi demo with dynamically enabled routes from another bundle

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#6937]
As part of #4853, we should have a demo that showcases the advantages of using Vaadin and OSGi:
- ~Vaadin components as declarative services~
- Dropping in/out routes dynamically from another bundle to a Vaadin application bundle where the navigation menu is updated automatically
- ~How the frontend resources bundle is built and deployed~
- ~How to setup live-reload of the bundles during development (IIRC should be possible)~

**Comment by alexweirig** [comment]
I agree, that would be great.

**Comment by JulianFeinauer** [comment]
Hi folks, I already created such a Demo (using Apache Karaf with Felix) in my Repo here: https://github.com/JulianFeinauer/vaadin-flow-karaf-example
So I am happy to contribute and work together with you guys.

**Comment by stbischof** [comment]
Would be nice to have a demo with plain osgi, just felix framework, scr (declarative services), and http, instead of karaf

Maybe the annotations like @Route could be be markt with
@ComponentPropertyType

```
@ComponentPropertyType
public @interface Props { 
int my_port() default 8080; // my.port property
} 
@Component
@Props(my_port=9080) 
public class ExampleImpl implements Example {
 …
}
```

**Comment by denis-anisimov** [comment]
The ticket mixes different functionalities which are not implemented at the moment.
So it can't be done at the moment.

**Comment by pleku** [comment]
The declarative services part and split frontend are not possible at the moment, can be demoed later if/when possible.
Adding routes from another bundle is now part of the Karaf base starter vaadin/base-starter-osgi-karaf.
