### ISSUE TITLE
remove flow.start() in favor of always using flow.serverSideRoutes

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6942]
There is one Flow JS API: flow.serverSideRoutes
There is no "compatibility" flow.start() JS API

Having a client side router means that we have extra round trips when ... (needs research).

DoD:
 - the flow.start() API method is removed from the Flow JS API
 - all usages of flow.start() in the code / tests / documentation should be removed

**Comment by platosha** [comment]
While implementing, we should make sure that the router outlet has `height: 100%;` style.
