### ISSUE TITLE
DataChangeEvent can't unregister its listener

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#6947]
`ComponentEvent`s have a useful `unregisterListener` method to be able to unregister themselves once invoked, but `DataChangeEvent` does not; it would be useful to set a "once" listener (not sure if there's another way to do it).

**Comment by denis-anisimov** [comment]
When you register a listener you get `Registration` instance to unregister it in both cases.
So there is already to unregister the listener , right ?

I personally find any listener related method in event class as a confusing design.
So `ComponentEvent::unregisterListener` is quite weird method for me.

But let's have it as an enhancement.

**Comment by Legioth** [comment]
The problem is usually that the listener callback cannot access the returned `Registration` without ugly workarounds such as assigning it to an instance field or wrapping it in an `AtomicReference<Registration>` or `new Registration[1]`.

**Comment by heruan** [comment]
@denis-anisimov the reason of having `ComponentEvent::unregisterListener` is what @Legioth has explained, e.g.

```java
button.addClickListener(event -> {
  // something to do only once
  event.unregisterListener();
});
```

but I can't do this in `DataProvider::addDataProviderListener`.

**Comment by pleku** [comment]
This issue is up for grabs, please make sure to read contribution guidelines before contributing https://github.com/vaadin/flow/blob/master/CONTRIBUTING.md

**Comment by torok-peter** [comment]
This is much more complex than a Good First Issue :-(
