### ISSUE TITLE
CCDM: ironListStyles can't be loaded 

### ISSUE THREAD

**Issue by qtdzz** [vaadin/flow#6948]
### Step to reproduce
1. Take `skeleton-starter-flow` branch `ccdm`
2. Add the following snippet to the `MainView` constructor
```
        IronList<String> ironList = new IronList<>();
        ironList.setHeight("100px");
        Stream<String> items = IntStream.range(0, 100)
                .mapToObj(i -> ("Item " + i));
        ironList.setItems(items);
        ironList.setId("ironlist");
        add(ironList);
```
3. Run the application with `mvn jetty:run -Pproduction`
4. Go to `http://localhost:8080`
### Actual
there is an error message in the console 
```
GET http://localhost:8080/frontend-es6/ironListStyles.css net::ERR_ABORTED 404 (Request was not handled by any registered handler.)
```

### Expected
No error as in npm mode

Edit: this only happens in `production` mode

**Comment by qtdzz** [comment]
My finding is that all the dependencies in V14 go through the `BootstrapUriResolver` which translates all the `frontend://` to `./frontend` (`com.vaadin.flow.server.BootstrapHandler.BootstrapPageBuilder#createDependencyElement`). In `ccdm` branch, usually we don't have `session` when creating the first HTML response so we can't reuse the same `BootstrapUriResolver`.
Possible solution:
 * it should be possible to provide a simple implementation of `VaadinUriResolver` to resolve url in bootstrap side
 * Or a simpler solution could be that changes the application configuration `com.vaadin.flow.shared.ApplicationConstants#FRONTEND_URL_ES6` to `frontend/` instead of the current `frontend-es6/`

**Comment by Artur-** [comment]
`frontend://` is related to Bower and should be removed as part of #6857
To me it looks like a problem with `IronList`: https://github.com/vaadin/vaadin-iron-list-flow/blob/master/vaadin-iron-list-flow/src/main/java/com/vaadin/flow/component/ironlist/IronList.java#L80-L90

The `ironListStyles.css` is listed below `BOWER MODE` and should never be used for npm. The styles come from `ironListStyles.js`: https://github.com/vaadin/vaadin-iron-list-flow/blob/master/vaadin-iron-list-flow/src/main/java/com/vaadin/flow/component/ironlist/IronList.java#L84

**Comment by ptdatkhtn** [comment]
In production mode, we have the same error in V14 when I create it dynamically, like this: 
```java
        NativeButton createIronList = new NativeButton("Create Iron List", event -> {
           IronList list = new IronList();
           list.setHeight("100px");
           list.setItems("Item 1", "Item 2", "Item 3");
           add(list);
        });
        add(createIronList);
```

One solution idea is to configure the client to always resolve frontend resources using the same `frontend/` prefix instead of `-es6`/`-es5` when in production npm mode, in `com.vaadin.flow.server.BootstrapHandler.ApplicationParameterBuilder#getApplicationParameters(com.vaadin.flow.server.VaadinRequest, com.vaadin.flow.server.VaadinSession)`:

```java
            if (productionMode && !deploymentConfiguration.isCompatibilityMode()) {
                appConfig.put(ApplicationConstants.FRONTEND_URL_ES6,
                        deploymentConfiguration.getDevelopmentFrontendPrefix());
                appConfig.put(ApplicationConstants.FRONTEND_URL_ES5,
                        deploymentConfiguration.getDevelopmentFrontendPrefix());
            } else {
                appConfig.put(ApplicationConstants.FRONTEND_URL_ES6,
                        deploymentConfiguration.getEs6FrontendPrefix());
                appConfig.put(ApplicationConstants.FRONTEND_URL_ES5,
                        deploymentConfiguration.getEs5FrontendPrefix());
            }
```
