### ISSUE TITLE
CCDM: TestBench timing checking functions not working 

### ISSUE THREAD

**Issue by qtdzz** [vaadin/flow#6949]
Our workaround for `waitForVaadin` function in Testbench is not enough for other timing checking functions. It requires more methods on `window.Vaadin.Flow.clients[client]` object while we only add `isActive()`.
The script for those functions resides in `com.vaadin.testbench.commands.TestBenchCommandExecutor#getTimingValues`

**Comment by haijian-vaadin** [comment]
This has been fixed.
