### ISSUE TITLE
dev-updater is run in production mode

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#6951]
Vaadin 14.1.beta1, Spring Boot starter

I built the application with 
`mvn clean package -Pproduction`

I then run the application with 
`java -jar target/<appname>.jar`

**Expected behavior:**
Application starts without running dev-updater

**Observed behavior:**
dev-updater starts

Running dev-updater requires node and npm, which means it's not possible to deploy the app to a production server without them.

**Comment by caalador** [comment]
14.1.0.beta1 contains Vaadin Flow (2.1.0.rc1) this issue is fixed in 2.1.0.rc2 (see #6657)
Test with beta2 or 14.1-SNAPSHOT if you are running a jar

**Comment by caalador** [comment]
Closing as fixed in pr's 6858 and 7060
