### ISSUE TITLE
Shortcut events triggered although lifecycleOwner's parent is not visible

### ISSUE THREAD

**Issue by onuridrisoglu** [vaadin/flow#7033]
Shortcut events are triggered as long as the component is visible and enabled.
However, if the parent component of lifecycleOwner is hidden, shortcut events are still triggered.
Here is a small code to generate the issue:
```Java
public MainView() {
        Button button = new Button("Click me",
                e -> Notification.show("Button is clicked"));
        button.addClickShortcut(Key.ENTER);
        VerticalLayout layout = new VerticalLayout(button);
        Button hideShow = new Button("Hide/Show");
        TextArea textArea = new TextArea();
        textArea.setVisible(false);
        hideShow.addClickListener(evt -> {
        	layout.setVisible(!layout.isVisible());
        	textArea.setVisible(!textArea.isVisible());
        });
        add(layout, textArea, hideShow);
    }
```

When `Hide/Show` button is clicked, the layout that contains the button is hidden.
Whenever enter key is pressed in textarea, the button click event is triggered.

Vaadin version: 14.0.14
Flow version: 2.0.18
Chrome version: 78

**Comment by mehdi-vaadin** [comment]
One workaround for this is to use `Shortcuts.addShortcutListener` instead of `Button:: addClickShortcut` to be able to change the `lifeCycleOwner` to `layout` like the following.

```Java
Shortcuts.addShortcutListener(layout, button::click, Key.ENTER);
```
