### ISSUE TITLE
Changing Routes of the application should work after compiling the class without restarting the server

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#7070]
When building apps, I want to be able to add new views to my app, and after compiling the (Java) code, be able to open them in the browser, without restarting the server.

### Acceptance criteria
- [x] It should work with `jetty-maven-plugin`
- [x] It should work with Hotswap agent
- [x] It should work with JRebel
- [x] It should work with `spring-dev-tools` for Spring apps
- [ ] ~It should work with Wildfly maven plugin for CDI apps~
- [x] It should work with TomEE maven plugin for CDI apps 
- [x] Deleting a route, adding a new route and renaming a route should be supported

*NOTE* If initial investigation indicates that any of the servers / tools require changes to make it work, create a new ticket explicitly for this.

**Comment by joheriks** [comment]
Live reload with Wildfly Maven plugin will most likely not be doable without updates to the plugin itself: https://issues.redhat.com/browse/WFMP-71.

**Comment by joheriks** [comment]
### Result of investigation

All tests by running the app via Maven from IntelliJ (with no additional plugins or non-default settings, except JRebel plugin which was enabled only for JRebel test).

#### Legend
**Add**: Adding a new view class with a unique `@Route` annotation. Test passes if the route is navigable.
**Update**: Change the value of the `@Route` annotation of an existing class, without renaming the class. Test passes if the new route is navigable.
**Delete**: Remove a `@Route` annotated class that is navigable. Test passes if route is no longer navigable.

| 					| Add			| Update		| Delete 		| Keep session |
|-|-|-|-|-|
| jetty-maven-plugin	| y				| y			| y			| n 			|
HotSwap agent (jetty)	| y †				| y †			| n			| y †			|
JRebel (jetty)			| y				| y			| y			| y			|
spring-dev-tools		| y				| y			| y			| y			|
CDI (TomEE)			| y				| y			| n			| y ❊		|

†) Works when running `mvn jetty.run` from IntelliJ, however, see issue with Hotswap Agent in general
❊) Serialization issue in CDI starter fixable by updating starter (https://github.com/vaadin/skeleton-starter-flow-cdi/issues/137)
