### ISSUE TITLE
NotFoundException better error handling

### ISSUE THREAD

**Issue by nemojmenervirat** [vaadin/flow#7071]
Maybe default error handler could provide more information when handling `NotFoundException`

Lets assume we have this class
```
public class ViewWithoutRouteAnnotation extends Div {
}
```
and we are trying to get its URL
```
@Route
public class MainView extends Div {
	public MainView() {
		RouteConfiguration.forApplicationScope().getUrl(ViewWithoutRouteAnnotation.class);
	}
}
```
Because class does NOT have `@Route` annotation `NotFoundException` is thrown. `RouteNotFoundError` class handles exception and in development mode we get: 
![image](https://user-images.githubusercontent.com/3105705/70014898-2939c000-157c-11ea-9737-b2dacf4453e5.png)
There is no exception logged in console.
In this example everything is clear. But if we have more code in constructor we don't know which line of code is causing problem.

 - Suggestions:

First in `RouteConfiguration`  in method `getUrlForTarget` add target class name. Existing code:
```
private String getUrlForTarget(Class<? extends Component> navigationTarget,
            RouteRegistry registry) {
        Optional<String> targetUrl = registry.getTargetUrl(navigationTarget);
        if (!targetUrl.isPresent()) {
            throw new NotFoundException(
                    "No route found for given navigation target!");
        }
        return targetUrl.get();
}
```
Suggested change:
```
throw new NotFoundException("No route found for navigation target " + navigationTarget.getName() + "!");
        
```

Second in `RouteNotFoundError` add logger. For example:
```
@Override
public int setErrorParameter(BeforeEnterEvent event, ErrorParameter<NotFoundException> parameter) {
		// existing code...
	log.error(parameter.getCaughtException().getMessage(), parameter.getCaughtException());
	return HttpServletResponse.SC_NOT_FOUND;
}
```

**Comment by caalador** [comment]
I think the intention is not to break the navigation so that you would get the no route error view.
I feel that the exception should be changed to `RouteNotRegisteredException` that would not be caught by the RouteNotFoundError view as that is not the correct exception view to show for this.

**Comment by bogdanudrescu** [comment]
When this is implemented we need to search all throws occurrences and update the javadoc.
