### ISSUE TITLE
remove the 5min delay in the Sonar step in CI builds

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#7077]
The CI builds in the `ccdm` branch of `flow` repo spend about 5 minutes in the 'Sonar' step, whereas in the `master` branch the same step takes under a minute. There should not be that large of a difference in how long it takes to run Sonar checks on the project between the branches.

See the build time breakdown here: https://docs.google.com/spreadsheets/d/1sF0G2eSvpUzKSmJPC6YQvV5tfcte-B6VoV5e_4tPPrI

DoD:
 - the root cause of the issue is described in a comment in this issue
 - the config is changed so that the Sonar step in the `ccdm` branch is as fast as it is in the `master` branch

**Comment by haijian-vaadin** [comment]
It can be closed now, as we are running in the master branch.

Didn't find any significant differences before and after the ccdm branch merge, both are around 2 and a half minutes.
