### ISSUE TITLE
optimise the forntend build time in V15

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#7078]
When building front-end code in Vaadin 15 apps I want that to take no longer than it takes in equivalent Vaadin 14 apps so that my experience as a developer does not get worse when I upgrade from V14 to V15. With Vaadin 15.0.0.alpha4 frontend builds take on average about 40 seconds longer (see the CI build time breakdown in https://docs.google.com/spreadsheets/d/1sF0G2eSvpUzKSmJPC6YQvV5tfcte-B6VoV5e_4tPPrI).

Implementation note:
One suspect for why in V15 frontend builds take longer than those in V14 is the fallback bundle and the TypeScript compiler that takes quite a while to process it (even though there is really no need to pass it through the TS compiler).

Implementation note 2:
Another idea to speed up flow CI builds is to run `npm install` in one of the IT projects before the build, and them sym-link the `node_modules` folder into the other IT projects. That may speed up the CI build since most ITs have the same npm dependencies.

DoD:
 - the root cause of the extra build time in V15 is described in a comment in this GH issue
 - the config is changed so that the front-end build time is not longer than in V14

**Comment by haijian-vaadin** [comment]
Close this issue in favor of https://github.com/vaadin/flow/issues/7596
