### ISSUE TITLE
Vaadin 14.0.14 compatibility problem with Safari on iPadOS 13

### ISSUE THREAD

**Issue by Matteo-gv** [vaadin/flow#7087]
With iPadOS i've a problem with application components. The same application, works well on Android and on Pc with Chrome 78.0 .
It seems something related with server authentication, i'm trying on Tomcat 9.0 with BASIC authentication.

[my-app.zip](https://github.com/vaadin/flow/files/3921147/my-app.zip)

![IMG_0049](https://user-images.githubusercontent.com/58481087/70131308-5cff0d80-1682-11ea-93da-d59c21a04f87.PNG)

**Comment by mehdi-vaadin** [comment]
@Matteo-gv thank you for reporting this issue. It seems that it's similar to #6817.

**Comment by Matteo-gv** [comment]
Are there any updates about this issue?

**Comment by joheriks** [comment]
The issue also occurs with Safari (13.0.3) on macOS  (Catalina).

**Comment by joheriks** [comment]
Same core issue as #6560.
