### ISSUE TITLE
Consider ignoring annotations on interfaces and abstract classes

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#7088]
Because of the restrictions in Spring Boot classpath scanning that caused https://github.com/vaadin/spring/issues/519, it could be considered to update our non-Boot logic to also ignore such cases so that we would reduce the risk of core functionality or add-ons that won't work with Spring Boot.

In practice, this would mean that we would ignore annotations from interfaces or abstract classes and only look at regular classes. We may still want to consider inherited annotations on regular classes, but for those cases we should first verify how Spring Boot currently works.

We cannot just stop supporting those cases right away since that may break existing (non-Boot) applications. Instead, we would have to start out by only logging a warning and then at some point start ignoring or throwing for such cases, potentially with a configuration flag for anyone who wants to explicitly keep using annotations on interfaces.

**Comment by knoobie** [comment]
See related spring ticket: https://github.com/spring-projects/spring-framework/issues/17399

**Comment by denis-anisimov** [comment]
Alright, thanks a lot for  information .
So we can actually fix this on Spring side instead of our side.

This suggestion should work : https://github.com/spring-projects/spring-framework/issues/17399#issuecomment-554685965

**Comment by Legioth** [comment]
Seems to work perfectly: https://github.com/vaadin/spring/pull/525. I don't see any purpose for this ticket any more.

Thanks again for making us aware of this possibility!
