### ISSUE TITLE
Upgrading from Vaadin 14.0.15 to 14.1.0: CSS style not applied

### ISSUE THREAD

**Issue by emattaboni** [vaadin/flow#7093]
**Issue:** CSS styles and template styles not applied in app using vaadin 14.1.0, works fine with Vaadin 14.0.15.

**Steps taken to upgrade app:**
- Upgraded version in POM: from 14.0.15 to 14.1.0
- Deleted node_modules, package*.json and webpack*.js
- Executed maven update on all modules of app

**More infos:**
Using spring-boot
CSS files are in "<app>/frontend/styles" folder
In main layout:

> ```
> @CssImport("./styles/style.css")
> @CssImport(value = "./styles/applayout-styles.css", themeFor = "vaadin-app-layout")
> ```
> Added `@JsModule(com.vaadin.flow.component.dnd.internal.DndUtil.DND_CONNECTOR)`

**Comment by juhopiirainen** [comment]
Thanks for the issue. I'll transfer this to the Flow team for investigations.

**Comment by mehdi-vaadin** [comment]
@emattaboni are you able to reproduce it? Can you share a minimal reproducible example?

**Comment by emattaboni** [comment]
Tried to reproduce but it works: my project is quite complex, I'll re-check on it.

Sorry for the false alarm :(

**Comment by mehdi-vaadin** [comment]
@emattaboni no problem at all. Maybe it's a corner case. Please keep us informed if you find something.
