### ISSUE TITLE
java.lang.Boolean-typed property with the name of isFoo() ignored by BeanPropertySet

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#7094]
Vaadin 14.0.12, JDK 8. This is actually a bug in JRE, so we will need to implement a workaround.

Take the following class:

```java
public class Foo {
    private Boolean foo;

    public Boolean isFoo() {
        return foo;
    }

    public void setFoo(Boolean foo) {
        this.foo = foo;
    }

    public static void main(String[] args) throws Exception {
        final BeanInfo beanInfo = Introspector.getBeanInfo(Foo.class);
        final PropertyDescriptor iprop = Arrays.stream(beanInfo.getPropertyDescriptors()).filter(it -> it.getName().equals("foo")).findFirst().get();
        System.out.println(iprop.getReadMethod());
        System.out.println(iprop.getWriteMethod());

        final PropertySet<Foo> propertySet = BeanPropertySet.get(Foo.class);
        final PropertyDefinition<Foo, ?> prop = propertySet.getProperty("foo").get();
        System.out.println(prop);
    }
}
```

This code will print:

```
null
public void com.vaadin.starter.skeleton.Foo.setFoo(java.lang.Boolean)
Exception in thread "main" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.vaadin.starter.skeleton.Foo.main(Foo.java:35)
```

The reason is that Java Introspector will errorneously print null as `iprop.getReadMethod()`, which will cause the BeanPropertySet to ignore this field. We need to implement a workaround for this into BeanPropertySet which will properly discover the `isFoo()` getter.

Curiously, using the primitive `boolean`-typed field causes Java Introspector to magically start working:

```java
public class Foo {
    private boolean foo;

    public boolean isFoo() {
        return foo;
    }

    public void setFoo(boolean foo) {
        this.foo = foo;
    }

    public static void main(String[] args) throws Exception {
        final BeanInfo beanInfo = Introspector.getBeanInfo(Foo.class);
        final PropertyDescriptor iprop = Arrays.stream(beanInfo.getPropertyDescriptors()).filter(it -> it.getName().equals("foo")).findFirst().get();
        System.out.println(iprop.getReadMethod());
        System.out.println(iprop.getWriteMethod());

        final PropertySet<Foo> propertySet = BeanPropertySet.get(Foo.class);
        final PropertyDefinition<Foo, ?> prop = propertySet.getProperty("foo").get();
        System.out.println(prop);
    }
}
```

Will print:

```
public boolean com.vaadin.starter.skeleton.Foo.isFoo()
public void com.vaadin.starter.skeleton.Foo.setFoo(boolean)
com.vaadin.flow.data.binder.BeanPropertySet$BeanPropertyDefinition@6aa8ceb6
```

I've got the standard OpenJDK8 installed on my Ubuntu 19.10;
```
$ java -version
openjdk version "1.8.0_232-ea"
OpenJDK Runtime Environment (build 1.8.0_232-ea-8u232-b09-0ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```

**Comment by Legioth** [comment]
It's arguable whether this is a bug. The `isXyz` naming convention is explicitly defined only for `boolean` but not for `java.lang.Boolean`.

**Comment by denis-anisimov** [comment]
Just for the record : I'm not sure (and perhaps I even think) that this is not a bug neither in Flow nor in JRE.

I think it works according to Java bean spec.
If I'm not wrong spec says that getter for `boolean` should starts with `is`.
And it doesn't say that this is applicable for `Boolean` .

`Boolean` != `boolean`   for sure.
Because `Boolean`  can be `null`  (and this is an object) .
`boolean` is primitive and can't be `null` .

So for me at least everything is according to spec.

This ticket is more expectation than a bug. And I'm not sure that the expectation is correct.

**Comment by mvysny** [comment]
@denis-anisimov I think the `is` prefix was used because it resembles the English syntax more (`isPretty()` vs `getPretty()`), not because of nullability.

> The isXyz naming convention is explicitly defined only for boolean but not for java.lang.Boolean.

@Legioth I agree. My expectation was otherwise, but it is true that the Bean Spec is clear: `is` for primitive `boolean` only. Could be something that could be improved in the spec perhaps, but that's definitely a different battleground there.

Quoting spec at https://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/

> In addition, for boolean properties, we allow a getter method to match the pattern:public boolean is<PropertyName>();

With this I conclude that it's a possible omission in the spec, not a bug in Introspector or Vaadin. I propose to close this issue, since it's working according to the spec.

**Comment by mvysny** [comment]
For reference, it is easy to hit this with Kotlin & syntetic getters: https://youtrack.jetbrains.com/issue/IDEA-25268
