### ISSUE TITLE
enable live-reload in dev mode both for TS and Java changes

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#7101]
When running a Vaadin 15 app in the dev mode, I want the browser page to reload automatically after I change some front-end resources or some Java classes so that I can stay in the IDE and see the browser window opened alongside to refresh every time I save changes / rebuild the project.

Vaadin 14 used to have the webpack Live Reload server enabled, but it caused race conditions: https://github.com/vaadin/flow/issues/5688.

Note:
Spring DevTools include a LiveReload server out-of-the-box (running on by default). However it only detects changes to static resources and Java classes. It does not detect when webpack re-runs front-end builds.

In scope of this task:
 - create a solution that works for Spring Boot projects (with Spring DevTools)
 - explore to see how that could work without Spring DevTools. Share some thoughts on this in the ticket comments:
    - when there is no automatic servlet container restarts, i.e. live-reload is triggered only be webpack rebuilds
    - with Jetty, i.e. live-reload is triggered both by webpack and by Jetty servlet container restarts
    - with JRebel, i.e. live-reload is triggered both by webpack and by JRebel class hot reload
    - with HotSwap Agent and DCEVM, i.e. live-reload is triggered both by webpack and by HotSwap Agent class hot swap
    - with the WildFly Maven plugin

**Comment by joheriks** [comment]
Fixed with #8875
