### ISSUE TITLE
move the remaining docs pages from Connect to Vaadin

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#7112]
The following docs pages from the Connect repo should be adoped to the Vaadin 15 documentation:
 - [x] [Vaadin Connect Exceptions](https://github.com/vaadin/vaadin-connect/blob/master/doc/vaadin-connect-exceptions.asciidoc)
 - [x] [Generating TypeScript wrappers for `@VaadinService` Java classes](https://github.com/vaadin/vaadin-connect/blob/master/doc/typescript-generator.asciidoc)
 - [x] [Vaadin Connect TypeScript client](https://github.com/vaadin/vaadin-connect/blob/master/doc/default-client.asciidoc)
 - [x] [Vaadin Connect client middleware](https://github.com/vaadin/vaadin-connect/blob/master/doc/client-middleware.asciidoc)
 - [x] [Vaadin Connect validation in the service methods](https://github.com/vaadin/vaadin-connect/blob/master/doc/service-methods-validation.asciidoc)

**Comment by ptdatkhtn** [comment]
- need to add docs for Vaadin Connect maven plugin (https://github.com/vaadin/vaadin-connect/blob/master/doc/vaadin-connect-maven-plugin.asciidoc) and mention it in  Vaadin Connect TypeScript client page
