### ISSUE TITLE
Dragging disabled components is possible visually

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7114]
As reported in comments for https://vaadin.com/docs/v14/flow/dnd/drop-target.html#drop-target-styling

The client side should check if the dragged element is disabled and not allow drag to start in such case.

**Comment by joernBee** [comment]
Joern
In my opinion ... Why should a disabled component not be draggable?

Pekka Hyvönen
To be honest, it was my first instinct as a developer that I would expect that a user should not be able to interact with disabled component in the UI.

I asked around, and > 90 % of our developers shared my opinion. This is actually different from how just an disabled element behaves in the browser, and even different from how it works in Framework version 8, and nobody has opened an issue about this there (!).

It would be very confusing that the user can see the drag and drop happen in UI even when component.setEnabled(false) has been called, but in the code on the server doesn't react to this. Another aspect is that there might be scenarios where the developer expects that this is how it works, but it does not and then the user can do things that should not be possible.

Hi Pekka
I agree totally that the visual behaviour and the internal representation should match!
