### ISSUE TITLE
Investigate whether X-Atmosphere-Transport=close request is necessary

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#7120]
Based on https://vaadin.com/forum/thread/17855707/vaadin-10-14-logout-with-push-relogin-redirects-to-vaadinservlet, it seems like there's a `X-Atmosphere-Transport=close` request being sent to the server after closing the push connection.

This request may get caught in a login filter and cause unexpected side effects if it's sent after the user has logged out. We should investigate whether it's actually necessary to send this request in situations when the session is expired.

**Comment by Artur-** [comment]
This is ignored by the saved request filter nowadays and should not cause any problems
