### ISSUE TITLE
Typed text is discarded in Lazy mode with timeout

### ISSUE THREAD

**Issue by tulioag** [vaadin/flow#7128]
In an input or text field with lazy value change mode, a timeout and a value change listener that takes some time to execute, some typed characters are discarded.

* Code example:
Given the following input
```java
		final Input input = new Input();
		input.setValueChangeMode(ValueChangeMode.LAZY);
		input.setValueChangeTimeout(500);

		input.addValueChangeListener(event -> {
			try {
				Thread.sleep(1000);
			} catch (InterruptedException e) {
				throw new RuntimeException(e);
			}
		});
```
* Actual behavior: If you type some characters, pause for a moment and type some more, the characters typed after the pause are discarded
![input-issue](https://user-images.githubusercontent.com/28783969/70605154-972c5a00-1c02-11ea-97d3-4ec1f0f5e326.gif)

* Expected behavior: No characters are removed from the input.

* Versions
```
[INFO] +- com.vaadin:vaadin:jar:14.1.2:compile
[INFO] |  +- com.vaadin:vaadin-core:jar:14.1.2:compile
[INFO] |  |  +- com.vaadin:flow-server:jar:2.1.1:compile
```
* Tested on: 
   * Chromium on Linux, JDK 8
   * Also reproduced for text-field in https://github.com/vaadin/vaadin-text-field-flow/issues/209 in Windows, JDK 11, Firefox and Chrome

Related to https://github.com/vaadin/vaadin-text-field-flow/issues/209

**Comment by heruan** [comment]
I confirm, adding that it happens also with the default timeout (i.e. not setting any timeout explicitly). This, unfortunately, landed on our production app and we're getting numerous reports.

**Comment by anasmi** [comment]
Marking this as BFP, since original issue is closed in favor of this one https://github.com/vaadin/vaadin-text-field-flow/issues/209
