### ISSUE TITLE
Javascript and CSS files inside jar modules not loading in Vaadin 14.1 (npm mode)

### ISSUE THREAD

**Issue by igormilina** [vaadin/flow#7129]
- Description of the bug
I have multi module maven project using Spring Boot, packaged as a war. In development, `"mvn  clean process-resources"` is executed before project is run from within IDE.
In one of my jar modules I have custom component with `@JavaScript(value = "./js/commons.js")`. When run with Vaadin 14.0.4 javascript file is successfully loaded in browser.
But, when upgraded to Vaadin 14.1.2, javascript file is never loaded. No other change was made to the project.

- Expected behavior
Javascript defined using class annotation `@JavaScript(value = "./js/commons.js")` should be loaded in both 14.0.4 and 14.1.2.

- Actual behavior
In 14.1.2 javascript file is never loaded.

- Versions:
    - Vaadin / Flow version: 14.1.2
    - Java version: 11
    - OS version: Win10
    - Browser version (if applicable): tested in latest Chrome and Firefox

My current workaround is to put: `UI.getCurrent().getPage().addJavaScript("./js/commons.js", LoadMode.EAGER);` in my custom component's constructor. Using this, javascript file is loaded as expected (with 14.1.2).

In this forum thread is reported that `@JsModule` has similar problem loading in 14.1, so it could be the same issue: https://vaadin.com/forum/thread/17986666/17986667

**Comment by igormilina** [comment]
Unfortunately, @CssImport(value = "./styles/commons.css") placed on custom component is affected also, the css file is not loaded.

I have found that this problem (not loading js and css) is present ONLY when custom component and its resources (js and css) are inside jar module. When I move custom component and its resources into main war, everything works like a charm. Resources in jar are located according to docs, in "src\main\resources\META-INF\resources\frontend\" folder. But as I said before, this setup worked in 14.0.4, so that should be ok. But in 14.1.2, for some reason, resources that are not inside main war (in "frontend" folder) are not loaded.

I also noticed that js and css that were not loaded are not present in "generated-flow-imports.js" file. To be more precise, those files are present after first log:
`INFO dev-updater - Updated D:\projects\idea\svjedodzbe\svjedodzbe\svjedodzbe-web\target\frontend\generated-flow-imports.js`

but they are gone after second log:
`INFO  dev-updater  - Updated D:\projects\idea\svjedodzbe\svjedodzbe\svjedodzbe-web\target\frontend\generated-flow-imports.js`

generated-flow-imports.js is updated twice during application startup, once before vaadin servlet is started and once after it has started. Second update seems to remove more than it should?

**Comment by caalador** [comment]
Hi.

The double execution is not yet fixed as we haven't come up with how we can know that the 
`ServletContainerInitializer` has executed already, but the collection of resources got a change in 14.1.3 that should at least make the found packages the same as for the first run making the second execution skip npm install and webpack compilation.

**Comment by igormilina** [comment]
I have tested my issue with 14.1.3 and generated-flow-imports.js are indeed the same for both runs.

I also had one bug, in my "vaadin.whitelisted-packages" list I didn't propertly targeted UI classes inside my jar. This somehow worked 14.0.4, but not in 14.1. So this whole issue was error on my side.
Closing as invalid.
