### ISSUE TITLE
Components inside a Grid not properly detached

### ISSUE THREAD

**Issue by fheckl** [vaadin/flow#7143]
Since I cannot reopen #5610 I am creating a new issue here but the problem I have is the same:

Steps to reproduce:
* Create a Grid component with a component column that does not create new components but instead tries to reuse created components
* Attach the grid to a container
* Replace the container content with something different
* Re-attach the Grid to the container

**Result**: Exception with message "Trying to detach an element from parent that does not have it." (AbstractNodeStateProvider:123)

The problem in my opinion is that when replacing the Grid with different content the component column children are not properly detached from their parents. To phrase it a little more precisely: they are detached from the parent, but their parents are not set to null because the children think they are already detached.

Possible bug fix:
```
diff --git a/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java b/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
index 8e6f968563..de100cc4c8 100644
--- a/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
+++ b/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
@@ -242,6 +242,7 @@ public class StateNode implements Serializable {
      */
     public void setParent(StateNode parent) {
         if (hasDetached()) {
+            this.parent = null;
             return;
         }
         boolean attachedBefore = isRegistered();
```

Here is the link to a simple app demonstrating the behavior: https://gitlab.com/fheckl/vaadinsample

**Comment by fheckl** [comment]
You may have already seen it in the pom.xml of my sample project, but anyway: this bug was found with Vaadin version 14.1.2.

**Comment by fheckl** [comment]
Please note: I just pushed new content to the repo mentioned above because I included code for possible bug #7152 but nothing changed in regard to the issue here.

**Comment by caalador** [comment]
This is not a valid issue in that the JavaDoc explicilty notes that it should be a new instance
```
     * ... ComponentRenderer that uses the componentFunction to
     * generate new {@link Component} instances...
     *
     * @param componentFunction
     *            a function that can generate new component instances
```
So from the framework point of view the usage is wrong as the function should always return a new component.

To use an existing component through the function you could go the route:
```
grid.addColumn(new ComponentRenderer<>(item -> {
  Button button = buttonMap.get(item);
  button.getElement().removeFromTree();
  return button;
}));
```
Which will disconnect the item and make it seemingly reusable.

**Comment by fheckl** [comment]
Thanks @caalador for clarifying what we are apparently doing wrong. Using your proposed method of re-using the button fixes the problem.
I will forward it to the appropriate team members since we have our own special layer in between Vaadin and the final app and the component creation and rendering is done in that special layer. They will then have to identify the necessary changes.
Closing the issue for now. If we have any other issues that we think are wrong on your side, I will just reopen this issue.
