### ISSUE TITLE
Component inside a Grid becomes unusable after removeAll and readding

### ISSUE THREAD

**Issue by fheckl** [vaadin/flow#7152]
This may be related to issue #7143 but has a slightly different effect.

How to reproduce:

- Again we have a button inside a Grid. The Grid lives inside a container. 
- The button's action triggers a refresh of the container whereby we remove all of the container's content using removeAll. 
- Then the same grid with that same button instance is immediately re-added to the container along with some other content

Expected behavior: the button works just as it did before.

Actual behavior: the button is still present, but clicking it will have no effect with a warning "Got an RPC for non-existent node: xy" being logged to the terminal console (not the browser console).

Sample code is available at https://gitlab.com/fheckl/vaadinsample in file Problem2.java
 
- Versions:
    - Vaadin / Flow version: 14.1.2
    - Java version: 1.8
    - OS version: macOS 10.15.2
    - Browser version (if applicable): Chrome 79.0.3945.79

**Comment by fheckl** [comment]
After reading @caalador 's comment to the related issue (https://github.com/vaadin/flow/issues/7143#issuecomment-565385615) I tried to apply the proposed solution to this problem as well but even creating the button completely new in the component creator function does not solve it.

**Comment by caalador** [comment]
The main problem is that the button in the grid is seen as a already instantiated on the server and for this reason doesn't seem to re-add it on the client in the response. 
A workaround, while we are investigating what can be done, would be to reset the dataCommunicator:
```
        button.addClickListener(clickEvent -> {
            grid.getDataCommunicator().reset();
            panel.removeAll();
            panel.add(grid, textBelow);
        });
```

**Comment by caalador** [comment]
On the other hand we again have the issue of reusing the button that should always create a new instance, so changing the code to be:
```

    VerticalLayout panel;
    Paragraph textBelow;
    Grid<SimplePojo> grid;

    private Component createLayout() {
        panel = new VerticalLayout();

        textBelow = new Paragraph("When you click the button again, 'Got an RPC for non-existent node' will be logged!");
        grid = new Grid<>(SimplePojo.class);

        grid.addColumn(new ComponentRenderer<>(pojo -> getButton()));
        grid.setItems(Collections.singletonList(new SimplePojo("Dan", 55)));
        grid.setHeightByRows(true);

        panel.add(grid);

        return panel;
    }

    private Button getButton() {
        Button button = new Button("I will only work once");
        button.addClickListener(clickEvent -> {
            System.out.println(button.getElement().getNode().getId());
            panel.removeAll();
            panel.add(grid, textBelow);
        });
        return button;
    }
```
Will make the button work each click as a new instance is populated to the grid.
The main problem for this issue is that when reattaching during same roundtrip we do not refresh data to the client as nothing should have changed, but in this instance the re-used button is not resent, where as if the button is regenerated the button will be sent to the client after each click. and the button will get a new node id.

**Comment by fheckl** [comment]
> On the other hand we again have the issue of reusing the button that should always create a new instance, so changing the code to be:
> ...
> Will make the button work each click as a new instance is populated to the grid.
> The main problem for this issue is that when reattaching during same roundtrip we do not refresh data to the client as nothing should have changed, but in this instance the re-used button is not resent, where as if the button is regenerated the button will be sent to the client after each click. and the button will get a new node id.

@caalador :
I just tried this myself and did not seem to get your second code example working using only the code you mentioned. For me, the button only works on each click if I combine the example with resetting the data communicator in the button's event click handler (as shown in your first example). Otherwise the component creator function is not called again.
I tried with both the original Vaadin version of the issue (14.1.2) as well as the current 14.1.4 and got no difference in behavior.

**Comment by caalador** [comment]
Hi.

You are right. I must have tested against the "broken" snapshot where i always sent all the data again to the client.

So the two correct ways would either to reset the datacommunicator or to not detach and attach the grid on the same roundtrip.

**Comment by fheckl** [comment]
Thanks for all your explanations. 

We will use the workaround with resetting the data communicator for now.
