### ISSUE TITLE
[PUSH] Vaadin 14.1.x PUSH with websocket is slow

### ISSUE THREAD

**Issue by letrthang** [vaadin/flow#7166]
- Description of the bug:
While Push (with websocket enable) in Vaadin 14.1.x is more stable than previous versions. Now it becomes very slow on establishing the connection between server and browser causing pages loading slow. 

- Versions:
    - Vaadin version: 14.1.x
    - Java version: 11
    - OS version: Linux
    - Browser version (if applicable): Chrome 78

**Comment by caalador** [comment]
Could you add a sample project with expectations for different page load times.

**Comment by letrthang** [comment]
any project that enables PUSH.
just measure time from:
"_Vaadin push loaded_"
to:
"_Establishing push connection_."

![image](https://user-images.githubusercontent.com/13396193/71123226-2a761880-221d-11ea-83dc-5a5c421a886e.png)

**Comment by caalador** [comment]
Well there has to be something special in the application as at least my times are around 1-2s and not close to 22s as in your screenshot
```
Vaadin push loaded

Setting heartbeat interval to 300sec.

Scheduling heartbeat in 300 seconds

Starting application ROOT-2521314

Vaadin application servlet version: 2.1.2

Handling message from server

Handling dependencies

StateTree after applying changes:

{pushConfiguration: {…}, elementData: {…}, clientDelegateHandlers: Array(0), polymerServerEventHandlers: Array(0), synchronizedPropertyEvents: Array(0), …}

handleUIDLMessage: 2 ms

First response processed 1744 ms after fetchStart

Processing time was 23ms

Establishing push connection
```

**Comment by letrthang** [comment]
did you run on prod mode or dev mode ?

**Comment by caalador** [comment]
I ran it in development mode with springBoot embedded tomcat and had the same times for both websocket and websocket_xhr transports.
The whole application load time was ~1.5s in development mode and for production mode I'm getting a load time of ~300ms

**Comment by letrthang** [comment]
you run it on localhost ?

**Comment by caalador** [comment]
Yes. development builds are usually on localhost. My server is for some reason not responding throuhg anything except ssh at the moment so I can't test the deployment there

**Comment by letrthang** [comment]
ok, i am running our app on the AWS. what i observed that vaadin 14.0.x is faster than 14.1.x.

**Comment by caalador** [comment]
Now that I got the server to answer the timings are close to the same as for local host.
My server is an installation of debian 8 running tomcat 9

**Comment by letrthang** [comment]
maybe this is our server problem. because we have a load balancer also. i will close this issue.
Thank so much for your testing.

**Comment by letrthang** [comment]
Hi caalador

after you opened page, could you reload that page again and see vaadin push Establishment time ?

**Comment by caalador** [comment]
There's no change in the connection 800ms-1.3s in devmode and 300ms in production is what I'm getting at the moment.

**Comment by letrthang** [comment]
caalador, thanks so much for the support. i will close this issue

**Comment by allenvpn312** [comment]
I can confirm push 14.1.3 is slower than the 14.0.x version.  It seems push behavior is more unstable on version 14.1.x than 14.0.x.
