### ISSUE TITLE
BitBucket pipeline build error

### ISSUE THREAD

**Issue by corbettcode** [vaadin/flow#7167]
We have just migrated to Vaadin 14 and trying to build a production version in a BitBucket pipeline which now generates the error: "Failed to execute goal com.vaadin:vaadin-maven-plugin:14.1.2:prepare-frontend (default) on project onerev-app:". I can build and run both profiles (development and production) on my development system without error. The problem occurred when we were on Vaadin 14.1.1. We upgraded to see if it would resolve the problem.

I'm including part of the POM file in case we have done something wrong:

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <dotGitDirectory>${project.basedir}/../.git</dotGitDirectory>
                    <prefix>git</prefix>
                    <verbose>false</verbose>
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties
                    </generateGitPropertiesFilename>
                    <format>properties</format>
                </configuration>
            </plugin>

            
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                
                <version>1.8.0</version>

                <executions>
                    <execution>
                        
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        
                        <phase>generate-resources</phase>
                    </execution>
                </executions>
                <configuration>
                    <nodeVersion>v12.13.1</nodeVersion>

                    
                    

                    
                    
                </configuration>
            </plugin>
            
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <excludes>
                    <exclude>META-INF/persistence.xml</exclude>
                </excludes>
            </resource>
        </resources>
    </build>

    <profiles>
        <profile>
            <id>development</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.vaadin</groupId>
                        <artifactId>vaadin-maven-plugin</artifactId>
                        <version>${vaadin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>prepare-frontend</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>pl.project13.maven</groupId>
                        <artifactId>git-commit-id-plugin</artifactId>
                        <version>3.0.0</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>revision</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <dotGitDirectory>${project.basedir}/../.git</dotGitDirectory>
                            <prefix>git</prefix>
                            <verbose>false</verbose>
                            <generateGitPropertiesFile>true</generateGitPropertiesFile>
                            <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties
                            </generateGitPropertiesFilename>
                            <format>properties</format>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>production</id>
            <properties>
                <vaadin.productionMode>true</vaadin.productionMode>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>com.vaadin</groupId>
                    <artifactId>flow-server-production-mode</artifactId>
                </dependency>
            </dependencies>

            <build>
                <plugins>
                    <plugin>
                        <groupId>com.vaadin</groupId>
                        <artifactId>vaadin-maven-plugin</artifactId>
                        <version>${vaadin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>prepare-frontend</goal>
                                    <goal>build-frontend</goal>

                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
                <resources>
                    <resource>
                        <directory>src/main/resources</directory>
                        <excludes>
                            <exclude>application-development.yml</exclude>
                            <exclude>sample-application-development.yml</exclude>
                        </excludes>
                    </resource>
                </resources>
            </build>
        </profile>
    </profiles>

**Comment by caalador** [comment]
So production mode prepare-frontend fails, but development mode prepare-frontend doesn't fail in the pipeline? Could you give a bit more of the logs around the exception.

**Comment by pleku** [comment]
ping @corbettcode ^ please without some logs we cannot really advance on this issue and will have to close it. My guess would be that some checks done by `prepare-frontend` would be failing in the CI system, maybe the `npm` version check ?

One workaround for the issue might be to put the files generated by `prepare-frontend` to VC where the CI server can get them.

**Comment by mehdi-vaadin** [comment]
@corbettcode I'm closing this issue. You can create a new issue with more info to help us find the problem. You can also add the required info here and we will reopen the issue.
