### ISSUE TITLE
improve the DX of adding polyfills: WC and other

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#7173]
When creating an app with Vaadin 15+ I do not want to see polyfills nor think about polyfills until later in the development life cycle, so that I can focus on the app functionality first and worry about how to make the app working for _all_ supported browsers later. At the same time, I would like to stay assured that the topic of polyfills is covered, and I _can_ look into it in more details when needed.

The current V15 approach is to
 - add the loader for Web Components polyfills into every `index.html` example in the docs
 - also add it into the default `index.html` file generated by the frontend build pipeline
 - not really have any examples for how to add any other polyfills

This DX is not ideal because
 - the developers are forced to copy / paste a code snippet that they are not sure yet if they really need. That looks and feels like boilerplate code that just gets in the way.
 - when the developers need to add another polyfill (e.g. for the [ResizeObserver API](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)), Vaadin does not guide them in doing that

DoD:
 - Check the apps created with `npm init react-app my-react-app`, `ng new my-angular-app` and `vue create my-vue-app` to see what developer experience do they offer in regards to polyfills.
 - Design the changes needed in the polyfills-related DX in Vaadin (open one or several issues).

**Comment by haijian-vaadin** [comment]
This ticket can be closed since we don't need polyfill any more.
