### ISSUE TITLE
Improve DX with auto-importing generated TS service wrappers

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#7176]
When calling a Java method from TypeScript code through Vaadin 15, I want the auto-imports feature of my IDE to work after I typed the first few letters of the Java **class name**, so that I do not have to scroll to the top of the file and add an import there first, before auto-completion starts working for me.

With Vaadin 15.0.0.alpha8 the situation is that auto-imports do work for Java **method names**, not for **class names** (because all methods in the generated TS service wrappers are exported individually, and there is no TS symbol that matches a Java class name). That is the result of the decision done in https://vaadin.slack.com/archives/CDNTYMS9H/p1545049736011300.

A better DX would be if auto-completion and auto-imports work both with Java class names and Java method names:

```java
@VaadinService
public class UserService {
    public User getCurrentUser() {
        return new User("my-name");
    }
}
```

 - type `UserS` in TypeScript and press `Cmd`+`Space` to have the IDE to add an import for `import {UserService} from './generated/UserService.js';`
 - type `getCurr` in TypeScript and press `Cmd`+`Space` to have the IDE to add an import for `import {getCurrentUser} from './generated/UserService.js';`

**Comment by haijian-vaadin** [comment]
Need to export an object in addition to the individual methods.

**Comment by haijian-vaadin** [comment]
Per [Slack discussion](https://vaadin.slack.com/archives/CDNTYMS9H/p1612515667171000), there was another opinion to use object name pattern, i.e. `userService` instead of `UserService`. In the end, the class has more votes, the benefits being that it matches the Java class name and it matches the endpoint file name.
