### ISSUE TITLE
Vaadin Connect Controller can not resolve default endpoint name if subclass proxies are used

### ISSUE THREAD

**Issue by TomRauchenwald** [vaadin/flow#7205]
Vaadin Version: 15.0.0.alpha9
Spring Version: 2.2.1.RELEASE

VaadinConnectController does not determine the correct endpoint name for a `@VaadinService` if the bean is proxied with CGLIB (e.g. by using `@Transactional`).
 
This is my Endpoint:
```
@VaadinService
public class MessageSchemeEndpoint {
    private final MessageSchemeRepository messageSchemeRepository;

    @Autowired
    public MessageSchemeEndpoint(MessageSchemeRepository messageSchemeRepository) {
        this.messageSchemeRepository = messageSchemeRepository;
    }

    @Transactional
    public List<MessageSchemeDto> list() {
        return messageSchemeRepository.findAll(Sort.by(Sort.Order.asc("schemeId")))
                .stream()
                .map(messageScheme -> new MessageSchemeDto(messageScheme.getSchemeId(), messageScheme.getSchemeShortName(), messageScheme.getDescription(), messageScheme.getImageId()))
                .collect(Collectors.toList());
    }
}
```
In VaadinConnectController, in validateServiceBean(), this resolves the name of the proxy:
![image](https://user-images.githubusercontent.com/15888440/71170915-c70bdb00-225c-11ea-9d2f-ffac284247be.png)
Since the client uses the name of the class, the lookup of the service fails in `serveVaadinService():
![image](https://user-images.githubusercontent.com/15888440/71173281-8f079680-2262-11ea-9530-ca31ab482b62.png)
```
export function list(): Promise<Array<MessageSchemeDto>> {
  return client.call('messageSchemeEndpoint', 'list');
}
```

There's `ProxyUtils.getUserClass(beanType)` to retrieve the unproxied type in spring, perhaps that can help.

Setting the service name via `@VaadinServlet("serviceName")` doesn't work either, because `beanType.getAnnotation(VaadinService.class)` can't find the annotation on the proxy. Spring's `AnnotationUtils.findAnnotation(beanType, VaadinService.class)` might work here.

**Comment by vlukashov** [comment]
This is now fixed in Flow 3.0-SNAPSHOT / Vaadin 15.0-SNAPSHOT.
Will be released as Flow 3.0.0.alpha13 / Vaadin 15.0.0.alpha10.
