### ISSUE TITLE
local installation of pnpm does not work on Travis

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#7206]
This is more an investigation rather than a bug ticket

currently, don't know the exact issue here: 
- probably can be related with `non-preinstall-pnpm` environment 

### step to reproduce
Take `platform/14.2`, remove the `npm install -g pnpm` from travis configuration file (https://github.com/vaadin/platform/blob/master/.travis.yml).

**Comment by ZheSun88** [comment]
It looks this is an issue with Travis only. 
Tested with a windows laptop which has never run `pnpm` and our starter can be started correctly. 
ticket closed.

**Comment by caalador** [comment]
Closing issue as there has been lots of changes to this part. Reopen as new ticket if issue still persists.
