### ISSUE TITLE
Lots of missing npm packages errors when pnpm 3.8.1 is globally installed

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#7219]
Running `mvn install` on a 15 alpha 10 project results in errors like
```
Error: Cannot find module 'mkdirp'
Require stack:
- /.../project-folder/webpack.generated.js
- /.../project-folder/webpack.config.js
```

```
pnpm --version
3.8.1
```

If there is a minimum version of `pnpm` required, there should be a version check like with `npm`

Upgrading globally installed pnpm to 4.0.0 resolves the issue

**Comment by pleku** [comment]
I presume that when the pnpm version is checked and it is too old, it has been installed globally. As any local installation should have been done by the framework, and it should be already a supported version. I find it hard to believe anyone would have a reason to have a certain pnpm version installed locally for the project (14.0 or 14.1) and would not want us to just update it.

I think it is better if we don't fail the build and just install a working pnpm version locally and log something like this to the console:
```
Detected a global install of pnpm version <version_here>, which is not supported.
Installing supported version <supported_version> locally for this project.
We recommend you to update your global pnpm installation with the following command:
npm install -g pnpm
```
Optionally if we require a certain version but not the newest, then add it to the command in the console ^.

**Comment by Artur-** [comment]
Sounds even better to install a newer version in the project
