### ISSUE TITLE
Add method to get the latest known complete url

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow#7238]
Currently you can get url via Router, but it does not include domain name, context path, etc.

It is possible to obtain the full url from the browser via JavaScript call, like

`this.getElement().executeJs("return window.location.href;").then(fullurl -> System.out.println(fullurl.asString()));`

However, this method is async, and not applicable for all use cases.

This feature request is also motivated by the observation that synchronization via future.get() does not work, the following will halt the server

```
     future = this.getElement().executeJs("return window.location.href;").toCompletableFuture();
     try {
         fullUrl = future.get().asString();
     } catch (InterruptedException | ExecutionException e) {
     }

```

**Comment by TatuLund** [comment]
Just found the original request for the feature: https://github.com/vaadin/flow/issues/1897

**Comment by pleku** [comment]
I don't understand how this issue differs from #1897, so closing this one.
