### ISSUE TITLE
Investigate running on servers for plain servlet projects in IntelliJ IDEA

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#7301]
Test that _Run/Debug in IntelliJ IDEA_ works for the following servers (Run/Debug configurations) with 14.2-SNAPSHOT:
- Jetty
- Tomcat

In case some server cannot be run from IntelliJ, it should be documented to _Development Workflow_ section. We should check if the server/IntelliJ combination supports live reload, and mention this in the documentation.

**Comment by pleku** [comment]
Doesn't work and to be fixed https://github.com/vaadin/flow/issues/7448
