### ISSUE TITLE
Investigate running on server for CDI projects in Eclipse

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7302]
Test that Run on Server in Eclipse/Debug on Server works for following EE servers with 14.2-SNAPSHOT:

- TomEE
- WildFly 18
- RedHat JBoss EAP 7
- Oracle WebLogic Server 12.2.1
- IBM WebSphere Application Server 8.5 Liberty Profile and 9 (or whatever you can download and install via Eclipse)

In case some server cannot be run from Eclipse, it should be documented to Development Workflow section. We should check if the server/Eclipse combination supports live reload, and mention this in the documentation.

**Comment by denis-anisimov** [comment]
TomEE: completely broken for me. I'm not able to run skeleton cdi app on TomEE via `Run on Server` at all.
Here is a long description of this issue : https://github.com/vaadin/flow/issues/7386.
The behavior in this ticket is initially discovered with Tomcat but I was able to get rid of it somehow for plain skeleton.
For CDI skeleton and TomEE it happens for me every time (Tom EE is registered as a Tomcat server).
So I can't get working skeleton app at all.

**Comment by denis-anisimov** [comment]
Wildfly : issue is created. The application is started though the directory used for `npm install` is wrong.
But there are not routes.

JBoss EAP7: the directory is wrong again.
```
Created webpack configuration file: /Users/denis/EAP-7.2.0/bin/webpack.config.js
16:59:51,620 INFO  [dev-updater] (ServerService Thread Pool -- 73) Updated /Users/denis/EAP-7.2.0/bin/target/frontend/generated-flow-imports.js
17:00:02,041 INFO  [dev-webpack] (ServerService Thread Pool -- 73) Starting webpack-dev-server, port: 59632 dir: /Users/denis/EAP-7.2.0/bin
```

And same as Widlfy routes issue :  `Skipping automatic servlet registration because there are no navigation targets registered to the route registry and there are no web component exporters`.

**Comment by denis-anisimov** [comment]
Web Sphere Liberty: I haven't seen any messages from dev server and `npm install` in the console.
But the result is similar to JBoss and Wildfly : 
```
Error 404: SRVE0190E: File not found: /
```
And there is a message :
```
INFO com.vaadin.flow.server.startup.ServletDeployer - Skipping automatic servlet registration because there are no navigation targets registered to the route registry and there are no web component exporters
```

**Comment by denis-anisimov** [comment]
Couldn't add Web Logic server to Eclipse.

**Comment by denis-anisimov** [comment]
@pleku , should I close the ticket ?
