### ISSUE TITLE
Add Element.setProperty(String, Object) for any bean

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#7307]
There should be a `setProperty` method which takes any bean as the value. Calling e.g.
```
getElement().setProperty("i18n", myTranslations);
```
should be able to populate a component `i18n` object correctly. 

If you have a Person bean like
```
public class Person {
private String firstName, lastName;
private int age;
// setters + getters
}
```
then
```
setProperty("person", myPerson);
```
should be equal to
```
setProperty("person.firstName", myPerson.getFirstName());
setProperty("person.lastName", myPerson.getLastName());
setProperty("person.age", myPerson.getAge());
```
except that the whole object value is set once on the client side.

**Comment by Legioth** [comment]
Some open questions to understand the boundaries of this feature:
* `setProperty(String, Object)` will cause some ambiguity with the existing `setProperty(String, String)` method. Would it make sense to use a custom name, similarly to the existing `setPropertyJson` method?
* What should the various `getProperty` methods return for a property that is set in this way?
* Should it be possible to define that some of the sub properties should be ignored, renamed or serialized in some custom way?

**Comment by Artur-** [comment]
The name is not that important to me at least, `setPropertyBean` is fine

I have no idea what `getProperty` returns today if you set a bean to a property and synchronize it. If they try to cast to JS equivalents, then probably like JS would do it.

It would probably be benficial if the existing `@Include/@Exclude` annotations worked also here so there is one common way of converting a bean to JSON.

**Comment by Legioth** [comment]
The `getProperty` methods that cast to JS equivalents are quite easy. The tricky one is `getPropertyRaw` - should it return the original object or a `JsonValue` representation of it? This gets even more interesting if you change the value in the bean after calling `setProperty` (either before or after the client response has been sent).
```
element.setProperty("person", myPerson);
myPerson.setFirstName("Bob");
updatebutton.addClickListener(event -> myPerson.setFirstName("Jack"));
```

Should `getPropertyRaw` return something that reflects the values that have been sent to the client or should it return the `Person` instance that is no longer in sync with the client-side property value?

**Comment by Legioth** [comment]
I'm actually quite sure the name should be something like `setPropertyBean` in order to clarify expectations if passed (built-in) value objects that are not bean-like, e.g. `java.util.Date`.

**Comment by Artur-** [comment]
When you set a bean as a property, I would assume it gets converted to JSON internally. The case of changing the bean values is quite clear as you are not binding the property to the bean, you are setting the property value to the current bean values

**Comment by Legioth** [comment]
With that interpretation, the implementation of `setPropertyBean` would basically be `return setPropertyJson(name, convertToJson(bean));` and then `getPropertyRaw` would automatically return the corresponding JSON value and all the other `getProperty` methods would work as they currently do for something set as a `JsonObject`.

**Comment by Artur-** [comment]
Sounds reasonable to me
