### ISSUE TITLE
Updating an entity based on a template model

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#732]
TemplateModel should contain a static helper method for updating an entity class based on the values in the model. The method only updates the parts which have been mapped to the model and leaves other parts as is.

The API should be

```
/**
 * Updates the given bean based on the values in the model at the given modelPath.
 *
**/
public void TemplateModel.updateBeanFromModel(T bean, String modelPath)

/**
 * Updates the given bean based on the values in the proxy object.
* <p>
 * The proxy object must be an instance previously returned by #getProxy().
**/
public void TemplateModel.updateBeanFromModel(T bean, T proxy);
// This calls update(bean,modelPath) using the modelPath stored in the proxy
```

Depends on #729, #731

**Comment by Legioth** [comment]
Requested in https://vaadin.com/forum/thread/17022752

**Comment by mshabarov** [comment]
Closed because `TemplateModel` and Polymer templates are deprecated in V23 and we're not going to add a new functionality there.
