### ISSUE TITLE
Spring Security managed logout triggers timeout too soon when push is enabled

### ISSUE THREAD

**Issue by tltv** [vaadin/flow#7323]
Logout is not always redirecting to /logout page when using Spring boot application with Spring security controlled logout URL and logout success handler. Only when Push is enabled (in any mode). Also seems that overriding timeout URL has its role here.
Its redirecting to /timeout page instead when custom timeout URL is given. Depending on how long time logout success handler and connection in general takes.

Below is a example of logout configurations in SecurityConfiguration that can reproduce this issue:

```java
        @Override
	protected void configure(HttpSecurity http) throws Exception {
		http.csrf().disable()
		...
		.and().formLogin().loginPage(LOGIN_URL).permitAll()
                 ...
		// Configure logout
		.and().logout().logoutUrl("/doLogout").logoutSuccessHandler(this::onLogout);
	}

	public void onLogout(HttpServletRequest request, HttpServletResponse response, Authentication authentication) throws IOException, ServletException {
	try {
		Thread.currentThread().sleep(5000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
        SimpleUrlLogoutSuccessHandler urlLogoutHandler = new SimpleUrlLogoutSuccessHandler();
        urlLogoutHandler.setDefaultTargetUrl("/logout");
        urlLogoutHandler.onLogoutSuccess(request, response, authentication);
    }
```

And this is how timeout page is set in VaadinServiceInitListener.
```java
@Override
public void serviceInit(ServiceInitEvent event) {
		event.getSource().setSystemMessagesProvider((SystemMessagesProvider) systemMessagesInfo -> {
            CustomizedSystemMessages messages = new CustomizedSystemMessages();
            messages.setSessionExpiredURL("/timeout");
            return messages;
        });
}
```

Attached zip contains full app that reproduces this issue. Logout button in the app will navigate to /doLogin URL. Success handler will just change the URL to navigate to /logout. In addition there is a timeout that helps to make this issue reproducible every time. Five seconds did the trick. Otherwise it happens more randomly.

Notice that this happen with Chrome and Edge, but not with FireFox.
This bug does not exist with Vaadin 14.0.5 with Chrome.

- Minimal reproducible example
See attached test application based on StoreFront Starter app
- Expected behavior
Logout redirects to /logout page without exceptions.

- Actual behavior
Logout redirects to /timeout page.

- Tested with versions:
    - Vaadin 14.1.3 / 14.1.4
    - Java 11
    - Windows 10
    - Chrome (79.0.3945.88), Edge
    - spring etc. versions in the attached zip (StoreFront starter app)

[testapp.zip](https://github.com/vaadin/flow/files/4040645/testapp.zip)

**Comment by Imrnkhan** [comment]
<http>
    
    <session-management>
        <session-authentication-strategy>
            <concurrency-control max-sessions="1" expired-url="/login?expired" />
        </session-authentication-strategy>
    </session-management>
</http>
add this and try out

**Comment by HerbertsVaadin** [comment]
Here's an example for V24.
[logout-timeout-issue-v24.zip](https://github.com/vaadin/flow/files/12701578/logout-timeout-issue-v24.zip)

In the example I had to use a 5 second thread sleep like @tltv , but in one of our customers app, this occurs with no delay. Haven't found a reason for it or any workarounds.

**Comment by Imrnkhan** [comment]
If user does not do anything (i.e. use mouse, key press, scrolling etc) for 2 mins then user will be logged out automatically and the page will be redirected to login page:
spring boot project application java.and this this is my code can any one fix and help out this code [](url)
[demo2-master.zip](https://github.com/vaadin/flow/files/12706288/demo2-master.zip)
