### ISSUE TITLE
Upgrading the version number in a NpmImport might fail silently

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow#7330]
In some cases, updating the version number and restarting the build won't do anything. The solution is to delete the package-lock file and run the build again.

This is far from ideal; users won't have any idea that the version didn't update, why it didn't update, and how to fix it. 

The framework needs to handle this better, at the very least inform the user that the update failed and how to retry.

**Comment by caalador** [comment]
Any information on in which cases?
Also I guess this is for 2.1 as 2.2 has a better way of handling the packages.

**Comment by tmattsso** [comment]
2.1 yes. I just updated the version number of a JS file import (leaflet js in my case); I don't know what more info you want.

**Comment by caalador** [comment]
Did you update it up or down? 
Also did you use `mvn clean ???:run` or are you running through a IDE plugin?
Could you paste the NpmImport change.

**Comment by tmattsso** [comment]
`@NpmPackage(value = "leaflet", version = "1.6.0")`
upgraded from 1.5.something, maybe.
Ran mvn clean spring-boot:run through eclipse.

**Comment by caalador** [comment]
Seems like the lock file is not updated for the `@vaadin/flow-deps` even though the content has changed and npm install is rerun.

leaflet package.json contains:
```
  "_requiredBy": [
    "/@vaadin/flow-deps"
  ],
  "version": "1.5.1"
```
Which is wrong as the version should now stand at 1.6.0 as required by `@vaadin/flow-deps`

Needs investigation on what can be done for 2.1 as the problem doesn't exist with the updated package.json usage in 2.2 (both pnpm and npm work as expected)

**Comment by caalador** [comment]
Closing issue as it didn't replicate on versions other than 2.1 which is not supported anymore. 
Tested this with 14.3.3 (Flow 2.3.3) and the upgrade worked as expected.
