### ISSUE TITLE
Import lists into a template model

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#736]
`TemplateModel.import` should support lists in the bean to import. Lists are imported by creating a ModelList with the given path, which is then populated based on the list contents

Depends on #730

**Comment by pleku** [comment]
Apparently this is already supported for `TemplateModel`,  even though https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/templatemodel/TemplateModel.java#L35 is a bit vague on this.
