### ISSUE TITLE
Issue with UI refresh from async thread

### ISSUE THREAD

**Issue by lucienbanholzer** [vaadin/flow#7365]
Dear Support,

I am facing an issue when reaching a page which fetch data asynchronously (in a dedicated thread).
Here is my config : I am implementing a SpringBootApp (2.2.2.RELEASE) which bootstrap vaadin (14.1.5).
My application uses also an App Layout (vaadin/vaadin-app-layout 2.0.4) where I've added the Push annotation.
![image](https://user-images.githubusercontent.com/24808446/72507348-04f02500-3844-11ea-8759-5fa0829cd8c8.png)

Here is how to proceed to reproduce the bug : 

**Set a view like the following one (same code as in the** https://vaadin.com/docs/v14/flow/advanced/tutorial-push-access.html tutorial) : 

```
@Route(value = "sandbox", layout = AppNavigation.class)
@PageTitle("sandbox")
public class SandboxView extends VerticalLayout {
	private LoadThread loadThread;
	private FeederThread thread;

	@Override
	protected void onAttach(AttachEvent attachEvent) {
		add(new Span("Waiting for updates"));

		// Start the data feed thread
		thread = new FeederThread(attachEvent.getUI(), this);
		thread.start();
	}

	@Override
	protected void onDetach(DetachEvent detachEvent) {
		// Cleanup
		thread.interrupt();
		thread = null;
	}

	private static class FeederThread extends Thread {
		private final UI ui;
		private final SandboxView view;

		private int count = 0;

		public FeederThread(UI ui, SandboxView view) {
			this.ui = ui;
			this.view = view;
		}

		@Override
		public void run() {
			try {
				// Update the data for a while
				while (count < 10) {
					// Sleep to emulate background work
					Thread.sleep(500);
					String message = "This is update " + count++;

					ui.access(() -> view.add(new Span(message)));
				}

				// Inform that we are done
				ui.access(() -> {
					view.add(new Span("Done updating"));
				});
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
	}

}
```

**And another one to handle 404 for instance** : 

```
@PageTitle(DashboardConst.TITLE_NOT_FOUND)
@ParentLayout(AppNavigation.class)
public class CustomRouteNotFoundError extends RouteNotFoundError {

	public CustomRouteNotFoundError() {
		RouterLink link = Component.from(
				ElementFactory.createRouterLink("sandbox", "Go to the front page."),
				RouterLink.class);
		getElement().appendChild(new Text("Oops you hit a 404. ").getElement(),link.getElement());
	}

	@Override
	public int setErrorParameter(BeforeEnterEvent event, ErrorParameter<NotFoundException> parameter) {
		return HttpServletResponse.SC_NOT_FOUND;
	}
}
```

When I access the 404 page and click on the link to be redirected to the first view : the view is correctly displayed but the addings done by the FeederThread via ui.access are not displayed. However if I just open the side menu then the UI get updated (cf video).

![bug_async_thread](https://user-images.githubusercontent.com/24808446/72511113-daee3100-384a-11ea-9a4a-7a6bd978e5d6.gif)

Thanks a lot for your help.
BR

**Comment by grass83** [comment]
Dear Support,
I am having a similar problem in Vaadin 14. Is there any progress on this issue?

Thank you very much for your help.

**Comment by mehdi-vaadin** [comment]
@grass83 it was moved to the high priority list which means someone will start working on it soon. You will notice the progress here.

**Comment by Legioth** [comment]
The root cause here is that `@Push` from the parent layout is for some reason not honored when bootstrapping an error page.

You can see this by printing the push mode in `SandboxView. onAttach`:
```
add(new Span("Push mode: " + attachEvent.getUI().getPushConfiguration().getPushMode()));
```

You can work around this by making either view explicitly enable push in the constructor or `onAttach`:
```
UI.getCurrent().getPushConfiguration().setPushMode(PushMode.AUTOMATIC);
```

**Comment by grass83** [comment]
Dear @Legioth 
I have tried the work around code and it is working perfectly.

Thank you very much for your help.
Regards
