### ISSUE TITLE
Import maps into a template model

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#738]
`TemplateModel.import` should support maps in the bean to import. Maps are imported by creating a ModelMap with the given path, which is then populated based on the map contents.

Only Maps with String keys are supported, other key types throw `IllegalArgumentException`.

Depends on #730

**Comment by jflamy** [comment]
I want to have an i18n-capable template.  I would pass the translations as a map instead of creating an array or large bean.

**Comment by mshabarov** [comment]
Closed because `TemplateModel` and `Polymer` templates are deprecated in V23 and we're not going to add a new functionality there.
