### ISSUE TITLE
@BodySize values not being respected in V15

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/flow#7385]
In V14, if you annotate your view with `@BodySize` the values for width and height are used to style the body.

With V15, these values are not being used, so body is always set to `width: 100vw; height: 100vh`.

Tried with `skeleton-starter-flow` with `vaadin-bom@15.0.0-alpha11` and with latest snapshot (`vaadin-bom-15.0-20200103.002106-185`).

**Comment by manolo** [comment]
In which class have you set the annotation ?

**Comment by haijian-vaadin** [comment]
Just aked Diego, it was added to the MainView.java, together with @PWA annotation

**Comment by manolo** [comment]
In V15, `@BodySize` and other annotations modifying the app-shell need to be in a class extending `AppShellConfigurator`.
The error is shown in console (java),  not throwing in order not to break apps, just saying that the annotation has no effect

**Comment by haijian-vaadin** [comment]
That's my suspect. Do we have it documented somewhere?

**Comment by manolo** [comment]
https://vaadin.com/docs/v15/flow/typescript/application-shell.html#java-annotations
