### ISSUE TITLE
Pressing enter on a focused button with a click shortcut fires two events

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#7396]
If a button has Enter as aa click shortcut and is focused when pressing enter, it fires two click events. I would expect it to only fire one. 
![double-click](https://user-images.githubusercontent.com/883698/72568358-d20e5700-386c-11ea-908a-4b1526f7a13d.gif)

**Comment by Legioth** [comment]
You can work around this by doing
```
button.addClickShortcut(Key.ENTER).setBrowserDefaultAllowed(false);
```

We went back and forth a couple of times with regards to the default setting for whether browser defaults should be prevented or not. I don't remember exactly how we ended up the way it is.

**Comment by Legioth** [comment]
You can work around this by doing
```
button.addClickShortcut(Key.ENTER).setBrowserDefaultAllowed(false);
```

We went back and forth a couple of times with regards to the default setting for whether browser defaults should be prevented or not. I don't remember exactly how we ended up the way it is.

**Comment by denis-anisimov** [comment]
Duplicate of https://github.com/vaadin/flow/issues/8037
