### ISSUE TITLE
Revert 2.2 to use npm by default

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7398]
Currently 2.2 has a flag `disable.pnpm`.

### Acceptance Criteria
- [ ] This change is only for the `2.2` branch
- [ ] Change flag name and semantics to `pnpm.enable` and it should "stay" `false` by default
- [ ] Most tests can stay running npm which is the default
- [ ] The tests for pnpm ought to be enough to validate that the flag works to enable pnpm

**Comment by denis-anisimov** [comment]
There should be one module which has two poms : one is using `pnpm` , another pom uses `npm`.
So the second pom explicitly disables `pnpm` via the flag.

This module should be found and changed: the new flag should be used to run `pnpm` and `npm` should be run without any flag.

**Comment by pleku** [comment]
Issue readjusted with the latest target of just renaming the parameter and keeping `pnpm` as default until further notice.
