### ISSUE TITLE
Make master branch build on 3.0 / V15

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7412]
#### Preparations:
Fork from `master` and push protected branches for Vaadin 14.2 targeted versions of the following things. Use the project (not platform) version as the branch name, like `2.2`. Branch protection rule should be applied automatically.
- [x] Flow
- [x] Spring
- [x] CDI
- [x] MPR

Make sure there is a snapshot build in Bender for the branch created in previous step. The master branch snapshot build will soon be building the next version (for V15).
- [x] Flow
- [x] Spring
- [x] CDI
- [x] MPR

Fork from `master` and push a `v14` branch for all the starters that should be on top of latest stable 14 version, currently 14.1
- [x] project base vanilla
- [x] project base cdi
- [x] project base spring
- [x] beverage-starter-example
- [x] business app starter
- [x] bakery-app-starter

Additional things:
- [x] Make sure the platform version update script for maintenance releases targets the newly created `v14` branches with the update PRs for all the ^ starters [Juho]
- [x] Make sure vaadin.com/start page uses the newly created `v14` branches for the starters  [joheriks]
- [x] Make sure start.vaadin.com wizard uses the newly created `v14` branches for the starters  [joheriks]

#### Merge all `ccdm` branches to master:
Make sure all changes are picked from `master` -> `ccdm` branch. Then make a PR from `ccdm` -> `master` that should be merged, NOT squashed or rebased.
- [x] Flow [Haijian ]
- [x] Spring [Haijian]
- [x] CDI [Denis]
- [ ] MPR [Denis, dat took over]
- [x] project base vanilla [joheriks]
- [x] project base cdi [joheriks]
- [x] project base spring [joheriks]
- [x] beverage-starter-example [joheriks]
- [x] business app starter [joheriks]
- [x] bakery-app-starter [joheriks, Haijian took over]

#### Cleanup
Any snapshot builds for the ccdm branches can be removed.

#### Other stuff
Portlet repositories are not part of this as the add-on will not be able to be finalized on time for Vaadin 15.
The documentation repository flow-and-components-documentation is excluded from this for now and to be handled separately, because it is not built similarly and there is no rush. Also it needs design with the steak holders.

**Comment by denis-anisimov** [comment]
Spring SNAPSHOT still uses the `master` branch instead of `12.2`.

**Comment by pleku** [comment]
MPR has some regression which has its own issue, closing this one as everything is done.
