### ISSUE TITLE
Simplify imports from @vaadin/flow-frontend

### ISSUE THREAD

**Issue by platosha** [vaadin/flow#7419]
So far when importing from `@vaadin/flow-frontend` we were using file paths, like so:

```typescript
import {Flow} from '@vaadin/flow-frontend/Flow';
```

This was due to an issue with `webpack-babel-multi-target-plugin` preventing using the `main` field in `package.json` there.

Now that we have dropped the es5 bundle and `webpack-babel-multi-target-plugin`, let us simplify the imports to reference the package:

```typescript
import {Flow} from '@vaadin/flow-frontend';
import {Router} from '@vaadin/router';
```

DoD:

- `node_modules/@vaadin/flow-frontend/package.json` has a `main` field referencing an index file with all public exports
- Imports use `@vaadin/flow-frontend` package, including:
  - Generated `index.ts` and `connect-client.default.ts`
  - Examples in the docs
  - Skeleton starter
  - Starter wizard
- Binder should have its own package @vaadin/forms

**Comment by haijian-vaadin** [comment]
the @vaadin/flow-frontend package is done in [this commit](https://github.com/vaadin/flow/commit/a8c709e434c7dfb2090e5094e28c425238f8be5b#diff-78156aff7245b58e2bae4f007e1612e992957e132ce3ea465cfb8e6350b0380c). 
What's remaining is to update the usages mentioned in the ticket.
