### ISSUE TITLE
PWA install prompt is shown on installed PWA

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#7425]
Vaadin 14.1. 

I would not expect to see the install prompt anymore after already installing the app. Clicking install on the installed app only hides the prompt. 

<img width="1130" alt="Screen Shot 2020-01-26 at 9 20 09 AM" src="https://user-images.githubusercontent.com/883698/73138968-68850a00-401d-11ea-80ff-82849a886a6d.png">

**Comment by mehdi-vaadin** [comment]
Which browser are you using? I tried with Chrome 79 on Mac and couldn't reproduce it.

**Comment by marcushellberg** [comment]
Chrome 79 on Mac

**Comment by mehdi-vaadin** [comment]
I tried once again with Chrome 80 after cleaning Chrome applications cache. I also checked it on another machine. Still can't reproduce it. 

@marcushellberg maybe something special about your case. Could you share more info about your app? Can we test it with your code?

One more thing is that maybe something in the settings of your Chrome is different. For instance, enabling `chrome://flags/#bypass-app-banner-engagement-checks` may occur that behavior. See [this Stackoverflow post](https://stackoverflow.com/a/41866791/5613292) about that.

**Comment by mehdi-vaadin** [comment]
@marcushellberg since we haven't heard from you, I'm closing this issue. Whenever you have time please check my previous comment and if it doesn't help you, let us know.
