### ISSUE TITLE
Use readPackage hook to pin dependency versions with pnpm

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow#7432]
## Problem

In order to have reproducible builds, we created `@vaadin/vaadin-shrinkwrap` package.
While we add it as a dependency, individual components are added separately, too.

As a result of using `pnpm` the shrinkwrap takes no effect and in fact causes duplicates.
So we need something like [dependency resolutions in Yarn](https://legacy.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to fix that.

## Solution

We can place a `pnpmfile.js` with a `readPackage` hook to pin transitive dependencies.
The idea is to put components versions to the `"resolutions"` in `package.json` like this:

```js
  "resolutions": {
    "@vaadin/vaadin-element-mixin": "2.2.0",
    "@vaadin/vaadin-overlay": "3.2.18"
  }
```

See example project with a `pnpmfile.js`: https://github.com/web-padawan/pnpm-resolutions

One question that needs to be solved is how do we define what platform version is in use, and what `package.json` to use as a single source of truth for the set of compatible versions.

I assume we can keep `@vaadin/vaadin-shrinkwrap` package and we can fetch `dependencies` from there, and then map them to `"resolutions"` in the root `package.json` of the project.

**Comment by pleku** [comment]
If I understand correctly, this is something that needs to be done on the platform level when the `package.json` gets build for `vaadin` and `vaadin-core` ? Or is this something that the application developers would need too to be done out-of-the-box when the use the platform and add a 3rd party frontend dependency to the project ?

So is the implication of this problem that there might be different versions of certain packages in the same project pending on for example what dependency was introduced first and thus get populated into `pnpn-lock.yaml` ? And for a clean project another set of versions could get used ?

**Comment by web-padawan** [comment]
> this is something that needs to be done on the platform level 

This is something that needs to be done in the project that is generated by Flow.

The problem in 15.0 and 14.2 at this point is that component versions come from two origins:

- `@vaadin/vaadin-shrinkwrap` that pins e. g. `@vaadin/vaadin-overlay` to `3.2.18`
- `@NpmPackage` annotation that adds inndividual components like `@vaadin/vaadin-combo-box`
  - while `@vaadin/vaadin-combo-box` also depends on `@vaadin/vaadin-overlay` it does NOT pin the version but uses `^` instead. That's how we get duplicate dependencies today.

By having `"resolutions"` we actually eliminate a need for shrinkwrap. But we should handle them on the top level where we actually run `pnpm install`, not on the platform level.

When a new platform version is released, and user runs the project, we should discover that and update `resolutions` in `package.json`. This way they will be updated in `pnpm-lock.yaml` too.

Hope this is clear now, please ping me if you have any further questions.

**Comment by Artur-** [comment]
So without any changes to the shrinkwrap, could we make this work by changing your `pnpmfile.js` to read `node_modules/@vaadin/vaadin-shrinkwrap` if present and let any `resolutions` found in the project `package.json` override that?

**Comment by web-padawan** [comment]
@Artur- yes, that's basically what I'd like to achieve.

I haven't checked whether we already have `@vaadin/vaadin-shrinkwrap/package.json` at the moment when `readPackage` is called but apparently after packages are downloaded.

Docs for the hook are here: https://pnpm.js.org/en/3.6/hooks

**Comment by Artur-** [comment]
From what I see, `readPackage` is never called for e.g. `@vaadin/vaadin-dialog` which would indicate that you can lock the dialog version this way but not its dependencies, e.g. `vaadin-overlay`.

**Comment by web-padawan** [comment]
In the [example project](https://github.com/web-padawan/pnpm-resolutions) I linked in the original issue, I show how to pin `vaadin-overlay`

```sh
readPackage hook is declared. Manifests of dependencies might get overridden
Pinned @vaadin/vaadin-overlay required by @vaadin/vaadin-shrinkwrap from ^3.2.16 to 3.2.18
Pinned @vaadin/vaadin-overlay required by @vaadin/vaadin-date-picker from ^3.2.0 to 3.2.18
Pinned @vaadin/vaadin-overlay required by @vaadin/vaadin-context-menu from ^3.2.9 to 3.2.18
Pinned @vaadin/vaadin-overlay required by @vaadin/vaadin-combo-box from ^3.2.0 to 3.2.18
Pinned @vaadin/vaadin-overlay required by @vaadin/vaadin-dialog from ^3.2.0 to 3.2.18
Pinned @vaadin/vaadin-overlay required by @vaadin/vaadin-select from ^3.2.0 to 3.2.18
Pinned @vaadin/vaadin-overlay required by @vaadin/vaadin-login from ^3.2.1 to 3.2.18
Pinned @vaadin/vaadin-overlay required by @vaadin/vaadin-confirm-dialog from ^3.2.0 to 3.2.18
```

The only problem is that we can't rely on `@vaadin/vaadin-shrinkwrap` present locally.
We should be able to get it from store folder, but I wasn't able to get store location.

**Comment by Artur-** [comment]
Right, I was missing the shameful parameter

**Comment by Artur-** [comment]
> The only problem is that we can't rely on @vaadin/vaadin-shrinkwrap present locally.
We should be able to get it from store folder, but I wasn't able to get store location.

Is there any guarantee that `vaadin-shrinkwrap` is downloaded before some other package is passed through `readPackage`? Otherwise  the version info could be created as a file in `target/frontend` where other files are also generated before `pnpm i` is run

**Comment by web-padawan** [comment]
@Artur- I have updated my example to pin versions based on those specified in `vaadin-shrinkwrap` listed as a dependency, instead of using `"resolutions"` (we can have them if we need).

So you can try to add this `pnpmfile.js` and see how it works for you: 
https://github.com/web-padawan/pnpm-resolutions/blob/master/pnpmfile.js

Note, that currently the script only covers simple case when `~./pnpm-store` exists.

Please see [`@pnpm/store-path`](https://github.com/pnpm/store-path/blob/master/src/index.ts) for a comprehensive script that handles some edge cases. I didn't use it because `pnpmfile.js` is executed before we install dependencies, so we can't rely on it there.

**Comment by web-padawan** [comment]
Submitted https://github.com/vaadin/starter-wizard/pull/349 to test, let's see if it passes the build.

**Comment by web-padawan** [comment]
Looks like with the local `pnpm` installation the `.pnpm-store` ends up somewhere else than in home directory where the script currently assumes it to be.

So I have added another script that runs on `preinstall` and gets versions info from npm directly, by fetching from https://registry.npmjs.org/@vaadin/vaadin-shrinkwrap and saving data to JSON.

Updated the starter again to try this change.

**Comment by pleku** [comment]
>Right, I was missing the shameful parameter

I'm a bit late to the party, but I see that Flow is also using `--shamefully-hoist=true` for `pnpm`. 
So this is needed to get the flat structure. But now it is not enough with platform ? If I try with 14.2-SNAPSHOT how can I see this problem or is not there due to no shrinkwrap for snapshot ? As all I see is a flat structure (made with symlinks) in `node_modules` ? And for instance `vaadin-overlay` is resolved to `3.4.0` for everything in `pnpm-lock.yaml`.

If I test with `14.2.0.alpha10`, then it is still the same result.

Or is the issue with that there is randomness in this and something might cause another version to be resolved ? Sorry if I'm asking stupid questions but I don't understand how this is now suddenly an issue not noticed before or even now with 14.2.

**Comment by web-padawan** [comment]
>  is the issue with that there is randomness in this and something might cause another version to be resolved 

Yes that's the issue that we attempted to fix with `shrinkwrap` but it wasn't a proper fix.

So, for example, now we have `vaadin-element-mixin` 2.3.0 picked up, although it contains new API for RTL that shouldn't be there in 14.2 but is targeting future versions - 14.3 or later.

With the suggested change we will be able to pin transitive dependencies to exact versions like we could with `bower` (see lockfile diff in [starter-wizard PR](https://github.com/vaadin/starter-wizard/pull/349/files#diff-4c3931f66cb5c011888ce5114109913fL1358)) and avoid duplicates at the same time.

**Comment by pleku** [comment]
>So, for example, now we have vaadin-element-mixin 2.3.0 picked up, although it contains new API for RTL that shouldn't be there in 14.2 but is targeting future versions - 14.3 or later.

Right, thanks for the clarification. It seems that we're able to avoid this for polymer currently and getting `3.2.0` instead of `3.3.0` (which causes conflicts) because we have Java code that adds it explicitly to the `package.json` under 
```
"vaadin": {
    "dependencies": {
      "@polymer/polymer": "3.2.0",
```

**Comment by denis-anisimov** [comment]
The result of investigation:
- not performance issues detected.
- we should avoid download `versions.json`  file via JS. We should either download it via Java or assume that it's already there available via classpath (provided somehow by the Platform : will be clarified later on).
- put `pnpmfile.js` into the project folder so it can be used by the `pnpm`.
