### ISSUE TITLE
Nightly snapshot build for Flow 2.2 and its dependents

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#7445]
Configure a nightly snapshot build trigger for each of the following in `bender.vaadin.com` Teamcity under `Flow private`. The versions to be built should match Flow 2.2.
- flow (2.2)
- spring (12.2)
- cdi (11.2)
- portlet (1.0)
- mpr (2.0)

The build steps should:
- compile
- run integration tests
- deploy artifacts to https://oss.sonatype.org/content/repositories/vaadin-snapshots 

For now, we will not add any classifier to it (like `NIGHTLY-...`), unless we discover that it would be needed.

You need to find out if it makes sense to reuse any existing snapshot builds/triggers, or create a template for the build configuration/project so that it can be reused later with different branches and/or parameters.

**Comment by mehdi-vaadin** [comment]
Flow 2.2 nightly snapshots project has been created [here](https://bender.vaadin.com/project.html?projectId=Flow_Snapshots_Flow22nightlySnapshots&tab=projectOverview). I will verify it later to make sure that it works as expected.
