### ISSUE TITLE
Clean up the ccdm branch

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#7447]
Flow has merged and ccdm branch to master and ccdm branch has been deleted. Let's do a delete the ccdm branch for other repos as well:
- [x] project base vanilla
- [x] project base cdi
- [x] project base spring
- [x] beverage-starter-example
- [x] business app starter
- [x] bakery-app-starter
- [x] flow-and-components-documentation, 
- [x] Spring
- [x] CDI
- [x] MPR
- [x] Vaadin Docs (https://github.com/vaadin/vaadin-docs/commit/24fb616e97c403ff1950d61dc331b8bb4ae780bf)
- [x] Vcom starter (https://gitlab.vaadin.com/search?utf8=%E2%9C%93&search=ccdm&group_id=&project_id=498&search_code=true&repository_ref=development&nav_source=navbar)

**Comment by joheriks** [comment]
Also check `README.md` and other files for stale references to `ccdm`. For instance:
https://github.com/vaadin/beverage-starter-flow/blob/master/README.md
