### ISSUE TITLE
Run on server from IntelliJ IDEA requires prepare-frontend to be executed first

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7448]
1) Create a Vaadin application in e.g. start.vaadin.com and import it to IDEA
2) Build the project from IDEA using _Build -> Build project_
2) Then try to run it on an application server like Tomcat/Jetty using "Run on server" feature of IDEA (_Run -> Edit configurations -> create new application server configuration_), specifying the project as a `war` artifact to be deployed

Expected: it will just work 

Actual: it will fail because it is not able to get the paths correct, error message:

```
Failed to find the following css files in the `node_modules` or `C:\Users\Pekka\workspaces\Servers\apache-tomcat-8.5.46\bin\.\frontend` directory tree:
      - styles/views/masterdetail/master-detail-view.css
      - styles/views/dashboard/dashboard-view.css
      - styles/views/list/list-view.css
      - styles/views/form/form-view.css
  Check that they exist or are installed. If you use a custom directory for your resource files instead of the default `frontend` folder then make sure it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)


		at com.vaadin.flow.server.frontend.AbstractUpdateImports.getCssLines(AbstractUpdateImports.java:213)
...
```

Possible ways to workaround it are:
- Run `mvn install` once to get the `prepare-frontend` triggered and create webpack config files and `flow-build-info.json` created
- Set `mvn install` as the preceding goal for the server startup instead of `build project`
- Make it so that the `prepare-frontend` is executed whenever the project is built in IDEA or when it is imported, as it should be enough and the user would not have to care

**Comment by mehdi-vaadin** [comment]
I'm closing this as the document about how to run on sever in IntelliJ has been added via https://github.com/vaadin/flow-and-components-documentation/pull/1091.
