### ISSUE TITLE
Follow up #7432: Use readPackage hook to pin dependency versions with pnpm

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#7451]
- [x] Use `pnpmfile.js`  from #7432.
- [x] Correct the code a bit so that it doesn't fail in the corner cases.
- [x] Assume that `versions.json`  (or some other name) is available in the classpath (the exact location is TBD).
- [x] So there is no need to download it but just access it via the classpath.
- [x] Make it possible to read the file via `pnpmfile.js` (copy it to the `target`  folder ?)
- [x] Generate `pnpmfile.js` file in the  project folder before running `pnpm install` .

Testing with platform split out to #7493

**Comment by pleku** [comment]
Reopened to make sure it has been explicitly tested with the platform snapshot.
