### ISSUE TITLE
CCDM: IndexHtmlHandler does not handle routes with dots

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#7494]
`IndexHtmlHandler` was took from vaadin-frontend-server to serve the bootstrap page. The condition used for handling the request is just discard anything with an extension, meaning that those files should be served by the `StaticFileHandler` 

This issue causes build failures in MPR https://github.com/vaadin/multiplatform-runtime-internal/issues/352 because IT's are calling routes with the full class name like `http://localhost:9998/com.vaadin.test.CookiesView`

Solutions:
- Change regex to be more specific, right now it discards everything with a dot followed by a letter and more letters or numbers `Pattern.compile("\\.[A-z][A-z\\d]+$");` ,  it could be changed to something like one dot and 2-4 characters, not a good solution though.
- Check the Router registry in the `IndexHtmlHandler.canHandleRequest`. Not reliable, because we need to render the bootstrap when in the URL comes a route for the client-side
- Check whether the `StaticFileHandler` finds the file. This does not work because the static handler is actually run before the bootstrap one
- Put the `IndexHtmlHandler` the last in the handlers chain rendering the `index.html` as last resource, then it's responsability of the vaadin-router to resolve the route

**Comment by denis-anisimov** [comment]
It might be worth to note that Flow has tests which also uses FQNs for routing.
If those tests don't fail then it means those tests are not executed for the functionality which is broken.
So probably the tests should be executed for this case as well .

**Comment by manolo** [comment]
So, we have not realised this before because all tests in flow are run with the `vaadin.useDeprecatedV14Bootstrapping=true` but `flow-tests/test-ccdm`

**Comment by Legioth** [comment]
What about making it possible for the application to override the default regexp? The we could still skip stuff that looks like static requests by default, but still allow our own tests to use a different configuration.

Another alternative that has also been suggested but maybe not thoroughly evaluated is to make the decision based on the `Accept` headers from the browser instead. If there is a header but none of the values matches a whitelist of things that can be seen as requesting a HTML document, then it is ignored.

**Comment by Legioth** [comment]
What about making it possible for the application to override the default regexp? The we could still skip stuff that looks like static requests by default, but still allow our own tests to use a different configuration.

Another alternative that has also been suggested but maybe not thoroughly evaluated is to make the decision based on the `Accept` headers from the browser instead. If there is a header but none of the values matches a whitelist of things that can be seen as requesting a HTML document, then it is ignored.

**Comment by haijian-vaadin** [comment]
should be in beta 2

**Comment by manolo** [comment]
@leif implementation adds this API so as the user can configure their rules
```
public class AppShell implements AppShellConfigurator {    
    public AppShell() {
        VaadinService.getCurrent().setBootstrapUrlPredicate(
                req -> !req.getPathInfo().matches(".+\\.[A-z][A-z\\d]+$"));
    }
}
```

The API is the same than we implemented for the inclusion of the initial Uidl fragment in the bootstrap page
