### ISSUE TITLE
Investigate how prepare-frontend could be triggered for IntelliJ projects automatically

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7497]
This would fix _run on server_ issues. Details in #7448

We should ask the designer team for hints on how to go about this. Timeboxed 2 days.

In theory it could be enough to fix this issue just for our starters with something that makes IDEA run `prepare-frontend` when the project is imported. But this will not cut it for projects started from start.spring.io or for another IDE.

**Comment by caalador** [comment]
One possibility would be:
https://www.jetbrains.com/help/idea/delegate-build-and-run-actions-to-maven.html#delegate_to_maven
But at first glance it requires the user to setup by hand, but this will run maven and thus execute the defined prepare-frontend goal.

**Comment by caalador** [comment]
One minor help could be to have `runConfigurations` in the starters even though these also require one to execute it, but might help when it would be visible in the dropdown.

For instance a `mvn compile` run target would be in `.idea/runConfigurations/Compile_project.xml`

```
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="Compile project" type="MavenRunConfiguration" factoryName="Maven">
    <MavenSettings>
      <option name="myRunnerParameters">
        <MavenRunnerParameters>
          <option name="goals">
            <list>
              <option value="compile" />
            </list>
          </option>
          <option name="resolveToWorkspace" value="false" />
          <option name="workingDirPath" value="$PROJECT_DIR$" />
        </MavenRunnerParameters>
      </option>
    </MavenSettings>
    <method v="2" />
  </configuration>
</component>
```

**Comment by caalador** [comment]
For documentation the information when generating a run configuration for tomcat could inform to add a `Run maven goal` with `command line` as `vaadin:prepare-frontend`  before `Build artifact` to `Before launch` at the bottom of the Server tab.

This is also something the user needs to configure themselves for the project as we can not expect them to have a server installation so we could have a default run configuration for it.

**Comment by joheriks** [comment]
Another possible avenue for making it work with IntelliJ is to add the following piece XML files to starters in `.idea/misc.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="MavenCompilerTasksManager">
    <option name="afterCompileTasks">
      <set>
        <MavenCompilerTask>
          <option name="goal" value="com.vaadin:vaadin-maven-plugin:14.1.16:prepare-frontend" />
          <option name="projectPath" value="$PROJECT_DIR$/pom.xml" />
        </MavenCompilerTask>
      </set>
    </option>
  </component>
</project>
```
This makes IntelliJ run `prepare-frontend` after project build, which in turn is guaranteed to occur before the war is packaged when running on server. In the UI, this can be toggled by right-clicking on a Maven goal and toggling the "Execute Before/After" check items in the context menu.

Some caveats:
- The exact version of the `vaadin-maven-plugin` seems to be needed in the XML files (need to check if it can be omitted/wildcarded)
- It needs the path to `pom.xml`, meaning the above will work if the project is imported as a new project, but not if it is imported as a module in an existing IntelliJ project.
