### ISSUE TITLE
Support running multiple webapps in in dev-mode within same application server (JVM)

### ISSUE THREAD

**Issue by jensgoe** [vaadin/flow#7502]
i develop two webapps deployed as two separate ear-files on a Payara4.1 (Glassfish) server. The problem is that i can only run the first deployed app. The next app i deploy does not start because it cannot find js-files/css-files from the frontend folder.

i did a lot of investigation and came to the conclusion that it is related to the webpack-dev-server. the first deployed app starts a new webpack-dev-server. the second app detects that an webpack-dev-server is running and uses this connection. if the second app is requesting resources from the frontend folder it connects to the webpack-dev-server of the first app and that server does not find the requested resources.

if a webpack-dev-server starts the DevModeHandler stores with method saveRunningDevServerPort the port id in the temp file. the file name is based on a unique name of the JVM (computeDevServerPortFileName). 

Currently i use the following workaround.
After deploying the first app i am looking in the temp folder for the file with the port id of the webpack-dev-server. i delete that file and then i deploy the second app. then a new webpack-dev-server is started and everything works. thats annoying :-(

My guess is that a webpack-dev-server needs to be started for each application.

**Comment by Legioth** [comment]
I guess what could be done is to also use the context path as part of the lookup key, or to make it completely configurable by the application.

**Comment by jensgoe** [comment]
i recently updated to version 14.2. It seems that multiple node instances are startet now and that solved this problem for me.
