### ISSUE TITLE
Switching from the client-side view to server-side view is slow

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#7505]
1. Go to start.vaadin.com
2. Created a new v15 app with a List view and a Master-Detail (CRUD) Java view. The List view was set up as the default. 
3. Opening the app loads the List view ok, but when I switch to the Master-Detail view, it takes an uncomfortably long time to load it on the first time: https://drive.google.com/open?id=1zIWXbveJTZ4_zJQxEn81uZKeLWMYMyDQ - maybe it would be nicer if the menu reacted only after the view has loaded.

**Comment by platosha** [comment]
For implementation, it’s enough that the wrapper element for the server-side view shows a loading progress indicator when loading the first server-side view.

It might make sense to show it on second and other server-side view loads as well.

We could copy the UX of v14 and before loading progress indication.

There is a bootstrap loading indicator element in the index page already, we could implement this by taking control of its state in Flow.ts.
