### ISSUE TITLE
CCDM: IT's ignore the existence of  the `Flow.clients.TypeScript` 

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#7514]
`Flow.clients.TypeScript`  is added by Flow Client so as TB can be notified when the client is loaded or when there is pending work in client router.

Though, there are tests checking different flow features that trust in `Flow.client` object having only one entry, those tests fail when disabling v14 boostrapper e.g. https://github.com/vaadin/flow/blob/master/flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/ExportedJSFunctionIT.java#L102

**Comment by haijian-vaadin** [comment]
should be in beta 2
