### ISSUE TITLE
CCDM: feature missing `InternalServerError` component  is not displayed

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#7515]
In V14 when there is an exception while router renders a view, the exception is caught and sent to the browser using the `InternalServerError` component, this feature is missing in V15 handlers.

The significant code is in the https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/router/Router.java#L234

**Comment by haijian-vaadin** [comment]
not need for beta2
