### ISSUE TITLE
vaadin.urlMapping doesn't work with V15 apps

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow#7521]
```
// application.properties
vaadin.urlMapping=/app/*
```
Doesn't seem to change the context where connect listens to endpoint requests. This change alone makes the app's endpoint calls to "/app/connect/..." but the endpoint requests are always responded with an HTML page.

Workaround:

```
vaadin.connect.prefix=/connect
```

**Comment by haijian-vaadin** [comment]
Rename vaadin.connect.prefix -> vaadin.endpoint.prefix
