### ISSUE TITLE
DeploymentConfiguration’s CSRF protection setting does not affect @Endpoint protection

### ISSUE THREAD

**Issue by platosha** [vaadin/flow#7525]
`DeploymentConfiguration#isXsrfProtectionEnabled()` can be used to disable the protection when it is not used.

But for `@Endpoint` requests, the protection is enabled regardless of the setting.

Use case and steps to reproduce:

1. Make an app that has both server-side views, and `@Endpoint` with `@AnonymousAllowed`

2. Before you ever visit server-side view, requesting the endpoint without csrf header works

3. After you visit server-side view once, requesting the endpoint without csrf header gives access error

**Comment by haijian-vaadin** [comment]
Needed for before stable.
