### ISSUE TITLE
Latest Chrome on Ubuntu is reported as unsupported browser in 3.0 / V15

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7538]
As reported in https://twitter.com/OlafKortluke/status/1227120477145096193

**Comment by caalador** [comment]
Sorry for the miss click.

Vaadin 15.0.0.beta1 from start.vaadin.com worked on ubuntu 18.04.3 with Chrome 80.0.3987.87

User-Agent: `Mozilla/5.0 (Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36`

**Comment by olaf-2** [comment]
Olaf here who mentioned the issue on Twitter. 

This morning the error message appeared and even a restart of the browser did not help. Now I cannot reproduce it anymore. Everything works perfectly. Sorry for the inconvenience.

**Comment by denis-anisimov** [comment]
Seems this is not an issue anymore.
So I close it.
Please add a comment if I should reopen it.
