### ISSUE TITLE
ReflectionCache.clearAllActions are cleared because of weak references

### ISSUE THREAD

**Issue by roeltje25** [vaadin/flow#7549]
In our development setup we use hotswapagent which will call ReflectionCache.clearAll() after class changes in order to make sure changes to classes are picked up everywhere. However, this was not working. After some investigation it seems that there are several ReflectionCaches in vaadin and they register a clear action using addClearAllAction. In java 11 at least (I did not test other jvms) this is not working. the lambda which is registered does not have a strong reference outside of the clearAllActions map. this map uses weak references, as such the jvm garbage collects the lambda and the clearAllAction is removed. many caches are therefore not cleaned as they should.

I have fixed the issue in our code base by duplicating the reflectioncache code and to add a strong reference for each this::clear lambda to prevent garbage collection from removing the clearAllAction while the reflectioncache is strongly referenced.

here is the top snippet of the class as I have it at this moment:

```java
public class ReflectionCache<C, T> {
    private static final Set<Runnable> clearAllActions = Collections
            .synchronizedSet(Collections.newSetFromMap(new WeakHashMap<>()));

    private final ConcurrentHashMap<Class<? extends C>, T> values = new ConcurrentHashMap<>();

    private final SerializableFunction<Class<? extends C>, T> valueProvider;
   
    // strong reference to clear action
    private final Runnable clearAction = this::clear;

    /**
     * Creates a new reflection cache with the given value provider. The value
     * provider will be used to produce a new cached value whenever there is a
     * cache miss. It will be run in a context where no {@link CurrentInstance}
     * is available to prevent accidentally caching values that are computed
     * differently depending on external circumstances.
     *
     * @param valueProvider
     *            a function that computes the cached value for a class, not
     *            <code>null</code>
     */
    public ReflectionCache(SerializableFunction<Class<C>, T> valueProvider) {
        if (valueProvider == null) {
            throw new IllegalArgumentException("value provider cannot be null");
        }
        this.valueProvider = wrapValueProvider(valueProvider);

        // add clear action using strong reference instead of this::clear directly
        addClearAllAction(clearAction);
    }
```

**Comment by Legioth** [comment]
Thank you for a very insightful issue report with a clear analysis of the problem!
