### ISSUE TITLE
Search for another plugin that can be used to DL and install of nodejs

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7550]
Related to #6249 , see if there is an alternative for frontend-maven-plugin that could be reused.

**Comment by joheriks** [comment]
`frontend-maven-plugin` contains a separate core module with the download and installation lgoic that could be used as a regular dependency:
https://github.com/eirslett/frontend-maven-plugin/blob/master/frontend-plugin-core/pom.xml
