### ISSUE TITLE
ShortcutRegistration.listenOn with more than one component doesn't work

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#7552]
For example, with the following code,

```Java
TextField username = new TextField("Username");
PasswordField password = new PasswordField("Password");
Button login = new Button("Sign in", event -> login());
login.addClickShortcut(Key.ENTER).listenOn(username, password);
```
the shortcut (`Enter`) only works on `username` (the first one) and is not triggered on `password` (the second one).

Vaadin version: 15.0-SNAPSHOT

**Comment by denis-anisimov** [comment]
This feature has been considered as implemented but it's doesn't work. So we should fix it ASAP.
