### ISSUE TITLE
CCDM: no way to use exported webcomponents 

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#7559]
Generated bundle in client-side mode is not able to import flow exported webcomponents  since it takes as entry the `frontend/index.ts` file that loads asynchronously the generated `target/frontend/generated-flow-imports`

Possible solution is to deliver two bundles: `vaadin-bundle.js` and `vaadin-wc.js`, the first used in the `IndexHtmlRequestHandler` and second in the `WebComponentBootstrapHandler`

A workaround for having flow IT's passing is to have a custom `index.ts` file with just a line `import '../target/frontend/generated-flow-imports';` but there is an issue related with this solution: https://github.com/vaadin/flow/issues/7557

**Comment by Legioth** [comment]
What is the use case, aside from our own ITs?

**Comment by manolo** [comment]
- Given any Vaadin application that is exported the whole application as a webcomponent, it cannot be used from a 3rd party application importing it as a webcomponent. workaroune: needs to be run with the old bootstrap
- Given a Vaadin application that can be used as a regular vaadin app including some client views, but it has exported sever views as webcomponents, it is imposible to use from a 3rd party app.
