### ISSUE TITLE
CCDM: event.forwardTo does not work in v15

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#7578]
This code does not work in V15

```
    @Route("foo")
    public class MyView extends Div implements BeforeEnterObserver {
        @Override
        public void beforeEnter(BeforeEnterEvent event) {
            event.forwardTo("bar");
        }
    }
```

**Comment by haijian-vaadin** [comment]
Is it so that "bar" is a client-side route? This ticket means that `event.forwardTo` cannot navigate to a client-side route?

**Comment by haijian-vaadin** [comment]
Related to https://app.zenhub.com/workspaces/ccdm-5d413125e27a7b3dba911156/issues/vaadin/flow/6490

**Comment by ptdatkhtn** [comment]
even "bar" is a server-side route, it doesn't update the correct url.
