### ISSUE TITLE
PROD mode not activated for multi-module spring-boot projects

### ISSUE THREAD

**Issue by cheppsn** [vaadin/flow#7579]
**Environment:**
- Vaadin 14
- Spring Boot 2.2.4
- Gradle 5.0 + Vaadin Gradle Plugin 0.5.0

**Problem description:**
When building a multi-module spring-boot application where Vaadin is used in a subproject (i.e. module) then the  `flow-build-info.json` with _prodMode=true_ setting will be packed into a nested module jar such as `jar:file://.../boot-app.jar!/BOOT-INF/lib/vaadin-ui.jar!/META-INF/VAADIN/config/flow-build-info.json` (with `vaadin-ui.jar` being the packaged module).

Unfortunately loading `flow-build-info.json` from a "double-nested-jar" resource path is _explicitly disabled_ in [DeploymentConfigurationFactory.java#L354](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java#L354).

There's a comment on [line 325](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java#L325), but I don't see why only "single jar flow-build-info" should be accepted in this case.

The application thus defaults to _development mode_ and due to this we cannot currently deploy our Vaadin 14 application in PROD mode, which is a bummer.

Note: Bug was originally filed as https://github.com/vaadin/vaadin-gradle-plugin/issues/39 (initial problem description, closed in favor of this bug, because not a build-problem but a runtime-problem).

**Comment by cheppsn** [comment]
I wonder if there are any possible work-arounds until this will be fixed?

**Comment by caalador** [comment]
So the build is that you are building a WAR with flow packaged in there as a jar?

The problem we face here is that for a war we can not know if we can accept the build-info from a jar as it might be for an miss packaged add-on and it has caused lots of confusion when things fail with non existent file paths.

The correct way for the production build with Spring would be to have in `application.properties` the property `vaadin.productionMode = true`

**Comment by cheppsn** [comment]
> So the build is that you are building a WAR with flow packaged in there as a jar?

We're not building a WAR, we're actually packaging with `bootJar` (from `bootDistZip`) and then deploy as runnable JAR/embedded server distribution. But yes, inside that artifact, our flow-code is a jar.

> The correct way for the production build with Spring would be to have in application.properties 
> the property vaadin.productionMode = true

That would be fine with me (and would of course have to match the way, a build artifact has been produced; i.e. probably best written by PROD build itself).

**Comment by caalador** [comment]
I see now. We could perhaps drop the else clause so that if there for the 2 jars case doesn't exist a flow-build-info inside the main jar we would do the same as for others and just select the first and log the warning that we couldn't determine the file.
