### ISSUE TITLE
theme="dark" added to <body> instead of <html>

### ISSUE THREAD

**Issue by Frettman** [vaadin/flow#7588]
I'm using Vaadin 14.1.17 (in a Spring Boot application) and I had some trouble with Lumo's shadows not really showing, especially using the dark theme. I have tracked it down to the fact that theme="dark" (from my @Theme annotation) is set on the body instead of on the html-tag.

Setting a breakpoint in Lumo#getHtmlAttributes leads me to TaskUpdateImports where those attributes are added to the body using this template: `document.body.setAttribute('%s', '%s');`

BootstrapPageBuilder#handleThemeContents(...) - which would handle it correctly from the looks of it - is only called when running in compatibility mode, which I'm not.

This is the same issue as in #4765, but apparently, it hasn't been fixed completely, yet.

**Comment by denis-anisimov** [comment]
This has been fixed for compatibility mode but then has been reintroduced for NPM accidentally. 
Needs to be fixed.

Thanks for reporting.
