### ISSUE TITLE
CCDM: test SessionCloseLogoutIT fails in bootstrapping v15

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#7600]
There is an exception when running the test in TC that does not happen in local.

```
Caused by: java.lang.AssertionError: Received error message in browser log console right after opening the page, message: [2020-02-14T18:53:31+0000] [SEVERE] http://172.16.1.163:8888/view/VAADIN/build/vaadin-4-2ecfa5ca1a31d0bd1c7b.cache.js 0:8701 "Push connection using long-polling failed!"
```
It might be due to the `@Push` annotation that is in multiple test views (as shown below) instead of in an `AppShell` class, but needs further investigation.

```
[main] ERROR com.vaadin.flow.server.startup.VaadinAppShellInitializer -

Found app shell configuration annotations in non `AppShellConfigurator` classes.
Please create a custom class implementing `AppShellConfigurator` and move the following annotations to it:
    - @Push from com.vaadin.flow.uitest.ui.PushSettingsView
    - @Push from com.vaadin.flow.uitest.ui.LongPollingPushView
    - @Push from com.vaadin.flow.uitest.ui.PushLongPollingUpdateDivView
    - @Push from com.vaadin.flow.uitest.ui.LongPollingMultipleThreadsView
    - @Push from com.vaadin.flow.uitest.ui.SessionCloseLogoutView
    - @Push from com.vaadin.flow.uitest.ui.routing.PushLayout
    - @Push from com.vaadin.flow.uitest.ui.TrackMessageSizeView
    - @Push from com.vaadin.flow.uitest.ui.PushWSUpdateDivView
```

**Comment by denis-anisimov** [comment]
>There is an exception when running the test in TC that does not happen in local.

Yes and no:
- if I run the  `IT` locally then it doesn't fail 
- if I open run the server with view locally and open a view manually then I see the error in the console:


```
vaadin-5-f776035f32111fb70854.cache.js:1 Push connection using long-polling failed!
```

So there is an issue and this is might be quite serious issue.
It doesn't look like Long polling Push is broken but this needs to be investigated. The message at least says that push
connection failed which  is serious.

**Comment by denis-anisimov** [comment]
<img width="805" alt="Screen Shot 2021-03-24 at 3 17 06 PM" src="https://user-images.githubusercontent.com/11425472/112309130-0755d680-8cb4-11eb-8074-eae84680c7dc.png">

**Comment by denis-anisimov** [comment]
I'm going to enable the `IT` via workaround : ignore the error message in the console.
The IT tests totally different thing.
But this ticket:
- has to be fixed
- it should be done ASAP
- can't be closed because test doesn't fail: as I said I will change the `IT`  so it doesn't fail but this ticket describes a bug which is unrelated to the `SessionCloseLogoutIT`

**Comment by denis-anisimov** [comment]
Looks like this is a generic Push issue which can be reproduced without fusion, in Flow 14: https://github.com/vaadin/flow/issues/10103
