### ISSUE TITLE
Write all maven parameters into the token file so they can be set and used for dev mode

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#7626]
There are many maven parameters which  are used by maven plugin whose values are used by dev mode via property values.
E.g. : `pnpmEnable` is a maven parameter, its property is `Constants.SERVLET_PARAMETER_ENABLE_PNPM`.
This property is used inside dev mode.

The issue is: if you configure the maven plugin via  `pnpmEnable` config parameter then it works only for production mode ( it affects only maven plugin code). And it doesn't affect anyhow the dev mode.
Dev mode requires `Constants.SERVLET_PARAMETER_ENABLE_PNPM` property which should be set either via system property (being prefixed with `vaadin.`) or a web init parameter.

It's inconvenient when you use two different ways to configure set value (even for different modes).

What needs to be done:
- detect all such proeprties
- write them into the token file at the maven build stage (in the `prepare-frontend` goal most likely).
- read them at runtime inside `DeploymentConfigurationFactory`  from the token file
- set them as init parameters .

**WARNING** : don't make a regression/bug! Don't set init parameter to the value from the token file if it's already _THERE_ (so it has been set as an explicit parameters). The existing values should take precedence over the values in token file.

**Comment by caalador** [comment]
Note: When adding things to the flow-build-info.json in prepare-fronten the json should be checked in build-frontend for things that should not be there in production mode and be removed.

**Comment by denis-anisimov** [comment]
>Note: When adding things to the flow-build-info.json in prepare-fronten the json should be checked in build-frontend for things that should not be there in production mode and be removed.

I think it's not really a proper way to clean up the token file via modifying it....
I can see a following situation :
- the token file is generated  
- then production mode is executed 
- as a result of previous state the token file content is modified 
- the dev mode is executed somehow so that the token file is not regenerated (e.g. Run via IDE after the production mode)

As a result dev mode will not have setting written by the maven because production mode has removed it.

It seems that the better place to remove the setting is a memory representation of the token file.
But it's read inside `DeploymentConfigurationFactory`, so already in runtime.
(not maven).

In fact I don't like direct access to token file without any model which we have at the moment.
It might be that the information from the token may be read from another place as well. And then 
we will need to remove the properties from there as well. So it's a code duplicaiton.
In that sense the maven plugin `build-frontend` goal is better.
But as I said I see a potential issues with that.

I suggest to avoid removal of anything and just use a special section for dev mode settings which never interfere with production mode: introduce a new Json Object (e.g. `"dev"`) and put all dev mode settings there.
This way production mode keys will not interfere with the dev mode.

**Comment by caalador** [comment]
The main problem is that dev settings should never be available in a production build as they contain paths and other things that just shouldn't be there.

So not modifying it would mean that you should make a flow-dev-build-info.json file that is not added to the production time war, but this will make things more complicated as we need more handling of things.

**Comment by denis-anisimov** [comment]
:(

**Comment by denis-anisimov** [comment]
Do we already have some clean-up code for dev mode things ?

**Comment by caalador** [comment]
BuildFrontendMojo has the `updateBuildFile()` that removes development keys and disables devServer execution.

**Comment by denis-anisimov** [comment]
OK, thanks.
