### ISSUE TITLE
Confusing behaviour when creating a RouterLink to a non-existing target

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#7634]
If you create a `RouterLink` for a component class that doesn't have a `@Route` annotation or for a class that isn't registered as a route, then the following will happen when opening the view:

1. `validateRouteParameters` called from `setRoute` will log a warning saying that navigation may fail with a 404 error
2. `setRoute` will unconditionally do `getUrl` which throws a `NotFoundException`
3. The exception is caught and triggers the `RouteNotFoundError` view instead of the regular error view.

This can be reproduced by running `new RouterLink("", Button.class);` in the constructor of a navigation target class.

We should instead do either of these options:
1. Use a dummy url instead of calling `getUrl` after logging the warning. The warning message should in this case also be clarified since it now implies that the link would work if the route gets registered between the time the link is created and the time when the user actually clicks the link.
2. Remove the logged warning and instead ensure we throw some other exception instead of `NotFoundException` so that the generic error handler is triggered.

**Comment by caalador** [comment]
Same issue as on the bottom in #7071
