### ISSUE TITLE
Make it possible to configure `MessageHandler.MAX_SUSPENDED_TIMEOUT` 

### ISSUE THREAD

**Issue by johannest** [vaadin/flow#7658]
Related to https://github.com/vaadin/flow/issues/7553 

It seems that especially when using Push heavy application with less optimal network the risk of unnecessary forced re-synchronization is too high with current 5s timout: `MAX_SUSPENDED_TIMEOUT = 5000` This will result following chain of actions in the browser:
```
Gave up waiting for message 9 from the server
Resynchronizing from server
Trying to start a new request while another is active
```

And if the application is heavy and network less optimal this might worsen the UX compared to case when waiting the missing request longer.

**Comment by joheriks** [comment]
## Acceptance criteria:
- [ ] Add servlet parameter `maxSuspendTimeout` and pass it to client.
- [ ] Update documentation for V14 and v15.
- [ ] Parameter addition requires update to `vaadin-spring` add-on.
