### ISSUE TITLE
Unsupported operation exception with Text and `setId`

### ISSUE THREAD

**Issue by anasmi** [vaadin/flow#7686]
**Use case** : `setId` for a `Text` component
**Expected** : A proper error message
**Actual** : ` nested exception is java.lang.UnsupportedOperationException)`

Code to reproduce: 

```
import com.vaadin.flow.component.Text;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route("text-view")
public class TextView extends VerticalLayout {

    public TextView(){

        Text text=new Text("Some random text");
        text.setId("some ID");
        add(text);
    }
}

```

**Comment by denis-anisimov** [comment]
`Text`  is not HTML Element. It's a node. It's just a text node.
It's not possible to set `id` to it as any other attribute.
So `expected`  is not correct in this case.
But the exception should be meaningful.

**Comment by anasmi** [comment]
Indeed, didn't check the implementation before. Thanks for pointing out

**Comment by Legioth** [comment]
As a workaround, you can use the `Span` component instead of `Text`.
