### ISSUE TITLE
After calling fowardTo on the server-side to a client-side view, cannot navigate to server-side view

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#7725]
Given :
1. A server-side dashboard view
1. A server-side mater detail view
2. A client-side form view
3. In the server-side mater detail view, call `event.forwardTo("form");` in the `beforeEnter()` method

Expected:
It forwards to the client-side form view, and everything still works.

Actual:
It forwards to the client-side form view, but when you try to navigate to the server-side dashboard view, nothing happens on the UI, even though you can see some requests in the console.

Only on Flow 3.1-SNAPSHOT, can reproduce with the attached project
[https://app.zenhub.com/files/34809191/00078536-94ae-4884-a3fd-2d7fae4cd1a6/download](https://app.zenhub.com/files/34809191/00078536-94ae-4884-a3fd-2d7fae4cd1a6/download)

**Comment by ptdatkhtn** [comment]
The cause is that after using forward to in server-side view, JavascriptBootstrapUI does not reset the value of `isUnknownRoute` property to be false before every checking forward target  action.

fixes by #7719
