### ISSUE TITLE
Allow importing endpoints from generated package

### ISSUE THREAD

**Issue by platosha** [vaadin/flow#7758]
Currently, developers have to use relative imports endpoints:

```typescript
import * as dashboardEndpoint from '../../generated/dashboardEndpoint';
```

This is a little inconvenient for views on different directory hierarchy levels.

We could make importing easier by providing a generated package with all endpoints, similar to `@vaadin/flow-frontend`:

```typescript
import {dashboardEndpoint} from '@vaadin/flow-endpoints';
```

**Comment by Legioth** [comment]
I think we should avoid `@vaadin/` in this context to make it clear which modules are from the npm registry and which ones are generated. Something like `@vaadin-generated/` would be more appropriate.

**Comment by platosha** [comment]
Closing in favour of #9544, see the comparison here: https://github.com/vaadin/flow/issues/9544#issuecomment-768256068.
