### ISSUE TITLE
When application is deployed, we should let the user know what to do next

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7762]
Based on DX tests for running devmode in a separate thread https://github.com/vaadin/flow/issues/7656, the users don't know or notice from the console log message bloat, at least with Jetty but also with Spring Boot, that they could open the browser already and access the application.

It had been also reported in other DX tests that some _newbie_ developers were uncertain on what they should do after starting the application server. "The debug message is not helpful and it is too long". (from @samie)

Thus the proposal is to:
1) Simplify the current debug output to a oneliner, now it is:
```
====================================================================
Vaadin is running in DEBUG MODE.
In order to run your application in production mode and disable debug features, you should enable it by setting the servlet init parameter productionMode to true.
See https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-basic.html for more information about the production mode.
====================================================================
```

2) Output to the console the instruction that the application can be opened in the browser, something like:
```
====================================================================

Your Vaadin application has started and is available by opening http://localhost:8080 in the browser.

Vaadin is running in DEBUG MODE. 
When packaging your application for production, you should disable debug features.
See https://vaadin.com/docs/flow/production/tutorial-production-mode-basic.html for more information

====================================================================
```
This would require determining the used port and possible context path for the application. Also this should be only shown for development/DEBUG mode.

**Comment by mehdi-vaadin** [comment]
It should be tested with Spring Boot, Tomcat, and Websphere too.
