### ISSUE TITLE
Remove logging for Node.js commands and pnpm installing & running

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#7764]
We need to remove ugly logging for running Node.js commands, installing pnpm & running pnpm install:
```
/usr/local/bin/npm --no-update-notifier --no-audit \ 
    install pnpm@4.5.0 

/usr/local/bin/node \ 
    ./node_modules/pnpm/bin/pnpm.js \ 
    --shamefully-hoist=true install 

/usr/local/bin/node \ 
    ./node_modules/webpack-dev-server/bin/webpack-dev-server.js \ 
    --config \ 
    ./webpack.config.js --port 53938 \ 
    --watchDogPort=53937 -d --inline=false
```
Those should not be output at all to the console as they bring no information whatsoever to the users.

**Comment by mehdi-vaadin** [comment]
The above-mentioned logging should not be logged by default. When the logging level is DEBUG, they should be logged.

**Comment by manolo** [comment]
@mshabarov why is it ugly? IMHO for frontend developers is quite useful to know what is happening, it helps to know where are each tool installed.
Is there any customer complaining about this, or is just your feeling?

**Comment by mshabarov** [comment]
@manolo it's not really "ugly", the right word here would be "detailed" or "extra". Sorry for the wording. Node.js and pnpm logs are important for developers, no doubts. 

This ticket has been created as a result of feedback from Vaadiners who performed DX tests for 'Devmode as a separate thread' feature. Some of them complained on extra/detailed logging and asked to reduce logging and add clearer explanations what is going on.

As @mehdi-vaadin said good way is to make them visible under DEBUG level.

**Comment by pleku** [comment]
>@mshabarov why is it ugly? IMHO for frontend developers is quite useful to know what is happening, it helps to know where are each tool installed.
Is there any customer complaining about this, or is just your feeling?

@manolo it gave a frown for 4/4 Java developers in DX tests with with 14.2. I would also question what type of value this output even gives in normal scenarios for frontend developers. Maybe on INFO level but I would not add any extra logging output from frontend tooling processes unless there is a clear need for that.
