### ISSUE TITLE
Flow 3.1 defaults to class scanning in development mode

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#7773]
To reproduce:
1. Check out plain skeleton starter.
2. Update platform version to `16.0-SNAPSHOT` (you may need to also add/enable snapshot repositories)
3. Run `mvn vaadin:prepare-frontend`
4. Check the contents of `target/classes/META-INF/VAADIN/config/flow-build-info.json`
5. Note the line`"devmode.optimizeBundle": true`, which enables class scanning in dev mode.

Expected result: class scanning is disabled by default in dev mode.

Note that Maven plugin configuration parameter`optimizeBundle` sets whether to use class scanning in production mode (default value`true`), while `devMode.optimizeBundle` sets whether to use class scanning in development mode (default value should be `false`). This seems to be a regression as it does not exist in Vaadin 15.0.0.

Version: 16.0-SNAPSHOT (Flow 3.1)
Java: 8

**Comment by denis-anisimov** [comment]
This is kind of "regression" after writing the values specified for the production mode (via pom) into the token file and use them for dev mode avoiding specifying the same properties twice.

So in fact we may not use the same properties for dev mode as for production mode: there some intentionally different values which should not have the same values.
This is true at least for `devmode.optimizeBundle` : the parameter value should not leak into token file and affect dev mode anyhow.
`optimizeBundle` for production mode has to be separated from `devmode.optimizeBundle` .
