### ISSUE TITLE
Custom component not identified as module if no @NpmPackage defined

### ISSUE THREAD

**Issue by anantjagania** [vaadin/flow#7786]
Running vaadin 14.1.8 in dev mode. 

I have a custom component developed using Polymer3 which doesn't need any npm dependencies. Running vaadin app in dev mode with the custom component doesn't detect it has JS module and doesn't load the component when accessed the app in the browser. However, adding fake @NpmPackage works just fine.

Note: This works fine if "build-frontend" defined during packaging.

**Comment by caalador** [comment]
Hi.

Do you have a sample where this fails.
I updated my add-on to 14.1 https://github.com/caalador/TimeSelector/tree/Vaadin14
and the demo works as expected. It also uses only local P3files and no Npm packages.

**Comment by anantjagania** [comment]
I dont have one right now. But will get uploaded soon. 
Also, I had tried with a custom component within app and not as an addon. 

Thanks,
Aanant

**Comment by anantjagania** [comment]
My apology. When I created a fresh project using vaadin starter and added a custom component then things worked fine. I upgraded Vaadin to 14.1.19 and re-arranged certain vaadin dependencies for my main project and custom component work fine now without `@NpmPackage` annotation. 

Thanks for looking into it.
