### ISSUE TITLE
OPTION key does not work in addClickShortcut(key, KeyModifier.ALT)

### ISSUE THREAD

**Issue by ywuliu** [vaadin/flow#7798]
- Description of the bug:
I used this function : addClickShortcut(key, KeyModifier.ALT) I supposed it works on MAC->OPTION key, however, no
- test code: 
Button b=new Button("TEST", x->System.out.println("I am clicked"));
b. addClickShortcut(Key.KEY_S, KeyModifier.ALT);

- Expected behavior: output
- Actual behavior nothing
- Versions:
    - Vaadin / Flow version: 14.1.16
    - Java version 11
    - OS version Mac: 10.15.3
    - Browser version (if applicable) Firfox

**Comment by czp13** [comment]
I have tested, only happening for Firefox. Chrome works fine: 
```
Sending xhr message to server: {"csrfToken":"1fa73b25-a41c-4620-856b-66f86002d5a7","rpc":[{"type":"event","node":1,"event":"keydown","data":{"event.shiftKey":false,"(['KeyS'].indexOf(event.code) !== -1 || ['KeyS'].indexOf(event.key) !== -1) && !event.getModifierState('Shift') && event.getModifierState('Control') && !event.getModifierState('Alt') && !event.getModifierState('AltGraph') && !event.getModifierState('Meta') && (event.stopPropagation() || true)":false,"event.metaKey":false,"event.code":"KeyS","(['KeyS'].indexOf(event.code) !== -1 || ['KeyS'].indexOf(event.key) !== -1) && !event.getModifierState('Shift') && !event.getModifierState('Control') && event.getModifierState('Alt') && !event.getModifierState('AltGraph') && !event.getModifierState('Meta') && (event.stopPropagation() || true)":true,"event.key":"ß","event.isComposing":false,"event.ctrlKey":false,"event.repeat":false,"event.location":0,"event.altKey":true}}],"syncId":4,"clientId":4}
```

In case of firefox the event is not sent at all to server side.

With this custom JS script the triggering is happening (only in the browser log), so it should be possible to add:
```
document.addEventListener('keydown', function(event) {
  if (event.metaKey) {
    console.log('Command key was pressed.');
  } else if (event.altKey) {
    console.log('Option key was pressed.');
  }
}); 
```

**Comment by czp13** [comment]
The problem comes down to browser implementation differences. 
The **option** key keydown event will be different in the browsers:

Mozzila:
```
event.getModifierState('Alt') -> true
event.getModifierState('AltGraph') -> true
```

Chrome:
```
event.getModifierState('Alt') -> true
event.getModifierState('AltGraph') -> false
```

Our event evaluation logic (in flow client js) (when we deciding should it be sent to the server or not, do have a listener for this or not) is built that only supporting when only one modifier is true so check this:

```event.getModifierState('Alt') && !event.getModifierState('AltGraph')```

This will never be true in the case of Mozzila.  We will discuss tomorrow how and whether should we fix this or not. Until then:

You can have this workaround to support both Firefox and Chrome:

````
       // Chrome case:
        b.addClickShortcut(Key.KEY_S, KeyModifier.ALT);
        // Mozzila case:
        b.addClickShortcut(Key.KEY_S, KeyModifier.ALT, KeyModifier.ALT_GRAPH);
```
 
 Tested and it worked in my case (tested with Shortcuts.addShortCutListener() but shall be the same).

**Comment by czp13** [comment]
Hi @ywuliu,

I wanted to let you know that the changes you requested were successfully merged into our main branch on Monday (March 13th). We also cherry-picked the changes for other versions, including 23.x, 24, and 9. To see which versions this fix has been added to, please check the labels on the PR (the fixes will be released next time a specific version have a release)

We hope that you'll be satisfied with the fix, and we welcome any feedback you may have. If you notice anything that isn't working correctly, or if you have any other notes or feedback, please don't hesitate to let us know. Thanks!
