### ISSUE TITLE
[CCDM] Java 11 nightly for master branch fails

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7801]
And has been doing so for a while already https://bender.vaadin.com/viewType.html?buildTypeId=Flow_Nightly_FlowJava10Nightly&tab=buildTypeHistoryList, related to TS compilation for flow-client https://bender.vaadin.com/viewLog.html?buildId=131591&buildTypeId=Flow_Nightly_FlowJava10Nightly&tab=buildLog

**Comment by haijian-vaadin** [comment]
It was a bender configuration issue. Adding `env.INTERN_ARGS` fixed it.
