### ISSUE TITLE
Show a notification in the UI after live reload happened

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7820]
Follow up after #7790. This should give an indication to the users that the reload has happened and the browser doesn't need a refresh, no need to guess "did the reload happen or not". It should be hidden automatically after the focus gets back to the browser window.

Based on early discussions, it should show a token and some timing information related to the reload. For example:
```
#5 14.11.46 Live-reload done.
```
or 
```
Live-reload #5 done 5 seconds ago
```
This information could be also output to browser and server console.

**Comment by joheriks** [comment]
Regarding the server side console message, the JRebel and HotswapAgent plugins currently log (at `info` level) a message when they trigger live reload. To avoid log bloat, we should either not log any additional message in `flow-server` or alternatively, if we do so, demote the existing log messages to `debug` level.

**Comment by joheriks** [comment]
To clarify, the notification should *only* be shown when the live reload mechanism triggers the refresh (and not when the user manually refreshes).
