### ISSUE TITLE
Route not found after recompiling and reloading a page

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#7822]
Sometimes, recompiling and reloading a page causes `NotFoundException` and leads to the available routes page. It doesn't happen all the time. It's likely to happen when the CPU is busy. I can reproduce it with a plain servlet app with the Maven Jetty plugin.

Vaadin version: 14.1.18
OS: macOS Catalina 10.15.3
Browser: Chrome 80
IDE: IntelliJ IDEA Ultimate 2019.2

**Comment by mehdi-vaadin** [comment]
While I'm easily getting this error with `jetty-maven-plugin 9.4.27.v20200227`, I couldn't reproduce it with its latest version `9.4.27.v20200227`. So, the simple solution would be to upgrade the Jetty Maven Plugin to its latest version. It might be helpful to have a note in our docs about it as well.

**Comment by mehdi-vaadin** [comment]
I couldn't reproduce this issue with Spring Boot apps. So, it seems that the problem was only on the Jetty Maven plugin side.

**Comment by mehdi-vaadin** [comment]
Documents and the starters that use Jetty have been updated. So, this issue can be closed.

**Comment by jojule** [comment]
This is a timing issue: When you do not have fast enough computer, this keeps occurring regularly.

For example, on my 4-core 3.3GhZ i5 iMac with 16GB memory and 4TB SSD, route is lost every time one makes a code change to a view. Thus Spring DevTools and reload is completely broken on anything but the latest computers. If you take 2020 MacBook Pro with 8 core i9, reload works reliably; except if you happen to be streaming video at the same time.


My environment where bug can be reproduced reliably:
- MacOS 10.15.5 (19F101)
- iMac (Retina 5K, 27-inch, Mid 2015), 3.3 GHz Quad-Core Intel Core i5, 16 GB 1600 MHz DDR3
- OpenJDK Runtime Environment (build 14.0.1+14)
- Node v14.5.0
- Apache Maven 3.6.3
- Chrome 83.0.4103.116 (Official Build) (64-bit)
- Vaadin 14.3.0
- IntelliJ 2020.1.3 CE


To reproduce
- Download default app starter from https://vaadin.com/start/v14 (Spring Boot)
- Unzip
- `idea pom.xml`
- Run by double-clicking Maven > My Starter Project > Plugins > spring-boot > spring-boot:run
- Open localhost:8080 in Chrome and see that app runs correctly and shows that live reload is available with Spring Boot Devtools and is enabled
- In MainView.java, add `add(new Button("Foo"));` to end of `MainView` method.
- Click Build Project
- Browser incorrectly updates to shows "You are offline" page for "Vaadin Application"
- Reload page
- White page with error: **_Could not navigate to '', Eeason: Couldn't find route for '', Available routes:_**

This is a known bug in Spring Devtools: https://github.com/spring-projects/spring-boot/issues/19543


Proposed fix:
In the "Could not navigate to" view, explain the issue and link to documentation that explains how to work around this by using other available options for reload until underlaying Spring Devtools issue is fixed

**Comment by joheriks** [comment]
Tailored Spring add-on's "route-not-found" page to show an explanatory message as suggested in https://github.com/vaadin/flow/issues/7822#issuecomment-659712226.
