### ISSUE TITLE
Document Live Reload feature using Spring

### ISSUE THREAD

**Issue by jm-ferreira** [vaadin/flow#7830]
Document all necessary steps to use Live Reload with Spring Boot

**Comment by mehdi-vaadin** [comment]
https://github.com/vaadin/flow/issues/7793#issuecomment-600068145 should be added to the document.

**Comment by pleku** [comment]
Mention that it should be enabled out-of-the-box for Spring Boot projects from start.spring.io or vaadin.com. Otherwise, it should be enough to just add the spring-dev-tools dependency to the project.

**Comment by jm-ferreira** [comment]
**Acceptance Criteria**

- [ ]  Verify if spring-dev-tools maven module is set on the Vaadin project
- [ ]  Instruct user to check [https://docs.spring.io/spring-boot/docs/1.5.16.RELEASE/reference/html/using-boot-devtools.html](url)
- [ ] Replace already existing Vaadin docs related to Live Reload on Spring (setting a browser extension is not needed anymore - if they do instruct to disable)
