### ISSUE TITLE
Document Live Reload feature using JRebel

### ISSUE THREAD

**Issue by jm-ferreira** [vaadin/flow#7831]
Document necessary steps to use Live Reload feature using JRebel.
Usage of new JRebel module should be described.

**Comment by pleku** [comment]
Should be enough to document the currently needed steps:
- link to JRebel documentation to install it
- how to enable the plugin that we have now as a separate artifact

**Comment by jm-ferreira** [comment]
**Acceptance Criteria**

- [ ]  Add links to JRebel installation instructions
- [ ]  Instruct on how to add JRebel-Flow-Plugin to the Vaadin project (exclude from production build since it's not a desirable feature)
- [ ]  Mention that ATM there are some exceptions related to running JRebel that can be safely ignored
