### ISSUE TITLE
Document Live Reload feature using HotswapAgent

### ISSUE THREAD

**Issue by jm-ferreira** [vaadin/flow#7832]
Document all necessary steps to use Live Reload with HotswapAgent

**Comment by pleku** [comment]
We should provide the happy path for the users to take to enable the hotswap agent & live reload with Vaadin. Thus we would recommend the JDK where hotswap agent is enabled, provide where to get that, and finally mention that they need to enable it for Maven/Gradle/IDE - whatever they are using to run the project while developing.

**Comment by jm-ferreira** [comment]
**Acceptance Criteria**

- [ ]  Instruct user to download DCEVM and the lastest 1.4.1-SNAPSHOT (2019-04-06) (if a new DCEVM with 1.4.1 is not released then instruct how to override the HotswapAgent version used)
- [ ]  Mention which version of HotswapAgent is needed to run Live Reload (> 1.4.1)
- [ ]  Write step-by-step guide on how to setup JVM and HotswapAgent with Vaadin projects
- [ ]  Mention specific blockers related with different IDE setups
  - There's a flag that should be set in the JVM config when using Netbeans ([https://github.com/vaadin/flow/issues/7836#issuecomment-607443844](url))
