### ISSUE TITLE
Toggle UI for live-reload

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#7834]
When clicking on the live-reload icon in development mode, a debug window should open. This  should contain a toggle button for enabling and disabling live reload for the current browser window.

See UI mockup in #7790 .

**Comment by pleku** [comment]
As the original PR added an `input` element for disabling the live reload, I would switch it to be a `div` instead. The final appearance will probably be a switch though (as is in the mockup).

```
            Element disableButton = Browser.getDocument()
                    .createElement("input");
```

**Comment by joheriks** [comment]
I'll do the window and button as simple divs in this ticket, and leave the tuning for #7835.
