### ISSUE TITLE
The UI for Live Reload client should be beautified

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#7835]
The UI that is created via #7829 will be shown on all the pages during dev mode. At the moment it has no style at all. It should be styled. There are some ideas in #7790 about how it can look like.

**Comment by pleku** [comment]
The parts that should be made pretty are:
- the dialog for the live reload which now only shows the status of the reload and a toggle for enabling and disabling it (#7834 for toggle)
- the "button" for opening the dialog
- the notification show to show after the reload has occurred #7820

**Comment by joheriks** [comment]
## Acceptance criteria 
* The lit-element prototype is added to the branch: https://github.com/vaadin/skeleton-starter-flow-spring/tree/lit-live-reload; should be handed over to a designer for polishing
* The updated web component should be merged back into flow-client
