### ISSUE TITLE
User should be informed that live-reload is active only when actually enabled in the backend

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#7845]
The live reload client-side overlay should inform the user "Live reload is active" only if there is an enabling technology---JRebel, HotswapAgent, or Spring Boot Devtools---running on the server side. For the first two, their corresponding hooks (`flow-jrebel-plugin` and https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-vaadin-plugin/src/main/java/org/hotswap/agent/plugin/vaadin/VaadinPlugin.java) should set a string identifying the technology in the `LiveReload` instance when they initialize; this string can be sent to the client during the connection handshake (Spring Boot Devtools does not require additional server-side support, since the client connects to it on a different port and can determine on that basis whether it is the enabling technology).

**Comment by pleku** [comment]
As discussed, it would be great if we can detect which technology is in use and make sure the client does not try to connect unnecessarily to the server side at all or for the wrong technology.

**Comment by joheriks** [comment]
The status should be yellow if the WS connection is successfully established, but no live-reload-enabling technology exists.
