### ISSUE TITLE
Suppress Live Reload WebSocket connection error in the browser console

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#7847]
Live reload client attempts to connect to the Spring Dev Tools Live Reload server before connecting to the Flow Live Reload server. When Spring Dev Tools is not available, the browser shows the following error message:
```
WebSocket connection to 'ws://localhost:35729/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```
It should be investigated how it can be suppressed. See https://github.com/vaadin/flow/pull/7829#pullrequestreview-376359107

**Comment by joheriks** [comment]
The browser console error may not be possible to suppress. Also, the Spring devtools port is actually configurable via`spring.devtools.livereload.port` in `application.properties`, so we would need to anyway send a property from the server for the port. I therefore propose we use `springBootDevToolsPort` from the server to decide whether we should attempt the WS connection at all (and if so, which port to use).

**Comment by mehdi-vaadin** [comment]
@joheriks that's a good idea. I think we can close this ticket now and create a new ticket for adding `spring.devtools.livereload.port` parameter.

**Comment by joheriks** [comment]
#7970
