### ISSUE TITLE
Unit tests for the DevModeInitializer fail if pnpm is not installed

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#7848]
### Steps to reproduce

1. Checkout the master branch of this repo
2. Make sure `pnpm` is not installed
3. Run `mvn test`

### Expected result

All tests pass

### Actual result

The following tests fail

```
DevModeInitializerClassLoaderTest#should_loadResources_from_customClassLoader
DevModeInitializerTest#should_Run_Updaters_when_NoNodeConfFiles
DevModeInitializerTest#shouldUseFullPathScannerByDefault
DevModeInitializerTest#should_generateTs_files
DevModeInitializerTest#shouldUseByteCodeScannerIfPropertySet
DevModeInitializerTest#should_Run_Updaters
DevModeInitializerTest#should_Run_Updaters_when_NoAppPackageFile
DevModeInitializerTest#should_notGenerateOpenApi_when_EndpointIsNotUsed
DevModeInitializerTest#should_Run_Updaters_when_NoWebpackFile
DevModeInitializerTest#listener_should_stopDevModeHandler_onDestroy
DevModeInitializerTest#should_Not_AddContextListener
DevModeInitializerTest#should_generateOpenApi_when_EndpointPresents
```

According to the log output, an attempt to install pnpm is made

`[main] INFO dev-updater - Installing pnpm v4.5.0 locally. It is suggested to install it globally using 'npm add -g pnpm@4.5.0'`

Yet the error is thrown in `FrontendUtils#getExecutable` when the `cmd` is `pnpm`. When it is `node`, the executable can be found.

**Comment by caalador** [comment]
Seems that running the `DevModeInitializerTest` fails to actually install pnpm so that it can be found.
In the case where I run `TaskRunPnpmInstallTest` first I do get pnpm installed to .vaadin and after that the dev mode initializer test does pass.
Tested on Win10
