### ISSUE TITLE
Fix PWA error message when starting a non-app-shell v15 project

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow#7851]
currently the startup outputs an error message when the PWA annotation is in the wrong place. 

1. This message is scary, completely unnecessarily. The app still works.
2. It offers no help about why the user needs to make this change

Change the log to a more friendly level, saying something like 'we changed the way you configure PWAs, please see this link for more info', then link to documentation that explains what has changed, why it changed, and how users should update their app to make it correct.

**Comment by vlukashov** [comment]
related discussion: https://vaadin.slack.com/archives/CDNTYMS9H/p1584628443199100

**Comment by haijian-vaadin** [comment]
Also change the log level to warning.
