### ISSUE TITLE
EmailValidator doesn't pass on an empty string

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#7899]
Vaadin 14.1.19. I have the following code:

```
binder.forField(new TextField()).withValidator(new EmailValidator()).bind("field");
```

However, the validator marks an empty TextField as invalid, effectively disabling the possibility to have an optional email.

Certainly I can hook a converter before the validator which converts empty string to null and vice versa (it's required anyway because of TextField rejecting nulls), but I wonder whether EmailValidator should pass blank strings?

**Comment by caalador** [comment]
I would guess this is the same for if you use `RegexpValidator`?

**Comment by mvysny** [comment]
I think so. However the RegexpValidator is much more versatile and might be (mis)used to match non-blank strings, so I'm not sure whether RegexpValidator should pass for blank strings. Maybe an optional constructor parameter?

**Comment by caalador** [comment]
Feels like that. Else the regex should be able to accept an empty value.

**Comment by rolandoisidoro** [comment]
Any workaround for this?

**Comment by Artur-** [comment]
```
new EmailValidator() {
protected boolean isValid(String value) {
if ("".equals(value)) return true;
return super.isValid(value);
}
}

```

**Comment by pleku** [comment]
Would be easy to contribute an `OptionalEmailValidator` or such which also accepts "". But we've had `CompositeValidator` earlier on https://vaadin.com/api/framework/7.7.17/com/vaadin/data/validator/CompositeValidator.html, I guess it should be just easy to chain the existing validators.

**Comment by denis-anisimov** [comment]
I suggest to overload `EmailValidator` CTOR  with a boolean value which says whether an empty value should be accepted or not.
That will keep binary compatibility and won't require introducing a new class.
