### ISSUE TITLE
General validators for client-side forms according to JSR-380

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#7932]
As a developer, when creating client-side forms, I want to have a set of built-in validators so that I can use them to validate my data easily. For example, I can check if the value from an email field is a valid email address or not with code like:
```
html`
  import {isEmail} from '...';

  isEmail(getValue(orderModel.customer.email));
`
```

DoD:
A set of constraint functions according to JSR-380.

**Comment by manolo** [comment]
Consider the usage of https://github.com/validatorjs/validator.js as a dependency to avoid rewrite validators that are already included there. Also take a look to the class-validator for typescript project  https://github.com/typestack/class-validator/blob/master/package.json

**Comment by platosha** [comment]
We don’t offer i18n right away here, but future we would want to make error messages translatable.

The built-in error messages could be in English for now, but the constraints should keep their arguments (e. g., limit in `Max(limit)`) and the default message available for i18n translation function to be supported in future.

**Comment by platosha** [comment]
Validator API could look like:

```typescript
export type ValidationCallback<T> = (value: T) => boolean | Promise<boolean>;

export interface Validator<T> {
  callback: ValidationCallback<T>,
  message: string,
  // Limit
  value?: any
}
```
