### ISSUE TITLE
Figure out how to get grid to allow scrolling "million rows" without giving amount of rows

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7968]

**Comment by denis-anisimov** [comment]
The result is :
- it's not possible to use Grid with indefinite size.
- Grid requires size to be set even though the data provider may return infinite  rows of data.

What's possible to do it:
- set Grid size
- detect that Grid is  going to be scrolled until the current size (in advance) 
- update the size ( increase it) on the fly.
- Components team says that scrolling position will be preserved at least.

So it's a matter of a boilerplate code to deal with the size .
Technically we may implement this but that will require dramatic changes in `DataCommunicator`  implementation.
No changes are needed on web component side.
Most likely `grid-flow` connector also will require changes.

One more thing to note: size is not just send to the Grid to set it .
The size value is used in server side and client side to do some calculations.
We will need to figure out what to do with this calculations when size is not defined.

And also one more thing about size: there are almost no issues when one needs just to show items in the Grid (in case size is not provided). I think it won't require a lot of changes to support indefinite size of items in Grid just to display them.
But things becomes more complicated when one needs to update items in Grid:
- add/insert a new row
- modify an existing row

I expect dramatic changes in `DataCommunicator`  to support undefined size and data modifictions.
