### ISSUE TITLE
Live-reload does not recognize Spring Boot DevTools using non-default live-reload server port or not running at all

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#7970]
The live-reload client-side currently always attempts to connect to port 35729 to poll for a potential Spring Boot live-reload server, and if failing, attempts to connect to the dedicated push channel. This approach has two problems:

1. ~For non-Spring applications and Spring not running devtools, the browser console contains an error like the following: `WebSocket connection to 'ws://localhost:35729/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`. The message cannot be supressed and is confusing since it looks like something is wrong.~

2. If a Spring project has changed the port via configuration `spring.devtools.livereload.port` in `application.properties`, it will fall back to the dedicated push channel while the developer probably want to use the custom port. 

3. If Spring Boot Devtools are not running (e.g. `spring-boot-maven-plugin` is configured with `<fork>false</fork>`, this is not detected and the error in 1. is shown in the broswer console. Should detect this state on the server side and initialize the gizmo accordingly (live reload unavailable).
 
Acceptance criteria:
* No error in browser console during normal startup of both Spring and non-Spring applications.
* We identify on the server side that Spring Boot devtools is runing and communicate the correct port to the client side.

**Comment by joheriks** [comment]
The first issue is fixed by #8015

**Comment by pleku** [comment]
### Acceptance Criteria
- emphasis on the documentation in the beginning-ish, that DON'T use multiple hotswap/live reload technologies at the same time (devtools/jrebel/hotswapagent/jetty-scaninterval/tomee...) or the browser reload plugins
- clarify/fix the terminology in the documentation about what is live reload (devtools&jrebel&hotswap) and what is just enabling hotswap (jetty & tomee)
