### ISSUE TITLE
DX test live reload with HotswapAgent

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7999]
Either with manually provided hotswap agent / JDK built with it or we wait for the official release of such.

Considerations:
- using an existing big project
- testing with someone who is already using hotswapagent or familiar with it
- testing with someone who doesn't have anything ready, and discovers that live reload is not activated and then pursues to instructions to enable it

#### Acceptance Criteria
- [x] Use the DX testing template from drive
- [x] Create the DX testing scenario: instructions with steps to take
- [x] Run the tests & record feedback
- [x] Analyze results and conclude corrective actions

**Comment by mehdi-vaadin** [comment]
> using an existing big project

It might be difficult to migrate an existing big project, which is probably based on V14, to V16. So, we can postpone this part to when the live reload feature is ported back to 14.X.

**Comment by pleku** [comment]
>It might be difficult to migrate an existing big project, which is probably based on V14, to V16. So, we can postpone this part to when the live reload feature is ported back to 14.X.

While it might be easier to just test with an existing v14 project, migrating from 14 to 16/17 with the legacy bootstrapping should be rather trivial ? Thus there would be no migration.
