### ISSUE TITLE
Clean package.json on update to 14.2

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#8007]
In some cases there remains in the package.json the dependency target `"@vaadin/flow-deps": "./target/frontend"` and the old hash `"vaadinAppPackageHash": "ecf1e4b3715be..."` thesse should be removed for newer versions.

Especially  the `@vaadin/flow-deps`  if left will fail `(p)npm install` as the target/frontend doesn't get a package.json anymore.

**Comment by pleku** [comment]
>Especially the @vaadin/flow-deps if left will fail (p)npm install as the target/frontend doesn't get a package.json anymore.

Is there a case where this can be left there ? Since sounds to me that if it stays there and fails the build, then it is a blocker ?

**Comment by caalador** [comment]
I just had this with the combo-box demo
