### ISSUE TITLE
Exceptions should not break a UI

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#801]
If exception happens in some event handler (f.e. as a reaction on some client-side event) then UI becomes broken because of internal error.

It's possible to install `ErrorHandler` via `VaadinSession.setErrorHandler` and be notified about exceptions but it's not possible to change UI since it becomes broken when an exception is thrown.

UI should remain functional.

**Comment by mstahv** [comment]
I find this "new behaviour" really nasty for both application developers and end users.

Even if the framework does nothing by default and just kills the UI, we should definitely have a hook for developers to catch "component errors" and let them handle and decide how that app behaves in such situations.

**Comment by samie** [comment]
For similar problematic error handling situation see also #4377

**Comment by CookedApps** [comment]
The UI still freezes in Vaadin 12.0.3 if an exception is thrown inside a `ValueChangeListener`. Example: 
```java
textField.addValueChangeListener(e -> {
    throw new RuntimeException();
});
```
