### ISSUE TITLE
LiveReload Firefox plugin and Vaadin Live Reload race condition

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#8020]
To reproduce:
- Install LiveReload plugin into Firefox
- Open a Spring Boot application with Vaadin live reload gizmo enabled
- Enable Firefox LiveReload plugin
- Edit Java code and compile
- Note that sometimes LiveReload plugin refreshes (in which case there will be no notification about reloading the page), sometimes Vaadin gizmo.

On Chrome with LiveReload plugin it seems to work consistently (Vaadin reload kicks in before plugin), though this is a lucky accident.

Version:  Vaadin 15 with flow-3.2.0.alpha2

**Comment by rucko24** [comment]
Hi, LiveReload with flow 4.1.24 and Springboot 2.2.6.RELEASE not found yet ?


![](https://files.gitter.im/vaadin/flow/OD4v/realoadingLiveReload.gif)

**Comment by joheriks** [comment]
@rucko24 Thanks for your comment. I just tested it with the  [Vaadin 14 spring starter](https://github.com/vaadin/skeleton-starter-flow-spring/tree/v14) using Vaadin version 14.1.25 and Spring Boot and LiveReload worked in both Chrome (LiveReload v2.1.0) and Firefox (LiveReload v. 20.3.0). There seems to be a lot of errors in the console, can you please open a new ticket with the full console output and ideally a minimal example that reproduces the issue.

**Comment by rucko24** [comment]
> @rucko24 Thanks for your comment. I just tested it with the [Vaadin 14 spring starter](https://github.com/vaadin/skeleton-starter-flow-spring/tree/v14) using Vaadin version 14.1.25 and Spring Boot 2.2.6.RELEASE and LiveReload worked in both Chrome (LiveReload v2.1.0) and Firefox (LiveReload v. 20.3.0). There seems to be a lot of errors in the console, can you please open a new ticket with the full console output and ideally a minimal example that reproduces the issue.

Hi there, well everything seems to be working correctly, the server restarts quickly with ctrl + f9 or ctrl + shift + f9 

**everything is going well.**

**Comment by pleku** [comment]
### Acceptance Criteria
- emphasis on the documentation in the beginning-ish, that DON'T use multiple hotswap/live reload technologies at the same time (devtools/jrebel/hotswapagent/jetty-scaninterval/tomee...) or the browser live reload plugins with our live reload
- clarify/fix the terminology in the documentation about what is live reload (devtools&jrebel&hotswap) and what is just enabling hotswap (jetty & tomee)
