### ISSUE TITLE
Maven problem in 15.0.4

### ISSUE THREAD

**Issue by Tz1Git** [vaadin/flow#8033]
Update project pom.xml:

```
        <!-- Dependencies -->
        <vaadin.version>15.0.4</vaadin.version>

```

Then error:

```
  <plugin>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-maven-plugin</artifactId>
                <version>${vaadin.version}</version>
                <executions>
------>       <execution>
                        <goals>
                            <goal>prepare-frontend</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
Error: Plugin execution not covered by lifecycle configuration: com.vaadin:vaadin-maven-plugin:15.0.4:prepare-frontend (execution: default, phase: process-resources)

**Comment by denis-anisimov** [comment]
This is en eclipse issue, right ?
It's related to m2e support in eclipse.
I don't think we can do anything about this.
To avoid the error you may exclude the plugin form the lifecycle.

**Comment by Tz1Git** [comment]
Note that the pom.xml I am using is the one created in "Create a new project with Vaadin" using the CDI and JavaEE option.

Everything was working on 15.0.3. They made a hotfix on 15.0.4 that no longer compiles for WildFly.

I also downloaded a blank project (CDI) and the same problem happens.

Removing the plugin offers this error (first thing we did):

`Failed to execute goal com.vaadin: vaadin-maven-plugin: 15.0.4: build-frontend (default) on proactive project: Execution default of goal com.vaadin: vaadin-maven-plugin: 15.0.4: build-frontend failed : Could not write exported web component module! InvocationTargetException: Path provided by parameter 'outputDirectory' (C: \ Users \ PC1 \ git \ ProAtivo \ target \ frontend) is not a directory -> [Help 1]
`
Bad idea, I code return, so I had to go to the line

  ```
    <! - This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself .-->
            <plugin>
            <groupId> org.eclipse.m2e </groupId>
            <artifactId> lifecycle-mapping </artifactId>
            <version> 1.0.0 </version>
```

And it includes this option:

```
<action>
<execute />
</action>
```

It funcinated, but I don't know if it's the best way to do it. I reported the error because in all cases, you need to test the pom.xml that is generated by the Vaadin page.

**Comment by ugurdoksan** [comment]
I also came accros with this issue in 15.0.4

**Comment by denis-anisimov** [comment]
Sorry at this point I don't understand the issue.

As I understood the steps to reproduce is:
- Create a new project with Vaadin using CDI and Java EE. Where ? On `vaadin.com` site or other way? I guess it comes from `vaadin.com`.
- Update version to `15.0.4` .

Then expected result: no errors, everything works.

What is the current result ?
Is something broken ? In which way it's broken ?
You may not run the project using maven command line ?

**Comment by DManstrator** [comment]
I stumbled about the same problem yesterday **but within Visual Studio Code**. When working with Vaadin 15.0.2 I had no problem, after updating to 15.0.4, VS Code gave me a similar error message to the one already mentioned here:
```
Conflicting lifecycle mapping (plugin execution "com.vaadin:vaadin-maven-plugin:15.0.4:prepare-frontend (execution: default, phase: process-resources)"). To enable full functionality, remove the conflicting mapping and run Maven->Update Project Configuration.
```
After downgrading to Vaadin 15.0.2, it worked again.

My VS Code Setup:
```
Version: 1.44.0 (user setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:31:18.860Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
```

POM file:
```xml
<plugin>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-maven-plugin</artifactId>
    <version>${vaadin.version}</version>
    <executions>
        <execution>
            <goals>
                <goal>prepare-frontend</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <pnpmEnable>true</pnpmEnable>
    </configuration>
</plugin>
```

**Comment by RainerGanss** [comment]
Exact same problem as @DManstrator

**Comment by DManstrator** [comment]
This is also an issue with Vaadin 15.0.5 which I want to use since it fixes a security issue. But not for Vaadin 15.0.3 and lower. For me it's not an Eclipse or general IDE issue at this point.

**Comment by Tz1Git** [comment]
In my post I put what to do to work. Take a look up there

**Comment by RainerGanss** [comment]
@Tz1Git I use VS Code - not eclipse.

**Comment by DManstrator** [comment]
@Tz1Git Thank you for that but I'm convinced it should be in interest of Vaadin to fix that and not the job of everyone implementing a hotfix for it. And I'm using VS Code as mentioned above so this is nothing for me sadly.

**Comment by Artur-** [comment]
Probably caused by https://github.com/vaadin/flow/commit/e740b880e01fd773e13cc41b90934ecc4de52f51#diff-edb73af5d80cb83b99c25aea7abf12b0 which incorrectly states that `prepare-frontend` should be both ignored and executed
