### ISSUE TITLE
There should be a way to avoid Vaadin reliance on cookies

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#8039]
See this ticket : https://github.com/vaadin/framework/issues/814

It should be possible to use Vaadin app without any reliance on cookies.

Vaadin app as any other Java servlet app set `JSESSIONID` cookie on first server response to track an HTTP session.
Vaadin relies on HTTP session servlet mechanism which relies on this cookie.
Sometimes cookies don't work: e.g. in embedding applications ( see https://github.com/vaadin/flow/issues/5769).
We should provide a way to configure the app do not rely on cookies and somehow track the session id in every request/response .
That will allow to make app working even if cookies are not supported for some reasons.

**Comment by pleku** [comment]
In this case as we claim that we have embedding support and did not already explicitly mention that it is not supported cross domain in Safari, I'm willing to rule this out as an bug as we have a good idea how to fix this for those users who are relying to get this fixed.

**Comment by martinisraelsen** [comment]
Thanks @pleku. I really really really appreciate it!

**Comment by pleku** [comment]
Related changes done to a custom fork of Framework 7.7
https://github.com/pontusbostrom/framework/commit/9bb9001607404ea29add0b06044a540ffbaaa9dd
https://github.com/pontusbostrom/framework/commit/ab2232d1f09cf16ab11459eac2b9dac0832f7f45
https://github.com/pontusbostrom/framework/commit/9dcd466e75930954f0f482a8471a7401b1d88462

**Comment by pleku** [comment]
>Related changes done

Which (pointed by @Legioth elsewhere) open the door for possible session fixation attack - so we'll have to look at other alternatives to this.

**Comment by Legioth** [comment]
It depends on the use case whether the session fixation risk can be mitigated or is acceptable as-is. The challenge is that that kind of evaluation is highly dependent on specifics of the application. It also means that if we enable this kind of functionality, then it should be done in a way that makes the application developer explicitly aware of the risks. Using a configuration property such as `enableSessionFixationAttacks` was suggested in an internal discussion.

Other alternatives that I'm aware of:
* Track the session based on the [SSL connection](https://docs.oracle.com/javaee/7/api/javax/servlet/SessionTrackingMode.html#SSL). I haven't looked into whether this is practical and whether there are any security implications to keep in mind. This makes local development slightly more complicated since you would either need to manage a self-signed certificate for your localhost or alternatively do local development with a different session tracking strategy.
* Pass the session id in a custom header value. The benefit compared to session cookies is that they are passed through by Safari with the regular CORS setup. The benefit compared to passing the id in the URL is that session fixation is not an issue. The main question is how to integrate this with the servlet container.
* Same as above with custom header value, but implement our own session map instead of integrating with the servlet container. This requires quite much custom logic since we also need to take care of e.g. session invalidation timeouts. There's also the security implication of having all the sessions in the system easily available to all code running the system. The same capabilities has since been removed from the servlet API for security reasons (see `HttpSessionContext`).
* Pass requests through a proxy on the origin host so that the requests are same-site from the browser's point of view. This is mostly a candidate for internal embedding but it's not practical for components that are intended to be embedded by third parties.
* Rewrite the component using client-side logic and a stateless communication protocol (e.g. JWT for authentication).

**Comment by denis-anisimov** [comment]
>Track the session based on the SSL connection

>This makes local development slightly more complicated 

Does it ?
When you develop you may use normal cookies mechanism even if you need to test how the component is embedded.
Then you deploy your app (so that it may be embedded) and you can configure it so that it uses SSL tacking mode

So this could be a kind of dev mode (cookie) vs production mode ( SSL ).
During dev mode you don't have any SSL related issues since cookies are used.
There can be differences between cookie mode vs SSL mode but that's our responsibility to eliminate all such issues.

**Comment by denis-anisimov** [comment]
It seems `SessionTrackingMode.SSL` the way to go.

I was able to configure web component (embedded) app to use SSL and `SessionTrackingMode.SSL`.
Checked the initial bug https://github.com/vaadin/flow/issues/5769: embedded app works in Safari with `SessionTrackingMode.SSL` .

Some notes:
- the steps to reproduce from https://github.com/vaadin/flow/issues/5769 will need corrections because of using SSL. The replacements are : port number and URL for the embedded application because the app will be deployed to some real web server which is configured to use SSL and it can't be Jetty: jetty doesn't support `SessionTrackingMode.SSL`.
- I've uses Tomcat with configured SSL and `SessionTrackingMode.SSL` as described here : https://tomcat.apache.org/tomcat-9.0-doc/ssl-howto.html#SSL_and_Tomcat.
- It seems we have another bug related to `SessionTrackingMode.SSL` + Push in Safari but I will make another ticket for that.
- We need a documentation ticket how to configure embedded app to work with `SessionTrackingMode.SSL`. I will make a ticket about that.

Overall: I'm closing this ticket since it's possible to use  `SessionTrackingMode.SSL` as a tracking mode instead of cookies and this is the simplest and reliable built-in mechanism for HTTP session tracking.
As I already mentioned: you don't have to use this mode during development. 
If you develop embedded web component that you do all testing locally and you may use `localhost` as a domain name and there are no issues with cross-domain cookies.
But once you deploy the app in production you should use `SessionTrackingMode.SSL`.

**Comment by denis-anisimov** [comment]
Please let me know if there are any issues with the suggested approach or the ticket should be reopened for some reason.

**Comment by Legioth** [comment]
There are apparently some disclaimers related to using the `SSL` mode, as described e.g. here https://stackoverflow.com/questions/2817325/retrieve-ssl-session-id-in-asp-net/2885177#2885177. I don't know how big of a problem those are in practice.

**Comment by denis-anisimov** [comment]
Hmmm...
It seems this is a very specific case for using the SSL mode....
The recommendation is not to use  SSL Session ID for user identification.
But I don't see a direct recommendation not use SSL mode for tracking HTTP session.

**Comment by Legioth** [comment]
The underlying reason appears to be the possibility that the id changes unexpectedly at the discretion of the user agent. From that point of view, a lost HTTP session has just as big impact on the user as lost user identification would have.

**Comment by denis-anisimov** [comment]
Is it really about losing HTTP session ?
Because I see this is a bug (in a web server impl) : it doesn't preserve the session at all so technically it means that HTTP session does not work at all.
But (I'm not exactly sure) it's about unreliable SSL session ID : you may not use it because it doesn't have to be the same (for the same HTTP session). But I think the session should be preserved.....

**Comment by Legioth** [comment]
My understanding is that the client may trigger creating a new SSL session id without regards for any side effects. The case mentioned in the linked example was that opening a new tab in IE8 makes the new tab use a newly generated session id, thus causing the new tab to also have a different HTTP session.

We don't support IE8, but there is a possibility that other browsers may also behave in a similar way since the specification doesn't encourage the browser to retain the id.

**Comment by denis-anisimov** [comment]
>The case mentioned in the linked example was that opening a new tab in IE8 makes the new tab use a newly generated session id

looks like that

>thus causing the new tab to also have a different HTTP session.

Not sure about that.
The new tab will use a new HTTP session. Yes.
But I don't see a statement that previous tab will reset its session and will use a new one....
May be this is true.
I don't know.

>We don't support IE8, but there is a possibility that other browsers may also behave in a similar way since the specification doesn't encourage the browser to retain the id.

If there is an issue then yes, there can be other browsers which does the same.

But let's return back to the original problem:
- at the moment SSL is the only feasible way to solve the issue with cookies.
- every other alternative is not a bug fix but rather a huge new feature: I don't see how this can be done as a fix . I mean it requires design decision , a lot of discussions and a lot of code to implement.

There is no any read-made solution to support HTTP session other than 3 values of `SessionTrackingMode` enum.

So we will have to either totally drop HTTP session support and write our own implementation which doesn't depend on HTTP session anyhow :
- this is risky as a hell: can introduce a lot of regressions
- I can't even imagine how much code needs to be rewritten and how much new code should be written (just to support custom HTTP session impl).

So I would say this is almost not an option.

Another option is to rewrite embedded web components impl.
And this is also a totally new feature which also requires design decision and a lot of work.

Technically : this BFP means that we don't have any embedding web components support at all and it needs to be written from scratch.
I can say for myself: I cannot do this alone as a BFP fix.

So I would suggest to go with SSL until it's proven that there are exact issues and reasons why we can't use it.
(though there is already one with Safari and Push).

**Comment by Legioth** [comment]
Agreed. The big question is whether `SessionTrackingMode.SSL` would be useful enough in real life. I don't know any other way of finding that out than extensively testing a prototype to find out whether there are any practical issues. For any shortcomings that we identify, we would need to verify with Vaadin users interested in this functionality whether the limitations are blockers for their use case.

**Comment by denis-anisimov** [comment]
Sure.

**Comment by martinisraelsen** [comment]
I'd be more than happy to do some testing. Is this already released? If not, how would I go about testing it?

**Comment by pleku** [comment]
@martinisraelsen the way to make it work using SessionTrackingMode.SSL is explained here https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/embedding-flow-applications/tutorial-webcomponent-intro.asciidoc#using-an-external-embeddable-application

This approach did not require any changes to Flow itself. Please let us know if it is not clear enough or if you run into some issues with this, thanks.

**Comment by martinisraelsen** [comment]
@pleku got it! Will try that approach today. Thanks!!

**Comment by martinisraelsen** [comment]
I tried switching to SessionTrackingMode.SSL but was not able to get it to work with a Spring-boot application. 

The "Cookies Disabled" messages shows up consistently in Safari, Chrome and FF.

Flow: 14.1.27
Tomcat: 9.0.34
Spring-boot: 2.2.6.RELEASE

Not sure if it's because of something in the sample code, spring boot or something completely different. 

I have attached a super small embedded component.

[embedded-app-spring.zip](https://github.com/vaadin/flow/files/4548017/embedded-app-spring.zip)

**Comment by denis-anisimov** [comment]
It is necessary to enable SSL for the target server.
Since you are using Spring boot I have suspicion that you have not configured Tomcat for SSL (since Spring boot uses embedded Tomcat which I have no idea how to configure for SSL).

The project should be deployed to some server which is configured to use SSL.
It still may be a Spring boot app but you won't be able run the app via Java main class or via `spring-boot:run` : it needs to be deployed .

Have you configured anyhow the target server to support SSL?

**Comment by martinisraelsen** [comment]
> It is necessary to enable SSL for the target server.
> Since you are using Spring boot I have suspicion that you have not configured Tomcat for SSL (since Spring boot uses embedded Tomcat which I have no idea how to configure for SSL).
> 
> The project should be deployed to some server which is configured to use SSL.
> It still may be a Spring boot app but you won't be able run the app via Java main class or via `spring-boot:run` : it needs to be deployed .
> 
> Have you configured anyhow the target server to support SSL?

Hi @denis-anisimov. As far as I know yes. The issue appears both when I use the embedded tomcat and also if the app is deployed as a regular WAR file to the server. 

I added a ServletContextInitializer and I can see in the log file that the session tracking mode is changed (this is from the zip file I attached in the previous reply.

```
public class SessionTrackingConfigListener implements ServletContextInitializer {

   @Override
   public void onStartup(ServletContext context) throws ServletException {
      EnumSet<SessionTrackingMode> modes = EnumSet.of(SessionTrackingMode.SSL);

      System.out.println("**************************************************************");
      System.out.println("Setting SSL Tracking Mode to " + modes);
      context.setSessionTrackingModes(modes);
      System.out.println("**************************************************************");
   }
}
```

I also noted that if I change the ServletContextInitializer to see the session tracking mode to COOKIE, then I do not get the "cookies disabled" message and if I change it back to SSL then I get the "cookies disabled" message again. So as far as I can tell, Tomcat is using SSL tracking mode.

**Comment by denis-anisimov** [comment]
@martinisraelsen , I don't see any additional configuration in the pom file of your project which enables SSL for the embedded Tomcat.

So I'm pretty sure you have no SSL/HTTPS enabled in Tomcat.

>So as far as I can tell, Tomcat is using SSL tracking mode.

SSL session tracking mode is not the same as enabling SSL/HTTPS.

SSL session tracking mode can't work without HTTS/SSL for the web server.

SSL/HTTS may work without SSL session tracking mode.
What I see from your response: you've added the `ServletContextInitializer`  which switched the session tracking mode.
This is trivial action and is not enough to enable SSL session tracking mode.
HTTPS is required for SSL session tracking mode. It's far away from trivial to configure the web server to work via HTTPS(SSL).

So either you made this web server configuration and know that HTTPS works or you haven't configure web server for HTTPS and then it doesn't work of course.

So could you please point me the exact lines in the pom file which enables HTTPS for the embedded Tomcat if I'm wrong: I'm interested in HTTPS configuration via maven.

Here is quite long description with many many steps which are required to configure the Tomcat to use HTTPS/SSL : **https://tomcat.apache.org/tomcat-9.0-doc/ssl-howto.html**

So have you done this config for your external Tomcat ?

You have to have at least a certificate. Do you have self-signed certificate or some trusted certificate for your domain ?

I spent several hours to configure my Tomcat and make sure that SSL tracking mode works for embedded app loaded from different domain because of SSL/HTTPS web server configuration:
so this is far away from easy/trivial.

You most likely should have problem with self signed certificate in your browser/OS. I had to make it trusted manually to be able to use HTTPS with Tomcat.

So, 
just to make sure we are on the same page: you are able to use HTTPS protocol with your Tomcat ?
So the URL "https://localhost:443" opens some page in your browser ?

**Comment by martinisraelsen** [comment]
@denis-anisimov 

For Spring-boot apps HTTPS settings can be specified in application.properties:



server.port=8443
server.ssl.key-store=[keystore]
server.ssl.key-store-password=[password]
server.ssl.key-password=[password]

The stand-along server is indeed using HTTPS.

You can see it here: https://test.bookingcentral.com/embedded-app-spring/embedded

**Comment by denis-anisimov** [comment]
Ah, I missed that.
Alright, I see it uses HTTPS indeed.
I will check the app in details, thank you.

**Comment by martinisraelsen** [comment]
@denis-anisimov 

I just modified the embedded-app (same file as the file) and logged what the SessionTrackingMode is in the request. It is set to COOKIE, URL.

The ServletContextInitializer 

```
public class SessionTrackingConfigListener implements ServletContextInitializer {

   @Override
   public void onStartup(ServletContext context) throws ServletException {
      EnumSet<SessionTrackingMode> modes = EnumSet.of(SessionTrackingMode.SSL);

      System.out.println("**************************************************************");
      System.out.println("Setting SSL Tracking Mode to " + modes);
      context.setSessionTrackingModes(modes);
      System.out.println("**************************************************************");

   }
}
```

is definitely being run, so it seems that something else is re-setting the tracking mode after the ServletContextInitializater. It may be that spring-boot is involved.

**Comment by denis-anisimov** [comment]
So it means that the app doesn't use SSL session tracking mode and this is what I suspected.
So this is an application issue, right ?

**Comment by martinisraelsen** [comment]
@denis-anisimov Your're right. I ended up redoing the HTTPS configuration in server.xml and it seemed to fix it. Thanks for your help.

**Comment by denis-anisimov** [comment]
Very good !
I'm glad it's working.

**Comment by mvysny** [comment]
What about support of the URL-based session tracking? Vaadin doesn't support this at the moment - it will endlessly reload the page and eventually will give up stating "Cookies disabled". SSL session tracking is unreliable as discussed above.
