### ISSUE TITLE
vaadin-maven-plugin  on JDK 14

### ISSUE THREAD

**Issue by linux-china** [vaadin/flow#8046]
Can not compile the project with JDK 14. 

```
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:14.1.25:build-frontend (default) on project alibaba-broker-server: Execution default of goal com.vaadin:vaadin-maven-plugin:14.1.25:build-frontend failed: Unsupported class file major version 58 -> [Help 1]
```

**Comment by denis-anisimov** [comment]
I'm going to make a cherry-pick for this ticket which is fixed in newer versions already.
But  I'm not sure when it will be released.
I recommend to use latest versions: `14.2`.

**Comment by cachorios** [comment]
NO esta anadando? no puedo hacer un deply me da error
Unsupported class file major version 58!!!!!!

**Comment by cachorios** [comment]
nadie tiene la solucion?

**Comment by cachorios** [comment]
@caalador caalador added this to Needs triage in Java Framework bugs & maintenance (Vaadin 10+)

alli no hay nada!!!
