### ISSUE TITLE
DataProvider - Unknown size

### ISSUE THREAD

**Issue by Springrbua** [vaadin/flow#8052]
### Problem

In a flow-application I am currently working on, I am trying to display data in a `vaadin-grid`, using a `DataProvider`. However, I was not able to implement a `DataProvider` for our usecase.
The problem I am facing is, that the `DataProvider` needs to know the `size` of the datasource.
Since my datasource might contain a lot of data and other users could insert or delete some rows, I don't know the total size of it.
Also, I would like to use keyset pagination, since offset pagination is not very efficient.
During my research, regarding keyset pagination with `Vaadin`, I found an [issue for vaadin framework](https://github.com/vaadin/framework/issues/10014), where it is stated, that the `DataProvider` does not prevent you from using keyset pagination, since `offset` and `limit` can be interpreted by the implementation. However, a mapping between offset and keyset seems to be possible only if all entries are cached in memory, which is not possible if there are too many entries. Also, caching the entries in memory would not take into account the changes of other users.

So I would like to be able to implement a `DataProvider`, without needing to know the total size of the datasource and with keyset pagination, instead of offset pagination.

### Notes
I was trying to implement this on my own, by extending the `vaadin-grid` also on the client side but was not able to do that until now. I found, that the implementation probably needs to be quite different then the offset version and has some limitations compared to it.
For example, you would only be able to scroll within the client side cache, since you need to know the key(s) of the last entry of the block to be able to load the next block.
With offset pagination instead, you would be able to scroll to an absolute position at any time, since you could calculate the offset out of the scroll position.
The scrollbar should therefore probably be hidden, since it would jump around whenever the client side cache changes.

**Comment by pleku** [comment]
Some related prototyping for `<vaadin-grid>` with unknown size done here https://github.com/vaadin/flow/issues/7968

Next step: #8055

**Comment by mshabarov** [comment]
## Acceptance criteria:

- 'No size' implementation for DataProvider/DataCommunicator/Components has been created, taking into account the design from #8055.
- Proposed implementation should treat all the components with lazy load (Grid, Tree Grid, ComboBox).
- Use case example has been demonstrated and agreed.

**Comment by pleku** [comment]
To be available in Flow 4.0.0.alpha1 and Vaadin 17.0.0.alpha6 by using just providing the items lazily with the fetch callback:
```java
        GridLazyDataView<Item> lazyDataView = grid
                .setItems(query -> fakeBackend
                        .generateItems(query.getOffset(), query.getLimit()));
        /*
         * By default the grid will initially adjust the scrollbar to 200 items
         * and as the user scrolls down it automatically increases the size by
         * 200 until the backend runs out of items.
         *
         * Both the estimated item count and its increase can be customized
         * to allow the user to scroll down faster when the backend will
         * have a lot of items.
         */
        lazyDataView.setItemCountEstimate(1000);
        lazyDataView.setItemCountEstimateIncrease(1000);
```

**Comment by Springrbua** [comment]
@pleku while the DataProvider now seems to work, without knowing the size, it still requires you to use offset pagination.
Are there any plans on supporting keyset pagination too?

**Comment by mshabarov** [comment]
@Springrbua thank you for asking. We have [https://github.com/vaadin/flow/issues/8557](this ticket) for that in the backlog.

**Comment by Springrbua** [comment]
Thank you for the information :)
