### ISSUE TITLE
Build validation fails because FrontendProtocolIT tests in 2.1

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#8063]
`FrontendProtocolIT::loadComponentFromEs6Path` and 
`FrontendProtocolIT::loadComponentFromEs6Property`
uses some hybrid mode to test template in the compatibility mode.
E.g. `loadComponentFromEs6Path`  uses production mode without production mode (production mode 
is set as a property so the app is working in production but the resources are not compiled for production).

That hybrid mode apparently causes the issues being tested in the modern Chrome browser which doesn't support anymore `html imports`.
As a result an imported component is not initialized at all: polyfills have to be loaded from the URL `frontend://bower_components/webcomponentsjs/webcomponents-loader.js`  but it's not loaded because the URL is resolved to a resource somewhere inside `frontend-es6`  and it just doesn't exist (e.g. in `loadComponentFromEs6Path` case : resources has not been compiled).

**Comment by caalador** [comment]
The same tests have been failing the `Flow 2.2 nightly snapshot` build since 12 Apr

**Comment by pleku** [comment]
Since no app should be running similarly in "production mode" but not with a production built frontend bundle, this is not really a blocker issue as things still work both in "real" devmode & production mode.

**Comment by mcollovati** [comment]
Closing because compatibility mode is not supported anymore in the maintained Vaadin versions.
