### ISSUE TITLE
Design API for providing data provider data to outside

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#8074]
Based on #4510, draft API design to support the following use cases:
- When showing a grid to the user, I need to know the current data (including sorting and filtering) so I can export exactly same data to a .pdf
  - In context of this issue, this is only about being able to get the data required for the exporting from the grid, not about exporting it to a pdf itself (even though that would be a nifty feature!)
  - This must take into account the difference between in-memory and lazy data providers - the users still most likely want all the data to be included in the data set, not just the rendered subset. The example should show how to achieve the generating for the whole data set with current filtering and sorting applied, even though the component has only rendered a subset of the data. For the lazy data provider this will mean getting all the items from the backend and it might be costly (like with `selectAll` which is not enabled by default for lazy data providers in grid).
  - It is up to the developers to decide how the render the data, the important part would be in getting the same data set in the same ordering
- When showing data to a user in a grid, I want to know the data set fetched by the data provider, so, that I can expand/select the first item automatically and provide controls for the user to navigate to the next/previous item
- When using a data provider in a component, I want to easily show the size of the data set in another component so that I can display it in an external component

### Acceptance Criteria
- Provide an API design with usage examples on how to achieve the ^ cases with the API from `DataProvider`/components. Grid can be the example component. Can also contain an example of how it works without any API changes, if possible. Implementation can be stubbed

**Comment by Legioth** [comment]
All this data is already tracked internally by `DataCommunicator`. I wonder whether it would be appropriate to expose all those as public API in that class rather than tying it to any specific component. A component such as Grid can of course offer shorthand methods for specific cases, but the main API would still be in the universally used `DataCommunicator` class.

**Comment by pleku** [comment]
I agree that it doesn't necessarily make sense to expose this API in the components directly. `DataCommunicator` has been otherwise an implementation detail thus far, so there might be some discoverability issues with it. So thus an API for `DataProvider` or the components might make more sense.

**Comment by Legioth** [comment]
I don't see how API in `DataProvider` can help here since it is stateless and thus isn't aware of what filtering and sorting is currently used. If we accept that you have to supply those manually, then you could just as well use the existing `fetch` and `size` methods from that interface.

**Comment by pleku** [comment]
I agree, not `DataProvider` but maybe `HasDataProvider` which is the component facing part and I see it on general level part of the DataProvider concept. I should have been more clear with this. But I don't also know if it should be there either, just would like to keep all options on the table that make it easy to use and discover.

**Comment by caalador** [comment]
Component.getActiveItems(); 

-- with DataCommunicator
!-- get activeKeyOrder from DataCommunicator and stream through keyMapper to serve item stream --!
!-- activeKeyOrder could be sent in an event, keyMapper has a public getter --!

-- else
!-- getQuery with range --!
!-- Who stores the query? --!

Component.getAllItems(); !-- Get all items from DataProvider using latest query with range [0, size()]  --!
!-- Who stores the query? --!

DataRequestObserver !-- Listen for data requests and get event with query? --!
!-- For component with DataCommunicator activeKeyOrder should be in event --!
```
DataRequestEvent {
    !-- Should always be there --!
    Query query
    DataProvider<T, F> dataProvider

    !-- May or may not be there depending if component has DataCommunicator --!
    List<String> activeKeyOrder
    DataCommunicator<T> dataCommunicator

    Stream<T> getActiveItems() {
        if(dataCommunicator != null)
            keyMapper = dataCommunicator.getKeyMapper()
            return activeKeyOrder.stream.map(key -> keyMapper.get(key))
        return dataProvider.fetch(query)
    }

    int size() {
        if(dataCommunicator != null)
            return dataCommunicator.getAssumedSize(); // new method
        return dataProvider.getSize(query);
    }
}
```
Export data
```
new Button("Export pdf", click -> PdfGenerator.get().export(grid.getAllItems()));
```
Active set with next/prev navigation
```
List<T> activeItems = new ArrayList<>();
Button previous("pre", click -> grid.select(activeItems.indexOf(grid.getSelectedItems().get(0))-1));
Button next("next", click -> grid.select(activeItems.indexOf(grid.getSelectedItems().get(0))+1));

grid.addDataRequestObserver(requestEvent -> {
    requestEvent.getActiveItems().forEach(acitveItems::add);
    grid.select(activeItems.get(0));
})
```

Updating dataset size into a component
```
Text contentSize;
grid.addDataRequestObserver(requestEvent -> {
    contentSize.setValue(requestEvent.size());
})
```

**Comment by Legioth** [comment]
> Who stores the query

The query is a function of the component's internal state. In the case of Grid, sorting options are a state of which columns are currently set to be sorted. In ComboBox, the filter is directly derived from the text entered into the field.

I'm not sure I understand the purpose of the data request observer. It seems like an implementation detail what data is fetched when - if that's all I need, then I could just as well wrap the `DataProvider` instance instead.

What seems more relevant would be to get notifications when the active items, query conditions or the current assumed size changes. This is technically quite close to a "data request event", but I think the semantic difference is quite significiant.

**Comment by caalador** [comment]
Grabbing the query will help in the generic sense that then to get the same dataset we don't have to be bound to a component implementation.

I expect users will also want to have it for ListDataProvider etc where you usually do not handle the fetch and just create it by giving a bunch of items. Wrapping generated instances is not what they want to do.

Also the idea for the Observer(could be listener) is to do for item set changes (new range, filtering, sorting...) what DataProviderListener does for refresh events. 

There is also the problem with not having enough data in dataprovider as grid will request pages before also so you wouldn't actually know what the first visible item is when not in the initial load.

**Comment by Legioth** [comment]
I'm not sure I understand exactly what you mean. Could you come up with some enlightening code examples?

**Comment by caalador** [comment]
## New API
```java
/* Query with range [0, Integer.MAX_VALUE] */
Stream<T>       HasDataProvider.getAllItems();
/* Listener for when a new data is sent to the client */
Registration    HasDataProvider.addActiveDataChangeListener(DataChangeListener);
```

```java
DataChangeListener {
    /* Stream of the latest items sent to the client */
    /* Stream is sorted + filtered same as last set sent to client */
    Stream<T> getRequestedItems()
    /* Full size of data to be had with current filters */
    int size()
}
```

## Usage Examples
**Export data by current filters as sorting:**
```java
new Button("Export pdf", click -> PdfGenerator.get().export(grid.getAllItems()));
```

**Next/prev navigation for sorted and filtered current item set**
Having component specific methods makes this simpler see sample at end
```java
// Requested items should contain the latest item set sen to the client
// this means each dataChange the list should be re-populated
List<T> requestedItems = new ArrayList<>();
Button previous("pre", click -> grid.select(
        requestedItems.indexOf(grid.getSelectedItems().get(0))-1
    ));
Button next("next", click -> grid.select(
        requestedItems.indexOf(grid.getSelectedItems().get(0))+1
    ));

grid.addActiveDataChangeListener(changeEvent -> {
    // Clear list to have the correct items and ordering.
    requestedItems.clear();
    changeEvent.getRequestedItems().forEach(requestedItems::add);
    
    // if no selection select first requested item 
    // (on first load this is the first item in the grid)
    if(grid.getSelectedItems().isEmpty())
        grid.select(requestedItems.get(0));
})
```

**Update current item set size into another component**
```java
Text contentSize;
grid.addActiveDataChangeListener(changeEvent -> {
    contentSize.setValue(changeEvent.size());
})
```

### New component features
Component (is this usefull apart from grid?) should add a method for getting the
next-/previousItem for a given item.
```java
/* Get the next item from the given item in the current known items.
 * Fetch new rows if needed.
 */
T nextItem(T);
/* Get the previous item from the given item in the current known items.
 * Fetch new rows if needed.
 */
T previousItem(T);
/* Get item on given row. If row outside of currently active items fetch 
 * a new Range of current up/down to requested row 
 */
T getItemOnRow(int);
/* Select item on given row. getItemOnRow forst and then select item. */
void selectItemOnRow(int);
```

**Select first item on grid load, buttons to select next and previous in grid.**
```java
Button previous("pre", click -> grid.select(
        grid.previousItem(grid.getSelectedItems().get(0))
    ));
Button next("next", click -> grid.select(
        grid.nextItem(grid.getSelectedItems().get(0))
    ));

// Select initial item from grid
grid.selectItemOnRow(0);
```

**Showing details on grid items in order without doing selection in grid.**
```java
DetailCard {
    Button previous("pre", click -> showDetails(grid.nextItem(currentItem)));
    Button next("next", click -> showDetails(grid.nextItem(currentItem)));
}
```

**Comment by pleku** [comment]
One small nit on https://github.com/vaadin/flow/issues/8074#issuecomment-618952494 is that some getters are not named as getters like the convention is.

**Comment by caalador** [comment]
Updated, also changed size() to getDataSize()

**Comment by pleku** [comment]
Another comment about 
```java
Registration    HasDataProvider.addActiveDataChangeListener(DataChangeListener);
```
How is the relation to the existing 
```java
    /**
     * Adds a data provider listener. The listener is called when some piece of
     * data is updated.
     * <p>
     * The {@link #refreshAll()} method fires {@link DataChangeEvent} each time
     * when it's called. It allows to update UI components when user changes
     * something in the underlying data.
     *
     * @see #refreshAll()
     * @param listener
     *            the data change listener, not null
     * @return a registration for the listener
     */
    Registration addDataProviderListener(DataProviderListener<T> listener);
```
which actually happens to fire a `DataChangeEvent`. So there is some slight conflict with the names.

There also a problem with the existing code that the API is for catching events is typed to `DataChangeEvent` but then you have to explicitly cast to `DataRefreshEvent` to determine what was updated. And this is very bad design and has caused some bugs in component implementations.

So it would be great if we can somehow now unify & fix this when we add a new listener/event here.

**Comment by caalador** [comment]
Well the difference is that the new listener is about the client side fetch data and the old is about refresh in one(or more) items data. 

The newer is fired for client data request and the old one is for a DataProvider refresh event.

We should perhaps update the name and event of the old one at the same time we add the new listener interface also the new listener and event should perhaps be `ActiveDataChangeListener` and `ActiveDataChangeEvent`

**Comment by pleku** [comment]
> the new listener and event should perhaps be ActiveDataChangeListener and ActiveDataChangeEvent

👍 

But not sure what we should do with the existing `DataChangeEvent`. Should we keep `DataChangeListener` to get all 3 different events for consistency (🤮)  and add a `DataRefreshListener` that simply gets only `DataRefreshEvent` ?

**Comment by caalador** [comment]
Well the new ones are planned for the mixin interface and the old one is in DataProvider so in scope they don't mix, but getting rid of the confusing one would benefit in the long run. Perhaps deprecate it and remove asap?

**Comment by pleku** [comment]
Split this issue now to:
- API for seeing the data size changes https://github.com/vaadin/flow/issues/8171 https://github.com/vaadin/flow/issues/8172
- Trying to fix the bad design of `DataChangeEvent` https://github.com/vaadin/flow/issues/8175
- One still to be created for accessing next/previous item based on a given item for Grid

**Comment by Legioth** [comment]
It seems weird that an event about *active data*  would have a getter for the total size of the data rather than for the size of the active data.

Why would I want to manually maintain a copy of `requestedItems` when I can just as well use `getNextItem(T)` and `getNextItem(T)` which could assumingly delegate to `DataCommunicator` in the case of Grid. Without that, the only use case for the new listener would be to propagate size changes which is maybe something that should be done in a different way considering my previous observation about the semantics of that event.

**Comment by caalador** [comment]
You don't want to keep the requestedItems for grid if it has the possibility to navigate by item. It is the generic possibility when the component doesn't support navigation by item.

If we only have size in the event then it should be DataSizeChangeListener or the like.

**Comment by Legioth** [comment]
A separate discussion brought up the though that different operations in this scope are practical depending on whether the data provider is in-memory or lazy. Based on that, I started thinking that it could be useful to offer a different API surface depending on which is used. The way of doing that in practice would be that any overload of `setItems` or a custom overload of `setDataProvider` that accepts `ListDataProvider` would be defined to return a type with more API available whereas the regular `setDataProvider` method would return a more restrictive type. Capturing the return value of `setDataProvider` may not always be practical, so there would also be a getter for getting this instance after setting the data. The drawback here is that the declared type would be the more restrictive option and you'd have to do an explicit cast if you know that in-memory data is used.

This thinking could be useful even if we don't expose any API difference. The main point then would be that all these operations related to the active item set would be exposed through a separate instance instead of bloating the API of the component itself. This instance would in a way be a delegate to `DataCommunicator` for components that do lazy loading and a similar implementation shared between all the non-lazy components. This also offers an easy way of introducing this functionality for all relevant components without lots of per-component design and implementation.

Practically speaking, this instance would be a "view" into what you get from the data provider with separate APIs for the full data set and the "active" data set (mostly relevant when using lazy loading). This view would be automatically updated based on filter and sorting configuration set through the component. It could maybe also be used as an alternative to data provider wrappers for dynamically configuring sorting or filtering for components that don't do it natively.

The basic operations would mostly be the same as already discussed here, e.g. `getAllItems()`, `getActiveItems()` and listening to events when those change. It could make sense to have one event for the overall data set (fired when filtering or sorting is changed or when the data provider fires an event) and one event for the active data set (fired when the overall data set changes and when the user scrolls so that a new range of items is activated).

**Comment by Legioth** [comment]
We may actually also have a problem with the whole concept of "active" items since the set of active items is not necessarily continuous with the way items are kept as active until the client has confirmed that deactivation has been carried out. It's possible that this only means that the user-facing definition of what items are considered active would not be the same as the internal definition used by `DataCommunicator`.

**Comment by pleku** [comment]
>It's possible that this only means that the user-facing definition of what items are considered active would not be the same as the internal definition used by DataCommunicator.

This is an interesting observation, but is it somehow now different for Flow than old FW ?
To my understanding the users who have been abusing the internals of `DataCommunicator` have not complained that it doesn't match what is actually shown in the UI.

>whether the data provider is in-memory or lazy. Based on that, I started thinking that it could be useful to offer a different API surface depending on which is used. The way of doing that in practice would be that any overload of setItems or a custom overload of setDataProvider that accepts ListDataProvider would be defined to return a type with more API available whereas the regular setDataProvider method would return a more restrictive type.

I think this design approach should be now spiked further as it would allow us to return an interface which exposes for instance `ItemNavigation` (first bad name that came to my mind) API for `setItems` or `setDataProvider(ListDataProvider)` calls. There we could already support a lot of the things that are more difficult (or not yet solved) for lazy data providers, like the tedious `scrollToItem`. I don't know how the getter should work though, if the returned interface has API that does not work when lazy data providers are set. One option would be to go with 
`Optional<SomeApiSurface> getSomeApiSurface()` but IMO this is the same as just taking the FFS route and using 
```java
Optional<T> getNextItem(T activeItem)`
Optional<T> getPreviousItem(T activeItem)`
```
instead of hiding it behind the interface. But ofc. for components that don't allow lazy data providers, even the `Optional` there is unnecessary. So for any component that doesn't allow lazy data, the API would be easier, and for those components that support lazy data, the developer would have to take caution.

>Practically speaking, this instance would be a "view" into what you get from the data provider with separate APIs for the full data set and the "active" data set (mostly relevant when using lazy loading). This view would be automatically updated based on filter and sorting configuration set through the component. It could maybe also be used as an alternative to data provider wrappers for dynamically configuring sorting or filtering for components that don't do it natively.

Would the next step be to try to convert the use cases in this issue to separate lazy/in-memory "views/API surfaces" ? The decision would be then about whether to expose those directly through component API (by adding a new mixing interface) or through the API surface. Naming will be fun in either case.

**Comment by Legioth** [comment]
> To my understanding the users who have been abusing the internals of DataCommunicator have not complained that it doesn't match what is actually shown in the UI.

I don't remember whether we had explicit confirmation of deactivation also in V8. The V8 API is based on `Map<Object, T> getActiveData()` i.e. it doesn't give any indication of the ordering of active items. The API proposed in this ticket does instead imply that there would be a single continuous range of active items, which could be much more useful.

In either case, the main point is that if we take the effort of designing an API for some use cases, then the quality requirements for that API might be higher than the requirements for workarounds based on abusing API that happens to be available for other reasons.

> I don't know how the getter should work though, if the returned interface has API that does not work when lazy data providers are set.

My suggestion is that the recommended way for application code is to store the reference that you get form calling `setItems` or `setDataProvider`. There may be cases when that isn't practical (e.g. a generic exporter add-on that just gets a reference to an existing Grid instance) and for those, it would most likely be fine to also provide a getter that returns a type with the minimally guaranteed functionality, and then you would have to fall back to `instanceof` and casting for those cases.

> Would the next step be to try to convert the use cases in this issue to separate lazy/in-memory "views/API surfaces" ?

What about collecting a list of all the operations that would make sense (i.e. are useful and doable with reasonable performance) for the in-memory and for the lazy case? We already have a good start with various suggestions from this ticket:
* `getAllItems()`
* `getActiveItems()` / `getRequestedItems()`
* `getDataSize()`
* `getNextItem(item)` & `getPreviousItem(item)`
* `getItemOnRow(index)` & `selectItemOnRow(index)`
* + relevant listeners

One interesting observation here is that `getNextItem` in the in-memory case can always return a value (except for the last item in the data) whereas the lazy case would only work for items in the active range. This means that the in-memory operation would be suitable to return `T` whereas the lazy operation should preferably return `Optional<T>`. This leaves us with these bad options:
* Always go with `Optional<T>`
* Have the `Optional<T>` in the generic base type and then introduce a sub type with a `T` variant defined with a separate name to make Java happy.
* Skip inheritance for `getNextItem`. This means that there would be a generic base type completely without `getNextItem ` and then one specialization for in-memory and another specialization for lazy.

**Comment by pleku** [comment]
Design concluded and continuing in #8248 (which will be split into further implementation parts).
