### ISSUE TITLE
Link to live reload setup documentation

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#8077]
As a developer, if I have not set up a live-reload backend technology I see the message "Live reload unavailable". To make it easier for me to take live reload into use, this message should link to the documentation for setting up HotswapAgent / JRebel / Spring Boot Devtools (https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/workflow/workflow-overview.asciidoc).

**Comment by pleku** [comment]
Could be an option to link to some magic vcom address that will redirect to where we want to. First to the github docs and later on to the correct vcom/docs page.

**Comment by juuso-vaadin** [comment]
Here's my proposal for the design:
![image](https://user-images.githubusercontent.com/19607782/79733262-818c1700-82fd-11ea-89a3-d070db70b1c4.png)

Bigger one is a notification that is shown the first time app is run in dev mode. Smaller one is a status message in gizmo (similar to active/inactive statuses). Clicking "Details" opens up the Debugger and the message and link are in the log.

**Comment by joheriks** [comment]
With the above PR, there are three types of messages shown to the user:
* Splash message: blinks directly in the gizmo. When reloading and after reload has completed. Only one splash message can be shown (and it may not contain details or a link). Gets demoted to the tray after 5 seconds.
* Notifications: stacked above the gizmo. For warning about `@PreserveOnRefresh` and live reload not being available. May contain details and link. Get demoted to the tray after 5 seconds  unless they contain a link, in which case they need to be clicked on. If "Dismiss" button is clicked explicitly, the same message is never shown as a notification again (localstorage).
* Tray messages: Only visible when expanding the gizmo. All messages end up here.
This should be pretty flexible for future use.
