### ISSUE TITLE
Vaadin 15.0.4 Flow Maven Plugin reintroduces Conflicting lifecycle mapping in Eclipse

### ISSUE THREAD

**Issue by neerup** [vaadin/flow#8079]
In a few prior versions of Vaadin this problem has occurred. I know i can configure lifecycle-mapping plugin to ignore this, but 15.0.3 did not have this problem, could this be the same as vaadin/platform#644
![image](https://user-images.githubusercontent.com/4113036/79420441-33071180-7fb9-11ea-91c0-6211c1e95f15.png)

**Comment by ugurdoksan** [comment]
Same issue in 15.0.4 and 15.0.5.

I only changed the Vaadin version 15.0.3 to 15.0.4 or 15.0.5 and Eclipse gives this error on pom.xml
![Capture](https://user-images.githubusercontent.com/24225109/79898205-8a6f0c80-8413-11ea-8cb7-689507769a0b.PNG)

**Comment by Artur-** [comment]
Same as #8033 which has a link to the commit that causes this
