### ISSUE TITLE
setVisible does not work if done after remove/add of component

### ISSUE THREAD

**Issue by tepi** [vaadin/flow#8100]
Considering the following example:

    public class MainView extends VerticalLayout {
    
        public MainView() {
            Span hidden = new Span("Initially hidden");
            hidden.setVisible(false);
    
            Button toggle = new Button("Toggle Visibility", e -> {
                Notification.show("Server side visibility before: " + hidden.isVisible());
                remove(hidden);
                add(hidden);
                hidden.setVisible(!hidden.isVisible());
                Notification.show("Server side visibility after: " + hidden.isVisible());
            });
    
            add(toggle, hidden);
        }
    }

What happens is that the span never gets visible in the browser, even though the notifications show that the state changes correctly. If I reorder the lines, it will work as expected:

                hidden.setVisible(!hidden.isVisible());
                remove(hidden);
                add(hidden);

Tested on Vaadin 14.1.25.

**Comment by denis-anisimov** [comment]
Thank you very much for the short and exact issue description.
It's so rare nowadays.

Confirmed.

**Comment by denis-anisimov** [comment]
Had no chance to work closely with this bug because was busy with other tasks.
Won't proceed with this now since we have other priorities.

I put here the test view code which can be used to copy -paste into our IT module:
```

@Route("com.vaadin.flow.uitest.ui.RemoveAddVisibilityView")
public class RemoveAddVisibilityView extends Div {

    public RemoveAddVisibilityView() {
        Span hidden = new Span("Initially hidden");
        hidden.setVisible(false);

        NativeButton toggle = new NativeButton("Toggle Visibility", event -> {
            remove(hidden);
            add(hidden);
            hidden.setVisible(!hidden.isVisible());
        });

        add(toggle, hidden);
    }
}
```

**Comment by denis-anisimov** [comment]
A note for myself:
- Server side code works fine:
- initially the Element set invisible, `span` tag is sent to the client side.
- The Element on the client side is empty as it should be and has `hidden` attribute.
- Once the element is removed/added the server side send the correct data : the visibility is set to `true`.
- On the client side the element is initialized correctly : the Text child is added to it.
- But the `hidden` attribute value is not changed for some reason.

So this is a client side issue.
