### ISSUE TITLE
Embedded app reloads main application on when session is expired

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#8101]
Embedded app is a Vaadin app which has an HTTP session
The main app may be a static page or any other app which doesn't have to be a servlet app.
If it a Servlet app then it has its own session.

Embedding app HTTP session may expire (or something else may happen : e.g. session can be closed explicitly).
Flow client side reloads the page if session is expired.
But that happens with the main page: if embedding app Vaadin session expires the main (embedding) page is reloaded.

It seems this is wrong: embedded app should not influence that way on the main/embedding page.
I think embedded app should reinit/reconnect the embedded component when session is expired and not reload the main page.

Not sure whether this is a bug or not but anyway it's worth to have it to track.
Can be closed if we agree that this is by design.

**Comment by caalador** [comment]
Sounds like we should at least make the default not to automatically reload for an embedded application.
