### ISSUE TITLE
Routes are no longer found under OSGi since 14.1.24

### ISSUE THREAD

**Issue by GMMStraider** [vaadin/flow#8105]
After updating Vaadin 14 to 14.1.24 or 25 Routes are no longer added from OSGi bundles. You can reproduce this by updating the version to 14.1.24 or 25 in the OSGi starter project [https://github.com/vaadin/base-starter-flow-osgi](https://github.com/vaadin/base-starter-flow-osgi).
After looking at the changelog for flow 2.1.7 I suspect that the bug might have been introduced with the support for skinnywar.

**Comment by denis-anisimov** [comment]
Right, this is a regression introduced by support for skinnywar.

Thank you very much for finding the cause of the bug.
