### ISSUE TITLE
webComponentMode config param is incorrectly true in the client-side

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#8107]
`webComponentMode` config param in the client-side for a normal Vaadin app should be `false` by default. However, it is incorrectly `true` in Flow 3.X. You can check it with the following code in the browser console:
```
window.Vaadin.Flow.getApp("ROOT-2521314").getConfig("webComponentMode")
```
It seems that the following line in `Flow.ts` causes this bug:
https://github.com/vaadin/flow/blob/master/flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts#L197

Any fix for #3619 depends on this issue to get fixed first.

**Comment by haijian-vaadin** [comment]
The fix would be to have a separate flag in ApplicationConstants for the client-side routing.
