### ISSUE TITLE
Flow Felix Jetty Integration Tests nightly fails

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#8118]
It fails for both Flow 2.1 and 2.2. Here are links to TeamCity builds:
- [Flow Felix Jetty Integration Tests (2.1)](https://bender.vaadin.com/viewLog.html?buildId=141515&tab=buildResultsDiv&buildTypeId=Flow_Nightly_FlowFelixJettyIntegrationTests21)
- [Flow Felix Jetty Integration Tests (2.2](https://bender.vaadin.com/viewLog.html?buildId=140758&tab=buildResultsDiv&buildTypeId=Flow_Nightly_FlowJettyIntegrationTests)

**Comment by denis-anisimov** [comment]
It's incorrect on fact to create a ticket for two branches at the same time even though both builds are about OSGi.

**Comment by mehdi-vaadin** [comment]
Sorry. My bad. I was thinking that maybe something common caused this. Thanks for the point.

**Comment by denis-anisimov** [comment]
There are common parts and totally different.
Anyway it's always better to distinguish branches: you never know whether this is the same cause or not.
