### ISSUE TITLE
Update Patient Portal memory consumption tests for Flow 3.x

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#8129]
Add new builds running https://bender.vaadin.com/viewType.html?buildTypeId=PatientPortalNightly using Flow 3.1 (16) and latest 3.2 (17?).

Views should be server driven Java views like before, but the new client driven bootstrapping which is the default since 15 should be used.

**Comment by denis-anisimov** [comment]
Done.
Patient portal nightly is added for `3.1` and `3.2` . Statistics is added for these builds as well.
