### ISSUE TITLE
Vaadin 15 does not handle errors as Vaadin 14 did

### ISSUE THREAD

**Issue by tuscland** [vaadin/flow#8142]
### Description of the bug:

In Vaadin 14, when an exception occurred in our code (e.g. a custom `UnauthenticatedException` of ours), the client would be rerouted to the proper error component (that implements `HasErrorParameter<UnauthenticatedException>`).

In Vaadin 15, rerouting does not occur, instead the session global error handler is invoked.

### Minimal reproducible example
[my-starter-project-exception handling.zip](https://github.com/vaadin/flow/files/4521466/my-starter-project-exception.handling.zip)

### Expected behavior
When an exception is thrown, the corresponding exception handler is invoked, rerouting to the expected component.

### Actual behavior
Exception is handled by the session exception handler, no rerouting occurs.

### Versions:
    - Vaadin / Flow version: 15.0.5
    - Java version: 11.0.8
    - OS version: macOS 10.15.4
    - Browser version: Firefox 75

**Comment by haijian-vaadin** [comment]
HI @tuscland, thanks for the feedback. 
The `HasErrorParameter` is only supposed to handle errors **during navigation**. In the attached example, if the `UnauthenticatedException` is thrown in the button click listener, then neither v14 nor v15 will reroute to the `UnauthenticatedExceptionHandler`.

On the other hand, if the `UnauthenticatedException` is thrown during navigation, e.g. in the beforeEnter event in the `MainView`, then both v14 and v15 will reroute to the `UnauthenticatedExceptionHandler`.

**Comment by tuscland** [comment]
Thank you @haijian-vaadin for your reply. 

I understand the behavior in Vaadin 15 is closer to what it should do, and that Vaadin 14 was more lenient. This is a good thing.
