### ISSUE TITLE
PWA application cache ?

### ISSUE THREAD

**Issue by vlipovetskii** [vaadin/flow#8155]
I have created a sample application with help of https://vaadin.com/start

The application has @PWA annotation by default and placed its frontend code and resources to the browser cache. 
How to cleanup the application stuff from the browser cache ?

**Comment by caalador** [comment]
Service workers can be removed from the Application tab in the  `Developer Tools` (F12) window.

Closing issue as this is a forum question and not an issue ticket.

**Comment by Legioth** [comment]
> and not an issue ticket

On the other hand, this ticket is maybe an indication that some clarifications are missing from the documentation?
