### ISSUE TITLE
Polymer component does not render fully in its frame under v15.0.5

### ISSUE THREAD

**Issue by markhm** [vaadin/flow#8157]
As discussed with @haijian-vaadin. After migrating [Mapbox-Flow](https://github.com/markhm/mapbox-flow) be Polymer template-based, this issue remains under v15.0.5. 

See the screenshots here, which make the problem directly apparent: 
https://github.com/vaadin/flow/issues/8081#issuecomment-619195371.

Note that this problem is not found under v14.2.0.alpha11, which makes it reasonable to suggest the problem is found in Vaadin v15.0.5, rather than Mapbox itself.

To reproduce:
- checkout `https://github.com/markhm/mapbox-flow`;
- Put a property file with an `accessToken`, see the [README.md](https://github.com/markhm/mapbox-flow);
- `mvn jetty:run` and browse to http://localhost:8080 to see that there is no problem under 14.2.0.alpha11;
- Change vaadin-bom version in `pom.xml` to 15.0.5;
- `mvn clean jetty:run` and browse to http://localhost:8080 to see the component is not rendered in full under 15.0.5.

Don't hesitate in case of questions. Many thanks...!

**Comment by haijian-vaadin** [comment]
Hi @markhm. We invested in this issue. The root cause is that the in Vaadin 15, the Flow container was initially hidden, and the `mapboxgl.Map` was initialized a bit too early in the `ready` callback, since the measuring couldn't be done at that time. As a workaround, you can move the `mapboxgl.Map` initialization into the `connectedCallback`, as 
```
    ready() {
        super.ready();

        console.log("at ready()");

        // this.color = require('onecolor');
        // const div = document.createElement('div');
        // this.appendChild(div);
        // this.updateConfig();

        mapboxgl.accessToken = this.accessToken;

        console.log("initialLocation = " + this.initialLocation);
    }

    connectedCallback(){
        super.connectedCallback();
        
        // to avoid the map being initialized twice
        if(this.offsetWidth===0){
            return;
        }

        this.map = new mapboxgl.Map(
            {
                container: 'map', // container id" +
                style: 'mapbox://styles/mapbox/streets-v11', // stylesheet location" +
                center: JSON.parse(this.initialLocation), // starting position [lng, lat]" +
                zoom: this.zoomLevel // starting zoom" +
            });
    }
```

**Comment by markhm** [comment]
Hi @haijian-vaadin. Thank you for looking into this and for the solution. 🙏🏻

I have now also found the [Polymer element lifecycle](https://polymer-library.polymer-project.org/3.0/docs/devguide/custom-elements#element-lifecycle) documentation.

Best, Mark

**Comment by markhm** [comment]
One more thought. 

I've noticed that after initializing, a direct subsequent call to the `MapboxMap` instance fails, since the JS `map` is not there yet. This is - of course - explained by the `connectedCallback`-approach. 

You wrote the _Flow container was initially hidden_. Are you referring to something in my code, or is because of Vaadin 15...?

Is there anything else I can do to wait until the JS map is fully available (apart from something like `Thread.sleep()` )...? 

🙏🏻

**Comment by haijian-vaadin** [comment]
Hi @markhm, good to hear back from you.

> You wrote the Flow container was initially hidden. Are you referring to something in my code, or is because of Vaadin 15...?

It's because of Vaadin 15 issue, this is currently the way how it works because of  the mix of client-side and server-side routing.



> Is there anything else I can do to wait until the JS map is fully available (apart from something like Thread.sleep() )...?

You can use sth like below in your `connectedCallback `
```
// to avoid the map being initialized twice
if(this.offsetWidth===0){
    return;
}
```
As shown in my previous code example.

**Comment by markhm** [comment]
All good. Thanks for your response. 👍🏻
