### ISSUE TITLE
Loading indicator stays visible if endpoint call fails

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#8162]
1. Download and start https://start.vaadin.com/?preset=all-ts&dl
2. Open localhost:8080
3. Set browser to offline
4. Navigate to e.g. `dashboard-view-typescript`

The requests fail as you are offline but the loading indicator stays on forever

**Comment by haijian-vaadin** [comment]
Found the root cause:
It's because we are showing the loading indicator for endpoint call, see the [code](https://github.com/vaadin/flow/blob/master/flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts#L354).
Tried with our offline branch, the behavior is the same.
