### ISSUE TITLE
Dependency missing since 14.1.19+

### ISSUE THREAD

**Issue by mkemmerz** [vaadin/flow#8166]
Hello,

we encountered an issue with our project.
Everything was working fine with Flow 14.1.18 in our project. A newer version (14.1.19 - 14.1.26) causes the following exception:

> Failed to execute goal on project X: Could not resolve dependencies for project X:jar:X-snapshot: Failed to collect dependencies at com.vaadin:vaadin-testbench:jar:14.1.26 -> com.vaadin:vaadin-confirm-dialog-testbench:jar:2.0.3 -> com.vaadin:vaadin-button-testbench:jar:2.0-SNAPSHOT: Failed to read artifact descriptor for com.vaadin:vaadin-button-testbench:jar:2.0-SNAPSHOT: Failure to find com.vaadin:flow-component-base:pom:2.0-SNAPSHOT in X was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced -> [Help 1]

I understand the issue but what has changed in 14.1.19+ and what dependency is exactly new / missing?

**Comment by caalador** [comment]
Sounds like a missing or corrupt jar package. 

Have you tried running maven with the -U flag to forces checking for missing releases and updated snapshots on remote repositories.

Another possibility would be to run `mvn dependency:purge-local-repository`, but note that this will remove the .m2 cached packages and re-download them see [Purging local repository dependencies](https://maven.apache.org/plugins/maven-dependency-plugin/examples/purging-local-repository.html)

**Comment by Artur-** [comment]
The problem is that https://repo1.maven.org/maven2/com/vaadin/vaadin-crud-testbench/3.0.1/vaadin-crud-testbench-3.0.1.pom references a SNAPSHOT version. This seems to be a problemt also in other testbench packages

**Comment by Artur-** [comment]
Not sure what would have changed in 14.1.19 but if you have the snapshot repository in your pom.xml it should work

**Comment by mkemmerz** [comment]
We made it work with the following pom.xml setup:   

           <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-testbench</artifactId>
            <version>14.1.27</version>
            <scope>test</scope>
            <type>jar</type>
            <exclusions>
                <exclusion>
                    <groupId>com.vaadin</groupId>
                    <artifactId>vaadin-button-testbench</artifactId>
                </exclusion>
            </exclusions>    
        </dependency>         

        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-confirm-dialog-testbench</artifactId>
            <version>2.0.3</version>
            <scope>test</scope>
            <type>jar</type>
            <exclusions>
                <exclusion>
                    <groupId>com.vaadin</groupId>
                    <artifactId>vaadin-button-testbench</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-button-testbench</artifactId>
            <version>2.0.2</version>
            <scope>test</scope>
            <type>jar</type>
        </dependency>
