### ISSUE TITLE
Add new methods to HasDataProvider mixin interface

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#8171]
Add the following new methods to HasDataProvider

```java
/* Query with range [0, Integer.MAX_VALUE] */
Stream<T>       HasDataProvider.getAllItems();
/* Listener for when a new data is sent to the client */
Registration    HasDataProvider.addActiveDataChangeListener(ActiveDataChangeListener);
```
And create the `ActiveDataChangeListener` and `ActiveDataChangeEvent`
classes.

```java
ActiveDataChangeEvent {
    /* Stream of the latest items sent to the client */
    /* Stream is sorted + filtered same as last set sent to client */
    Stream<T> getRequestedItems()
    /* Full size of data to be had with current filters */
    int getFullDatasetSize()

    int getRequestRangeStart()
    int getRequestRangeEnd()
}
```

**Comment by Legioth** [comment]
Would those new methods have `default` implementations (and in how would those methods behave)? Otherwise, this would be a breaking change.

**Comment by pleku** [comment]
> Would those new methods have default implementations (and in how would those methods behave)? Otherwise, this would be a breaking change.

That is anoter good point why the existing interface is problematic, in addition to not really belonging to all components https://github.com/vaadin/flow/issues/8172#issuecomment-619942393

What would be a good name for a new mixin interface for this ? It is not easy to describe the behavior..
- `HasDataChangeListeners` ?
