### ISSUE TITLE
Add header toolbar to live-reload gizmo

### ISSUE THREAD

**Issue by juuso-vaadin** [vaadin/flow#8174]
To help users identify what this new panel is about, add in section with "Vaadin Development Mode" heading. Also the minimizing button and repositioning drag-handle can be positioned to the same header section.

![image](https://user-images.githubusercontent.com/19607782/80364198-296d8b80-888e-11ea-87c1-9f331cda4160.png)

**Comment by pleku** [comment]
### Acceptance Criteria
- add the text for the development mode on the header
  - intentionally do not add drag handle yet, postponed to later if we add more features to the dialog
