### ISSUE TITLE
Live Reload and HotswapAgent not reloading classes in IntelliJ

### ISSUE THREAD

**Issue by jm-ferreira** [vaadin/flow#8176]
For some unknown reason running HotswapAgent and IntelliJ makes Live-reload enabled, but when you make changes and recompile the browser reloads without showing the changes made in the code.

It was expected that upon recompile the changes would be reflected on the browser.
Changes are not reflected. The application remains the same if you do not explicitly stop and start the server.

HotswapAgent 1.4.1-SNAPSHOT, TravaOpenJDK 11.0.6+1 and IntelliJ IDEA.
Tested on run and debug mode.

Requires investigation.

**Comment by jm-ferreira** [comment]
Steps to reproduce:

- On Preferences -> Build, Execution and Deployment -> Compiler, check if Build Project Automatically is on
- Run application on Debug mode using TravaOpenJDK
- Make changes to some class and wait a few seconds, HotswapAgent and Live Reload will trigger but not pickup any changes.

(Rebuilding the project manually works as expected)

**Comment by jm-ferreira** [comment]
After some investigation, we've concluded this problem is caused by some remnant changes made by a previous install of JRebel plugin for IDEA. 
It was decided to update docs so we warn users about this.

**Comment by jm-ferreira** [comment]
Closing this since docs have been updated and no further action on this is needed.

**Comment by CodingYourAmbition** [comment]
> On Preferences -> Build, Execution and Deployment -> Compiler, check if Build Project Automatically is on
this is helpful
