### ISSUE TITLE
Make Div implement HasOrderedComponents

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#8188]
This would expose useful helpers such as `getComponentAt` and `indexOf`.

**Comment by pleku** [comment]
Should be fairly straightforward for to contribute this. Adding unit tests should be enough for testing. For new contributors, please check the guide first https://github.com/vaadin/flow/blob/master/CONTRIBUTING.md

**Comment by ovidiupopa91** [comment]
Hi @pleku. I can work on this issue after we close https://github.com/vaadin/flow/issues/3241
