### ISSUE TITLE
Make it possible to create lazy data binding without learning the concept of DataProvider

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#8189]
Claim without any strong proof points: Users are mostly using Vaadin components and the concept of DataProvider is irrelevant for them if they can provide the data fetching strategy with a simple lambda expression. If they need repeat themselves, they should most often create for example a PersonTable instead of creating custom DataProvider and connect that to multiple components.

We should bring back the feature from V8 where the lazy data providing strategy can also be provided with an overloaded setItems method. This would be easier to find for new users and would need less learning of Vaadin specifics.

**Comment by pleku** [comment]
The demos for `Grid` component also use the static builder methods in `DataProvider` to generate a data provider, instead of actually creating an instance of it or using a specific data provider. I think it should be possible to incorporate the necessary methods in `HasDataProvider` (probably not `HasItems`) to set the items/data provider by just providing the callback. The discoverability of the stastic methods somewhere else than in the component API is not that straight forward.

**Comment by Legioth** [comment]
Would this mean anything else than a shorthand so that you could in the simple case replace `grid.setDataProvider(DataProvider.fromCallbacks(x, y))` with something along the lines of `gird.setDataProvider(x, y)`?

**Comment by mstahv** [comment]
When we get the technical parts of the current investment done, we should think about the naming. If the most simple way to put data to our components is setItems, new users should see a hint of the lazy loading approach when autocompleting in IDE. setItemsLazy

**Comment by pleku** [comment]
There is a design doc and the naming issue described here for internal review with lots of suggestions https://docs.google.com/document/d/1bynXbEn-8ViV92EcagUbqrlm4RGr1aa0NjIdM-1Hyd0/edit#

I'm keen on using the doc internally as suggestions and commenting make it quite much easier to coordinate, but here is a recap of the situation and the current alternatives:

#### The problems are that
1) Most people are used to using setItems and setDataProvider. For in-memory data, they will use setItems unless we deprecate and remove it. And we want to now switch it to return the list data view
2) New users might not know that they should use setDataProvider for lazy data

#### Alternatives for the naming and behavior

1. Reuse setItems & setDataProvider and change return type from void to return the API surface (AKA DataView)
     - Breaking change for setItems due to return type changing
     - New users don’t know about DataProviders
2. Reuse setItems and add setItemsLazy
     - Breaking change for setItems due to return type change
     - Open question if setDataProvider should be deprecated or not
3. Just use setDataProvider but deprecate the setItems
     - Not a breaking change
     - DataProvider is not really a stream/collection/array … 
     - Would need to know about dataProvider in advance, not a good option
4. Distinct API for every component - setRows setOptions 
     - No breaking changes
     - setRowProvider and setOptionsProvider for callback/lazy case
     - No unified API for components limits discoverability ??
     - Would have to deprecate setItems & setDataProvider
5. setData for in memory and setDataProvider for callback
     - Or use setData for both
     - No breaking changes
     - Would have to deprecate setItems & setDataProvider
6. Retrain existing setItems setDataProvider
     - No breaking changes
     - Force everyone to use correct API for fetching data view
        - getDataView() : V extends DataView
        - getListDataView() : V extends ListDataView
        - getLazyDataView : V extends LazyDataView

**Comment by pleku** [comment]
Based on the options above, chose `setDataSource` for now as it fits the usage for both in-memory and backend data and allows us to not make breaking changes. One noted problem is that there is the `javax.sql.DataSource` which we don't accept as a parameter nor will we introduce a new `DataSource` class either.

#### Acceptance Criteria

The methods would thus be:
```java
V extends ListDataView<T> setDataSource(Collection<T>  collection);
V extends ListDataView<T> setDataSource(Stream<T>  stream);
V extends ListDataView<T> setDataSource(T...  data);
V extends ListDataView<T> setDataSource(InMemoryDataProvider dataProvider);

V extends LazyDataView<T> setDataSource(CallbackProvider.FetchCallback<T, Void> fetchCallback);
V extends LazyDataView<T> setDataSource(CallbackProvider.FetchCallback<T, Void> fetchCallback, CallbackProvider.FetchCallback<T, Void> countCallback);
V extends LazyDataView<T> setDataSource(BackendDataProvider<T, Void> dataProvider);
```
- All old `setItems` variants are deprecated.
- All old `setDataProvier` variants are deprecated
DataProvider class:
- All static methods could be maybe deprecated (?) but chose not to since there might be a good reason to use those. The old component methods that accept a data provider are deprecated anyway. There should not be any usage of this API in any of the demos though.

**Comment by caalador** [comment]
Actually should the `V extends ListDataView<T> setDataSource(InMemoryDataProvider dataProvider);` be `V extends ListDataView<T> setDataSource(ListDataProvider dataProvider);`  as many of the `ListDataView` methods require the data source to be a List?
Also the name suggests that this is for List data.

**Comment by pleku** [comment]
The problem with requiring `ListDataProvider` instead of `InMemoryDataProvider` is that if someone has made a custom `InMemoryDataProvider` that is not extending `ListDataProvider`, then they cannot use those anymore but through a deprecated API. Any ideas how to handle that @caalador ?

**Comment by caalador** [comment]
We would have to have then an `V extends DataView setDataSource(InMemoryDataProvider)` as the AbstractListDataView will throw for a non ListDataProvider when any method calls getDataProvider()

**Comment by pleku** [comment]
Ok, then lets do that. The javadocs should probably point somehow point and urge to use the other methods or the one with `ListDataProvider` so that someone who is using the parent type `InMemoryDataProvider` unnecessarily could change type and use that API instead.

**Comment by caalador** [comment]
Now the question is that where should it be? in the components? 
else we need 
```

public interface HasDataView<T, V extends DataView<T>> extends Serializable {

    V setDataSource(InMemoryDataProvider<T> dataProvider);
}
```
But then we also need an implementation for AbstractDataView that supports InMemoryDataProvider or a DataViewImpl.

**Comment by pleku** [comment]
To be available in Flow 4.0.0.alpha1 and Vaadin 17.0.0.alpha6 by using just providing the items lazily with the fetch callback:
```java
GridLazyDataView<Item> lazyDataView = grid.setItems(
        query -> fakeBackend.generateItems(query.getOffset(), query.getLimit()));
```
or if exact count is desired like currently with data provider:
```java
GridLazyDataView<Person> lazyDataView = grid.setItems(
        query -> personService .fetch(query.getOffset(), query.getLimit()).stream(),
        query -> personService.count());
```

**Comment by bsutton** [comment]
I've just been trying to use this and its a mess.

Given the functions we are passing in really amount to a BackendDataProvider I don't understand why I can just pass in a BackenDataProvider. This approach is completely inconsistent and I've spent hours looking for the wrong thing.

**Comment by mstahv** [comment]
Hi Brett, 

What's up? Would love to hear more details about the problems you see here. Feel free to book a meeting with me if you want to share the details in a video call.
