### ISSUE TITLE
Flow 1.0, CDI 10.0 and Spring 10.0 build failures

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#8192]
Flow and snapshot builds for 1.0 fail in bender. Investigate reason and take corrective action.

**Comment by denis-anisimov** [comment]
Should we care about `1.0` at all ?
Is it supported version ?

**Comment by denis-anisimov** [comment]
The version is still LTS.

**Comment by caalador** [comment]
Flow 1.0 build is fixed, but the add-ons are still failing.
Initial look seems like we are searching for elements too early as in the error screenshots we have the loading indicator still visible.
