### ISSUE TITLE
MPR build failures

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#8201]
The following MPR builds are failing in bender:
* MPR 1.1 Snapshot for Flow 1.0
* MPR 2.0 Snapshot for Flow 2.1 and validation for Flow 2.2
* MPR 3.0 Snapshot for Flow 3.0 and validation for 3.1 and 3.2

Investigate reason and take corrective action

**Comment by denis-anisimov** [comment]
Ticket for MPR 3.0 is created (CCDM code) : https://github.com/vaadin/flow/issues/8270
