### ISSUE TITLE
Use a no bundle server for frontend assets during development

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#8217]
This is an alternative approach to https://github.com/vaadin/flow/issues/6248
 for solving the slow frontend build process during development time in Vaadin 14+

Consider using something like https://open-wc.org/developing/es-dev-server.html to load modules directly instead of bundling to get rid of the webpack build stage during development. 

The initial startup would be slower than with the proposed solution in https://github.com/vaadin/flow/issues/6248, but this would also work as developers add their own frontend code.

**Comment by pleku** [comment]
This was one of the options considered last year internally as an improvement over the current situation, but as the maturity was unclear and it was "yet another new thing to integrate and switch to", it was not yet acted upon. As it requires the `node_modules` folder to be there, I wonder if it works with what pnpm produces (google doesn't say).

The plan has been to next look at Webpack 5 and the performance improvements it brings, including the possibility of creating a "default widgetset" for development mode (#6773). We can take a look at es-dev-server as an alternative to that if necessary. At least the pnpm question and supporting TS needs to be considered.

**Comment by Legioth** [comment]
One strong candidate right now could be Snowpack 2 which is currently in an early access phase. It promises to do basically the same things as webpack, but doing everything on-demand instead of up-front in development mode.

**Comment by pleku** [comment]
This is what Vite now does. It is available in V22 behind a feature flag.
