### ISSUE TITLE
IndexHtmlRequestHandlerIT::should_renderServerView_When_ClickSameServerLinkTwiceAndGoToClientView is broken

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#8219]
The test makes an assertion which is failing.

Apparently it expects the content which is not changed after second click to a link.
But the content is doubled instead.
Here is the resulting content after the second click to the same link:

```
ViewWithAllEvents: 1 setParameter

ViewWithAllEvents: 2 beforeEnter

ViewWithAllEvents: 3 onAttach

ViewWithAllEvents: 4 afterNavigation

ViewWithAllEvents: beforeLeave

ViewWithAllEvents: 1 setParameter

ViewWithAllEvents: 2 beforeEnter

ViewWithAllEvents: 4 afterNavigation
```

This is unexpected for the test and it fails.
I'm going to disable it since my PR which doesn't contain any thing related to this doesn't pass the validation.
The test should be fixed and enabled back.

**Comment by haijian-vaadin** [comment]
This was due to a newer version of @vaadin/router, fixed by pin an older version of router. This PR #8197 passes and the snapshot is green, so closing this ticket.
