### ISSUE TITLE
Links (anchor) related ITs failing

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#8223]
4 tests are filing during PRs validation.
See PR https://github.com/vaadin/flow/pull/8222
One test is disabled because of https://github.com/vaadin/flow/issues/8219.
The latest issue may be related to this one.

The mentioned PR has _no any other_ changes except disabling one test.
So it may not fail.
But it fails because of these 4 tests.

FragmentLinkIT.testInsidePageNavigation_noRouterLinkHandling
MultipleAnchorsIT.numerousDifferentAnchorsShouldWorkAndHistoryShouldBePreserved
MultipleAnchorsIT.numerousEqualAnchorsShouldRepresentOneHistoryEntry
ScrollIT.anchorUrlsWorkProperly

**Comment by haijian-vaadin** [comment]
This was due to a newer version of @vaadin/router, fixed by pin an older version of router. This PR https://github.com/vaadin/flow/pull/8197 passes and the snapshot is green, so closing this ticket.

**Comment by denis-anisimov** [comment]
All `3.x` versions has this issue.
The fix needs to be ported to all `3.x` branches.

**Comment by haijian-vaadin** [comment]
I think the fix has been ported to 3.0 and 3.1 branches by Johannes, we can close it now.
