### ISSUE TITLE
(Vaadin+Spring) External component in "vaadin.whitelisted-packages"

### ISSUE THREAD

**Issue by Tonne-TM** [vaadin/flow#8228]
Original Forum Post: https://vaadin.com/forum/thread/18230584/vaadin-spring-external-component-in-vaadin-whitelisted-packages-not-wor

In my use case I added a Component from Vaadins Ad-Ons Repository to my project. I am using the application property "vaadin.whitelisted-packages" ([Wiki](https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html)). How can I add the package of the external component?

I tried the following
```
vaadin.whitelisted-packages=com/my/webapp/,com/mlottmann/VStepper/
```
Sadly this way the component is not working at runtime due to missing files. When I remove the whitelist start up time is much longer and the component is working.

This is maven dependency of the addon:
```xml
        <dependency>
            <groupId>com.mlottmann.VStepper</groupId>
            <artifactId>VStepper</artifactId>
            <version>1.0.8</version>
        </dependency>
```

**Comment by knoobie** [comment]
Did you try to use a lower-cased variant of the groupId or removing the "VStepper"?

**Comment by Tonne-TM** [comment]
> Did you try to use a lower-cased variant of the groupId or removing the "VStepper"?

I tried both is sadly did not help.

**Comment by caalador** [comment]
What version are you using I tested with the spring starter using v15.0.5 and v14.1.25
and had the whitelist as `vaadin.whitelisted-packages=com/mlottmann/vstepper,org/vaadin/example` and it worked.

If you could have a minimal project that reproduces this it would help with debugging the issue.

**Comment by Tonne-TM** [comment]
Ok I now changed the order and somehow it is working now:
`vaadin.whitelisted-packages=com/mlottmann/vstepper,de/my/webapp `
