### ISSUE TITLE
flow-build-info.json in production build references local directories

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow#8231]
### Description of the bug

In a production mode build (war file) the flow-build-info.json file under WEB-INF/classes/META-INF/VAADIN/config has lines pointing to directories in the local development machine (such as "connect.generated": "/home/LOCAL_MACHINE_FOLDER/frontend/generated"). 

### Expected behavior
flow-build-info.json should not reference directories in the local development machine

### Versions:
Vaadin 15.0.5

**Comment by haijian-vaadin** [comment]
Need to clean development settings in build-frontend, check `BuildFrontendMojo::updateBuildFile` to see how others were cleaned. 

Slack discussion https://vaadin.slack.com/archives/C6X43FE8M/p1588586059028200.

**Comment by haijian-vaadin** [comment]
This issue is fixed in Vaadin 15.0.6
