### ISSUE TITLE
Endpoint superclass methods not exported

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#8237]
Given 
```
@Endpoint
@AnonymousAllowed
public class PersonEndpoint extends CrudEndpoint<Person, Integer> {
}
```
and
```
public abstract class CrudEndpoint<T, ID> {

    @Override
    public Optional<T> get(ID id) {
 ...
   }

    @Override
    public T update(T entity) {
 ...
    }

    @Override
    public void delete(ID id) {
 ...
    }

}
```

I would expect to get an endpoint TS with 3 methods. 

Instead I get
```
2020-05-05 12:55:19.816  INFO 23474 --- [  restartedMain] c.v.f.s.c.g.OpenApiSpecGenerator         : There are no connect endpoints to genertate.
```

Problems:
1. The error message sounds like there are no endpoint classes found when in reality it seems to interpret the class as having no methods.
2. "genertate" should be "generate"

If I override all methods in my endpoint class, I get the expected result

**Comment by manolo** [comment]
An option might be to change the message:
`There are no connect endpoints to generate. If there are public methods to expose in super classes you might consider to override those in the endpoint class`

**Comment by vlukashov** [comment]
Reference: In JPA the `@Entity` annotation does not consider inherited properties unless the superclass that defines them is annotated with `@MappedSuperclass`.

@Artur-, would you expect that in Vaadin the `@Endpoint` annotation works similarly to `@Entity` in this aspect? That would be the `@EndpointExposed` option suggested by Manolo.

Or would you expect that all inherited public methods are exposed by default without any extra annotations?

**Comment by Artur-** [comment]
It is fine to me to add an annotation to the parent class. It is not fine to override all methods.

**Comment by jojule** [comment]
This is now generated as default example from start.vaadin.com. Highlights the importance of this bug...

```
@Endpoint
@AnonymousAllowed
public class PersonEndpoint extends CrudEndpoint<Person, Integer> {

    private PersonService service;

    public PersonEndpoint(@Autowired PersonService service) {
        this.service = service;
    }

    @Override
    protected PersonService getService() {
        return service;
    }

    @Override
    public Optional<Person> get(Integer id) {
        // Workaround because of https://github.com/vaadin/flow/issues/8237
        return super.get(id);
    }

    @Override
    public Person update(Person entity) {
        // Workaround because of https://github.com/vaadin/flow/issues/8237
        return super.update(entity);
    }

    @Override
    public void delete(Integer id) {
        // Workaround because of https://github.com/vaadin/flow/issues/8237
        super.delete(id);
    }

    @Override
    public List<Person> list(int offset, int limit) {
        // Workaround because of https://github.com/vaadin/flow/issues/8237
        return super.list(offset, limit);
    }

    @Override
    public int count() {
        // Workaround because of https://github.com/vaadin/flow/issues/8237
        return super.count();
    }
}

```
