### ISSUE TITLE
Bundle added to document head in development mode

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow#8274]
There is an inconsistency with adding JS bundle to `<head>` or `<body>` depending on the mode:

## Development mode

Bundle is added to `<head>`:

<img width="698" alt="Screenshot 2020-05-07 at 19 59 58" src="https://user-images.githubusercontent.com/10589913/81322965-5c3d2e00-909d-11ea-9923-e7065165ed7c.png">

## Production mode

Bundle is added to `<body>`:

<img width="735" alt="Screenshot 2020-05-07 at 19 57 24" src="https://user-images.githubusercontent.com/10589913/81323033-75de7580-909d-11ea-9ce9-c619647f7933.png">

As a result, the following code works in production but fails in development mode:

```js
document.body.removeAttribute('unresolved');
document.body.appendChild(document.createElement('small-screen-dialog'));
```

It would be better to align this behavior and always add JS bundle to `<body>`.

**Comment by caalador** [comment]
Which flow version is this? 2.x or 3.x series as that makes a big difference on the bootstrap.

**Comment by web-padawan** [comment]
This was reproduced in Starter Wizard which uses V16 beta at the moment.

**Comment by haijian-vaadin** [comment]
Close it for now, as we(me and @web-padawan ) were not able to reproduce with starter-wizard. Let's reopen it when the problem reappears.

**Comment by web-padawan** [comment]
Reopening, this is still an issue. Not being able to use `document.body` inside a script results in errors like this:

![Screenshot 2020-07-17 at 15 35 04](https://user-images.githubusercontent.com/10589913/87786760-32de1280-c843-11ea-8a3d-7c550b5cc1b1.png)

**Comment by web-padawan** [comment]
Note, this can be reproduced in Vaadin 17 alpha as well. 

Steps to reproduce:

1. add `document.body.removeAttribute('unresolved')` to `index.ts` (entrypoint of a CCDM project)
2. in development mode, no error happens
3. in production mode, error is thrown

**Comment by web-padawan** [comment]
Looks like now the bundle is consistently added to `head` which is something to keep in mind. I do not think it is a blocker.
