### ISSUE TITLE
Fsevents 1 might no longer work on Node 14+

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#8278]
```
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
```

**Comment by Artur-** [comment]
`fsevents 1` is included through `chokidar 2`

`chokidar 2` is included through:
1. webpack@4.42.0 through watchpack@1.6.1 (Fix pending in https://github.com/webpack/watchpack/pull/153)
2. webpack-babel-multi-target-plugin@2.3.3 through `@babel/cli@7` (https://github.com/babel/babel/issues/11488#issuecomment-619614369 says it will not be fixed before @babel/cli version 8 at some point but that a new version can be forced)
3. webpack-dev-server@3.9.0 (Fixed in https://github.com/webpack/webpack-dev-server/pull/2539, pending release)

**Comment by Artur-** [comment]
https://github.com/fsevents/fsevents/releases/tag/v2.0.0

```
We have upgraded to N-API. For that reason we have also dropped support for node < 6.

For that reason, we have made this a major version bump so dependents have to opt in. The actual API remains entirely the same, so if you are depending on fsevents, it should be as simple as changing the version number in your package.json.
```

**Comment by mocca-dev** [comment]
I'm having the same issue
