### ISSUE TITLE
Push not enabled despite annotation `@Push` added to `AppShell` in Vaadin 16

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#8283]
To reproduce:
* Download and unzip [this project](https://github.com/vaadin/flow/files/4598960/push-test.zip)
* Go to project folder / import project into IDE
* Run the Maven goal `jetty:run`
* Browse to http://localhost:8080

`AppShell` class contents:
 ```java
@PWA(name = "Project Base for Vaadin", shortName = "Project Base", enableInstallPrompt = false)
@Push
public class AppShell implements AppShellConfigurator {
}
```

The `MainView` class contains only this code:
```java
@Route("")
public class MainView extends VerticalLayout {

    @Override
    protected void onAttach(AttachEvent attachEvent) {
        add(new Span("pushed"));
        getUI().get().push();
    }
}
```

Erroneous behavior: The explicit `UI::push` in call fails with the following:
```
java.lang.IllegalStateException: Push not enabled
	at com.vaadin.flow.component.UI.push(UI.java:654)
	at org.vaadin.example.MainView.onAttach(MainView.java:21)
	at com.vaadin.flow.component.ComponentUtil.onComponentAttach(ComponentUtil.java:230)
...
``` 
Expected behavior: The explicit `UI::push` call does not fail. This works in Vaadin 15 series versions, e.g., 15.0.4.

Versions:
* Vaadin 16.0.0.beta1
* Java 8

**Comment by nicoulaj** [comment]
I can confirm this issue. Neither automatic nor manual push work for me on 16.0.0.beta1.

**Comment by nicoulaj** [comment]
I did a bit of debugging, and it seems to me that the `@Push` annotation on `AppShell` is not read. `Bootstraphandler.createAndInitUI()` tries to read it from `MainView`, but it cannot be set there because of a validation check to ensure it is set only on `AppShell`.

A workaround is to enable it application wide using the `pushMode` property, for instance for a spring boot app put in `application.properties`:
```
vaadin.pushMode=AUTOMATIC
```

**Comment by manolo** [comment]
@nicoulaj  @joheriks is this an issue that already happens in v15 or is a regression from v15 to v16.
We did some work with Push in v15, but perhaps it was not enough

**Comment by nicoulaj** [comment]
@manolo It's a regression between 15 and 16. I believe it is more related to `AppShellConfigurator` not used correctly to initialize `UI.pushConfiguration`.

**Comment by manolo** [comment]
It's a regression introduced somehow, taking it. Thanks

**Comment by manolo** [comment]
As reference, the workaround is to use the server side bootstrap by enabling the appropriate flag
