### ISSUE TITLE
Client-side forms: Align the import styles

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#8293]
I find it confusing that there are 3 different import styles I need to use with client-side forms in Vaadin:

- `import {Binder, field} from '@vaadin/flow-frontend/Binder';`
- `import * as personEndpoint from '../../generated/PersonEndpoint';`
- `import PersonModel from '../../generated/com/example/application/PersonModel';`
- `import Person from '../../generated/com/example/application/Person';`

Ideally, I’d like to use one style of imports. My personal preference is named imports like in 
`import {Binder, field} from '@vaadin/flow-frontend/Binder'`:
- `import {Binder, field} from '@vaadin/flow-frontend/Binder';`
- `import {PersonEndpoint} from '../../generated/PersonEndpoint';`
- `import {PersonModel} from '../../generated/com/example/application/PersonModel';`
- `import {Person} from '../../generated/com/example/application/Person';`

**Comment by haijian-vaadin** [comment]
Related https://github.com/vaadin/flow/issues/7176, having named imports will also solve this issue.

**Comment by vlukashov** [comment]
Also related to:
 - https://github.com/vaadin/flow/issues/7419
 - https://github.com/vaadin/flow/issues/7758
 - https://vaadin.slack.com/archives/C6X43FE8M/p1586352973187100

**Comment by haijian-vaadin** [comment]
No hard requirement for 
```
import {PersonModel} from '../../generated/com/example/application/PersonModel';
import {Person} from '../../generated/com/example/application/Person';
```
since the auto-import works already

**Comment by haijian-vaadin** [comment]
I think we can close this one, since:
1. No big benefits for styles like
```
import {PersonModel} from '../../generated/com/example/application/PersonModel';
import {Person} from '../../generated/com/example/application/Person';
```
2. `import * as personEndpoint from '../../generated/PersonEndpoint';` to `import {PersonEndpoint} from '../../generated/PersonEndpoint';` would be done in https://github.com/vaadin/flow/issues/7176
