### ISSUE TITLE
Strange error message when resolving a JS result fails

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#8302]
Using a `getElement().callJsFunction("foo").toCompletableFuture().get()...` results in this error message when called inside an component event listener:

```
java.lang.IllegalStateException: Cannot do a blocking operation from the thread that has locked  the session is locked since the result cannot be made available while the session is locked.
```

It is somehow understandable, what this means, but at the same time it seems a bit like someone wanted to replace an old error message with a new one and forgot to delete the old part.

**Comment by Legioth** [comment]
I blame whoever passed my typos through code review.  😄

Revised text in https://github.com/vaadin/flow/pull/8312.
