### ISSUE TITLE
Flow 3.0 SNAPSHOT fails

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#8309]
https://bender.vaadin.com/viewLog.html?buildId=147101&buildTypeId=Flow_Flow30_Flow30Snapshot&tab=buildLog

Fails because of timeout

**Comment by mehdi-vaadin** [comment]
I didn't find anything suspicious. Maybe it's related to the load of the machines at the moment of the build as it doesn't happen always. I increased the timeout in failure conditions to 75 minutes. That might be enough. We will investigate it if it happens again.
