### ISSUE TITLE
Introduce missing filtering/sorting API for DataView

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#8313]
Add missing filtering and sorting methods to `DataView` (create a new interface or add to `ListDataView`, to be investigated within this ticket). Move the following methods to a new `DataView` interface (if there would be a new interface considered) from `ListDataView`:

```
    V withFilter(SerializablePredicate<T> filter);
    V withSortComparator(SerializableComparator<T> sortComparator);
```

See `InMemoryDataProvider` for reference.

**Comment by pleku** [comment]
As long as we have a default implementation for all of the methods, I think we could just add them directly to the `ListDataView` interface. Basically the methods are already provided by `ListDataProvider`.

There might be components where it doesn't make that much sense to sort/filter things but at least it would be really easily possible when needed.

**Comment by pleku** [comment]
### Acceptance Criteria
- Adding the same filtering API as in `ListDataProvider`, when it makes sense and is demoable with Grid / Select, for instance when building a "filter table"
- Adding the sorting API as in `ListDataProvider`, when it makes sense and is demoable with Grid / Select
