### ISSUE TITLE
Stage 2.2.0

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#8318]
Stage it for now and prepare release notes as draft.

Validate the staged artifact by:
- getting latest 14.1 starter project like bakery/business-app 
- running the app in with 14.1
- bumping to 14.2.0.rc1 and the staged 2.2.0
- validate that everything works out fine, npm install happens the first run
- run the project again and npm install should not be run again

**Comment by jm-ferreira** [comment]
Validated staged artifact against business-app following the instructions.
npm install ran 1st time after bump
npm install did not run on following runs, as expected
