### ISSUE TITLE
Nightly build with Java 12 are failing

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#8328]
A number of nightly starter tests running on Java 12 are failing:
https://bender.vaadin.com/viewType.html?buildTypeId=Flow_StarterTests_NightlyBuilds_Java12BeverageBuddy
https://bender.vaadin.com/viewType.html?buildTypeId=Flow_StarterTests_NightlyBuilds_Java12Bookstore
https://bender.vaadin.com/viewType.html?buildTypeId=Flow_StarterTests_NightlyBuilds_Java12SkeletonStarter

In fact we don't need to have Java 12 test anymore. They should use Java 14 instead.

So :
- migrate all Java 12 tests to Java 14
- make sure they work.

**Comment by joheriks** [comment]
Updated all starter builds to use Java 14.
