### ISSUE TITLE
DefaultValueInitializationIT.defaultValues_areSetToCorrectValues_withCorrectUpdateCounts fails in 2.3 branch

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#8329]
https://bender.vaadin.com/viewLog.html?buildId=148036&

```
Caused by: org.openqa.selenium.NoSuchElementException: No element with tag <*> found with the attributes [id='value'] using index 0
```
in `flow-tests/test-embedding/test-embedding-generic-compatibility/`.

**Comment by joheriks** [comment]
The test is flaky, it mostly passes but sometimes fails. The flakiness occurs also 2.2,but not in 3.0+ . It seems limited to compatility mode submodules of `test-embedding`.

**Comment by joheriks** [comment]
The reason behind this flakiness was quite interesting. It has appeared after Chrome dropped native support for HTML imports. The polyfill that kicks in in its stead does not attach the shadowroot to the custom elements fast enough, so a TestBench selector expecting to find shadowroot already attached failed.
