### ISSUE TITLE
Update Vite config to extract Highcharts.js to its own chunk

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow#8336]
Significant part of the bundle is related to Highcharts.js (used by Vaadin Charts).

The idea is to configure `splitChunks` in webpack config to use bundle splitting:

- vaadin-bundle - contains app logic (e.g. components using PolymerTemplate)
- vaadin-charts~bundle - contains only Highcharts.js
- vaadin-vendors~bundle - contains Polymer itself and all Vaadin components.

This is how it looks in Bakery app starter (see https://github.com/vaadin/bakery-app-starter-flow-spring/pull/1065)

<img width="657" alt="Screenshot 2020-05-14 at 13 32 20" src="https://user-images.githubusercontent.com/10589913/81927182-e4ff2100-95eb-11ea-9c7d-28290de5d798.png">

This should make caching more efficient, because Highcharts.js version we use is fixed.
So, the corresponding chunk will not be affected when updating to a new Vaadin patch release.

**Comment by Legioth** [comment]
Would it somehow be possible to externalize this detail to be parts of `vaadin-charts-flow` instead of hardcoding for this particular case in Flow itself?

**Comment by web-padawan** [comment]
It would be even better to have some sort of adapter that would allow add-ons to specify that:

1. their dependencies are ES5 and don't need to be transpiled (for 14.x)
2. their dependencies should be extracted to separate chunk.

The first part is only relevant for 14.x and covered by this block:

```js
// Do not transpile Highcharts.js which is ES5
exclude: [
  /node_modules\/highcharts/
],
```

The second part is covered by `splitChunks` config:

```js
optimization: {
  // Split Vaadin components to vendor bundle
  splitChunks: {
    chunks: 'all',
    // Extract Highcharts.js to its own bundle
    cacheGroups: {
      charts: {
        test: /[\\/]node_modules[\\/]highcharts[\\/]/,
        chunks: 'all'
      }
    }
  },
}
```

**Comment by Legioth** [comment]
Is it so that both those use cases could be implemented as high-level helpers on top of a generic low-level functionality that allows an add-on to have an impact on the generated webpack configuration?

If looking at the topic of generic webpack configuration, then I see two potential approaches:
1. The add-on contains custom Java code that is run when `webpack.generated.js` is generated
2. The add-on contains a static hardcoded file that is put into some appropriate location and then included into the main `webpack.config.js` in the same way as how `webpack.generated.js` is included.

**Comment by web-padawan** [comment]
> those use cases could be implemented as high-level helpers on top of a generic low-level functionality that allows an add-on to have an impact on the generated webpack configuration?

I don't think we want to expose internals by giving direct access to webpack configuration but this can be of course provided as part of low-level functionality.

A few more potential use cases (other than charts) are:

- `vaadin-cookie-consent`: a `cookieconsent` [library](https://bundlephobia.com/result?p=cookieconsent)
- `vaadin-rich-text-editor`: a [minified Quill copy](https://github.com/vaadin/vaadin-rich-text-editor/blob/master/vendor/vaadin-quill.min.js)

**Comment by web-padawan** [comment]
Renamed the issue to mention Vite - see [the documentation](https://vitejs.dev/guide/build.html#customizing-the-build) for more detail on how to implement this.
