### ISSUE TITLE
Introduce a new abstract layer between DataView and DataCommunicator

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#8344]
Decouple DataView classes from component specifics and make them stateless by introducing an extra abstraction layer in the middle. With this new API a DataView implementations shouldn't know whether there is a DataCommunicator behind, or not.

This new API should include the following:
- getting data provider instance
- add size change listener
- get all items
- get data size.

**Comment by caalador** [comment]
The more I try to make this better the more I feel we shouldn't have this layer of abstraction at all and have the DataView(s) manage these things.
