### ISSUE TITLE
Patient portal nightly is failing in 3.2

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#8348]
https://bender.vaadin.com/viewLog.html?buildId=148404&

All tests are filing but this may be because of Chrome cluster.
I've restarted it, close the ticket if this helps.

**Comment by caalador** [comment]
Just as a note. the issue may be with the scroll position where the item is not visible and thus not interactable. If you can track down which element it is that fails this then add a scrollIntoView JS execution for it `((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", element);`
