### ISSUE TITLE
lit-element added as a dev dependency to projects

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#8351]
All Vaadin 16.0.0.beta2 projects get `lit-element` both as a `devDependency` and a `dependency`. This does not make sense as you don't use `lit-element` only during development, you need it runtime. It also causes
```
npm WARN The package lit-element is included as both a dev and production dependency.
```

You can see the duplicates even here
https://github.com/vaadin/skeleton-starter-flow-spring/blob/master/package.json#L48

**Comment by pleku** [comment]
For Flow 3.1 I think removing this should have been done when live reload was disabled, but was probably forgotten.

For 3.2+ it is needed for compiling the client engine for devmode, but should not be in the production bundle ? Not sure how we can avoid it there

**Comment by Artur-** [comment]
How is the compilation of client engine related to my project?

**Comment by joheriks** [comment]
## Acceptance criteria
- Flow 3.1:
  - [ ] Remove `lit-element` from `NodeUpdater` [default dev dependencies](https://github.com/vaadin/flow/blob/3.1/flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java#L286).
- Flow 3.2: 
  - [ ] Move `lit-element` to `NodeUpdater`s default *runtime* dependencies.
  - [ ] Exclude `VaadinDevmodeGizmo.js` (+ all exclusive transitive dependencies) from the production webpack bundle
