### ISSUE TITLE
Preserve on refresh is broken

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#8355]
Use `master`  branch.
Open out `test-root-context` test `com.vaadin.flow.uitest.ui.PreserveOnRefreshView`.
Refresh the page.
URL is replaced with `http://localhost:8888/view/`  instead being `http://localhost:8888/view/com.vaadin.flow.uitest.ui.PreserveOnRefreshView`.

**Comment by denis-anisimov** [comment]
This line causes the behavior:
`getPage().executeJs(CLIENT_REPLACESTATE_TO, getInternals().getActiveViewLocation().getPathWithQueryParameters());`.

Currently it's line 130 in `JavaScriptBootstrapUI`:
https://github.com/vaadin/flow/blob/072d4503532bfa5dc27b4dc844535d3c6161938a/flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java#L130

**Comment by manolo** [comment]
@denis-anisimov  Is this a regression from 15 to 16 ?
@bogdanudrescu might it be fixed in your changes to the javascriptBootstrapUI ?

**Comment by denis-anisimov** [comment]
I don't know whether this is a regression or not.
The information which is already provided points the exact line in the code which causes the beahvior.

**Comment by haijian-vaadin** [comment]
Seems I cannot reproduce it anymore. Could you @denis-anisimov also help to verify if it's fixed?

**Comment by denis-anisimov** [comment]
Yes, this is already fixed somehow in the `master`  branch.
