### ISSUE TITLE
@PreserveOnRefresh does not restore Dialog

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow#8373]
After refreshing the page (F5) the dialog is no longer open. This happens with Vaadin 15.0.6 and 16.0.0.beta2 (works as expected with Vaadin 14.1.28) 

```
Dialog d = new Dialog();
add(new Button("click", ev -> d.open()));
```

**Comment by joheriks** [comment]
Root cause is #7587.

**Comment by syampillai** [comment]
This bug exists in Vaadin 16.0.0 too.
