### ISSUE TITLE
InternalErrorIT.sessionExpired_refreshByDefault is flaky

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#8375]
https://bender.vaadin.com/viewLog.html?buildId=149357&tab=buildResultsDiv&buildTypeId=Flow_Flow21_Flow21Snapshot

`Caused by: java.lang.AssertionError: After killing the session, the page should be refreshed, resetting the state of the UI.`

**Comment by joheriks** [comment]
Backporting #7739 to 2.2 and 2.3.
