### ISSUE TITLE
vaadin 15  and openliberty 20.0.0.x throws javax.servlet.ServletException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by ollin** [vaadin/flow#8383]
Starting the example project from https://vaadin.com/start/latest with openliberty ( https://openliberty.io/ ) results in an exception.

- (Open Liberty 20.0.0.4/wlp-1.0.39.cl200420200401-1714) on OpenJDK 64-Bit Server VM, version 13.0.2+6-MTS (en_US)
- Vaadin 15.0.6
- Ubuntu 20.04

see attachted example project:

[cdi-java-ee-vadin15.zip](https://github.com/vaadin/flow/files/4650433/cdi-java-ee-vadin15.zip)

run
```
npm install
mvn clean package liberty:run
```
results in:
```
[INFO] [WARNING ] CWWWC0001W: The [com.vaadin.flow.server.startup.DevModeInitializer@16332e8e] ServletContainerInitializer, located in the following application [dada Project], produced the following error while invoking the onStartup method: [javax.servlet.ServletException: java.lang.reflect.InvocationTargetException
[INFO]  at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.onStartup(ClassLoaderAwareServletContainerInitializer.java:99)
[INFO]  at com.ibm.ws.webcontainer.webapp.WebApp.initializeServletContainerInitializers(WebApp.java:2530)
[INFO]  at [internal classes]
[INFO] Caused by: java.lang.reflect.InvocationTargetException
[INFO]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[INFO]  at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.onStartup(ClassLoaderAwareServletContainerInitializer.java:94)
[INFO]  ... 2 more
[INFO] Caused by: java.lang.IllegalStateException: There are neither 'flow-build-info.json' nor 'webpack.config.js' file available in the project/working directory. Ensure 'webpack.config.js' is present or trigger creation of 'flow-build-info.json' via running 'prepare-frontend' Maven goal.
[INFO]  ... 14 more
[INFO] ]
[INFO] [err] [Default Executor-thread-6] INFO com.vaadin.cdi.CdiServletDeployer - Automatically deploying CDI Vaadin servlet to /*
[INFO] [ERROR   ] SRVE0283E: Exception caught while initializing context: java.lang.IllegalStateException: There are neither 'flow-build-info.json' nor 'webpack.config.js' file available in the project/working directory. Ensure 'webpack.config.js' is present or trigger creation of 'flow-build-info.json' via running 'prepare-frontend' Maven goal.
[INFO]  at com.vaadin.flow.server.DeploymentConfigurationFactory.verifyMode(DeploymentConfigurationFactory.java:436)
[INFO]  at com.vaadin.flow.server.DeploymentConfigurationFactory.readBuildInfo(DeploymentConfigurationFactory.java:186)
[INFO]  at com.vaadin.flow.server.DeploymentConfigurationFactory.createInitParameters(DeploymentConfigurationFactory.java:165)
[INFO]  at com.vaadin.flow.server.DeploymentConfigurationFactory.createPropertyDeploymentConfiguration(DeploymentConfigurationFactory.java:127)
[INFO]  at com.vaadin.flow.server.startup.ServletDeployer$StubServletConfig.createDeploymentConfiguration(ServletDeployer.java:184)
[INFO]  at com.vaadin.flow.server.startup.ServletDeployer.lambda$getServletConfigurations$0(ServletDeployer.java:242)
[INFO]  at java.base/java.util.Optional.ifPresent(Optional.java:176)
[INFO]  at com.vaadin.flow.server.startup.ServletDeployer.getServletConfigurations(ServletDeployer.java:241)
[INFO]  at com.vaadin.flow.server.startup.ServletDeployer.contextInitialized(ServletDeployer.java:219)
[INFO]  at com.vaadin.flow.server.startup.ServletContextListeners.contextInitialized(ServletContextListeners.java:42)
[INFO]  at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2417)
[INFO]  at [internal classes]
```

**Comment by mehdi-vaadin** [comment]
@ollin thank you for reporting this issue. Your example project misses `vaadin-maven-plugin`. The `pom.xml` only has one in `production` profile. You need `vaadin-maven-plugin` in development mode too. With a different goal (`prepare-frontend`) though. See [pom.xml](https://github.com/vaadin/skeleton-starter-flow-cdi/blob/v15/pom.xml#L151) of the project base for Vaadin and CDI.
```
<plugin>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-maven-plugin</artifactId>
    <executions>
        <execution>
            <goals>
                <goal>prepare-frontend</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
By the way, it seems that the `contextRoot` in `server.xml` should be set to a literal value instead of an expression. I had to change it to make it work. I'm not a Liberty expert though. Maybe I'm wrong.

Please let us know if this comment fixes your problem.

**Comment by ollin** [comment]
Thanks Medhi for looking at it. I did not transfer all configurations when creating the example project. Next, I didn't pay attention with the error messages. So this was definitely an issue on my side. 

But your comment put me in the right direction. The settings of the plugin "liberty-maven-plugin" were not correct. Big Thx for that!

So Vaadin 14 and openliberty work together in dev-mode. I can boot from the IDE and via mvn CLI without problems. Thanks a lot!

The live reload does not yet work. I'm trying here:  https://github.com/ollin/cdi-java-ee-vadin14

**Comment by mehdi-vaadin** [comment]
>The live reload does not yet work.

I'm afraid we don't support live reload with Liberty Maven plugin at the moment. I encourage you to create another issue for that. You might want to consider using TomEE Maven plugin for development time. You can find more info about that on [Hot Deploy of CDI Applications](https://vaadin.com/docs/v14/flow/workflow/tutorial-cdi-live-reload.html) document.

**Comment by ollin** [comment]
@mehdi-vaadin live reload in openliberty works with this simple example. I didn't test advanced features. But so far, so good... :)

**Comment by mehdi-vaadin** [comment]
@ollin thanks for the update :)
