### ISSUE TITLE
Measure memory usage with a complex app with and without template

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#840]

**Comment by SomeoneToIgnore** [comment]
https://github.com/vaadin/flow/commit/aa1a059b6dd17cbe4ea99ef7c4cf0e1b5a039305

This commit removed the tests from the system.
We need to restore the tests and tune TeamCity to collect performance statistics.
Examples of the previous configurations can be found at the bottom of: http://r2d2.devnet.vaadin.com/viewType.html?buildTypeId=Flow_FlowSnapshot&tab=buildTypeStatistics&branch_Flow_Snapshot=__all_branches__

**Comment by SomeoneToIgnore** [comment]
Alternative option: use patient-portal project that was created to run those tests, create a standalone job that checks out the portal and runs tests.

In my opinion, this way is more preferable since it does not complicate flow poms and codebase.

**Comment by pleku** [comment]
Issue moved to [vaadin/patient-portal-demo-flow #71](https://github.com/vaadin/patient-portal-demo-flow/issues/71) via [**ZenHub**](https://www.zenhub.com/)
