### ISSUE TITLE
When StreamResourceWriter fails, the server should return 500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#8426]
This bug seems to be a duplicate of #6076 however it could be something completely else, so I'll rather file a new bug.

Vaadin 14.2.0; use the Skeleton Starter for a base (the v14 branch), and overwrite the MainView.java with the following:

```java
@Route("")
@PWA(name = "Project Base for Vaadin", shortName = "Project Base", enableInstallPrompt = false)
@CssImport("./styles/shared-styles.css")
@CssImport(value = "./styles/vaadin-text-field-styles.css", themeFor = "vaadin-text-field")
public class MainView extends VerticalLayout {

    public MainView() {

        add(new Anchor(new StreamResource("foo.png", new StreamResourceWriter() {
            @Override
            public void accept(OutputStream outputStream, VaadinSession vaadinSession) throws IOException {
                throw new IOException("Simulated");
            }
        }), "foobar"));

    }
}
```

The exception is properly logged into the console, however the browser responds with 200 OK.

### Expected behavior
The browser should respond with 500 INTERNAL SERVER ERROR
### Actual behavior
The browser responds with 200 OK and a web page is displayed, containing the following text:

```
The image “http://localhost:8080/VAADIN/dynamic/resource/0/1d766ff2-a12f-4aec-bf96-9120c1fdbbe3/foo.png” cannot be displayed, because it contains errors.
```
![Screenshot from 2020-05-27 09-21-35](https://user-images.githubusercontent.com/254091/82984823-91cd9b00-9ffb-11ea-8c19-18b84776d419.png)

**Comment by mvysny** [comment]
![Screenshot from 2020-05-27 09-23-26](https://user-images.githubusercontent.com/254091/82984932-c0e40c80-9ffb-11ea-8621-cf9d8f9ff0b9.png)

What's weird is that the browser says that the resource foo.png comes from a service worker.

**Comment by caalador** [comment]
As far as I could follow on the server the response should return a 500 not a 200.

**Comment by mvysny** [comment]
Could it be that it's the service worker who turns 500 into 200 somehow?

**Comment by caalador** [comment]
I don't have the service worker and it still gets 200 so it probably isn't that.

**Comment by denis-anisimov** [comment]
Can't reproduce this with `14.5.2` ,
500 Server error status is the status code for the image URL.
