### ISSUE TITLE
Make DefaultInstantiator extendable

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow#8427]
Currently, if you extend `DefaultInstantiator` and register your new custom instantiator through SPI, the custom `Instantiator` must be instantiated through a no-arg constructor. This constructor will not have access to a `VaadinService` instance and thus the `private VaadinService service` member variable in the parent `DefaultInstantiator` can never be set. This, in turn, means the `init` method will return false and the custom Instantiator won't be picked up. If the `init` method is overridden to return true, the methods requiring the `VaadinService` instance will fail.

**Comment by mvysny** [comment]
A workaround is to override the `VaadinServletService.getInstantiator()` and create your own instantiator there.

**Comment by mvysny** [comment]
Use-case for this: to provide cached route instances.

**Comment by mvysny** [comment]
Note that in Vaadin 14.6, it will be possible to override an `InstantiationFactory`, removing the need to have a custom `VaadinServlet`.

**Comment by mvysny** [comment]
Even better solution: don't extend DefaultInstantiator but delegate to it:

```java
@WebServlet(urlPatterns = "/*", asyncSupported = true)
public class MyServlet extends VaadinServlet {

    @Override
    protected VaadinServletService createServletService(DeploymentConfiguration deploymentConfiguration) throws ServiceException {
        VaadinServletService service = new VaadinServletService(this,
                deploymentConfiguration) {
            @Override
            protected Instantiator createInstantiator() throws ServiceException {
                Instantiator defaultIn = super.createInstantiator();
                return new MyInstantiator(defaultIn);
            }
        };
        service.init();
        return service;
    }

    public static class MyInstantiator implements Instantiator {
        private final Instantiator delegate;
        public MyInstantiator(Instantiator delegate) {
            this.delegate = delegate;
        }
        @Override
        public boolean init(VaadinService service)
        {
            return delegate.init(service);
        }

        @Override
        public Stream<VaadinServiceInitListener> getServiceInitListeners()
        {
            return delegate.getServiceInitListeners();

        }

        @Override
        public I18NProvider getI18NProvider()
        {
            return delegate.getI18NProvider();
        }

        @Override
        public <T> T getOrCreate(Class<T> type)
        {
            // try to create the class yourself, or fallback to delegate.getOrCreate(type)
        }

        @Override
        public <T extends Component> T createComponent(Class<T> componentClass)
        {
            // try to create the class yourself, or fallback to delegate.getOrCreate(type)
        }
    }
}
```

This is bloody steps-in-the-dark try-and-fail. See rant at https://github.com/vaadin/docs/issues/739

**Comment by denis-anisimov** [comment]
There is `InstantiatorFactory` which passes `VaadinService` argument to the method which creates an `Instantiator`.
As a result `Intstantiator` impl can extends `DefaultInstantiator` now since there is a service instance available.
This works for 2.6+.

**Comment by mvysny** [comment]
Yeah I can see `InstantiatorFactory` but it's not clear how to pass in a custom implementation to Vaadin! See https://github.com/vaadin/docs/issues/739
