### ISSUE TITLE
HasClearButton interface

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#8443]
Vaadin 14.2.0.

A lot of components have `isClearButtonVisible()` and `setClearButtonVisible()` method. Excerpt from VoK's `FilterBar.kt` file:

```
        (field as? TextField)?.isClearButtonVisible = true
        (field as? TextArea)?.isClearButtonVisible = true
        (field as? IntegerField)?.isClearButtonVisible = true
        (field as? BigDecimalField)?.isClearButtonVisible = true
        (field as? EmailField)?.isClearButtonVisible = true
        (field as? PasswordField)?.isClearButtonVisible = true // okay this case is not really that useful :-D
        (field as? ComboBox<*>)?.isClearButtonVisible = true
        (field as? DatePicker)?.isClearButtonVisible = true
        (field as? TimePicker)?.isClearButtonVisible = true
```

It would be good to have `HasClearButton` interface which those components would then implement.

**Comment by pleku** [comment]
What is the use case ? Is it testing related or being able to build generic things for building forms or such ?

**Comment by mvysny** [comment]
In this particular case it's intended to populate Grid's Filter Bar with filter components. It's handy to have the clear buttons visible for all filter components.

**Comment by knoobie** [comment]
@mvysny I think I have accidentally fixed this issue with https://github.com/vaadin/flow-components/pull/2320

**Comment by mvysny** [comment]
@knoobie sweet, thank you, that's exactly what I wished for. Closing.
