### ISSUE TITLE
Prevent respecting view specific Push annotation for V15+ bootstrap mode

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#8447]
The problem is : it's not clear when view specific Push annotation should be used and when it should not.

Currently the only way : you have to know that it's necessary to do check for the mode (whether this is v14 bootstrap mode or a new one) and then apply the logic or not.

This knowledge is hidden, not obvious and is error-prone.

The suggestion is : do not allow Push annotations on view at all. Static validator should just throw if the app is running V15+ mode and there is a view with Push annotation.

Currently it just log a warning which can be easily disregarded.

Another approach is to introduce an internal API to get Push annotation from the view which changes its behavior based on the mode.

**Comment by denis-anisimov** [comment]
@Legioth , @pleku do we agree that we go with the throwing approach ?

**Comment by Legioth** [comment]
I would prefer it if the legacy bootstrap mode could keep working exactly the same way as in V14, while the new default "app shell" mode would throw for misplaced `@Push` annotations.

**Comment by denis-anisimov** [comment]
Sure.
That's what suggested:
- V14 mode will still work as is
- V15+ mode always throw an exception (currently it throws only if there is an AppShell class).

**Comment by vlukashov** [comment]
I can see one problem with this suggestion:

When I upgrade an existing V14 LTS project to V15+, with this suggestion my application will stop working even though I do not change anything except for the Vaadin version. I am not using the app shell (no `AppShellConfigurator` class in my app), all views are server-side Java views as in V14, and as a developer I would see no reason why my per-view push configuration should stop working.

@Legioth, have you considered that trade-off here?

**Comment by Legioth** [comment]
Oh right. I guess that's the reason for the apparently weird logic of having different behaviour depending on whether an `AppShellConfigurator` class is present.

In this case, I'd still be leaning towards making it throw. The reason for that is that the practice of per-view `@Push` annotations is overall problematic and there has been talks about getting rid of it for that reason. From that point of view, I think the transition between V14 LTS to any newer version would be an appropriate breaking point. It's simply a band-aid that would have to be ripped off sooner or later.

**Comment by pleku** [comment]
>V14, and as a developer I would see no reason why my per-view push configuration should stop working.

This is because the client side bootstrapping is used by default ? 

I think it is better to have a clear indication when jumping from 14 LTS to next version (a major version bump in Flow) that you need to do changes than give an impression that things work out of the box but really don't.

**Comment by vlukashov** [comment]
> the practice of per-view @Push annotations is overall problematic and there has been talks about getting rid of it

That could justify throwing an exception and failing the build right away. I can go with that.

Have we published any deprecation warnings for this usage of Push? Generally I would consider a good practice to first release a new major version that shows deprecation warnings but keeps the functionality working, and removing the deprecated functionality in one of the following major versions.

In this case it looks like that's exactly what we are doing here by having warnings in V15 and exceptions in V16. We should still mention it in the release notes / migration docs. Is there an separate issue to make that docs update?

**Comment by Legioth** [comment]
To do everything by the book, we should not only consider migration from 15 to 16, but also migration from 14 to the next LTS.
