### ISSUE TITLE
CCDM: Throwing exceptions instead of logging for breaking changes

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#8454]
In Vaadin 15+, there are some breaking changes due to the new way of bootstrapping. For example, `@PWA` and `@Push` annotations have to be added to the `AppShellConfigurator`.

The current behavior is that it logs information like below in the console.
```
Found app shell configuration annotations in non `AppShellConfigurator` classes.
Please create a custom class implementing `AppShellConfigurator` and move the following annotations to it:
    - @Push from com.vaadin.flow.uitest.ui.TrackMessageSizeView
    - @Push from com.vaadin.flow.uitest.ui.LongPollingPushView
...
```
The downside is that people can overlook the logs and don't realize that their application is broken. 

To fix this, let's throw the exception instead of just logging the errors, so that a developer would be immediately aware of things I need to do when migrating from a legacy bootstrap mode.

**Comment by knoobie** [comment]
Looks like https://github.com/vaadin/flow/issues/8447 or?

**Comment by haijian-vaadin** [comment]
Yep, closing this one as a duplicate of #8447
