### ISSUE TITLE
vaadin-devmode-gizmo not visible depending on view content

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/flow#8460]
### Description of the bug

Live reload is UI component is shown in dev mode, but depending on the view content/styles in some cases it's not visible nor interactable.
### Minimal reproducible example
Can be reproduced in [bookstore-example](https://github.com/vaadin/bookstore-example/tree/v14) by bumping version to 14.3.0.alpha1 (flow 2.3.0.alpha1). I couldn't test with 16.0.0.rc1 (flow 3.1.0) since #8432 prevents live reload to be shown.

### Expected behavior
Gizmo window is shown as in login view:
![image](https://user-images.githubusercontent.com/9820084/83248886-6939d280-a1ae-11ea-9d32-edb49aa58384.png)

### Actual behavior
After login view gizmo is still in DOM but not visible nor interactable.
![image](https://user-images.githubusercontent.com/9820084/83248998-97b7ad80-a1ae-11ea-9d00-8f46c9588d55.png)

### Versions:
    - Vaadin / Flow version: 14.3.0.alpha1 / 2.3.0.alpha1
    - Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T21:33:14+03:00)
    - Java version: 1.8.0_241
    - OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"

**Comment by pleku** [comment]
> I couldn't test with 16.0.0.rc1 (flow 3.1.0) 

16 doesn't have the live reload so it would be impossible anyway.

**Comment by joheriks** [comment]
Which browser? Unable to reproduce with Firefox 76 or Safari on macOS.

**Comment by alvarezguille** [comment]
Chrome Version 83.0.4103.61

**Comment by alvarezguille** [comment]
In inventory view the following overlays are visible:
![image](https://user-images.githubusercontent.com/9820084/83380760-74c40e00-a3e7-11ea-9f7b-4ca4e376b751.png)
![image](https://user-images.githubusercontent.com/9820084/83380817-991fea80-a3e7-11ea-808f-65648ebdfb43.png)

But after clicking details on the second overlay it's not visible anymore:
![image](https://user-images.githubusercontent.com/9820084/83380928-ed2acf00-a3e7-11ea-924d-a815112d2430.png)

This gizmo is not visible on all views:
![image](https://user-images.githubusercontent.com/9820084/83381011-2b27f300-a3e8-11ea-9fd6-90a5331aa491.png)
