### ISSUE TITLE
Change parameter of Registration.once(Command) to Registration

### ISSUE THREAD

**Issue by mperktold** [vaadin/flow#8466]
[Pull request 7383](https://github.com/vaadin/flow/pull/7383) introduced a couple of handy utility methods for `Registration`.

One of them is `Registration.once(Command)`, which allows to create a idempotent registration, i.e. one that does nothing if already removed:

```java
public Registration addCallback(Runnable callback) {
  callbacks.add(calback);
  return Registration.once(() -> callbacks.remove(callback);
}
```

While this works great, it would be more composable it accepted a `Registration` instead of a `Command`. Especially when delegating to other registering methods, you could then simply wrap the returned registration using once instead of converting it to a Command using `::remove`.

For example, the above can be rewritten using the `addAndRemove` shortcut method, which was introduced in the same pull-request:

```java
public Registration addCallback(Runnable callback) {
  return Registration.once(addAndRemove(callbacks, callback)::remove);
}
```

But if `Registration.once` accepted a `Registration`, this could simply be:

```java
public Registration addCallback(Runnable callback) {
  return Registration.once(addAndRemove(callbacks, callback));
}
```

It also makes sence on a conceptual level: In order for `Registration.once` to work properly, the command must remove something, so it has to be something like a registration.

If backward compatibility is a concern, you could leave the method accepting a `Command` and add a new one that accepts Registrations. To avoid ambiguity when passing lambdas, the new one should probably become an method on Registration that could be used like this:

```java
public Registration addCallback(Runnable callback) {
  return addAndRemove(callbacks, callback).once();
}
```

One question here is which one should be the primitive and which one should delegate to the other.
To avoid overhead of converting from one interface to the other, the primitive should be the one that is used more often.

But personally, I`m also fine with changing the existing method and introducing a breaking change.

**Comment by Legioth** [comment]
All `Registration` instances are supposed to be idempotent-ish. The "ish" comes from `addAndRemove` where an old registration instance would remove an item that has been added back again. This is assumed to be an acceptable compromise in the absence of any use case where it would matter in practice. If there is one, then please let us know :)

What that means is that wrapping an existing registration in `once` would effectively be a no-op and thus quite pointless. Instead, the purpose of `once` is to take a generic callback that isn't idempotent, e.g. the [page resize listener registration](https://github.com/vaadin/flow/blob/9db0208ec9fa592e894eb671f46fbe929ede5fb2/flow-server/src/main/java/com/vaadin/flow/component/page/Page.java#L82) that uses a counter, and turn that into something that can be used as a registration.

(Yes I know, that example is implemented the "wrong" way since does `once(combine(a, b)::remove)` instead of the more logical `combine(once(a), b)`. The idea there is that if we already have the overhead of doing `once`, then we could just as well benefit from it to also avoid the overhead doing `remove()` again on `b`)

**Comment by mperktold** [comment]
> 
> 
> All `Registration` instances are supposed to be idempotent-ish.

That was my intuition as well, but then I got proven wrong by Registrations returned by `EventBus.addListener`, which [fail if the listener is not found](https://github.com/vaadin/flow/blob/fc760bf228f1f831f3d1e7578548634bd13e73b1/flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java#L339-L342). As a consequence, all Registrations returned by `Component.addListener` and `ComponentUtil.addListener` have the same behavior.

> 
> The "ish" comes from `addAndRemove` where an old registration instance would remove an item that has been added back again. This is assumed to be an acceptable compromise in the absence of any use case where it would matter in practice. If there is one, then please let us know :)

No I think you are right, this should be OK.

> 
> What that means is that wrapping an existing registration in `once` would effectively be a no-op and thus quite pointless. Instead, the purpose of `once` is to take a generic callback that isn't idempotent, e.g. the [page resize listener registration](https://github.com/vaadin/flow/blob/9db0208ec9fa592e894eb671f46fbe929ede5fb2/flow-server/src/main/java/com/vaadin/flow/component/page/Page.java#L82) that uses a counter, and turn that into something that can be used as a registration.

Also in this example you have a `Registration` which comes from `Component.addListener` and is not idempotent, so you need to wrap it using `once`. To do that, you have to convert it to a command first using `::remove`, but that would not be needed if `once` accepted a `Registration`.

If you happen to have a generic callback instead of an existing `Registration`, i.e. a lambda or a method reference, it can be captured as `Registration` without any problems, since it is also a functional interface and both `Command` and `Registration` have no parameters and return `void`.

On the other hand, we might also consider to remove the need for `once` in these cases altoghether and make `EventBus.addListener` idempotent. Then we could really assume that `Regstrations` are idempotent, and `once` will mostly be used to construct new idempotent `Registrations` from non-idempotent lambdas.

> 
> (Yes I know, that example is implemented the "wrong" way since does `once(combine(a, b)::remove)` instead of the more logical `combine(once(a), b)`. The idea there is that if we already have the overhead of doing `once`, then we could just as well benefit from it to also avoid the overhead doing `remove()` again on `b`)

Yes that makes sense. But look, you wrote `combine(once(a), b)`, while the correct version would be `combine(once(a::remove), b)`, even though the `::remove` part just adds useless noise.

**Comment by Legioth** [comment]
Let's aim at fixing the registration returned from the component event bus. https://github.com/vaadin/flow/issues/8506
