### ISSUE TITLE
Unclear comment in webpack.config.js

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#8485]
The generated webpack.config.js says
```
/**
 * This file has been autogenerated as it didn't exist or was made for an older
 * incompatible version.
 *
 * This file can be used for manual configuration. It will not be modified
 * if the flowDefaults constant exists.
 */
```

This is quite contradicatory as it says:
* Do your conf here. 
* Nobody else will modify it
* It might have been overwritten because there was an older version in place

So I should write conf here but it might be overwritten.

If I should indeed write my conf here, it sounds like it should never be overwritten by somebody else and the text could be e.g.

```
This file contains project specific customizations for the webpack build.

Defaults are provided in an autogenerated webpack.generated.js file and used by this file. The webpack.generated.js file is overwritten on each build and no customization can be done there.
```

**Comment by caalador** [comment]
The message is truly missleading as we only log an exception if webpack.generated.js is not referenced from the file and generate a new one only if no file exists.

Logged warning:
`Flow generated webpack configuration was not mentioned in the configuration file: webpack.config.js. Please verify that './webpack.generated.js' is used in the merge or remove the file to generate a new one.`
