### ISSUE TITLE
CDI Add-on IT tests failing in 3.2 branch

### ISSUE THREAD

**Issue by jm-ferreira** [vaadin/flow#8491]
CDI Add-on is failing in 3.2 branch. 26 tests in total.

InstantiatorCustomizeTest.instantiatorCustomizedByAlternative 

InstantiatorCustomizeTest.instantiatorCustomizedByDecorator 
ServiceTest.errorHandlerCustomized  
ServiceTest.sessionDestroyEventObserved 
ServiceTest.sessionExpiredMessageCustomized 
TemplateTest.scopedComponentInjectedToTemplate
 itest.PushTest 
RouteContextTest.eventObserved 
RouteContextTest.navigateFromRootToMasterReleasesRootInjectsEmptyBeans |  
RouteContextTest.navigationFromApartToMasterReleasesGroup |  
RouteContextTest.navigationFromAssignedToMasterHoldsGroup |  
RouteContextTest.postponedNavigationDoesNotCreateTarget |  
RouteContextTest.rerouteReleasesSource |  
SessionContextTest.httpSessionCloseDestroysSessionContext |  
SessionContextTest.sameSessionIsAccessibleFromUIs |  
SessionContextTest.vaadinSessionCloseDestroysSessionContext |  
SmokeTest.injectionDoesNotHappenWithDisabledCdiServlet |  
SmokeTest.injectionHappensWithEnabledCdiServlet |  
UIContextTest.beanDestroyedOnSessionClose |  
UIContextTest.beanDestroyedOnUIClose |  
UIContextTest.normalScopedBeanInjectedToLargerScopeChangesWithActiveUI |  
UIContextTest.observerCalledOnInstanceAttachedToUI |  
UIContextTest.sameScopedComponentInjectedInOtherView |  
UIContextTest.viewSurvivesNavigation |  
UIEventsTest.navigationEventsObserved |  
UIEventsTest.pollEventObserved

Requires further investigation.

**Comment by denis-anisimov** [comment]
The ticket is in a wrong repository.
This is Flow repository but the failures are in CDI repository.
Should have been created in CDI repository.
