### ISSUE TITLE
Three IT tests in Beverage Buddy are failing

### ISSUE THREAD

**Issue by jm-ferreira** [vaadin/flow#8492]
Regardless of the build, nightlies for Java 11 and 12 and 14.1 snapshot build are failing

ReviewsListIT.buttonIsLumoThemed[ANY_Chrome_] |  
ReviewsListIT.createEditAndRemoveReview[ANY_Chrome_] |  
ReviewsListIT.numberOfReviewsIsCorrect[ANY_Chrome_]

Requires investivagation

**Comment by joheriks** [comment]
Java 11 and 12 runs are against platform `14.1`, they could be updated to run against `14.2`. Not sure do we need the 14.1 starter builds still also.

**Comment by joheriks** [comment]
The tests started failing after this commit:
https://github.com/vaadin/beverage-starter-flow/commit/3cbae233aec4bb0f270f360fd13cff9227e5b061

This seems to be because `package.json` is updated to match what Flow 2.2 generated and then it braks on the downgrade to 14.1 (confirmed by first deleting `package-*.json` and then running the ITs → passes). Should we remove the 14.1 starter tests.

**Comment by jm-ferreira** [comment]
After changing the `vaadin-version` parameter to `14.3-SNAPSHOT`, builds are passing again. No further action needed, closing this issue.

**Comment by joheriks** [comment]
Can you also update the other tests nightly starter tests (Java 11 and Java 12), e.g., "Java 11: Skeleton Starter Spring" still builds against `14.1-SNAPSHOT`.

Also [Flow Starters 14.1 builds](https://bender.vaadin.com/project.html?projectId=Flow_StarterTests_FlowStartersItPlatform141Snapshot&tab=projectOverview&branch_Flow_StarterTests_FlowStartersItPlatform141Snapshot=%3Cdefault%3E) should be updated to build against 14.3.

**Comment by jm-ferreira** [comment]
Changed Flow Starters IT Platform 14.3 Snapshot to run builds on 14.3-SNAPSHOT.
I left the project ID unchanged as it could break some links. If required I can change this too.

**Comment by jm-ferreira** [comment]
All [starter nightlies](https://bender.vaadin.com/project.html?projectId=Flow_StarterTests_NightlyBuilds) changed to run on 14.3-SNAPSHOT, also.
