### ISSUE TITLE
Using Addon that references to a template file from npm package doesn't work in production mode

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#8493]
To reproduce:
1. Download the attached project
2. Run `mvn clean jetty:run -Pproduction`
3. Go to localhost:8080
4. You see an exception from the log
`java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'color-picker-field' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file`

Observations:
1. The example uses the [color picker field addon](https://vaadin.com/directory/component/color-picker-field-for-flow), which references the template file through npm package `@JsModule("@appreciated/color-picker-field/src/color-picker-field.js")`
2. The addon works in V14.1 and V14.2
3. The addon works in development mode in V15 and V16
4. The addon does not work in production mode in V15 and V16

[example.zip](https://github.com/vaadin/flow/files/4721411/example.zip)

**Comment by manolo** [comment]
This is another corner case of the problem described in https://github.com/vaadin/flow/issues/8053
The issue was introduced in the https://github.com/vaadin/flow/commit/9e037137b4a39e88b1201ef521d9996c2faffe3e change which optimizes the size of the stats file stored in final `war` file.
In consequence stats file in production differs from the one used during devmode.

It can be checked by running the attached project using `V15.0.0.beta1` that does not fail, and `V15.0.0.rc1` that fails

I did a quick research and comparing the files there is a block in dev-mode that includes sources for the addon sources in devmode different to the one in production

- DevMode
```
{
 "hash": "f9b0b320c1711b3d3fe9",
 "assetsByChunkName": {
  "bundle": "build/vaadin-bundle-37aa0ca9571e68253d47.cache.js",
  "export": "build/vaadin-export-5e943eab1a6a66a2e61e.cache.js"
 },
 "chunks": [
  {
   "id": 0,
   "names": [],
   "files": [
    "build/vaadin-0-b72fc8ece0bf043d4a70.cache.js"
   ],
   "hash": "553ae09764a756374bd6",
   "modules": [
    {
     "id": "../node_modules/.pnpm/registry.npmjs.org/@appreciated/color-picker-field/2.0.0-beta.4/node_modules/@appreciated/color-picker-field/src/color-picker-field.js",
     "name": "../node_modules/.pnpm/registry.npmjs.org/@appreciated/color-picker-field/2.0.0-beta.4/node_modules/@appreciated/color-picker-field/src/color-picker-field.js",
     "source": ...
    },
    {
     "id": "../node_modules/.pnpm/registry.npmjs.org/@appreciated/color-picker-field/2.0.0-beta.4/node_modules/@appreciated/color-picker-field/theme/lumo/color-picker-field-styles.js",
     "name": "../node_modules/.pnpm/registry.npmjs.org/@appreciated/color-picker-field/2.0.0-beta.4/node_modules/@appreciated/color-picker-field/theme/lumo/color-picker-field-styles.js",
     "source": ...
    },
    ...
```

- ProdMode
```
{
 "hash": "852f4c3375de68cd5c96",
 "assetsByChunkName": {
  "bundle": "build/vaadin-bundle-7939b486526373fdb508.cache.js",
  "export": "build/vaadin-export-c541e68fbbb7e9b8f5dd.cache.js"
 },
 "chunks": [
  {
   "id": 0,
   "names": [
    "bundle"
   ],
   "files": [
    "build/vaadin-bundle-7939b486526373fdb508.cache.js"
   ],
   "hash": "c73d7f02aee62936131d",
   "modules": [
    {
     "id": 104,
     "name": "../target/index.ts + 2 modules"
    }
   ]
  },
```

**Comment by manolo** [comment]
UPDATE: the project in V14.2.0 does not fail, but it has the commit optimising the stats

**Comment by manolo** [comment]
Just for adding more info, I did some manual adjustments to the stats, and removing all source blocks but those whose name is in  `target/frontend/generated-flow-imports*.js` files, works always. But it needs that webpack visit those files somehow.

**Comment by kobazzo** [comment]
Thanks. Now what i must do to take the fix?

**Comment by caalador** [comment]
@kobazzo Until the next release 3.1.2 and the 16 version is out you would need to use the 3.1-SNAPSHOT

**Comment by kobazzo** [comment]
> @kobazzo Until the next release 3.1.2 and the 16 version is out you would need to use the 3.1-SNAPSHOT

Thanks.

3.1-SNAPSHOT of what? What is the pom import that i need to use?

thank you.

**Comment by caalador** [comment]
you should be able to update the Vaadin version to 16.0-SNAPSHOT

Else you might need to update with the following set:
```
<repositories>
        <repository>
            <id>vaadin-prereleases</id>
            <url>https://maven.vaadin.com/vaadin-prereleases/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
</repositories>

<pluginRepositories>
        <pluginRepository>
            <id>vaadin-prereleases</id>
            <url>https://maven.vaadin.com/vaadin-prereleases/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
</pluginRepositories>

<dependencies>
    <dependency>
        <groupId>com.vaadin</groupId>
        <artifactId>flow-server</artifactId>
        <version>3.1-SNAPSHOT</version>
    </dependency>
    <dependency>
        <groupId>com.vaadin</groupId>
        <artifactId>flow-client</artifactId>
        <version>3.1-SNAPSHOT</version>
    </dependency>
</dependencies>

<plugins>
    <plugin>
        <groupId>com.vaadin</groupId>
        <artifactId>flow-maven-plugin</artifactId>
        <version>3.1-SNAPSHOT</version>
    </plugin>
</plugins>
```

Note that you need to switch the vaadin-maven-plugin to flow-maven-plugin when you use this

**Comment by kobazzo** [comment]
> you should be able to update the Vaadin version to 16.0-SNAPSHOT
> 
> Else you might need to update with the following set:
> 
> ```
> <repositories>
>         <repository>
>             <id>vaadin-prereleases</id>
>             <url>https://maven.vaadin.com/vaadin-prereleases/</url>
>             <snapshots>
>                 <enabled>true</enabled>
>             </snapshots>
>         </repository>
> </repositories>
> 
> <pluginRepositories>
>         <pluginRepository>
>             <id>vaadin-prereleases</id>
>             <url>https://maven.vaadin.com/vaadin-prereleases/</url>
>             <snapshots>
>                 <enabled>true</enabled>
>             </snapshots>
>         </pluginRepository>
> </pluginRepositories>
> 
> <dependencies>
>     <dependency>
>         <groupId>com.vaadin</groupId>
>         <artifactId>flow-server</artifactId>
>         <version>3.1-SNAPSHOT</version>
>     </dependency>
>     <dependency>
>         <groupId>com.vaadin</groupId>
>         <artifactId>flow-client</artifactId>
>         <version>3.1-SNAPSHOT</version>
>     </dependency>
> </dependencies>
> 
> <plugins>
>     <plugin>
>         <groupId>com.vaadin</groupId>
>         <artifactId>flow-maven-plugin</artifactId>
>         <version>3.1-SNAPSHOT</version>
>     </plugin>
> </plugins>
> ```
> 
> Note that you need to switch the vaadin-maven-plugin to flow-maven-plugin when you use this

Thank you.
Trying to use 16.0-SNAPSHOT:


```
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8
        </project.reporting.outputEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <failOnMissingWebXml>false</failOnMissingWebXml>

        <vaadin.version>16.0.0</vaadin.version>
    </properties>
...
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-testbench</artifactId>
            <scope>test</scope>
        </dependency>
```

But i have this error: 

Could not download sources or javadoc
Could not read maven project
Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact com.vaadin:vaadin-bom:pom:16.0-SNAPSHOT @ line 23, column 25
[ERROR] 'dependencies.dependency.version' for com.vaadin:vaadin-core:jar is missing. @ line 34, column 21
[ERROR] 'dependencies.dependency.version' for com.vaadin:vaadin-testbench:jar is missing. @ line 149, column 21
[ERROR] 'dependencies.dependency.version' for com.vaadin:flow-server-production-mode:jar is missing. @ line 286, column 29

Can you help me please?

Thank you.

**Comment by caalador** [comment]
Do you have vaadin-prereleases as a repository and pluginRepository?

If you have those then it should find the snapshots.

e.g. add the following
```
<repositories>
        <repository>
            <id>vaadin-prereleases</id>
            <url>https://maven.vaadin.com/vaadin-prereleases/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
</repositories>

<pluginRepositories>
        <pluginRepository>
            <id>vaadin-prereleases</id>
            <url>https://maven.vaadin.com/vaadin-prereleases/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
</pluginRepositories>
```

**Comment by stefanuebe** [comment]
This issue seems to still exists somehow, we have that now in a V20 project. I'll try to create a sample project with the reproducable issue.
