### ISSUE TITLE
Add updateItem to DataView

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#8499]
This would simply delegate to `refreshItem` in the data provider.
The default way to determine the identity should be by using `equals` and `hashcode` but the problem is that the user should be able to provide another mean for this, like providing a callback `SerializableFuction<T, Object>` which will return the type to use for the identity check between two items.

Add
```java
void updateItem(T item)
void updateItem(T item, SerializableFunction<T, Object> identityProvider)
```
Update the Grid DX test task number 4 to use a bean type that needs to use the `updateItem` with the identity provider or the code will.

**Comment by mshabarov** [comment]
AbstractListDataView::contains(T item) has TODO with the similar identity issue. It could be addressed within scope of this ticket.
