### ISSUE TITLE
File download via StreamResource not working when the file name contains one or more spaces

### ISSUE THREAD

**Issue by ajgassner** [vaadin/flow#8500]
### Description of the bug
File download via StreamResource not working when the file name contains one or more spaces. Spring Boot with `vaadin-spring-boot-starter` is used.

It seems #5360 causes the issue.

### Minimal reproducible example
[stream-resource-demo.zip](https://github.com/vaadin/flow/files/4729484/stream-resource-demo.zip)

### Expected behavior
File download is working

### Actual behavior
HTTP 400 Bad Request

### Versions:
    - Vaadin version: 16.0.0
    - Spring Boot: 2.2.6
    - Java version: 11
    - OS version: MacOS
    - Browser version: Chrome 80

**Comment by caalador** [comment]
Some investigation revealed that in developmentMode the request goes to webpack-dev-server as the request starts with /VAADIN/ and it returns a 400 Bad request. In the case of 404 we would just send it to the next handler, but now it fails here.

The fix would be to not redirect any requests with a path starting with /VAADIN/dynamic/ see DevModeHandler::isDevModeRequest

**Comment by denis-anisimov** [comment]
The issue in fact has no relation to dev mode handler.
`DevModeHandler::isDevModeRequest` indeed returns true for paths starting with ` /VAADIN/ ` but this is not a single check for the resource.
The check for static resource is :

```
 DevModeHandler handler = DevModeHandler.getDevModeHandler();

        if (handler != null && handler.isDevModeRequest(request)
                && handler.serveDevModeRequest(request, response)) {
            return true;
        }
```.

When dev handler presents (and that's one more issue with our tests: we have test for stream resource but it's not executed in Dev mode!)  it should be able also to handle the request via `handler.serveDevModeRequest` and it's not able to handle normally `/VAADIN/dynamic/` URIs.

So the file without space works fine in dev and non dev mode.

But if file name in the CTOR contains a space (e.g. `new StreamResource("file name",`   ) then it doesn't work.
I will  add this test for dev mode module only and introduce a space to our existing test.

**Comment by denis-anisimov** [comment]
But yes, for some reasons the file name which contains a space can be handled via `handler.serveDevModeRequest` (the method returns `true`) and that's the reason of the behavior.
