### ISSUE TITLE
Client-side form: Make it easier to pass a message to a validator

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#8512]
Currently, when creating a validator, if you want a custom message rather than the default one, you can pass it through an option object. E.g.
`this.binder.for(firstname).addValidator(new NotEmpty({message: 'First name cannot be empty'}));`

It would be easier if I can pass the message directly as a constructor argument. e.g.,
`this.binder.for(firstname).addValidator(new NotEmpty('First name cannot be empty'));`

**Comment by vlukashov** [comment]
The out-of-the-box client-side validators like `Size`, `NotEmpty` and others are primarily intended for  usage in auto-generated form models. Using them manually to add custom client-side validators is not a use case I would optimize for.

Won't fix.
