### ISSUE TITLE
Create a documentation for Data View In-Memory case

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#8521]
Update the existing documentation for Data Provider API so as to describe new exposed API of Data View, including only in-memory case at this point.

**Comment by pleku** [comment]
Current data binding topic is quite big as it includes forms:
![Capture](https://user-images.githubusercontent.com/1478381/84238068-20b1db80-ab03-11ea-8881-a3011d1422a9.PNG)

An idea would be to split the existing _Binding Data to Components_ chapter in to two:
- "Creating Forms"
- "Showing items from backend" 

or something better preferably. 

The new topic "showing items from backend" could be split into further subtopics as the current data provider page https://vaadin.com/docs/v14/flow/binding-data/tutorial-flow-data-provider.html is quite large. The subtopics could be:
1) Showing a list of items
2) Filtering and sorting
3) Add, remove and update items
4) Navigating between the items
5) Showing the size of the data
6) Fetching all items for exporting
7) Fetching items lazily from backend
8) [maybe split some parts from the lazy case ?]

Also the grid documentation subsection should be updated https://vaadin.com/docs/v14/flow/components/tutorial-flow-grid.html

**Comment by mshabarov** [comment]
Branch `feature/dataprovider2` of `flow-documentation-parent` contains an updated version of dataprovider chapter. Assigned to @magi42 for review.
