### ISSUE TITLE
Second round DX test for in-memory data view

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#8522]
After #8497 and #8499 are done
1) update the DX test script to reflect the changes
  - update select test task 3 to ask for editing the selected item in the form
2) rerun the tests with 2-3 candidates
3) analyse feedback

**Comment by mshabarov** [comment]
In-memory data view round 2 DX test results are collected in the [test_notes](https://docs.google.com/document/d/1gz9LAsWga25XEHbPmhMdWzNMK9zTu6GxKS955NH_ZJ8/edit#heading=h.708ek75lvvzp).
Ticket created as a result of DX feedback:
- https://github.com/vaadin/flow/issues/8608
- https://github.com/vaadin/flow/issues/8618
- https://github.com/vaadin/flow/issues/8609
