### ISSUE TITLE
Make it easier to use to paged repositories for data provider data

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#8557]
_When binding my grid to a Spring data repository, I want to be able to map the fetch `Query` directly into a `Pageable` in a Spring repository, without wasting time in converting the offset and limit to the correct page and I would also expect that the component would respect the page size that I give it, and not try to fetch multiple pages at the same time because I have to workaround it in my code._

So basically one should not have to do things like https://github.com/Artur-/spring-data-provider/blob/master/src/main/java/org/vaadin/artur/spring/dataprovider/PageableDataProvider.java#L64 to be able to map the `Query` to a `https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/PageRequest.html`.
Another thing is that currently the requests are done for multiple pages at once, like with page size 50 the grid might request for 150 items in a query. This should be configurable so that the data communicator would limit the query to the requested page size and respect it. Thus this would imply that if grid needs 150 items and the page size is 50, there will be 3 separate fetch `Query` done. The current behavior would stay as the default. This API should be accessible via the `LazyDataView`.

Related to https://github.com/vaadin/spring/issues/388 but this is just to make it easier to connect these two concepts, but not try to introduce things to the framework or Sprin add-on (yet).

#### Acceptance Criteria
- it is possible to get the page information from `Query` with `PageRequest.of(query.getPage(), query.getPageSize())` - even if `getPageSize()` be duplicate for `getLimit()` it would still be clearer
- it is possible to tell the component to "limit query size to page size". This API has to be in `LazyDataView` (and call `DataCommunicator`) since `DataProvider` doesn't know about the component or create the query itself

**Comment by mstahv** [comment]
@mshabarov Started this in https://github.com/vaadin/flow/tree/feature/pageIndexMethod 

Methods are there and it kind of works, but in certain cases Grid still polls backend in multiples of what is given to it using `setPageSize`. So basically the second point of the acceptance criteria. The behaviour in the second point could actually be the default as I'd claim most people to expect it works like that.

If later seen necessary, we could then consider to allow configuration form LazyDataView using `allowRequestsOverMultiplaPages`.
