### ISSUE TITLE
Maps and 2d Arrays cause webpack compilation errors with Vaadin 17.0.0.alpha2

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#8582]
1. Download app from https://start.vaadin.com/?preset=try-ts
2. Add 
```
    private Map<String, String> mapProp;
    private int[][] array2dProp;
```
to `src/main/java/com/example/application/views/dashboard/HealthGridItem.java`
3. Run `mvn`. 

Expected and actual outcome: No errors

4. Change Vaadin version in pom.xml to `17.0.0.alpha2`
5. Remove `enableInstallPrompt` from `src/main/java/com/example/application/AppShell.java`
5. Run `mvn`

Expected outcome:
No errors

Actual outcome:
```
ERROR in [at-loader] ./frontend/generated/com/example/application/views/dashboard/HealthGridItemModel.ts:20:39 
    TS1005: ']' expected.
```
and about 20 other similar errors for the same file:
```ts
export default class HealthGridItemModel<T extends HealthGridItem = HealthGridItem> extends ObjectModel<T> { 
  public readonly array2dProp = new ArrayModel(this, 'array2dProp', Array<number>Model);
  public readonly mapProp = new { [key: string]: string; }Model(this, 'mapProp');
  ...
}
```

**Comment by Haprog** [comment]
Currently for me when using `<vaadin.version>17.0.0.alpha5</vaadin.version>` and latest `flow` master installed (without the fix) this is how the broken model output looks like (syntax errors):
```ts
export default class HealthGridItemModel<T extends HealthGridItem = HealthGridItem> extends ObjectModel<T> { 
  ...
  public readonly array2dProp: ArrayModel<ModelType<Array<number>Model>, Array<number>Model> = new ArrayModel(this, 'array2dProp', Array<number>Model);
  ...
  public readonly mapProp = new { [key: string]: string; }Model(this, 'mapProp');
  ...
}

```

Just wanted to share for reference since it's different from what is in the issue description. I will test the PR branch next.
