### ISSUE TITLE
Problematic dependency

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#8588]
This dependency might cause serious issues with applications using the Java Mail API or Spring.

<img width="368" alt="Screenshot 2020-06-18 at 15 38 08" src="https://user-images.githubusercontent.com/851745/85027028-bdb2eb00-b179-11ea-8b1f-618c86bcaf34.png">

See for example this [StackOverflow question](https://stackoverflow.com/questions/45444031/nosuchmethoderror-when-trying-to-send-email-in-spring-boot/45454769).

**Comment by heruan** [comment]
Also this dependency from `swagger-codegen` causes dramatic issues (i.e. app not running):

<img width="281" alt="Screenshot 2020-06-18 at 16 04 25" src="https://user-images.githubusercontent.com/851745/85030248-80505c80-b17d-11ea-92c0-b382e7c32838.png">

Like the Mail API, there could different versions on the server (e.g. 4.7.1 for `antlr-runtime`).

**Comment by knoobie** [comment]
I'm wondering, is swagger-codegen really needed in `flow-server` at runtime or is it only used to create Vaadin Connect stuff while developing? Shouldn't this be done by the `vaadin-*-plugin` or in a separate module.

**Comment by Legioth** [comment]
`swagger-codegen` is needed at runtime in development mode since then all the processing is done separately for each redeploy rather than only as a built-time thing.

It would be great to somehow have the development mode dependencies separated from the "real" runtime dependencies, but achieving that isn't trivial with the current setup.

**Comment by knoobie** [comment]
@Legioth it would be lovely, if `flow-development-mode` would be a separate artifact which can be removed in the profile that activates `production`.

**Comment by Legioth** [comment]
Just separating the artefacts would be a good first step, but there would still be a problem with runtime conflicts during development.

A "proper" solution would be to use a separate classloader for the development mode dependencies instead of including them on the regular classpath.

**Comment by haijian-vaadin** [comment]
A workaround could be to manually exclude the `mailapi` dependency. For example, if it's a Vaadin spring application, you can exclude it from the `vaadin-spring-boot-starter`, i.e.
```
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-spring-boot-starter</artifactId>
       <executions>
          <exclusion>
             <groupId>javax.mail</groupId>
             <artifactId>mailapi</artifactId>
          </exclusion>
       </executions>
</dependency>
```
If it's a non Spring Vaadi application. You can exclude it from `vaadin` or `vaadin-core` in a similar manner. i.e.
```
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-core</artifactId>
       <executions>
          <exclusion>
             <groupId>javax.mail</groupId>
             <artifactId>mailapi</artifactId>
          </exclusion>
       </executions>
</dependency>
```

**Comment by madduci** [comment]
If you plan to use also the `spring-boot-starter-mailer`, you need to add also these dependencies:

```
   <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-mail</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.sun.mail</groupId>
          <artifactId>jakarta.mail</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>com.sun.mail</groupId>
      <artifactId>smtp</artifactId>
      <version>1.6.4</version>
    </dependency>
    <dependency>
      <groupId>com.sun.mail</groupId>
      <artifactId>jakarta.mail</artifactId>
      <version>1.6.4</version>
    </dependency>
    <dependency>
      <groupId>com.sun.mail</groupId>
      <artifactId>mailapi</artifactId>
      <version>1.6.4</version>
    </dependency>
```
