### ISSUE TITLE
Fluent DataView method to return a component-specific interfaces

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#8609]
Make the return types of `setFilter`, `addFilter` and other fluent API methods in `AbstractListDataView` generic, so as to return something extends `AbstractListDataView`. This would allow the developer chain together the methods from abstract class and from a component-specific data view interface. Example for `Select` component:

`dataView.setFilter(someFilter).addFilter(someFilter).getItemOnIndex(0)`.

**Comment by pleku** [comment]
There is not that much added value of chaining the methods with data views so the added complexity doesn't pay of in my opinion. I don't see us doing this so closing it for now.
