### ISSUE TITLE
Explain ` `Skipping `npm install```

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#8614]
Vaadin 14.1.28/14.2.x

Vaadin plugin sometimes decides to skip npm install when building for production, for no apparent reason.

I'd expect at least something like

>  `Skipping `npm install`` because of X Y Z, please see https://github.com/foo for details.

**Comment by denis-anisimov** [comment]
The only reason why it skips `npm install` is : the packages are already installed.

Is `"because the frontend packages are already installed"` is a good explanation ?

**Comment by mvysny** [comment]
Sounds good! I'd even include more information:

```
"because the frontend packages are already installed in the folder c:/foo/bar/node_modules and the checksum file node_modules/something.json says everything is up-to-date"
```
