### ISSUE TITLE
Maven Plugin Documentation missing

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#8617]
The Vaadin Gradle plugin has a clear landing page with the documentation: https://github.com/vaadin/vaadin-gradle-plugin/

However, the official Vaadin Maven Plugin has no documentation page at this point:

* https://github.com/vaadin/maven-plugin is a Vaadin 8 plugin, or something deprecated
* The sources are at https://github.com/vaadin/flow/tree/master/flow-maven-plugin but there is no documentation
* Search for "maven" at https://vaadin.com/docs/index.html returns nothing usable
* There is a bit of documentation at https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-basic.html

A succinct page describing all goals and pointing to example project is much needed.

**Comment by mshabarov** [comment]
@mvysny could it be better to transfer this issue to `flow-and-components-documentation`?

**Comment by mvysny** [comment]
It probably depends on whether we wish to publish a site created automatically by Maven, or whether we wish to write a markdown documentation from scratch. In the latter case it would be good to to as you suggest.

**Comment by mshabarov** [comment]
Should be here https://github.com/vaadin/flow/blob/main/flow-plugins/flow-maven-plugin/README.md.

**Comment by durcon** [comment]
Thank you for the really fast anwser. However, I'm also looking for some release notes.

I get following warning:

> [WARNING] The <productionMode>true</productionMode> Maven parameter no longer has any effect and can be removed. Production mode is automatically enabled when you run the build-frontend target.

The documentation says:

> Define whether the application is running in production mode. Defaults to false. For production, the frontend is bundled and optimized, as described in [Deploying to Production](https://vaadin.com/docs/latest/production).

I'm a little confused. I thought release notes would help me, but I didn't find anything about this flag. Maybe I looked at the wrong place?

**Comment by caalador** [comment]
Yes the documentation and readme should be updated on that.
The change came with the express mode in the [pr](https://github.com/vaadin/flow/commit/56f1d007f4a71bb07b5a1dee0ed29d21c73322f3)

Created a [ticket](https://github.com/vaadin/flow/issues/18485) to update the documentation
