### ISSUE TITLE
Logout code doesn't work in the master branch

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#8627]
See this test : https://github.com/vaadin/flow/pull/8626/files#diff-efd7ca3a1cca19f611e5da192ed611d0

This is a usual way of doing logout from the application: redirect to some logout page and close the session:
```
public LogoutView() {
        NativeButton button = new NativeButton("logout", ev -> {
            UI.getCurrent().getPage().setLocation(BaseHrefView.class.getName());
            UI.getCurrent().getSession().close();
        });
        add(button);
    }
```

normally `BaseHrefView.class.getName()`  is something like "/logout".
This works fine (the location is changed, redirect happens) in `2.2`.

But it's broken on the `master` branch (may be also in `3.x` ).

Here is what happens:
- The redirect JS is sent fine.
- on the client side in the Network tab I see that "logout" URL navigation is canelled (BaseHrefView.class.getName()).
- instead `LogoutView` is reloaded.

The UI lifecycle is terminated at this point already (when redirect is called).

Original ticket is : https://github.com/vaadin/flow/issues/8623

It has the same scenario but the only unexpected effect is the red error message (in `2.2`).
In the `master` branch in addition to that : redirect doesn't happen.

**Comment by denis-anisimov** [comment]
Regression is introduced by this commit: https://github.com/vaadin/flow/commit/98fedc0595be47a72193f7ab14572434d63fb86b#diff-4d352dddb4ef4c53b600ede46da80dc3

**Comment by denis-anisimov** [comment]
I don't understand what't going on there........

The reason is simple: `SystemErrorHandler::handleSessionExpiredError` should call `handleUnrecoverableError` in the same processing cycle (without calling a scheduler).
But if I move this code anyhow out of the scheduler then another test is failing  : `RouterSessionExpirationIT`.
The test navigates to a view via router link and the view invalidates the session.
Navigation happens for very short time, session expire message returns back to the view from which navigation has been done.

This is a consequence of handling session expire message in the same cycle: it doesn't happen if session expire message is handled deferred. 

But this logic is totally broken somehow.
The router link should be handled by the `RouterLinkHandler`. The method has a special mechanism to to set a "response session expire" handler via : setNextResponseSessionExpiredHandler.
Once it's set (that happens on router link click event) the session expire should invoke this handler instead of the default one.
And this functionality never works in the `master` branch: router links never goes via `RouterLinkHandler`.

It works as it should in `2.2`.
So apparently there is some CCDM functionality which :
 - totally broke the way of handling router links and session expired functionality
- router links works somehow apart from `RouterLinkHandler`.

**Comment by manolo** [comment]
Seems related to https://github.com/vaadin/flow/issues/7575

**Comment by manolo** [comment]
Possible workaround if the app does not use client-side views is disabling `vaadin-router` by enabling the  `useDeprecatedV14Bootstrapping` parameter.

**Comment by denis-anisimov** [comment]
OK, I'm not able to fix this issue since it comes from another project which I know any information about : `vaadin-router`.

The important information is (as mentioned):
- router link clicks are not handled by `RouterLinkHandler`  in flow-client
- `RouterLinkHandler`  has a special code for exactly this situation : once a link is clicked it sets a `nextResponseSessionExpiredHandler` which should be executed in the session expired handler instead of default way of session expire handling : 
```
if (nextResponseSessionExpiredHandler != null) {
                        nextResponseSessionExpiredHandler.execute();
                    } else {
                        registry.getSystemErrorHandler()
                                .handleSessionExpiredError(null);
                        registry.getUILifecycle().setState(UIState.TERMINATED);
                    }
```
- so the code is broken initially since `nextResponseSessionExpiredHandler` is never set by the router link handler.
- it's illegal to use `Scheduler.get().scheduleDeferred(`  in the `handleSessionExpiredError` because of the breaking the common scenario for logout (this ticket). You may find the test case in https://github.com/vaadin/flow/pull/8641.
- if you want to "defer" some execution but not move it to the next browser handling cycle (via a scheduler) then you may use `Reactive.addPostFlushListener`  (also see the PR above).

I've tried to replace the scheduler logic with `Reactive.addPostFlushListener(` but it failed because of `RouterSessionExpirationIT`. And the reason is the absence of proper router link click.

So I pass this to CCDM team. Doesn't really mater how it will be fixed. Just fix it based on the provided info.

**Comment by denis-anisimov** [comment]
It seems that:
- the https://github.com/vaadin/flow/commit/98fedc0595be47a72193f7ab14572434d63fb86b#diff-4d352dddb4ef4c53b600ede46da80dc3 should be reverted
- then this ticket can be considered as fixed
- the issue that I have with `RouterSessionExpirationIT` is just a duplicate of #7575

**Comment by heruan** [comment]
Note that also exception handlers don't work in V16 when using e.g. `UI.navigate`: the exception is thrown without any handler invoked.

**Comment by haijian-vaadin** [comment]
Related commit https://github.com/vaadin/flow/commit/76ec7e24e92c858df1f8ee28e2ce67bb19a6db4f
