### ISSUE TITLE
Maybe add a setFilter(? filter) method to LazyDataView

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#8646]
The new data view doesn't have any filtering API for lazy case. To set a filter for grid one has to e.g.:
```java
final TextField filterField = new TextField("Filter by name",
        event -> grid.getDataProvider().refreshAll());
grid.setDataSource(query -> fakeBackend.fetchItems(query.getOffset(),
        query.getLimit(), filterField.getValue()));

```
It would be convenient if the `LazyDataView` would have a method for setting the filter, which would then be provided by the `Query` with the `getFilter()` method. The method would make sure 
1) the filter gets to the query
2) the data communicator reacts to the filtering change

The problem is with the generics type. Currently the filter type in `LazyDataView` is `Void`. Couple of alternatives for this:
a) Expose a new type parameter for `LazyDataView` which signifies the filter type. This makes usage quite cumbersome for the simple cases without filtering which is not desired.
b) Just use type of `Object` for `setFilter(Object filter)` and then also for `Query::getFilter` and users have to explicitly cast it. Simple-ish but also not that much different from just getting the filter yourself directly in the query.
c) Expose another type of `FilterableLazyDataView` which will have the extra type parameter and the method to set the filter. This could be separated from the basic data view with API. Example:
Grid:
```java
LazyDataView<T> setDataSource(FetchCallback<T, ?> fetch);
FilteringDataView<T, FT> setDataSourceWithFilter(FetchCallback<T, FT> fetch);
```
ComboBox:
```java
LazyDataView<T> setDataSource(FetchCallback<T, String> fetch);
FilteringDataView<T, FT> setDataSourceWithFilter(FetchCallback<T, QF> fetch, BiFunction<String, VF, QF> filterCombiner);
```

**Comment by mshabarov** [comment]
This ticket is a blocker for https://github.com/vaadin/vaadin-combo-box-flow/issues/355, because `ComboBox` has an internal string filter and current `LazyDataView` with `Void` as a filter type does not fit.

**Comment by pleku** [comment]
Not adding the method but exposing the potential component internal filter type as part of vaadin/vaadin-combo-box-flow#355.

The recommended approach for providing outside-component based filters is to just take those into account in the callbacks (fetch and optional count) and reset the data.
