### ISSUE TITLE
DevModeHandlerTest::webpackIsNotExecutable_throws fails on Windows agent

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#8665]
Integration test `DevModeHandlerTest.webpackIsNotExecutable_throws` fails when running on Windows Server 2019 agent in TeamCity Bender.

`java.lang.AssertionError: Expected test to throw exception with cause is an instance of com.vaadin.flow.server.ExecutionFailedException`

https://bender.vaadin.com/viewLog.html?buildId=162324&buildTypeId=Flow_Misc_Flow32SnapshotWindows_Flow32SnapshotMasterWindows#testNameId261507595536428168

**Comment by pleku** [comment]
Has been fixed by #8896
