### ISSUE TITLE
Missing method to access UI from AfterNavigationEvent

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#8669]
The `AfterNavigationEvent` does not have any method to access the current UI (e.g. `getUI()`), although it is created from a `LocationChangeEvent` which has that.

It would be useful to be able to access either the `LocationChangeEvent` or the `UI` from the `AfterNavigationEvent`.

**Comment by jhult** [comment]
@mshabarov, I can submit a pull request to expose `LocationChangeEvent` if you are interested.

**Comment by mshabarov** [comment]
@jhult It would be much appreciated, please do if have a chance. Thank you!

**Comment by Legioth** [comment]
As a workaround, you can use `UI.getCurrent()` which should always be defined while that event is fired.
