### ISSUE TITLE
Bump the versions

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#8679]
- Flow version will go to 4.0-SNAPSHOT
- The project in bender for 3.2 should be renamed to be building 4.0 instead
  - 3.2 is not going to be used
- flow-component-base version will go to `4.0-SNAPSHOT` and use flow 4.0-snapshot
- Spring addon version goes to next major
- CDI addon versino goes to next major
- MPR version goes to next major

**Comment by mshabarov** [comment]
Patient Portal job also updated and aimed to `4.0-SNAPSHOT`
