### ISSUE TITLE
App freezes if not used for a while

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#8699]
If the app is not used for a while, i.e. a page is kept open on a browser but without any action on it, when the user attempts any further action (e.g. navigation) the app freezes with this client error:

<img width="1401" alt="Screenshot 2020-07-07 at 18 40 39" src="https://user-images.githubusercontent.com/851745/86814527-d419db80-c081-11ea-81ad-a9acf1a92e40.png">

In particular, at first the blue loading bar gets stuck (pulsating) then disappears before reaching the end; then, any attempt to navigate away from the page freezes the app with a blank page and the blue loading bar stuck forever (and the client error on the console).

I can replicate this 100% of the time after more than 20 minutes of inactivity (but also happens with less).

This could be related to #7553 and #7399.

**Comment by mshabarov** [comment]
Thank you, @heruan for the ticket. I'm starting look into this issue.

**Comment by mshabarov** [comment]
@heruan could you please give an exact version of `vaadin` you observed this issue on?

**Comment by heruan** [comment]
@mshabarov this is happening with Vaadin 16.0.0 and I noticed it always happens after this other error:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/851745/87280339-52e39e00-c4f2-11ea-8b44-b5fe86070937.png)

**Comment by haijian-vaadin** [comment]
@heruan Do you use any TypeScript views and Endpoints? Do you have an example project that we can use to reproduce the problem?

**Comment by heruan** [comment]
I don't use TS views nor endpoints. I've already provided access to an instance of our application, see Prime Support ticket 3396.

**Comment by haijian-vaadin** [comment]
Got it, thanks for the info, I will take a look at the support ticket.

**Comment by heruan** [comment]
This message is logged regularly when the crash happens:

```
WARN  [com.vaadin.flow.server.communication.ServerRpcHandler] (default task-1) Resynchronizing UI by client's 
request. Under normal operations this should not happen and may indicate a bug in Vaadin platform. If you see 
this message regularly please open a bug report at https://github.com/vaadin/flow/issues
```

**Comment by haijian-vaadin** [comment]
As the feezing it almost always comes hand in hand with resynchronization, I think probably increase the value of maxMessageSuspendTimeout would help (see the [doc](https://vaadin.com/docs/flow/advanced/tutorial-all-vaadin-properties.html)). The default value is 5000(ms), Can you help to increase the value to 10000 or 15000, to see if the freeze issue happens less frequently?

**Comment by haijian-vaadin** [comment]
Hi, Can you help to try out a new Flow version 3.1.5 to see if it fixes this issue? 

How use a different Flow version in the pom file?
1. add a <flow.version> property in the pom file
`<flow.version>3.1.5</flow.version>`
2. add a <flow-bom> dependency in the <dependencyManagement> section
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>flow-bom</artifactId>
                <version>${flow.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-bom</artifactId>
                <version>${vaadin.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
3. replace `<vaadin-maven-plugin>` with `<flow-maven-plugin>`
