### ISSUE TITLE
forward and reroute missing class,urlparam combination in  BeforeEnterEvent

### ISSUE THREAD

**Issue by thigg** [vaadin/flow#8712]
### Description of the bug
Rerouting or forwarding from the BeforeEnterEvent does not allow to use the parameter combination` class,parameter`

### Minimal reproducible example
```
 @Override
    public void beforeEnter(final BeforeEnterEvent event) {
            event.forwardTo(OtherView.class,"randomparameter");
    }
```
### Versions:
    - Vaadin / Flow version: 14.3
    - Java version:
    - OS version:
    - Browser version (if applicable):
    - Application Server (if applicable):
    - IDE (if applicable):

**Comment by mshabarov** [comment]
Thank you for the ticket, @thigg. A new method `void forwardTo(Class<? extends Component> forwardTargetComponent, RouteParameters parameters)` has been introduced in V17 within new Url template support feature. Need to investigate whether we can backport it (or a part of it) to 14.3.

**Comment by thigg** [comment]
A backport would be nice.
I used `event.forwardTo(RouteConfiguration.forApplicationScope().getUrl(SomeView.class), parameter);` instead.

Yes, enhancement is correct.

**Comment by pleku** [comment]
Just as a clarification - the might not be backported to 14.3, but to a new upcoming 14.x release together if/when we backport the url template feature.

**Comment by pleku** [comment]
The API has been backported to the Vaadin 14.5 LTS version https://vaadin.com/api/platform/14.6.1/com/vaadin/flow/router/BeforeEvent.html#forwardTo-java.lang.Class-com.vaadin.flow.router.RouteParameters-

So I think this can be closed. In case some API is missing, please open a new issue describing the use cases.
