### ISSUE TITLE
Live reload does not work for client-side changes

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#8721]
Vaadin 17. 

I have a Spring Boot project with both a client-side and a server-side view.  

Changes to the server-side view get live reloaded as expected. Client-side view changes are not reloaded unless I also make a change to Java code. 

I would expect any code change, regardless of origin to trigger the reload.

**Comment by haijian-vaadin** [comment]
Closing this one as it will be fixed once https://github.com/vaadin/flow/issues/8852 is fixed
