### ISSUE TITLE
CCDM: allow fluent API for adding validators

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#8722]
As a developer, when adding multiple validators to a `BinderNode`, I want to have a fluent API so that I can chain it in one statement. i.e. `binder.for(model).addValidator(a).addValidator(b)`. 

DoD:
`BinderNode.addValidator()` should return the `BinderNode` itself instead of `void`.

**Comment by Legioth** [comment]
Manually adding client-side validators that don't also have a server-side counterpart is a bad practice. Why would we want to make the API for that case easier to use?

**Comment by haijian-vaadin** [comment]
Good question, this requirement was raised during a dx testing. It makes sense on its own. We can close it as it's not a recommended practice.
