### ISSUE TITLE
typescript modules inadvertently generated from java code

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#8743]
@jzelenka commented on [Fri Jul 17 2020](https://github.com/vaadin/platform/issues/1449)

Vaadin version 16.0.1

According to https://vaadin.com/docs/v16/flow/typescript/accessing-backend.html  typescript modules should be generated to `{project.basedir}/frontend/generated` for java classes anotated with @Endpoint annotation.

I presume it should be `com.vaadin.flow.server.connect.Endpoint`, however, they are generated also for "other" @Endpoint annotations, for example for `org.springframework.ws.server.endpoint.annotation.Endpoint`

Looks like only simple string "Endpoint" is taken into account.

---

@ZheSun88 commented on [Fri Jul 17 2020](https://github.com/vaadin/platform/issues/1449#issuecomment-660158802)

Thanks for using Vaadin Platform, we appreciate your help and are going to take care of this as soon as possible.

**Comment by haijian-vaadin** [comment]
Thanks for reporting, we are able to reproduce the problem and pinpoint the root cause. It's coming from an [underlying library](https://github.com/javaparser/javaparser/issues/1713). 

A fix is on the way.
