### ISSUE TITLE
Fix MPR master build failures

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#8758]
MPR builds have been failing for `master` branch since 17.07.2020.
https://bender.vaadin.com/viewLog.html?buildId=170392&buildTypeId=Flow_Flow32_AddOns_Mpr30

**Comment by mshabarov** [comment]
MPR build fails again
https://bender.vaadin.com/viewLog.html?buildId=172425&buildTypeId=Flow_Flow32_AddOns_Mpr30

**Comment by denis-anisimov** [comment]
I don't know what's going with MPR generally because every time the reason of the failure is different is has no sense.
But the latest build passed: https://bender.vaadin.com/viewLog.html?buildId=172780&buildTypeId=Flow_Flow32_AddOns_Mpr30.
So, I'm closing this issue.
