### ISSUE TITLE
PendingJavaScriptResult always null?

### ISSUE THREAD

**Issue by MatsG23** [vaadin/flow#8784]
I want to connect the Notification WebPush API with my Vaadin WebApp. I made this JS and Route:

src/main/resources/META-INF/resources/webpush.js
`function supportWebPush() {
    try{
        if('serviceWorker' in navigator && 'PushManager' in window){
            return "supported";
        }else{
            return "not supported";
        }
    }catch (e) {
        return e;
    }
}`

src/main/java/<PACKAGE-NAME>/WebPush.java
`@Route("webpush")
@PageTitle("WebPush")
public class WebPush extends VerticalLayout {
public WebPush(){
        final UI ui = UI.getCurrent();
        ui.getPage().addJavaScript("/webpush.js");
        ui.getPage().executeJs("supportWebPush()").then(jsonValue -> {
            System.out.println("Executed");
            System.out.println(jsonValue.getType());
            System.out.println(jsonValue.asString());
        });
    }
}`

I made the js file according to [this tutorial from CodeLabs](https://developers.google.com/web/fundamentals/codelabs/push-notifications). I tried it out on seperate webserver while tutorial and it worked - in vaadin it don't.

I don't see an exception, but this is the console (WebPush.java System.out.println):

`Executed
NULL
null
false`

Versions
    - Vaadin / Flow version: 14.3.1
    - Java version: openJDK 11 (Coretto)
    - OS version: Windows 10
    - Browser version (if applicable): Chrome 84.0.4147.89
    - IDE (if applicable): IntelliJ IDEA 2020.1.4

Best regards 
Mats

EDIT:
If anyone knows, how to format that code correctly on GitHub, please edit this issue and then delete this "EDIT"-snippet.

**Comment by Artur-** [comment]
Try using
```
ui.getPage().executeJs("return supportWebPush()")
```

**Comment by MatsG23** [comment]
> Try using
> 
> ```
> ui.getPage().executeJs("return supportWebPush()")
> ```

Thank you very much, it works!

**Comment by MatsG23** [comment]
As if by magic.. it isn't working any longer. Yesterday it worked brilliant... 
I already 

-cleaned the _target_-Folder
-removed the _sw.js_ in Chrome (Developer Tools > Application > Clear Storage > Clear Site Data)
-reinstalled my _.m2_-Repository and _node_modules-_Folder

It is the same code, but it somehow don't work! Do anyone have an idea?

**Comment by MatsG23** [comment]
Is it right to add the JS-File like that?
`@JsModule("./webpush/webpush.js")`

It says function not defined when I click on button (run subscribe-to-notification-function)

**Comment by MatsG23** [comment]
I experienced an error where the function suddendly wasn't found.
I fixed it using
`page.addJavaScript("webpush/webpush.js");`
(Path from Project Root frontend/webpush/webpush.js)
instead of 
`@JsModule("./webpush/webpush.js")`
