### ISSUE TITLE
Improvement: Possibility to add a value change listener on a specific field in the binder.

### ISSUE THREAD

**Issue by akvyalkov** [vaadin/flow#8791]
Ideally, it would be something like that:
```
binder.forField(specificTextField)
    .withConverter(...)
    .withValidator(...)
    .bind(Person::getName, Person::setName)
    .addValueChangeListener(...); // nonexistent functional
```

The way to do it now is something like that:
```
TextField nameTextField = new TextField();
TextField surnameTextField = new TextField();

binder.bind(nameTextField, Person::getName, Person::setName);
binder.bind(surnameTextField, Person::getSurname, Person::setSurname);

binder.addValueChangeListener(event -> {
    if(event.getHasValue().equals(nameTextField)){
        // nameTextField value changed
    } else if(event.getHasValue().equals(surnameTextField)) {
        // surnameTextField value changed
    }
}
```

**Comment by denis-anisimov** [comment]
I don't see any reason to use `Binder` to add a `ValueChangeListener`.
`Binder` works with HasValue interface (every `forField` accepts only `HasValue`).
So instead using a `Binder` instance it's possible to add a listener to the `HasValue` directly _and in a generic way_.
`HasValue` has a method `addValueChangeListener`. I don't see any benefit to have it in the `Binding` vs having it in `HasValue`.

So I'm closing this since the requested functionality is already available.
Please let me know if I miss something.

**Comment by akvyalkov** [comment]
The main benefit I can see in using `Binder` is converters and validators for specific fields so we can use prepared data instead of raw input of `HasValue`. 
I see it as the way to react to user input, but only on the proper one. 
It will help to build "multistep input forms" where fields content changes based on previous user inputs.

**Comment by denis-anisimov** [comment]
Please provide exact and precise design of the requested feature in this case.
And update the description with this design.

You original description contains the only example: 
```
binder.addValueChangeListener(event -> {
    if(event.getHasValue().equals(nameTextField)){
        // nameTextField value changed
    } else if(event.getHasValue().equals(surnameTextField)) {
        // surnameTextField value changed
    }
}
```

This is exactly the same as `HasValue::addValueChangeEvent` . So it doesn't explain/demonstrate the feature which you have in your mind.
Once you make the feature request clean with all the details I will reopen the ticket.
For now I don't see any difference between existing functionality and some vague request.
