### ISSUE TITLE
 Component.getElement().getNode().isAttached() returns true after the UI is already closed

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#8812]
### Description of the bug
After calling `UI::close` the attached Components are still attached.

### Minimal reproducible example
See https://github.com/vaadin/flow/pull/8810
### Expected behavior
After calling `UI::close` the attached Components are not attached anymore. (like V8)
### Actual behavior
After calling `UI::close` the attached Components are still attached.
### Versions:
    - Vaadin / Flow version: 10+

**Comment by mvysny** [comment]
This ticket refers to a new functionality filed in https://github.com/vaadin/flow/issues/7911 . In order to fix this issue, the `UI.close()` should detach all of its components:

* Fire detach listeners
* call `onDetach()`
* `getElement().getNode().isAttached()` must return false
* etc

**Comment by denis-anisimov** [comment]
Corrected the description which originally referred to functionality which doesn't exist .

I don't see this is as a bug.
`UI:close` doesn't close the `UI`.

The javadoc says: 
```
 Marks this UI to be {@link #onDetach(DetachEvent) detached} from the
 session at the end of the current request, or the next request if there
 is no current request (if called from a background thread, for instance.)
```

So it doesn't close the UI immediately (I agree, the method name is very confusing).
If there is an issue that `Component.getElement().getNode().isAttached()` returns `true` when a `UI` instance is actually closed then please create another ticket for this.
