### ISSUE TITLE
[BUG] Styles don't work properly in Javascript-triggered fullscreen mode

### ISSUE THREAD

**Issue by edler-san** [vaadin/flow#8817]
Goto https://demo.vaadin.com/invoice-editor-app/

Open a console and execute:
`var elem = document.getElementsByTagName('invoice-editor-app')[0];
`
Now, find the 'Send' button via inspector and 'make it available as temporary variable' (Chrome) or 'use in console' (Firefox). Add a click listener.
`temp0.addEventListener('click', function(){elem.requestFullscreen()})
`
Click it.  It looks like this in both Firefox (79.0) and Chrome (84.0.4147.105)
<img width="1440" alt="sc" src="https://user-images.githubusercontent.com/19165931/88713552-c48b3100-d11b-11ea-9941-bb387817b17a.png">

I found this bug originally in a 14.3.0 application. It is present in 14.3.1 as well.

**Comment by pleku** [comment]
Hi @edler-san what are you expecting to happen when calling the the `vaadin-button` to `requestFullscreen()` ?

When I read from MDN it says

>An element that you wish to place into full-screen mode has to meet a small number of simple requirements:
> It must be one of the standard HTML elements or `<svg>` or `<math>`.

and obviously `vaadin-button` is not a standard element. Also in Flow there is no feature even for this so I hardly see Flow to be the right repository for this. I'm on the verge of closing this issue, please clarify.

**Comment by edler-san** [comment]
The same behaviour also applies when calling on the vaadin-button-container which is a div. But the document you linked actually contains the solution: 

> It's worth noting a key difference here between the Gecko and WebKit implementations at this time: Gecko automatically adds CSS rules to the element to stretch it to fill the screen: "width: 100%; height: 100%". WebKit doesn't do this; instead, it centers the fullscreen element at the same size in a screen that's otherwise black. To get the same fullscreen behavior in WebKit, you need to add your own "width: 100%; height: 100%;" CSS rules to the element yourself

**Comment by pleku** [comment]
Ok. But `<div class="vaadin-button-container">` is inside the `#shadow-root` of the `vaadin-button` so it is considered "private API" in that sense. I'm still not sure why and how this should work but I'm sure this is not a framework issue as we don't really control this in any way.

In case some of the components don't work the right way in full screen mode (and you think they should (?)) then please open an issue for the web component repository like https://github.com/vaadin/vaadin-button
