### ISSUE TITLE
TS Form: @NotNull validation doesn't work with object type property

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#8821]
Given:
Contact.java
```
@Entity
public class Contact extends AbstractEntity implements Cloneable {

    @ManyToOne
    @JoinColumn(name = "company_id")
    @JsonIgnoreProperties("employees")
    @NotNull
    private Company company;
    ...
```
and Company.java
```
@Entity
public class Company extends AbstractEntity {
  private String name;
  ...
}
```
A form for Contact, with a combobox for the company property. I could submit the form without selecting a value for the company.
<img width="1179" alt="Screenshot 2020-08-05 at 14 42 44" src="https://user-images.githubusercontent.com/30408303/89408977-f7d84c00-d729-11ea-94e9-44a53fe2ca23.png">

The code is in https://github.com/vaadin-learning-center/crm-tutorial-typescript/tree/haijian/use-ts-form

A workaround now is to manually add a Required validator to the company id property, i.e
```
this.binder.for(this.binder.model.company.id).addValidator(new class extends Required<Number>{
      validate(value: number){
        return value > 0;
      }
    });
```

**Comment by Haprog** [comment]
We should make sure this also works when there's a vaadin-combo-box that allows custom values.
