### ISSUE TITLE
Integer overflow in DataCommunicator.fetchFromProvider()

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#8828]
Flow-data 4.0.0.beta1; if Integer.MAX_VALUE is passed in as the value for limit, the `pages` computation overflows and will compute the value of -42949672 which will leave query null, leading to assertion failure at 757

**Comment by mvysny** [comment]
![Screenshot from 2020-08-07 11-35-43](https://user-images.githubusercontent.com/254091/89626703-722bdc00-d8a2-11ea-91c2-f5af00051eeb.png)

**Comment by mshabarov** [comment]
Thank you, @mvysny . A page number calculation formula will be updates so as to avoid an integer overflow:
`final int pages = (limit - 1) / pageSize + 1;`

**Comment by jensgoe** [comment]
Please have a look at my comment https://github.com/vaadin/flow/commit/5cd56f6dac769067e3ce1522370e263f81949860#r42617680

**Comment by pleku** [comment]
Hi @jensgoe, in which component does this occur with ?

**Comment by jensgoe** [comment]
Yes, thats right. MultiSelectComboBox. Maybe that component needs to pass the pageSize?

**Comment by pleku** [comment]
Yes as we don't require components to do that by having it as a constructor parameter, we should just have a default value for it https://github.com/vaadin/flow/issues/9051
