### ISSUE TITLE
Property update request for disabled element warning when calling setEnabled(false)

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/flow#8848]
Tested with Vaadin 13.0.3

With this relative simple example:

```
@Route("")
public class MainView extends VerticalLayout {
    private TextField disabledTextField;
	public MainView() {
		disabledTextField = new TextField();
		disabledTextField.setEnabled(false);
		add(disabledTextField);
    }
}
```
Just by entering the application we get this warning in the log:

```
[qtp1326230282-42] WARN com.vaadin.flow.server.communication.rpc.MapSyncRpcHandler - Property update request for disabled element is received from the client side. The property is 'invalid'. Request is ignored.
```

Is that right?

**Comment by pleku** [comment]
See comment https://github.com/vaadin/flow/pull/9473#issuecomment-739958715

Basically there are some updates happening for most of the Vaadin "user input" components that should not occur, and when the component has been set as disabled / readonly, this will give the warning. Working on this.

**Comment by Frettman** [comment]
I still get this warning e.g. simply by adding a disabled DatePicker to my layout. (Vaadin Flow 20.0.6).
