### ISSUE TITLE
Generate nullable TS types for nullable Java types

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#8849]
When accessing properties of a TypeScript type generated from a Java type, I want properties that are nullable in Java to remain nullable in TypeScript, so that any existing Java POJO type can be used in an endpoint without any modifications (even if the some properties are `null` in Java at the run time).

This effectively reverts the decision made in https://github.com/vaadin/flow/issues/6717 (to make the TS types non-nullable by default). The main reasons to revert that decision are:

1. When all TS types are non-nullable by default, there needs to be a way to change the default to generate a nullable type sometimes. The current implementation relies on the `Optional<T>` wrapping, which is not ideal for the reasons explained in https://github.com/vaadin/flow/issues/7371 and https://vaadin.slack.com/archives/CDNTYMS9H/p1592226597202000. That issue suggest to rely on `@Nullable` instead of `Optional<T>`.

    Relying on `@Nullable` leads to a situation where one would need to write very confusing code like `@Nullable @NotNull MyEntity nullableNotNullEntity` in order to create a form with a combo-box that's initially empty, but requires a value (see https://github.com/vaadin/flow/pull/8835#discussion_r468081943).

    Dropping `@Nullable` and making all properties nullable by default resolves that issue.

1. When all TS types are non-nullable by default, the Java types that are outside of developers' control (3rd party, external modules, etc) may become unusable with endpoints. If they include a single `null` property, an attempt to return such a POJO from an endpoint would result in a runtime exception (see https://github.com/vaadin/flow/pull/6891).

    Dropping `@Nullable` and making all properties nullable by default resolves that issue.

The downsides of making all properties of the generated TS types nullable by default are explained in https://github.com/vaadin/vaadin-connect/issues/404:

1. When all TS types are nullable by default, the generated types become more complicated. For example, `List<Map<String, Map<String, Version>>> prop` in Java becomes `prop?: Array<{ [key: string]: { [key: string]: Version | undefined; } | undefined; } | undefined>` in TypeScript.

1. When all TS types are nullable by default, in TypeScript code developers need to check for `undefined` every time when they address any (sub) property of a POJO returned from an endpoint. For example, `const pojo = await Endpoint.getMeMyPojo(); if (pojo.name) { doStuff(pojo.name) }`.

    This downside is somewhat alleviated by the [optional chaining (`?.`)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) and [nullish coallescing (`??`)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_Coalescing_Operator) operators, that were added to the language recently.

Not a downside, but also relevant:

1. When all TS types are nullable by default, there needs to be a way to change the default and generate a non-nullable property sometimes. A reasonable approach would be to rely on some form of `@Nonnull` or `@NotNull` annotation. For example `@Notnull List<@Notnull Map<String, @Notnull Map<String, @Notnull Version>>> prop` to generate `prop: Array<{ [key: string]: { [key: string]: Version; }; }>`.

1. ~When all TS types are nullable by default, there is no need to run run-time checks on the values returned by the endpoints for `null` property values. The [null checker](https://github.com/vaadin/flow/pull/6891) will need to be removed.~

    UPD: The null checker is still needed to check that `@Nonnull`-annotated properties are indeed non null at the run time.

**Comment by haijian-vaadin** [comment]
Relying on `NotNull` to generate non-nullable properties would probably be problematic. 
Having in Java
```
@NotNull
private Company company;
```
would generate in TS
```
company: Company;
```
and default empty value for `company`, which will break the NotNull validation.

**Comment by mvysny** [comment]
Definitely a :+1: from me for annotation-based solution. However, I would stay away from JSR305's `javax.annotation.Nullable`, for couple of reasons:

1. The JSR305 is Dormant and has been for quite some time: https://stackoverflow.com/questions/2289694/what-is-the-status-of-jsr-305 therefore, the official support won't be coming anytime soon. The official artifact at https://mvnrepository.com/artifact/javax.annotation/javax.annotation-api/1.3.2 doesn't contain the `Nullable` annotation.
2. The unofficial artifact containing javax.annotation.Nullable (com.google.code.findbugs:jsr305:3.0.0) is deprecated and violates Oracle's license: https://github.com/google/guava/issues/2960
3. Both Guava and FindBugs is moving away from `javax.annotation.Nullable`.

In short, there's no official support for `javax.annotation.Nullable`; the unofficial support is deprecated and violates Oracle's license; all big players are moving away from that annotation.

The solution is to either:
1. Start using one of the `Nullable` annotations available in other packages: Intellij's `com.intellij:annotations:12.0` or SpotBugs' new annotation, etc.
2. Simply accept any annotation named `Nullable` and `NotNull` (regardless of the package) as an indication of the nullability (or lack thereof). I vote for this solution; this is also what Guava guys say: https://github.com/google/guava/issues/2960#issuecomment-336681820

On top of this, it would be good to have a pluggable Java Service API which would say whether a type is nullable or not. This would not only allow app- and customer-specific solutions, but also allow for support for Kotlin (which natively supports nullable types).

**Comment by haijian-vaadin** [comment]
This might also affect the form binding (validation).

**Comment by haijian-vaadin** [comment]
The task would be to update the generator (OpenApiObjectGenerator.java) to change the type to be nullable by default and updating the tests.
