### ISSUE TITLE
Cache the App Shell in the (generated) Service Worker

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#8854]
When adding the `@PWA` annotation to the `AppShell` class, I want all app shell assets to be cached, so that the app can load the app shell when started offline.

DoD:
 - the generated service worker caches all Webpack output: `index.html`, and all JS bundles (directly or indirectly referenced from `index.html`), so that the app can fully load the `/` page (app shell) from the SW cache
 - the revision of each cached resource is calculated based on its content, so that whenever the original file is updated the Service Worker detects the change and updates the cached version
 - all properties of the `@PWA` annotation work as earlier (expect for `offlinePath`)
    - `manifestPath`
    - `iconPath`
    - `startPath`
    - `name`
    - `shortName`
    - `description`
    - `themeColor`
    - `backgroundColor`
    - `display`
    - `offlineResources`
   
    The `offlinePath` property is depricated in favor of a `offlineComponent` / `offlineComponentImport` pair (defined in https://github.com/vaadin/flow/issues/8855).
 - the docs of the `@PWA` annotation are updated to reflect the new behaviour

Implementation notes:
 - Currently Vaadin handles the `@PWA` annotation at the run time: generates a web manifest file, a service worker file, icons, etc (see the [`PwaHandler`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java) class). In order to include the webpack output into the generated service worker it may be easier to move its generation to the build time where that info is readily available. There is a handy webpack plugin for that already (`workbox-webpack-plugin`).

   This approach is prototyped in the [`webpack-workbox`](https://github.com/vaadin/flow/compare/webpack-workbox) branch by Artur. Use it unless there is a good reason not to (in which case please explain the reasons in a comment to this issue).

**Comment by Haprog** [comment]
Currently linked issues in this epic: #8996, #9064, #9063, #8982, #8911, #8983, #8912 (linking here so that they are visible even without ZenHub access).

**Comment by haijian-vaadin** [comment]
This can be closed as all the subtasks have been accomplished.
