### ISSUE TITLE
Backport lit-html to 2.5

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#8862]
Backport the lit html feature to 2.4.
Also remember taking in the documentation.

**Comment by Artur-** [comment]
Also note that LitTemplate is meant to use with TypeScript so you need to backport TypeScript support also

**Comment by pleku** [comment]
In addition to benefiting users, TS support is required if we want to backport _livereload on frontend changes_.

**Comment by jcgueriaud1** [comment]
Any idea if TS will be backported in flow 2.x with Lit template?
Lit can be backported without TS and TS can be backported without lit but the entire documentation to use lit in Vaadin is written in Typescript.

**Comment by pleku** [comment]
>Any idea if TS will be backported in flow 2.x with Lit template?

As TS is what we recommend people to use in their lit templates, I'm fairly sure we'll backport both at the same time.

**Comment by mvysny** [comment]
@pleku what is the target Vaadin version for this please? Vaadin 14.4?

**Comment by pleku** [comment]
@mvysny it is 14.5.

**Comment by pleku** [comment]
### Acceptance Criteria
Lit-templates:
- [ ] The basic lit template support and the reading attribute values should be backported (former in 4.0 and latter in 5.0)
- [ ] Documentation is updated for v14 branch of the new docs site (both lit + polymer), need to mention that the changes are from 14.5
- [ ] SVC Java+HTML templates are changed to be lit template based (done for v18 version, backport if possible?)

Polymer-templates:
- [ ] Not deprecated in 2.x series. But javadocs should be updated that LitTemplate is the recommended way.
- In Flow 5.0 the polymer template parts were moved to another module, it is an open question if this would be done for 2.5 too. It should be 100% backwards compatible for application code if we do so - if someone is relying on some internal parts of the FW then they need to make the trivial changes.
- Updating Bakery from 14.4 to 14.5 shouldn't require any changes to polymer templates

Explicitly outside of the scope: Updating Bakery to be lit template based

**Comment by caalador** [comment]
SVC will need to delete the lts folders in resources to get LitTemplate version to LTS.
This shoud be done when 14.5 becomes the LTS version.
