### ISSUE TITLE
Make BeforeEvent forward/reroute methods consistent with UI.navigate()

### ISSUE THREAD

**Issue by epricer** [vaadin/flow#8873]
It would be nice to have BeforeEvent.forwardTo() and BeforeEvent.rerouteTo() methods that have the same signature as the [UI.navigate() ](https://github.com/vaadin/flow/blob/86bedce4f3153e5f167eeaca80e68aa7922fabf4/flow-server/src/main/java/com/vaadin/flow/component/UI.java#L853)method that takes a class an a single route parameter.

The existing UI.navigate() method is very convenient, and calling the BeforeEvent methods requires more boilerplate code.

**Comment by pleku** [comment]
Sounds like a reasonable request. Would be up for grabs for contributing. Unit tests mandatory to `RouterTest`, ITs to `RerouteIT` & `ForwardToIT` would be surplus.

**Comment by mshabarov** [comment]
Have been already done via https://github.com/vaadin/flow/pull/17407. Proposed for closure.
