### ISSUE TITLE
Using nested properties in a bean grid throws error when middle object is null

### ISSUE THREAD

**Issue by KasparScherrer** [vaadin/flow#8891]
### Description of the bug
When a Grid Column is added using a nested property name, it will throw an error if an intermediate object is null.  

The problematic line of code is in `NestedBeanPropertyDefinition::getGetter` where the intermediate object is fetched (null) and passed into `invokeWrapExceptions`.   
I think it should instead directly return a ValueProvider that always returns null, if `parent.getGetter().apply(bean)` returns `null`.

### Minimal reproducible example
```
@Route(value = "Test")
public class TestView extends VerticalLayout {
    public TestView(){
        add(new Button("add Grid for employees WITH company", click -> {
            addEmployeeGrid(true); // works
        }));
        add(new Button("add Grid for employees WITHOUT company", click -> {
            addEmployeeGrid(false); // does not work
        }));
    }

    public void addEmployeeGrid(boolean employeeHasCompany){
        List<Employee> employeeList = mockEmployees(employeeHasCompany);
        Grid<Employee> grid = new Grid<>(Employee.class, false);
        grid.setColumns("name", "company.companyname");
        grid.setDataProvider(new ListDataProvider<>(employeeList));
        add(grid);
    }

    private List<Employee> mockEmployees(boolean employeeHasCompany) {
        List<Employee> list = new ArrayList<>();
        if(employeeHasCompany){
            list.add(new Employee("Laurel", new Company("UBS")));
            list.add(new Employee("Hardy", new Company("IBM")));
        } else {
            list.add(new Employee("Laurel"));
            list.add(new Employee("Hardy"));
        }
        return list;
    }

    public class Employee {
        private String name;
        private Company company;

        public Employee(String name) {
            this.name = name;
        }
        public Employee(String name, Company company) {
            this.name = name;
            this.company = company;
        }
        public String getName() {
            return name;
        }
        public void setName(String name) {
            this.name = name;
        }
        public Company getCompany() {
            return company;
        }
        public void setCompany(Company company) {
            this.company = company;
        }
    }

    public class Company {
        public String companyname;

        public Company(String companyname) {
            this.companyname = companyname;
        }
        public String getCompanyname() {
            return companyname;
        }
        public void setCompanyname(String companyname) {
            this.companyname = companyname;
        }
    }
}
```

### Expected behavior
When a grid for employees without a company is added, the column for the property "company.companyname" is empty, because company is null.

### Actual behavior
When a grid for employees without a company is added, no items are shown and a NullPointerException is thrown.

### Versions:
    - Vaadin / Flow version: 14.3.0
    - Java version: OpenJDK 11
    - OS version: MS Windows 10 Pro
    - Application Server: IBM WebSphere Liberty 20.0.0.8

**Comment by KasparScherrer** [comment]
After writing this issue I now found an [older issue](https://github.com/vaadin/vaadin-grid-flow/issues/425) describing the same thing but in less detail (no repro).  
I think this bug has huge implications to all Binders and Grids that use Bean binding through property names. But should be quite easy to fix in my eyes.

**Comment by TatuLund** [comment]
This is kind of missing feature. We have since Vaadin 8.8 API to set nestedNullBehavior

https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/Grid.java#L1038

The same thing could be potential solution also in Vaadin 14+ as well.

We have two modes in Vaadin 8. By default we are throwing Null Pointer Exception, in other mode NPE is not thrown and value is set to be null. It depends on application which one is correct as one can also have scenario, where application should not have null there and NPE should be thrown in order to detect that.

**Comment by KasparScherrer** [comment]
> We have two modes in Vaadin 8. By default we are throwing Null Pointer Exception, in other mode NPE is not thrown and value is set to be null. It depends on application which one is correct as one can also have scenario, where application should not have null there and NPE should be thrown in order to detect that.

perfect! Your commit has everything I wanted. Thank you

**Comment by aelkman** [comment]
Which release is this planned for? I don't see it in 17.0.8

**Comment by tangomannX** [comment]
@TatuLund: Is there a reason why the api extension in vaadin 8 was made in grid but not in com.vaadin.data.BeanPropertySet.NestedBeanPropertyDefinition#getGetter where the actual cause of the problem is (in my opinion)?
