### ISSUE TITLE
Vaadin for TypeScript: Offline form submission MVP

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#8905]
As a developer, I want to be able to submit a form offline, when coming back online, the offline submitted form can be synced automatically to the backend. 

To make this happen,  we can make endpoint requests deferrable, so that when offline the requests can be cached locally, and when back online, those requests will be submitted automatically.

DoD:
1. Have a `@Deferrable` annotation that can be added both to the endpoint class or individual endpoint methods.
2. Once having the `@Deferrable` annotation on the Endpoint Java class, the generated Typescript function will return a `DeferrableResult`. E.g.
```
function _update(entity: Person): Promise<DeferrableResult<Person>> {
    return (new DeferrableResult('Person', 'update', {entity}) as DeferrableResult<Person>)._request();
}
```
3. A `DeferrableResult` has the metadata of an endpoint request, and possibly the intended result. E.g.
```
class DeferrableResult<T> {
  isDeferred: boolean = false;
  id?: number;
  result?: T;
  constructor(public endpoint: string, public method: string, public args?: any) {
  }

  async _request() {
      if (navigator.onLine) {
          this.result = await client.call(this.endpoint, this.method, this.args);
      } else {
          this.isDeferred = true;
          id = saveToIndexDB(this);
      }
      return this;
  }
}
``` 
4. The service worker will load the requests from the local cache and submit them when online.

Outcome:
1. All the existing code should work the same as before, nothing breaks.
2. Once an Endpoint method is marked as `@Deferrable`, then it's the developer's responsibility to check the returned `DeferrableResult` and do sth accordingly if needed. E.g.
```
const deferrableResult = update(person);
if (deferrableResult.isDeferred){
  // offline logic
}else{
  deferrableResult.result?.firstName;
}
```
Acceptance Criteria:
We can build an offline form like https://docs.google.com/document/d/1epUsSs2yM08l4HDvQGHzwxDwWRlXzmepQLD6qE0sI8I/edit

**Comment by platosha** [comment]
Using union types is not particularly nice, especially with an union of a developer-defined type and a framework-defined type. These are not related and probably not similar too, so developers would basically always have to put an if-check around the result for any kind of usage. I think, it’s better to have the `DeferredRequest` as a generic wrapper around the user type instead.

**Comment by haijian-vaadin** [comment]
Close this one, as the functionalities have been implemented.
