### ISSUE TITLE
Vaadin for TypeScript: Fail application start when detecting that @Cachable and @Deferrable are used together

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#8916]
[`@Cachable`](https://github.com/vaadin/flow/issues/8890) and [`@Deferrable`](https://github.com/vaadin/flow/issues/8905) are intended to be used for different use cases. Users shouldn't mix them together.

If such misusage is detected, throw an exception and prevent the application from starting, so that the user can be notified about this misusage early.

**Comment by vlukashov** [comment]
`@Deferred` endpoints are excluded from the Vaadin 19 release.
