### ISSUE TITLE
Read attribute values to server side memory from TS templates

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#8923]
Based on #3735 so that when the (lit) template is in TypeScript (instead of plain JS) the attribute values are reflected on the server side memory.

#### Acceptance Criteria
- Same as https://github.com/vaadin/flow/issues/3735#issuecomment-683695230 but to whatever TS templates Vaadin designer creates

**Comment by denis-anisimov** [comment]
This ticket cannot be done without https://github.com/vaadin/flow/issues/8966.

So #8966 goes first.

**Comment by denis-anisimov** [comment]
This is done along with the same ticket for Polymer templates.
