### ISSUE TITLE
Remove the progress-plugin from use

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#8933]
During webpack 5 investigation it was noted that the progress-plugin makes webpack compilation
slower and removing the plugin made the compilation 55.91% faster. 15.24 s with progress plugin vs 6.72 s without on
a CardProject from start.vaadin.com
Also on windows terminals and multiple other terminals the plugin will not print everything on a single line, 
but output multiple lines making unnecessary log rows.

Remember to check and update the Webpack Startup time test to have a lower value.

**Comment by pleku** [comment]
As a reference, the build times with and w/o progress-plugin https://docs.google.com/spreadsheets/d/1CuVsrpt8-cfFY9Edsc2o1V7YsL3a0DNEyz6AbXD8Nbo/edit#gid=0
