### ISSUE TITLE
Optionally generate files into `build/` instead of `target/`

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#8953]
Currently the Maven `target/` folder is hardcoded on many places in the Flow code. However, Gradle generates stuff into the `build/` folder.

I'm not familar with Flow's code base to point all places, however I can point out certain examples I've discovered:

1. The `NodeTasks.addBootstrapTasks()` function will always generate `index.html`/`index.ts` to `project_home/target/` (see the `outputDirectory` variable for more details)
2. The `DEFAULT_GENERATED_DIR` value. The value is read by the `DevModeInitializer` class and the `NodeTasks` class, and both classes use the same approach: the value may only be overridden via a Java System property `FrontendUtils.PARAM_GENERATED_DIR` (`vaadin.frontend.generated.folder`).
3. Possibly more: e.g. there is a code generating `target/flow-frontend/form/package.json`.

It's okay to have the `target/` hardcoded (to target Maven as the default environment), but a means should be provided to override this default value, in order to support Gradle better. The value can either be overridden by the Gradle plugin if the class is invoked only from the plugin code (`NodeTasks` accepting the name of the target folder as String parameter); the value can also be read from the `flow-build-info.json` when the value is needed in the runtime (the `DevModeInitializer` class for example).

### Versions:
    - Vaadin / Flow version: Vaadin 17.0.0, Flow 4.0.0

**Comment by pleku** [comment]
For Maven the `target` folder can be modified, and we have already worked on making it so that it is not hardcoded anywhere. So basically modifying it via Maven configuration should make it so that it is not used anywhere. Not sure how to do that for Gradle.

So this seems like a regression. We cannot presume that `/target/` is always the folder that is used for build output. If we cannot (in a certain place) check that what is the output folder (e.g. from Java code), then we should make it configurable. (CC: @haijian-vaadin)

**Comment by haijian-vaadin** [comment]
@pleku could you help to point to some code example where the target folder is not hardcoded?

**Comment by mvysny** [comment]
> For Maven the target folder can be modified, and we have already worked on making it so that it is not hardcoded anywhere (in Flow code)

That sounds really encouraging. Could you please point me to the place in the Flow codebase where Flow reads Maven properties? I can then analyze whether that approach would also work with Gradle.

**Comment by mvysny** [comment]
With the newest development of events, I think we can close this in favour of #10335
