### ISSUE TITLE
Push connection does not consider context path when opened in a route with nested wildcard params

### ISSUE THREAD

**Issue by mperktold** [vaadin/flow#8968]
### Description of the bug

I have configured Vaadin to be served from a context path `/vaadin/*`.
Also I have a route `about` that takes a `@WildcardParameter`.

When I directly open the app at a nested wildcard parameter, e.g. `/vaadin/about/a/b`, the client tries to establish the push connection at `/` instead of `/vaadin` and therefore fails.

When you enter the app at other routes, like `/vaadin`, `/vaadin/about` or even `/vaadin/about/a`, everything works fine.
Then you can even navigate navigate to `/vaadin/about/a/b` via the router, and it still works.

I observed this problem when upgrading from Vaadin 14.3.0 to 17.0.0.

### Minimal reproducible example
I created a repository that reproduces the problem: [vaadin-pushproblems](https://github.com/mperktold/vaadin-pushproblems)

Run the project, either using the Jetty Maven plugin via `mvn jetty:run` or using embedded Jetty server by executing the `Main` class.
Open the browser's DevTools to observe what's happening.
Open `localhost:8080/vaadin/about/a/b`.

### Expected behavior
The push connection should be established correctly regardless of where the user enters the app.

### Actual behavior
The push connection is tried to be established at `/` instead of `/vaadin` and therefore fails.

### Versions:
    - Vaadin / Flow version: 17.0.0
    - Java version: 11.0.8
    - OS version: Windows 10 64 bit

**Comment by joheriks** [comment]
Thank you @mperktold for the detailed bug description and example. This was indeed a regression from introduced with the new bootstrapping handlers in V17 (due to shared logic the problem also manifests even without using `@Push`, in that the live reload on frontend changes wouldn't work on views with parameters containing slashes).

**Comment by mperktold** [comment]
You're welcome @joheriks, thanks for taking care of this.

I wanted to verify that this works now as expected, but I'm not sure which version contains the fix.
With 17.0.4, it works in the reproducer but not in our actual project, which is odd.

Any idea why this could be the case?

**Comment by joheriks** [comment]
@mperktold The change did not make it into the latest Vaadin 17 release (Flow 4.0.2), so it shouldn't work with 17.0.4.
