### ISSUE TITLE
new NumberRenderer<>(provider, locale) does not format numbers according to locale

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#8970]
The `NumberRenderer(ValueProvider, Locale)` constructor ends up using `String.format(locale, "%s", value)` where `%s` in the format string is defined to use the value as a `Formattable` if it implements that interface and otherwise uses `toString()` on the value. Since e.g. `Double` or `Integer` doesn't implement `Formattable`, the end result is that numbers are formatted using `toString()` which uses the JVM default locale without taking the provided locale into account. The end result is thus that numbers are not formatted according to the provided locale.

Using the `NumberRenderer(ValueProvider, NumberFormat)` constructor instead (using e.g.`NumberFormat.getInstance(locale)` to get a `NumberFormat` instance) works as exected.

**Comment by pleku** [comment]
This has been working like this since 1.0 with the javadocs of
```java
     * The renderer is configured to render with the number's natural string
     * representation in the given locale.
```
so it is on the borderline as "the numbers natural string representation in the given locale" is not entirely obvious, but probably one could expect it to try to behave the same as when creating the `NumberFormat` out of the locale. The javadocs could be clarified then too. But I'll mark this as a bug.

**Comment by Legioth** [comment]
What is the purpose of a `NumberRenderer(ValueProvider, Locale)` constructor other than to format numbers based on the provided locale?

As it's currently implemented, the locale parameter seems to not have any practical impact at all except in the special case with a value provider that returns a custom `Number` subtype that also implements `Formattable` (none of the bulit-in ones do).

I expect that `new NumberRenderer<Object>(ignore -> Double.valueOf(1.2), new Locale("fi"))` would render values as `1,2` whereas the same with `Locale.ENGLISH` would render values as `1.2`. With the current implementation, both variants format the number according to the JVM's default locale.
