### ISSUE TITLE
Vaadin For TypeScript: API for getting all the offline submitted forms

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#8976]
As a developer, I want to know what are the offline form submissions, so that I can, for example, list all the offline submissions, show the number of pending requests. 

DoD:
1. In `Connect.ts`, there is a function in `ConnectClient` `getDeferredCalls(): Promise<Array<EndpointREquest>>`, which retrives all the cached requests.
2. Have a documentation and code example of how to use the APIs mentioned above.

**Comment by vlukashov** [comment]
`@Deferred` endpoints are excluded from the Vaadin 19 release.
