### ISSUE TITLE
Vaadin for TypeScript: Offline form submission Enhancements

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#8977]
As a developer, once I can submit a form offline, I want more peripheral functionalities to make my offline workflow more complete. E.g.
1. I can cache the data that are needed for rendering the form offline, e.g. items in a Combobox
2. I can get a list of all the offline submitted forms.
3. I can delete an offline form submission
4. I can preview an offline form submission
5. I can listen for the form data status, i.e. when the data sync to backend succeeded/failed.
.

This is an Epic for the offline form submission enhancements after the [MVP](#8905)

**Comment by vlukashov** [comment]
`@Deferred` endpoints are excluded from the Vaadin 19 release.
