### ISSUE TITLE
VaadinSession.checkHasLock throws IllegalStateException. How can i catch this?

### ISSUE THREAD

**Issue by lanmaster** [vaadin/flow#8987]
If i make mistake and, for example, create new thread, from which i try to invoke `DataProvider.refreshAll()` method.
Then i get stacktrace like this: 

> java.lang.IllegalStateException: Cannot access state in VaadinSession or UI without locking the session.
> 	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:526)
> 	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:540)
> 	at com.vaadin.flow.internal.StateTree.checkHasLock(StateTree.java:408)
> 	at com.vaadin.flow.internal.StateTree.beforeClientResponse(StateTree.java:339)
> 	at com.vaadin.flow.data.provider.DataCommunicator.lambda$requestFlush$2f364bb9$2(DataCommunicator.java:429)
> 	at com.vaadin.flow.internal.StateNode.runWhenAttached(StateNode.java:873)
> 	at com.vaadin.flow.data.provider.DataCommunicator.requestFlush(DataCommunicator.java:428)
> 	at com.vaadin.flow.data.provider.DataCommunicator.reset(DataCommunicator.java:176)
> 	at com.vaadin.flow.data.provider.DataCommunicator.lambda$handleAttach$425c8a01$1(DataCommunicator.java:398)
> 	at com.vaadin.flow.data.provider.AbstractDataProvider$1.accept(AbstractDataProvider.java:54)
> 	at com.vaadin.flow.data.provider.AbstractDataProvider$1.accept(AbstractDataProvider.java:51)
> 	at com.vaadin.flow.data.provider.AbstractDataProvider.lambda$fireEvent$2(AbstractDataProvider.java:110)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at com.vaadin.flow.data.provider.AbstractDataProvider.fireEvent(AbstractDataProvider.java:108)
> 	at com.vaadin.flow.data.provider.AbstractDataProvider.refreshAll(AbstractDataProvider.java:62)
> 	at ru.waptaxi.wtwebordermanager.jettyserv.webcontext.views.archive.archivegrid.ArchiveGrid$1.lambda$run$0(ArchiveGrid.java:154)
> 	at java.util.Optional.ifPresent(Optional.java:159)
> 	at ru.waptaxi.wtwebordermanager.jettyserv.webcontext.views.archive.archivegrid.ArchiveGrid$1.run(ArchiveGrid.java:153)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

In last method code `throw new IllegalStateException(message);` throw an exception which i don't know how to catch or log. How can i catch it?

**Comment by lanmaster** [comment]
<vaadin.version>14.3.3</vaadin.version>

**Comment by Legioth** [comment]
Generic runtime exceptions such as `IllegalStateException` are typically signalling programming mistake rather than an exceptional situation. For that reason, it's recommended to update the application code to avoid the mistake instead of trying to handle the exception.

In this particular case, the problem is that UI state is updated without the appropriate locking. Fix this either by either using `UI::access` to run your logic in a safe way or by using `VaadinSession::hasLock` to explcitly check whether the current thread holds the session lock before making any modifications to the state.

**Comment by lanmaster** [comment]
I didn't want to handle the exception. I just want to log this exception. How can i view this signal instead?

**Comment by Legioth** [comment]
This doesn't look like a report about a defect or missing feature in Vaadin, but rather like a generic question on how to use Java or Vaadin. I'd recommend taking such question to e.g.  https://vaadin.com/forum/ or https://stackoverflow.com/ instead.
