### ISSUE TITLE
Vaadin 17 serverside: UI.getCurrent().getRouter().navigate don't update browser history

### ISSUE THREAD

**Issue by DemiusAcademius** [vaadin/flow#8989]
I use tutorial for Spring security; after login I have code:
  ```java
ui.getRouter().navigate(ui, new Location(redirectUrl), NavigationTrigger.PROGRAMMATIC);
```
also I try code:
```java
UI.getCurrent().navigate(redirectUrl);
```

redirectUrl is empty String;

router redirects to the right view, but not update browser history (address bar);

total method code:
```java

@Override
    protected void onLogin(AuthorizationRequest r) {
        try {
            // try to authenticate with given credentials, should always return not null or throw an {@link AuthenticationException}
            final Authentication authentication = authenticationManager
                    .authenticate(new UsernamePasswordAuthenticationToken(r.username, r.pw));

            // if authentication was successful we will update the security context and redirect to the page requested first
            SecurityContextHolder.getContext().setAuthentication(authentication);

            // dirty hack
            var redirectUrl = requestCache.resolveRedirectUrl();
            if (redirectUrl.equals(SecurityConfiguration.LOGIN_URL)) {
                redirectUrl = "";
            }

            System.out.println("Redirect URL: " + redirectUrl);

            var ui = UI.getCurrent();
            // ui.getPage().executeJs("document.location = '/ " + redirectUrl + "';");
            ui.getRouter().navigate(ui, new Location(redirectUrl), NavigationTrigger.PROGRAMMATIC);
            /// UI.getCurrent().navigate(redirectUrl);
        } catch (AuthenticationException ex) {
            this.showErrorMessage(ex.getMessage());
        }
    }
```
method triggerred from lit-element event, Java code:
```java
@Override
    protected final void onAttach(AttachEvent attachEvent) {
        super.onAttach(attachEvent);
        registration = addListener(UserLoginEvent.class, e -> {
            this.onLogin(e.detail);
        });
    }
```

temporary I use hack:
```java
ui.getPage().executeJs("document.location = '/ " + redirectUrl + "';");
```

**Comment by DemiusAcademius** [comment]
But if I navigate from login to 'home' route all works OK. (problem only with empty route)

**Comment by bogdanudrescu** [comment]
Hi @DemiusAcademius, could you please send us your entire project where we can reproduce the issue! Thank you!

**Comment by bogdanudrescu** [comment]
`Router` class is an implementation detail, you should not use `ui.getRouter().navigate`. This is something else we should fix.

**Comment by bogdanudrescu** [comment]
We can't reproduce the issue, kindly ask @DemiusAcademius to provide the project where we may reproduce it.

Using `ui.getRouter().navigate(ui, new Location(redirectUrl), NavigationTrigger.PROGRAMMATIC);` won't work, as it is mentioned above, and we will fix it so that `UI.getRouter()` won't be publicly accessible, since its usage is internal.

`UI.getCurrent().navigate("");` works as intended and the address bar of the browser and the history updates accordingly.

**Comment by DemiusAcademius** [comment]
Unfortunately, I stopped using Vaadin server-side and now only use the Vaadin client components with lit-element together with the Quarkus. But I use client-side Vaadin router and found small issue.

I use path 
```
{ path: '/(.*)', component: 'main-menu' } for fullscreen menu.
```

If router show menu for path `/ui/billing/production/indications` (There is no component for this path yet ) and I use 
```
Router.go("/ui/billing")
```
for update path in chrome

Router inserts into outlet second instance of main-menu

**Comment by bogdanudrescu** [comment]
Actually, this `UI.getCurrent().getRouter().navigate(UI.getCurrent(), new Location(""), NavigationTrigger.UI_NAVIGATE);` is working and updates the address bar.

**Comment by bogdanudrescu** [comment]
@DemiusAcademius I have created https://github.com/vaadin/vaadin-router/issues/479. Please add more comments there about the client side issue, sharing a test project where the issue can be reproduced is very helpful.
