### ISSUE TITLE
Use workbox background sync for offline form submission

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#9045]
Currently, the cached offline requests are submitted in window online listener, one limitation is that a user needs to keep the application open, the requests cannot be submitted in the background.

One promising way of overcoming this limitation is to use [workbox background sync](https://developers.google.com/web/tools/workbox/modules/workbox-background-sync). So that the failed requests can be cached by workbox and submitted by service worker in the background.

DoD:
The requests indicated by the @Deferable annotation should be cached by workbox when offline, and submitted automatically when coming back online.

Ref:
check out the [disconnect-project](https://github.com/fluorumlabs/disconnect-project/tree/old-vue-implementation) for inspiration.

**Comment by vlukashov** [comment]
`@Deferred` endpoints are excluded from the Vaadin 19 release.
