### ISSUE TITLE
Use a default page size for DataCommunicator to avoid errors

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9051]
Related to https://github.com/vaadin/flow/issues/8828#issuecomment-696605995 also reported in https://vaadin.com/directory/component/multiselect-combo-box/discussions

We should just set a default page size in `DataCommunicator` so that components will not break due to not doing it. Otherwise it should be the responsibility of the constructor to require it as a parameter always.

The default page size should be 50 as it has been used for Grid and ComboBox thus far. The components can anyway override it at any point.

**Comment by pleku** [comment]
The workaround is to call the `setPageSize()` either in the component constructor, via component API or by getting the `DataCommunicator` (if no API provided then via reflection).

**Comment by jensgoe** [comment]
Is this fix included in 17.0.6. i could test it.

**Comment by mshabarov** [comment]
Hi @jensgoe, no. This fix will be available in `V17.0.7` which is scheduled on 13.10.2020.
