### ISSUE TITLE
Update/add documentation for PWA and new offline features

### ISSUE THREAD

**Issue by Haprog** [vaadin/flow#9065]
1. Update existing [PWA docs](https://vaadin.com/docs/v17/flow/pwa/tutorial-pwa-introduction.html) (check what pages need updates, at least some of it is outdated).
2. Document new offline features
  2.1. Offline start?
  ~2.2. Offline form submission?~ (has a separate [issue](https://github.com/vaadin/flow-and-components-documentation/issues/1339))
3. custom service worker

This may be split to more specific issues (and converted to epic) if needed.

**Comment by haijian-vaadin** [comment]
For the offline submission, we have a [ticket](https://github.com/vaadin/flow-and-components-documentation/issues/1339) for that, It's currently in progress.

**Comment by vlukashov** [comment]
The documentation for offline start should include an example of how to save server-side data to a client-side cache and use that data to render a view when offline.
