### ISSUE TITLE
pushURL configuration is not working

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/flow#9077]
### Description of the bug
setting pushURL configuration property is not working 

### Minimal reproducible example
Using a Vaadin 14.3.7 Spring Boot starter project, add a simple view that uses @Push
```
@Route("")
@Push
public class PushView extends VerticalLayout {
    public PushView() {

    }
}
```

And in `application.properties`, add the following line: `vaadin.pushURL = customUrl`
Then open `http://localhost:8080`

### Expected behavior
The websocket communication would work using the specified Url

### Actual behavior
An error is obtained in the client-side:
![image](https://user-images.githubusercontent.com/42799254/94551153-95995480-025d-11eb-804f-58e5627dfa5e.png)

### Versions:
    - Vaadin / Flow version: 14.3.7
    - Java version: 8
    - OS version: Windows
    - Browser version (if applicable): Chrome and Firefox

**Comment by joheriks** [comment]
Workaround until fixed is to define `vaadin.pushURL=/vaadinServlet/customUrl` instead.
