### ISSUE TITLE
WebBrowser may throw NPE for some methods

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#9111]
When invoking e.g. `webBrowser.isWindows()` a NPE may be thrown if `browserDetails` is null. This is similar to #6955 but still happens with Flow 3.1.7 as not all `isXXX` methods check if the property is null.

**Comment by denis-anisimov** [comment]
This is fixed in the the latest versions.
But `2.x` serises  has a couple of methods which just absent in the latest versions and they don't have this check.
