### ISSUE TITLE
Queued Deferred requests should be automatically submitted when the application starts online

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9115]
With Vaadin 17.0.6 / Flow 5.0.offline-SNAPSHOT there is an issued when queued deferred calls are not sent to the server if the app starts online:

**Example:**
1. open the app (online)
2. go offline
3. make a deferred call
4. close the web page
5. go online
6. open the app (online)

**Expected behavior**
The deferred request is submitted upon the application start.

**Actual behavior**
The deferred request sits in the queue and is not submitted until the app goes offline / online again.
<img width="658" alt="image" src="https://user-images.githubusercontent.com/22416150/95095609-ec0e0380-0733-11eb-8432-77370c59b201.png">

NOTE: [this line](https://github.com/vaadin/flow/blob/feature/offline/flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts#L291) should probably trigger submission of deferred requests if the app starts online. When doing so it should avoid having a race it the app starts in multiple tabs at the same (e.g. browser restart with the app opened in several tabs).

**Comment by haijian-vaadin** [comment]
Per discussion, it's better for the developer to invoke `client.checkAndSubmitCachedRequests()`. Reason being that a developer might [define some MiddleWare for keep tracking of the offline form submission status](https://github.com/vaadin/flow/issues/9046).

So the task could be:
1. Export the `checkAndSubmitCachedRequests()` method in `Connect.ts`
2. Have documentation in the [Offline Form Submission](https://github.com/vaadin/flow-and-components-documentation/blob/feature/offline/documentation/pwa/tutorial-offline-form-submission.asciidoc) page explain how to do that with code examples.

**Comment by haijian-vaadin** [comment]
Implemented in https://github.com/vaadin/flow/issues/9046 and https://github.com/vaadin/flow-and-components-documentation/pull/1366
