### ISSUE TITLE
AppShellRegistry.modifyIndexHtml() should not modify the shared state of the app

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9118]
How comes that `AppShellRegistry.modifyIndexHtml(Document document, VaadinRequest request)` modifies field title of `AppShellRegistry` instance, which is, in fact, stored in `ServletContext` attribute (that is - effectively singleton)?

https://github.com/vaadin/flow/blob/c009afc5c24d8a3d6abc14f6f5cd3faea80c1932/flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java#L271

**Comment by haijian-vaadin** [comment]
This ticket is fixed in https://github.com/vaadin/flow/pull/9133
