### ISSUE TITLE
Vaadin For TypeScript: Have integration tests for offline navigation acceptance criteria

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#9121]
DoD:
Having some integration tests in the Flow repo which test the acceptance criteria defined in this [platform issue](https://github.com/vaadin/platform/issues/1542). 

- <s>Once the app is opened in the browser, clicking on a navigation link works also offline: the new view is rendered and the browser URL changes. This requires that the app shell class has the @PWA annotation, and the target view is a client-side view (i.e. created with TypeScript). Done in the `test-ccdm-navigation` module with [pr 9261](https://github.com/vaadin/flow/pull/9261)</s>
- <s>For server-side views offline navigation works as before: clicking on a server-side view shows a 'you are offline' view. Done in `test-ccdm` module with [pr 9200](https://github.com/vaadin/flow/pull/9200)</s>

UPD
Could consolidate the tests in [pr 9261](https://github.com/vaadin/flow/pull/9261) and [pr 9200](https://github.com/vaadin/flow/pull/9200) into one place. And have test cases:

- client-to-client
- client-to-server
- server-to-client
- server-to-server

**Comment by joheriks** [comment]
PR #9325 adds server-to-client and server-to-server offline tests. The server-to-server fails because the navigation handler tries to call `flowRoot.$server.leaveNavigation` so it is ignored.
