### ISSUE TITLE
SPIKE: running npm mode in OSGi

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9126]
- Create a `feature/osgi` based on `2.5` branch
- See what needs to be done (in the feature branch) to be able deploy a Vaadin WAB which has `build-frontend` meaning that the webpack devserver is not started
- Any documentation needed should go to the starter readme for now

Target is to just get the application deployed and running using npm. It is fine if it is still ugly and requires workarounds in the starter. Once this is done, the base-starter for osgi should be updated to use the feature snapshot in npm mode (no webjar unpacking).

**Comment by denis-anisimov** [comment]
`feature/osgi` branch is created in the `base-starter-flow-osgi`  repo.
It allows to run the starter in NPM mode and production mode.
No changes in Flow repo done to be able to run the starter, instead a number of hacks are done directly in the starter project.
Issues are create for those hacks.
