### ISSUE TITLE
Revert tsconfig.json change to avoid needing a manual upgrade step in projects

### ISSUE THREAD

**Issue by Haprog** [vaadin/flow#9144]
Since #9109 the `feature/offline` branch uses TS in the service worker and needs to have `"lib": ["webworker"]` in `tsconfig.json` to avoid randomly failing webpack build. However we have no mechanism (at least currently) to do any updates to existing `tsconfig.json` in the project so we need to at least make sure to include this information in release notes as upgrade instructions, otherwise when upgrading to this version the webpack build will start failing randomly if you don't make this update to tsconfig.

**Comment by vlukashov** [comment]
Adding `"lib": ["webworker"]` to the root `tsconfig.json` file would silence the TS compiler in cases if the developer uses some of the Service Worker APIs in the main application code where they are not available. This is not ideal.

A different approach would be adding `/// <reference lib="webworker" />` to the top of the generated `sw.ts` file (as suggested in https://github.com/microsoft/TypeScript/issues/11781), or moving the `sw.ts` file into a separate folder with its own `tsconfig.json` (as suggested in https://stackoverflow.com/questions/56356655/structuring-a-typescript-project-with-workers).

**Comment by Haprog** [comment]
@vlukashov That sounds like a better solution. Thanks for the insights! I guess we can still use this issue to fix it (revert changes to tsconfig and add the lib reference comment to `sw.ts` if that makes it work).
