### ISSUE TITLE
OSGi: Properties which are used for the servlet registration via HTTP whiteboard are not available in the Deployment config for some reasons

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#9145]
This code is used to register a vaadin servlet via HTTP whiteboard spec:

```
Hashtable<String, Object> properties = new Hashtable<>();
        properties.put(
                HttpWhiteboardConstants.HTTP_WHITEBOARD_SERVLET_ASYNC_SUPPORTED,
                true);
        properties.put(InitParameters.SERVLET_PARAMETER_COMPATIBILITY_MODE,
                false);
        properties.put(InitParameters.SERVLET_PARAMETER_PRODUCTION_MODE, true);
        properties.put(HttpWhiteboardConstants.HTTP_WHITEBOARD_SERVLET_PATTERN,
                "/*");
        ctx.registerService(Servlet.class, new FixedVaadinServlet(),
                properties);
```

But deployment configuration created by the servlet for some reason returns `false` for method `isProduction`.

I have to override `createDeploymentConfiguration`  method and return a custom Deployment configuration instance which returns `true` for `isProduction`:
```
private static class FixedVaadinServlet extends VaadinServlet {
        @Override
        public void init(ServletConfig servletConfig) throws ServletException {
            super.init(servletConfig);

            getService().setClassLoader(getClass().getClassLoader());
        }

        @Override
        protected DeploymentConfiguration createDeploymentConfiguration(
                Properties initParameters) {
            initParameters.put(InitParameters.SERVLET_PARAMETER_PRODUCTION_MODE,
                    true);
            DeploymentConfiguration config = new DefaultDeploymentConfiguration(
                    getClass(), initParameters) {
                @Override
                public boolean isProductionMode() {
                    return true;
                }
            };

            return config;
        }

    }
```

**Comment by pleku** [comment]
Acceptance Criteria
- [ ] the project base doesn't have any hack for the deployment configuration
- [ ] the readme has documentation on how to switch & build for both production mode and non-production mode

**Comment by denis-anisimov** [comment]
This is the mixture of my mistake (because of lack of HTTP whiteboard spec detailed knowledge) and an issue which I described here : https://github.com/vaadin/flow/issues/9192

First of all:
- init parameter can't be used as is .It needs to be prefixed with  `"servlet.init."`. So `"productionMode"` become `"servlet.init.productionMode"`.
- one may not use `true`  as a boolean value in the properties (see the reason in #9192 even though this may be fixed in HTTP whiteboard RI properly, the reason is exactly the same: properties are not really convenient class here). `"true"` as a String needs to be set as a property value.
- and the same mistake I've done in the code `initParameters.put(InitParameters.SERVLET_PARAMETER_PRODUCTION_MODE,true);` which should set production mode for our own deployment configiration.
