### ISSUE TITLE
Fusion: Random 'Anonymous access is not allowed' error for @AnonymousAllowed endpoint calls.

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#9164]
Some people have reported that they randomly got the `Anonymous access is not allowed` error for @AnonymousAllowed endpoint calls. The error looks like in the attached screenshot.

The difficult part is that it's not reproducible. From the code in `VaadinConnectAccessChecker`, it might come from the CSRF token check.
```
    private String verifyAnonymousUser(Method method,
            HttpServletRequest request) {
        if (!getSecurityTarget(method)
                .isAnnotationPresent(AnonymousAllowed.class)
                || cannotAccessMethod(method, request)) {
            return "Anonymous access is not allowed";
        }
        return null;
    
    private boolean cannotAccessMethod(Method method,
            HttpServletRequest request) {
        return requestForbidden(request)
                || entityForbidden(getSecurityTarget(method), request);
    }

    private boolean requestForbidden(HttpServletRequest request) {
        if (!xsrfProtectionEnabled) {
            return false;
        }

        HttpSession session = request.getSession(false);
        if (session == null) {
            return false;
        }

        String csrfTokenInSession = (String) session.getAttribute(VaadinService.getCsrfTokenAttributeName());
        return csrfTokenInSession == null || !csrfTokenInSession.equals(request.getHeader("X-CSRF-Token"));
    }
```
![unnamed.png](https://images.zenhubusercontent.com/5e0dcbb3f28dea52f669852b/6487df2d-259f-4874-a554-8c70514ee242)

One observation: it happened today after the server has started and waited for about 6 minutes, then when trying to submit a request, I got the `Anonymous access is not allowed` error.

DoD:
1. Separate the error messages, 1 error message with 2 different conditions confuses the user.
When `!getSecurityTarget(method)`, return "Anonymous access is not allowed".
When `cannotAccessMethod(method, request)`, return "CSRF token has expired" or sth similar.
2. The root cause is identified and fixed.

**Comment by Legioth** [comment]
Might be useful to add server-side logging that explicitly tells the reason when rejecting requests.

**Comment by johannest** [comment]
It looks like that Vaadin Connect client caches the csrf token. When the token changes for any reason, the connect client still has the old one and subsequent calls to server-side endpoints fails. For me the easiest way to change the token is to use live reload and do server-side change that triggers the reload, at least with IntelliJ that results quite often call to VaadinService.createAndRegisterSession which creates a new session and csrf token. Clearing the browser cache helps when the issues starts happening. But that is not practical workaround.

**Comment by platosha** [comment]
I’m cannot to reproduce this with `master` and `feature/offline` branches. I suspect the issue is caused elsewhere by caching HTML responses (service worker, perhaps?)

Nevertheless, here are IT tests PRs: #9329 vaadin/spring#677 They are passing currently on bare master, but fail if there is a custom service worker with HTML caching in the test application, e. g. `workbox-webpack-plugin` is used in `webpack.config.js` with this combination of settings:
- `GenerateSW` mode
- precaching for the build and `index.html`
- and `navigateFallback: 'index.html'`

My intention is to make sure that we don’t accidentally introduce this while developing our provided service worker code.
