### ISSUE TITLE
LitTemplate parser prints: LitTemplateParserImpl - Couldn't find the definition of the element with tag 'my-form'

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#9165]
Having the following Java class
```java
@Tag("my-form")
@JsModule("./src/my-form.ts")
public class MyForm extends LitTemplate {
    @Id
    public TextField nameField;
}
```

accompanied by the `my-form.ts` file:

```ts
import {html, LitElement} from 'lit-element';

// @customElement("my-form")
export class MyFormElement extends LitElement {
    render() {
        return html`
      <h2>Hello</h2>
      <vaadin-text-field id="nameField"></vaadin-text-field>
    `;
    }
}

customElements.define("my-form", MyFormElement);
```

Upon browsing to the route containing this component, the following is logged into the console:
```
[ForkJoinPool.commonPool-worker-1] INFO com.vaadin.flow.server.DevModeHandler - Started webpack-dev-server. Time: 10342ms
[http-nio-8080-exec-7] INFO com.vaadin.flow.component.littemplate.LitTemplateParserImpl - Couldn't find the definition of the element with tag 'my-form' in any lit template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method LitTemplateParser.getTemplateContent() which should return an element representing the content of the template file
[http-nio-8080-exec-7] INFO com.vaadin.flow.component.littemplate.LitTemplateDataAnalyzer - Couldn't parse template for class org.vaadin.example.MyForm class. Only specific Lit template format is supported. Please check that your template definition directly contains 'render' method which returns html`_template_content_`.
[http-nio-8080-exec-5] INFO com.vaadin.flow.component.littemplate.LitTemplateParserImpl - Couldn't find the definition of the element with tag 'my-form' in any lit template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method LitTemplateParser.getTemplateContent() which should return an element representing the content of the template file
[http-nio-8080-exec-5] INFO com.vaadin.flow.component.littemplate.LitTemplateDataAnalyzer - Couldn't parse template for class org.vaadin.example.MyForm class. Only specific Lit template format is supported. Please check that your template definition directly contains 'render' method which returns html`_template_content_`.
```

However, the form itself is displayed, and the `nameField` is populated correctly (the following code works properly and doesn't fail with NPE):

```java
@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        final MyForm form = new MyForm();
        add(form);
        form.nameField.setValue("Link");
    }
}
```

The INFO messages should either be an exception (can't load template, can't continue) or shouldn't be logged at all. Current behavior is confusing for the developer - is it working correctly or not? Do I perhaps have some kind of mistake in my ts file?

### Versions:
    - Vaadin / Flow version: 18.0.0.alpha1 / 5.0.0.alpha1
    - Java version: 1.8
    - OS version: Ubuntu 20.10 x86-64
    - Browser version (if applicable): Firefox
    - Application Server (if applicable): Tomcat 9.0.31
    - IDE (if applicable): Intellij

**Comment by mvysny** [comment]
[skeleton-starter-flow.zip](https://github.com/vaadin/flow/files/5369384/skeleton-starter-flow.zip)

Example app which reproduces the issue.

**Comment by Artur-** [comment]
Is the logging related to using `customElements.define("my-form", MyFormElement);` instead of `@customElement("my-form")` ?

**Comment by mvysny** [comment]
Both approaches will cause the log messages to appear.

**Comment by denis-anisimov** [comment]
I think this is known issue which is not reported yet.

The issue is just an extension : `ts` is not recognized as an extension for templates.
If you use `.js` file extension then it should just work fine.
Could you please check it.

Then the question is : should we recognize only `ts` and `js`  extensions or remove any extension check at all....

**Comment by denis-anisimov** [comment]
For this specific case: `ts`  extension is not recognized as an extension for JS module file and it's filtered out.

The log has `INFO` level which clearly means it's not SEVERE.

The inability of parse the template doesn't break functionality: this is done by @Artur- from the very beginning.
E.g. in polymer template `@Id` injection checks that the the element presents in the template and it throws if it doesn't.

The current impl (done by Artur) doesn't check anything in the template. And there is an IT which will fail if such check will be done (in the straightforward way). We support only templates produced by Designer which doesn't produce templates like in the IT test.
Another feature which relies on parsing is setting template attributes on the server side as properties.

I may not answer to the question whether we should allow to work any template format or not (which currently is supported but some functionality won't work): this is not my decision.
It's extremely complicated to implement the parser which will cover all usecases, moreover there was an explicit decision to support only templates which are produced by designer.
Again: the question whether we should throw and explicitly disallow any other template (which is _explicitly_ supported at the moment via IT) is something which forced by the current impl and I don't have any opinion about this.
