### ISSUE TITLE
Please make LitTemplateParserImpl public

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#9169]
Vaadin 18.0.0.alpha1. Please make LitTemplateParserImpl public otherwise it's really hard to hook into the template loading mechanism.

**Comment by denis-anisimov** [comment]
For testing purpose: it's possible to extend the class already just putting the subclass into the same package (it's a bit ugly approach I know, but for testing it can be applied).
For other purposes: I would like to see usecases.
The class is internal and should not be exposed to the users as API (at least there was no any reasons for this). So if it's made `public` then it should be moved into some `internal` package.

**Comment by mvysny** [comment]
> just putting the subclass into the same package (it's a bit ugly approach I know, but for testing it can be applied)

I wonder whether that's compatible with Java 9+ module system. This kind of hacks is a bit of a security hole after all, and it might be plugged, by JavaEE servers, Java 9 modules, or other security counter-measures.

Also, why make LitTemplateParserFactory public when the only viable option is to extend LitTemplateParserImpl which is not public?

**Comment by mvysny** [comment]
Discussion continues in the PR #9171
