### ISSUE TITLE
Please update Apache httpclient

### ISSUE THREAD

**Issue by mas4ivv** [vaadin/flow#9173]
flow-server is currently using httpclient 4.5.2, which has a major security issue (see https://issues.apache.org/jira/browse/HTTPCLIENT-1803). This version should be upgraded to at least 4.5.3.

**Comment by pleku** [comment]
Hi and thanks for the heads up. We'll bump the version to the latest in that minor release.

**Comment by pleku** [comment]
For any existing project, a newer version can be declared in the project and the one imported by flow-server can be excluded (if necessary).
