### ISSUE TITLE
Document the OSGi support

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9174]
While in most cases people will just take the base starter to get a Vaadin-OSGi project up and running, we should still document what there is to it, so that it is possible to replicate the necessary things for another Vaadin project like BAS.
#### Acceptance Criteria
- [x] Add docs to the base starter readme on what is required for a Vaadin project to make it possible to build is as an WAB and to be able to deploy it to your OSGi framework.
- [x] List all known limitations, like lacking declarative support, lacking documentation on how to get push working (other than Karaf)

**Comment by denis-anisimov** [comment]
done in the base-starter project osgi branch
