### ISSUE TITLE
OSGi: make IT tests running in NPM mode for felix-jetty

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#9188]
We have a nightly build which is executed in compatibility mode to verify that OSGi works.

There is already a PR which will allow to run NPM mode in felix jetty without ugly hacks.
Once this is merged we should make a build which verifies that NPM mode works in production mode.
So we need another nightly build which will run our test-root-context tests and verify that OSGi in NPM mode and production is not broken.

At the moment there is no any other way to prove that NPM mode works in OSGi except manual check.

**Comment by pleku** [comment]
We should make this for now based on the `2.5-osgi-SNAPSHOT` for every night.

**Comment by denis-anisimov** [comment]
Two nightlies are made for `feature/osgi` branch ( 2.5.osgi-SNAPSHOT) : compat mode job (the same as OSGi validation for `2.5`) and NPM mode job
