### ISSUE TITLE
Do not recommend disabling Spring Security CSRF

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#9202]
In documentation on Spring Security integration (https://vaadin.com/docs/v17/flow/typescript/adding-login-form-with-spring-security.html) we recommend disabling csrf globally (`http.csrf().disable();`) as a default solution. This is a bad practice for the real apps and should be avoided (see [Coding Practices and Recommendations of Spring Security for Enterprise Applications](https://arxiv.org/pdf/2007.14319).)

As an alternative we suggest
> If CSRF is still needed for other endpoints in the application, it is possibe to disable CSRF just for Vaadin endpoints: `http.csrf().ignoringAntMatchers("/connect/**")`

Suggestion: remove recommendation to disable CSRF completely and recommend this alternative approach.

**Comment by haijian-vaadin** [comment]
Verify this at least with our CRM tutorial project before updating the doc

**Comment by haijian-vaadin** [comment]
Fixed in https://github.com/vaadin/flow-and-components-documentation/pull/1368
