### ISSUE TITLE
Fusion: Weird UI behavior when offline

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#9207]
As a user, when I am offline, if I see the offline page, I don't want to see the Vaadin reconnection dialog and `reconnect attempt xxx for heartbeat`, see the attached screenshot.
![Screenshot 2020-10-20 at 21.28.43.png](https://images.zenhubusercontent.com/5e0dcbb3f28dea52f669852b/7a964df5-c5e0-42d4-afd4-ff7e8628b6a9)

**Comment by haijian-vaadin** [comment]
part of #9203

**Comment by haijian-vaadin** [comment]
pause the heartbeat while`navigator.online` is `false`

**Comment by joheriks** [comment]
I think in addition to pausing the heartbeat, we could also add automatic load of the server-side view when transitioning back to the online state. This would be consistent with the behavior we had for the `offline.html` page which contained the following hook:
```
  window.addEventListener('online', function () {
    window.location.reload();
  });
```
