### ISSUE TITLE
Fusion: field with @Id annotation in Java should be nullable in the generated TypeScript code

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#9222]
Given a Java entity
```
@MappedSuperclass
public abstract class AbstractEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;
    ...
}
```
The generated TypeScript code is
```
export default interface AbstractEntity {
  id: number;
}
```
This leads to the problem that an object that extends from AbstractEntity will have a default value 0 for id. This could result the problem that a record of id 0 in the DB would be overridden.

Note that in the example above, it's not a problem, since it's using `GenerationType.SEQUENCE` and by default 0 is considered an invalid id. But the default behavior can be overridden.

DoD:
For a Java field that has an `@Id` annotation (with simple name check), the generated typescript field should be nullable. e.g.
```
export default interface AbstractEntity {
  id: number | undefined;
}
```

**Comment by Legioth** [comment]
Would that cover `@javax.persistence.Id`, `@org.springframework.data.annotation.Id` or some other arbitrary `@Id` annotation?

**Comment by haijian-vaadin** [comment]
Good question,  I think any `@Id` could be treated as nullable.
