### ISSUE TITLE
Make 2.x validate on NPM mode instead of compatibility

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#9237]
Now that we have NPM as the main focus for the 2.x branch we should change the validation to use NPM mode instead of compatibility mode and have compatibility as a nightly test run.

This will make bender snapshot builds faster as right now we test compatibility and then root-context in NPM mode as extra.

This would basically impact 2.4 forward.

When this is added the NPM profile can be removed from the TeamCity Flow PR build.

**Comment by mcollovati** [comment]
This has been fixed
