### ISSUE TITLE
Create a demo for the application theme with global styles

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#9282]
Create a demo for the feature in `vaadin/application-theme-demo` which showcases the in-project app theme usage with some global css applied to the Vaadin crm tutorial end result. https://github.com/vaadin-learning-center/crm-tutorial

It will be initially just a module for “in-project demo” and later on for reusable case. It should showcase
- [x] global styles
- [x] component specific theming with e.g. applying borders to all text-fields
- [x] background image used via css
- [ ] background image used via Java code
- [x] using a custom font from a npm package ?
- [x] using font-awesome icons from an npm package

Part of https://github.com/vaadin/flow/issues/9246

**Comment by taefi** [comment]
`background image used via Java code` is waiting for #9535

**Comment by taefi** [comment]
After #9622 is merged, the `background image used via Java code` is working now.
