### ISSUE TITLE
The docs for theming should be revised and added for the new In-App Theming

### ISSUE THREAD

**Issue by taefi** [vaadin/flow#9284]
The docs for https://github.com/vaadin/docs/tree/master/articles/themes about theming should be revised and add these:

- Application theme is the way to go instead of the old way of doing things.
- The existing docs about lumo/material could be either removed or "deprecated" as not recommended anymore so those could be moved and a disclaimer added to top that "this is how it used to be".
- Need to check how the variant should be applied for Lumo later on and update that on docs.

Part of #9246

**Comment by tanbt** [comment]
https://github.com/vaadin/docs/pull/41
