### ISSUE TITLE
Some heuristic checks are required for the first arg in the TemplateModel.importBean method

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#929]
Since TemplateModel.importBean method accepts any object it's very easy to make a mistake.

F.e. pass Optional instance instead of bean (which is inside the Optional instance).

There should be some checks that prevents calling import for such situation: either disable some known types or do not allow to pass anything that has no any properties at all.

**Comment by mshabarov** [comment]
Closed because `TemplateModel` and `Polymer templates` are deprecated in V23 and we're not going to add a new functionality there.
