### ISSUE TITLE
Non-thread-safe cache implementation in NpmTemplateParser

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#9302]
Class `NpmTemplateParser` (singleton via `NpmTemplateParser.INSTANCE`) has the following implementation of caching:

https://github.com/vaadin/flow/blob/f1a1b9c97d8aeeb55e33e7952d792beb012a96ce/flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java#L202-L220

Here, `cache` is a `HashMap<String,String>`. Not only it is modified outside of synchronized block, but also, instead of (atomic in case of `ConcurrentHashMap`, if that would be one) `computeIfAbsent()`, a `containsKey - put - get` is used.

**Comment by denis-anisimov** [comment]
This is absolutely valid bug.
The access to the `cache` is thread unsafe.
