### ISSUE TITLE
Investigate method to emulate offline properly for ITs

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#9314]
PR #9280 introduces a change to `sw.ts` to fix issue #9218 and adds a test that offline navigation to a non-root route works correctly. Before the fix, putting Chrome in offline mode and loading a non-root route resulted in the following state if the route had not been reloaded previously while still online:

![chrome-site-cant-be-reached](https://user-images.githubusercontent.com/2838896/98124672-2b0eb080-1ebc-11eb-99e8-783f69106485.png)

However, the IT validating the fix (`ServiceWorkerIT::testOfflineStart_nonRootReload`) does not trigger the above screen in Chrome with the original `sw.ts`. Rather, the app works as expected. So currently,  this IT does not protect against future regressions.

So there is a discrepancy between manually setting offline mode in Chrome Devtools and the currently employed method in `ChromeDeviceTest`. Investigate alternative methods for offline ITs that correspond more closely to the real offline scenario. Some possible ideas:
- Use Chrome DevTools API directly
- Enable Offline via DevTools using a high-level scripting library like [puppeteer](https://github.com/puppeteer/puppeteer)

**Comment by joheriks** [comment]
Tested https://webdriver.io/docs/api/chromium.html#setnetworkconditions, with `network_conditions={offline: true, throughput: 0, latency: 0}`. Does not trigger the issue.

**Comment by joheriks** [comment]
### Summary of investigation

As Selenium 4 (current in alpha) adds an API for sending CDP (Chrome DevTools Protocol) commands, I suggest we wait for the final and TestBench upgrade. With Selenium 4 the network condition emulation mentioned in the previous comment can be accessed as follows. To go offline:
```java
        DevTools devTools = chromeDriver.getDevTools();
        devTools.createSession();
        devTools.send(Network.emulateNetworkConditions(
                true, // offline flag
                0, // latency
                -1, // download throttling
                -1, // upload throttling 
                Optional.empty()
        ));
```
and back online:
```java
        devTools.send(Network.emulateNetworkConditions(
                false, // offline flag
                0, // latency
                -1, // download throttling
                -1, // upload throttling 
                Optional.empty()
        ));
```
These commands work without enabling the `mobileEmulation` experimental option. Tested in headless and graphical mode.

**Comment by haijian-vaadin** [comment]
Agreed to close this one and have a new ticket (#9555) to use the new APIs in Selenium 4.
