### ISSUE TITLE
In LitTemplates renderers of grid mapped by Id do not work

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#9316]
It's impossible to configure grid column renderers in Lit templates, because content is not displayed even though it is rendered in dom. It seems that the problem is that java sets `loading` when the component is mapped and it's never cleared.

Although flow documentation recommends defining columns and data in Java, it should be possible to do in Ts.

How to reproduce:

Download a project from start.vaadin.com with the card-list view in HTML+Java.

Perform the following changes to java code:

```
@Route(value = "card-list")
@PageTitle("Card List")
@JsModule("./views/cardlist/card-list-view.ts")
@Tag("card-list-view")
public class CardListView extends LitTemplate implements AfterNavigationObserver {

    public CardListView() {
    }
    
   @Id("grid")  Grid<Person> grid;

    @Override
    public void afterNavigation(AfterNavigationEvent event) {
        List<Person> persons = Arrays.asList(
        createPerson(...),
        ...
      );

     this.getElement().setPropertyList("items", persons);
    }

}
```

Change the extension of `card-list-view.js` to `.ts` and modify it in so as instead of using templates it uses renderers as it's recommended by the web component.

```
import { css, customElement, html, LitElement, property } from 'lit-element';

@customElement('card-list-view')
export class CardListView extends LitElement {

  @property({ type: Array })
  items!: any[]

  render() {
    return html`
      <vaadin-grid id="grid" theme="no-border no-row-borders" .items="${this.items}">
        <vaadin-grid-column .renderer="${this.colRenderer}">
        </vaadin-grid-column>
      </vaadin-grid>
    `;
  }

   colRenderer(root:HTMLElement, _:any, data:any) {
    if (!root.firstChild) {
      const item = data.item;
      root.innerHTML = `
          <vaadin-horizontal-layout theme="spacing-s" class="card">
          <img src="${item.img}"></img>
          <vaadin-vertical-layout>
            <vaadin-horizontal-layout theme="spacing-s" class="header">
              <span class="name">${item.name}</span>
              <span class="date">${item.date}</span>
            </vaadin-horizontal-layout>
            <span class="post">${item.post}</span>
            <vaadin-horizontal-layout theme="spacing-s" class="actions">
              <iron-icon icon="vaadin:heart"></iron-icon>
              <span class="likes">${item.likes}</span>
              <iron-icon icon="vaadin:comment"></iron-icon>
              <span class="comments">${item.comments}</span>
              <iron-icon icon="vaadin:connect"></iron-icon>
              <span class="shares">${item.shares}</span>
            </vaadin-horizontal-layout>
          </vaadin-vertical-layout>
        </vaadin-horizontal-layout>      
      `
    }
  }
  ```

  Inspecting the DOM you can see that everything is rendered fine, but flow incorrectly sets the loading attribute, preventing user to see the cards.

  Obviously configuring everything with java API works, but it's cumbersome for projects that already are using templates for simplifying java code.

 It also works removing the Id mapping `@Id("grid")  Grid<Person> grid;`

There is a project with these changes already set at https://github.com/manolo/dx-lit-element

**Comment by knoobie** [comment]
Reminds me of the opposite in #9018 `It is not supported to declare presentation like grid columns or renderers via the template (only via component API in Java).`

**Comment by manolo** [comment]
Even though the recommendation for configuring the grid is via Java, mapping the grid element should not ruin the grid configuration  done in the template. It might be interesting to have the grid element instance in java side to for example change visibility.
In any case, documentation at https://vaadin.com/docs/v17/flow/polymer-templates/tutorial-template-intro.html does not mention that configuring grid in template is unsupported, just that it's recommended the java way.
Not supporting any kind of configuration in the template for grid is IMO a backsliding.

**Comment by manolo** [comment]
@knoobie

**Comment by knoobie** [comment]
@manolo My interpretation would be `grid columns` or `renderers via the template`. Nevertheless, I would like to configure columns in lit as well. Just wanted to point to the ticket I know of which could be the culprit why it isn't supported at the moment.

**Comment by pleku** [comment]
For Flow 5.0, this works as intended. There is no feature parity between `PolymerTemplate` and `LitTemplate` because for the latter it is intended that you'll drive data and logic through the Java API. In this case this it means `Grid` column configurations and their data. It is considered bad practice now to split it between the template and the Java code. In case someone wants to 

This needs to be clarified in the documentation and made explicit. Similarly we should probably consider adding a section about "differences between polymer & lit template and migration" (if there is not one already) to avoid causing confusion.

**Comment by pleku** [comment]
> Nevertheless, I would like to configure columns in lit as well.

👍 but I might steal this issue for fixing the documentation about grid column configuration for now and ask for another issue about supporting configuring the grid columns in Lit templates. That would be then dropped to the backlog to wait and see if there is enough interest on this feature.
