### ISSUE TITLE
swagger deps are not OSGi compatible

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#9334]
There is a number of `swagger-codegen`  ( group id `io.swagger.codegen.v3` , e.g. `swagger-codegen` artifact ) fusion related deps in the `flow-server` which are not OSGi compatible.

The same issue as #9333.

**Comment by denis-anisimov** [comment]
It seems this library is used only either in maven plugin or in dev mode `DevModeInitializer`.
Since we explicitly exclude `DevModeInitializer` for OSGi it may be set as optional without any issue.
So this is the same situation as with `http-client` .

Proper fix for this should be : 
- extract dev mode module from `flow-server` : long-requested thing.
- modularize Fusion functionality so that it works only if it's available (in the classpath). It will require dependency inversion which can be done via introduced `Lookup` in the `6.0` .

**Comment by haijian-vaadin** [comment]
The endpoint code has been moved to `fusion-endpoint` module in https://github.com/vaadin/flow/pull/9499, so this ticket can now be closed.
