### ISSUE TITLE
DevModeHandler is not Serializable

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#9339]
`DevModeHandler` is not serializable because of

```
    private final CompletableFuture<Void> devServerStartFuture;
```

Since the whole stateful implementation of `DevModeHandler` does not support serialization, the class should implement custom `readObject`/`writeObject` explicitly throwing `NotSerializableException`

**Comment by pleku** [comment]
Why would a development mode only class be serializable ?

**Comment by fluorumlabs** [comment]
> Why would a development mode only class be serializable ?

That's a good question. Could that cause issues during hot swapping?
