### ISSUE TITLE
Fusion: Application Connection State store

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#9343]
As a developer, I want to have a single source of truth about the current application state, so that I can e.g. show a connection state indicator correspondingly. 

In Flow, there are different causes for a connection state change, xhr request, heartbeat, reconnecting attempts, push. 
In Fusion, it can be caused by an endpoint call, navigator.online, navigator.offline.

DoD:
Have a `ConnectionStateStore` class in `ConnectionSate.ts` file, which holds the state and should update the state based on the statechart described in #9203.
```
class ConnectionStateStore {
   // connection state could be but not limited to: connected, loading, loaded, reconnecting, or connection lost
   state: ConnectionState;
   
   getState():  ConnectionState{
     return sate
   }

   addStateChangeHandler()
   
   goOnline()
   goOffline()
   // methods in ConnectionStateHandler
}
export const connectionStateStore = new ConnectionStateStore();
```

Note, take a look at [ConnectionStateHandler](https://github.com/vaadin/flow/blob/master/flow-client/src/main/java/com/vaadin/client/communication/ConnectionStateHandler.java), see how Flow handles state transitions.

Part of #9203

**Comment by joheriks** [comment]
Initial sketch of state store here:

https://github.com/vaadin/flow/blob/7afba9ae01a5a6429a814a969c1d234d9604533a/flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts

No transitions between the states yet, will implement those next.

**Comment by vlukashov** [comment]
1. When storing anything in the global namespace, keep the shared Flow / Fusion state in the `window.Vaadin` namespace (not in the `window.Vaadin.Flow` namepace).
1. There needs to be a TypeScript API for configuring the loading indicator, e.g.
    ```ts
    import { setLoadingIndicatorConfiguration } from '@vaadin/flow-frontend/AppShell`;

    setLoadingIndicatorConfiguration({
        firstDelay: 300,
        secondDelay: 1500,
        thirdDelay: 5000
    });
    ```
    NOTE: `@vaadin/flow-frontend` should eventually be changed to something like `@vaadin/vaadin` (out of scope of this task)
1. The Java API for configuring the loading indicator should remain working (when a UI instance is available). Eventually it should be deprecated in favor of a another Java API more consistent with `@PWA`, `@Theme` and other Java-based app shell config APIs (out of scope of this task).
1. There is no direct mapping between every request state and connection state: when any of the loading requests fails, the state changes to `CONNECTION_LOST`. When all loading requests succeed the state changes to `CONNECTED`. The first successful request recovers from `CONNECTION_LOST` to `CONNECTED`.

**Comment by joheriks** [comment]
It seems the following two sentences in point 4:

> When all loading requests succeed the state changes to `CONNECTED`.

and 

> The first successful request recovers from `CONNECTION_LOST` to `CONNECTED`.

are somewhat contradictory. The first implies keeping track of outstanding calls and only transitioning to `CONNECTED` when all have succeeded, whereas the other basically means "last state update wins". However, there is probably some context missing here.

**Comment by haijian-vaadin** [comment]
I think they are for 2 different state transitions. The first is for the transition from `LOADING` to `CONNECTED`, the second is for the transition from `CONNECTION_LOST` to `CONNECTED`.
