### ISSUE TITLE
Fusion: connect dependencies are not OSGi compatible

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#9350]
At least `spring-beans` (used package `org.springframework.beans.factory.annotation` ) has no OSGi compatible manifest.
I see a number of Spring deps with comment `<!--  Connect Dependencies -->` in the `flow-server` pom file which are potentially are not OSGi compatible.

In fact the functionality in `flow-server` which depends on Spring may not be in `flow-server` at all.
It should be moved into Spring add-on or another add-on which depends on Spring add-on.

**Comment by denis-anisimov** [comment]
May be I'm wrong and missing something but it looks like the package `com.vaadin.flow.server.connect` which contains classes with Spring dependencies is a "standalone" package which may be simply extracted from `flow-server` module to some other module without any additional action.
The package is quite isolated.
Spring is used only for the classes in this package and the only provided functionality is  a REST endpoint .

For now I will make Spring deps optional which will disable Connect endpoints and it won't work in OSGi.

**Comment by haijian-vaadin** [comment]
The endpoint code has been moved to `fusion-endpoint` module in https://github.com/vaadin/flow/pull/9499, so this ticket can now be closed.
