### ISSUE TITLE
Disallow application theme and theme class at the same time

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9370]
Follow up to https://github.com/vaadin/flow/pull/9349#discussion_r520502269 it should not be possible to have both `@Theme(value="my-theme", themeClass=Material.class)` at the same time. This should throw a meaningful exception during build time and explain that the application theme is always based on Lumo (or the parent theme defined in theme.json) and cannot be used with the theme class.

**Comment by caalador** [comment]
This will have an impact that you always need to add the lumo-theme dependency when having a string theme definition.

This is mostly an issue for our testing, but should perhaps get some consideration in any case as now we are always depending on Lumo.
