### ISSUE TITLE
Update the SVC master-details view template to use the new data APIs for v17 and v18

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9372]
This should be done for both the Java and the Java+HTML view templates (latter to be updated to lit by #9371)

**Comment by mshabarov** [comment]
The generated project still uses:

- org.vaadin.artur.helpers.LaunchUtil to launch a browser when the project starts
- org.vaadin.artur.helpers.CrudService which we might want to delete
- org.vaadin.artur.helpers.GridSorter which is a simple data class helper to provide data to Fusion grids
- org.vaadin.artur.helpers.PagingUtil to convert between offset,limit <-> pagenumber, page size
- org.vaadin.artur.helpers.CrudServiceDataProvider to connect a Flow Grid to a Spring Boot service
- import { showNotification } from '@vaadin/flow-frontend/a-notification'; to show simple notifications in Fusion

This should be fixed
