### ISSUE TITLE
Update all the css and theming output from start.vaadin.com view templates to the application theme feature

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9373]
The feature should be used for v19 once there is a prerelease of it available. It should be used for all the theming that can be done from the _Theme_ tab on the left side. For all different view template types.

To add separate CSS for the `Button` and `TextField` in the `themes/components` and the rest should go to the `global.css` file.

**Comment by mshabarov** [comment]
The checkbox can added providing an option to have the theme structure or not in generated project. Theme name input field can be added, or a theme name can be auto-generated depending on project name.

**Comment by Artur-** [comment]
A good starting point would be no extra options: always create a theme named from the project name

**Comment by Artur-** [comment]
Large part of the implementation needed is here https://github.com/vaadin/starter-wizard/pull/875

**Comment by pleku** [comment]
#9741 should be taken into account in the generated project by always having by minimum an empty `styles.css` there (or just put the global styles there).
