### ISSUE TITLE
Reintroduce OSGi documentation for v19

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9375]
It should be added back here https://github.com/vaadin/docs/tree/master/articles/flow, probably quite low in the menu listing, maybe before Advanced section (?) or after Spring and CDI topics.

Explain what does Vaadin OSGi support mean at the moment, explain the limitations (like no Fusion/TS views) and point to the OSGi project base as a starting point.

**Comment by denis-anisimov** [comment]
https://github.com/vaadin/docs/pull/40
