### ISSUE TITLE
Fix appshell annotation override

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#9379]
Theme annotation should now only be taken from the AppShellConfigurator.
At the moment the Visitor accepts Route endpoints and RouteLayouts which should
not be visited.

All tests testing theme should be migrated to only use AppShelConfigurator and the 
flow-themes system.property `vaadin.allow.appshell.annotations` should be removed so we fail
for all faulty annotations.

**Comment by pleku** [comment]
As we for now want to keep on eagerly failing when the annotation is in the wrong place, we should not change the scanning behavior (for now). But we should migrate our own tests to use the annotation on a appshellconfigurator instead of having a workaround in place for allowing it to be in route targets. So basically any place with `vaadin.allow.appshell.annotations` should be removed (due to themes) and tests fixed.

**Comment by caalador** [comment]
In `FrontendClassVisitor:`we have the Theme visitors:
```

        // Visitor for @Theme annotations in classes annotated with @Route
        themeRouteVisitor = new RepeatedAnnotationVisitor() {
            @Override
            public void visit(String name, Object value) {
                if (VALUE.equals(name)) {
                    endPoint.theme.themeName = (String)value;
                } else if (THEME_CLASS.equals(name)) {
                    endPoint.theme.themeClass = ((Type) value).getClassName();
                    children.add(endPoint.theme.themeClass);
                } else if (VARIANT.equals(name)) {
                    endPoint.theme.variant = value.toString();
                }
            }
        };
        // Visitor for @Theme annotations in classes extending RouterLayout
        themeLayoutVisitor = new RepeatedAnnotationVisitor() {
            @Override
            public void visit(String name, Object value) {
                if (VALUE.equals(name)) {
                    themeRouteVisitor.visit(name, value);
                } else if (THEME_CLASS.equals(name) && endPoint.theme.themeClass == null) {
                    themeRouteVisitor.visit(name, value);
                } else if (VARIANT.equals(name)
                        && endPoint.theme.variant.isEmpty()) {
                    themeRouteVisitor.visit(name, value);
                }
            }
        };
```

These should be checked that are they needed as we should only accept the Theme annotation on the `AppShellConfigurator` class
