### ISSUE TITLE
Getting this frontend/style related error with every Vaadin starter project and then I have to create it manually

### ISSUE THREAD

**Issue by javac9** [vaadin/flow#9385]
java.lang.IllegalStateException: 
  Failed to find the following css files in the `node_modules` or `C:\Users\user\PROJECTS\VAADIN-STARTERS\my-project\.\frontend` directory tree:
      - ./styles/views/form/form-view.css
  Check that they exist or are installed. If you use a custom directory for your resource files instead of the default `frontend` folder then make sure it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)

**Comment by caalador** [comment]
Which starter are we talking about. Any one gotten from [start.vaadin.com](https://start.vaadin.com/) or one of the hello world examples from the [start](https://vaadin.com/start) page?
Also which platform version is the project targetting?

**Comment by javac9** [comment]
It's about `one gotten from start.vaadin.com` -- custom tailored one.

**Comment by caalador** [comment]
Could you give details on the changes it contains that it fails, as starting from scratch will not result in much.

**Comment by javac9** [comment]
> Could you give details on the changes it contains that it fails, as starting from scratch will not result in much.

I just tried again with the same ZIP archive I still have from the last project that hat this issue but this time it went OK. However, `npm install` ended with errors.
- I unpacked the archive
- opened the project in IntelliJ IDEA
- it offered to run npm install
- that ended with this:

```
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" install --scripts-prepend-node-path=auto
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to
 the actual version of core-js@3.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! code ENOLOCAL
npm ERR! Could not install from "target\flow-frontend" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-11-13T07_01_10_896Z-debug.log

Process finished with exit code 1
```

I guess you can close this issue for now, should I be able to reproduce and mark the right steps, I will get back to it.

**Comment by caalador** [comment]
You can open up a new issue if this keeps happening.

The last npm issue sounds like the package.json has a probeml as target/flow-frontend shouldn't be mentioned anymore in any version. This should get fixed if you just delete package.json. (which combination gave this package.json?)
