### ISSUE TITLE
Fusion: Java API for customising the loading indicator and reconnection dialog should remain working

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#9401]
As a developer, I could use 

- `LoadingIndicatorConfiguration` to config `firstDelay`, `secondDelay`, `thirdDelay`, `applyDefaultTheme`

- `ReconnectDialogConfiguration` to config `dialogText`, `dialogTextGaveUp`, `reconnectAttempts`, `reconnectInterval`, `dialogGracePeriod`, and `dialogModal`

There are 2 different entry points for obtaining the `LoadingIndicatorConfiguration` and `ReconnectDialogConfiguration`
1. AppShellSettings
```
public class AppliShell implements AppShellConfigurator {

    @Override
    public void configurePage(AppShellSettings settings) {
        settings.getLoadingIndicatorConfiguration();
        settings.getReconnectDialogConfiguration();
    }
}
```
2. UI
 `UI.getCurrent().getLoadingIndicatorConfiguration()`, `UI.getCurrent().getReconnectDialogConfiguration`

All these configurations should work with the new offline visual indicator.

Part of #9203

**Comment by joheriks** [comment]
Note that `dialogModal` and `dialogGracePeriod` are no longer relevant, [and should be removed](#9508).
