### ISSUE TITLE
Fusion: TypeScript API for configuring the offline visual indicator

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#9402]
As a developer, I want to have some APIs for configuring the offline visual indicator, so that I can do customizations in a similar way as described in #9401.

Some example code, the API doesn't need to be the same

  ```ts
 import { setConnectionIndicatorConfiguration } from '@vaadin/flow-frontend/AppShell`;

    setConnectionIndicatorConfiguration({
        firstDelay: 300,
        secondDelay: 1500,
        thirdDelay: 5000
    });
```
    
NOTE: `@vaadin/flow-frontend` should eventually be changed to something like `@vaadin/vaadin` (out of scope of this task)

**Comment by joheriks** [comment]
Note that the API has been simplified: app developers will have access to the component (via `ConnectionIndicator.ts: getConnectionIndicator` and can modify any of its properties in their `frontend/index.ts`.
