### ISSUE TITLE
Jetty plugin not serving resources

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#9405]
The Jetty plugin when executing `mvn jetty:run` by default only serves `src/main/webapp` (also it seems `${project.output.directory}/webapp-tmp`) as static resources.

The app theme files are copied only `${project.build.outputDirectory}/META-INF/resources` which is served as per the Servlet 3.0 specification. 

A fix for running jetty should be found other than requiring adding the plugin configuration 
```
<webApp>
  <resourceBases> 
    <resourceBase>${project.build.outputDirectory}/META-INF/resources</resourceBase>
  </resourceBases>
</webApp>
```

**Comment by Legioth** [comment]
`src/main/webapp` is related to war files. `META/INF/resources` is related to jar files. Mixing those is not recommended.

I think there's already some other parts in `flow-maven-plugin` that takes into account the difference between jar and war packaging. This case might also need something similar?

**Comment by caalador** [comment]
But then Spring-boot serves `META-INF/resources` as static resources and we would want to have the `frontend/theme` static files copied under `src/main/webapp` either as they should be only in the build artifact.

**Comment by Legioth** [comment]
Spring Boot is typically jar, thus using `META-INF/resources` as expected.

I guess this is only a problem for development mode since we're already recommending to use `jetty:run-exploded` or such for production? How do other generated static resources work in dev mode?

**Comment by caalador** [comment]
I guess the best way to go is to have the static files go to `VAADIN/static` and serve them from there by ourselves as then we do not need to care about jar vs war.

**Comment by pleku** [comment]
Reopened to figure out how we can get any resources from the theme folder to work with using an url with path `"/theme/my-theme/something.png"` from Java or CSS regardless of the app packaging or used server.
