### ISSUE TITLE
Document using theme resources inside the theme folder

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9408]
- How to use a background image from the theme folder - both CSS & Java code
- How to change the font for your application

**Comment by knoobie** [comment]
I would like to see something like this documented as well (if needed; dunno if there is some kind of magic behind the scene that makes it harder to do so):

- using static resources from the domain root (e.g. serving static files from apache/nginx with img.domain.com or /img/..)
- using static resources from the context path (e.g. serving static files via spring from ./img/..)

Or is the url-rewrite only in use if the `url(*)` starts with `theme/my-theme`?

**Comment by pleku** [comment]
Good point @knoobie, thanks. We should document that the cases you pointed are possible and add tests that validate that it is so (#9430).

**Comment by tanbt** [comment]
Update in https://github.com/vaadin/docs/pull/41.

**Comment by tanbt** [comment]
vaadin/docs#41 is merged.
