### ISSUE TITLE
Spring starter broken when running in legacy V14 bootstrap mode

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#9412]
As a developer, I should be able to run a in Spring application in legacy V14 bootstrap by setting `vaadin.useDeprecatedV14Bootstrapping=true` to `application.properties`. However, the application starts but displays duplicated view and `vaadin-router` errors.

Steps to reproduce:
1. Checkout the Spring skeleton starter
1. Add `vaadin.useDeprecatedV14Bootstrapping=true` to `application.properties` and remove appshell files (`frontend/index.ts` and `frontend/index.html`).
1. Run the application via `spring-boot:run`.

The application looks as follows when loaded in the browser:
![Screenshot 2020-11-16 at 13 41 45](https://user-images.githubusercontent.com/2838896/99258104-bb37e880-2820-11eb-9525-0635b29395d0.png)

The problem seems to be that `prepare-frontend` writes `useDeprecatedV14Bootstrapping": false` into the token file `target/classes/META-INF/VAADIN/config/flow-build-info.json` causing conflicting configuration for the (forked) JVM process. Running `Application` class instead of `spring-boot:run` does not cause the same problem (unless `prepare-frontend` has been run previously, because then again the token file will override the Spring configuration).

Versions: V17, V18

**Comment by joheriks** [comment]
Workaround: the system property (`vaadin.useDeprecatedV14Bootstrapping`) can be passed to both the startup and fored JVM. E.g.:
```
mvn -Dspring-boot.jvmArguments="-Dvaadin.useDeprecatedV14Bootstrapping" -Dvaadin.useDeprecatedV14Bootstrapping spring-boot:run
```

**Comment by haijian-vaadin** [comment]
The `useDeprecatedV14Bootstrapping": false` maybe not needed to be written into the token file, check if we can remove that.
