### ISSUE TITLE
Fusion: connection state check going from offline to online

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#9424]
Currently, when receiving an online event, the connection state is updated from CONNECTION_LOST to CONNECTED (based on this [commit](https://github.com/vaadin/flow/commit/29fe11405c0c47051721df0010b00b4e7fbdc20b)). But it's better to also check the connection to the backend, similar to the heartbeat request or an HTTP head request.

The updated state chart would be sth like
![Vaadin online _ offline state diagram.png](https://images.zenhubusercontent.com/5e0dcbb3f28dea52f669852b/89282b2f-9697-4094-8d43-eb96123ed7fc)

**Comment by joheriks** [comment]
Looking over the diagram again, would it be more sensible to transition to `RECONNECTING` when receiving an `online` event while in `CONNECTION_LOST`. Like so:

![Vaadin online _ offline state diagram(1).png](https://images.zenhubusercontent.com/5cac4e8e039cc17631989ee5/eb2c0ee0-cd53-4d43-beb5-029217cde0bc)

The conceptual definition of `RECONNECTING` seems to fit the bill: we have lost the connection to the server, and should try to reconnect.

**Comment by haijian-vaadin** [comment]
Yep, good thinking, that makes more sense

**Comment by joheriks** [comment]
After #9427, the behavior will be slightly different:

<img width="816" alt="Vaadin online _ offline state diagram(2)" src="https://user-images.githubusercontent.com/2838896/100077424-010d3600-2e4b-11eb-9fe9-52a3017a09b5.png">
 
The main change is that the `RECONNECTING` states behaves differently depending on whether the Flow client has been loaded or not (i.e., whether the user has visited a server-side page). If loaded, the reconnect logic with multiple reconnect attempts (implemented in [DefaultConnectionStateHandler](https://github.com/vaadin/flow/blob/master/flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java)) will be used. On the other hand, if the user had only loaded client-side views, a simpler single-attempt reconnect logic (implemented in [Flow.ts](https://github.com/vaadin/flow/blob/master/flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts)) will be used. The former takes precedence whenever loaded, regardless of active view / route.
