### ISSUE TITLE
DX testing application theme for in project features

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9467]
Prerequisites:
- documentation is merged
- 6.0.0.alpha1 is available
- a branch of Flow based CRM using the correct version is available
- use cases to test are prepared and any needed extra documentation is available
- instructions for the test are prepared with links to docs and the test project (no demo)

Run the test with 1-2 Java developers and 1-2 designers.
Instead of filling the DX testing template, just link the tasks and test results (in google docs) here to this issue.

**Comment by caalador** [comment]
DX project creation to gitlab is under way.

**Comment by caalador** [comment]
DX application base now available at: https://gitlab.vaadin.com/mgrankvi/appthemedx/-/tree/master
Needs 9505 to be in before it works as it should.

**Comment by pleku** [comment]
The use cases to test are here https://docs.google.com/document/d/1ZBcoY4TbryBplisArgLechJ07Dat0uPb8ACS1LSO5-A/edit# it includes also one test for npm based assets.

**Comment by mshabarov** [comment]
Test results https://docs.google.com/document/d/1Zv0ncYdTC4UMURgYqiSZtEuxS_jB7rymF9J-0MROJbU/edit?usp=sharing
