### ISSUE TITLE
Demo for importing resources from npm modules

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#9477]
Show how to use the assets (other than CSS) like fonts and images from npm dependency to the theme. How should it work:
1. Install the dependency with npm
2. Add an "assets" block to `theme.json`, and then map the assets from the dependency to local URIs:

```json
"assets": {
"@foo/bar": {
"images/**": "foobar/images"
}
```
The first part is the module name, the second is the source folder inside the module and the last part is how it is referred inside the application theme.

3. Use the assets with a local path as defined in `theme.json`:

```
background-image:
url('foobar/images/logo.svg');
```

or

```java
Image logo = new Image("foobar/images/logo.svg", "");
```

**Comment by taefi** [comment]
This demo is implemented in https://github.com/vaadin/application-theme-demo

**Comment by taefi** [comment]
I closed this issue as the implementation to showcase the usage is done. Although, when the `VAADIN/static/...` issue for URLs is resolved, the code in this demo should be updated.
