### ISSUE TITLE
AppTheme doesn't work on FireFox

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#9488]
App theme fails to load on firefox as new CSSStyleSheet causes a TypeError: Illegal constructor
This is because at the moment constructable stylesheets are only implemented in chrome.

The feature is on the road map for FireFox, but until it's there we need to add a polyfill for the feature.

**Comment by knoobie** [comment]
Firefox Bugtracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1520690

![image](https://user-images.githubusercontent.com/3968629/100199985-48a0ca00-2efe-11eb-866a-0eed46db0ae0.png)
Source: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#constructable_stylesheets
