### ISSUE TITLE
Make it easier to see the relevant part of a navigation error

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#9493]
When navigating to a view that throws an exception in its constructor, I'm presented with a basic HTML page that shows the exception message (and also the stacktrace if production mode is not enabled).

![Screenshot 2020-11-25 at 13 24 05](https://user-images.githubusercontent.com/1294657/100221799-db069500-2f21-11eb-902d-2bc17ae65747.png)

An experienced developer looking at this message probably knows that the most relevant piece of information is the last part of the stacktrace and the end of the error message. A less experienced developer might not be aware of this gotcha and instead focus on the beginning of the message that conveys little useful information (e.g. `Error creating bean with name 'com.example.application.views.helloworld.HelloWorldView'`).

One suggestion for how to make the message easier to understand is to bold the last segment of the message to make it stand out.

![Screenshot 2020-11-25 at 13 25 37](https://user-images.githubusercontent.com/1294657/100221752-c924f200-2f21-11eb-97a7-cd0cd78924f7.png)

**Comment by tarekoraby** [comment]
How about making it even easier by only mentioning the root cause in an h3 or h4 element?

![image](https://user-images.githubusercontent.com/42799254/140477262-6f284ad0-3549-4f51-a5bf-54b7eaddd496.png)

**Comment by tarekoraby** [comment]
@Legioth if the aforementioned approach is fine with you, I can make a PR. (my approach has the nice benefit of being cleaner to implement than the one that requires highlighting part of the text).
