### ISSUE TITLE
the connection state indicator is not visible in pure Fusion apps

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9506]
When building an app with Fusion I expect the connection state indicator to be visible even if I do not add any server-side views, so that the UX is consistent between Fusion / Flow / hybrid Vaadin apps. With Flow 6.0.pr-9427-SNAPSHOT this is not the case.

Steps to reproduce:
 - create a TS + HTML app with start.vaadin.com
 - override the versions of Vaadin and Flow to 19.0-SNAPSHOT and 6.0.pr-9427-SNAPSHOT
 - remove the `Flow` import and the use of server-side routes in `index.ts`:
    ```typescript
    import { Flow } from '@vaadin/flow-frontend/Flow';
    
    const { serverSideRoutes } = new Flow({
      imports: () => import('../target/frontend/generated-flow-imports'),
    });
    ```
 - start the app
 - turn on the offline more in the browser dev tools
 - see that there is no connection state indicator

**Comment by vlukashov** [comment]
Workaround: explicitly import the connection indicator code into `index.ts`:
```ts
import {getConnectionIndicator} from '@vaadin/flow-frontend/ConnectionIndicator';
getConnectionIndicator();
```

**Comment by joheriks** [comment]
The indicator will now be added if either `Flow` is imported, or via `Connect` if endpoints are imported to any of the Fusion views. If neither is true, user will need to explicitly import `@vaadin/flow-frontend/ConnectionIndicator` and call `getConnectionIndicator()` to add it to the DOM.

**Comment by vlukashov** [comment]
This is apparently still an issue with V19 + Flow 6.0.offline-SNAPSHOT. See details in https://vaadin.slack.com/archives/CDNTYMS9H/p1607947620446000

**Comment by vlukashov** [comment]
Am I missing something or was this issues re-introduced?
![Screen Recording 2021-02-16 at 05 18 PM](https://user-images.githubusercontent.com/22416150/108083420-b717a300-707b-11eb-84ce-e64cd151d09b.gif)

1. download a Vaadin 19 (Fusion) app from start.vaadin.com with Master-detail and About views
2. start the app and turn on the offline mode in the browser dev tools
3. see that there is no 'connection lost' banner until a user action that triggers an endpoint request

**Comment by haijian-vaadin** [comment]
yes, I noticed the same and made a [PR](https://github.com/vaadin/flow/pull/10046) already
