### ISSUE TITLE
PR #9451 introduces a regression that breaks vaadin-board-flow ITs

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#9514]
`vaadin-flow-components` snapshot is broken for several hours https://bender.vaadin.com/viewType.html?buildTypeId=FlowComponents_Snapshot&tab=buildTypeStatusDiv&branch_VaadinFlowComponents=%3Cdefault%3E 

Doing a git bisect, I found that the culprit is the commit 18ee55985eaafba645535560d0ee7954406e2aa3

How to reproduce:
- checkout `vaadin-flow-components` 
- do a clean of the project  `mvn clean`
- run vaadin-board ITs by running  `mvn verify -am -B -pl vaadin-board-flow-parent/vaadin-board-flow-integration-tests -Dtest=none` 
- during the `flow:build-frontend` phase, webpack hangs

The problem seems to be in the following lines of the `target/frontend/generated-flow-imports.js`
```
import $css_0 from 'Frontend/rowtypes.css';
addCssBlock(`<custom-style><style>${$css_0}</style></custom-style>`);
import $css_1 from 'Frontend/styles.css';
addCssBlock(`<custom-style><style>${$css_1}</style></custom-style>`);
```
by commenting them webpack execution finishes.

Probably it happens in all projects having a `@CssImport`  annotation

**Comment by caalador** [comment]
Couldn't fail it anymore locally or on the CI system.
Has been fixed by #9505 but the 6.0-SNAPSHOT build failed in the evening so the fix didn't come in before the nightly run.
