### ISSUE TITLE
VaadinServletContext::getAttribute(Class, Supplier) set the default value 

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#9517]
The method `VaadinContext::getAttribute(Class<T> type, Supplier<T> defaultValueSupplier) `  sets the value rom the supplier instead just using the value to return.
It has some sense though I don't have a strong opinion about this.

The issue is: javadoc of `VaadinContext::getAttribute(Class, Supplier)` doesn't mention this.
So either the method should not set the attribute but just return the value from the supplier (then I'm not sure why supplier is needed at all?) or this behavior should be documented.

In case the current behavior of `getAttribute` is changed (so that it doesn't set the value anymore) the API of `VaadinContext`  should be extended so that it provides a method to atomically execute a command.
Currently `getAttribute` allows to check the value presence and set the value atomically (under the context lock).
If behavior is changed then there will be no way to execute such operation properly (it will be thread unsafe).

**Comment by Legioth** [comment]
I would suggest clarifying the documentation for two reasons:
* It's preferred to avoid changing behaviour
* Being able to do an atomic update might be important in some use cases in case the thread that first populates the value also needs to do some additional initialization tasks.

**Comment by denis-anisimov** [comment]
I agree
