### ISSUE TITLE
Binding to a double using a TS form does not work

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#9521]
### Minimal reproducible example
1. Go to https://start.vaadin.com/?preset=fusion
2. Change view type to "master-detail" and download
3. Change the type of `phone` in `Person.java` to `double`
4. Remove the data generation code from `DateGenerator`
5. Run the project and try to set the value of phone to `12.2`.

### Expected behavior
You can type "12.2" in the field

### Actual behavior
When you type "12." the value changes to "12" and it is impossible to input a decimal number.

### Versions:
    - Vaadin / Flow version: 18rc1

**Comment by Artur-** [comment]
Seemingly the only way to enter "12.2" in the field is to paste it, that works fine

**Comment by Feuerwerk** [comment]
I have this problem only with Firefox (currently using v83.0), with Chrome (currently using v87.0.4280.67) it works as intended

**Comment by haijian-vaadin** [comment]
Having a special check on the number value in the field strategy.
