### ISSUE TITLE
Create a test for checking the CSS loading order

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#9529]
Crete an IT test in Flow checking the CSS loading order:

1. Lumo styles
   (2. Parent theme)
2. Current theme
   (4. App-specific bundled css added via @CssImport)
   (5. App-specific unbundled css added via @Stylesheet
   (6. Page.addStylesheet)

**Comment by tanbt** [comment]
I found that styles from `@StyleSheet` have a higher priority than from `addStyleSheet()`.
If that is correct, then the issue description should switch the orders of items (5) and (6) (?).
