### ISSUE TITLE
logout() should clear the CSRF token even if the logout call to the backend fails

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9537]
As a user I expect that after I logged out of the app offline, I would not be able to make authenticated requests to the backend when coming back online, so that I can trust the "Logout" button. With Vaadin 19.0-SNAPSHOT / Flow 6.0.pr-9427-SNAPSHOT this is not the case.

**Steps to reproduce:**
 - check out the `offline-demo` branch of the Vaadin CRM app from https://github.com/vaadin-learning-center/crm-tutorial-typescript/tree/offline-demo
 - remove the workaround in `frontend/auth.ts` (keep only `await logoutImpl();`):
    ```ts
    (window as any).Vaadin.TypeScript.csrfToken = 'logged-out/offline';
    try {
      await logoutImpl();
    } catch {
      // whatever
    }
    ```
 - remove the app's own auth check from `offlineSyncToastHandler` (in `frontend/utils/offline-sync-toast-handler.ts`)
    ```ts
    if (!isLoggedIn()) {
      submitter.keepDeferredCallInTheQueue();
      return;
    }
    ```
 - open the app and login
 - go offline
 - make a deferrable call
 - logout() (see that the `/logout` network request fails and `logout()` throws)
 - manually change the URL to `/`
 - go online (see that deferred requests are submitted even though you have not logged in)

**Expected behavior:**
 - logout() does not throw even if the `/logout` network request fails
 - logout() clears the CSRF token even if the `/logout` network request fails
 - deferred request submission fails (as unauthorized) when going online after having logged out offline

**Comment by vlukashov** [comment]
NOTE: the CSRF token is stored in the workbox cache inside the `index.html` document. Removing it from `window.Vaadin.TypeScript.csrfToken` at the run time does not clear it from the cache. Therefore after an offline logout, restarting the app from the cache again would mean the token is restored and the user is effectively logged in again.

**Comment by haijian-vaadin** [comment]
- `logout()` should clear the runtime.

Two possible ways to clear the token from cache.
  - clear the persisted CSRF Token.  
  - Not having the CSRF token in the cache.

**Comment by joheriks** [comment]
The proposed PR identifies the request for `index.html` to be originating from the service worker by inspecting the `Referer` header for `sw.js`, and if so, excludes the CSRF token initialization.

**Comment by Legioth** [comment]
A user will still be logged in after a failed logout request because the actual state of being logged in is determined by the contents of the server-side HTTP session that corresponds to the session id in the user's session cookie. Discarding the CSRF token will only affect the current tab whereas a newly opened tab can still use the existing session cookie and receive a new CSRF token from the server. Discarding session cookies from the browser would not be practical because of the `HttpOnly` attribute.

The fix to this issue does thus only give the appearance of being properly logged out, even though the the user is actually still logged in through their retained session cookie.

**Comment by vlukashov** [comment]
> A user will still be logged in after a failed logout request because the actual state of being logged in is determined by the contents of the server-side HTTP session that corresponds to the session id in the user's session cookie. Discarding the CSRF token will only affect the current tab whereas a newly opened tab can still use the existing session cookie and receive a valid CSRF token from the server. Discarding session cookies from the browser would not be practical because of the `HttpOnly` attribute.
> 
> The fix to this issue does thus only give the appearance of being properly logged out, even though the the user is actually still logged in through their retained session cookie.

I've moved this into a separate issue: https://github.com/vaadin/flow/issues/9789
