### ISSUE TITLE
Deferrable calls should try reaching the backend when connection is lost, but the browser is online

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9538]
As a developer I expect a deferrable endpoint call to try to reach the backend before giving up and placing the call into the 'deferred calls queue' when the browser believes it's online, even if the Vaadin app is in the 'connection lost' state, so that making a deferrable call would re-establish the connection if the backend was temporarily down but it up again at the time of the call (a server restart). In that way deferrable calls should behave in the same way as regular endpoint calls. With Vaadin 19.0-SNAPSHOT / Flow 6.0.pr-9427-SNAPSHOT this is not the case.

**Steps to reproduce:**
 - check out the `offline-demo` branch of the Vaadin CRM app from https://github.com/vaadin-learning-center/crm-tutorial-typescript/tree/offline-demo
 - login
 - shut down the backend
 - make a deferrable call (see that the connection state changes to 'connection lost')
 - start the backend
 - make another deferrable call (see that the connection state remains 'connection lost')
 - make a regular endpoint call (see that the connection is re-established and all deferred calls are submitted)

**Expected behavior:**
 - making a deferrable call should re-establish the connection

**Comment by haijian-vaadin** [comment]
`deferrableCall` in Connect.ts should check the `navigator.online` state, instead of our connection state, as long as the browser is online, it should make the call.

**Comment by vlukashov** [comment]
`@Deferrable` endpoints are excluded from the Vaadin 19 release.
