### ISSUE TITLE
Deferrable calls should be submitted automatically after connection is re-established

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9539]
As a developer I expect deferrable calls to be submitted automatically after the app gets 'connected', also in the case when the 'connection lost' state is caused by a failed endpoint call (the  backend going down), and the 'connected' state is caused by a successful endpoint call, so that the deferred calls submission behavior is consistent with that for the browser `online' / 'offline' events. With Vaadin 19.0-SNAPSHOT / Flow 6.0.pr-9427-SNAPSHOT this is not the case.

**Steps to reproduce:**
 - check out the `offline-demo` branch of the Vaadin CRM app from https://github.com/vaadin-learning-center/crm-tutorial-typescript/tree/offline-demo
 - login
 - shut down the backend
 - make a deferrable call (see that the connection state changes to 'connection lost')
 - start the backend
 - make a regular endpoint call (see that the connection is re-established)
 - check the deferred calls queue in the IndexedDB (see that the deferred call is still there)
 - go offline and then online
 - see that the deferred calls are submitted

**Expected behavior:**
 - the queued deferred calls are submitted immediately after the connection state changes to 'connected', without waiting for the 'online' browser event

**Comment by haijian-vaadin** [comment]
Replace `self.addEventListener('online', this.submitDeferredCalls);` in `Connect.ts` with `$wnd.Vaadin.connectionState.addStateChangeListener(this.submitDeferredCalls)`

**Comment by vlukashov** [comment]
`@Deferrable` endpoints are excluded from the Vaadin 19 release.
