### ISSUE TITLE
add an entry for `@Deferred` endpoints in the Vaadin usage statistics

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9540]
When an app has one or more @Deferred endpoints, it should add a separate entry about that into the usage statistics data like so:
![Screenshot 2020-11-28 at 23 22 20](https://user-images.githubusercontent.com/22416150/100629417-f1ea2480-3331-11eb-8f63-f0fb5356c6eb.png)

name: endpoint/@Deferred
version: [same as the Flow version]

**Comment by haijian-vaadin** [comment]
Add an import line in the generated files if they contain deferred endpoints. When importing a file that calls deferred calls.
