### ISSUE TITLE
Connection state indicator should be visible when the vaadin login overlay is open

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9541]
As a user I expect the Vaadin loading / connection state indicator to have a higher z-index than Vaadin overlays, so that the indicator is visible also when the vaadin-login overlay is open.  With Vaadin 19.0-SNAPSHOT / Flow 6.0.pr-9427-SNAPSHOT this is not the case.

**Steps to reproduce:**
 - check out the `offline-demo` branch of the Vaadin CRM app from https://github.com/vaadin-learning-center/crm-tutorial-typescript/tree/offline-demo
 - open the app (see the login screen)
 - go offline
 - see the connection state indicator flashing briefly and disappearing

**Expected behavior:**
 - the connection state indicator saying "connection lost" should be visible on top the scree as in any other view of the app

**Comment by haijian-vaadin** [comment]
z-index: 251; for v-status-message in <vaadin-connection-indicator>
