### ISSUE TITLE
Consider adding an alias for the generated frontend assets

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#9544]
Refactoring a frontend project could be easier if we aliased the generated folder with webpack https://webpack.js.org/configuration/resolve/

That way, you could write
`import Company from 'Generated/com/vaadin/tutorial/crm/backend/entity/Company';`

instead of 
`import Company from '../../../../../generated/com/vaadin/tutorial/crm/backend/entity/Company';`

Which would also not break if you move the file around.

**Comment by platosha** [comment]
Related: https://github.com/vaadin/flow/issues/7758

**Comment by vlukashov** [comment]
Another option is to use `~` as the alias:
```
import Company from '~/generated/com/vaadin/tutorial/crm/backend/entity/Company';
```
details: https://medium.com/@davidmieloch/tilde-paths-with-eslint-typescript-and-webpack-971f694c9b15

**Comment by haijian-vaadin** [comment]
Yet another one option https://codeandsuch.github.io/webpack-aliases-typescript/

**Comment by haijian-vaadin** [comment]
Frist Investigate which option would work for the IDE.

**Comment by Artur-** [comment]
I would avoid `~` for two reasons:
1. It is hard to type (at least on some keyboards)
2. `~` means home and here we are not referring to the user's home nor the project's home but the frontend folder

Not sure why it should be `Generated/` either, why not `generated/`?

**Comment by haijian-vaadin** [comment]
Theming could probably benefit from this as well.

**Comment by platosha** [comment]
Tried both the path aliases and the package symlink approaches. The auto-complete and auto-import behaviour in VSCode and IntelliJ IDEA is the same between both approaches, so “IDE support” refers to both of them below.

The approach | Example auto-import path | IDE support | Notes
--- | --- | --- | ---
No alias (current behaviour) | `../../generated/MyEndpoint` | ✅ | Traversing levels of hierarchy, as outlined in this issue.
Package alias (as suggested in #7758) | `@vaadin/generated/MyEndpoint` | ❌ | Auto-import refers to the relative path instead, unless `generated` is moved out of `frontend`.  Requires FS symlink.
Prefixed alias for the generated directory (as in the issue description) | `Generated/MyEndpoint` | ✅ | 
Prefixed frontend directory alias | `Frontend/generated/MyEndpoint` | ✅ | Also allows simple references for other `frontend` exports.
Bare root to frontend directory alias  | `/generated/MyEndpoint` | ✅ | See above.

The package alias approach has clear downsides here.

I'd personally prefer aliasing the `Frontend`:
- Simple references for other frontend things, e. g., `import { router } from 'Frontend/index';`
- Helps to avoid maintaining multiple specific aliases
- The webpack documentation also [has examples using capital case aliases](https://v4.webpack.js.org/configuration/resolve/#resolvealias). This is probably to minimise the risk of confusion with npm package names, which must start with a lowercase letter or `@scope-name`.
- We already have the `Frontend` alias in generated webpack config for internal use. Adding it to `tsconfig.json` while implementing this issue would also align aliases in both places, which is nice to have.

**Comment by Artur-** [comment]
Why should the alias be Capitalized instead of matching the folder name, i.e. `frontend/generated` ?

**Comment by vlukashov** [comment]
This is probably a late comment, but just noticed today that NuxtJS is using `~` as the alias to the source root: https://nuxtjs.org/docs/2.x/directory-structure/assets
