### ISSUE TITLE
Bug/Improvement: Disabling component/element/field is too strong 

### ISSUE THREAD

**Issue by netbeansuser2019** [vaadin/flow#9563]
Dear Vaadin,

It seems there is so different handling of "enable/disable" flag as in legacy Vaadin version.
But it seems that such current behavior is not so correct.

a) why disabling of field's remove invalid-looks (such "red background" one)
b) why disabling of field's hides set error message
c) why disabling of component block showing of "title" so hard to signal to user what is possibly
wrong

Even overriding of onEnabledStateChanged(boolean enabled) does not help as field has possibly some "extra parts" that it is not controlled (or maybe I do know about such way) and share disable state from field's parent.

So suggested solution:
At least any possibility to realized a-c) or in worst case to realize c)

**Comment by netbeansuser2019** [comment]
#8514

**Comment by netbeansuser2019** [comment]
@pleku 
@mshabarov 

If you read a description you have it all and just usage of any of your examples from vaadin side can lead to this.
There is nothing custom, but it seems that it is Vaadin team standard way to closing issues without action.
Frankly speaking you should valued that anybody take a time a report a issues to be improved your product.

a) why disabling of field's remove invalid-looks (such "red background" one)
- just use any form field and make it invalid (so set any value that it is invalid for any vaadin validator) 
- set that disabled
b) why disabling of field's hides set error message
- follow a)
- ensure that it is set any error any message 
c) why disabling of component block showing of "title" so hard to signal to user what is possibly
wrong
- set attribute title

**Comment by pleku** [comment]
Ok, so you've created a new issue and copied the same things here without providing more details. I've locked the other issue so we can continue here. Like I said there:

> Frankly speaking you should valued that anybody take a time a report a issues to be improved your product.

Yes we do value good input. But we also ask you to value our time and report issues in a manner that does not waste anybody's time - by providing examples with code and screenshots when necessary, specially when it is about something that is very hard to be described in written format in understandable English. For example:

> why disabling of field's remove invalid-looks (such "red background" one)

is close to gibberish. The following details would be more interesting to be reproduced in a code example so we can be sure that we're on the same page as a code example leaves very little room for interpretation:
>just use any form field and make it invalid (so set any value that it is invalid for any vaadin validator)
set that disabled
b) why disabling of field's hides set error message
follow a)
ensure that it is set any error any message
c) why disabling of component block showing of "title" so hard to signal to user what is possibly
wrong
set attribute title

**Comment by taefi** [comment]
Hi @netbeansuser2019, 

I want to discuss a very general usage of disabling a field, that should clear the error message and also the red background and anything related to that validation failed before disabling the field. 

In most use cases, when you provide an option for not filling some fields by disabling them, why should the user still get errors for the invalid values of disabled fields? 

Imagine you provide a RadioGroup to the user to select between 2 options in a form, for filling a set of fields for option1 or another set of fields for option two. The user starts filling the fields related to option1. In the middle of the way, the user changes his/her mind and wants to try the second option from the RadioGroup and fill the other set of fields (related to option2). When the user filled out the whole set of fields related to option2 correctly,  why we should bother showing errors about invalid values of disabled fields related to option1?

When a user has no control over entering new values in a field, what is the purpose of showing validation messages or a red background? What should the user do in that situation?

**Comment by Legioth** [comment]
As an addition to the above, I would in general suggest that UI components that should still be active although not modifiable by the user should be configured as readonly rather than as disabled.

**Comment by netbeansuser2019** [comment]
@pleku 

If I provide a code you could not use it due to legal point of view. In ideal world I will be happy to do so, but due to legal boundaries I cannot.

**Comment by netbeansuser2019** [comment]
@taefi 

One example when user has not rights to change that due to ACL, but it can see it. He/she can still rights to report data integrity issue.

**Comment by netbeansuser2019** [comment]
@Legioth well there was no other way then do that this way, but imaging prior version of Vaadin if I remember right throws an Exception if you set value from server side so there was demand of usage of disabled state. So any migration work demand to rework that to readonly state. But my humble understanding is that it should not be lost information like validation message or simple fact that even pure HTML title attribute was vanished when it is disabled.

**Comment by pleku** [comment]
Ok. So being able to show: invalid state, error messages and title (aka tooltip) while the component is disabled is not the preferred default end user experience that one would imagine. For instance MDN says for `disabled` attribute that:
> The Boolean disabled attribute, when present, makes the element not mutable, focusable, or even submitted with the form. The user can neither edit nor focus on the control, nor its form control descendants. If the disabled attribute is specified on a form control, the element and its form control descendants do not participate in constraint validation. Often browsers grey out such controls and it won't receive any browsing events, like mouse clicks or focus-related ones.

So based on "do not participate in constrain validation" it would imply to me that there should not be any error state either. Simply the "disabled" component should IMO just show that there is an component there, but the user cannot interact or influence it.

> but imaging prior version of Vaadin if I remember right throws an Exception if you set value from server side so there was demand of usage of disabled state. So any migration work demand to rework that to readonly state

Since Vaadin 10, the `field.setReadOnly(true)` should still allow changing the value with application code on the server side. I think it was considered a design flaw in the earlier versions that we fixed (while it was a breaking change to do so, it was still for the better).

I'm not sure if there is still something needed here. This might be valid for being able to decide "which component features show/work while the component is still disabled" but that is kind of component specific, and not just something that the framework can handle if the component (in the browser) automatically disables some features when it gets the attribute.

**Comment by netbeansuser2019** [comment]
It is up to you, i have already rewrite that by readonly way. 
I think that all should be documented or at least mentioned in migration guide if it is not there yet.

Even if you think it is not right I am still thinking that "title" should not be ignored e.g. like in pure HTML <input disabled title="Lorem ipsum">.

**Comment by pleku** [comment]
The specifics of read-only and disabled state are mentioned in the migration docs, https://vaadin.com/docs-beta/v14/flow/migration/5-components/#setreadonlyboolean-readonly-is-component-specific-and-works-differently and I don't at the moment what would be needed to add there to be more specific. The migration docs will be revised before the nextLTS and should be more concrete about differences when coming from Vaadin 8 which is EOL in a year or so.
