### ISSUE TITLE
Expected behaviour or not: If a component, declared as a class field, is added multiple times to another components, it will only appear within the last component?

### ISSUE THREAD

**Issue by javac9** [vaadin/flow#9578]
Version: 18.0.1

I've added a component (declared as a class field) to the more than one other components. It appears, however, that only the last `add` action is respected and the previous ones are discarded.

Is this a normal behaviour? I guess we shouldn't be doing this at all, or at least we should not declare such a component as a class field (in my case, it was by accident, I planned to remove the old `add` once I have the component in the new location, which was accidentally above the old location).

**Comment by Legioth** [comment]
This works as expected. A component instance can only have one parent component. When it's added as a child of one component, it's automatically removed from any previous parent.
