### ISSUE TITLE
Support making reusable ApplicationTheme

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#9585]
The feature for supporting reusable application theme should be added. This would mean creating a jar that only contains theme resources and a java class with Npm resource annotations if needed.

For an example see https://github.com/Artur-/theme-example/tree/reusable

There should be a test module that applies the theme from the jar file.

**Comment by pleku** [comment]
#### Acceptance Criteria
- [ ] Adding a module with a theme that has some css and resources in src/main/resources/META-INF/resources/themes/reusable-theme/ and it is used by another module

**Comment by tanbt** [comment]
When packaging themes to JAR file, themes from (at least) two locations:
* `src/main/resources/META-INF/resources/themes/` 
* `frontend/themes/`
should be packaged, together with the related Java files which contains `@NpmPackage`.
