### ISSUE TITLE
One should not have to restart app when adding a new css file to app theme

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9594]
Currently this is needed when adding new files - we should just make webpack detect new files out-of-the-box so no restart is needed for that.

### Acceptance Criteria: 

To have test(s) in the live-reload module to cover the following scenarios:
- Adding a new CSS file
- Adding a static resource like a Font and address it in CSS files 
- Support for deleting an already existing theme file

Related issue: https://github.com/vaadin/flow/issues/9596

**Comment by caalador** [comment]
To be noted for the adding of new files:
https://github.com/webpack/webpack-dev-server/issues/1006#issuecomment-320974577
