### ISSUE TITLE
Rename the application theme generated file to theme-name.generated.js

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#9595]
The generated theme file should also have a header informing that this is a generated file.

Note that the application plugin resolves the theme name from the theme-generates.js file import statement and this should be updated at to correctly parse the name in `application-theme-plugin.js : nameRegex`

**Comment by Artur-** [comment]
Other generated files are placed in `frontend/generated`, would that be better?

**Comment by caalador** [comment]
I guess the main problem with moving the file is that the paths for the imports will either get full paths or complex relative paths.
So before a bigger refactoring on the paths we will go with the file rename.

**Comment by pleku** [comment]
#### Acceptance Criteria
- [ ] Update the plugin ^ to use the new name & bump the plugin version
- [ ] Update the documentation to refer to the new file name with a new screenshot on the theme resources

**Comment by pleku** [comment]
> Other generated files are placed in frontend/generated, would that be better?

> I guess the main problem with moving the file is that the paths for the imports will either get full paths or complex relative paths.
So before a bigger refactoring on the paths we will go with the file rename.

Moving the file #9678
