### ISSUE TITLE
Deleting an app theme file fails the webpack compilation

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9596]
E.g. deleting a component css file will fail the compilation with an error of missing the file as pointed by `my-theme.js`.

**Comment by mshabarov** [comment]
Also if you create a new file -> delete it -> create a new file with the same name, then webpack compilation fails. Might be related to webpack file caching. Delete event can be caught in `theme-live-reload-plugin` and we could tell webpack to clean the cache or somehow workaround it.

**Comment by mshabarov** [comment]
No good solution found on how to workaround the file/folders delete errors so far.
It's proposed to mention this limitation in docs, stating:

_Files/folders inside `frontend/themes/my-theme` folder might be deleted during application development/theming. Please notice that you may get webpack errors in the application logs, as follows:
`Error: ENOENT: no such file or directory, open 'your-project-root-path/frontend/themes/my-theme/global.css'`
or even see a webpack error pop up on your application page.
This is a known limitation and you need to refresh the browser page manually, if you see webpack error pop up, and merely ignore  this error in logs._

**Comment by mshabarov** [comment]
Closed with a note in the theme documentation https://github.com/vaadin/docs/blob/master/articles/theming/application-theme.asciidoc#use-application-themes
