### ISSUE TITLE
Adopt app theme to base/skeleton starters

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9597]
For example https://github.com/vaadin/skeleton-starter-flow-cdi/tree/master/frontend/styles should be updated to use an app theme and the readme link to the new documentation. This should be done for
- [x] vanilla starter
- [x] cdi starter
- [x] osgi starter

(Spring starter is covered by #9373)

**Comment by tanbt** [comment]
Starter `RawProjectProvider` downloads raw base/skeleton projects from "vaadin.com/vaadincom/start-service...".
