### ISSUE TITLE
Fusion: replace the connect package name 

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#9603]
Now the endpoint related code has been moved from flow-server to fusion-endpoint. We could at the same time update the package name, e.g. replace `flow` with `fusion`, `connect` with `endpoint`

Note that we shouldn't introduce breaking change, instead the current package name `connect` should be deprecated, it can be removed in the next major release (v20?)

**Comment by Haprog** [comment]
`vaadin.flow.server.connect` still seems to be under `vaadin.flow`. Should there instead be `vaadin.fusion` where it would go into?

**Comment by haijian-vaadin** [comment]
Good point, I updated the description

**Comment by haijian-vaadin** [comment]
Done in https://github.com/vaadin/fusion/issues/3.
