### ISSUE TITLE
Offline: compressed files served uncompressed

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#9606]
### Steps to reproduce

- Download any starter app from `start.vaadin.com`.
- Update to snapshot versions listed below.
- Enable `production` profile.
- Launch the app and open in Chrome and inspect network traffic
- Note that several requests, e.g. for bundles, are done to the server with `Accept-Encoding: gzip, deflate, br`.
- Note that the reponse headers (missing `Content-Encoding`) and file sizes show that e.g. `vaadin-bundle-14ea03a7f3e3dd0923ea.cache.js` is served uncompressed, even though `vaadin-bundle-14ea03a7f3e3dd0923ea.cache.js.gz` exists on the server.

### Expected behavior

Resources are served gzip-compressed.

### Versions
Vaadin: `19.0-SNAPSHOT` (2020-12-08)
Flow: `6.0.offline-SNAPSHOT` (2020-12-08)

**Comment by haijian-vaadin** [comment]
there is a check in the `ResponseWriter` that needs to be fixed.

**Comment by joheriks** [comment]
Also needs add a production-mode IT that checks that the `Content-Encoding` header (and preferably content) of a requested file matches the expected compression (`gzip`).
