### ISSUE TITLE
Throw a meaningful exception when no custom theme folder created

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#9610]
### Description of the bug / feature
It's not clear enough what is happening and how to fix the error when webpack compilation fails on App startup due to absence of `my-theme` folder, whenever the `@Theme("my-theme")` annotation is present. 
Webpack shows:
```
ERROR in ../target/flow-frontend/theme/theme-generated.js
Module not found: Error: Can't resolve 'theme/my-theme/my-theme.js' in '/Users/mikhail/workspace/vaadin/application-theme-dx/appthemedx-master/target/flow-frontend/theme'
```
and the browser console shows: `Uncaught (in promise) Error: Cannot find module 'theme/my-theme/my-theme.js'`.

Although the App Theme feature experienced developers may quickly recognise the issue, let's explicitly tell the developer what to do by throwing the exception immediately with a meaningful message what happened and how to fix it.

### Minimal reproducible example
1. Download app project https://gitlab.vaadin.com/mgrankvi/appthemedx/-/tree/master
2. Add `@Theme("my-theme")` on `Application` class
3. Add `theme` folder to `frontend` folder
4. Run the app `mvn spring-boot:run` and open the page localhost:8080.
5. See webpack error and error message in log.
### Expected behavior
Application logs the explanatory message what the developer did wrong
### Actual behavior
Webpack fails and shows low-level error message
### Versions:
    - Vaadin / Flow version: flow `6.0.0.alpha1`
    - Java version: 8
    - OS version: mac os
    - Browser version (if applicable): chrome 87
    - Application Server (if applicable): spring-boot app
    - IDE (if applicable): IDEA ultimate

**Comment by pleku** [comment]
The idea would be to not create a folder automatically as it would result into other problems when the user has made a typo or just forgot to include the dependency to a reusable theme. Instead the build should fail with a clear error that says something meaningful for the user like: _Discovered @Theme("foobar") annotation but no folder "frontend/themes/foobar/" present in the project or available or inside a jar dependency for the app. Check if you forgot to create the folder or have typo in the theme or folder name "foobar"._
