### ISSUE TITLE
Rename the App Theme root folder to themes

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#9611]
As the `frontend/theme` folder may contain a multiple themes and the current rules are to use the `components` (in plural) folder for components custom styles, it makes sense to rename `theme` to `themes` so as to make the things consistent.

**Comment by pleku** [comment]
#### Acceptance Criteria
- [ ] Use the folder name in Java code: regex, comments, variables, error messages, tests 
- [ ] Use the folder name in webpack.generated.js, theme-loader.js 
- [ ] Use the folder name in the documentation
- [ ] Use the folder name in the demo
