### ISSUE TITLE
Add Application Theme tests for Dev Mode

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#9628]
Current Application Theme tests cover only the production mode in module `flow-test-themes-npm`, and, thus, some app theme changes (at least those for `/theme/my-theme/` requests handling in `DevModeHandler`) are not covered.
The tests should be added for the Dev Mode by making another maven module, or by making a double pom-file.

Ideally, it should cover these changes https://github.com/vaadin/flow/pull/9590 https://github.com/vaadin/flow/issues/9594 https://github.com/vaadin/flow/issues/9596

**Comment by caalador** [comment]
The `test-live-reload` module would seem like the most likely place to add the tests at as we are adding and removing files.

**Comment by caalador** [comment]
Ticket has already been done. DevMode tests are in `flow-tests/test-application-theme/test-theme-live-reload`
