### ISSUE TITLE
Vaadin loading indicator changes the colour with global styles

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#9630]
### Description of the bug / feature
Vaadin loading indicator changes its colour to the custom colour defined in `global.css` file within `frontend/themes/my-theme` with a delay of 0.5-1 sec. Initially it shows the default colour (blue) and then turns to custom colour.

Possible reason for that is that the default colour is included in the first response that the browser gets, and then it starts to load the first JS bundle, and that bundle contains the actual application theme (colour). For the time the browser loads, parses, and executes the first JS bundle, the default colour (blue) is used.

The possible fix is that the theme’s global style sheet should be injected already in the first HTML response that the browser gets.

This issue reproduces with `@CssImport` annotation either, so it's not limited to Application Theme feature.

### Minimal reproducible example
1. Download app example from here https://gitlab.vaadin.com/mgrankvi/appthemedx/-/tree/master
2. Create `theme/my-theme/global.css` file in `frontend` folder and place the following CSS there:
```css
html, :host {
--lumo-primary-color: red;
--lumo-primary-text-color: red;
}
```
3. Add `@Theme("my-theme")` annotation to `Application` class.
4. Run the application.
5. Notice the loading indicator colour change from blue to red during page loading.

Video recording https://drive.google.com/file/d/1YSAu3EhUEhzfSq1vIJajOJwGGtSJl5Ax/view?usp=sharing
### Expected behavior
Loading indicator has a red colour all over the loading process.
### Actual behavior
Loading indicator changes its colour.
### Versions:
    - Vaadin / Flow version: 6.0.0.alpha1
    - Java version: 8
    - OS version: mac OS
    - Browser version (if applicable): Firefox 83.0 (64-bit)
    - Application Server (if applicable): Spring-boot
    - IDE (if applicable): Intellij IDEA

**Comment by knoobie** [comment]
Reminds me of this old bug https://github.com/vaadin/flow/issues/6824

**Comment by pleku** [comment]
I'm not sure if it is feasible to inline the global css or to link it on the initial page, at least we want to keep it so that the global css is not being reloaded each time but can be cached. This requires a bit of investigation on what would be the alternatives.

One option is to just document this as a known limitation and provide an example of how to get the default loading indicator styles overridden for the initial page response.

**Comment by tanbt** [comment]
> inline the global css 

Is this idea about reading global.css (the new name is styles.css) content and somehow inject to index.html? Sounds like a not-small workaround to me: need to read the current theme and get the loading indicator styles from styles.css, then inject into `frontend/index.html` or `target/index.html`.

> link it on the initial page

This requires the current styles.css file has to be configured for public access or it can be copied to a public resource folder, before injecting the `<link>` of that stylesheet into `frontend/index.html` or `target/index.html`.

Both workaround solutions are not trivial. I suggest to fix the loading indicator in a more proper way.
Added a docs for this case.

**Comment by caalador** [comment]
This has been moved to done so I'm closing the issue.
