### ISSUE TITLE
CSSImport with "themeFor" for own component not working

### ISSUE THREAD

**Issue by egloffmark** [vaadin/flow#9637]
Dear all I am using Vaadin Flow v 17.0.9. I created an own component "HelloComponent" based on an existing Div component and like to apply a CSS for my component via the `@CSSImport`. It is not working, the css is ignored and also no shadow root with style element get created.

**Java Classes**

```
@Route("/")
@Theme(value = Lumo.class)
@CssImport(value = "./styles/hello-component.css", themeFor = "hello-component")
public class MainView extends VerticalLayout {
	
	private static final long serialVersionUID = 1L;
	
	@PostConstruct
	private void init() {
		setSizeFull();
		add(new HelloComponent());
	}
}

@Tag("hello-component")
public class HelloComponent extends Div {

	private static final long serialVersionUID = 1L;
	
	public HelloComponent() {
		setSizeFull();
		setText("Text");
	}
}
```
**Style** "frontend/styles/hello-component.css"
```
:host  {
	color: red;
}
```
Generated HTML Code in Browser
```
<hello-component style="width: 100%; height: 100%;">Text</hello-component>

```

**Comment by jcgueriaud1** [comment]
Hi,
There are some answers in the forum:
https://vaadin.com/forum/thread/18494899/create-own-component-with-css-stylesheet

**Comment by denis-anisimov** [comment]
Closing this since the ticket is not an issue.
The explanation is provided via the link in the comment above.
