### ISSUE TITLE
Add new modules to application theme demo to use a reusable parent theme and application specific theme

### ISSUE THREAD

**Issue by taefi** [vaadin/flow#9655]
- To add a new module to demonstrate how to create a reusable theme that can be packaged as jar
- To add a new module to demonstrate how to reuse a theme as parent (either packaged as jar or existing in another `themes/some-parent` directory)

**Comment by pleku** [comment]
Waiting for a good example of parent - app theme use case from @rolfsmeds.

**Comment by rolfsmeds** [comment]
Ok who am I kidding, I don't have time to come up with anything proper before the holidays.

How about we just use the theme defined for the DX tests as parent theme, and then apply some sub-theme styles on top:

1. Some Lumo overrides for app-specific branding:
```
html, :host {
    --lumo-primary-color: green;
    --lumo-primary-text-color: green;
}
```

2. Component styling overrides to vaadin-text-field:
```
[part="input-field"] {
    border: 1px solid green;
}
```

3. And a different font file, e.g. https://fonts.google.com/specimen/JetBrains+Mono
Declared in document.css and applied with `--lumo-font-family: 'Jetbrains Mono';`
