### ISSUE TITLE
Can't resolve 'themes/my-theme/my-theme.generated.js'

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#9658]
### Description of the bug / feature
Webpack shows a compiler error when you add `@Theme("my-theme")`

### Minimal reproducible example
1. https://start.vaadin.com/?preset=prerelease&dl
2. Add `@com.vaadin.flow.theme.Theme("my-theme")` to `Application.java`

### Expected behavior
The project compiles without warnings or errors

### Actual behavior
```
ERROR in ../target/flow-frontend/theme/theme-generated.js
Module not found: Error: Can't resolve 'themes/my-theme/my-theme.generated.js' in '/.../projectfolder/target/flow-frontend/theme'
 @ ../target/flow-frontend/theme/theme-generated.js 1:0-80 2:26-37
 @ ../target/frontend/generated-flow-imports.js
Child html-webpack-plugin for "index.html":
```

### Versions:
    - Vaadin / Flow version: 19 alpha 1
    - Java version: 15
    - OS version: mac

**Comment by mshabarov** [comment]
The root cause is the same as in https://github.com/vaadin/flow/issues/9610

**Comment by pleku** [comment]
Merging to #9610 as they're basically the same issue.
