### ISSUE TITLE
Expose connectionIndicator as constant instead of getter function

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#9671]
Instead of accessing the connection via a getter, it should be exposed as a constant. So as a developer, I could configure it as follows in `index.ts`:

```
import {connectionIndicator} from '@vaadin/flow-frontend';
// ...
connectionIndicator.setPosition(TOP);
connectionIndicator.setPosition(BOTTOM);
```

**Comment by haijian-vaadin** [comment]
Regarding this, do we want to export a new constant `connectionIndicator` or provide  TS definition for `window.Vaadin` and let user use `window.vaadin.connectionIndicator` instead?  ping @Legioth ?
