### ISSUE TITLE
Unable to use client-side binder on ComboBox backed by an object array

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#9675]
Vaadin version: 18

I have:
```
<vaadin-combo-box
  label="Company"
  .items=${this.companies}
  item-label-path="name"
  item-id-path="id"
  item-value-path="id"
  ...=${field(model.companyId)}
></vaadin-combo-box>
```

Bound to an array of objects looking like this:
```
[{id: 1, name: "Path-Way Electronics", employeeIds: Array(6)}]
```

The ComboBox displays the `id` as the selected value. When opening the dropdown, I see the company names correctly. If I try to select one, it fails on a validator that assumes the value is a number (it tries to set the name as the value).

If I use dev tools to set the CB value to a valid id, the selection shows the company name correctly.

The combo-box binding does not take the object paths into consideration when binding. https://github.com/vaadin/flow/blob/fafc0f21a693a13a95f48c1ca307de3a548275c9/flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts#L65

**Comment by haijian-vaadin** [comment]
One idea is that we take the `item-value-path` attribute presence into account for binding.

The second idea is that use option in the directive to tell to use value or selectedItem for binding.

**Comment by haijian-vaadin** [comment]
Note, this has an impact on our best practices of using DTO, a DTO normally references another object by id rather than the whole enity.

**Comment by platosha** [comment]
Closing in favour of vaadin/fusion#151
