### ISSUE TITLE
Change theme-generated.js to be TypeScript

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#9678]
### Description of the bug / feature
When you try
```
import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';
applyTheme(document)
```
in a TypeScript file, you get an error
```
Could not find a declaration file for module '@vaadin/flow-frontend/themes/theme-generated'.
```

### Minimal reproducible example
Add the mentioned code to a V19 alpha 1 project

### Expected behavior
The import should just work

### Actual behavior
The declaration error is thrown

### Versions:
    - Vaadin / Flow version:19 alpha 1

**Comment by pleku** [comment]
The documentation should be fixed too not show any imports for `.js` files (if there are any).
