### ISSUE TITLE
Extract plugin code to a separate module

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#9685]
For a much simplified maintenance of the Gradle plugin, it would be great to have the Maven plugin implementation, but without the Maven-related code.

## Current situation

Currently the code from the `flow-maven-plugin` module needs to be carefully ported to the Gradle plugin on every major Vaadin release, replacing Maven-specific bits with Gradle-specific bits. That is laborous and error-prone.

## Expected situation

As much code as possible should be extracted to a new module, e.g. `flow-plugin-base` or similar. That module will not depend on any Maven-related classes, but would implement as much as possible of the plugin functionality.

For example the code from BuildFrontendMojo would be ported to BuildFrontend. The BuildFrontend will then accept a Maven-independent configuration for all values and all stuff that's currently provided by Maven (e.g. list of runtime jars); the class will simply execute the build-frontend task. The Maven plugin would then simply define the BuildFrontendMojo and would simply configure and call the BuildFrontend class. Gradle plugin will then be able to do the very same thing easily - define a BuildFrontendTask, which would simply configure and call the BuildFrontend class.

Would be good to target this for Vaadin 19 since Vaadin 19 support is broken in Gradle plugin atm.

**Comment by stbischof** [comment]
@mvysny it would be great to have this! so we can build our own plugin

@maho7791 could be the start-point for generate!

**Comment by stbischof** [comment]
I just started working on this.

https://github.com/bipolis/flow/tree/plugin

my goal is to have an cli-plugin

**Comment by mvysny** [comment]
@stbischof I'm not sure whether cli will work, since the Vaadin plugin needs a list of jars from the classpath, in order to discover all `@NpmPackage`-annotated classes, in order to generate package.json (and possibly other).

**Comment by stbischof** [comment]
I will find out what is needed. May add an -cp attribute to list all jars and an -o for output.

This message was just to let you know that someone is also working on this.
