### ISSUE TITLE
Move theme-generated.js from the target/flow-frontend/themes folder to frontend/generated

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9687]
Follow up to #9678, this should be done so that the active theme can be imported in a Fusion similarly regardless of the origin of the theme: in-project `frontend/themes/my-theme` would be imported the same way when it is inside a `.jar`.

**Comment by caalador** [comment]
Should it be better to have it in `target/flow-frontend/themes/` as then it's definable as `@vaadin/flow-frontend/themes/my-theme/my-theme.generated.js`

**Comment by pleku** [comment]
Yes most likely the desired option for now would be to just have to do 
```ts
import { theme } from './generated/theme';

@customElement('main-layout')
export class MainLayout extends LitElement {
  static styles = [theme];
}
```
and then there is no need to worry about what the currently active theme actually is.

**Comment by pleku** [comment]
Related discussion in `https://vaadin.slack.com/archives/CDNTYMS9H/p1608641893104400?thread_ts=1608219489.062900&cid=CDNTYMS9H` and this issues should match bullet 1) meaning the file is moved to `generated/theme.js`. 2) and 3) are done in #9684

**Comment by caalador** [comment]
This has a problem when we have a parent theme also. the parent theme can not also be generated/theme.js are we talking about the same generated file as the main entrypoint for theme is target/flow-frontend/themes/theme-generated.js and the XYZ.generated.js file in the respective theme folders define the theme imports which could be n´moved to under target somewhere so they wouldn't be seen.

**Comment by Artur-** [comment]
`generated/theme.js` is just an import for the active theme
