### ISSUE TITLE
Flaky Test

### ISSUE THREAD

**Issue by shaker-project** [vaadin/flow#9689]
### Description of the bug / feature

Hello, we are a group of researchers interested in understanding methods to reduce costs associated with Test Flakiness [1]. We developed an approach to detect flaky tests, dubbed Shaker [2]. Shaker spawns stressor tasks in the running environment (e.g., tasks that consume lots of cpu or memory) to identify if perturbations can make tests fail.

We ran Shaker on flow project and found the following likely flaky tests.

* vaadinServlet_forDifferentRequests_shouldHaveCorrectResponse - failed 1 times in 12 reruns.
* should_notGenerateOpenApi_when_EndpointIsNotUsed - failed 1 times in 12 reruns.

We sincerely hope that this can be useful information and look forward to hearing back.
 
[Denini](https://github.com/denini08), [Leopoldo](https://github.com/leopoldomt) and [Marcelo](https://github.com/damorim).

[1] https://hackernoon.com/flaky-tests-a-war-that-never-ends-9aa32fdef359

[2] D. Silva, L. Teixeira and M. d’Amorim, "Shake It! Detecting Flaky Tests Caused by Concurrency with Shaker," 2020 IEEE International Conference on Software Maintenance and Evolution (ICSME), Adelaide, Australia, 2020, pp. 301-311, https://ieeexplore.ieee.org/document/9240694/.

### Versions:
    - Vaadin / Flow version: 5.0.2
    - Java version: 8
    - OS version: Ubuntu 18.04

**Comment by denis-anisimov** [comment]
There are two test methods in the desription.
Could you please clarify which class has the methods ?

**Comment by shaker-project** [comment]
*  `vaadinServlet_forDifferentRequests_shouldHaveCorrectResponse`. class: `com.vaadin.flow.server.DevModeHandlerTest`
* `should_notGenerateOpenApi_when_EndpointIsNotUsed`. class: `com.vaadin.flow.server.startup.DevModeInitializerTest`

**Comment by denis-anisimov** [comment]
Thank you.

**Comment by joheriks** [comment]
These flakiness issues are fixed in master by df7a5f80b8c77f5d1505ecd6aea7e1adf70141bf, 9e8a0618dbc7ffec22b8fff49a520b846f7f2c49 and 86efdc6a54196914982bcad2a72e8649fe4338d2.

**Comment by joheriks** [comment]
Cherry-pick of the applicable changes for 5.0 [here](9748). Closing this ticket.

**Comment by joheriks** [comment]
@shaker-project Thanks for identifying the tests and the Shaker tool sounds interesting. Is it available somewhere to try out?

**Comment by denini08** [comment]
Hi @joheriks , we are working to make a release of shake easy to use for everyone, when we finish we will share with you. The repository link is https://github.com/STAR-RG/shaker
