### ISSUE TITLE
Fusion: investigate how to split Fusion and Flow

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#9692]
Split Fusion and Flow has been a recurring topic from time to time, but not really much has been done. Let's try to make it happen by starting from this investigation ticket. 

The expected outcome:
A document about the findings and proposal(s). No need to touch the code, we will decide what to do based on the findings.

Fusion codes are in 4 modules in Flow:
1. fusion-endpoint, which is pure fusion, should be very easy to split to a new repo.
2. flow-client, should investigate to see if the fusion code could be extracted to a different module e.g. `fusion-client`, so that fusion-client could depend on flow-client, but flow-client shouldn't depend on fusion-client.
3. flow-server, should investigate to see if the fusion code could be extracted to a different module e.g. `fusion-server`, so that fusion-server could depend on flow-server, but flow-server shouldn't depend on fusion-server.
4. `flow-maven-plugin` -> `vaadin-maven-plugin` that then uses a `SPI` architecture to allow Flow and Fusion to add its own hooks into the various phases needed during the build. The same underlying logic would then also be shared with e.g. a Gradle plugin and the dev mode that runs inside the application server.

The investigation is time-boxed to **3** days.

**Comment by Haprog** [comment]
As part of the investigation I think we should come up with a list of (possible) benefits of doing the splitting. If there is no compelling benefits, then why would it be done?

**Comment by haijian-vaadin** [comment]
> As part of the investigation I think we should come up with a list of (possible) benefits of doing the splitting. If there is no compelling benefits, then why would it be done?

Good question, the benefits could be that:
1. We have move Fusion to a separate repo
2. People who don't use Fusion features at all could exclude the Fusion dependencies.

**Comment by Haprog** [comment]
> 1. We have move Fusion to a separate repo

This isn't a benefit in itself. Who does this help and why?

Probably it would be good because of:
1. (developer) marketing reasons
2. Easier to find the source and issues for Fusion when it's in the repo name
3. Clearer split of code ownership between Flow and Fusion teams

Also possible negative side effects of the splitting actions should be considered if we can think of some (pros / cons).

**Comment by haijian-vaadin** [comment]
Good point, I updated the my previous comment.

**Comment by Artur-** [comment]
Cons: 
1. Moving Fusion to a separate repository means separate versions and a lot more syncing problems. We should rather move e.g. github.com/vaadin/spring into this repository and sync versions than move stuff out
2. As Fusion still would depend on Flow, you would only be able to use Flow without Fusion and not the other way around. This can already be done today by excluding `fusion-endpoint`
3. (The obvious) Doing this always means not doing something else

So many parts are common like `spring`, project setup, bootstrapping, routing, ... Feels really unclear to me how moving some Fusion code to a separate repository would help

**Comment by gilberto-torrezan** [comment]
Note: this ticket is part of https://github.com/vaadin/platform/issues/2039

**Comment by haijian-vaadin** [comment]
The research result is available at https://docs.google.com/document/d/1UC-H6J1VmXOdzACWIwenFhP4yOEfjCpMeMiY3UL_Od4/edit#
