### ISSUE TITLE
Add a general description about theme hierarchy / approaches into docs

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#9700]
Extend the existing docs for theming with a general information on the theming hierarchy and what are the existing approaches to create a theme in Vaadin applications. 
It should cover the new application theme feature (including parent and reusable theme), and the old approaches (`@CssImport`, `@Stylesheet`, custom theme).
Visual diagram would be also a good option to give the readers a better picture of the whole theme feature in Vaadin.

**Comment by pleku** [comment]
Agreed for now to include the explanation to https://github.com/vaadin/docs/blob/master/articles/theming/overview.asciidoc for the _concepts_ part to introduce the theme annotation & folder that is used when theming an application and also mention reusing and inheriting a theme.
