### ISSUE TITLE
DX testing app theme part 2

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9703]
- Npm based resources
- Reusable theming
  - Parent theme

Instructions (DX TEST part 2):
https://docs.google.com/document/d/1ZBcoY4TbryBplisArgLechJ07Dat0uPb8ACS1LSO5-A/edit#heading=h.idve3edpi4ja

**Comment by taefi** [comment]
This task fulfilled with 6 Java developers with different levels of experience in styling, NPM and the new theming mechanism. The detailed description for all 6 testers and also a summary is available in the following doc:

https://docs.google.com/document/d/1lwl5BT0lN-VQB5LwK_KvTVzrw8hX_tpNQHj5BW1moRI
