### ISSUE TITLE
2.4 nightly validation build for Windows is always failing with PwaTestIT.testPwaResources

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#9704]
https://bender.vaadin.com/viewLog.html?buildId=205662&buildTypeId=Flow_Flow24_Nightly_ValidationWithWindows

Same for 2.5 https://bender.vaadin.com/viewType.html?buildTypeId=Flow_Flow25_Nightly_ValidationWithWindows
Seem a global problem.

**Comment by mshabarov** [comment]
Solved by updating Chrome (browser/webdriver) version on Windows agent.
