### ISSUE TITLE
[BUG] Error: While showing Image from local Hard Drive .

### ISSUE THREAD

**Issue by prashant7526** [vaadin/flow#9711]
**Describe the bug**
We have the situation: where we are showing the pictures in a gallery. These pictures are loading from the local resource (hard drive). 
We are using code from the example given on Vaadin Documentation. [Dynamic Content](https://vaadin.com/docs/flow/advanced/tutorial-dynamic-content.html). 

We have two cases and both cases two different errors:
**To Reproduce:: Case 1:**
```
final Image img =new Image(this.getStreamResource(file.getAbsolutePath()), "Couldn't load image :(");

private StreamResource getStreamResource(final String fileName)
	{
		return new StreamResource("MyResourceName", () -> {
			try
			{
				return new FileInputStream(fileName);
			}
			catch(final Exception e)
			{
				e.printStackTrace();
			}
			return null;
		});
	}
```
**Expected behaviour**
**_Above code results in "Pool Maxed out" or "sorry, too many clients already" (If gallery is refreshed too many times by different user. Pool just keeps on increasing till reach its limit.)_**

**To Reproduce:: Case 2:**
```
final Image img =new Image(this.getStreamResource(file.getAbsolutePath()), "Couldn't load image :(");

private StreamResource getStreamResource(final String fileName)
	{
		return new StreamResource("MyResourceName", () -> {
			try
			{
				this.getInputStream(fileName);
			}
			catch(final Exception e)
			{
				e.printStackTrace();
			}
			return null;
		});
	}

private FileInputStream getInputStream(final String fileName) throws IOException
	{
		try(FileInputStream fileInputStream = new FileInputStream(new File(fileName)))
		{
			return fileInputStream;
		}
		catch(final Exception exception)
		{
			exception.getMessage(),
		}
		return null;
	}
```

**Expected behaviour**
**_Above code results in "Resource Closed"_**

**Additional context**
Is it our way of reading/loading pictures is wrong? Or Is this the correct way of doing it? 
**_### NOTE: We also have the issue with "Pool Maxed out" when allowing users to upload multiple photos._** :( 

Thank you in advance.

**Comment by caalador** [comment]
Isn't `sorry, too many clients already` an exception for PostgreSQL?
Also `Pool Maxed out` seems to be a JDBC exception. 

So in this case it would seem the exception is somewhere else where you are using a database that just gets too many connections.

In the second case the `getStreamResource`  factory method will always return null.

**Comment by prashant7526** [comment]
Caalador, Sir I agree with you. These are PostgreSQL, but as I said these errors coming while Refreshing this page. That is wired. My application use c3p0 and framework maintaining all by itself I mean connection pool internally. This is the page where we are seeing these issues.

**Comment by prashant7526** [comment]
Also when I check in PGadmin. When we are running the application no connection we see in Dashboard except for one. 
But when the gallery load we see connection increasing:

"SHOW TRANSACTION ISOLATION LEVEL"

**Comment by caalador** [comment]
I can't see anything that would cause that effect with the stream resource.
As we don't have the full class code we can only guess on reasons, but do you load the files to show from the database?
Nothing in Image nor StreamResource will use DB connections so there must be some other reason in the view why it uses up all connections without releasing them on reload.

**Comment by prashant7526** [comment]
Hi all,

This is not an invalid question. But I would say, I cannot explain. if you guys want me to send you a class. I can send it. But this problem still exists. The only thing helping me is: **unreturnedConnectionTimeout**

**Comment by pleku** [comment]
@prashant7526 the labels just mean that this instead of valid issue for the framework, it seems like this was not valid, but instead an question (please don't read too much into those).

In case there is a problem with the framework, please create a new issue that **contains the full steps and code** for us to reproduce the issue so we may investigate and fix it. I'm sure you can understand that prefer spending our time on concrete issues. In case you need hands on help, I would recommend trying the forum, discord channel or commercial support instead.

**Comment by prashant7526** [comment]
So, I got the issue but I don't know how to solve it. 

The method:  getStreamResource(String fileName); When called once creates one pool, and when called in the loop as much as the number of images it creates the pool as the number of images. 

If I remove this single method. This page doesn't create any pool. So any help now? Nothing else is creating a pool and making too many connections in this file.


[GalleryView.txt](https://github.com/vaadin/flow/files/5842969/GalleryView.txt)

**Comment by prashant7526** [comment]
Please help.

**Comment by caalador** [comment]
As Pekka said this is not an issue with the framework as the exception is for the database.
I did take a quick look and you are doing `galleryPathCommentList = HsqlUtil.INSTANCE.fetchByPicturePath(file.getAbsolutePath());` for each file and then a couple of other extra fetches so you should make certain that the HsqlUtil doesn't keep the connections open or better yet do the comment fetch as a single batch for all the files.

**Comment by prashant7526** [comment]
Even if we are not using that line (which tried), we removed all the db code from this file. And left with just picking up files and populating on the layout. In that case, the moment we populate the image in layout that is where pool start to make.
`this.imgGalleryThumbsHorizontalLayout.add(customVerticalLayout);`
if you will comment above line the pool will not get created.

**New flow that we've done** 
Now we have hashamap that hold String and StreamResource, we are populating that hashmap the load of the file once and doesn't change until user doean't click on upload (another view)/delete, if user clicked on these we are clearing the hashmap and loading again.

Now for example you load the file and parent window populated the Hashmap. when you come on this gallery firast time it is  creating pool. And after then if you keep on coming back on this without having hashmap refreshed the pool will not create. (As I said Hashmap is not loading on this view that is now another class).

But as soon as you make any change and hashmap gets clear and reload with data, you come to this page again first time after reload opf hashmap and it will create pool again and second time it won't.

What is happening?

**Comment by prashant7526** [comment]
This is our new changed file.

[GalleryView.txt](https://github.com/vaadin/flow/files/5855365/GalleryView.txt)

**Comment by prashant7526** [comment]
> As Pekka said this is not an issue with the framework as the exception is for the database.
> I did take a quick look and you are doing `galleryPathCommentList = HsqlUtil.INSTANCE.fetchByPicturePath(file.getAbsolutePath());` for each file and then a couple of other extra fetches so you should make certain that the HsqlUtil doesn't keep the connections open or better yet do the comment fetch as a single batch for all the files.

These connections are getting closed. We have checked. When we remove all the DB code from this file when loading the page. Pool gets created.
But, when we comment this line `this.imgGalleryThumbsHorizontalLayout.add(customVerticalLayout);` pool doedn't get created

**Comment by prashant7526** [comment]
It seems to me` StreamResource with Layout and image (the combination).` Is having an issue.

**Comment by caalador** [comment]
What you should do is, pick a clean hello world starter from https://vaadin.com/start and create the gallery on that without any database things only the loading of the images without any comments or other DB things.
Then add some db things until something breaks. If it's a framework problem create a new issue with the minimal code that depicts the exception and steps to reproduce. 

If you can't reproduce the problem you should go to the forum, discord channel or commercial support as this is now about a full application.

**Comment by prashant7526** [comment]
> What you should do is, pick a clean hello world starter from https://vaadin.com/start and create the gallery on that without any database things only the loading of the images without any comments or other DB things.
> Then add some db things until something breaks. If it's a framework problem create a new issue with the minimal code that depicts the exception and steps to reproduce.
> 
> If you can't reproduce the problem you should go to the forum, discord channel or commercial support as this is now about a full application.

OK, I will do it today. And will let you guys know.

**Comment by prashant7526** [comment]
Thanks, it is a framework issue. We got it. Have to contact the vendor.
