### ISSUE TITLE
npm install fails because of npm 7

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#9714]
Vaadin 18.0.2, start.vaadin.com fusion project. 

The current pnpm setup doesn't support an easy way of adding npm dependencies (you have to install them with a very specific version of pnpm with `~/.vaadin/node_modules/pnpm/bin/pnpm.js i foo`), so I want to disable pnpm. 

I disabled pnpm in `application.properties` with `vaadin.pnpm.enable=false`

Running the app now fails on npm dependency resolution:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: no-name@undefined
npm ERR! Found: typescript@4.0.3
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"4.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"^2.7 || ^3" from awesome-typescript-loader@5.2.1
npm ERR! node_modules/awesome-typescript-loader
npm ERR!   dev awesome-typescript-loader@"5.2.1" from the root project
```

**Comment by marcushellberg** [comment]
I suppose this has to do with `awesome-ts-loader` which hasn't been updated in 2 years, is archived in GitHub, and isn't aware of TS4

**Comment by vlukashov** [comment]
There is indeed a problem with using an outdated `awesome-typescript-loader`, but apparently it's not critical as I am not able to reproduce this failure:

1. create a new Vaadin 18 / Fusion project with [https://start.vaadin.com/?preset=fusion](https://start.vaadin.com/?preset=fusion)
   (or with Vaadin CLI: `npx @vaadin/cli init --fusion npm-install-test`)
2. switch from `pnpm` to `npm`
   ```bash
   echo "vaadin.pnpm.enable = false" >> src/main/resources/application.properties
   ```
3. run `mvn` to start the project in the dev mode
   See that Vaadin runs npm to install frontend dependencies, and that the installation completes successfully.
   
   NOTE: npm does log a _warning_ related to `awesome-typescript-loader` requiring an old TS version, but that does not fail the installation:
   ```
   npm WARN awesome-typescript-loader@5.2.1 requires a peer of typescript@^2.7 || ^3 but none is installed. You must install peer dependencies yourself.
   ```
4. open the app in the browser at [http://localhost:8080/](http://localhost:8080/)

I've tried this on macOS 10.14.6 with Node v14.15.0 and npm 6.14.8. Not sure if JDK and Maven versions matter.
What versions of Node / npm do you have installed?
Could you please try to run the steps above and see if you can consistently reproduce the issue?

**Comment by caalador** [comment]
Isn't the problem here that Marcus wants to use version 4.0.3 of typescript in the project?

**Comment by emarc** [comment]
This seems to depend on node/npm version; it **fails on node 15**, works on 14.

Some ppl might have 15 and run into this, and those ppl might spend too long to figure it out, bugging others in the process, like... a friend of mine. ;-)

**Comment by haijian-vaadin** [comment]
I installed node 15 locally (node v15.5.0 and npm 7.3.0), tried a fusion project with a hello world, about, and master-detail view in start.vaadin.com, but seems I couldn't reproduce the problem. Could you @marcushellberg or @emarc help to attach the project you were using for us to reproduce the problem?  Or does the problem depend on sth else as well?

**Comment by emarc** [comment]
You can use the project from https://start.vaadin.com/?preset=fusion as-is.
Note that `mvn` works, but `npm install` does not.

Also worth noting that `pnpm` probably (?) does not have this problem – just in case it's aliased or something.

**Comment by haijian-vaadin** [comment]
thanks for the update @emarc. Now I'm able to repdocue. running `npm install` is fine with node `14.5.4` but fails with `15.5.1`.

**Comment by marcushellberg** [comment]
It's worth noting that pnpm doesn't work either, because Vaadin requires/assumes an ancient version of it. If you have installed the latest current version of pnmp and use it to install dependencies, it will fail.

**Comment by haijian-vaadin** [comment]
I got error
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: no-name@undefined
npm ERR! Found: webpack@5.13.0
npm ERR! node_modules/webpack
npm ERR!   peer webpack@"^4.0.0 || ^5.0.0" from html-webpack-plugin@4.5.1
npm ERR!   node_modules/html-webpack-plugin
npm ERR!     peer html-webpack-plugin@"^3.0.0 || ^4.0.0" from script-ext-html-webpack-plugin@2.1.4
npm ERR!     node_modules/script-ext-html-webpack-plugin
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0" from script-ext-html-webpack-plugin@2.1.4
npm ERR! node_modules/script-ext-html-webpack-plugin
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/haijian/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/haijian/.npm/_logs/2021-01-12T12_12_35_479Z-debug.log
```
Two things to check
1. why it tries to use webpack 5
2. Looks like the `script-ext-html-webpack-plugin` is outdated as well. We can see if it's really needed and if we can replace it with sth else.

**Comment by vlukashov** [comment]
The failures on Node 15 may be related to the changes in handling of peer dependencies introduces in npm 7 that comes with Node 15: https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/

If that's the case, Vaadin's "npm mode" is generally incompatible with Node 15, and this is what this GH issue is about.

**Comment by vlukashov** [comment]
Node 15 / npm 7 was released on October 20th, 2020 and has the end-of-life on June 1st, 2021.
All Vaadin versions actively maintained in the 2020-10-20 - 2021-06-01 time frame should support it: V14.x, V18 and V19.
