### ISSUE TITLE
OSGi in V19

### ISSUE THREAD

**Issue by QNENet** [vaadin/flow#9732]
After having checked out the proposed documentation for OSGi in V19 I have been moved to make some suggestions about V19 and OSGi.

I have created a demo version of my approach to v14 compatibility mode (attached) and a youtube video which might help in understanding what I am talking about.

The readme of the demo has many comments and thoughts which I hope might be helpful.

[qneweb14c-demo.zip](https://github.com/vaadin/flow/files/5753550/qneweb14c-demo.zip)

https://youtu.be/SapZPFP-qsE

**Comment by QNENet** [comment]
It has been suggested that I put the some of the content of the readme.md as an issue comment to save opening the demo zip so here it is.

# qneweb14c
QNE Web project using Vaadin 14 Compatability mode.

##Thoughts
Using OSGi/Karaf as I have shown, it becomes easy to have real time addition and removal of views just
by starting and stopping bundles.
 
 A publish/subscribe bus makes this a simple exercise.

#Comments
I have had a look at (what I think) is the proposed V19 OSGi documentation on the Flow repo.

It does not provide much more info than the V14 docs.

For Vaadin to be taken seriously by OSGi developers they should not be told to go and sort out the
dependencies to get the system running and the Vaadin Starter approach in my opinion is not
suitable for OSGi purposes.

A Vaadin version of my qwebfeatures feature module should be a part of the Vaadin code and 
kept up to date.

The code provided is part of the front end of my project which I do not intend to open source
until the community network I am building gains the desired "network effect".

I "humbly" suggest that vaadin produce a V19 OSGi demo based on my code's fit with Karaf.

Instead of the factory/view setup in my V14c code, of course PROTOTYPE bundles should be used for views.

If you are interested, I am availabe to discuss any of the details of my code and would like to assist
with making Vaadin a first class system for use in OSGi applications.   

#Finally
The only reason I have stuck with Vaadin for my OSGi code is that I am "Rusted On" to modularity and I love 
the Vaadin Java server approach.

If I were not "Rusted On" I would have given up a long time ago and gone in other directions.

My 14c version is the result of 100's of hours of struggle to get a flow version running.

V8 was relatively easy in comparison.

I have still not got the parsing of Html templates working and cannot therefore use Designer.

V19 I believe is the opportunity to bring OSGi developers on board but they will need much better 
hand holding (less friction) than appears to be on the Vaadin drawing board at present.

A V19 of a demo that just drops into the Karaf deploy folder would remove all that friction.

As already stated, I am always available to assist, 

paulf@qnenet.com

**Comment by denis-anisimov** [comment]
Sorry, I don't get what the ticket is about ?

Does it describe an issue/bug/enhancement ?
And what are the steps to reproduce ?

Also please note :
- Platform V19 (Flow 6.0) osgi is extracted to the https://github.com/vaadin/osgi repo
- v14 OSGi support compatibility mode is still in the Flow repo

This ticket looks like a demo which is built on top of existing v14 OSGi support.
But the title is "OSGi in V19". So I'm quite confused with the ticket.

**Comment by pleku** [comment]
Thank you @QNENet Paul for the contribution, we'll discuss internally what will be the next steps. cc: @mstahv 

> For Vaadin to be taken seriously by OSGi developers they should not be told to go and sort out the
dependencies to get the system running and the Vaadin Starter approach in my opinion is not
suitable for OSGi purposes.

The "Karaf feature" has been in the plans even though it was not done immediately. 

> I "humbly" suggest that vaadin produce a V19 OSGi demo based on my code's fit with Karaf.

Yes as many are using Karaf, I agree that it would be beneficial to also have a demo for that.

> I have still not got the parsing of Html templates working and cannot therefore use Designer.

This is I believe something that we could show in the v19 version of the starter with Lit templates.

**Comment by QNENet** [comment]
This is part of an email I sent to the Karaf User Mail List.  You may get some value from my code, if not nothing lost.

Karaf 4.3 and Vaadin Flow V19.

I am attempting to create a demo of the new Vaadin 19 https://github.com/vaadin/base-starter-flow-osgi

I have built and run it successfully as per the repo where it uses a bnd approach.

My karaf attempt, https://github.com/QNENet/vaadindemo,  fails with the error below.

If I comment out "<bundle>mvn:com.vaadin/flow-osgi/6.0-SNAPSHOT</bundle>" entry in the demofeatures module the system builds but will not run, of course.

It seems that the Karaf feature I add to demofeatures, pax-http-whiteboard does not provide the necessary "org.osgi.service.http.context"

----------------------------------------------------------------------------------------------------------------------------------

Error executing command:
Unable to resolve root:
missing requirement [root]
    osgi.identity;
    osgi.identity=demo;
    type=karaf.feature;
    version="[1.0.0.SNAPSHOT,1.0.0.SNAPSHOT]";
filter:="(&(osgi.identity=demo)(type=karaf.feature)(version>=1.0.0.SNAPSHOT)(version<=1.0.0.SNAPSHOT))"

[caused by: Unable to resolve demo/1.0.0.SNAPSHOT: missing requirement [demo/1.0.0.SNAPSHOT]
    osgi.identity;
    osgi.identity=com.vaadin.flow.osgi;
    type=osgi.bundle;
    version="[6.0.0.202101100021,6.0.0.202101100021]";
    resolution:=mandatory

[caused by: Unable to resolve com.vaadin.flow.osgi/6.0.0.202101100021: missing requirement [com.vaadin.flow.osgi/6.0.0.202101100021]
    osgi.wiring.package;
filter:="(&(osgi.wiring.package=org.osgi.service.http.context)(version>=1.1.0)(!(version>=2.0.0)))"]]
----------------------------------------------------------------------------------------------------------------------------------------------

**Comment by denis-anisimov** [comment]
The latter comment has noting to do with `OSGi in V19` title and the original ticket description.
It looks like a totally different issue which is not even :
- Flow related (`osgi`  repo should be used)
- it's not clear whether this is issue even in our code : we have two tests that proves that OSGi impl works (felix-jetty container is used and bnd tools)
- even if it's something that should be done on our side it's a Karaf related ticket which has to be created as a standalone ticket.

So please avoid putting everything into one ticket.
There is a reason why issue  tracker is used : it allows to find issues fast and helps to categorize them and work on isolated tickets instead of everything at once.

This comment will be lost for sure if you won't create another ticket.

**Comment by denis-anisimov** [comment]
https://docs.osgi.org/javadoc/osgi.cmpn/7.0.0/org/osgi/service/http/context/ServletContextHelper.html

`ServletContextHelper` is a part of compendium 7 specification.
Compendium 7 specification is what we are relying on.
if compendium 7 specification is not supported by the OSGi container then out OSGi impl can't be used.

**Comment by pleku** [comment]
So one thing that does not yet have an issue open - is to provide a demo for Vaadin OSGi app with Karaf.
The "Karaf feature" or [provisioning](https://karaf.apache.org/manual/latest/provisioning) can be continued in #6525 though /flow is probably not the right repository for it. We'll probably take a look at this in the upcoming weeks.

Another thing, which was discussed in the OSGi mailing list, is the usage of compendium/enterprise specification, or declaring individual specifications. We don't have a clear understanding on this but apparently there should be some changes made and it would be better to switch to use distinct versions ? Can you please @QNENet clarify if this is the case or even contribute a PR to https://github.com/vaadin/osgi in case that fixes problems ?

**Comment by QNENet** [comment]
Being involved in this process on a major project is a new experience for me, so sorry for getting out of line.
As this issue was marked as "Feedback" I considered this issue to be suitable for general developer discussion about the latest flow version.
As Vaadin makes regular requests for feedback, I suppose the only avenue is the forum which does not seem suitable for the feedback I am offering.
I have opened OSGi issue #19 for future work re this matter.

**Comment by denis-anisimov** [comment]
This is the correct link : https://github.com/vaadin/osgi/issues/19.
