### ISSUE TITLE
Consider a way to use JS proxies on the client side.

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#974]
#970 is intended to solve an issue when a JS binding expression refers to a property which is not set in the model.

May be this is enough may be not.

It doesn't solve an issue if an expression refers to a property which is not defined int the model.
So if model is defined as 

``` java
public interface MyModel extends TemplateModel{
    String getName();
    vois setName(String name);
}
```

then ModelMap (server side)/ NodeMap (client side) will be populated with only "name" property.
It means that e.g. evaluation of the {{lastName? name+' '+lastName: name}} binding will throw an exception.

We may want to use JS proxies if we want to avoid the exception (proxies just allow to avoid the exception but it's still unknown which value should be used for `lastName` here: is it `""` (`String` type) or `0` (`int` type) .

There are also other cases when we want to use proxies.

At the moment there are at least two issue with proxies:
- Proxies are not supported by JS engine that is used in GWT unit tests.
- PhantomJS doesn't support proxies.

Both issues has to be solved in order to be able to use proxies.

**Comment by Legioth** [comment]
This issue is related to functionality in the old template system based on the Angular syntax. It's not directly relevant with the current architecture.
