### ISSUE TITLE
Import only styles.css as global styles instead of all css files from theme root folder

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9741]
Based on the DX testing feedback and internal review on how things worked in previous framework versions, we should only import one "magic css file" for the application theme shared styles instead of the original feature design of:
```
Any other stylesheets not in the components folder are loaded as global css.
```
The benefit of this is that the developer gets to have explicit control over what is loaded and in which order by having to import the css themselves to the file. The proposal is to name this file as `styles.css` like with legacy framework versions 6-8. Another alternative could be `shared-styles.css`, but at the time of writing of this the former should be used. This will mean that there is less magic and more control for the global css files.

### Acceptance Criteria
- [x] only load `styles.css` file from the active theme folder
- [x] when in development mode (devserver running), and there is an active in-project "application" theme in use without the `styles.css` file present in active theme the folder, automatically create the file with content that says something like `import your application global css files here or add the styles directly to this file`
- [x] when building the frontend for production and the active in-project theme folder does not contain the `styles.css` file, fail the build with error stating that "styles.css file is missing and is needed for the _theme-name_ in use" (even as empty as we want to avoid developer errors where the wrong theme is used or some files are not being added to the theme).
- [x] Update this requirement to documentation to mention that it is needed for getting explicit control over the loading order of the global css
- [x] Update https://github.com/vaadin/application-theme-demo to use this

**Comment by knoobie** [comment]
Huge +1 for 

> The benefit of this is that the developer gets to have explicit control over what is loaded and in which order by having to import the css themselves to the file
