### ISSUE TITLE
Running SpringBoot's main is not serving mapped "assets" from NPM packages

### ISSUE THREAD

**Issue by taefi** [vaadin/flow#9757]
#### Steps to reproduce:
1. Download a vaadin-java starter from SVC
2. Just change the vaadin, flow, spring add-on versions to the latest prereleases:
```xml
<vaadin.version>19.0.0.alpha1</vaadin.version>
<flow.version>6.0.0.alpha3</flow.version>
<vaadin.spring.version>16.0.0.alpha2</vaadin.spring.version>
```
3. Add the followings to `theme.json`:
```JSON
{
     "importCss": ["@fortawesome/fontawesome-free/css/all.min.css"],
     "assets": {
            "@fortawesome/fontawesome-free": {
                    "svgs/brands/**": "fontawesome/svgs/brands"
            }
     }
}
```
4. Add the following `Image` to a view: 
```java
Image crmImage = new Image(
                "themes/custom-theme/fontawesome/svgs/brands/vaadin.svg",
                "Vaadin SVG");
```
5. Add `@NpmPackage(value = "@fortawesome/fontawesome-free", version = "5.15.1")` to any view class.
6. Add `@Theme("custom-theme")` to the app-shell class.
7. Run the SpringBoot application from the main method.

#### Current Behavior:

- It is not serving the NPM SVG brand icons that result in not showing the vaadin SVG icon. 
- While the exact same application is working completely fine by running it using: `mvn spring-boot:run`

P.S: In both ways, the application starts normally and all other changes correctly applied (including fontawesome font-icons and all the other changes such as background-image, font, overridden Lumo styles, which are not listed here for simplicity)

#### Expected output:
To serve the NPM assets mapped by `assets` block in `theme.json` while the application is being run by the main method. 

#### Environment: 
- MacOS Big Sur 11.1
- Java 15.0.1 and 11.0.8
- Browser: Google Chrome Version 87.0.4280.88 (Official Build) (x86_64)
- IDE: Intellij IDEA 
- Node `v14.15.0`
- NPM `6.14.8`

**Comment by caalador** [comment]
Can't replicate on 19.0-SNAPSHOT could you test with that.
Either it works for me both ways or then it fails both ways what one has a typo in the theme name.
