### ISSUE TITLE
add configurable limit on number of heartbeat retries

### ISSUE THREAD

**Issue by HermanBovens** [vaadin/flow#9759]
Currently, heartbeats can be enabled (with a configurable interval) or disabled completely.

As described in https://stackoverflow.com/questions/65602379/how-to-limit-the-number-of-times-vaadin-14-tries-to-send-heartbeat-requests, there are cases where you'd like to have heartbeats (to ensure detection of UIs that should be closed) but don't want them to retry endlessly, such as [due to this mod_auth_openidc issue](https://github.com/zmartzone/mod_auth_openidc/issues/331).  We currently had to disable heartbeats completely to work around this, but this is not ideal.

So I suggest to add a config option `maxHeartbeatRetries` to be able to limit the number of retries.  After the limit is reached, the client should stop sending any requests.

**Comment by Legioth** [comment]
There's also the `closeIdleSessions` which makes heartbeats stop after a while.

**Comment by HermanBovens** [comment]
@Legioth  Correct me if I'm wrong, but I think `closeIdleSessions` only works if the heartbeats actually reach the server.  The problem here is that when the max session time (OpenID) is reached, the heartbeats won't reach the server anymore.  The server will detect that no heartbeats or other requests are coming in and will clean up, but the client will keep trying as far as I know.

**Comment by Legioth** [comment]
I believe the `Vaadin-Refresh` token is also considered for the heartbeat responses. Making the authentication proxy include that token in the intercepted response might thus be one way of making the client reset itself to e.g. a login form after the session timeout.

**Comment by knoobie** [comment]
@HermanBovens your problem description reminds me of a  problem I was facing with V8 and Spring Boot. I leveraged the internal implementation of `DefaultConnectionHandler` and created a custom ErrorHandler for clients that send HEARTBEAT calls when the server session was already expired. 


![image](https://user-images.githubusercontent.com/3968629/103889221-5a24e680-50e6-11eb-8dd5-9f194d38973f.png)


@Legioth  the PR that changes the DefaultConnectionHandler doesn't look like it was ported to flow. 


Framework: https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java#L149

Flow: https://github.com/vaadin/flow/blob/74e62ebb32cbf6a1aa986ec9aa547ce00b19ee24/flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java#L137

**Comment by HermanBovens** [comment]
I was going through the code to find out what would need to be changed, and found that the UI instance has a ReconnectDialogConfiguration which includes reconnectAttempts property to control how many times to re-try requests (including heartbeat requests). Default seems to be 10000.

I guess I should just set this to 10 or so, programmatically.

**Comment by pleku** [comment]
>I guess I should just set this to 10 or so, programmatically. In v14 using PageConfigurator and in v18 using AppShellConfigurator, it seems.

I can confirm that. If it doesn't work (meaning the change of the configuration is not applied), you can open another issue.

**Comment by pleku** [comment]
>DefaultConnectionHandler doesn't look like it was ported to flow.

Some parts of that changeset look a bit obscure as they mention Safari 6 and don't have any tests (https://github.com/vaadin/framework/commit/477e9fe824efeae0085ea15ec4bd05740fa2df40), but if those help to address some issue, they could be at least partly ported to Flow.

**Comment by knoobie** [comment]
@pleku The code in flow looks the same (even with the same comments mentioning  iOS 6 Safari and no tests. ;) if I remember correctly, those lines were only touched to update the ancient ticket numbers. 

If you want, I can forward those changes to flow - not sure about the tests, because there are currently non involving HeartbeatHandler in the whole codebase.

**Comment by pleku** [comment]
@knoobie please go ahead, I think we can make an exception for now and live without the tests as the changes have been in the framework for a while and there are no regressions reported.
