### ISSUE TITLE
The default Lumo theme should work also in Fusion apps

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9765]
When using the default Lumo theme by adding `@Theme(themeClass = Lumo.class)` annotation or by omitting the `@Theme` annotation altogether, I want the global Lumo styles to be applied to the light DOM of the app automatically, so that the way to use the default theme is consistent with that for [custom themes](https://github.com/vaadin/flow/issues/9684).

This is not the case with Vaadin 19.0-SNAPSHOT.

**Steps to reproduce**:
1. create a new Vaadin 19 / Fusion project with [https://start.vaadin.com/?preset=fusion](https://start.vaadin.com/?preset=fusion)
   (or with Vaadin CLI: `npx @vaadin/cli init --fusion --pre fusion-theme`)
2. change the Vaadin version to `19.0-SNAPSHOT` in `pom.xml`
3. stop using the custom `fusion-theme` theme (comment out `@Theme(value = "fusion-theme")` in `Application.java`)
4. remove the workarounds that include the Lumo theme manually:
   - in `index.html` remove:
     ```html
     <custom-style>
       <style include="lumo-color lumo-typography"></style>
     </custom-style>
     ```
   - in `index.ts` remove:
     ```ts
     import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';
     applyTheme(document);
     ```
 - run the app with `mvn` and see that the Lumo theme is NOT applied to the page light DOM: in the browser console evaluate `window.getComputedStyle(document.body)['font-family']` and see that it has the deafult value (`"serif"`)

**Expected behavior**
The Lumo theme should be applied to the body of the document, including the font family. That is, `window.getComputedStyle(document.body)['font-family']` should evaluate to `"-apple-system, BlinkMacSystemFont, \"Roboto\", \"Segoe UI\", Helvetica, Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\""`.

**Comment by pleku** [comment]
So does this work differently from v18 fusion only project ? Shouldn't there be an IT somewhere for this ?

**Comment by vlukashov** [comment]
> So does this work differently from v18 fusion only project ? Shouldn't there be an IT somewhere for this ?

This issue is not new to V19. It's not something that broke after adding the new theming API. The new theming API only makes this issues more apparent.

**Comment by rolfsmeds** [comment]
This is the only existent Fusion theming documentation that I could find: https://vaadin.com/docs-beta/latest/fusion/application/fusion-application-main-view/#import-theme-global-styles

**Comment by pleku** [comment]
>in index.ts remove:
> import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';
applyTheme(document);

This part is no longer a necessary workaround as it is handled automatically when a custom theme is used.

It is not clear to us what the "default Lumo" theme should provide to the fusion views. This seems like a missing feature instead of a bug as it has been around for quite a while and is even partly documented.
