### ISSUE TITLE
Mention the Spring Security changes needed for the offline feature

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#9786]
In apps configured with Spring Security, after login the app is redirected to `/sw-runtime-resources-precache.js` (using 19.0.0.alpha2)

Take a look to this change in Bakery
https://github.com/vaadin/bakery-app-starter-flow-spring/pull/1141/commits/0eead32f213f2fbd53b4c79f4ee52b82a87c65e2#diff-7c93516d70cd0b8aa1c6b72864bd53136a865cdbe60dcfb0602bdf86556968f0R128

Also need to mention that the request cache needs to exclude service worker initiated requests. It's needed for https://github.com/vaadin/flow/issues/9787, see the fix in [this commit](https://github.com/vaadin/bakery-app-starter-flow-spring/pull/1141/commits/14f774c7cbaf28564981e1fee148e26de1f7180b)

**Comment by paveldabrowski** [comment]
I have the same issue ?  After login the app is redirected to /sw-runtime-resources-precache.js (using 19.0.0)
Where can I find solution?

**Comment by haijian-vaadin** [comment]
Hi @paveldabrowski, here is the related documentation https://vaadin.com/docs-beta/latest/guide/upgrading/#ignore-one-more-service-worker-related-static-file. Hope it helps, let us know if it's unclear.

**Comment by paveldabrowski** [comment]
> Hi @paveldabrowski, here is the related documentation https://vaadin.com/docs-beta/latest/guide/upgrading/#ignore-one-more-service-worker-related-static-file. Hope it helps, let us know if it's unclear.

Thank you very much. :-)

**Comment by Avec112** [comment]
This issue should be opened again. I just updated from v18.0.6 to v19.0.1. 
After login (Spring Security) I get this `sq-runtime-resources-precache.js` in my face
