### ISSUE TITLE
PNPM overrides version with platform version

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#9793]
When using pnpm if you want to depend on a non platform version of a vaadin component the npm version will be overridden with the platform defined version.

e.g. if the platform npm version of vaadin-charts is 6.3.1 and you add a dependency for vaadin-charts 9.0.0 that has the npm version 7.0.0 then as the version is still framework managed as NpmPackage will update the version versions.json  for forcing versions will get the platform version 6.3.1 instead of the expected 7.0.0

If the version is set manually to 7.0.0 in package.json it will override the platform version but in this case also the java package need to be updated.

For a sample project see https://github.com/vaadin/vaadin-charts/issues/557

**Comment by pleku** [comment]
I think in part this is what is expected - one can manually override the versions in package.json but otherwise we "default to" platform versions so that the user gets a tested and tried package, instead of inconsistencies. But using another version of a component (than what is in the platform) is a valid use case and should be supported somehow too.

I don't know what options we have - should we just provide a way to disable the _platform versions.json based locking_  and document things ?

**Comment by pleku** [comment]
As there is a workaround for installing the desired version(s) to use into `package.json`, not marking this as a blocker.

**Comment by caalador** [comment]
The problem is that you can't override manually the version as you need to have a new component which makes it so that you get the platform version and not the component package version.

Also the workaround is not that nice as you have to 
1. add the flow component dependency
2. add a NpmPackage annotation that brings in a wrong version of the webcomponent
3. update the version in package.json

This is not what is expected as the expected thing is that you add a newer version of a component and get the webcomponent version for that component and not the platform version.

**Comment by knoobie** [comment]
Just an idea, could be totally over-engineered but would allow for a good DX but could creates a new layer for maintenance... 

```xml

          <plugin>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-maven-plugin</artifactId>
            <version>${vaadin.version}</version>
            <configuration>
              <customVersions>
                <component>
                  <class>com.vaadin.flow.component.textfield.TextField</class>
                  <version>2.9.0</version>
                </component>
              </customVersions>
            </configuration>
          </plugin>

```

Java developer love to configure the dependencies in the pom ;)

**Comment by caalador** [comment]
One choice would be to have a flag to disable the usage of platform `versions.json` which could bring in the problem that one might get conflicting versions (polymer being the main problem in most cases).

Another would be that we would lock the versions set in package.json even for "framework managed" versions, but this might
mean that we get a version that is not compatible with the used platform version due to an add-on that depends on a Vaadin component (using NpmPackage) making the server and client side implementations out of sync.

**Comment by pleku** [comment]
There are two other pnpm related fixes/improvements ongoing: #9804, #9834 (#9835) which might affect this, so not starting this issue until those are concluded, which should be within 1-2 weeks.

**Comment by caalador** [comment]
Should we just use the package.json versions for locking as the platform versions are in any case updated into the package.json when going through the frontend packages as the versions is more to lock any transitive dependencies than actual versions from package.json.

e.g. create versions by collecting package.json dependencies and padding with platform versions that for some reason are not in there.

**Comment by mheicke** [comment]
Any news on this?
