### ISSUE TITLE
Ensure fusion is OSGi compliant 

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#9813]
Vaadin 19 adds OSGi, all delivered artefacts should work in OSGi

**Comment by denis-anisimov** [comment]
`fusion` is not OSGi compatible since it's based on Spring.

May be I misunderstood the term `fusion`.

**Comment by denis-anisimov** [comment]
The current impl of `fusion-endpoint`  module will not ever be OSGi compatible.

**Comment by manolo** [comment]
Ok, thanks for the clarification.
Then we need to assure that it's correctly documented. 
Closing this
