### ISSUE TITLE
Multi module maven project & webpack-dev-server hot reload

### ISSUE THREAD

**Issue by flefebure** [vaadin/flow#9821]
Hi,

Vaadin 14.4.5 / Flow 2.4.4

Considering a multi-module maven project with a module including frontend resources in the standard folder $root/module/src/main/resources/META-INF/resources/frontend

Is it possible to have the webpack-dev-server hot serve the resources in this directory ?

Actually, I appears that the hot reload is only possible for resources in $root/frontend
I tried some manipulations of the generated webpack.config.js but without success

A multi-module test project, (adapted from https://github.com/vaadin/flow-spring-examples) : https://github.com/flefebure/flow-spring-examples

(Run ui-bootstrap/TutorialApplication in eclipse/idea to tried the live reload of ui-module/src/main/resources/META-INF/resources/frontend/example-template.js)

Franck

**Comment by denis-anisimov** [comment]
This looks like a question and not an issue.
Please use https://vaadin.com/forum for questions.

The issue when you described is a known limitation.
The frontend resources are copied (from jars or external dependencies) into the main project where web pack dev server is executed and external locations are not monitored once the copy is made.
I'm pretty sure we have a ticket for this already.

**Comment by flefebure** [comment]
Mmm IMO it's more an issue that a question. But effectively it's a duplicate https://github.com/vaadin/flow/issues/6347 ... Didn't find it last day. Sorry
