### ISSUE TITLE
`pnpm i` should not require the `--shamefully-hoist` option

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9834]
When installing a front-end dependency with `pnpm i`, I do not want to have to provide the `--shamefully-hoist` option. Yet I still want that after `pnpm i` (no hoist) the `mvn` command still works normally. With Vaadin 19.0.0.alpha3 this is not the case.

Depends on https://github.com/vaadin/flow/issues/9719

DoD:
 - running `pnpm i [dependency]` works in a Vaadin 19 project downloaded from start.vaadin.com (before and after running `mvn` first)
 - all Flow integration tests pass, all starters work fine, start.vaadin.com projects work fine

**Context:** (more in the [feature design document](https://docs.google.com/document/d/1UQ_JpxRSGBKeK2V48mJmM3B8ZViF6O_5dhwu6bRMguw/edit#heading=h.u357i1tq3rkm))
Why does Vaadin use the --shamefully-hoist flag of pnpm?

It was added to solve issues with using transitive dependencies without explicitly declaring them. 
The `--shamefully-hoist` flag was added in #7059 about a year ago. A comment on the related issues explains the reasoning:

> - pnpm installs packages in a specific way. It doesn't use flat structure for node_modules as npm. It installs the declared dependencies into node_modules but all transitive dependencies are installed into node_modules/.pnpm/registry.npmjs.org/. As a result node_modules contains only small set of declared dependencies and all other transitive deps are installed in a different folder. This is correct structure which should be handled properly. BUT webpack is not able to handle this structure at all. When you run it it fails with error because it tries to find a transitive dependency (e.g. mkdirp ) and it's not able to find it.
>
> - to be able to solve this there is a config parameter shamefully-hoist=true which says pnpm to install deps into node_modules . The parameter works being added into .nmprc (another question : is there a way to avoid using this file?). But when I run webpack I still get an error like this Error: Can't resolve '@vaadin/flow-frontend/dndConnector-es6.js?babel-target=es5' in '/Users/denis/workspace/flow/flow-tests/test-mixed/target/frontend'. Will see what can I do about it.

**Implementation ideas:**
 - just drop the option, if possible
   Drop the option, list the `mkdirp` (and other) implicitly used dependencies explicitly in package.json, mention in the release notes this as a breaking change and recommend deleting the node_modules folder after the next Vaadin version update.
 - if dropping the option is not possible, move it to `.npmrc` so that specifying it explicitly is no longer necessary

**Comment by joheriks** [comment]
Going with the first option, removing `--shamefully-hoist`, while e.g. `mkdirp` could be added explicitly as a dev dependency since we use that only in `webpack.generated.js`, we also run into issues like for example the following (they are not the only ones):
```
ERROR in ../target/flow-frontend/field-highlighter/src/vaadin-field-highlighter.js
Module not found: Error: Can't resolve '@polymer/iron-a11y-announcer/iron-a11y-announcer.js' in '/Users/joheriks/vaadin/dev/my-project/target/flow-frontend/field-highlighter/src'
 @ ../target/flow-frontend/field-highlighter/src/vaadin-field-highlighter.js 8:0-88 124:4-21
 @ ../target/flow-frontend/field-highlighter/theme/lumo/vaadin-field-highlighter.js
 @ ../target/frontend/generated-flow-imports.js
```
```
ERROR in [at-loader] ./node_modules/@vaadin/vaadin-app-layout/src/vaadin-app-layout.d.ts:18:29 
    TS2307: Cannot find module '@vaadin/vaadin-themable-mixin/vaadin-themable-mixin.js' or its corresponding type declarations.
```

Here Webpack can't resolve `@polymer/iron-a11y-announcer` and ` @vaadin/vaadin-themable-mixin` because the packages go into `node_modules/.pnpm` instead of flat into `node_modules` as they are not direct dependencies of the project. So it seems that by design we need a flat hierarchy (or find a way to get the transitive dependencies of components into `package.json`, which is probably not easy).

**Comment by Artur-** [comment]
The pnpm model is basically "Whatever dependency a certain package uses, must declare that it uses that dependency". So if Vaadin autogenerates some scripts into the user's project, then it must also add the needed dependencies. I think this still sounds doable.

There is then also the problem with TypeScript definition files and when testing I ended up needing to do
```
pnpm i --save-dev @vaadin/vaadin-control-state-mixin @vaadin/vaadin-list-state-mixin @polymer/iron-resizable-behavior @polymer/iron-scroll-target-behavior @vaadin/vaadin-control-state-mixin @vaadin/vaadin-list-mixin highcharts
```
to get everything to work. This again sounds odd, that I need to depend on e.g. `@vaadin/vaadin-control-state-mixin` but without it the result is
```
ERROR in [at-loader] ./node_modules/@vaadin/vaadin-button/src/vaadin-button.d.ts:20:33 
    TS2307: Cannot find module '@vaadin/vaadin-control-state-mixin/vaadin-control-state-mixin.js' or its corresponding type declarations.

```
