### ISSUE TITLE
Re-check the performance of pnpm vs. npm 

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9835]
When using Vaadin I expect that by default it makes a reasonable choice of the front-end package manager. Since Vaadin 14.2 and Vaadin 15 the default is pnpm because in late 2019 it was determined to be significantly faster than npm for repeated builds (see #6150).

In early 2021 the situation might have changed:
> I tested svc with npm  and pnpm for the case when you have already downloaded the deps, i.e. ran install at least once.
> The results are roughly:
>  - The pnpm version Vaadin uses is the slowest option (36s)
>  - npm 6 comest next (19s)
>  - The latest pnpm is significantly better than the used one (13s)
>  - npm 7 is fastest (10s)

more context in the [feature design document](https://docs.google.com/document/d/1UQ_JpxRSGBKeK2V48mJmM3B8ZViF6O_5dhwu6bRMguw/edit#heading=h.2ckta28kw1pd)

DoD:
 - re-run the same performance benchmarks as in #6150
 - consider 3 options:
    - the default npm from latest Node 14
    - the default npm from latest Node 15
    - the latest pnpm
  - summarize the results in a comment to this GH issue
  - make a recommendation to stay with pnpm or to switch the default back to npm

**Comment by haijian-vaadin** [comment]
Should try both the cases with `~/.pnpm_store` and without should be measure.

**Comment by jhult** [comment]
It sounds like some of the work in #9719 should occur before this is re-tested.

**Comment by knoobie** [comment]
npm 7 is now the latest and greatest https://github.blog/2021-02-02-npm-7-is-now-generally-available/

**Comment by joheriks** [comment]
The following times were measured by running `rm -rf node_modules` follwed by `npm i --legacy-peer-deps`/ `pnpm i --shamefully-hoist` based on `package.json` in https://github.com/vaadin/business-app-starter-flow:

| Package manager | Node.js   | Time (s) |
| ----------------| --------- | -------- |
| npm 7.4.3       | 15.8.0    | 10.1     |
| npm 6.14.10     | 14.15.4   | 18.8     |
| pnpm 5.15.2     | 15.8.0    | 5.5      |

Average of three runs on 2019 MacBook Pro with SSD and fast network. Deleted `~/.npm` between switching versions and discarded the results from the first run (warm cache).

**Comment by joheriks** [comment]
And these are the timings with existing `node_modules`:

| Package manager | Node.js   | Time (s) |
| ----------------| --------- | -------- |
| npm 7.4.3       | 15.8.0    | 2.2      |
| npm 6.14.10     | 14.15.4   | 6.8      |
| pnpm 5.15.2.    | 15.8.0    | 1.7      |

The conclusions would be that while performance has improved for both managers, like before pnpm has a about a 2:1 advantage over npm. This indicates we should continue using pnpm, in particular as the npm bundled with LTS Node.js (14.15.4) is 6.14.10.

**Comment by Artur-** [comment]
I see similar results for the linked package.json. 

However if I use `package.json` from the start.vaadin.com project, the results are 

```
rm -rf node_modules && time npm i
real	0m11.292s
```
```
rm -rf node_modules && time pnpm i --shamefully-hoist
real	0m11.674s
```

With an existing `node_modules` it becomes
```
rm -rf node_modules && npm i && time npm i
real	0m2.328s
```
```
rm -rf node_modules && pnpm i --shamefully-hoist && time pnpm i --shamefully-hoist
real	0m2.713s
```

in other words, no performance difference at all

**Comment by Artur-** [comment]
Adding `--ignore-scripts` even turns it to npm's advantage:
```
rm -rf node_modules && time npm --ignore-scripts i
real	0m8.041s
```

```
rm -rf node_modules && time pnpm --ignore-scripts --shamefully-hoist i
real	0m8.636s
```

**Comment by knoobie** [comment]
Personally I would prefer npm over pnpm just because it is the default package manager. The small difference in performance doesn't really justify the additional cost of adding a new "framework".

**Comment by joheriks** [comment]
I get the same 2:1 ratio in favor of pnpm (ver `5.15.2`) over npm (ver `7.5.0`) with Vaadin 18 starter fresh from start.vaadin.com:
`npm i --legacy-peer-deps  9.33s user 5.98s system 232% cpu 6.572 total`
`pnpm i --shamefully-hoist  5.17s user 8.81s system 221% cpu 6.310 total`

**Comment by Artur-** [comment]
This was the start.vaadin.com project itself, not a generated project

**Comment by Artur-** [comment]
https://gist.github.com/Artur-/6a308019aa25ad8bd108ba182942e77f should be pretty close to what I was testing

**Comment by joheriks** [comment]
Redid the measurements, as it seems I may have misinterpreted the output of the macOS `time` command (taking user time instead of walltime, the former exceeding the latter due to multi-CPU utilization).

The numbers with the above `package.json` (same npm and pnpm versions as in my previous comment): 
`npm i --legacy-peer-deps  11.54s user 8.91s system 237% cpu 8.621 total`
`pnpm i --shamefully-hoist  5.45s user 12.27s system 257% cpu 6.886 total`

So it turns out the advantage of pnpm is significantly lower.

**Comment by vlukashov** [comment]
As the result of this research suggest, Vaadin should switch the default front-end package manager from pnpm to npm: https://github.com/vaadin/flow/issues/9986

**Comment by Avec112** [comment]
While performance is one thing what about the fact that npm created large module packages inside each and every project while pnpm only linked them. This is/was the biggest advantage with pnpm over npm in my opinion. Have this changed so npm also just linkes all dependencies now? I hope we are not going back to project sizes of over 100Mb because npm is not symlinking dependencies like pnpm does. 
https://pnpm.io/pnpm-vs-npm
https://pnpm.io/symlinked-node-modules-structure

**Comment by Artur-** [comment]
pnpm support is still there even though npm is used by default
