### ISSUE TITLE
Error when session invalidated with @Push and slow network

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/flow#9853]
### Description of the bug / feature
Over slower networks, invalidating the session in a view that uses @Push causes the user to see  a red error message visible in the top right corner, **“Tried to move from state TERMINATED to TERMINATED which is not allowed”**

### Minimal reproducible example

1. Open the following view in the browser:
```
@Route("PushView")
@Push
public class PushView extends VerticalLayout {

    public PushView() {
        add(new Button("Logout", e -> UI.getCurrent().getSession().getSession().invalidate()));
    }
}
```

2. In chrome dev tools, throttle the network (e.x. to Fast 3G).
3. click "Logout"

### Expected behavior
No error is displayed
### Actual behavior
A red popup: "Tried to move from state TERMINATED to TERMINATED which is not allowed"
### Versions:
    - Vaadin / Flow version: 14.4.6 + Spring
    - Java version: 11
    - OS version: Windows 10
    - Browser version (if applicable): Chrome  87.0.4280.141

**Comment by tanbt** [comment]
Also reproducable with `14.4.6 + servlet`.

**Comment by denis-anisimov** [comment]
This should be fixed by https://github.com/vaadin/flow/commit/2e35fe71f54f18e83a70aab3e2eb85fcb236fe9f.

At least I don't see now in the code anywhere changing the state to TERMINATED without checking whether it's already TERMINATED.
