### ISSUE TITLE
VaadinServlet should be properly reinitialized 

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#9858]
`GenericServlet` has two lifecycle methods:
-`init(ServletConfig)`
- `destroy`

Two issues here:
- `destroy` may be called when `VaadinService` is not available yet (with the current impl)
- `init`  may be called several times by the Servlet container with different `ServletConfig` instance : current impl assumes that servlet container calls it once.

The issues have been investigated during attempts to run an app in Karaf.
PAX-web may reuse the same servlet instance and calls lifecycle methods:
- init
- destroy
- init (with another `ServletConfig`) : reinit the same instance
- destroy (later on at some point)

So two assumptions are wrong: 
- `destroy` should not assume that service instance is never null
- `init` should expect that it may be called several times with different arguments but every next time `destroy` is called before.

**Comment by QNENet** [comment]
Not sure if this is relevant to this problem but for my karaf 19 demo to work I had to not use pax-web and use felix-http instead.
See https://github.com/QNENet/vaadin19demo/blob/main/starterfeatures/src/main/feature/feature.xml

**Comment by denis-anisimov** [comment]
Thanks,
I concluded this based on my struggle with PAX-web.

It has its own way to do things.
This ticket is just one issue.
The main problem for now is: `ServletContextListener`  is not called. It has to be deployed and registered as a service before servlet registration.  At least I was able to get it working with very simple project.
