### ISSUE TITLE
Add jandex index to all necessary artifacts

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#9862]
Vaadin 14.4.6: in order to support Quarkus, so-called Jandex index needs to be created. The reason is that Quarkus doesn't rely on classpath scanning to discover classes; instead it uses Jandex index. Alternatively, the jar files needs to have an empty `beans.xml` file present. Please see https://quarkus.io/guides/cdi-reference for more details.

These files need to be present in all `flow-*` jar files.

**Comment by mvysny** [comment]
As a workaround I've created a project which builds the Vaadin Jandex index; I'm also publishing the artifact on jcenter and maven central. See https://github.com/mvysny/vaadin-jandex/ for more details.

**Comment by pleku** [comment]
### Acceptance Criteria
- [ ] /platform project will build Jandex index for all necessary Vaadin artifacts
    - flow + flow-components artifacts, theme integrations, everything that has an annotation that the Vaadin application is going to read
    - not needed: cdi, spring, mpr ...

**Comment by pleku** [comment]
Not yet done as #11241 is pending
