### ISSUE TITLE
Auto-installed Node.js in .vaadin should not take precedence over global by default

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#9863]
Flow downloads and installs Node.js into `~/.vaadin` if it can't find `npm` command globally (i.e., on `PATH`). After such auto-installation, Flow will subsequently prefer `npm` and `node` commands in  `~/.vaadin`, even if a global installation has been added later. This version of node is used both when Flow runs `npm install` (when `vaadin.pnpm.enable=false`) and when it launches `webpack-dev-server`. 

This is contradictory to the auto-install logic (which prefers global) and should not be the default behaviour.  Only if the `require.home.node` parameter is set to true (false by default) should the `~/.vaadin/node/node` be forced.

Flow version: 6.0-SNAPSHOT (2021-01-22).

**Comment by Artur-** [comment]
The starter wizard project uses Node 15 / npm 7. 
npm 7 uses a different lock file version than earlier npm versions (npm 7 == lockfile v2, earlier == lockfile v1)

Now every time I do something, not sure what, node is installed into ~/.vaadin/node

After this happens, the starter wizard (Vaadin 19) project uses the old node version and creates a v1 lockfile instead of the v2.

Then I have to delete ~/.vaadin/node to make everything work again.

Then some operation installs node into ~/.vaadin/node and it repeats.

**Comment by martinisraelsen** [comment]
Also seem to happen in 14.4.6. I keep deleting ~/.vaadin/node and it works for a period of time. Then all of a sudden builds will fail with this message:

`
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:14.4.6:prepare-frontend (default) on project bookingcentralx: 
[ERROR] 
[ERROR] ======================================================================================================
[ERROR] Your installed 'node' version (8.1.2) is too old. Supported versions are 10.0+
[ERROR] Please install a new one either:
[ERROR]   - by following the https://nodejs.org/en/download/ guide to install it globally
[ERROR]   - or by running the frontend-maven-plugin goal to install it in this project:
[ERROR]   $ mvn com.github.eirslett:frontend-maven-plugin:1.7.6:install-node-and-npm -DnodeVersion="v12.14.0" 
[ERROR] 
[ERROR] You can disable the version check using -Dvaadin.ignoreVersionChecks=true
[ERROR] ======================================================================================================
[ERROR] 
[ERROR] -> [Help 1]
`

**Comment by denis-anisimov** [comment]
I cannot find any place in the code which prefer Node.js installed into home folder over the global one.

But I see the code which is introduced by @joheriks to run the tools: npm/pnpm, etc (they are just scripts) and the scripts from the home folder take precedence over the scripts installed globally. 

So the `node`  exec itself is searched globally first.
But then the scripts like `npm-cli.js`  and `npx-cli.js` are selected first from home dir and only if they are absent the global is chosen.
This is what I'm going to fix: not sure whether this is the exact cause of the issue.

**Comment by joheriks** [comment]
`baseDir` is project directory and `alternativeDirGetter` returns `~/.vaadin`:
https://github.com/vaadin/flow/blob/f1f8046b7e345d6dc08dd2ea13899eb7f36b505c/flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java#L394-L399
So the first found `node` executable inside these will be used, and only if none found in project or home will it invoke `frontendToolsLocator.tryLocateTool` to return the global one.

**Comment by denis-anisimov** [comment]
Ah, indeed.
I missed that there is an obscure check `if (defaultLocation == null)` which always `false`.
True , global node is fallback in the end.

But that doesn't cancel the fact that introduced `getNpmCliToolExecutable` method first checks home folder for scripts and only if they are not found then it searches them globally.
So things are broken on many places.
