### ISSUE TITLE
The "connection lost" banner should be visible immediately when starting an app offline

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9874]
When starting the app offline, I want to see the "connection lost" banner immediately if my backend is not not started, so that when I am developing and I navigate to the app before starting the backend it is immediately obvious to me that the backend is not running and I need to start it.

**Steps to reproduce**:
1. create a new Vaadin 19 / Fusion project with [https://start.vaadin.com/?preset=fusion](https://start.vaadin.com/?preset=fusion)
   (or with Vaadin CLI: `npx @vaadin/cli init --fusion --pre offline-start`)
2. clean all caches and delete the Service Worker for localhost:8080
3. start the app with `mvn` and open it in the browser at http://localhost:8080
4. stop the server
5. refresh the page in the browser
6. see a page that looks broken and has no "connection lost" banner visible
![image](https://user-images.githubusercontent.com/22416150/105701811-8c6e7a80-5f13-11eb-9d70-c40c6f2431d3.png)

**DoD:**
The "connection lost" banner is immediately visible on the page that loads after following the steps 1-6 above.

**Comment by Artur-** [comment]
Is this only for dev mode? In production, I would want my offline app to "just work"

**Comment by platosha** [comment]
The service worker is responding the index page from cache here, after a failed attempt to fetch it from the server. So, because the service worker is already aware of using cache, the solution I’d suggest here is is to propagate this bit to the connection indicator’s initial state.
