### ISSUE TITLE
npm dependencies removed from Vaadin and never removed from package.json

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#9923]
### Description of the bug / feature
For instance in https://github.com/vaadin/flow/commit/be4d8728f82d47ec6cdf2a07d8d8ef8d5d9980a6#diff-9d304505c371577e41313b4fecaac15cc72806d2ca0803a42622fd2869f40a54, `awesome-typescript-loader` was removed.

I would assume that this means that a project `package.json` containing:
```
....
  "devDependencies": {
...
    "awesome-typescript-loader": "5.2.1",
...
  "vaadin": {
...
    "devDependencies": {
...
      "awesome-typescript-loader": "5.2.1",
```

would be updated so all references to `awesome-typescript-loader` are removed when starting the application with the new version.

### Minimal reproducible example
Take an existing Vaadin 18 project and upgrade to Flow 6 alpha 5

### Actual behavior
Nothing is done to `awesome-typescript-loader` in `package.json` and the unnecessary dependency is kept installed.

### Versions:
    - Vaadin / Flow version: 6 alpha 5

**Comment by Artur-** [comment]
In the start.vaadin.com project, there was extra
```
"awesome-typescript-loader": "5.2.1",
"raw-loader": "4.0.0",
"script-ext-html-webpack-plugin": "2.1.4",
"terser": "4.6.7",
"webpack-babel-multi-target-plugin": "2.3.3",
"@webcomponents/webcomponentsjs": "^2.2.10"
```
which is around 60MB node_modules when separately installed

**Comment by vlukashov** [comment]
duplicate of https://github.com/vaadin/flow/issues/9720?

**Comment by Artur-** [comment]
Yes
