### ISSUE TITLE
Flow 5.0 client build fails with Error: Uncaught TypeError: Cannot read property 'Flow' of undefined

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#9924]
```
 Error: Uncaught TypeError: Cannot read property 'Flow' of undefined
[01:03:33][Step 4/5]   @ webpack:/src/main/resources/META-INF/resources/frontend/Flow.ts?:254:21
```
https://bender.vaadin.com/viewLog.html?buildId=211575&buildTypeId=Flow_Flow50_Flow50Snapshot&tab=buildLog&_focus=22797

**Comment by haijian-vaadin** [comment]
The build turned green after [this commit](https://github.com/vaadin/flow/commit/3ca2635647230ae6390a3f7892fd6275a82bcc21), and it has been green for [5 consecutive runs](https://bender.vaadin.com/viewType.html?buildTypeId=Flow_Flow50_Flow50Snapshot), so I think we can close the ticket.
