### ISSUE TITLE
As a developer I want to be able to use longs in the model

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#993]
In many cases an entity bean contains an id field which is of type long or Long. I want to be able to use these in the model, like I would use int or double.

**Comment by mvysny** [comment]
Actually it seems that Flow *can* transfer `java.lang.Long`s: in Beverage Buddy the `Review.id` is of type `java.lang.Long`. However there is a weird behavior there: https://github.com/vaadin/flow/issues/4030

**Comment by Artur-** [comment]
The most common use for `long` is probably to send a timestamp, especially as `Date` or `LocalDateTime` and variants are not supported

**Comment by pleku** [comment]
>Actually it seems that Flow can transfer java.lang.Longs: in Beverage Buddy the Review.id is of type java.lang.Long

It is converting it to a string using `LongToStringEncoder`, so it not really transferring it as a `long`.

**Comment by Legioth** [comment]
> The most common use for `long` is probably to send a timestamp, especially as `Date` or `LocalDateTime` and variants are not supported

As a workaround, you can use `double` for anything that is a timestamp (53 bits of precision is more than enough) and an ISO 8601 `String` for anything that is a local date.

**Comment by samie** [comment]
This is not only applying to templates, but all cases where domain objects have them?

**Comment by Legioth** [comment]
Templates has so far been the only case where domain objects are sent to the client as-is. This is now changing with the RPC services for TS views.
