### ISSUE TITLE
Backport DataView API from master to 2.x

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#9953]
Along with DataView API changes, the support for page repositories should be also backported.
Changes on combo box side includes changes on both Java and web component side.
The backports are done in a backwards compatible manner for the 14-series, even though this limits the benefits from the new API slightly.

#### Acceptance Criteria:
- [ ] The DataView API changes on flow side are merged to 2.6 and released
- [ ] The changes on components side are merged and released (Grid, ComboBox, CheckboxGroup, RadioButtonGroup, Select, ListBox)
  - The component examples are backported and adopted to use the getter for the right data view type 
- [ ] Documentation changes backported https://vaadin.com/docs/v18/flow/binding-data/tutorial-flow-data-provider.html
- [ ] SVC has been updated accordingly as for V18 (master-details view and list view)
- [ ] Spring data related helpers and API is backported https://github.com/vaadin/spring/blob/master/vaadin-spring/src/main/java/com/vaadin/flow/spring/data/VaadinSpringDataHelpers.java
- [ ] Lets use the new APIs in Bakery - there should be no breaking changes when going from 14.5 to 14.6

Some practical implications:
- We cannot remove `HasItems` nor `HasDataProvider` or change the return type for the API described there
  - We can add a note to the method javadocs about the data view API
- We can add the `setItems` API replacing `setDataProvider` and deprecate the latter pointing to the new API

**Comment by pleku** [comment]
Based on internal discussions this backport is unlikely to happen.
