### ISSUE TITLE
grid._observer is undefined

### ISSUE THREAD

**Issue by realulim** [vaadin/flow#9957]
### Description of the bug / feature
When trying to set a grid as an ItemDetailsRenderer for my parent grid, a number of JavaScript error message appear on screen and in the console log there is a message stating:

There seems to be an error in the Vaadin Grid:
grid._observer is undefined
Please submit an issue to https://github.com/vaadin/vaadin-grid-flow/issues/new!

The above link doesn't work, so perhaps that could be fixed as well.
### Minimal reproducible example
```
parentGrid.setItemDetailsRenderer(new ComponentRenderer<>(bean -> {
    VerticalLayout div = new VerticalLayout();
    Grid<String> details = new Grid<>();
    details.setItems("Foobar");
    div.add(details);
    return div;
}));
```
### Expected behavior
The string "Foobar" should show as the details of every grid row.
### Actual behavior
There are a bunch of JavaScript error messages appearing on the screen and in the console log, all of a similar form like this:
`(TypeError) : $0.$connector.reset is not a function`

I am attaching the full log as a file and a screenshot.
### Versions:
    - Vaadin / Flow version: 14.4.5
    - Java version: 11.0.9.1
    - OS version: Fedora 33
    - Browser version (if applicable): Firefox 84.0, Chrome 87.0.4280.88
    - Application Server (if applicable): 
    - IDE (if applicable):
![screenshot](https://user-images.githubusercontent.com/17084846/106735725-e1497980-6614-11eb-99b8-fe83e306020b.png)
[log.txt](https://github.com/vaadin/flow/files/5917802/log.txt)

**Comment by realulim** [comment]
I just saw that yesterday a new version of Vaadin came out and with that version 14.4.7 everything works as expected.

**Comment by caalador** [comment]
Hi.

Thanks for the issue, as it seems that it works as it should with the latest version I'm closing this ticket.
If the issue comes back please open a new issue at that time.
