### ISSUE TITLE
Change CSS loader configuration

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#9970]
### Description of the bug / feature

We should change how CSS file imports are handled in TS files to make it more clear what is happening and to make importing view specific CSS to the document easier.

### Expected behavior
When importing a plain CSS file, it should be added to the document:
```
import './something.css`
```

When importing a CSS file ending in `.shadow.css`, it should be made available as a `CssResult` which can be used with the `LitElement` `static styles`:
```
import style from './something.shadow.css`
```

### Actual behavior
RIght now it works like
```
import './something.css`
```
is a no-op
```
import styles from './something.css`
```
works as `.shadow.css` described above.

To just load a CSS file into the document you need something like
```
import '!style-loader!css-loader!./something.css';
```

### Versions:
    - Vaadin / Flow version: 19

**Comment by platosha** [comment]
Implementing as described means a breaking change for all existing TypeScript views, that already import css for their shadow roots.

Alternatively, we considered a less breaking option: keep bare `import styles from 'something.css';` working as before, and introduce a filename suffix convention for the document-level styles, for example: `import 'something.global.css';`. However, contrary to this idea, simple document-level style imports are preferred, as in future we want to not use shadow DOM for regular views.

To make the breaking change smoother, as a first step here, we could deprecate the bare css imports (without `.shadow.` filename suffix) for shadow roots first. Ideas suggested for implementing deprecation:

- The TypeScript definition in `types.d.ts` could have a `/** @deprecated */` JSdoc tag for the exported `CSSResult` instances. This would provide IDE feedback, marking all the usages of `CSSResult` imported from bare `.css` files.
- We could also log a deprecation warning using a custom webpack loader for any bare `.css` imports. It should be noted, that webpack loaders cannot distinguish between whether the import is used for the exports (`CSSesult` for shadow roots) for the side-effects (document styles).

**Comment by Haprog** [comment]
Here's a workaround snippet for `webpack.config.js` to start using the proposed filename suffix solution (`.css` and `.shadow.css`) in an existing project already:

```js
...
const cssLoaders = flowDefaults.module.rules.find(r => r.test && r.test.toString() == '/\\.css$/i');
if (cssLoaders && cssLoaders.use[0].loader === 'lit-css-loader') {
  cssLoaders.test = /\.shadow\.css$/i;
  const docCssLoader = {
    test: /\.css$/i,
    exclude: /\.shadow\.css$/i,
    use: [
      {
        loader: 'style-loader'
      },
      cssLoaders.use.find(l => l.loader === 'css-loader'),
      cssLoaders.use.find(l => l.loader === '@vaadin/theme-loader')
    ]
  };
  flowDefaults.module.rules.push(docCssLoader);
}

// Add the above before this line
module.exports = merge(flowDefaults,
...
```

This modifies the default CSS loader to work only on `*.shadow.css` and adds another CSS loader for other `*.css` files.

Or if you want to keep the current default as is and add a loader for `*.global.css` you can use this instead:

```js
...
const mainCssLoader = flowDefaults.module.rules.find(r => r.test && r.test.toString() == '/\\.css$/i');
const globalCssLoader = flowDefaults.module.rules.find(r => r.test && r.test.toString() == '/\\.global\\.css$/i');
if (mainCssLoader && !globalCssLoader) {
  mainCssLoader.exclude = /\.global\.css$/i;
  flowDefaults.module.rules.push({
    test: /\.global\.css$/i,
    use: [
      {
        loader: 'style-loader'
      },
      mainCssLoader.use.find(l => l.loader === 'css-loader'),
      mainCssLoader.use.find(l => l.loader === '@vaadin/theme-loader')
    ]
  });
}

// Add the above before this line
module.exports = merge(flowDefaults,
...
```

**Comment by Haprog** [comment]
Or if you'd want to use a resource query style import like `import './foo.css?global';` instead of `import './foo.shadow.css` (not requiring renaming of files) that's possible with something like this:

```js
...
const cssLoaders = flowDefaults.module.rules.find(r => r.test && r.test.toString() == '/\\.css$/i');
if (cssLoaders) {
  const origUse = cssLoaders.use;
  cssLoaders.oneOf = [
    {
      resourceQuery: /global/,
      use: [
        {
          loader: 'style-loader'
        },
        cssLoaders.use.find(l => l.loader === 'css-loader'),
        cssLoaders.use.find(l => l.loader === '@vaadin/theme-loader')
      ]
    },
    {
      use: origUse
    }
  ];
  delete cssLoaders.use;
}

// Add the above before this line
module.exports = merge(flowDefaults,
...
```

**Comment by Haprog** [comment]
To close the issue I'd suggest that we actually add a new loader for `.global.css` so people can start using that for easy document level style importing and deprecate the `CssResult` usage from `.css` import (if possible and if it's not a `.shadow.css`). Current default for other `.css` would still be as is otherwise.

**In a future version** we can switch the default by making only `.shadow.css` loaded as a `CssResult` and all other `.css` imported into document (`.global.css` and `.shadow.css` would still keep working but at this point the user can simplify and remove the `.global` part from the filename if they like). We can remove the separate loader config for `.global.css`. No need to deprecate `.global.css` as it would still work but it would be handled by the default `*.css` loader but we can stop using the extra `global` word in possible docs and examples.

Would this make sense?

**Comment by Haprog** [comment]
I tested that the planned deprecation works at least in VS Code if I have this in `types.d.ts`:

```ts
declare module '*.shadow.css' {
  import { CSSResult } from 'lit-element';
  const content: CSSResult;
  export default content;
}

declare module '*.css' {
  import { CSSResult } from 'lit-element';
  /** @deprecated */
  const content: CSSResult;
  export default content;
}
```

And ordering seems to matter so they need to be in this order. Otherwise the `*.css` option catches both cases. I'm not sure if this is specced somewhere though (so it uses the first match).
