### ISSUE TITLE
Clarify idempotence of Registrations in JavaDoc

### ISSUE THREAD

**Issue by mperktold** [vaadin/flow#9978]
Since #8506 has been fixed, a `Registration` is supposed to be idempotent (or [idempotent-ish](https://github.com/vaadin/flow/issues/8466#issuecomment-636516695) at least), i.e. calling `remove()` multiple times has the same effect as calling it once.

However, this is not mentioned explicitely in the documentation:

https://github.com/vaadin/flow/blob/c009afc5c24d8a3d6abc14f6f5cd3faea80c1932/flow-server/src/main/java/com/vaadin/flow/shared/Registration.java#L26-L37

My interpretation of the current JavaDoc would be exactly the idempotent-ish behavior described by @Legioth, but I think it would be better to be more explicit about it to provide clear guidelines how on to use or implement `Registration`s.

For example, one may wonder if a `Registration` field should be nulled out after calling `remove`, or whether a custom callback must be wrapped with `Registration.once` or not.

**Comment by Legioth** [comment]
Could be mentioned that nulling a `Registration` field might be beneficial to allow memory to be released even if would be safe to call `remove()` again.

**Comment by mperktold** [comment]
True. But It's a difference whether it's just beneficial for memory footprint reasons or crucial for program correctness.

Then again, you could always say "do null them out and your good no matter what".
