### ISSUE TITLE
Designer support for custom theme feature in flow

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9982]
The feature should work for Flow projects with v19+ or v14.6+ (14-minors). It needs to be able show the used theme in the designer preview.

**Comment by miguelatvaadin** [comment]
Related issues at the [designer project:](https://github.com/vaadin/designer-internal)

- https://github.com/vaadin/designer-internal/issues/1817
- https://github.com/vaadin/designer-internal/issues/1818
- https://github.com/vaadin/designer-internal/issues/1819
