### ISSUE TITLE
Custom theme feature backporting from master to 2.6

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9983]
- [x] Backport the custom theme feature in a backwards compatible (but forward incompatible) way, by not changing the theme annotation value - instead we add a new parameter to it:
```java
@Theme(themeFolder="foobar")
``` 
this means that we make the default `value` be `Lumo.class`.

What this implies is that:
```java
 @Theme(value=Lumo.class, themeFolder="foobar") // this would be the same as the default

// the following will need throw explaining that the custom theme folder only works with lumo theme
@Theme(value=SomeThingElseThanLumoOrExtendingLumo.class, themeFolder="foobar")
@Theme(value=Material.class, themeFolder="foobar")

// the following will work, given Savu extends Lumo
@Theme(value=Savu.class, themeFolder="foobar")

// because we make Lumo.class the default value, it will be possible to just add the annotation and that should fail because it is an user error
@Theme // this should throw, asking for specifying the custom theme folder
```

- [x] If someone tries using `@Theme(themeFolder="foobar")` when in compatibility mode, we should throw an error noting that custom themes don't' t work in compatibility mode
- [x] Backport the documentation, and note there that:
  - This feature only works for npm-mode, NOT in compatibility mode
  - This feature is available since 14.6 and 19
  - For version 19+ the theme annotation is changed so that the custom folder is the value parameter
- [ ] The SVC templates should be updated to use this feature for v14.
- [x] The theme demo app should get another branch with v14.6 in use
- [x] update [the project used for PiT](https://gitlab.vaadin.com/mgrankvi/appthemedx/-/tree/master) to use 14.6

If there are things that are only applicable for fusion projects, like maybe #9842, those don't have to backported to 14.
Adding the custom theme feature should not regress the frontend build time for v14. The plugins should not be applied when the custom theme folder is not in use.

**Comment by caalador** [comment]
Having an empty `Theme` annotation will work the same way as not having a `Theme` annotation in the application and lead to usage of the default theme if it's available on the classpath

**Comment by pleku** [comment]
Another thing to TODO, update [the project used for PiT](https://gitlab.vaadin.com/mgrankvi/appthemedx/-/tree/master) to use 14.6

**Comment by caalador** [comment]
Created branch: https://gitlab.vaadin.com/mgrankvi/appthemedx/-/tree/14.6/
Still needs the AppShellConfig removed and theme annotation changed to work with 14 branch.

**Comment by caalador** [comment]
Note: #9613 adds css loading order tests, and for some reason they load differently under V14.
This will need to be investigated and/or documented after we have all the features in.
- [ ] Investigate and fix loading order.
