### ISSUE TITLE
Eclipse Code Formatter plugin for Intellij Idea seems to 

### ISSUE THREAD

**Issue by miguelatvaadin** [vaadin/flow#9984]
### Description of the bug / feature
This issue refers 2 issues related to Eclipse Code Formatter for Intellij Idea.

#### Issue nr 1
Is not reordering the imports as stated at the Vaadin Flow contibuting guide (https://github.com/vaadin/flow/blob/master/CONTRIBUTING.md). E.g.:

```java
import javax.*
import java.*
<blank line>
import all other imports
<blank line>
import com.google.gwt.*
import com.vaadin.*
<blank line>
import elemental.*
import static all other imports
```

#### Issue nr 2
Is not line-wrapping . According to the contributing guid line length should be 80 characters.

#### Issue nr 1
Just edit a java file and add the folloging imports:

```java
import static java.lang.Math.sqrt;

import com.vaadin.flow.component.Text;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;
```

#### Issue nr 2
Just edit a java file and add the folloging lines:

```java
        l.stream().filter(s -> s.isEmpty()).sorted((a, b) -> a.compareTo(b)).map(s -> s.toLowerCase(Locale.ROOT)).collect(Collectors.joining());

        // dwe duh weduh weud weuidh uwiedh wuiedh wiuedh wuihed iuwehd uiwe dwuied hiuwehd wuieh duiwehdwuehd weuid wiued we d
```

#### Issue nr 1
Imports should be reordered as: 

```java
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;

import com.vaadin.flow.component.Text;

import static java.lang.Math.sqrt;
```
#### Issue nr 2
Lines should be wrapped as:
```java
        l.stream().filter(s -> s.isEmpty()).sorted((a, b) -> a.compareTo(b)).
                map(s -> s.toLowerCase(Locale.ROOT)).
                collect(Collectors.joining());

        // dwe duh weduh weud weuidh uwiedh wuiedh wiuedh wuihed iuwehd uiwe 
        // dwuied hiuwehd wuieh duiwehdwuehd weuid wiued we d
```

### Actual behavior
Imports are not reordered neither lines are wrapped.

### Versions:
- Intellij Idea 2020.3
- Eclipse code formatter plugin 20.7.201.6668.0-Eclipse_2020-06-JavaOnly

**Comment by miguelatvaadin** [comment]
According to retro meeting, 2 actions were suggested:

- find the version of Eclipse formatter / configuration that works 
- use Maven plugin for formatting (take a look on CE example), and add a maven goal to run before push

**Comment by knoobie** [comment]
I had a similar problem - I used `mvn formatter:format` in the end. It worked, but be careful it formats the whole project. Resulting in hundreds of changed files for me.

**Comment by caalador** [comment]
Closing issue as all new code should be formatted with `mvn formatter:format` to have the code base always the same.
