### ISSUE TITLE
Second loading indicator when using nested routers?

### ISSUE THREAD

**Issue by oliveryasuna** [vaadin/flow#9992]
### Description of the bug / feature
Please see an example project attached. Try clicking on the tabs. You will see a loading indicator quickly appear and disappear. Now try ending the server and clicking on a tab. You will still see that quick loading indicator, followed by a longer one.
### Minimal reproducible example
https://mega.nz/file/tIZwGLba#pV4fJBwpIoGdEZdYFYIumtDIwaUlUyj-YhG1AynHBqI
### Expected behavior
One loading indicator.
### Actual behavior
There are two loading indicators.
### Versions:
    - Vaadin / Flow version:
    - Java version: 11.0.9
    - OS version: Windows 10 Enterprise 20H2 build 19042.746
    - Browser version (if applicable): Brave 1.19.92 (Chrominium 88.0.4324.152)
    - Application Server (if applicable): Spring
    - IDE (if applicable): n/a

**Comment by pleku** [comment]
I could not reproduce this with 19.0.2. After killing the server, there is one loading indicator which turns into the connection lost indicator which has been revised in v19.
