### ISSUE TITLE
AfterNavigationEvent should give access to RouteParameters as well

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#9993]
There's `BeforeEvent.getRouteParameters()` but there is no such `AfterNavigationEvent.getRouteParameters()`.
### Versions:
    - Vaadin / Flow version: 14.5.0.alpha3

**Comment by Legioth** [comment]
Could you also describe a use case where this information would be useful?

**Comment by pleku** [comment]
Did you have a specific case in mind where those would be needed?

Looking at the code, it should be fairly trivial to include the parameters into https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java#L238 as the parameters are available there. But creating those in https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java#L160 requires some effort or code duplication to create the parameters.

**Comment by mvysny** [comment]
> Did you have a specific case in mind where those would be needed?

Nothing specific in mind; it's only a personal preference of listening to `AfterNavigationEvent` and init'ing the view there: since `AfterNavigationEvent`s are final and can not be redirected, the view init code's work won't go into waste. Maybe it is foolish.

I was just curious why AfterNavigationEvent lacks stuff which BeforeEvent contains.

**Comment by jcgueriaud1** [comment]
I got the same "problem". In my Vaadin application (done in Vaadin 14.x pre 14.5), I'm using AfterNavigation to highlight the menu like it's explained in the documentation:
https://vaadin.com/docs/v14/flow/routing/tutorial-routing-lifecycle/#afternavigationevent
I can still using the getLocation or probably highlight the menu in BeforeEnter.

From the documentation:
> This event is typically used to update various parts of the UI after the actual navigation is complete. Examples include adjusting the content of a breadcrumb component and visually marking the active menu item as active.

The breadcrumb could need the parameter like: Home>Books>Edit Book 3
